### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by CalvinRodo** [wet-boew/wet-boew#1077]
I think there needs to be a focus on improving the documentation. 

I use it all the time and I still find myself having no idea where anything is without having to do some serious digging.

It's not very usable.

**Comment by hsrudnicki** [comment]
@laurawesley and others: are you ready to close this issue ?

**Comment by laurawesley** [comment]
yes

**Comment by pjackson28** [comment]
Closing since the documentation and WET website have changed significantly as a result of the work that was done. A new issue should be created if any further issues need to be addressed.
