### ISSUE TITLE
JQ Pagination plugin

### ISSUE THREAD

**Issue by num3thod** [wet-boew/wet-boew#1789]
We have an big interest in incorporating a pagination feature into WET. With ability to get page content through AJAX or directly from on-page divs. If we propose a solution and initiate a pull request this week, what version of WET would this likely appear in? What are the other implications? Keep in mind this would be first for us.

examples:
http://flaviusmatis.github.com/simplePagination.js/
http://archive.plugins.jquery.com/project/pagination
http://beneverard.github.com/jqPagination/

Thanks,

MR
@lampk1972

**Comment by hsrudnicki** [comment]
@nschonni @pjackson28 @gandyp  @num3thod @LaurentGoderre : can be the issue closed or otherwise ?

**Comment by hsrudnicki** [comment]
Please update this issue's status whether this issue can be closed or otherwise?

**Comment by hsrudnicki** [comment]
Further to this issue opened in 2013, can be this issue closed or otherwise? Please update this issue's status as well, thx

**Comment by hsrudnicki** [comment]
Based on the above earlier discussion, this issue shall be fixed with its status in v4.1.0, in case of otherwise please update this issue's status as well, thx

**Comment by masterbee** [comment]
Closing the issue since the pagination branch was removed and no longer available for the issue discussion
