### ISSUE TITLE
Web Feed Widget - optional images support

### ISSUE THREAD

**Issue by michael-milette** [wet-boew/wet-boew#1889]
Is it possible to control whether images appear or not?

For example, I would like to:

- Not have images appear in Twitter feeds
- Have the images in my RSS feed to show up to the left of the text.

Best regards,

Michael Milette

**Comment by hsrudnicki** [comment]
@michael-milette @thomasgohard @pjackson28 @LaurentGoderre : can be this issue closed or otherwise ?

**Comment by pjackson28** [comment]
Yes it should be closed as we don't have any control over the Twitter feed and the RSS feed can be styled with CSS. In addition the issue has been inactive for quite a while.
