### ISSUE TITLE
using KSS for CSS documentation / Living Style Guide??

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew#1918]
Was looking for a website style guide builder and came across KSS

http://warpspire.com/posts/kss/

https://github.com/kneath/kss

http://warpspire.com/kss/

Github's own Style guide is built using KSS:
https://github.com/styleguide/

Thoughts on using it to develop WETs Style Guides?

@pjackson28 @nschonni @LaurentGoderre @cfarquharson

**Comment by hsrudnicki** [comment]
So, can be this issue closed ?

**Comment by laurawesley** [comment]
Yes
