### ISSUE TITLE
Sign-in / Sign-out link location and colour

### ISSUE THREAD

**Issue by cfarquharson** [wet-boew/wet-boew#1940]
Shouldn't the sign-in/sign-out be coded above the H1, not below it?  

It seems like a non-standard location for this kind of feature, especially since it's something normally found even higher up in the banner on most sites.

I have done quick mock ups below (coded right before the H1 with a float:right and also changed the margin-top to '0' .

Lastly, there are other button colors to choose from.  I think having the blue accent sign-in button placed below the blue accent search button is a bit confusing.  I have included demos with the default button color and a dark button color
![paul-signin](https://f.cloud.github.com/assets/2319199/376550/2c308a24-a43f-11e2-8e0e-af4b20abee33.png)
![paul-signin3](https://f.cloud.github.com/assets/2319199/376552/30ae6206-a43f-11e2-804c-fdbc88f79794.png)
![paul-signin2](https://f.cloud.github.com/assets/2319199/376553/34832f38-a43f-11e2-901c-ccaebe063d75.png)

**Comment by hsrudnicki** [comment]
@cfarquharson @pjackson28 : can be this issue closed ?

**Comment by LaurentGoderre** [comment]
I believe this can be close, it appears to be for v3.1
