### ISSUE TITLE
Creating NuGet packages

### ISSUE THREAD

**Issue by nschonni** [wet-boew/wet-boew#2002]
Now that Maven packages have been added to the core, I wanted to bring up creating NuGet packages for .Net builds again.
This would involve added the nuget.exe and the nuspec files for the different packages http://docs.nuget.org/docs/creating-packages/creating-and-publishing-a-package
I was thinking of the following:
- WET-BOEW.Core: grids, pe-ap files
- WET-BOEW.GWCU-FEGC: GCWU theme with a dependency on the Core package
- Other theme packages

The .Net variant could then publish a package with any workarounds for their layout issues.

**Comment by hsrudnicki** [comment]
@pjackson28 @nschonni @LaurentGoderre : can be this issue closed or otherwise ?

**Comment by hsrudnicki** [comment]
Please update this issue's status whether this issue, which had been referenced with others 5802, 6977, can be closed or otherwise?

**Comment by hsrudnicki** [comment]
Please update this issue's status whether this issue can be closed or otherwise? [Note: this issue had been opened in 2013, and as well dependable on other issues]

**Comment by hsrudnicki** [comment]
Close this issue due to "Going Stale" or if otherwise,  please update this issue's status? Thank you

**Comment by hsrudnicki** [comment]
@nschonni @pjackson28 : Based on your last comments of August 2014, is this above still a backlog issue, marked to "collect dust" / never going to fix?  Either way, please update this issue's status, whether this issue can be closed or otherwise?  Thank you

**Comment by masterbee** [comment]
Closing since there is a push for better packaging in the experimental repo, where better segregation of theme and core will assist in this process
