### ISSUE TITLE
GCWU: Focus on search input box

### ISSUE THREAD

**Issue by rmc-ims** [wet-boew/wet-boew#2584]
Focus on seach box is hard to see.
It is definitely not as clearly indicated as for a standard form input box.

The light blue (#F0FCFF) is very close to white.
I would suggest using a more visible color and/or adding a border to make the focus more visible.

**Comment by hsrudnicki** [comment]
So, can we close this issue or otherwise ?

**Comment by hsrudnicki** [comment]
Please update this issue's status whether this issue created in 2013 can be closed or otherwise?

**Comment by hsrudnicki** [comment]
Further to your discussion started in 2013, can be this issue closed or otherwise?

**Comment by hsrudnicki** [comment]
Due to a lack of further discussion or status update(s), this issue has been labeled "Going Stale" and closed.
