### ISSUE TITLE
jQuery blockUI

### ISSUE THREAD

**Issue by rlambert27** [wet-boew/wet-boew#2689]
Hello,

I'd like to suggest adding jQuery blockUI into the WET package. It's being used across our department so when a user performs an action (e.g.: hits the submit button) the UI is blocked so no changes can be made while the screen is loading or performing calculations.

I've seen this used in other departments also so i'm not suggesting this be added as functionality so it's the same and consistent across all departments.

jQuery blockUI was released July 8th: 

http://malsup.com/jquery/block/
Code examples: http://malsup.com/jquery/block/#demos

**Comment by hsrudnicki** [comment]
Can be this issue closed ?

**Comment by hsrudnicki** [comment]
Please update this issue's status whether this issue can be closed or otherwise? [ Note that this issue had been opened in 2013, updated in 2014, and referenced with 6024 ]

**Comment by hsrudnicki** [comment]
Made "Going Stale" in order to close this issue of 2013, due to no status update(s), or if otherwise, please update this issue's status as well? Thx

**Comment by hsrudnicki** [comment]
Due to no further discussion/status updates, as well referencing this issue with the opened other (6024) , this issue can be closed as the full resolving shall be included in the referenced issue.
