### ISSUE TITLE
Geomap features are not selectable on map in mobile mode

### ISSUE THREAD

**Issue by jvanulde** [wet-boew/wet-boew#2743]
In iOS 6 map features are not selectable. @jolevesq please look into this.

**Comment by hsrudnicki** [comment]
@pjackson28 @jolevesq @jvanulde : can be this issue closed ?

**Comment by jvanulde** [comment]
@hsrudnicki this is still an issue.

**Comment by jvanulde** [comment]
@hsrudnicki we can close this now.
