### ISSUE TITLE
Responsive Graphs & Charts?

### ISSUE THREAD

**Issue by raubs** [wet-boew/wet-boew#2768]
Hi,

We're currently in the process of implementing a couple pie charts for our Transparency section, but we're finding that when we resize the page, the pie chart stays the same dimensions. I checked the examples in the WET documentation and it seems like that is how it is implemented. I'm assuming all of the charts and graphs are implemented in a similar way, thus not resizable. Are there plans to make this plugin responsive in the future? 

Also, in IE8, if the pie chart was placed in a grid column, it remains overlayed on top of the grid column (extending past the grid column) because it can't fit. In other, more modern browsers, when the screen is resized to "mobile" view, you never see the whole chart/graph because it flows off the page.

Anyway, just curious. It'd be a nice feature if possible. 
Our only other alternative right now is to go back to using an image, unfortunately.

**Comment by hsrudnicki** [comment]
@raubs @LaurentGoderre : Can be this issue closed or otherwise ?

**Comment by LaurentGoderre** [comment]
No, this is still an issue

**Comment by hsrudnicki** [comment]
Please update this issue's status whether this issue had been fixed and ready to be closed or otherwise?

**Comment by hsrudnicki** [comment]
Going stale or keeping this issue as opened as last commented by @LaurentGoderre ?

**Comment by hsrudnicki** [comment]
Due to no further status updates/discussion, this issue has been labeled as "Going Stale" and closed as well.
