### ISSUE TITLE
Calendar component - new use case

### ISSUE THREAD

**Issue by MaryBethBaker** [wet-boew/wet-boew#2796]
Issue: I'm working with Stephane and @neoinsight on a birth date calendar picker that enables users to pick the year of their birthday without having to scroll backwards or have to guess about the go to functionality.

Use When

This feature can be used in the context of any page where users are asked to select a date in the past, such as a birth date.

//cc @berubs

**Comment by hsrudnicki** [comment]
@MaryBethBaker @nschonni @pjackson28 : can be this issue closed or otherwise ?

**Comment by pjackson28** [comment]
There are other issues that are dealing with using the HTML5 date picker + polyfill so this issue can be closed as it is just an example date picker use case.

**Comment by MaryBethBaker** [comment]
Any chance you can remove me from future WET-BOEW tickets? I'm not working on the project.

Mary Beth

**Comment by pjackson28** [comment]
@MaryBethBaker You'll likely have to do it yourself but maybe either the unsubscribe button on the right or the unwatch button at the top at the top will help.
