### ISSUE TITLE
WxT training working group needed

### ISSUE THREAD

**Issue by laurawesley** [wet-boew/wet-boew#2812]
As many people noted before and during CodeFest (ref #2811 among others), there are lots of training needs within the WxT community.

I would like to propose we start a training working group. 

Anyone want to work on that?

**Comment by hsrudnicki** [comment]
@laurawesley @thomasgohard : can be this issue closed ?

**Comment by LaurentGoderre** [comment]
We can close for now

**Comment by splashE** [comment]
Yes pls.
 Elena
 


     On Friday, June 5, 2015 4:14 PM, Laurent Goderre <notifications@github.com> wrote:
   

 Closed #2812.—
