### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by CalvinRodo** [wet-boew/wet-boew#2816]
It might be worthwhile to look into some sort of automatic documentation generation tools to help build some good docs for implementers and contributors. 

Issues like #2814 would probably happen less if we had better documentation for developers.

/cc @masterbee @LaurentGoderre @patheard @nschonni @duboisp @pjackson28 

What do you think of introducing something like one of these tools for 4.0?
http://www.lsauer.com/2013/05/javascript-documentation-generator.html#.UgqGYH_hd4Y

**Comment by hsrudnicki** [comment]
So, are you ready to close this issue or otherwise ?

**Comment by hsrudnicki** [comment]
When possible, please update this issue's status whether this issue, opened in 2013 and updated in 2014, can be closed or otherwise?

**Comment by hsrudnicki** [comment]
Due to a lack of further response(s), this issue has been labeled as "Going Stale" and closed
