### ISSUE TITLE
Dublin Core / HTML Data Metadata discussion follow-up

### ISSUE THREAD

**Issue by krisaston** [wet-boew/wet-boew#2822]
The DC / HTML data breakout session at CodeFest was only the beginning of what is clearly a much needed larger discussion. Many thanks to everyone who came out and shared their feedback and ideas. I took many notes (and when I can figure out how to link them to this issue, I will!)

This issue is a place where the discussion can continue, questions, pros/cons, ideas, evidence can be discussed, to contribute building the future direction of web metadata for the GC. Your input is needed on this topic!

Related issues: #2541 #1305

**Comment by hsrudnicki** [comment]
@LaurentGoderre @chrismajewski @krisaston : Again, can be this issue closed ?

**Comment by chrismajewski** [comment]
It could be closed then, that was a comment.

It can be closed now.
