### ISSUE TITLE
jQuery inline picklist

### ISSUE THREAD

**Issue by iku19** [wet-boew/wet-boew#2929]
I want to implement a function in one of page, and try to use inline picklist. That is like a pick list in left and arrow bar in the middle and another empty area will show items after you pick any items from left side.

Is this feature in the WET already? if not, I have to use some third party code, and hope not to break your js from WET.

**Comment by hsrudnicki** [comment]
Can be this issue closed ?

**Comment by hsrudnicki** [comment]
Please update this issue's status whether this issue, opened in 2013 and last commented in 2014, can be closed or otherwise?

**Comment by hsrudnicki** [comment]
Due to no further discussion or status updates, this issue has been labelled as "Going Stale" and closed.
