### ISSUE TITLE
Printing charts and graphs

### ISSUE THREAD

**Issue by gdanova** [wet-boew/wet-boew#2939]
When using this plugin with IE8, printing does not print the chart data (empty graphs), and Print Preview overlays the chart image over text.

Sample page: http://www.cra-arc.gc.ca/gncy/fnncl/r130828-eng.html

**Comment by hsrudnicki** [comment]
@duboisp @pjackson28 : can be this issue closed ?

**Comment by gdanova** [comment]
OK by me to close.
