### ISSUE TITLE
Pie Charts - Decimal Issue

### ISSUE THREAD

**Issue by agagnon** [wet-boew/wet-boew#3267]
http://wet-boew.github.io/wet-boew/demos/charts/pie-en.html

If you go in the Decimal Precision section, charts will only work properly with a period(.) as the decimal separator, not with a comma(,) (as used in French). 

Eng: 12.3
Fra: 12,3

With comma as decimal separator, the chart will show, but won't consider decimals in calculation, meaning the data in the chart won't reflect exactly those in the table.

**Comment by esand** [comment]
This bug should be re-opened. The regular expression (/(\d{1,3}(?:(?: |,)\d{3})*)(?:(?:.|,)(\d{1,2}))?$/) on line 206 of charts.js is a disaster, and the entire "getcellvalue" parsing function completely botches numeric processing.

If you take the exact function and try manually parsing numbers in console, you'll soon see how bad it is. Try parsing a number prefixed with a zero like 0385, the result is 3.5. Try parsing 2000, the result is 20. The only way this function works properly is if every value is a float (contains a decmial point).
