### ISSUE TITLE
Pie Charts - Legend overlap

### ISSUE THREAD

**Issue by agagnon** [wet-boew/wet-boew#3268]
http://wet-boew.github.io/wet-boew/demos/charts/pie-en.html

In some example, legend overlap the data table.
![chart-overlap](https://f.cloud.github.com/assets/1794026/1353072/45ae825a-3740-11e3-9132-77d56c2e383b.jpg)

**Comment by duboisp** [comment]
This is not an issue anymore, as the default rendering location for the legend is at the bottom of the pie charts

**Comment by LaurentGoderre** [comment]
@agagnon can you confirm that this is no longer an issue and that we can close?

**Comment by agagnon** [comment]
I suppose this isn't a problem anymore in v4.0, but it's still is in v3.1, but since v3.1 is not supported anymore, I guess we'll just have to deal with it.

v3.1 (Labeling threshold example) : http://wet-boew.github.io/wet-boew-legacy/v3.1/demos/charts/pie-en.html
