### ISSUE TITLE
Charts with long tables

### ISSUE THREAD

**Issue by duprasf** [wet-boew/wet-boew#3341]
Bonjour,
Today we tried to make a chart for a very long table, the problem is that the chart width is the same as the table. We would like to have the graph in a right side column (span-3) we don't mind if the table goes beyond the width of the page when it is expended, but it does not make any sense for the charts to be off screen. 
![pie-chart](https://f.cloud.github.com/assets/4225321/1411289/d878f8ac-3db4-11e3-8567-f2b1a043be32.jpg)

I tried to flip the table, but the pie chart only accept data in rows for the pie chart. Anyone had problems with this? How did you fix it?

**Comment by duboisp** [comment]
@duprasf are you still experiencing that issue in WET 4?

**Comment by duprasf** [comment]
We did not move to WET 4 yet. This can be closed. I don't think we have that chart on the site anymore but will look at other chart when we move to WET 4.
