### ISSUE TITLE
data ajax plugin demo code example

### ISSUE THREAD

**Issue by pliz22** [wet-boew/wet-boew#3371]
I like the idea of this, but I can't find a good example of any kind of action/ event driven uses for this.
The demo page just shows static content being inserted into more static content.

I would love if the demo page added some kind of... I don't know.
$.find("id").on("click"...).something.data-ajax-replace(filename)?

**Comment by hsrudnicki** [comment]
Can be this issue closed ?

**Comment by hsrudnicki** [comment]
Please update this issue's status [Note that this issue had been opened in 2013 and last commented in 2014], thx
