### ISSUE TITLE
How to handle large tables on mobile?

### ISSUE THREAD

**Issue by pjackson28** [wet-boew/wet-boew#3402]
In v3.1 we had both the column selector and table linearization options available from jQuery Mobile to help deal with large tables. What should be done in v4.0? We've already seen some issues with large tables on mobile devices where it overflows the viewport and messes with fitting content withing the viewport.

Should we be recreating the column selector and table linearization approaches? Are there good 3rd party solutions available? I know DataTables has the ability to hide columns but is that enough?

**Comment by hsrudnicki** [comment]
@pjackson28 @nschonni : Can be this issue closed or otherwise ?

**Comment by hsrudnicki** [comment]
Please update this issue's status whether it can be closed as its referenced issue (3078) or otherwise?
[Note that this issue had been opened in 2013 and last commented in 2014]

**Comment by hsrudnicki** [comment]
Due to no further discussion and updates, this issue's status has been labeled as "Going Stale" and closed

**Comment by pjackson28** [comment]
I thought @duboisp was still working on a solution for this. @duboisp Is that still the case?

**Comment by pjackson28** [comment]
Also including @thomasgohard since he was also involved previously.

**Comment by hsrudnicki** [comment]
@duboisp @thomasgohard and others :Again,  Label this issue as "Going Stale" and closed this or otherwise?

**Comment by hsrudnicki** [comment]
@duboisp @thomasgohard : Does this issue need to be opened or can be closed? Either way, please update this issue's status, thank you

**Comment by hsrudnicki** [comment]
Is this still a backlog issue/an issue to be resolved?  Either way, please update this issue's status, whether this issue can be closed or if otherwise?

**Comment by hsrudnicki** [comment]
Does this remain in the 4.0 Backlog or if otherwise? Please update the status of this, as well the referenced issues, thanks

**Comment by masterbee** [comment]
closed since a duplicate of https://github.com/wet-boew/wet-boew-styleguide/issues/274
