### ISSUE TITLE
Standard on Web Usability - Archive Page Notice

### ISSUE THREAD

**Issue by irwink** [wet-boew/wet-boew#3444]
PWGSC's Translation Bureau feels that the wording for the French notice for Archived web pages used in the Standard on Usability is not correct French.  The following wording is taken from the working examples page from github (http://wet-boew.github.io/wet-boew/demos/archived/archived-fr.html):

L’information dont il est indiqué qu’elle est archivée est fournie à des fins de référence, de recherche ou de tenue de documents. Elle n’est pas assujettie aux normes Web du gouvernement du Canada et elle n’a pas été modifiée ou mise à jour depuis son archivage. Pour obtenir cette information dans un autre format, veuillez communiquer avec nous. 

Translation Bureau propose the following wording:

L’information dite archivée est fournie à des fins de référence, de recherche ou de tenue de documents. Elle n’est pas assujettie aux normes Web du gouvernement du Canada et n’a pas été modifiée ni mise à jour depuis son archivage. Pour obtenir cette information dans un autre format, Contactez-nous.

The text "Contactez-nous" is a link to a contact us page.

Is the above wording acceptable and would pages that use this wording be regarded as meeting the requirements for being Archived on the Web ?

**Comment by hsrudnicki** [comment]
Can be this issue closed or otherwise ?

**Comment by hsrudnicki** [comment]
When possible, please update this issue's status as well, thx

**Comment by hsrudnicki** [comment]
@thomasgohard and others: Make 'Stale' and close this issue or otherwise? Please update this issue's status asap

**Comment by hsrudnicki** [comment]
Made "Going Stale" and if no further status updates/discussion, then this issue can be closed or otherwise? Please update this issue's status, thx
