### ISSUE TITLE
Feeds: RTL issues

### ISSUE THREAD

**Issue by pjackson28** [wet-boew/wet-boew#3511]
Date brackets incorrect and date on wrong side in RTL mode (may not be fixable, but should look int square brackets)

![feedsrtl](https://f.cloud.github.com/assets/1326498/1506696/6024834c-4941-11e3-8ec4-5bebc6fd3571.jpg)

**Comment by LaurentGoderre** [comment]
BTW, where is this occurring @pjackson28 ?

**Comment by pjackson28** [comment]
Not really an issue now that square brackets are no longer used around the timestamp.

**Comment by pjackson28** [comment]
Correction, it happens on the Facebook feed which still uses square brackets for some reason.

**Comment by LaurentGoderre** [comment]
This will be fixed in v4.0.11
