### ISSUE TITLE
Box shadown for menu is misaligned

### ISSUE THREAD

**Issue by thomasgohard** [wet-boew/wet-boew#3629]
The box shadow for the menu is misaligned, so that there's a gap at the top of the drop-down:
![boxshadowmissalignment](https://f.cloud.github.com/assets/1810242/1565164/1052bd9e-507a-11e3-898c-9046787d59d3.png)

**Comment by stephenbe** [comment]
Is this still an issue? I don't see a box shadow on my end

**Comment by thomasgohard** [comment]
Looks like it's gone. Closing.
