### ISSUE TITLE
datatables filter

### ISSUE THREAD

**Issue by pliz22** [wet-boew/wet-boew#3674]
hi everyone,

any ideas if the filter box size can be preloaded?  on slower pcs, especially with ie8, some clients have complained of clicking the wrong links because after rendering the filter box, the entire table is moved down about 40px.

i've kind of fixed what i need by doing `#gv_filter{margin-top:-40px;}` but this, depending on the page, moves the filter up into the title.  it depends if there are controls that appear before the table.  if so, it doesn't look too bad.  if there aren't then the filter is displayed on top of the title, or the menu bar, etc.

so the preload idea is to somehow set this size before rendering it.  maybe i can do this on the server side, or add some CSS to the basic table, like `table:before{content:"&nbsp;";min-height:40px;}`.

any ideas or things i could try out?

thanks

**Comment by hsrudnicki** [comment]
@pliz22 @LaurentGoderre : Can be this issue closed or otherwise ?

**Comment by pliz22** [comment]
Yes 

Sent from Yahoo Mail on Android
