### ISSUE TITLE
Consolidate grunt-contrib-imagemin and grunt-imagine

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/wet-boew#3794]
This lower priority

**Comment by hsrudnicki** [comment]
Can be this issue closed ?

**Comment by hsrudnicki** [comment]
Please update this issue's status [Note that this issue had been opened in 2013 and last commented in 2014 milestones], thx

**Comment by hsrudnicki** [comment]
Due to no further discussion and/or updates, this issue's status has been labeled "Going Stale" and can be closed.
