### ISSUE TITLE
Using Local Files for Chart and Table functions

### ISSUE THREAD

**Issue by samperd** [wet-boew/wet-boew#3795]
Hey Folks,

I have played around with charts and tables using HTML
  
Now I would like to remove the data from the HTML file and place it in a seprate file such as a JSON or XML file.

Later, it would be great to call a service, but first thing is first.

How might I achieve this?

**Comment by hsrudnicki** [comment]
@samperd  @LaurentGoderre : Can we close this issue ?

**Comment by samperd** [comment]
Closing issue due to above request. Perhaps some day someone can implement the original feature request.
