### ISSUE TITLE
Need to create dropdown buttons like in Bootstrap

### ISSUE THREAD

**Issue by cfarquharson** [wet-boew/wet-boew#3882]
Is someone going to create a WET version of the JS needed for but Bootstrap Button dropdowns? http://getbootstrap.com/components/#btn-dropdowns

as per @masterbee request in BCI folder

**Comment by hsrudnicki** [comment]
@thomasgohard @LaurentGoderre and others : Can be this issue closed ?

**Comment by charlesmorin** [comment]
Well, we did not hear much from TBS about that requirement. We have developed a workaround so we could use a similar approach when required. 

As stated in my comment from October 9th 2014, it may look useless for websites, but it is very useful for applications development.

**Comment by hsrudnicki** [comment]
@thomasgohard and others : Please update this issue's status [Note that this issue had been opened in 2013 and last commented in 2014 milestone(s) but no further discussion about that requirement], thank you

**Comment by hsrudnicki** [comment]
Due to no further discussion and/or updates, this issue's status has been labeled "Going Stale" and can be closed.
