### ISSUE TITLE
Support for using same-page hashlinks in the current page highlighting script

### ISSUE THREAD

**Issue by gmontgomery** [wet-boew/wet-boew#4042]
Hey can you add support for same page hashlinks page highlighting? Our client wants hash links in the left hand menu.

For example:
While at this page: meetings.cfm#part1
```html
<ul>
<li><a href="hearings.cfm">Hearings</a></li>
<li><a href="meetings.cfm">Meetings</a></li>
<li><a href="meetings.cfm#part1">Meetings Part 1</a></li>
<li><a href="meetings.cfm#part2">Meetings Part 2</a></li>
<li><a href="meetings.cfm#part3">Meetings Part 3</a></li>
<li><a href="studies.cfm">Studies</a></li>
</ul>
```
It will add the nav-current class to the link item [meetings.cfm#part3], even though that's not where we are in the site heirarchy.

Thanks.

**Comment by hsrudnicki** [comment]
@gmontgomery @pjackson28 @LaurentGoderre : Can be this issue closed or otherwise ?

**Comment by pjackson28** [comment]
Yes as nav-current highlighting is not intended to be used for same page links.
