### ISSUE TITLE
Responsive Image Maps?

### ISSUE THREAD

**Issue by ApplebyT** [wet-boew/wet-boew#4144]
I've run into a problem with image maps. I'm using an image with an attached image map in a grid structure. I have to give the image the "image-actual" class to match the poly data in the image-map. When the browser window is resized the text in the adjoining column overlaps the image until it reaches the right width to switch to mobile mode.
So I was wondering if there is a responsive image map solution in WET such as the attached link? (code is available MIT license on Git-Hub)
http://mattstow.com/experiment/responsive-image-maps/rwd-image-maps.html

**Comment by hsrudnicki** [comment]
Can be this issue closed or otherwise ?

**Comment by silentcanadian** [comment]
Hi, I'd like to keep this issue open if that's possible.  I'm currently using WET v.4 for one of our initiatives and recently I've been asked about the feasibility of adding an image map to the web page.  Is there anything within WET at the moment which would be used for this?

**Comment by hsrudnicki** [comment]
Please update this issue status whether this time the issue, opened in 2013, is ready to be closed or otherwise? Thanks

**Comment by silentcanadian** [comment]
Yes this can be closed.

**Comment by ApplebyT** [comment]
Sorry for not responding. Please go ahead and close as this has been visited elsewhere.
