### ISSUE TITLE
Printing Tables in IE9

### ISSUE THREAD

**Issue by raubs** [wet-boew/wet-boew#4225]
Hi,

We recently received word that one of our expense tables does not print. So, I checked it out on Firefox, Chrome, Safari, and IE8, and the table in question shows up fine when printed. However, in IE9, which most of our council has switched to, there are problems viewing the table; that said, IE9 Compatibility Mode does allow the table to be shown.

I checked out the code and it is pretty much identical to the "Right-Align" example on the WET demo site (http://wet-boew.github.io/wet-boew/demos/grids/grid-table-en.html#right). What I've come to realize, after commenting out my table and pasting in the example table, is that the length of the table is what is causing it to not print.

Our page is presented with a left navigation (span-2), an H1 at the top of the page, followed by 2x 4-5 line paragraphs (with h3 titles for each), followed by an H3, then a 13-15 line table at the bottom of the page. 

When we attempt to Print Preview, only the footer of the table is displayed. BUT, if I removed (or comment out) a few of the rows from the table, all of a sudden it displays in the print preview. I thought maybe it was a hidden character causing the problem, but I commented out different rows and it still gave me the same problem. I'm not really sure why only the footer is showing, but that's what happens...As I said, every other browser works fine, and IE8, and IE9 Compatibility mode works fine too.

I'm wondering if I should force the browser to switch to Compatibility mode in order for the table to show properly in Print mode. Has anyone else had this issue? Also, if you can suggest an alternative solution, that would be greatly appreciated!

**Comment by hsrudnicki** [comment]
@raubs @pjackson28 @nschonni @LaurentGoderre : Can be this issue closed or otherwise ?

**Comment by pjackson28** [comment]
Yes, since it was a v3.1 issue, which we don't support any more.
