### ISSUE TITLE
CRA web site:  Site menu accessibility issue involving the four tabs in the navigation bar

### ISSUE THREAD

**Issue by lonnycameron** [wet-boew/wet-boew#4287]
In Fall 2013 an external vendor (Sage Research) conducted a usability test. The main objective of this research was to get usability feedback from persons with disabilities on the WET designs for the home page and segment landing pages of the external CRA web site.  For Screen Reader users, three related accessibility issues users involving the “Site menu navigation bar” were identified as a result of this test.   In the English WET template provided by Treasury Board Secretariat (TBS), the HTML code references an object called the “Site menu” in the <nav role="navigation"> section.  All three issues are related to this section of the template.  All of the issues are so closely related, so a single issue was logged in github.  

Background info:

The current implementation of the CRA web site has four tabs defined in the navigation bar that map to the four CRA audience segments.  The four tabs/audience segments are:

1.	Individuals and families
2.	Businesses
3.	Charities and giving
4.	Representatives

These tabs make up a major organizational and navigational framework for the CRA web site.  For a screen reader, the four tabs are underneath the heading Site Menu, which is the third heading from the top of the page, just after Search.

Explanation of these issues:

Issue 1:  The term "Site menu" did not resonate with some users.

Most participants found this label to be unclear, and not to be a heading they would be likely to explore (i.e., have the screen reader read what is underneath the heading).  This issue was pervasive for users who liked to navigate by heading.  A more descriptive label would help draw attention to the content associated with this heading.

Issue 2:  "Skip to main content" takes the user after the Site menu.

The Skip to main content link at the top of the page takes the user to the first heading after the four tabs.  A couple of participants had navigation difficulties as a result of using this link because it skips over the four tabs.

Issue 3:  The 4 tabs are not links.

For a screen reader, the four tabs are underneath the heading Site Menu, which is the third heading from the top of the page, just after Search.  When JAWS reads clickable elements, it states the nature of the clickable object.  Most often these are “links”.  In the case of the four tabs, these are “menus.”  For example, when JAWS reads Individuals and families, what it says is, “Individuals and families menu”.  Because the four tabs are “menus” and not links, they do not appear if one uses the JAWS command to bring up a list of the links on a Web page.

**Comment by hsrudnicki** [comment]
Can be this issue closed or otherwise ?

**Comment by pjackson28** [comment]
Yes it can be closed as the issue becomes moot when the menu is standardized across the GC through Web Renewal.
