### ISSUE TITLE
tabbed interface - Carousel - more information 

### ISSUE THREAD

**Issue by sophiek4905** [wet-boew/wet-boew#4346]
I'm interested in tabbed interface - carousel plugin. 

I want to find out:

1. if the user interface can be expanded to include 
eg: speed controller, scrub bar, rocker loop button etc   

2. if more layers can be added on top of the images 

3. more documentation on this plugin

**Comment by hsrudnicki** [comment]
Can be this issue closed ?

**Comment by jvanulde** [comment]
@hsrudnicki this can be achieved with OpenLayers natively so technically it can be done with Geomap. My view is that this is a highly specialized requirement that would take some effort to build in. My recommendation would be to implement this using custom script on top of Geomap.

**Comment by hsrudnicki** [comment]
and what do you, @pjackson28 @LaurentGoderre, think in regards to this issue status ?

**Comment by LaurentGoderre** [comment]
@sophiek4905 does that work for you?

**Comment by sophiek4905** [comment]
Thank you for your help & suggestions.   We will certainly explore more on Geomap in the future.
