### ISSUE TITLE
Documentation Template for Tombstone Data

### ISSUE THREAD

**Issue by NicolasHorne** [wet-boew/wet-boew#4361]
To help documenting the components of the Toolkit, please fill out the template below with the relevant information. Add the completed template as a comment on this issue.

### Component name
* The name of the component.

### Purpose
* A brief description of the component. 

### Use when
* The instances when the use of the component is recommended or acceptable.

### Do not use when
* The instances when use of the component should be avoided or is discouraged.

### Working example
* A link to the working example of the component.

### HTML markup to enable the component in a Web page
* The base HTML markup to use to enable the component in a Web page.

### Configuration options
* The configuration options for the component.

### Source code
* A link to the folder containing the files for the component in the GitHub repository.

**Comment by hsrudnicki** [comment]
Are you ready to close this issue ?

**Comment by pjackson28** [comment]
Yes since the documentation has been built.
