### ISSUE TITLE
Analysing your Complex HTML Table

### ISSUE THREAD

**Issue by toddddot** [wet-boew/wet-boew#4377]
Hello.

When using the Complex HTML Table validator, all scope attributes are stripped out.

Why is this happening?

Todd.

**Comment by olegk1** [comment]
Hi Pierre: 
For some reason, "12 table techniques" link is not functional. Where can I have at the techniques you were referring to? 
Also re:using Table Validator. The validator didn't find any errors with my table but displayed it in "HTML Results" somewhat different from my original HTML code. Does it mean I have to use the code that validator displayed in order for the table to be considered accessible?

Thanks.

**Comment by hsrudnicki** [comment]
@LaurentGoderre @pjackson28 and others: Can be this issue closed or otherwise ?

**Comment by olegk1** [comment]
It is ok to close it, if you ask me. Thank you!
