### ISSUE TITLE
Geomap: Allow overlay to not populate a feature table

### ISSUE THREAD

**Issue by jelofson** [wet-boew/wet-boew#4404]
Since we can't use WMS as an overlay in Geomap like you can in Openlayers, we are having to use KML. As such, we have a very large kml file of close to 7000 polygons. It takes a lot of time and resources to render that layer, partly, I would think because it's generating a very large 7000 row table. It doesn't appear that I can turn the feature table off? I can turn off the layers, but that affects the other layers. I suppose there are WCAG implications to consider.

Maybe there should be an option for WMS as an overlay.

**Comment by jvanulde** [comment]
@jelofson we are working on adding WMS overlays. Currently we allow for setting transparency of the background image as well as the opacity of the portrayal on the map. We are hoping to get this into a PR soon once we have completed our testing. Screenshot:
![screen shot 2015-01-19 at 12 41 53 pm](https://cloud.githubusercontent.com/assets/2255248/5807551/47726914-9fd9-11e4-9082-89cbaab65bc2.png)

**Comment by LaurentGoderre** [comment]
@jvanulde do you think it will be ready for mid february?

**Comment by jvanulde** [comment]
Hope so @LaurentGoderre

**Comment by jvanulde** [comment]
@jelofson I wouldn't mind your input on how you think the legendGraphic should be brought in. I thought about parsing the GetCapabilities document to get the legendGraphicUrl but I don't that is practical on mobile - the capabilities documents (XML) can be quite large. For now I have allowed users to specify a legendGraphicUrl in the configuration. Will that work for your purposes? Screenshot of legend graphic:

![screen shot 2015-01-19 at 2 14 36 pm](https://cloud.githubusercontent.com/assets/2255248/5808775/0133b482-9fe6-11e4-9bfc-323865b4e112.png)

**Comment by jelofson** [comment]
@jvanulde First off, thanks for looking into WMS layers! This is great news and the screenshots look great. As for the legend, that is a good question. Using an image is fine with me, so long as it's accessible. In a map app I created, I used less dynamic legends. For example, in the legend column, I inserted a div with a table for the legend. Each div has an ID. When adding layers, one of the layer options, regardless of type, was the legend div id. Then, at some point, I run a function called buildLayerSwitcher to insert the checkboxes to toggle the layers etc. I also had to support cql queries for geoserver because we had to show data for a particular date. (see screenshot). The client also wanted the legends open all the time, but that could be changed. The first, second and fourth layers are wms. The other is vector based on dynamically generated kml.

![image](https://cloud.githubusercontent.com/assets/497112/5809057/80c4b9d4-9ff1-11e4-9529-1e50e6013124.png)

You can see the source here: 
http://cwfis.cfs.nrcan.gc.ca/interactive-map, or I can give you access via bitbucket where the git repo is. 

I know the WET stuff is more elegant, but for now, it's working. How will you deal with features?

**Comment by jvanulde** [comment]
Thanks @jelofson for the link. So we have now added support for cql_query, legend graphics (static or dynamic), and HTML legends that can be configured through the config file. Example:

    ...{
			title: "GeoMet (WMS)",
			caption: "This is a sample WMS service loaded by Geomap.",
			type: "wms",
			url: "http://geo.weather.gc.ca/geomet/?Lang=E",
			visible: false,
			version: "1.1.1",
			format: "image/png",
			layers: "GDPS.ETA_PR",
			transparent: true,
			options: { 
				opacity: 0.5,
				//legendGraphicUrl: "http://geo.weather.gc.ca/geomet/?Lang=E&LAYERS=GDPS.ETA_PR&VERSION=1.1.1&FORMAT=image%2Fpng&SERVICE=WMS&REQUEST=GetLegendGraphic&STYLE=PRECIPMM"
				legendHTML: "<small>Precipitation (mm)</small>" +
						"<ul class='list-unstyled'>" +
						"<li><span style='background-color:#800000;display:inline-block;height:20px;width:20px'/> <small>100.0</small></li>" +
						"<li><span style='background-color:#FF0000;display:inline-block;height:20px;width:20px'/> <small>50.0</small></li>" +
						"<li><span style='background-color:#FF4500;display:inline-block;height:20px;width:20px'/> <small>25.0</small></li>" +
						"<li><span style='background-color:#FFA500;display:inline-block;height:20px;width:20px'/> <small>20.0</small></li>" +
						"<li><span style='background-color:#FFD700;display:inline-block;height:20px;width:20px'/> <small>15.0</small></li>" +
						"<li><span style='background-color:#E5E500;display:inline-block;height:20px;width:20px'/> <small>10.0</small></li>" +
						"<li><span style='background-color:#7FFF00;display:inline-block;height:20px;width:20px'/> <small>7.5</small></li>" +
						"<li><span style='background-color:#7FFFD4;display:inline-block;height:20px;width:20px'/> <small>5.0</small></li>" +
						"<li><span style='background-color:#00FFFF;display:inline-block;height:20px;width:20px'/> <small>2.5</small></li>" +
						"<li><span style='background-color:#87CEFA;display:inline-block;height:20px;width:20px'/> <small>1.0</small></li>" +
						"<li><span style='background-color:#1E90FF;display:inline-block;height:20px;width:20px'/> <small>0.5</small></li>" +
						"<li><span style='background-color:#0000CD;display:inline-block;height:20px;width:20px'/> <small>0.25</small></li>" +
						"<li><span style='background-color:#000080;display:inline-block;height:20px;width:20px'/> <small>0.10</small></li>" +
						"</ul>"
			}
		}, ...

Screenshot with HTML legend:

![screen shot 2015-01-20 at 10 34 52 am](https://cloud.githubusercontent.com/assets/2255248/5823471/d47916f6-a091-11e4-9768-85dd858c2fba.png)

Note that Geomap now generates dynamic legends for vector data sources (e.g. KML, JSON, tabular, etc.).

**Comment by jelofson** [comment]
I think that's going to be great. Nice work. I need to migrate the app to WET4 in the next couple of months, so I will try it out then. Thanks so much for working on this.

**Comment by LaurentGoderre** [comment]
@jelofson can we close then?

**Comment by jelofson** [comment]
Based on information here, yes, you can mark it closed.

**Comment by LaurentGoderre** [comment]
You can always reopen if it's still an issue
