### ISSUE TITLE
Forms + Multiple Pages = Survey?

### ISSUE THREAD

**Issue by accurate** [wet-boew/wet-boew#4431]
Hi there,
Just wondering if it's possible to combine forms with a series of pages with basic Yes/No radio buttons.

For example, page 1 would have a yes or no question.

Answering yes will go to page 2 while answering no will skip to page 5.

I do not need to keep data throughout, it's just a linear process.

Where do I get the data from the form to process and determine which page to skip?

Thanks for your time.

**Comment by hsrudnicki** [comment]
Are you ready to close this issue ?

**Comment by pjackson28** [comment]
Yes as it requires custom code and not something that could really be offered globally.
