### ISSUE TITLE
Panel colour more vibrant.

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/wet-boew#4480]
Could we possibly make the default Bootstrap panel colours more vibrant and not so pastel?

http://wet-boew.github.io/wet-boew-styleguide/new/design/panels-en.html#colour

I would like to see the title bar have more contrast and maybe be a little more differences between them.

Also would like to see text (mandatory) added to the panel describing what they are used for.

CC: @thomasgohard & @cfarquharson

**Comment by hsrudnicki** [comment]
Are you ready to close this styling issue or otherwise ?

**Comment by hsrudnicki** [comment]
Please update this issue's status [Note that this issue had been opened in 2013 and last commented in 2014 milestone(s) and no further discussion after], thanks

**Comment by hsrudnicki** [comment]
@shawnthompson and others: Put "Going stale" and close this issue of last year or otherwise?

**Comment by hsrudnicki** [comment]
Due to no further status updates/discussion, this issue made "Going Stale" and closed.
