### ISSUE TITLE
Add text-decoration: none; to list-group

### ISSUE THREAD

**Issue by cfarquharson** [wet-boew/wet-boew#4515]
Currently the list-group class leaves the link's underline and removes it on :hover.

Can we just remove it permanently?  It's very awkward to look at and we ALREADY did that override for the left menu use of list-group. 

Here's the default look:
![listgroup](https://f.cloud.github.com/assets/2319199/2117887/9ed6776e-90e8-11e3-892c-ad16422f8e73.JPG)

Here's the better look:
![listgroup2](https://f.cloud.github.com/assets/2319199/2117888/a2d0700e-90e8-11e3-822e-7bcd370cd779.JPG)

**Comment by hsrudnicki** [comment]
Can be this styling issue closed or otherwise ?

**Comment by hsrudnicki** [comment]
Please update this issue's status [Note that this issue had been opened in 2013 and last commented in 2014 milestone(s)], thanks

**Comment by hsrudnicki** [comment]
Make "Going Stale" and closed or otherwise? If no any brief response/update, then this issue as stale can be closed (?)

**Comment by hsrudnicki** [comment]
Due to no further discussion/status updates, this issue made "Going Stale" and closed.
