### ISSUE TITLE
Component documentation for v4.0

### ISSUE THREAD

**Issue by pjackson28** [wet-boew/wet-boew#4516]
It's necessary to build the documentation for each of the components for v4.0 as soon as possible since the formal release is a month and a half away. We'll use this issue to track progress on that documentation. I've created a placeholder for each component in <code>docs/ref/</code> using the agreed upon documentation template. Please use that to create your documentation.

I've assigned the documentation to the know active contributors for each component but there are a lot that are unassigned. I can take some of the unassigned on but I'll need help since there are a lot of unassigned. Please post what unassigned ones you are willing to take on (or if you know someone else that can help out).

Assigned
- [x] Accessibility responsibility breakdown - @pjackson28
- [x] ARCHIVED - Archiving content - @thomasgohard
- [x] Calendar of Events - @berubs 
- [x] Base theme - @pjackson28
- [x] Canada.ca theme - @pjackson28
- [x] Charts and graphs - @duboisp 
- [ ] [Core framework (v3.1)](http://wet-boew.github.io/wet-boew/docs/ref/core-en.html) - @nschonni
- [x] Country Content - @nschonni 
- [x] Data Picture - @patheard 
- [x] Datalist polyfill - @pjackson28
- [x] Details/summary polyfill - @pjackson28
- [x] Equal height - @thomasgohard 
- [x] Favicon - @patheard 
- [x] Feedback form - @pjackson28
- [x] Feeds - @pjackson28
- [x] Footnotes - @EricDunsworth 
- [x] Form validation - @pjackson28
- [x] Government of Canada intranet theme - @pjackson28
- [x] Government of Canada Web Usability theme - @pjackson28
- [x] Input type="date" polyfill (date picker) - @berubs 
- [x] Input type="range" polyfill (slider control) - @pjackson28
- [x] Lightbox - @pjackson28
- [x] MathML polyfill - @patheard 
- [x] Meter polyfill - @pjackson28
- [x] Multimedia player - @LaurentGoderre 
- [x] OGPL theme - @pjackson28
- [x] Overlay - @pjackson28, @thomasgohard 
- [x] Prettify - @patheard 
- [x] Progress polyfill - @pjackson28
- [x] Session timeout - @patheard 
- [x] Share widget - @pjackson28
- [x] Tabbed interface - @schindld 
- [x] Tables - @jeresiv 
- [x] Text highlighting - @pjackson28
- [x] Toggle - @patheard 
- [x] Twitter embedded timeline - @pjackson28
- [x] Web Accessibility Assessment Methodology - @pjackson28
- [x] WET theme - @pjackson28

Unassigned
- [x] Data Inview
- [x] Menu

@patheard @EricDunsworth @LaurentGoderre @nschonni @jeresiv @berubs @masterbee @thomasgohard @duboisp @cfarquharson

**Comment by hsrudnicki** [comment]
Can be this issue closed ?

**Comment by pjackson28** [comment]
Yes, all the documentation is in place.
