### ISSUE TITLE
Rewriting getting started documentation for v4.0

### ISSUE THREAD

**Issue by pjackson28** [wet-boew/wet-boew#4517]
We need to update our documentation for v4.0. The Getting started section is something that hasn't been tackled yet. I've listed the related v3.1 documentation below (will need to be converted to .hbs files in v4.0).

Do we have any volunteers for each part of this documentation (or know someone who would be willing to take on one or more parts)?

- [x] [Getting started](http://wet-boew.github.io/wet-boew/docs/gs-cd/index-en.html)
- [x] [Using GitHub for WET](http://wet-boew.github.io/wet-boew/docs/gs-cd/github-en.html)
- [ ] [Implementing WET](http://wet-boew.github.io/wet-boew/docs/gs-cd/impl-en.html)
- [x] [Developing for WET](http://wet-boew.github.io/wet-boew/docs/gs-cd/dev-en.html)
- [ ] [Building WET](http://wet-boew.github.io/wet-boew/docs/gs-cd/build-en.html)
- [ ] [Adding new functionality](http://wet-boew.github.io/wet-boew/docs/gs-cd/add-en.html)
- [x] [Contributor guidelines](http://wet-boew.github.io/wet-boew/docs/gs-cd/contrib-en.html)
- [ ] [External projects used in WET](http://wet-boew.github.io/wet-boew/docs/ref/external-en.html)

@patheard @EricDunsworth @LaurentGoderre @nschonni @jeresiv @berubs @masterbee @thomasgohard @duboisp @cfarquharson

**Comment by hsrudnicki** [comment]
Are you ready to close this issue or otherwise ?

**Comment by hsrudnicki** [comment]
No further discussion since 2014, so please update this issue's status whether this issue can be closed or otherwise? Thx

**Comment by hsrudnicki** [comment]
Made "Going Stale" and if no further status updates/discussion then this issue can be closed or otherwise? Please update this issue's status, thx

**Comment by hsrudnicki** [comment]
Due to no further discussion/status updates, this issue can be closed as going stale.
