### ISSUE TITLE
Table validator vs WPSS

### ISSUE THREAD

**Issue by nrc-cnrc-web** [wet-boew/wet-boew#4545]
Hi,

Below is an email I received from one of our Senior Comms people regarding a discrepancy between code output by the Table Validator and analysis of that code by WPSS. If someone could weigh in as to which is correct, I'd appreciate it.

Thanks,
Matt

------------
This is the output from the Table Validator. This is also what an instructor for the Canada School of Public Service Accessibility course suggested we should do. Note that the data cells do not include in their headers element the id “tb1-0”.

When this is checked by WPSS, we receive the following error:

1.3.1 H43: Using id and headers attributes to associate data cells with header cells in data tables. Missing 'headers="tb1-0"' found in header 'id="tb1-5"'. Header defined at (line:column) 184:6. Source line: &lt;td headers="tb1-2 tb1-4 tb1-5"&gt;

To correct the error we need to make reference to “tb1-0” in the headers element for all td cells if a cell they refer to also refers to tb1-0.

For example, if a cell X has `headers="tb1-2 tb1-4 tb1-5"` and the cell with ID tb1-5 includes `headers=” tb1-0”`, then cell X must include tb1-0 in its headers element.
```html
	<table class="span-6" id="tb1">
		<thead>
			<tr>
				<th class="align-left align-bottom" id="tb1-0"> Measured Quantity &amp; Range or Instrument</th>
				<th class="align-left align-bottom" id="tb1-1">Frequency</th>
				<th class="align-left align-bottom" id="tb1-2"><span class="align-left align-bottom">Calibration Measurement Capability <br />expressed as an Uncertainty  (±) <br />
				<span class="font-small">(See <a href="/eng/solutions/advisory/clas/certificates/supplementary_notes.html">supplementary notes</a>)</span></span></th>
				<th class="align-left align-bottom" id="tb1-3"> Remarks</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<th colspan="4" id="tb1-4"> Frequency</th>
			</tr>
			<tr>
				<th class="align-left background-white" id="tb1-5" headers="tb1-0 tb1-4"><div class="indent-large"> 0.01&nbsp;Hz to 10&nbsp;MHz </div></th>
				<td>&nbsp;</td>
				<td headers="tb1-2 tb1-4 tb1-5">0.22  parts in 10<sup>9</sup></td>
				<td headers="tb1-3 tb1-4 tb1-5"><p>By phase comparison.  See Type II capabilities below for frequency. </p><p>Measure and source capabilities. For suitably stable sources with amplitudes between 0.1 V to 5 V rms. </p></td>
			</tr>
		</tbody>
	</table>
```
------------

**Comment by hsrudnicki** [comment]
@LaurentGoderre and others: Can be this issue closed or otherwise ?

**Comment by hsrudnicki** [comment]
@duboisp and others: Since the referenced issue had been closed, can be this issue of 2014, to be closed as well or otherwise? Please update this issue's status, thank you

**Comment by hsrudnicki** [comment]
Made "Going Stale" and if no further discussion/status updates then this issue can be closed as the above referenced issue or otherwise? Please update this issue's status, thx

**Comment by duboisp** [comment]
@hsrudnicki you can close this issue,

To summarize this request,

* There is a difference between how the WET table validator set ids/headers and how the WPSS evaluate table for assessibility
* It was said that there is two method for setting the ids/headers on a tables
 * Implicit relationship
 *  Explicit relationship
* It was suggested that someone with authority take a clear decision on which method to use, but that never happenned yet

Cheers and sorry for my late reply

:smile:

**Comment by hsrudnicki** [comment]
Based on the above, this issue is closed now.
