### ISSUE TITLE
Overlay (v4.0)

### ISSUE THREAD

**Issue by MBlondin** [wet-boew/wet-boew#4557]
Similar to the v3.X slideout tab feature, will the Overlay feature have a tag that can scroll with the page to access the overlay

**Comment by MBlondin** [comment]
@LaurentGoderre @thomasgohard Instead of having an image that scrolls with the page to show the overlay (like the WET3.0.4 Slide Out Tab)  Could a fixed to top NavBar with a link to open the overlay be a valuable option?

**Comment by thomasgohard** [comment]
@MBlondin what about the approach @Empereol is suggesting in #6367?

**Comment by MBlondin** [comment]
@thomasgohard the approach suggestion by @Empereol  looks interesting and promissing but I wonder the view that it would have on a phone.  The reason I propose the Overlay to display a step-by-step is, for example on our Web Application at NSERC/SSHRC, we use a wizard step for our forms to limit loading time to a minimum and currently use the WET 3.0.4 Slide Out Tab as our Table of contents of steps.

**Comment by thomasgohard** [comment]
We want a common solution for the wizard pattern. And, yes, it would have to work on mobile, which I think @Empereol's approach can support easily enough.

The problem with an overlay-based solution is that you need a trigger. And, if the contents of the overlay need to be available at any point in the process, that means that that trigger must permanently claim some part of the screen. That's a bad solution for small-screen devices where screen space is very limited. It's also a bad solution for large-screen devices where the trigger will be so small or out of the way as to be invisible to users.

**Comment by hsrudnicki** [comment]
Are you ready to settle on a solution to close this issue dilemma ?

**Comment by hsrudnicki** [comment]
@MBlondin and others: Please update this issue's status as well [Note that issue 6367 had been referenced with this issue], thank you

**Comment by hsrudnicki** [comment]
Based on the following:
1)  the last comment from @thomasgohard
2)  no further inputs/updates to this issue's dilemma/status
3) the closed issue 6367 
this issue can be closed
