### ISSUE TITLE
Datalist polyfill (auto-complete)-IE8-desktop

### ISSUE THREAD

**Issue by nrustand92** [wet-boew/wet-boew#4621]
Clicking the text field generates a drop down menu.  I can scroll through the list w/ the mouse, but when the scroll bar is clicked, the menu closes (rather than letting me scroll up and down)

**Comment by pjackson28** [comment]
Can someone please look into this? It seems that this issue affects IE9 as well. Most likely because the scroll bar is considered outside the container that the polyfilled datalist resides in (not part of the DOM).

**Comment by pjackson28** [comment]
Note that this is not an issue for IE10 or later as those browsers have native support for datalist.
