### ISSUE TITLE
Charts: JS could use cleaning up and optimization

### ISSUE THREAD

**Issue by pjackson28** [wet-boew/wet-boew#4685]
Charts.js could use some cleaning up and optimization. It is much better than before but there are several opportunities to optimize DOM queries and updates and to do more with caching.

Created this issue as a reminder that more cleanup and optimization needs to be done to help keep it as small and speedy as possible.

/cc @duboisp

**Comment by hsrudnicki** [comment]
@pjackson28 @duboisp @LaurentGoderre : Can be this issue closed ?

**Comment by hsrudnicki** [comment]
@duboisp and others: Please update this issue's status whether this issue, last commented in 2014, had been fixed and ready to be closed or otherwise? Thank you

**Comment by hsrudnicki** [comment]
Due to no further discussion/status updates, this issue has been labeled "Going Stale" and closed.
