### ISSUE TITLE
Tabbed Interface: Is there a difference between how these are designed and the Carousel tabs?

### ISSUE THREAD

**Issue by dfarough** [wet-boew/wet-boew#4744]
@wet-boew/access-working-group 
I am noticing that when switching from one tab to another, that Jaws is not reading the currently selected tab before speaking the newly selected tab.  This is the result that I would prefer to see/hear when using the Carousel tabs.  Currently the Carousel tabs are a bit chatty when moving from one to another. Is there something being done differently here that would explain this?

**Comment by hsrudnicki** [comment]
So, can be this issue closed or otherwise ?

**Comment by dfarough** [comment]
These tabs are working for me now.  This can be closed.
