### ISSUE TITLE
Main menu large view - breadcrumb issue (From HE)

### ISSUE THREAD

**Issue by rubinahaddad** [wet-boew/wet-boew#4915]
From HE: https://github.com/wet-boew/wet-boew-styleguide/issues/15

For the WET menu

**Recommendation: the bread crumbs should match the menu.**
 Reviewers found the mismatch between the bread crumbs and menu confusing. “If the user looks at the crumb trail they can see that they are in the “Working Examples” area. The crumb trail is not accurately “Synced” to the menu, as the user is actually in “Home > Implement WET > Working Examples > Menu”. The “Implement WET” part is missing from the crumb trail which breaks the user’s mental model of the navigation path.”

**Comment by hsrudnicki** [comment]
@rubinahaddad @pjackson28 and @LaurentGoderre : Can be this issue closed or otherwise ?

**Comment by hsrudnicki** [comment]
Please update this issue's status whether this issue, which had been referenced with the issue: 971, can be closed or otherwise?

**Comment by hsrudnicki** [comment]
Based on the above, this issue of 2014 has been closed, if you think otherwise please update this issue's status again, thank you

**Comment by hsrudnicki** [comment]
Leave a comment
