### ISSUE TITLE
IE8 Charts and graphs-line & bar graphs-desktop

### ISSUE THREAD

**Issue by nrustand92** [wet-boew/wet-boew#4938]
![ie8charts graphs](https://f.cloud.github.com/assets/5949078/2472847/f44ff762-b03a-11e3-8fcd-a7ef79ef790a.png)

Wherever there are bar or line graphs in all the 6 charts & graphs examples, it got cut off when screen is shrunk.

**Comment by hsrudnicki** [comment]
Can be this issue closed ?

**Comment by pjackson28** [comment]
Yes since we no longer support IE8.
