### ISSUE TITLE
Form validation example bug - "Digits only" field accepted chars other than digits without complaint

### ISSUE THREAD

**Issue by rubinahaddad** [wet-boew/wet-boew#4941]
http://wet-boew.github.io/v4.0-ci/demos/formvalid/formvalid-en.html

On Mac OS 10.9.1, Safari, the "digits only" field accepted chars other than digits without complaint. Users were able to enter punctuation into the digits field and letters into the “between 5 & 40” field.

**Comment by hsrudnicki** [comment]
Are you ready to close this issue ?

**Comment by LaurentGoderre** [comment]
It should be fixed now, the issue was fixed upstream in v1.12 and we are on v1.13

**Comment by LaurentGoderre** [comment]
Need to test with SauceLabs

**Comment by LaurentGoderre** [comment]
I tested with SauceLabs and it is working
