### ISSUE TITLE
Javascript form validation Canadian postal code?

### ISSUE THREAD

**Issue by PatrickJoannisse** [wet-boew/wet-boew#4963]
I couldn't find any method under form validation for Canadian postal code. I added a method for one for my current projects (using the Jquery.validator.addMethod) but I'm sure there's a way with WET that I just couldn't find. Am I missing something?

**Comment by hsrudnicki** [comment]
@PatrickJoannisse @pjackson28 and @LaurentGoderre : Can be this issue closed ?
