### ISSUE TITLE
Headers don't display well in summary tags

### ISSUE THREAD

**Issue by bsouster** [wet-boew/wet-boew#4965]
Adding any header tag around the text in summary tag displays poorly.

In case anyone is unfamiliar, this is a somewhat new requirement in light of Rubina's finding of a W3 update allowing header tag use in summary tag:
http://www.w3.org/html/wg/drafts/html/master/interactive-elements.html#the-summary-element

**Comment by hsrudnicki** [comment]
@bsouster @pjackson28 @LaurentGoderre : Can be this issue closed ?

**Comment by pjackson28** [comment]
Yes since the fix is to apply the appropriate h* class to the summary element to match the heading level.
