### ISSUE TITLE
Accessibility responsibility breakdown-Asus tablet-Chrome-portrait view

### ISSUE THREAD

**Issue by nrustand92** [wet-boew/wet-boew#5019]
Text displaying # of entries shown hidden when scrolled to the right. I'm concerned users may want to have it displayed at all times. What do you think @thomasgohard @pjackson28 ?
![screenshots_20140326_083935](https://cloud.githubusercontent.com/assets/5949078/2532750/5a72b03a-b549-11e3-84e3-3ee887a99617.png)

![screenshots_20140326_083950](https://cloud.githubusercontent.com/assets/5949078/2532746/3c9a7da4-b549-11e3-8dcf-2cfb622c64a6.png)

**Comment by hsrudnicki** [comment]
@thomasgohard and others : Are you ready to close this issue ?

**Comment by pjackson28** [comment]
It can be closed here as better responsive table solutions are being dealt with in other issues. This is just a specific example of the more general issue.
