### ISSUE TITLE
WET 4.0 - Twitter feed - accessibility

### ISSUE THREAD

**Issue by crichard** [wet-boew/wet-boew#5028]
I was testing the use of the twitter-timeline widget, and I can't seem to figure out how to get to the reply-retweet-favorite icons using the keyboard only.  They appear on mouseover, but I can't see the options with the keyboard.

**Comment by hsrudnicki** [comment]
Can be this issue closed or otherwise ?

**Comment by hsrudnicki** [comment]
Please update this issue's status whether this issue, opened and last updated in milestone(s) in 2014, can be closed or otherwise? Thank you

**Comment by hsrudnicki** [comment]
Due to no further discussion/questions/status updates, this issue has been labeled "Going Stale" and closed.
