### ISSUE TITLE
Usability of expand/collapse for screen reader users

### ISSUE THREAD

**Issue by lonnycameron** [wet-boew/wet-boew#5135]
CRA has created some design guidelines for Questions and Answers pages, AKA FAQ pages.  The main goal was to provide guidance to content authors who are considering creating a new Questions and Answers page on the CRA external web site.

One of the recommendations is to code the question and the answer using the expand/collapse WET component (http://wet-boew.github.io/v4.0-ci/demos/details/details-en.html).  When the page is first loaded, using progressive disclosure, only the question is visible to the user.  If the user is interested in the answer, then they can expand the question to see the answer.

![expand_collapse_example_01](https://cloud.githubusercontent.com/assets/1899872/2617589/a691f5e4-bc14-11e3-9cd4-0a71ef40f9f3.PNG)

When a screen reader encounters the expand/collapse icon it simply states, “button”, and then reads the text for the question.  When we tested with one screen reader user, they were not sure of the purpose of this button.  The user said it would be helpful, if they had some additional context to tell them the purpose of this button.

We are proposing the use of the expand all/collapse all buttons at the top of the page to help provide screen reader users with additional context.

For example,

![expand_collapse_example_02](https://cloud.githubusercontent.com/assets/1899872/2617604/e229e67a-bc14-11e3-8a85-028a01069a3c.PNG)

Does anyone have any other suggestions for improving the usability of the expand/collapse component in this Questions and Answers context?

**Comment by hsrudnicki** [comment]
Can be this issue closed ?

**Comment by pjackson28** [comment]
Yes since the issue is limited to IE8 and that browser is no longer supported.
