### ISSUE TITLE
Geomap and photos question

### ISSUE THREAD

**Issue by crichard** [wet-boew/wet-boew#5138]
I would like to know if it is possible to use geomap to display photos which are geotagged (ie for a relay event).  Thanks.

**Comment by hsrudnicki** [comment]
@crichard and others: Can be this issue closed ?

**Comment by hsrudnicki** [comment]
@crichard and others: Please update this issue's status whether this issue, opened and last commented in 2014, can be closed or otherwise? Thank you

**Comment by jolevesq** [comment]
@hsrudnicki I think we can close this.
