### ISSUE TITLE
Details/summary polyfill (expandable/collapsible content): 

### ISSUE THREAD

**Issue by rlambert27** [wet-boew/wet-boew#5141]
Quick question for you guys.. our clients raised an issue …not sure if there is a solution to this honestly, but thought I’d ask.

They use expand/collapse extensively throughout their content… text is collapsed by default. They also use local anchors, and sometimes, these anchors point to a target in a collapsed area.

The link doesn’t “work” when the target is collapsed (hidden)…our client says this may be a showstopper… I don’t think there is a workaround to this is there? Short of possibly coding some javascript on the local anchor to automatically expanding the collapsed area containing the target?

Let me know, thanks!

**Comment by hsrudnicki** [comment]
@rlambert27 @pjackson28 : Can be this issue closed ?

**Comment by rlambert27** [comment]
Yes
