### ISSUE TITLE
Spacing issue when paragraph follows details

### ISSUE THREAD

**Issue by bsouster** [wet-boew/wet-boew#5163]
We're getting complaints that the spacing after details is causing it to appear associated with the content below it.

![details1](https://cloud.githubusercontent.com/assets/1944744/2645324/619efa48-bf31-11e3-805a-cbba095941b8.jpg)

![details2](https://cloud.githubusercontent.com/assets/1944744/2645328/655c50cc-bf31-11e3-9643-3e055ca7bce7.jpg)

**Comment by hsrudnicki** [comment]
@bsouster and others: Can be this issue closed ?

**Comment by pjackson28** [comment]
Yes we can close as this issue has been inactive for over a year and there are options readily available for adding the desired spacing.
