### ISSUE TITLE
Multimedia player play/pause bug in Firefox

### ISSUE THREAD

**Issue by rubinahaddad** [wet-boew/wet-boew#5169]
From HE: https://github.com/wet-boew/wet-boew-styleguide/issues/11

The Play / Pause in the middle of the screen: The reviewers pointed out that it is typical to be able to start and stop video playing by clicking in the middle of the video. In some device/browsers this worked, and in others it didn't:

This didn't work in Firefox on a Nexus 7 tablet

**Comment by hsrudnicki** [comment]
@rubinahaddad @LaurentGoderre : Can be this issue closed ?

**Comment by hsrudnicki** [comment]
@rubinahaddad and others: Please update this issue's status whether this issue, opened and referenced with the closed issue 11, can be closed or otherwise?

**Comment by hsrudnicki** [comment]
Due to no further discussion/status updates, this issue has been labeled as "Going Stale" and closed.

**Comment by rubinahaddad** [comment]
@hsrudnicki have you tested to see if the bug has been fixed? If it's still an issue it shouldn't have been closed. Bug tickets shouldn't be closed until they have been addressed or the WET team indicates that they function as designed.

**Comment by hsrudnicki** [comment]
@rubinahaddad and others: Finally you have responded, but not before closing and notifications sent earlier, anyway this issue has been re-opened and please periodically update this issue's status, it means that you are working on this issue/keeping in mind, thank you

**Comment by rubinahaddad** [comment]
@hsrudnicki I opened these issues when i was working at TBS (which i no longer am). These were all for the WET team.

**Comment by hsrudnicki** [comment]
@rubinahaddad : So and additionally due to some restructuring of the WET, we can wait a couple of days to check if more comments/updates will come, if not this issue will be closed.

**Comment by andre-gh** [comment]
@hsrudnicki It is likely safe and helpful to leave confirmed issues open but label them as stale

**Comment by hsrudnicki** [comment]
@andre-gh : Fine, and thank you for your input

**Comment by hsrudnicki** [comment]
Remain this issue still opened or otherwise?  Either way, please again update this issue's status, whether this issue can be closed as resolved/fixed or if otherwise?  Thank you

**Comment by hsrudnicki** [comment]
Is this still a bug, as well a valid issue? Please update the status of this for the current year, thank you

**Comment by masterbee** [comment]
closed since the media player now has an icon on center of the screen to play (overlays the image)
