### ISSUE TITLE
Demo files for each language in each theme

### ISSUE THREAD

**Issue by burgvan** [wet-boew/wet-boew#5182]
Noticed on the v4.0 that it no longer has demos for each language for each theme such as how it was on v3.1 - http://wet-boew.github.io/v3.1-ci/demos/theme-base/index-en.html

**Comment by hsrudnicki** [comment]
Are you ready to close this issue or otherwise ?

**Comment by LaurentGoderre** [comment]
We can close this since there is an issue on GCWeb about this and it's the last theme that needs it.
