### ISSUE TITLE
Improve developer experience for improving documentation

### ISSUE THREAD

**Issue by jpmckinney** [wet-boew/wet-boew#5219]
I'm trying to improve WET's docs. It's currently more confusing than it should be to answer the question, "How do I use WET in my own project?" Anyway, this issue is not about answering that question.

Here is my basic process for setting up my environment and improving the docs:

1. Do the documented Node, Grunt, etc. steps
1. Run `grunt` to generate `dist/`
1. [Install a LiveReload browser extension](http://feedback.livereload.com/knowledgebase/articles/86242-how-do-i-install-and-use-the-browser-extensions-)
1. Open an HTML page from the `dist/unmin/` directory in my browser
1. Enable the LiveReload extension for that browser tab
1. Run `grunt watch:demos`
1. Edit and save files under `site/pages`. The browser tab will automatically refresh.

However, since [assemble always compiles everything](https://github.com/assemble/assemble/issues/451) it takes about 20 seconds from saving a file to seeing what it looks like in the browser.

Please tell me there is a better way to preview changes to documentation pages.

**Comment by hsrudnicki** [comment]
@jpmckinney @nschonni : Can be these issue(s) closed ?

**Comment by jpmckinney** [comment]
I haven't heard of a better way to preview changes that doesn't take ~20 seconds per change, but maybe there is none.

**Comment by LaurentGoderre** [comment]
The way our watch functionality is configured works great for JS and CSS but not so much for html yet

**Comment by hsrudnicki** [comment]
Please update this issue's status whether this issue can be closed when the configured functionality works for HTML as well or otherwise? Thank you

**Comment by hsrudnicki** [comment]
@jpmckinney and others: Please update this issue's status whether this issue, referenced with the other 5221 that is already merged, can be closed or otherwise? Thank you

**Comment by jpmckinney** [comment]
I think people who actively develop wet-boew would have a better idea of whether the time to compile JS, CSS, HTML has been reduced significantly from the 20 seconds when the issue was reported. /cc @LaurentGoderre @nschonni

**Comment by hsrudnicki** [comment]
Close this issue, just labeled as "Going Stale" or if otherwise, then please update this issue's status ? Thank you

**Comment by hsrudnicki** [comment]
Based on the above, this issue can be closed.
