### ISSUE TITLE
Add "Page Layouts" in Working Examples

### ISSUE THREAD

**Issue by burgvan** [wet-boew/wet-boew#5230]
Feedback form and Archived - Archiving Content should be categorized under "Page Layouts"

**Comment by hsrudnicki** [comment]
Are you ready to close this issue or otherwise ?

**Comment by hsrudnicki** [comment]
Please update this issue's status, whether this issue, opened as well as last commented in 2014, can be closed or otherwise? Thank you

**Comment by hsrudnicki** [comment]
Close this issue, just labeled "Going Stale" or otherwise? 
@laurawesley and others, please respond and continue updating this issue's status, thank you

**Comment by hsrudnicki** [comment]
No further discussion/status updates, this issue can be closed
