### ISSUE TITLE
Geomap-Inline layer data-Zoom to city link doesn't work

### ISSUE THREAD

**Issue by nrustand92** [wet-boew/wet-boew#5248]
Clicking "Zoom to city" doesn't enlarge the map anymore than it already is

![image](https://cloud.githubusercontent.com/assets/5949078/2726614/8e2301d4-c5be-11e3-9e3f-3203a62d88c6.png)

**Comment by hsrudnicki** [comment]
Are you ready to close this issue ?

**Comment by jvanulde** [comment]
No. I think this is a good suggestion and it should remain as an outstanding issue.

**Comment by hsrudnicki** [comment]
Is this still an outstanding issue, if yes for how long? Either way, please update this issue's status, whether this issue of 2014 can be closed as fixed or if otherwise?  Thank you

**Comment by jvanulde** [comment]
We should close this and create a new feature request for disabling zoom controls at minimum and maximum scales.

**Comment by hsrudnicki** [comment]
Can be this issue closed or otherwise?

**Comment by jvanulde** [comment]
Yes close it.

**Comment by hsrudnicki** [comment]
Based on the above, thank you
