### ISSUE TITLE
New Homepage for WET Mockup

### ISSUE THREAD

**Issue by burgvan** [wet-boew/wet-boew#5264]
I’m currently working with the WET team on re-designing the WET website by creating some mock-ups first. Here’s the homepage mock-up for desktop and mobile that I would like to hear some feedback on. I’m aiming for a modern and clean design for the website. Ideally, when the user first lands on the page, they would see the large banner with an arrow pointing downwards to guide them further down the page. We have decided to change the Information Architecture, so we’re planning on integrating “Guides”. At the moment, the label “Guides” is up in the air but we are planning on integrating the guides once those are cleaned up. We will be testing the proposed Information Architecture online very soon as well so it might change. 

We kept the blue/gray/light colour scheme to keep the branding consistent. The homepage is designed to be more user-friendly in terms of being able to find the important content on the page easier and quicker. An example of this is making the Download and Getting Started buttons noticeable once the user lands on the page. We are trying to reach out to ALL groups of users, not just developers/IT, especially on this particular page as well as the Getting Started page (coming soon!). We think integrating a social aspect on the homepage such as the Github feed and the alternating quotes from news articles would instigate more people to contribute to the project. The benefits are lightly listed and then the main links that different types of users would possibly be looking for are linked in 6 different boxes with self-explanatory titles. The 3 samples of websites that are built with WET are showcased at the bottom for a final touch of what WET is all about. 

Please let me know what you think of these mock-ups. 

Thank you!

Vanessa

![newhomepage](https://cloud.githubusercontent.com/assets/4314923/2766689/668bbc66-ca31-11e3-8ada-84b53cccdf6d.jpg)

**Comment by hsrudnicki** [comment]
https://github.com/wet-boew/wet-boew/issues/5413 - New Getting Started

**Comment by hsrudnicki** [comment]
@burgvan and others : Can be this issue closed or otherwise ?

**Comment by laurawesley** [comment]
Is the site going to be updated?!

Date: Tue, 9 Jun 2015 10:55:51 -0700

**Comment by hsrudnicki** [comment]
Please update this issue's status, and if still applicable answer to the question in last comment? Thanks

**Comment by hsrudnicki** [comment]
Make "Going stale" in order to close this issue or otherwise? 
Thank you in advance for this issue's status update.

**Comment by hsrudnicki** [comment]
Made this issue "Going Stale"

**Comment by hsrudnicki** [comment]
and this issue can be closed due to no further discussion/status updates.
