### ISSUE TITLE
Online WET Website Content Navigation Test

### ISSUE THREAD

**Issue by shoffmand** [wet-boew/wet-boew#5266]
We are testing the proposed new Information Architecture/Navigation system for WET on Optimal Workshop. 

Here is a link to the test in English: https://webstandard-normesweb.optimalworkshop.com/treejack/wetwebsiteinformationarchitecture

And in French: https://webstandard-normesweb.optimalworkshop.com/treejack/architecturedelinformation-boew

It shouldn't take too long to go through, and the information gathered will help with making sure that WET gets better/stays good.

**Comment by hsrudnicki** [comment]
So, can be this issue closed ?

**Comment by hsrudnicki** [comment]
Please update this issue's status whether this issue has been solved, based on your above discussion of 2014, and to be ready closed or otherwise? Thank you

**Comment by hsrudnicki** [comment]
Due to no further discussion/status updates, this issue is closed as resolved.
