### ISSUE TITLE
Charts and graphs - Customizing pie charts-IE10-laptop

### ISSUE THREAD

**Issue by nrustand92** [wet-boew/wet-boew#5324]
Minor issue with Segment Labelling example (there's a white circle in the middle).

![image](https://cloud.githubusercontent.com/assets/5949078/2824284/6cb05622-cf2e-11e3-82fa-b91b96103818.png)

**Comment by hsrudnicki** [comment]
@duboisp and others : Can be this issue closed ?

**Comment by hsrudnicki** [comment]
@duboisp @nrustand92 and others: Can be this issue of 2014, closed or otherwise? Please update this issue's status? Thank you in advance

**Comment by hsrudnicki** [comment]
Made "Going Stale" and waiting for further update in regards to this issue's status or close this?

**Comment by hsrudnicki** [comment]
Due to no further discussion, this issue has been closed.
