### ISSUE TITLE
Filing a bug or an issue should include expectation regarding behaviour

### ISSUE THREAD

**Issue by pjackson28** [wet-boew/wet-boew#5333]
I noticed that we don't give a basic rules of the road regarding user behaviour. For instance there is nothing that covers what is expected when interacting with others and indicating that you are responsible for your own comments. Blogs and other sites often have such "rules of the road".

@laurawesley Any suggestions for what we should add regarding this?

**Comment by hsrudnicki** [comment]
Are you ready to close this issue or otherwise ?

**Comment by locutux** [comment]
Yes, please close the issue. Thank you.
