### ISSUE TITLE
Force Autocomplete Polyfill for IE10

### ISSUE THREAD

**Issue by CalvinRodo** [wet-boew/wet-boew#5336]
So turns out IE10 has a horrible implementation for Data-Lists on input controls. 
you can only search from the beginning of the strings in the polyfill, there is no scroll bar for picking items out of the list. Overall it's just a horrible horrible mess. 

That being said how do we force the polyfill to run on IE10? 

http://playground.onereason.eu/2013/04/ie10s-lousy-support-for-datalists/
http://blog.paciellogroup.com/2012/08/notes-on-html5-accessibility-support-in-ie-10/

This is for version 3.1.X

**Comment by hsrudnicki** [comment]
Are you ready to close this issue ?

**Comment by hsrudnicki** [comment]
@CalvinRodo and others: Is this "CSS fix at just IE10", based on the last comment from @pjackson28 , implemented and working? Please update this issue's status, thank you

**Comment by hsrudnicki** [comment]
Due to no further discussion/status updates, this issue has been labeled "Going Stale" and closed.
