### ISSUE TITLE
Charts and graphs - Customization: Label Angle

### ISSUE THREAD

**Issue by philchau** [wet-boew/wet-boew#5359]
Flot - xaxis - labelAngle.

Has this feature been implemented?  I'm working on a large time series- graph and all my dates are all jammed up against each other.   Can't seem to get the xaxis label to rotate.

Example:
```html
<table class="wb-charts table" data-flot='{ "xaxis": { "labelAngle": 90}, "yaxis": { "max": 25} }'>
```
No go.

**Comment by hsrudnicki** [comment]
@duboisp @philchau : Can be this issue closed ?

**Comment by hsrudnicki** [comment]
Further to the last comment @duboisp @philchau , since the PR 5396 had been merged, so this issue can be closed? Please update this issue's status, thank you

**Comment by hsrudnicki** [comment]
Based on last comment from @duboisp and no further discussion/status updates, this issue has been labeled "Going Stale" and closed.
