### ISSUE TITLE
How to open a details/summary by javascript?

### ISSUE THREAD

**Issue by bomarleau** [wet-boew/wet-boew#5369]
Hi,
I am quite new to WET. I tried to write a javascript to manually trigger details section:
```js
function resetDetails(detailsName){
	var details = document.getElementById(detailsName);
	if (details.class == "polyfill open") {
		details.class="polyfill";
	} else {
		details.class = "polyfill open";
	}
} 
```
It seems not working. Could some one provide some help here, thanks a lot.

**Comment by GarthMartin** [comment]
@pjackson28  While this should be striaght forward, for some reason it is not working for me.

I am trying to re-open the details element that was open prior to a postback (through a value in a hidden field) however the details element does not open.  Am I missing something?

As an example, here is one of my details sections (part of an accordion)
```html
<details class="bio-group">
                            <summary class="wb-toggle tgl-tab" data-toggle='{"parent":".accordion","group":".bio-group"}' id="boardMembershipsToggle">
                                <asp:Literal ID="BoardMembershipsLabel" runat="server" Text="<%$Resources:BoardMembershipsLabel %>" ClientIdMode="Static"/></summary>
                            <div class="tgl-panel">
                                <%--  content here --%>
                            </div>
                        </details>
```

and I am trying to toggle it with the following JS (hardcoded for simplicity - even this does not work)
```javascript
 $("#boardMembershipsToggle").click();
```
The element appears to get focus (it's highlighted) but does not open.

I have the first details section set to ```open="open"```, but even if I remove that, the behaviour does not change.

Do we need to toggle the click through the ```toggle.wb-toggle``` event?

Cheers,

**Comment by GarthMartin** [comment]
@pjackson28 Never mind....just realized that I was not waiting for wb-ready....oops.

**Comment by LaurentGoderre** [comment]
Can we close?

**Comment by GarthMartin** [comment]
@LaurentGoderre It's not my thread so I cannot close it.

**Comment by LaurentGoderre** [comment]
@bomarleau can we close this issue?

**Comment by hsrudnicki** [comment]
Again, can be this issue closed ?

**Comment by pjackson28** [comment]
Yes we can close since the issue has been resolved.
