### ISSUE TITLE
JavaScript errors when WET used in MVC4

### ISSUE THREAD

**Issue by locutux** [wet-boew/wet-boew#5399]
Hi,

I have not seen a parrallel repository with WET in a MVC4 project. When I code my project in MVC4, it works fine, the pages load error-free. When I incorporate the WET, it shoots JavaScript exceptions in pe-ap-min.js like the object does not have the property or method "equalHeights" whenever a page loads. Have you ever experienced a problem with MVC4 projects?

Thank you for any insight and for your time.

**Comment by hsrudnicki** [comment]
Can be this issue closed ?

**Comment by locutux** [comment]
Oh boy, sorry I even forgot this existed. Please go ahead and close it. Thanks.

**Comment by hsrudnicki** [comment]
@locutux : If this issue is ready for closing, then you or @LaurentGoderre are in charge of closing it.

**Comment by hsrudnicki** [comment]
@pjackson28 :+1:   (Thx for closing it)
