### ISSUE TITLE
Force toggle to open specific item by passing the variable in the URL?

### ISSUE THREAD

**Issue by cfarquharson** [wet-boew/wet-boew#5411]
We want to have a specific toggle open by default when coming from a different page.  Can the be done?  Normally the item is closed but sometimes we want it open by default. 

It's the same way the you can target a tab to be the visible one by just using the tab id.

**Comment by hsrudnicki** [comment]
@cfarquharson @pjackson28 : Can be this issue closed or otherwise ?

**Comment by hsrudnicki** [comment]
@cfarquharson and others: Please update this issue's status whether this issue, last commented by @pjackson28 in 2014, can be closed or otherwise? Thank you

**Comment by hsrudnicki** [comment]
Based on last comment form @pjackson28 and no further discussion/status updates, this issue has been labeled "Going Stale" and closed.
