### ISSUE TITLE
Where is the server configuration information?

### ISSUE THREAD

**Issue by pjackson28** [wet-boew/wet-boew#5412]
@nschonni The getting started guides in v3.1 have the server configuration information for dealing with SVG and IE compatibility mode. Where is that information located in v4.0? We should also add server configuration for the font files used by Bootstrap as that is not server configuration issue we see on occasion.

**Comment by hsrudnicki** [comment]
Can be this issue closed or otherwise ?

**Comment by pjackson28** [comment]
Yes, the server configuration documentation can be found here: http://wet-boew.github.io/v4.0-ci/docs/server-en.html
