### ISSUE TITLE
New Getting Started

### ISSUE THREAD

**Issue by burgvan** [wet-boew/wet-boew#5413]
Here's a mock-up of the new Getting Started page for the WET website. After conducting some usability testings on the current site, we noticed that the developers rarely used the Getting Started page and they would directly go to the Working Examples page and documentation. Our goal is to appeal other audiences like Comms people and novice users by creating a guided page for them to understand WET, hence why there are some visuals included as well. The information would be displayed in an accordion. I would like to hear some feedback on it and either I or someone else can code this page, and then we can conduct some more testings on it.

![gettingstarted-v5](https://cloud.githubusercontent.com/assets/4314923/2932459/3dbea5c2-d7b1-11e3-8de3-d825c9bbe2ed.jpg)

**Comment by hsrudnicki** [comment]
@burgvan : Can be this issue closed ?

**Comment by hsrudnicki** [comment]
Made this issue "Going Stale", and please update this issue's status whether this issue can be closed or otherwise?

**Comment by hsrudnicki** [comment]
Closed due to no further discussion/status update(s)
