### ISSUE TITLE
asp.net form element conflicting with main content style

### ISSUE THREAD

**Issue by b0uch3** [wet-boew/wet-boew#5417]
The main content area should be displayed with a white background and grey borders, but I've noticed that my masterpage is not delivering the style correctly.   I have trouble shot it to a point where it appears that the asp.net form tag is the reason the white background area is not appearing.

Has anyone worked around this?

I'm pretty sure the style would be applied to the <main> container.  However it needs to be all wrapped in an asp.net <form runat="server ...  tag.

**Comment by hsrudnicki** [comment]
@b0uch3 @LaurentGoderre is asking about closing of this issue or updating its status , again can you close this issue or otherwise ?

**Comment by hsrudnicki** [comment]
Due to no further discussion/status updates, this issue made "Going Stale" and closed as well.
