### ISSUE TITLE
Hover states - Lightbox

### ISSUE THREAD

**Issue by rubinahaddad** [wet-boew/wet-boew#5427]
From HE: https://github.com/wet-boew/wet-boew-styleguide/issues/7

Problem: All three reviewers noted the lack of, or barely detectable, hover response of clickable objects.

Suggestion: All clickable objects should show a more noticeable hover response

**Comment by hsrudnicki** [comment]
Can be this issue closed?

**Comment by pjackson28** [comment]
@thomasgohard What are your thoughts on this? Should a change be made? If so, what should be the change?

**Comment by hsrudnicki** [comment]
Due to no further discussion/status updates, this issue has been labeled "Going Stale" and closed as well.
