### ISSUE TITLE
Lightbox - Click Behaviour ON images in Galleries

### ISSUE THREAD

**Issue by rubinahaddad** [wet-boew/wet-boew#5430]
From HE: https://github.com/wet-boew/wet-boew-styleguide/issues/7

Problem: Several reviewers noted that clicking anywhere on an image advances to the NEXT image, whereas many implementations support clicks to the left of the image going to the PREVIOUS image.

Suggestion: Consider supporting this functionality.

**Comment by hsrudnicki** [comment]
@rubinahaddad @pjackson28 : Can be this issue closed ?

**Comment by pjackson28** [comment]
It is related to #5429. The problem we are facing is there is no clear way to implement such a fix. The next and previous buttons are in the same container as the actual image (which that container is the full width of the screen), so there seems to be no easy easy way to make the buttons reliably and consistently overlap the image to the degree we want. Would have been easier if Magnific Popup include the next/previous buttons in the image container, but that is not the case.

**Comment by hsrudnicki** [comment]
Based on last comment from @pjackson28, this issue with the other referenced issue have been labeled "Going Stale" if not further status updates, then this issue with the other one can be closed.

**Comment by hsrudnicki** [comment]
Due to last comment from @pjackson28 and no further status updates/discussion, this issue has been closed.
