### ISSUE TITLE
Twitter timeline - Scrolling Challenges

### ISSUE THREAD

**Issue by rubinahaddad** [wet-boew/wet-boew#5434]
From HE: https://github.com/wet-boew/wet-boew-styleguide/issues/14

Scrolling Challenges
Problem: All three users had issues with scrolling. Different problems on different devices, but the issues mostly center on scrolling the timeline versus scrolling the web page – particularly on small screen devices.

Suggestion: Use the Width parameter to narrow the widget on mobile devices, so the slice of the web page that is visible is greater.

**Comment by hsrudnicki** [comment]
Are you ready to close this issue or otherwise ?

**Comment by pjackson28** [comment]
Still waiting on the recommended approach to be identified in the styleguide.

**Comment by hsrudnicki** [comment]
The referenced issue 132 of wet-boew-styleguide remains open and not updated (no discussion), so again, please update this issue's status whether this issue can be closed or otherwise, thank you

**Comment by hsrudnicki** [comment]
Made "Going Stale" in order to close this issue soon or if otherwise please update this issue's status?

**Comment by hsrudnicki** [comment]
This issue can be closed due to not provided the recommended approach in the styleguide (The other referenced issue of the wet-boew styleguide remains opened) or update if you think otherwise?
