### ISSUE TITLE
Form validation: 

### ISSUE THREAD

**Issue by jzhang6** [wet-boew/wet-boew#5437]
Hi there,

I used wb-frmvld to validate the form, it looks great, but if I added one JQuery validator to validate some fields in the same form, it seems there is a conflict between wb-frmvld and Jquery validator. 

Thanks in advance.
James

**Comment by hsrudnicki** [comment]
So, can be this issue closed?

**Comment by pjackson28** [comment]
Yes as that new method was incorporated into jQuery validator a while ago.
