### ISSUE TITLE
Postal Code Validator?

### ISSUE THREAD

**Issue by fahmyr** [wet-boew/wet-boew#5473]
We have validators for telephone numbers, email (<input class="form-control" id="email1" name="email1" type="email"/>), url, everything but Postal Code. Why is a postal code validator not included? Where is the documentation on how the pattern attribute works, where is the documentation on where all the data rules are defined.

The postal code validator is what I'm missing but it would be nice to be able to define custom validation rules somehow.

**Comment by hsrudnicki** [comment]
Can be this issue also closed?

**Comment by LaurentGoderre** [comment]
Canadian postal code was included in v1.12 and we are on v1.13. Closing
