### ISSUE TITLE
Date Validation Error

### ISSUE THREAD

**Issue by fahmyr** [wet-boew/wet-boew#5477]
The validation is allowing some invalid dates to pass through.
```html
 <input name="ProvincialPermitExpiryDate" id="ProvincialPermitExpiryDate" type="date" class="form-control" data-rule-dateiso="true" required="required" />
```
01/01/2014 - Not allowed
2014-22-22 - Not allowed

2014/01/01 - allowed
2014/22/22 - allowed

**Comment by pjackson28** [comment]
Closing since IE8 is no longer supported by WET.
