### ISSUE TITLE
Enabling Analytics in Share Widget (Bookmarks)

### ISSUE THREAD

**Issue by jbrousse** [wet-boew/wet-boew#5481]
Hello,

Is anyone using the addAnalytics option in the share widget? I tried enabling it but it is not working. I think bookmark-min.js is referencing old GA calls and functions. Does anyone know how to enable analytics tracking for sites using the newer Universal Google Analytics (analytics.js)? Any info is greatly appreciated.

Thanks

**Comment by hsrudnicki** [comment]
So, are you ready to close this issue or otherwise?

**Comment by LaurentGoderre** [comment]
Closing since we no longer use that plugin and v3.1 is no longer supported
