### ISSUE TITLE
Overlay - dialog size

### ISSUE THREAD

**Issue by b0uch3** [wet-boew/wet-boew#5482]
How do we control the width of the overlay?   

We're modifying an ASP.NET set of modals that are controlled by the ModalPopupExtender.

This is the code that holds the modal.   I tried adding col-lg-XX to the panel's cssClass but it didn't affect the width of the modal.  
```html
    <asp:Panel ID="pnlSearch"  runat="server" CssClass="modal-dialog">        
        <div id="SearchModal" class="modal-content overlay-def"> 
            <header class="modal-header"> 
                <h2 class="modal-title">
                    <asp:Label ID="lblMessage" runat="server" text="Find Reserve" meta:resourcekey="lblMessageResource1"></asp:Label>
                </h2> 
            </header> 
            <div class="modal-body text-center"> 
                <asp:PlaceHolder ID="phBandSearch" runat="server"></asp:PlaceHolder>            
            </div>
        </div>
    </asp:Panel>
```

**Comment by hsrudnicki** [comment]
@pjackson28 @b0uch3 : Can be this issue closed or otherwise?

**Comment by pjackson28** [comment]
@LaurentGoderre Since it involves .NET, any comments on this before we close?

**Comment by LaurentGoderre** [comment]
I would say it is best to avoid using .NET to interfere with the functionality of WET as it gets really messy and is really unoptimized. It's hard to say what the issue is without seeing it.

**Comment by hsrudnicki** [comment]
Again, can be this issue closed or otherwise? Please update this issue's status, thank you

**Comment by hsrudnicki** [comment]
Based on the two last comments from @LaurentGoderre and @pjackson28, and no further status updates, this issue has been labeled "Going Stale" and closed.
