### ISSUE TITLE
Polyfill for placeholder

### ISSUE THREAD

**Issue by UncleZen** [wet-boew/wet-boew#5502]
Is there a WET approved polyfill for placeholder attribute?

**Comment by hsrudnicki** [comment]
@pjackson28 @UncleZen : Can be this issue closed?

**Comment by LaurentGoderre** [comment]
Since placeholder can't be relied upon natively they are just a nice to have therefore we won't provide a polyfill

**Comment by pjackson28** [comment]
Also note that IE8 and IE9 technically fall out of the WET support window anyway since each is well below 5%.
