### ISSUE TITLE
Interesting usability opinion: Kill the Hamberger Button

### ISSUE THREAD

**Issue by michael-milette** [wet-boew/wet-boew#5516]
Just came across an article I though you might find interesting.

http://techcrunch.com/2014/05/24/before-the-hamburger-button-kills-you/

**Comment by hsrudnicki** [comment]
Further to the above article in regards to top-right hamburger-style navigation and other techniques for complex navigation:
http://www.smashingmagazine.com/2013/09/11/responsive-navigation-on-complex-websites/

**Comment by hsrudnicki** [comment]
Based on the above discussions/opinions: Are you ready to close this issue?

**Comment by pjackson28** [comment]
The search icon was added with the hamburger icon to better reflect what was contained within. It seemed to fare better after the changes.

@thomasgohard Can we go ahead and close this issue?
