### ISSUE TITLE
Multimedia scrubbing improvement

### ISSUE THREAD

**Issue by rubinahaddad** [wet-boew/wet-boew#5541]
Is there a way to make the scrubber work by clicking and dragging, or by touching and dragging? This is a common user interaction for scrubbers.

**Comment by hsrudnicki** [comment]
Can be this issue closed or otherwise?

**Comment by LaurentGoderre** [comment]
We will keep open but I will not implement until we have an example of such interaction on the Web.

**Comment by hsrudnicki** [comment]
Please continue updating this issue's status whether this issue can be closed or otherwise? Thank you

**Comment by hsrudnicki** [comment]
Made "Going Stale" and now wait as @LaurentGoderre last commented (  but how long ?), and please keep this issue's status updated

**Comment by LaurentGoderre** [comment]
There is value and this, we can keep open

**Comment by hsrudnicki** [comment]
Keep this issue still opened?  Either way, please update again this issue's status, whether this issue can be closed as resolved/fixed or otherwise?  Thank you

**Comment by hsrudnicki** [comment]
Please update the status/milestone of this issue again for the current year, thank you

**Comment by hsrudnicki** [comment]
Based on the above: Is this still an issue to keep open due to its value? Please update the status of this for the current year as well, thank you

**Comment by masterbee** [comment]
closing until we can find good examples of this behavior that does not incur a full download.
