### ISSUE TITLE
Popovers

### ISSUE THREAD

**Issue by rubinahaddad** [wet-boew/wet-boew#5586]
Are there any plans to create a widget similar to Bootstrap's popover, but an accessible version?

http://getbootstrap.com/javascript/#popovers 

If not, is it possible to do one? I could see this as being the tooltip as well, since it shows up on click instead of hover.

**Comment by hsrudnicki** [comment]
Can be this issue closed or otherwise?

**Comment by RobJohnston** [comment]
The details/summary approach was being discussed in the issue "Help text on form elements":  https://github.com/wet-boew/wet-boew/issues/6613#issuecomment-91658850

**Comment by pjackson28** [comment]
Yes, there is no plan at this point to implement that functionality. Perhaps if someone could flesh out the requirements (covering the issues raised above) and flesh out solid use cases then it could be revisited. Closing for now.
