### ISSUE TITLE
Multiple alerts on the same page one after the other

### ISSUE THREAD

**Issue by pjackson28** [wet-boew/wet-boew#5605]
How should we address multiple alerts on the same page one after the other? In the styleguide there is an example of 3 in a row: http://wet-boew.github.io/wet-boew-styleguide/v4/writing/index-en.html

Is there a cleaner way of dealing with this?

/cc @thomasgohard @rubinahaddad

**Comment by hsrudnicki** [comment]
So, can be this issue closed as well?

**Comment by hsrudnicki** [comment]
Due to no continued discussion and here all referenced issues had been closed, so the issue has been labeled "Going Stale" and closed/resolved as well.

**Comment by hsrudnicki** [comment]
Resolved/closed
