### ISSUE TITLE
Twitter timeline loading after equal height is triggered

### ISSUE THREAD

**Issue by zachfalsetto** [wet-boew/wet-boew#5628]
As the title says. The twitter timeline plugin on WET is loading after equal height is triggered.

After some discussion, a solution we came up with was to have equal height re-trigger after the timeline loads.

**Comment by hsrudnicki** [comment]
Are you ready to close this issue or otherwise?

**Comment by hsrudnicki** [comment]
Made "Going Stale" and if no further updates then this issue can be closed or otherwise? Please update this issue's status, thx

**Comment by hsrudnicki** [comment]
Base on the above discussion, this issue is closed.
