### ISSUE TITLE
Datalist polyfill: list closes when clicking the scrollbar

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/wet-boew#5638]

**Comment by hsrudnicki** [comment]
Can be this issue closed?

**Comment by hsrudnicki** [comment]
Made "Going Stale" to close this issue as resolved/fixed due to the above or if otherwise? Either way, please update this issue's status, thank you

**Comment by hsrudnicki** [comment]
Based on the above milestone setting, can be this issue closed as resolved/fixed or if otherwise?  Either way, please update this issue's status, thank you

**Comment by masterbee** [comment]
Closing since the issue cannot be replicated
