### ISSUE TITLE
Rough notes on how WET works + needs checking and revamping

### ISSUE THREAD

**Issue by Simeon1** [wet-boew/wet-boew#5639]
WET Notes (**Very rough, mostly unedited**)  

src
* main directory
* contains plugins

wb.js
* is the core
* get URL parts

wb.
* the name space for the .
* most plugins will have a reference to wb.

WET
* tries to render to the browser as soon as possible
* defer after loading for when the page starts to paint
* causes JavaScript to be event loading

browsers
* are event driven

wet
* now with wet wait for the browser to call wet

all plugins 
* are live bind
* top level dom structure listens to events
* event listeners are at the top level dom document
* add anchor eventually function will come to document root

i18n
* internationalization

other
* separate complete packaged objects that a plugin would call items in other folder

plugin
* every plugin has its own folder
* contain 
* all plugins live in events version change of 3 to 4 is when the plugins communication got 	revamped
* now plugins are event driven

actual syntax
plugins are called
* from the markup
* wb-name of the plugin
* no vowel naming convention
* important because of namespace

anonymous function example
	-function($, win, un)
encapsulation
* $ brought in conflicts
* passing two variables inside a function
* called encapsulated coding function
* this is protected because we are not reading the dom it is event driven
* undef
 * in some plugins
 * used for when a variable is undefined
 * the browser will pass the undefined 

== typecasts
* “/”==/ - calls toString()
* === - checking same type

wrapper function
* use strict
* garbage collection is more active
* if you don't use to string objects become polluted language becomes loose

plugin name is the class name
all vars in the feeds

plugins
* plugins have a visual change

selectors
* inside the core there is a timer poke
* queue of an array of selectors of everything in the page

wet 3.1 sites
* takes more than 10 seconds to load page

3 states a plugin will have
* state before js has reached plugin
* init stage
* finale

timerpoke
* as code is executing and reading it stores the item in a queue
* makes sure whatever plugins are needed get included in the DOM

feeder class
* has init state

document
* wb. Stores the document plugin

pattern naming
* all encapsulated 

jsperf.com
* bunch of JavaScript guys
* bench marks JavaScript code

var
* convention that we use all the time
* old way was:
```js
var mario=””;
var mario=””;
```
* causes an error
* now:
```js
var mario = “ “,
	mario2=” “;
```

ATS
* lexical parser of the language

after plugin code is initialized then uses below line to:
```js
$document.on( "timerpoke.wb " + initEvent, selector, init);
```

**Comment by hsrudnicki** [comment]
Can be this issue closed or otherwise?

**Comment by LaurentGoderre** [comment]
Not sure what the purpose of this issue is. Closing. Please reopen if still needed
