### ISSUE TITLE
Field values set using JS get wiped out by wb-frmvld when the input it wrapped in a label

### ISSUE THREAD

**Issue by mmouchet** [wet-boew/wet-boew#5648]
I've found a bug in the Form Validation plugin which is causing field values which are being set using JS on page load to get wiped out.

This was found on a feedback form we are working on which has a "name", "email", and "remember me" checkbox whose values are saved in cookies if the "remember me" is checked off by the user. On the window.onload event we are reading the cookies and setting the name, email and checkbox values of the form.

This only appears to happen when the input fields are wrapped in the label.

I've put together a simple snippet to show the bug:

```html
<div class="wb-frmvld">
	<form action="#" method="POST" name="feedback">
	      <div class="form-group">
		        <label for="name"><span class="field-name">Name</span>:
	        		<input class="form-control" type="text" name="name" id="name" />
	        	</label>
	        </div>
	        <div class="checkbox">
	            <label for="remember">Remember<input type="checkbox" name="remember" id="remember" value="Y"/></label>
	        </div>
	</form>
</div>

<script>
	document.getElementById("name").value = "TEST";
	document.getElementById("remember").checked = true;
</script>
```

When you run the code within a WET template the fields will be set by the JS and then wiped out within a second or two.

I've setup another example where the input fields are not wrapped in the label and works as expected

```html
<div class="wb-frmvld">
	<form action="#" method="POST" name="feedback">
        <div class="form-group">
	        <label for="name"><span class="field-name">Name</span>:</label>
        	<input class="form-control" type="text" name="name" id="name" />
        </div>
        <div class="checkbox">
            <label for="remember">Remember</label>
            <input type="checkbox" name="remember" id="remember" value="Y"/>
        </div>
	</form>
</div>

<script>
	document.getElementById("name").value = "TEST";
	document.getElementById("remember").checked = true;
</script>
```

**Comment by hsrudnicki** [comment]
Can be this issue closed?

**Comment by mmouchet** [comment]
Yes, the issue can be closed.

Thank you
Mike
