### ISSUE TITLE
Conditionally include oldIIE Sass sections

### ISSUE THREAD

**Issue by nschonni** [wet-boew/wet-boew#5651]
This was done in v3, but wasn't ported over for v4.
The basic approach would be to add an `$oldIE: true` in src/base/ie8-wet-boew.scss, and then use conditional blocks around our oldIE hacks so they are only emitted in the ie8 sheet.

The reverse could also be used to hide some of the modern browser CSS, but that is mostly handled by Autoprefixer already

**Comment by hsrudnicki** [comment]
Can be this issue closed?

**Comment by LaurentGoderre** [comment]
These case seem limited to GCWU and and OGPL so closing.
