### ISSUE TITLE
The validation isn't activating

### ISSUE THREAD

**Issue by pastlifeuknow** [wet-boew/wet-boew#5667]
<strong>What I've got</strong> 
<ul>
<li>Using database to decide whether or not specific fields are needed for the form.</li> <li>Populating the required fields with rules based on type of input. </li>

<li>After that returning the div that contains the form back to template which has the validation loaded.</li> 

<li>All fields have labels with span class="field-name" and the encompassing div has class="wet-boew-formvalid" . </li>
</ul>
<strong> Problem </strong>
Errors are not displaying inline or above like they should according to form validation:
http://wet-boew.github.io/v3.1-ci/docs/ref/formvalid/formvalid-en.html

<strong> Questions </strong>
<ul>
<li> Would the jquery.mobile.min file failing to load disable validation? </li>
<li> if not would the server side driven fields disable validation? </li>
<li> If not any ideas why its not working? </li>
</ul>

<strong> Thank you very much </strong>

**Comment by hsrudnicki** [comment]
No further discussion, so can be this issue closed?

**Comment by LaurentGoderre** [comment]
Closing since it affects v3.1 only
