### ISSUE TITLE
Configure Grunt tasks to run with newer files only

### ISSUE THREAD

**Issue by Pacoup** [wet-boew/wet-boew#5671]
Any reason this is not implemented right now?

http://stackoverflow.com/questions/16788731/grunt-watch-multiple-files-compile-only-changed
https://github.com/tschaub/grunt-newer

Working on WET code is currently somewhat of a painful affair, with every change requiring a multi-minute build (at least on my not very new computer) because all files are rebuilt, regardless of whether they've changed.

Not sure if there's any hurdles to grunt-newer versus something like Make where you can specify the dependency tree for the compilation order when working with C. Any Node expert here?

**Comment by LaurentGoderre** [comment]
#6514 would address this, now running grunt watch rebuild only the needed section when files are changed

**Comment by Pacoup** [comment]
Right, sounds like a nice solution. I'm not going to implement grunt-newer because I totally forgot about this and now I don't want to try implementing it anymore, haha, so, closing this. Thanks.
