### ISSUE TITLE
Question/Suggestion-Tabbed Interface Flickr

### ISSUE THREAD

**Issue by nrustand92** [wet-boew/wet-boew#5684]
Once a flickr image is clicked & it's in modal mode, should we add previous/next arrows to navigate through the photos?

**Comment by hsrudnicki** [comment]
Can be this issue closed?

**Comment by LaurentGoderre** [comment]
This was not implemented no

**Comment by hsrudnicki** [comment]
Please continue the updates to close this issue

**Comment by hsrudnicki** [comment]
Made "Going Stale" to close this issue if no further response/status update or otherwise? Please update this issue's status, thx

**Comment by hsrudnicki** [comment]
Based on the above, this issue can be closed as resolved or if otherwise (then please update again this issue's status) ? Thank you
