### ISSUE TITLE
Question/Suggestion-Tabbed Interface Youtube

### ISSUE THREAD

**Issue by nrustand92** [wet-boew/wet-boew#5686]
I feel like the Youtube videos thumbnail look too similar to Flickr thumbnails (although they're labeled appropriately).  Should we perhaps add features to the YT thumbnails so it's more obvious they're videos? Like a sideway triangle play icon, or put in the video length like how Youtube does it (see below)?

![wc-screenshot-parkscanadayt-20140708-e](https://cloud.githubusercontent.com/assets/5949078/3513645/d39a4e1a-06c4-11e4-9c8f-e0e990f0bd70.png)
?

**Comment by hsrudnicki** [comment]
Can be this issue closed or otherwise?

**Comment by hsrudnicki** [comment]
Made "Going Stale" and can be closed if no further status updates or otherwise? Please update this issue's status, thx

**Comment by hsrudnicki** [comment]
Closed this issue or if otherwise, please update this issue's status.
