### ISSUE TITLE
Form Validation-Telephone Number

### ISSUE THREAD

**Issue by nrustand92** [wet-boew/wet-boew#5691]
I put the phone number without the dashes & no error message after I clicked "Submit."

http://wet-boew.github.io/wet-boew/demos/formvalid/formvalid-en.html

![wc-screenshot-wetformvalidation-20140708-e](https://cloud.githubusercontent.com/assets/5949078/3515477/388144e4-06d6-11e4-924e-1c9ffdb1ba17.png)

**Comment by hsrudnicki** [comment]
So, can be this issue closed?

**Comment by pjackson28** [comment]
Yes I guess we can. We can consider the format in the label to be a recommendation but not the only accepted method.
