### ISSUE TITLE
Are slidefade and pop transitions working correctly?

### ISSUE THREAD

**Issue by pjackson28** [wet-boew/wet-boew#5696]
@sviens I tried to use the slidefade and pop transitions that are defined in the base CSS and they look like they aren't working properly (unlike fade, slide and slidevert which seem to be working fine). Could you please take a look and see if they are behaving the way they are supposed to? If not, please fix them so they behave as you intended.

**Comment by stephenbe** [comment]
Maybe you guys could add a transition library already made in wet?

http://daneden.github.io/animate.css/

I could make a pull request if you would be interested in adding this animation library into WET

Let me know!

**Comment by thomasgohard** [comment]
@LaurentGoderre what do you think about that library?

**Comment by hsrudnicki** [comment]
@LaurentGoderre @pjackson28 @sviens and others: Are you ready to close this issue?

**Comment by LaurentGoderre** [comment]
I don't think we are ready for this yet

**Comment by hsrudnicki** [comment]
Made "Going Stale" and if this issue's status remains not updated then this issue can be closed or otherwise? Please update this issue's status, thx

**Comment by hsrudnicki** [comment]
@LaurentGoderre and others: Is this still an issue?  Either way, please update this issue' status, whether this issue can be closed as resolved/fixed or otherwise?  Thank you

**Comment by hsrudnicki** [comment]
Is this still an issue? Can be this closed or otherwise? Thank you

**Comment by hsrudnicki** [comment]
Based on the above, this can be closed. If you think about an enhancement or otherwise, please update the status of this again, thank you
