### ISSUE TITLE
jQuery mask on form elements

### ISSUE THREAD

**Issue by cfarquharson** [wet-boew/wet-boew#5709]
Is there something in WET like this?  It's a great way to ensure consistent formatting: http://igorescobar.github.io/jQuery-Mask-Plugin/

**Comment by hsrudnicki** [comment]
Are you ready to close this issue?

**Comment by LaurentGoderre** [comment]
This may be implemented natively as a display feature (instead of changing the input) but I don't think we will be implementing this
