### ISSUE TITLE
Details/summary polyfill (expandable/collapsible content): basic html view

### ISSUE THREAD

**Issue by dfarough** [wet-boew/wet-boew#5712]
@wet-boew/access-working-group The Access working group has flagged an accessibility issue when using the basic html view for this feature.

In this view, there is no easy way to navigate to this content.  the example buttons are converted to text and there is no heading for the content within the expandable text.  This makes it difficult for users of access technology to move to the text within the expanded region without reading through the page sequentially. The button text  can not be tabbed to either.  In this case the basic html view of this page content is much less accessible than the standard view of this content.

There are perhaps 2 options to handle this situation.

1.  when the page is converted to basic html perhaps the expandable content button could be converted to a heading and perhaps placed in the tab order so that a user could tab to it.

2.  ask all content authors to include a heading at the beginning of the content.

**Comment by hsrudnicki** [comment]
No yet written response from @bsouster, but are you ready to close this issue?

**Comment by pjackson28** [comment]
The way to deal with heading visually in a summary element is to apply the equivalent h* class on the summary element. For example:
```html
<summary class="h3"><h3>Heading text</h3></summary>
```

**Comment by pjackson28** [comment]
Also, this is an HTML markup issue and not something that should be fixed with JavaScript. When using details/summary, authors should be determining the appropriate HTML structure that should be applied in addition to details/summary. 

Should this be moved to the styleguide? It isn't a WET issue, it is an overall issue with how to structure you HTML markup on the page (so would exist with or without WET).

**Comment by bsouster** [comment]
@pjackson28 Sorry for the late response. The heading levels within summary have no longer been an issue since we added this to our CSS:

summary h2, summary h3, summary h4, summary h5, summary h6 {
	display: inline;
	vertical-align: middle;
}

**Comment by pjackson28** [comment]
@bsouster Does it work with you custom CSS disabled and using the class approach? The reason we had to rely upon the h* class approach is it was the only way to reliably size the expand/collapse triangle to the heading (which at the same time should address what you were trying to fix with you custom CSS).

**Comment by bsouster** [comment]
It works, but it adds an unnecessary left indent. The lower the heading level, the larger the indent. Ex: h5 has a larger left indent than h2.
![headers](https://cloud.githubusercontent.com/assets/1944744/8602137/87036966-263e-11e5-92d2-83c037a825a4.jpg)

**Comment by pjackson28** [comment]
Thanks for catching that. Actually it looks like the indenting for the h5 is perfect (1.1em) but is not enough for the higher headings. In h1 to h4 it looks like the triangle icon is overflowing the details container to the left (whereas there is no overflow for h5)..

**Comment by pjackson28** [comment]
Will be fixed by PR #6929.

**Comment by pjackson28** [comment]
Note that this will not fix the issue in IE8. We are now at the maximum selector limit for IE8 so we can't do any more targetted fixes for IE8 without creating more IE8 issues.
