### ISSUE TITLE
WET 5: The Web Components Era

### ISSUE THREAD

**Issue by Pacoup** [wet-boew/wet-boew#5725]
Watching the <a href="https://www.youtube.com/watch?v=8OJ7ih8EE7s">Polymer and Web Components change everything you know about Web development</a> presentation from Google I/O 2014, it occurred to me that Web Components could be a boon to the WET.

So, I'm throwing this idea out there, how about making WET 5 a complete reimagining of the wet-boew framework built entirely on the idea of Web Components.

A few ideas:

**Highly interactive**
It should leverage technologies like Polymer to produce highly interactive, 60 fps animated interfaces.

**Automatic Accessibility**
New elements can be created with Web Components which completely integrate and abstract all of the ARIA and other means of accessibility for the implementer. For example, WET 5 could add ARIA to Bootstrap without needing to change how Bootstrap is used by implementers, etc.

**Interchangeable Components**
The new framework should try to leverage existing framework conventions to make WET more approachable, e.g., Google has:
```HTML
<google-map map="{{map}}"></google-map>
<google-map-directions map="{{map}}"
    startAddress="San Francisco" endAddress="Mountain View">
</google-map-directions>
```

WET would have:
```HTML
<wb-map map="{{map}}"></wb-map>
<wb-map-directions map="{{map}}"
    startAddress="Ottawa" endAddress="Montreal">
</wb-map-directions>
```

**Future Future**
Since Web Components are still very new, this version of wet-boew would be a future future project. As in an experiment with the assumption that an eventual version of IE and everyone else will support Web Components or that polyfills would fill in the gap with support from a bigger project, e.g. <a href="http://www.polymer-project.org/resources/compatibility.html">Polymer's polyfills</a>.

**Comment by hsrudnicki** [comment]
Are you ready to close this issue or otherwise?

**Comment by Pacoup** [comment]
Not sure. I believe this was discussed extensively at the last CodeFest. I'm not aware of any final decision for next-gen WxT, but this is probably out of date now. @pjackson28 ?

**Comment by pjackson28** [comment]
No decisions have been made as we are currently focused on Web Renewal. What is everyone's thoughts considering these proposed approaches considering where we are going with Web Renewal?

**Comment by LaurentGoderre** [comment]
I would prefer to not go there until allthe major browser support it so we are not solely relying on polyfill. There are steps we can take to move towards it but my opinion is that this is premature to build on just yet.

**Comment by Pacoup** [comment]
Sounds good. I will close this in the meantime.
