### ISSUE TITLE
Migration Guide from 3.1.x to 4.0.x

### ISSUE THREAD

**Issue by at88mph** [wet-boew/wet-boew#5729]
Hi there,

We're in the process for planning a migration from 3.1.12 to 4.0.3 this summer.  Working with version 4.0 is wonderful and I managed to recreate a few of our pages, but is there a migration guide available that would make the transition more friendly?

Many thanks,
Dustin

**Comment by hsrudnicki** [comment]
Can be this issue closed?

**Comment by at88mph** [comment]
Probably, thanks.  I suspect everyone will need to figure out translating the different css combinations on their own for the most part.

Regards,
Dustin


Dustin N. Jenkins 
Tel/Tél: 250.363.3101 | facsimile/télécopieur: (250) 363-0045 | Dustin.Jenkins@nrc-cnrc.gc.ca 
National Research Council Canada | 5071 West Saanich Rd, Victoria BC. V9E 2E7 
Conseil national de recherches Canada | 5071, ch. West Saanich, Victoria (C.-B) V9E 2E7 
Government of Canada | Gouvernement du Canada

**Comment by pjackson28** [comment]
Wasn't there work done on creating a guide?

@bsouster Didn't your area create some guidance?

**Comment by bsouster** [comment]
I can't find the original issue for this, but here's [what we made at CIC](http://www.cic.gc.ca/wet4-css-classes.xlsx).

**Comment by hsrudnicki** [comment]
Based on the above, this issue can be closed as well, and additionally labeled "Made Stale" since no further status update. If you strongly think otherwise please let it know! Thank you
