### ISSUE TITLE
Feeds: Working example download size is far too big

### ISSUE THREAD

**Issue by pjackson28** [wet-boew/wet-boew#5736]
@masterbee The Feeds working example page is way beyond the 500kb maximum. It is ringing in at 4.3Mb with 141 requests, a 1:33 load time and a 5.8s onload. This needs to be fixed as it is causing major performance issues, particularly on mobile and is a major problem overall.

Correction: It is actually much worse than originally reported as some of it was cached originally.

**Comment by hsrudnicki** [comment]
Are you ready to close this issue?

**Comment by LaurentGoderre** [comment]
Not sure yet

**Comment by LaurentGoderre** [comment]
This was fixed by #6797
