### ISSUE TITLE
Geomap zoom out control fonctionality reusable?

### ISSUE THREAD

**Issue by amoriset** [wet-boew/wet-boew#5758]
Hi, I would like to know if it's doable to take the functionality from the zoom out control populated from the map (left top corner) and use it as a link to the popupinfo when zoomed in like shown in my screenshot? We are using Wet 3.1

![geomap-zoom-out](https://cloud.githubusercontent.com/assets/4672172/3663967/503288a2-11d8-11e4-9c26-ef3df5836c2c.jpg)

Thanks!

**Comment by hsrudnicki** [comment]
@amoriset @pjackson28 and others: Can be this issue closed?

**Comment by LaurentGoderre** [comment]
Closing since the original question was answered
