### ISSUE TITLE
Look at Commit Please for commit message validation

### ISSUE THREAD

**Issue by nschonni** [wet-boew/wet-boew#5761]
See https://www.npmjs.org/package/commitplease
It adds a githook during the NPM install to enforce commit message formats. This won't catch stuff for people that never install the NPM packages, but that would be another check to add.

**Comment by hsrudnicki** [comment]
@nschonni @EricDunsworth : Can be this issue closed?

**Comment by LaurentGoderre** [comment]
No, we could still implement, potentially

**Comment by hsrudnicki** [comment]
Just labeled "Going Stale" but based on last comment, this issue remains still open!

**Comment by LaurentGoderre** [comment]
This is not likely to be implemented anymore

**Comment by hsrudnicki** [comment]
Thank you for last comment/update, and this issue can be closed.
