### ISSUE TITLE
Incorrect font sizes are applied to Form Validation Examples for Fav Pets and Citizenship Status

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew#5797]
Incorrect font sizes are applied to Form Validation Examples for Fav Pets and Citizenship Status

http://wet-boew.github.io/v4.0-ci/demos/formvalid/formvalid-en.html#lname1

Assuming the correct size:
![screen shot 2014-07-25 at 2 58 44 pm](https://cloud.githubusercontent.com/assets/1994838/3706853/c33126cc-142d-11e4-97b4-80cde98a855d.png)

And the incorrect size:
![screen shot 2014-07-25 at 2 58 38 pm](https://cloud.githubusercontent.com/assets/1994838/3706857/c9ffb55e-142d-11e4-8724-c21619a1ca2b.png)

**Comment by claudielarouche** [comment]
I've never actually done this before so might need some help but if I make the following modification to the code in _base.scss located in \wet-boew\src\base\bootstrap-overrides, would that work for you?

<pre><code>
legend {
    border-top: 1px solid #e5e5e5;
    border-bottom: 0;
    float: left;
}
fieldset {
    padding-top: 10px;
    &:first-child {
        border-top: 0;
    }
}
.fixLegend{
    border: none;
    font-size: $font-size-base;
    font-weight: bold;
    margin-bottom: 5px;
}
</pre></code>
The border top would be attached to the legend as it was before, and we have a new class to make the legend appear the same size as other labels when necessary (I took the name <code>fixLegend</code> from another department's website but <code>chkbxrdio-grp</code> works just fine and I don't mind a <code>margin-bottom</code> of <code>0</code> if that's better).

**Comment by LaurentGoderre** [comment]
It should probably be a different class name than `fixLegend`

**Comment by RobJohnston** [comment]
A similar issue was also filed in bootstrap and was closed without being resolved:  https://github.com/twbs/bootstrap/issues/16051.  No upstream fix coming for this.

**Comment by thomasgohard** [comment]
The `border` should be on the `fieldset`, not the `legend`, as the `fieldset` can be used without a `legend`.

I've modified the CSS to implement a solution. You just need to apply the class `chkbxrdio-grp` to the `fieldset` containing the group of checkboxes or radio buttons.

**Comment by hsrudnicki** [comment]
Are you ready to close this styling issue?

**Comment by claudielarouche** [comment]
Not sure if this is common practice or not, but is it ok to wait until the pull request has been merged, so that it can be tested?

https://github.com/wet-boew/wet-boew/pull/6848

By the way, thank you so much everyone for your work on this!

**Comment by StephenOTT** [comment]
Just add in the commit message of the pull request `closes #5797' and if the pull request is accepted when it merges it will close this issue.
