### ISSUE TITLE
How I can get a templete for DND Web site in .aspx

### ISSUE THREAD

**Issue by mdhindsa2014** [wet-boew/wet-boew#5802]

**Comment by RobJohnston** [comment]
@GarthMartin asked me for a copy of my master page so I threw something together and posted an example here:  https://github.com/RobJohnston/Master-Page-Demo.  

There are so many ways to do this, and so many decisions to be made along the way that could fork into something easier or nastier down the road, but this works well enough and  other can use as a starting point if they wish.

I think that once VS 2015 comes out, with its support for npm and grunt and all that, there will be an easier solution for all this.

**Comment by LaurentGoderre** [comment]
@RobJohnston with nuget you probably don't need npm or grunt for .NET. We would only need to maintain a package from nuget.

**Comment by RobJohnston** [comment]
Yes, I was just reading #2002 about that very subject.

**Comment by hsrudnicki** [comment]
Are you ready to close this issue or otherwise?

**Comment by hsrudnicki** [comment]
Close this issue just labeled as "Going Stale" or otherwise? Please update this issue's status, thx

**Comment by hsrudnicki** [comment]
Based on the above discussion and no more status updated, this issue can be closed.
