### ISSUE TITLE
Don't rely on whitespace in html / inline-block in site search (WET 4.0.4)

### ISSUE THREAD

**Issue by stockholmux** [wet-boew/wet-boew#5825]
I'm re-implementing parts of WET and my minification caused a difficult to track down issue with the site search. This is almost exactly as it comes from the kit, except for the line breaking in the html code for `#wb-srch`:
```html
<section id="wb-srch" class="col-md-4 visible-md visible-lg"><h2>Search</h2><form action="https://google.ca/search" method="get" role="search" class="form-inline"><div class="form-group"><label for="wb-srch-q">Search website</label><input id="wb-srch-q" name="q" type="search" value="" size="27" maxlength="150" class="form-control"><input type="hidden" name="q" value="site:wet-boew.github.io OR site:github.com/wet-boew/"></div><button type="submit" id="wb-srch-sub" class="btn btn-default">Search</button></form></section>
```
My site:
![screen shot 2014-07-31 at 9 58 19 am](https://cloud.githubusercontent.com/assets/1152927/3766249/2a67aaf2-18c3-11e4-9aa6-482aca503521.png)

Wet-boew site:
![screen shot 2014-07-31 at 10 11 00 am](https://cloud.githubusercontent.com/assets/1152927/3766443/eba5b424-18c4-11e4-8c81-031fee037d69.png)

Wouldn't it be better to rely on margins to achieve this spacing instead of linebreaks/spacing? Seems more fool proof.

**Comment by hsrudnicki** [comment]
Can be this issue closed?

**Comment by LaurentGoderre** [comment]
I believe we can close this?
