### ISSUE TITLE
information about data tables sorting

### ISSUE THREAD

**Issue by pliz22** [wet-boew/wet-boew#5843]
I am using the data tables, and one of my columns is using data-ajax-replace to change the content for every row in the column.
i've tried many ways to sort this column but it never sorts, it does not change.
so my question is mainly, does data table keep a cache or sort based on the source, or based on what the DOM looks like at this moment in time.
here, for example, is what is in the column before AJAX and it is sorted from 22 to 25:
```html
<td><div data-ajax-replace="linkscount.aspx?ssd=1234&countid=22"><span class="fa fa-spinner fa-spin"></span></div></td>
```
```html
<td><div data-ajax-replace="linkscount.aspx?ssd=1234&countid=25"><span class="fa fa-spinner fa-spin"></span></div></td>
```
here, for example, is what is in the column after AJAX, and no matter that i click on the sort button, it is always sorted from 22 to 25 (or, it never sorts, it just remains the same):
```html
<td><span class="wb-inv">0</span><a href="links.aspx?catid=22">0 links</a></td>
```
```html
<td><span class="wb-inv">14</span><a href="links.aspx?catid=25">14 links</a></td>
```
what it should be doing is moving the 14 up and the 0 down, and or the 0 up and the 14 down.

**Comment by hsrudnicki** [comment]
Can be this issue closed?

**Comment by pliz22** [comment]
Yes 

Sent from Yahoo Mail on Android
