### ISSUE TITLE
IE9 and Department Signature line

### ISSUE THREAD

**Issue by wilkk5** [wet-boew/wet-boew#5870]
Hello,

Using Version 4.04 Intranet theme with Win 7 / IE9.  When I display the default WET pages (eg content-secmenu-en.html), the entire Department Signature (ie Government of Canada) line does not appear.  If I use F12 in IE and change compatability mode to IE8, it does appear.  Also, if I open the same page directly off my drive (s:/ drive vice http), it is fine.  Any suggestions?

Also, has banner_source.png (the Intranet background image) disappeared for v4?

Thanks,
Karen

**Comment by hsrudnicki** [comment]
@wilkk5 @LaurentGoderre : Can be this issue closed?

**Comment by hsrudnicki** [comment]
Due to no further discussion/status updates, this issue can be closed, and additionally labeled "Going Stale"
