### ISSUE TITLE
Have Closed Captioning Appear by Default or at a Specific Time

### ISSUE THREAD

**Issue by bsouster** [wet-boew/wet-boew#5899]
One of our web advisors has brought a semi-frequent issue, and solution ideas, to our attention (quoted below). Is it possible to put in one of these solutions? Any other ideas?

"For videos that have audio in a language that is not the language of the page (e.g., an interview conducted in English in the French version of the video posted to the French language page; re-enacting a historical event where characters are not speaking an official language), users have reported frustration in that they cannot understand the audio. 

"While they can click the "CC" button to activate the subtitles, that might not be apparent. Allowing for the closed captions to be displayed by default when the video starts, or activated at a certain time, would better fulfill official language and accessibility obligations.

"An alternative is open captioning overlaid on top of the video, but TBS has discouraged them. Voice-overs can be done, but they increase production costs. For both of these options, it is more difficult to correct an error than with an XML closed captioning file. Therefore, having more control over when closed captioning is displayed is a better option."

**Comment by hsrudnicki** [comment]
@bsouster and others: Can be this issue closed?

**Comment by bsouster** [comment]
@LaurentGoderre While @pjackson28 solution seems sufficient, maybe just an example in the documentation would help a lot of people like myself using the plugin.

**Comment by LaurentGoderre** [comment]
This is not an option yet though

**Comment by hsrudnicki** [comment]
Made "Going Stale" and closed this issue, if you think otherwise please respond/update this issue's status again, thx

**Comment by hsrudnicki** [comment]
Is this above still an issue, waiting for a fix, including the documentation, see 5574 issue, based on last comments from @bsouster, @LaurentGoderre ?  Either way, please update this issue's status, whether this issue can be closed as resolved/fixed or if otherwise?  Thank you
