### ISSUE TITLE
The Future of CSS Animations in the Toolkit

### ISSUE THREAD

**Issue by sviens** [wet-boew/wet-boew#5908]
The Toolkit is looking to take user interface animations to the next level!

What [Toolkit features (demos)](http://wet-boew.github.io/wet-boew/demos/index-en.html) would benefit from CSS animations (transitions, transforms, and key-frame animations)?

What approaches would be of greatest benefit to the user interface as it relates to creating an enhanced experience for the user?

### Learning resources
- [CSS3 Transitions, Transforms, Animation, Filters and more!](http://css3.bradshawenterprises.com/)
- [Using CSS transitions (MDN)](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Using_CSS_transitions)
- [Using CSS transforms (MDN)](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Using_CSS_transforms)
- [Using CSS animations (MDN)](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Using_CSS_animations)

### Performance matters!
- [High Performance Animations](http://www.html5rocks.com/en/tutorials/speed/high-performance-animations/)

### Advanced techniques and tools
- [CSS easing animation tool](http://matthewlein.com/ceaser/)
- [Animate.css](http://daneden.github.io/animate.css/)
- [GSAP: The new standard for HTML5 animation](http://www.greensock.com/gsap-js/)

**Comment by hsrudnicki** [comment]
Are you ready to close this issue?

**Comment by hsrudnicki** [comment]
Due to no further discussion/status updates in implementation of the experimental technology, made "Going Stale" and closed this issue or if otherwise, please respond/update this issue's status again,
