### ISSUE TITLE
White space-geomap-legend

### ISSUE THREAD

**Issue by nrustand92** [wet-boew/wet-boew#5928]
Could we perhaps have more space between one legend category to the next?
E.g., the ATOM title is equally close to both the light blue & purple boxes

![image](https://cloud.githubusercontent.com/assets/5949078/3936138/e1c4bd08-249d-11e4-9873-1093204eaf84.png)

**Comment by LaurentGoderre** [comment]
@nrustand92 please reopen if it's still an issue
