### ISSUE TITLE
Adding to Documentation

### ISSUE THREAD

**Issue by joshdevries** [wet-boew/wet-boew#5937]
I was looking through the source files of the wet folder and I do not see where the documentation files are generated from. I think that if you want the community to help with the documentation that it would good idea to have a doc directory that we can add new help content to. we could then send a pull request to have the changes added. 

If this already exists, please point me in the right direction.

**Comment by hsrudnicki** [comment]
@joshdevries and others: Please update this issue's status whether this issue can be closed or otherwise? Thank you

**Comment by hsrudnicki** [comment]
Made "Going Stale" and closed this issue as resolved based on last discussion comments.
