### ISSUE TITLE
Heuristic Evaluation - Canada.ca's Gallery Layouts

### ISSUE THREAD

**Issue by burgvan** [wet-boew/wet-boew#5945]
Please perform a heuristic review of the following pages:  <a href="http://www.canada.ca/en/mobile/index.html" target="_blank">Mobile Centre</a> and <a href="http://www.canada.ca/en/social/index.html" target="_blank">Social Media Gallery</a>
If you’re using Internet Explorer, please make sure it is up-to-date.

The questions represent a quick and brief heuristics evaluation for both pages. The purpose of this evaluation is to provide immediate usability feedback, proper implementation and developmental guidance for the gallery layout.

For more instructions, go to the following posted issues:
<a href="https://github.com/wet-boew/GCWeb/issues/746">Social Media Gallery heuristic evaluation</a>
<a href="https://github.com/wet-boew/GCWeb/issues/747">Mobile Centre heuristic evaluation</a>

Thank you and your feedback will be greatly appreciated!

**Comment by hsrudnicki** [comment]
@pjackson28 @burgvan : Are you ready to close this issue?

**Comment by pjackson28** [comment]
Yes as it is a GCWeb issue and not a WET core issue.
