### ISSUE TITLE
Hover slide transition demo causes flickering/jumping

### ISSUE THREAD

**Issue by andre-d** [wet-boew/wet-boew#5965]
Demo here: http://codepen.io/anon/pen/HnLfk

Using a translate transition on hover can cause the element to become non-hovered from the translate and flicker back and forth between hover and non hover as it jumps back and forth.  To avoid this, wrap the element in an inline-block element and watch the hover of that element and translate the child

**Comment by hsrudnicki** [comment]
Can be this issue closed?

**Comment by hsrudnicki** [comment]
Made "Going Stale" and closed this issue based on the above or if otherwise then please update this issue's status again, thx

**Comment by hsrudnicki** [comment]
Is this still an issue to be resolved in the 4.0 Backlog or otherwise?  Please update the status of this for the current year, thank you

**Comment by masterbee** [comment]
closed since abandoned by owner and could not replicate issue in current build
