### ISSUE TITLE
mega menu height and ie8 and ff

### ISSUE THREAD

**Issue by pliz22** [wet-boew/wet-boew#5973]
I know, sorry, but my clients are still on ie8.  I found a fix for this with firefox.
If the mega menu is very long (longer than the screen) then you cannot see the rest of the menu and you cannot scroll past the bottom of the page body.
In Firefox, my fix for this is to add a style="max-height:3000px" to the pop-up sub-menu UL.
Such as, 
```
<div class="row">
<ul class="list-inline menu" role="menubar">
    <li class=""><a class="item wb-navcurr" href="#" tabindex="0" aria-posinset="1" aria-setsize="5" role="menuitem" aria-haspopup="true"></a>
    <ul class="sm list-inline" role="menu" style="max-height:3000px;" aria-expanded="false" aria-hidden="true"></ul>
     </li>
```
But in ie8 (as usual) this doesn't work.  I cannot scroll further than the body.
I am wondering if anyone has any quick ideas of where I can stick an inline-style to fix this for ie8?
I tried adding max-height to the <div container> but that really does create a page that is 3000px high.  That's not really what I want.  The style on the pop-up sub-menu itself is not working.
Any other locations this might work?

**Comment by hsrudnicki** [comment]
@pliz22 @LaurentGoderre : Are you ready to close this issue or otherwise?

**Comment by pliz22** [comment]
Yes 

Sent from Yahoo Mail on Android
