### ISSUE TITLE
disabled button colours not passing contrast

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/wet-boew#5979]
Moving this from https://github.com/wet-boew/GCWeb/issues/323. Original issue opened by @cfarquharson. 

> It looks like the opacity is set to .65.  This may be too much for the disabled stated cuz the buttons aren't that dark to begin with.  Also, per #322 the size is weird of btn-primary
![button-disabled](https://f.cloud.github.com/assets/2319199/1674655/82aa580a-5cfc-11e3-90b1-1c4b7e4b493b.PNG)

**Comment by LaurentGoderre** [comment]
Is this still an issue?

**Comment by hsrudnicki** [comment]
@shawnthompson @pjackson28 @thomasgohard : No answer to @LaurentGoderre question, so again, are you ready to close this issue or otherwise?

**Comment by pjackson28** [comment]
Note that WCAG 2.0 does not have any contrast requirements for disabled components:

"Incidental: Text or images of text that are part of an inactive user interface component, that are pure decoration, that are not visible to anyone, or that are part of a picture that contains significant other visual content, have no contrast requirement."

So I am closing this issue as disabled buttons are not required to pass contrast and doing so could decrease usability by making an unclickable button look clickable.
