### ISSUE TITLE
jQuery Timeline script

### ISSUE THREAD

**Issue by crochefort** [wet-boew/wet-boew#5981]
Good day everyone, I notice that the style-tab-3 from the TAB script has not been port to WET 4.

So I did some research and found a script that might be a good addition.

http://www.csslab.cl/2011/08/18/jquery-timelinr/

I just want your input on how much effort it would take to bring it compliant. 

On my DEV server I start working on it but when i'm resizing the screen to get a mobile view the script dont resize correctly so it need some work on it.

@pjackson28  As you request :) thanks!

**Comment by hsrudnicki** [comment]
@crochefort @thomasgohard @pjackson28 : Can be this issue closed?

**Comment by thomasgohard** [comment]
No. It is presently in discussion.

**Comment by hsrudnicki** [comment]
Based on the above merged PR, and no further discussion/status updates, this issue made "Going Stale" and closed or if otherwise, please update again, thx
