### ISSUE TITLE
Look at Discourse for community discussion

### ISSUE THREAD

**Issue by nschonni** [wet-boew/wet-boew#6009]
http://www.discourse.org/ https://github.com/discourse/discourse is an open source project for creating a discussion site. It is built by some of the people behind StackOverflow, and brings some of the same expert system approach to a forum.

Pros:
- Free (except hosting) and Open Source
- No requirement for GitHub sign up as it allows social or u/p logins which may be easier to get some people setup with
- Multilingual

Cons:
- Hosting costs or their new PaaS cost
- Just hit V1
- Probably needs some A11y review, but their has been interest from the community to tackle that since higher Ed orgs have started to play with it in the US
- No support for old(er) IE, but Github is heading that way too

**Comment by hsrudnicki** [comment]
Are you ready to close this issue?

**Comment by LaurentGoderre** [comment]
We can look at it at another time
