### ISSUE TITLE
Code Sprint - Remote sessions 

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/wet-boew#6016]
I'm looking to get code sprints started Montreal to remotely work with the ones going on in the NCR.

Anyone interested in attending let me know at shawn.thompson@servicecanada.gc.ca.

How about you, @crichard?

Any ideas on how we can communicate would be good. IRC? Google hangout? Teleconference?

**Comment by LaurentGoderre** [comment]
Can I close this?

**Comment by shawnthompson** [comment]
Yeah I guess so.... They will resume in the fall.
