### ISSUE TITLE
Nav current: Turning off the class in the menu

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/wet-boew#6030]
Is there a way to turn off the menu highlighting for nav current on a certain page if you don't want it to show up for some reason?

cc/ @masterbee

**Comment by hsrudnicki** [comment]
Can be this issue closed or otherwise?

**Comment by pjackson28** [comment]
Yes, an explanation as to the navcurrent behaviour was provided. There doesn't seem to be a need to turn off this functionality as it can be controlled through the breadcrumb links. Closing and can be reopened if there is a solid use case identified that can't be met through breadcrumb link management.
