### ISSUE TITLE
Multimedia Player - Add play icon overlay

### ISSUE THREAD

**Issue by Wenifred** [wet-boew/wet-boew#6035]
Is there a way you can incorporate a play button icon in the middle of the display area?  The YouTube player has one, and when you mouse over it goes red.  Could the multimedia player have the same thing or something like it?

Maybe show the play button as white with 50% opacity.  When you hover over the display area the background has an overlay of black with 50% opacity with the play button in the middle at 100% white.  Just an idea...

**Comment by LaurentGoderre** [comment]
This was implemented a while ago
