### ISSUE TITLE
Person type and key properties question

### ISSUE THREAD

**Issue by rubinahaddad** [wet-boew/wet-boew#6043]
My team was having a discussion about the person type, and we tested our structure (with Google's Structured Data Testing Tool), but didn't use email, and it still passed. In the guide it says that name and email are the min key properties, but most of the time the person type is usually present without email. Is it a mistake in the guide? 

https://github.com/wet-boew/wet-boew/wiki/GC-Semantic-Web-Implementation-Guide

"Person [schema.org]

The Person type is intended to describe an individual. It is extendable for biographies, relationships and additional properties as described by schema.org.
Key properties

- name
- email"

**Comment by LaurentGoderre** [comment]
Can we close this?

**Comment by chrismajewski** [comment]
We probably can, this is being defined in Kristina's Canada.ca Metadata Application Profile which aligns with the demo I ran at the last CodeFest.
