### ISSUE TITLE
Multimedia player (3.1 & 4.x) + IE (9, 10, 11)

### ISSUE THREAD

**Issue by lucas-hay** [wet-boew/wet-boew#6052]
In IE 9, 10 and 11, the multimedia player (3.1 and 4.x) has an issue when a video plays to the end.

Upon ending, you have to click play twice to get the video to play again.

**Comment by LaurentGoderre** [comment]
@lucas-hay IE seems to really mess up it's implementation of the Media API but I found a simple fix for this. It should be included in next version.
