### ISSUE TITLE
Datepicker (polyfill) - Same Month Date Range Issue

### ISSUE THREAD

**Issue by iballant** [wet-boew/wet-boew#6068]
Hi,

The datepicker polyfill doesn't properly select the correct date range in the calendar when the "min" & "max" are within the same month. (all dates are selectable within that month instead of only the dates from "min" to "max").

For example:
when a date range is set with a range from "2013-03-10" to "2013-03-27" using the html
`<input class="form-control" type="date" id="startdate" name="startdate" min="2013-03-10" max="2013-03-27" />`

We get:
![datepickerrangeissue](https://cloud.githubusercontent.com/assets/8861142/4356691/ec69b048-425b-11e4-92c1-1d8e87dcdf2d.png)
(which is incorrect since we can select days 1 to 9 and 28 to 31)

Updating the datepicker.js 
 ```
...
addLinksToCalendar = function( fieldId, year, month, $days ) {
		var field = document.getElementById( fieldId ),
			minDate = field.getAttribute( "min" ),
			maxDate = field.getAttribute( "max" ),
			fromDateISO = wb.date.fromDateISO,
			len = $days.length,
			lowLimit, highLimit, minDay, maxDay, index, day;

		minDate = fromDateISO( ( minDate ? minDate : "1800-01-01" ) );
		minDay = minDate.getDate() - 1;
		maxDate = fromDateISO( ( maxDate ? maxDate : "2100-01-01" ) );
		maxDay = maxDate.getDate();

		lowLimit = ( year === minDate.getFullYear() && month === minDate.getMonth() );
		highLimit = ( year === maxDate.getFullYear() && month === maxDate.getMonth() );

		for ( index = 0; index !== len; index += 1 ) {
			if ( ( !lowLimit && !highLimit ) || ( lowLimit && index >= minDay && !highLimit ) || ( lowLimit && highLimit && index >= minDay  && index < maxDay) || ( highLimit && index < maxDay && !lowLimit) ) {
				day = $days[ index ];
				day.innerHTML = "<a href='javascript:;' tabindex='-1'>" +
					day.getElementsByTagName( "div" )[ 0 ].innerHTML + "</a>";
			}
		}

		$days.find( "a" ).eq( 0 ).attr( "tabindex", "0" );
	},
...
 ```
Changed:
if ( ( !lowLimit && !highLimit ) || ( lowLimit && index >= minDay ) || ( highLimit && index < maxDay ) ) 
To:
if ( ( !lowLimit && !highLimit ) || ( lowLimit && index >= minDay **&& !highLimit** ) || **( lowLimit && highLimit && index >= minDay  && index < maxDay)** || ( highLimit && index < maxDay **&& !lowLimit**) )

(*or in datepicker.min.js:*
`(!g&&!h||g&&k>=i&&!h||g&&h&&k>=i&&j>k||h&&j>k&&!g)`
)

With this change we now get the expected result:
![datepickerrangefixed](https://cloud.githubusercontent.com/assets/8861142/4356909/0694b42a-425e-11e4-8e2b-cfbd8e733e01.png)
(only days 10 to 27 are selectable)

Extra Info:
- Tried using WET 4.0.4 & 4.0.5
- issue tested in IE 8.0 and FF 31.0
- the issue can be reproduced using the datepicker working example by changing the min & max value in the html code.

Thanks!
Ian.

**Comment by hsrudnicki** [comment]
Are you ready to close this issue?

**Comment by LaurentGoderre** [comment]
This will be addressed by the new date picker

**Comment by rlambert27** [comment]
Hi @pjackson28 or @thomasgohard, any idea when the new date picker will be ready? I spoke with Ian today and this needs to be resolved, it's a pretty simple bug to fix. If the new date picker does not have a scheduled release date then I'll go ahead submit a PR for this issue. Let me know, thanks!

**Comment by pjackson28** [comment]
That will have been answered by @masterbee as his group has taken over responsibility for that work.

**Comment by LaurentGoderre** [comment]
The work is almost done, jut need the unit test from being finished to guarantee nothing breaks

https://github.com/LaurentGoderre/wet-boew/tree/refactor-calendar

**Comment by hsrudnicki** [comment]
Based on the above, this issue had been labeled "Going Stale" and closed as resolved/fixed or if otherwise then please update again the issue's status, thank you.

**Comment by rlambert27** [comment]
Hi @LaurentGoderre any news on when the new date picker will arrive?

**Comment by TimCadieux** [comment]
I assume this is still an issue as it appears to be occurring for me as well?

**Comment by LaurentGoderre** [comment]
@TimCadieux which version of WET?

**Comment by TimCadieux** [comment]
Confirm.   * v4.0.23 - 2016-11-18

Just noticed 4.024 is available..will give that a try

**Comment by TimCadieux** [comment]
Ok, so i just updated to 4.0.24.  It still occurs.  Whichever plugin is
given a MAX date last, is the one that works.

**Comment by LaurentGoderre** [comment]
@TimCadieux Can you expand on that?

**Comment by TimCadieux** [comment]
Hmm, let me get back to you on this.  I rebooted overnight and today it *seems* to be working..so maybe some files were cached.
