### ISSUE TITLE
wb-charts and apostrophe

### ISSUE THREAD

**Issue by pliz22** [wet-boew/wet-boew#6079]
here is the result of wb-chart on something with a caption with apostrophe:
```
<div style="width: 100%; padding: 0px; position: relative;" role="img" aria-label="Résultats cumulatifs jusqu" à="" l'âge="" de="" 60="" -="" graphique.="" plus="" détails="" dans="" le="" tableau="" suivant.'style="height:250px; width:846px"><canvas style="direction: ltr; position: absolute; left: 0px; top: 0px;" class="flot-base"></canvas></div>
```
i tried three ways
```
Résultats cumulatifs jusqu'à l'âge de 60
Résultats cumulatifs jusqu&apos;à l&apos;âge de 60
Résultats cumulatifs jusqu&amp;apos;à l&amp;apos;âge de 60
```
i also tried in my code to htmlencode and urlencode it but the result is always the same

**Comment by LaurentGoderre** [comment]
Is this still an issue?

**Comment by hsrudnicki** [comment]
Can be this issue closed?

**Comment by pliz22** [comment]
Yes 

Sent from Yahoo Mail on Android

**Comment by hsrudnicki** [comment]
@LaurentGoderre  and others: Is this still an issue? Please update again the status of this, whether this can be closed or otherwise, thank you

**Comment by pliz22** [comment]
Can be closed 

Sent from Yahoo Mail on Android 
 
  On Tue, Aug 16, 2016 at 3:16 PM, Hanna S Rudnicki<notifications@github.com> wrote:   
@LaurentGoderre and others: Is this still an issue? Please update again the status of this, whether this can be closed or otherwise, thank you

**Comment by hsrudnicki** [comment]
Based on the above, this can be closed as resolved. If you think otherwise, please update the status of this again, thank you
