### ISSUE TITLE
Table validator: <tfoot> elements getting moved around in HTML results

### ISSUE THREAD

**Issue by EricDunsworth** [wet-boew/wet-boew#6082]
Hey @duboisp,

I've noticed that if I insert a table that contains a `<tfoot>` preceding a `<tbody>` into the validator, it'll move the `<tfoot>` to come after the `<tbody>` in the HTML results...

That doesn't seem to be in line with the HTML5.1 specification (which claims `<tfoot>` can come either before or after `<tbody>`):
http://www.w3.org/TR/html51/tabular-data.html#the-tfoot-element

Any chance this could be looked into/resolved?

Thanks :).

I've provided an example below...

**Input table:**

```
<table>
    <thead>
        <tr>
            <th>head1</th>
            <th>head2</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <td>totals1</td>
            <td>totals2</td>
        </tr>
    </tfoot>
    <tbody>
        <tr>
            <td>data1</td>
            <td>data2</td>
        </tr>
        <tr>
            <td>data1</td>
            <td>data2</td>
        </tr>
    </tbody>
</table>
```

**Table validator's HTML results** (http://wet-boew.github.io/v4.0-ci/demos/tablevalidator/tablevalidator-en.html):

```
<table>
    <thead>
        <tr>
            <th id="tbl5">head1</th>
            <th id="tbl6">head2</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td headers="tbl5">data1</td>
            <td headers="tbl6">data2</td>
        </tr>
        <tr>
            <td headers="tbl5">data1</td>
            <td headers="tbl6">data2</td>
        </tr>
    </tbody>
<tfoot>
        <tr>
            <td headers="tbl5">totals1</td>
            <td headers="tbl6">totals2</td>
        </tr>
    </tfoot></table>
```

**Comment by shawnthompson** [comment]
Doesn't the `tfoot` repeat in print if the table spans multiple pages?

**Comment by cvrebert** [comment]
> Doesn't the `tfoot` repeat in print if the table spans multiple pages?

Not in [Safari](https://bugs.webkit.org/show_bug.cgi?id=17205) or [Chrome](https://code.google.com/p/chromium/issues/detail?id=24826).

**Comment by hsrudnicki** [comment]
Can be this issue closed?

**Comment by EricDunsworth** [comment]
@hsrudnicki This issue has yet to be fixed, so IMO there'd be value in keeping it open until it gets resolved.

**Comment by hsrudnicki** [comment]
@EricDunsworth and others: Close this issue as resolved/fixed or otherwise?  Please update this issue's status before labeling "Going Stale" and/or closing, thank you

**Comment by EricDunsworth** [comment]
@hsrudnicki I just tried reproducing the opening post's example and the problem is still occurring. So this issue is still valid.

**Comment by EricDunsworth** [comment]
Roughly a month after my last comment, [WHATWG's HTML spec](https://html.spec.whatwg.org/multipage/tables.html#the-tfoot-element) and the W3C's HTML [5.1](https://www.w3.org/TR/html51/tabular-data.html#elementdef-tfoot)/[5.2](https://w3c.github.io/html/tabular-data.html#elementdef-tfoot) specs changed to disallow the ``<tfoot>`` element from preceding ``<tbody>``.

As a result, what I was asking for in this issue now goes against the HTML specs. So I'll close it out now.
