### ISSUE TITLE
Plug-in/banner to warn of browser support are supported

### ISSUE THREAD

**Issue by nschonni** [wet-boew/wet-boew#6103]
Mostly related to the eventual end of IE8, we might want to take a similar approach as HTML5 Boilerplate
https://github.com/h5bp/html5-boilerplate/blob/1c4fcf32142e888946db579df0efbb52542e0ed1/src/index.html#L17-L19

**Comment by DHaslip** [comment]
If a user has JavaScript disabled, is the WET framework still expected to function?  But just not be as usable or pretty?  Or can we assume that having JavaScript enabled is a requirement now?

**Comment by pjackson28** [comment]
@DHaslip We take a progressive enhancement approach in WET so the experience will be much more usable and enhanced (and pretty) when JavaScript is enabled but provide the basics when JavaScript is disabled (so basic HTML and CSS). For example the menu bar has no sub-menus when JavaScript is disabled but the user can still access pages through the menu bar.

**Comment by hsrudnicki** [comment]
Again, are you ready to close this issue?

**Comment by pjackson28** [comment]
Yes, there isn't any plan to force such a banner globally. It should be dealt with on a site-by-site basis, based on the targeted support. For instance a site could choose to support older browsers despite them not being supported by WET (that site would be on the hook for adding the additional support).
