### ISSUE TITLE
Question/Suggestion: jQuery countdown timer

### ISSUE THREAD

**Issue by Deborahs** [wet-boew/wet-boew#6118]
Will there be or is there a jQuery plugin which provides this functionality for WET v4?

**Comment by Mimimonn** [comment]
Since last year any update on getting a countdown? We deal with a lot of sports event and now using the canada.ca campaign theme template we are a bit limited. Is there any countdown features, accessible and supported in wet4?

**Comment by LaurentGoderre** [comment]
Not at this point to but you're welcome to help us with this

**Comment by Mimimonn** [comment]
We had one developed custom made last year and was accessible, not very sexy but it worked. If I provide the code for it do you think its something we could work to integrate on wet4? It would be very nice for the sport event users to know when the Games will start, we deal with the Olympics and such events.

**Comment by RobJohnston** [comment]
Maybe you can find a sexier one here to inspire you:  http://plugins.jquery.com/?s=countdown

**Comment by Mimimonn** [comment]
Great thanks for the info, I would be happy, to share what we have done last year if it can help create an accessible feature to be used by everyone in the community.

**Comment by hsrudnicki** [comment]
So, are you ready to close this issue?

**Comment by Mimimonn** [comment]
The counter has been put in place for canada day, it was not a minute or second counter but a day by day counting down, and it passed accessibility, would be great to have it in the official templates. 
Code used:

Javascript Code:
<script type="text/javascript">
function countdown() { 
  var today = new Date();
  var canadaDay = new Date();
  canadaDay.setFullYear(today.getFullYear());
  canadaDay.setMonth(6); //months starts at 0
  canadaDay.setDate(1);
 
  var timeDiff = Math.abs(canadaDay.getTime() - today.getTime());
  var daysLeft = Math.floor(timeDiff / (1000 * 3600 * 24));
  if(daysLeft > 0) {
    var lang = document.documentElement.lang;
    var s = ""
    if(daysLeft > 1) {
        s = "s";
    }
    if(lang == "fr") {
      document.write("<p>Countdown avant la fete du Canada : " + daysLeft + " jour" + s + "</p>");
    }
    else {
      document.write("<p>Countdown before Canada Day: " + daysLeft + " day" + s + "</p>");
    }
  }
}
</script>
<div id="Countdown"><script>countdown();</script></div>

If this helps the contact person Anik Morrisette at anik.morissette@pch.gc.ca for questions such has what heppend when it reachers zero? etc..

**Comment by hsrudnicki** [comment]
Based on the above, this issues has been resolved and closed if you think otherwise, then please update this issue's status.
