### ISSUE TITLE
Datepicker (polyfill) in IE - Text field value does not align vertically

### ISSUE THREAD

**Issue by scraymer** [wet-boew/wet-boew#6120]
A few clients have reported now that all our date fields don't align vertically and the value is cut off from the bottom padding using IE9. We knew about this but marked it up as a known deficiency in our TFS systems. 

We are using wet-boew production version 4.0.5. However, I noticed that on the documentation site of wet-boew when collecting screenshots just now that this issue is no longer a problem in IE9 (Still a minor issue in IE11). I looked in the issues for the datepicker pollyfill label and in the 4.0.6 release notes but couldn't find anywhere about this getting fixed. 

I'm creating this issue as documentation as I couldn't find any reference to a fix. Therefore, is it safe to say this issue for the datepicker pollyfill in IE9 will be fixed in the next release, v4.0.7? Moreover, has the IE11 datepicker pollyfill issue been discussed and if so will it be addressed or left as is in a future releases?

This is what it looks like on our site for IE9 and IE11 using wet-boew version 4.0.5.
![wet-4 0 5](https://cloud.githubusercontent.com/assets/2136510/4493636/268c942e-4a4b-11e4-8b7b-f2ddd9c08ce1.png)

This is what is looks like on the documentation page for IE9 and IE11 using wet-boew development version 4.0.7 assuming - http://wet-boew.github.io/v4.0-ci/demos/datepicker/datepicker-en.html.
![wet-4 0 7](https://cloud.githubusercontent.com/assets/2136510/4493668/78f0e7ba-4a4b-11e4-8489-04af97af9682.png)

Thanks for any information you can provide!

**Comment by LaurentGoderre** [comment]
@scraymer we updated our version of WET can you updated to the latest development release and test?

**Comment by LaurentGoderre** [comment]
I check IE 9, 10 and 11 and all looks ok.
