### ISSUE TITLE
Responsive table inside panel in IE9

### ISSUE THREAD

**Issue by wilkmit** [wet-boew/wet-boew#6129]
When using responsive tables inside a panel in the IE browser I get a strange bug that is adding space under the horizontal scroll bar when I hover over the table rows. This only happens when the horizontal scroll bar is visible (when I shrink my browser window size). Does anyone else get this bug?

![capture](https://cloud.githubusercontent.com/assets/6516828/4529127/da27a862-4d74-11e4-9ef2-62eaf36c4975.PNG)

**Comment by LaurentGoderre** [comment]
Our version of bootstrap has been updated, can you verify that this is fixed now?

**Comment by wilkmit** [comment]
Seems to be working fine for me now. Thanks.

**Comment by wilkmit** [comment]
This issue seems to be fixed. Thank you.

**Comment by LaurentGoderre** [comment]
Awesome! Thanks for verifying!
