### ISSUE TITLE
Datepicker alternative functionality

### ISSUE THREAD

**Issue by amonsour** [wet-boew/wet-boew#6143]
One of our clients announced that it is difficult to close-in on the year, and would require constant clicking on the left arrow to get to the year you were born in. 

Is there a way to have supporting/instructional text to let users know to click on the month/year (October 2014) to open the drop down month/year?

Another option could be to have the option to open the datepicker with the dropdowns for date of birth, etc..

Please see the images below:

![1](https://cloud.githubusercontent.com/assets/9057540/4559051/ac26b470-4ee7-11e4-9c0d-a6ff67559cb5.JPG)

![2](https://cloud.githubusercontent.com/assets/9057540/4559049/a91c8732-4ee7-11e4-9766-d0cd090b3a09.JPG)

**Comment by hsrudnicki** [comment]
Can be this issue closed or otherwise?

**Comment by hsrudnicki** [comment]
@LaurentGoderre and others: This issue has two other referenced issues, and please update this issue's status whether this issue keep still as opened or otherwise? Thank you

**Comment by LaurentGoderre** [comment]
Closing in favor of #6558 and will be closed by #6606
