### ISSUE TITLE
Geomap: Bounding box issues with the draw tool

### ISSUE THREAD

**Issue by bchagnon** [wet-boew/wet-boew#6148]
Random behavior when using the Draw tool: sometimes, when first clicking on the map to draw a box, the position of the starting coordinate and the corner of the red bounding box do not match.

Example:
![geomap_draw](https://cloud.githubusercontent.com/assets/2006029/4578026/9f711b46-4fc1-11e4-99ff-de47986d996d.png)

I clicked on Iqaluit to start drawing a box but the red bounding box displayed lower on the map (using Chrome Version 37.0.2062.124 m)

**Comment by jvanulde** [comment]
@pjackson28 I think we can close this. @bchagnon can you confirm.

**Comment by bchagnon** [comment]
And I confirm.
