### ISSUE TITLE
Tabbed Interface: Test on Ipad

### ISSUE THREAD

**Issue by mohamedbecha** [wet-boew/wet-boew#6150]
Hi there,

I'm testing my website on a real Ipad. The details of the tabbed interface are not showing on the horizontal side? No problem with the Vertical side because of the accordion transition.
I'm using the v4.0.6

Thx

**Comment by LaurentGoderre** [comment]
Is this still an issue?

**Comment by hsrudnicki** [comment]
@mohamedbecha @pjackson28 : again, the above question, can be this issue closed or otherwise?

**Comment by hsrudnicki** [comment]
Again, based on the above, and no further discussion/issue updates, this issue has been labeled as "Going Stale" and closed as well.
