### ISSUE TITLE
Button drop down documentation seems to be missing

### ISSUE THREAD

**Issue by wilkmit** [wet-boew/wet-boew#6156]
Have you stopped supporting button drop downs? I can not seem to see the documentation.

http://wet-boew.github.io/wet-boew-styleguide/v4/design/buttons-en.html#btn-dropdowns

![capture](https://cloud.githubusercontent.com/assets/6516828/4595849/2bcd173a-509d-11e4-8269-6245bf1b06e4.PNG)

**Comment by hsrudnicki** [comment]
@thomasgohard @pjackson28 @wilkmit @CalvinRodo : Are you ready to close this issue?

**Comment by CalvinRodo** [comment]
@hsrudnicki  Unless there has been some consensus to either add back in the drop down or remove all remnants of it from the CSS then no it cannot be closed.

**Comment by LaurentGoderre** [comment]
We don't touch upstream dependencies and I am not sure we will add any JavaScript for it

**Comment by hsrudnicki** [comment]
... and further discussion needed, at least please update this issue's status whether this issue can be closed or otherwise? Thank you

**Comment by hsrudnicki** [comment]
Is this above still an issue, waiting for your consensus to resolve/fix it?  Either way, please update this issue's status, whether this issue (in regards to content styling, bootstrap, as well update of Documentation, ...) can be closed as resolved/fixed or if otherwise?  Thank you

**Comment by hsrudnicki** [comment]
Is this still an issue? Can be this closed or otherwise? Please update the status of this, thank you

**Comment by hsrudnicki** [comment]
Due to no further discussion/updates, this issue of 2014 year can be closed. If you think otherwise, please again update the status of this, thank you
