### ISSUE TITLE
glyphicons causing compatibility view in IE8

### ISSUE THREAD

**Issue by jl3d** [wet-boew/wet-boew#6175]
<span class="glyphicon glyphicon-th-list"></span> used in the mobile menu button for example seems to cause IE8 to drop into compatibility view.
Without the glyphicon, IE8 doesn't crash and attempt to reload the page in compatibility view.

This occurs in the working examples as well:
http://wet-boew.github.io/themes-dist/theme-gcwu-fegc/content-en.html
http://wet-boew.github.io/themes-dist/GCWeb/index-en.html

**Comment by LaurentGoderre** [comment]
Can we close?

**Comment by pjackson28** [comment]
Yes since IE8 is no longer supported.
