### ISSUE TITLE
Mega Menu alignment issue

### ISSUE THREAD

**Issue by upsonp** [wet-boew/wet-boew#6192]
Hi guys,

I updated my WET 4.0 GCWU-FEGC theme yesterday and there seems to be a problem with the alignment of the mega menu now.
![align_issue_001](https://cloud.githubusercontent.com/assets/3355126/4769207/73c68bbe-5b76-11e4-9fb1-1f66d00875ff.png)

The issue seems to be with the css ".col-md-5" rule applied to "wb-stt1" element seen below.

![align_issue_002](https://cloud.githubusercontent.com/assets/3355126/4769209/7aba0a9a-5b76-11e4-8887-7959853e1e25.png)

Setting the width to "0px" in the FireFox css inspector changes the alignment of the menu
![align_issue_003](https://cloud.githubusercontent.com/assets/3355126/4769213/7f756624-5b76-11e4-8333-d4cb188319c8.png)

**Comment by LaurentGoderre** [comment]
Closing since tracking in the GCWU repo
