### ISSUE TITLE
geomap: allow to activate aoi widget by default 

### ISSUE THREAD

**Issue by pvgenuchten** [wet-boew/wet-boew#6206]
We use the aoi widget quite a lot so users select an area of interest on a map to be used as a query filter to look for objects in that area. Geomap is then presented in an advanced search form. Now a user has to click the aoi button to show the coords-boxes, however I would like to add a class aoi-active that enables the widget by default

**Comment by LaurentGoderre** [comment]
Perhaps this would be more suitable as a new issue?

**Comment by jvanulde** [comment]
@pvgenuchten thanks for the feedback. I will look into the split button idea.

**Comment by jvanulde** [comment]
@pvgenuchten I have changed the buttons slightly. See screenshot below. Will this be sufficient?

![screen shot 2015-01-27 at 6 49 22 am](https://cloud.githubusercontent.com/assets/2255248/5920330/c6551610-a5f0-11e4-8a77-349022c71801.png)

**Comment by hsrudnicki** [comment]
@jvanulde @pjackson28 @LaurentGoderre @pvgenuchten : Are you ready to close this issue?

**Comment by pvgenuchten** [comment]
@hsrudnicki yes this works great now
