### ISSUE TITLE
Review Bootstrap v3.3.0

### ISSUE THREAD

**Issue by thomasgohard** [wet-boew/wet-boew#6216]
[Bootstrap 3.3.0 has been released](http://blog.getbootstrap.com/2014/10/29/bootstrap-3-3-0-released/). Can someone review the changes to make sure 3.3.0 can be safely integrated into the Toolkit.

The announcement also provides a preview of what's coming in version 4.

**Comment by cvrebert** [comment]
Note that the latest bootstrap-sass version is currently v3.3.3.

**Comment by LaurentGoderre** [comment]
Thanks! it takes us a while to get up to date
