### ISSUE TITLE
showing modal help

### ISSUE THREAD

**Issue by b0uch3** [wet-boew/wet-boew#6217]
I've been trying to integrate the wet supported modal into a .NET forms application but I am having issues displaying the form using anything but a basic anchor tag.  I need to trigger the modal from a button that submits a formview so that example is not possible since asp.net buttons don't have an href or aria-controls attribute.

I've attempted to show it by triggering a script off of OnClientClick but the example jquery scripts do not work as is and I'm not sure how I need to tweak them in order to show a modal based on the examples in the documentation.

the main example shows:
```
$( "#overlay1" ).trigger( "open.wb-lbx" );
```
--> what does wb-lbx class reference need to line up with?

i've seen another post that a user had mentioned using:
```
$( "#overlay1" ).trigger( "open.wb-overlay" );
```
--> is there any reason to change wb-lbx to wb-overlay?
```
<p><a href="#overlay1" aria-controls="centred-popup-modal" class="wb-lbx lbx-modal" role="button">Centred popup - Modal (Lightbox + Modal)</a></p>
```
--> this triggers it fine but I need to use a web control to trigger it.  Is there a way to configure a button like this?
```
<asp:Button ID="modalButton" cssclass="wb-lbx lbx-modal" runat="server" Text="Button"  />
```
I tried using:
```
<asp:Button ID="modalButton" cssclass="wb-lbx lbx-modal" runat="server" Text="Button"  onClientClick="showModal();" />
```
I placed the trigger script in a showModal function but that doesn't do anything.  I thought perhaps that the trigger script above needs to go into document.ready() which would wire up the asp:Button instead.  That didn't produce anything either. I don't really understand what $( "#overlay1" ).trigger( "open.wb-lbx" ); actually does, although it looks like it sets up an event.

```
<section id="overlay1" class="mfp-hide modal-dialog modal-content overlay-def">
	<header class="modal-header">
		<h2 class="modal-title">modal window</h2>
	</header>
	<div class="modal-body">
		...
		<button class="btn btn-primary popup-modal-dismiss" type="button">Close modal popup</button>
	</div>
</section>
```

**Comment by hsrudnicki** [comment]
@b0uch3 @pjackson28 : Can be this issue closed?

**Comment by pjackson28** [comment]
Closing as the question was answered but can be reopened if needed.
