### ISSUE TITLE
Add assemble helper for generating examples with code preview

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/wet-boew#6225]

**Comment by hsrudnicki** [comment]
Can be this issue closed or otherwise?

**Comment by LaurentGoderre** [comment]
I can't remember why but when I tried to do it last time it wasn't as simple as I anticipated. There was a major roadblock for this.

**Comment by hsrudnicki** [comment]
Closed due to no further discussion/status update if otherwise, please update again this issue's status? Thank you
