### ISSUE TITLE
Session Timeout Wording and Button

### ISSUE THREAD

**Issue by DHaslip** [wet-boew/wet-boew#6227]
At CRA, some applications require a log in, and other do not.  We will be implementing the session timeout plugin in both types of applications.  However, the wording of the current session timeout plugin seems to imply that the user is logged in, which will be confusing for those users who have not.  Would it be possible to change the wording of the second session timeout dialog, so that it applies to all users, whether or not they have explicitly logged in?  I would suggest the following:

o	Change the text to “This session has expired”.
o	Change the button text to “Exit”

**Comment by hsrudnicki** [comment]
@DHaslip @thomasgohard : Can be this issue closed?

**Comment by hanseller** [comment]
Gentlemen, i need your help. I am working on Canada.ca template (version 4). 
I would like to know how i can customize the session time out message as the message that already there is different from the purpose of the page..... Thank you

**Comment by hsrudnicki** [comment]
Based on the above discussion: Made this issue as "Going Stale" and closed this issue or if otherwise { @hanseller  @DHaslip  and others: Please update this issue's status again } ?
