### ISSUE TITLE
control-label class

### ISSUE THREAD

**Issue by CalvinRodo** [wet-boew/wet-boew#6230]
I noticed in this example http://wet-boew.github.io/wet-boew-styleguide/v4/design/forms-en.html#forms-horizontal that there is a class of control-label on the labels, but there isn't an associated class, also searching through the code base doesn't turn up anything.

I'm assuming this is a holdover from the bootstrap documentation, if so it should be remove.
Or is it going to eventually be an actual class for labels.

**Comment by hsrudnicki** [comment]
@thomasgohard @CalvinRodo : Can be this issue closed?

**Comment by CalvinRodo** [comment]
I don't know nothing explicitly states to use it and it's not in the examples for inline forms.

**Comment by hsrudnicki** [comment]
Made "Going Stale" in order to close this issue soon or otherwise? Either way, please update this issue's status, thank you in advance Mr. @thomasgohard and others

**Comment by hsrudnicki** [comment]
Is this still an issue? If not, can be this closed or if otherwise?

**Comment by hsrudnicki** [comment]
Again, based on last comments, can be this issue closed as resolved/fixed when WET member confirms that a requested guidance on control of labels in the documentation has been included/updated as discussed above?

**Comment by hsrudnicki** [comment]
and in case of the docs, see the issue: 5574

**Comment by RobJohnston** [comment]
Bootstrap documentation is still silent on the usage of `control-label`, but [w3schools](http://www.w3schools.com/bootstrap/bootstrap_forms.asp) notes that it's only for horizontal forms:

> A horizontal form stands apart from the other forms both in the amount of markup, and in the presentation of the form.
> 
> Additional rules for a horizontal form:
> 
> - Add class .form-horizontal to the `<form>` element
> - Add class .control-label to all `<label>` elements

Something like that last point could be added to the documentation to close this issue.

**Comment by hsrudnicki** [comment]
Can be this closed, after referencing to 5574 issue?

**Comment by hsrudnicki** [comment]
Closed, but if you think otherwise please update the status of this again, thank you
