### ISSUE TITLE
Tabbed Interface and Multimedia Player - JS error and loading issues on DWAN network

### ISSUE THREAD

**Issue by crichard** [wet-boew/wet-boew#6231]
I am using WET 4.0.6.  I am testing a page which uses a tabbed interface, and one of the tabs contains a video player.  This particular problem occurs when using a DWAN-network computer with IE9, and part of the problem also seems to happen when emulating IE9 in IE11 on an Internet computer.  The video is mp4 and loads correctly in the latest browsers.

Problem 1: on IE9, the Flash fallback is loaded (DWAN and internet)
Problem 2 : JS error - Object expected wet-boew.min.js Line 8 Col 4660 (L'objet ne gère pas la propriété ou la méthode doPause) when trying to change tabs, and no tab content is visible

Sample urls :
http://webdev.multimediaservices.ca/en/job/pharmacyofficer-48
http://webdev.multimediaservices.ca/en/job/aerospaceengineeringofficer-36

I also have problems with the WET 3.1.15 tabbed interface on DWAN (http://www.forces.ca/en/job/pharmacyofficer-48), where clicking on other tabs will not make it visible.  The tab anchor appears in the URL and a page refresh is required to load the page.

If anyone else has access to DWAN and could help me figure this out, it would be appreciated.

**Comment by LaurentGoderre** [comment]
Is this still an issue?
