### ISSUE TITLE
WET 4 - Session login/logout Guidance

### ISSUE THREAD

**Issue by chyne** [wet-boew/wet-boew#6232]
Is there any guidance for WET 4 related to positioning of login/logout links, as there was for WET 3.1?

**Comment by shawnthompson** [comment]
@pcwsmith would adding this to the GCWeb templates be a good thing?

**Comment by shawnthompson** [comment]
@pcwsmith or @DK-TBS is there anything in the works for something like this?

**Comment by DK-TBS** [comment]
Nothing in the works on our end.  We've had a look Thomas' sketches over here, and everyone thinks it's tops.  No complaints from TBS!  Run with it  :)

**Comment by RobJohnston** [comment]
So using existing styles, what's the best markup to accomplish this today (or close to it)?  Some thoughts...

```html
<div class="well bg-info full-width text-right">
        Signed in as User Name
        <button class="btn btn-default" type="button">Account settings</button>
        <button class="btn btn-primary" type="button">Sign out</button>
</div>
```
or

```html
<div class="row bg-info">
    <div class="pull-right mrgn-tp-md mrgn-rght-lg mrgn-lft-md">      
        <ul class="list-inline">
        <li>Signed in as User Name</li>
        <li><button class="btn btn-default" type="button">Account settings</button></li>
        <li><button class="btn btn-primary" type="button">Sign out</button></li>
        </ul>
    </div>
</div>
```

I think the first looks better but the second responds more like the screenshot.

**Comment by robwloch** [comment]
Just wondering if the Logout button should maybe have the colour btn-danger instead of btn-primary. Thoughts?

**Comment by thomasgohard** [comment]
@RobJohnston I'm out of town right now. I have the markup on a separate computer I don't have with me. I'll post it as soon as I'm back.

@robwloch `btn-danger` should be reserved for truly dangerous actions. The sort that you cannot reverse. I think `btn-primary` is appropriate here as it is the primary action for that form.

**Comment by robwloch** [comment]
@thomasgohard To me "Sign out" does seem to fit the criteria for a dangerous action especially inside a web application where you could potentially lose all of your work; another candidate would be a "Delete" button perhaps. In the mock-up screenshot above wouldn't the "Submit" button be the appropriate primary action button for that page? Or is it per form where the page contains multiple forms?

Thank you, Rob.

**Comment by thomasgohard** [comment]
@robwloch applications should warn you if you're going to lose your data from a particular action. Signing out isn't irreversible like delete it. You can sign back in.

Although, changing the colour of the sign-out button as an indicator that it may have irreversible consequences, before explicitly mentioning those consequences, may have some value. We're looking at design patterns for applications. I'll bring this one up.

In the mock-up above, ignore the actual content. I just took a random page to give an idea of the visual and positioning of the sign-out pattern.

**Comment by robwloch** [comment]
Thank you @thomasgohard for seeing some potential value in this for applications.

**Comment by thomasgohard** [comment]
Here's the markup and CSS.

Note that the code hasn't been thoroughly tested yet and may change. I'll try to get something up into the working examples and themes soon.

```html
<section class="signon">
  <h2 class="wb-inv">Sign-on information</h2>
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <p class="signon-state">Signed in as <span class="signon-username">User Name</span></p>
        <button class="btn btn-default">Account settings</button>
        <button class="btn btn-primary">Sign out</button>
      </div>
    </div>
  </div>
</section>
```

```css
.signon {
    background-color: #ddd;
    padding: 0.5em 0;
    text-align: right;
}

.signon-state {
    display: inline-block;
    margin-right: 1em;
}
```

**Comment by plopes3000** [comment]
@thomasgohard this looks great! 

Question 1: Is the account settings button linked to some Canada,ca shared account information like GCKey? I ask because we have a profile section on our web app that "could" be an account setting page. For example, it allows Veterans to update their rank or their address. 

Question 2: Using your mock-up examples, could "check status of your application" have child pages and if so how is that displayed?

**Comment by thomasgohard** [comment]
Answer 1: No, as there is no such thing. At this time, the account settings would be for the user's account for the application to which they are signed-in.

Answer 2: Once a user is signed-in to an application the sign-on bar would remain visible at the same location on every page they navigate to until they sign out of the application.

**Comment by hsrudnicki** [comment]
@thomasgohard and others: Can be this issue closed?

**Comment by MBlondin** [comment]
@thomasgohard When is the Sign in/Sign Out example going to be up in the examples?  In the interim, where does the markup go?  (In which DIV?)

**Comment by rlambert27** [comment]
@thomasgohard Any update on this? We have web applications wanting to implement this but no examples are provided in the current version of WET. Thanks!

**Comment by hsrudnicki** [comment]
Make "Going Stale" towards closing this issue or otherwise? Please keep this issue's status updated again, thank you

**Comment by hsrudnicki** [comment]
Please update the status of this issue, as well other referenced issues, whether the issue(s) can be closed or if otherwise?  Thank you

**Comment by hsrudnicki** [comment]
and just in case of the docs update, check the issue: 5574

**Comment by hsrudnicki** [comment]
Can be this and/or other referenced issues closed? Please update the status of this again, thank you

**Comment by RobJohnston** [comment]
I think this can be closed... there are now examples for signed on and signed off (at least for the Canada.ca theme):

- http://wet-boew.github.io/themes-dist/GCWeb/content-signedon-en.html
- http://wet-boew.github.io/themes-dist/GCWeb/content-signedoff-en.html

**Comment by hsrudnicki** [comment]
We agree that this can be closed. In case of otherwise, please update the status of this again. Thank you

**Comment by plopes3000** [comment]
Sorry to reply late to this. We've already applied the version designed by @thomasgohard in our My VAC Account app at Veterans Affairs. His is different from (and better in our opinion) than the sign-in @RobJohnston linked to above. If there is any chance to suggest Thomas' login, then I would vote for that. Cheers!

**Comment by LaurentGoderre** [comment]
Can you explain in what way it's better?

**Comment by plopes3000** [comment]
I hope I'm not opening up a huge can of worms because I love the Canada.ca theme and all the hard work that has gone into it. It is amazing!  

My VAC Account (MVA) is an authenticated app, so my reasoning is based on how we implemented the WET4 template based on our Veterans needs, which is ever so slightly different than the Canada.ca site. With that in mind, the sign-in bar that @thomasgohard designed visually anchors the page better, making it more recognisable to Veterans when they want to sign-out. 

Hope that helps!

**Comment by LaurentGoderre** [comment]
Ok, that is a very minimal difference, one that would be very easy to do, if the team in charge o the Canada.ca theme would be ok with it.

/cc @shawnthompson @pcwsmith
