### ISSUE TITLE
[Feeds] YouTube Data API version 2.0 was deprecated in March 2014

### ISSUE THREAD

**Issue by thomasgohard** [wet-boew/wet-boew#6238]
The Feeds plugin currently use version 2.0 of the YouTube Data API, which was [deprecated in March 2014](http://apiblog.youtube.com/2014/03/committing-to-youtube-data-api-v3.html). The shutdown of the version 2.0 API is scheduled for April 20, 2015.

**Comment by hsrudnicki** [comment]
@thomasgohard @LaurentGoderre : Can be this issue closed?

**Comment by hsrudnicki** [comment]
Again, please update this issue's status and close this when ready, thx

**Comment by hsrudnicki** [comment]
Based on the above with two merged PRs and no further discussion/status updates, this issue is closed.
