### ISSUE TITLE
Building a new theme.

### ISSUE THREAD

**Issue by brooke-stephens** [wet-boew/wet-boew#6241]
Do you have anymore documentation on creating new themes?
http://wet-boew.github.io/wet-boew/docs/start-en.html#develop

I've done the install of node.js, bower, grunt, etc. and created a new theme.  It's given me some source files: .hbs, .scss, etc.

How do I start using these files to create a new look?  How do I use handlebarsjs files?  Do I compile them into html?

I'm new to handlebarsjs so I'm not sure what to do with .hbs files.

Thanks,
Brooke

**Comment by shawnthompson** [comment]
@LaurentGoderre I'm coming to code sprint tomorrow can you help me build my MTL theme?

**Comment by LaurentGoderre** [comment]
Yeah
