### ISSUE TITLE
Charts and graphs - Customization: wb-charts-line class not working on wb-charts-bar

### ISSUE THREAD

**Issue by benhurqc** [wet-boew/wet-boew#6259]
When working on a table that has the class wb-charts-bar on it, putting the class wb-charts-area on one of the data row works (see example below) but not the class wb-charts-line. 
![tmp](https://cloud.githubusercontent.com/assets/2052290/5012425/047fd854-6a54-11e4-920a-e923dff2c870.png)

**Comment by LaurentGoderre** [comment]
@benhurqc is this still an issue?

**Comment by hsrudnicki** [comment]
@benhurqc @duboisp @LaurentGoderre : Can be this issue closed?

**Comment by hsrudnicki** [comment]
v4.0.19 or otherwise? Either way, please keep this issue's status updated, thank you

**Comment by hsrudnicki** [comment]
Made "Going Stale" to close this issue soon as resolved based on the above milestone or if otherwise? Either way, please update this issue's status, thank you

**Comment by hsrudnicki** [comment]
Again, can be this issue closed as resolved/fixed based on the provided milestone v.4.0.19?

**Comment by hsrudnicki** [comment]
Please update again the milestone or the status of this, whether this can be closed or otherwise, thank you

**Comment by hsrudnicki** [comment]
Based on the above, this can be closed as resolved. If you think otherwise, please update the status of this again, thank you
