### ISSUE TITLE
Twitter embedded timeline: scaling 100% width using grid classes

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/wet-boew#6263]
When using the bootstrap grid classes to wrap around the twitter feed, the feed box does not expend to 100% of the width of the containing element.

```html
<section class="col-md-6">
	<h2>Example</h2>
	<div class="wb-twitter">
		<a class="twitter-timeline" href="https://twitter.com/search?q=%23WxT" data-widget-id="329066756620566528">Tweets about "#WxT"</a>
	</div>
</section>
```
![capture](https://cloud.githubusercontent.com/assets/2575266/5015220/d82dd272-6a69-11e4-9bda-b50a924be480.JPG)

According to the [Twitter Embedded Timeline configuration options](https://dev.twitter.com/docs/embedded-timelines#customization) we need to use the following:

```html
<a class="twitter-timeline"
  width="300"
  height="500"
  href="https://twitter.com/twitterdev"
  data-widget-id="YOUR-WIDGET-ID-HERE">
Tweets by @twitterdev
</a>
```

> The minimum width of a timeline is 180px and the maximum is 520px. The minimum height is 200px.

`width` and `height` are not valid HTML5 attributes on `a` elements and sometimes we might want to have the widget's width to be larger than 520px.

**Comment by pjackson28** [comment]
Is there an actual need to change the height? What would be the use case? Note that the WET plugin can't make the markup validation issue go away, the most it can do is defer it until the JS executes since there is no way to get around configuring the height using that attribute (so the JS would add the invalid attribute at runtime).

**Comment by pjackson28** [comment]
One thing I noticed, is that the width/height attributes are just used to set the width and height on the style attribute of the iframe. So you don't even need the width/height attribute. You can change things with the following CSS trick:

```css
.wb-twitter iframe[style] {
    width: 100% !important;
}
```

The <code>element[style]</code> with the <code>!important<|code> is an old CSS trick for overriding the style attribute on an element so you can set whatever width you want. Same can be done for the height.
if you can override.

**Comment by shawnthompson** [comment]
It's for the [Campaign page](http://wet-boew.github.io/themes-dist/GCWeb/campaign-en.html) in GCWeb. If we want the Twitter feed ti be twice as high as so it's even with other two feeds combined.

I guess another was to deal with the height is to use `data-tweet-limit="3"`

**Comment by pjackson28** [comment]
Just use the CSS trick I posted above. You can control width and height easily through CSS so don't even have to bother with the width and height attributes.

**Comment by shawnthompson** [comment]
Would we want to set that by default in WET?

**Comment by pjackson28** [comment]
That can make for long lines desktop so could possibly be a UX concern. I'm assuming we just leave the height as is.

@thomasgohard What are your thoughts on this. See the screenshot below for what this could look like if we make it fully responsive (width-wise). Should we just make it 100% width in all cases?
![twitter](https://cloud.githubusercontent.com/assets/1326498/5596744/b80baf9c-9263-11e4-81c8-999b949b5a7a.png)

**Comment by shawnthompson** [comment]
It would be up to the person coding the page to use the grids responsibly. It works like that for the other [feeds](http://wet-boew.github.io/v4.0-ci/unmin/demos/feeds/feeds-en.html)

**Comment by pjackson28** [comment]
Okay, I added it by default in PR #6406 (along with a loading animation I repurposed from the multimedia player so it shows that something is coming).

**Comment by shawnthompson** [comment]
Thanks :+1:

**Comment by thomasgohard** [comment]
In terms of readability, the width should max out around 95 characters per line. We can include that in the guidance though.
