### ISSUE TITLE
Inconsistant rendering of errors. 

### ISSUE THREAD

**Issue by CalvinRodo** [wet-boew/wet-boew#6281]
The Form Validation Plugin page and the Form Working Examples page both have different ways of rendering invalid fields.

Example: 
[Form Validation Page](http://wet-boew.github.io/v4.0-ci/demos/formvalid/formvalid-en.html)
![2014-11-19 13_05_16-form validation - working examples - web experience toolkit](https://cloud.githubusercontent.com/assets/87738/5111179/cb00f448-6fec-11e4-8e56-bf84b85bb6df.png)

[Form Working Examples page.](http://wet-boew.github.io/wet-boew-styleguide/v4/design/forms-en.html#forms-control-states)
![2014-11-19 13_04_33-forms - working examples - web experience toolkit](https://cloud.githubusercontent.com/assets/87738/5111181/cd81ee7a-6fec-11e4-97fc-237360011e8c.png)

Which one is the official way of rendering errors, or are they both okay?

**Comment by CalvinRodo** [comment]
The only thing blocking me now is lack of free time, I should be able to get to it eventually though.

**Comment by LaurentGoderre** [comment]
Can we close then?

**Comment by CalvinRodo** [comment]
Do you want to wait until I submit the pull request for the documentation or should a separate issue be opened for that referencing this issue? I'm not sure on the workflow you guys use here for keeping track of tasks.

**Comment by CalvinRodo** [comment]
This is just a comment for my future usage. 

Add documentation for people implementing their own errors code is as follows 

## Html For Implementing your own Errors

### Form Control
````html
<div class="form-group has-error">
  <label for="bar">
    Foo <strong class="required">(required)</strong>
    <span class="label label-danger">Error #:  Error Message</span>
  </label>
  <input id="bar" type="text" required="true" aria-required="true" />
</div>
````


### Error Summary

#### For single error
````html
<section class="alert alert-danger" tabindex="-1">
  <h2>The form could not be submitted because 1 error was found.</h2>
  <ul>
    <li><a href="#Id_of_input_with_error">Error 1: This field is required.</a></li>
  </ul>
</section>
````

#### Multiple Errors
````html
<section class="alert alert-danger" tabindex="-1">
  <h2>The form could not be submitted because 2 errors were found.</h2>
  <ul>
    <li><a href="#Id_of_1st_input_with_error">Error 1: This field is required.</a></li>
    <li><a href="#Id_of_2nd_input_with_error">Error 2: This field is required.</a></li>
  </ul>
</section>
````

**Comment by hsrudnicki** [comment]
No answer to the question from @LaurentGoderre , so again, are you, @CalvinRodo @pjackson28, ready to close this issue?

**Comment by CalvinRodo** [comment]
@hsrudnicki  Nope.

**Comment by hsrudnicki** [comment]
But based on the above including the all issues referenced and closed, this issue just labeled as "Going Stale" can be closed as well or if otherwise please update this issue's status again, thank you
