### ISSUE TITLE
Multimedia Player: Converting HTML captions to YouTube SRT

### ISSUE THREAD

**Issue by SlaneyChris** [wet-boew/wet-boew#6286]
My question is:

I have several videos that are currently playing in the WET player, with in-line captioning. These captions work well. Now I would like to upload the same videos to YouTube. I want to put the same captions on those videos. Is there an easy way to convert the html5 captions to a captioning file that is supported by Youtube? (.srt etc) I have a lot of videos so I would prefer not to have to rewrite all the captions. 

Here's an example of the code I am referring to:
(i.e. <span class="wet-boew-tt" data-begin="5.50s" data-dur="4.39s">dialogue dialogue blah blah blah</span>)

Thanks

**Comment by LaurentGoderre** [comment]
Any update on this?

**Comment by hsrudnicki** [comment]
@SlaneyChris @LaurentGoderre : Are you ready to close this issue?

**Comment by LaurentGoderre** [comment]
Closing due to inactvity

**Comment by crochefort** [comment]
@LaurentGoderre  ... seem's that I have been able to extract my timing .. will try to build the Youtube CC today... 

Might be good to put this script in the Doc ... to help people ...
