### ISSUE TITLE
WET 4 - "Stacked Progress Bar"

### ISSUE THREAD

**Issue by chyne** [wet-boew/wet-boew#6308]
I am looking to implement something link this from Bootstrap (http://getbootstrap.com/components/#progress-stacked).

Is there a specific reason this feature wasn't included in WET 4?

**Comment by hsrudnicki** [comment]
@chyne @LaurentGoderre : Can be this issue closed?

**Comment by hsrudnicki** [comment]
Due to the above and no further discussion/status updates, this issue, as well labeled as "Going Stale", has been closed or otherwise? If you strongly think of otherwise, please update this issue's status again, thank you
