### ISSUE TITLE
Difference between wet-boew.css and wet-boew.min.css

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew#6309]
There is a difference between the minified and unminified versions of WxT for the img-responsive class in the wet-boew.css file.

After talking with @LaurentGoderre it was mentioned this is a known issue?

wet-boew.css unminified:

.img-responsive {
  display: block;
  width: 100% \9;
  max-width: 100%;
  height: auto; }

wet-boew.min.css minified:

img-responsive{
display:block;
max-width:100%;
height:auto
}

This results in images in IE being blown up when using WxT unminified. Is there something I am perhaps missing? Everything works as expected when using the minified version.

**Comment by sylus** [comment]
I am not sure but it is still present on latest dev if that helps.

https://github.com/wet-boew/wet-boew-dist/blob/v4.0-dist/unmin/css/wet-boew.css#L872

**Comment by LaurentGoderre** [comment]
Yeah, we haven't upgraded bootstrap yet

**Comment by sylus** [comment]
Hey @LaurentGoderre any idea when we will ship with a new version with this fixed? :)

**Comment by LaurentGoderre** [comment]
Is this a priority for you guys?

**Comment by sylus** [comment]
Not at the moment as only occurs when unminified version is used. Just curious about the upgraded bootstrap version. ^_^

**Comment by LaurentGoderre** [comment]
Is this still an issue? I think our bootstrap update fixed this

**Comment by sylus** [comment]
Yeah looks to be fixed :)
