### ISSUE TITLE
ie11 - module-* background-image is a black bar

### ISSUE THREAD

**Issue by mxlav** [wet-boew/wet-boew#6312]
* Opened an issue in Drupal-Wetkit issue queue https://www.drupal.org/node/2366299. 
* Appears to be a WET issue, not a Drupal-Wetkit issue.
* Using Wetkit V1.7 (**WET v3**)

**Issue**
All alert messages in IE11 have a black bar instead of the image/icon. See above link for screenshots.

**Comment by LaurentGoderre** [comment]
Closing since v3.1 is no longer supported
