### ISSUE TITLE
Sitemap page (list of links)

### ISSUE THREAD

**Issue by soatley** [wet-boew/wet-boew#6314]
We would like to incorporate a sitemap on our implementation.  Does anyone have any examples or recommendations on the best way to do this?

**Comment by hsrudnicki** [comment]
@thomasgohard @pjackson28 and others: Can you close this issue?

**Comment by RobJohnston** [comment]
http://www.sitemaps.org/ has all technical info.  
https://www.dmoz.org/Computers/Internet/Searching/Search_Engines/Sitemaps has some generators.

**Comment by hsrudnicki** [comment]
@thomasgohard  @soatley  and others: Made "Going Stale" in order to close soon this issue or otherwise? Either way, please update this issue's status, thank you
