### ISSUE TITLE
Overlays "Centred popup" and "Centred popup-Modal" not working when using class="wb-frmvld"

### ISSUE THREAD

**Issue by biljanap** [wet-boew/wet-boew#6325]
Is there a reason I would not be able to use overlay "Centred popup" and "Centred popup-Modal" if I use class="wb-frmvld" anywhere on my page? I can use any other overlays but these two.

**Comment by hsrudnicki** [comment]
@biljanap @LaurentGoderre @pjackson28 : Can be this issue closed?

**Comment by biljanap** [comment]
@hsrudnicki I forgot about this. I will try it today. I'll let you know by the end of the day....or Monday. Thanks.

**Comment by hsrudnicki** [comment]
@biljanap and others: Made "Going Stale" to close this issue soon or otherwise? Please update this issue's status whether this issue can be closed or otherwised, thank you

**Comment by hsrudnicki** [comment]
Is this still an issue, waiting for an input/more details from @biljanap or otherwise and can be closed?

**Comment by hsrudnicki** [comment]
Is this still an issue?  Either way, please update this issue's status, whether this issue can be closed as resolved/fixed or if otherwise? Thank you

**Comment by hsrudnicki** [comment]
Based on the above, as well no response from @biljanap  this issue can be closed. If you think otherwise, please update this issue's status again, thank you
