### ISSUE TITLE
Session Timeout not working with .NET

### ISSUE THREAD

**Issue by redNomer** [wet-boew/wet-boew#6340]
hi
I have tried using the Session Timeout code provided in various pages without any success.
<span class="wet-boew-sessiontimeout" data-wet-boew='{"inactivity": 10000, "logouturl": "http://wet-boew.github.io/wet-boew-legacy/v3.1/demos/index-en.html"}'></span>
I have tried both the 3.1 and 4.0 versions still not success

How do I use it?
Add the following to the page:
```html
<span class="wb-sessto" data-wb-sessto='{logouturl: "./"}'></span>
```

So simple... So why doesn't it work! 

tom

**Comment by LaurentGoderre** [comment]
CLFPagePlugin? Is it possible that it's not WET4 but WET 3.1 or even 3.1?

**Comment by pjackson28** [comment]
@LaurentGoderre I don't think CLFPagePlugin is part of WET as I don't recall any of the WET v2 or v3 plugins being called that. Perhaps it is a browser plugin.

**Comment by redNomer** [comment]
Date: Tue, 13 Jan 2015 07:35:20 -0800From: notifications@github.comTo: wet-boew@noreply.github.comCC: tom.reddon@live.caSubject: Re: [wet-boew] Session Timeout (#6340)CLFPagePlugin? Is it possible that it's not WET4 but WET 3.1 or even 3.1?

—Reply to this email directly or view it on GitHub.

  
    
    
  
  
 		 	   		  =

**Comment by redNomer** [comment]
Hi, sorry I haven't been able to spend any time on this recently 
But I will find some time this week to review it
thanks,
tom
 

 
Date: Tue, 13 Jan 2015 07:40:23 -0800

**Comment by LaurentGoderre** [comment]
I know it's not part of WET. It must be a custom implementation of WET (It's what it was called when I was a Transport Canada)

**Comment by LaurentGoderre** [comment]
Is this still an issue?

**Comment by redNomer** [comment]
you can close this oneit didn't work so we're not using it Date: Mon, 16 Feb 2015 07:22:16 -0800From: notifications@github.comTo: wet-boew@noreply.github.comCC: tom.reddon@live.caSubject: Re: [wet-boew] Session Timeout (#6340)Is this still an issue?

**Comment by LaurentGoderre** [comment]
The plugin or WET overall?

**Comment by redNomer** [comment]
the plugin
 
Date: Mon, 16 Feb 2015 10:13:58 -0800

**Comment by redNomer** [comment]
I should clarify  - I couldn't get it to workand ran out off time to continue to work on it Date: Mon, 16 Feb 2015 10:13:58 -0800From: notifications@github.comTo: wet-boew@noreply.github.comCC: tom.reddon@live.caSubject: Re: [wet-boew] Session Timeout (#6340)The plugin or WET overall?

**Comment by hsrudnicki** [comment]
Are you ready to close this issue?

**Comment by redNomer** [comment]
I could never get it to work!

I'm on vacation today and will be back in the office on Tuesday. Maybe we can discuss it then.



Sent from my Windows Phone
________________________________

**Comment by hsrudnicki** [comment]
@pjackson28 @LaurentGoderre : your further help is needed to close this issue

**Comment by redNomer** [comment]
our application uses wet 3.1
 
please provide instructions on how to implement your session timeout code 
what I have tried so far does work!

 
Date: Fri, 12 Jun 2015 14:02:08 -0700

**Comment by hsrudnicki** [comment]
Made "Going Stale" to close this issue soon or otherwise? Either way, please update this issue's status, thank you

**Comment by redNomer** [comment]
close the issue as I no longer work on the project

 
Date: Wed, 2 Dec 2015 08:58:33 -0800
