### ISSUE TITLE
Step-by-step (Wizard) component

### ISSUE THREAD

**Issue by Empereol** [wet-boew/wet-boew#6367]
Is there a wizard or similar component in WET? If not, is there any reservations against a wizard component or thoughts to keep in mind before before creating and submitting a wizard component?

I'm working with the CRTC on designing and implementing some changes dealing with how users retrieve and submit forms. The UX team has come up with a wizard style idea (Concept below). 

![wet4_wizard_example](https://cloud.githubusercontent.com/assets/746530/5416677/f378fd06-81ff-11e4-94fe-7bde9db4d123.png)

Some things to take note of in the concept:
- The user would not be able to advance a step unless hitting a specific action ("Continue to next step" button).
- The user would be able to go back to any previous step by hitting the appropriate step's title/link.
- The user's selection from a previous step would be listed in the "collapsed" step.

Before developing this type of component I want to determine if there are any components that exist with similar functionality or if there are any components that could be used within the creation of this component.

**Comment by thomasgohard** [comment]
@pcwsmith @shawnthompson was one of you already working on a similar pattern?

**Comment by shawnthompson** [comment]
We have the [Advance service initiation pages](http://wet-boew.github.io/themes-dist/GCWeb/servicecomplexe/index-en.html) on Canada.ca, which is a step by step but on separate pages.

**Comment by thomasgohard** [comment]
@Empereol is it correct to assume that this component would be on a single page, not on separate pages like @shawnthompson's solution?

**Comment by Empereol** [comment]
Yes, the JavaScript version of this component would be solely on one page with the steps expanding and collapsing based on which step is active. If JavaScript is disabled it would have to fallback to a multi-page version.

**Comment by thomasgohard** [comment]
@Empereol How would it fallback to a multi-page version if JavaScript is disabled? Wouldn't that require interacting with the server?

**Comment by Empereol** [comment]
JS would hijack the form action and perform AJAX calls. So yes, there would have to be some interacting with the server to direct to (or retrieve via AJAX) the proper page/options for the next step based on your current step's selected option.

**Comment by thomasgohard** [comment]
@Empereol so the default state would be a multi-page form. And, if JavaScript is enabled, the component would pull the content from the subsequent pages into the first one. And that instead of loading a new page. Is that correct?

**Comment by Empereol** [comment]
Yup, that is correct.

**Comment by CalvinRodo** [comment]
how would you be able to tell when the current stage is valid and that you are ready to go on to the next one?

**Comment by thomasgohard** [comment]
@LaurentGoderre what do you think about this from a technical point of view?

**Comment by LaurentGoderre** [comment]
Sounds like a fun challenge. It would also help to meet WCAG 2.0 SC 3.3.4 Error Prevention (Legal, Financial, Data) if a summary page is presented at the end to confirm the data.

I assume that the data will get collected as you go and only submitted when all steps are completed right? If so there will be a need to implement a Javascript solution using local storage and a server side solution (in the databse or the back end technology).

**Comment by thomasgohard** [comment]
I've created a feature branch to work on this component: https://github.com/wet-boew/wet-boew/tree/multi-step-process-component.

**Comment by hsrudnicki** [comment]
Are you ready to close this issue?

**Comment by hamdaneh** [comment]
Hi,
I am trying to access the link : https://github.com/wet-boew/wet-boew/tree/multi-step-process-component but I get 404 error. Is there a such WET component available ?
That would be great!
Thanks.

**Comment by LaurentGoderre** [comment]
It was most likely removed

**Comment by hamdaneh** [comment]
Is there a step-by-step or wizard component in WET or alternative to that ? I found this, wondering what you think ...  http://www.jquery-steps.com/GettingStarted

**Comment by LaurentGoderre** [comment]
Not tat this point

**Comment by hsrudnicki** [comment]
@Empereol @thomasgohard and others: Please update this issue's status whether this issue, which had been referenced with the issue 4557, the both are waiting for your decision in fixing, can be closed or otherwise?

**Comment by hamdaneh** [comment]
Well 4557 is about overlays, not really what I was looking for. The real one has been removed. So I guess we can close this issue. Such feature does not exist anymore.

**Comment by hsrudnicki** [comment]
Based the above, this issue can be closed.
