### ISSUE TITLE
JS error on IE8 in GCWeb search box

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/wet-boew#6370]
Error occurs on the following page in IE8 when the search box is clicked:
http://wet-boew.github.io/themes-dist/GCWeb/docs/ref/GCWeb/GCWeb-en.html
 
Webpage error details
 
User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0; SLCC1; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; MS-RTC LM 8; OfficeLiveConnector.1.3; OfficeLivePatch.0.0; .NET4.0C; .NET4.0E)
Timestamp: Fri, 12 Dec 2014 17:18:08 UTC

Message: 'className' is null or not an object
Line: 6
Char: 4328
Code: 0
URI: http://wet-boew.github.io/themes-dist/GCWeb/js/polyfills/datalist.min.js
 
 Specifically, the error occurs on the autolist.className.indexOf line in the following function. 

```javascript
// Handle focus and resize events
$document.on( "focusin txt-rsz.wb win-rsz-width.wb win-rsz-height.wb", function( event ) {
       var focusEvent = ( event.type === "focusin" ),
              eventTarget = event.target,
              eventTargetId = ( eventTarget ? eventTarget.id : null ),
              inputs, input, autolist, i, len;
 
       // Only correct width if the polyfill has been initialized
       if ( initialized ) {
              inputs = $document.find( selector ).get();
              len = inputs.length;
              for ( i = 0; i !== len; i += 1 ) {
                     input = inputs[ i ];
                     if ( focusEvent ) {
                           autolist = input.nextSibling;
                           if ( autolist.className.indexOf( "hide" ) === -1 &&
                                  eventTargetId !== input.id && eventTargetId !== autolist.id &&
                                  !$.contains( autolist, eventTarget ) ) {
 
                                  closeOptions( input );
                           }
                     } else {
                           correctWidth( input );
                     }
              }
       }
});
```

**Comment by hsrudnicki** [comment]
Can this issue be closed?

**Comment by RobJohnston** [comment]
Probably, since it's an IE8 issue and that is <5% now.  Also, I no longer have IE8 to test with.

**Comment by hsrudnicki** [comment]
@LaurentGoderre : Based on the above answer, this issue is ready to be closed

**Comment by pjackson28** [comment]
@LaurentGoderre Just noticed that you put a v4.0.15 milestone on it.Did you want to reopen this issue or should it be left closed?

**Comment by LaurentGoderre** [comment]
We can leave it close for now but it wasn't fixed yet
