### ISSUE TITLE
Geomap: Auto-load the map at specific co-ordinates

### ISSUE THREAD

**Issue by josephbr** [wet-boew/wet-boew#6373]
Is it possible to have Geo-Map load and automatically zoom into a specific latitude and longitude? The documentation covers creating links to areas on the map but I would like it to already zoom into the right spot from that start.

**Comment by LaurentGoderre** [comment]
Is this still an issue?

**Comment by josephbr** [comment]
Sorry, I was occupied with other tasks; just getting back to this now. When you say add a feature request, do you mean create a new issue containing the feature request and a reference to this ticket?

**Comment by jvanulde** [comment]
Yes please. Then we can close this support request.
