### ISSUE TITLE
Feeds: Triggers Ad-block Plus

### ISSUE THREAD

**Issue by thomasgohard** [wet-boew/wet-boew#6377]
Either something in the plugin or the content being loaded by the plugin is triggering Ad-block plus in Firefox and breaks the page.

This is recent as the working example for the feeds plugin was still working fine late last week.

**Comment by hsrudnicki** [comment]
Are you ready to close this issue?

**Comment by hsrudnicki** [comment]
Please update this issue status and close this when fixed, thanks

**Comment by hsrudnicki** [comment]
Made "Going Stale" to close this issue soon or otherwise? Either way, please update this issue's status asap, thank you

**Comment by hsrudnicki** [comment]
Is this still an issue?  Either way, please update this issue's status, whether this issue can be closed as resolved/fixed or otherwise? Thank you

**Comment by hsrudnicki** [comment]
@thomasgohard @pjackson28 : This issue has been closed based on the above, if you think otherwise please update this issue's status or milestone again, thx
