### ISSUE TITLE
Why is it so hard to get help? simple email?

### ISSUE THREAD

**Issue by mhutchis** [wet-boew/wet-boew#6382]
The wet site on TBS web site has no contact us for WET. This is not helpful.

**Comment by LaurentGoderre** [comment]
@mhutchis questions regarding WET should be asked here to ensure we have a history of question all in one location

**Comment by hsrudnicki** [comment]
Can be this issue closed or otherwise?

**Comment by pjackson28** [comment]
Closing as an explanation was given and there has been no further activity in the last 5 months.
