### ISSUE TITLE
Geomap: placeholder text in geocoder widget is truncated in french

### ISSUE THREAD

**Issue by jvanulde** [wet-boew/wet-boew#6390]
@jolevesq please take a look at this. Screenshot showing issue:

![screen shot 2014-12-22 at 12 47 04 pm](https://cloud.githubusercontent.com/assets/2255248/5530793/eb9290bc-89d8-11e4-80c6-b77afb11066b.png)

**Comment by jolevesq** [comment]
I modified the i18n google docs to replace ' by the the HTML ASCII code. @pjackson28 should I do a pull request or something to notified I modified the file?

**Comment by jvanulde** [comment]
@jolevesq I think you need to follow this pocess: Use grunt update-i18n to pull down the latest copy. Then use grunt i18n_csv to regenerate the i18n JSON files with that new i18n file.

**Comment by LaurentGoderre** [comment]
Actually, you only need to do `grunt update-i18n` and open a PR. the rest will get taken care of the next time you build. The generated i18n files are not tracked, only the CSV.

**Comment by jolevesq** [comment]
@LaurentGoderre when you say open a PR, is it create a new one? I did update-i18n and i18n_csv. I did a commit locally and pushed it to my origin. Do I have something else to do?

**Comment by LaurentGoderre** [comment]
Yeah, on your origin, you need to press the green button to create a pull request
