### ISSUE TITLE
Wet4 & Drupal 7, JS library loading slowly or not at all

### ISSUE THREAD

**Issue by ashzadeh** [wet-boew/wet-boew#6404]
Hello,

I'm creating a Wet4 theme for Drupal. I'm using the jQuery 2.1.1 and Wet4.0.9. I load the wet-boew.min.js file at the bottom of my page. It works except for these issues. This is all being done locally. 

1. Lighbox elements: the jquery.magnific-popup.min.js file takes 6-8 seconds to load. Once it does, lightbox elements work.
2. Tabbed elements don't render as tabs. I used the same markup as the demo material.
3. Carousel elements only load the first element.

Thank you.
Ash

**Comment by jhunte** [comment]
Sorry for the late reply. This is not using the Drupal variant, I'm creating the theme from scratch. I apologize for not paying my console log earlier. This is what I have. '.min.js' doesn't exist in the source files I have. I can see the tab related error below.

  [Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (.min.js, line 0)
  [Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (.min.js, line 0)
  [Error] TypeError: undefined is not an object (evaluating 'd("tab-rot").on')
	B (wet-boew.min.js, line 11)
	
The other JS files loading are (in order and at the bottom of the page):
  1. jquery.min.js (2.1.1)
  2. jquery.once.js
  3. drupal.js
  4. wet-boew.min.js

As for the long loading time, it seems as if it is reading wet-boew.min.js for a few seconds. Once it does, I get the third error above and lightbox then works.

**Comment by ashzadeh** [comment]
Sorry for the late reply. This is not using the Drupal variant, I'm creating the theme from scratch. I apologize for not paying my console log earlier. This is what I have. '.min.js' doesn't exist in the source files I have. I can see the tab related error below.

  [Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (.min.js, line 0)
  [Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (.min.js, line 0)
  [Error] TypeError: undefined is not an object (evaluating 'd("tab-rot").on')
B (wet-boew.min.js, line 11)

The other JS files loading are (in order and at the bottom of the page):

1. jquery.min.js (2.1.1)
2. jquery.once.js
3. drupal.js
4. wet-boew.min.js

As for the long loading time, it seems as if it is reading wet-boew.min.js for a few seconds. Once it does, I get the third error above and lightbox then works.

**Comment by LaurentGoderre** [comment]
Still, @sylus may have some insight as to why this is happening. I don't know why you would get 403s. Have you tried accessing the resource files directly?

**Comment by ashzadeh** [comment]
Some further testing: on jsfiddle, the tabs don't work until the screen size is smaller than 768. 
    http://jsfiddle.net/z0e9vyg5/

**Comment by LaurentGoderre** [comment]
Do you have an example I can look at?

**Comment by ashzadeh** [comment]
Hi Laurent, 

You can see the tabs interface here: http://jsfiddle.net/z0e9vyg5/

**Comment by pjackson28** [comment]
@ashzadeh I'm not surprised it is slowing the page down as you have the JS in the head when it should be at the end of the body (like the WET examples do). So the JS is blocking loading of the page, hence the delays. As for why it isn't working, WET isn't even initializing, probably related to how you set up the page.

As for why it is working below 768px, you are likely testing with a browser that has native support for details/summary so it will expand/collapse without WET's help (although won't be an accordion). It doesn't work for me in Firefox because it currently doesn't have native details/summary support.

So you should mimic the markup/structure of the WET examples as closely as possible if you want to ensure that WET is loading properly.

**Comment by ashzadeh** [comment]
@pjackson28 Thank you for your quick reply. I have tried to follow the WET structure here and can't get the tabs to work: http://liveweave.com/uLIIAK

**Comment by pjackson28** [comment]
@ashzadeh The html element is coded incorrectly. It is missing some critical attributes and classes. For instance the absence of the lang attribute means WET doesn't know which language file to load (and also would fail WCAG 2.0 for not declaring the page language).

**Comment by ashzadeh** [comment]
@pjackson28 Wow, can't believe I missed that. Thank you, Paul and everyone else in this thread. Tabs work now.
