### ISSUE TITLE
Action / Confirm button in overlay

### ISSUE THREAD

**Issue by soatley** [wet-boew/wet-boew#6405]
How can I get an action button to work in an overlay? I'm using the Overlay to confirm changes before the page is submitted.  On the page, I have an anchor that opens the overlay and that works great.  A message and two buttons are provided to the user.  One to cancel and return (closes the modal overlay) and the other is an `<input type="submit">` button. 

The button can be clicked on but it doesn't go anywhere.  If I simulate a click using jQuery while the overlay is open, it doesn't do anything.  If I close the overlay and do the same thing, it works.  This leads me to believe that the button actions are trapped by some sort of JS.

I'm looking for something similar to the session timeout buttons where clicking a button will work.

Looking through the code to make the overlay it doesn't look like the clicks are trapped in there, but I may have missed something....

This code seems to work as a work around for me:

````
$(document).on("click vclick", ".mfp-wrap [type=submit]", function(event) {
$.magnificPopup.close();
event.target.click()
});
````

**Comment by soatley** [comment]
An action is specified but that made me check the layout of the page.  Even though the modal code is located within the form element, when it is shown on the screen, it moves it to the first element after the opening of the body element which pushes it outside of the form element.

Because I'm running on ASP.NET, this is why it's not posting back.  There's an option in Magnific to support .NET actually: http://dimsemenov.com/plugins/magnific-popup/documentation.html?1#prependto I'll work on finding a way to get that to work with WET.

**Comment by soatley** [comment]
I had to update the magnific javascript file to the one that supported the prependTo option. 

Once that was done, in the wet-boew.js file, right before the magnific popup is initialized:
````
	if (elm.getAttribute("data-prepend")) {
	    settings.prependTo = document.getElementById(elm.getAttribute("data-prepend"));
	}
````

So, as long as I include the data-prepend attribute on any lightbox/overlay items that have a button in it that posts, this will make sure it stays within the form element.

**Comment by pjackson28** [comment]
You could do it with the data-wb-lbx attribute where mySelector is something that would be a valid jQuery selector:

```js
data-wb-lbx='{"prependTo": "mySelector"}'
```

**Comment by pjackson28** [comment]
Note that the above will need 1.0.0 to work, but I've bumped the version of Magnific Popup in PR #6413.

**Comment by soatley** [comment]
Your way is much easier for me and saves having to modify the JS file.  Thanks for the tip!

**Comment by pjackson28** [comment]
Note that another approach could be to use JS on the submit button to trigger the action specified on the outside form element (although wouldn't provide any benefit over prependTo).
