### ISSUE TITLE
WET3 and WET4

### ISSUE THREAD

**Issue by cleclerc** [wet-boew/wet-boew#6407]
Just confirming, for a client, that it is NOT possible to use WET4 pages and maintain the current WET3 menu. 

Their current site is in WET3 and so, if we are creating new pages for them in WET4, the menu style/structure for this section would need to change as well, Correct?

Thanks.

**Comment by pjackson28** [comment]
Correct, the menus would need to be adapted to what is supported under WET v4. In WET v4, it is possible to go more than two levels deep but it would mean using collapsible sub-sections (as shown in Section 3 of http://wet-boew.github.io/v4.0-ci/demos/menu/menu-en.html). Note that it is recommended that you avoid going that deep as it does significantly increase complexity for mobile users (and other users as well). Also note that for Government Canada sites, existing menus will be replaced by the Canada.ca menu as part of migration to Canada.ca.
