### ISSUE TITLE
Implement a live chat communication tool for wet-boew (Slack!)

### ISSUE THREAD

**Issue by melodyma** [wet-boew/wet-boew#6411]
Although Github is a great team collaboration tool, it doesn't lend itself as a fluid communication tool for distributed teams working on projects such as wet-boew. We should implement a team chat app for this project where team members and users can share information.

I suggest that we should use Slack, which is a very popular enterprise-type chat app with great integration to Github, Travis CI etc. You can set up different channels for different purposes and even add bots for Github PR and other alerts of the link. And, did I mention it's free??? It's used by companies like airbnb, Stripe and Expedia.

Here's more information about Slack:
https://slack.com/
- Integration: https://staticity.slack.com/services/new
- Pricing Plans: https://staticity.slack.com/pricing
- Non-profits can get a free upgrade to the 'Standards' plan: https://slack.zendesk.com/hc/en-us/articles/204368833
 
And to be fair, there are alternatives - Here's hipchat by Atlassian. I've never used it, but people say it's pretty decent too. https://www.atlassian.com/software/hipchat

**Comment by thomasgohard** [comment]
We already have a channel on IRC. It's #wet-boew on freenode.

**Comment by LaurentGoderre** [comment]
Nobody actually used the IRC, maybe this one can be useful

**Comment by shawnthompson** [comment]
I did! /me likes IRC

**Comment by CalvinRodo** [comment]
IRC is blocked here at my office so is a no go.

**Comment by thomasgohard** [comment]
Finding a chat service that isn't blocked on government networks is going to be difficult. Then again, finding any site that isn't blocked on most government networks is probably difficult. Sometimes government sites themselves are blocked on government networks.

**Comment by stephenbe** [comment]
Slack is such an amazing app, we use it constantly at our agency, very valuable tool.

@cjbarber created a repo with alternative chat systems we could maybe use :

https://github.com/cjbarber/hipchat-alternatives

Can anyone in the government check these out, see if they're blocked?

**Comment by hsrudnicki** [comment]
Are you ready to close this issue or otherwise?

**Comment by RobJohnston** [comment]
I remember Slack wasn't functional at CIC when this issue was created (couldn't send messages), but it works now.  I think they changed a protocol that they were using that was blocked by a firewall rule.  Others may have more luck now.

Also since then, a [Windows version](http://slackhq.com/post/113969353750/slack-for-windows) has been released.  Still nothing for Blackberry :-1:.  

The  #wet-boew channel on freenode seems to not really exist now?  I couldn't find it a couple months ago.  Slack seems like a web front-end to IRC to me.

**Comment by hsrudnicki** [comment]
@thomasgohard @LaurentGoderre : your further response/decision is needed to close this issue or otherwise

**Comment by hsrudnicki** [comment]
Due to the above, this issue has been closed if you strongly think otherwise please update this issue's status again, thx

**Comment by RobJohnston** [comment]
Mattermost is an open source, self-hosted Slack-alternative
http://www.mattermost.org/
