### ISSUE TITLE
Plugin scss variables location question

### ISSUE THREAD

**Issue by melodyma** [wet-boew/wet-boew#6412]
@LaurentGoderre 

I'm in the process of re-organizing the custom scss variables so that it's easier customization and maintainability.

I noticed that there are some plugin-level scss variables in src/_variables.scss, specifically "Calendar", "Multimedia Player" and "Footnotes" and in other cases, plugin-level scss variables that are in the _base.scss file of the plugin themselves. Is there a preference to keep plugin-level variables in the plugin's related _base.scss or even introduce plugin-specific _variables.scss file or should the plugin-level variables be placed in the global src/_variables.scss file?

**Comment by LaurentGoderre** [comment]
I think that all configurable variable should be moved to src/_variables.scss.; This way you only need to look in one place for customization

**Comment by LaurentGoderre** [comment]
Bewatre though....not asll variables are meant to be configurable so some of theme will remain in `_base.scss`

**Comment by LaurentGoderre** [comment]
Please note that the branch is severely out of sync. I am rebasing right now which means you will need to do some git tricks to get the updates. I will let you know when it's ready

**Comment by thomasgohard** [comment]
Why not keep the plugin-specific variables with the plugin code? That would mean all the plugin-specific code is in one place. Plus, if we ever wanted to support custom builds, it would be easier to do so if plugin-specific code was not spread around.

**Comment by LaurentGoderre** [comment]
Leaving the variables in the plugin code is spreading it around. All customizable variables should be in one file to make it easier for themes to customize them when we add this functionality.

**Comment by melodyma** [comment]
Hi Laurent,

@LaurentGoderre - I already started a new clean branch with my changes in progress or should I use the one that is up there? 

Also, how do I know which plugin variables are customizable or not?

**Comment by LaurentGoderre** [comment]
@melody, I think we are going to abandon that branch so start from scratch. I will have PR soon to better define the variables, I will cc you on it.

As for which one can be customize, it would have to be a judgment call.

**Comment by melodyma** [comment]
@LaurentGoderre I started this branch with preliminary changes: https://github.com/melodyma/wet-boew/compare/scss-plugin-variables

Should I continue with that branch or wait for your PR before I submit one for that branch?

**Comment by LaurentGoderre** [comment]
You probably will need to re-apply your changes after my PR gets merged

**Comment by melodyma** [comment]
When do anticipate that the PR will get merged? Is it going to be a big
change? I'll pace my changes accordingly.

**Comment by LaurentGoderre** [comment]
It is somewhat of a big change yes. Hopefully we can merge this week

**Comment by LaurentGoderre** [comment]
Any question on this or can we close it?

**Comment by melodyma** [comment]
I'm good. I will close this issue.
