### ISSUE TITLE
How to convert Tab interface(wet-boew-tabbedinterface tabs-style-3) in WET 3 to WET 4?

### ISSUE THREAD

**Issue by bomarleau** [wet-boew/wet-boew#6415]
<div class="wet-boew-tabbedinterface tabs-style-3 auto-height-none">
	...					</div>

**Comment by pjackson28** [comment]
@bomarleau You are best off just taking your tab and tabpanel content from your WET v3.1 implementation and putting it in the WET v4 tabbed interface carousel markup (tweaking as necessary). There likely is nothing other than your content that would be transferable.

**Comment by bomarleau** [comment]
Thanks for the repaly. In WET v4, I could not find the left side panel. Do I have to copy  the javascrip t and ccss related to the Tab from WET 3.1 as well?

**Comment by LaurentGoderre** [comment]
@thomasgohard was that style deprecated?

**Comment by thomasgohard** [comment]
Only two styles were brought over to WET 4. The "standard" tabbed interface and the carousel. The other styles has usability issues.

**Comment by bomarleau** [comment]
@thomasgohard 
Could you specify in more details. Our new web site is going to use left side panel. I have never heard about the usablity issue before.

**Comment by thomasgohard** [comment]
@bomarleau The problems with `tab-style-3` were that:
* The tabs did not convey *clickability*.
* The buttons did not meet the requirements for the minimum target size of touch interfaces.
* The side-by-side layout could not be adapted to small-screen devices where the available width is limited.

**Comment by LaurentGoderre** [comment]
@bomarleau can we close this?

**Comment by bomarleau** [comment]
Yes, we can close this. Thanks for the replay.
