### ISSUE TITLE
Country Location not working in IE and Chrome

### ISSUE THREAD

**Issue by bsouster** [wet-boew/wet-boew#6420]
I tested on fresh WET v4.0.9 production files. 

It works on:
* Firefox 34

Doesn't work on:
* IE8
* IE9
* Chrome 39

By "doesn't work", I mean it seemingly doesn't do anything. Country content never makes its way into the page.

@nschonni

**Comment by LaurentGoderre** [comment]
It's probably working because Your Firefox has a cached setting and not the other browser.

I am getting an error from the http://freegeoip.net/ service

**Comment by LaurentGoderre** [comment]
There you go.

http://stackoverflow.com/questions/20882227/is-there-another-site-like-freegeoip-net

**Comment by LaurentGoderre** [comment]
Nevermind, that was last year but still it appears to be down anyways

**Comment by nschonni** [comment]
If you look at the issue tracker https://github.com/fiorix/freegeoip it looks like there has been some hosting issues lately. It may be worth looking at setting up a GC instance since the service is all available from the repo and make the country content take a custom URL for the API

**Comment by bsouster** [comment]
Any idea how long this might take to fix? CIC has a lot of content using Country Location, so we'll need to do something if it's going to be down a while.

I tested it again this morning on 4 different computers with IE, FF and Chrome with varying results. FF is the only one that consistently works.

**Comment by LaurentGoderre** [comment]
None of theme are working, the Firefox is only working because of your cache. If you clear it, it will stop working.

As to when this going to be fixed, this is completely outside of our control because it's a third party site. That being said, the source code is open source and instructions are provided to host it yourself so if this is a high priority for your department you can host the service yourself.

**Comment by bsouster** [comment]
As far as hosting, do you think it's something departments should do independently or centralized, maybe with Canada.ca?

I know the tests with centralized mega-menu and features didn't pan out for the latest GCWeb launch; maybe this would be a similar situation.

I'll try to get this moving on our servers either way -- just trying to think ahead.

**Comment by LaurentGoderre** [comment]
Seems like the hosting issue were resolved, the server is back online!
