### ISSUE TITLE
Repo has been removed from Google search results by bad DMCA takedown notice

### ISSUE THREAD

**Issue by cvrebert** [wet-boew/wet-boew#6422]
This repo is URL number 94 on https://www.chillingeffects.org/notices/10275257
Context: https://news.ycombinator.com/item?id=8848544

**Comment by crochefort** [comment]
Just wondering where is the Porn stuff here ... 

@pjackson28 @LaurentGoderre  if your fireweall block it ... here's the info...
The sender is NSFW by the way!! 

https://www.chillingeffects.org/notices/10275257#
Copyright claim #3

KIND OF WORK:movie
DESCRIPTIONThe materials reported in this notice are the copyrighted DVD/videos of Wicked Pictures. A representative list of these works is available at http://www.wickedpictures.com

#94 https://github.com/wet-boew/wet-boew

**Comment by CalvinRodo** [comment]
It seems like it's just a script that went wrong, there are quite a few github repos that are included in that dmca notice.

**Comment by crochefort** [comment]
Someone already did a counter-complaint for all github stuff!

https://news.ycombinator.com/item?id=8848597

**Comment by LaurentGoderre** [comment]
@cvrebert you are awesome!!! Thanks for letting us know!

**Comment by LaurentGoderre** [comment]
The issue seems to be resolved thanks to counter notification
