### ISSUE TITLE
Geomap: Set projection based on Longitude and Latitude pair?

### ISSUE THREAD

**Issue by josephbr** [wet-boew/wet-boew#6423]
Would it be possible to add the feature mentioned in this comment to Geomap?
https://github.com/wet-boew/wet-boew/issues/6373#issuecomment-67555230

Namely the idea of only requiring a longitude and latitude pair and having the map take care of the projection work for you. Currently I have found it considerably difficult to get Geomap to zoom into the correct spot.

**Comment by LaurentGoderre** [comment]
@jvanulde please respond

**Comment by jvanulde** [comment]
@josephbr this is now possible. We have added support for some additional configuration options as follows:

    ...   
    center: [ -123, 49 ],
    zoomLevel: 5
    ...

Configured this way the map will load centered on the LonLat configured in the center parameter and will be zoomed into the level specified in the zoomLevel parameter.

**Comment by hsrudnicki** [comment]
Just by occasion, are you ready to close this issue or otherwise?

**Comment by jvanulde** [comment]
Yes we can close.
