### ISSUE TITLE
Zebra striping conflicting with table styles

### ISSUE THREAD

**Issue by muling** [wet-boew/wet-boew#6432]
We have a table row header that spans multiple rows.  This table has zebra striping applied.  However, it seems that the row header (first column) is no longer styled properly when this is applied.  Row headers that have the first row (of the second column) highlighted cause the row header to not be styled.  

![zebra-bug](https://cloud.githubusercontent.com/assets/2365028/5671760/893b3986-9758-11e4-8e65-7a99ee36eefa.JPG)

**Comment by pjackson28** [comment]
Could you please identify how you applied the zebra striping? There technically are three ways of doing it. Please also provide the table markup (at least first few rows). Please also provide a screenshot of what the row header is supposed to look like (so just provide an image with zebra striping off).

**Comment by muling** [comment]
This is what it is supposed to sort of look like (WET3 look):
![naefs-info](https://cloud.githubusercontent.com/assets/2365028/5681187/159dbe0e-97e4-11e4-9b33-ebd5317a3058.JPG)

This is a portion of the markup:
![naefs-info-table-markup](https://cloud.githubusercontent.com/assets/2365028/5681243/c3030432-97e4-11e4-990b-d4cacbc1e539.JPG)

**Comment by pjackson28** [comment]
I just tried your markup and don't get the dark grey column and row headers like you do. Do you have any custom CSS that you are applying? If so, then perhaps your CSS doesn't have enough specificity to override the Bootstrap zebra striping CSS.

**Comment by muling** [comment]
No we don't have any custom classes except for one small one.  When I disable that, it makes no difference.

th:first-child {
    white-space: normal !important;
}

**Comment by pjackson28** [comment]
I was just able to reproduce on the Canada.ca theme but it doesn't occur on any other theme. It seems there is custom table CSS for the Canada.ca theme that doesn't play well with the Bootstrap zebra striping. Please file the issue in the wet-boew/GCWeb repository (and close here) as the issue is exclusive to the Canada.ca theme.

/cc @masterbee @shawnthompson

**Comment by LaurentGoderre** [comment]
I believe this is related to https://github.com/wet-boew/GCWeb/issues/329

**Comment by shawnthompson** [comment]
We have to remove those styles from GCWeb....

**Comment by shawnthompson** [comment]
Removed the custom table styles from GCWeb in https://github.com/wet-boew/GCWeb/pull/881. This should fix your problem. Thanks

**Comment by LaurentGoderre** [comment]
@muling can you confirm that updating to the new version fixes the issue?

**Comment by muling** [comment]
We are using version 4.0.10, and it doesn't seem to fix the issue as far as I can tell.

**Comment by LaurentGoderre** [comment]
Did anything change when you updated it?

**Comment by muling** [comment]
Do you mean change anything in the template?  Not that I am aware.

**Comment by LaurentGoderre** [comment]
No, I mean did the table look change when you updated to v4.0.10?

**Comment by muling** [comment]
No.  What is it supposed to look like?

**Comment by LaurentGoderre** [comment]
The display of the table should have changed when you updated to v4.0.10....Are you sure it is correctly applied?

**Comment by muling** [comment]
There are CSS customizations, but even when I totally remove our customizations, the table still does not apply the correct table striping.

**Comment by LaurentGoderre** [comment]
Did you follow Bootstrap's documentation?

http://getbootstrap.com/css/#tables-striped

**Comment by muling** [comment]
You can see our code in the comments above.  The examples in that link do not cover what we need in our table.

**Comment by hsrudnicki** [comment]
Are you ready to close this issue?

**Comment by muling** [comment]
Yes thanks.
