### ISSUE TITLE
Tabbed Interface - Carousel: 

### ISSUE THREAD

**Issue by SMLGCP** [wet-boew/wet-boew#6433]
Hello

I just had a question about this plugin, I was recently made aware that bootstrap's version of this plugin was not accessible and was wondering if this one was and what was changed to make this accessible? what makes them different?

Many thanks

SL

**Comment by pjackson28** [comment]
This tabbed interface - carousel plugin was built from scratch. It was designed to achieve a high level of accessibility by conforming to WCAG 2.0 level AA and implementing WAI-ARIA (in particular the tabpanel design pattern). It has been tested with screen readers as well (Jaws and NVDA in particular).

**Comment by SMLGCP** [comment]
Thanks' a lot for clarifying appreciate it.
