### ISSUE TITLE
Responsive table 

### ISSUE THREAD

**Issue by olegk1** [wet-boew/wet-boew#6437]
Hi guys: 

I've applied .responsive-table class to my table, but it doesn't seem to work as I don't see horizontal scrollbar below the table in mobile view. 

Could you help please? Thanks.

Here's the example code: 
```
<details>
    <summary class="h2">
        <h2>Main collapsible bar TITLE</h2>
    </summary>
    <div class="wb-tabs">
        <div class="tabpanels">
            <details open="open">
                <summary>
                    <h3>2013-14 tab</h3>
                </summary>
                <div class="parent-boxTabs">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default wb-toggle" data-toggle='{"selector": "details", "parent": ".parent-boxTabs", "type": "on"}'>OPEN ALL</button>
                        <button type="button" class="btn btn-default wb-toggle" data-toggle='{"selector": "details", "parent": ".parent-boxTabs", "type": "off"}'>CLOSE ALL</button>
                    </div>
                    <details>
                        <summary>
                            <h4>Nested collapsible bar TITLE 1 (2013-14 tab)</h4>
                        </summary>
                        <div>
                             <div class="table-responsive transparency-tbl">           
  <table class="table table-bordered">
   <caption class="text-left">Travel Expenses - 2014</caption>
    <thead> 
   	   <tr>
            <th>Date(s)</th>
            <th>Purpose</th>
            <th>Destination</th>
            <th>Total Cost</th>
        </tr>
     </thead>
     <tbody>   
        <tr>
            <td>21/05/14</td>
            <td>Lorem Ipsum is simply dummy tex</td>
            <td>Lorem Ipsum is simply dummy tex</td>
            <td class="text-right more-info">
            <details>
               <summary>$00.00</summary>
             <ul class="list-unstyled doubleLineSpace text-left pddn-left-sm fontSize75">
             <li>Air Fare: -</li>
             <li>Other Transport: 00</li>
             <li>Accommodation: -</li>
             <li>Meals / Incidentals: 00</li>
             <li>Other: -</li>
             <li>Describe:</li>
             </ul>
            </details> 
            </td>
        </tr>
        <tr>
            <td>03/05/14 to 09/05/14</td>
            <td>Lorem Ipsum is simply dummy tex</td>
            <td>Lorem Ipsum is simply dummy tex</td>
            <td class="text-right more-info">
            <details>
               <summary>$00</summary>
             <ul class="list-unstyled doubleLineSpace text-left pddn-left-sm fontSize75">
             <li>Air Fare: $00</li>
             <li>Other Transport:$00</li>
             <li>Meals / Incidentals:$00</li>
             <li>Other: -</li>
             <li>Describe:</li>
             </ul>
            </details> 
            </td>
        </tr>
</tbody>  
</table>
</div>  
                        </div>
                    </details>
                    <details>
                        <summary>
                            <h4>Nested collapsible bar TITLE 2 (2013-14 tab)</h4>
                        </summary>
                        <div>
                            Nested collapsible bar TITLE2 content (2013-14 tab)
                        </div>
                    </details>
                </div>
            </details>
            <details >
                <summary>
                    <h3>2012-13 tab</h3>
                </summary>
                <div class="parent-boxTabs2">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default wb-toggle" data-toggle='{"selector": "details", "parent": ".parent-boxTabs2", "type": "on"}'>OPEN ALL</button>
                        <button type="button" class="btn btn-default wb-toggle" data-toggle='{"selector": "details", "parent": ".parent-boxTabs2", "type": "off"}'>CLOSE ALL</button>
                    </div>
                    <details>
                        <summary>
                            <h4>Nested collapsible bar TITLE 1 (2012-13 tab)</h4>
                        </summary>
                        <div>
                            Nested collapsible bar TITLE 1 content (2012-13 tab)
                        </div>
                    </details>
                    <details>
                        <summary>
                            <h4>Nested collapsible bar TITLE 2 (2012-13 tab)</h4>
                        </summary>
                        <div>
                            Nested collapsible bar TITLE2 content (2012-13 tab)
                        </div>
                    </details>
                </div>
            </details>
        </div>
    </div>
</details>

```

**Comment by pjackson28** [comment]
I just tried it and it works for me on FF once there is not enough room to fit the table, even with content wrapping. The scroll bar doesn't show up for me until there is not enough room.

**Comment by olegk1** [comment]
Are you talking about scroll bar right below the table, not browser window's scroll bar? For me scroll bar right below the table (as it is in WET's example) doesn't appear at all, but browser window's scroll bar appears at about 768px narrower. I checked it in both FF and Chrome. I'm using exactly the same code as I posted here.

**Comment by olegk1** [comment]
The only way I can see the table being displayed as it should (by WET) in mobile is when I moved it up directly inside "main collapsible bar" details. But neither inside tabbed interface, not inside nested collapsible bar inside tabbed interface it doesn't work as it should. But by our design tables should be presented inside tabbed interface's nested collapsible bars. Is it possible at all?

**Comment by pjackson28** [comment]
Here is what I see in Firefox and Chrome with the markup you provided (no changes). The image shows the scrollbar that appears for the table once it overflows the tabpanel.

![scrollbar](https://cloud.githubusercontent.com/assets/1326498/5709684/ecea4a80-9a69-11e4-8ace-70395a6dc0c9.png)

**Comment by pjackson28** [comment]
Note that you don't even need to use table-responsive inside a tabpanel as it takes care of its own overflowing (so suggest removing table-responsive in this case altogether as it is not needed).

**Comment by olegk1** [comment]
I removed table-responsive inside tabpanel, but it didn't change anything. My tables still don't get displayed with scroll bars below inside tabbed interface, only inside main bar directly. Is it possible that we don't use the same WET release as you do? We've just updated today to the latest development release.

**Comment by pjackson28** [comment]
I'm using the latest WET code so I'm not sure why it isn't working for you. Are you seeing any clipping? The only time the scroll bar will show up is when the content overflows the container.

**Comment by olegk1** [comment]
I was told we were also using the latest WET code, and yes - I am not sure why it isn't working for me either.

**Comment by pjackson28** [comment]
Which zip file are you using? Could you please provide the link?

**Comment by josephbr** [comment]
Here is the link. It's the latest development release for v4.0:
https://github.com/wet-boew/wet-boew-dist/archive/v4.0-dist.zip

**Comment by pjackson28** [comment]
I just tried your code above with one of the html files in that zip file and I get the same scrollbar as I did before (so looks like my screenshot). Don't know why it isn't working for you. Could there be any custom CSS or JS that could be interfering? Do you still get the issue if you take the zip file, and add you code above to one of the HTML files (so no other changes)?

**Comment by olegk1** [comment]
That's quite possible that there is some interference. We've been trying to understand what's going on.

**Comment by hsrudnicki** [comment]
Are you ready to close this issue?

**Comment by josephbr** [comment]
Yes, the feature has been added and I have nothing further to ask.
