### ISSUE TITLE
Multi-page form UX

### ISSUE THREAD

**Issue by andrewleith** [wet-boew/wet-boew#6438]
We have applications that essentially boil down to multi-page forms.  When a user starts one, we want their focus to be on completing that task.  That being said, the header becomes rather redundant and unnecessary and takes up a lot of screen real estate (154px according to Chrome). It also provides them the opportunity to navigate away in the middle of the task, which is not wanted.

Has any work been done for alternate layouts of this type of use-case? Perhaps the header could collapse or shrink or something else?

Thanks,
Andrew

**Comment by sgdowney** [comment]
Perhaps the full screen overlay could meet your needs?
http://wet-boew.github.io/wet-boew/demos/overlay/overlay-en.html

**Comment by andrewleith** [comment]
I suppose it could (assuming I can make it work without JS).  But if that's "allowed", why couldn't I just not include the header on my pages during the form and get functionally the same thing?

**Comment by LaurentGoderre** [comment]
@thomasgohard would be best placed to answer this question. Also note that there is a related discussion in #6367

**Comment by thomasgohard** [comment]
@andrewleith @pcwsmith and I are working on this right now. Something is coming shortly.

**Comment by andrewleith** [comment]
We are going to just scroll the header out of view when our pages are long enough to warrant it.  Not perfect, but it will work.

**Comment by thomasgohard** [comment]
@andrewleith do not scroll the header out of view. Depending on how you implement it, you may introduce accessibility problems.

The Content and information architecture specification now specify how to deal with this use case. The details are in section 6.4 of the specification. You can find the specification on GCpedia.

**Comment by andrewleith** [comment]
I'll have a read through.  We already implemented this and has passed all of our accessibility testing.  I'll see if there is time to change it based on those specifications.
