### ISSUE TITLE
IE Compatibility Mode instructions need to be reviewed.

### ISSUE THREAD

**Issue by mankev** [wet-boew/wet-boew#6440]
After receiving the following email:

"Not sure who takes care of this at Dept. X, but  the deptx.xx.ca server is forcing compatibility mode in IE. This breaks the layout when the site is viewed in IE.
The solution is documented at http://wet-boew.github.io/wet-boew/docs/server-en.html."
(BTW our server is not forcing compatibility mode)

We read the solution, however it was not clear whether it applied to Intranets or Internets. The article claims that "IE displays Intranet web pages using Compatibility View" although I cannot find anything to back up this claim. Later in the troubleshooting section the article refers to "public facing sites", but once again uses an "Intranet Zone Setting" as an example. Either way the article should just stick to the subject and forget about Intranets and Internets.

There are some links to an MSDN article on configuring the server to send X-UA-Compatible headers, but this could lead to problems if the solution is taken literally from the article because it will set the browsers to IE7 compatibility mode (yes the article does specify edge, but often it is just the link to the solution that gets passed around).
<Location /store>
   Header set X-UA-Compatible “IE=EmulateIE7”
</Location> 

Finally using the X-UA-compatible setting for HTML5 sites is redundant since using the HTML5 doctype (<!DOCTYPE html> ) has the same effect as using the X-UA-Compatible directive:
http://msdn.microsoft.com/en-us/library/jj676915%28v=vs.85%29.aspx

"Use the following value to display the webpage in edge mode, which is the highest standards mode supported by Internet Explorer, from Internet Explorer 6 through IE11.

    <meta http-equiv="x-ua-compatible" content="IE=edge" >

Note that this is functionally equivalent to using the HTML5 doctype. It places Internet Explorer into the highest supported document mode. "

and

"Because it forces all pages to be opened in standards mode, regardless of the version of Internet Explorer, you might be tempted to use edge mode for all pages viewed with Internet Explorer. Don't do this, as the X-UA-Compatible header is only supported starting with Internet Explorer 8. "

Cheers
KM

**Comment by LaurentGoderre** [comment]
This might be true in theory but not in practice, some IE setting makes it ignore the DOCTYPE and go to compatibility mode. 

In reality, it's not your server causing Compat Mode, it's usually a setting in corporate IE that makes it detect .gc.ca website as being Intranety sites and render it in Compat Mode. The easiest way is to add the X-UA-compatible for sites using WET4

**Comment by pjackson28** [comment]
True that it technically it is not the server that is triggering compatibility mode, but considering the reality of desktop configurations, it is best to be proactive and use the X-UA-Compatible header (since this compatibility mode issue is one of the most common issues being raised). Also note that the X-UA-Compatible header being supported starting with IE8 is irrelevant since compatibility mode brings rendering back to IE7 (so IE7 edge mode doesn't help the situation).

**Comment by hsrudnicki** [comment]
Are you ready to close this issue or otherwise?

**Comment by mankev** [comment]
Yes, thank you.
