### ISSUE TITLE
Datepicker Polyfill inside of a tab element will scroll the tab rather than displaying above the tab

### ISSUE THREAD

**Issue by andre-d** [wet-boew/wet-boew#6441]
I have a form inside of a tab, one of the elements is a date picker.  When selecting the date picker, the calendar element exists inside the tab and depending on the position may require scrolling of the tab to get to the date picker.

I think the date picker calendar should exist globally on the page and always attempt to be visible at the highest level above the tab.

code:

     <div class="wb-tabs" id="tabs">
	<div class="tabpanels" >

		<details id="test">
			<summary>Test</summary>
			<input type="date">

		
		</details>
		
	</div>
    </div>

Screenshot:

![test](https://cloud.githubusercontent.com/assets/714162/5724117/4e178e14-9b17-11e4-9bd1-a647a98312c7.png)

**Comment by LaurentGoderre** [comment]
Not a bad idea. @thomasgohard is it possible to have some usability review on how we can improve the display of the date picker?

**Comment by pjackson28** [comment]
The date picker does exist globally (only one instance per page). The problem you are encountering is tabpanels is a relative container and the date picker is absolutely positioned meaning that the date picker is confined to the boundary of tabpanels and it is not able to push out those boundaries when there is not enough room. All you can do is ensure that the tab panel has sufficient height/width to fit the date picker (just like with any other absolutely positioned content).

**Comment by pjackson28** [comment]
I should also clarify that the tab panel has to have overflow hidden to actually behave correctly as a tab panel (otherwise transitions and other aspects won't work correctly). So that is why you are getting the clipping when there is not enough room to fit the date picker. This should be quite the edge case as all the following criteria would need to be met for this to happen:

1. Browser does not have native support for a date picker (only Firefox and IE for now)
2. Tabbed interface used with an input type="date" field inside the tab panel.
3. Insufficient content in the tab panel to fit a date picker.

**Comment by andre-d** [comment]
I am hitting this edge case in a UI mockup, IE and Firefox both do not support the date element as you pointed out.  The calendar picker is very large and you need around 300px of space below the input element within the tab to ensure this works as expected.  I have a form field to pick a date within a tab, the date picker actually has four dropdowns and a submit button below it and it still creates a scroll bar on the tab.

Regardless though, the calendar dropdown should not exist within the tab ever, it exists within the window to populate the field which exists in the form (just like how a select element works)

**Comment by andre-d** [comment]
To clarify, I believe it is unexpected behavior for the picker UI of a select, date, color, or any abstract GUI to exist within the flow of the document.  The intention is to emulate what the browser will be doing in the future once supported (or other browsers do). 

Additionally, I believe it is unexpected for the document to have consider leaving space for something within a child for something which is supposed to be abstracted away to the browser.

**Comment by pjackson28** [comment]
The original author positioned it right after the initiating button to cover the use case of a user navigating out with a keyboard and staying in proximity of the actual button and field. Moving the date picker to a global context would leave keyboard users far away from the original location if the navigate out.

A way of fixing that would be to manage focus like with the Lightbox. The triggering button would need to take care of moving focus to the date picker element (already done) and then focus would need to be returned to either the button or the input field on close.

In theory it shouldn't be too much work. Would you be interested in creating a PR to implement such a change?

**Comment by andre-d** [comment]
I will look at creating a PR for this in my next down time (within the next few weeks).

**Comment by thomasgohard** [comment]
@LaurentGoderre what do you mean by <q>the display of the date picker</q>? Are you talking about the positioning or the layout and design? We already started looking at layout and design improvements in https://github.com/wet-boew/wet-boew/issues/6143.

**Comment by LaurentGoderre** [comment]
mostly positioning but that would go with the layout and design as well

**Comment by thomasgohard** [comment]
In terms of positioning, I agree with @andre-d: The date picker should appear above the tab in this scenario.

Maybe we should test how the component behaves in various scenarios to identify other situations like the one with tabs cause problems.

**Comment by LaurentGoderre** [comment]
Note that this WCAG common failure applies to this. According to Failure Example 1 and the title it would fail but according to the test, propperly managing the focus would not make it fail.

http://www.w3.org/TR/2014/NOTE-WCAG20-TECHS-20140916/F85

**Comment by hsrudnicki** [comment]
Are you ready to close this issue or otherwise?

**Comment by hsrudnicki** [comment]
Made "Going Stale" to close this issue based on the other referenced and closed issue (7215) or otherwise? Either way, @LaurentGoderre @andre-d please update this issue's status, thank you
