### ISSUE TITLE
Tables: Datatable

### ISSUE THREAD

**Issue by hamdaneh** [wet-boew/wet-boew#6445]
Hi,
I am trying to use data-wb-tables attribute of the : table class="wb-tables table  table-hover"   element of my html. But whenever I pass a json object containing a function, it complains about it.

How do we pass a function ? Here is my example:

data-wb-tables='{ "ajax" : {"url" : "${api_url}" }, 
			    "deferRender": true, 
			    "fnRowCallback": "function(nRow, aData, iDisplayIndex) {console,log('test');}"
}'

Is there another way to do that ? Maybe in javascript, re-initialize the table and then add the callback? Whenever I try to do that, it complains that the table was already initialized.

Please help!
Thanks.
Houda.

**Comment by pjackson28** [comment]
Passing functions through the data attribute isn't supported in WET. What about using events instead? http://datatables.net/reference/event/

**Comment by LaurentGoderre** [comment]
The console.log breaks the HTML because it use the single quote which would end the data-wb-tables attributes. SIngle quotes inside the JSON needs to be encoded

**Comment by LaurentGoderre** [comment]
To add to what @pjackson28 said, you should never send a function via JSON, the only way to make a function provided via JSON is to use the extremely unsafe `parse` method which we don't use.

**Comment by hamdaneh** [comment]
Ok, will try that. What type of event you recommend  ? draw ? 

the goal here is to change a cell and  add "html markup" (checkbox using the cell data).

**Comment by pjackson28** [comment]
The draw event would probably make the most sense.

**Comment by pjackson28** [comment]
Note that WET provides the wb-updated.wb-tables event (extension of the draw event) which would be even safer to use as it ensures all the WET processing after a draw event has completed. Here is the code taken from the Tables documentation:

```js
$( document ).on( "wb-updated.wb-tables", ".wb-tables", function( event, settings ) {
});

$( ".wb-tables" ).on( "wb-updated.wb-tables", function( event, settings ) {
});
```

**Comment by hamdaneh** [comment]
Thank you so much! will try it.

**Comment by pjackson28** [comment]
@LaurentGoderre Did you mean the eval() method rather than the parse method?

**Comment by LaurentGoderre** [comment]
Yes sorry.

**Comment by chyne** [comment]
@hamdaneh Did you get this working? I've only way I have been able to get a checkbox added to a column is to initialize the datatable in code, which means I need to drop the wb-tables class (to prevent double initialization), but then a lot of the styling seems dependent on the wb-tables class being present.

**Comment by LaurentGoderre** [comment]
You shouldn't modify the classes. I will need to investigate

**Comment by hamdaneh** [comment]
I had to do it in the javascript code, the same way as you did (drop the table and initialize it), and then pass the json object with advanced settings (functions to add html stuff).

**Comment by LaurentGoderre** [comment]
This may work as a work around but this is highly discouraged. We should work on a more elegant fix for this.

**Comment by chyne** [comment]
I am open to suggestions. I am passing functions that define how to render certain rows, so I would think that hooking into the draw.dt event would be too late.

**Comment by LaurentGoderre** [comment]
@hamdaneh @chyne you don't need to use the data attributes to specify callbacks. Any of the DataTable callback can be added using the following approach

<script>
(function() {
	window[ "wb-tables" ] = {
		rowCallback: function( row, data ) {
			
		},
		initComplete: function ( settings, json ) {

		},
	};
})();
</script>

**Comment by hsrudnicki** [comment]
@hamdaneh @chyne @pjackson28 @LaurentGoderre : Can this issue be closed or otherwise?

**Comment by hamdaneh** [comment]
Yes! Please close.
