### ISSUE TITLE
Should an h1 contain language tag and/or em tag?

### ISSUE THREAD

**Issue by nathanpw** [wet-boew/wet-boew#6447]
Hi, I have 2 scenarios for an `<h1>` that we are seeing:

1. The h1 contains an organization name which is only available in french. For example:

```
<h1 id="wb-cont">Notes for an address at the annual convention of the <span lang="fr">Association québécoise pour l’enseignement en univers social</span> and the Association for Canadian Studies</h1>
```

2. The h1 contains the name of legislation. For Example:

```
<h1>Annual Report to Parliament on the <em>Access to Information Act</em> 2013-2014</h1>
```

How would you recommend handling these situation, is there any tbs policy or standard for dealing with these situations? Are the above examples correct?

**Comment by nathanpw** [comment]
@pjackson28 @StephenOTT

**Comment by pjackson28** [comment]
@nathanpw There are no issues with either of the examples you provided. WCAG 2.0 requires that changes in language be identified programmatically (which is being done in the 1st example) and there is no issue with nesting an <code>em</code> element in an <code>h1</code> element.

**Comment by StephenOTT** [comment]
Handling this manually (assuming it is not a issue against the standards and policy), but with a CMS it will need some tweaking around how the CMS UI handles this.  Most CMS' will have their Title field be their page title as well as the H1 on the page.  So some design thinking needs to be done from a implementation standpoint.

Typically a title field in CMS won't allow can HTML markup to be added.

**Comment by LaurentGoderre** [comment]
The markup could be stripped from the title tag by the CMS. It is acceptable to not have the language tag in the title tag if the portion in a different name is a proper name (like in the example)

**Comment by Bgolden67** [comment]
The only time we've experienced an issue with adding any tag to our h1 with our WMCS (Teamsite) is when we were calling an XML feed for our RSS before we went to news.gc.ca, the xml would "break" if that wasn't stripped before it was called to make the RSS feed or used to auto populate a "What's New" page
I don't believe it was ever resolved so the team here had to not put <em> in the h1 field. thankfully it wasn't a very common requirement. As for the lang attribute, it would have caused the same result but we've not had any instances where we would have been required

**Comment by LaurentGoderre** [comment]
Can we close this?

**Comment by nathanpw** [comment]
Yeap, this can be closed. Thanks for the responses everyone! :)
