### ISSUE TITLE
GitHub very handy trick for reviewing PRs

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/wet-boew#6449]
Someone just thought me a GitHub trick that is just too good not to share. On a PR, when reviewing the difference section, if you append `?w=1` to the URL it tells GitHub to ignore difference in whitespace. This make it much easier to review PR when the indentation changed

**Comment by Pacoup** [comment]
Woa, brilliant. Thanks for the tip.

**Comment by thomasgohard** [comment]
That tip and more here: https://github.com/tiimgreen/github-cheat-sheet.

**Comment by shawnthompson** [comment]
:+1: Thanks for sharing!
