### ISSUE TITLE
Avoid ajax mega menu

### ISSUE THREAD

**Issue by vallieresc** [wet-boew/wet-boew#6452]
We are running an application that regenerates markup for multiple client apps and our theme files are located on our CDN. This means that the generated content is completely separate from the theme. It would be very difficult if even possible with our setup to generate this mega menu. 

I tried to implement the mega menu in our generated markup but JS doesn't seem to enable it. I get a JS error: 
Uncaught TypeError: Cannot read property 'nodeName' of undefined in web-boew.min.js
It's related to the mega menu anchor tag I believe.

Is there a way to implement the mega menu inline?

**Comment by LaurentGoderre** [comment]
@vallieresc your setup shouldn't prevent you from using the Ajax approach. Can you give some details on why you aren't able to use the AJAX approach?

**Comment by vallieresc** [comment]
@LaurentGoderre I cannot use the AJAX approach because the menu has to be generated for every client application running off our framework. We have over 15 clients. Our generator is not on the same server as the theme (where the ajax needs to be). We also cannot create 15 AJAX menus in our theme because the theme has no knowledge of different apps, it only provides the css, js and images we need for our layout.

**Comment by LaurentGoderre** [comment]
Wouldn't you have the same problem with the top level menu then?

**Comment by Pacoup** [comment]
@vallieresc Did you try using the rendered code from a browser?

That's what we've been doing at CIHR because it allows for local testing (AJAX requests can only run from a domain; the same domain, to prevent CSRFs) and it's faster to load (no need for an additional HTTP request, not to mention that particular request will often execute after everything else has loaded, making the website menu appear to load quite slowly).

```HTML
<nav role="navigation" id="wb-sm" class="wb-menu visible-md visible-lg wb-menu-inited wb-navcurr-inited" typeof="SiteNavigationElement">
  <div class="pnl-strt container visible-md visible-lg nvbar">
    <h2>Topics menu</h2>
    <div class="row">
      <ul class="list-inline menu" role="menubar">
        <li class="">
          <a href="#project" class="item" tabindex="0" aria-posinset="1" aria-setsize="3" role="menuitem" aria-haspopup="true">WET project<span class="expicon glyphicon glyphicon-chevron-down"></span></a>
          <ul class="sm list-unstyled" id="project" role="menu" aria-expanded="false" aria-hidden="true">
            <li><a href="http://wet-boew.github.io/v4.0-ci/index-en.html#about" tabindex="-1" aria-posinset="1" aria-setsize="9" role="menuitem">About the Web Experience Toolkit</a></li>
            <li><a href="http://wet-boew.github.io/v4.0-ci/index-en.html#benefits" tabindex="-1" aria-posinset="2" aria-setsize="9" role="menuitem">Benefits</a></li>
            <li><a href="http://wet-boew.github.io/wet-boew/docs/ref/accolades-en.html" tabindex="-1" aria-posinset="3" aria-setsize="9" role="menuitem">Awards, articles and videos</a></li>
            <li><a href="http://wet-boew.github.io/wet-boew/docs/events-en.html" tabindex="-1" aria-posinset="4" aria-setsize="9" role="menuitem">Events</a></li>
            <li><a href="https://github.com/wet-boew/wet-boew/" tabindex="-1" aria-posinset="5" aria-setsize="9" role="menuitem">Main project page</a></li>
            <li><a href="http://wet-boew.github.io/v4.0-ci/License-en.html" tabindex="-1" aria-posinset="6" aria-setsize="9" role="menuitem">Terms and conditions</a></li>
            <li><a href="http://wet-boew.github.io/wet-boew/docs/versions/rdmp-en.html" tabindex="-1" aria-posinset="7" aria-setsize="9" role="menuitem">Roadmap of past and future releases</a></li>
            <li><a href="http://wet-boew.github.io/wet-boew/docs/versions/index-en.html" tabindex="-1" aria-posinset="8" aria-setsize="9" role="menuitem">Version history</a></li>
            <li><a href="http://www.tbs-sct.gc.ca/ws-nw/index-eng.asp" tabindex="-1" aria-posinset="9" aria-setsize="9" role="menuitem">About the Web Standards</a></li>
          </ul>
        </li>
        <li>
          <a href="#implement" class="item" tabindex="-1" aria-posinset="2" aria-setsize="3" role="menuitem" aria-haspopup="true">Implement WET<span class="expicon glyphicon glyphicon-chevron-down"></span></a>
          <ul class="sm list-unstyled" id="implement" role="menu" aria-expanded="false" aria-hidden="true">
            <li><a href="http://wet-boew.github.io/wet-boew/docs/start-en.html" tabindex="-1" aria-posinset="1" aria-setsize="4" role="menuitem">Getting started with WET</a></li>
            <li><a href="http://wet-boew.github.io/wet-boew/docs/versions/dwnld-en.html" tabindex="-1" aria-posinset="2" aria-setsize="4" role="menuitem">Download WET</a></li>
            <li><a href="http://wet-boew.github.io/v4.0-ci/demos/index-en.html" tabindex="-1" aria-posinset="3" aria-setsize="4" role="menuitem">Working examples</a></li>
            <li><a href="http://wet-boew.github.io/wet-boew/docs/index-en.html" tabindex="-1" aria-posinset="4" aria-setsize="4" role="menuitem">Documentation</a></li>
          </ul>
        </li>
        <li>
          <a href="#contribute" class="item" tabindex="-1" aria-posinset="3" aria-setsize="3" role="menuitem" aria-haspopup="true">Contribute to WET<span class="expicon glyphicon glyphicon-chevron-down"></span></a>
          <ul class="sm list-unstyled" id="contribute" role="menu" aria-expanded="false" aria-hidden="true">
            <li><a href="http://wet-boew.github.io/wet-boew/docs/bugs-en.html" tabindex="-1" aria-posinset="1" aria-setsize="4" role="menuitem">Filing a bug or an issue</a></li>
            <li><a href="http://wet-boew.github.io/wet-boew/docs/pull-en.html" tabindex="-1" aria-posinset="2" aria-setsize="4" role="menuitem">Creating a pull request</a></li>
            <li><a href="http://wet-boew.github.io/wet-boew/docs/pull-en.html#test" tabindex="-1" aria-posinset="3" aria-setsize="4" role="menuitem">Testing your code</a></li>
            <li><a href="http://wet-boew.github.io/wet-boew/docs/start-en.html#develop" tabindex="-1" aria-posinset="4" aria-setsize="4" role="menuitem">Developing for WET</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
```

There may be technical reasons you might not want to do that, though. @LaurentGoderre?

**Comment by vallieresc** [comment]
@LaurentGoderre No the top level menu I can generate them in our master layout. I can generate all the markup from the master layout but any external assets are in our CDN. There's no link between the 2 except for the calls I make in the master layout for the css, js and images. Each client app are configured via xml and filters so devs can hide menu items or change them for a specific page based on conditions.

@Pacoup I tried but my code was slightly different. I'll try yours.

**Comment by LaurentGoderre** [comment]
@Pacoup the AJAX menu is not delayed because of the AJAX but rather because it waits until the page load to enhance it. The AJAX menu also gets cached when the server is set up properly which menas that it only loads kit on the first page.

There is also some significant risk to doing this method because you use ARIA code that is supposed to be added automatically which could lead to accessibility failures

Last but not least, with this approach, the menu is completely unusable if JavaScript is disabled of if jQuery fails to load. The AJAX method ensures that the links to the landing pages on the top level menu items only get replaced if JavaScript is working.

**Comment by LaurentGoderre** [comment]
@vallieresc @Pacoup it is highly discouraged to use that approach

**Comment by LaurentGoderre** [comment]
@vallieresc is there any reason why you can't have the menu as a static HTML file for all the different apps?

**Comment by vallieresc** [comment]
@Pacoup Your solution works great :) I will be going with it!

@LaurentGoderre I could have them as different AJAX files on the CDN but then I would need 15 conditions to load the proper file based on the client app currently running and keep maintaining these conditions as we go. The client devs would have a hard time updating the AJAX menu since they don't play with the theme files, only I do. Also this would make the menu non dynamically modifiable by client devs since it would be static. They must be modifiable at runtime.

I don't believe devs should be forced to use AJAX for the menu. We develop locally usually and it reduces the requests. There should be a way to bypass the AJAX if we don't want to go that route. 

I will be generating the ARIA codes and I have handled javascript disabled mega menu cases before. Worst case, I can create a small jquery script to override the default javascript disabled menu URLs.

Thanks for your help.

**Comment by LaurentGoderre** [comment]
@vallieresc that approach is not supported by WET and your solution can break in future versions of WET. Additionally this could lead to accessibility issues.

If you do go in this way, include the markup as it is in the AJAX file not the generated source so that ARIA and tabindex are generated by WET instead

**Comment by vallieresc** [comment]
@LaurentGoderre I tried but that caused a JS error in wet-boew.min.js. I could troubleshoot a bit further with the unminified version to narrow it down.

**Comment by LaurentGoderre** [comment]
That's most likely because you replaced a mandatory element, such as the `nav` element

**Comment by vallieresc** [comment]
everything is there

**Comment by LaurentGoderre** [comment]
Here is what I have

```html
<nav role="navigation" id="wb-sm" data-trgt="mb-pnl" class="wb-menu visible-md visible-lg" typeof="SiteNavigationElement">
<div class="pnl-strt container visible-md visible-lg nvbar">
<h2>Topics menu</h2>
<div class="row">
<ul class="list-inline menu" role="menubar">
<li><a href="#project" class="item">WET project</a>
<ul class="sm list-unstyled" id="project" role="menu">
<li><a href="http://wet-boew.github.io/v4.0-ci/index-en.html#about">About the Web Experience Toolkit</a></li>
<li><a href="http://wet-boew.github.io/v4.0-ci/index-en.html#benefits">Benefits</a></li>
<li><a href="http://wet-boew.github.io/wet-boew/docs/ref/accolades-en.html">Awards, articles and videos</a></li>
<li><a href="http://wet-boew.github.io/wet-boew/docs/events-en.html">Events</a></li>
<li><a href="https://github.com/wet-boew/wet-boew/">Main project page</a></li>
<li><a href="http://wet-boew.github.io/v4.0-ci/License-en.html">Terms and conditions</a></li>
<li><a href="http://wet-boew.github.io/wet-boew/docs/versions/rdmp-en.html">Roadmap of past and future releases</a></li>
<li><a href="http://wet-boew.github.io/wet-boew/docs/versions/index-en.html">Version history</a></li>
<li><a href="http://www.tbs-sct.gc.ca/ws-nw/index-eng.asp">About the Web Standards</a></li>
</ul>
</li>
<li><a href="#implement" class="item">Implement WET</a>
<ul class="sm list-unstyled" id="implement" role="menu">
<li><a href="http://wet-boew.github.io/wet-boew/docs/start-en.html">Getting started with WET</a></li>
<li><a href="http://wet-boew.github.io/wet-boew/docs/versions/dwnld-en.html">Download WET</a></li>
<li><a href="http://wet-boew.github.io/v4.0-ci/demos/index-en.html">Working examples</a></li>
<li><a href="http://wet-boew.github.io/wet-boew/docs/index-en.html">Documentation</a></li>
</ul>
</li>
<li><a href="#contribute" class="item">Contribute to WET</a>
<ul class="sm list-unstyled" id="contribute" role="menu">
<li><a href="http://wet-boew.github.io/wet-boew/docs/bugs-en.html">Filing a bug or an issue</a></li>
<li><a href="http://wet-boew.github.io/wet-boew/docs/pull-en.html">Creating a pull request</a></li>
<li><a href="http://wet-boew.github.io/wet-boew/docs/pull-en.html#test">Testing your code</a></li>
<li><a href="http://wet-boew.github.io/wet-boew/docs/start-en.html#develop">Developing for WET</a></li>
</ul>
</li>
</ul>
</div>
</div>
</nav>
```

**Comment by Pacoup** [comment]
@vallieresc Laurent's right, you should do it with the code straight from the AJAX file.

You just need to modify your ```<nav>``` element to this:
```HTML
<nav role="navigation" id="wb-sm" data-trgt="mb-pnl" class="wb-menu visible-md visible-lg" typeof="SiteNavigationElement">
```

**Comment by vallieresc** [comment]
Works! I didn't have the data-trgt attribute.
