### ISSUE TITLE
Table captions

### ISSUE THREAD

**Issue by Wenifred** [wet-boew/wet-boew#6457]
Hi there,

I was wondering if captions on a table could have some default styling. The caption doesn't seem to be very visible and it is usually the title of the table.  See example:
![19-01-2015 11-11-42 am](https://cloud.githubusercontent.com/assets/5551287/5803389/11aec712-9fcc-11e4-9071-9257713c636f.png)
Even if it was bold it may help. I played around with it, here is an example with a background colour, padding bigger font size.
![19-01-2015 11-18-11 am](https://cloud.githubusercontent.com/assets/5551287/5803534/2897aa1a-9fcd-11e4-8be5-e3caa4bc8333.png)
Just a suggestion, thanks.

**Comment by LaurentGoderre** [comment]
@Wenifred we don't add any default style to tables to avoid creating conflict with apps or existing content. Tables should be be styled using Bootstrap classes.

**Comment by Wenifred** [comment]
Oh I see.  I am trying to use WET styles as much as I can without adding too much customized CSS for the department publishers to use so when we migrate over to Canada.ca they would not have to recode everything again.  Are there any padding classes available to try to create what is above?  
Any chance of adding a dark grey background colour or any grey background colours?

**Comment by LaurentGoderre** [comment]
Here is the documentation for Bootstrap tables. It's best to keep to these styles.

http://getbootstrap.com/css/#tables

**Comment by Wenifred** [comment]
Okay, I see they do have a style for caption, but it isn't applied on WET.

    caption {
        padding-top: 8px;
        padding-bottom: 8px;
        color: #777;
        text-align: left;
    }

 I will add to our own style sheet, thanks.

**Comment by LaurentGoderre** [comment]
@Wenifred it's highly discouraged to use this snippet because it has accessibility and usability issues. In v4.0.11 there will be a Bootstrap override to fix the issue (#6455).

If you are to add custom style in the meantime, please use the following:

https://github.com/wet-boew/wet-boew/pull/6455/files#diff-93656052841a8c39fc075d98b607fb71R835

**Comment by Wenifred** [comment]
Okay will do, thanks.
