### ISSUE TITLE
Links to download canada.ca theme v4.0.10 are broken

### ISSUE THREAD

**Issue by biljanap** [wet-boew/wet-boew#6463]
I am trying to download the latest stable canada.ca theme from this page: http://wet-boew.github.io/wet-boew/docs/versions/dwnld-en.html#v40stable.
Links to both "Source code" and "Production files" are broken.
The same is for "Government of Canada Web Usability", "Government of Canada Intranet" and "Open Government Platform (OGPL)" themes but only to download "Production files".

**Comment by LaurentGoderre** [comment]
Yes...I am releasing them as we speak. I can't release them all at once

**Comment by biljanap** [comment]
Sorry, it was just my bad luck then :o)....and yours :o)
