### ISSUE TITLE
Should Remove "Regulations under this Act" Paragraph from Regulations Template

### ISSUE THREAD

**Issue by jdmlouis** [wet-boew/wet-boew#6466]
As Regulations will not have Regulations attached to them (only Acts have Regulations attached to them), the portion entitled "Regulations under this Act" should be removed as redundant from the Regulations Template.  

Quick link for review: http://wet-boew.github.io/themes-dist/GCWeb/regulations-en.html and http://wet-boew.github.io/themes-dist/GCWeb/regulations-fr.html

![regulations](https://cloud.githubusercontent.com/assets/675897/5857126/34a915cc-a217-11e4-8d29-c57c4bf6c5ce.PNG)

**Comment by pjackson28** [comment]
@jdmlouis Please file this issue in wet-boew/GCWeb as this issue is exclusive to the Canada.ca theme so will need to be addressed there.

**Comment by jdmlouis** [comment]
Thank you - I have refiled this issue and will close this one.
