### ISSUE TITLE
MP4 Video has trouble to display in IE 9

### ISSUE THREAD

**Issue by ikug** [wet-boew/wet-boew#6467]
Here there,

We have some videos in our website, and are facing problems of displaying in IE 9, but all works on the other browsers - Firefox and Chrome.

Currently my IE 9 is set up Browser Mode as IE9 compat view with Doc Mode as Quirks. My video won't be played or even not been seen in IE 9. Then I changed IE 2 modes to IE9 and IE9 standards, then kind of being seen but not able to be played.

I tried your "Multimedia Player - Video" working example in IE 9, and all the videos are not able to be played, and all showing Black screen with a control bar (but it has ended to the end already)

see the attached image.

BTW, we are using WET 4.0.10 in our app.

Please investigate to see what issue will be.

Thanks,

![image](https://cloud.githubusercontent.com/assets/10654702/5857518/6ddd47a2-a21a-11e4-84f3-1af742525bb5.png)

**Comment by LaurentGoderre** [comment]
@ikug video will not work in Compatibility view because of how Compatibility View is designed, besides WET sites should not be rendered using Compat View.

From the look of it it seems that your network is preventing you to play the video and not a bug in the player. It seems you network policies also prevent your IE to download font icons. I recommend testing your app outside of your network or submitting the issue with your IT department

**Comment by ikug** [comment]
Thank you for your apply.

I knew the IE Compat View is not working, but after switch to IE 9 and IE 9 standards, then the image above is what you can see.

I am just wondering as you said it might be our network block the video, but why Firefox and Chrome can play the video without any issue? They are all in the same network.

BTW, just adjust my version of WET, we are currently using WET 4.0.9.

**Comment by LaurentGoderre** [comment]
Normally IT departments don't customize Firefox or Chrome too much while but they often change settings for IE.

**Comment by ikug** [comment]
Please take a look the image below. I put both modes of IE as IE9 and IE 9 standard, but the video play and control button seems disappeared, (user can't see) but able to be played after clicking the dark area.

What kind of issue will occur this?


![image](https://cloud.githubusercontent.com/assets/10654702/5877010/176ce1cc-a2ea-11e4-8e23-d66a6acdc4a7.png)

**Comment by LaurentGoderre** [comment]
As I mentioned before, this ks font icons from being downloaded.is an network policy put in place by the IT department that bloc

**Comment by ikug** [comment]
Do you mean downloaded.js instead of downloaded.is?

**Comment by LaurentGoderre** [comment]
Laptop fail. This is what I meant to say

As I mentioned before, this is an network policy put in place by the IT department that blocks font icons from being downloaded.

**Comment by ikug** [comment]
Haha...

May I ask where I can find the download.js? From WET 4?

**Comment by LaurentGoderre** [comment]
There is no download.js, that was a typing error with my laptop where part of my comment got move around in a way that did not make sense.

To resolve this issue you need to call your IT department and ask them to allow font downloads in Internet Explorer
