### ISSUE TITLE
YouTube player - tracking with Google Analytics

### ISSUE THREAD

**Issue by crichard** [wet-boew/wet-boew#6468]
Is there any way to track when a youtube video is started or completed with WET 4.0.10 ?  Since the YT videos are loaded in an iframe, what works with the regular multimedia player does not work with youtube videos.

**Comment by lucas-hay** [comment]
Hi Cynthia, there is certainly a way and we (Service Canada) have a script to do this. Please touch base with me tomorrow to discuss. We have plans of sharing the script with the community but are working on some final tweaks before we share it.

**Comment by LaurentGoderre** [comment]
In the player, events are made to bubble so you can track all players the same way (irrespective of if it's native, flash or youtube)

```javascript
$(".wet-boew-multimedia").on("play", function() { });
```

**Comment by crichard** [comment]
This works.  Merci Laurent.
```
wb.doc.on("play", ".wb-mltmd", function() {});
```
