### ISSUE TITLE
Highlight specific date on the Date Pick

### ISSUE THREAD

**Issue by E1D1** [wet-boew/wet-boew#6469]
I would like to know if there is a way to highlight specific dates on the datepicker when using the the code below with  beforeShowDay:

WET 4 Example
--------------

```javascript
<div class="form-group">
	<label for="startdate">Start Date<span class="datepicker-format"> (<abbr title="Four digits year, dash, two digits month, dash, two digits day">YYYY-MM-DD</abbr>)</span></label>
	<input class="form-control" type="date" id="startdate" name="startdate" min="2013-03-27" />
</div>

```
I want the above code to behave like the one below

Code to highlight dates
----------------------------------
```javascript
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.14/themes/smoothness/jquery-ui.css" />
 <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
 <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js"></script>
 <script type="text/javascript">
           var sessionDays = [[2015, 01, 29, 'Session 1'], [2015, 02, 10, 'Session 2'], [2015, 02, 20, 'Session 3'], [2015, 06, 21, 'Session 4'], [2016, 09, 25, 'Session 6'], [2013, 10, 13, 'Comference'], [2015, 01, 12, 'Conference'], [2014, 12, 25, 'Christmas'], [2014, 12, 26, 'Boxing Day']];					   
					        $(function () {
           $("#date").datepicker({
               beforeShowDay: setsessionDays
           });
 
           
           function setsessionDays(date) {
               for (i = 0; i < sessionDays.length; i++) {
                   if (date.getFullYear() == sessionDays[i][0]
                        && date.getMonth() == sessionDays[i][1] - 1
                        && date.getDate() == sessionDays[i][2]) {
                       return [true, 'sessionDays', sessionDays[i][3]];
                   }
               }
               return [true, ''];
           }
       });
   </script>
    <style type="text/css">
 .ui-datepicker td.sessionDays a, .ui-datepicker td.sessionDays a:hover {
    background: none #FFEBAF;
    border: 1px solid #BF5A0C;
  }
</style>
</head>
<body>
<h1>Highlight Date</h1>

<input type="text" id="date" />

</body>
</html>

```

**Comment by E1D1** [comment]
My apologies for the previous post...the code is not showing correctly.

I would like to know if there is a way to highlight specific dates on the datepicker when using the the code below with beforeShowDay:

WET 4.0 Date picker Example 
--------------------------------------------
```javascript
<div class="form-group">
	<label for="startdate">Start Date<span class="datepicker-format"> (<abbr title="Four digits year, dash, two digits month, dash, two digits day">YYYY-MM-DD</abbr>)</span></label>
	<input class="form-control" type="date" id="startdate" name="startdate" min="2013-03-27" max="2013-05-07" />
</div>
<div class="form-group">
	<label for="enddate">End Date<span class="datepicker-format"> (<abbr title="Four digits year, dash, two digits month, dash, two digits day">YYYY-MM-DD</abbr>)</span></label>
	<input class="form-control" type="date" id="enddate" name="enddate" min="2013-03-27" max="2016-05-07" />
</div>
```

Basicaly I am trying to achieve the following using the WET 4.0 Datepicker
```javascript
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.14/themes/smoothness/jquery-ui.css" />
 <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
 <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js"></script>
 <script type="text/javascript">
           var sessionDays = [[2015, 01, 29, 'Session 1'], [2015, 02, 10, 'Session 2'], [2015, 02, 20, 'Session 3'], [2015, 06, 21, 'Session 4'], [2016, 09, 25, 'Session 6'], [2013, 10, 13, 'Comference'], [2015, 01, 12, 'Conference'], [2014, 12, 25, 'Christmas'], [2014, 12, 26, 'Boxing Day']];					   
					        $(function () {
           $("#date").datepicker({
               beforeShowDay: setsessionDays
           });
 
           
           function setsessionDays(date) {
               for (i = 0; i < sessionDays.length; i++) {
                   if (date.getFullYear() == sessionDays[i][0]
                        && date.getMonth() == sessionDays[i][1] - 1
                        && date.getDate() == sessionDays[i][2]) {
                       return [true, 'sessionDays', sessionDays[i][3]];
                   }
               }
               return [true, ''];
           }
       });
   </script>
    <style type="text/css">
 .ui-datepicker td.sessionDays a, .ui-datepicker td.sessionDays a:hover {
    background: none #FFEBAF;
    border: 1px solid #BF5A0C;
  }
</style>
</head>
<body>
<h1>Highlight Date</h1>

<input type="text" id="date" />

</body>
</html>
```

**Comment by LaurentGoderre** [comment]
@E1D1 the date picker is a polyfill which emulates a native HTML5 date picker if it isn't supported. Therefore, the polyfill can't provide more functionality its native implementation.

**Comment by E1D1** [comment]
@LaurentGoderre 

Sorry for the late reply but could you please explain why you say " if it isn't supported."

**Comment by LaurentGoderre** [comment]
Some browser have native support for a date picker (such as Chrome) while other browser have not yet implemented it (e.g. Firefox). The date picker is a polyfill that bring that missing functionality to browser that don't already have. For that reason we do not add any functionality that native implementation don't have.

**Comment by CalvinRodo** [comment]
@E1D1 
Basically the polyfill will only support the HTML5 specification
http://www.w3.org/TR/html-markup/input.date.html

Why can't you just set the current value for the Date textbox to be the value you want? That will start with it highlighted.

**Comment by E1D1** [comment]
Hi Calvin 

Because I want a few days to be highlighted on the calendar ?

**Comment by CalvinRodo** [comment]
Can you just set a min date and a max date to encompass the days ? 

The other option is to not use type=date at all and just implement your own datepicker.

**Comment by E1D1** [comment]
Hi Calvin

Because I want a few days to be highlighted on the calendar ?

**Comment by E1D1** [comment]
Yes I could but it won't highlight for instance feb. 3rd and feb. 14

**Comment by CalvinRodo** [comment]
No it wouldn't. 

What is the reason for highlighting these values? 

Would maybe a drop down list be better suited for this?

**Comment by E1D1** [comment]
Not really ... I want the user to use the calendar and at the same time highlight important dates .

The code I posted above works but not with the wet template

**Comment by CalvinRodo** [comment]
Of course it doesn't because the html 5 date picker does not allow you to do that. 

Are these important dates to inform the user of optimal dates to pick or just something like notifying them of holidays? 

Maybe it should be a date picker but then some radio buttons below to specify the important dates to pick? 

Otherwise your out of luck.

**Comment by pjackson28** [comment]
If you are looking to highlight important dates, then maybe you should use the Calendar of events for that purpose and type="date" separately for selecting the date.
