### ISSUE TITLE
Issue with Menu Bar in Firefox when hitting "ctrl + +"

### ISSUE THREAD

**Issue by CalvinRodo** [wet-boew/wet-boew#6472]
When on this page and hitting ctrl + + a few times the items in the menu bar lose left justification, this happens when I hit 110% zoom in Firefox, my screen is set to 1366 x 768

![menutest](https://cloud.githubusercontent.com/assets/87738/5900133/76ce50c4-a533-11e4-9d70-f1d79d3dbf72.png)

This is the page the test occurred on 
http://wet-boew.github.io/themes-dist/theme-gcwu-fegc/index-en.html

**Comment by LaurentGoderre** [comment]
Duplicate https://github.com/wet-boew/theme-gcwu-fegc/issues/189
