### ISSUE TITLE
Error with i18n text when ending session

### ISSUE THREAD

**Issue by CalvinRodo** [wet-boew/wet-boew#6473]
This was found by our clients when doing testing on an app. 

Time tou session: S\'il vous plaît ouvrir une nouvelle session. And Avertissement d\'expiration de la session (try to escape char " ' " )

**Comment by LaurentGoderre** [comment]
Can you send a screenshot of the problem. I can't reproduce.

The i18n files uses double quotes (`"`) so single quotes within it don't need to be encoded

**Comment by CalvinRodo** [comment]
I'll try and get a screenshot of it, it was not found by me but one of the clients testing the my service canada business account release this weekend, it was specified as a "known" issue with WET and I was told no one had ever entered an issue here so I figured I'd do it for them. 

There is a very real chance this has been fixed, or it's been implemented incorrectly.

**Comment by LaurentGoderre** [comment]
What version are they using?

**Comment by CalvinRodo** [comment]
It looks like 3.1.7 I'm working on recreating it now.

**Comment by LaurentGoderre** [comment]
3.1 is no longer supported though. It's working well in v4.0

**Comment by CalvinRodo** [comment]
It's not supported but I would imagine the majority of the sites that use WET aren't using v4.0

**Comment by LaurentGoderre** [comment]
Maybe so but we are not going to provide any fix for that version

**Comment by CalvinRodo** [comment]
Alright
