### ISSUE TITLE
Feeds: css file

### ISSUE THREAD

**Issue by idekaresearch** [wet-boew/wet-boew#6474]
To use the WET 4 Feeds widget, do I have to include the feeds.css <link rel="stylesheet" href=".../feeds.min.css"> or will the WET framework dynamically load the appropriate css?

**Comment by LaurentGoderre** [comment]
You don't need tom load any file manually.

**Comment by idekaresearch** [comment]
I noticed that the feeds.css file is being included manually in the Feeds working sample. This css formats the final look.

**Comment by pjackson28** [comment]
@idekaresearch The feeds.css just contains demo CSS for styling the Feeds plugin. It is not required for the plugin to work.

**Comment by idekaresearch** [comment]
Our client saw the sample and wanted the look, but when I use the widget, the default bullets display for each item. I'll just include the relevant css. Thanks!
