### ISSUE TITLE
Image in Tab

### ISSUE THREAD

**Issue by ikug** [wet-boew/wet-boew#6476]
I am using tab for our pages. In each tabs could have a image beside of content. I created one, and found out the display is different bwteen Chrome and IE9.

In Chrome: 

![image](https://cloud.githubusercontent.com/assets/10654702/5925053/f6a2ef84-a62e-11e4-9ed8-b7b4f7851114.png)

But in IE 9:

![image](https://cloud.githubusercontent.com/assets/10654702/5925215/f0fe3326-a62f-11e4-848a-7bfa8be66c10.png)

As you can see the image is extremely huge, and content is just under of it. We are supposed to having the correct one which is showing on Chrome, but our users are allowed to use IE9 only. And the IE 9 document mode has to be Quirks, and it is what you see from the attached image.

Is there any I can make it display properly as like showing on the Chrome? Or IE 9 isn't be supported with WET 4.0.10?

**Comment by pjackson28** [comment]
IE9 is supported but Quirks mode is not (we only support standard mode). Why do you need to run in Quirks mode? That is a very buggy and inconsistent rendering mode to be running (will lead to all sorts of problems). Also you should check to see if you are running in IE9 mode or in compatibility mode (use F12 to bring up developer tools). WET does not support compatibility mode as it is effectively a buggier IE7.

If your users are switching to Compatibility mode automatically, then that could be fixed on the server with instructions from the following page: http://wet-boew.github.io/v4.0-ci/docs/server-en.html (in IE Compatibility Mode section).

**Comment by ikug** [comment]
Thank you for your response.

It is not that we want to use. It is the application we are using has to be Quirks mode, and worst thing is our users are only allowed to use IE 9 on Quirks mode. If it switches to standards, then the application can't be used properly.

I know what you are saying, and I just can't make a deal with them about it. But I am looking for some way to make it display nicely(as like Chrome) without changing anything else.

Any thoughts can be appreciated...

**Comment by pjackson28** [comment]
There is probably little we can due to help as Quirks mode and Standards mode are very different and all IE9 testing is done with standards mode. For your scenario, I would suggest having a custom CSS file that loads only for IE9 (see how we do that with conditional comments) and in that file have fixes that fix the IE9 issues you are facing.

**Comment by ikug** [comment]
Which file is from WET?

**Comment by pjackson28** [comment]
I was meaning look at the template markup (HTML) and see how we use IE conditional comments. You can use a similar approach to target a CSS file at just IE9.
