### ISSUE TITLE
Problems with datalist in Chrome when large number of items

### ISSUE THREAD

**Issue by eehret** [wet-boew/wet-boew#6478]
We noticed that when we try to use datalist with a large number of items it does not work well:
1.  If you have > around 100 items and you type something that matches a much smaller subset of the items, those items will show up.  But as soon as you match too many items (or if you just click the arrow without filtering, the list will not render at all (large black box instead).   When the black box problem happens, the UI becomes unresponsive.
2.  If there are too many items to show on the screen, some of the items may be completely inaccessible (cannot be shown nor scrolled to easily). 

If Chrome's datalist implementation is really bad, I wonder if we can force a polyfill?

**Comment by pjackson28** [comment]
If you have that many datalist items then you dynamically load the items as you may be running into browser memory issues. See the [dynamic datalist example](http://wet-boew.github.io/v4.0-ci/demos/datalist/datalist-dynamic-en.html) for how to do the dynamic approach with large datalists.

**Comment by eehret** [comment]
Is ~100 really too many items?  It doesn't seem outlandish.
Anyway, we are going to use jQueryUI's autocomplete for now, since that one seems to work fine for our purposes.

Thanks for the help.

**Comment by LaurentGoderre** [comment]
100 choices seems to defeat the purpose of such components though...

**Comment by pjackson28** [comment]
Since this is potentially an issue with the native support in Chrome for an HTML5 element, I can't say. But if you have more than 100 items then that becomes a lot of markup to include in a page (will mean a lot of page bloat which is not good for mobile). At that point you may want to consider sourcing the data from an off-page source to minimize the actual total page size. Keep in mind that the recommended total page size (gzipped) is 200kb with an upper limit of 500kb so that becomes a lot harder meet if you hardcode in a lot of datalist items.

**Comment by eehret** [comment]
We are aware that pulling in this data dynamically with an async call would be preferable... if we have time, we may do that.  That's a big IF though :)

**Comment by LaurentGoderre** [comment]
I already created code samples for this, the only portion needed is the backend to send the options to the async call

**Comment by hsrudnicki** [comment]
@eehret @LaurentGoderre @pjackson28 : Can this issue be closed or otherwise?

**Comment by LaurentGoderre** [comment]
I believe so because this is a problem with the native Chrome datalist

**Comment by shwetatripathi03** [comment]
@eehret.. I am looking for a solution to the same problem, please let me know if you found any solution to resolve this issue.

**Comment by mittaladi** [comment]
I am having a total of 5000 options and chrome is displaying only 500, Is there any way to change this limit?
