### ISSUE TITLE
Disabling mobile mode for WET 4.0 (Intranet Theme)

### ISSUE THREAD

**Issue by McEmily** [wet-boew/wet-boew#6482]
Was wondering if there is a way to disable mobile mode for the Intranet theme of WET 4.0?

Our application is often run within an 800x600 browser control in another application, and it renders it in mobile mode every time. We have a feeling our end users won't like this (even though these are the newest standards) and we can't necessarily ask that the browser controls be made any larger by default to compensate for it.

I've tried building a new version of the theme, but with no success. It's either proxy issues (within workplace walls), permissions (ie running it using root), or unlocking issues (trying to unlock files that aren't locked?).

Please advise if there is an easier solution than reinventing the wheel, so to speak. Thank you.

**Comment by LaurentGoderre** [comment]
Unfortunately we do not support this. It can be done but it requires custom building and might make it more difficult to get future update.

**Comment by CalvinRodo** [comment]
Is there any guidance on how to do this?

**Comment by LaurentGoderre** [comment]
Since it's not supported there is no guidance on how to do this

**Comment by LaurentGoderre** [comment]
Closing since the request is not supported
