### ISSUE TITLE
Menu Bar and Search Box Missing in WET 4.0.10

### ISSUE THREAD

**Issue by ikug** [wet-boew/wet-boew#6483]
We upgraded WET new version from WET 4.0.9 to WET 4.0.10 this week. After we implemented to our current application, I found the menu bar and search box are missing in IE 8. I looked at your release note, and realized the one of new changes from old version is "Theming: Added the ability for themes to customize WET variables". I am not sure if this is the reason to course the menu bar and search box missing in IE 8. 

In IE8 with browser mode as IE 8 and document mode as standards, our application displays properly with menu bar and search box by WET 4.0.9, but missing by the latest version.

I attached the images for you to have a look, they are the same page(same code) but with different WET version.
Also you will see the way to display the 2 boxes are different.
In WET 4.0.9 it shows 2 boxes(Updates, and To Do) as equal, but in WET 4.0.10 it only displays one box(Updates) cross the whole page, which is not correct. 

This is WET 4.0.9 in IE 8:

![image](https://cloud.githubusercontent.com/assets/10654702/5958718/a561c72c-a795-11e4-88f1-27ff01c899fa.png)

Following is WET 4.0.10 in IE 8:

![image](https://cloud.githubusercontent.com/assets/10654702/5958733/d480253a-a795-11e4-9371-673b988b184d.png)

**Comment by LaurentGoderre** [comment]
Thanks! I am on it!

**Comment by LaurentGoderre** [comment]
I wonder if it's that bug with IE If it has too many rules, it starts ignoring them

**Comment by LaurentGoderre** [comment]
Weird, it seems to be the minification that breaks it

This works:
http://wet-boew.github.io/themes-dist/theme-gc-intranet/unmin/index-en.html

This doesn't:
http://wet-boew.github.io/themes-dist/theme-gc-intranet/unmin/index-en.html

@nschonni any idea?

**Comment by LaurentGoderre** [comment]
Got it! WET Core has an IE8 cleaning task I will port the task over to the other themes

**Comment by LaurentGoderre** [comment]
Thanks a lot for reporting this! The following PR will need to be replicated on every theme

#6484
