### ISSUE TITLE
Geomap redraw layer

### ISSUE THREAD

**Issue by upsonp** [wet-boew/wet-boew#6487]
I'm hoping for someone to help me work through an issue I'm having. It's related to <a href="https://github.com/wet-boew/wet-boew/issues/2299">this discussion</a> we had awhile ago.

In the discussion I was asking for a native method that would allow Geomap to filter points based on a bounding area. Well we have the AOI tool now, which is half way to what I was looking for.

I'm trying to write an updated version of the tool I discussed in the topic thread above, using more javascript and less PHP. After I get the bounding area using the AOI and build a new table I can't get the map to update based on that new table. Is there a way to refresh just the layer and the map to force it to re-plot points from an updated table without refreshing the whole page?

**Comment by upsonp** [comment]
Any word or update on this request?

I've successfully managed to get the table to update to features that exist in the AOI box using a filter from the tables API (http://www.datatables.net/reference/api/). However, I lose the "select" column and the points on the map aren't updated.

**Comment by jvanulde** [comment]
@upsonp thanks for prompting us again on this. There isn't a way that I can think of to refresh the table. Effectively, we need to call the a private function. The best way to accomplish this would be for us to expose a public function that allows for a full or partial refresh of the table markup. Can you confirm that this would work? Without having explored any options I expect that we could attach a listener on the layer that would auto-magically do a refresh on an update.

**Comment by upsonp** [comment]
Yeah, that's kind of what I have in mind. I spent most of last week looking at the code trying to figure out how to do just that, but I'm nit well versed in JavaScript.

**Comment by jvanulde** [comment]
Looking into it a little further I notice that there is a onFeaturesAdded listener on the layer that generates the table elements. Have you tried removing the features from the layer and then adding the selected ones back to the layer?

**Comment by upsonp** [comment]
@jvanulde I've tried removing them from the table. I'm not sure how to clear them from the map layer, because I CAN do that if I knew how to clear the map layer.

I'm assuming you're referring to the methods in this file
https://github.com/wet-boew/wet-boew/blob/master/src/plugins/deps/geomap-lib.js

How do you call those methods?

**Comment by upsonp** [comment]
I've been really badly fumbling my way though this for the last week. I'm now able to add features to the map using the OpenLayers API, but it doesn't seem to be calling the onFeaturesAdded method.

Bare with me, I have very little JavaScript experience, but the following will create an array of features from an XML file containing all the relevant point information and add the points that are "in bounds" to the map layer in the Area of Interests (set in another method). The table isn't updated at all and I'm not sure how to tell if the onFeaturesAdded method is being called.

```JavaScript
var featureLayer = mapSample.getLayer("#RPSSLocations");
			
var header = xmlDoc.getElementsByTagName("header");
var col = header[0].getElementsByTagName("colName");

var locations = xmlDoc.getElementsByTagName("location");
var point, x, y, loc;
			
var attrMap = {};
var features = [];
for( i=0; i<locations.length; i++ ) {
  loc = locations[i];
  x = parseFloat(loc.attributes["lon"].value);
  y = parseFloat(loc.attributes["lat"].value);
  if( inBounds( x, y ) ) {
    point = new OpenLayers.Geometry.Point(x, y);

    attrMap[col[0].childNodes[0].nodeValue] = loc.getElementsByTagName("addr")[0].childNodes[0].nodeValue;
    attrMap[col[1].childNodes[0].nodeValue] = loc.getElementsByTagName("name")[0].childNodes[0].nodeValue;
    attrMap[col[2].childNodes[0].nodeValue] = loc.getElementsByTagName("prov")[0].childNodes[0].nodeValue;
    attrMap[col[3].childNodes[0].nodeValue] = loc.getElementsByTagName("station")[0].childNodes[0].nodeValue;
	
    allow = loc.getElementsByTagName("allowance");
    for( j=4; j<col.length; j++ ) {
      attrMap[col[j].childNodes[0].nodeValue] = allow[j-4].childNodes[0].nodeValue;
    }

    features.push(new OpenLayers.Feature.Vector(point, attrMap));
  }
}
featureLayer.addFeatures(features);
```

**Comment by jvanulde** [comment]
Can you check to see what eventListeners have been added to "featureLayer" and let me know if "onFeaturesAdded" is there?

**Comment by upsonp** [comment]
I'm sorry I haven't responded. I've been off on other projects for the last month. I'm getting back into the web thing now... for awhile at least

@jvanulde I'm not sure what to look at to see if the onFeaturesAdded event was added to the featureLayer. I do have a public demo though if you have time to take a look, I assume you'd know where to find it in firebug for chromes equivalent. I'll keep looking as well.

https://inter-l01.dfo-mpo.gc.ca/sites/bio/science/data-donnees/can-ewlat/index2-en.php

Unfortunately, one of the issues with the public demo is the AOI button is missing form the map, I assume that's because the GeoMap version isn't up-to-date on the server. 

Another issue is the performance in Internet Explorer is terrible. I'm debating opening another ticket to discuss that issue as it's a huge issue for my client. Works great in FireFox, Chrome, Opera and Safari.

Sucks lemons in IE, sometimes it causes the browser to completely lock up, sometimes it just takes a REALLY long time to load. After it's loaded it seems to work fine.

**Comment by jvanulde** [comment]
It looks to me like the delay is with the table. Either Geomap is taking too long to read the table or the table is taking too long to render. File an issue and we can track it down.

**Comment by hsrudnicki** [comment]
Are you ready to close this issue or otherwise?

**Comment by jvanulde** [comment]
No. Still and issue.

**Comment by hsrudnicki** [comment]
Made "Going Stale", and please update again @jvanulde / others this issue's status whether this issue can be closed or otherwise?  Thx

**Comment by hsrudnicki** [comment]
Is this still an issue?  Either way, please update this issue's status, thank you

**Comment by upsonp** [comment]
@hsrudnicki I'm not using the AOI button anymore. Would have been handy, but we ended up going without it. If I pick it up and have issues in the future I can create a new issue so feel free to close one.

**Comment by hsrudnicki** [comment]
Thank you @upsonp , this is closed.
