### ISSUE TITLE
Tabbed Interface: Tabs on Google Chrome

### ISSUE THREAD

**Issue by mohamedbecha** [wet-boew/wet-boew#6488]
Hi there,
There is an issue with the tabs on Google Chrome. It takes 2 clicks to open a tab. 
The first click makes the tab active, the second click changes its text content...
IE and Firefox work great; one click is enough
Thx

**Comment by pjackson28** [comment]
I just tried the live working example with Chrome and the tabs change with just one click. Which version of WET are you using? Can you reproduce the issue with the live working example at: http://wet-boew.github.io/v4.0-ci/demos/tabs/tabs-en.html?

**Comment by mohamedbecha** [comment]
Im using v4.0.6. The link (WET page) above took 2 click with Chrome...

**Comment by pjackson28** [comment]
I can't reproduce your issue on Chrome 40.0.2214.94 m (with the live working example). The tab panel changes each time on the first click (both in desktop and mobile view). What version of Chrome are you using? Have you configured Chrome in any way?

**Comment by LaurentGoderre** [comment]
@mohamedbecha you should update to v4.0.10

**Comment by mohamedbecha** [comment]
Version 40.0.2214.94 m : same as yours but still taking 2 clicks. I never did a custom configuration for chrome. thx
Testers are welcome

**Comment by mohamedbecha** [comment]
@LaurentGoderre  Sounds good

**Comment by pjackson28** [comment]
Could you please record what you are seeing? Perhaps if we see the steps that you take and the visual results that will help.

**Comment by mohamedbecha** [comment]
http://youtu.be/8GAs2XHK44Q here is a video i made

**Comment by pjackson28** [comment]
Weird. I don't know how to reproduce that. No matter what I do in Chrome I can't get that result. I tried exactly what you did and everything changes right away. Can you reproduce on any other machine? If so, can you reproduce on a machine on a different network?

**Comment by LaurentGoderre** [comment]
I believe this may be caused by the markup used. Can you please post the markup here?

**Comment by mohamedbecha** [comment]
@LaurentGoderre  It is not a page that i created. it is the wet tabs:  http://wet-boew.github.io/v4.0-ci/demos/tabs/tabs-en.html 
@pjackson28 Will try it at home

Thank you all

**Comment by mohamedbecha** [comment]
IE9 (real not emulation): Tabs content is not showing

**Comment by pjackson28** [comment]
It does for me. See the following video of the test I just ran with IE9: https://saucelabs.com/tests/8c6000ef84494f948cd3b9165b5de616

Perhaps you are having network issues? Could your network be blocking important files? You might be able to tell through the developer tools (F12) and looking at the network traffic (perhaps you have some 404s or other).

**Comment by mohamedbecha** [comment]
yes , but if you copy paste the tabs code and try to create a simple tabs testing examples, they will not work

**Comment by pjackson28** [comment]
Perhaps there is an issue with the markup in the examples you created? What happens if you use the working example markup with no changes? Do the live working examples work for you in IE9?

**Comment by mohamedbecha** [comment]
i just copy paste the code for the tabs. making a very simple 2 tabs for testing. 
The test i made don't work in IE9. But, the live example works fine

**Comment by pjackson28** [comment]
What mode is your browser running in for your local test? Is it in IE9 mode or compatibility mode? Do you get any errors in the console? What changes (if any) did you make after copying/pasting? Could you post the tabbed interface markup of the test that doesn't work?

**Comment by mohamedbecha** [comment]
i have IE9 installed in a old work station for testing. no errors.. here is the code :
 
<div class="wb-tabs">
	<div class="tabpanels">
		<details id="details-panel1">
			<summary>Example 1</summary>
			<p>Example 1</p>
		</details>
		<details id="details-panel2" open="open">
			<summary>Example 2</summary>
			<p>Example 2</p>
		</details>
	</div>
</div>

**Comment by mohamedbecha** [comment]
i have IE9 installed in a old work station for testing. no errors.. here is the code :

'  <div class="wb-tabs">
' 	<div class="tabpanels">
' 		<details id="details-panel1">
' 			<summary>Example 1</summary>
'			<p>Example 1</p>
'		</details>
'		<details id="details-panel2" open="open">
'			<summary>Example 2</summary>
'			<p>Example 2</p>
'		</details>
'	</div>
' </div>

**Comment by mohamedbecha** [comment]
![untitled-3](https://cloud.githubusercontent.com/assets/6919911/6082305/705bc744-adee-11e4-9478-60b0905829a7.png)

**Comment by pjackson28** [comment]
I don't see anything in there that would cause an issue. What mode is your IE9 running in? Is it compatibility mode? Are there any files that are not being downloaded?

**Comment by mohamedbecha** [comment]
IE is running on normal mode...

**Comment by pjackson28** [comment]
Strange that it works fine on your machine for the live working examples but not locally. Have you checked to see if there is a 404 for any of the supporting files (can do with the developer tools)? There needs to be something that is different, either in the browser or with the page, to explain why it behaves differently with those two scenarios.

Can you reproduce your issue on any other machine with IE9?

**Comment by hsrudnicki** [comment]
@mohamedbecha @pjackson28 @LaurentGoderre : Can this issue be closed?

**Comment by hsrudnicki** [comment]
Made "Going Stale" to close this issue soon or otherwise?
Either way, please update this issue's status, thank you in advance @mohamedbecha / @pjackson28

**Comment by hsrudnicki** [comment]
Based on the last comment from @pjackson28, is this still an issue waiting for an answer from @mohamedbecha or if otherwise?  Either way, please update this issue's status whether this issue can be closed as resolved/fixed or otherwise, thank you

**Comment by hsrudnicki** [comment]
Is this still an issue? Can be this closed or otherwise?
