### ISSUE TITLE
Help Question: rel="external"

### ISSUE THREAD

**Issue by Bgolden67** [wet-boew/wet-boew#6490]
Is there any reason that the rel="external" attribute has been left out of the toolkit samples?
Example url place holders for things like Facebook, Twitter etc. should be using rel="external" and if we want it to be consistently used they should be included in the sample pages shouldn't they? Otherwise it come be mis-understood that it's no longer necessary to use them.

just food for thought

**Comment by LaurentGoderre** [comment]
Nice catch! @pjackson28 I believe we should add them for those links shouldn't we?

**Comment by pjackson28** [comment]
Yes, any missing rel="external" should be added.

**Comment by Bgolden67** [comment]
thanks guys!

**Comment by LaurentGoderre** [comment]
@Bgolden67 are you able to open a PR?

**Comment by Bgolden67** [comment]
a PR?

**Comment by LaurentGoderre** [comment]
Pull request

**Comment by LaurentGoderre** [comment]
I added them.

**Comment by LaurentGoderre** [comment]
I added them.
