### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by regagnon** [wet-boew/wet-boew#6491]
I would like to know if there is a section on how to create tabs.
If yes can you please provide me with the link.

thanks

René

**Comment by pjackson28** [comment]
You can find the documentation here:http://wet-boew.github.io/wet-boew/docs/ref/tabs/tabs-en.html

**Comment by regagnon** [comment]
Thank you very much, much appreciated.
 


 
 
Cheers
 
René Gagnon
>>> Paul Jackson <notifications@github.com> 2015/02/02 2:45 PM >>>

You can find the documentation
here:http://wet-boew.github.io/wet-boew/docs/ref/tabs/tabs-en.html
—
Reply to this email directly or view it on GitHub (
https://github.com/wet-boew/wet-boew/issues/6491#issuecomment-72523812
).

 >
Ce courriel est destiné exclusivement au destinataire mentionné en titre
et peut contenir de l'information privilégiée, confidentielle ou
soustraite à la communication aux termes des lois applicables. Toute
divulgation non autorisée, toute reproduction ou réacheminement est
interdit. Si vous n'êtes pas le destinataire de ce courriel, ou n'êtes
pas autorisé par le destinataire visé, ou encore, si vous l'avez reçu
par erreur, veuillez le mentionner immédiatement à l'expéditeur et
supprimer le courriel et les copies.

>
This e-mail message is intended for the named recipient(s) and may
contain information that is privileged, confidential and/or exempt from
disclosure under applicable law. Unauthorized disclosure, copying or
re-transmission is prohibited. If you are not a named recipient or not
authorized by the named recipient(s), or if you have received this
e-mail in error, then please notify the sender immediately and delete
the message and any copies.
