### ISSUE TITLE
Geomap: Highlighting of selected entry row is broken.

### ISSUE THREAD

**Issue by bchagnon** [wet-boew/wet-boew#6492]
When selecting an entry row by checking its check box on, the row does not get highlighted. New code still uses the deprecated WET 3.x class "background-highlighting".

**Comment by jvanulde** [comment]
@bchagnon please confirm that this has been fixed so the issue can be closed.

**Comment by bchagnon** [comment]
I confirm that this issue has been fixed!

**Comment by jvanulde** [comment]
Merci @bchagnon
