### ISSUE TITLE
DataTables : Error handling

### ISSUE THREAD

**Issue by hamdaneh** [wet-boew/wet-boew#6494]
Hi,
I am trying to remove the default behaviour of Datatables when Ajax throws an error if JSON is mal formatted by adding this:

$.fn.dataTable.ext.errMode = 'none';

But I get in the console this error : 
Uncaught TypeError: Cannot read property 'ext' of undefined.

Thanks!
Houda.

**Comment by LaurentGoderre** [comment]
That means that datatable is not loading properly

**Comment by pjackson28** [comment]
Maybe not directly related but important to note that WET doesn't support malformed JSON. It will ignore any malformed JSON that you include in any data-wb-* attribute (since supporting malformed JSON would be a significant security risk).

**Comment by hamdaneh** [comment]
Thanks! You are right, I had to move that line after the datatable is initialized.

Bad JSON can happen when the service layer is down, so we need to handle errors for timeouts/400 bad requests etc., We need to show proper error messages to users.

**Comment by LaurentGoderre** [comment]
I don't believe it can be this easy. I will try to find a solution

**Comment by hamdaneh** [comment]
Hi,
Me again,
I am trying to add an event listener on error now.. but my function is not triggered. Is the event error.dt the right one to use?
 
$.fn.dataTable.ext.errMode = 'none';
.on( 'error.dt', function ( e, settings, techNote, message ) {
	    	
	        console.log( ' An error has been reported by DataTables: ', message );
	    } )

Took this from this web site documentation : http://datatables.net/reference/event/error

Thank you again for your precious help!
Houda.

**Comment by LaurentGoderre** [comment]
You are missing a selector. Try this:

```javascript
wb.document.on( 'error.dt', function ( e, settings, techNote, message ) {

        console.log( ' An error has been reported by DataTables: ', message );
    } )
```

**Comment by hamdaneh** [comment]
thanks! that worked.

**Comment by hamdaneh** [comment]
Sorry, it is not working, I thought for some reason that it worked...  I have tried everything, including this:

```javascript
$.fn.dataTable.ext.errMode = function ( e, settings, helpPage, message ) { console.log(message)};
```
But nothing seems to work... Not able to have a custom function for error handling.

**Comment by LaurentGoderre** [comment]
@hamdaneh here's how to do it:

```html
<script>
(function() {
	wb.doc.one( "preXhr.dt", function() {
		$.fn.dataTable.ext.errMode = "throw";
	});

	wb.win.on( "error", function( event ) {
		var error = event.originalEvent.error;
		if ( error.message.match( /^DataTables warning/ ) ) {
			//Deal with error here
		}
		return false;
	});
})();
</script>
```

**Comment by LaurentGoderre** [comment]
@hamdaneh have you tried it?

**Comment by hamdaneh** [comment]
Not yet, will let you know as soon as I try it.

**Comment by LaurentGoderre** [comment]
I'm closing but please reopen if it's still an issue
