### ISSUE TITLE
iFrame with WET

### ISSUE THREAD

**Issue by ikug** [wet-boew/wet-boew#6498]
I am just wondering if iFrame is against with WET?

In our app, we use WET and iFrame, but the layout seems weird once rendered.

**Comment by pjackson28** [comment]
There is nothing in WET that prevents the use of iframes, WET uses them in a few cases, although they should still be used sparingly as they can create headaches (e.g., inability for the current page to control any aspect of the iframe, including CSS, without an established API). Where possible you should use AJAX and similar approaches instead as they give you more control over the end result.

But to answer your specific concern, there should be nothing in WET that would affect the rendering of an iframe (besides, WET can even touch the contents of an iframe).

**Comment by ikug** [comment]
OK, thanks.
