### ISSUE TITLE
for Demo pages: Institutional page

### ISSUE THREAD

**Issue by Bgolden67** [wet-boew/wet-boew#6499]
Just wondering how one aspect in the intitutional page will be handled in the template page being made available.
In the guidelines being shown, there is a drop down menu on the social media icons to link to multiple accounts,
see page 89 & 93
http://www.gcpedia.gc.ca/gcwiki/images/d/d8/Canada_Site_Content_IA_Specification_-_V1_-_approved-EN.pdf

how will this be achieved?

**Comment by pjackson28** [comment]
Could you please file this in wet-boew/GCWeb? This question seems to be specific to the Canada.ca theme.

**Comment by Bgolden67** [comment]
Thanks Paul and yes Canada.ca theme specific.

**Comment by shawnthompson** [comment]
This is being done for release 1.5 of GCWeb and has just been merged in. We are using a overlay instead of a drop down menu.

**Comment by Bgolden67** [comment]
Is there an eta on the release date for this?

**Comment by shawnthompson** [comment]
It's available in the latest [development release](http://wet-boew.github.io/wet-boew/docs/versions/dwnld-en.html#v40dev) or can be seen on the [Theme landing page](http://wet-boew.github.io/wet-boew/docs/versions/dwnld-en.html#v40dev) on the Facebook and Youtube icons

**Comment by LaurentGoderre** [comment]
Can we close this?
