### ISSUE TITLE
Footnotes Overlap

### ISSUE THREAD

**Issue by EricLavoie88** [wet-boew/wet-boew#6500]
When using the "Print Preview" options in IE and FF, the links in brackets following the footnotes at the bottom of the page overlap the text that follows.

**Comment by pjackson28** [comment]
@EricDunsworth Please look into this.

**Comment by EricLavoie88** [comment]
![footnoteoverlap](https://cloud.githubusercontent.com/assets/7073468/6066130/b9b91ec0-ad38-11e4-9fd7-df684cbc2191.JPG)

**Comment by EricDunsworth** [comment]
The reason for what's happening in the screenshot is that the page in question is using footnote links that contain folder/file names. Normally the footnote links are meant to point towards same-page IDs (e.g. ``<a href="#id">``).

Anyways, I'll look into making some CSS adjustments to prevent the screenshot's effect from happening :).

**Comment by EricLavoie88** [comment]
In addition to the footnotes issues, we've also found a few other "issues" related to the links that appear in brackets beside the link text in the print version. 

1. We use relative links for all links to the TBS website (/folder/file.asp) and this is how they appear in the brackets in the print version. Is there a way to add the domain name in order to get the full URL? (http://www.tbs-sct.gc.ca/folder/file.asp)

2. The links in brackets also appear after every link in the table of contents, which isn't very useful for the user in a print version. Not sure if it would be possible to disable this function for the TOC or internal links to anchors as they are not relevant.

Thanks.
![toc-print-version](https://cloud.githubusercontent.com/assets/7073468/6080352/5560ee3e-adde-11e4-888f-d4954642d0d6.jpg)

**Comment by thomasgohard** [comment]
@EricLavoie88 can you open a separate issue for the table of contents links. @zachfalsetto is developing a plugin for the table of contents, we can address that issue there.

**Comment by EricDunsworth** [comment]
Issue #4229 is also out there (seems to be dedicated to print CSS/URL issues).

**Comment by pjackson28** [comment]
@EricLavoie88 For the first question, there is no way to apply the domain name. CSS only has access to what is in the markup so has no way of determining what is the domain name of the page. With this print example it is just using the content of the href attribute so if the domain name is not in the href attribute then it can't be in the brackets either.
