### ISSUE TITLE
Secondary Menu

### ISSUE THREAD

**Issue by CalvinRodo** [wet-boew/wet-boew#6502]
Is there any documentation on how to implement the secondary menu other then viewing the source in the theme examples 

http://wet-boew.github.io/themes-dist/theme-gcwu-fegc/content-secmenu-en.html

**Comment by LaurentGoderre** [comment]
Not that I am aware. The code is fairly easy to implement though

**Comment by CalvinRodo** [comment]
It is but it would make the documentation a lot more usable if we didn't have to go looking at the source for pages. 

Is this code correct

````
<nav id="wb-sec" role="navigation">
  <h2>This title will be hidden used by screen readers only</h2>
  <h3 class="wb-navcurr>First List</h3>
  <ul class="list-group menu list-unstyled">
    <li class="list-group-item">
      <a href="#">link text</a>
    </li>
  <h3 class="wb-navcurr>Second menu List</h3>
  <ul class="list-group menu list-unstyled">
    <li class="list-group-item">
      <a href="#">link text</a>
    </li>   
  </ul>
</nav>

**Comment by rlambert27** [comment]
Hi Calvin,

The "class="list-group-item"" goes on the A element and not the LI element.

Roch

**Comment by CalvinRodo** [comment]
Is there a bug in the implementation here then since according to the documenation on (list groups) [http://wet-boew.github.io/wet-boew-styleguide/v4/design/listgroup-en.html] the list-group-item goes on the li

**Comment by thomasgohard** [comment]
The `list-group-item` class can go on any element: http://wet-boew.github.io/wet-boew-styleguide/v4/design/listgroup-en.html#links.

**Comment by CalvinRodo** [comment]
@thomasgohard But can it go on any element in this situation or does it have to go on an anchor tag inside of a list item side for the side menu to work? Should I even have list items in the side menu.

**Comment by pjackson28** [comment]
If you put it on the li instead then the clickable area for the link will only be the size of the text (so not full width and height). So not a good idea to put it on the li instead (unless you use extra markup or custom CSS which defeats the purpose).

**Comment by CalvinRodo** [comment]
Sounds good, so this is 

````html 
<nav id="wb-sec" role="navigation">
  <h2>This title will be hidden used by screen readers only</h2>
  <h3 class="wb-navcurr">First List</h3>
  <ul class="list-group menu list-unstyled">
    <li><a class="list-group-item" href="#">link text</a></li>
  </ul>
  <h3 class="wb-navcurr">Second menu List</h3>
  <ul class="list-group menu list-unstyled">
    <li ><a class="list-group-item" href="#">link text</a></li>   
  </ul>
</nav>
````

So next question what does the class `wb-navcur` do?

**Comment by pjackson28** [comment]
It's the class for visually identifying the link for the current page. Normally it is applied by a plugin but it can be hardcoded if it is always the same item (like in the secondary menu examples).

**Comment by CalvinRodo** [comment]
@pjackson28 If that's the case why is it being applied to the H3 tag in the example pages?

**Comment by pjackson28** [comment]
It's being added to the h3 to show that it represents the current page. All of the links below it are for sub-pages. In that example it is just providing the name of the current section and then the top links for that section.

**Comment by CalvinRodo** [comment]
Ah cool so then something like this would be more appropriate 

````html
<nav id="wb-sec" role="navigation">
  <h2>This title will be hidden used by screen readers only</h2>
  <ul class="list-group menu list-unstyled">
<li>
  <h3>First List</h3>
  <ul class="list-group menu list-unstyled">
    <li><a class="list-group-item wb-navcurr" href="#">Current Page</a></li>
  </ul>
</li>
<li>
  <h3>Second menu List</h3>
  <ul class="list-group menu list-unstyled">
    <li ><a class="list-group-item" href="#">link text</a></li>   
  </ul>
</li>
    </ul>
</nav>
````

I also noticed that you have two ULs inside of each other to get the correct styling so I think this should be the proper markup and I should have a good understanding for when I or whomever gets around to writing the documentation for this.

**Comment by pjackson28** [comment]
It at least renders correctly in the mobile panel. @thomasgohard Could you please provide your feedback on what is proposed?

**Comment by thomasgohard** [comment]
Mmm… The GC Web Usability theme isn't implementing the secondary menu as detailed in https://github.com/wet-boew/GCWeb/issues/776#issuecomment-65173962.

@DK-TBS is the design you detailed in https://github.com/wet-boew/GCWeb/issues/776#issuecomment-65173962 still up to date?

**Comment by DK-TBS** [comment]
Yep!  Those screenshots and description are still accurate, the spec describes the same approach.

**Comment by LaurentGoderre** [comment]
@thomasgohard how does it differ?

**Comment by hsrudnicki** [comment]
@CalvinRodo @LaurentGoderre @pjackson28 @thomasgohard @DK-TBS @rlambert27: can we finalize/tackle the issue discussion to close it?
Based on your discussion:
- This issue #776 is about "the need / use of a left menu on Canada.ca" 
- The issue #6502 is about coding details "on how to implement the secondary menu", where the "linkify" list group means using:
1)  the class = "list-group" inside <ul> or <div> element(s)
2) and the class="list-group-item" inside <li> and/or <a>, including in case of custom content other elements such as <p>, <h..> for headings

**Comment by CalvinRodo** [comment]
My bug has been fixed I'm content to close this.
