### ISSUE TITLE
Print version links in brackets in the Table of Contents

### ISSUE THREAD

**Issue by EricLavoie88** [wet-boew/wet-boew#6504]
In a web browser's print version, the links in brackets (which appears after every link text on a web page) appears after every link in the table of contents, which isn't very useful for the user in a print version. Not sure if it would be possible to disable this function for the TOC or internal links to anchors as they are not relevant.
![toc-print-version](https://cloud.githubusercontent.com/assets/7073468/6080908/3dcaeafe-ade3-11e4-8ca5-fd97bdc750e8.jpg)

**Comment by biljanap** [comment]
This seems to be default Bootstrap behavior. We have custom css file and this is the code we used on our project to override it:
<code>@media print { a[href]:after { content:"" !important; } }</code>

**Comment by hsrudnicki** [comment]
Can this issue be closed?

**Comment by EricLavoie88** [comment]
Yes thanks.
