### ISSUE TITLE
Data Ajax Issue in IE with CORS and https

### ISSUE THREAD

**Issue by gocGrabinski** [wet-boew/wet-boew#6506]
Attempting to use Data Ajax (fetch, replace) with CORS from one https domain to another https domain (our CDN for common elements).  
	The Data Ajax calls work in FireFox(v 33) but NOT in Internet Explorer (11 in Edge and 8 mode).  Have not tried with any other browsers.
	Solution could be to use XDomainRequest with IE scripts.
	Copied an example script using the XDomainRequest object in IE. It was successful. It allowed the an AJAX CORS request in IE from in our https server set up. 
	Regular jQuery $.ajax throw Access Denied error in IE.
	

	var targetUrl = "https:// ...";
	if (window.XDomainRequest) {
            // Use Microsoft XDR
            alert('Using XDomainRequest Object');
            var xdr = new XDomainRequest();
            xdr.open("get", targetUrl);
            xdr.onload = function() {
                // XDomainRequest doesn't provide responseXml, so if you need it:
                var dom = new ActiveXObject("Microsoft.XMLDOM");
                dom.async = false;
                $('#rspns').html(xdr.responseText);
            };
            xdr.send();
        } else {
            // your ajax request here
			$.ajax({
			    type: 'GET',
			    url: targetUrl ,
			    crossDomain: true,
			    //dataType: 'html',
			    success: function(responseData, textStatus, jqXHR)
			    {
			        $('#rspns').html( responseData );
			    },
			    error: function (jqXHR, textStatus, errorThrown)
			    {
			        $('#msg').html('<ul><li>Status: '+textStatus+' - ' + jqXHR.status + '</li><li>'+errorThrown+'</li><li>Response Headers: ' + jqXHR.getAllResponseHeaders()+ ' </li></ul>');
			        alert('CORS failed - ' + textStatus);
			    }
			});	

        }

**Comment by LaurentGoderre** [comment]
Data Ajax works with CORS in IE11 we tested this at length. However, since in your other issue you were in compatibility mode, it is possible that that is interfering with this. It's also worthy to note that IE 8 and 9 do not support CORS at all and require a fallback

**Comment by gocGrabinski** [comment]
Hi Laurent,
Did you test with an https set up ? Just wondering.
Our testing with http worked fine in IE11. It is the https set up that is not working.
When I try the https urls  with IE11 in Edge mode it appears as if the data-ajax calls in IE11 just do not occur.

Our http set up in IE11 gives me this:
Confirming Edge mode …
[cid:image001.png@01D04529.A0F01A50]
Network shows data-ajax calls:
[cid:image002.png@01D04529.A0F01A50]


Our https set up gives me this
[cid:image003.png@01D04529.A0F01A50]
Network shows NO ajax calls:
[cid:image004.png@01D04529.A0F01A50]

No JavaScript errors in console. AJAX requests just do not happen.

Same https url  in Fire Fox gives me this:
[cid:image005.png@01D04529.A0F01A50]

Stan Grabinski
Prgrammeur analyste | Programmer Analyst
Téléphone | Telephone 819-654-4035

**Comment by LaurentGoderre** [comment]
The images did not upload, can use the GitHub site to upload the images?

**Comment by gocGrabinski** [comment]
Here are the images ...
Our http set up in IE11 gives me this:
![http_example_console](https://cloud.githubusercontent.com/assets/5992730/6133855/f3d4507a-b12a-11e4-8cc2-6c32fec2f252.jpg)

Network shows data-ajax calls: 
![http_example_network](https://cloud.githubusercontent.com/assets/5992730/6133693/c6e1f15e-b129-11e4-906c-14e081fd9a9c.jpg)
Our https set up gives me this 
![https_example_console](https://cloud.githubusercontent.com/assets/5992730/6133740/1ccf6ac4-b12a-11e4-9804-1f85789ac685.jpg)
Network shows NO ajax calls:
![https_example_network](https://cloud.githubusercontent.com/assets/5992730/6133767/422fdc86-b12a-11e4-849e-2e381bd93a66.jpg)
No JavaScript errors in console. AJAX requests just do not happen. Same https url in Fire Fox gives me this: 
![https_example_firefox_network](https://cloud.githubusercontent.com/assets/5992730/6133752/2a7efd56-b12a-11e4-9a54-713cbb4012cc.jpg)

Since it appears to work fine with Fire Fox, pretty sure it is not a path issue with any of the scripts. Appears IE is just more strict with CORS and https.  Perhaps we need to do more server side setup for IE to work (headers) ?

**Comment by LaurentGoderre** [comment]
@gocGrabinski to be clear...are you requesting something via ajax via the exact same subdomain but using https instead of http or are you requesting something from another subdomain or domain?

**Comment by gocGrabinski** [comment]
There are two https domains.

1.       The ‘app’ https domain with our content.

2.       The ‘cdn’ https domain that has all of our WET4 distribution, plus the ‘common’ html components we are trying to ajax in with the data-ajax.
For our tests I have taken the example content-en.html and content-fr.html pages that came with the v4_0_10 distribution and altered the css, js, images to use our  https CDN.

For example:

<link href="https://cdn-canada.services.gc.qat/app/WET4/gcweb/v4_0_10/assets/favicon.ico<view-source:https://cdn-canada.services.gc.qat/app/WET4/gcweb/v4_0_10/assets/favicon.ico>" rel="icon" type="image/x-icon">
<link rel="stylesheet" href="https://cdn-canada.services.gc.qat/app/WET4/gcweb/v4_0_10/css/wet-boew.min.css<view-source:https://cdn-canada.services.gc.qat/app/WET4/gcweb/v4_0_10/css/wet-boew.min.css>">

<link rel="stylesheet" href="https://cdn-canada.services.gc.qat/app/WET4/gcweb/v4_0_10/css/theme.min.css<view-source:https://cdn-canada.services.gc.qat/app/WET4/gcweb/v4_0_10/css/theme.min.css>">

<!--[if lte IE 9]>

The data-ajax calls from https app domain to https cdn domain:

1.  <nav role="navigation" id="wb-sm" class="wb-menu visible-md visible-lg" data-trgt="mb-pnl" data-ajax-fetch="https://cdn-canada.services.gc.qat/app/WET4/gcweb/v4_0_10/ajax/aV1_0/sitemenu-en.html" typeof="SiteNavigationElement">

2.  <div id="gcwb_prts" class="wb-eqht row" data-ajax-append="https://cdn-canada.services.gc.qat/app/WET4/gcweb/v4_0_10/ajax/ftrd_vdtt/ftrd-vdtt-en.html"></div>

3.  <div data-ajax-replace="https://cdn-canada.services.gc.qat/app/WET4/gcweb/v4_0_10/ajax/aV1_0/GoCFooterMenu-en.html" class="original"></div>






Stan Grabinski
Prgrammeur analyste | Programmer Analyst
Téléphone | Telephone 819-654-4035

**Comment by LaurentGoderre** [comment]
Are you sure that the right CORS header are returned (don't know if it's possible that Firefox doesn't treat a request as CORS bu IE does...)

**Comment by gocGrabinski** [comment]
![https_example_firefox_ajaxheaders](https://cloud.githubusercontent.com/assets/5992730/6135312/9a6dad78-b135-11e4-8bfe-2f9fc95f8462.jpg)
This is what Fire Fox shows for the response headers. Not sure what else IE would need.

**Comment by LaurentGoderre** [comment]
I think that your CORS headers are backwards. I think they need to be on the other server

**Comment by LaurentGoderre** [comment]
I tried reproducing locally and everything is working fine in IE11 for me

**Comment by gocGrabinski** [comment]
Laurent - tested a few more times using xmlHttpRequest object directly. Once again it all works great in Fire Fox but in IE11 (Edge mode) get an 'Access Denied' error after the xmlHttpRequest.open() is called.  Which lead me to this https://msdn.microsoft.com/en-us/library/ie/ms537505%28v=vs.85%29.aspx#xdomain. Looks like I will have to talk to our IE team about the Security Zone set up. Hopefully this will resolve my issue.
Is the IE8/9 fallback for CORS ( XDomainRequest ) to be part of the WET4 data-ajax scripts ?  Just wondering.
Thanks for your help with this.

**Comment by LaurentGoderre** [comment]
The fallback for CORS needs to be a server side solution, mixed with a small amount of client side script but WET has all the hooks to allow that and it is being used in some production environments. Would you want more details on how to achieve this?

**Comment by gocGrabinski** [comment]
Yes please,
As our department moves to IE11  from IE8 and our sites/web apps switch to WET4 I am sure the fallback for CORS might need to be implemented as we make the transition.

Stan Grabinski
Prgrammeur analyste | Programmer Analyst
Téléphone | Telephone 819-654-4035

**Comment by LaurentGoderre** [comment]
Basically, the fallback is to use the same concept as JSONP but with HTML (HTMLP). WET uses Modernizr to determine if CORS is supported if not, it checks if a `corsFallback` method is present and invokes it before sending the ajax request. In this method you can apply the changes to the requested needed for the HTMLP.

https://github.com/wet-boew/GCWeb/blob/master/src/theme.js#L74-L79

For the server side, you need to create a way to server the HTML as a javascript script which calls a specified function with your markup as a string (encoded). The way you implement it depends on what server you have. I created solution for IIS and Apache in the past. that I can share.

**Comment by gocGrabinski** [comment]
Have confirmed that it was an IE Zone related problem. Our application development domain falls under a different IE Zone than our development CDN domain on our network. Once in the same IE Zone data-ajax CORS works correctly in IE11.
