### ISSUE TITLE
Conditional Comments Issue with IE 11

### ISSUE THREAD

**Issue by gocGrabinski** [wet-boew/wet-boew#6508]
Was working on another issue when I noticed that IE11 was loading scripts for IE8 AND IE9 and above.
Not sure if this is intentional or not. The page on http://www.canada.ca/en/index.html still renders OK.

However there is a recurring un handled error:
SCRIPT5007: Unable to get property 'indexOf' of undefined or null reference
File: datalist.min.js, Line: 6, Column: 4354

Our IE11 Edge/Enterprise setting emulates IE8.

![ie11_console](https://cloud.githubusercontent.com/assets/5992730/6114714/0ffd63f8-b06e-11e4-9046-7400901df63f.jpg)
![ie11_network](https://cloud.githubusercontent.com/assets/5992730/6114713/0ffd4de6-b06e-11e4-8841-bbdc8ea10d57.jpg)

**Comment by CalvinRodo** [comment]
I'm not seeing these issues at all with ie11 

In ie11 edge mode I'm seeing the following coming down the pipe. 
![networkie11edge](https://cloud.githubusercontent.com/assets/87738/6115270/7114ff58-b072-11e4-8065-86a6ecfbb4d9.png)

In IE8 I get the expected scripts as well: 
![networkie8mode](https://cloud.githubusercontent.com/assets/87738/6115280/81cd4b8e-b072-11e4-947b-b8a8c7db1d4f.png)

Although it is grabbing some scripts twice in ie9 mode 

![networkie11ie9mode](https://cloud.githubusercontent.com/assets/87738/6115311/c5f5c872-b072-11e4-9137-c71dc9a69b47.png)

I'm seeing the following in my console when loading the page in Edge mode in ie11:

![2015-02-09 15_35_18-welcome to canada ca - internet explorer](https://cloud.githubusercontent.com/assets/87738/6115285/905d942e-b072-11e4-8058-b01fd3269472.png)

It seems to only cause issues with IE11 in enterprise mode when rendering in IE8 mode, it seems to work just fine when ie11 is in enterprise mode and rendering edge. 

The easiest solution is to not have any site that implements WET 4 on the enterprise mode site list for ie8, they should only render in edge mode.

**Comment by gocGrabinski** [comment]
Thanks for the quick response Calvin. 
When I try IE11 Edge mode (desktop) all works as you describe. When I try IE11 ie8 mode (desktop) I still get both sets of scripts loading.  Possible it is something else in my IE configuration/installation causing that however.
I will bring this to the attention of our IE team.
Thanks again.

**Comment by CalvinRodo** [comment]
What department are you in could it be that they have a gpo that forces enterprise mode to be on?

**Comment by pjackson28** [comment]
You should also take a look at the server configuration documentation: http://wet-boew.github.io/wet-boew/docs/server-en.html. Of particular interest is the IE compatibility mode section which provides help for configuring the server to trigger edge mode in browsers.

**Comment by gocGrabinski** [comment]
I am at ESDC.
I have an early version of our IE11 release for testing.  Roll out will be next fiscal.  We have a IE11 product management team that manages the URLs that require Enterprise mode.
I am starting to wonder if there is some other issue with my  IE11 install however.

Stan Grabinski
Prgrammeur analyste | Programmer Analyst
Téléphone | Telephone 819-654-4035

**Comment by CalvinRodo** [comment]
No i"m fairly certain it has to do with Enterprise mode, I don't think forcing edge in the headers will fix this specific problem since I believe enterprise mode ignores it, although I'm not sure if you have to turn that on per site or what. 

http://blogs.msdn.com/b/ie/archive/2014/11/11/announcing-improvements-to-the-enterprise-mode-site-list.aspx

> When Internet Explorer 11 navigates to a site on the list, the browser loads the page in the specified document mode just as it would load the page if the document mode were specified through an X-UA-Compatible meta tag on the page, and the UA string associated with the selected document mode is sent. Some customers have told us that they even need to override the X-UA-Compatible meta tag as set by the Web site, so this new functionality does so without needing to change a single line of code on the site itself. 

As far as I know with enterprise mode you have to specify what sites to render specially otherwise it works as normal. So as long as sites that use WET 4 aren't put on the list there shouldn't be an issue. WET 4 sites should work just fine with IE11 and shouldn't need to be forced to work in IE8 mode so this shouldn't be an issue.

**Comment by CalvinRodo** [comment]
@gocGrabinski I also ran into problems with WET 3 in Enterprise mode set to ie8 mode, it doesn't render well at all. 

But as I said it should not be need to run sites that have implemented WET 3 and WET 4 as they should work just fine with IE11. 

![wet3 ie11 enterprise mode](https://cloud.githubusercontent.com/assets/87738/6132636/d81a5112-b121-11e4-8d79-ef90241079c9.png)
