### ISSUE TITLE
Secondary Menu breaks JS with LI's without anchor tags in them

### ISSUE THREAD

**Issue by CalvinRodo** [wet-boew/wet-boew#6510]
The secondary menu causes a javascript error that breaks the rest of the page loading.

More specifically it causes the following error to get thrown *TypeError: i is undefined wet-boew.min.js:10* this is in Firefox 34, this causes the wb-ready.wb event to not get fired.

The following should be enough to replicate the issue. 
````html 
<nav  id="wb-sec" role="navigation">
    <h2>Assistant Menu</h2>
    <ul class="list-group menu list-unstyled">
        <li><h3>Test Header</h3>
            <ul class="list-group menu list-unstyled">
                <li><a href="#">Item 1</a></li>
                <li>Item</li>
            </ul>
        </li>
</nav>
````

We use the secondary menu in the ROE Web assistant to inform the user of the number of steps left to completing an ROE, here is an example of what I mean from our WET v3 of this page. 

![wet3sidemenuexample](https://cloud.githubusercontent.com/assets/87738/6133854/f0a9dd52-b12a-11e4-8252-685553ffdcb8.png)

**Comment by LaurentGoderre** [comment]
@CalvinRodo the left menu should not be used for this purpose because it's only meant for navigation. This kind of stuff need to be in the content area.

**Comment by CalvinRodo** [comment]
It is being used for navigating it's just restricting navigation to certain pages until you progress through the flow of the assistant.

**Comment by CalvinRodo** [comment]
@LaurentGoderre 
According to the [w3C specification for the nav element ](>http://www.w3.org/TR/html5/sections.html#the-nav-element)

>A nav element doesn't have to contain a list, it can contain other kinds of content as well. In this navigation block, links are provided in prose:

Which implies to me that what I'm doing here is kosher. Although maybe there is a better way to implement it, like disabled links

**Comment by LaurentGoderre** [comment]
I was not really referring of the markup but rather the concept of placing content that represent progress in a navigation section. Navigation on a page is a secondary element (this is why it's collapsed in mobile view) while the progress of the current task is a primary element, it does not belong in a navigation area.

**Comment by CalvinRodo** [comment]
But as i said it's not solely representing progress, it's also used as the main source of navigation in our assistant.

**Comment by pjackson28** [comment]
You are using nav for more than its intended purpose. If you want to show progression then you should be doing that in the content area where it is always available. You should be using it for a hybrid navigation/progression area as it is just for secondary navigation.

I also don't see the value of having unlinked menu items in the side menu. How is that supposed to be rendered in the mobile panel? The he is fine because it becomes the summary in the drtails/summary but what do we do with an unlinked menu item with no nested links?

Also doesn't seem like a good idea to be providing disabled navigation links in the side menu either. You should look into splitting up your navigation and progression indicators.

**Comment by LaurentGoderre** [comment]
It's not valid though to have non navigational elements in a navigation area

**Comment by CalvinRodo** [comment]
@pjackson28 

I'm using it for navigational purposes, we just don't let them navigate farther then they are allowed to. The value to have unlinked menu items is to let the user know how what further steps are left in the process. 
I guess I could just take this whole thing out of a nav element, but in my view this is a major block of navigational elements and thus is a valid usage of the nav element.

Mobile is not a concern for ROE Web we have pretty much zero users that access our site from a mobile browser.

@LaurentGoderre 

According to the W3C standard on Nav elements that I linked to earlier a nav can contain non navigation elements, in fact your secondary menus contain h3 and h2 headers which are non-navigational.


From : http://www.w3.org/TR/html5/sections.html#the-nav-element

>A nav element doesn't have to contain a list, it can contain other kinds of content as well. In this navigation block, links are provided in prose:
````html
<nav>
 <h1>Navigation</h1>
 <p>You are on my home page. To the north lies <a href="/blog">my
 blog</a>, from whence the sounds of battle can be heard. To the east
 you can see a large mountain, upon which many <a
 href="/school">school papers</a> are littered. Far up thus mountain
 you can spy a little figure who appears to be me, desperately
 scribbling a <a href="/school/thesis">thesis</a>.</p>
 <p>To the west are several exits. One fun-looking exit is labeled <a
 href="http://games.example.com/">"games"</a>. Another more
 boring-looking exit is labeled <a
 href="http://isp.example.net/">ISP™</a>.</p>
 <p>To the south lies a dark and dank <a href="/about">contacts
 page</a>. Cobwebs cover its disused entrance, and at one point you
 see a rat run quickly out of the page.</p>
</nav>
````

**Comment by LaurentGoderre** [comment]
Again, I was not talking about the spec but from a logical perspective. Headings help the grouping and the consumption of the navigation, text that is not a link and not a heading don't serve navigation purpose and it doesn't fit the mental model. 

What you could do instead is having a list of future steps in the content area and only the navigation for the past steps in the left navigation

**Comment by CalvinRodo** [comment]
So basically you guys are saying this bug isn't being fixed if not then I say feel free to close it.

**Comment by CalvinRodo** [comment]
So i just did a quick test and this is not related exclusively to the nav menu. 

````html
<div id="wb-sec" >
    <h2>Assistant Menu</h2>
    <ul class="list-group menu list-unstyled">
        <li><h3>Test Header</h3>
            <ul class="list-group menu list-unstyled">
                <li><a href="#">Item 1</a></li>
                <li>Item</li>
            </ul>
        </li>
    </ul>
</div>
````
This code will also cause javascript to break, so it seems to be related to the wb-sec class. 

As I said if this bug is not going to be fixed then you might as well close this issue.

**Comment by LaurentGoderre** [comment]
I think that this specific error has to do with putting the h3 in the list item. The h3 should not be in a list

**Comment by LaurentGoderre** [comment]
Ooops nevermind that is how it's implemented

**Comment by LaurentGoderre** [comment]
You shouldn't change the nav element to a div

**Comment by CalvinRodo** [comment]
I did it as a test, to see what was causing it.

**Comment by LaurentGoderre** [comment]
It's most likely in the logic to generate the mobile menu

**Comment by CalvinRodo** [comment]
Should that code run when it's not in mobile mode.

**Comment by LaurentGoderre** [comment]
I will fix the failure but these non links will not be included in the mobile menu

**Comment by CalvinRodo** [comment]
That's fine, as I said we have no mobile users, so no one ever sees mobile mode anyways.

**Comment by pjackson28** [comment]
Yes it needs to run when not in mobile mode as viewpoint width changes can happen on desktop and mobile devices (e.g., changing from landscape to portrait orientation or shrinking the browser window).

Also low mobile numbers is not sufficient justification for not trying to support mobile (since can change in the future and current poor mobile support could be a contributing factor). Besides, optimization for mobile devices is a requirement that applies to all public-facing GC websites and web applications (in the mobile standard).

**Comment by CalvinRodo** [comment]
I'm pretty sure we aren't assessing for the mobile standard here, once we do I'll worry about it, but until that time I'm not going to spend my time worrying about implementing features that no one is using. 

Once they start accessing our site through mobile devices then it will be worth optimizing for it. Until that time the most I will do to accommodate Mobile users is implement WET.
