### ISSUE TITLE
flot plugin loading issues

### ISSUE THREAD

**Issue by danpoleary** [wet-boew/wet-boew#6516]
I also left comments in https://github.com/wet-boew/wet-boew/issues/4466.

when using the following code:
```
<script>
(function( wb ) {
"use strict";

// List of dependencies to load
var deps = [
        "site!../demos/charts/jquery.flot.navigate.js", "site!../demos/charts/jquery.flot.navigationControl.js" // Script location
    ];
/*
// Use this is you have included the script in a "deps" folder then build WET 4
var modeJS = wb.getMode() + ".js",
    deps = [
        "site!deps/jquery.flot.stack.js" + modeJS // Script location
    ];
*/

// Bind, only once, to the event that initiate the parsing of the table.
// because at that time, flot is loaded
wb.doc.one( "pasiveparse.wb-tableparser.wb", ".wb-charts", function( ) {
    // Load dependencies
    Modernizr.load({
        load: deps
    });
    return true; // allows the events to continue
});

})( wb );
</script>
```

The plugins are only loaded if 2 or more table charts exist on the page. if only one, they are not loaded.

I have dug deeper into this issue, and you can repeat it on the sample charts/charts-en.html sample page.

Take the above code, and add it to the page, but instead of stacked, use flot.navigate and flot.navigationControl.

Apply the following to the bar table example on the charts-en.html page:
```
data-flot='{ "zoom": { "interactive": true }, "pan": {"interactive": true}, 
            "navigationControl": {
        "display": true,
            "homeRange": {"xmin":-10,"xmax":10,"ymin":-10,"ymax":10},
            "panAmount": 100,
            "zoomAmount": 1.5,
            "position": {"left": "20px", "top": "20px"}

    }}'
```
When you run the page, the bar chart will have navigation controls as expected.

Now, comment all the other charts except for the bar chart and re-run the page. No navigation will be loaded for the bar chart.

Now add an empty chart table entry anywhere else on the page (KEY):
```
<table class="wb-charts wb-charts-area table"></table>
```
Re-run the page... Surprise, the bar chart now has navigation again.

It appears that there is an error in wet-boew.js, creating a race condition. Here is what I was able to trace so far for both conditions.

    Only the bar chart table exists - No navigation generated.
    a. wet-boew - Modernizr.load = function () { yepnope.apply(window, [ ].slice.call(arguments, 0))}
    Called 3 times, base load, for the built in flot plugins, and for prettify
    b. wet-boew - modernizer.load() is called.
    c. (a.) is called again for the flot.navigate and flot.navigationControl plugins.
    d. jquery.flot - initPlugins is called with only pie, canvas, and orderBars.
    e. flot.navigate and flot.navigationControl are loaded and push'd to the plugins.
    Page is loaded, but no navigation controls.

    The bar chart table exists and one empty chart table as per (KEY) above - navigation generated.
    a. wet-boew - Modernizr.load = function () { yepnope.apply(window, [ ].slice.call(arguments, 0))}
    Called 4 times, base load, for the built in flot plugins twice, and for prettify
    b. wet-boew - modernizer.load() is called.
    c. (a.) is called again for the flot.navigate and flot.navigationControl plugins.
    d. flot.navigate and flot.navigationControl are loaded and push'd to the plugins.
    e. wet-boew - modernizer.load() is called.
    f. jquery.flot - initPlugins is called with pie, canvas, orderBars, navigate, and navigationControl.
    g. both flot.navigate and flot.navigationControl init functions called.
    Page is loaded, with navigation controls.

Dan

**Comment by LaurentGoderre** [comment]
That code doesn't seem very robust as far as async go, Modernizr load is not synchronous so parsing occurs before the plugin is loaded.

**Comment by danpoleary** [comment]
That code was from the other ticket! So if that code is not proper, how do we load flot plugins then?

**Comment by LaurentGoderre** [comment]
Please test the latest change and let me know
