### ISSUE TITLE
Form Validation and Tab interface: How to add a custom validation method?

### ISSUE THREAD

**Issue by spacejang** [wet-boew/wet-boew#6519]
Hi there,

I have a form inside Tabbed interface.
1. custom validation method works if the form is without Tabbed interface. however the following code does not work.
```html
<div class="wb-tabs">
	<div class="tabpanels">
		<details id="details-panel1">
			<summary>Test Search</summary>
			<div class="wb-frmvld">
				<form name="" action="searchResult-en.html" method="get" class="form-horizontal" id="Reports">
					<div class="panel panel-default">
						<div class="panel-heading">
						  <h2 class="panel-title">Test Search</h2>
						</div>
						<div class="panel-body">
							<div class="form-group">
								<div class="col-sm-3 control-label">
									<label>Report Start Date:</label>
								</div>
								<div class="col-sm-9">
									<label for="startDate" style="font-weight: normal;">Start Date<span class="datepicker-format"> (<abbr title="Four digits year, dash, two digits month, dash, two digits day">YYYY-MM-DD</abbr>)</span></label>
									<input class="form-control" type="date" id="startDate" name="startDate" min="2011-11-24" />
								</div>
							</div>
							<div class="form-group">
								<div class="col-sm-3 control-label">
								  <label class="wb-inv">Report Start Date</label>
								</div>
								<div class="col-sm-9">
									<label for="endDate" style="font-weight: normal;">End Date<span class="datepicker-format"> (<abbr title="Four digits year, dash, two digits month, dash, two digits day">YYYY-MM-DD</abbr>)</span></label>
									<input class="form-control maxDate" type="date" id="endDate" name="endDate" min="2011-11-24" />
							   </div>
							</div>
						</div>
					</div>
				</form>
			</div>
		</details>
	</div>
</div>
```
```javascript
$(".wb-frmvld").on("wb-ready.wb-frmvld", function (event) {

        $.validator.addMethod("beforeDate", function (value, element, param) {
            return this.optional(element) || (($(param).val() === '') ? false : (value >= $(param).val()));
        }, "Please enter a EndDate greater than or equal to StartDate");

        var now = new Date();
        var day = (now.getDate() < 10 ? '0' : '') + now.getDate();
        var month = ((now.getMonth() + 1) < 10 ? '0' : '') + (now.getMonth() + 1);
        var year = now.getFullYear();
        var todayDate = year + "-" + month + "-" + day;

        $("#endDate").rules("add", {
            beforeDate: "#startDate",
            max: todayDate
        });

        $("#startDate").rules("add", {
            max: todayDate
        });
});
```

it would be greatly appreciated if you could help.Thanks

**Comment by spacejang** [comment]
<div class="wb-tabs">
            <div class="tabpanels">
                <details id="details-panel1">
                    <summary>Test Search</summary>
                    <div class="wb-frmvld">
                        <form name="" action="searchResult-en.html" method="get" class="form-horizontal" id="Reports">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h2 class="panel-title">Test Search</h2>
                                </div>
<div class="panel-body">
                                <div class="form-group">
                                    <div class="col-sm-3 control-label">
                                        <label>Reprt Start Date:</label>
                                    </div>
                                    <div class="col-sm-9">
                                        <label for="startDate" style="font-weight: normal;">Start Date<span class="datepicker-format"> (<abbr title="Four digits year, dash, two digits month, dash, two digits day">YYYY-MM-DD</abbr>)</span></label>
                                        <input class="form-control" type="date" id="startDate" name="startDate" min="2011-11-24" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-3 control-label">
                                        <label class="wb-inv">Reprt Start Date</label>
                                    </div>
                                    <div class="col-sm-9">
                                        <label for="endDate" style="font-weight: normal;">End Date<span class="datepicker-format"> (<abbr title="Four digits year, dash, two digits month, dash, two digits day">YYYY-MM-DD</abbr>)</span></label>
                                        <input class="form-control maxDate" type="date" id="endDate" name="endDate" min="2011-11-24" />
                                    </div>
                                </div>
                            </div>

-------------------------
    $(".wb-frmvld").on("wb-ready.wb-frmvld", function (event) {

    $.validator.addMethod("beforeDate", function (value, element, param) {
        return this.optional(element) || (($(param).val() === '') ? false : (value >= $(param).val()));
    }, "Please enter a EndDate greater than or equal to StartDate");

    var now = new Date();
    var day = (now.getDate() < 10 ? '0' : '') + now.getDate();
    var month = ((now.getMonth() + 1) < 10 ? '0' : '') + (now.getMonth() + 1);
    var year = now.getFullYear();
    var todayDate = year + "-" + month + "-" + day;

    $("#endDate").rules("add", {
        beforeDate: "#startDate",
        max: todayDate
    });

    $("#startDate").rules("add", {
        max: todayDate
    });
    });

**Comment by LaurentGoderre** [comment]
@spacejang you can wrap block of code with 3 of the ` character followed with the language to create codes of block.

**Comment by LaurentGoderre** [comment]
@spacejang it is also recommended to use bubbling for event handler. You should be using:

```javascript
wb.doc.on("wb-ready.wb-frmvld", ".wb-frmvld", function (event) {

});
```

**Comment by spacejang** [comment]
The following code does not work for me.
wb.doc.on("wb-ready.wb-frmvld", ".wb-frmvld", function (event) {
    $.validator.addMethod("beforeDate", function (value, element, param) {
        return this.optional(element) || (($(param).val() === '') ? false : (value >= $(param).val()));
    }, "Please enter a EndDate greater than or equal to StartDate");

 ..........more code ...
    });

**Comment by LaurentGoderre** [comment]
It gives you an error or it doesn't do anything?

**Comment by spacejang** [comment]
it doesn't do anything? Form submitted without "message"..

**Comment by LaurentGoderre** [comment]
And outside of the tabbed interface it works?

**Comment by spacejang** [comment]
yes. it works both. Thanks
1. wb.doc.on("wb-ready.wb-frmvld", ".wb-frmvld", function (event) {
2.  $(".wb-frmvld").on("wb-ready.wb-frmvld", function (event) {

**Comment by hsrudnicki** [comment]
@spacejang @LaurentGoderre : Can this issue be closed?

**Comment by pjackson28** [comment]
@spacejang Can you reproduce the issue with the latest code? I recall an event bubbling issue with the tabbed interface that was resolved a few versions ago that may have caused issues with a nested form. If it still doesn't work, maybe try using wb-ready.wb (when all WET initialization has completed) to see if waiting until then makes a difference.

**Comment by hsrudnicki** [comment]
@spacejang and others: Made "Going Stale" to close this issue as resolved or if otherwise?
Either way, please update this issues status, thank you

**Comment by hsrudnicki** [comment]
Is this still an issue waiting for an answer from @spacejang? Either way, please update the status of this issue, whether this issue can closed as resolved/fixed or otherwise, thank you

**Comment by spacejang** [comment]
Thank you for all of your comment. We decided the form outside of Tabbed interface a long time ago. However I will try it later with new wet templates. Thank you all.
