### ISSUE TITLE
Generic root-level pages (except 404) are broken in all themes

### ISSUE THREAD

**Issue by EricDunsworth** [wet-boew/wet-boew#6528]
The pages in question are fine in the wet-boew repo's site, but are broken in various ways throughout all other theme repos. Seems like wet-boew's version of the pages in question are getting re-used "as-is" in the other themes.

Any chance this could be looked into? Not sure if there's any value in keeping the license pages (.txt versions already exist in the repos), but IMO the index pages should be kept and based off the themes' own splash page examples.

Links follow...

**wet-boew (for reference - all other themes are broken):**
* http://wet-boew.github.io/v4.0-ci/index.html
* http://wet-boew.github.io/v4.0-ci/License-en.html
* http://wet-boew.github.io/v4.0-ci/Licence-fr.html

**GCWeb:**
* http://wet-boew.github.io/themes-dist/GCWeb/index.html (should probably look like [this](http://wet-boew.github.io/themes-dist/GCWeb/splashpage.html))
* http://wet-boew.github.io/themes-dist/GCWeb/License-en.html
* http://wet-boew.github.io/themes-dist/GCWeb/Licence-fr.html

**theme-gcwu-fegc:**
* http://wet-boew.github.io/themes-dist/theme-gcwu-fegc/index.html (should probably look like [this](http://wet-boew.github.io/themes-dist/theme-gcwu-fegc/splashpage-en.html))
* http://wet-boew.github.io/themes-dist/theme-gcwu-fegc/License-en.html
* http://wet-boew.github.io/themes-dist/theme-gcwu-fegc/Licence-fr.html

**(other themes are impacted too)**

**Comment by LaurentGoderre** [comment]
Can you provide more details, these links seem to work....

**Comment by EricDunsworth** [comment]
@LaurentGoderre Here's a few screenshots for reference...

http://wet-boew.github.io/themes-dist/GCWeb/License-en.html
![gcweb-license](https://cloud.githubusercontent.com/assets/1907279/6218384/35f12fd0-b5ec-11e4-9726-80e31c67a70a.png)

http://wet-boew.github.io/themes-dist/theme-gcwu-fegc/index.html
![gcwu-index](https://cloud.githubusercontent.com/assets/1907279/6218388/400ae11e-b5ec-11e4-83ea-4e2cb7fb7f71.png)

**Comment by LaurentGoderre** [comment]
Oh ok. Feel free to open a PR but this is definitely not a priority

**Comment by EricDunsworth** [comment]
I don't think I'm familiar enough with how the build system piggybacks on wet-boew when building themes to be able to fix it myself.

If I have a chance and can figure it out I'll try fixing it. Otherwise, someone else that has more experience with configuring the build system might need to look into it at some point.

**Comment by hsrudnicki** [comment]
@EricDunsworth @LaurentGoderre : Are you ready to close this issue

**Comment by EricDunsworth** [comment]
@hsrudnicki This issue is still occurring to this day.

**Comment by hsrudnicki** [comment]
@EricDunsworth @LaurentGoderre : Can be this issue's closed as resolved or otherwise?

**Comment by EricDunsworth** [comment]
@hsrudnicki Yep :). Looks like the busted pages in the other themes have ceased to exist, so we're in business!
