### ISSUE TITLE
Feedback form comment box-character limit

### ISSUE THREAD

**Issue by nrustand92** [wet-boew/wet-boew#6534]
Is it possible to have the number of remaining characters updated as users type in a comment box (see the input field under "Please provide details"):
http://www.canada.ca/en/contact/feedback.html

I'm not putting this under the GCWeb repo because perhaps it's applicable to forms in various themes and working examples.

The idea is to look like this:
![characterlimit](https://cloud.githubusercontent.com/assets/5949078/6232552/b9e2e398-b69a-11e4-9b7b-ddc9aca2d0d5.png)

**Comment by RobJohnston** [comment]
I'll add to this a request to do a word count as well as a character count.  Some inspiration:
 * http://www.sitepoint.com/10-jquery-wordtext-counter-plugins/
 * http://stackoverflow.com/questions/14010446/word-and-character-count-using-jquery

**Comment by LaurentGoderre** [comment]
Word count is a lot harder to implement because of JavaScript lack of support for french characters in Regular Expressions. More specifically, the word boundary regular expression doesn't work on words that begin or end with a french accent

**Comment by RobJohnston** [comment]
I think this guy might have it:  http://plugins.jquery.com/word-and-character-counter/

**Comment by LaurentGoderre** [comment]
Not bad!

**Comment by RobJohnston** [comment]
So for @nrustand92 and others, I've tried this out and it's working well for me.  Nice and quick too compared to a normal javascript counter (at least up to 3000 words, which is my limit).  To get results like in the screenshot of the original post, you would need something like this, placed after jquery loads:

```html
    <script src="Scripts/word-and-character-counter.js"></script>
    <script type="text/javascript">
        wb.doc.on("wb-ready.wb", function (event) {
            $("#details").counter({
                goal: 1200,
                count: 'down'
            });
        });
    </script>
```

This assumes a textarea with an ID of "details" and will produce a message like "1189 character(s) left".

**Comment by nrustand92** [comment]
Nice!!!

**Comment by nrustand92** [comment]
Thanks @RobJohnston!
@LaurentGoderre would you or someone else be able to implement this feature on a working example?
If not, that's ok, just asking :)  thank you in advance.

**Comment by LaurentGoderre** [comment]
Eventually maybe but we are a bit busy right now

**Comment by nrustand92** [comment]
no worries thx!

**Comment by hsrudnicki** [comment]
Are you ready to close this issue or otherwise?

**Comment by hsrudnicki** [comment]
Based on the above, made "Going Stale" and closed this issue as resolved for now at least or if otherwise? Then, please update this issue's status again, thank you

**Comment by robwloch** [comment]
Just wondering if someone would have the time to add this feature to the working example?
