### ISSUE TITLE
Tabbed Interface breaks change event on element

### ISSUE THREAD

**Issue by GarthMartin** [wet-boew/wet-boew#6537]
I have a jQuery applied change event on a select element that works fine in a regular panel layout, but when the exact same code is applied in a tabbed interface layout, the change event never fires.  (it is the exact same code since I am mocking up 2 UI looks for the client.)

I call the same code in the document.ready function and it works as expected, but never fires on change.

The source looks fine in the tabbed interface, and behaves the same in all browsers. 

My document.ready looks like this in both scenarios:

$("#ContactTypeValue").change(function() {ToggleInternalExternalContactDetails();});

The Toggle... function currently simply contains an alert and in the regular Panel layout, it fires, but in the tabbed interface layout, it does not.

Any thoughts?

Thanks,

Garth

**Comment by LaurentGoderre** [comment]
There seem to be something going on with the tabbed interface....there are a few plugins that have issue in it. I will investigate.

**Comment by LaurentGoderre** [comment]
Actually you can probably fix your issue by changing your code to the following:

```
wb.doc.on("change", "#ContactTypeValue", function() {ToggleInternalExternalContactDetails();});
```

**Comment by LaurentGoderre** [comment]
The tabbed interface performs a DOM rewrite which invalidates that selector. By listening on the document and filtering by ID it guarantees that handler will work event on DOM changes

**Comment by GarthMartin** [comment]
Thanks Laurent.  That fixed the issue.  What exactly is the wb.doc object? I am not that familiar with it.
Cheers,

**Comment by LaurentGoderre** [comment]
`wb.doc` is a cached version of `$(document)`. Creating a jQuery object wastes resources so we cached the ones that are used frequently so your code doesn't have to.

**Comment by GarthMartin** [comment]
Thanks again.
