### ISSUE TITLE
Tabs should provide a way to disable the remember last tab functionality

### ISSUE THREAD

**Issue by andre-d** [wet-boew/wet-boew#6538]
I have an application like /View/170 with a tab inside it for info and another for related metadata.  I would like (and in testing it seems the user expects it to) when visisiting /View/170 to always give you the Info panel and not remember your last tab open.

I am aware I can use /View/170#Info or what have you and always be explicit, but it would be nice to not require or redirect to the fragment unless you are being explicit.   

I imagine there are other use cases where you wouldn't expect the last tab to remembered, for example a Preferences page with a few tabs inside it might expect /Preferences to always give you the general preferences tab and not display "other options" or something first. (And at the same time not have to link to /Preferences#GeneralOptions

**Comment by crichard** [comment]
See #6252 .  If your page has a unique page id, the tab selection from a previous page should not be remembered.

**Comment by andre-d** [comment]
I would still like the ability to optionally direct link to a tab. Like in
the preferences example. Removing the ID removes the ability all together.

**Comment by crichard** [comment]
Until a feature like that is implemented, I think you can disable session storage for a page.  You can use this function and call it on a specific page.  It worked in WET 3.1, I don't know about WET 4.0.

```
function disableSessionStorage() {
        if (typeof window.sessionStorage !== 'undefined') {
            var key,
        len = window.sessionStorage.length;
            // Check all sessionStorage keys and remove the tabbed interface activePanel keys
            while (len--) {
                key = window.sessionStorage.key(len);
                if (key.indexOf('activePanel-') === 0) {
                    window.sessionStorage.removeItem(key);
                }
            }
        }
    }
```

**Comment by andre-d** [comment]
Yeah. I did something like that. It changed a bit in four but basically on
load early on in the page load I remove any previous keys about the tab.

**Comment by pjackson28** [comment]
The easiest way would be to specify the tab you want active in the URL hash. The URL hash will always override whatever the plugin remembers as the last active tab. You could do the same thing with the <code>wb-select.wb-tabs</code> event as well.

**Comment by pjackson28** [comment]
It probably would be fairly easy to add an option to the plugin that makes it ignores sessionStorage as well (ignoring would be off by default). Anyone interested in taking a crack at it? It could just be a boolean available through data-wb-tabs and a simple conditional wrapped around each sessionStorage area.

**Comment by LaurentGoderre** [comment]
Since it's a boolean, why not use a class name instead? It would simplify the code. I'm just not sure what to call that class

**Comment by crichard** [comment]
ignoreSession maybe ?

**Comment by pjackson28** [comment]
You could make it available through a class name, but it should be available through the data attribute as well. Otherwise you wouldn't be able to specify a global setting for the page (e.g., through <code>window[ "wb-tabs" ]</code>). Also note that we don't use camel-case for class names (so "ignore-session" may be better).

**Comment by LaurentGoderre** [comment]
Sounds good!

**Comment by crichard** [comment]
Can I give it a try, or do you want to do it @andre-d ?

**Comment by LaurentGoderre** [comment]
@crichard go ahead! ;)
