### ISSUE TITLE
<cite> font-style

### ISSUE THREAD

**Issue by Bgolden67** [wet-boew/wet-boew#6544]
Just wondering what the reasoning was behind changing the <cite> tag from italicized by default to normal font in the css?

Which then brings the question of what should publishers be using to italicize their cited text..  should they start using <i> again after so many years of avoiding it so as to not use <em> and emphasize it?

**Comment by LaurentGoderre** [comment]
@Bgolden67 Bootstrap italicizes the `cite` element in the new version so there is no reason for us to duplicate it.

**Comment by Bgolden67** [comment]
So in the next release cite will be italicized again? In 4.0.10, of the canada.ca theme the  cite tag is set to normal in the wet-boew-min.css and this is over riding the default action to italicize it.

**Comment by LaurentGoderre** [comment]
The next release will be fixed.

**Comment by hsrudnicki** [comment]
So, based on the above, can this issue be closed?

**Comment by Bgolden67** [comment]
Thanks!
