### ISSUE TITLE
Must click twice on validation summary error messages

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/wet-boew#6545]
Go to the form validation page (http://wet-boew.github.io/wet-boew/demos/formvalid/formvalid-en.html) and click submit.  You will see 7 errors listed in a validation summary.  Click one, and it goes to the correct form field.  Now scroll up to the validation summary again and click one.  It will do nothing.  If you click twice it will go to the form field.  Tested in IE9, FF 18, Chrome 40, all the same.

**Comment by crochefort** [comment]
Look's like on the first click it's loosing the focus and after that ... it goes. I hope this help.

**Comment by pjackson28** [comment]
I checked in the JS and the click event on those links are not making it to the document node when focus was in the field initially.  This likely is because the summary is updated every time there is a field blur.

**Comment by pjackson28** [comment]
PR #6561 should address the issue. It introduces a 100ms delay before updating the summary links to give enough time for events to bubble up.
