### ISSUE TITLE
Date picker icon not displaying with IE9?

### ISSUE THREAD

**Issue by juliemercier** [wet-boew/wet-boew#6546]
When I look at this page: http://wet-boew.github.io/wet-boew/demos/datepicker/datepicker-en.html, I do not see the datepicker icon. However, when I click where the icon should be, the calendar picker displays. I checked with some of my colleagues and we all have the same issue. Is there something we're missing? Thanks.

**Comment by RobJohnston** [comment]
Hit F12 and make sure that you're in the "Browser Mode: is "IE9" and not "IE9 Compatability View"?

**Comment by JasonTBS** [comment]
While in IE9 edge mode I still do not see the glyphicons. When doing a network capture within the IE9 developer window I do not see the glyicons resource being loaded.

**Comment by juliemercier** [comment]
Is it possible, glyphicons are being blocked by the firewall?

**Comment by juliemercier** [comment]
When I go to this page: http://glyphicons.com/, out of 610 icons, I see a little over a dozen icons and on this page: http://getbootstrap.com/components/ I only a dozen icons.

**Comment by LaurentGoderre** [comment]
@juliemercier is this occuring on your personal computer or your work one?

**Comment by juliemercier** [comment]
We are all having this issue at work.

**Comment by LaurentGoderre** [comment]
This is caused by a network policy put in place by SSC which blocks font icons from being loaded. It is not an issue with this project

**Comment by juliemercier** [comment]
OK. Thank you.
