### ISSUE TITLE
Thumbnail Images overlay on the Main Image

### ISSUE THREAD

**Issue by ikug** [wet-boew/wet-boew#6548]
I have an issue with slide show for image.
I attach it with the message below. My concern is what happens if the images in the thumbnail are more than 3 or 4, with "Play" button are wider than the certain size(displaying size for single image on the above), how the thumbnail looks like with all the small images?
For an instance, that I have 7 images put into slideshow for image, and how the 7 images display in the thumbnail area?

We are using WET 4.0.9.

![image](https://cloud.githubusercontent.com/assets/10654702/6271606/b33e197c-b82f-11e4-91c3-dced76b548c9.png)

**Comment by ikug** [comment]
I also test it on another case with lower resolution with no wide images. It seems  thumbnail area got extended based on how high the size of image.
In my next attachment, I only put 3 images into thumbnail, but because of height, the thumbnail area covers caption area, and "Play" or "Pause" button is overlay on the image.

Does thumbnail class has dynamicly controlling the size of itself, based on what kind of size of images? Otherwise, there is no limit for how many images can be put into thumbnail area, then that will be what you will see.
Or should it have a rule that mention the limitation of images, and resolution of image as well...

![image](https://cloud.githubusercontent.com/assets/10654702/6276433/c5fb7184-b854-11e4-9020-646814cec954.png)

**Comment by ikug** [comment]
I would like to add an additional issue within this ticket.
It is about a scrollbar showing underneath of displaying image itself. This issue has already showed in the first comment above, and I attach another image below, so that it will look clearly.

Also this issue happens in IE only, not in Firefox and Chrome.

![slideshow with scrollbar](https://cloud.githubusercontent.com/assets/10654702/6397339/fd7a48b2-bdb1-11e4-9ccf-f29d544b0ef9.jpg)

**Comment by ikug** [comment]
I knew what causes has a scrollbar on image itself in IE. 
It has a extra row class above the credit content. Once I removed the row class then it shows properly.

![image](https://cloud.githubusercontent.com/assets/10654702/6401826/39ca6f6c-bdd1-11e4-9dd4-a8ad4578a4af.png)

**Comment by ikug** [comment]
Has this issue been fixed and added to 4.0.12 release?
If yes, how the images will be displayed in thumbnail? Let's see if I have 20 images in thumbnail...

**Comment by LaurentGoderre** [comment]
This has not yet been fixed no.

**Comment by LaurentGoderre** [comment]
This is a duplication of #6039 which @crichard is working on
