### ISSUE TITLE
Feature/Plugin Request: Tag/Word Cloud

### ISSUE THREAD

**Issue by sviens** [wet-boew/wet-boew#6549]
On behalf of the Marketing and Social Media group at Public Safety Canada, I'd like to request a tag/word cloud feature. Example: http://www.wordle.net/

The intended use is to provide greater prominence to words that appear more frequently in the content of the Get Cyber Safe blog and allow navigation based on these words.

Thank you.

**Comment by zachfalsetto** [comment]
Would there be a limit to the amount of words included in the word cloud? I find that if there are too many words, it is far less effective. Also these things take up a large amount of space. On the blog I see a large search section followed by the blog articles. Would this further push the articles below the fold?

**Comment by sviens** [comment]
I don't see why the word count couldn't be limited, especially it if helps usability. Maybe a limit of 20-25 words? The search section is being removed in the coming months (tied to our upgrading to WET4).

**Comment by LaurentGoderre** [comment]
I am curious what @pcwsmith opinion is on this

**Comment by pcwsmith** [comment]
Tag clouds are are pretty much unusable as a nav pattern - they are over-complicated and confusing to most people. I would advise against going there.There is certainly no plan to make this an available in-page nav pattern in the Content and IA spec.

(Really these are meant more as tools for analyzing information - even there, they are mostly a toy.)

**Comment by sviens** [comment]
Thank you for reviewing this request.

**Comment by nellleo** [comment]
@pcwsmith Many readers find them easy mechanisms to filter content. Is there something that could be created to carry popular/widely-used blog widgets like tag clouds that can be introduced here? I'm very much against GC blogs looking as sterile as they do minus the widgets (and they honestly still do.. :-) ).

**Comment by LaurentGoderre** [comment]
You are welcome to open a PR for this features but we will not be working on this for the time being

**Comment by pcwsmith** [comment]
FWIW, a better pattern might be tag-specific navigation - where each post is tagged with a few keywords, and clicking on a tag associated with an individual post delivers a list of all/recent posts that have also been tagged with that keyword. Have not researched this in any detail, but seems to me to be more relevant and unobtrusive way of promoting discovery of similar content within a blog. Somehting to consider if you want to pursue this.

**Comment by hsrudnicki** [comment]
Are you ready to close this issue?

**Comment by hsrudnicki** [comment]
Due to the above and no further discussion, made "Going Stale" and closed this issue or if otherwise (then please update this issue's status) ?
