### ISSUE TITLE
SCSS variables: Inventory

### ISSUE THREAD

**Issue by melodyma** [wet-boew/wet-boew#6551]
@LaurentGoderre - Just taking an inventory of everything that has to have it's variables pulled out to the variables file. It would great if you can confirm!

- [ ] Cal Events ???
- [ ] Calendar ???
- [ ] Charts
- [ ] Core ???
- [ ] Lightbox
- [ ] Overlay
- [ ] Tables
- [x] Tabs/Carousel
- [ ] Text Highlight
- [ ] Zebra

**Comment by LaurentGoderre** [comment]
Maybe Feeds, Share and Toggle too

**Comment by hsrudnicki** [comment]
Are you ready to close this issue?

**Comment by hsrudnicki** [comment]
Made "Going Stale" in order to close this issue if no further discussion/status updates or if otherwise? Either way, please update this issue's status, thank you

**Comment by hsrudnicki** [comment]
Is this still an issue? Either way, please update the status of this issue, whether this issue can be closed as resolved/fixed or otherwise, thank you

**Comment by hsrudnicki** [comment]
Due to the above, this issue can be closed. If you think otherwise, please update the status of this again, thank you
