### ISSUE TITLE
Data Ajax: pulling in content by id not working

### ISSUE THREAD

**Issue by Christopher-O** [wet-boew/wet-boew#6563]
In WET version 4.0.3 and prior, there was a function available for the data ajax script to directly pull content from a page by ID, class or tag.  For example the ajax call would be something like 
="ajax/data-ajax-extra-2-en.html #ajax-content"
that would pull content wrapped with the id of "ajax-content".  You can further customize it by pulling in by class and/or certain tags within that content.
As of version 4.0.4, that function has disappeared due to a change in the ajax-fetch and data-ajax scripts in the wet-boew.js script.   Is it possible to get this function back for a future version of WET4?  Or is there a new way to pull in content based on id/class/tag??

**Comment by LaurentGoderre** [comment]
It's weird....I can't find it anywhere....

**Comment by LaurentGoderre** [comment]
I don't think either of these plugins ever had that functionality. The only one that does is the lightbox plugin

**Comment by pjackson28** [comment]
It actually did because before 4.0.4 it used the load() function (now uses the ajax() function). According to jQuery: "The .load() method, unlike $.get(), allows us to specify a portion of the remote document to be inserted. ... When this method executes, it retrieves the content of ajax/test.html, but then jQuery parses the returned document to find the element with an ID of container."

So essentially load has an extra filter on top of the normal ajax() function. So for this to work in WET, that filter would have to be applied on the returned results.

**Comment by Christopher-O** [comment]
I was looking at the load() jQuery function online and it mimics exactly how our current WET4 template operates (we are still using WET 4.0.0).  We would like to update to 4.0.11 to take advantage of a few new features that became live in 4.0.5 but we do not want to lose this great feature by doing so.

**Comment by LaurentGoderre** [comment]
Using the ajax method gives as a much greater level of control on the ajax process but we can look at adding this functionality.

**Comment by Christopher-O** [comment]
That would be greatly appreciated!

**Comment by pjackson28** [comment]
We recently added similar functionality to the Lightbox plugin (https://github.com/wet-boew/wet-boew/blob/master/src/plugins/lightbox/lightbox.js#L215-L220). It isn't as full-featured as what jQuery provided as it only allows selecting by the URL hash (so just by id). If the select by id is all that is needed then we could use the Lightbox approach. If more is needed, then perhaps whatever is developed could be used for Lightbox as well (while still supporting selecting by URL hash).

**Comment by Christopher-O** [comment]
90% of the time, we use the ID approach (hashtag), but for our main page we use the class approach 
="ajax/data-ajax-extra-2-en.html .ajax-content" and add the class ajax-content inside the class="" part of a tag, so that we can pull multiple pieces (like story items), into a div tag to build up content.   I have also used the tag function
="ajax/data-ajax-extra-2-en.html #ajax-content li" to re-customize tags with different classes/styles on other pages.  Also we have been known to use multiple ids (similar to the class approach), if we want the webmaster ONLY to pull in certain bits of content
="ajax/data-ajax-extra-2-en.html #ajax-content,#ajax-content2"

It would be nice to get all the flexability of the jQuery load() function back as it helps with removing the need to duplicate content across multiple sources and introducing the risk of mistakes by doing so.  We are not in any rush to update as of yet, so I would rather hold off on using the lightbox approach if this could be re-implimented.

**Comment by LaurentGoderre** [comment]
I don't think WET should provide more than ID selection. We can provide the option to provide a custom filter function that overrides our basic one.

**Comment by Christopher-O** [comment]
Another possibility (if adding these functions to the ajax() function to be an issue), could be to reimplement the load() function from 4.0.3 with a different set of attributes (e.g. data-load-append/data-load-replace/etc.).

**Comment by LaurentGoderre** [comment]
@Christopher-O we can't go back to the load because it does not give enough control for request like JSONP etc.

**Comment by Christopher-O** [comment]
Okay, thanks for the comment, I look forward to seeing what might come out of this.

**Comment by shawnthompson** [comment]
As am I!
