### ISSUE TITLE
populating a dataTables dynamically

### ISSUE THREAD

**Issue by DavidTrottier1** [wet-boew/wet-boew#6571]
using wet 4.0.10
developing with ie9

I wonder if anyone has managed to populate a wet 4 datatables dynamically using .net c#. I see in the working example that all table are being populated by static values or by json files but i'm looking to fill the table dynamically from database. dotnet gridview is what I am currently using but I wish I could use the datatable from the wet to stay consistent. Or is there a way to apply the wet look and feel to an existing gridview ou listview using wet calsses? 

thanks for your support,
David

**Comment by LaurentGoderre** [comment]
@DavidTrottier1 you could create an API that output the JSON file dynamically for the table

**Comment by sgdowney** [comment]
When you say that you want to populate dynamically, what do you mean exactly?  Will the data be available as the page is being generated on the server or will be pulled in after rendering on the client browser?

**Comment by DavidTrottier1** [comment]
the data would be available after the page is generated since I'm using server side entity framework to pull the data direct from the database.

I'm starting to think that a web API linked to the database that output a json is the only way around. what do you think?

I was also trying to adapt the wet 4 look and feel to my dotnet gridview but no success.

**Comment by LaurentGoderre** [comment]
@DavidTrottier1 it may not be the only option but I believe it's the most flexible and future proof one. Let me know if you need help implementing it.

**Comment by sgdowney** [comment]
There are a few ways to approach this.  I'm assuming that your page will execute some type of Ajax request to get the data.  The results could be returned in a couple of ways:
1.  A JSON formatted array of objects.
2.  An HTML table with all the prerequisite classes set on it.  The datatable plugin could then be manually initialized.
For the data api you could go with http://www.odata.org/ and use an OData plugin for datatables.  I have played with that as well.

**Comment by DavidTrottier1** [comment]
thanks for your support guys, I'll let you know if I need any help implementing it. your help is very appreciated.

**Comment by LaurentGoderre** [comment]
OData looks cool but might be overkill for a simple API to start. .NET has really good JSON serialization functionality

**Comment by DavidTrottier1** [comment]
awesome, I'll look into the .NET solution
