### ISSUE TITLE
WET Input type="date" polyfill (date picker) not showing up

### ISSUE THREAD

**Issue by E1D1** [wet-boew/wet-boew#6572]
Good day,

I'm trying to implement the date picker using and it doesnt seems to be showing up. I see the input but the calendar icon is not showing up in EI nor in Firefox.

here is the code.
```
<div class="form-group">
	<label for="startdate">Start Date<span class="datepicker-format"> (<abbr title="Four digits year, dash, two digits month, dash, two digits day">YYYY-MM-DD</abbr>)</span></label>
	<input class="form-control" type="date" id="startdate" name="startdate"  />
</div>

```

**Comment by LaurentGoderre** [comment]
Is it working in our example for you?

**Comment by E1D1** [comment]
No...I use the same example from the WET website. exactly as displayed in the code

**Comment by LaurentGoderre** [comment]
I meant is it working on the WET website?

**Comment by LaurentGoderre** [comment]
@E1D1 any update on this?

**Comment by E1D1** [comment]
This can be closed as it was a nested div issue
