### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by b0uch3** [wet-boew/wet-boew#6580]
I'm having a UX consistency problem when using the date type attribute in IE.

In my forms, I am implementing action buttons using input-group-addon.  However when I try and set a date field using type=date, the generated calendar icon cannot be attached the same way from what I can tell.

Here's what I'm trying to achieve along with what the datepicker documentation example creates.

![date-field](https://cloud.githubusercontent.com/assets/2925742/6416373/af81eae4-be73-11e4-9ba4-f934caefb5d0.png)

**Comment by b0uch3** [comment]
Here's the .NET markup:

```
        <div class="row">
            <div class="col-lg-3">
                <asp:Label id="lblStartDate" runat="server" Text="Project Start Date" AssociatedControlID="txtStartDate" CssClass="control-label"></asp:Label>
                <div class="input-group">
                    <asp:TextBox ID="txtStartDate" runat="server"  CssClass="form-control" placeholder="yyyy-MM-dd"  ></asp:TextBox>
                    <div class="input-group-addon">
                        <asp:LinkButton ID="btnCalendarStart" runat="server" Text="Button" CssClass="">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </asp:LinkButton>
                    </div>
                </div>
            </div>
            <div class="col-lg-3">
                <asp:Label id="lblEndDate" runat="server" Text="Project End Date" AssociatedControlID="txtEndDate" CssClass="control-label"></asp:Label>
                <asp:TextBox ID="txtEndDate" type="date" runat="server"  CssClass="form-control" placeholder="yyyy-MM-dd"  ></asp:TextBox>
            </div>
        </div>
```

**Comment by pjackson28** [comment]
What you are trying to do will be impossible to achieve with any browser that has native support for input type="date" (e.g., Chrome, Android browser, iOS Safari, Opera, etc) since the browser is in full control of applying and styling that button. The polyfill you are trying to style is only intended to replicate the native support that is available in other browsers and is not intended to provide any additional styling capability, especially since the target audience of the polyfill is already limited, and continuously shrinking.

**Comment by b0uch3** [comment]
Thanks. That's what it looked like to me.  however, your example displays the button right beside the field, albeit without attaching it to the field.  I can't replicate that. I'm not sure why.  I'm hooked in to version 4.0.10.

I've been looking at other components, and the only one that I think I'll have full control over which will allow me to add a trigger button the way I need to for consistency is the .NET ajax calendar extension.

**Comment by pjackson28** [comment]
Why would you need to enforce that consistency across browsers? Wouldn't it be better to rely upon the calendar support that users would be familiar with already? What works well for users on one browser may work very poorly for users on another (particularly when dealing with touchscreens and mobile devices). For instance if an iPhone or iPad user is familiar and comfortable with using the date picker in iOS Safari, why make them have to learn how to use the .NET ajax calendar version which is likely very mouse-centric? That is the benefit of using the HTML5 input type="date" support, the browser takes care of the date picking interface for you (although the polyfill is needed for browsers that currently lack that support).

Note also that if you implement a 3rd party solution for adding a date picker, you would be responsible for ensuring its accessibility and usability (where 3rd party components can often be severely lacking in those areas).

**Comment by hsrudnicki** [comment]
@b0uch3 @pjackson28 : Can this issue be closed?

**Comment by hsrudnicki** [comment]
Due to no further discussion/status updates, this issue has been labeled "Going Stale" and closed.
