### ISSUE TITLE
Links for latest news not working on institution template page (grid system medium)

### ISSUE THREAD

**Issue by Joberrr** [wet-boew/wet-boew#6581]
Concerning institution-en.html line 165.
Links for the 'Latest' news items with photos will not work when the browser window size is medium (col-md-6).  The links will work without issue when the browser window is large (col-lg-4) or when it is small (single column).

Example page (be sure to resize browser to medium layout size):
http://www.canada.ca/en/gov/dept/transport.html

**Comment by pjackson28** [comment]
This looks like issue that is specific to the Canada.ca theme. If so, please close the issue here and refile in wet-boew/GCWeb as it will likely have to be addressed in that repository.
