### ISSUE TITLE
Anyway to see the changes made to the theme files?

### ISSUE THREAD

**Issue by vallieresc** [wet-boew/wet-boew#6582]
I've looked through your changes but it doesn't list any changes to the theme templates. I seem to be getting huge SVG images when upgrading from 10 to 11.

**Comment by pjackson28** [comment]
Which theme is this occurring in? If it is the Canada.ca theme then you should file the issue in wet-boew/GCWeb as they would know what changed. You could also look at the differences between the v4.0.10 and v4.0.11 tags in that repo to see what actually changed.

**Comment by pjackson28** [comment]
I should also mention that you could go to the file in question on the repo and look at it's history to find out all the changes that were made, including the commits where the changes were made (which would have messages).

**Comment by vallieresc** [comment]
I'm using web usability found it on Wet-boew / theme-gcwu-fegc
