### ISSUE TITLE
Form Validation Input Field Stays Red after Error is Cleared & Is Red for No Error

### ISSUE THREAD

**Issue by neoinsight** [wet-boew/wet-boew#6584]
1. In usability testing of form fields, some participants noticed that after they had cleared a validation error, the field outline remains red. It should revert back to black once the validation passes. 

2. If a min or max date is applied to a Datepicker Polyfill input with validation, the field turns red once it gains focus, before the person has even entered a date, and it stays red afterwards, even though no error occurred. It should not go red unless there is an error. 

In the image below, a date past max has been entered, then the person tabbed to the next field. An error message is displayed for the date in the top image. Notice that the Date de retour field is red. It has focus but nothing has been entered. In the second image, the error message is cleared but the field outline is still red. No error message was ever displayed for the Date de Retour field, but it is still red too. 

You can try this out on this page: http://neoinsight.com/test/wetform2/exform3-fr.html

![red error datepicker field](https://cloud.githubusercontent.com/assets/1855584/6431250/d5850598-bff7-11e4-9cad-a93c3860bd9b.png)
![red post-error datepicker field](https://cloud.githubusercontent.com/assets/1855584/6431251/d586c5a4-bff7-11e4-9988-c2d560001c4d.png)

Code for the datepicker fields: 
```
<label for="startdate">Date de départ<span class="datepicker-format"> (<abbr title="Four digits year, dash, two digits month, dash, two digits day">YYYY-MM-DD</abbr>)</span></label>
  <input class="form-control" type="date" id="startdate" name="startdate" max="2016-12-30">
  <label for="enddate">Date de retour<span class="datepicker-format"> (<abbr title="Four digits year, dash, two digits month, dash, two digits day">YYYY-MM-DD</abbr>)</span></label>
  <input class="form-control" type="date" id="enddate" name="enddate" max="2016-12-30">
```

@pcwsmith This was an action from Friday's meeting.

**Comment by pjackson28** [comment]
Will be fixed by PR #6603.
