### ISSUE TITLE
Date picker icon not displaying

### ISSUE THREAD

**Issue by E1D1** [wet-boew/wet-boew#6587]
Hi,

When generating the date picker using the Jquery's command .append(), The calendars glyphicon is not showing up. 

```
 $("#container").append('<li id="day1" class="days"><details open="open"><summary>Date </summary><div class="form-group"><label class="col-md-3 control-label" for="datecontainer">Date</label><input type="date" id="datecontainer" name="datecontainer" class="form-control" /></div></details></li>');
```

Thankx for your help

**Comment by CalvinRodo** [comment]
Are you manually triggering the wb-init.wb-date event as per the documentation? 

http://wet-boew.github.io/v4.0-ci/docs/ref/datepicker/datepicker-en.html

**Comment by CalvinRodo** [comment]
@e1d1 can this be closed? Did manually triggering the plugin fix this?

**Comment by E1D1** [comment]
yes this can be close. It was a coding issue
