### ISSUE TITLE
How are views of YouTube Multimedia Player tracked in YT Analytics?

### ISSUE THREAD

**Issue by MattMoore-GOC** [wet-boew/wet-boew#6594]
Looking at the code, it does not appear that the YouTube Multimedia Player uses YT's embed code to display the video. My question is how a view of the video in the WET player is recording by YouTube's analytics. Will they be counted as it they were played on the video page itself? As an embed? Are they tracked at all by YT?

**Comment by pjackson28** [comment]
It doesn't use YouTube's embed code but it does use YouTube's chromeless player API. So it should update YouTube's analytics like an embed does. If it doesn't then that would be an issue with YouTube's chromeless player API.

**Comment by LaurentGoderre** [comment]
If it doesn't, it's fairly easy to track those on your own.

**Comment by lucas-hay** [comment]
@MattMoore-GOC are you currently using Google analytics on your site?

**Comment by LaurentGoderre** [comment]
@MattMoore-GOC does it answer your question?

**Comment by hsrudnicki** [comment]
Can be this issue closed?

**Comment by pjackson28** [comment]
Closing as the question was answered.
