### ISSUE TITLE
Multimedia player: youtube demo not working

### ISSUE THREAD

**Issue by bsouster** [wet-boew/wet-boew#6596]
We noticed the Youtube Mutlimedia player demo isn't loading up:
http://wet-boew.github.io/wet-boew/demos/multimedia/multimedia-youtube-en.html

I tried the same demo from the WET package on our server and it's working perfectly (v4.0.9).
Maybe connected to the caption issue recently discovered?

**Comment by LaurentGoderre** [comment]
We really need unit test for this plugin!!!Thanks for letting us know
