### ISSUE TITLE
AJAX Ligtbox close button Problem

### ISSUE THREAD

**Issue by causerdan** [wet-boew/wet-boew#6600]
I found a small bug in the modal lightbox.  I could only find this in the one instance of this plugin but the close button ends up moving the right side of the screen.  You can actually see it on the demo page:  http://wet-boew.github.io/v4.0-ci/demos/lightbox/lightbox-en.html

I was looking at the Ajax Example 1.

![modallightboxerror](https://cloud.githubusercontent.com/assets/8202566/6528156/1ca04a92-c3ee-11e4-9ed9-1bdec36c3220.png)

Any thoughts on the fix?

**Comment by pjackson28** [comment]
Thanks for catching that. Will be fixed by PR #6602.
