### ISSUE TITLE
Mega Menu not displaying in IE8 (WET 4.0)

### ISSUE THREAD

**Issue by McEmily** [wet-boew/wet-boew#6601]
Among other issues with IE8 (including svg objects displaying as xml-style code) the biggest issue our intranet application is having is the mega menu is not displaying at all in IE8, thus eliminating any form of navigation through our application. Granted, I am running IE11 with IE8 compatibility mode, which only mimics the IE8 browser, but this is a concern to my team because the widespread update from IE8 to IE11 keeps getting pushed back and there's no guarantee all our internal users will have IE11 by our release date. We're currently using 4.0.10. Any suggestions on how we can work around this issue? Thanks

**Comment by pjackson28** [comment]
You can't rely on any testing with IE11 running in IE8 compatibility mode as emulation in IE11 is badly broken. We have repeatedly seen in the past issues being raised with IE8 compatibility mode that don't occur in a true IE8 browser.

As for why the SVG objects are not rendering correctly, it could be your server is not configured correctly to support SVG. Another thing you should look into is what mode an IE8 browser is running in. It is not uncommon for IE8 to default to compatibility mode for intranets which is effectively IE7. So it is important to always run in edge mode. For help on how to ensure your server is configured correctly, see: http://wet-boew.github.io/v4.0-ci/unmin/docs/server-en.html
For

**Comment by LaurentGoderre** [comment]
@McEmily you should get these IE VM to test in a true IE environment

https://www.modern.ie/en-us

**Comment by stephenbe** [comment]
@LaurentGoderre More to @pjackson28 point, I tried those VM systems, and even those have quirks compared to IE8 on windows XP. So, I would suggest @McEmily to also test on a windows XP virtual environment as well to make sure it works.

**Comment by LaurentGoderre** [comment]
Isn't the IE8 in XP already ?

**Comment by stephenbe** [comment]
@LaurentGoderre yes it is, I just wanted to point out that the VMs from https://www.modern.ie/en-us are with windows 7 and IE8 on windows 7 can be different then IE8 on xp. I usually test IE8 on XP and IE8 on windows 7 to make sure it my website works. I also agree with your point that testing with IE11 running in IE8 compatibility mode is broken.

**Comment by McEmily** [comment]
I only need IE8 with Windows 7, since this is an internal application. I'll try the VMs. Thank you!

**Comment by LaurentGoderre** [comment]
@McEmily I can definitly help you with this as I do this almost everyday. Maybe you can come to codesprint.

**Comment by hsrudnicki** [comment]
Can this issue be closed?

**Comment by hsrudnicki** [comment]
Made "Going Stale" and closed this issue as resolved; if you think otherwise, please update/respond to this issue's status as soon as possible to keep this issue still opened, thank you
