### ISSUE TITLE
Question regarding text case for label element

### ISSUE THREAD

**Issue by biljanap** [wet-boew/wet-boew#6604]
I am moving an existing application to WET4. I noticed that text case has not been used consistently for <label> elements. Sometimes sentence case is used and sometimes each word is capitalized.
I would like to advise the client to go one way or another. I checked Form validation example (<a href="http://wet-boew.github.io/v4.0-ci/unmin/demos/formvalid/formvalid-en.html">http://wet-boew.github.io/v4.0-ci/unmin/demos/formvalid/formvalid-en.html</a>) for some guidance but even in the example there is no consistency. Would anybody know if one way is better than the other?
Thanks

**Comment by NPhilouze** [comment]
It's generally accepted to follow the Microsoft UI guide lines which would be sentence-style capitalization: https://msdn.microsoft.com/en-us/library/dn742478.aspx 

Source: http://ux.stackexchange.com/questions/28172/what-are-some-reference-works-for-capitalization-in-ui-text

**Comment by biljanap** [comment]
@NPhilouze Thanks. That's what I go with for new applications.

**Comment by LaurentGoderre** [comment]
@pcwsmith, @DK-TBS what are your thoughts on this?

**Comment by pcwsmith** [comment]
Overall we are following a sentence-case style for labels and headings in Canada.ca screens. But I'm sure we haven't been 100% consistent in our documentation either.

**Comment by pjackson28** [comment]
Note PR #6608 switches the labels for form validation, date picker and feedback form to sentence case. We welcome any PRs for switching over any other text to sentence case that we missed or even help identifying what we missed.

**Comment by hsrudnicki** [comment]
Can this issue be closed?
