### ISSUE TITLE
H1 property="name"

### ISSUE THREAD

**Issue by DHaslip** [wet-boew/wet-boew#6609]
Would someone be able to explain what the <code>property="name"</code> attribute is used for on the <code>&lt;h1&gt;</code>  element?  It doesn’t look like it’s required as “Skip to Main Content”  works correctly without it in both Firefox and IE11.  And normally undefined attributes would be prefixed with <code>data-</code>, so I'm not sure where <code>name</code> is used.

**Comment by pjackson28** [comment]
It is HTML Data, in particular RDFa 1.1 Lite + Schema.org. As stated in the Standard on Web Interoperability:
"HTML data is an approach for embedding and extracting machine-readable content in Web pages. HTML data is used in a variety of ways, assisting with the retrieval, extracting and re-use of content in Web pages by Web browsers, search engines, and data re-users." (http://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=25875#appE)

**Comment by DHaslip** [comment]
Thanks.  A follow-up question:  Does the “skip to main content” link require the  <code>&lt;h1&gt;</code>   element of the page to have the property=”name” attribute?  Or is the  id=”wb-cont” attribute sufficient?

**Comment by pjackson28** [comment]
The two are unrelated. The property="name" attribute is used to programmatically identify the webpage name when building the data structure for the page. It is effectively the same as metadata, where its absence would mean the parser would have to make assumptions as to what is the name of the resulting data structure. So both are needed, with <code>id="wb-cont"</code> being needed for the skip link and <code>property="name"</code> being needed for the data structure.

**Comment by pjackson28** [comment]
Note also that html5 permits more than one h1 on the page (in fact all headings could technically be made into h1 if sectioning elements are used correctly). So you can no longer safely assume what is the name of the page (can't even rely upon the title element since often sites cram more than the page name in there). So that is why we need to be clear and unambiguous regarding what is the actual page name (hence the use of <code>property="name"</code>).

**Comment by hsrudnicki** [comment]
Can this issue be closed?

**Comment by pjackson28** [comment]
Yes as the question was answered.
