### ISSUE TITLE
Tables: Issues with Pager when using Server Side Processing

### ISSUE THREAD

**Issue by junioro12** [wet-boew/wet-boew#6610]
We're trying to use the Tables control (http://wet-boew.github.io/wet-boew/demos/tables/tables-en.html) to display a large dataset...so we needed to enable server side processing.  It works actually quite well, however the pager at the bottom of the table seems incorrect.  If you select the next/previous links, its cycles through 33,000+ records just fine, calling for them a page at a time from the server:
![image](https://cloud.githubusercontent.com/assets/4061577/6560987/442925fc-c664-11e4-8e42-f009b7fbac7d.png)

You can see however, that the pager shows the final page as 6 in this case, when it should be page 3,334 as shown by the example below which shows the identical dataset/JSON call to a server side application/page but just loads the table data into a table from the DataTables example pages/documentation:
![image](https://cloud.githubusercontent.com/assets/4061577/6561019/7c398982-c664-11e4-8623-45bad24a7433.png)

I'm not sure if we've done anything incorrectly, but since we've done nothing to the control and have simply set this to use server side processing, is it possible the the WET "adaptation" to this control has somehow caused a bug with the display of pagination links?

**Comment by pjackson28** [comment]
@junioro12 Thanks for catching that! It turns out an incrementer was being used instead of the old HTML when enhancing the pagination text for accessibility purposes. So the problem manifested itself when going beyond 5 pages (at which point the incrementer approach falls apart). Will be fixed by PR #6612.

**Comment by junioro12** [comment]
Great...that was quick...I look forward to this release to get this fixed, should be before we launch our project, so that's excellent, thanks a lot!
