### ISSUE TITLE
 Left nav wb-navcur not working properly 

### ISSUE THREAD

**Issue by Fu22yWu22y** [wet-boew/wet-boew#6611]
I'm having issues with the left-nav and the css tag wb-navcur no generating properly.
it works fine an a fair amount of links but there some links that it doesn't work .

so far the only consistence i saw between a page links working properly vs not working properly is  if the "href" contains a  _   the  wb-navcur  doesn't get attributed  

works
 href="/pro/Questionnaire/ProgramSelection/ProgramSelection"
doesn't work
 href=""/pro/Questionnaire/Application/Form/project_ident"

**Comment by pjackson28** [comment]
I can't reproduce the issue. I tried putting "/pro/Questionnaire/Application/Form/project_ident" as the href for one of the breadcrumb links and the href for one of the side menu links and the wb-navcurr class was correctly applied. It worked in the menu bar as well (to see if it worked in a different menu). Is there any mismatch between the breadcrumb link href and the side menu link href? If you are trying to match to the actual page URL, is there any mismatch between the side menu link href and the page URL?

I also noticed that in your second href you have two double quotes at the start (not sure if that is just a typo or what you actually used).

**Comment by Fu22yWu22y** [comment]
This happening in the side bar  
i thought i was related to the _ but it might not be  
i found on other page without the _ and it doesn't work  
it's odd because when  i click Program Selection link  the "wb-navcurr" get attributed properly  but when i click anything beyond that the  "wb-navcurr"  doesn't get attributed 

<nav role="navigation" id="wb-sec" typeof="SiteNavigationElement" class="wb-sec col-md-3 col-md-pull-9 wb-navcurr-inited">
                    <h2>Side navigation (left column)</h2>  
<ul class="list-group menu list-unstyled">
    <li>
        <h3  class="list-group-item-heading"> <a href="/pro/Questionnaire/Application/FormList/1">Applications and Projects</a></h3>
     </li>
</ul>
<ul class="list-group menu list-unstyled">
    <li>
        <h3 class="list-group-item-heading">Application</h3>
        <ul class="list-group menu list-unstyled">
            <li><a class="list-group-item" href="/pro/Questionnaire/ProgramSelection/ProgramSelection">Program Selection</a></li>
            <li><a class="list-group-item" href="/pro/Questionnaire/Application/Form/project_ident">Project Identification</a></li>
            <li><a class="list-group-item" href="/pro/Questionnaire/Application/Form/mailing_address">Mailing Address</a></li>
        </ul>
    </li>
</ul>
                </nav>


url: http://localhost:5905/pro/Questionnaire/Application/Section/project_ident
![project_indent](https://cloud.githubusercontent.com/assets/11393905/6578166/dff0f686-c718-11e4-8d78-6ba69f3f003b.png)
url: http://localhost:5905/pro/Questionnaire/ProgramSelection/ProgramSelection
![programselection](https://cloud.githubusercontent.com/assets/11393905/6578179/f3cdbfcc-c718-11e4-8f1f-d7ed6003eac1.png)

**Comment by Fu22yWu22y** [comment]
i was blind the href and the url did not match   
thanks for the help !
