### ISSUE TITLE
Video Not Playing in IE

### ISSUE THREAD

**Issue by ikug** [wet-boew/wet-boew#6615]
I am using CMS to render a page for video by WET 4.0.9.
For some reason from CMS, we have to put IE as browser IE 9 and doc IE8.
Now I found the video can't be played, but all of other browsers have no problem with it.
The issue is when I click "Play" button, then the console said: Object doesn't support property or method 'doPause', ie8-wet-boew2.min.js
![image](https://cloud.githubusercontent.com/assets/10654702/6583601/84ebee26-c73b-11e4-844a-c15dace54c58.png)
, line 9 character 7073.

**Comment by LaurentGoderre** [comment]
@ikug the video can't play in Compatibility Mode because Compatibility mode is really broken.

Please see the section on Compatibility Mode to fix your issue

http://wet-boew.github.io/wet-boew/docs/server-en.html
