### ISSUE TITLE
Remove Flash AllowScriptAccess Override

### ISSUE THREAD

**Issue by sdkibb** [wet-boew/wet-boew#6616]
In the multimedia.js file, do we need to have the "allowScriptAccess" value to be "always" or can we remove this or set it to the default value which is sameDomain? The reason I ask is that this causes medium issues on the vulnerability scanner. Not the end of the world but I have to address it on each scan so if it's not completely necessary it'd be great if we remove it as a default and allow others to add it in when required.

 Thanks,
 Sean

**Comment by LaurentGoderre** [comment]
This setting only really applies to IE8, which is bound to have a lot of other security issues anyways. Besides, I don't think we can remove it because some department do use subdomains to access WET files and changing this  setting will break the player for them.

**Comment by sdkibb** [comment]
AppScan doesn't really factor in browser type but I kind of came to the same conclusion that changing it at this point could really hurt some when upgrading. At the same time though, anyone who does a vulnerability assessment will get this flagged as a medium risk. At that point they either have to remove/modify the line and re-scan or justify the risk.
