### ISSUE TITLE
Web Experience Toolkit Date Picker in french

### ISSUE THREAD

**Issue by E1D1** [wet-boew/wet-boew#6617]
Is there a way to display the date picker in french in an dynamically generated content page ?

**Comment by LaurentGoderre** [comment]
In which browser is it not displaying in french?

**Comment by sgdowney** [comment]
If the lang attribute is set correctly on the '''<html> tag then the date picker should have the correct language.

**Comment by E1D1** [comment]
Thank You SGDowney

changing the language did the trick but if I am using Resources in ASP.net to toggle between French and English content. Is there another way to force the calendar to display in french

**Comment by sgdowney** [comment]
I use a resource to set the lang in the masterpage
```
<html class="no-js" lang="<%: MasterPageResources.HtmlTagLanguageIndicator %>" dir="ltr">
```

**Comment by sgdowney** [comment]
MVC implementation
```
<html class="no-js" lang="@MasterPageResources.HtmlTagLanguageIndicator" dir="ltr">
```

**Comment by RobJohnston** [comment]
Lots of approaches.  You could use a different master page for each language or one master page with a line like:
```html
<html class="no-js" lang="<%=TwoLetterLangName %>" dir="ltr">
```
and a property in the code-behind of the master page like:
```vb
    Public ReadOnly Property TwoLetterLangName As String
        Get
            Return Thread.CurrentThread.CurrentUICulture.TwoLetterISOLanguageName
            'Return CultureInfo.CurrentCulture.TwoLetterISOLanguageName
        End Get
    End Property
```
For this, I inherit every page from a class I call BasePage instead of System.Web.UI.Page and override the culture based on the file name (i.e., does it end in -fra.aspx?).
```vb
    Protected Overrides Sub InitializeCulture()
        Dim userCulture As String
        Dim pattern As String = "^\S+-(\S+).aspx\S*$"
        Dim m As Match

        m = Regex.Match(Request.RawUrl, pattern, RegexOptions.IgnoreCase)

        'Given an arbitrary page such as "/SomeDir/SomePage-fra.aspx?id=123",
        'the above pattern should find 1 group: "fra".

        If m.Success Then
            Select Case m.Groups.Item(1).Value
                Case "fra"
                    userCulture = "fr-ca"
                Case Else
                    userCulture = "en-ca"
            End Select

            Thread.CurrentThread.CurrentUICulture = New CultureInfo(userCulture)
            Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(userCulture)
        End If
    End Sub
```

**Comment by LaurentGoderre** [comment]
@RobJohnston it's not imperative but you should switch to using two letter code for your pages because the two letter code is the standard for the internet as defined by the IETF. This way, you wouldn't need the `Select Case` and you could use the language code directly.

**Comment by RobJohnston** [comment]
Good to know.  Again, easily done within the web.config
```
    <urlMappings>
      <add url="~/MyPage-eng.aspx" mappedUrl="~/MyPage.aspx" />
      <add url="~/MyPage-fra.aspx" mappedUrl="~/MyPage.aspx" />
    </urlMappings>
```

Can't wait until the .Net variant (https://github.com/wet-boew/wet-boew-dotnet) gets some more traction... I think that I've created master pages for at least 5 departments since .NET 2.0 came out.

**Comment by LaurentGoderre** [comment]
Are you leading that one?

**Comment by RobJohnston** [comment]
I've thought about it.  I keep doing it a bit differently every year and would love comments like the one you made.  But I think the best time to start is with ASP 5, which is due out soon.

**Comment by LaurentGoderre** [comment]
Are you in the GC? If so, which department?

**Comment by RobJohnston** [comment]
Contractor, cuttently at CIC.  Previously PCO, DND, TBS, INAC...

**Comment by E1D1** [comment]
@

lang="<%: MasterPageResources.HtmlTagLanguageIndicator %>

worked like a charm

Thank you

**Comment by derekvasilich** [comment]
I tried setting the lang attribute of the HTML tag to the 2 character code `fr` but I am still getting an english datepicker. In fact, the French example page does not even display a French datepicker: https://wet-boew.github.io/wet-boew/demos/datepicker/datepicker-fr.html
<img width="249" alt="image" src="https://github.com/wet-boew/wet-boew/assets/1587685/c31fde53-8572-42fe-9963-e4825234e56b">

**Comment by derekvasilich** [comment]
The issue that we are facing is that we have build an app using WET-BOEW in React. It has a language toggle in the top right hand corner similar to the one on all GoC websites. We are expecting that when the language is toggled from English to French that all content / controls / labels / etc displayed on the page are rendered using the appropriate language. We are not really using the date picker as a polyfill but rather as a React component. Not sure how it works underneath though.
