### ISSUE TITLE
What versions of Internet Explorer are supported?

### ISSUE THREAD

**Issue by josephbr** [wet-boew/wet-boew#6618]
I am wondering, which versions of Internet Explorer are supported by the current version of the Web Experience Toolkit? I looked through the documentation and I could not find a web browser compatibility list. Please let me know if I have overlooked something.

**Comment by RobJohnston** [comment]
I don't think that it's in the docs.  Look here #6341.

**Comment by josephbr** [comment]
Thank you. That answers my question.
