### ISSUE TITLE
Multimedia Player - YouTube: Play button overlay

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/wet-boew#6620]
The play button over the video is not the same size as the [WET media player](http://wet-boew.github.io/v4.0-ci/unmin/demos/multimedia/multimedia-en.html) one.

![capture](https://cloud.githubusercontent.com/assets/2575266/6643894/54043b36-c986-11e4-9f0c-486f512a598f.JPG)

![capture2](https://cloud.githubusercontent.com/assets/2575266/6643897/559fbdb2-c986-11e4-92de-bf56c2e1d8da.JPG)

**Comment by LaurentGoderre** [comment]
One is controlled by YouTube, the other is ours.

**Comment by hsrudnicki** [comment]
@shawnthompson @LaurentGoderre : Can this issue be closed?

**Comment by shawnthompson** [comment]
Sure why not.
