### ISSUE TITLE
Images in thumbnail of slideshow

### ISSUE THREAD

**Issue by ikug** [wet-boew/wet-boew#6627]
We are using WET 4.0.9.
For some reason the images in thumbnail of slideswhow have been gone, only left is the Pause button. This button is even not working now because of no images in the thumbnail bar.

Do you know what could cause no images displaying in the thumbnail bar? It seems there is nothing showing of <span class="curr-index">...

Any help will be appreciated.

**Comment by LaurentGoderre** [comment]
Are you experiencing this in IE9 on your internal network?

**Comment by ikug** [comment]
Yes, internal network will cause this issue? But it showed all the images in thumbnail in IE9 before. Also the another page on internal network is working fine always. And the code is the same as well.

**Comment by LaurentGoderre** [comment]
Please test on another browser or with an IE9 outside of your network. There is a setting in use in a lot of internal IE9 that prevent the icons from loading

**Comment by LaurentGoderre** [comment]
Ohh the thumbnail.....nevermind then. Do you have an example I can look at

**Comment by ikug** [comment]
This same issue happens on all the browsers, not just IE.

**Comment by ikug** [comment]
Here is the image I have the problem, and there are 3 images should be showing in the thumbnail, but just one now.

![image](https://cloud.githubusercontent.com/assets/10654702/6718977/035676c0-cd8e-11e4-981d-b13624895689.png)

**Comment by ikug** [comment]
I think the problem is here -- highlight in the image:

![image](https://cloud.githubusercontent.com/assets/10654702/6719017/40f523e6-cd8e-11e4-91a3-acb9bb45754b.png)

**Comment by LaurentGoderre** [comment]
I looks like a markup issue. Can you post the code you used?

**Comment by ikug** [comment]
Here is the part of image slideshow:

[code]<section class="col-md-9     ">
<div class="wb-tabs carousel-s2 show-thumbs playing ">
<ul role="tablist"></ul>
<div class="tabpanels">
<div id="panel-1426686999554-1" role="tabpanel" class="in fade">
<figure>
<img src="/iw/cci/meta/no-injection/iw-mount/default/main/Internet/MAT_Internet/WORKAREA/work/assets/MAT_Internet/images/tree.jpg" alt=" tree"/>
<div class="pstn-tp-md pstn-rght-md pstn-tp-xs pstn-rght-xs">
<div class="col-md-12">
<p class="small opct-80 well well-sm brdr-rds-0">treetree</p>
</div>
</div>
</figure>
</div>
<div id="panel-1426686999554-2" role="tabpanel" class="out fade">
<figure>
<img src="/iw/cci/meta/no-injection/iw-mount/default/main/Internet/MAT_Internet/WORKAREA/work/assets/MAT_Internet/images/artwork.jpg" alt=" artwork"/>
<div class="pstn-tp-md pstn-rght-md pstn-tp-xs pstn-rght-xs">
<div class="col-md-12">
<p class="small opct-80 well well-sm brdr-rds-0">artworkartwork</p>
</div>
</div>
</figure>
</div>
<div id="panel-1426686999554-3" role="tabpanel" class="out fade">
<figure>
<img src="/iw/cci/meta/no-injection/iw-mount/default/main/Internet/MAT_Internet/WORKAREA/work/assets/MAT_Internet/images/temple.jpg" alt=" temple"/>
<div class="pstn-tp-md pstn-rght-md pstn-tp-xs pstn-rght-xs">
<div class="col-md-12">
<p class="small opct-80 well well-sm brdr-rds-0">templetemple</p>
</div>
</div>
</figure>
</div>
</div>
</div>
</section>
[/code]

**Comment by ikug** [comment]
Please let me know if you can see the code:

<code><section class="col-md-9     ">
<div class="wb-tabs carousel-s2 show-thumbs playing ">
<ul role="tablist"></ul>
<div class="tabpanels">
<div id="panel-1426686999554-1" role="tabpanel" class="in fade">
<figure>
<img src="/iw/cci/meta/no-injection/iw-mount/default/main/Internet/MAT_Internet/WORKAREA/work/assets/MAT_Internet/images/tree.jpg" alt=" tree"/>
<div class="pstn-tp-md pstn-rght-md pstn-tp-xs pstn-rght-xs">
<div class="col-md-12">
<p class="small opct-80 well well-sm brdr-rds-0">treetree</p>
</div>
</div>
</figure>
</div>
<div id="panel-1426686999554-2" role="tabpanel" class="out fade">
<figure>
<img src="/iw/cci/meta/no-injection/iw-mount/default/main/Internet/MAT_Internet/WORKAREA/work/assets/MAT_Internet/images/artwork.jpg" alt=" artwork"/>
<div class="pstn-tp-md pstn-rght-md pstn-tp-xs pstn-rght-xs">
<div class="col-md-12">
<p class="small opct-80 well well-sm brdr-rds-0">artworkartwork</p>
</div>
</div>
</figure>
</div>
<div id="panel-1426686999554-3" role="tabpanel" class="out fade">
<figure>
<img src="/iw/cci/meta/no-injection/iw-mount/default/main/Internet/MAT_Internet/WORKAREA/work/assets/MAT_Internet/images/temple.jpg" alt=" temple"/>
<div class="pstn-tp-md pstn-rght-md pstn-tp-xs pstn-rght-xs">
<div class="col-md-12">
<p class="small opct-80 well well-sm brdr-rds-0">templetemple</p>
</div>
</div>
</figure>
</div>
</div>
</div>
</section>
</code>

**Comment by ikug** [comment]
This is better:

![image](https://cloud.githubusercontent.com/assets/10654702/6719269/c9719a46-cd8f-11e4-8ed5-630f4b9da9cf.png)

**Comment by biljanap** [comment]
@ikug I believe you are missing list items (`<li>`) inside `<ul role="tablist">`
This is the code that's missing:
```html
<li class="active"> <a href="#panel-1426686999554-1" title="Tab 1: Some Title text"><img src="/iw/cci/meta/no-injection/iw-mount/default/main/Internet/MAT_Internet/WORKAREA/work/assets/MAT_Internet/images/tree.jpg" alt="" /></a> </li>
<li> <a href="#panel-1426686999554-2" title="Tab 2: Some Title text"><img src="/iw/cci/meta/no-injection/iw-mount/default/main/Internet/MAT_Internet/WORKAREA/work/assets/MAT_Internet/images/artwork.jpg" alt="" /></a> </li>
<li> <a href="#panel-1426686999554-3" title="Tab 3: Some Title text"><img src="/iw/cci/meta/no-injection/iw-mount/default/main/Internet/MAT_Internet/WORKAREA/work/assets/MAT_Internet/images/temple.jpg" alt="" /></a> </li>
```

**Comment by ikug** [comment]
Thank you, Yes, I was missing the inside code of UL from source code as you can see.
But I found it is I am actually missing caption function from my code, and it is why it can't render/capture any input of caption then display into figcaption tag. Because of this reason, there is no li tag is inside of ul tag.

Thanks again for looking into it.
