### ISSUE TITLE
Div list-group functionality missing in GoC web usability theme?

### ISSUE THREAD

**Issue by kavinay** [wet-boew/wet-boew#6633]
Hi guys,

I'm using the following coloured list group code from the working example page (http://wet-boew.github.io/wet-boew-styleguide/v4/design/listgroup-en.html ) on a GoC web usability theme page:

```html
<ul class="list-group">
	<li class="list-group-item list-group-item-success">Dapibus ac facilisis in</li>
	<li class="list-group-item list-group-item-info">Cras sit amet nibh libero</li>
	<li class="list-group-item list-group-item-warning">Porta ac consectetur ac</li>
	<li class="list-group-item list-group-item-danger">Vestibulum at eros</li>
</ul>

<div class="list-group">
	<a href="#" class="list-group-item list-group-item-success">Dapibus ac facilisis in</a>
	<a href="#" class="list-group-item list-group-item-info">Cras sit amet nibh libero</a>
	<a href="#" class="list-group-item list-group-item-warning">Porta ac consectetur ac</a>
	<a href="#" class="list-group-item list-group-item-danger">Vestibulum at eros</a>
</div>
```

This results in:

![list-group-colour-error](https://cloud.githubusercontent.com/assets/290346/6784803/1874621a-d13f-11e4-9006-b5dace8d739a.PNG)

Unfortunately, the second list-group does not display the list items in colour. Is it possible that a selector for the div > .list-group style chain is buggy in the GoC web usability version?

Thanks,

Kavin

**Comment by LaurentGoderre** [comment]
Are you using this in the content area or in a navigation area?

**Comment by kavinay** [comment]
I think it's being being used in the navigation area. Does the behaviour drop in the nav?

**Comment by LaurentGoderre** [comment]
I don't think these colors are part of the spec so they may not be supported. I am curious, why are you using colors in the navigation?

**Comment by kavinay** [comment]
Ah, okay, that would make sense. Maybe I'm looking at the wrong spot for guidance. Is the spec available so I can figure out where the design guides don't indicate a potential use is unsupported on purpose?

**Comment by LaurentGoderre** [comment]
You are not in the wrong spot. Here is the section of the spec.

http://tbs-sct.gc.ca/ws-nw/mo-om/ts-st/p7-eng.asp#Section11_1_5

**Comment by hsrudnicki** [comment]
Can this issue be closed?

**Comment by LaurentGoderre** [comment]
I believe so since the question was answered
