### ISSUE TITLE
Share widget: way to suppress disclaimer?

### ISSUE THREAD

**Issue by robwloch** [wet-boew/wet-boew#6635]
Is there a way to suppress the following disclaimer or can this be added in a future WET4 sub-release?

"No endorsement of any products or services is express or implied."

The scenario is that for internal Govt use the only sharing option we'd want to show is Email since we don't have access to sites like Facebook, Twitter, etc... and therefore the disclaimer doesn't really apply for general Email.

Thank you!

**Comment by pjackson28** [comment]
You could hide the disclaimer with the following CSS:

```css
.shr-dscl {
	display: none;
}
```

**Comment by robwloch** [comment]
Thank you @pjackson28 . I passed on your advice but the development team had a good point that this would not hide it from screen readers. Could an attribute or switch maybe be added to this widget in the future to not even write out the disclaimer instead of just hiding it with CSS?

**Comment by pjackson28** [comment]
Actually display: none does hide it from most screen readers nd is regularly used by WET and other solutions to hide content from all (including screen readers).

**Comment by robwloch** [comment]
You're right @pjackson28 , it worked perfectly. Thanks again!
