### ISSUE TITLE
How poster attribute is working with IE Quirks mode

### ISSUE THREAD

**Issue by ikug** [wet-boew/wet-boew#6636]
I am using WET 4.0.9.

Based on our current architecture, I have to work within IE quirks mode for editing content, then go to preview mode for content preview which it will be in fully IE 9.

The problem is poster attribute for video is not working in IE quirks mode. The poster is to have a image as placeholder of video, but I just can't see it in quirks mode.

It seems working in WET 3 version with our condition, but since I moved on WET 4, then the image couldn't be seen.

Is there any huge difference between WET 3 and WET 4 for poster attribute?(It is almost nothing, after comparing) If not, then why it didn't work in IE only, not the other browsers? The source code looks the same between different browsers.

**Comment by LaurentGoderre** [comment]
@ikug Compatibility View (or quirks mode) has a lot of problems especially when it comes to HTML5 videos and Flash and should not be used to emulate older versions of IE. If you need to test IE you should use virtual machines with native versions of the browser.

https://www.modern.ie/en-us/virtualization-tools#downloads

**Comment by ikug** [comment]
Thank you for your quick reply. I understand the IE has problem with quirks mode specially going with Html 5. But same browser with quirks mode, one with WET 3 is working, but with WET 4 not.
So, I am wondering if there is huge difference between WET 3 and WET 4.

Thanks you for your link, but unfortunately I am not able to go further. It is blocked by our network... Lol.

**Comment by LaurentGoderre** [comment]
There is a significant difference between 3 and 4 yes.

**Comment by LaurentGoderre** [comment]
Note that this wouldn't affect users with a regular IE9

**Comment by ikug** [comment]
Thanks, actually I am not asking for the difference about IE, and my question is asking the difference between classes in WET 3 and classes in WET 4 for video player.
For an instance, it uses class(wet-boew-multimedia) for video player in WET 3, instead of using  class(wb-mltmd) in WET 4. Then will it be the reason why image placeholder not showing in Quirks mode in IE 9?

**Comment by LaurentGoderre** [comment]
The multimedia player in WET4 is a completely rewrite to re-use HTML5 and have significant differences.

**Comment by ikug** [comment]
Thank you.
This is what I thought. Then do you think any possible to have image placeholder showing in IE 9 quirks mode? or is there any affection for new class of multimedia player in WET 4?

**Comment by LaurentGoderre** [comment]
I doubt we can fix this because it is a bug with IE and the new multimedia player is a polyfill

**Comment by ikug** [comment]
Thanks again. Are you saying your WET group will be going to fix this issue in IE?

**Comment by LaurentGoderre** [comment]
Unfortunately no. we are not going to fix this issue. WET4 does not support Quirks mode.

**Comment by LaurentGoderre** [comment]
Is the poster image on the same domain as the player and the video?

**Comment by ikug** [comment]
Yes. We have 2 steps for our video player implementation.
First is in IE 9 Quirks mode, which is the issue I am facing now -- image not showing, only displaying the image not video.That means the video won't be able to play.
Second is in fully IE 9, it should show image as placeholder first, then be able to play video. I don't have any issue with it, except for our network security policy.

**Comment by LaurentGoderre** [comment]
Yeah, unfortunately we  can't fix that.

**Comment by ikug** [comment]
Thank you for your cents. Not a problem. 
But I try to fix it. I just replace video element with an image element as placeholder. So then the user will be able to see the image in step 1.
