### ISSUE TITLE
Geomap: draw bounding box

### ISSUE THREAD

**Issue by muling** [wet-boew/wet-boew#6637]
Is there a way to allow the user to select an area of the map (using a mouse or touch screen) and then pass that lat/lon data through a form?  I see that you have something similar where you can draw on the map, but with predefined areas to select from.  Is there a way for me to define the shapes?

**Comment by jvanulde** [comment]
Yes. If you enable the AOI widget then users can draw a box and the coordinate string is provided in a hidden field that you can access in your application. Please see the documentation for the aoi class in the docs. If you need assistance please let me know.

**Comment by muling** [comment]
I am finding that the map loads fairly slowly on my browsers (and often get a prompt asking whether to stop the script or wait).  How well does this plugin perform on a live site with a lot of traffic?

**Comment by jvanulde** [comment]
@muling can you be more specific? The plugin is client-based so performance is only limited by the client. Of course, performance could be impacted by the data source that you are trying to load into the map. Can you provide me with the datasource that you are trying to load?

**Comment by muling** [comment]
I'm just trying to load the wet geomap example page.  http://wet-boew.github.io/wet-boew/demos/geomap/geomap-en.html

**Comment by jvanulde** [comment]
What browser/version are you using?

**Comment by muling** [comment]
I am using the latest version of Firefox.  Last week, it may have happened on IE or Chrome too.  When I cleared my cache, it seems to be responding much better.

**Comment by jvanulde** [comment]
I am not having that issue with Firefox v36.0.4 on Mac or Windows. If the issue persists please create an issue and we can take another look.

**Comment by LaurentGoderre** [comment]
@muling Have you tried removing your site custom scripts when testing this to make sure it's not caused by other scripts?

**Comment by muling** [comment]
I am viewing a page made by WET.

**Comment by LaurentGoderre** [comment]
Really....which page is that?

**Comment by muling** [comment]
See my note above.

**Comment by LaurentGoderre** [comment]
Can you list your steps so I can try to reproduce

**Comment by muling** [comment]
Since I cleared my cache this morning, I wasn't able to duplicate the problem.

**Comment by LaurentGoderre** [comment]
Very strange. @jvanulde do you use local storage for the plugin?

**Comment by jvanulde** [comment]
No, Geomap doesn't leverage local storage.

**Comment by muling** [comment]
The problem seems to be happening again this morning.  I left the page open overnight.  Could it be caused by a Firefox memory leak?

![Uploading geomap-jserror.jpg . . .]()

**Comment by jvanulde** [comment]
I can confirm that this occurs for me as well in the latest version of Firefox.

**Comment by LaurentGoderre** [comment]
@jvanulde can you test with the unminified file to see which line is causing the issue?

**Comment by jvanulde** [comment]
I am only getting this with Firebug enabled. @muling do you have Firebug enabled as well?

**Comment by muling** [comment]
I will disable it and let you know after a few hours.

**Comment by LaurentGoderre** [comment]
@jvanulde @muling I recommend that you switch to Firefox Developer edition. The native development tools in that version are better than the Firebug ones I find and reduce the weird issues like those.

**Comment by jvanulde** [comment]
I can't replicate the issue using Firefox Developer Edition.

**Comment by muling** [comment]
With Firebug disabled, I don't see the issue.

**Comment by LaurentGoderre** [comment]
Can we close then if it's an issue with Firebug?

**Comment by muling** [comment]
ok let's close it.
