### ISSUE TITLE
Form validation: required checkbox that is on its own and not in a fieldset asterisk issue

### ISSUE THREAD

**Issue by robwloch** [wet-boew/wet-boew#6638]
We've come across instances where we require a single checkbox not in a fieldset and it is a required field. It seems that the asterisk bleeds into the checkbox. We've played with the CSS a bit as follows to get the red asterisk to appear before the checkbox but not sure if this can maybe be properly added to WET framework too? Thank you.

'''
div.checkbox.required:before{
        content:"* ";
        color: red;
        margin-left:-.665em
}
'''

**Comment by LaurentGoderre** [comment]
It porbably would me more elegant to use markup like this:

```html
<div class="checkbox required">
    <label for="animal3"><input type="checkbox" name="accept" value="1" id="accept" required="required" />I Accept</label>
</div>
```

We would still need some CSS for this though

**Comment by robwloch** [comment]
Thank you @LaurentGoderre . This is how it looks with the CSS added but wondering if you guys will add it to WET4 or should we just have our own custom CSS? Also, maybe for consistency you'd have the asterisk to the right of the checkbox.

![capture](https://cloud.githubusercontent.com/assets/5721679/6828116/4294f178-d2e2-11e4-98f0-022bf6a7380a.PNG)

**Comment by pjackson28** [comment]
I suspect the asterisk should remain on the left for scanning purposes (i.e., all the red asterisks should be aligned horizontally to enable scanning). If you put it on the right then it would be easily missed.

**Comment by thomasgohard** [comment]
Yes, the asterisk should be on the left of the checkbox. All the asterisks should be aligned down the form to support scanning.

**Comment by stephenbe** [comment]
@LaurentGoderre One a side note, I am always debating with myself if having a `label` wrapping a input is semantic or not. in the examples they don't wrap up, but it still works if you do 

http://www.w3.org/TR/WCAG20-TECHS/H44.html

Any insight into this would be much appreciated

**Comment by LaurentGoderre** [comment]
@stephenbe, the wrapping of the label is not enough for conveying relationships but in the example the label wraps and use the `for=id` to make an explicit relationship. I believe the label is wrapping the checkbook for styling reasons.

**Comment by stephenbe** [comment]
@LaurentGoderre I agree. I only do it if I really don't have a choice.

I actually did one with the label and input separated already if ever you would want to use it for WET : 

http://codepen.io/stephenbe/pen/wBOwEj

**Comment by LaurentGoderre** [comment]
Thanks!

**Comment by robwloch** [comment]
Hi @LaurentGoderre , I see that you've committed a fix for this but the issue is still open so just wondering if it's in the latest WET 4 sub-release? Or, in general how can I tell which release something will be in? Thank you.

**Comment by LaurentGoderre** [comment]
I proposed a fix but it isn't merged in. It hasn't been resolved yet

**Comment by robwloch** [comment]
Hi @LaurentGoderre , who needs to approve your proposed fix so that it can be merged? I ask because I'm afraid that this is going to sit in this state indefinitely and we have developers asking what they're supposed to do when they have a singe required checkbox field.

**Comment by LaurentGoderre** [comment]
I usually do but I didn't have the time to do the final review. @pjackson28 can you review?

**Comment by pjackson28** [comment]
The changes looked good (an it passed the build checks) so I merged them in.

**Comment by robwloch** [comment]
Thank you guys!
