### ISSUE TITLE
Phone number listed in Minister's Template

### ISSUE THREAD

**Issue by pch-alexanderm** [wet-boew/wet-boew#6640]
The telephone number listed in the Minister's profile page templates is a private GC office number.  It should be replaced with XXX-XXX-XXXX http://wet-boew.github.io/themes-dist/GCWeb/ministerial-en.html

**Comment by pjackson28** [comment]
Since this issue is specific to the Canada.ca theme (so needs to be fixed in a different repo), please file the issue in wet-boew/GCWeb and close the issue here.
