### ISSUE TITLE
Ministerial Profile Page 

### ISSUE THREAD

**Issue by pch-alexanderm** [wet-boew/wet-boew#6642]
The Ministerial Profile page contains GC phone numbers for an individual that has no relationship to the template.  It should be removed and replaced with filler text.  

http://wet-boew.github.io/themes-dist/GCWeb/ministerial-en.html

**Comment by pjackson28** [comment]
Please post this to the GCWeb repo instead since this is specific to the Canada.ca theme. Here is the URL for filing an issue to that repo: https://github.com/wet-boew/GCWeb/issues/new
