### ISSUE TITLE
Multi level mega menu in WET 4.0

### ISSUE THREAD

**Issue by irwink** [wet-boew/wet-boew#6643]
Has anyone implemented a multi level mega menu in WET 4.0 (Web Usability theme).  I have read the issues (https://github.com/wet-boew/wet-boew/issues/4807, https://github.com/wet-boew/wet-boew/issues/5307) describing why it is not supported (out of the box), and why it is not a good idea (usability and accessibility issues).

I have been asked by our communications team to provide it for our WET 4.0 pages.  Our sites will contain a mixture of WET 3.0 and WET 4.0 pages and our WET 3.0 pages have a multi level mega menu (http://www.tpsgc-pwgsc.gc.ca/comm/index-eng.html).  The few implementations I have tried (summary/details tags and column count) didn't behave like the WET 3.0 implementation.

If someone has implemented such a mega menu I would be interested to see the details.  If someone has tried and failed, or gave up, I would be interested in that also (possibly use it as a reason to not do it here too).

**Comment by pjackson28** [comment]
If you are moving to the GC Web Usability theme in WET v4.0 then we encourage you to take the same approach as TBS (http://www.tbs-sct.gc.ca/tbs-sct/index-eng.asp) and implement WET v4.0 faithfully rather than forcing WET v4.0 to behave like WET v3.x. Creating that hybrid will make future migration and onboarding to Canada.ca more difficult and time consuming.

So in this case, you should make your WET v3.0 pages adopt a WET v4.0 style menu rather than the other way around.

**Comment by irwink** [comment]
This was my first suggestion to our communications team, however, they are still looking for a multi level menu (if possible).

**Comment by pjackson28** [comment]
I don't think it is possible without creating significant keyboard accessibility/usability issues as we weren't able to resolve the conflicting keyboard expectations for visual and non-visual users (making the sub-sub-menu open by default really messes up visual keyboard expectations versus non-visual expectations).

Strange that the comms area is so focused on making a multi-level mega menu in WET v4.0 when they lose all control over the menu bar when they move to Canada.ca. They should instead be focusing their efforts on aligning to what will be required for Canada.ca to help simplify the future migration and onboarding work.

**Comment by irwink** [comment]
Communications agreed to go with a simple mega menu.
