### ISSUE TITLE
Progressive enhancement initComplete callback?

### ISSUE THREAD

**Issue by spartingto** [wet-boew/wet-boew#6648]
Hello,

I'm working with WET 3.1.7, the project has no intention to upgrade to 4 unfortunately. My issue is that when using wet-boew-tables we're getting flickering of unstyled content for a couple of seconds as the page is loading. It will shift a number of times within the browser.

I'm now loading the table via ajax once a skeleton page is loaded. This will ensure none of the supporting dataTable js is fired when the page is loaded. This obviously means we're losing sorting and paging functionality which is bad.

I'd like to hide the page entirely, then when the table has finished jumping around show the page. My problem is I cannot bind to any event from PE or DataTables when they are done doing their thing.

Is there any way to accomplish this? I've been told users may have epileptic fits if we leave it as is.

Thanks!

**Comment by LaurentGoderre** [comment]
WET 3.1 is no longer supported. That being said, your problem can most likely be addressed without all those workarounds. Do you have a page that shows the problem?

**Comment by sgdowney** [comment]
Would it be possible to upgrade to the last version of the 3.1 branch, 3.1.15?

**Comment by hsrudnicki** [comment]
@spartingto @LaurentGoderre and others: Can this issue be closed?

**Comment by pjackson28** [comment]
Closing since v3.1 is no longer supported.
