### ISSUE TITLE
Form validation // Reset form

### ISSUE THREAD

**Issue by UncleZen** [wet-boew/wet-boew#6652]
I have been experiencing difficulties resetting a form when using the WET form validation plugin. As you may observe in this page: http://wet-boew.github.io/v4.0-ci/demos/formvalid/formvalid-en.html when the user clicks the reset button the errors are actually cleared, but visually the controls continue to indicate errors in the form. Is there a fix or a workaround for this issue?

Thanks!

Zen

A quick clarification: This behaviour seem to take place only in case of required fields such as Title, First name, last name, telephone number in the sample page.

**Comment by hsrudnicki** [comment]
@UncleZen @LaurentGoderre : Can this issue be closed?

**Comment by RobJohnston** [comment]
May have been fixed by #6584, "Form Validation Input Field Stays Red after Error is Cleared & Is Red for No Error"?  At least related.

**Comment by pjackson28** [comment]
Will be fixed by PR #6880.
