### ISSUE TITLE
"Search" or "search engine"?

### ISSUE THREAD

**Issue by nrustand92** [wet-boew/wet-boew#6656]
For the following question:
"Did you use the search on our website today?"--in a website survey, with "search" referring to the search engine, would it be better to call it:
a) "Search"-as it is
b) "Search box," or
c) "Search engine"
d) anything else???

@thomasgohard @rubinahaddad @neoinsight @npjontek @bizsanford or anyone else, please chime in.

**Comment by bizsanford** [comment]
@nrustand92 Originally I would have voted just "search" but after doing some brief research, I'd say use "Did you use the search engine on our website today?" - it's clearer what you're talking about to the user. Possibly even "... on Canada.ca today?" but I'd say that depends how the rest of the survey is worded.

Using just "search" might be where we are headed in the future, but for example, I googled Google (inception!) and here's what they say... "search for information about (someone or something) on the Internet using the search engine Google."

**Comment by neoinsight** [comment]
Hmm, I've never heard even one of the 70+ usability participants on Canada.ca call it a 'search engine'. Search box is definitely used. I think the key is to distinguish it from Google  - so when you say "on our website today", it might be better to say "Did you use the search box located on the top right of any of our web pages today"

**Comment by LaurentGoderre** [comment]
I agree that the 'engine' might be ambiguous. I think that Search Box is more concrete and specific which might make it easier to understand.

**Comment by thomasgohard** [comment]
I agree with @neoinsight. Only IT types would likely refer to it as a search *engine*.

Although I would caution with specifying the location as top right of our web pages as that's only applicable on large screens. On mobile, it's in the menu.

I think that the original wording should be fine. You're asking specifically about "our website". If there's a worry about people including Google searches, you could reword as "Did you use the search [box] on Canada.ca today?" as @bizsanford suggested. People should understand.

**Comment by nrustand92** [comment]
Thanks everyone!

**Comment by bizsanford** [comment]
@nrustand92 I sent out a quick informal email poll to around 10 less techy people (I think I'm too far in) and got back "search box" and "search bar". You might also consider adding a tooltip with a short description... But I don't know if that's necessary (or accessible?).

**Comment by bizsanford** [comment]
@nrustand92 FYI - here's what I emailed them: "I’m doing a some informal user research… no wrong answers. What would you call the thing the red arrow is pointing to (top right)? And can you use it in a sentence for me please."

Here are some sentences I got back:
To find what you are looking for, type key words into the search bar.
Matt went to google and typed, “Why am I so perfect?” into the search bar.
Please use the search bar at the top right corner of the page.
If I want to find something specific that I'm looking for on a page, I will use the search box to try to find it. 
I just typed 'search bar' into Google's search bar to find any synonyms and came up empty. 

![search](https://cloud.githubusercontent.com/assets/11576030/6904474/f64991a0-d6ee-11e4-941c-c0e825c4e419.jpg)

**Comment by cdennis2** [comment]
Yes - thank you very much!  Your feedback is indeed appreciated!

**Comment by nrustand92** [comment]
@bizsanford thanks so much!!!

**Comment by hsrudnicki** [comment]
So, can this issue be closed?

**Comment by bizsanford** [comment]
Yes (right @nrustand92?)

**Comment by nrustand92** [comment]
Yes!

On Tue, Jun 16, 2015 at 5:13 PM, Elizabeth Sanford <notifications@github.com
