### ISSUE TITLE
WET Toolkit Mini?

### ISSUE THREAD

**Issue by mbourass** [wet-boew/wet-boew#6657]
Hi,

There might be an application deployed that would use the WET toolkit over a "really" slow connection. Is there a lightweight version of the toolkit and also is there one that could be standalone (in case there is no connection to Internet at all)?

Thanks in advance,

Martin Bourassa

**Comment by LaurentGoderre** [comment]
WET was created to be efficient on slow mobile connections. Have you encountered any issues?

We would have to look into standalone capabilities

**Comment by mbourass** [comment]
Thanks Laurent for the quick answer. We will have to do some testing eventually. The development is only starting but we have already that in mind.

That would be for a application that will run up North (Resolute Bay) using a satellite link to the south.

So, every bit of data counts!

- Martin

**Comment by mbourass** [comment]
Laurent, should I wait for an answer about standalone capabilities soon?

Martin

**Comment by CalvinRodo** [comment]
What do you mean by standalone? 

WET is just a framework for a website, it's already "standalone".

**Comment by mbourass** [comment]
I know it is a framework but what if there is no access to Internet at all? Are all the components (javascript librairies, CSS files, images, etc.) accessible locally?

**Comment by LaurentGoderre** [comment]
I am not clear as to what standalone means. You may be able to package it up so that it's all local but you need a web server of some sort to make it work.

**Comment by mbourass** [comment]
Ok, how do you package it up then? All files would be accessible from the localhost only?

**Comment by LaurentGoderre** [comment]
The only file that we rely on external sources is jQuery I believe, which you can download and host locally

**Comment by mbourass** [comment]
Thank you Laurent. We'll do some testing and try by hosting jQuery locally and see what happens.

**Comment by AndresCaicedo** [comment]
One suggestion for slower sites:  Ensure your HTTP headers have an expiry of 1 year for any WET files.  After the initial load, they will exist in your local cache.  Each time you upgrade your version of WET, however, they will understandably need to load the resources again.

However, if clients are often *disconnected*, and your browsers support it, you could use HTML5 Application Cache.  I've successfully used WET in a offline situation using the tips from [alistapart.com](http://alistapart.com/article/application-cache-is-a-douchebag).

My application cache file is as follows:

    CACHE MANIFEST
    # Contact Info page
    CACHE:
    /wet-boew/assets/logo.svg
    /wet-boew/ajax/sitemenu-en.html
    /wet-boew/css/theme.min.css
    /wet-boew/css/wet-boew.min.css
    /wet-boew/fonts/glyphicons-halflings-regular.woff
    /wet-boew/js/i18n/en.min.js
    /wet-boew/js/deps/jquery.dataTables.min.js
    /wet-boew/js/wet-boew.min.js

    //ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.js

    /js/contactlist.core-0.2.js
    /js/contactlist.offline-0.2.js

    FALLBACK:
    /index.html /index-offline.html

The `index.html` includes a hidden IFRAME that loads `index-offline.html`.  You can see that `/js/contactlist.offline-0.2.js` is cached, but it's only referenced by the `index-offline.html` page.  That is one way to separate the logic between online and offline states.

Again, depending on what you're trying to accomplish, this may or may not work for you.

(Why the long comment? Just as much for my own documentation!)

**Comment by mbourass** [comment]
Thank you Andres.

Really appreciate the time and the nice reply.

- Martin

**Comment by LaurentGoderre** [comment]
Does that resolve your issue?

**Comment by mbourass** [comment]
I don’t know yet. I passed it on to the developper on my project. I will only know when we test…

- Martin

**Comment by hsrudnicki** [comment]
@mbourass @LaurentGoderre : Are you ready to close this issue?

**Comment by mbourass** [comment]
Yes, thanks.

**Comment by CalvinRodo** [comment]
@mbourass I'm curious if this suggestion resolved your issue, I'm also looking to implement WET on some slow connections (Ships at sea) and would like to know how this worked for you?

**Comment by mbourass** [comment]
@CalvinRodo It has been implemented but not tested in the real environment yet. We're getting late in that project...
