### ISSUE TITLE
Extra code on secured error/splash pages 

### ISSUE THREAD

**Issue by Wenifred** [wet-boew/wet-boew#6658]
Hi there,

When going into a secure area (apps) some odd code is showing up. I generates this code:

```
<div style="position: absolute;">
  <math>
    <mfrac>
      <mi>xx</mi>
      <mi>yy</mi>
    </mfrac>
  </math>
</div>
```

We noticed them specifically on the error message and splash page that we grabbed from the Government of Canada Web Usability theme. If I change the link to https:// on your example pages it shows the same code.  

Here are a couple examples:
https://wet-boew.github.io/themes-dist/theme-gcwu-fegc/404-en-fr.html
https://wet-boew.github.io/themes-dist/theme-gcwu-fegc/servermessage-en-fr.html

![31-03-2015 4-34-46 pm](https://cloud.githubusercontent.com/assets/5551287/6929603/16ee49d8-d7ca-11e4-93cb-e91040563fc5.png)

Thanks,
Wendy

**Comment by nschonni** [comment]
That code is injected by the MathML polyfill when it tests the browser for support. The library has cleanup code to remove that leftover markup https://github.com/wet-boew/wet-boew/blob/70790415dd970782e8221b2e9e12e79e785c2035/src/core/wb.js#L463 so I'm not sure why it is being leftover

**Comment by LaurentGoderre** [comment]
Looks like something is being loaded via http on an https page which causes this issue. in IE, if you click Show All Content, it disappears.

**Comment by LaurentGoderre** [comment]
This happens when the link to jQuery uses http and the page linking to it uses https. We should probably change all themes to link to HTTPS all the time.

**Comment by Wenifred** [comment]
Sorry I should have came back to update this ticket. That is exactly what we did, we changed the jQuery path to https and it resolved the issue.

**Comment by LaurentGoderre** [comment]
We will solve this for everyone by always pointing to https. It is the recommendation to use HTTPS to link to CDN resources

**Comment by pjackson28** [comment]
Note that PR #6874 will hide the MathML through CSS in case jQuery doesn't load for whatever reason.
