### ISSUE TITLE
Geomap: Add international maps

### ISSUE THREAD

**Issue by bsouster** [wet-boew/wet-boew#6665]
@jvanulde

**Comment by bsouster** [comment]
We currently have someone going over Terms and Conditions for these two basemaps:
http://cartodb.com/enterprise/ 
http://developer.mapquest.com/web/products/open/map

**Comment by hsrudnicki** [comment]
Can this issue be closed?

**Comment by bsouster** [comment]
@jvanulde Thanks Joost!
