### ISSUE TITLE
WET CAPTCHA

### ISSUE THREAD

**Issue by bsouster** [wet-boew/wet-boew#6667]
Are there any plans of creating a CAPTCHA for WET or one already in the works?

**Comment by pjackson28** [comment]
No, there are no plans at this time for creating a CAPTCHA under WET. Please see https://github.com/wet-boew/theme-gcwu-fegc/issues/136 for the related discussion. The recommendation is to use less intrusive and more reliable approaches (less false negatives/positives).

**Comment by bsouster** [comment]
Missed that, thanks Paul
