### ISSUE TITLE
Input type="date" polyfill (date picker): arrow keys do not work as expected in the calendar grid of days 

### ISSUE THREAD

**Issue by dfarough** [wet-boew/wet-boew#6670]
@wet-boew/access-working-group
According to the aria guidelines for the date picker using up and down arrows should move you to the same day in the previous or next week.  Are we going to conform to these practices in the date picker?
see http://www.w3.org/TR/wai-aria-practices/#datepicker for other keyboard functionality.  Left as it is, navigation throughout  the grid is much worse than it would be if we allowed the cursor keys to function as described in the ARIA practices document.  this would be a big help to keyboard and AT users.

**Comment by LaurentGoderre** [comment]
@dfarough, I just tested and using the up arrow jumps to the same day in the previous week and the down arrow is going to the same day in the next week. Bear in mind that if you reach the higher or lower bound (trying to reach a date that is outside the min and max defined) then the selection stays at the same location.

Can you describe the issue you are encountering?

**Comment by dfarough** [comment]
OK, I see the problem now.
I was pressing down arrow which would not work because that date was out of range.  Also because I was using Jaws it is necessary to disable the virtual cursor before using the arrow keys to navigate the calendar grid.  perhaps using a different min and max date range would be less confusing for the examples.  Also providing a hint when entering the grid would be helpful.  Alternatively  putting the grid within the application role would cause the cursor keys to work properly automatically.  It seems to me that this was changed some time ago although I cannot remember the reason at the moment.

**Comment by pjackson28** [comment]
We removed the application role because NVDA treats such a region as a black box (making it hard to get in and out). In this case it may be okay since the polyfill takes care of moving focus in and out of the area (you can't navigate into it by normal means, which was a major issue with the menus). So maybe we try re-adding the application role and see if things behave as they should in Jaws and NVDA (for NVDA we should do a before and after to see if anything changes). If that works out in both screen readers, then maybe we could try re-adding the application role to the lightbox plugin to address similar issues.

**Comment by dfarough** [comment]
Is there some way to indicate to a user that arrowing beyond the min and maximum dates specified for the date range has occurred?  Perhaps a message of some sort should be provided.  I got no clue even when I turned off the virtual cursor that I was trying to move beyond the valid date range.

**Comment by LaurentGoderre** [comment]
There is no easy way to do this because there are several ways you can end up out of bounds, for example if you try to switch month or years with the page up and down arrows

**Comment by mysticjeff** [comment]
Maybe a javascript alert w/ARIA if keyboard command is pressed that puts 1 in that position?

-----Original Message-----

**Comment by jrowsell** [comment]
This may work, as the alert would inform the user they are outside of bounds for the calendar.

**Comment by LaurentGoderre** [comment]
Using an alert could be potentially very disruptive.

**Comment by mysticjeff** [comment]
The alert could be non visual ? 
Or minimally visual.

Better than getting lost.

-----Original Message-----

**Comment by LaurentGoderre** [comment]
I don't think there is such a thing as non visual alert. We rely on the ARIA specs for this and unfortunately they don't specify the behavior for such scenario

**Comment by mysticjeff** [comment]
If you use A segment of text that is off screen using CSS (i.e. navaid)

And some javascript to trigger it being read (i.e. 
http://www.paciellogroup.com/blog/2012/06/html5-accessibility-chops-aria-rolealert-browser-support/


-----Original Message-----

**Comment by LaurentGoderre** [comment]
If everyone agrees on this approach, I can implement it in the new code

**Comment by SBleeks** [comment]
We should probably test a sample first.

**Comment by hsrudnicki** [comment]
Are you ready to close this issue?

**Comment by LaurentGoderre** [comment]
No, nothing was implemented

**Comment by hsrudnicki** [comment]
Made "Going Stale" and please update this issue's status whether this issue can be closed or otherwise?

**Comment by hsrudnicki** [comment]
Is this still an issue? Either way, please update again this issue's status, whether this issue that is referenced with the other issue: 6671 can be closed or otherwise?  Thank you

**Comment by LaurentGoderre** [comment]
I believe that this is fixed but we can wait until this is test (even though the unit test indicates that it works)

**Comment by dfarough** [comment]
@wet-boew/access-working-group 
Do the wet 4 examples reflect the code to be tested?

Which of the many issues discussed here have been addressed?

In my opinion the following issues have not been addressed.

1.  Arrow keys do not behave as discussed in the ARIA specification unless the user disables the virtual cursor or browse mode in access technology.

2.  no messaging occurs if a user moves out of a minimum or maximum date range.

also if you move into the date picker for the start date and go to the month drop down you cannot select a different month even though all 12 months are present.

the visible focus does not change when moving  through dates in the calendar grid unless I disable the virtual cursor or browse mode in Jaws.  The only discernible difference between  dates that are out of range is that the date is not a link.  if I press enter on a date that is out of range the dialogue disappears and the system focus is placed back to the start date which has not changed as a result of our trip to the date picker.  Sometimes Jaws looses track of the focus and pressing tab at this point causes focus to move to the address bar.

Earlier there was some discussion around the use of the application role for this dialogue.  Has this been ruled out?  If so, how do you plan to advise users of some Access technology of steps to be taken to achieve the proper behaviour of the cursor keys in the calendar grid?

**Comment by LaurentGoderre** [comment]
This is very difficult to track compond issues. I will close this since it was mostly implemented. Please open new and seperate issues for remaining problems.

**Comment by hsrudnicki** [comment]
Based on the above, this issue can be closed as resolved. If you think otherwise, please again update the status of this, thank you
