### ISSUE TITLE
Feedback Form (WET 4.x)

### ISSUE THREAD

**Issue by tbuhler** [wet-boew/wet-boew#6671]
I am setting up a form using the feedback form example and I noticed that if I have JavaScript disabled in the browser the form and inputs disappear (this happens in the working example). Is there a solution for this issue?

**Comment by LaurentGoderre** [comment]
This is by design. The solution relies on JavaScript and therefore replaces the form with alternate ways to send feedback (mail or phone)

**Comment by LaurentGoderre** [comment]
@tbuhler did this answer your question?

**Comment by hsrudnicki** [comment]
@tbuhler @LaurentGoderre : Can this issue be closed?

**Comment by pjackson28** [comment]
Closing since the question was answered.
