### ISSUE TITLE
JavaScript Style Guide

### ISSUE THREAD

**Issue by CalvinRodo** [wet-boew/wet-boew#6672]
Hi Guys, 

I'm looking to create a recommendation for JavaScript in our branch here at ESDC as well as providing some rules for static analysis. 

I'm really looking to do as little work as possible by using something that's already been done, so I'm looking to recommend the same naming conventions and Static Analysis (JSHint) rules that are in use by WET-BOEW. 

Do you have anything other then the following guidelines for contributors to your project? 
http://wet-boew.github.io/wet-boew/docs/pull-en.html
http://wet-boew.github.io/wet-boew/docs/opt-en.html

For instance do you have anything that enforces naming conventions for variables and functions?

**Comment by LaurentGoderre** [comment]
Actually JSHint is not for code style but for code performance (especially for minification).

We use JSCS (JavaScript CodeStyle) to enforce the code styles. We use jQuery as a basic but we customize it a bit.

**Comment by LaurentGoderre** [comment]
Here is our JSCS config file https://github.com/wet-boew/wet-boew/blob/master/.jscsrc

**Comment by LaurentGoderre** [comment]
I also personally use Sublime 3 which has an amazing linter with a JSCS component that highlight errors as you go.

**Comment by CalvinRodo** [comment]
Awesome, so then I guess the recommend workflow for JavaScript would be a combination of JSHInt and JSCS.  

So I guess where you diverge from JQuery is specified in the JSCS config file?
https://contribute.jquery.org/style-guide/js/

Now this is just curiosity on my part but what prompted the customization of the rules?

**Comment by CalvinRodo** [comment]
I'm a big fan of Sublime Text as well, but I don't think I'd be able to recommend that in house.  

We are stuck with what's already been approved, so I'll be coming up with guides on how to integrate JSCS and JSHint into Visual Studio and Eclipse.

**Comment by LaurentGoderre** [comment]
I'm sure it can be done! There might already be plugins or you might be able to create one.

**Comment by CalvinRodo** [comment]
Oh for sure, VS has support for gulp, grunt, and linters. 
I'm sure eclipse does as well.
