### ISSUE TITLE
Multimedia player: play event not detected in Firefox and IE

### ISSUE THREAD

**Issue by crichard** [wet-boew/wet-boew#6676]
I am tracking events using Google Analytics.  I want to track information on videos played on my website.  I am using v4.0.13-development - 2015-03-27.  I have the same issue with 4.0.11.  The play event is not detected in Firefox and IE11.  It works fine in Chrome.

```
var gaTracking_HTML5 = function () {
            console.log('gaTracking_HTML5 called');
            var href = $(this).find("source").attr('src');
            videotitle = $(this).find("video").attr('title');
            if (href == undefined) {
                href = $(this).data('src');
                videotitle = $(this).data("title");
            }

            if (currentvideotitle != videotitle) {
                started = false;
            }

            if (!started) {
                try {
                    currentvideotitle = videotitle;
                    ga('send', 'event', {
                        'eventCategory': 'Videos',
                        'eventAction': 'Play',
                        'eventLabel': href + ' (' + videotitle + ')'
                    });
                    started = true;
                    console.log('Video Play ' + href + ' (' + videotitle + ')');
                }
                catch (err) { }
            }
        }
```

```
wb.doc.on("play", ".wb-mltmd", gaTracking_HTML5);
```

**Comment by LaurentGoderre** [comment]
:S There is a bug in one of the browser with the `play` event so I switched to the `playing` event

**Comment by crichard** [comment]
Ok, it works with playing.  But in Chrome, there seems to be a bug where the function called in on "playing" is called non-stop (like every second or more).

```
 $(wb.doc).on("playing", ".wb-mltmd", gaTracking_HTML5);
```
![function_mltmd](https://cloud.githubusercontent.com/assets/390668/7094212/732f0c26-df8d-11e4-9cfd-e619776dcbf3.png)

**Comment by crichard** [comment]
The problem is that the video is rendered as a Flash object in Chrome for some reason ...

**Comment by LaurentGoderre** [comment]
That must be a bug in the Flash fallback then. I will have to fix that.

**Comment by LaurentGoderre** [comment]
Actually it's not supposed to do that at all. The flash code seems ok

**Comment by crichard** [comment]
What could cause this then?  
See this link in Chrome: http://webdev.multimediaservices.ca/en/job/pharmacyofficer-31

**Comment by LaurentGoderre** [comment]
I don't know. I would have to investigate

**Comment by hsrudnicki** [comment]
@crichard @LaurentGoderre : Can this issue be closed?

**Comment by LaurentGoderre** [comment]
No it's still an issue

**Comment by hsrudnicki** [comment]
Made "Going Stale" before closing this issue or otherwise? Please update this issue's status again, thank you

**Comment by hsrudnicki** [comment]
Is this still an issue? Either way, please again update this issue's status, whether this issue can be closed as fixed or otherwise?  Thank you

**Comment by hsrudnicki** [comment]
Is this still an issue? Please update the status of this again in regards to the current year, thank you

**Comment by hsrudnicki** [comment]
Is this still an issue? Please keep the status of this issue updated for the current year as well, thank you

**Comment by masterbee** [comment]
closing since the caller's (creator of issue) appears to have abandoned the issue and WET code base has evolved greatly since the last entry
