### ISSUE TITLE
Geomap: Add support for logical operators

### ISSUE THREAD

**Issue by muling** [wet-boew/wet-boew#6678]
Need to add some business logic to the style rules for the map markers.  It doesn't seem like this is currently supported.

We would like to do something like this:

      style: {
        rules: [
          new OpenLayers.Rule({
            filter: new OpenLayers.Filter.Logical({
              type: OpenLayers.Filter.Logical.AND,
              filters: [
                new OpenLayers.Filter.Comparison({
                  type: OpenLayers.Filter.Comparison.EQUAL_TO,
                  property: 'Data Available',
                  value: 'Yes'
                }),
                new OpenLayers.Filter.Comparison({
                  type: OpenLayers.Filter.Comparison.EQUAL_TO,
                  property: 'Operation Schedule',
                  value: 'Continuous'
                })
              ]
            }),
            symbolizer: {
              strokeColor: 'red',
              fillColor: 'red',
              pointRadius: '6',
            }
          })

**Comment by LaurentGoderre** [comment]
@jvanulde please answer

**Comment by jvanulde** [comment]
@muling this is in progress.

**Comment by jvanulde** [comment]
@muling we have something working now. Can you send me a sample file with some rules you need implemented? That way we can test against your requirements.

**Comment by muling** [comment]
You mean the config rules file?  Or can I just send you a plain description of the rules?

**Comment by jvanulde** [comment]
Plain description will be sufficient. As well as a datasource/dataset that you intend to apply them too.

**Comment by muling** [comment]
Config rules:
If schedule is continuous AND data_availabe=yes, then display green circle
Else if schedule is continuous AND data_availabe=no, then display red circle
Else if schedule is seasonal AND data_availabe=yes, then display a green square
Else if schedule is seasonal AND data_availabe=no, then display a red square

Sample Dataset (up to 8000 points):
<tr data-type="wkt" data-geometry="POINT (-108.773330, 59.999440)">
        <td><input type="checkbox" id="check1" name="check[]" value="07QC005,1,,,"/></td>
        <td><label for="check1">ABITAU RIVER ABOVE CUMING LAKE</label></td>
        <td>SK</td>
        <td>07QC005</td>
        <td class="icon-green image-center">Yes</td>
        <td>Continuous</td>
      </tr>
      <tr data-type="wkt" data-geometry="POINT (-81.414640, 50.602920)">
        <td><input type="checkbox" id="check2" name="check[]" value="04ME003,2,,,"/></td>
        <td><label for="check2">ABITIBI RIVER AT ONAKAWANA</label></td>
        <td>ON</td>
        <td>04ME003</td>
        <td class="icon-green image-center">Yes</td>
        <td>Continuous</td>
      </tr>
      <tr data-type="wkt" data-geometry="POINT (-109.837220, 49.642500)">
        <td><input type="checkbox" id="check3" name="check[]" value="11AB095,3,,,"/></td>
        <td><label for="check3">ADAMS LAKE</label></td>
        <td>SK</td>
        <td>11AB095</td>
        <td class="icon-red-diamond image-center">No</td>
        <td>Seasonal</td>
      </tr>
      <tr data-type="wkt" data-geometry="POINT (-119.654440, 50.938330)">
        <td><input type="checkbox" id="check4" name="check[]" value="08LD001,4,,,"/></td>
        <td><label for="check4">ADAMS RIVER NEAR SQUILAX</label></td>
        <td>BC</td>
        <td>08LD001</td>
        <td class="icon-green image-center">Yes</td>
        <td>Continuous</td>
      </tr>
      <tr data-type="wkt" data-geometry="POINT (-122.715560, 58.106110)">
        <td><input type="checkbox" id="check5" name="check[]" value="10CD005,5,,,"/></td>
        <td><label for="check5">ADSETT CREEK AT KILOMETRE 386.0 ALASKA HIGHWAY</label></td>
        <td>BC</td>
        <td>10CD005</td>
        <td class="icon-green image-center">Yes</td>
        <td>Continuous</td>
      </tr>

**Comment by jvanulde** [comment]
Thanks @muling that helps. So we have it working based on the psuedo-rules provided. Please see the screenshot below. We have some testing to do still but I am hoping we can push the update soon.

Result:

![screen shot 2015-05-13 at 9 53 31 am](https://cloud.githubusercontent.com/assets/2255248/7616261/ee2487ce-f957-11e4-89e4-0d1d036be080.png)

For you reference here is the configuration:

    "style": {
    "type": "rule",
    "rule": [
      {
        "filter": "AND",
        "title": "Continuous - Data avail.",
        "filters": [
          {
            "field": "schedule",
            "value": ["continuous"],
            "filter": "EQUAL_TO"
          },
          {
            "field": "data_available",
            "value": ["yes"],
            "filter": "EQUAL_TO"
          }
        ],
        "init": {
          "strokeColor": "green",
          "fillColor": "green",
          "pointRadius": 8,
          "fillOpacity": 0.8,
          "strokeWidth": 2
        }
      },
      {
        "filter": "AND",
        "title": "Continuous - No data",
        "filters": [
          {
            "field": "schedule",
            "value": ["continuous"],
            "filter": "EQUAL_TO"
          },
          {
            "field": "data_available",
            "value": ["no"],
            "filter": "EQUAL_TO"
          }
        ],
        "init": {
          "strokeColor": "red",
          "fillColor": "red",
          "pointRadius": 8,
          "fillOpacity": 0.8,
          "strokeWidth": 2
        }
      },
      {
        "filter": "AND",
        "title": "Seasonal - Data avail.",
        "filters": [
          {
            "field": "schedule",
            "value": ["seasonal"],
            "filter": "EQUAL_TO"
          },
          {
            "field": "data_available",
            "value": ["yes"],
            "filter": "EQUAL_TO"
          }
        ],
        "init": {
          "strokeColor": "green",
          "fillColor": "green",
          "graphicName": "square",
          "pointRadius": 8,
          "fillOpacity": 0.8,
          "strokeWidth": 2
        }
      },
      {
        "filter": "AND",
        "title": "Seasonal - No data",
        "filters": [
          {
            "field": "schedule",
            "value": ["seasonal"],
            "filter": "EQUAL_TO"
          },
          {
            "field": "data_available",
            "value": ["no" ],
            "filter": "EQUAL_TO"
          }
        ],
        "init": {
          "strokeColor": "red",
          "fillColor": "red",
          "graphicName": "square",
          "pointRadius": 8,
          "fillOpacity": 0.8,
          "strokeWidth": 2
        }
      },
      {
        "elseFilter": true,
        "title": "Other",
        "init": {
          "pointRadius": 8,
          "strokeColor": "#666666",
          "graphicName": "triangle",
          "fillColor": "#666666",
          "fillOpacity": 0.8,
          "strokeWidth": 2
        }
      }
    ]
    }

**Comment by muling** [comment]
Is it possible to use our own icon?  What shapes are available?

**Comment by jvanulde** [comment]
You can use your own symbols. Or one of the predefined ones: "star", "cross", "x", "square", "triangle", and "circle" as value for the graphicName property of a symbolizer.

**Comment by hsrudnicki** [comment]
Can this issue be closed?

**Comment by muling** [comment]
We haven't tested it ourselves yet, but you can close it.
