### ISSUE TITLE
Remove the event calendar list filtering?

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/wet-boew#6681]
It seems like this functionality is broken and was for a year which makes me wonder if we need it at all

**Comment by LaurentGoderre** [comment]
@pjackson28 what do you think?

**Comment by pjackson28** [comment]
I think it would be risky to drop it, particularly because there may be some departments migrating from WET3 that expect that functionality. Best to fix it if we can.

**Comment by LaurentGoderre** [comment]
ok
