### ISSUE TITLE
Date polyfil does not fire/disables the onChange event when leaving associated textbox

### ISSUE THREAD

**Issue by GarthMartin** [wet-boew/wet-boew#6683]
I am implementing a "drityForm" functionality and as part of it I assign a change event to all input types on my form as follows:

```javascript
//Setup the onChange event on each of the form elements to set the dirty flag.
    $("#mainForm input:text, #mainForm textarea, #mainForm input:checkbox, #mainForm select, #mainForm input:radio, #mainForm .trigger-dirty").each(function () {
        var elem = "#" + $(this).attr("id");
        wb.doc.on("change", elem, function () {
            SetDirtyForm(true);
        });
    });
```

This is all well and good except when I use the date-picker.  If I enter a date manually it works, however if I use the date picker the event does not fire.  Despite the focus going back to the text box associated to the date-picker, when that element loses focus, the change event does not fire.

Any thoughts on this?  Is there a callback or something I can leverage on the date picker to fire my dirty form event?  

Thanks,

Garth

**Comment by LaurentGoderre** [comment]
The date picker is being completely remade. We will implement this in the new one.

**Comment by GarthMartin** [comment]
@LaurentGoderre is there an ETA on that?  Any thoughts on how I could implement this functionality while still using the polyfil?  Is there a callback or something I could use?

**Comment by LaurentGoderre** [comment]
Unfortunately no, the code needs to be changed to trigger the handler from within

**Comment by GarthMartin** [comment]
OK back to the drawing board...

**Comment by GarthMartin** [comment]
@jueheed  here is how I worked around this issue - ref #6841.
``` javascript
  // the WET 4 date polyfil kills the onchange event for the textbox so we need to work around this for the date fields
    // all date fields must be tagged with .trigger-dirty-date for this to work and have a data-defaultValue attribute set.
    // the Number type validation also kill the onchange event so we can do it this way as well.
    $("#mainForm .trigger-dirty-date, #mainForm .trigger-dirty-text").each(function () {
        var elem = "#" + $(this).attr("id");

        // grab the current value of our field and set our data attribute
        $(elem).attr("data-defaultValue", $(elem).val());

        wb.doc.on("blur", elem, function () {
            // compare the current value of the date field with the previous value
            if ($(elem).val() != $(elem).attr("data-defaultValue")) {
                SetDirtyForm(true);
            }
        });
    });

**Comment by LaurentGoderre** [comment]
I want to keep it open so I remember to fix it in the new version

**Comment by GarthMartin** [comment]
OK, sorry bout that!

**Comment by hsrudnicki** [comment]
@LaurentGoderre @GarthMartin : Are you ready to close this issue?

**Comment by LaurentGoderre** [comment]
No because it is not yet fixed

**Comment by hsrudnicki** [comment]
Made "Going Stale" to close this issue as resolved/fixed due to the above or otherwise? Either way, please update this issue's status, thank you
