### ISSUE TITLE
Collapsible alerts: I get 102 aria effors for this page using Firebug

### ISSUE THREAD

**Issue by dfarough** [wet-boew/wet-boew#6684]
The error message is:
An ARIA attribute was used that is not allowed for this role

**Comment by LaurentGoderre** [comment]
@Pacoup was it you who worked on that plugin?

**Comment by Pacoup** [comment]
@LaurentGoderre Yup, I'll check it out.

**Comment by Pacoup** [comment]
@dfarough I can't find any such WAI-ARIA validator in Firebug. Are you using an extension? If so, which extension?

**Comment by dfarough** [comment]
I am using Fireeyes

**Comment by Pacoup** [comment]
@dfarough This has nothing to do with Collapsible alerts. It is the drop down menu and other elements of the page which are misusing certain ARIA attributes:

```HTML
<a role="menuitem" aria-setsize="9" aria-posinset="2"
   tabindex="-1" href="http://wet-boew.github.io/v4.0-ci/index-en.html#benefits">
Benefits</a>
```

For instance, this menu item includes the `aria-setsize` and `aria-posinset` attributes which seem to only be usable on elements with the roles **listitem** and **option**.

* http://www.w3.org/TR/wai-aria/states_and_properties#aria-setsize
* http://www.w3.org/TR/wai-aria/states_and_properties#aria-posinset

@LaurentGoderre @pjackson28 ?

**Comment by pjackson28** [comment]
@pacoup In WAI-ARIA 1.1 they did extend it to radio and tab roles but the reason why we added it to menuitems is because certain screen readers were not announcing the number of items in the menu. So the aria-setsize and aria-posinset were added to correct that behaviour and improve the usability for screen reader users.

**Comment by LaurentGoderre** [comment]
Safe to say that we can ignore those warning then?

**Comment by Pacoup** [comment]
I would say so. @dfarough ?

**Comment by dfarough** [comment]
@wet-boew/access-working-group

That seems reasonable to me, however I saw an article written by BrYan Gareventa which discusses changes that are being worked on   in the ARIA practices document that are quite interesting so perhaps there are aspects of this work that we can incorporate in our menus.  check out the article at: 
https://www.linkedin.com/groups/ARIA-Menus-updated-support-automatic-4512178.S.5965034268953432068

**Comment by LaurentGoderre** [comment]
@dfarough  Can you open a new issue for this so we can more easily manage future improvments?

**Comment by dfarough** [comment]
I will close this issue.  I have created https://github.com/wet-boew/wet-boew/issues/6694

**Comment by LaurentGoderre** [comment]
Thanks!
