### ISSUE TITLE
Form validation: 

### ISSUE THREAD

**Issue by philos22** [wet-boew/wet-boew#6685]
Hi, 

The form validation plugin was working fine for a while, but suddenly, now the error messages on the top of the page are showing up like this:
"undefined 1undefined Email:undefinedThis field is required."
when they should be like:
"Error 1: Email: This field is required."

Thanks

**Comment by LaurentGoderre** [comment]
Where is this occuring? Looks like an i18n issue

**Comment by LaurentGoderre** [comment]
I can't reproduce on the working examples. Two reason I can see, the first one, the page does not have a valid lang attribute, the second reason is that the `js/i18n` folder is missing.

**Comment by LaurentGoderre** [comment]
@philos22 any update on this?

**Comment by philos22** [comment]
Sorry for the late reply...

I had xml:lang in my html tag but not lang

**Comment by LaurentGoderre** [comment]
Can we close then?

**Comment by philos22** [comment]
Yes, thank you very much!
