### ISSUE TITLE
Geomap Internet Explorer (IE) issue map loading

### ISSUE THREAD

**Issue by upsonp** [wet-boew/wet-boew#6687]
https://inter-l01.dfo-mpo.gc.ca/sites/bio/science/data-donnees/can-ewlat/index2-en.php

I set up this public demo to demonstrate a huge performance issue in Internet Explorer. GeoMap works great in FireFox, Chrome, Opera and Safari, but it really sucks in IE.

Sometimes it causes the browser to completely lock up, sometimes it just takes a REALLY long time to load. After it's loaded it seems to work fine.

**Comment by CalvinRodo** [comment]
I'm going to take a guess here based on past experience I've had with the Tables plugin and say that some of the issue has to do with the size of the table. We ran into a huge problem with any table that had over a hundred or so items it would just take forever to load, it was even worse on IE < 11 and would run into issues in IE 8. 

One of the solutions that we found was to load the data asynchronously, now that became a giant pain in the butt in IE < 11, but it was the only solution we could find. 

I highly recommend you follow our lead and do the same, you have way too many data points for the tables plugin to handle synchronously. You'll also find benefits in other browsers as well. 

I can only assume the geomap plugin would have similar issues in IE.

**Comment by upsonp** [comment]
I know very little about how to do asynchronous loading with jQuery / JavaScript / AJax

Do you have any resources I can read up on? I was trying todo this anyway by having an Area of Interest box the user can draw on the map and it would reshape the table and plot the points, I wasn't very successful. I kind of had it working in Firefox and Chrome, but it wouldn't do anything at all in IE 9.

**Comment by CalvinRodo** [comment]
If you are doing any work in JavaScript you absolutely have to use the [Mozilla Developer Network (MDN)](https://developer.mozilla.org/en-US/docs/Web/JavaScript) as a reference. 

I imagine you ran into an issue where you were using a method that wasn't supported in IE 9 and you didn't have the appropriate polyfills for it, MDN will tell you what Native JS functions are supported by what browser and provide you with polyfills so you can use those functions.

As for documentation on Asynchronous loading I highly recommend the [DataTables website](http://www.datatables.net/) and the [Jquery API Documentation](https://api.jquery.com/) in particular it's section on [AJAX](https://api.jquery.com/category/ajax/)

**Comment by upsonp** [comment]
Thanks for the links @CalvinRodo I'm having an issue loading a table, when I try to use this method (http://www.datatables.net/examples/data_sources/ajax.html) I get the table is already initialized.

Is there a way to load the data table before the GeoMap API creates and loads it. Or, more preferable, a way to load the table after the map is loaded, but then put the table data on to the map?

```javascript

**Comment by LaurentGoderre** [comment]
You should be able to specify the ajax in the `data-` attribute of the datatable

**Comment by LaurentGoderre** [comment]
```
<table class="wb-tables table table-striped table-hover" data-wb-tables='{ "ajax": "data/html/rpsslocations.txt"}'>
</table>
```

**Comment by CalvinRodo** [comment]
We used a WebService, in your case it might be easier to follow @LaurentGoderre advice of using a data attribute. 

In our situation IE couldn't handle the full list of items even through a data attribute, and so we had to keep calling a Web Service with either the filter or the page number. We couldn't load up a text file, it was too big.

**Comment by upsonp** [comment]
@CalvinRodo @LaurentGoderre Great So I'm loading data from a text file into the data-table, is there an ajax variable I can use to load javascript functions for processing that data?

As and example I have this in my text file

```
{
	"data": [
		[
		"POINT (-67.1012, 44.5018)",
		"<a target=\"_blank\" href=\"selected-location-en.php?type=RPSS&amp;prov=NB&amp;loc=Machias Seal Island&amp;station=365\">Machias Seal Island</a>",
		"NB",
		"365",
		"4",
		"10",
		"15",
		"21",
		"28",
		"36",
		"46",
		"58",
		"72",
		"88",
		"106"
		],
```

The first variable is the location I want to draw on the map so I need to produce a Table row like

```HTML
		<tr data-geometry="POINT (-67.1012, 44.5018)" data-type="wkt">
			<td><a target="_blank" href="selected-location-en.php?type=RPSS&amp;prov=NB&amp;loc=Machias Seal Island&amp;station=365">Machias Seal Island</a></td>
			<td>NB</td>
			<td>365</td>
			<td class="allow 2000">4</td>
			<td class="allow 2010">10</td>
			<td class="allow 2020">15</td>
			<td class="allow 2030">21</td>
			<td class="allow 2040">28</td>
			<td class="allow 2050">36</td>
			<td class="allow 2060">46</td>
			<td class="allow 2070">58</td>
			<td class="allow 2080">72</td>
			<td class="allow 2090">88</td>
			<td class="allow 2100">106</td>
		</tr>

```

**Comment by LaurentGoderre** [comment]
If your file is in JSON, you should renamed it to .json instead of .txt and it will be interpreted as JSON so you won't need to process it.

https://datatables.net/reference/option/ajax

**Comment by upsonp** [comment]
This is awesome, thanks @LaurentGoderre I hate having to continually pestering people for how to do stuff, but once I get the hang of it I should be able to find this stuff myself ^_^

**Comment by upsonp** [comment]
@LaurentGoderre I've been able to use the data- method to load a JSON file pretty easily, do you have any examples of people using this to load the table with functions. I'm still looking at other examples, but I haven't found a way to set the <tr> data-geometry attribute using data from the file.

It also creates an issue with the first column in the table the GeoMap API creates with the selection check boxes because the table data is update AFTER the map and table have loaded and the table is reformatted by the GeoMap API.

**Comment by LaurentGoderre** [comment]
I think we will need to figure it out with @jvanulde

**Comment by LaurentGoderre** [comment]
Btw, is it an issue in IE11?

**Comment by upsonp** [comment]
@LaurentGoderre I tried it out in IE11, it's still not as good as it is in Firefox or Chrome, but it's still not great.

**Comment by hsrudnicki** [comment]
So, are you ready to close this issue?

**Comment by upsonp** [comment]
This still a problem with load times in internet explorer. I think we've narrowed it down to an issue with the table plugin when there's more than a hundred entries. I've requested some training in July that I hope will help me to sort out the problems, but honestly the Ajax / javaScript solution seems pretty complex just to make it work in IE.

**Comment by hsrudnicki** [comment]
Made "Going Stale" to close this issue soon or otherwise? Either way, please update this issue's status, thank you

**Comment by upsonp** [comment]
I'm using KML files to handle the data now. It was a pain to write a converter to create them, but it works much more effectively. The performance in IE is still not as good as it is in other browsers, but it's significantly better than it was and at the very least usable.

I'll close this for now given it's not on my radar anymore.
