### ISSUE TITLE
Input type="date" polyfill (date picker): 

### ISSUE THREAD

**Issue by muling** [wet-boew/wet-boew#6689]
When I try to change the year drop down from the current year to the previous, the months do not update accordingly.  This happens for Firefox and IE.  The WET3 version of this plugin worked correctly.

**Comment by LaurentGoderre** [comment]
Currently with v4 as with v3 you need to press the go button to update the month after selecting it. The date picker is being revised and a new version should be available shortly.

**Comment by muling** [comment]
This poses a problem for us.  

<input id="startDate" class="short form-control row-end mrgn-lft-0 mrgn-rght-0 date_js_off wb-date-inited picker-field" type="date" value="2015-04-07" max="2015-04-13" min="2013-10-14" name="startDate">

If I wanted to change the year to 2013, the month is still set to April, which is not within the valid range specified.  So it prevents me from selecting the year.

**Comment by LaurentGoderre** [comment]
Hopefully we will have the new version out in a week or two

**Comment by hsrudnicki** [comment]
@muling @LaurentGoderre : Can this issue be closed?

**Comment by muling** [comment]
I assume the new version is out, but I haven't tested it.

**Comment by LaurentGoderre** [comment]
No it is not out yet. there are still a few issues to work out and unit tests to write

**Comment by hsrudnicki** [comment]
Made "Going Stale" to close this issue soon or otherwise? Either way, please update this issue's status, thank you
