### ISSUE TITLE
Input type="date" polyfill (date picker):more issues 

### ISSUE THREAD

**Issue by dfarough** [wet-boew/wet-boew#6690]
@wet-boew/access-working-group

I notice in the ARIA date picker document that the current date should get focus when tabbing to the Calendar Grid.  In our implementation the first day of the month gets the focus.  Would it not make sense to make the current date get the focus?  On the same issue, I think that if someone goes to the trouble of entering a date in the date text box and then uses the calendar to open the calendar, that the date previously entered should get the focus regardless of the current date.

I have also noticed that if I open Internet explorer in the restored state and bring up the calendar, that the whole calendar grid is not always visible on screen.  Can or should this issue be addressed?.

**Comment by LaurentGoderre** [comment]
In will be addressing those issues in the new version. However the last issue might be a browser bug, I will have to check.

**Comment by LaurentGoderre** [comment]
Related to #6744

**Comment by LaurentGoderre** [comment]
This was fixed by #6606
