### ISSUE TITLE
Lightbox: 

### ISSUE THREAD

**Issue by olegk1** [wet-boew/wet-boew#6691]
Hi guys: 
I've checked your Lightbox example. It works fine with my code when I use images to trigger lightbox. However, when I try to use text link instead for that trigger, it does work. Do you have some examples of your lightbox working with text link instead of images? 

Thanks.

**Comment by crichard** [comment]
This page has a few demos you can refer to: http://wet-boew.github.io/v4.0-ci/demos/lightbox/lightbox-en.html

**Comment by olegk1** [comment]
Thank you very much! I've checked that example too, but all I need is just a text link as a lightbox trigger, not a drop-down.

**Comment by crichard** [comment]
Just use the code in the if block that matches your case.
```
/* on click of your text link */
$("#link-id").on("click", function (){
    $document.trigger( "open.wb-lbx", [
			[
				{
					/*values here depend on what you want to display*/
                    src: "#inline_content",
					type: "inline"
				}
			]
		]);
});
```

**Comment by olegk1** [comment]
Sorry to bug you, it is still not clear to me. Let's say, I have a "foo.jpg" image that I want to use with lightbox. And I have text link 'show the lightbox". How would I make that function to trigger "foo.jpg" in the lightbox? Thanks!

**Comment by crichard** [comment]
It's quite simple.  See example below.

Here is your link in your html page:
```
<a id='link-id' href='#'>Link Here</a>
```

Here is your javascript:
```
$("#link-id").on("click", function (){
			$(document).trigger( "open.wb-lbx", [
					[
						{
							src: "foo.jpg", /* insert correct image path here */
							type: "image"
						}
					],
					false,
					[
						"Caption text here"
					]
				]);
		});
```

**Comment by olegk1** [comment]
Yes, that looks simple. I've copied your code as it is change image url to my image file, but as it is, it still doesn't work. Should  I add maybe "lightbox.min.js" link into head section? Do you have workable page just with that code?

**Comment by crichard** [comment]
Sure.  You can download a full example here: http://apps.multimediaservices.ca/web/demo.zip
You absolutely have to include the WET scripts in your page.

**Comment by olegk1** [comment]
OK, I got it! I needed to move lightbox JS code below jQuiry initialization code. Now it works with the text link. Thanks for your help and patience, Cynthia!

**Comment by LaurentGoderre** [comment]
@olegk1 if you are doing events, you don't need to wait for window.load. Your script after the otrher scripts though

**Comment by olegk1** [comment]
Thank you, Laurent!  Yes, you are right. The script works without "window.onload" wrapping as well.

**Comment by LaurentGoderre** [comment]
Can we close the issue then?

**Comment by olegk1** [comment]
Yes, please.
