### ISSUE TITLE
Question about object element text alternative

### ISSUE THREAD

**Issue by rlambert27** [wet-boew/wet-boew#6692]
Hello,

Just a quick discussion on the object element that is used in the templates. Our Compliance Sheriff is reporting an error on : 

OBJECT element does not have content that provides alternate description. 

Which is pointing to H53: http://www.w3.org/TR/WCAG20-TECHS/H53.html

H53 indicates:
Check that the body of each object element contains a text alternative for the object. 

The WET provides:

<a class="gl-FIP" href="/en/index.html"><object tabindex="-1" data="/v1.5.2/dist/assets/sig-blk-en.svg" type="image/svg+xml"></object><span class="wb-inv"> Government of Canada</span></a>

What is the reason for the <span> being outside the object element? I did find this issue #4699 but it says that aria-label would satisfy the requirement for WCAG conformance but I don't see the aria-label.

Thoughts?

Roch

**Comment by LaurentGoderre** [comment]
The problem is that the content of an object tag is not treated as a text alternative but as a fallback. That content is made available when the object tag can't load the content, which means that it doesn't work well as a text alternative when the object tag is used to load an SVG.

**Comment by rlambert27** [comment]
So if the browser can't load SVG files for any reason, the space at the top will simply be white with no alternative?

**Comment by LaurentGoderre** [comment]
It shouldn't because there is a polyfill that replaces it with an image if SVG can't be displayed.

**Comment by rlambert27** [comment]
Sounds good.

**Comment by LaurentGoderre** [comment]
You didn't need to close it, you can just update it

**Comment by rlambert27** [comment]
Update what?

**Comment by LaurentGoderre** [comment]
I got confused with your PR, nevermind
