### ISSUE TITLE
css styling form-group has-error has-feedback with glyphicon

### ISSUE THREAD

**Issue by pliz22** [wet-boew/wet-boew#6701]
I wanted to know if anyone had an idea to get the glyphicon to position within the input box without using full-width class on the input element.
with input class="full-width" the glyphicon is visually positioned in the textbox, but if i remove class="full-width", it is not.  if i remove the right:0px; then the glyphicon is positioned at the beginning of the text box which could be an alternative, but it is positioned on top of any text in the box.
i know in the documentation it says to play with right: 0px; to position it that way but it seems difficult to do for every input element?  is there a css such as... span.glyphicon:before.  or a right: inherit; or float:left; combination that i could use?  i tried a lot of them already but i'm just not smart enough.

**Comment by LaurentGoderre** [comment]
Can you add a mockup of what you are trying to do?

**Comment by pliz22** [comment]
![fullwidth](https://cloud.githubusercontent.com/assets/5824593/7204471/80bbec2a-e4f0-11e4-91f8-b3007a62783e.gif)
so the first one is what happens when the input box has "full-width" css class.  the second is when you remove it.  the third is what i want so no matter the width of the box the X will appear on the end of it.

**Comment by LaurentGoderre** [comment]
What does the icon mean? and error?

**Comment by pliz22** [comment]
http://wet-boew.github.io/wet-boew-styleguide/v4/design/forms-en.html#forms-control-states
under the heading with optional icons
anyway, this is what i came up with, seems clunky but at least it uses classes and no hard-code styling
```
<div class="row form-group has-error has-feedback" id="fnindgroup">
   <p class="mrgn-bttm-sm">
      <label for="fnind" id="fner" class="control-label">First name *</label>
   </p>
   <div class="col-xs-9 row">
      <input name="fnind" id="fnind" class="form-control full-width" type="text">
      <span class="glyphicon glyphicon-remove form-control-feedback mrgn-rght-md"></span>
   </div>
</div>
```

**Comment by LaurentGoderre** [comment]
@pliz22 that example may have some accessibility issues. It seems to be using an icon with no text alternative to indicate an error. Not to mention that it may be confused as a button for clearing the field as is present often on mobile devices.
