### ISSUE TITLE
Want pagination feature without table plugin

### ISSUE THREAD

**Issue by muling** [wet-boew/wet-boew#6704]
I would like to have the ability to add pagination to a list, but not necessarily want the overhead of using the WET table plugin.  If the list is large in nature (e.g. thumbnail images), then using the table plugin results in long load times.  The carousel would not be useful in this scenario because we want more than one image to be displayed at a time.

**Comment by LaurentGoderre** [comment]
I think a few people want something like this

**Comment by muling** [comment]
For this type of feature, it would be nice to be able to load only the content on the page selected and not load the entire list.

**Comment by LaurentGoderre** [comment]
Through ajax?

**Comment by muling** [comment]
Yes that is one option.

**Comment by LaurentGoderre** [comment]
Would you be able to start working on such feature and contribute it back?

**Comment by muling** [comment]
I don't know if I can commit any resources to this now since our WET4 project schedule is pretty tight.  I would need to speak to my manager about this.

**Comment by muling** [comment]
is there a git server we can hook in to without us having to install one?

**Comment by muling** [comment]
is there a git server we can hook in to without us having to install one?

**Comment by LaurentGoderre** [comment]
GitHub is a git server that you can use

**Comment by shawnthompson** [comment]
Doesn't SSC have a git server? I have the link at work, I can share it when I get there.

**Comment by shawnthompson** [comment]
[SSC Gitlab](http://gitlab.ssc.etg.gc.ca/)

**Comment by LaurentGoderre** [comment]
Please use GitHub for anything related to WET though

**Comment by hsrudnicki** [comment]
@muling @LaurentGoderre @shawnthompson : Can this issue be closed?

**Comment by hsrudnicki** [comment]
Made "Going Stale" to close this issue or otherwise?  Either way, please update this issue's status, thank you

**Comment by hsrudnicki** [comment]
Is this still an issue?  Please update this issue's status, whether this issue can be closed as resolved or if otherwise? Thank you

**Comment by muling** [comment]
You can close this.
