### ISSUE TITLE
Input type="date" polyfill (date picker): Can we redesign the calendar?

### ISSUE THREAD

**Issue by dfarough** [wet-boew/wet-boew#6705]
@wet-boew/access-working-group
I was looking at Bryan Garaventa's date picker, and it occurred to me that maybe we should redesign our date picker.  
http://whatsock.com/tsg/Coding%20Arena/ARIA%20Date%20Pickers/ARIA%20Date%20Picker%20(Basic)/demo.htm
With his date picker, focus moves immediately to the calendar grid and the cursor keys can be used to navigate the calendar.
Keyboard users need to use shift+tab to move out of the calendar to the buttons which appear above the grid to access the buttons to change year and month.   these buttons also have keyboard shortcuts assigned to them .

It seems to me that initial focus on the calendar grid makes sense.  The idea of tabbing in reverse to change the year or month is counter intuitive to me though which is why I am suggesting that maybe these buttons belong at the bottom underneath the calendar grid.

Is there some reason why we place focus initially at the top of the date picker making it necessary for keyboard users to tab several times in order to access the calendar grid?

I would expect that a majority of users would probably want only to specify a date within the current month.  Is there some metric which indicates that users expect to see these controls above the calendar grid?

I should also point out that his date picker does use the application role which causes screen readers to switch in to their application or focus mode automatically.

**Comment by LaurentGoderre** [comment]
It is redesigned right now. Can you wait to evaluate the new one instead?

**Comment by dfarough** [comment]
sure no problem.

**Comment by hsrudnicki** [comment]
@dfarough @LaurentGoderre : Can this issue be closed?
