### ISSUE TITLE
Default base map (CBM) attribution links are broken

### ISSUE THREAD

**Issue by bchagnon** [wet-boew/wet-boew#6707]
Broken links: 
 http://geogratis.gc.ca/geogratis/CBM_CBC?lang=en
 http://geogratis.gc.ca/geogratis/CBM_CBC?lang=fr
 
New links: 
 http://www.nrcan.gc.ca/earth-sciences/geography/topographic-information/free-data-geogratis/geogratis-web-services/17216#g3
 http://www.rncan.gc.ca/sciences-terre/geographie/information-topographique/donnees-gratuites-geogratis/services-web-geogratis/17294#g3

**Comment by LaurentGoderre** [comment]
@jvanulde please respond/investigate

**Comment by prushforth** [comment]
There is a typo in the french attribution hyperlink text: "©GéoGratis - Carte de Base du Canada" should be
"©GéoGratis - Carte de base du Canada" according to the (francophone) who reported the issue

**Comment by jvanulde** [comment]
Both are fixed in the i18n spreadsheet so they should be automagically added to the next build.

**Comment by bchagnon** [comment]
Good job ☺
--
Benoît
(613) 759-6829
560, rue Rochester, pièce 5-B6

**Comment by LaurentGoderre** [comment]
@jvanulde actually no...it's 90% automated but you still need to run `grunt update-i18n` and commit the results. I will take care of it for you.

**Comment by jvanulde** [comment]
Merci @LaurentGoderre

**Comment by LaurentGoderre** [comment]
THis should be resolved now. Can you test?

**Comment by jvanulde** [comment]
@LaurentGoderre it seems as though the data provider wants to change the target page. Please stand by for potential update.

**Comment by jvanulde** [comment]
@LaurentGoderre please revert. The old URI was reinstated. No change required for now.

**Comment by LaurentGoderre** [comment]
I can't revert because it may affect other strings. I can change it again if you update the spreadsheet again.

**Comment by jvanulde** [comment]
Spreadsheet updated.

**Comment by pjackson28** [comment]
PR #6805 includes the spreadsheet fixes.
