### ISSUE TITLE
Creating a PHP template

### ISSUE THREAD

**Issue by sbrioux** [wet-boew/wet-boew#6711]
Was wondering if you felt as though using tools like Grunt and such in order to create a PHP template of 3 of the WET themes would be a worth while venture?

**Comment by LaurentGoderre** [comment]
There is a PHP variant for WET

https://github.com/wet-boew/wet-boew-php

**Comment by sbrioux** [comment]
I had noticed that.  However, I didn't think it had been updated to WET 4.0.  As well I was wanting to use WET as a dependency within application as I build them and I don't have a need for all the template files that are provided.

**Comment by crochefort** [comment]
Good day @sbrioux just want to let you know yes we have a V4 available...

https://github.com/wet-boew/wet-boew-php/tree/v4.0

@upsonp might be able to answer your question on the php side if you want to close it here!

**Comment by hsrudnicki** [comment]
@sbrioux @upsonp @crochefort @LaurentGoderre : Are you ready to close this issue?

**Comment by LaurentGoderre** [comment]
Closing since there is a v4 version for the PHP variant
