### ISSUE TITLE
Run yo wet-boew-theme from the command prompt fails

### ISSUE THREAD

**Issue by KarinLau** [wet-boew/wet-boew#6713]
Hi,
I tried to follow the instructions on http://wet-boew.github.io/wet-boew/docs/start-en.html#implement
under “I want to customize WET and design a new WET theme“.
Point 5 “Run yo wet-boew-theme from the command prompt,..” didn’t work out.

As I didn’t know how I had to answer the question
[?] What license do you want to use? (MIT)
I first tried with “MIT” the second time I left it empty. (The other tries I took M, I and T).
All tries ended with failure:
...
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node build.js
npm ERR! You can get their info via:
npm ERR! npm owner ls node-sass
...

These are the logs for the first 2 tries:
https://gist.github.com/KarinLau/8444e64046005c503289#file-npm-debug_1sttry-log

As the error message suggested it to be a node-sass error I created an issue there in the first place:
https://github.com/sass/node-sass/issues/884

Could you help me?
Cheers,
Karin

**Comment by LaurentGoderre** [comment]
This is caused by a combination of factors that I have not yet fully grasped but normally you can run `yo generator-wet-boew-theme` until it fails, then run `grunt init` to restart where it failed and it generally fixes the problem.

**Comment by KarinLau** [comment]
Thanks for your answer. I tried it but it didn't work out. So I retried the whole 5 steps of the instruction again. There was a problem in step 3 then. I could fix it and proceeded again to the last 5th step. I got a new error that python was missing. So I also installed Python 3.4.3. My new error now looks like this:
'gyp ERR! configure error
gyp ERR! stack Error: spawn D:\Program Files (x86)\Python34 ENOENT
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
gyp ERR! stack     at child_process.js:1144:20
gyp ERR! stack     at process._tickCallback (node.js:355:11)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "D:\\Program Files (x86)\\nodeJS\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\KL\node_modules\grunt-sass\node_modules\node-sass
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
Build failed
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files (x86)\\nodeJS\\\\node.exe" "D:\\Program Files (x86)\\nodeJS\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! node-sass@0.9.3 install: `node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@0.9.3 install script 'node build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\KL\npm-debug.log'

I also tried the trick you already mentioned and just run 'grunt init' after it, and then running 'yo wet-boew-theme' again. But it isn't get better.
Do you have any ideas?

**Comment by LaurentGoderre** [comment]
@KarinLau, there is a regre4ssion issue with libsass (dependency of node-sass) which prevents us to upgrade to the newest version for the time being. The version we are using only have binaries for Node version 0.10. It does support Node 0.12 by compiling node-sass manually but that is very difficult to do.

For this reason, we recommend using Node version 0.10 for now.

http://www.nodejs.org/dist/v0.10.38/x64/node-v0.10.38-x64.msi
http://www.nodejs.org/dist/v0.10.38/node-v0.10.38-x86.msi

**Comment by KarinLau** [comment]
I started all over again with Node 0.12. No success.
My new error looks like this:

npm ERR! mytheme@4.0.12 postinstall: `bower update`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mytheme@4.0.12 postinstall script.
npm ERR! This is most likely a problem with the mytheme package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower update
npm ERR! You can get their info via:
npm ERR!     npm owner ls mytheme
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "D:\\Program Files (x86)\\nodejs\\\\node.exe" "D:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\KL
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\KL\npm-debug.log
npm ERR! not ok code 0

Guess I'm giving up.
Thanks for your help.

**Comment by LaurentGoderre** [comment]
@KarinLau it doesn't work well with Node 0.12, it needs to be node 0.10 for the time being

**Comment by LaurentGoderre** [comment]
Also, make sure you installed bower `npm install -g bower`

**Comment by KarinLau** [comment]
Sorry for the confusion. Of course I did take Node 0.10 (I mixed it up in my comment here)

C:\Users\KL>npm version
{ http_parser: '1.0',
  node: '0.10.38',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.36',
  zlib: '1.2.8',
  modules: '11',
  openssl: '1.0.1m',
  npm: '1.4.28',
  mytheme: '4.0.12' }

The bower installation I did with the command provided in the documentation:
npm install -g grunt-cli yo bower

**Comment by LaurentGoderre** [comment]
@KarinLau what happens if you try to run `bower update`?

**Comment by LaurentGoderre** [comment]
@KarinLau can you email me? laurent.goderre@gmail.com

**Comment by hsrudnicki** [comment]
@KarinLau @LaurentGoderre : Can this issue be closed?

**Comment by KarinLau** [comment]
@hsrudnicki  Yes, I think so.
