### ISSUE TITLE
Sorting in the table plug-in - links and capitalization making a difference

### ISSUE THREAD

**Issue by supertia** [wet-boew/wet-boew#6716]
I created a webpage containing the following table:

```
<table id="factsheets" class="table wb-tables table-condensed table-bordered table-striped table-hover">
	<thead>
		<tr>
			<th>Good/Service</th>
			<th>Supplier Name</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><a href="../factsheets/view.asp?id=21">Knowledge and Research Products</a></td>
			<td>Knowledge and</td>
		</tr>
	
		<tr>
			<td><a href="../factsheets/view.asp?id=19">KNOWLEDGE and Research Products</a></td>
			<td>KNOWLEDGE and</td>
		</tr>
	
		<tr>
			<td><a href="../factsheets/view.asp?id=20">Knowledge or Research Products</a></td>
			<td>Knowledge or</td>
		</tr>
	
		<tr>
			<td><a href="../factsheets/view.asp?id=18">KNOWLEDGE or Research Products</a></td>
			<td>KNOWLEDGE or</td>
		</tr>
	</tbody>
</table>
```

Expected results:
A) When I sort by the Good/Service column, the two "Knowledge and Research Products" items should appear before the two "Knowledge or Research Products" items, regardless of the capitalization.
B) When I sort by Supplier Name column, the two "Knowledge and Research Products" items should appear before the two "Knowledge or Research Products" items, regardless of the capitalization.

Actual results:
A) Same as the expected results. Which is actually a little surprising, since this is the column that contains the links. And I checked and the order it is sorting is not based on the id's contained in the links, as the actual results sort them as follows: id=19; id=21; id=18; id=20.
![table-test - link-containing-column is correct](https://cloud.githubusercontent.com/assets/12084610/7297996/a854188a-e99a-11e4-804f-bf14f5732b5c.png)

B) When I sort by Supplier Name, the two capitalized items appear before the two non-capitalized items.
![table-test - non-link-column is incorrect](https://cloud.githubusercontent.com/assets/12084610/7298004/b699e6f4-e99a-11e4-9bde-84002db2ecba.png)

**Comment by Linvalla** [comment]
Technically, this would be correct in the JS world.

Because K is not equal to k...

You'd have to override the sort to put everything in Uppercase to determine
sort order or change your data to match accordingly...  Case sensitivity is
key here...

**Comment by supertia** [comment]
I'm confused though: why is the sort order different for the two columns?

**Comment by pjackson28** [comment]
Perhaps it is because the two columns are different data types so may have different sort algorithms. The first column would be an HTML data type while the second column would be a text data type.

**Comment by hsrudnicki** [comment]
So, can this issue be closed?

**Comment by hsrudnicki** [comment]
Due to no further discussion/status updates, this issue made "Going Stale" to close this as resolved or if otherwise?  Either way, please keep this issue's status updated, thank you

**Comment by supertia** [comment]
I think that this is still an issue. But I don't personally have the time right not to work on resolving it though. I don't think that it is the right action to close an issue or mark it as resolved if it is not really resolved. But I'm not really sure how this project is supposed to work.

**Comment by hsrudnicki** [comment]
Has been this resolved or it's still an issue? Either way, please update this issue's status, whether this issue can be closed as resolved/fixed or if otherwise?  Thank you

**Comment by supertia** [comment]
I believe that this is still an issue, in which case it is not resolved/fixed.

I'm not sure how to update the status. The only option I see is the "Close and comment" button. Do you want me to close an issue that is not resolved?

**Comment by hsrudnicki** [comment]
It is not a must to close an unresolved issue unless @LaurentGoderre or/and  @masterbee agree to "won't fix" or other reason to close, anyway it's good to keep each issue's status updated, which prompts for more comments and support, thank you for keeping the status of this issue updated

**Comment by RobJohnston** [comment]
@supertia, I think there may be a remedy to your problem.  I see that DataTables has a `data-sort` and a `data-order` attribute for just this purpose.  See their page on [Orthogonal data](https://datatables.net/manual/data/orthogonal-data).

**Comment by hsrudnicki** [comment]
Can be this issue closed as resolved or otherwise? Please update the status of this for the current year, thank you

**Comment by supertia** [comment]
Thanks @RobJohnston. That does indeed resolve my problem. Thanks!
