### ISSUE TITLE
Delay with Feeds Widget

### ISSUE THREAD

**Issue by jbrousse** [wet-boew/wet-boew#6717]
Has anyone else noticed a delay when using the Feeds widget with the news.gc.ca feed? We've seen a delay of up to 30 minutes. I read issue <a href=https://github.com/wet-boew/wet-boew/issues/4860">#4860</a> where @pjackson28 indicates that the issue is likely caused by the Google Feed API. Given that Web Renewal will be using this widget to pull news items on institutional home pages, this delay could cause some issues moving forward. Is there a workaround that can be implemented to ensure the widget does not cache feeds for any period of time?

**Comment by Linvalla** [comment]
Assuming the feeds are ASYNC, and using jQUERY's AJAX Api, you can set a
global to not cache, and set the rest of your AJAX calls to cache at that
level...

Declare this in your JS:

$.ajaxSetup({ cache: false });

**Comment by jbrousse** [comment]
Thanks for the suggestion @Linvalla but this did not resolve the issue. I'm afraid there might not be a solution since it relies on Google's API, which seems to have been designed this way.

**Comment by LaurentGoderre** [comment]
Is this occurring on your work network or on a device outside the network? It could be your network interfering.

**Comment by jbrousse** [comment]
Tested on devices internally and externally. Issue is present on dev and prod servers. Tested from computers and smartphones. It occurs across the board. Added cache directives to both dev and prod servers but it did not change the behavior.

**Comment by hsrudnicki** [comment]
Are you ready to close this issue?

**Comment by jbrousse** [comment]
Yes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: hsrudnickiSent: Thursday, June 18, 2015 1:15 PMTo: wet-boew/wet-boewReply To: wet-boew/wet-boewCc: jbrousseSubject: Re: [wet-boew] Delay with Feeds Widget (#6717)Are you ready to close this issue?

—Reply to this email directly or view it on GitHub.
