### ISSUE TITLE
Multimedia Player - YouTube: French closed captions

### ISSUE THREAD

**Issue by nash0033** [wet-boew/wet-boew#6718]
The closed captions don't seem to be working on the French version of the youtube embed. Not even in the example provided here: http://wet-boew.github.io/wet-boew/demos/multimedia/multimedia-youtube-fr.html

**Comment by LaurentGoderre** [comment]
It was working before. Perhaps the API changed slightly, thanks for reporting it!

**Comment by bashour** [comment]
Can this be fixed for version V.4.0.13? as I am having the same issue.

**Comment by LaurentGoderre** [comment]
Unfortunately we don't backport fixes like these. Are you able to upgrade your version?

**Comment by bashour** [comment]
Not sure, as its not my call!
