### ISSUE TITLE
value of slider not returned

### ISSUE THREAD

**Issue by lbrissot** [wet-boew/wet-boew#6723]
I tried to use the proposed codes for the sliders from http://wet-boew.github.io/v4.0-ci/demos/slider/slider-fr.html and the "valeur actuelle", which is displayed on the demo, is not displayed on the copied page.
Do I need a complementary lib to get this returned value ?
Best regards, and anyway many thanks for this very useful program

**Comment by LaurentGoderre** [comment]
@lbrissot can you explain more in detail what you are doing? Note that if you just copied the page locally it probably won't work, you need a web server for it to work.

**Comment by lbrissot** [comment]
Hello, sorry for the delay, I was out of home for a week.
Here under is the code I am using with my localhost MAMP


<!DOCTYPE html >


<html>

<head>
<meta charset="utf-8">

</head>
<body>
<section>
<h3>Altitudes&#160;: -50 à 4000 m par pas de 200 <span id="html5shim-1-out"></span></h3>
<input name="html5shim-1" id="html5shim-1" type="range" min="-50" max="2000" step="200" title="Altitude : -50 à 4000 m par pas de 200" value="-50" />
<input name="html5shim-2" id="html5shim-2" type="range" min="200" max="4000" step="200" title="Altitude : -50 à 4000 m par pas de 200" value="200" />
</section>
</body>
</html>

This displays the cursor as on the example but when a cursor is moved, I do not see - as displayed on the example - "(valeur actuelle :  xx)"  xx being the value corresponding to cursor position.

My question is "How this value is returned to the display ?" PHP, javascript ? AJAX ?  ....?
Thanks by advance

**Comment by pjackson28** [comment]
@lbrissot That value is updated with the included demo JS, it is not part of the polyfill. You can repurpose that JS if you want, it can be found in demo/slider.min.js (or demo/slider.js). Here is the JS that is included in that file: 

```js
( function( $, document, wb ) {
"use strict";

var currentValueString = document.documentElement.lang === "fr" ?
		"Valeur actuelle&#160;:" :
		"Current Value:",
		$document = wb.doc,
		$slider;

$document.on( "change", "#html5shim-1, #html5shim-2", function( event ) {
	document
		.getElementById( event.target.id + "-out" )
			.innerHTML = "(" + currentValueString + " " + this.value + ")";
} );

$document.one( "timerpoke.wb", function() {
	$slider = $( "<input name='html5shim-3' id='html5shim-3' type='range' value='50'/>" );
	$slider.appendTo( "#slider-prg" ).trigger( "wb-init.wb-slider" );
	setTimeout( function() {
		$slider.get( 0 ).value = 85;
		$slider.trigger( "wb-update.wb-slider" );
	}, 2000 );
} );

} )( jQuery, document, wb );
```

**Comment by lbrissot** [comment]
Thanks for your help,

Nevertheless I did not succeeded getting this returned value, neither from a direct copy of the sent code (between <script> tags), nor from the add of a "slider.min.js" file copied in the same repository as the html file.
I am going to dig a little bit deeper to understand the code.

L.Brissot

**Comment by LaurentGoderre** [comment]
Do you have an example we can look at ?

**Comment by lbrissot** [comment]
Many thanks for your help.

I have put the files on my association's site
http://seaccueil.free.fr/SEA/fichiersGPX/curseur.html

as you can see I have inserted both the code sent by Paul Jackson from demo/slider/js, and the js file itself in the same repository ...SEA/fichiersGPX.

What is wrong ?

**Comment by pjackson28** [comment]
You are missing all the JS files required by WET, so an error is being thrown in the console saying that jQuery is not defined. For instance you are missing the reference to the jQuery JS file as well as wet-boew.min.js. You shouldn't be manually including slider.min.js and should instead let WET load it automatically. So I recommend that you use the WET template as is to start with.

**Comment by lbrissot** [comment]
Many thanks for your patience and help.
What was missing was indeed the load of the jQuery JS file.
I can now go ahead toward my goal of getting a selection of a range of elevations through dynamic cursors looking like that

Thanks again.

L.Brissot
