### ISSUE TITLE
Magnific Popup as Confirm dialog

### ISSUE THREAD

**Issue by GarthMartin** [wet-boew/wet-boew#6729]
I am trying to get magnific popup to function as a confirm dialog, returning true/false but am having issues with the callbacks.  Here is my initialization code:
```javascript
 wb.doc.trigger("open.wb-lbx", [
        [
        {
            src: '#ConfrimDeleteDialog',
            type: 'inline',
            callbacks: {
                open: function () {
                    console.log('Popup is opened');
                },
            }

        }],
        true
    ]
    );
```
I cannot get any callbacks to function, even with simple logging.  Am I missing something simple here?

I basically want to do something like this:
```javascript
function ConfirmAction() {
    var retVal;

    $('#ConfirmDeleteYesButton').click(function () {
        retVal = true;
    });

    $('#ConfirmDeleteNoButton').click(function () {
        retVal = false;
    });

    wb.doc.trigger("open.wb-lbx", [
        [
        {
            src: '#ConfrimDeleteDialog',
            type: 'inline',
            callbacks: {
                close: function () {
                    return retVal;
                },
            }

        }],
        true
    ]
    );
  }
```
Thanks,

**Comment by LaurentGoderre** [comment]
You shouldn't use events and callback at he same time. You should pick one and stick to it.

**Comment by LaurentGoderre** [comment]
The plugin doesn't support sending callbacks this way. You should use events instead

```javascript
wb.doc.on.on('mfpOpen', function(e /*, params */) {
  console.log('Popup opened',  $.magnificPopup.instance);
});
```

http://dimsemenov.com/plugins/magnific-popup/documentation.html#api

**Comment by GarthMartin** [comment]
I trust .on.on is a typo?  And when you say the plugin, you are referring to the WET implentation of magnific popup?  According to the api docs for magnific, callbacks are supported exactly in this fashion.

The way I read your suggestion, this would apply to all popups, no?  Or should I specify the selector as the second parameter in the .on() ?

Thanks,

**Comment by GarthMartin** [comment]
Is the plugin somehow returning true back to the caller?  I am trying to use the popup as a confirm dialog, basically "return ConfirmAction();" in the OnClientClick event of my button but the main OnClick event always fires before the dialog has a chance to return a value back.

**Comment by pjackson28** [comment]
Avoid using callback directly as WET uses some of those callbacks internally to implement accessibility fixes/enhancements. For instance the plugin uses the open, change and parseAjax callbacks so overriding them will affect the Lightbox functionality (likely wiping out some of the accessibility enhancements).

As for why you are not capturing the click, I suspect that it might be because your event handlers are being established before the buttons are in place. You should be applying the click handlers after an mfpOpen or mfpChange event and not on initialization as the buttons won't exist in the lightbox container before then (lightbox container remains empty until you open it).

**Comment by GarthMartin** [comment]
The issue is not necessarily that the click is not captured, more that the calling event does not wait for the return.  It gets a true immediately once the popup opens.  I will try chaning the order of events to see if that changes anything...

**Comment by pjackson28** [comment]
Could you please post your latest code? I'm assuming it is no longer the same as the code above.

**Comment by GarthMartin** [comment]
this is the current code:

```javascript
function ConfirmAction() {
   var retVal;
   wb.doc.trigger("open.wb-lbx", [
        [
        {
            src: '#ConfirmDeleteDialog',
            type: 'inline',
        }],
        true
    ]
    );

   wb.doc.on('mfpClose', "#ConfirmDeleteDialog", function (e) {
       return retVal;
       $magnificPopup.instance.close();
   });

   $('#ConfirmDeleteYesButton').click(function () {
       retVal = true;
   });

   $('#ConfirmDeleteNoButton').click(function () {
       retVal = false;
   });
}
```

As I mentioned, it is not the click event necessarily that is not being captured, it's the initial calling event (done as "return ConfirmAction();" in a OnClientClick event), automatically gets returned true and subsequently fires the button's OnClick event.

I suspect that the open method is returning true as soon as it succeeds.

**Comment by pjackson28** [comment]
You have nothing stopping ConfirmAction from returning right after it is called. What your function does is trigger an event, sets up three event handlers and then returns on it's own (implicit return). You may not explicitly be returning a value but it will return one anyway unless you stop it from doing so. The next steps should be taken as the result of handling an event (so the button click), and not the returning of a value from a sequential function.

**Comment by pjackson28** [comment]
So you could really simplify all this to something like the following:
```js
wb.doc.on( "click", "#ConfirmDeleteYesButton", function (e) {
       ... do something in response to a yes ...
});

wb.doc.on( "click", "#ConfirmDeleteNoButton", function (e) {
       ... do something in response to a no...
});
```

**Comment by GarthMartin** [comment]
Yes, I was thinking along the lines of another implementation where the action was a redirection as opposed to a return value.  I now realize what I am trying to do will not work this way!

Thanks Paul!
