### ISSUE TITLE
List

### ISSUE THREAD

**Issue by regagnon** [wet-boew/wet-boew#6732]
Good day

This concern the spacing in a list.

How do you create extra space between the items in a list?

Thanks

René

**Comment by Bgolden67** [comment]
unless it's changed, and i'm not aware, <ul class="lst-spcd"> will add spacing between your bullets

**Comment by thomasgohard** [comment]
@Bgolden67 you need to wrap any code sample with either single backticks (\`) for single line code samples or triple backticks (```) for multiline code samples.

**Comment by regagnon** [comment]
I don't understand what you are trying to tell me.
 
There's nothing on the site, all the list have the same spacing.
 
Am I permitted to create a css file that will allow me to have more
spaces between the list items?
 
René

>>> Brian Golden <notifications@github.com> 2015/04/29 8:22 AM >>>

unless it's changed, and i'm not aware, will add spacing between your
bullets

—
Reply to this email directly or view it on GitHub (
https://github.com/wet-boew/wet-boew/issues/6732#issuecomment-97406917
).



Ce courriel est destiné exclusivement au destinataire mentionné en titre
et peut contenir de l'information privilégiée, confidentielle ou
soustraite à la communication aux termes des lois applicables. Toute
divulgation non autorisée, toute reproduction ou réacheminement est
interdit. Si vous n'êtes pas le destinataire de ce courriel, ou n'êtes
pas autorisé par le destinataire visé, ou encore, si vous l'avez reçu
par erreur, veuillez le mentionner immédiatement à l'expéditeur et
supprimer le courriel et les copies.  

This e-mail message is intended for the named recipient(s) and may
contain information that is privileged, confidential and/or exempt from
disclosure under applicable law. Unauthorized disclosure, copying or
re-transmission is prohibited. If you are not a named recipient or not
authorized by the named recipient(s), or if you have received this
e-mail in error, then please notify the sender immediately and delete
the message and any copies.

**Comment by regagnon** [comment]
can you provide an example, please

 
Cheers
 
René Gagnon
>>> Thomas Gohard <notifications@github.com> 2015/04/29 9:06 AM >>>

@Bgolden67 ( https://github.com/Bgolden67 ) you need to wrap any code
sample with either single backticks (`) for single line code samples or
triple backticks (```) for multiline code samples.
—
Reply to this email directly or view it on GitHub (
https://github.com/wet-boew/wet-boew/issues/6732#issuecomment-97420405
).



Ce courriel est destiné exclusivement au destinataire mentionné en titre
et peut contenir de l'information privilégiée, confidentielle ou
soustraite à la communication aux termes des lois applicables. Toute
divulgation non autorisée, toute reproduction ou réacheminement est
interdit. Si vous n'êtes pas le destinataire de ce courriel, ou n'êtes
pas autorisé par le destinataire visé, ou encore, si vous l'avez reçu
par erreur, veuillez le mentionner immédiatement à l'expéditeur et
supprimer le courriel et les copies.  

This e-mail message is intended for the named recipient(s) and may
contain information that is privileged, confidential and/or exempt from
disclosure under applicable law. Unauthorized disclosure, copying or
re-transmission is prohibited. If you are not a named recipient or not
authorized by the named recipient(s), or if you have received this
e-mail in error, then please notify the sender immediately and delete
the message and any copies.

**Comment by sgdowney** [comment]
The style guide may provide some insight for you.
http://wet-boew.github.io/wet-boew-styleguide/v4/design/index-en.html
Under the Core Design Features the Margin Proximity may provide the spacing you need.

**Comment by Bgolden67** [comment]
@thomasgohard DOH! I forgot .. thanks for the reminder

'<ul class="lst-spcd">'

**Comment by regagnon** [comment]
what?
 
There's nothing here!

>>> Brian Golden <notifications@github.com> 2015/04/29 9:56 AM >>>

@thomasgohard ( https://github.com/thomasgohard ) DOH! I forgot ..
thanks for the reminder
''

—
Reply to this email directly or view it on GitHub (
https://github.com/wet-boew/wet-boew/issues/6732#issuecomment-97433565
).



Ce courriel est destiné exclusivement au destinataire mentionné en titre
et peut contenir de l'information privilégiée, confidentielle ou
soustraite à la communication aux termes des lois applicables. Toute
divulgation non autorisée, toute reproduction ou réacheminement est
interdit. Si vous n'êtes pas le destinataire de ce courriel, ou n'êtes
pas autorisé par le destinataire visé, ou encore, si vous l'avez reçu
par erreur, veuillez le mentionner immédiatement à l'expéditeur et
supprimer le courriel et les copies.  

This e-mail message is intended for the named recipient(s) and may
contain information that is privileged, confidential and/or exempt from
disclosure under applicable law. Unauthorized disclosure, copying or
re-transmission is prohibited. If you are not a named recipient or not
authorized by the named recipient(s), or if you have received this
e-mail in error, then please notify the sender immediately and delete
the message and any copies.

**Comment by thomasgohard** [comment]
@regagnon not sure why you're not seeing it. As @Bgolden67 stated, you have to add class `lst-spcd` to your list to increase the spacing between items.

**Comment by sgdowney** [comment]
@thomasgohard Is that documented somewhere?

**Comment by thomasgohard** [comment]
Only in the style guide issue tracker at this point from what I can tell: https://github.com/wet-boew/wet-boew-styleguide/issues/87.

I'll file an issue to add this to the style guide.

**Comment by thomasgohard** [comment]
Issue added as https://github.com/wet-boew/wet-boew-styleguide/issues/246.

**Comment by hsrudnicki** [comment]
Can this issue be closed?

**Comment by LaurentGoderre** [comment]
Closing since the remaining issue is being tracked int he style guide
