### ISSUE TITLE
opening lightbox from script with ajax fails

### ISSUE THREAD

**Issue by pvgenuchten** [wet-boew/wet-boew#6733]
As introduced in https://github.com/wet-boew/wet-boew/pull/6631, this seems to fail when you try to open the lightbox from script, see the ajax demo at the demo page http://wet-boew.github.io/wet-boew/demos/lightbox/lightbox-en.html

Can i suggest to change line 215 in src/plugins/lightbox/lightbox.js to: filter = (currItem.el)?currItem.el.data( "wbLbxFilter" ):undefined,

**Comment by LaurentGoderre** [comment]
All Ajax examples work for me.....they don't for you?

**Comment by LaurentGoderre** [comment]
Ok, I reproduced the problem. Thanks for submitting it!
