### ISSUE TITLE
AJAX caching in Internet Explorer

### ISSUE THREAD

**Issue by Christopher-O** [wet-boew/wet-boew#6735]
We just recently updated from WET 4.0.0 to WET 4.0.12.  In the previous template, we use the ajax to pull news items over from one page to our main homepage.  As these are time sensitive postings, we had noticed that for some people viewing the pages in Internet Explorer, that sometimes they would not see the updated content on the homepage, even though others could.  We discovered it seemed to be a cache issue with Internet Explorer.  No amount of Shift+F5 or clearing the cache would solve the issue.  The user would have to wait until Internet Explorer updated the cache file, which seemed that could take anywhere from 5 minutes to 5 hours.  I  found a solution by adding the following snippet into the wet-boew.min.js file, $.ajaxSetup({cache : false});   This solved the issue.  Since moving to the new template, the issues has arisen again, but when another webmaster placed the same snippet in the js file, it disabled the entire js file.   

We will look into trying to implement a fix but was wondering if there is a way to resolve this in a future version of WET.   The issue does not exist in Firefox (have not had the chance to test in other browsers), only Internet Explorer.  thank you.

**Comment by LaurentGoderre** [comment]
@Christopher-O You probably shouldn't disable caching for all browser because of an IE only bug.That syntax is discouraged because it affects the whole codebase. Have you narrowed down which version of IE are affected? Is IE11 affected as well? If we know which versions are affected, we can disable caching only for those versions of IE without affecting all other users (which are 90%+ of our users)

**Comment by LaurentGoderre** [comment]
Are you using the `data-ajax` or `ajax-fetch` plugin?

**Comment by Christopher-O** [comment]
95% of our userbase uses IE11 and it affects them.  It also existed in IE8 before they upgraded.  I am using the data-ajax (as I thought the fetch is only for the menus).   The strange thing is that it does not affect everyone equally across the country.  It seems that people in Ontario and Quebec see more of a delay of the content than people on the Western side (though alot of people in British Columbia seem to have the issue).  We have sent multiple inquiries to our IT departments, but they seem to have no idea on what may be causing the issue or how to solve it.   They do not believe it's a server issue.  I do not know if it's any setting in Internet Explorer, nor that I think it would be as all versions of IE11 rolled out have equal administrator settings.

**Comment by pjackson28** [comment]
First off, you should be using Ctrl+F5 to do a hard refresh and not Shift+F5. Also agreed that you should not be globally disabling AJAX caching, as that will mean larger page sizes across the board (e.g., since you will be redownloading the AJAXed-in menus every time).

Have you checked the cache settings in IE? Usually that is the cause because the automatic handling in IE is quite flaky (can be quite stubborn with caching). Check here:

Internet Options -> General (Tab) -> Browsing history (section) -> Settings (button) -> Temporary Internet Files (Tab) -> Check for newer version of stored pages (section)

If the "Automatically" option is selected then that may be your cause. It can get quite sticky with caching (and is frequently the culprit with caching headaches). "Every time I visit the webpage" tends to work much better. If that works then that is something that the IT department should be able to change through desktop profiles.

**Comment by Christopher-O** [comment]
Sorry, yes I meant Ctrl+F5, and that does not work either. Even when deleting their Temporary Internet Files, and clearing everything else, it still does not pull the newest AJAX data.  And yes, that option "Automatically" is selected (by administrator settings).  It is strange that even though it's across the board, some areas are affected and others are not.  I will have the team look into whether that change will be approved to be made.   It is definitely a scourge of IE with their cache issues (and from reading online, it seems to be the only browser that has real issues with it).

**Comment by LaurentGoderre** [comment]
Do you have an example page that is affected, it is possible to that IE may misuse caching direction and that some network based caching is in play here. I think the only way the geographic location matters is if it uses network based cache and perhaps IE is having an issue dealing with those.

**Comment by LaurentGoderre** [comment]
P.S. @Christopher-O data-ajax is not only for menu and you can use it to get content though ajax-fetch is more flexible and easier to use for dynamic use cases.

**Comment by Christopher-O** [comment]
I do, but unfortunately it's an intranet site, that I do not believe you have access to (do you have access to the CRA infozone site?).  I have rolled this up to my superiors to further investigate this, and I will inform them when asking IT to investigate the network and see if there are geographical differences in how the it's stored and sent to the browser.

**Comment by Christopher-O** [comment]
So I can use ajax-fetch for basic content as well (i.e. not the menu bar)?  I recall trying the ajax-fetch on a previous version of WET4 (4.0.0) and it did not work for me. I tried using it as a test for a menu bar and it worked fine, but just simply using it as a replacement for data-ajax-replace proved unsuccessful.

**Comment by LaurentGoderre** [comment]
It is working pretty well now with unit tests to prove it. I recommend using data-ajax to load content when the page loads and using ajax-fetch to load additional content after the page has loaded.

**Comment by Christopher-O** [comment]
You are correct, I just tested it and it does work as well as data-ajax-replace now.  I will suggest we try that out for a while to see if that makes any difference.  Thank you for the suggestion.

**Comment by LaurentGoderre** [comment]
@Christopher-O if you encounter a browser that has the issue, it would be nice to see the http headers for that browser and page (using the IE developers tools)

![ienetwork](https://cloud.githubusercontent.com/assets/1090826/7418724/fc84421a-ef3d-11e4-8e14-71ceafca3ac4.png)

**Comment by Christopher-O** [comment]
I can ask someone who I know has the issues to try and send me their data.  Is it just the response "HTTP/1. 1 200 OK" that you are looking for?  That is what I get, but again, I do not have the issue.

**Comment by LaurentGoderre** [comment]
No, it's all the other headers that are important.

**Comment by Christopher-O** [comment]
Here is what I get from the affected page.  I don't know if that has anything unusual.

**Comment by Christopher-O** [comment]
@LaurentGoderre  for some reason my browsers are not allowing me to upload images to Github, but here is the details from the Response Header tab from a user who was having these issues
Response: HTTP/1.1 200 OK
Cache-Control: private
Content-Length: 27902
Content-type: text/html
Server: Microsoft-IIS/7.0
IISExport: This web site was exported using IIS Export v4.2
X-Powered-By: ASP.NET
Date: Mon, 04 May 2015 14:50:31 GMT
X-RBT-Optimized-By: Y201WA01 (RiOS 8.0.1a) SC

**Comment by LaurentGoderre** [comment]
There is no caching headers, maybe IE is unpredictable because the caching behavior is not explicitly defined.

**Comment by shadeinc** [comment]
We have the same problem of caching in IE when using AJAX includes. Has there been a fix for IE implemented for this? Is there a plan to have one?
