### ISSUE TITLE
Tabbed Interface and Form Validation

### ISSUE THREAD

**Issue by GarthMartin** [wet-boew/wet-boew#6743]
I am using form validation on a tabbed interface.  I have included data-wb-frmvld='{"ignore": ""}' on the div surrounding my form so that all fields that are required get included in the validation.

While the validation fires for all fields as it should, however only the errors for the visible tab are displayed in the summary, and when I click on another tab that has errors, the summary does not get updated to reflect the errors on that tab until I click on one of the error messages.  Selecting the tab does not change the summary.

Are there any guidelines/documentation for using validation on a tabbed interface?

Thanks,

Garth

**Comment by LaurentGoderre** [comment]
The plugin was not designed to work this way. @ThomasGohard any issues with using tabs for a form from a usability point of view.

**Comment by GarthMartin** [comment]
@LaurentGoderre Sorry, when you say the plugin was not designed to work this way, are you referring to the tabbed interface or the form validation?

Thanks

**Comment by thomasgohard** [comment]
@GarthMartin do you have multiple forms in multiple tabs? Or one form across multiple tabs?

**Comment by GarthMartin** [comment]
@thomasgohard Single form across tabs.  I have placed the save/cancel buttons outside of the tab panels so visually the context implies a global save across all tabs.  

The context of the tab panels is consistent; a single business object, grouped into logical sections that represent a whole.  The intent is to reduce the need to vertically scroll during data entry.

A couple of the tabs have what I would call a sub-form, where users may add multiple items to a list (mailing addresses, phone numbers, email addresses) using buttons inside the individual tab so the visual context applies to the current tab (and the wording is crafted so the user knows they are not saving, rather adding/removing from a list).

Thanks,

Garth

**Comment by thomasgohard** [comment]
@GarthMartin what's the rationale for reducing the need to scroll vertically? What are you trying to achieve by that?

**Comment by GarthMartin** [comment]
@thomasgohard Is there an issue from an accessibility/usability perspective with trying to eliminate scrolling?  

I have found that most client's do not like excessively long forms for data entry and most business processes do not necessarily support a "stepped" or "flow" type data entry, it all needs to be available all the time, hence using tabs.

Garth

**Comment by LaurentGoderre** [comment]
I would imagine that this would confuse a lot of people doing it that way

**Comment by thomasgohard** [comment]
@GarthMartin using a tabbed interface likely will make the form less usable as it's a more complex interaction and user workflow. There are definitely better ways to deal with long forms (e.g., https://github.com/wet-boew/wet-boew/issues/6367).

**Comment by GarthMartin** [comment]
Thanks for all your insights.  We are looking at a different design.
