### ISSUE TITLE
Polyfill Date input shows incorrect date

### ISSUE THREAD

**Issue by jelofson** [wet-boew/wet-boew#6744]
The date input type polyfill shows the next day instead of the day selected in the input.
For example, go to your date picker example page. Select 2013-05-01 by using the calendar. The date in the form element will be correct. Now click the calendar again. Now, it will show 2013-05-02 selected instead of 01.

**Comment by jelofson** [comment]
Check line 224 in datepicker.js
targetDate.setDate( targetDate.getDate() + 1 );
If you remove the +1, it works as expected (for me anyway). Using FF 37, IE 10 64 bit.

**Comment by LaurentGoderre** [comment]
The polyfill is being rewritten. This will be addressed in the new version.

**Comment by hsrudnicki** [comment]
Can this issue be closed?

**Comment by dfarough** [comment]
Is there a point to closing issues like this if a new version of the date picker is coming?  I would think that these and other related tickets would be helpful when testing any new version of the date picker.

**Comment by LaurentGoderre** [comment]
No, they should remain open until the new version is merged
