### ISSUE TITLE
Form validation with checkbox and radiobutton names containing dollar signs

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/wet-boew#6747]
Here's how to test:
1.  Go to the [Form Validation](http://wet-boew.github.io/wet-boew/demos/formvalid/formvalid-en.html) example.
2.  Hit F12 to use developer tools and change the name of the checkboxes from "animal" to "ani$mal".
3. Click the submit button (and see the validation errors, as expected).
4. Do nothing more than click submit a second time (no validation and the form submits).

I would expect jQuery Validation to prevent the form from being submitted on the second click.

This sounds similar to #5018, but it only applies to checkboxes and radio buttons.  I thought wrapping the changes merged for that issue in the wb.jqEscape() function would help, but no.

Didn't see anything in the jQuery Validation issue queue about using dollar signs in names.  The docs there just say to wrap names in quotes if they contain strangeness like square brackets.  BTW, tested with square brackets  "ami[m]al" and stars "ani*mal" and they both work fine.

Why is this a problem?  When using .Net with WebForms and MasterPages, the controls get names like ctl00$contentPlaceHolder1$CheckBoxAnimal.

**Comment by LaurentGoderre** [comment]
@RobJohnston you shouldn't let .NET decide on your controls name but I agree this should probably be resolved

**Comment by RobJohnston** [comment]
One does have control over the ID of a control by using the [ClientIDMode property](https://msdn.microsoft.com/en-us/library/system.web.ui.control.clientidmode(v=vs.110).aspx) but not the name because the [Name property](https://msdn.microsoft.com/en-us/library/system.web.ui.htmlcontrols.htmlinputcontrol.name(v=vs.100).aspx) must have the same value as the Control.UniqueID property for most controls to work properly.  

It's the [UniqueID](https://msdn.microsoft.com/en-us/library/system.web.ui.control.uniqueid(v=vs.100).aspx) that includes the identifier for the server control's naming container (a placeholder on a master page in the case above).  That's where the dollar signs come from.  I can only change what is between the dollar signs.

**Comment by LaurentGoderre** [comment]
I really dislike out-of-the box ASP.NET and it's extreme bloat......It would be easier and way more optimize to use standard HTML5 and deal with the HTTP response rather than deal with all the non-sense .NET adds on.

**Comment by RobJohnston** [comment]
If I have time in July & August, I might create a MVC version for the wet-boew-dotnet project.  That may help to get people off of WebForms.

**Comment by LaurentGoderre** [comment]
I may be able to help with that if I have time. If you do, you should probably demonstrate how to separate the logic into an API.

**Comment by hsrudnicki** [comment]
@RobJohnston @LaurentGoderre : Based on the above maybe it's too early, but just by occasion, can this issue be closed or otherwise?

**Comment by RobJohnston** [comment]
Original issue hasn't had any work done on it (and neither has the follow-up conversation... yet!).

**Comment by RobJohnston** [comment]
Looks like this was fixed upstream:  https://github.com/jzaefferer/jquery-validation/issues/1331

**Comment by LaurentGoderre** [comment]
This fixed has not been released yet; 1.13.2 is in pre-release. When it comes out we can bump our version.

**Comment by RobJohnston** [comment]
@LaurentGoderre Version 1.14.0 came out and the fix was included in this version:  "Escape dollar sign in error id".

**Comment by RobJohnston** [comment]
Any chance of this making it into the release on Monday?  Seems simple enough.  See change log here:  https://github.com/jzaefferer/jquery-validation/releases/tag/1.14.0

**Comment by andre-gh** [comment]
Bumping that dependency is too high for for the super small fix release we are doing on Monday.

**Comment by RobJohnston** [comment]
This has just been fixed with WET 4.0.21, since it includes jQuery Validation 1.15.0.
