### ISSUE TITLE
How to start to use WET?

### ISSUE THREAD

**Issue by xunan-zhang** [wet-boew/wet-boew#6749]
Could you give me a link or brief how to use WET 2.0/4.0?
I browse the WET related web sites for a couple of days. I cannot find anywhere really introduce how to start a web site following WET standard.
1. what should I do if I already have a public web site and want to following WET 4.0?
2. should I download some lib files? where to download? Where Could I find how to use the libs?
3. Where are the reusable compoents? How could I use them?
4. I saw lots of .js files, which codes are in mess formats. How could I found the usage?

Thanks,

Zhang Xunan

**Comment by LaurentGoderre** [comment]
All the information is here http://wet-boew.github.io/wet-boew/index-en.html

Let us know if there is something specific you can't find

**Comment by xunan-zhang** [comment]
Hi Laurent, Thank you very much for the help. It seems I know some how to do it. 
The attached is one of our web page. Should we make the styles (color, font) and the formats (sizes, position) of the header, footer, menus, pictures and contents are exact the same?
In our page, there is a page header picture, is it acceptable?
Thanks again,
Carl Zhang 


     On Thursday, May 7, 2015 2:56 PM, Laurent Goderre <notifications@github.com> wrote:
   

 All the information is here http://wet-boew.github.io/wet-boew/index-en.htmlLet us know if there is something specific you can't find—

**Comment by xunan-zhang** [comment]
Sorry for forgeting attaching the file. Here is it. 


     On Thursday, May 7, 2015 8:20 PM, Xun an Zhang <zhangxunan@yahoo.ca> wrote:
   

 Hi Laurent, Thank you very much for the help. It seems I know some how to do it. 
The attached is one of our web page. Should we make the styles (color, font) and the formats (sizes, position) of the header, footer, menus, pictures and contents are exact the same?
In our page, there is a page header picture, is it acceptable?
Thanks again,
Carl Zhang 


     On Thursday, May 7, 2015 2:56 PM, Laurent Goderre <notifications@github.com> wrote:
   

 All the information is here http://wet-boew.github.io/wet-boew/index-en.htmlLet us know if there is something specific you can't find—

**Comment by LaurentGoderre** [comment]
@xunan-zhang it seems that email attachments don't work. Can you upload the image directly on GitHub?

**Comment by xunan-zhang** [comment]
![webpage](https://cloud.githubusercontent.com/assets/12301961/7552580/69e47e1c-f68a-11e4-8790-de160fca19c1.jpg)
Hi Laurent, 
I draged and Dropped. Could you see it now?

**Comment by LaurentGoderre** [comment]
@xunan-zhang I<m afarid it's not that easy. You will need to update your template to the GC Web Usability Theme and update your content to use Bootstrap. It's not a seemless transition form CLF2 to WET4

**Comment by xunan-zhang** [comment]
Got it. Thank you very much 


     On Monday, May 11, 2015 11:09 AM, Laurent Goderre <notifications@github.com> wrote:
   

 @xunan-zhang I<m afarid it's not that easy. You will need to update your template to the GC Web Usability Theme and update your content to use Bootstrap. It's not a seemless transition form CLF2 to WET4—

**Comment by xunan-zhang** [comment]
Hi Laurent,  Thanks for your patient. I have another question. I got the page of "GC Web Usability Theme" and its source code. I see some code like this"<script src="../../../dist/js/jquery.min.js"></script>
<link rel="icon" type="image/x-icon" href="../../../dist/theme-gcwu-fegc/images/favicon.ico" />
<link rel="stylesheet" href="../../../dist/grids/css/util-min.css" />
<link rel="stylesheet" href="../../../dist/js/css/pe-ap-min.css" />
<link rel="stylesheet" href="../../../dist/theme-gcwu-fegc/css/theme-min.css" />

<noscript><link rel="stylesheet" href="../../../dist/theme-gcwu-fegc/css/theme-ns-min.css" />
</noscript>"Where could I get these files:    jquery.min.js    util-min.css    pe-ap-min.css    theme-min.css    theme-ns-min.css I tried to go the the fold "../../../dist" from the website, but I failed. I download the release version   
| Government of Canada Web Usability | Download - v4.0.11 source code - Government of Canada Web Usability theme (theme only) | Download |

 from http://wet-boew.github.io/wet-boew/docs/versions/dwnld-en.html#v40devAnd upzip it. I cannot find these files inside it. Could you tell me where could I get them? Thanks, Carl Zhang

**Comment by xunan-zhang** [comment]
Sorry, I got wrong "GC Web Usability Theme" page. It is for 3.0.
Now I got new "GC Web Usability Theme" at
    http://wet-boew.github.io/wet-boew-jekyll/theme-gcwu-fegc/index-en.html
the .css and .js files are different. I can find most of them. But there still are some files cannot find
  such as: jquery.min.js, global.js

Is this web site of the "GC Web Usability Theme" the latest 'template'?

Thanks,

Carl Zhang

**Comment by LaurentGoderre** [comment]
In WET jQuery is loaded from the CDN so we don't package it. This download has everything you need to get started.

https://github.com/wet-boew/theme-gcwu-fegc/releases/download/v4.0.14/themes-dist-4.0.14-theme-gcwu-fegc.zip

From the following page:

http://wet-boew.github.io/wet-boew/docs/versions/dwnld-en.html

**Comment by xunan-zhang** [comment]
Hi Laurent,

I created template from "GC Web Usability Theme". It works. Thank you very much.

But I found an issue. Our existing system is using lots of JSF components. When I change <head> tag to <h:head>, all font inside <a> become obviously smaller. Do you know why? and how can we handle this? 

Thanks,

Carl Zhang

**Comment by LaurentGoderre** [comment]
That's weird, there are no selectors on the head tag. Why are you prefixing the head though?

**Comment by LaurentGoderre** [comment]
Actually, that prefix is not supposed to be present when the JSP is run

**Comment by xunan-zhang** [comment]
1. When I create a richfaces dropDownMenu, I use <rich:dropDownMenu>
and <rich:menuItem>. If the head is <head>, it does not work. If I change to <h:head>, the dropDownMenu works fine.

2. Our codes are in .xthml file.

3. When I use <h:head>, the font becomes smaller. Then I take the source code of the web page using Ctrl+U. And save it into an .xhtml file. Open it in browser again (such as IE, Firefox). the font comes back (become normal).

**Comment by LaurentGoderre** [comment]
Why are you using .xhtml? It should be.html since we are using HTML5.

**Comment by xunan-zhang** [comment]
Our system was developed many years ago. There are hundreds of .xhtml files. 

It seems we cannot simply change the extension names from .xhtml to .html.

Does HTML 5 support JSF, Richfaces, Primefaces...? We use lots of these technologies in our existing system.

Thanks,

Carl

**Comment by LaurentGoderre** [comment]
HTML supports it because it's just an output. What you could do instead of renaming them is changing the mime type for .xhtml to text/html

**Comment by johnpalaganas** [comment]
@xunan-zhang You can maintain the .xhtml extension and still have valid HTML5 code.

The latest JSF supports most if not all of HTML5 features. I would be careful with Primefaces as some of the code it renders does not meet accessibility guidelines or you may have to "hack" it to make modifications but its not the way to go. I would avoid those third party JSF frameworks if you can and stick to WET4 plugins.

**Comment by xunan-zhang** [comment]
Hi John,

Thank you for your reply. I have dropped Primefaces components. But still there are a few Richfaces components in our.xhtml files. Such as <rich:dropDownMenu> for our main menu bar, and <rich:panelMenu> for our left-panel menu. I have changed the font in top-bar menu to the same style of WET 4.0. but the font in <rich:panelMenu needs to update its classes with .js. Do we have .css in wet 4.0 to support this? 

In addition, how will we test whether our website is WET 4.0 compliance? Do we have any tool for it?

Thanks,

Carl

**Comment by LaurentGoderre** [comment]
Not sure I understand what the issue is.

**Comment by johnpalaganas** [comment]
Hi Carl,

I'm not using Richfaces at the moment so I can't comment on how to modify it. However, I did a quick Google on how rich:panelMenu renders. I would be looking for an alternative as rich:panelMenu component renders TABLES for layout purposes. This would not pass accessibility as it's not a tabular data.

I would consult your COE if Richfaces is exempt from your department, otherwise pick the closest WET4 component or seek an accessible alternative or make one from scratch but make sure it's accessible.

As for general compliance, make sure you use WET4 components and if its not currently available.
Seek an accessible alternative or make one from scratch but make sure it's accessible as well.

Cheers,
John

**Comment by xunan-zhang** [comment]
Hi Laurent,

They are 2 questions:

1. Whether we can use Richfaces: if we can, how do we set the font in 'rich:panelMenu' component because the font is obvious not the style of WET 4.0

2. After our website updated, how can we test if it meets completely WET 4.0 standard?

Thanks,

Carl

**Comment by xunan-zhang** [comment]
Hi John,

Thank you for your reply so quickly. I will think of replacing Richfaces components as many as possible. Does WET 4.0 support standard JSF? Will our website be WET 4.0 compliance if we use only standard JSF components in our website (no Richfaces, Primefaces, Myfaces, ...)

Another question: How do we test the accessibility, look and feel? In some codes, we have to use our own .css. such as layout.
   For LOOK, we inherit or copy WET 4.0 .css to our own .css files sometime
   How do we test FEEL, where can I find the instruction?

Thanks,

Carl

**Comment by johnpalaganas** [comment]
Hi Carl,

> Will our website be WET 4.0 compliance if we use only standard JSF components in our website (no Richfaces, Primefaces, Myfaces, ...)"

You will have to test all generic JSF components to be able to answer this.
Always assume no, anyways it's a good practice do a separate testing on the code it renders.

> Another question: How do we test the accessibility, look and feel? In some codes, we have to use our own .css. such as layout.

WET conforms to the Web Content Accessibility Guidelines (WCAG 2.0) Level AA. So make sure to test against that. Familiarize yourself with WCAG 2 http://www.w3.org/TR/WCAG20/ all WET4 components have gone through WCAG2 assessment so its best to use them, otherwise you will have to do thorough testing. Ask your COE for help.

Cheers,
John

**Comment by xunan-zhang** [comment]
Thanks, John. I will have a look at the WCAG2.0

**Comment by xunan-zhang** [comment]
Hi John,

1. The downloaded .css files of the WET4.0 include some pairs:
   theme.min.css              theme-coa.min.css
   theme-sp-pe.min.css    theme-sp-pe-coa.min.css
   theme-srv.min.css        theme-srv-coa.min.css
  What the -coa files for? how do I use them?

2. When I load the .css files into my template file(or web page), what the order is the best? It seems the order of files is matter.

3. Is there any website describe the .css files and .js files? And guideline to use them?

Thanks,

Carl

**Comment by xunan-zhang** [comment]
Hi John,

Could I have a technical question?

When I create my own horizontal menu and vertical menu to replace my "rich:dropDownMenu", and "rich:panelMenu". I reference the page:
   http://wet-boew.github.io/themes-dist/theme-gcwu-fegc/content-secmenu-en.html#
For the menu "Implement WET", before I move mouse onto the menu, I got the screen shot:

**Comment by xunan-zhang** [comment]
Hi John,

Could I have a technical question?

When I create my own horizontal menu and vertical menu to replace my "rich:dropDownMenu", and "rich:panelMenu". I reference the page:
http://wet-boew.github.io/themes-dist/theme-gcwu-fegc/content-secmenu-en.html#
 For the menu "Implement WET", before I move mouse onto the menu, I got the screen shot:
![wet_accessibility_inactive](https://cloud.githubusercontent.com/assets/12301961/8625542/7b05b4f0-270d-11e5-8185-486e7fa72b01.png)

When I move the mouse onto the "Implement WET" menu, I got another screen shot:
![wet_accessibility_active](https://cloud.githubusercontent.com/assets/12301961/8625575/a7b82e9c-270d-11e5-8f12-9ab9c56e9483.png)

1. Please note the red circles. How the mouse triggers the "active" "open" in the circles?
2. I take the codes into my own project. updated all paths correctly, But when I move the mouse onto the "Implement WET" menu. No drop down menuItems display
3. I used css hover and list implement my own horizontal menu and vertical menu. Both work fine. But I cannot see the "active", "open" status on my pages.

Could I ask what tech or tool is used in the "dropDownMenu" in the original code of the page?

Thanks,

Carl

**Comment by pjackson28** [comment]
@xunan-zhang The problem is you implemented yourself with CSS where the live one uses a combination of CSS and JS. You should be using what is provided through WET, implementing the prescribed HTML markup (and the WET CSS and JS), rather than building everything from scratch.

**Comment by johnpalaganas** [comment]
@xunan-zhang 

> The downloaded .css files of the WET4.0 include some pairs:
theme.min.css theme-coa.min.css
theme-sp-pe.min.css theme-sp-pe-coa.min.css
theme-srv.min.css theme-srv-coa.min.css
What the -coa files for? how do I use them?

There's really no need for you to know the specifics of those css files unless you're developing for WET. Use the WET template files as your basis then intergrate your own css and js files if needed.

> When I load the .css files into my template file(or web page), what the order is the best? It seems the order of files is matter.

Same answer as above.

> Is there any website describe the .css files and .js files? And guideline to use them?

If you need to know the css files as in what specific class does this, consult the WET4 Style Guide for a complete list of usable class or inspect a WET template with Firebug to fulfill your curiosity.

> 1. Please note the red circles. How the mouse triggers the "active" "open" in the circles?
> 2. I take the codes into my own project. updated all paths correctly, But when I move the mouse onto the "Implement WET" menu. No drop down menuItems display
> 3. I used css hover and list implement my own horizontal menu and vertical menu. Both work fine. But I cannot see the "active", "open" status on my pages.
Not sure if I understand your question but if you dont see a drop down menu when you hover on the menu, make sure you have the /ajax folder which contains the complete menu files (ex: sitemenu-en.xhtml)

Don't recreate anything from scratch but use the WET templates as the first basis.

**Comment by xunan-zhang** [comment]
Hi pjackson,

1. I open the source code of the page. I did not see any JS is included. Only a theme.min.css is included. This theme.min.css file is not the one we downloaded from wet4.0 website. It seems contains both theme.min.css and wet-bew.min.css

2. I tried to reused this page as our template. But I cannot make the dropDownMenu work. So I created my own.

Thanks,

Carl

**Comment by johnpalaganas** [comment]
The menu or aka MegaMenu is located here: http://wet-boew.github.io/v4.0-ci/demos/menu/menu-en.html

**Comment by xunan-zhang** [comment]
Hi John,

1. I did create my template from this page
   http://wet-boew.github.io/themes-dist/theme-gcwu-fegc/content-secmenu-en.html#
I believe I set the path/folder correctly. Other parts work fine. But the menu cannot drop down when I move the mouse onto it.

2. I put the "in-page html" code to replace my menu code. 
   2.1) And put menu-include-en.html into resources/ajax folder. And re-set the path. The mouse move on does not trigger the menu items
   2.2) And put ajax/menu-include-en.html in the same folder of my home page. It does not work either.
   2.3) The contents of menu-include-en.html is not loaded into page/template when mouse on

3. I downloaded and unzip the wet 4.0 onto my machine. I double click the file "contents.html", it displays in IE and/or FireFox. everything looks fine. But the mouse-onto-menu does not trigger to display its menu items

Thanks,

Carl

**Comment by pjackson28** [comment]
Make sure to run it on a web server. If you try to run it locally (by clicking on a file) then the sub-menus won't be ajaxed in due to cross-origin restrictions so won't show up on a hover.

As for the JS and CSS, you need to have wet-boew.min.css and theme.min.css loading successfully. If either are missing then the menu won't behave correctly. Note also that theme.min.css now incorporates wet-boew.min.css.

**Comment by xunan-zhang** [comment]
Hi Paul,

You are right. The ajax does not work. 
<nav

**Comment by xunan-zhang** [comment]
Hi Paul,

You are right. The ajax does not work. 
 <nav data-ajax-replace="/views/ajax/sitemenu-en.html ...> 
does not load the content into the page. so the 
 <li><a href="...&implement" does not load the sub menuItems /> </li>

I ran these on my local web server. All paths are set to local folders. There should no be cross-origin reference. I am working on why the ajax not working. If the problem sticky, I have to give it up and use my own menus.

Thanks you very much,

Carl

**Comment by LaurentGoderre** [comment]
Are you sure that the path is correct. If you open the developer tools and check the http request, try finding the one for the menu and try accessing it with your browser

**Comment by xunan-zhang** [comment]
Hi Laurent,

Here is an example I copied from wet 4 website (https://wet-boew.github.io/v4.0-ci/docs/ref/menu/menu-en.html). 
Menu: section 1    Section 2    Section 3 are displayed in a row. When I move mouse on one of them. No menu items display. I check the source code with Firebug. The code in 'ajax/menu-include-en.html' is not loaded in.

![menu](https://cloud.githubusercontent.com/assets/12301961/8675694/6ea57764-2a13-11e5-9e2c-e149db4e5cd9.png)

Could help have a look at what is wrong?

Thanks,

Carl

**Comment by pjackson28** [comment]
Are you sure ajax/menu-include-en.html is the correct relative URL? Shouldn't it also include "/e-services/" or some other part of the CSS URL as well? You are effectively telling the page to look for an ajax folder in the same directory as the page, and that folder contains menu-include-en.html. You should instead do server relative like you did for your CSS files.

**Comment by xunan-zhang** [comment]
Hi Paul,

Please refer to the red circles. 'ajax' folder and 'testMenu.html' are in the same folder 'views'. I also tried the full path '/e-services/views/ajax/...". I got the same result.

Are the 'data-ajax-fetch', 'data-ajax-insert', ... standard attributes of HTML 5.0? or is it created by WET 4.0 ? I did not find how and where it is triggered. I think I must miss some jar file, or .js file.

Thanks,

Carl

**Comment by LaurentGoderre** [comment]
In your web browser you should inspect the HTTP request (in the Network tab). Could you send a screenshot of that?

**Comment by pjackson28** [comment]
You should determine where the files actually get deployed. Figure out what is the actual URL of the deployed <code>menu-include-en.html</code> file and put that in the markup (make it server relative). All of the <code>data-ajax</code> attributes are from WET but you should be using <code>data-ajax-replace</code> instead of <code>data-ajax-fetch</code> (since <code>data-ajax-fetch</code> is deprecated).

**Comment by xunan-zhang** [comment]
Hi Laurent,

Are you mean this?
![ie network http](https://cloud.githubusercontent.com/assets/12301961/8677008/b8db9212-2a1a-11e5-96de-76aab3b9a2ed.png)

Thanks,

Carl

**Comment by LaurentGoderre** [comment]
Have you tried in another browser than IE?

**Comment by xunan-zhang** [comment]
Hi Paul,

The actual deployment on my local machine is the same structure as in Eclipse.

![e-services deployed](https://cloud.githubusercontent.com/assets/12301961/8677355/9f1b91fe-2a1c-11e5-8d83-a118d009c3af.png)

the 'data-ajax-fetch' is copied from wet 4.0. I tried 'data-ajax-replace'. The same thing.

Thanks

**Comment by xunan-zhang** [comment]
Yes. Firefox, IE 9.0, and Google Chrome.
All are the same

**Comment by johnpalaganas** [comment]
@xunan-zhang Can you access localhost:8080/e-services/ajax/menu-include-en.html on your browser?

**Comment by pjackson28** [comment]
WET v4.0 stopped using data-ajax-fetch a while ago so please switch exclusively to data-ajax-replace. As for why it is not working, I suggest using either Firefox + Firebug or Google Chrome to diagnose the issue. You should be looking to see what is the result of the request for "menu-include-en.html". If it is a 404 request then check what URL it is requesting and then correct the URL in the markup to generate the correct URL.

**Comment by xunan-zhang** [comment]
Hi John,
Yes. I can access http://localhost:8080/e-services/views/ajax/menu-include-en.html directly  it displays:     Section 1          Item 1.1     Section 2         .....
Thanks,
Carl 


     On Tuesday, July 14, 2015 11:56 AM, Paul Jackson <notifications@github.com> wrote:
   

 WET v4.0 stopped using data-ajax-fetch a while ago so please switch exclusively to data-ajax-replace. As for why it is not working, I suggest using either Firefox + Firebug or Google Chrome to diagnose the issue. You should be looking to see what is the result of the request for "menu-include-en.html". If it is a 404 request then check what URL it is requesting and then correct the URL in the markup to generate the correct URL.—

**Comment by pjackson28** [comment]
Do you get any JavaScript errors in the error console? The two most common reasons for this not working are either a 404 for the requested file or a JavaScript error that interferes with the building of the menu. A less common one is network/browser restrictions blocking the AJAX request, even on a web server (seems to be pretty rare though).

**Comment by xunan-zhang** [comment]
Hi Paul,

1. Where are the ajax-data attributes interpreted when running? 
2. There is no any error or javascript error in console box.
3. One 404 error was the .css name wrong. should be theme.min.css, I wrote into theme-min.css. Has corrected. Still not work. One more 404 remained for "/favicon.ico". Don't know where it comes from. I deleted all favicon.ico from my project source codes. It still comes
4. I other pages are using JSF ajax. It works fine

Thanks,

Carl

**Comment by pjackson28** [comment]
Looking at your network traffic, I don't see wet-boew.min.js anywhere so if it is not being downloaded then nothing JS-related in WET will work (since that is all the JS for all WET plugins, including the menu plugin). So I suggest figuring out why it is not showing up in the network traffic. Perhaps that script reference wasn't added to end of the body tag?

1. The data-ajax attributes are handled by wet-boew.min.js which seems to be absent from your network traffic.
2. Since none of the WET JS seems to be loaded then that would likely explain why.
3. The incorrect CSS URL would certainly have been a contributing factor, but not as big as the absent wet-boew.min.js. As for the favicon.ico, you should not be removing that from your source code. You should be replicating the HTML markup specified by WET and not picking and choosing what to include. For any acceptance testing you should be comparing the HTML markup output from your application with the HTML markup specified by WET, correcting any differences. It looks like the majority of issues you have encountered are because of differences in the markup you are generating and what is required by WET.
4. Good to know that you don't have that issue as it can create a lot of problems.

**Comment by johnpalaganas** [comment]
Dude, you're missing some javascript files in order to run the drop down menu.

Where is wet-boew.min.js???

It's best if you run a page using one of the WET4 templates as it will have all the necessary links to the required javascript and css files.

**Comment by xunan-zhang** [comment]
Hi John,

1. Actually, I have put the wet-boew.min.js into the source codes of testMenu.html after screen shot
It is at /e-services/resource/js/wet4.0/wet-boew.min.js. and also 
          /e-services/resource/js/wet4.0/ie8-wet-boew2.min.js
          /e-services/resource/js/wet4.0/theme.min.js
It does not work either.

2. I did create my template from a wet 4.0 theme page. The theme page works in IE. After I adapted to local and updated the path. It does not work anymore.

Thanks,

Carl

**Comment by pjackson28** [comment]
@xunan-zhang Is wet-boew.min.js showing up in your network traffic now? In the images you've attached to the thread, it is not included in the network traffic, not even a failed request. Could you post an updated image for the network traffic? I also suggest checking the network traffic with something other than IE as it is a pretty poor network tool in comparison to what is available on other browsers.

**Comment by pjackson28** [comment]
Please also post the markup snippit where you include the JS files as that could also offer clues as to what is going wrong.

**Comment by xunan-zhang** [comment]
Hi Paul,

Here are the source code and the traffic result.
![e-services markup snippit](https://cloud.githubusercontent.com/assets/12301961/8681594/7779dc18-2a36-11e5-90b1-9507bbcd6bbf.png)
![e-services network trafic](https://cloud.githubusercontent.com/assets/12301961/8681596/7d14070c-2a36-11e5-926f-1c29a03f26da.png)

It is strange. don't know where is the 'xxyy' comes from. If put the <script> in <head> </head>. No xxyy

Thanks,

Carl

**Comment by pjackson28** [comment]
Your script references are in the wrong location. You have them outside of the body element and are missing the conditional comments, etc. Please replicate how they are referenced in the WET templates. You should be doing a side-by-side comparison between your markup and the WET template markup to make sure the only differences are the URLs and the content. Nothing else should be different in your generated HTML, including for any of the tags.

**Comment by pjackson28** [comment]
Note the xxyy is because Modernizr has executed the MathML browser support test but the WET JS has not executed so hasn't had a chance to clean up the test artifacts. You should check in the error console again to make sure there are no errors (likely related to the script references being in the wrong location in the DOM).

**Comment by LaurentGoderre** [comment]
Actually the xxyy is a sign that jQuery didn't load. I don't see it in your screenshot. Did you remove the references to it?

**Comment by xunan-zhang** [comment]
Thank goodness. It works now.

1. I re-take the page:
http://wet-boew.github.io/themes-dist/theme-gcwu-fegc/content-secmenu-en.html
Keep all the contents except for updating the folders.

2. I keep the 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.js"></script>

The sub-menu items appears now finally

Thanks for Laurent, Paul and John. Very appreciate your help.

I will replace the contents one-by-one tomorrow.

Thanks again,

Carl

**Comment by xunan-zhang** [comment]
Hi Laurent, Paul, and John,

A question again.

   I try to replace the WET 4.0 menu with my own menus. I cannot clean up the WET 4.0 menu/menu items. How to clean them up?

My code is:
   \<nav role="navigation" id="wb-sm" data-ajax-replace="/e-services/views/ajax/sitemenu-en.html" data-trgt="mb-pnl" class="wb-menu visible-md visible-lg" typeof="SiteNavigationElement">
\</nav>

when 'ajax/sitemenu-en.html' was loaded first time. Any updates late in the file does not affect the original menu/menu items. Even I delete the file and 'ajax' folder. System still display original menu, menu items

Thanks,

Carl

**Comment by pjackson28** [comment]
The menu bar needs to be changed both in the page and in the AJAXed in menu. The menu bar is specified twice to provide a fallback for when JS is disabled.
