### ISSUE TITLE
Geomap prevents definition of layer options on WMS basemap layer

### ISSUE THREAD

**Issue by jfbourgon** [wet-boew/wet-boew#6750]
According the the online documentation http://wet-boew.github.io/wet-boew/docs/ref/geomap/geomap-en.html (see Basemap configuration example), it should be possible to define layer options such as `singleTile: true` or `opacity: 0.5` on a WMS basemap layer.

However current geomap-lib codebase prevents doing this because the layer options object is hardcoded to `isBaseLayer: true` and connot be extended
```javascript
if ( hasBasemap ) {
    if ( basemap.type === "wms" ) {
        keys = getLayerKeys( basemap );
        geomap.map.addLayer(
            new OpenLayers.Layer.WMS(
                basemap.title,
                basemap.url,
                keys,
                {
                    isBaseLayer: true
                }
            )
        );
```

Following proposed code would allow definition of layer options on a WMS basemap layer.
```javascript
if ( hasBasemap ) {
    if ( basemap.type === "wms" ) {
        keys = getLayerKeys( basemap );
        layerOptions = keys['options'];
        layerOptions.isBaseLayer = true;
        geomap.map.addLayer(
            new OpenLayers.Layer.WMS(
                basemap.title,
                basemap.url,
                keys,
                layerOptions
            )
        );
```

**Comment by LaurentGoderre** [comment]
@jvanulde please respond

**Comment by jvanulde** [comment]
@jfbourgon have you tried putting your configuration in the "options" parameter? It should get added as part of the keys array.

**Comment by jfbourgon** [comment]
Yes but it doesn’t work since the options parameter is being ignored when the OL layer object is created.

The proposed patch works as expected using the options parameter.

**Comment by jvanulde** [comment]
The code is working for the WMS sample map in the demo. This is the configuration:

    basemap: {
		title: "WMS-Toporama",
		type: "wms",
		url: "http://wms.ess-ws.nrcan.gc.ca/wms/toporama_en",
		version: "1.1.1",
		format: "image/png",
		layers: "limits",
		mapOptions: {
			maxExtent: "-2650000.0, -900000.0, 3600000.0, 4630000.0",
			restrictedExtent: "-2750000.0, -1000000.0, 3700000.0, 4730000.0",
			maxResolution: "auto",
			projection: "EPSG:3978",
			units: "m",
			displayProjection: "EPSG:4269",
			aspectRatio: 0.8
		}
	}

Everything in mapOptions is passed into the layer constructor.

**Comment by jvanulde** [comment]
@jfbourgon I think I see the issue now. Sorry, I was looking at the wrong parameter. Can you send an example configuration that you are trying to get working so I can test the patch.

**Comment by hsrudnicki** [comment]
@jfbourgon @jvanulde @LaurentGoderre : Can this issue be closed?

**Comment by jvanulde** [comment]
We can close this.

**Comment by josegar74** [comment]
I have tried in version 4.0.21, with the following configuration:
```
 var wet_boew_geomap={basemap : {	
				title: 'CBMT',
				type: 'wms',
				url: 'http://maps.geogratis.gc.ca/wms/CBMT',
				layers: 'CBMT',
				format: 'image/png',
				version: '1.1.1',
				options: { singleTile: true, ratio: 1.0, projection: 'EPSG:4326' },
				mapOptions: {
					maxExtent: '-141,41,-52,84',			
					maxResolution: 'auto',
					projection: 'EPSG:4326',
					restrictedExtent: '-141,41,-52,84',
					units: 'd',
					numZoomLevels: 12,
					displayProjection:"EPSG:4326",
					aspectRatio:.8
				}
			},overlays:[]};
```

, but seem not taking in account using the `singleTile`. See the following image with labeling issues due to not using the singleTile option:

![map](https://cloud.githubusercontent.com/assets/1695003/15385806/43b3b4b4-1da4-11e6-8c3b-4cf53f2ed273.png)

Or I'm doing something wrong?

**Comment by jvanulde** [comment]
Have you tried setting singleTile in mapOptions? It should work. Also, is there a reason why you need to use the WMS service of the default base layer which is optimally served using ESRI REST?

**Comment by josegar74** [comment]
I have tried to setup `singleTile: true` in the `mapOptions`, but no success.

About the reason to use WMS, is to use 4326 projection so can use the map current extent coordinates for filtering metadata that is georeferenced in this projection. Not sure if the ESRI REST service provides support for 4326 projection?

**Comment by jvanulde** [comment]
I don't know why that doesn't work. It should. Can you file a bug please. In any case Geomap will project your extent coordinates for you as per the image below:

![screen shot 2016-05-25 at 5 26 59 am](https://cloud.githubusercontent.com/assets/2255248/15539841/9fa40eba-2239-11e6-8769-e6004c2cefa2.png)

**Comment by josegar74** [comment]
Will check the WMTS option. 

I created also this specific issue #7561
