### ISSUE TITLE
Highlighting a secondary menu

### ISSUE THREAD

**Issue by GarthMartin** [wet-boew/wet-boew#6755]
What is the recommended way of highlighting the current location in a secondary (left) menu?

Given the following:

```html
<nav role="navigation" id="wb-sec" typeof="SiteNavigationElement" class="col-md-3 col-md-pull-9 visible-md visible-lg">
    <h2><%=SectionMenu %></h2>
    <ul class="list-group menu list-unstyled">
        <li>
            <h3 class="wb-navcurr"><%=MenuHeader %></h3>
            <ul class="list-group menu list-unstyled">
                <li><a class="list-group-item" href="/page1">Page1</a></li>
                <li><a class="list-group-item" href="/page2">Page2</a></li>
                <li><a class="list-group-item" href="/page3">Page3</a></li>
                <li><a class="list-group-item" href="/page4">Page4</a></li>
            </ul>
        </li>
    </ul>
</nav>
```

what should be styled - the li or the link, (and with which class) to have the li highlighted when it is the current page?  I am intending to control the current page indicator in code.

I have tried using "list-group-item-info" and "active" to no success.  Well "active" gives me a border, but I was thinking more in line of the background color changing.

Thanks,

**Comment by thomasgohard** [comment]
I believe it's `wb-navcurr` on the `a` element.

**Comment by pjackson28** [comment]
Note that there is a plugin in WET for applying the class automatically. It is in use by the menu bar and normally works on the side menu (matches the link href against the page URL and the breadcrumb hrefs).

**Comment by GarthMartin** [comment]
@pjackson28 That's what I thought, but it does not seem to be working properly.  How exactly does the plugin work?  Is there some documentation somewhere?

**Comment by zachfalsetto** [comment]
https://github.com/wet-boew/wet-boew-styleguide/pull/247
Documentation is in the works

**Comment by pjackson28** [comment]
@GarthMartin The wb-navcurr plugin is automatically triggered by the menu plugin when the following two conditions are met:
1. The side menu container has <code>id="#wb-sec"</code>
2. An element with <code>class="wb-navcurr'</code> does not exist within the side menu container.

**Comment by GarthMartin** [comment]
@pjackson28 So if I use the sample provided in the 4.0.12 dist download package, where the h3 tag in the first list has wb-navcurr, does that mean that the plugin will not work because an element already has wb-navcurr?  

Note that this appears to be different than the code used in the online example:

http://wet-boew.github.io/themes-dist/theme-gcwu-fegc/content-secmenu-en.html

```html
<nav role="navigation" id="wb-sec" typeof="SiteNavigationElement" class="col-md-3 col-md-pull-9 visible-md visible-lg">
                <h2>Section menu</h2>
                <ul class="list-group menu list-unstyled">
                    <li>
                        <h3 class="wb-navcurr">Content page - Secondary menu</h3>
                        <ul class="list-group menu list-unstyled">
                            <li><a class="list-group-item" href="#">Item&#32;1</a></li>
                            <li><a class="list-group-item" href="#">Item&#32;2</a></li>
                            <li><a class="list-group-item" href="#">Item&#32;3</a></li>
                            <li><a class="list-group-item" href="#">Item&#32;4</a></li>
                            <li><a class="list-group-item" href="#">Item&#32;5</a></li>
                            <li><a class="list-group-item" href="#">Item&#32;6</a></li>
                            <li><a class="list-group-item" href="#">Item&#32;7</a></li>
                            <li><a class="list-group-item" href="#">Item&#32;8</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
```

**Comment by LaurentGoderre** [comment]
@GarthMartin if you remove the `nav-current`, the plugin will add it for you automatically

**Comment by GarthMartin** [comment]
@LaurentGoderre Thanks, that worked.
