### ISSUE TITLE
Documentation - Lightbox - Events - mfp events

### ISSUE THREAD

**Issue by sebastienHubert** [wet-boew/wet-boew#6759]
Hi, I've been working with the lightbox plugin and noticed that in the lightbox documentation for mfp events, there seems to be an error in the code snippets included. Please see attached image for specific portion.

![lightboxdocumentationsnapshot](https://cloud.githubusercontent.com/assets/11776025/7573511/317ea0aa-f7f4-11e4-8f65-1178db39196d.PNG)

I believe that portion should instead be the following:
- $.magnificPopup.instance.items[ 0 ].src;

Just thought I'd share.

**Comment by pjackson28** [comment]
@sebastienHubert Looks like you are correct. Thanks for catching that. Would you be interested in submitting a PR to fix it?

**Comment by sebastienHubert** [comment]
It would be my first time, so I’m not exaclty how I’d go about doing that, but I can give it a try.

**Comment by LaurentGoderre** [comment]
Let mw know if you need any help with creating it

**Comment by sebastienHubert** [comment]
Hi Laurent, Paul, I've been busy, and I think I've confirmed that I do not yet have the proper tooling to be able to perform this kind of task, or at least, not all developers at CRA can. There's something in the pipeline, called GCGit I think, but it's no here yet. Hopefully that makes sense to you. 

So at this point, I'm not sure if it's worth waiting for me to be able to do this myself since it could take a while for the tooling to be available, it's in something akin to a certification process at the moment.

**Comment by pjackson28** [comment]
No problem. Will be fixed by PR #6814.

**Comment by sebastienHubert** [comment]
Can I say that was quick...I'm ready to close whenever you are.

**Comment by hsrudnicki** [comment]
So again, based on the above, can this issue be closed?
