### ISSUE TITLE
Grouped toggle default state not working

### ISSUE THREAD

**Issue by vallieresc** [wet-boew/wet-boew#6764]
I am implementing tabbed sections and if I set "state: on" it will not load the tab and its content opened. I must absolutely set the css class on on the toggled content to have it visible on load.

My code:
```html
<div class="tabpanel">
	<div class="btn-group">
		<button type="button" class="btn btn-default wb-toggle" data-toggle='{"selector": "#toggle4", "group": ".grouped", "type": "on", "state": "on"}' aria-controls="toggle4">Example 4</button>
		<button type="button" class="btn btn-default wb-toggle" data-toggle='{"selector": "#toggle5", "group": ".grouped", "type": "on", "state": "off"}' aria-controls="toggle5">Example 5</button>
		<button type="button" class="btn btn-default wb-toggle" data-toggle='{"selector": "#toggle6", "group": ".grouped", "type": "on", "state": "off"}' aria-controls="toggle6">Example 6</button>
	</div>
	<div class="row">
		<div id="toggle4" class="grouped on">Toggle4</div>
		<div id="toggle5" class="grouped off">Toggle5</div>
		<div id="toggle6" class="grouped off">Toggle6</div>
	</div>
</div>
```

**Comment by vallieresc** [comment]
I also believe it should be possible to deprecate that group property and instead implement a surrounding div with a .tabpanel class name. All divs inside this .tabpanel would be part of the "group".

**Comment by pjackson28** [comment]
The state property is not for setting the initial state of the items to be toggled, it is for setting the initial state of a toggle button. So if you set the state of a button to be on, then the first button press will issue an off (irrespective of the actual state of the items to be toggled). So yes you need to set the initial CSS on the items to be toggled.
