### ISSUE TITLE
Group toggle not working divs

### ISSUE THREAD

**Issue by vallieresc** [wet-boew/wet-boew#6765]
I am trying to setup grouped toggle but the buttons disappear after a few clicks and divs do not toggle.

I tried a few group/parent combinations but it doesn't work.

It's possible that more than one of these be found on a page. Will it cause a conflict if the parent class is the same for all?

```html
<div class="tabpanel">
	<ul class="nav nav-tabs">
	   <li role="presentation">
			<a href="#SimpleControls-section-content" class="btn btn-default wb-toggle" data-toggle='{"selector": "#SimpleControls-section-content", "group": ".tab-content .section-content", "parent": ".tabpanel" "type": "on"}' aria-controls="SimpleControls" role="tab">Inputs</a>
	   </li>
	   <li role="presentation">
			<a href="#SpecialControls-section-content" class="btn btn-default wb-toggle" data-toggle='{"selector": "#SpecialControls-section-content", "group": ".tab-content .section-content", "parent": ".tabpanel" "type": "on"}' aria-controls="SpecialControls" role="tab">Test</a>
	   </li>
	</ul>
	<div class="tab-content">
	   <div role="tabpanel" id="SimpleControls-section-content" class="section-content on">
		  test1
	   </div>
	   <div role="tabpanel" id="SpecialControls-section-content" class="section-content off">
		  test2
	   </div>
	</div>
 </div>
```

**Comment by pjackson28** [comment]
What are you trying to achieve? It looks like you are trying to fake a nested tabbed interface using toggle. If you are trying to nest tabbed interfaces then don't use toggle for that purpose, use actual tabbed interfaces for the nesting (although there are likely usability issues with nesting in the first place).

**Comment by vallieresc** [comment]
I only want to toggle the .section-content divs. tab-content is only the parent. I was previously attempting to implement the Bootstrap toggle plugin but didn't work.

**Comment by pjackson28** [comment]
Are you trying to show one section at a time or multiple sections at a time? What is the intended behaviour? Also you need to be very careful with using the role attribute (from WAI-ARIA). as misuse can have negative consequences for screen reader users (for instance declaring something asa tabpanel when it actually isn't).

**Comment by vallieresc** [comment]
My scenario is very simple, I'm trying to have 1 section (.section-content) show at a time and don't want any conflict with other tab groups I might have further in my page.

The aria attribute is copied from bootstrap.

**Comment by pjackson28** [comment]
That sounds like a normal tabbed interface or an accordion. You should just use the WET tabbed interface or toggle accordion as is (you shouldn't be using the Bootstrap equivalents).

**Comment by vallieresc** [comment]
I am not using bootstrap anymore but I'm having a hard time getting your grouped toggle to work with my code. What am I doing wrong?

**Comment by pjackson28** [comment]
It would be much easier if you just switch to the default tabbed interface or toggle accordion markup rather than trying to emulate that behaviour through a group toggle (and potential introducing accessibility issues). Is there a reason why you can't use the tabbed interface or toggle accordion? Those two solutions have been extensively tested and don't require customization to get working.

**Comment by vallieresc** [comment]
ah! I wasn't aware of the tabbed interface. I thought the grouped toggle was it.
