### ISSUE TITLE
Update grunt-sass (maybe)

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/wet-boew#6770]
Libsass resolved the bug that was preventing us to move to the new version and node-sass 3.1.0 includes that version. Just need tro see if grunt-sass supports it now.

/cc @nschonni

**Comment by LaurentGoderre** [comment]
@EricDunsworth @rlambert27 when this is done, you will be able to upgrade back to Node v0.12

**Comment by EricDunsworth** [comment]
@LaurentGoderre Awesome, thanks :)!

**Comment by hsrudnicki** [comment]
@EricDunsworth @rlambert27 @LaurentGoderre : Can this issue be closed?

**Comment by LaurentGoderre** [comment]
No. It still needs to happen
