### ISSUE TITLE
Legend tag should have border-bottom

### ISSUE THREAD

**Issue by FrancoisJrPoulin** [wet-boew/wet-boew#6771]
Related to this "fix":
https://github.com/wet-boew/wet-boew/commit/5981bdb

Since the H1 now has a border-bottom, we will always end up we will always end up with the H1 followed by a line, followed by another line and then the legend. We will have two lines following each other without any content.

The other problem being that we have a line at the top of the legend/fieldset, but none at the bottom. So, we end up with a visual separation for the top of the fieldset, but none at the bottom, which is a problem when it's your last fieldset on the page. For consistency, this doesn't make any sense.

I think that going back to the bootstrap way of doing it, border-bottom instead of border-top would make more sense. if there is really a need to make a better visual distinction that a legend belongs to a certain fieldset/form fields, then a visual representation of a fieldset might be necessary (à la WET2).

I do believe that the bootstrap way of doing it (border-bottom) was more efficient and less prone to exceptions than the border-top way. Again for consistency, I believe that the H1 border-bottom should then be at the top as it has the same function as the legend border.

**Comment by LaurentGoderre** [comment]
Is this for the geomap?

**Comment by FrancoisJrPoulin** [comment]
No, it's not, it's for normal web forms.

**Comment by LaurentGoderre** [comment]
@thomasgohard can you look into this?

**Comment by thomasgohard** [comment]
It's the `border-bottom` on the `h1` that doesn't make sense. See https://github.com/wet-boew/wet-boew-styleguide/issues/236.

@masterbee you added a `border-bottom` on the `h1` in https://github.com/wet-boew/GCWeb/commit/4c276134602c150fc1c80d539af5b8296880862c. Why was that added?

**Comment by FrancoisJrPoulin** [comment]
I believe that even removing the `border-bottom` of the `h1` would not fix the issue that a `fieldset` has a beginning, but no end. If the purpose of the `border-top` is to make sure the `legend` belongs to the `fieldset`, then that would make the submit `button` part of the last `fieldset`.

It seems to me that a better option would be to use a `border-bottom` on the `fieldset` instead. It would mark the end of the `fieldset`. For the beginning of the `fieldsets`, we could have a `border-top` on the `form`.

Something like this for the top:
![top of form v2](https://cloud.githubusercontent.com/assets/12430053/7632622/e4da4cb0-fa1c-11e4-953e-20d467322542.PNG)

and the bottom:
![bottom of form v2](https://cloud.githubusercontent.com/assets/12430053/7632624/e978f258-fa1c-11e4-8b31-50d558302edb.PNG)

The border-bottom of the `h1` is removed. There is a clear separation as to where the `form`/`fieldset` starts. There is a clear separation below/between the `fieldsets`. There is a clear separation at the end of the last `fieldset`.

I had to add some space at the bottom of that last `fieldset` to distance the `button` from the `border-bottom` of it, so I would suggest to add 1em of margin-bottom and 1em of padding-bottom on the `fieldsets`. I would also add 1em of padding-top to the `form` to make the `border-bottom` of the `fieldsets` and the `border-top` of the `form` equal. It would also make the forms a bit more breathy.

I strongly believe that if we have a `border` at the top of the `form`, we should also have one at the bottom and that there should be some sort of separation between the `fieldsets` and I think that what I just suggested could fix that.

**Comment by thomasgohard** [comment]
When `fieldset`s are stacked one after the other, the `border-top` delineates the end of the previous `fieldset` **and** the start the next one.

I've moved to `border-top` from the `legend` element to the `fieldset` element in #6777.

**Comment by FrancoisJrPoulin** [comment]
But then there is no `border-bottom` at the end of the last `fieldset`, right? So anything that is not part of that last `fieldset` after it is not visually separated by anything.

**Comment by thomasgohard** [comment]
You wouldn't want a bottom border if the last `fieldset` is the end of the content or if the next element on the page already has some treatment to separate it though.

In #6777 I made sure that there's a separator between each `fieldset` (i.e., inner borders). When a form need outer borders, these can be added using classes `brdr-tp` and `brdr-bttm` on the `form` element. That allows people to control how a form is integrated into a page or part of a page, while ensuring that `fieldset`s are always separated visually.

**Comment by hsrudnicki** [comment]
@FrancoisJrPoulin @thomasgohard @LaurentGoderre : Can this issue be closed?

**Comment by hsrudnicki** [comment]
Due to the above and no further discussion/status updates, this issue labeled "Going Stale" and closed.
If you strongly think of otherwise, please update this issue's status again, thank you
