### ISSUE TITLE
Firefox browser and add-ons management

### ISSUE THREAD

**Issue by rlambert27** [wet-boew/wet-boew#6772]
Hi,

This is related to WET because we use Firefox to test accessibility of the plugins and themes.

Starting in version 39 of Firefox it will no longer be possible to install add-ons that are not signed unless using the nightly build or the developer edition.

Do any departments have any best practices concerning the add-ons and how are they managed? For example do you only allow add-ons that have been tested and the official AMO is blocked? Do you use the "Extension.getaddons.getURL" attribute to point to a local repository?

We're looking at seeing how we can control which add-ons are being installed by our developers and testers. 

Any information you can provide would be great, thanks!

Roch

**Comment by LaurentGoderre** [comment]
If Firefox is used for development or testing, I strongly recommend Firefox Developer Edition. Many function you previously needed add-ons for are covered by that version now.

**Comment by rlambert27** [comment]
Yes but FF developer edition (FFDE) allows the install of any XPI file, regardless if it's signed or not. You could have a user install an XPI file with malicious intent such as stealing password or browser sessions and send them to a web service. 

Now I know what you're thinking, typical technical peeps know how to detect and look through the smoke screen and see what some plugins really are, some non-technical people may not have that knowledge.

Another thing is allowing FFDE means you no longer have control on add-ons that are installed. In a huge organization would it not be a risk (security perhaps) to allow everyone free will on what to install on FFDE.

**Comment by LaurentGoderre** [comment]
I'm sure when they do implement this signing, it will be available in FFDE through a configuration option.

**Comment by hsrudnicki** [comment]
@rlambert27 @LaurentGoderre : Can this issue be closed?
