### ISSUE TITLE
Dropdown stays open after hovering on menu without dropdown

### ISSUE THREAD

**Issue by aastrong** [wet-boew/wet-boew#6773]
If i have menu items at the top. Some are dropdowns, some are not.
If i hover on a menu item that has a dropdown, and than move over and hover on a item that does not have a dropdown - the dropdown stays open, and does not close.

I would have expected the dropdown for the previous menu item to close when hovering on a menu item that does not have a dropdown.

Going to look into this issue - but wanted to raise the issue, and see if anyone else ran into the problem. 

Also opened an issue on drupal.org - https://www.drupal.org/node/2472649

**Comment by pjackson28** [comment]
I haven't been able to reproduce your issue with the latest version of WET. What version of WET are you using? I think that issue may have been raised and fixed many versions ago.

**Comment by aastrong** [comment]
I'll spin up a new version of WET and see if I run into issues. 
If not - I just need to upgrade.

Thanks for the response @pjackson28

**Comment by aastrong** [comment]
Hey there @pjackson28 
I just did a fresh install of Drupal WxT - And am still having the issue, - I did a quick video here - https://www.youtube.com/watch?v=Dwk4H_ARZOU&feature=youtu.be

Should I open this case up with Drupal WET rather than just WET?

Also, If i wanted to help fix some JS issues with Drupal WET ( specifically changes that have been fixed with WET, but have not been moved to Drupal WET.) 

How would I go about doing this, not 100% sure on the process of things, or even where exactly all the Core JS for Drupal WET lives. 

Again, thanks so much for your time.

**Comment by aastrong** [comment]
Oh, and to be a little clearer, my install was using the latest version ( 4.X ) of Drupal WET.
Thanks.

**Comment by LaurentGoderre** [comment]
@sylus would know better

**Comment by aastrong** [comment]
Thanks @LaurentGoderre ,
@sylus When you get the chance maybe you can point me in the right direction. 

I'd love to start giving back to WxT as much as I can.

**Comment by aastrong** [comment]
Ahh, i need to stay up-to-date on my Drupal issues :P
@sylus has already responded to me :)

Closing the issue, as its working as designed - but will come up with a patch/fix for Drupal WET if any one is interested, and post it here https://www.drupal.org/node/2472649

Thanks guys !
