### ISSUE TITLE
Data Ajax: Adding tags to selector options

### ISSUE THREAD

**Issue by Christopher-O** [wet-boew/wet-boew#6776]
Thank you for re-adding in the option for pulling data by selector (id) or class for the data-ajax plug in.  One thing that was available in versions 4.0.3 and prior was the added ability to pull based on tags.  This was helpful in order to pull data from within a container without having to pull the container as well.  This way, the page with the data-ajax code can redesign the data.  

For example, pulling in content from an ol list, and appending into a ul list, and adding in classes that will be applied to the li content since the ol container tags are not pulled in.
eg.  

Target page (target.html): ```<ol id="ajaxpuller"><li>List item 1</li><li>List item 2</li></ol>```
Data ajax page: ```<ul data-ajax-append="target.html #ajaxpuller li" class="lst-spcd"></ul>```

Hopefully there would be no issues adding this option back into an upcoming version of WET.

**Comment by LaurentGoderre** [comment]
I believe you can do it that way by specifying a selector

**Comment by LaurentGoderre** [comment]
If you add a space after the URL and specify a selector it will return only the matched elements.

Note that you have to be careful with your selectors or you can end up with unexpected results

**Comment by Christopher-O** [comment]
I have been trying it with WET 4.0.13 and it does not give me the same results as with WET 4.0.0.  In the old version (using the example in my original post), the results would give me just the li tags and the content within (and nest under the ul tag).  With WET 4.0.13 using the same code, it pulls in both the ol tag and all the li tags after the ul tag. so that the entire ol list is nested within the ul list.  It seems that it ignores using the tag selector.

**Comment by LaurentGoderre** [comment]
Can you add what the ajax content is, what the selector is and what is returned?

**Comment by Christopher-O** [comment]
Okay, here is the example html I use in a page called source.html
``` <ol id="selector">
    <li>List item 1 </li>
    <li>List item 2 </li>
    <li>List item 3 </li>
  </ol>```

and here I use the data-ajax in the page that applies the data
```<ul class="lst-spcd list-unstyled" data-ajax-append="source.html #selector li"></ul>```

in WET 4.0.0 the script outputs like this
```<ul class="lst-spcd list-unstyled wb-ajaxappend-inited"><li>List item 1 </li><li>List item 2 </li><li>List item 3 </li></ul>```

But in WET 4.0.13 the script outputs like this
```<ul class="lst-spcd list-unstyled wb-data-ajax-append-inited" id="wb-auto-1" data-ajax-append="source.html #selector li"><ol id="selector">
    <li>List item 1 </li>
    <li>List item 2 </li>
    <li>List item 3 </li>
  </ol></ul>```

Notice how in WET 4.0.13 there is an  ```<ul>``` and an  ```<ol>```  tag in the script, as the newer version seems to bypass and ignore the li selector completely.  Unless there is a new way to replicate the results from the WET 4.0.0 template in WET 4.0.13.

I hope that is the data you require.

**Comment by LaurentGoderre** [comment]
WHat happens if you use the following selector `#selector>li` instead?

**Comment by Christopher-O** [comment]
That seems to work!  Thank you so much!

**Comment by LaurentGoderre** [comment]
Np!
