### ISSUE TITLE
Feeds:  Flickr widget  - more documentation?

### ISSUE THREAD

**Issue by Bgolden67** [wet-boew/wet-boew#6778]
Can anyone provide extra direction on how to acquire the JSON URL to use in the code?
The only helpful easy to understand instruction i found in a google search resulted in something out of date because it refers to using the "orange" RSS feed button found on your flickr page... but there is no RSS feed button.

**Comment by thomasgohard** [comment]
See the [Flickr feeds documentation](https://www.flickr.com/services/feeds/) for details.

I'll add the link to the Feeds plugin documentation.

**Comment by thomasgohard** [comment]
@Bgolden67 did this solve your issue?

**Comment by Bgolden67** [comment]
Not really, but i think i need to be given access to the AANDC flickr account to find the ID i need.
the example given in the feed widget documentation uses an id like this <code>id=47711201@N05</code> and it's locating that id for the specific gallery i need to find.

**Comment by thomasgohard** [comment]
According to the [public feed API documentation](https://www.flickr.com/services/feeds/docs/photos_public/), the `id` is a `UserID`. I assume that you would normally retrieve that from your Flickr account.

I think I found the UserID for the AANDC Flickr account in the markup for the [account page](https://www.flickr.com/people/aandcanada/) though: `79815278@N07`. Putting that in the Feeds widget loads the AANDC feed for me. You probably want to verify it though.

I just searched the page markup for the pattern `@N` based on the ID format documented in their [flickr.people.findByUsername API call](https://www.flickr.com/services/api/flickr.people.findByUsername.html).

**Comment by Bgolden67** [comment]
Correct.. that loads the most recent images posted but I've been asked to load a specific collection/gallery not just the main account most recent.
I did the same searched for it.. I guess that's what i need to research in the flickr account is an id for a specific gallery/album.
Thanks for looking into it more... I will follow up on Tuesday

**Comment by thomasgohard** [comment]
There's no documented feed for a specific album. But I found an undocumented one in the Flickr forums. You'll still need the UserID. You'll also need the set ID, which you can obtain from the URL for the album.

For example, for the album at URL `https://www.flickr.com/photos/aandcanada/sets/72157647134984141`, the feed URL is `https://api.flickr.com/services/feeds/photoset.gne?set=72157647134984141&nsid=79815278@N07&format=json`.

**Comment by Bgolden67** [comment]
AHA!! Thank you!!
That did it... now i just need to figure out why it's showing oldest to newest instead of newest first *BUT*  this is better than what I had before.

**Comment by LaurentGoderre** [comment]
Can we close then?

**Comment by Bgolden67** [comment]
Thanks for the help!
-closed-
