### ISSUE TITLE
wb-toggle class in details tag do not behave properly in WET 4.0.13

### ISSUE THREAD

**Issue by shadeinc** [wet-boew/wet-boew#6782]
We just recently updated to WET v4.0.13, and the wb-toggle class does not behave the way it used to.

Code:
```html
<details class="wb-toggle" data-toggle='{"print":"on"}'>
```
In v4.0, clicking on the summary would be the only way to expand/collapse the details. Since 4.0.13, once expanded, clicking anywhere in the details portion of the content makes it collapse. This is a problem as no links can be clicked within the details portion of the content. Removing the wb-toggle class prevents this issue, however, it of course no longer auto-expand everything when printing.

Any help or feedback on this issue would be greatly appreciated.

Thank you

**Comment by pjackson28** [comment]
That's because you are putting wb-toggle on the details element, making it the element that triggers the toggle (hence why clicking anywhere in that element results in a toggle). You should be putting it on the the summary element instead like is done in the working examples.

**Comment by shadeinc** [comment]
Aaah so simple, thanks Paul! :)
