### ISSUE TITLE
How to overide functions in helpers.js

### ISSUE THREAD

**Issue by bomarleau** [wet-boew/wet-boew#6783]
Hi, we need to add some code in helpers.js function wb.formattedCompare for some customized comparison. What is the best way to do that without having to change too much to the WET?It will be difficult to have to modify the code every time there is a new WET package comes out.

**Comment by LaurentGoderre** [comment]
These helpers are for plugins so modifying them has a high risk of breaking them. What is your use case for changing them?

**Comment by bomarleau** [comment]
In our data table, we have ., .., ..., a, x, F in the data. We need to sort them as well. Sample code:
//Do a simple text comparisson if both are replacement characters
     if ( (a == "." || a == ".." || a == "..." || a == "X" || a == "x" || a == "F" || a == "f" || a ==" " || a == "&nbsp;")
         && (b == "." || b == ".." || b == "..." || b == "X" || b == "x" || b == "F" || b =="f" || b ==" " || b =="&nbsp;"))
         {  return ((a < b) ? -1 : ((a > b) ?  1 : 0));  }

**Comment by bomarleau** [comment]
This is for WET 3. Now WET 4 has changed, so the modficiation will be different.

**Comment by LaurentGoderre** [comment]
Which plugin are you trying to modify the behavior for? Also note that version 3 is no longer supported

**Comment by bomarleau** [comment]
The similar function is in helps.js(wb.formattedNumCompare ). I am wandering if we can override/extend the funcition outside of WET?

**Comment by LaurentGoderre** [comment]
If you override it it may break plugin. You can copy the function an use it in your custom JavaScript. You shouldn't modify helpers.

**Comment by bomarleau** [comment]
The code that may need to be changed:
wb.formattedNumCompare = function( a, b ) {
		var regEx = wb.formattedNumCompareRegEx,
			aMultiple = a.indexOf( "-" ) === -1 ? 1 : -1,
			aNumbers = ( ( a === "-" || a === "" ) ? "0" : a.replace( regEx, "" ) ).split( "." ),
			bMultiple = b.indexOf( "-" ) === -1 ? 1 : -1,
			bNumbers = ( ( b === "-" || b === "" ) ? "0" : b.replace( regEx, "" ) ).split( "." ),
			len = aNumbers.length,
			i, result;

		for ( i = 0; i !== len; i += 1 ) {
			result = parseInt( aNumbers[ i ], 10 ) * aMultiple - parseInt( bNumbers[ i ], 10 ) * bMultiple;
			if ( result !== 0 ) {
				break;
			}
		}
		return result;
	};

**Comment by bomarleau** [comment]
So, I will need to write the wb.formattedNumCompare in my javascript? When the plugin call this function, which one it will call?

**Comment by bomarleau** [comment]
One way I can think of is to overwrite the plugin tables.js as well to call the new function.

**Comment by LaurentGoderre** [comment]
I highly discourage it. What is your specific use case?

**Comment by bomarleau** [comment]
The use case is to be able to sort data in the sortable table. Normally, the data is numberical. But in some case, for some reason, the data can be ., ..,... , X or F. In those cases, when the data is sorted, we want them to be the smallest.

**Comment by LaurentGoderre** [comment]
This sound like very specific sorting that perhaps should be done server-side. If you were to update to WET4 you could use the DataTables sorting plugin to add your custom sorting types

http://www.datatables.net/plug-ins/sorting/

**Comment by hsrudnicki** [comment]
@bomarleau @LaurentGoderre : Can this issue be closed or otherwise?

**Comment by hsrudnicki** [comment]
Due to no further discussion/status update(s), this issue made "Going Stale" to close or if otherwise?
Either way, please update this issue's status, thank you

**Comment by hsrudnicki** [comment]
Based on the above, this can be closed as resolved; if you think otherwise, please update the status of this again, thank you
