### ISSUE TITLE
Error when running setup in script folder

### ISSUE THREAD

**Issue by claudielarouche** [wet-boew/wet-boew#6785]
Good morning,

I am following the instructions at the bottom of this website:
http://wet-boew.github.io/wet-boew/docs/start-en.html

I would like to eventually create a pull request. However when I try to run "setup" from the script directory, I get the following errors: 

<code>Error: Command failed: git -c core.longpaths=true config --get remote.origin.url</code>

<code>error git clone --template=C:\Users\larouchec\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/wet-boew/node-git-simple.git C:\Users\larouchec\AppData\Roaming\npm-cache\_git-remotes\git-github-com-wet-boew-node-git-simple-git-0d4a5d56: Cloning into bare repository 'C:\Users\larouchec\AppData\Roaming\npm-cache\_git-remotes\git-github-com-wet-boew-node-git-simple-git-0d4a5d56'...</code>

<code>error git clone --template=C:\Users\larouchec\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/wet-boew/node-git-simple.git C:\Users\larouchec\AppData\Roaming\npm-cache\_git-remotes\git-github-com-wet-boew-node-git-simple-git-0d4a5d56: fatal: unable to connect to github.com:</code>

<code>error git clone --template=C:\Users\larouchec\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/wet-boew/node-git-simple.git C:\Users\larouchec\AppData\Roaming\npm-cache\_git-remotes\git-github-com-wet-boew-node-git-simple-git-0d4a5d56: github.com[0: 192.30.252.129]: errno=No error</code>

Do you have any idea how I can resolve those issues? I tried the following commands to fix the connection to github problem but it didn't help:

<code>git config --global url."https://".insteadOf git://</code>

Any help you can provide will be greatly appreciated!

**Comment by LaurentGoderre** [comment]
Try using this:

https://github.com/npm/npm/issues/5257#issuecomment-60441477

**Comment by claudielarouche** [comment]
Ah thank you I didn't know about this troubleshooting document that's perfect! Now I am running into errors related to my version of Python, but we can close this ticket for now if you want, I can add a new ticket if I don't manage to fix those new errors myself...

**Comment by LaurentGoderre** [comment]
You should need python....in the meantime you need to run Node v0.10, not v0.12. It sounds like you are on 0.12.

**Comment by LaurentGoderre** [comment]
have you tried it?

**Comment by claudielarouche** [comment]
Sorry didn't get a chance to try it yet and I'm attending a conference today and tomorrow. I will try it again next week.

**Comment by claudielarouche** [comment]
I changed my version of node to v0.10 instead of 0.12. Now I am getting the following errors:

<code>1089 verbose addRemoteGit [ 'git@github.com:wet-boew/grunt-wet-boew-postbuild', 'v0.1.2' ]</code>
<code>1090 warn `git config --get remote.origin.url` returned wrong result (git@github.com:wet-boew/grunt-wet-boew-postbuild)</code>
<code>1091 error git clone git@github.com:wet-boew/grunt-wet-boew-postbuild Cloning into bare repository 'C:\Users\larouchec\AppData\Roaming\npm-cache\_git-remotes\git-github-com-wet-boew-grunt-wet-boew-postbuild-2960c717'...</code>
<code>1091 error git clone git@github.com:wet-boew/grunt-wet-boew-postbuild ssh: connect to host github.com port 22: Bad file number</code>
<code>1091 error git clone git@github.com:wet-boew/grunt-wet-boew-postbuild fatal: Could not read from remote repository.</code>
<code>1091 error git clone git@github.com:wet-boew/grunt-wet-boew-postbuild</code>
<code>1091 error git clone git@github.com:wet-boew/grunt-wet-boew-postbuild Please make sure you have the correct access rights</code>
<code>1091 error git clone git@github.com:wet-boew/grunt-wet-boew-postbuild and the repository exists.</code>
<code>1092 silly lockFile 2960c717-et-boew-grunt-wet-boew-postbuild git@github.com:wet-boew/grunt-wet-boew-postbuild</code>
<code>1093 silly lockFile 2960c717-et-boew-grunt-wet-boew-postbuild git@github.com:wet-boew/grunt-wet-boew-postbuild</code>
<code>1094 silly lockFile d1f62b99--grunt-wet-boew-postbuild-v0-1-2 grunt-wet-boew-postbuild@wet-boew/grunt-wet-boew-postbuild#v0.1.2</code>
<code>1095 silly lockFile d1f62b99--grunt-wet-boew-postbuild-v0-1-2 grunt-wet-boew-postbuild@wet-boew/grunt-wet-boew-postbuild#v0.1.2</code>
<code>1096 error 404 404 Not Found: grunt-wet-boew-postbuild</code>
<code>1096 error 404</code>
<code>1096 error 404 'grunt-wet-boew-postbuild' is not in the npm registry.</code>
<code>1096 error 404 You should bug the author to publish it</code>
<code>1096 error 404 It was specified as a dependency of 'wet-boew'</code>
<code>1096 error 404</code>
<code>1096 error 404 Note that you can also install from a</code>
<code>1096 error 404 tarball, folder, or http url, or git url.</code>

Do you know if something is wrong with grunt-wet-boew-postbuild?

**Comment by LaurentGoderre** [comment]
Try deleting the node_modules folder and starting again

**Comment by claudielarouche** [comment]
I deleted node_modules but it was still giving me error messages. So I deleted the content of the following folder and then it worked.

C:\Users\[my_username]\AppData\Roaming\npm-cache

Thank you so much for your patience!

**Comment by LaurentGoderre** [comment]
Aaah yeah, sometimes the npm cache corrupts. Nice catch!
