### ISSUE TITLE
Multimedia Player:  captions in xml or smi?

### ISSUE THREAD

**Issue by Bgolden67** [wet-boew/wet-boew#6787]
Any suggestions on what needs to be modified in the code to use xml file captions instead of in page html?
Our current videos currently call an xml or smi file to provide some CC, but in this wet4 player, they aren't loading.
one example with a smi file, but other than the smi vs xml the codes are identical:
<code>

	<video poster="/DAM/DAM-INTER-HQ-AI/WORKAREA/DAM/images-images/apology_video_1428935906293_eng.jpg" title="Indian Residential Schools Statement of Apology - Prime Minister Stephen Harper">
		
		<source type="video/mp4" src="http://rmedia.aadnc-aandc.gc.ca/media/APO/PM-Eng.mp4" />
		<track src="/DAM/DAM-INTER-HQ/WORKAREA/DAM/texte-text/ap01_1100100015679_eng.smi" kind="captions" data-type="application/smil+xml" srclang="en" label="English" />
	</video>

</code>

**Comment by LaurentGoderre** [comment]
It doesn't support SMI. If you use XML you need to use TTML

http://wet-boew.github.io/wet-boew/demos/multimedia/captions-en.xml

**Comment by Bgolden67** [comment]
ok good to know about .smi I will make the request to have those converted asap.

this is the xml we have.. it looks the same more or less
<code>http://rmedia.aadnc-aandc.gc.ca/media/SS/2014/XML/SS-2014-LoHO-eng.xml</code>

**Comment by LaurentGoderre** [comment]
Yeah that should work, have you tried it?

**Comment by LaurentGoderre** [comment]
Use:

```
<track src="captions-en.xml" kind="captions" data-type="text/xml" srclang="en" label="English">
```

**Comment by Bgolden67** [comment]
I think we have figured out it's teh media server it's being called from is the problem.
On Monday i will test it with a different path.

**Comment by LaurentGoderre** [comment]
Let me know

**Comment by hsrudnicki** [comment]
@Bgolden67 @LaurentGoderre : Can this issue be closed?

**Comment by Bgolden67** [comment]
This thread can be closed.
This issue inparticular was caused by the media server
