### ISSUE TITLE
Form validation: nowrap issue on long error messages

### ISSUE THREAD

**Issue by robwloch** [wet-boew/wet-boew#6788]
We've found the need to write some custom CSS to deal with long error messages in labels. Just wondering if you'd consider adding it to the WET 4 core in case other people could benefit from it too?

.label-error {
    white-space:normal;
    display: block;
    text-align: left;
}

Thank you, Rob.

Screenshot using custom CSS from Firefox mobile view:

![custom](https://cloud.githubusercontent.com/assets/5721679/7777424/ce76c6cc-0090-11e5-9c7c-4f5b89f72cb4.PNG)

**Comment by hsrudnicki** [comment]
@robwloch @LaurentGoderre @pjackson28 : Can this issue be closed or otherwise?

**Comment by robwloch** [comment]
@hsrudnicki , I just suggested this because it seems to be working in our dept but we'll have to let @LaurentGoderre and @pjackson28 decide if it's something that might benefit the broader WET community.

**Comment by andre-gh** [comment]
I will verify how error messages function when they are long later this week or next week, if it seems incorrect I will do up a pull request with this css or similar css added.
