### ISSUE TITLE
Using rel=external

### ISSUE THREAD

**Issue by Bgolden67** [wet-boew/wet-boew#6789]
Just a general Help question.
Until we all reside on canada.ca, should a link TO a page on canada.ca use <code> rel=external</code>, and vice versa on pages like the IP page, should they use a <code>rel=external</code> to point to our current sites?

**Comment by pjackson28** [comment]
There is no requirement to do that so it may be best to plan just for the end-state (everything on Canada.ca) rather than dealing with the headaches of an interim usage of rel=external for the transition.

**Comment by Bgolden67** [comment]
that was my gut response, but figured i would put it out there.
thanks
