### ISSUE TITLE
Opening popup on UpdatePanel postback causes jquery.magnific-popup.min.js to be reloaded multiple times

### ISSUE THREAD

**Issue by GarthMartin** [wet-boew/wet-boew#6790]
I have a couple update panels on a page which postback, saving or deleting data on the server.  Using the PageRequestManager I add an event to check for a flag that indicates if we should show a success dialog.  If so I open the dialog as follows:

```javascript
// show our success dialog box
    if (ShowSuccessDialog()) {
        wb.doc.trigger("open.wb-lbx", [[{ src: '#SaveSuccessfulDialog', type: 'inline' }], true]);
        wb.doc.on("click", "#SaveDialogOKClose", function () {
            ResetAllSuccessFlags();
        });
    }
```

For some reason every time the popup gets triggered, another copy of jquery.magnific-popup.min.js seems to be loaded into the browser memory.  After about 5 or 6 round trips to the server, the browser just bogs down and is not responsive.

Is there another way I should be opening/initing the popup?  I am using the popup this way on numerous other pages with no problems, but without UpdatePanels.

The rendered markup for the popup is below:

```html
<section class="wb-lbx mfp-hide modal-dialog modal-content overlay-def confirm-dialog wb-lbx-inited" id="SaveSuccessfulDialog">
                <header class="modal-header">
                    Success
                </header>
                <div class="modal-body">
                    Your data was saved successfully.
                    <div class="align-center">
                        <input id="SaveDialogOKClose" class="btn btn-primary btn-sm popup-modal-dismiss" title="Ok" name="ctl00$SaveDialogOKClose" value="Ok" type="submit">
                    </div>
                </div>
</section>
```

Thanks in advance,

Garth

**Comment by LaurentGoderre** [comment]
@GarthMartin the problem is most likely that your server is incorrectly handling caching. The dependency loader we use (Yepnope, included in Modernizr) rely on proper caching to avoid these multiple loads.

**Comment by GarthMartin** [comment]
How could I confirm that?  Currently I am running locally through Visual Studio.  I have not moved it to a dev server as yet.  

After further investigation, it appears to only be happening when I pop a confirm delete dialog on button click:

```javascript
// confirm the delete action
function ConfirmAction(elem) {

    wb.doc.trigger("open.wb-lbx", [
        [
        {
            src: '#ConfirmDeleteDialog',
            type: 'inline',
        }],
        true
    ]
    );

    // the yes button will launch the click event in a different JS namespace which essentially submits the click event 
    // but without the confirmation.
    wb.doc.on("click","#ConfirmDeleteYesButton", function () {
        $(elem).trigger("click.confirmed");
    });
}
```

The event on the delete button is a postback event handler.  I am thinking that the act of launching the click event in a different JS namespace may be causing the multi-loads.  Thoughts?

Garth

**Comment by LaurentGoderre** [comment]
The `open.wb-lbx` creates a new instance of a lightbox so it loads the dependencies first. If caching is enabled all subsequent load calls are ignored. If you are running of Visual Studio's web server, it is highly likely to not have proper caching.

**Comment by hsrudnicki** [comment]
@GarthMartin @LaurentGoderre : Can this issue be closed?

**Comment by hsrudnicki** [comment]
This issue labeled "Going Stale" and closed as resolved based on the above and no further discussion. If otherwise, please update this issue's status again, thank you.
