### ISSUE TITLE
Lightbox: Transparency overlay

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/wet-boew#6791]
When using the lightbox gallery and adding text below the image it makes it hard to read if the overlay has black text beneath it.

![lightbox-issue](https://cloud.githubusercontent.com/assets/2575266/7800050/61c95478-02dd-11e5-8b54-a89c34f310de.JPG)

cc: @trtustian

**Comment by thomasgohard** [comment]
Agreed. There should be a solid background behind the text.

Can you submit a pull request with the fix?

**Comment by hsrudnicki** [comment]
@shawnthompson @thomasgohard  @LaurentGoderre : Are you ready to close this issue?

**Comment by pjackson28** [comment]
So we now have two options, one changing the bottom text to a grey background with black text and the other increasing the opacity of the background overlay. Which should we pick? Should we offer both options? If so, how do we offer both options?

Also, this is something that should also be considered for addressing upstream.

**Comment by hsrudnicki** [comment]
Just labeled "Going Stale" to close this issue when resolved/fixed completely, and 
please @LaurentGoderre and others help in making decisions/answers to the last comment's questions from @pjackson28, thank you

**Comment by hsrudnicki** [comment]
Can be this issue closed as resolved/fixed or is this still an issue?  Either way, please update this issue's status, whether this issue can be closed or otherwise? Thank you
[Note that the both referenced PRs have been already merged.]

**Comment by RobJohnston** [comment]
I think this can be closed since https://github.com/wet-boew/wet-boew/pull/6856 got merged and the change can be seen on the [Lightbox working example] (http://wet-boew.github.io/wet-boew/demos/lightbox/lightbox-en.html).

**Comment by shawnthompson** [comment]
Thanks @RobJohnston
