### ISSUE TITLE
Input type="date" polyfill (date picker): picked date disappears the first click away

### ISSUE THREAD

**Issue by pliz22** [wet-boew/wet-boew#6793]
i've an odd issue for this date picker
the first load of the page, i click the calendar icon, pick a date, date fills the input box.  this is all okay.
if i click away from the field into another field the date disappears.
if i go back a second time then it stays.
if i tab out (even the first time) then it stays.
this is with WET 4011 the GCWU theme in Firefox.
i tried it here with the working examples and this is not an issue, so is it something so simple as my code shown below?
```
<fieldset class="mrgn-lft-md">
<legend></legend>
<div class="row form-group">
<p class="mrgn-bttm-sm">
<label for="frauddate" class="control-label">When did the suspected fraud happen?</label>
</p>
<div class="row col-xs-9">
<input name="frauddate" id="frauddate" type="date" class="form-control full-width" value="" />
</div></div>
```

**Comment by LaurentGoderre** [comment]
The date picker is being rewritten so we will need to test in the new one

**Comment by LaurentGoderre** [comment]
BTW< whhy do you have `value=""`?

**Comment by pliz22** [comment]
I am generating it with a loop but I added a condition to not put value of there isn't any and its a type date. 

But it still erases / forgets the first date that I pick. 

Feels like... It's half initialized before I pick a date and then finishes the initialization after I pick a date. 

I should put it class polyfill? 

Sent from Yahoo Mail on Android

**Comment by LaurentGoderre** [comment]
No,. you shouldn't have to do anything for it work.

**Comment by LaurentGoderre** [comment]
Do you ahve an example I can look at?

**Comment by pliz22** [comment]
ok, here is what i have, this is WET 4.0.11 GCWU theme
And I just noticed it works in IE11 but not in FF37
```<fieldset class="mrgn-lft-md"><legend></legend>
<div id="frauddate-row" class="row form-group">
<p class="mrgn-bttm-sm">
<label for="frauddate" class="control-label">When did the suspected fraud happen?</label>
</p>
<div class="row col-xs-9">
<input name="frauddate" id="frauddate" type="date" class="form-control full-width" />
</div>
</div>
```

**Comment by LaurentGoderre** [comment]
Can you reproduce in the working examples?

**Comment by hsrudnicki** [comment]
@pliz22 : Are you ready to close this issue and confirm it with @LaurentGoderre ?

**Comment by hsrudnicki** [comment]
Based on the above, as well no further discussion/status updates, this issue labeled "Going Stale" and closed.
If you strongly think of otherwise, please update this issue's status again, thank you
