### ISSUE TITLE
Multimedia Player: inline HTML captions not loading

### ISSUE THREAD

**Issue by Bgolden67** [wet-boew/wet-boew#6795]
Any suggestions?
here is the issue: 
intranet using wet4.0.11 in Teamsite. Multimedia player with inline HTML caption, and captions will not play. The video plays fine.

the code is basically identical to the sample code on the working example page. Infact i copied the exact code from the example, put it in my page and it's captions do not load either, but the video plays.

**Comment by hsrudnicki** [comment]
@Bgolden67 @LaurentGoderre : Can this issue be closed, and maybe this issue is related to #6787 ?

**Comment by LaurentGoderre** [comment]
Is this still occurring in the latest version?

**Comment by Bgolden67** [comment]
I will have to test it today and let you know
