### ISSUE TITLE
Adding validation rules

### ISSUE THREAD

**Issue by GarthMartin** [wet-boew/wet-boew#6796]
I am trying to add some validation rules and getting inconsistent behaviour between two pages.  The pages in questions are virtual copies of each other, in that they perform nearly identical functionality with different data entities (CRUD), but the manner in which the pages work is identical (load, display, add/edit/delete).

In a page specific javascript file I have the following:
```javascript
// add some custom validation
$(document).on("wb-ready.wb-frmvld", ".wb-frmvld", function (event) {
    $("#PostalCodeValue").rules("add", { postalCodeCA: true });
});
```
and this works just fine.

HOWEVER, in the page that gathers phone numbers, I have the following, in exactly the same place in the page processing sequence:
```javascript
// add some custom validation rules
$(document).on("wb-ready.wb-frmvld", ".wb-frmvld", function (event) {
     $("#PhoneNumberValue").rules("add", { phoneUS: true });
});
```
and jquery.validator.min.js throws an error 
``` 
Unable to get value of the property 'form': object is null or undefined
```

If I move the validation rules into a section that is 
```javascript
$(document).on("wb-ready.wb", function () {});
```
I do not get an error for Phone Number, but the rule is not added.

Any thoughts?

**Comment by pjackson28** [comment]
Out of curiosity, why are you using JS to add the rule? Why not just add the rule through markup with <code>data-rule-phoneUS="true"</code>? That way you don't have to worry about using event handlers to add the rule after the fact.

As for what could be going wrong in your instance, is the element in question within a form element? What is the difference in markup between the first and second example? A difference in form markup could be a contributing factor (e.g., jQuery validation can't find the related form element so the form property is set to null).

**Comment by GarthMartin** [comment]
@pjackson28 I was not aware that there was a data rule for phoneUS.  Is there one for postalCodeCA?

I resolved the problem, it was releated to markup and a missing .Net ClientIDMode=Static.  The error message was misleading, as it was not the form, but the element that was missing.

Thanks,

Garth

**Comment by RobJohnston** [comment]
There is a rule for postalCodeCA.. It can be seen in the additional-methods.js file.  Came in from #5473.

**Comment by GarthMartin** [comment]
Thanks!

**Comment by pjackson28** [comment]
@GarthMartin There should be a data rule for postalCodeCA as well since that method is included in jQuery Validation's additional-methods.js just like phoneUS.
