### ISSUE TITLE
Breadcrumb Bullets

### ISSUE THREAD

**Issue by bmoretton** [wet-boew/wet-boew#6798]
Hello,
 
I'm working towards getting the dynamic portion of the CPIC public website back up after our server crash.  I am hoping you could help answer a question.  My bullets on the breadcrumb trail are not coming up in Chrome or Firefox.  Can someone tell me why?
 
http://app.cpic-cipc.ca/English/search.cfm

Thx!
 
Brian

**Comment by claudielarouche** [comment]
You have an error message on the console that says:

<code>Failed to load resource: the server responded with a status of 404 (Not Found)
http://app.cpic-cipc.ca/fonts/glyphicons-halflings-regular.woff

Failed to load resource: the server responded with a status of 404 (Not Found)
http://app.cpic-cipc.ca/fonts/glyphicons-halflings-regular.ttf </code>

**Comment by RobJohnston** [comment]
Likely you'll have to configure the server to serve these types of files.  I'm guessing you're using IIS?  
http://codeasp.net/blogs/raghav_khunger/microsoft-net/2273/woff-ttf-svg-otf-eot-files-showing-404-error-in-console

**Comment by bmoretton** [comment]
Thank you!
