### ISSUE TITLE
Share widget components unable to pass the page subject and URL if there is more than one apostrophe in title element

### ISSUE THREAD

**Issue by biljanap** [wet-boew/wet-boew#6799]
We have issue with sharing the pages  with the  <code>title</code> element containing more than one apostrophe. This is fairly common in French pages. I believe the <code>title</code> content is used to pass information about subject of the web page.
I will use E-mail component as an example to illustrate the issue but it happens with most other components.
If the title contains more than one apostrophe, the subject line in Outlook mail window displays only content up to the second apostrophe. For example if the title of the page is 
```html
<title>Family’s rules in Biljana’s house</title>
```
The subject line in Outlook e-mail window will be “**Family’s rules in Biljana**”.  The rest is cut. Since the “process” of Sharing the page is stopped right before the second apostrophe, the URL of the page does not make it to the body of e-mail window either.

Here is an example of the page where the issue happens: http://nouvelles.gc.ca/web/article-fr.do?mthd=index&crtr.page=1&nid=979239

For some strange reason the generated html code to style “**tumblr**” component is all screwed up. This is the code I see when  I debug in Firefox: <code>class=" shr-lnk="" tumblr="" btn="" btn-default'=""</code>.

As a result the icon and styles are missing. See attachment:
![share-widget](https://cloud.githubusercontent.com/assets/2146304/7823428/6a852f14-03c9-11e5-9644-fd583b13694c.gif)

**Comment by pjackson28** [comment]
Tumblr seems to display correctly on the live working examples (both visually and in the markup).The Tumblr issue is most likely because you have a combination of two different WET versions. You most likely have some files with the Tumblr entry with others missing it.

As for your double appostrophe issue, I can't reproduce with the latest version of WET and Outlook 2010. I copied and pasted the exact same title in the title element and the result email subject was as it should be. What version of WET are you using? Perhaps there was an issue in an older version of WET that has since been fixed.

**Comment by biljanap** [comment]
@pjackson28 We are using v4.0.12 but I downloaded v4.0.14 and the issue is still there. I added two apostrophes to the existing <code>title</code> in WET **share-en.jsp** example page. I tested in IE 11 and Firefox 37.0.2. The same thing happens in both browsers. Sorry if I was not clear that "Tumblr" issue only happens when 2 apostrophes are present in the <code>title</code>. It is otherwise fine.

**Comment by pjackson28** [comment]
@biljanap I think I can see why I can't reproduce. Your title above is not using the problematic standard appostrophe, it is using the "Word" style apostrophe (which is a different character altogether). I can now reproduce if I replace the "Word" style appostrophes with regular apostrophes.

**Comment by biljanap** [comment]
@pjackson28 Yes I can see it now too. I don't know how I managed to use Word apostrophe in my example :o).

**Comment by pjackson28** [comment]
@biljanap PR #6811 will fix the issue. The problem was that the regex used for apostrophe filtering wasn't greedy (was missing the "g" option).
