### ISSUE TITLE
Remove 'Looking for WET v3.1' bar

### ISSUE THREAD

**Issue by duboisp** [wet-boew/wet-boew#6802]
Can we remove the 'Looking for WET 3.1' bar on every page and may be move that notice into a section in the [WET home page](http://wet-boew.github.io/wet-boew/index-en.html)

The issue is we got feedback from external user/developer at Guelph where they thought the WET was no longer an active project.

Cheers

:smile:

**Comment by LaurentGoderre** [comment]
Feel free to open a PR

**Comment by duboisp** [comment]
Ok, i will do

Cheers

**Comment by hsrudnicki** [comment]
@duboisp @LaurentGoderre : Can this issue be closed?
