### ISSUE TITLE
Input type="date" polyfill (date picker) - datepicker-format not working in Google Chrome

### ISSUE THREAD

**Issue by wilkmit** [wet-boew/wet-boew#6807]
datepicker-format not working in Google Chrome. Is there a way to override the chrome date picker and use the WET 4.0 one? 

    <div class="form-group">
	    <label for="date">Date<span class="datepicker-format"> (<abbr title="two digits month, dash, two digits day">MM-DD</abbr>)</span></label>
	    <input class="form-control" type="date" id="date" name="date" />
    </div>

**Comment by LaurentGoderre** [comment]
Google Chrome uses a native date picker and respects the HTML5 spec and returns an ISO format date.

**Comment by wilkmit** [comment]
I was confused about how the datepicker-format class worked. I thought it allowed you to alter the format of the date.
