### ISSUE TITLE
Is there a way to reference XmlHTTPRequest for a dynamic datalist?

### ISSUE THREAD

**Issue by jvanulde** [wet-boew/wet-boew#6810]
Using the following code:

    searchInput.trigger( {
	    type: "ajax-fetch.wb",
	    fetch: {
		    url: encodeURI( i18nText.geoLocationURL + "?q=" + val + "*" ),
		    dataType: wb.ielt10 ? "jsonp" : "json",
		    jsonp: wb.ielt10 ? "callback" : null
        }
    } );

I need to cancel the "fetch" if the user has updated the input field. Currently we are using:

    var xhr = $.get(...);

    if ( xhr ) { xhr.abort(); }

**Comment by LaurentGoderre** [comment]
Because it's an event, I don't think you can do that....

**Comment by hsrudnicki** [comment]
@jvanulde @LaurentGoderre : Can this issue be closed or otherwise?

**Comment by jvanulde** [comment]
Please close.

**Comment by pjackson28** [comment]
Following up on this, you may not be able to stop the event bubbling but the event triggers a plugin which uses $.ajax so you could use abort() if you are provided access to the reference created by $.ajax. The ajax-fetch plugin currently doesn't provide such access but in theory it could be changed to return the reference (or perhaps provide some method for triggering an abort).
