### ISSUE TITLE
Horizontal description lists

### ISSUE THREAD

**Issue by Bgolden67** [wet-boew/wet-boew#6812]
Silly issue really.. but it's caused frustration in attempting to use this.
it seems that no matter what we try to over ride the alignment, the <code>dt</code> item is aligned right. This causes a white space gap on the left side of the lists.
Is there a way I am missing to force this left aligned or can the <code> dl-horizontal</code> class be adjusted to default left instead?

**Comment by thomasgohard** [comment]
As indicated in https://github.com/twbs/bootstrap/issues/14180, we would need to implement an override for `.dl-horizontal dt` as it has greater specificity than `.text-left`.

Right-aligned text is harder to scan so the default should be left-aligned. There are also other problems with the style, including the fixed width for the `dt` element and long `dt` elements being truncated when they don't fit the fixed width. The styling of the horizontal description lists needs to be entirely redone.

**Comment by hsrudnicki** [comment]
@Bgolden67 @thomasgohard : Are you ready to close this issue or otherwise?

**Comment by Bgolden67** [comment]
thank you
