### ISSUE TITLE
Polyfill: Datalist (Auto-complete) - Some options being filtered out in Chrome on Mac

### ISSUE THREAD

**Issue by jvanulde** [wet-boew/wet-boew#6815]
The polyfill is filtering out some elements when rendering the list in Chrome:

Sample code:

![screen shot 2015-05-28 at 1 49 47 pm](https://cloud.githubusercontent.com/assets/2255248/7870799/751444ba-0540-11e5-8096-f56fe5336fce.png)

Sample screenshot (Chrome):

![screen shot 2015-05-28 at 1 47 25 pm](https://cloud.githubusercontent.com/assets/2255248/7870751/1e0640f6-0540-11e5-856e-6566affe81f4.png)

Sample screenshot (Firefox):

![screen shot 2015-05-28 at 1 51 09 pm](https://cloud.githubusercontent.com/assets/2255248/7870845/b9d17a1e-0540-11e5-8c6c-495c4c5d935f.png)

**Comment by sgdowney** [comment]
I think Chrome supports the list attribute so may not be using the polyfill.  Perhaps there are other attributes that specify how the browser searches for values in the list?  Match from start of string only or anywhere in the string?

**Comment by jvanulde** [comment]
Good point @sgdowney. It works in Safari too so I think it might be a Chrome issue... as you suggest.

**Comment by hsrudnicki** [comment]
@jvanulde @sgdowney : Can this issue be closed?

**Comment by sgdowney** [comment]
@jvanulde was this ever resolved?

**Comment by jvanulde** [comment]
Not to my knowledge. I think it's still an issue.

**Comment by neoinsight** [comment]
Perhaps this is why these usability participants had so many problems? They were both using Chrome. See this issue with accompanying video clips https://github.com/wet-boew/wet-boew/issues/6845

**Comment by pjackson28** [comment]
Most browsers have native support now (only old IE seems to be missing it) and they are inconsistent with how they handle the matching. Chrome only looks for matches at the start of the string while Firefox looks for matches anywhere in the string (which is why you get the results above).

@neoinsight You are probably right, likely the users weren't finding any matches because Chrome was only showing the results where the match was found at the start of the strings.

**Comment by jvanulde** [comment]
@pjackson28 based on your comments I think we can close this. @neoinsight do you concur?

**Comment by neoinsight** [comment]
@jvanulde Ok, I think this is a matching issue is bigger than just Chrome on Mac and I have other usability issues around it that will stay open.

**Comment by pjackson28** [comment]
Looking into it further it looks like all browsers with native support match from the start except for Firefox. Chrome, IE10+ and Opera all match from the start. The browsers that lack native support seem to be IE8/9, Safari and Safari iOS (rely on the WET polyfill instead).

As mentioned in #6894, the majority of browsers match from the start and we could make it even more consistent by making the WET polyfill match from the start as well (leaving just Firefox and it's 14% market as the outlier). Also was asked in #6894 whether that change should be made to the WET polyfill, leaving only Firefox as the outlier.

**Comment by hsrudnicki** [comment]
Made "Going Stale" to close this issue as resolved due to no further discussion or if otherwise?
Either way, please update this issue's status, thank you

**Comment by hsrudnicki** [comment]
Based on the above, this issue can be closed as resolved. If you think otherwise, please update the status of this again, thank you
