### ISSUE TITLE
Overlay close button missing type attribute

### ISSUE THREAD

**Issue by bmadzar** [wet-boew/wet-boew#6816]
The overlay plugin's "close" button (x in top right corner) does not have its `type` attribute set explicitly, defaulting to `type="submit"`.

If the overlay is defined inside of a form, this will cause that form to be submitted when the overlay is closed. This is unexpected.

Recommend adding `type="button"`, unless this behaviour is intentional.

**Comment by pjackson28** [comment]
Will be fixed by PR #6818.
