### ISSUE TITLE
Table id/headers associations with WET

### ISSUE THREAD

**Issue by gregrgay** [wet-boew/wet-boew#6817]
I sat in on Toufic Sbeiti's presentation about WET at the Guelph Accessibility Conference. Though he did not demo it, he mentioned briefly that the table plugin provided a way to generate table header IDs and the associated headers for data cells for multiheader rows/columns tables.

I'm not having any luck finding details on how that's done. Can someone point me to the appropriate docs or code. thx greg

**Comment by LaurentGoderre** [comment]
@duboisp is that done with the table validator?

**Comment by pjackson28** [comment]
Here is the table validator URL: http://wet-boew.github.io/v4.0-ci/demos/tablevalidator/tablevalidator-en.html

**Comment by gregrgay** [comment]
Yes, tablevalidator is what I'm looking for. 
thx

**Comment by duboisp** [comment]
Here the javascript code that actually perform the table analysis: https://github.com/wet-boew/wet-boew/blob/master/src/plugins/deps/tableparser.js

The table validator are just interpreting the result from that analysis in order to add IDs/headers.
