### ISSUE TITLE
oxford variant

### ISSUE THREAD

**Issue by joejoseph00** [wet-boew/wet-boew#6822]
A federal government client not subject to web renewal wishes to have a theme that looks and functions more like the university of oxford theme however would like to take advantage of the great work that has been done in wet-boew.

I'm looking at forking version 10 of one of the sub themes, not sure which sub theme would be the easiest to fork, or which version would be the best to use (perhaps I should fork the latest version of one of the existing variants.)

Or, one might just try to do this after using one of the existing themes as a base theme and do a lot of overrides.

See the oxford university website, it's got some nice touches like the scrolldown where the menu stays at the top and the page continues scrolling down.  Also the fonts are very beautiful, it's using the google font api.

http://www.ox.ac.uk/

**Comment by LaurentGoderre** [comment]
You should probably use the theme generator to start a new theme from scratch. You can copy over code from the base theme or other themes when appropriate.

**Comment by joejoseph00** [comment]
Ok, hmm, I didn't know that there was a theme generator for wetkit.  I'll try to find some documentation on this theme generator that you speak of, thanks for the tip.

**Comment by LaurentGoderre** [comment]
https://github.com/wet-boew/generator-wet-boew-theme

**Comment by joejoseph00** [comment]
ok, thanks for the link,  after yanking chains I finally got networks to open up ports and was able to run everything including yo wet-boew-theme successfully inside my dev VM.

"yo" then grabbed (using git) what looks to be a minimalist wet-boew template source files in src folder and I guess compiled this into a site folder is what it looks like.  Inside are some hbs files (first time I see this type of file, looks like they contain a lot of dashes and some text followed by what looks like html tagged text in a file that contains no body or head or style tag.

I'll have to dig more and see if there's some developer guides.  So far all I see is the readme.md
https://github.com/wet-boew/generator-wet-boew-theme/blob/master/README.md

So this would be easier than forking off say the "Canada" theme and trying to make an oxford variant?

**Comment by joejoseph00** [comment]
the "yo" script just dropped everything into pwd , this turned my home directory into a chaotic mess.  I re-ran it in a fresh folder.  I would have probably expected to have been prompted for a destination folder but alas, it is ok, just have to clean up my home folder.  I see this:
bower.json
.bowerrc
.editorconfig
.gitignore
Gruntfile.coffee
.jshintrc
lib
node_modules
package.json
site
src
.travis.yml

**Comment by LaurentGoderre** [comment]
The assumption is that the developer runs this inside a git repository. This is why it doesn't ask for a location.

The site folder contains what is needed to generate the HTML. It uses HandleBars (.hbs) for templating and it is being generated by Assemble.

The src folder contains the SCSS structure to add your responsive designs and an optinal JavaScript file in case you have theme specific code.

To compile, you need to run the grunt command which will place the result in a folder called dist

**Comment by joejoseph00** [comment]
Hi Laurent, thanks for the tips.  

According to the docs it says to run
"yo wet-boew-theme"

, but does not say to run this in a git repository.  

It looks to me that "yo wet-boew-theme" creates something similar to what is found in "wet-boew/theme-base"?

So I modify the .hbs files, the SCSS files in the src folder and optional JavaScript 

then after this I run the grunt command which will place the result in a folder called dist.

However from what I know of the dist folder is that it contains flat html files.  I'm not interested in flat html files, all I want is to modify the SCSS classes and javascript so that I can create an oxford variant for use with the drupal wetkit distro.  The Drupal wetkit distro does not really use the dist folder except for 404 error messages and we're not too concerned about theming 404 messages other than the text contents.

What I've already done in my tests is litereally copied one of the 5 base themes in the libraries folder and then integrated this with Drupal.  However I was hoping to do this according to your build standards so that I could maintain future compatibility and track changes upstream with your changes.  Just trying to think of a way to manage this the easiest way possible.

**Comment by joejoseph00** [comment]
What I want is an oxford variant using your coding standards, so that I can have this oxford variant in my libraries folder.  I've already patched the drupal distro to handle this as a 6th theme so I can easily switch between themes.  What I'm trying to figure out is how to do this using your build and coding standards and how to fork this in a way that I can maintain it and refactor future enhancements that you guys make upstream on the future 4.0.x versions.  Right now I think 4.0.14 is in development, lots of changes comming it seems, I'm not too concerned about the dist folder, it's a nice to have to look at for examples but drupal doesn't really care about it and maybe the 404 error pages and a splash page might be the only things that concern my use cases.  What matters to me is the javascript and sass scss whatever css , ideally this should remain in the same folder structure so that my themes can find the files they're programmed to look for.  It is expected that these files should be in predictable places.  Then on top of that I'm looking on how to fork this in a way that will be maintainable.  I am trying to wrap my brain around your build process, so now that I know that these hbs files are for creating flat html in the dist folder this will save me some time.

**Comment by LaurentGoderre** [comment]
Perhaps the new structure we are creating that will be out shortly will make it easier to understand. I also recommend building your theme in a static way using the HBS and layer adapt it to Drupal. This will allow using the theme on other platform or applications.

Also, I would be quite surprised if the Drupal Distro didn't use the dist folder, otherwise none of the theme would work. Perhaps the distro reorganizes the files around but it definitely uses it.

**Comment by joejoseph00** [comment]
Hmm, looks like the "yo wet-boew-theme" command fails in two places

it fails  on bower.json

and when running grunt it aborts on ie8-bootstrap
Running "sass:all" (sass) task
Warning: /src/ie8-wet-boew.scss:7: error: file to import not found or unreadable: "../lib/wet-boew/src/base/ie8-bootstrap"
 Use --force to continue.

Aborted due to warnings.

seeing as I don't care about ie8 I ran 
"grunt --force"

this time it builds much more, then fails on index-en.html
Warning: No string for key 'tmpl-skip-cont' for language 'en' Used --force, continuing.
Warning: No string for key 'tmpl-skip-cont' for language 'en' Used --force, continuing.

Execution Time (2015-06-04 13:40:33 UTC)
checkDependencies:all   20ms  ▇▇▇▇▇ 2%
copy:assets             12ms  ▇▇▇ 1%
sass:all                 9ms  ▇▇▇ 1%
autoprefixer:modern     71ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 9%
autoprefixer:oldIE      17ms  ▇▇▇▇▇ 2%
cssmin:dist             21ms  ▇▇▇▇▇▇ 3%
copy:js                 13ms  ▇▇▇▇ 2%
uglify:dist             44ms  ▇▇▇▇▇▇▇▇▇▇▇ 5%
assemble:demos         580ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 71%
Total 812ms

I am just wondering what it is I just built, is it something similar to wet-boew/theme-base ?

So I then looked at the folder structure and it built something but it wasn't what I was expecting.

Folder structure as generated by 
"yo wet-boew-theme"
and 
"grunt --force"

dist
node_modules
site
src


this differs from the wet-boew libraries significantly.

Version 4.0.10 of the wetboew libraries is 
ajax
assets
css
demos
docs
fonts
js

...

I just read your comment, looks like a major re-write for the wetkit_bootstrap module if this is the new way .

**Comment by joejoseph00** [comment]
I think all a CMS really cares about is where to find the assets, the js files and where to find the css files.

**Comment by joejoseph00** [comment]
ok, so major changes in the folder structure for 4.0.13 and beyond.  Good to know.

**Comment by joejoseph00** [comment]
I was hoping to find an easy way to refactor future changes but I'm not sure if thats possible, probably just have to choose a version and hope that it holds up at least until our project is done (about 14 months)

**Comment by LaurentGoderre** [comment]
v4.0.15 should solve all this. Btw, is your generator-wet-boew at the latest version? I fixed thos issues before.

**Comment by LaurentGoderre** [comment]
Actually, the first error caused the second. Bower pulls in the WET dependencies so by failling you are missing all the files needed to build. Try running `grunt init`

**Comment by joejoseph00** [comment]
ok I'll try that  thanks again.

**Comment by joejoseph00** [comment]
Looks like I'll have to update the generator-wet-boew , so I'll have to look at the install instructions again. 

Grunt init says:
Running "hub:wet-boew" (hub) task
>> No Gruntfiles matched the file patterns: "lib/wet-boew/Gruntfile.coffee"
Warning: No Gruntfiles matched any of the provided file patterns Use --force to continue.

Aborted due to warnings.

**Comment by LaurentGoderre** [comment]
run the install command again and it will update. If it fails when running yo wet-boew-theme, generally running grunt init after fixes it.

**Comment by joejoseph00** [comment]
ok, so 
sudo npm uninstall generator-wet-boew-theme
and then:
sudo npm install -g generator-wet-boew-theme

gives me the same version 4.0.13 that I uninstalled and the same problem again, version 4.0.13 seems to be missing stuff.

Is there a step that I missed?

I ran grunt init and it gave me the same message, 

Running "hub:wet-boew" (hub) task
>> No Gruntfiles matched the file patterns: "lib/wet-boew/Gruntfile.coffee"
Warning: No Gruntfiles matched any of the provided file patterns Use --force to continue.

Aborted due to warnings.

**Comment by joejoseph00** [comment]
trying again:
sudo npm uninstall generator-wet-boew-theme
npm WARN uninstall not installed in /home/d/test3/node_modules: "generator-wet-boew-theme"
[d@localhost test3]$ npm install generator-wet-boew-theme
npm WARN package.json @4.0.13 No description
npm WARN package.json @4.0.13 No repository field.
npm WARN package.json @4.0.13 No README data
npm WARN engine yo@1.4.7: wanted: {"node":">=0.10.0","npm":">=2.8.0"} (current: {"node":"0.10.38","npm":"1.4.28"})

**Comment by joejoseph00** [comment]
Yeoman Doctor message says: Everything looks all right!

but still version 4.0.13

**Comment by LaurentGoderre** [comment]
Hmmm...perhaps I didn't release v4.0.14, let me check

**Comment by joejoseph00** [comment]
ok, I'll try again after the check

**Comment by LaurentGoderre** [comment]
I will release it shortly

**Comment by LaurentGoderre** [comment]
Ok, I just released v4.0.14

**Comment by joejoseph00** [comment]
ok, I now get v4.0.14 
sudo npm uninstall -g generator-wet-boew-theme
sudo npm install -g generator-wet-boew-theme
this works

then when I run yo wet-boew-theme

> @4.0.14 postinstall /home/d/test5
> bower update

bower                         EINVALID Failed to read /home/d/test5/bower.json

Additional error details:
No name property set

I get a Failed at @4.0.14 postinstall script

then when I run "grunt init" , I get

 No Gruntfiles matched the file patterns: "lib/wet-boew/Gruntfile.coffee"
Warning: No Gruntfiles matched any of the provided file patterns Use --force to continue.

Aborted due to warnings.

**Comment by joejoseph00** [comment]
It's looking in lib/wet-boew, but the coffee file is in the root of the stuff where the "yo wet-boew-theme" puts it

looks like the path changed

**Comment by joejoseph00** [comment]
Laurent, can you please test this on your end?

**Comment by joejoseph00** [comment]
I created a lib/wet-boew folder and copied the coffee file to it and re-ran grunt init but got a new error unable to read package.json.

Then I copied the package.json to the lib/wet-boew folder and this time something is happening.  The only errors I get now is site/layouts/default.hbs not found.

Execution Time (2015-06-04 16:06:57 UTC)
checkDependencies:all   23ms  ▇▇ 3%
copy:wetboew            10ms  ▇ 1%
autoprefixer:modern     62ms  ▇▇▇▇ 9%
autoprefixer:oldIE      24ms  ▇▇ 3%
uglify:dist              8ms  ▇ 1%
assemble:demos         544ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 76%
Total 712ms

curiously, I searched for default.hbs and it exists in site/layouts

find . -name default.hbs
./site/layouts/default.hbs
./node_modules/assemble/test/fixtures/layouts/default.hbs
./lib/wet-boew/node_modules/assemble/test/fixtures/layouts/default.hbs

a couple of minor things to resolve upstream and it should be good.  Let me know if you can fix this?

Thanks

**Comment by LaurentGoderre** [comment]
It wont work until you resolve your bower version. WHat do you get when you run `bower -v`?

**Comment by joejoseph00** [comment]
bower -v
1.4.1

**Comment by joejoseph00** [comment]
what version of bower should I have?

**Comment by LaurentGoderre** [comment]
It doesn't really matter but for some reason your bower doesn't seem to work. What happens if you try to rune bower install?

**Comment by joejoseph00** [comment]
Hi Laurent, ok, figured out what the problem is. When running "sudo npm install -g generator-wet-boew-theme" the generator suggests a name, and it shows up in cyan blue, I hit "enter" thinking that this was a default value yet it was expecting me to type something.  So the bower.json file got written with an empty string for the name value instead of taking what I thought was the default.

So I edited the bower.json file and replaced the name value of empty string with some example name and then the script runs.  So what I'll do is re-run the generator-wet-boew-theme and this time populate the values instead of hitting <[enter]> on what I previously assumed was a default.

So yes, now that the version is 4.0.14 it is building now.

Now I just have to figure out what to do with this.

Thanks for your assistance,

**Comment by LaurentGoderre** [comment]
Let me know if you run into another issue

**Comment by joejoseph00** [comment]
I tried first grunt, but had to run ndm install first
now I've taken the GCWeb theme, and am able to run grunt, the first thing I did was change the accent-blue in the _variables.scss to something else.  what an improvement!  compiled it, and with one change to that variable file everything was fixed up.
nice, going to have fun playing with this now.
