### ISSUE TITLE
Date picker allows a date to be selected when input is disabled

### ISSUE THREAD

**Issue by firowind** [wet-boew/wet-boew#6823]
The date picker http://wet-boew.github.io/v4.0-ci/demos/datepicker/datepicker-en.html allows a date to be entered even when the field is disabled.

**Comment by LaurentGoderre** [comment]
Nice catch!!

**Comment by hsrudnicki** [comment]
@firowind @LaurentGoderre : Are you ready to close this issue?

**Comment by hsrudnicki** [comment]
Due to no further discussion/status updates, this issue made "Going Stale" to close as resolved/fixed or if otherwise?  
Please update this issue's status, thank you
