### ISSUE TITLE
IE 8 SCRIPT5: Access is denied. error on local computer

### ISSUE THREAD

**Issue by Makkurokurosuke** [wet-boew/wet-boew#6824]
I downloaded "Government of Canada Web Usability" v4.0.14 from
http://wet-boew.github.io/wet-boew/docs/versions/dwnld-en.html.

When I browsed index-en.html on IE8, I get the following errors and it does not display the page properly. Is there any way to fix the issues such as by changing browser setting?

SCRIPT5: Access is denied. ie8-wet-boew.min.js, line 9 character 259
SCRIPT5009: 'wb' is undefined ie8-wet-boew2.min.js, line 7 character 2
SCRIPT5009: 'wb' is undefined ie8-wet-boew2.min.js, line 7 character 2
SCRIPT5009: 'wb' is undefined theme.min.js, line 6 character 5
SCRIPT5009: 'wb' is undefined theme.min.js, line 6 character 5
XML5632: Only one root element is allowed. sig-en.svg, line 1 character 1
XML5632: Only one root element is allowed. wmms.svg, line 1 character 1

**Comment by LaurentGoderre** [comment]
You should try to run the files from a web server intead.

**Comment by Makkurokurosuke** [comment]
Thank you for the quick response. It works if I run the files from a web server. Could you tell me why it works from a web server? Is it a file permission issue?

**Comment by LaurentGoderre** [comment]
Most likely

**Comment by hsrudnicki** [comment]
@Makkurokurosuke @LaurentGoderre : Can this issue be closed?

**Comment by LaurentGoderre** [comment]
I believe so. Please reopen if it's still an issue.
