### ISSUE TITLE
Testing with Microsoft Edge

### ISSUE THREAD

**Issue by thomasgohard** [wet-boew/wet-boew#6825]
This thread to is start planning for testing with Microsoft Edge, which is expected to be released in late July.

- [ ] How can we get a copy before it's released?
- [ ] Can we get testing VMs like for Internet Explorer from modern.ie?
- [ ] Do services like SauceLabs have Microsoft Edge instances?

cc/ @pjackson28 @LaurentGoderre @zachfalsetto

**Comment by LaurentGoderre** [comment]
I doubt we will be able to get VMs for recent MS browsers. These VM is Microsoft way to help people update their legacy apps. Our best bet is to look at SauceLabs.

**Comment by EricDunsworth** [comment]
It looks like Microsoft does do a decent job of adding VMs for their latest browsers/OSes. On [modern.ie VMs page](http://dev.modern.ie/tools/vms/), I'm seeing combos as recent as IE11 + Windows 8.1. However, they might not be super quick to launch them... When IE11 was first launched, it seems to have taken 2 months for modern.ie VMs to be added for it.

There's also an [Azure RemoteApp page on modern.ie](https://remote.modern.ie/) that claims it can be used to test the "latest version of Internet Explorer" on Windows 10 Technical Preview... Not sure if that's just a very generic way of referring to the ability to test whatever Microsoft's latest browser happens to be (like Edge) on an up-to-date preview build of Windows 10.

**Comment by hsrudnicki** [comment]
@EricDunsworth @LaurentGoderre : Are you ready to close this issue or otherwise?

**Comment by hsrudnicki** [comment]
Made "Going Stale" to close this issue as resolved or if otherwise?
Either way, please update this issue's status, thank you

**Comment by hsrudnicki** [comment]
Based on the above, this can be closed as resolved. If you think otherwise, please update the status of this again, thank you
