### ISSUE TITLE
Details/summary polyfill (expandable/collapsible content): 

### ISSUE THREAD

**Issue by Bgolden67** [wet-boew/wet-boew#6826]
Is there something undocumented regarding forcing the summary/details to open when you print?
in WET3 we applied <code> class="print-open" </code>

Is there something to apply in WET4?

**Comment by Bgolden67** [comment]
i think i answered my question by looking into something else
<code> class="wb-toggle" data-toggle='{"print": "on"}' </code>

is all it takes right?

**Comment by pjackson28** [comment]
Yes, you would need to use something like the toggle plugin (or to implement this manually). The details/summary polyfill just mimics the native browser implementations which do not include this open on print functionality.

**Comment by Bgolden67** [comment]
thank you
