### ISSUE TITLE
Datatables row highlight

### ISSUE THREAD

**Issue by GarthMartin** [wet-boew/wet-boew#6829]
I am trying to  highlight a specific row in a datatable as per the API examples on http://datatables.net/reference/type/row-selector#
specifically the use of integer as the row id to highlight.  Using their code pretty much verbatim, 

```javascript
var table = $('#example').DataTable(); // Find indexes of rows which have `Yes` in the second columnvar indexes = table.rows().eq( 0 ).filter( function (rowIdx) {    return table.cell( rowIdx, 1 ).data() === 'Yes' ? true : false;} ); // Add a class to those rows using an index selectortable.rows( indexes )    .nodes()    .to$()    .addClass( 'highlight' );
```
I am able to select the row I want (it's in the indexes array) but the actual call to add the highlight class does nothing.  If I hardcode the row I want in the last line, it works fine.  Does the version of Datatables in WET support this type of selector on rows()?

Thanks,

**Comment by GarthMartin** [comment]
Sorry, preview was not working....here is the code again - my version (above is the code from datatables.net)
```javascript
var table = $('#CommitteeList').DataTable();
var indexes = table.rows().eq(0).filter(function (rowIdx) { return table.cell(rowIdx, 0).data() == duplicateCommitteeId ? true : false; });
table.rows(indexes).nodes().to$().addClass('highlight');
```

**Comment by pjackson28** [comment]
@GarthMartin Wouldn't it be easier (and faster) to skip using DataTables for this purpose and just use straight jQuery? For instance you could do something like the following:
```js
$( "td:contains( '" + duplicateCommitteeId + "' )" ).parent().addClass( "highlight" );
```
It would be even easier and faster if you had the id as an id attribute on the row or the cell, which would also make it easier to use vanilla JS.

**Comment by GarthMartin** [comment]
Good point.  I have the id in a hidden column.  Might be easier.

Thanks,

**Comment by hsrudnicki** [comment]
@GarthMartin @pjackson28 : Can this issue be closed?

**Comment by hsrudnicki** [comment]
Due to the above, this issue labeled "Going Stale" and closed as resolved.
If otherwise, please update this issue's status again, thank you
