### ISSUE TITLE
Marker styles in GeoMap using KML files

### ISSUE THREAD

**Issue by moonaa** [wet-boew/wet-boew#6830]
Hello,
I have a KML filling a GeoMap. I am trying to write some conditionals rules using the style attributes but can't get it to work, no marker at all appears. 

 style: {
            type: 'unique',
            field: 'UBI',
        init: {
            '30000420': {'pointRadius' : '6', 'fillColor' : 'green', 'strokeColor':'green' },
            '30000421': {'pointRadius' : '6', 'fillColor' : 'red', 'strokeColor':'red' }
        },
        select: {'fillColor' : '#666666', 'pointRadius' : '15'}
        }, 

The only way I can make the markers appears with the style attributes is without any type of style "rules" or "unique":
    style: {
            type: 'symbol',
            init: { 'pointRadius': '15', 'externalGraphic': 'data/marker.png' },
            select: { 'pointRadius': '15', 'externalGraphic': 'data/selected.png' }
}

Am I doing something wrong?

Thank you

**Comment by LaurentGoderre** [comment]
@jvanulde please answer

**Comment by hsrudnicki** [comment]
Are you ready to close this issue ?

**Comment by jvanulde** [comment]
@LaurentGoderre this is addressed in PR 6803.

**Comment by hsrudnicki** [comment]
Based on the above, this issue labeled "Going Stale" and closed.
