### ISSUE TITLE
Date picker not supported with Struts 1

### ISSUE THREAD

**Issue by firowind** [wet-boew/wet-boew#6832]
Most of CRA uses Struts 1 but doesn't support an input of type "date" although I found a quick fix.
Use a ```<html:text property="startdate" styleId="datepicker"/>```
and change the input type with jQuery ```$("#datepicker").attr("type","date");```

**Comment by LaurentGoderre** [comment]
Couldn't you use straight HTML for the input?

**Comment by firowind** [comment]
Yes, I can just use straight html.
I was using it wrong.

Thanks

**Comment by dravas-nat** [comment]
@firowind : if you are working at CRA, please contact Dev Center as we have implemented a fix for this problem. thanks!
