### ISSUE TITLE
Validation of input type "file" behaves differently than others

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/wet-boew#6834]
This is minor, but it was brought to my attention that the validation of input type="file" behaves differently than others.  For example, on the [Form validation page](http://wet-boew.github.io/v4.0-ci/demos/formvalid/formvalid-en.html), the required field error message is removed on most controls as soon as the user begins typing.  For the file input it is not removed when the user selects a file to upload but only disappears when the user moves control off the field.

I did find one issue on the jQuery forum about this:  https://forum.jquery.com/topic/jquery-validation-on-input-type-file

Can anything be done?

**Comment by hsrudnicki** [comment]
Can be this issue closed ?

**Comment by RobJohnston** [comment]
@hsrudnicki, You're caught-up to this week's issues.  At this rate, you'll be out of a job by the end of this afternoon.  Congrats!  

Let's give it a bit of time to see if anybody comes up with something clever.

**Comment by hsrudnicki** [comment]
@RobJohnston : fine :+1:

**Comment by hsrudnicki** [comment]
Made "Going Stale" to close this issue as resolved or otherwise?  
Either way, please update this issue's status, thank you

**Comment by hsrudnicki** [comment]
Does this remain an issue? Please update again the status of this issue, in regards to the referenced issue, for the current year, thx

**Comment by hsrudnicki** [comment]
Additionally, see the issue with number: 6245 if applicable

**Comment by kpduncan** [comment]
@RobJohnston  @hsrudnicki  What I think we need for file type is a method like `data-rule-types="[.pdf , .doc]"` and maybe `data-rule-maxsize="3000"`. I could work on this.

**Comment by RobJohnston** [comment]
@kpduncan For the types, one could write `data-rule-extension="pdf|doc"`.  That works now.

For the size, I don't think there is something like `data-rule-maxsize`.  I like it.  In the past, I've used the class `fileMaxSize` with a validator (example for ASP.Net):

```js
//Limit an individual file to 2MB.
jQuery.validator.addMethod("fileMaxSize", function (value, element) {
  var numFiles = $("#<%=FileUpload1.ClientID%>")[0].files.length;
  var iSize = 0;
  for (var i = 0; i < numFiles; i++) {
    iSize = ($("#<%=FileUpload1.ClientID%>")[0].files[0].size / 1024 / 1024); 
    if (Math.round(iSize * 100) / 100 > 2.0) {
      return false;    
    }
  }
return true;
}, "Document size must not exceed 2 MB.");
```

But neither of those solves this very minor issue.

**Comment by kpduncan** [comment]
@RobJohnston Issue with extension is it vague in what is allowed, but I guess you can add a that information under the label and for accessibility use aria-describedby so it reads the extra information to user.

**Comment by RobJohnston** [comment]
@kpduncan It's the jQuery Valdation [Extension method] (https://jqueryvalidation.org/extension-method/).  

From the [.rules() page] (https://jqueryvalidation.org/rules/): 

> Both rules and messages can be specified using data attributes, using data-msg (a generic, not-method specific message), `data-msg-[method]` and `data-rule-[method]`.

Another reference with a list of rules:  [Using the jQuery Validate Plugin with HTML5 Data Attribute Rules] (http://johnnycode.com/2014/03/27/using-jquery-validate-plugin-html5-data-attribute-rules/)

**Comment by kpduncan** [comment]
This works with regular file inputs. I tested on HTML 5 multiple (which also only works in as low as IE 10) and didn't work, but that would not really be a wet issue. Here what I came up with:

```javascript

$.validator.addMethod( "maxsize", function( value, element, param ) {
	var i;
	for ( i = 0; i < element.files.length; i++ ) {
		if(element.files[i].size <= (1048576 * param)) {
			return true;
		}
	}
	return false;
}, $.validator.format( "Documents size must not exceed {0} mb" ) );

a.validator.addMethod("maxsize",function(a,b,c){var d;for(d=0;d<b.files.length;d++)if(b.files[d].size<=1048576*c)return!0;return!1},a.validator.format("Documents size must not exceed {0} mb"))

```
Thanks for the information also.

**Comment by RobJohnston** [comment]
There's an open pull request at jQuery Validation for this very thing (https://github.com/jzaefferer/jquery-validation/pull/1512/files).  

But we're really getting off topic of the original issue.

**Comment by hsrudnicki** [comment]
So, can be this closed as resolved or otherwise? 
[ As already discussed, also http://stackoverflow.com/questions/20929355/jquery-validate-input-file-type  supports using of the rules method, and another discussion about the problem with an input type="file" on http://www.quirksmode.org/dom/inputfile.html that may be useful in resolving this ]

**Comment by kpduncan** [comment]
@hsrudnicki  No there is an issue. Reading more into the issue I found another issue. Sometimes file uploads require multiple input fields and the name to be the same. When validating it treats them the same, but only provides an error alert for one and form well submit with only one populated. While looking into this I discovered that file inputs are validating only when they are focused (not clicked/exited).

**Comment by hsrudnicki** [comment]
This remains still an open issue, as agreed, and please keep the status of this updated in near future, thank you

**Comment by kpduncan** [comment]
@RobJohnston Maybe we need a custom validation method for required file input areas.

**Comment by kpduncan** [comment]
This is what I have so far.
```javascript

( function() {

	function findFiles( method, element, params ) {
		var number = 0;
		$("#upload input[type=file]").each(function() {
			var value = $(this).val();
			var name = $(this).attr("name");
			if(value && name === $(element).attr("name")) {
				number++;
			}
		});
		switch(method) {
	    	case 'min':
		    	if(n >= params) {
		    		return true;
		    	}
		        break;
		    case 'max':
		    	if(n <= params && n > 0) {
		    		return true;
		    	}
		        break;
		    case 'range':
		    	if(n >= params[0] && n <= params[1]) {
		    		return true;
		    	}
		    	break;
		    case 'limit':
		    	if(n == params){
		    		return true;
		    	}
		    	break;
		}
		return false;
	}

	$.validator.addMethod( "fileMinimum", function( value, element, params ) {
		return findFiles( 'min', element, params );
	}, $.validator.format( "Please attach at least {0} document(s)" ) );

	$.validator.addMethod( "fileMaximum", function( value, element, params ) {
		return findFiles( 'max', element, params );
	}, $.validator.format( "Please attach at no more then {0} document(s)" ) );
	
	$.validator.addMethod( "fileRange", function( value, element, params ) {
		return findFiles( 'range', element, params );
	}, $.validator.format( "Please attach between {0} and {1} document(s)" ) );
	
	$.validator.addMethod( "fileLimit", function( value, element, params ) {
		return findFiles( 'limit', element, params );
	}, $.validator.format( "Please attach {0} document(s)" ) );
	
}() );

```
The issues I got to work out now is blur/focus when a file is added. Also got to work out the issue with inputs and same name.

**Comment by kpduncan** [comment]
I believe the jQuery method above well work for must situations. For my situation it works except I need another method:
```javascript
/**
 * Function to focus duplicate input
 */
function focusInputs(element){
	$("form input[type=file]").each(function() {
		if($(this).attr("id") === element){
			$(this).blur().focus();
		}
	});
};
```
This is called using the `onclick` method of the form button. Here is the html for clarification:
```html
<div class="form-group">
<label for="file1" class="required"><span class="field-name">English File</span></label>
<input id="file1" class="form-control" name="fileUpload" type="file" aria-describedby="#english-pdf" data-rule-extension="pdf" data-rule-filelimit="2" data-rule-maxsize="50"/>
<span id="english-pdf"><small>Well only accept english pdf files no larger then 50 MB./small></span>	
</div>
<div class="form-group">
<label for="file2" class="required"><span class="field-name">French File</span></label>
<input id="file2" class="form-control" name="fileUpload" type="file" aria-describedby="#french-pdf" data-rule-extension="pdf" data-rule-filelimit="2" data-rule-maxsize="50"/>
<span id="french-pdf"><small>Well only accept french pdf files no larger then 50 MB.</small></span>	
</div>
<div class="form-group">
<button class="btn btn-md btn-success" type="submit" onclick="focusInputs('file2');" role="button"><s:text name="adm.label.uld" /></button>
</div>
```

**Comment by kpduncan** [comment]
@RobJohnston Also that pull request was closed the person opened it no longer works with the team and had no interest in continuing the work they start. I have no done any request so some assistance would be  appreciated.

**Comment by RobJohnston** [comment]
A upstream fix for [jQuery Validation] (https://github.com/jzaefferer/jquery-validation/), continuing the maxsize pull request, would be my advice.  Maybe start by reading the GitHub docs to fork a repo:  https://help.github.com/articles/fork-a-repo/

**Comment by cybersubtype** [comment]
I have an active issue open for discuss on jQuery Validation. Can be view [here](https://github.com/jzaefferer/jquery-validation/issues/1869). I guess since this is now up-to them to help me work out the bugs and wither they want to support it. I guess in mean time @hsrudnicki can close this.

**Comment by cybersubtype** [comment]
I get the impression this won't be worked on by jQuery Validation. Anyone who interested in improving this they can view what I have here: https://www.cybersubtype.ca/apps/wet-demos/form-validation/file/

**Comment by cybersubtype** [comment]
jQuery Validation team has no interest in changing the application to work with multiple fields with the same name there been a known fix for over a year and no change. As for file input types their is no interest in updating this or adding additional library. If you are seeking a solution it well have to be changed locally for your application. Please view issue #7680 for the fix that allows inputs with same name. If just interested in the file validation methods view: https://www.cybersubtype.ca/apps/wet-demos/form-validation/file/.

**Comment by cybersubtype** [comment]
This is issue can now be closed.

**Comment by cybersubtype** [comment]
@RobJohnston @hsrudnicki This issue can now be closed.

**Comment by kodecount** [comment]
@sarasuri @nschonni @masterbee I believe issue #6834 and #7554 can be closed. These are dependent on jQuery validation group. I discussed the issue with them. Currently their is no way to cleanly fix this. If you want this issue fixed you'll have to use a around about method found here: jzaefferer/jquery-validation#997 (this is from 2014).

**Comment by kodecount** [comment]
@RobJohnston @LaurentGoderre I believe issue #6834 and #7554 can be closed. These are dependent on jQuery validation group. I discussed the issue with them. Currently their is no way to cleanly fix this. If you want this issue fixed you'll have to use a around about method found here: jzaefferer/jquery-validation#997 (this is from 2014).

**Comment by RobJohnston** [comment]
Based on the last comment, I'll close this.  It wasn't of great concern to me anyway (it was the boss's problem).
