### ISSUE TITLE
TBS contact responsible for WET?

### ISSUE THREAD

**Issue by annewoods** [wet-boew/wet-boew#6838]
Hello there,

My name is Anne Woods and I work in the IP Office at NRCan.  I am trying to identify the specific program/policy area in TBS with responsibility for the WET product.

I am also hoping to identify the IP and/or legal advisor that reviewed the MIT licence and GitHub Terms of Service (ToS).

I have some clients that would like to use GitHub for an OSS project and we are researching the various contracts, licences and policy implications.  We want to know how other Departments are handling this sort of thing.

Are you able to help put me in touch with these folks in TBS?

Regards,
Anne Woods
613-218-0745

**Comment by LaurentGoderre** [comment]
@pjackson28

**Comment by annewoods** [comment]
Thanks!

**Comment by pjackson28** [comment]
Closing issue since provided an answer by phone.
