### ISSUE TITLE
Graphs and charts

### ISSUE THREAD

**Issue by bashour** [wet-boew/wet-boew#6844]
We would like to use the "wb-charts" class on our tables to generate simple graphs however while testing we came across two issues. The first issue is that I couldn't find a way to customize the numbers of the y-axis of my graph as they automatically generated. it is a problem for us as we would like to show what the numbers represent i.e. (percentage or  dollars etc).  

The second issue is that I would like to show the exact value of each bar on the graph and I couldn't find a class to do so. The user would have to expand the long description to find out the exact values of each bar and we find that its not ideal.

Here is an example of what I was trying to achieve
![image-1](https://cloud.githubusercontent.com/assets/12627090/8038141/c2ba364c-0dcf-11e5-87a5-6a746b8175f0.jpg)

And here is what I have achieved using WET 
![image-2](https://cloud.githubusercontent.com/assets/12627090/8038149/c9d7ede8-0dcf-11e5-9c2c-2bad4b75e46d.jpg)

**Comment by LaurentGoderre** [comment]
@duboisp oplease response.

However, with regards to the axis labels, isn't it more common to add that to the title instead of on each label?

**Comment by bashour** [comment]
I suppose I did so in the legend, didn't add it to the title as it would be repetitive, but would be nice to add it to axis as well, I am assuming there is no way of doing that now? how about the second issue?

**Comment by LaurentGoderre** [comment]
I believe you need to user a plugin for that

https://github.com/leonardoeloy/flot-valuelabels/wiki

**Comment by hsrudnicki** [comment]
@bashour @LaurentGoderre : Just by occasion, are you ready or working to close this issue?

**Comment by LaurentGoderre** [comment]
Did you look at the plugin?

**Comment by bashour** [comment]
I did but I am not to sure how to incorporate it with the graph on in the code. maybe some direction would be great :)

**Comment by LaurentGoderre** [comment]
Then we should re-open this issue

**Comment by LaurentGoderre** [comment]
I believe that something like this would work, provided you download the plugin and place it in the `js\deps` folder..

```
window['wb-charts'].plugins = [
    "site!deps/jquery.flot.valuelabels.js",
]
```

Reference: https://github.com/crichard/wet-boew/commit/d5378dbab5da3df03e45127b2d39c01f7e881397

**Comment by duboisp** [comment]
Hi @bashour ,

Here a little step by step that I tested and work with the latest version of WET 4

## 1. 
Download [jquery.flot.valuelabels.js](https://github.com/winne27/flot-valuelabels)

## 2.
Copy the javascript file in the ```js\deps``` folder

## 3.
Insert the following javascript code to load the plugin, thanks @LaurentGoderre 
```xml
<script>
window['wb-charts'].plugins = [
    "site!deps/jquery.flot.valuelabels.js",
]
</script>
```

## 4. 
Use the following data-flot option in your table element to activate the plugin for all your series
```xml
<table class="wb-charts table" data-flot='{ "series": {"valueLabels": {"show":true} } }'>
```

## 5.
Test your chart, it should work :smile: 

----

## Labeling issue work-around
If your y-axis labeling seems to be aligned offside the charts, you will need adjust your ```data-flot``` attribute to deactivate the ```jquery.flot.canvas.js``` plugin. (it's use for providing charts responsiveness)
The table element code will look like
```xml
<table class="wb-charts table" data-flot='{ "series": {"valueLabels": {"show":true}, "canvas": false } }'>
```

## Customizing one specific series
You can customize the valueLabels plugin will be set for each individual series. You can setup the flot setting by adding a ```data-flot``` on the ```<th>``` that represent the title of your series like:
```xml
<th data-flot='{ "valueLabels":{ "align": "right", "fontcolor": "blue" } }'>Enquiries</th>
``` 

## Documentation
See [Flot valuelabels plugin documentation](https://github.com/winne27/flot-valuelabels/wiki) to know which option is supported. For example you only show a label for the maximum value in your series by setting the option ```showMaxValue``` to true. 
```xml 
<th data-flot='{ "valueLabels":{ "showMaxValue": true } }'>Enquiries</th>
```

## Custom label
If you want/need to use a custom label formater function, like ot add the % symbol, you can look at the [wet-boew charts documentation](http://wet-boew.github.io/wet-boew/docs/ref/charts/charts-en.html#functionpreset) to know how to proceed. 

----
Let me know if you need more instruction.

**Comment by bashour** [comment]
Thank you for the info I am going to test it out and let you know if it worked, just have a question, does it work with WET version v4.0.13? or just the latest one?

**Comment by LaurentGoderre** [comment]
The earlliest version for which this is supported is v4.0.12

**Comment by hsrudnicki** [comment]
Based on the above, this issue labeled as "Going Stale" and closed.
If otherwise, please update again this issue's status, thank you
