### ISSUE TITLE
ARCHIVED - Archived information: 

### ISSUE THREAD

**Issue by gdanova** [wet-boew/wet-boew#6846]
http://wet-boew.github.io/v4.0-ci/demos/archived/archived-en.html shows the heading in the alert as "Archived information", but the supporting Documentation page http://wet-boew.github.io/v4.0-ci/docs/ref/archived/archived-en.html shows the code (under How to implement) with a heading of "This page has been archived on the Web".

Which is the correct way to implement?. :confused:

French also, please.

**Comment by LaurentGoderre** [comment]
@thomasgohard

**Comment by hsrudnicki** [comment]
@thomasgohard  @gdanova  @LaurentGoderre : Can be this issue closed or otherwise ?

**Comment by LaurentGoderre** [comment]
It was only opened a couple of hours ago and haven't been answered yet

**Comment by gdanova** [comment]
Please don't close yet. Actually looking for an answer ASAP, at least on what should be in the H2.

**Comment by gdanova** [comment]
OK, glad it wasn't closed. Still looking for an answer to the discrepancy:

"Archived information" or "This page has been archived on the Web".

**Comment by gdanova** [comment]
Still looking for direction on this, as we're aiming to update our Archived banners.

"Archived information" or "This page has been archived on the Web".

**Comment by hsrudnicki** [comment]
Made "Going Stale" to close this issue or otherwise?
Either way, please update this issue's status, thank you

**Comment by gdanova** [comment]
Still seeking direction on this. Please see description in first message.

**Comment by hsrudnicki** [comment]
@MaximMartel : Did you work on the Archived topic? Can be this closed as resolved? Thank you/Merci pour votre réponse

**Comment by gdanova** [comment]
This issue had been made more complex. There are now three different texts to use:
**1**) http://wet-boew.github.io/v4.0-ci/demos/archived/archived-en.html
and
**2**) http://wet-boew.github.io/v4.0-ci/docs/ref/archived/archived-en.html
use identical body text, but the headings are different "Archived information" vs "This page has been archived on the Web". And then
**3**) http://www.tbs-sct.gc.ca/ws-nw/mo-om/ts-st/p9-eng.asp contains different body text, especially in the French.

Still looking for direction on which to use, or should we not worry about it and just replace them all with pre-built components once on Canada.ca?

**Comment by kodecount** [comment]
There is also this one: http://servicecanada.github.io/GCWeb/archived-en.html
