### ISSUE TITLE
Modifications to CSS for fieldset and legend

### ISSUE THREAD

**Issue by claudielarouche** [wet-boew/wet-boew#6847]
Good morning,

I am working on designing forms in WET 4. My forms contains checkboxes and radio buttons. Here is an example of the HTML used: 

<pre><code>
&lt;fieldset&gt;
	&lt;legend class="required" aria-required="true"&gt;
		&lt;span class="field-name"&gt;First Official Language&lt;/span&gt;
		&lt;strong class="required" aria-required="true"&gt;(required)&lt;/strong&gt;
	&lt;/legend&gt;								
	&lt;div class="radio"&gt;
		&lt;label for="lang1"&gt;
			&lt;input type="radio" name="lang" value="English" id="lang1" required="required" aria-required="true"&gt;English
		 &lt;/label&gt;
	&lt;/div&gt;									
	&lt;div class="radio"&gt;
		&lt;label for="lang2"&gt;
			&lt;input type="radio" name="lang" value="French" id="lang2" required="required" aria-required="true"&gt;French
		 &lt;/label&gt;
	&lt;/div&gt;									
	&lt;div class="radio"&gt;
		&lt;label for="lang3"&gt;
			&lt;input type="radio" name="lang" value="N/A" id="lang3" required="required" aria-required="true"&gt;N/A
		 &lt;/label&gt;
	&lt;/div&gt;	
&lt;/fieldset&gt;
</pre></code>

In order to be semantically correct, my radio buttons require a legend. And in order for the error validation to work properly, the whole thing has to be surrounded by a fieldset.

Unfortunately, the legend in WET 4 is styled so that it looks like a heading (see screenshot below taken directly from the <a href="http://wet-boew.github.io/wet-boew/demos/formvalid/formvalid-en.html" target="_blank">working examples</a>):

![screenshot 1](https://cloud.githubusercontent.com/assets/8117634/8061269/18236482-0e98-11e5-922a-ccda801dcdb2.png)

Furthermore, the fieldset has a border-top, making the whole thing look even more like a new heading. I would like my radio button to look like this instead:

![screenshot2](https://cloud.githubusercontent.com/assets/8117634/8061316/3594973e-0e98-11e5-9987-fddfc0be2a89.png)

No border top and character size identical to other labels. 

So my question is:
Is there a way I can change my HTML to achieve the result I am looking for?

If that's not possible, would you be ok if I make a modification to WET? My modification would be done on _base.scss located in \wet-boew\src\base\bootstrap-overrides

<pre><code>
legend {
	border-top: 1px solid #e5e5e5;
	border-bottom: 0;
	float: left;
}

fieldset {
	padding-top: 10px;
	&:first-child {
		border-top: 0;
	}
}

.fixLegend{
	border: none;
	font-size: $font-size-base;
	font-weight: bold;
	margin-bottom: 5px;
}
</pre></code>

The fixLegend is an extra class that we could apply to legends associated with radio buttons and checkboxes.

Let me know what your thoughts are!

**Comment by RobJohnston** [comment]
Wondering if #5797 addresses what you need?

**Comment by claudielarouche** [comment]
Hi Rob,

Yes you're right, looks like the same issue, thanks for pointing this out. I'll close this one and add a comment to #5797.
