### ISSUE TITLE
OAG Canada using WET 4.0.14 (not an issue)

### ISSUE THREAD

**Issue by MikeCA** [wet-boew/wet-boew#6849]
I know this is meant for issues/bug reporting, but I wanted to point out that the OAG website (www.oag-bvg.gc.ca) used a (slightly) customized version of WET 4.0.14 (latest stable) for its whole site and as a key part of presenting the Senators' Expenses report today.

Without the amazing work done by this team, the OAG's Web content would not look half as good, or render so well on both desktop and mobile.

Keep up the great work!

**Comment by LaurentGoderre** [comment]
Thank you for the kind words!

**Comment by hsrudnicki** [comment]
@LaurentGoderre @MikeCA : Can this issue be closed?

**Comment by hsrudnicki** [comment]
Based on the above as 'not an issue', this has been closed. 
If you think of otherwise, please update this issue's status again, thank you
