### ISSUE TITLE
Share Widget Filtering Not Working

### ISSUE THREAD

**Issue by Emil-A** [wet-boew/wet-boew#6851]
https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_14/samples/share-dev.shtml
In the above link there are 2 share buttons that show up above the footer of the page. However there should be 3, but the last "data-wb-share" that passes in an array of social media outlets as the variable filter doesn't work. I don't understand why the button doesn't even display yet the code is just like the documentation below.

http://wet-boew.github.io/wet-boew/demos/share/share-en.html

**Comment by LaurentGoderre** [comment]
You have a JavaScript error. These elements seem to be generated dynamically are they?

**Comment by Emil-A** [comment]
yes, they are being pulled from a javascript closure template

**Comment by claudielarouche** [comment]
So you'll notice that the ones that are working are generating this long HTML:

<pre><code>
&lt;!--Works--&gt;
&lt;div class="wb-share wb-init wb-share-inited" data-wb-share="{&quot;lnkClass&quot;: &quot;btn btn-default&quot;}" id="wb-auto-3"&gt;
	&lt;section id="shr-pg1" class="shr-pg mfp-hide modal-dialog modal-content overlay-def"&gt;
		&lt;header class="modal-header"&gt;
			&lt;h2 class="modal-title"&gt;Share this page&lt;/h2&gt;
		&lt;/header&gt;
		&lt;div class="modal-body"&gt;
			&lt;ul class="list-unstyled colcount-xs-2"&gt;
				&lt;li&gt;&lt;a href="https://bitly.com/a/bitmarklet?u=https%3A%2F%2Fssl-templates.services.gc.ca%2Fapp%2Fcls%2FWET%2Fgcweb%2Fv4_0_14%2Fsamples%2Fshare-dev.shtml" class="shr-lnk bitly btn btn-default" target="_blank"&gt;bitly&lt;/a&gt;&lt;/li&gt;
				&lt;li&gt;&lt;a href="http://www.blogger.com/blog_this.pyra?t=&u=https%3A%2F%2Fssl-templates.services.gc.ca%2Fapp%2Fcls%2FWET%2Fgcweb%2Fv4_0_14%2Fsamples%2Fshare-dev.shtml&n=Content%20page%20-%20Canada.ca" class="shr-lnk blogger btn btn-default" target="_blank"&gt;Blogger&lt;/a&gt;&lt;/li&gt;
				&lt;li&gt;&lt;a href="http://delicious.com/post?url=https%3A%2F%2Fssl-templates.services.gc.ca%2Fapp%2Fcls%2FWET%2Fgcweb%2Fv4_0_14%2Fsamples%2Fshare-dev.shtml&title=Content%20page%20-%20Canada.ca" class="shr-lnk delicious btn btn-default" target="_blank"&gt;Delicious&lt;/a&gt;&lt;/li&gt;
				&lt;li&gt;&lt;a href="http://digg.com/submit?phase=2&url=https%3A%2F%2Fssl-templates.services.gc.ca%2Fapp%2Fcls%2FWET%2Fgcweb%2Fv4_0_14%2Fsamples%2Fshare-dev.shtml&title=Content%20page%20-%20Canada.ca" class="shr-lnk digg btn btn-default" target="_blank"&gt;Digg&lt;/a&gt;&lt;/li&gt;
				&lt;li&gt;&lt;a href="http://www.diigo.com/post?url=https%3A%2F%2Fssl-templates.services.gc.ca%2Fapp%2Fcls%2FWET%2Fgcweb%2Fv4_0_14%2Fsamples%2Fshare-dev.shtml&title=Content%20page%20-%20Canada.ca" class="shr-lnk diigo btn btn-default" target="_blank"&gt;Diigo&lt;/a&gt;&lt;/li&gt;
				&lt;li&gt;&lt;a href="mailto:?to=&subject=Content%20page%20-%20Canada.ca&body=https%3A%2F%2Fssl-templates.services.gc.ca%2Fapp%2Fcls%2FWET%2Fgcweb%2Fv4_0_14%2Fsamples%2Fshare-dev.shtml%0A" class="shr-lnk email btn btn-default" target="_blank"&gt;Email&lt;/a&gt;&lt;/li&gt;
				&lt;li&gt;&lt;a href="http://www.facebook.com/sharer.php?u=https%3A%2F%2Fssl-templates.services.gc.ca%2Fapp%2Fcls%2FWET%2Fgcweb%2Fv4_0_14%2Fsamples%2Fshare-dev.shtml&t=Content%20page%20-%20Canada.ca" class="shr-lnk facebook btn btn-default" target="_blank"&gt;Facebook&lt;/a&gt;&lt;/li&gt;
				&lt;li&gt;&lt;a href="https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=&su=Content%20page%20-%20Canada.ca&body=https%3A%2F%2Fssl-templates.services.gc.ca%2Fapp%2Fcls%2FWET%2Fgcweb%2Fv4_0_14%2Fsamples%2Fshare-dev.shtml%0A" class="shr-lnk gmail btn btn-default" target="_blank"&gt;Gmail&lt;/a&gt;&lt;/li&gt;
				&lt;li&gt;&lt;a href="https://plus.google.com/share?url=https%3A%2F%2Fssl-templates.services.gc.ca%2Fapp%2Fcls%2FWET%2Fgcweb%2Fv4_0_14%2Fsamples%2Fshare-dev.shtml&hl=en" class="shr-lnk googleplus btn btn-default" target="_blank"&gt;Google+&lt;/a&gt;&lt;/li&gt;
				&lt;li&gt;&lt;a href="http://www.linkedin.com/shareArticle?mini=true&url=https%3A%2F%2Fssl-templates.services.gc.ca%2Fapp%2Fcls%2FWET%2Fgcweb%2Fv4_0_14%2Fsamples%2Fshare-dev.shtml&title=Content%20page%20-%20Canada.ca&ro=false&summary=&source=" class="shr-lnk linkedin btn btn-default" target="_blank"&gt;LinkedIn®&lt;/a&gt;&lt;/li&gt;
				&lt;li&gt;&lt;a href="http://www.myspace.com/Modules/PostTo/Pages/?u=https%3A%2F%2Fssl-templates.services.gc.ca%2Fapp%2Fcls%2FWET%2Fgcweb%2Fv4_0_14%2Fsamples%2Fshare-dev.shtml&t=Content%20page%20-%20Canada.ca" class="shr-lnk myspace btn btn-default" target="_blank"&gt;MySpace&lt;/a&gt;&lt;/li&gt;
				&lt;li&gt;&lt;a href="http://www.pinterest.com/pin/create/button/?url=https%3A%2F%2Fssl-templates.services.gc.ca%2Fapp%2Fcls%2FWET%2Fgcweb%2Fv4_0_14%2Fsamples%2Fshare-dev.shtml&media=&description=Content%20page%20-%20Canada.ca" class="shr-lnk pinterest btn btn-default" target="_blank"&gt;Pinterest&lt;/a&gt;&lt;/li&gt;
				&lt;li&gt;&lt;a href="http://reddit.com/submit?url=https%3A%2F%2Fssl-templates.services.gc.ca%2Fapp%2Fcls%2FWET%2Fgcweb%2Fv4_0_14%2Fsamples%2Fshare-dev.shtml&title=Content%20page%20-%20Canada.ca" class="shr-lnk reddit btn btn-default" target="_blank"&gt;reddit&lt;/a&gt;&lt;/li&gt;
				&lt;li&gt;&lt;a href="http://www.stumbleupon.com/submit?url=https%3A%2F%2Fssl-templates.services.gc.ca%2Fapp%2Fcls%2FWET%2Fgcweb%2Fv4_0_14%2Fsamples%2Fshare-dev.shtml&title=Content%20page%20-%20Canada.ca" class="shr-lnk stumbleupon btn btn-default" target="_blank"&gt;StumbleUpon&lt;/a&gt;&lt;/li&gt;
				&lt;li&gt;&lt;a href="http://www.tumblr.com/share/link?url=https%3A%2F%2Fssl-templates.services.gc.ca%2Fapp%2Fcls%2FWET%2Fgcweb%2Fv4_0_14%2Fsamples%2Fshare-dev.shtml&name=Content%20page%20-%20Canada.ca&description=" class="shr-lnk tumblr btn btn-default" target="_blank"&gt;tumblr&lt;/a&gt;&lt;/li&gt;
				&lt;li&gt;&lt;a href="http://twitter.com/home?status=Content%20page%20-%20Canada.ca%20https%3A%2F%2Fssl-templates.services.gc.ca%2Fapp%2Fcls%2FWET%2Fgcweb%2Fv4_0_14%2Fsamples%2Fshare-dev.shtml" class="shr-lnk twitter btn btn-default" target="_blank"&gt;Twitter&lt;/a&gt;&lt;/li&gt;
				&lt;li&gt;&lt;a href="http://compose.mail.yahoo.com/?to=&subject=Content%20page%20-%20Canada.ca&body=https%3A%2F%2Fssl-templates.services.gc.ca%2Fapp%2Fcls%2FWET%2Fgcweb%2Fv4_0_14%2Fsamples%2Fshare-dev.shtml%0A" class="shr-lnk yahoomail btn btn-default" target="_blank"&gt;Yahoo! Mail&lt;/a&gt;&lt;/li&gt;
			&lt;/ul&gt;
			&lt;p class="col-sm-12 shr-dscl"&gt;No endorsement of any products or services is expressed or implied.&lt;/p&gt;
			&lt;div class="clearfix"&gt;&lt;/div&gt;
		&lt;/div&gt;
	&lt;/section&gt;
	&lt;a href="https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_14/samples/share-dev.shtml#shr-pg1" aria-controls="shr-pg1" class="shr-opn wb-lbx btn btn-default wb-lbx-inited wb-init" id="wb-auto-4"&gt;
	&lt;span class="glyphicon glyphicon-share"&gt;&lt;/span&gt;Share this page&lt;/a&gt;
&lt;/div&gt;
</pre></code>
	
And the one that is not working is simply generating an empty div:

<pre><code>
&lt;!--Not working--&gt;
&lt;div class="wb-share wb-init wb-share-inited" data-wb-share="{&quot;filter&quot;: [&quot;email&quot;, &quot;facebook&quot;, &quot;linkedin&quot;, &quot;twitter&quot;], &quot;lnkClass&quot;: &quot;btn btn-default&quot;}" id="wb-auto-5"&gt;
&lt;/div&gt;
</pre></code>

**Comment by Emil-A** [comment]
yes, but that div should be generating the share modal code :/

**Comment by LaurentGoderre** [comment]
Make sure it is using single quotes around your JSON. otherwise it's a syntax error.

**Comment by Emil-A** [comment]
As it turns out the [share doc] (http://wet-boew.github.io/wet-boew/demos/share/share-en.html) is referencing the [v4_0_15 dev wet-boew.min.js file] (http://wet-boew.github.io/wet-boew/js/wet-boew.min.js). When using the v4_0_14 wet-boew.min.js, the filter parameter for data-wb-share breaks the code when trying to pass in "email". Thus why the div wasn't generating the modal code as it should've.

**Comment by LaurentGoderre** [comment]
Can we close then since it will be included in new release?

**Comment by pjackson28** [comment]
The only thing that is different in v4.0.15 is the ability to filter in the email option (works otherwise and that new addition is flagged as v4.0.15+ in the documentation). 

The issue raised here is a markup issue that is independent of the version (using double quotes instead of single quotes). By using double quotes for both the HTML attribute and the JSON inside you are effectively closing the attribute before WET can get to any of your filtering options. Switching the HTML attribute double quotes to single quotes should fix your issue (note that the JSON must use double quotes which is why single quotes need to be used for the HTML attribute).

So your HTML should be the following to work properly:
```html
<div class="wb-share" data-wb-share='{"filter": ["email", "facebook", "linkedin", "twitter"], "lnkClass": "btn btn-default"}'></div>
```

**Comment by Emil-A** [comment]
Sorry, I didn't see the "email" filtering flagged as v4.0.15+ in the documentation. Everything works now though, thank you.
