### ISSUE TITLE
Terms & Conditions Module?

### ISSUE THREAD

**Issue by aaornrylow** [wet-boew/wet-boew#6858]
Hi,

I'm just wondering if you have an existing plugin or implementation for a "terms and conditions" section (the kind that you can scroll through all the text and then click "I agree" to continue).

If not, how would you recommend going about creating one in WET?

Thanks,
-Aaron

**Comment by LaurentGoderre** [comment]
@thomasgohard wouldn't that be more appropriate for the style guide?

**Comment by hsrudnicki** [comment]
Maybe it's too early, but just by occasion, are you ready to close this issue or otherwise?

**Comment by aaornrylow** [comment]
Thanks.
