### ISSUE TITLE
Plugin Lightbox: position relative supported?

### ISSUE THREAD

**Issue by jvanulde** [wet-boew/wet-boew#6864]
Is it possible to constrain the lightbox overlay to a div?

**Comment by pjackson28** [comment]
It is constrained to a div already. For instance the visible portion is constrained to the mfp-content div and the background overlay is constrained to the mfp-bg div.

**Comment by hsrudnicki** [comment]
Based on the above, are you ready to close this issue?

**Comment by hsrudnicki** [comment]
Made "Going Stale" due to a lack of further status update(s) or otherwise?
Either way, please update this issue's status whether this issue can be closed or otherwise?

**Comment by hsrudnicki** [comment]
@jvanulde : Your question had been answered by @pjackson28, and no further following questions/comments from you, therefore this issue can be closed as resolved.

[If you think otherwise, please again update this issue's status, thank you]
