### ISSUE TITLE
jQuery Autocomplete

### ISSUE THREAD

**Issue by GarthMartin** [wet-boew/wet-boew#6866]
Just wondering if WET is overriding the callbacks on the jquery autocomplete widget?  For some reason I cannot use the normal callbacks for select and focus:
```javascript
select: function(event, ui){...},
focus: function(event, ui){...}
```
but instead had to set them manually:
```javascript
$(".elem").on("autocompleteselect", function(event, ui){...});
$(".elem").on("autocompletefocus", function(event, ui){...});
```

Just curious if there is something like the overrides for the magnific popup.

Thanks,

Garth

**Comment by pjackson28** [comment]
WET doesn't use jQuery autocomplete or any of jQuery UI but that framework has had a history of clashing with other frameworks. Why are you using jQuery UI? It is a very heavy framework with known mobile support issues. We recommend using HTML5 datalist instead to offload the work on the browser and for better performance on mobile (WET provides a datalist polyfill for browsers that lack native support).

**Comment by hsrudnicki** [comment]
Based on the above, are you ready to close this issue?

**Comment by hsrudnicki** [comment]
Based on the above, as well no further discussion/status updates, this issue labeled "Going Stale" and closed.
