### ISSUE TITLE
Sharebar Email 

### ISSUE THREAD

**Issue by q3t** [wet-boew/wet-boew#6875]
Hi,

I am using the version 3.0.14. 
I have an email link to the sharebar (I have put the addEmail to true) and I would like it to not open an empty blank page and just open the email service. 

Is there a way where I could make the email target to be "_top" instead of "_blank"? Or any other way to make it only open the email service. 

Thanks

**Comment by LaurentGoderre** [comment]
Version 3 is no longer supported you should update to v4
