### ISSUE TITLE
Panel with list-group inside a list-group not behaving as expected

### ISSUE THREAD

**Issue by wilkmit** [wet-boew/wet-boew#6879]
The issue is that when i have a panel with a list-group my second list-group within the first list-group picks up on the no border css from a list-group being inside a panel. I can work around it just wanted to point it out so it could possibly be fixed in a later release.

http://jsfiddle.net/n9o9v8r7/

    <section class="panel panel-default">
            <header class="panel-heading">
                 <h1 class="panel-title">Test</h1>
            </header>
            <ul class="list-group">
                <li class="list-group-item">Test 1
                    <ul class="list-group">
                        <li class="list-group-item">Test 1.1</li>
                        <li class="list-group-item">Test 1.2</li>
                        <li class="list-group-item">Test 1.3</li>
                    </ul>
                </li>
                <li class="list-group-item">Test 2</li>
                <li class="list-group-item">Test 3</li>
            </ul>
    </section>

**Comment by hsrudnicki** [comment]
@wilkmit @LaurentGoderre @pjackson28 : Can this issue be closed or otherwise?

**Comment by hsrudnicki** [comment]
Can this issue be closed?

**Comment by wilkmit** [comment]
I would like to see a fix but if it's just a bootstrap issue I can just send it up the chain.

**Comment by LaurentGoderre** [comment]
Perhaps this is by design? What did you expect as a result?

**Comment by wilkmit** [comment]
I expected a child list group styled the same as its parent list group.

**Comment by LaurentGoderre** [comment]
Can you show visually what you mean?

**Comment by wilkmit** [comment]
http://jsfiddle.net/n9o9v8r7/3/

I expected it to look like the example above but when in a panel like in the first JSFiddle I posted.

**Comment by LaurentGoderre** [comment]
Perhaps this should be reported up to Bootstrap

**Comment by hsrudnicki** [comment]
Make "Going Stale" to close this issue as reported to Bootstrap and/or resolved or otherwise?
Either way, please update this issue's status, thank you

**Comment by hsrudnicki** [comment]
Based on the above, can be this issue closed?

**Comment by hsrudnicki** [comment]
This can be closed as resolved based on the above. 
[Additionally, there are online resources: https://www.google.ca/?gws_rd=ssl#safe=strict&q=Panel+with+list-group+inside+a+list-group+ ]
If you think otherwise, please update the status of this again, thank you
