### ISSUE TITLE
Data tables page not rendering in Firefox

### ISSUE THREAD

**Issue by mccannk** [wet-boew/wet-boew#6881]
Just as an FYI the data table functionality (pagination, filtering, etc) doesn't render 
![data_tables](https://cloud.githubusercontent.com/assets/7660079/8258384/79818848-1682-11e5-8047-c2ba0167f1fd.jpg)
on the http://wet-boew.github.io/v4.0-ci/demos/tables/tables-en.html page in Firefox 38.0.5 (see screen capture).

**Comment by pjackson28** [comment]
I just tried with the same browser and it is working fine for me. Could JavaScript be disabled or is Basic HTML version enabled (can tell if there is a "Standard version" link at the top)? You should also check to see if any files didn't download successfully (for instance the jquery JS file may not have loaded).

**Comment by hsrudnicki** [comment]
Based on the above, are you ready to close this issue?

**Comment by mccannk** [comment]
I tried it from home this time and it looks fine.
