### ISSUE TITLE
Tables: ideas, not a bug

### ISSUE THREAD

**Issue by pliz22** [wet-boew/wet-boew#6882]
I have a table, and I am using the datatables plugin.  Everything is fine.
I'm also using a javascript waypoints thing.  Because, some data in the table is slow and there is a lot of it.
So there is a <td> in every <tr> which, when scrolled into view, triggers a waypoint, which fetches data into that <td>.
Everything is ok up to this point.

My question is if anyone has any ideas or suggestions with the following issue i have:
when I sort/reorder the datatable, the waypoints are not triggered and the data does not load.  I suppose because the rows are moved into view, but not with a scroll event or some such event which would trigger the waypoint.

my own simplest solution would be that when clicking a reorder column header, it would reload the page, thus all the rows would be in the DOM and would trigger scroll events (which would trigger the waypoints).

perhaps somethind to do with $.on( 'order.dt', function () {} ); this event?  it would reset the scroll positions of the elements in the DOM when the datatable is reordered.

**Comment by pjackson28** [comment]
What about checking the current scroll position after an order.dt and firing off any waypoints manually that should be fired? Is that possible? Ideally you wouldn't change the scroll position or reload the page at all on a reorder.

**Comment by pliz22** [comment]
I found after a order event do a window.resize. 

Took a few hours to figure out but works well. 

Thanks for giving this some thought 

Sent from Yahoo Mail on Android
