### ISSUE TITLE
Firefox mobile light box and popup showing at the bottom of the screen

### ISSUE THREAD

**Issue by wighawag** [wet-boew/wet-boew#6884]
Hi
Just tested some example and the light box example have the following issue on Firefox mobile: 
The light box/popup appear at the bottom of the screen. It look wrong and to see the picture I had to scroll down

**Comment by hsrudnicki** [comment]
@wighawag @LaurentGoderre : Can this issue be closed or it needs still be investigated?

**Comment by pjackson28** [comment]
@wighawag Could you please post a screenshot of what you are seeing? Note that this may need to be dealt with upstream by Magnific Popup as we rely upon that 3rd party plugin for the Lightbox (we provide a wrapper that overrides/configures portions of what Magnific Popup provides).

**Comment by stephenbe** [comment]
I just tested the lightbox in firefox with this demo : http://wet-boew.github.io/v4.0-ci/demos/lightbox/lightbox-en.html and it's working fine.

@wighawag Can you try the lightbox in the demo and can you tell us if you still see the bug? Could we also get your firefox version and on what OS are you testing?

**Comment by wighawag** [comment]
that's the one I have tested and I just tried again today and got the same issue.
Firefox Version 38.0.5 on Android 4.4.4

I tried the demo on Magific Popup and they work fine.

**Comment by stephenbe** [comment]
@wighawag okay do you have a demo so I can see? If the demo is working well, then it's probably your code that is the problem.

**Comment by wighawag** [comment]
I meant the demo on  http://wet-boew.github.io/v4.0-ci/demos/lightbox/lightbox-en.html is not working on my Firefox (Version 38.0.5 on Android 4.4.4)
but the demo on http://dimsemenov.com/plugins/magnific-popup/ is working fine

**Comment by stephenbe** [comment]
@wighawag okay I just re-tested it, I can now see your bug. 

@pjackson28 seems like the position fixed is not working properly on wet...not sure why though

**Comment by hsrudnicki** [comment]
@pjackson28 @wighawag @stephenbe : Are you ready to close this issue?

**Comment by stephenbe** [comment]
@hsrudnicki no, it has not been resolved. I will give you a few pointers to know when the issue is ready to closed.

1. Was the issue confirmed or denied? If the issue / bug is confirmed, then safe to say that we cannot close this until it is resolved.
2. If the last comment is a question directed to someone, then it cannot be closed until that key person has had a chance to answer.
3. Is there a pull request done againts this issue? Then we will be ready to close as soon as that PR is merged or closed.
4. If the issue has been lingering for months or years, then it's better to ask "what is the status of this issue". Instead of just asking it to be closed.

Hope this helps! :)

**Comment by hsrudnicki** [comment]
@stephenbe : No problem, hopefully in a near future the whole issue template will be updated to reflect better the issue tracking and notification process, now at least it's very appreciative that the status of this issue has just been updated, again thanks for your input and comment.

**Comment by hsrudnicki** [comment]
Based on the above, this issue has been lingering for 5 months, so please update this issue's status again whether this issue can be closed as resolved/fixed or otherwise?

**Comment by stephenbe** [comment]
You guys could use an no carrier bot to issue inactivity in a issue automatically...

http://blog.getbootstrap.com/2015/08/04/no-carrier/

**Comment by hsrudnicki** [comment]
Is this still an issue waiting for an answer to the last comment?  Either way, please update the issue's status, whether this issue can be closed as resolved/fixed or otherwise, thank you

**Comment by hsrudnicki** [comment]
Based on the above, can be this issue closed or otherwise? Please update this issue's status for this year, if not it will be closed, thank you

**Comment by masterbee** [comment]
closing since cannot replicate in latest version of Firefox 49 and Android 7
