### ISSUE TITLE
Carousel tab starting at 0

### ISSUE THREAD

**Issue by EricLavoie88** [wet-boew/wet-boew#6885]
When accessing the TBS-SCT home page through the splash page (I click on English through this link http://www.tbs-sct.gc.ca), in the bar under the carousel image where there are the play/arrow bar buttons, the item # starts at 0 as opposed to 1. The code looks identical to what is in the working example. Any idea why this is happening?

![carouselissue](https://cloud.githubusercontent.com/assets/7073468/8283920/0dec0192-18c8-11e5-8013-6e1ddeed59a9.PNG)

Thanks

**Comment by LaurentGoderre** [comment]
It's weird because when you cycle it goes back to 1 like it should

**Comment by LaurentGoderre** [comment]
Can you try upgrading to v4.0.14?

**Comment by pjackson28** [comment]
I think I see why, you didn't set class="active" on the active tab. The plugin is dependent upon that to determine the starting item number. Might not be a bad idea to add a fallback to 1 if the implementer forgets to add the active class.

**Comment by EricLavoie88** [comment]
That seems to have fixed it. Thanks

**Comment by pjackson28** [comment]
PR #6886 adds in a fallback for when the active class is omitted.
