### ISSUE TITLE
Search suggestion problems in Safari - usability testing

### ISSUE THREAD

**Issue by neoinsight** [wet-boew/wet-boew#6894]
Usability participant on Safari saw odd formatting of search suggestions - perhaps related to bizarre formatting we are seeing with the autocomplete in issue https://github.com/wet-boew/wet-boew/issues/6567.

Participant image below: 

![p7 march2015 safari search](https://cloud.githubusercontent.com/assets/1855584/8316411/dcc562fe-19c4-11e5-81bb-0f00f7106111.png)

Just tried it myself on Safari on my iMac, even weirder results, format is messed up AND the suggestions don't match the suggestions I see in Chrome for the same word (next image). 
![nursing search box safari](https://cloud.githubusercontent.com/assets/1855584/8316419/e512fc0a-19c4-11e5-80ca-01160016705f.png)
Suggestions in Chrome for same word on same page: 
![chrome search nursing](https://cloud.githubusercontent.com/assets/1855584/8316447/2073002e-19c5-11e5-95bd-12514c149cca.png)

@shawnthompson Refer this to you?

**Comment by hsrudnicki** [comment]
@neoinsight @shawnthompson : Can this issue be closed or otherwise, pls update this issue status?

**Comment by neoinsight** [comment]
No, I don't think this should be closed. As a safari user, I am having trouble selecting from the search suggestions on Canada.ca. The strange formatting above has changed, but now it's worse - I can't actually select and use a search suggestion. Nothing happens if I click, except that some search suggestions disappear. That's just bizarre. Here's a clip. https://youtu.be/cJWTyz3Fm9g

@hsrudnicki if you know the person that should be updating this issue status, please call them in.

**Comment by pjackson28** [comment]
@neoinsight What version of Safari is being used and on what version of Mac? Do you have the same problem on the following two pages as well?
* http://wet-boew.github.io/wet-boew/demos/datalist/datalist-en.html
* http://wet-boew.github.io/wet-boew/demos/datalist/datalist-dynamic-en.html

**Comment by neoinsight** [comment]
@pjackson28 My system is Safari 8.06, iOS 10.10.3
Still cannot select from search suggestions on Canada.ca. 
On the Datalist pages above, I CAN select from the suggestions.
 Different problem though and that is that the autofill box covers up the suggestions! Seen in image below. We are running 14 participants this week on intensive search tasks, and are capturing system and browser info. Will update this issue next week with what we see there. 
 
![datalist autocomplete autofill 1](https://cloud.githubusercontent.com/assets/1855584/8883261/72e2f8dc-321b-11e5-8cdf-4fd124d82909.png)

**Comment by pjackson28** [comment]
Wow, I doubt there is anything that WET can do about that crazy AutoFill bug. That is the browser doing that all by itself. Don't know why they thought it was a good idea to put an overlay over an input field that you are typing in. Does that happen for any other text input fields?

If it works in WET but not on Canada.ca then there is something wrong with how they implemented it in Canada.ca. is there an issue on the GCWeb repo yet for the Canada.ca specific issue? If not, could you please file an issue over there, referencing this issue?

**Comment by neoinsight** [comment]
@pjackson28 Agree that autofill bug is my browser. Annoying though! Haven't noticed it being a problem before. 

Re filing an issue in GC Web repo, there are several compounding issues here - perhaps the dividing line for WET versus GC Web is not clear to me for these. @masterbee may want to contribute to this.
 
1. String matching algorithm: Chrome and Safari consistently produce different Search auto-complete suggestions from the Google search. In issue https://github.com/wet-boew/wet-boew/issues/6845 you mentioned the browsers have different string search matching and in this issue too: https://github.com/wet-boew/wet-boew/issues/6815. 
- My take would be that WET should have polyfill so that auto-complete (itself, in Geomap, in Search fields etc.) works the same way across all browsers. I don't believe developers understand that this will happen, nor will they test for it. Hence the issues being posted about it. 

2. Format and cannot select on Safari: I will definitely file an issue in GCWeb about this. It's here: https://github.com/wet-boew/GCWeb/issues/1007

**Comment by pjackson28** [comment]
@neoinsight The issue with 1 and 2 is that polyfills add support where no native browser support exists, they aren't able to fix issues with native support. The problem we have here is the HTML5 spec doesn't seem to specify the matching algorithm for providing suggestions and left it up to the browser vendors who have implemented it in different ways (matching from the start of the string vs matching anywhere in the string).

Quickly looking at the browser support:
* Match from the start: Chrome, Internet Explorer 10+, Opera
* Match anywhere: Firefox, WET polyfill (Safari, Safari iOS, IE8/9)

Last time I checked Firefox only covered about 14% of the browser market while Chrome is the clear leader and Internet Explorer 10+ still has significant numbers. So the bulk of the users have browsers that natively match from the start or use the WET polyfill. Should we change the WET polyfill to match from the start to match the vast majority of browsers, leaving only Firefox as the outlier?

**Comment by neoinsight** [comment]
@pjackson. Yes your suggestion is exactly what I think would match user expectations. They all should match from the start. Hopefully Firefox will catch up eventually!

**Comment by pjackson28** [comment]
PR #7018 should make the datalist polyfill match strings the same as Chrome, Internet Explorer and Opera (from the start).

**Comment by pjackson28** [comment]
@neoinsight The PR has been merged in. Could you please test the live working example (http://wet-boew.github.io/v4.0-ci/demos/datalist/datalist-en.html) with your Safari browser to see if it is working as expected?

**Comment by neoinsight** [comment]
@pjackson28 Just tested on Safari, and yes, it's working almost as expected now. If I type in 'Va', I only see Vancouver, instead of 'Laval' and 'Vancouver'. However, as soon as I click into the field, it's displaying every possible autocomplete. That should not happen.  See image below: 
![datalist safari active](https://cloud.githubusercontent.com/assets/1855584/9176960/4a2220aa-3f5c-11e5-8996-2f104438f442.png)

 Also I tried it in Chrome and there's a problem there - I'm seeing repeated suggestions. See the image below (this is Chrome Version 44.0.2403.130 (64-bit) on OS 10) 
![polyfill in chrome](https://cloud.githubusercontent.com/assets/1855584/9176916/ff124626-3f5b-11e5-8147-ff5afae84d9a.png)

Q:Will this change be automatically updated in the GeoMap plugin?

**Comment by pjackson28** [comment]
@neoinsight When it shows you the whole list on click, was anything typed in the input field? Looking at your image it looks like nothing was typed in. In Chrome, if I click on the input field when it is empty it shows all suggestions, but when there is something typed in it only shows the matches on click.

As for repeated suggestions in Chrome, I can't reproduce with Chrome for Windows so perhaps that is a Chrome for Mac OSX issue. Chrome natively supports this functionality so likely would be browser bug.

**Comment by neoinsight** [comment]
@pjackson28 Re the whole list, I can't replicate it now, so I wonder if it was because I had backspaced. Sorry about that - ignore. 

Re repeated suggestions in Chrome, ok, I have seen it before occasionally and was worried it was somehow induced by the changes in the recent PR. But yes, seems likely to be a browser bug. 

Good to go then! 
@masterbee @pcwsmith - recommend that this change gets integrated into GC search improvement plans.

**Comment by neoinsight** [comment]
@pjackson28 Could this PR be applied to the Geomap demo too? We have participants next week, could have them try the Geomap again, had to halt last time as the matching caused such terrible problems.

**Comment by pjackson28** [comment]
@neoinsight It should be updated already as looking at the Geomap solution it is using datalist for that field.

**Comment by neoinsight** [comment]
@pjackson28 I think the string matching IS working correctly now in Geomap, but the datalist is most definitely not behaving the way it does in the datalist demo on Safari. I will post the new video on the Geomap issue https://github.com/wet-boew/wet-boew/issues/6845 so that we can close this one. Sadly, it doesn't look like this solves the very basic geomap problems at all, as you had hypothesized in that discussion.

**Comment by neoinsight** [comment]
@masterbee Please note this PR #7018 to apply to Canada.ca search. 
Now closing this issue as the PR has been merged.
