### ISSUE TITLE
Splash Page

### ISSUE THREAD

**Issue by KodiT56** [wet-boew/wet-boew#6896]
Hi Paul
I have another issue with the WET splash page.
The Developers here try to reduce the page  size 800 x 600 or less we have a particular JavaScript links on the French  English buttons  fail to work. at the reduced size. I am a little stumped on the behavior. we even tried the new 4.0 template but get the same result.
Have you ever encountered this behavior.
Any help would be appreciated.
Have a Great Day!
Cheers,
Kodi

**Comment by pjackson28** [comment]
Likely it has to do with how you implemented your JavaScript links or how you are listening for the events. Maybe it is dependent upon something in that is available in the larger view but is not available in the smaller view. If you provide the markup and JS you are using for the special JS links then perhaps we could help more.

**Comment by KodiT56** [comment]
Hi Paul sorry for the delay just getting approval for  releasing the code for you.

**Comment by KodiT56** [comment]
Here is the issue from the Developer
-------------------------------------------------
\wet-boew-dist-3.1.7\demos\theme-gcwu-intranet\languagetst.html

Drop the package into a web container
Drop the languagetxt.html file into the folder:

	\wet-boew-dist-3.1.7\demos\theme-gcwu-intranet\

Open the languagetxt.html file and click on the AVIS link - you should see the popup.

Shrink the window to mobility mode and click the AVIS link again.  The popup is not happening.

If either  or both of these lines are removed, the AVIS popup will work, but these lines were required.  So we need a means for this popup to work - if the popup works then JS is executing, which is what we need.

Here is the splash screen Markup.
-----------------------------------------------
<!DOCTYPE html>



<html lang="en" class="no-js">

<head>
<meta charset="utf-8" />

<title>Splash page - Bilingual (en-fr) - GC Web Usability Intranet theme - Web Experience Toolkit (WET) / Page d'entrée - Bilingue (en-fr) - Thème de la facilité d'emploi Web GC - Exemples pratiques - Boîte à outils de l'expérience Web (BOEW)</title>

<link rel="shortcut icon" href="../../dist/theme-gcwu-intranet/images/favicon.ico" />
<link rel="canonical" href="sp-pe-en-fr.html" />
<meta name="description" content="English description / Description en anglais" />
<meta name="description" lang="fr" content="French description / Description en français" />
<meta name="dcterms.creator" content="English name of the content author / Nom en anglais de l'auteur du contenu" />
<meta name="dcterms.creator" lang="fr" content="French name of the content author / Nom en français de l'auteur du contenu" />
<meta name="dcterms.title" content="English title / Titre en anglais" />
<meta name="dcterms.title" lang="fr" content="French title / Titre en français" />
<meta name="dcterms.issued" title="W3CDTF" content="Date published (YYYY-MM-DD) / Date de publication (AAAA-MM-JJ)" />
<meta name="dcterms.modified" title="W3CDTF" content="Date modified (YYYY-MM-DD) / Date de modification (AAAA-MM-JJ)" />
<meta name="dcterms.subject" title="scheme" content="English subject terms / Termes de sujet en anglais" />
<meta name="dcterms.subject" lang="fr" title="scheme" content="French subject terms / Termes de sujet en français" />
<meta name="dcterms.language" title="ISO639-2" content="eng" />
<meta name="dcterms.language" lang="fr" title="ISO639-2" content="fra" />
<meta name="robots" content="noindex, follow" />
<meta name="viewport" content="width=device-width, initial-scale=1" />



<script src="../../dist/js/jquery.min.js"></script>
<link rel="stylesheet" href="../../dist/grids/css/util-min.css" />
<link rel="stylesheet" href="../../dist/js/css/pe-ap-min.css" />
<link rel="stylesheet" href="../../dist/theme-gcwu-intranet/css/theme-sp-pe-min.css" />
<noscript><link rel="stylesheet" href="../../dist/theme-gcwu-intranet/css/theme-ns-min.css" /></noscript>



<link rel="stylesheet" href="custom-splash.css" />

</head>

<body><div id="wb-body">
<div id="wb-head">

<div id="wb-head-in"><header>

<div id="gcwu-sig" class="span-8"><div id="gcwu-sig-in"><object data="../../dist/theme-gcwu-intranet/images/sig-blk-en.svg" role="img" tabindex="-1" aria-label="Government of Canada / Gouvernement du Canada" type="image/svg+xml"><img src="../../dist/theme-gcwu-intranet/images/sig-en.png" class="image-actual" alt="Government of Canada / Gouvernement du Canada" /></object></div></div>

</header></div>
</div>

<div id="wb-core"><div id="wb-core-in" class="equalize">
<div id="wb-main" role="main"><div id="wb-main-in">

<h1 id="wb-cont">Welcome / <span lang="fr">Bienvenue</span></h1>

<div id="gcwu-title">
<div id="gcwu-title-left" class="span-3 margin-bottom-none">your.email@canada.ca
<p class="font-xsmall">Please select your language of choice.</p></div>
<div class="span-2 margin-bottom-none"></div>
<div id="gcwu-title-right" class="span-3 margin-bottom-none" lang="fr">votre.courriel@canada.ca
<p class="font-xsmall">S'il vous pla&icirc;t s&eacute;lectionner la langue de votre choix.</p></div>
<div class="clear"></div>
</div>

<div id="gcwu-lang"><nav role="navigation"><h2>Language selection links / <span lang="fr">Liens de sélection de langue</span></h2>
<div class="span-6 grid-12 margin-bottom-none">
<ul id="gcwu-ef-lang">
<li><div class="span-2 row-start margin-bottom-none"><a href="end-user-login-eng.html">English</a></div></li>
<li lang="fr"><div class="span-2 row-end margin-bottom-none"><a href="cont-fr.html">Français</a></div></li>
</ul>
</div>
<div id="gcwu-wmms" class="span-2 margin-bottom-none"><div id="gcwu-wmms-in"><object data="../../dist/theme-gcwu-intranet/images/wmms-intra.svg" role="img" tabindex="-1" aria-label="Symbol of the Government of Canada / Symbole du gouvernement du Canada" type="image/svg+xml"><img src="../../dist/theme-gcwu-intranet/images/wmms-alt.png" class="image-actual"  alt="Symbol of the Government of Canada / Symbole du gouvernement du Canada" /></object></div></div>
<div class="clear"></div>
</nav></div>

</div></div>
</div></div>

<div id="wb-foot"><div id="wb-foot-in"><footer><h2 id="wb-nav">Footer / <span lang="fr">Pied de page</span></h2>

<div id="gcwu-tc" class="span-8">
<div class="span-6 grid-12 margin-bottom-none margin-top-none row-start row-end">
<ul id="gcwu-ef-tc">
<li><div class="span-2 row-start"><a href="#" rel="license">Terms and conditions</a></div></li>
<li lang="fr"><div class="span-2 row-end"><a href="#" rel="license" onclick="alert('avisclick')">Avis</a></div></li>
</ul>
</div>
<div class="clear"></div>
</div>

</footer>
</div></div></div>


<script src="../../dist/js/settings.js"></script>


<script src="../../dist/theme-gcwu-intranet/js/theme-min.js"></script>
<script src="../../dist/js/pe-ap-min.js"></script>
<script src="../../dist/js/jquerymobile/jquery.mobile.min.js"></script>





</body>
</html>

**Comment by LaurentGoderre** [comment]
Maybe jQuery Mobile fails but I find it hard to believe it would occur even in v4.0

**Comment by KodiT56** [comment]
it apparently does??? Also if you go to basic HTML in your forms they completely disappear in Basic HTML not sure if that is intentional I thought they had to work Regardless.

**Comment by LaurentGoderre** [comment]
Yes that is intentiopnal bevause it relies on Javascript to send wo it wouldn't work

**Comment by hsrudnicki** [comment]
@KodiT56 @pjackson28 @LaurentGoderre : Are you ready to close this issue or otherwise (pls update this status status)?

**Comment by KodiT56** [comment]
Please keep open. The JavaScript has to be working at all times. when the page is reduced to 800x600 or less the English French buttons fail to link to there corresponding pages. see source code supplied. 
if in the JQuery are patches for this or new versions.
Hope you can assist.
Many Thanks 
Kodi

**Comment by pjackson28** [comment]
@KodiT56 Wasn't the forms issue addressed by the solution provided in #6876?

As for the splash page issue, I'm not sure I understand the issue. In WET v3.x it may be possible that jQuery Mobile is interfering, but in WET v4.x there is no JavaScript executing on the splash page (other than Modernizr browser checks and basic setup). Nothing on that page should be dependent upon JavaScript as it is just basic HTML and CSS.

What happens when you using the WET v4.x splash page? What does it do when you click on a language page link? Looking at your CSS it looks like you just have a normal link to a different page so it shouldn't be affected by anything WET does. Note that only WET v4.x is supported, support for v3.x was dropped nearly a year ago.

ow that is a WET issue as WET doesn't

**Comment by KodiT56** [comment]
Thanks Paul
The developers on this project refuse to up date to 4.0 until  SSC signs off on this version . But alot if the site fails with WCAG on validation and the responsive  aspects. I am caught in the middle being the auditor.
I forwarded your response to the Developer an his Management.
As far as I am concerned I have escalated this issue the best  I can considering that you no longer support this version. I will contact you again once the developers move on to the latest version of WET. Thanks again for your assistance.
You can close this issue please.
