### ISSUE TITLE
Minified and unminified resources

### ISSUE THREAD

**Issue by sgdowney** [wet-boew/wet-boew#6898]
I'm not sure if I'm seeing any benefit to having the minified and unminified js and css files together in the same folders.  I now have to go through all the folders to remove the unminified files in order to create a distribution package.  I don't see any benefit in shipping the unminified files to the server.

**Comment by RobJohnston** [comment]
@sgdowney It looks like from your other issues that you are using  .Net.  There is a way to modify your project file to exclude files and folders when publishing with Visual Studio.

See this StackOverflow question:  [Exclude `.js` files but not '.min.js' files from MSBuild publish] (http://stackoverflow.com/questions/25525197/exclude-js-files-but-not-min-js-files-from-msbuild-publish).  It seems to directly address your issue.

**Comment by LaurentGoderre** [comment]
This makes it way easier for variants (Drupal, Java, etc...) to switch between min and unmin for debugging purposes. Note that this is also how jQuery deploys to the CDNs

https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.js
https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js
http://code.jquery.com/jquery-2.1.4.js
http://code.jquery.com/jquery-2.1.4.min.js

**Comment by Linvalla** [comment]
Assuming you're using Visual Studio, you can have it not output as content
by right clicking on the file and telling it not to output as content.

If you are using MVC, you should be invoking it via CDN, cloudflare is
particularly nice as it hosts a lot of different libraries.  If you are
adamant about hosting yourself, you should be using bundling so it will
minify and compress accordingly all your JS code and use a map file to
allow browsers to reverse it.

**Comment by LaurentGoderre** [comment]
Deploying the unmin files to the server and having an option to switch your app to unminified can really help in some instances.
