### ISSUE TITLE
Forms: First checkbox in a list must be selected if javascript disabled

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/wet-boew#6901]
Is there a no-javascript fallback for a required checkbox list?

On the [form validation example] (http://wet-boew.github.io/wet-boew/demos/formvalid/formvalid-en.html), the very first checkbox in the checkbox list is the only one with a *required* attribute.  Works fine unless the user has javascript turned off, in which case the user has to choose the first checkbox in any HTML5 browser.  Radio button list is fine.

**Comment by LaurentGoderre** [comment]
I don't understand the issue, is it that it allows the user to not select any option if JavaScript is turned off?

**Comment by RobJohnston** [comment]
No, it's that the user *must* select the first option, whether he wants to or not.

**Comment by LaurentGoderre** [comment]
If Javascript is disabled?

**Comment by RobJohnston** [comment]
Correct, only if javascript is disable and on an HTML5 browser.

**Comment by LaurentGoderre** [comment]
That's a tricky situation....

**Comment by pjackson28** [comment]
There will be no solution as it is unsupported by the HTML5 spec and the W3C has marked it as wontfix: https://www.w3.org/Bugs/Public/show_bug.cgi?id=9160#c1

So nothing that WET can do about it as W3C has chosen not to fix this issue in the HTML5 spec.

**Comment by pjackson28** [comment]
The most you could do I guess is to add the required attribute through JavaScript before WET (and jQuery Validation) does its enhancement. Otherwise, it would require an upstream change in jQuery Validation (which may not go very far considering that it is a no-JS fallback request for a JS-based validation plugin).

**Comment by RobJohnston** [comment]
Sounds like a good idea.  Either of the following two lines seem to work:
```html
    <script type="text/javascript">
        $('#animal1').attr('required', 'required');
        //document.getElementById('animal1').setAttribute('required', 'required');
    </script>
```
Now I wonder if there should be a "Known Limitations" page in the docs (or a "can't fix" tag).

**Comment by pjackson28** [comment]
I put the wontfix tag on the issue as well as external: dependency upstream. As for known limitations, it is always good to document those. Do you have a suggestion for what should be documented?

**Comment by LaurentGoderre** [comment]
I just learned that there is a `novalidation` html5 attribute you can add a form to disable that behavior. Perhaps this should be the default for forms and we could have the form validation plugin remove that attribute with javascript?

**Comment by pjackson28** [comment]
The downside to that is that there would be no validation at all with JS disabled although I remember the Drupal community in the past recommending the use of novalidate anyway.

@sylus Do you recall why novalidate was being recommended?

**Comment by LaurentGoderre** [comment]
What good is validation without any error message? Client-side validation is to help users  avoid making errors, not to ensure data integrity so it would not be that harmful.

**Comment by pjackson28** [comment]
There is an error message with HTML5 validation and technically that is client-side validation as well (doesn't involve the server).

**Comment by LaurentGoderre** [comment]
Ahh i get it now. My solution wouldn't do much good.
