### ISSUE TITLE
input-group with button on the right is missing border-radius on input's left side

### ISSUE THREAD

**Issue by ptsimard** [wet-boew/wet-boew#6902]
As displayed on the example page (http://wet-boew.github.io/wet-boew-styleguide/v4/design/forms-en.html) and seeing it when using them on my own instance.

You can see that the controls on the right have mismatched border-radius
![input-group-radius](https://cloud.githubusercontent.com/assets/2463817/8381167/f2979694-1bf7-11e5-8e5f-b45fc738b0b5.png)

While it's minor and easy to override, I believe this is a bug in wet-boew.

**Comment by pjackson28** [comment]
Looks like it is a markup issue. Bootstrap seems to expect the input field to be the first child of <code>input-group</code> whereas in the example the first child  when actually a hidden Search label. The simplest solution would be to simply move the hidden Search label outside the <code>input-group</code> element.

**Comment by pjackson28** [comment]
Will be fixed by PR wet-boew/wet-boew-styleguide#252

**Comment by ptsimard** [comment]
Thank you for the fast feedback. I changed my markup and it works well.
