### ISSUE TITLE
Anchors in Tabbed Interface, problems from outside page

### ISSUE THREAD

**Issue by amonsour** [wet-boew/wet-boew#6903]
Good afternoon,

We're having problems with anchors within the Tabbed Interface.

When going to the tabbed anchor from an outside page; it is staying at the top of the page and not going down to the anchor placement in the tabbed interface. Sometimes however, it works and sometimes it doesn't. From what I can tell, the plugins are loaded last making the tabbed interface non-existent in the opening of the page.

I can't display a page for you to try, but if needed, I can display what's happening through images as it's in our test server.

We are using WET v4.0.9 (soon to be updating to latest).

Thanks!
Adam

**Comment by LaurentGoderre** [comment]
I believe that was fixed several versions ago

**Comment by pjackson28** [comment]
Yes, please try with the latest version as I believe this issue was resolved in a version after v4.0.7 (we are now at v4.0.15).

**Comment by amonsour** [comment]
Thanks @LaurentGoderre and @pjackson28. I will try it again when we update to the latest version of WET which should be soon. We are actually on 4.0.9; just got confirmation on it and I updated the first post.

**Comment by hsrudnicki** [comment]
@amonsour @pjackson28 @LaurentGoderre : Please update the status of this issue whether this issue can be closed or otherwise?

**Comment by amonsour** [comment]
The website is still on version 4.0.9. I will re-open the issue if when we update wet4 to the latest and there are still issues. Thank you,
