### ISSUE TITLE
btn min-height and min-width not overridden by btn-xs

### ISSUE THREAD

**Issue by bmadzar** [wet-boew/wet-boew#6905]
This problem has started occurring since we updated from 4.0.14 to 4.0.15, using the GCWU theme.

It seems that the `min-height` and `min-width` properties are inherited from `.btn` when using `.btn-xs`, resulting in buttons that are too large.

This happens on Chrome, Firefox and IE9.

**Comment by LaurentGoderre** [comment]
I believe this was implemented to ensure minimum touch targets for usability reasons

**Comment by bmadzar** [comment]
In this case, would it be possible to fix up the padding so the button content doesn't appear misaligned?

**Comment by LaurentGoderre** [comment]
@thomasgohard

**Comment by sgdowney** [comment]
If the `.btn-xs style doesn't meet the minimum touch target size should the style be removed or discouraged from use?

**Comment by hsrudnicki** [comment]
@thomasgohard and others : Please update this issue status whether this issue can be closed or otherwise?

**Comment by RitchieD** [comment]
I just migrated from wet 4.0.14 to 4.0.16 and got this issue.
All my extra small buttons have a min-height of 36 px.
I'm using btn-group-xs

**Comment by RitchieD** [comment]
For anyone using 4.0.16 and wants small buttons here is a temporary fix that you can add to your own CSS after WET styles.  (Remove this fix with new versions).
```
/* Temporary Fix for height of xs buttons for WET 4.0.16 */
.btn {
    border-style:outset;
    height:auto;
    min-height:0px;
    min-width:36px;
    white-space:normal
}
```

**Comment by DHaslip** [comment]
I just migrated from wet 4.0.14 to 4.0.16 and my extra small (btn-xs) and small (btn-sm) buttons have a min-height of 36 px, which makes them the same size as the default button.

Is this going to be fixed?

**Comment by ptsimard** [comment]
This is the kind of breaking changes that should not happen on a minor version upgrade. It can totally break a nice site design.

The btn-xs class is part of the documentation and has such, has been in use across many sites by many people.

This change should either be reverted or properly planned.

**Comment by andre-gh** [comment]
Sorry, there were project switchovers and this issue fell under.  I am assigning myself to this now and will be sure this gets fixed for the next release.  Reading the reasoning for this change over here wet-boew/GCWeb#963 it was never intended to break alignment of buttons text and instead was meant to increase the size to discourage usage as it breaks accessibility rules and as usage of btn-xs is low in wet projects it appears it got missed in testing.  It was considered a bug that it was even possible to create a button that inaccessible using built-in classes, and thus was changed.

That being said, button size changes can break application UIs pretty bad (it does not really matter too much in areas where you have a lot of whitespace like page content in the example), but inline buttons on web applications are often tightly fit. 

I can not revert the change for the working larger buttons as flip-flopping like that further breaks our versioning promise for anyone already on the newer version (two wrongs do not make a right), but I can fix btn-xs (and any other misaligned) for now as they are completely broken and have to change anyway.

**Comment by ptsimard** [comment]
Thank you. Sorry If i was a bit blunt. 

I'm in crunch time and quite preocuppied by deadlines. Getting random  changes like that threw me off.

So for a larger discussion on accessibility. I gather this means that any site using WET-BOEW should now not be able (by default) to do tight application-style layouts. Everything has to be the size of the sun? Couldn't big size be enforced at mobile screen size only?

**Comment by andre-gh** [comment]
@ptsimard I can not personally speak for the accessibility, I am more on the technical implementation side of things. That being said, implementing such that you assume that only small size screens are touchscreens is not super forwards-compatible.  The discussion in the issue I linked explained the rules more clearly.

**Comment by andre-gh** [comment]
@ptsimard I have fixed btn-xs for now and in the future in a more proper version btn-xs will act the same as btn-sm unless the accessibility folks decide otherwise.
