### ISSUE TITLE
Use of wb.doc.on syntax and exclusion in selector

### ISSUE THREAD

**Issue by GarthMartin** [wet-boew/wet-boew#6908]
Is there a way to use :not() in the selector when using the wb.doc.on syntax?

I have tried the following but it is not working as expected:
```javascript
wb.doc.on("click", "header a[href], footer a[href], .trigger-dirty, :not(.item)", function (e) {
        //Prevent the default behaviour.
        e.preventDefault();...
```
Obviously I am trying to exclude all elements with the class "item".

Thanks,

Garth

**Comment by LaurentGoderre** [comment]
This selector doesn't do what you think it does.  It doesn't remove `.item` from the previous selector. You will need to change your approach. Which `.item` are you trying to exclude?

**Comment by pjackson28** [comment]
Agreed, "header a[href], footer a[href], .trigger-dirty, :not(.item)" translates to "header a[href] OR footer a[href] OR .trigger-dirty OR :not(.item)". If you want to exclude, then the :not would need to be applied to each part of the selector or you would need to filter within the function area.

**Comment by GarthMartin** [comment]
Yep, agreed.  I got it to work
```
header a[href]:not(.item)....
```

Cheers,
