### ISSUE TITLE
Multimedia Player - Video: 

### ISSUE THREAD

**Issue by SteveBuell** [wet-boew/wet-boew#6921]
Default volume of "100" (max) is potentially unsafe. Suggest using something more reasonable such as 30 or 40 default volume.

**Comment by SteveBuell** [comment]
This was noticed live at "http://www.canada.ca/en/campaign/taxsavings/index.html"

**Comment by LaurentGoderre** [comment]
This is based on the OS volume though, so it's 100% of the current system volume.

**Comment by SteveBuell** [comment]
System volume is set at 24%. In the plugin page and the site I mentioned, it is still at 100%

**Comment by LaurentGoderre** [comment]
which means 100% of 24% so still 24%

**Comment by SteveBuell** [comment]
OK, I'll buy that. ;)

**Comment by LaurentGoderre** [comment]
If you find an instance of it being not the case in a browser that's a pretty significant bug in that browser and should be reported there, the browser should not be able to override the system settings.
