### ISSUE TITLE
Question: launching geomap

### ISSUE THREAD

**Issue by bsouster** [wet-boew/wet-boew#6923]
Hey guys,
I'm experimenting with geomaps, trying to get it to launch on-click instead of it being automatic after page load. The reason I'm trying to do this is free international maps have query limits. To keep those queries below the limit, I'm trying to show the map and send the query to the basemap provider only when the user specifically asks using a button "View map" on-click event.

I'm admittedly stumbling my way through this. Is there a way to hold off the wb-geomap launch and set it to an on-click event?

Thanks

**Comment by LaurentGoderre** [comment]
You should probably inject it with Javascript and initialize it manually.
