### ISSUE TITLE
Forms: Example shows validation message only in English

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/wet-boew#6924]
Slight problem with the current example page for form validation.  The [French page](http://wet-boew.github.io/wet-boew/demos/formvalid/formvalid-fr.html) is showing part of the validation message in English (see image attached).

![errorformvalidationlanguage](https://cloud.githubusercontent.com/assets/1347487/8598640/ca7db792-2629-11e5-92de-7c3837cf0b9a.png)

**Comment by pjackson28** [comment]
Looks like the jQuery validation language files are no longer being appended to the WET language files. Looks like it is because the i18n task is looking for dist/js/i18n/ to determine the language where that path is no longer valid after recent build changes.

**Comment by pjackson28** [comment]
Will be fixed by PR #6926.
