### ISSUE TITLE
Impossible to pass POST data for lightbox opened with JavaScript

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/wet-boew#6925]
Because the option to open a lightbox via javascript only allow you to access a small subset of magnificpopup settings, it is not possible to send POST data with ajax requests

**Comment by pjackson28** [comment]
Could you please be more specific about which specific calls/options that you are unable access? I can't find "post" or "POST" anywhere in the Magnific Popup documentation.

**Comment by LaurentGoderre** [comment]
See the answer here, the relevant config is out of reach in the current configuration

http://stackoverflow.com/questions/25032288/is-it-possible-to-pass-data-via-the-post-method-to-magnific-popup-when-ajax-load

**Comment by pjackson28** [comment]
Wouldn't a quick fix be to add support for an ajax option to the event and then have that map to an ajax property entry in the open call of the open event (much like what is done with other properties)?

**Comment by LaurentGoderre** [comment]
It would be dirty but it might work. We however need to fix this in the next version though

**Comment by LaurentGoderre** [comment]
Note that this problems apply to datatables as well. In next version, we need to change our approach to how we do our [plugin and interface with third party.

**Comment by pjackson28** [comment]
Will be fixed in Lightbox in PR #6928.

What options can't be accessed in DataTables? Isn't the DataTables wrapper much more open and configurable than the Lightbox wrapper?

**Comment by pjackson28** [comment]
From the looks of it you just need to pass the ajax parameter through data-wb-tables (unless I'm missing something). https://www.datatables.net/examples/data_sources/ajax.html

**Comment by LaurentGoderre** [comment]
That as well when doing extremely simple use case but when doing next gen web apps, the wayu we are doing it isn't cutting it at all. For example, you can't pass functions to the `data-` attributes etc.

We need to have this issue opened for next release because this needs to be revisited.

**Comment by pjackson28** [comment]
Then another issue should be opened because this issue is just about passing post data. You could create another issue about passing functions but that issue needs to be separate from this one.

**Comment by LaurentGoderre** [comment]
Ok
