### ISSUE TITLE
Form validation / Details (expand/collapse)

### ISSUE THREAD

**Issue by sebastienHubert** [wet-boew/wet-boew#6927]
Was it intentional that if required form fields are within a collapsed details tag that they are not validated by the form validation plugin?

**Comment by pjackson28** [comment]
Yes that is the default behaviour. You can override that using the "ignore" option covered in the documentation. The default for ignore is all hidden fields so that can be changed to cover more or less fields.

**Comment by sebastienHubert** [comment]
Very informative. That answers my question. Thank you for your time.
