### ISSUE TITLE
Getting weird behavior from the tabbed interface plugin

### ISSUE THREAD

**Issue by charlesmorin** [wet-boew/wet-boew#6932]
WET version : 4.0.9

I am using the tabbed interface plugin in some Java EE applications (hosted on JBoss 4.2.3 and JBoss 7.2). Applications uses Struts 1.3.5 and Spring 4.0.6.

When loading the JSP page, using the IE11 Developer Toolbar (F12), I got an error from the Debugger view, at line 11, column 21518 in wet-boew.*min*.js :

Faulty line is:
if(j=document.querySelector(c.parent),"tablist"!==j.getAttribute("role"))
Message: SyntaxError

When looking at the source from your working examples, I see the following classes on the "details" tag:
wb-auto-2-grp open fade in

But when I am looking at mine, I got:
*694a7066-8b19-44db-a140-a6c7c9684bbe*-grp open fade in

Any thoughts?

Thank you.

Charles
CRA

**Comment by pjackson28** [comment]
That is a known issue with v4.0.9. Please update to the latest version (v4.0.15) to fix the issue.

**Comment by charlesmorin** [comment]
I confirm that it works as advised.

Thank you Paul for the quick response.
