### ISSUE TITLE
Badges not lined-up with H3

### ISSUE THREAD

**Issue by RitchieD** [wet-boew/wet-boew#6936]
IE 11, WET 4.0.14

This is pretty minor; however, it would be an improvement if the Badges lined-up better when used with an H3.

```
<span class="h3">An H3 span <span class="badge">6</span></span>
<h3>An H3 Heading <span class="badge">6</span></h3>
<span>Plain Text <span class="badge">6</span></span>
```

<Can't upload pic...>

**Comment by RitchieD** [comment]
![capture](https://cloud.githubusercontent.com/assets/2989756/8678352/0e0fba22-2a22-11e5-8523-32950b112d7f.JPG)

**Comment by hsrudnicki** [comment]
@pjackson28 @thomasgohard @LaurentGoderre @RitchieD and others: Can be this issue closed or otherwise (pls update the status of this issue)?

**Comment by RitchieD** [comment]
@hsrudnicki  I don't think the status has changed since reported.  If its not going to be fixed, I guess you can close it as.  Even a work around would be nice.

**Comment by pjackson28** [comment]
@RitchieD Bootstrap aligns badges to the baseline rather than the top, so the badges are aligning correctly, even for h3. Now whether it should be aligned to the baseline is another question but that is the Bootstrap default.
