### ISSUE TITLE
Replace menu, menu items in file 'ajax/sitemenu-en.html'

### ISSUE THREAD

**Issue by xunan-zhang** [wet-boew/wet-boew#6941]
Hi Laurent, Paul, and John,

A question again.

I try to replace the WET 4.0 menu with my own menus. I cannot clean up the WET 4.0 menu/menu items. How to clean them up?

My code is:
 \<nav role="navigation" id="wb-sm" data-ajax-replace="/e-services/views/ajax/sitemenu-en.html" data-trgt="mb-pnl" class="wb-menu visible-md visible-lg" typeof="SiteNavigationElement">
 \</nav>

when 'ajax/sitemenu-en.html' was loaded first time. Any updates late in the file does not affect the original menu/menu items. Even I delete the file and 'ajax' folder. System still display original menu, menu items

Thanks,

Carl

**Comment by LaurentGoderre** [comment]
I am not sure I understand your problem

**Comment by xunan-zhang** [comment]
Hi Laurent,

I took the whole page of WET 4.0 from
   http://wet-boew.github.io/themes-dist/theme-gcwu-fegc/content-secmenu-en.html
And only change all the paths to make them pointer to my local machine .css, .js, and ajax. So the page including menu, menu items displaying from local web server is the same as above page from wet 4.0.

I tried to change the menu. Only first time it works. I cannot update the menu after.
   such as the menu "WET Project",  I updated it to "WET Project XXX" in the file "ajax/sitemenu-en.html". It still display "WET Project".

Thanks,

Carl

**Comment by pjackson28** [comment]
The menu bar needs to be changed both in the page and in the AJAXed in menu. The menu bar is specified twice to provide a fallback for when JS is disabled.

**Comment by xunan-zhang** [comment]
Hi Paul,

Yes. The menu in the page is default. It is displayed when ajaxed menu failed.

My issue now is that the "ajax/sitemenu-en.html" is valid. ajax and js work. I change the menu/menu items in the "ajax/sitemenu-en.html". The updates do not work.

Such as:
   1. when I use "ajax/sitemenu-enXX.html" in the \<nav data-ajax-replace="ajax/sitemenu-enXX.htm" at first time. There is no such a file under folder 'ajax'. It displays default menu in the PAGE (no menu items)
   2. Then I rename sitemenu-en.html to sitement-enXX.html, run again. It display the menu/menu items in the FILE "ajax/sitemenu-enXX.html"
   3. Then I delete the file "ajax/sitemenu-enXX.html", or update any contents of it, or delete whole content of it. It still displays the menu/menu items of original ajax/sitemenu-enXX.html.

Thanks,

Carl

**Comment by sgdowney** [comment]
The menu file is being cached by the browser.  You would have to either clear the browser cache or close and open the browser to see the updates.

**Comment by xunan-zhang** [comment]
Hi Stewart,

Yes. I update the setting of the browser. The updates can be seen now

Thank you very much,

Carl

**Comment by hsrudnicki** [comment]
@xunan-zhang @LaurentGoderre @pjackson28 @sgdowney : Can be this issue closed or otherwise (pls update the status of this issue)?

**Comment by xunan-zhang** [comment]
Yes. I updated the settting of my browsers to fix it. 


     On Tuesday, August 11, 2015 4:44 PM, hsrudnicki <notifications@github.com> wrote:
   

 @xunan-zhang @LaurentGoderre @pjackson28 @sgdowney : Can be this issue closed or otherwise (pls update the status of this issue)?—
