### ISSUE TITLE
Input type="date" polyfill (date picker): 

### ISSUE THREAD

**Issue by loyd33** [wet-boew/wet-boew#6947]
HI , we validate all pages from validator.nu but still got this warning
is there a way to avoid this warning ?
Warning: The date input type is not supported in all browsers. Please be sure to test, and consider using a polyfill.

Latest version of WET.

thanks.

**Comment by pjackson28** [comment]
I don't think there is any way to disable the warning but it can be safely ignored. WET does provide a polyfill for the date input type.

**Comment by loyd33** [comment]
ok I will ignored the warning . thanks
