### ISSUE TITLE
is a div 2 columns in a div 3 columns possible?

### ISSUE THREAD

**Issue by marieeved** [wet-boew/wet-boew#6955]
hi,
 I tried to have a carroussel with text aside. The text is not the text that goes with the carroussel (it's for an other section). I was able to put them seperatly in a "well" and in the principal framework, but I want them bigger. In fact, I want the carousel and text occupy the space of the entire length of the page (in my div), so 1/2 -1/2. but my div is already structured in 3 columns (1 / 3-1 / 3-1 / 3) as canada.ca on How to achieve this? Thanks.

**Comment by LaurentGoderre** [comment]
The basic concept of grids is that a row has to total 12 so a 3  and 9 column would give a full width 1/3 + 2/3 layout. I have a bit of a hard time understanding exactly what you are trying to achieve without seeing a diagram.

**Comment by marieeved** [comment]
I'm not able to publish my diagram. It said: something went really wrong... try later.

**Comment by marieeved** [comment]
En-tête de la page internet (avec logo et navigation)


















Pied de page (navigation)

**Comment by LaurentGoderre** [comment]
Email it to me and I'll attach it. laurent.goderre at gmail

**Comment by LaurentGoderre** [comment]
Here is the diagram

![diagram](https://cloud.githubusercontent.com/assets/1090826/8784593/dc9e4d9a-2ef0-11e5-86cb-a20b3a1239d5.PNG)

**Comment by LaurentGoderre** [comment]
So what you want here is this:

```html
<div class ="row">
    <div class="col-md-6">Carousel</div>
    <div class="col-md-6">Text</div>
</div>

<div class ="row">
    <div class="col-md-4">Contenu 1</div>
    <div class="col-md-4">Contenu 2</div>
    <div class="col-md-4">Contenu 3</div>
    <div class="col-md-4">Contenu 4</div>
    <div class="col-md-4">Contenu 5</div>
    <div class="col-md-4">Contenu 6</div>
</div>
```

**Comment by marieeved** [comment]
but I have something else before... how can I publish code? I try earlier and it appears like if I was on the browser.

**Comment by marieeved** [comment]
because I have code for web invisible. is it really important or not? because I think that is this block of code that affects everything else.
div class="container bg-white"
div class="row"
main class="col-md-9 col-md-push-3 bg-white ...
section
div class="row"
div class="col-md-12"
h2 class="wb-invisible">contenu principal h2
...

**Comment by LaurentGoderre** [comment]
To show code on GitHub you need to use the ` character. Use one around inline code or use 3 around a block of code

**Comment by marieeved** [comment]
this code is my framework for the entire page. if I cut it, all the section (carroussel, text, content#1...) takes more space. For an image, it's like when you click on the button "full screen". and it's not what  I want.

**Comment by marieeved** [comment]
'<div class="row">

**Comment by LaurentGoderre** [comment]
Use the same amount of ` at the end then at the beginning

**Comment by LaurentGoderre** [comment]
If you use my code inside your main it should still work

**Comment by marieeved** [comment]
'''</header>
<div class="container bg-white"> 
  <div class="row">
    <main role="main" property="mainContentOfPage" class="col-md-9 col-md-push-3 bg-white"> 
      <h1 id="wb-cont" property="name" class="wb-invisible">Content page - Secondary menu</h1>
      <section>   
         <div class="row"> 
          <div class="col-md-12">
          	<h2 class="wb-invisible">Contenu principal</h2>
          	<div class="ls-cmp-wrap" id="w1334584272415">
            <div class="iw_component" id="1334584272415">
            <div class="span-3 margin-top-large  hometab">
        
<h1>bla bla bla</h1>
<div class="row">
		<section class="col-md-6">
        
        <div class="well">
            <div class="wb-tabs carousel-s2">
...
            </div>
 </div>
    </section>
 
 <section class="col-md-6">
 <div class="well">
 <h3  class=" font-xxlarge">Vos nouvelles </h3>
<p>bla bla bla</p>
</div>
</section>
    </div>
</section>
</main>

<div class="wb-eqht row">
  <section class="col-lg-4 col-md-6 mrgn-bttm-md">
<a rel="external" href="design-1a.html">
<h2>bla bla bla</h2>
</a>
...
...
<footer> ...'''

**Comment by LaurentGoderre** [comment]
You can use the of them around a whole block of code and specify a format

**Comment by marieeved** [comment]
too complicated... I will check that tomorrow. I leave office in 15 minutes. but thanks to continue posting. I will read all your comments tomorrow.

**Comment by nschonni** [comment]
@marieeved I fixed your markup, you can see the instructions on https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting

**Comment by LaurentGoderre** [comment]
@nschonni seems like we both were lol

**Comment by marieeved** [comment]
I got it!!!! it was my first idea...
I put an :  `<aside class="gc-nttvs container">` after my block carroussel and news to create an other Framework for my content #1 to #6. 
and I close correctly the first Framework:
```<div class="container bg-white"> 
  <div class="row">
    <main role="main" property="mainContentOfPage" class="col-md-9 col-md-push-3 bg-white"> 
      <h1 id="wb-cont" property="name" class="wb-invisible">Content page - Secondary menu</h1>
      <section>   
         <div class="row"> 
          <div class="col-md-12">
          	<h2 class="wb-invisible">Contenu principal</h2>
       </div></div>
       </section>
       </main>
       </div>```
