### ISSUE TITLE
Multimedia player: Play icon continues to overlay the video even after the video is playing

### ISSUE THREAD

**Issue by pjackson28** [wet-boew/wet-boew#6956]
Reproduced on the live working examples in multiple browsers. The big play icon overlaying the video in the multimedia player temporarily turns into the spinning circular arrows while the video starts playing but then returns to the big play icon when the video is actually playing. Doesn't make a difference whether I used the play button in the control bar or the play icon overlaying the video to start the video. Regardless of how the video is started, the big play icon should disappear until the video is paused or stops.

@LaurentGoderre @crichard

**Comment by andre-gh** [comment]
Looks like on this change https://github.com/wet-boew/wet-boew/commit/2155aa1f0bfc4178a916ff5c083bf42d26a1a1a2#diff-4c6bbab1ee3af4755b179af75b9bbd81L118 the .playing selector set got removed.

**Comment by andre-gh** [comment]
More specifically @include multimedia_overlay_hidden went missing

**Comment by LaurentGoderre** [comment]
Yeah that would be it. I am wondering though since IE8 is no longer supported and it's only an overlay. Maybe we can rewrite it with the `:not` slector to make it way smaller and less complicated.

**Comment by pjackson28** [comment]
We should be careful about stripping out support for IE8. It is one thing to no longer maintain the support for IE8 but it is another to knowingly remove support for IE8. We could always do the smaller selector for modern browsers and have the more complicated one in the IE8 CSS. Although we do still have that problem of exceeding the maximum number of selectors supported by IE8.

**Comment by LaurentGoderre** [comment]
It's not essential for it to work so on IE8 it's only a nice to have.

**Comment by pjackson28** [comment]
We should be careful about breaking what already works in IE8, or introducing new issues. The support in IE8 shouldn't be breaking as we push out more maintenance releases.

Ideally the overlay would work as expected in IE8 but if we have to scale back in IE8 on this (which may make sense considering our IE8 max selector issue), then it is better to not provide that overlay at all in IE8 than to leave it there perpetually while the video is playing. Having the overlay at all is the nice to have in IE8, having an unimpeded view of the video should be provided at a minimum.

**Comment by Bgolden67** [comment]
I've seen this on Firefox not just IE

**Comment by LaurentGoderre** [comment]
@Bgolden67 I know. I was just proposing a fix that would solve it for everything but it would remove the overlay in IE8

**Comment by ehcee** [comment]
I was wondering if there was a temp solution that fix's this bug in media player or will it be fixed when the next version 4.0.17 of the WET templates are released?

**Comment by hsrudnicki** [comment]
Continue your thoughts/suggestions in order to close this issue? In case of otherwise, please update the issue's status.
