### ISSUE TITLE
media wysiwyg embed and apostrophe in title/alt attribute

### ISSUE THREAD

**Issue by churel** [wet-boew/wet-boew#6957]
Hello,

We have a issue on our website. When a contributor add a image on the wysiwyg with the media embed button and add a apostrophe on the title or alt attribute, this one is not well displayed by the browser.
Here a screenshot of the contributor adding the image : 
![issue](https://cloud.githubusercontent.com/assets/5156602/8806186/7918c56c-2fa3-11e5-88a8-a1db86610779.png)
Here the result on the browser : 
![screen shot 2015-07-21 at 12 25 41 pm](https://cloud.githubusercontent.com/assets/5156602/8806239/aa72dbde-2fa3-11e5-85ec-807ab42047c7.png)
Thanks,

**Comment by LaurentGoderre** [comment]
I don't think this is caused by WET. It's probably that your application is double HTML encoding: OPSEU's becomes `OPSEU&amp;#039;s` instead of `OPSEU&#039;s`

**Comment by LaurentGoderre** [comment]
Nevermind. This seems to be an IE only issue. Firefox does not do this.

**Comment by churel** [comment]
Hello Laurent,
It's not a IE only issue. I have it on chrome and firefox.
I had a quick fix right now by adding a html_entity_decode at the end of the media_wysiwyg_token_to_markup function on the media_wysiwyg module.
You are wright about double HTML encoding, before the drupal_render the string is `OPSEU&#039;` and drupal_render (on the media_wysiwyg_token_to_markup function) change it to `OPSEU&amp;#039;s`.
I can be wrong but I don't think there is anything I can do for it execpt patching the media_wysiwyg.

**Comment by LaurentGoderre** [comment]
If this is a problem with the drupal distro, this is the wrong repo. Can you post the issue to wet-boew/wet-boew-drupal please?

**Comment by churel** [comment]
Ok sorry for that. Don't know how I land here.
