### ISSUE TITLE
Forms: Extension method is for files, not phone numbers

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/wet-boew#6960]
In the [recent commit] (https://github.com/wet-boew/wet-boew/pull/6952/files), there was an example added on the [form validation] (http://wet-boew.github.io/wet-boew/demos/formvalid/formvalid-en.html) page for a telephone extension.  Problem is, I think this was for [file name extensions] (https://github.com/jzaefferer/jquery-validation/blob/master/src/additional/extension.js). Nothing entered in that field, neither text (like "png") nor a number will pass validation on that example page.

**Comment by pjackson28** [comment]
Thanks for catching that. The example and related documentation will be removed by PR #6961.
