### ISSUE TITLE
Issue with Twitter feed

### ISSUE THREAD

**Issue by fsnoddy** [wet-boew/wet-boew#6962]
We noticed an issue with the twitter feed where the scrollbars of the browser expand and collapse while the feed is loading (IE11, Firefox). We can easily see the issue on our network because of the speed issue but you can also see it for a couple of seconds on page load on the example page.
http://wet-boew.github.io/v4.0-ci/demos/twitter/twitter-en.html

This happens because the animated loading glyphicon is outside the screen. Removing the text-indent property from the ".wb-twitter .twitter-timeline" rule in the css seems to fix the problem but also shows the link which I suppose was meant to be hidden.

Please let me know if you need more details. Thank you.

**Comment by pjackson28** [comment]
PR #6963 removes the problematic text-indent property since it is better to have the link visible initially than to having the jumping while loading. Another PR can be created later to add a better solution if one is found.

**Comment by pjackson28** [comment]
PR #6963 removes the problematic text-indent property since it is better to have the link visible initially than to having the jumping while loading. Another PR can be created later to add a better solution if one is found.

**Comment by fsnoddy** [comment]
I'm happy with the solution. Thank you very much.
