### ISSUE TITLE
size of logo in intranet theme

### ISSUE THREAD

**Issue by marieeved** [wet-boew/wet-boew#6979]
Hi,
what is the size of logos in the intranet theme?
 I want to make mine but the photo seem too big for the place. I get up and down arrows next to the image to view it in full.
si I have to make it smaller I guess. so I need the size maimum that I can use.
thanks

**Comment by marieeved** [comment]
or how can I create a file with the format .svg like these images.
 which software that I have to use?
thanks.

**Comment by LaurentGoderre** [comment]
You shouldn't create those because they are trademarks. You can ask your FIP coordinator for the vector format for that branding and then convert that to SVG.
