### ISSUE TITLE
Major i18n overhaul

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/wet-boew#6981]
The way we handles translation makes it very difficult for variants to manage those translations. To better empower variant developer we need to revisit the way we manage our translations. For this, we should implement #5894 and #6003.

As part of this, we can look at translation services for FOSS that would allow us to manage our strings more efficiently and would allow variant to reuse the work done instead of having to redo it all.

/cc @masterbee @nschonni @pjackson28

**Comment by nschonni** [comment]
Cross linking #2094, #2986, and #6726

**Comment by LaurentGoderre** [comment]
Why did you add the Chrome tag?

**Comment by nschonni** [comment]
Hit the enter key when using the "Labels" filter so I removed it right after.

**Comment by LaurentGoderre** [comment]
Ah ok

**Comment by LaurentGoderre** [comment]
Transifex has a nice client for synchronizing translations. Only downside is that it's in Python.

**Comment by hsrudnicki** [comment]
Please continue your thought(s) and update this issue status whether this issue with others related can be closed or otherwise?

**Comment by hsrudnicki** [comment]
Further, please update this issue's status whether this issue can be closed or otherwise? Thx

**Comment by hsrudnicki** [comment]
Based on the above, the support PR is already closed but there are other referenced issues, lingering for over 4 months, to be resolved/fixed with this issue or if otherwise?
Either way, please update this issue's status, as well the referred issues, thank you

**Comment by hsrudnicki** [comment]
Is this still an issue? Please update the status of this, whether this can be closed or otherwise? Thx
