### ISSUE TITLE
Issue with the mobile menu expand/collapse styles

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/wet-boew#6984]
![expandcollpasemobilemenu](https://cloud.githubusercontent.com/assets/1090826/8917585/de35fb4a-3480-11e5-85ec-361f7919a5d7.PNG)

**Comment by thomasgohard** [comment]
That's because of the changes is #6951. I'll update the CSS so that the changes don't get picked up by the menu.

**Comment by hsrudnicki** [comment]
Please continue and update this issue status whether this issue can be closed or otherwise?

**Comment by EricDunsworth** [comment]
@thomasgohard @LaurentGoderre @masterbee Any chance #6989 and #6992 could be merged in ASAP?

The main WET site's mobile menu still looks totally messed up to this day (2 months later). If there's still no appetite to make any big decisions for a long-term solution, it can't hurt to merge in our existing PRs.

IMO the current look of the mobile menu gives off the impression that WET has practically been abandoned.
