### ISSUE TITLE
2 nav bars with dropdown/color different?

### ISSUE THREAD

**Issue by marieeved** [wet-boew/wet-boew#6985]
Hi,
I would like to have two navigation bars, each with a drop-down menu and a different color. is it possible?
I already tried calling 2 different files via ajax, but it does not work (2 nav in my html page and 2 different files for my menus).
I can combine my two menus in one navigation bar (only 1 nav, only one row but br between 2 menus for having a 2 bars below the other) with one single file and one single call ajax. In this case, I can't change the color of the second bar completely. I can change the color of li, but the rest of the bar is still the main color as the menu is not "justified".
Does anyone help me? Thank you.
![nav bar](https://cloud.githubusercontent.com/assets/13418868/8931079/b587371e-3501-11e5-81f8-5481c5b2e744.JPG)

**Comment by LaurentGoderre** [comment]
Doing so would break the mobile support so it is not recommended

**Comment by marieeved** [comment]
we don't need a mobile version functionnal. nobody use it. very few persons have a business cell.

**Comment by LaurentGoderre** [comment]
From a usability perspective it's suboptimal too. It may be possible to do it but it is not supported.

**Comment by marieeved** [comment]
you mean that to have 2 dropdown it's not super great for usability?

because for my intranet, it's required to have 2 nav (1 for national site and one for my intranet).
so without 2 dropdown, it would be a dropdown for the national site and navigation at left for my site. but I found that the navigation at left it's not modern. most websites no longer use it. 
and with this habit, I'm afraid that people will think that the navigation at top with the dropdown will be the navigation of the site (our intranet) and it will not because it will be a menu for an other intranet (national site).

In this context, that's why I wanted to have two dropdowns.

and like the menu represents 2 different things, I wanted to have something to differentiate them (that's why I think to the color).

**Comment by marieeved** [comment]
I noticed that on the server, the color doesn't appear... the color appears only if the dropdown is not working. So when the dropdown works correctly, it is impossible to change the blue color display by default?

**Comment by LaurentGoderre** [comment]
Not sure I understand the question

**Comment by marieeved** [comment]
the dropdown menu with WET is blue, can I change the color (without touch CSS files)?

**Comment by LaurentGoderre** [comment]
You need a custom stylesheet that overrides the styles to do that.

**Comment by marieeved** [comment]
thanks a lot for the info.
