### ISSUE TITLE
Body background color

### ISSUE THREAD

**Issue by parsbra** [wet-boew/wet-boew#6987]
What is the intended background color for the body of the page and the table backgrounds?

- theme.min.css ­­> has: 
@media screen
body {
    background: #f9f9f9;}
and
body {
    background: #f8f8f8;}

- wet-boew.min.css > has:
 body {
     background-color: #fff;}

Currently the background color being used is #f9f9f9 because theme.min.css appears last in the HTML, but I am guessing that it should be white for both the body and the tables.

**Comment by LaurentGoderre** [comment]
The color of the body or the color of the main content area? The body area is `#f9f9f9` for the WET theme and `#FFF` for the content area

**Comment by parsbra** [comment]
It appears that the #FFF is being over written by the #f8f8f8 from "theme.min.css". The content background is not #FFF...

**Comment by LaurentGoderre** [comment]
On which theme?

**Comment by parsbra** [comment]
canada.ca theme

**Comment by LaurentGoderre** [comment]
Ah ok, and you are right, it's `#F9F9F9`. Perhaps you should log this issue with that theme https://github.com/wet-boew/GCWeb

**Comment by parsbra** [comment]
I'm not really familiar with git hub,  do I need to repost the question, or does the gcweb label that you added handle that?

**Comment by LaurentGoderre** [comment]
Thanks !
