### ISSUE TITLE
Collapsible alert CSS issues

### ISSUE THREAD

**Issue by EricDunsworth** [wet-boew/wet-boew#6991]
Just wanted to bring up another CSS issue that started with PR #6951.

It doesn't seem to play nicely with collapsible alerts:
http://wet-boew.github.io/v4.0-ci/demos/collapsible-alerts/collapsible-alerts-en.html

@thomasgohard Any thoughts on what the "proper" look for these should be now? Should more overrides just be added to hide the borders?

**Comment by LaurentGoderre** [comment]
One more reason why the details styles should only applied when the details class is added to the element like Bootstrap did.

**Comment by hsrudnicki** [comment]
Please continue your thoughts, and update this issue status whether this issue can be closed or otherwise?

**Comment by hsrudnicki** [comment]
Please update this issue's pull request and status, thx

**Comment by hsrudnicki** [comment]
Based on the above, this issue, labeled "Going Stale" and closed as resolved/fixed, due to referenced PR and the other issue closed, or if otherwise?
If you think otherwise, please update this issue's status again, thank you
