### ISSUE TITLE
Calendar of Events: 

### ISSUE THREAD

**Issue by Bgolden67** [wet-boew/wet-boew#6996]
Has anyone had any issues with this?
We can't seem to get the calendar component to load. Using exactly the code provided and using wet 4.0.14

**Comment by pjackson28** [comment]
Does it work for you in the live working examples: http://wet-boew.github.io/wet-boew/demos/cal-events/cal-events-en.html? If so, then you should try upgrading to the latest version of WET or determining what you have done differently than the live working examples.

**Comment by Bgolden67** [comment]
Forgot to do a follow-up. A day after posting the the live example code was updated... it had been showing a wet3 class i guess. Once we noticed this change and changed the class it all works

closing this thread.

Thanks
