### ISSUE TITLE
Horizontal definition lists

### ISSUE THREAD

**Issue by terribly** [wet-boew/wet-boew#6998]
The default behavior of the DT in the horizontal definition list is idiosyncratic in that it aligns the DT to the right.

Alignment to the left would be customary...  if people want an alignment to the left (rarely I suspect), they should be able to override with text-right, correct. 

It definitely makes my glossary sections difficult to read...

**Comment by Bgolden67** [comment]
This has just recently been brought to my attention as well. I believe this is also a bootstrap default... can this be over-ridden as well or is there justification for not, besides the obvious trying not to over ride as much as possible.

**Comment by pjackson28** [comment]
@thomasgohard @pcwsmith Thoughts on this?

**Comment by DK-TBS** [comment]
@pjackson28 - Peter and I just took a look at the horizontal DLs, and we totally agree that the right alignment of the DT is odd.  Both authors and users would probably prefer that these be left aligned.  We'd support this change for sure.

**Comment by pjackson28** [comment]
Any such override should be added to https://github.com/wet-boew/wet-boew/blob/master/src/base/bootstrap-overrides/_base.scss.

@masterbee Anyone from your shop able to add the override?

@thomasgohard Any suggestions for how such an override should be added?

**Comment by terribly** [comment]
What is the status of this? Is there a fix to this coming? I am searching for a solution to how to present numerous glossary lists (and other horizontal DLs we have) in our publications before we migrate them. Am trying to avoid using something like a table so that they render in a usable form...

**Comment by andre-gh** [comment]
Taking this

**Comment by andre-gh** [comment]
Fixed via #6842

**Comment by dravas-nat** [comment]
@thomasgohard   @pjackson28  and @andre-gh  -  just want to confirm that the fix has been applied and that the label and its associated value are now left aligned. correct?

is this the latest example for Horizontal definition lists here:
http://wet-boew.github.io/wet-boew-styleguide/v4/design/lists-en.html#horizontal 

thanks for confirming!!

**Comment by Bgolden67** [comment]
will this be included in 4.0.19?

**Comment by andre-gh** [comment]
Yes, 4.0.19 includes #6842

**Comment by pjackson28** [comment]
@andre-gh Just a note that http://wet-boew.github.io/wet-boew-styleguide/v4/design/lists-en.html#horizontal  is running on a v4.0.19-development build from November 17. It does use the horizontal list fix but still should be rebuilt with the latest version.

**Comment by andre-gh** [comment]
@pjackson28 Thanks, updated

**Comment by dravas-nat** [comment]
@thomasgohard @pjackson28 and @andre-gh @robwloch : in relation to issues #6812 and #6842 - Improvements to the horizontal description list styling
thanks for fixing the default to be left-aligned. 

@thomasgohard : you also raised the following issue which we are facing right now: "There are also other problems with the style, including the fixed width for the  dt  element and long  dt  elements being truncated when they don't fit the fixed width. The styling of the horizontal description lists needs to be entirely redone."
we find the styling of the horizontal description list, specifically the fixed width of 160 px, to be way too restrictive.  
Does anyone have any suggestions to improve it? are you planning to fix this styling issue?
if required, we can provide examples to test this new fix...  let me know if we can assist in any way.

**Comment by terribly** [comment]
Has anyone taken up the issue of the problems with the style of dl-horizontal and the fixed width for the dt element and long dt elements being truncated when they don't fit the fixed width. 

Is it not possible to provide responsive widths to the dt and dd, e.g. <td class="col-md-3" 

This is basically what we do for table columns so why not dt and dd?

Seems to be the obvious way forward for styling this class.

**Comment by eswright** [comment]
Not sure if it is appropriate to ask this here, but is there a way to add a search box to the top of a dl in wet4?  In a page like http://www.nrcan.gc.ca/earth-sciences/geomatics/canadas-spatial-data-infrastructure/8904 'find in page' doesn't work when sections are collapsed.

**Comment by kodecount** [comment]
You could manipulate the [Text highlighting](https://wet-boew.github.io/v4.0-ci/docs/ref/texthighlight/texthighlight-en.html) plugin.

**Comment by eswright** [comment]
It just seems that a searchable glossary page should be something simple with high frequency of use.  Thanks.  I understand using a table is not best practices but at least it is easily filtered.

**Comment by kodecount** [comment]
I was able to do something like this (to get a table filter affect):

```javascript
<script>
wb.doc.on( "wb-ready.wb", function() {
	var main,
	dlFilter,
	div,
	label,
	input,
	i18n = wb.i18n;

	main = document.getElementsByTagName( "MAIN" )[0];
	dlFilter = document.getElementsByClassName( "dl-filter" )[0];

	if ( dlFilter ) {
		div = document.createElement( "div" );
		label = document.createElement( "label" );
		input = document.createElement( "input" );

		if ( !dlFilter.getAttribute( "id" ) ) {
			dlFilter.setAttribute( "id", "wb-dlft-auto" );
		}

		div.className = "dl-filter-component";
		label.innerHTML = i18n( "filter" ) + " ";
		input.setAttribute( "type", "search" );
		input.setAttribute( "aria-controls", dlFilter.id );

		input.addEventListener( "keyup", function() {
			var filter = this.value.toUpperCase(),
			dtList = document.getElementsByTagName( "dt" ),
			ddList = document.getElementsByTagName( "dd" );
			if ( filter ) {
				for ( i = 0; i < dtList.length; i++ ) {
					if ( ( dtList[i] && dtList[i].innerHTML.toUpperCase().indexOf(filter) > -1 ) || ( ddList[i] &&  ddList[i].innerHTML.toUpperCase().indexOf(filter) > -1 ) ) {
						dtList[i].style.display = "";
						dtList[i].nextElementSibling.style.display = "";
					} else {
						dtList[i].style.display = "none";
						dtList[i].nextElementSibling.style.display = "none";
					}
				}
			}
		});

		label.appendChild( input );
		div.appendChild( label );
		main.insertBefore( div, dlFilter );
	}
});
</script>
```

**Comment by duboisp** [comment]
@eswright

> Not sure if it is appropriate to ask this here, but is there a way to add a search box to the top of a dl in wet4? In a page like http://www.nrcan.gc.ca/earth-sciences/geomatics/canadas-spatial-data-infrastructure/8904 'find in page' doesn't work when sections are collapsed.

@eswright Here, in a closed issue, is not the right place for asking new question. Please submit your question by filling a [new issue](https://github.com/wet-boew/wet-boew/issues/new) and feel free to include in your issue description a reference at this closed issue along with your questions/feature request.

Thanks @kodecount for the code snipped, but here in this issue is not the best place considering the original context of this closed issue. +1 for suggesting to create a new issue and in fact that new issue should be where your solution proposal/suggestion should go. Discussing on open issue allow everybody to join and to contribute.
