### ISSUE TITLE
Fieldset Legend.  Provide option to allow Legend to be inside or on border.

### ISSUE THREAD

**Issue by RitchieD** [wet-boew/wet-boew#6999]
WET 4.0.16 moved the fieldset legend inside the border.  I prefer the normal legend in the border itself.  (like a group box)
Can you add an option (class) to allow the consumer to decided preference?

Example: Legend in border

![capture2-2](https://cloud.githubusercontent.com/assets/2989756/8987956/a617b73e-36b1-11e5-95a5-ace0036ce864.JPG)

Example: Legend inside of border
![capture1](https://cloud.githubusercontent.com/assets/2989756/8987968/b62a375a-36b1-11e5-956d-ab584e3edfca.JPG)

**Comment by pjackson28** [comment]
@thomasgohard Please respond.

**Comment by LaurentGoderre** [comment]
Isn't that the default behavior of fieldsets? Perhaps there is a class you need to use to change that behavior.

**Comment by hsrudnicki** [comment]
@thomasgohard Please update this issue status, thx

**Comment by hsrudnicki** [comment]
Made "Going Stale" to close this issue as resolved/fixed or if otherwise?
Either way, please update this issue's status, thank you

**Comment by RitchieD** [comment]
As there is no interested in providing an option, I overrode the WET fieldset styles to behave as desired.
Closing issue.
