### ISSUE TITLE
Main Menu Not Working + JS Error

### ISSUE THREAD

**Issue by accurate** [wet-boew/wet-boew#7008]
Hi there,

I literally copied/pasted the HTML code English content for the base theme (http://wet-boew.github.io/themes-dist/theme-base/content-en.html) and slowly started adding WordPress/PHP code.

I have a dynamic menu that outputs:
```
<nav role="navigation" id="wb-sm" class="wb-menu visible-md visible-lg" typeof="SiteNavigationElement">
  <div class="pnl-strt container visible-md visible-lg nvbar">
    <h2>Topics menu</h2>
    <div class="row">
      <ul class="list-inline menu" role="menubar">
        <li><a href="http://newp.dev/" class="item object-id-4">Home</a></li>
        <li><a href="#menu-15" class="item" aria-haspopup="true">Sample Page</a>
          <ul class="sm list-unstyled" id="menu-15" role="menu" aria-expanded="false" aria-hidden="true">
            <li><a href="http://google.com">Google.com</a></li>
            <li><a href="http://mashable.com">Mashable</a></li>
          </ul>
        </li>
        <li><a href="#menu-17" class="item" aria-haspopup="true">Accurate.ca</a>
          <ul class="sm list-unstyled" id="menu-17" role="menu" aria-expanded="false" aria-hidden="true">
            <li><a href="http://google.ca">Google.ca</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
```

But the drop-down chevrons aren't appearing. When I use the default menu from the content page, it works just fine. 

In addition to that, I'm getting a JS error "Uncaught TypeError: Cannot set property 'innerHTML' of null"
![screen shot 2015-07-31 at 11 45 52](https://cloud.githubusercontent.com/assets/4964631/9011208/c17eafc8-3779-11e5-8f83-d24e4ff45ec7.png)
![screen shot 2015-07-31 at 11 48 30](https://cloud.githubusercontent.com/assets/4964631/9011262/1d96e636-377a-11e5-89dd-37c0b3f2e82c.png)

Also, the mobile version isn't popping up.

I'm on v4.0.16.

**Comment by RobJohnston** [comment]
There's a WordPress variant here:  https://github.com/wet-boew/wet-boew-wordpress

The readme says that it's currently using WET 4.0.4, but it might give you a better starting point.

**Comment by accurate** [comment]
Thanks but I've seen it and prefer to do it myself:
1) Because I believe I can do it better,
2) It hasn't been updated in over a year, and
3) The menus aren't dynamic (which is what I've achieved, but with some minor setback).

**Comment by LaurentGoderre** [comment]
Something seems to be missing from the markup

**Comment by LaurentGoderre** [comment]
Can you check that your footer uses the same format as the one in the examples?

**Comment by voyera** [comment]
+1 on that error, investigating as to why it's giving me trouble... when I figure it out I'll update it here.

**Comment by voyera** [comment]
The issue with my code was that the <nav role="navigation"> was missing the following: data-trgt="mb-pnl".

I mistakenly removed it since I didn't want to load the full menu via ajax... and this is why I got the javascript error. Hope it helps!

**Comment by accurate** [comment]
Goodness, it worked! 

I removed it as well thinking it was related to loading the menu through ajax.

Thanks!

**Comment by voyera** [comment]
@accurate  glad it helped! :)
