### ISSUE TITLE
encoding basic math symbols

### ISSUE THREAD

**Issue by Bgolden67** [wet-boew/wet-boew#7013]
Is there any issue with using <code>&amp;minus; &amp;times; &amp;divide;</code> etc. instead of just typing - x / for simple equations in a piece of content?

**Comment by andre-gh** [comment]
http://www.deque.com/blog/dont-screen-readers-read-whats-screen-part-1-punctuation-typographic-symbols/#grammatical

and

http://www.deque.com/blog/dont-screen-readers-read-whats-screen-part-1-punctuation-typographic-symbols/#typo

Discuss what various screen readers say out loud for various entities.

**Comment by Bgolden67** [comment]
that's kind of disappointing that like the browser wars, we have similar issues with assistive technology not rendering/reading the same ways

**Comment by LaurentGoderre** [comment]
Wonder what would happen if you tried using MathML instead

**Comment by Bgolden67** [comment]
wow that's confusing to try to code a short equation !
will have to look into that more

**Comment by hsrudnicki** [comment]
@Bgolden67 and others: please continue your effort to close this issue and update this issue's status as well!
