### ISSUE TITLE
Open Layers version

### ISSUE THREAD

**Issue by agagnon** [wet-boew/wet-boew#7015]
I have a question regarding the Open Layers plugin. I know this plugin is used in the Geomap plugin in the Web Experience Toolkit, using version 2.13.1. A team here developed an important project using Open Layers 3.0, not the Geomap plugin from WET.

We would like to know if anyone is aware of any accessibility or compatibility issues with Open Layers, especially with version 3.x.  Do you have any concerns about using a newer version of Open Layers than the one used in WET?

If you have any comments, concerns, recommendations or questions, please tell me.

**Comment by pjackson28** [comment]
Related to #7011 which is suggesting an upgrade to OpenLayers 3.

**Comment by jvanulde** [comment]
@LaurentGoderre do we need to create a new repository for openlayers-dist and a mirror for v3.x of OpenLayers?

**Comment by LaurentGoderre** [comment]
I don't remember. I will have to look into it.

**Comment by agagnon** [comment]
Any updates or comments on my specific question ? Thanks.

**Comment by jvanulde** [comment]
HI @agagnon, I have been looking at OL3.x for a couple of weeks now and in fact I have started the process of migration on my local repo. Suffice it say that it will be a significant rewrite. Backwards compatibility for existing configurations will be a challenge. In terms of accessibility I still see that some markup will need to be added to maintain status-quo. I am not an expert however so I will have to defer specifics to someone more knowledgable on the accessibility front.

**Comment by hsrudnicki** [comment]
... and please update this issue status whether it's ready to close or otherwise?

**Comment by agagnon** [comment]
So far, noone has really answered me as to whether I can user OL3.x libraries in a WET 3.,1 project (which already uses OL2.9), is it safe, will there be conflict or compatibility issues ?

**Comment by LaurentGoderre** [comment]
In WET 3.1, I doubt it since it's no longer supported

**Comment by jvanulde** [comment]
@agagnon there shouldn't be a reason why you can't use OL3.x in WET 3.x. You will need to check to see if there are any accessibility issues and correct them. I have started implementing OL3.0 in the current version of WET and haven't run into any library conflicts. I hope this helps.

**Comment by agagnon** [comment]
The thing is that if we use OL3.x librairies in a WET 3.1 web page, WET already uses OL2.9, which means that two different OL versions will load in the same page. Do you think that might be a problem?

**Comment by jvanulde** [comment]
Haven't tested it, but since the namespaces are different you should be okay.

**Comment by hsrudnicki** [comment]
Further, please update this issue's status whether this issue can be closed or otherwise?

**Comment by hsrudnicki** [comment]
Make "Going Stale" due to no further status update(s) or otherwise?
Either way, please update this issue's status whether this issue can be closed as resolved or otherwise, thank you

**Comment by hsrudnicki** [comment]
Does this remain still an open issue? Please update this issue's status, whether this can be closed or otherwise?

**Comment by LaurentGoderre** [comment]
Closing since it's related to WET 3
