### ISSUE TITLE
form (questionnaire): how to display results automatically?

### ISSUE THREAD

**Issue by marieeved** [wet-boew/wet-boew#7020]
Hi,

I want to create a questionnaire. I'm able to use the code  to create the questions. but do we have a code that calculate auto the answers given by user and to display these results on an other page?
by example, I like the poll on meteomedia web site. I know... they display the results with a pie. If I just can display the results on a line, it will be fine. I don't ask so much. I hope... :)
thanks.

**Comment by pjackson28** [comment]
The WET [charts and graphs plugin](http://wet-boew.github.io/wet-boew/demos/charts/charts-en.html) is able to generate pie charts and other visualizations from tabular data. So if you are able to generate a table then WET can take care of generating the visualization. Also WET includes [form validation](http://wet-boew.github.io/wet-boew/demos/formvalid/formvalid-en.html) to help ensure users are answering the questions correctly.

If you were meaning server-side scripting that creates a table from all the answers and produces the table on a new page for you then WET doesn't do that (that requires server-side logic whereas WET is client-side only).

**Comment by marieeved** [comment]
I realized that it's impossible with our server to create a table from all the answers in making several tests with javascript/php code last friday. but thanks for the confirmation. :)

thanks a lot for the information, I will look at these tools. they can be useful for further needs.
