### ISSUE TITLE
Sign in / Sign out Translation

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/wet-boew#7022]
We need the french translation for the sign in / sign out strings.

Here are the strings we need to add to the spreadsheet

* <del>Sign In</del>
* <del>Sign out</del>
* <del>Register</del>
* <del>Account settings</del>
* Sign-on information
* Register
* Signed in as

**Comment by LaurentGoderre** [comment]
@masterbee can we get those translated

**Comment by LaurentGoderre** [comment]
Nevermind, they are already translated

**Comment by LaurentGoderre** [comment]
Actually we need some translations for the sign on pattern, I updated the list above

**Comment by masterbee** [comment]
@LaurentGoderre - thanks @MaximMartel has been assigned this to get the translation back to us. Thank you @MaximMartel

**Comment by MaximMartel** [comment]
Here is what I would say : 

•Sign-on information / Information de l'utilisateur actuel  
•Register / Inscription
•Signed in as / Connecté en tant que

@LaurentGoderre @masterbee

**Comment by LaurentGoderre** [comment]
Can you add those to the Google Spreadsheet?

**Comment by MaximMartel** [comment]
Will do @LaurentGoderre

**Comment by shawnthompson** [comment]
where's the google spreadsheet?

**Comment by LaurentGoderre** [comment]
I can't access it from here, Google Docs is blocked. Please send him the link @pjackson28

**Comment by pjackson28** [comment]
You can access it here: https://docs.google.com/spreadsheets/d/1BmMrKN6Rtx-dwgPNEZD6AIAQdI4nNlyVVVCml0U594o/edit#gid=0. To edit it, you will need to be granted editing privileges under a certain email account. I think you can request edit privileges through the interface. If not, send me an email indicating the email account you want edit privileges granted to.

**Comment by shawnthompson** [comment]
:+1: Thanks

**Comment by MaximMartel** [comment]
Thanks @pjackson28

**Comment by andre-gh** [comment]
Can we use something like https://www.transifex.com/customers/open-source/, is that an option?

**Comment by LaurentGoderre** [comment]
I have been trying to push the project for over a year now but no one is biting. Chances are your department will have an issue because we would need Python for the client to integrated with the process and find a way to get it through the firewalll

**Comment by andre-gh** [comment]
Partial integration is a possibility, just using transifex to manage translations then dumping out to csv is an option..is it not?

**Comment by LaurentGoderre** [comment]
Well, if we were to adopt it, it would be high time to manage our strings better, and separate strings for the javascript and strings for the template. That would mean potentially more work for your department. If @masterbee is ok with that, I will gladly help this transition, because this is something that variants would highly benefit from.

**Comment by andre-gh** [comment]
I will bring it up after October

**Comment by MaximMartel** [comment]
All done within the google drive excel sheet 
Id's are as follow:

`tmpl-sign-on-info` : Sign-on information/Information de l'utilisateur actuel

`tmpl-register`: Register/Inscription

`tmpl-signed-in-as`: Signed in as/Connecté en tant que

@andre-gh @LaurentGoderre

**Comment by LaurentGoderre** [comment]
I'll update my PR! Thanks!

**Comment by LaurentGoderre** [comment]
@MaximMartel not a priority but could you move those translations in the spreadsheet to be with the other existing ones so the strings are not fragmented? The other ones are at line 226
