### ISSUE TITLE
Charts and graphs - Customizing pie charts: 

### ISSUE THREAD

**Issue by terribly** [wet-boew/wet-boew#7024]
There seems to be a glitch here. In the Donut preset wb-charts-donut there is are 9 segments but only 6 values. This shows up in later examples as well. Why are all 9 not showing up?

**Comment by pjackson28** [comment]
@duboisp Please respond.

**Comment by duboisp** [comment]
Thanks @terribly for your question.

In fact it's not a glitch it is how the donut preset is configured for the pie chart flot plugin.

In the "donut preset" a threshold of 0.08 is set for the labeling. That means for all slices that are 8% or less will be hidden.

You can view that configuration in action in the Custom pie chart working example under the "Labelling threshold" heading.

You can avoid/overwrite that setting by using the ```data-flot``` attribute on the table element. Like the following:

```xml
<table class="wb-charts wb-charts-donut table" data-flot='{"series":{"pie":{"label":{"threshold":0}}}}'>
```

*FYI - The ```data-flot``` attribute and ```data-wb-charts``` attribute will overwrite any setting set by a preset.*

Reference: 
* Flot Examples: Pie Charts - http://www.flotcharts.org/flot/examples/series-pie/index.html

Cheers

:smile:

**Comment by terribly** [comment]
@duboisp Thanks! FYI: I think the link to the Flot Examples you shared here might be usefully included in the documentation as it is not clear on the GiTHub pages.

**Comment by hsrudnicki** [comment]
@duboisp and others : Can be this issue closed or otherwise?

**Comment by hsrudnicki** [comment]
Please update this issue's status
