### ISSUE TITLE
Broken Links for Key Resources

### ISSUE THREAD

**Issue by Bgolden67** [wet-boew/wet-boew#7026]
I'm getting this message when i try to access the downloads and the Examples link for Key resources
from here: https://github.com/wet-boew/wet-boew

Unknown Host

 Description: Unable to locate the server named "wet-boew.github.io" --- the server does not have a DNS entry. Perhaps there is a misspelling in the server name, or the server no longer exists. Double-check the name and try again.

**Comment by andre-gh** [comment]
Are you behind a workplace firewall which might be blocking access?

**Comment by Bgolden67** [comment]
i wasn't blocked yesterday.. wouldn't surprise me if they did something over night.. wouldn't be the first time they updated the firewall and screwed up security settings, but that's not the usual message when it's a firewall issue

**Comment by Bgolden67** [comment]
seems resolved now.. closed
