### ISSUE TITLE
What is the purpose of this unused file?

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/wet-boew#7027]
This file here doesn't seem to be in use anywhere

https://github.com/wet-boew/wet-boew/blob/master/site/pages/ajax/mobmenu.hbs

**Comment by masterbee** [comment]
@LaurentGoderre - after a rather long look into the history of this project :) this file was actually a fragment from the first alpha WET4 before we started to use JS to build the mobile menu. It used to be included in the page and just made visible via the CSS grid. It can be safely removed from any of the code I have seen.

**Comment by LaurentGoderre** [comment]
Nice!
