### ISSUE TITLE
Font awesome version

### ISSUE THREAD

**Issue by colleenhickey** [wet-boew/wet-boew#7032]
Are we limited to using version 4.0.3 for the font awesome icons or can we use the latest, 4.4?

**Comment by LaurentGoderre** [comment]
I don't think WET implements font awesome. Therefore II don't think there is any issue with using the latest version.

**Comment by colleenhickey** [comment]
Just making sure, since the instruction box on the Icons page has a link to v4.0.3.

Thanks!
