### ISSUE TITLE
SASS compile errors in tabs plugin?

### ISSUE THREAD

**Issue by rmwbweb** [wet-boew/wet-boew#7035]
Was compiling WxT using the SCSS source grabbed from GitHub Aug. 17 (using the default theme.scss) and got the following two errors:

> error src/plugins/tabs/_base.scss 
> Line 430: ".wb-tabs.carousel-s2 figure img" failed to @extend "%tab-width-100-height-auto".
> The selector "%tab-width-100-height-auto" was not found.

and ...

> error src/plugins/tabs/_screen-xxs-max.scss
> Line 13: ".wb-tabs.carousel-s1 li[role="presentation"]" failed to @extend "%accessible-invisible-xxSmallView".
> The selector "%accessible-invisible-xxSmallView" was not found.

If I made those those statements !optional everything else compiled just fine.

Any hints as to the source of those errors?

**Comment by pjackson28** [comment]
It doesn't look like either of those are needed and there seems to be no impact if they are removed (other than stopping the SCSS compile errors). So I suggest that they be removed.

I checked back through the history and looks like it has been an issue for a long time, just never flagged as an error. Perhaps a recent update to the SASS compiler is surfacing these as errors.

**Comment by masterbee** [comment]
@rmwbweb  and @pjackson28 - second that after the review. @rmwbweb would you like to make a PR to remove them?

**Comment by rmwbweb** [comment]
@masterbee :  Nor sure I should risk taking down canada.ca with my first pull request :-) But here's the diff for the two files in question with the complete removal that's working for us.

**./src/plugins/tabs/_base.scss:** (at line 428)
````
 428,431d427
 <
 <                       img {
 <                               @extend %tab-width-100-height-auto;
 <                       }
````

**./src/plugins/tabs/_screen-xxs-max.scss:** (at line 10)
````
 10,17d9
 <       &.carousel-s1 {
 <               li {
 <                       &[role="presentation"] {
 <                               @extend %accessible-invisible-xxSmallView;
 <                       }
 <               }
 <       }
 <
````

**Comment by LaurentGoderre** [comment]
I am not getting any compile errors, which project are you trying to compile?

**Comment by rmwbweb** [comment]
@LaurentGoderre  Initially, the WxT theme right out of the box, but anything that uses that .scss above gives me the error because those extended selectors don't seem to exist anywhere.

This may be because I am compiling with vanilla sass and it's picky in that situation.

**Comment by LaurentGoderre** [comment]
The build would be failing if there was something wrong with the SCSS though so I am wondering what is different

**Comment by pjackson28** [comment]
@LaurentGoderre I checked the source code and they are invalid extends (found the extends but couldn't find the definitions in any of the source files). Not sure why the build is not flagging them as errors.

**Comment by hsrudnicki** [comment]
as a further to the above, please update this issue's status whether this issue can be closed or otherwise?

**Comment by hsrudnicki** [comment]
Made "Going Stale" due to no further status update(s), or if otherwise?
Either way, please update this issue's status whether this issue can be closed as resolved/fixed or otherwise? Thank you.

**Comment by rmwbweb** [comment]
As of last week, this situation still existed. Our approach (non-GoC) is that we want to use the WxT SASS untouched -- making all modifications in our theme SASS. If we have to edit WxT SASS every time it's updated (even for something so tiny), that's not ideal.

Despite what I said above, I will be happy to take responsibility for submitting a fix if you have patience :-)

**Comment by hsrudnicki** [comment]
Based on the last comment, this issue is opened and active

**Comment by LaurentGoderre** [comment]
We certainly can and should fix this issue that seem to only happen in the ruby version of sass. I will warn though that recompiling WET with a different implementation sass may cause the output stylesheet to differ from the official one. It shouldn't in theory but it might

**Comment by kristremblay** [comment]
Thank you, Laurent, that's good to know going forward.

**Comment by LaurentGoderre** [comment]
I just compared the two and there doesn't seem to be a lot of differences. One thing to be mindful is that we run autoprefixer on the css file after compiling it through sass. The autoprefixer differences account for most of the changes in the diff I made.

**Comment by LaurentGoderre** [comment]
Thanks everyone for your help on this!
