### ISSUE TITLE
Equal to validation

### ISSUE THREAD

**Issue by Spock07** [wet-boew/wet-boew#7036]
Recently I ran into an issue with the "equal to" validation, I know it is intended for validating passwords and works fine. However it has been used for validating emails and it has an issue. The validation works but it requires that the email to validate using Case sensitive. Since emails are not case sensitive we need an email equal to method that does not validate case. Is this possible?

**Comment by LaurentGoderre** [comment]
To add a custom validator you need to do:

```javascript
wb.doc.on( "wb-ready.wb-frmvld", ".wb-frmvld", function( event ) {
    $.validator.addMethod("equalTo", function(value, element) {

    });
});
```

Make sure that another rule doesn't already exist for it though

**Comment by hsrudnicki** [comment]
Please update this issue's status whether this issue can be closed or otherwise?

**Comment by hsrudnicki** [comment]
Based on the above, made "Going Stale" to close this issue, if no further response/comment, as resolved or if otherwise?
Either way, please update this issue's status, thank you

**Comment by hsrudnicki** [comment]
This is closed as resolved, based on the above. If you think otherwise, please update the status of this again
