### ISSUE TITLE
Table Header cells highlighting on hover

### ISSUE THREAD

**Issue by apressey** [wet-boew/wet-boew#7040]
In the WET 3 version of the Laws website, we used the header cell highlighting features shown here:

http://wet-boew.github.io/wet-boew-legacy/v3.1/demos/zebra/columnhighlight.html

Is there a way to do this in the current version of the framework?

**Comment by LaurentGoderre** [comment]
Here is Bootstrap's documentation
http://getbootstrap.com/css/#tables-hover-rows

**Comment by apressey** [comment]
Thanks, yes I already looked at that page.   I want Column/Row Header cell highlighting.

For example, see the complex headers on this page:

http://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1400/page-46.html

and notice how the highlighting helps visually identify the headers for the cell.

**Comment by LaurentGoderre** [comment]
The last example in this documentation page implements the vertical hover as well

http://wet-boew.github.io/wet-boew/demos/zebra/zebra-en.html

**Comment by apressey** [comment]
Thanks, yes, I tried that as well.  I showed all the options to the client, (zebra stripe, row hover, col hover, data tables, and different combos of those features) but still they like it better the way we have it now.  And it makes sense.  Highlighting the whole column is distracting, all we want to highlight is the header cells of the active (hovered) cell.

So, im guessing this is not available in the new framework, since you have suggested all the stuff that I tried already.  Oh well, Data Tables is a great enhancement, but we dont really need those features in this case.

Thanks for trying

**Comment by sgdowney** [comment]
This may not be the best solution, but if you could identify the CSS for the vertical table body highlighting, you could override it to make it the same as the none highlighted table body cells.  That may still highlight the header cells as required.

**Comment by hsrudnicki** [comment]
Can be this issue closed or otherwise? Please update this issue's status

**Comment by apressey** [comment]
This was a question not an issue.  The question was:

Is there a way to do this in the current version of the framework?

So, I'm thinking the lack of an answer could be mean that the answer is No.
