### ISSUE TITLE
Font Error

### ISSUE THREAD

**Issue by TinoTran-Work** [wet-boew/wet-boew#7041]
Good morning,

We recently updated to the latest version of the WET Framework from v4.0.10 to v4.0.16.  

When we load our page now, we are getting the following error.  

![fonterror](https://cloud.githubusercontent.com/assets/9271170/9362629/dae78d88-465e-11e5-97a3-92eca05130eb.png)

Thank you for your time.  Have an amazing day!

**Comment by pjackson28** [comment]
Do you get the same errors when visiting the live working examples (http://wet-boew.github.io/wet-boew/demos/index-en.html)? If not, then did you copy over all of the files as is from the v4.0.16 zip file? Folder structures changed a bit recently so these errors could be because the files are not copied over to where the files are expected.

**Comment by sgdowney** [comment]
Which folders would be the correct ones to use?  When I unzip the GCWU-FEGC release files I used the 
\assets
\css
\fonts
\js
folders from the root.  
Should I be using the these folders instead?
\theme-gcwu-fegc
\wet-boew

**Comment by LaurentGoderre** [comment]
The two are kind of duplicate for backwards compatibility. You can use either one of them

**Comment by sgdowney** [comment]
It would appear that using these folders results in the @font-face error
\assets
\css
\fonts
\js
Using these folders does not result in the @font-face error
\theme-gcwu-fegc
\wet-boew

**Comment by LaurentGoderre** [comment]
Really?

**Comment by sgdowney** [comment]
I'll double check, but that does seem to be the case.

**Comment by LaurentGoderre** [comment]
I found it. I am working on a fix

**Comment by LaurentGoderre** [comment]
Actually no, It worked for me using the latest code. I will have to check if something is broken specifically with v4.0.16

**Comment by loyd33** [comment]
I was getting the same error on v. 4.0.16
Found a fix for this .
replace  \fonts\glyphicons-halflings-regular.eot (36 KB)
by \wet-boew\fonts\glyphicons-halflings-regular.eot (20 KB).
Error disappear. The size of the **"eot"** file got bigger in **\fonts** folder starting in version 4.0.15
I don't know why.

**Comment by LaurentGoderre** [comment]
This is fixed in v4.0.18
