### ISSUE TITLE
Abbr has dotted underline in Firefox 40+

### ISSUE THREAD

**Issue by sam-he** [wet-boew/wet-boew#7043]
Not sure this is a bug or not. 

Firefox 40 starts to display dotted underline for `<abbr>`. As you can see on these pages:
http://weather.gc.ca/city/pages/on-118_metric_e.html
http://news.gc.ca/web/article-en.do?nid=891909 

abbr[title] {border-bottom:1px dotted #767676;} is defined in theme.min.css as well.

Other readings:
https://bugzilla.mozilla.org/show_bug.cgi?id=1170480 
http://www.w3.org/TR/html5/rendering.html#phrasing-content-0 
https://github.com/twbs/bootstrap/issues/16574

Should we let browser to handle the text decoration? what's the expected display for <abbr> on GC pages?

Sam

**Comment by Pacoup** [comment]
This is a Chrome bug (as pointed out in https://code.google.com/p/chromium/issues/detail?id=480213, Chrome does not currently consider ```text-decoration: dotted underline;``` a valid property), so, in theory, it should be left as is.

That I know of, there is no way to mimic the property correctly without native rendering.

Unless it's the other way around; remove the text decoration for all browsers, but I'm not sure what this means for accessibility. @LaurentGoderre ?

**Comment by LaurentGoderre** [comment]
I thought it always was underlined like that....I am not sure we should remove it for all browsers

**Comment by Pacoup** [comment]
Yeah, I don't think we should remove it either.

**Comment by Bgolden67** [comment]
I agree.. don't remove it.. when it's not there.. i get questioned about where it is

**Comment by masterbee** [comment]
third that as well and mirror @Bgolden67 experience on our end as well.

**Comment by hsrudnicki** [comment]
So, can be this issue closed or otherwise?

**Comment by hsrudnicki** [comment]
Made "Going Stale", as well closed this issue as resolved based on the above or if otherwise?
In case of otherwise, please update this issue's status again, thank you
