### ISSUE TITLE
dropdown menu - how to write links?

### ISSUE THREAD

**Issue by marieeved** [wet-boew/wet-boew#7046]
Hi,
now that I have placed my files in different folders to respect my architecture, the dropdown doesn't work on every page...
questions:
with a dropdown menu, in the ajax file, my links must to be only like : 
"accueil.html" 
(even if the real path between the ajax file and this file is more like: "../fra/accueil.html"
because when you navigate on the website, the user can be anywhere so the path to this file change each time/on each page where they are?

that's mean that I can't have 2 files with the same name even if there are in different folders?
Ex: "nous/index.html" and "nouvelles/index.html"... because in the ajax file I have to use this links "index.html" and "index.html"

I'm lost! Is there anyone who can help me find my "path".

**Comment by LaurentGoderre** [comment]
Because the ajax menu gets injected into a page, the links are relative to the page including it not the ajax itself which means that relative links are practically impossible. You need to use absolute links inside your ajax file.

**Comment by marieeved** [comment]
while reading you, I realize that it was so obvious... :)
thank you for answering all of my questions, even the small ones.

**Comment by LaurentGoderre** [comment]
No problem :)
