### ISSUE TITLE
Calendar icon - link title and invisible text

### ISSUE THREAD

**Issue by colleenhickey** [wet-boew/wet-boew#7047]
We have noticed that the title on the link for the calendar icon, as well as the invisible text, includes anything within the field label, including error message.  I would have expected that it should include only the text within the span with class of field-name.  See attached screen capture.

![calendar_link_title](https://cloud.githubusercontent.com/assets/1843862/9411597/ea8511b0-47f4-11e5-912b-c9f0774e625c.jpg)

**Comment by hsrudnicki** [comment]
Please update this issue's status whether this issue can be closed or otherwise?

**Comment by hsrudnicki** [comment]
Based on the above, made "Going Stale" to close this issue, lingering for 4 months, or if otherwise?
Either way, please update this issue's status whether this issue can be closed or otherwise, thank you

**Comment by LaurentGoderre** [comment]
Can be addressed by #6606 - needs test
