### ISSUE TITLE
Data Ajax: plugin not working on TBS-SCT site.

### ISSUE THREAD

**Issue by EricLavoie88** [wet-boew/wet-boew#7049]
I'm trying to use the Data Ajax plugin on our site and it doesn't seem to work. However, using the same code, I can ajax in the content from the "Data Ajax" examples on the WET site.

Here is my code. The first section is trying to call a page within www.tbs-sct.gc.ca and the second section is including content from your website. Note that this code is on a different domain than www.tbs-sct.gc.ca.

```html
<h2>Test www.tbs-sct.gc.ca</h2>

<section data-ajax-after="http://www.tbs-sct.gc.ca/psm-fpfm/learning-apprentissage/ptm-grt/adcm-eng.htm" class="original">
	Test TBS
</section>

<h2>Test WET-BOEW</h2>

<section data-ajax-after="http://wet-boew.github.io/v4.0-ci/unmin/demos/data-ajax/ajax/data-ajax-extra-en.html" class="original">
	Test WET
</section>
```

Note: The htm in the first section is wrapped in the `<section class="ajaxed-in">` tag.

Any idea why this wouldn't work? 

Thanks

**Comment by EricLavoie88** [comment]
Just realized the code did not work. Do you have access to this page: http://authoring.generic.gc.ca/test-fra.asp

**Comment by LaurentGoderre** [comment]
Doing cross-domain ajax request is very tricky. It is possible to do but it is very complex.

**Comment by EricLavoie88** [comment]
What would be involved in making it work?

**Comment by LaurentGoderre** [comment]
Some server-side coding to emulate JSONP but with HTML. We did it for the centralized priorities images.

**Comment by LaurentGoderre** [comment]
Actually, the first step is to enable CORS properly on the servers to allow cross site sharing, then you need the JSONP emulation for browser that don't support CORS.

**Comment by andre-gh** [comment]
Are there browsers aside from IE9 which do not support CORS?

**Comment by LaurentGoderre** [comment]
No

**Comment by hsrudnicki** [comment]
As a further, can be this issue closed or otherwise?

**Comment by EricLavoie88** [comment]
Yes it can be closed.
