### ISSUE TITLE
Input type="date" polyfill (date picker): 

### ISSUE THREAD

**Issue by jueheed** [wet-boew/wet-boew#7050]
Is there a way to specify the date format other than yyyy-MM-dd? With the default setting, Chrome browser displays the date format yyyy/MM/dd instead. How would we toggle between them?

**Comment by LaurentGoderre** [comment]
The date format in the case of native date picker, such as Chrome, because the date returned will always be in ISO format

**Comment by jueheed** [comment]
The problem is it's not returning ISO format - it's returning in yyyy/MM/dd, we would like to have it displayed to ISO yyyy-MM-dd in Chrome.

**Comment by andre-gh** [comment]
I believe the date format chrome displays to the user (different from the value it programmatically returns) is based on the language setting of the user's browser and or OS.

**Comment by andre-gh** [comment]
I believe the date format chrome displays to the user (different from the value it programmatically returns) is based on the language setting of the user's browser and or OS.

https://developers.google.com/web/updates/2012/08/Quick-FAQs-on-input-type-date-in-Google-Chrome?hl=en

> Users can type a date value into the text field of an input[type=date] with the date format shown in the box as gray text. This format is obtained from the operating system’s setting.  Web authors have no way to change the date format because there currently is no standards to specify the format.

**Comment by LaurentGoderre** [comment]
The date that is displayed and the date that is returned are not necessarily the same. However, the date returned will always be in ISO format

**Comment by andre-gh** [comment]
Yes, the date returns in the same format regardless of what is displayed.  This approach is actually good in some ways as it adapts to the user's local preferences instead of the designer/developer guessing which format they prefer.   The downside is more-so in data entry and such where you might want to specify an exact input format for transferring data and avoiding mistakes by having the same input format throughout all setups.

**Comment by LaurentGoderre** [comment]
I guess so but then if you have a data entry workflow, wouldn't you just ensure that all the device used for data entry have the same settings? It becomes less a web problem and more a device problem.

**Comment by andre-gh** [comment]
You normally would, in the case I am recalling there were data entry coming in from various folks in the provinces who were using machines managed by the specific provinces inputting data for the federal government so there was some disarray in configuration but they wanted a very specific data format for the input box to avoid errors.

More of an edge case, but there are use cases where you might want a specific date input format.  There is however, nothing we can do about that without forcing a polyfill so the conversation of much value.

Just interesting to note that there are indeed cases where clients might want to enforce a specific date input box and you have to explain to them "if they use chrome, they get a different input format depending on their settings" and give them a document explaining how to change language preferences.

**Comment by LaurentGoderre** [comment]
Unfortunate!

**Comment by hsrudnicki** [comment]
So, can be this issue closed or otherwise?

**Comment by andre-gh** [comment]
This issue can be closed.  

The answer is no because "This format is obtained from the operating system’s setting" and because "there currently is no standards to specify the format."

Via https://developers.google.com/web/updates/2012/08/Quick-FAQs-on-input-type-date-in-Google-Chrome?hl=en

**Comment by hsrudnicki** [comment]
Based on the above, this issue has been closed.
In case of otherwise, please update this issue's status again, thank you.
