### ISSUE TITLE
Stop adding automatic top margin to heading

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/wet-boew#7052]
The automatic top-margin that is added to all heading elements make their use in anything other than simple content very complicated. The top margin should probably be controlled via CSS classes, i.e. `<h2 class="h2-margin">Heading</h2>` or `<h2 class="h4 h4-margin">Heading</h2>`

**Comment by hsrudnicki** [comment]
Now is time to update this issue's status whether this issue had been solved/fixed and can be closed or otherwise?

**Comment by hsrudnicki** [comment]
Made "Going Stale" due to no further status update(s)/discussion to resolve this issue or if otherwise?
Either way, please update this issue's status, thank you
