### ISSUE TITLE
Charts & Graphs Bar Spacing

### ISSUE THREAD

**Issue by upsonp** [wet-boew/wet-boew#7056]
I'm having a bit of an issue with my chart. I only have two items to display and that seems to create a bit of an issue with how the bars are spaced. See image.

It looks like the plot is paired as [orange, red] when it should be paired as [red, orange], especially when you get over to 2050+

![fig1](https://cloud.githubusercontent.com/assets/3355126/9467100/a195bdc4-4b0f-11e5-9a88-dc3aaa0bdfa9.png)

Is there a way to create a gap between the bars? and/or change the width of the bars maybe?

I created a work around by adding a row of zeros to my table.

![fig2](https://cloud.githubusercontent.com/assets/3355126/9467314/32287236-4b11-11e5-9e09-fb492ab2bf2e.png)

It makes the plot look better, but has some draw backs. 
1) there's a row of data screen readers will read, which is going to confuse people
2) there's blank legend item, which is going to confuse people
3) there's just a hint of the blue bar on the graph even though the value is zero, which is going to confuse people

But the bar widths and spacing looks perfect.

**Comment by pjackson28** [comment]
@duboisp Please respond.

**Comment by duboisp** [comment]
@upsonp I did a couple test with differents configuration for flot and it seems that using a ```lineWidth``` set to 0 fix your issue.

Here the source code of my test that might work for you. 
```html
<table class="wb-charts wb-charts-bar table" data-flot='{"series": {
        "bars": {
            "lineWidth": 0
        }
    }}'>
<caption>Title</caption>
	<tr>
		<th>Title
		<th>2020
		<th>2030
		<th>2040
		<th>2050
		<th>2060
		<th>2070
		<th>2080
		<th>2090
		<th>2100
	<tr>
		<th>TG RCP4.5
		<td>0
		<td>1
		<td>6
		<td>9
		<td>11
		<td>13
		<td>18
		<td>22
		<td>26
	<tr>
	<th>TG RCP8.5
		<td>3
		<td>4
		<td>7
		<td>9
		<td>13
		<td>19
		<td>25
		<td>33
		<td>40
</table>
```

But that will change a little bit the appearance of the charts

![wet-boew-7056](https://cloud.githubusercontent.com/assets/1676030/9512051/4b7b2d9c-4c4b-11e5-8d26-f5ae6483a428.PNG)

Cheers

**Comment by hsrudnicki** [comment]
So, based on the above answer, can be this issue closed or otherwise? Pls update this issue's status

**Comment by upsonp** [comment]
Thanks I'm good with this solution. Case closed
