### ISSUE TITLE
WET version 4.0.17 themes unavailable

### ISSUE THREAD

**Issue by nicolasraymond** [wet-boew/wet-boew#7057]
Hi,
On this page : http://wet-boew.github.io/wet-boew/docs/versions/dwnld-en.html, the production files for the Government of Canada Web Usability and Government of Canada Intranet are broken links.

**Comment by MaximMartel** [comment]
Base, Government of Canada Intranet and Open Government Platform (OGPL) production files are broken links as well.

**Comment by MaximMartel** [comment]
@nicolasraymond Pull request created and will be fixed by pull request #7060

**Comment by andre-gh** [comment]
In the mean time the 4.0.17+1 releases for the broken themes are available direct via Github.  

https://github.com/wet-boew/theme-gcwu-fegc/releases/tag/v4.0.17%2B1

and

https://github.com/wet-boew/theme-gc-intranet/releases/tag/v4.0.17%2B1

For the themes you mentioned
