### ISSUE TITLE
Determine if a form is valid through javascript

### ISSUE THREAD

**Issue by jfbourgon** [wet-boew/wet-boew#7059]
I'm using the WET4 form validator plugin and it performs as expected except that I would like to be able to determine if the submitted form is actually valid through javascript. Here is the code snippet I use:

```javascript
$( "#edit-form" ).submit( function( event ) {
    event.preventDefault();          
    if ( $( this ).valid() ) {
        // perfom some action such as invoking AJAX calls
    }
} 
```
The condition evaluate well but the call to `valid()` makes the error summary to be displayed twice as shown here:
![form-validation](https://cloud.githubusercontent.com/assets/1030226/9470086/5190ee62-4b18-11e5-89c4-58f08f89f55b.jpg)

**Comment by pjackson28** [comment]
That's because valid() tells jQuery validation to run the validation a second time. If you want to fire something off of a successful submit then do so in the action attribute of the form element as that is only fired on a successful submit. Here is an example:

```html
<div class="wb-frmvld">
     <form action="javascript:handleSuccessfulSubmit();" method="get" is="validation-example">
...
<script>
handleSuccessfulSubmit = function() {
     window.console.log( "valid form" );
};
</script>
...

**Comment by hsrudnicki** [comment]
Now is time to update this issue's status whether this issue can be closed or otherwise?
