### ISSUE TITLE
Texthighlight - special character can break page rendering

### ISSUE THREAD

**Issue by apressey** [wet-boew/wet-boew#7063]
A member of the public let us know that our page could be broken using special characters in the URL for the Texthighlight feature.  The example page also shows the problem.

http://wet-boew.github.io/wet-boew/demos/texthighlight/texthighlight-en.html?txthl=%3c#example

**Comment by andre-gh** [comment]
https://github.com/padolsey/findAndReplaceDOMText attempts to solve this problem, we should look into porting the plugin to that...< and > are not the only potential issues with the way this plugin works.

**Comment by hsrudnicki** [comment]
This is further to the above, can be this issue closed or otherwise? Pls update this issue's status

**Comment by apressey** [comment]
There has been no change, why would it be closed?  When I click on the link I posted its still a mess.

**Comment by booshi** [comment]
@apressey On click of the link [Highlight example text that meets the search criteria] (http://wet-boew.github.io/wet-boew/demos/texthighlight/texthighlight-en.html?txthl=avian%20influenza+world+cook+flu-like%20symptoms+Don%27t%20Forget...+causes%20sickness%20in%20birds,%20it%20can%20also%20infect%20people.) the page is no longer broken. Can you please confirm and close this issue.

**Comment by hsrudnicki** [comment]
Got it unbroken, so this issue can be closed.
In case of proven otherwise, please update this issue's status again, thank you

**Comment by apressey** [comment]
Please click on the link in the original post.  I just checked in IE 10, Firefox and Chrome.  And the page is broken in all 3.  If the search string contains an html special character it breaks the display.  It does not look fixed to me.
![image](https://cloud.githubusercontent.com/assets/1998701/11957926/b43b5372-a892-11e5-8cd9-432b08a7dd20.png)

**Comment by apressey** [comment]
This issue should not have been closed.  I outlined steps in the original post to produce the error, and the error still occurs.  And now, I am unable to open the post again myself.

**Comment by hsrudnicki** [comment]
This issue has been reopened, but when I briefly checked including my colleague on IE10, and Firefox the link http://wet-boew.github.io/wet-boew/demos/texthighlight/texthighlight-en.html?txthl=avian%20influenza+world+cook+flu-like%20symptoms+Don%27t%20Forget...+causes%20sickness%20in%20birds,%20it%20can%20also%20infect%20people., we did not have the markup in yellow color unless something else should have been done...

**Comment by apressey** [comment]
As I explained, the query inside the link has to have a special character in it.  Thats why I included one in the original post.  Your link doesnt have an html special character in it.

**Comment by hsrudnicki** [comment]
Yes, you are right, also we got the same error as you when we tested the link: http://wet-boew.github.io/wet-boew/demos/texthighlight/texthighlight-en.html?txthl=%3c#example
on IE10 and Firefox browsers, so again the issue stays as opened due to the problem as you explained, thank you

**Comment by hsrudnicki** [comment]
Is this still a bug? Please update this issue's status for this year as well, thank you

**Comment by apressey** [comment]
I opened the link http://wet-boew.github.io/wet-boew/demos/texthighlight/texthighlight-en.html?txthl=%3C#example
 in Chrome and IE 11.   The bug is exactly the same, nothing has changed.

**Comment by cybersubtype** [comment]
@apressey @hsrudnicki Found an easy solution on [stackoverflow](http://stackoverflow.com/questions/1787322/htmlspecialchars-equivalent-in-javascript/4835406#4835406).

Basically add this:
```javascript
// clean html characters
var map = {'&': '&amp;','<': '&lt;','>': '&gt;', '"': '&quot;',"'": '&#039;'};
searchCriteria = searchCriteria.replace(/[&<>"']/g, function(m) { return map[m]; });
``` 
Before [Line 46](https://github.com/wet-boew/wet-boew/blob/f5f33e0240649fe22fd12f28978113841762bffa/src/plugins/texthighlight/texthighlight.js#L46)

**Comment by kodecount** [comment]
@apressey Not sure if still involved in WET, but I made the PR for the fix.

**Comment by apressey** [comment]
Issue is resolved.  Clicking on the link in my original post, no longer results in the special characters displaying on the screen.
