### ISSUE TITLE
Calendar of Events: support for dates with several events  

### ISSUE THREAD

**Issue by SBleeks** [wet-boew/wet-boew#7065]
If there are 8 items/events in a given date, will this cause an issue with the overlay display?  currently the working example offers a maximum of 2 or 3 events.  Even this many events within the overlay seems to cover the calendar.  so, if up to 10 items/events occur in a given date, is it possible to display the overlay somewhere else on the page so that the overlay presentation doesn't interfere with access to the calendar via the mouse. 
Would it be possible to see the fluid calendar with  dates containing 8 events?
@wet-boew/access-working-group

**Comment by hsrudnicki** [comment]
Please update this issue's status whether this issue can be closed or otherwise?

**Comment by hsrudnicki** [comment]
Based on the above, as well a lack of further discussion, this issue labeled "Going Stale" to close this as resolved or if otherwise? 
@SBleeks : Do you still need an answer to your question?
Either way, please update this issue's status whether this issue can be closed or otherwise, thank you

**Comment by LaurentGoderre** [comment]
Reviewing this, if we move the overlay, it would make it impossible to manage focus and what to display when if it's in a different position.

**Comment by hsrudnicki** [comment]
Can be this issue closed or otherwise? Please update this issue's status for this current year as well, thank you

**Comment by masterbee** [comment]
closed issue since it appears to be abandoned by carrier (creator of issue)
