### ISSUE TITLE
No actual video content

### ISSUE THREAD

**Issue by SBleeks** [wet-boew/wet-boew#7066]
There doesn't seem to be any actual video content here.  We'd like to review the player controls while the video is playing.

@wet-boew/access-working-group

**Comment by LaurentGoderre** [comment]
The working examples has a video content.

**Comment by MaximMartel** [comment]
The controls appears to show when the video is playing. 
http://wet-boew.github.io/wet-boew/demos/multimedia/multimedia-en.html

Is there a specific browser that your having this issue?

**Comment by SBleeks** [comment]
Using IE9 it seems to take a minute or more to load the video.  No issue with IE11.  No issue with Firefox.

I suppose we can close the issue
