### ISSUE TITLE
Duplicate validation errors if using "require_from_group"

### ISSUE THREAD

**Issue by rachelywang** [wet-boew/wet-boew#7067]
I added a customized validation to ensure at least one field (telephone number, email) must be filled, using jQuery "require_from_group". Now the errors are displayed multiple times at the top of the page.

![snap5](https://cloud.githubusercontent.com/assets/12052626/9547845/15c9ed7a-4d6b-11e5-81b0-d17cc3b3ca78.jpg)

My code:

<div class="row">
            <div class="col-md-6 pull-left">
                <div class="form-group"><label for="submitter_telephoneNumber" class="required"><span class="field-name">Telephone (including area code): </span><br> <strong class="required">(Telephone OR Email is required)</strong> , both is preferred</label>
                     <input class="form-control required_group" type="tel" id="submitter_telephoneNumber" name="submitter_telephoneNumber" ng-model="submitter.telephoneNumber" placeholder="Telephone" maxlength="50"/>
                </div>

```
        </div>
        <div class="col-md-6 pull-right">
            <div class="form-group"><label for="submitter_email" class="required"><span class="field-name">Email: </span><br> <strong class="required">(Email OR Telephone is required)</strong> , both is preferred</label>
                 <input class="form-control required_group" type="email" id="submitter_email" name="submitter_email" ng-model="submitter.email" placeholder="email@example.com" maxlength="50"/>
            </div>
        </div>
    </div>
```

...

<script src="./wet-boew/js/wet-boew.min.js"></script>

<script>
wb.doc.on( "wb-ready.wb-frmvld", ".wb-frmvld", function( event ) {
    $(".required_group").each(function () { 
        $(this).rules('add', {
            require_from_group: [1, ".required_group"],
            messages: {
                require_from_group: 'An email or telephone is required.'
            }  
        });
    });
});

I'm using Firefox 40.0.3 and latest WET4 version 17.

I tried previous versions, and this issue appeared since version 12 when the fix of summary links was introduced.

**Comment by cgroves** [comment]
Problem started occurring in version 12

**Comment by wangyuxiao** [comment]
My code:

<div class="row">
            <div class="col-md-6 pull-left">
                <div class="form-group"><label for="submitter_telephoneNumber" class="required"><span class="field-name">Telephone (including area code): </span><br> <strong class="required">(Telephone OR Email is required)</strong> , both is preferred</label>
                     <input class="form-control required_group" type="tel" id="submitter_telephoneNumber" name="submitter_telephoneNumber" ng-model="submitter.telephoneNumber" placeholder="Telephone" maxlength="50"/>
                </div>
            </div>
            <div class="col-md-6 pull-right">
                <div class="form-group"><label for="submitter_email" class="required"><span class="field-name">Email: </span><br> <strong class="required">(Email OR Telephone is required)</strong> , both is preferred</label>
                     <input class="form-control required_group" type="email" id="submitter_email" name="submitter_email" ng-model="submitter.email" placeholder="email@example.com" maxlength="50"/>
                </div>
            </div>
        </div>
...
<script src="./wet-boew/js/wet-boew.min.js"></script>
<script>
wb.doc.on( "wb-ready.wb-frmvld", ".wb-frmvld", function( event ) {
    $(".required_group").each(function () {	
        $(this).rules('add', {
            require_from_group: [1, ".required_group"],
            messages: {
                require_from_group: 'An email or telephone is required.'
            }        	
        });
    });
});

**Comment by wangyuxiao** [comment]
My code:

![snap6](https://cloud.githubusercontent.com/assets/12052626/9554545/8cc8b2a2-4d94-11e5-84e9-07a251546a25.jpg)

**Comment by LaurentGoderre** [comment]
I don't think your code does what you think it does.....what you are telling it to do is to loop through all fields with the `required_group` class and to create validation rule. So you end up with as many duplicate validation rule as there are fields on the page. This is why you end up with so many duplicated error messages.

**Comment by wangyuxiao** [comment]
I want either telephone or email or both to be filled. So I do the same thing like what the jQuery validation example does. See the link: http://jqueryvalidation.org/require_from_group-method/

I tried to copy the following code to the line after "validator = $form.validate( {" (Line 5750 of web-boew.js version 12). It gave me the same results.

I found out the "setTimeout( function() {" function of the showErrors function causes me the problem.

Thanks.

**Comment by rachelywang** [comment]
I moved the declaration of "$summaryContainer" from the beginning of the showErrors function to the place inside of the setTimeout function, now it works. Here is the code:

setTimeout( function() {
var $summaryContainer = $form.find( "#" + errorFormId );
// Output our error summary and place it in the error container
// Create our container if one doesn't already exist
if ( $summaryContainer.length === 0 ) {
$summaryContainer = $( "<section id='" + errorFormId + "' class='alert alert-danger' tabindex='-1'>" + summary + "</section>" ).prependTo( $form );
} else {
$summaryContainer.empty().append( summary );
}
...

**Comment by pjackson28** [comment]
That declaration is also used on line 266 outside of that JS file (formvalid.js). An easy fix for that part would be to just use <code>$form.find( "#" + errorFormId )</code> directly on line 266 instead of <code>$summaryContainer</code>.

Could you please submit these fixes in a PR?

**Comment by hsrudnicki** [comment]
as a further, please update this issue's status and as well before for corresponding PR, thx

**Comment by hsrudnicki** [comment]
Make "Going Stale" or if otherwise?
Either way, please update this issue's status, thank you

**Comment by RobJohnston** [comment]
It was mentioned above that this started in 4.0.12.  I noticed that it still existed in 4.0.14 but seems to have been fixed in the latest version (4.0.20).

**Comment by hsrudnicki** [comment]
Based on the above, can be this closed as fixed already?  Thx

**Comment by lucas-hay** [comment]
Address in #7940
