### ISSUE TITLE
Carrousel: maximum of tabs?

### ISSUE THREAD

**Issue by marieeved** [wet-boew/wet-boew#7068]
Hi,

Is there a maximum number of items that can be put in a carrousel?
and what is the best number... 3?
Thank you.

**Comment by andre-gh** [comment]
A carousel like on the thumbnails is limited to however many fit in the available width for the carousel (the canada.ca homepage for example can only fit four or so on a smaller width).

A carousel without thumbnails enabled appears to have no issues going to higher numbers.  If you start getting to very large numbers you should likely consider why you are using the carousel pattern as user's will never see all of the content if it gets too large.

**Comment by marieeved** [comment]
thanks for the information. 
my question was more in order to know what to write in comments on my html page (to help my team the days that I will not work at office this fall).
