### ISSUE TITLE
Intranet RSS feeds

### ISSUE THREAD

**Issue by bsoicher** [wet-boew/wet-boew#7076]
Can only access public feeds through google api.   So an intranet has no way of loading internal feeds without making them public.

**Comment by LaurentGoderre** [comment]
A fix for this has been implemented in v4.0.17

#7030

**Comment by hsrudnicki** [comment]
When possible, please update this issue's status, thx

**Comment by hsrudnicki** [comment]
Based on the above, this issue assumed as resolved, and closed, as well labeled "Going Stale" due to no further discussion.
If you strongly think otherwise, please update this issue again, thank you.
