### ISSUE TITLE
Government of Canada Web Usability Theme - gap between breadcrumbs and contents area

### ISSUE THREAD

**Issue by Makkurokurosuke** [wet-boew/wet-boew#7078]
http://wet-boew.github.io/themes-dist/theme-gcwu-fegc/content-secmenu-en.html

Could you fix to remove the big gap between breadcrumbs and contents area?

![goc_them](https://cloud.githubusercontent.com/assets/6284197/9666427/f5bbbddc-5243-11e5-9036-49ff420d6744.png)

**Comment by LaurentGoderre** [comment]
Duplicate of #7077
