### ISSUE TITLE
Fieldsets/Legends

### ISSUE THREAD

**Issue by seguinrs** [wet-boew/wet-boew#7079]
Hi,

Why are fieldsets/legends not displaying the borders?

Thanks
Roger

**Comment by LaurentGoderre** [comment]
@thomasgohard

**Comment by seguinrs** [comment]
Who will fix this issue ?, is someone looking at this issue? Thanks

**Comment by hsrudnicki** [comment]
and as further, please update this issue's status as well, thx

**Comment by seguinrs** [comment]
Issue is still opened, the borders of the fieldset don't appear.

![nofieldsetborder](https://cloud.githubusercontent.com/assets/14113912/10192380/f92d98c6-6749-11e5-96b9-d813fe1cba74.png)

**Comment by seguinrs** [comment]
VS 2013 Markup:

           <div>
                <fieldset>
                    <legend>
                        <asp:Label ID="lbltitre" runat="server" meta:resourcekey="lbltitreResource1"></asp:Label></legend>
                    <div class="row">
                        <div class="col-md-4">
                            <asp:Label ID="UserNameLabel" runat="server" EnableViewState="False" meta:resourcekey="UserNameLabelResource1"
                                AssociatedControlID="ddlLogin"></asp:Label>
                        </div>
                        <div class="col-md-4">
                            <asp:DropDownList ID="ddlLogin" runat="server">
                                <asp:ListItem Value="5258">5258 -</asp:ListItem>
                                <asp:ListItem Value="5802">5802 -</asp:ListItem>
                            </asp:DropDownList>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <asp:RequiredFieldValidator ID="rfv03" runat="server" ControlToValidate="UserName"
                                meta:resourcekey="rfv03Resource1" SetFocusOnError="True" Style="" CssClass="text-danger"
                                Display="Dynamic"></asp:RequiredFieldValidator>
                            <asp:RegularExpressionValidator ID="rev01" runat="server" CssClass="text-danger"
                                ControlToValidate="UserName" ValidationExpression="^[0-9]*$" meta:resourcekey="rev01Resource1"
                                Display="Dynamic"></asp:RegularExpressionValidator>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <asp:Label ID="UserFileLicense" runat="server" EnableViewState="False" meta:resourcekey="UserFileLicenseRessource1"
                                AssociatedControlID="UserName"></asp:Label>
                        </div>
                        <div class="col-md-2">
                            <asp:TextBox ID="UserName" EnableViewState="true" runat="server" MaxLength="8" meta:resourcekey="UserNameResource1" CausesValidation="True"
                                class="full-width"></asp:TextBox>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <asp:Label ID="PasswordLabel" runat="server" EnableViewState="False" meta:resourcekey="PasswordLabelResource1"
                                AssociatedControlID="Password"></asp:Label><br />
                        </div>
                        <div class="col-md-2">
                            <asp:TextBox ID="Password" 
                                runat="server" MaxLength="8" TextMode="Password" meta:resourcekey="PasswordResource1"
                                class="full-width" Text=""></asp:TextBox>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <asp:RequiredFieldValidator ID="rfv02" runat="server" Style="" CssClass="text-danger"
                                ControlToValidate="Password" Display="Dynamic" meta:resourcekey="rfv02Resource1"></asp:RequiredFieldValidator>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <asp:Label ID="lblProvince" runat="server" EnableViewState="False" meta:resourcekey="lblProvinceResource1"
                                AssociatedControlID="dpListProvince"></asp:Label>
                        </div>
                        <div class="col-md-4">
                            <asp:DropDownList ID="dpListProvince" runat="server" meta:resourcekey="dpListProvinceResource1">
                                <asp:ListItem meta:resourcekey="ListItemResource1"></asp:ListItem>
                            </asp:DropDownList>
                        </div>
                    </div>
                </fieldset>
            </div>

**Comment by seguinrs** [comment]
Rendered HTML:

           <div>
                <fieldset>
                    <legend>
                        <span id="ctl00_ContentPlaceHolder1_c1_lbltitre"><Strong>Please identify yourself</Strong></span></legend>
                    <div class="row">
                        <div class="col-md-4">
                            <label for="ctl00_ContentPlaceHolder1_c1_ddlLogin" id="ctl00_ContentPlaceHolder1_c1_UserNameLabel">Code</label>
                        </div>
                        <div class="col-md-4">
                            <select name="ctl00$ContentPlaceHolder1$c1$ddlLogin" id="ctl00_ContentPlaceHolder1_c1_ddlLogin">
		<option value="5258">5258 -</option>
		<option value="5802">5802 -</option>

	</select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <span id="ctl00_ContentPlaceHolder1_c1_rfv03" class="text-danger" style="color:Red;display:none;">Please enter a valid file number (9999)</span>
                            <span id="ctl00_ContentPlaceHolder1_c1_rev01" class="text-danger" style="color:Red;display:none;">Please enter a valid file number (9999)</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <label for="ctl00_ContentPlaceHolder1_c1_UserName" id="ctl00_ContentPlaceHolder1_c1_UserFileLicense">File/license <b>(required)</b>:</label>
                        </div>
                        <div class="col-md-2">
                            <input name="ctl00$ContentPlaceHolder1$c1$UserName" type="text" maxlength="8" id="ctl00_ContentPlaceHolder1_c1_UserName" class="full-width" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <label for="ctl00_ContentPlaceHolder1_c1_Password" id="ctl00_ContentPlaceHolder1_c1_PasswordLabel">Password <b>(required)</b>:</label><br />
                        </div>
                        <div class="col-md-2">
                            <input name="ctl00$ContentPlaceHolder1$c1$Password" type="password" maxlength="8" id="ctl00_ContentPlaceHolder1_c1_Password" class="full-width" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <span id="ctl00_ContentPlaceHolder1_c1_rfv02" class="text-danger" style="color:Red;display:none;">Please enter the password</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <label for="ctl00_ContentPlaceHolder1_c1_dpListProvince" id="ctl00_ContentPlaceHolder1_c1_lblProvince">Province or territory:</label>
                        </div>
                        <div class="col-md-4">
                            <select name="ctl00$ContentPlaceHolder1$c1$dpListProvince" id="ctl00_ContentPlaceHolder1_c1_dpListProvince">
		<option value="1">Newfoundland and Labrador</option>
		<option value="2">Prince Edward Island</option>
		<option value="3">Nova Scotia</option>
		<option value="4">New Brunswick</option>
		<option selected="selected" value="5">Quebec</option>
		<option value="6">Ontario</option>
		<option value="7">Manitoba</option>
		<option value="8">Saskatchewan</option>
		<option value="9">Alberta</option>
		<option value="10">British Columbia</option>
		<option value="11">Yukon</option>
		<option value="12">Northwest Territories</option>
		<option value="13">Nunavut</option>

	</select>
                        </div>
                    </div>
                </fieldset>
            </div>

**Comment by seguinrs** [comment]
Is there someone assigned to this issue?

Thanks
Roger

**Comment by LaurentGoderre** [comment]
Again, this should follow the principle of non-interference that Bootstrap use and be controllable via class

**Comment by seguinrs** [comment]
What does this mean?
How can this be fixed?

**Comment by LaurentGoderre** [comment]
It should be fixed in WET

**Comment by seguinrs** [comment]
Ok, who will fix this?

Thanks
Roger

**Comment by andre-gh** [comment]
Looking at the source it looks like fieldset is supposed to have a border in WET, I will take this and investigate what the default is currently supposed to be currently.

**Comment by andre-gh** [comment]
@LaurentGoderre bootstrap also styles their fieldsets without a class

@seguinrs The fieldset has no border because WET is setup to only have border in between two fieldsets appearing at the top of every fieldset after the first fieldset.  This appears to be intentional and there is a large comment about it in the codebase.

**Comment by andre-gh** [comment]
@sagecram Would it be helpful to have a class designed for forms with only one fieldset?

**Comment by seguinrs** [comment]
No since most forms have more than one fieldset, also many forms have fieldsets within fieldsets.
FYI this was also an issue with previous issues of WET;  this issue was fixed by Mark Browsky(TC Employe) in the past.
Here is an example a previous version of WET that works: https://wwwapps.tc.gc.ca/Prog/4/sis/Login_Ouverture.aspx?lang=en

Thanks

Here is the source:
                <fieldset id="fldsetLogin" runat="server"  title="User Login" class="span-3 print-span-3">
                    <legend id="legendLogin" runat="server" >Login to system</legend>
                    <div id="loginLayoutList" >
                    <div class="margin-top-none" id ="usernameListitem">
                    <cc1:LabelTextBox ID="ccUserName" runat="server" MaxLength="20" HelpResKey="log_lblUsernameHelp" />
                    </div>

                <div class ="clear"></div>

                    <div>
                        <uc:Help ID="txtPasswordHelp" runat="server" HelpResKey="log_PasswordHelp"/>
                        <label runat="server" id="pwdLabel" for="txtPassword" class="margin-bottom-none float-left indent-none print-span-3"></label>
                    </div>
                    <div class="span-3 margin-bottom-medium print-span-3">
                        <uc:ErrorControl runat="server" ID="ECPWD"/>
                        <input id="txtPassword" type="password" runat="server" class="span-2 margin-bottom-none" maxlength="20" />
                    </div>

                  <div class="span-3 margin-bottom-none print-span-3">
                    <asp:Button ID="loginSubmit" Text="Login"  runat="server" class="margin-top-none indent-medium" />
                   </div>
                    <div class="span-3 margin-bottom-none print-span-3" id="forgotListitem" >
                    <asp:HyperLink class="indent-medium" runat="server" id="passwordForgetLink">I forgot my Password</asp:HyperLink>
                    </div></div>
                </fieldset>



Thanks
Roger

**Comment by andre-gh** [comment]
This is the situation:

In bootstrap (which WET extends) they overwrite the default fieldset behavior to look like this (line below the heading):

![fset](https://cloud.githubusercontent.com/assets/13316676/10378478/3cd38c00-6dd7-11e5-91ad-f79de6068558.png)

WET Overwrote that to put a single line between fieldsets like this:

![fset](https://cloud.githubusercontent.com/assets/13316676/10378539/815227d8-6dd7-11e5-8cd5-6d7a06f59024.png)

However, if you only have a single fieldset you end up with no line.  Ideally WET would have three classes:  Default browser behavior, fieldset-border-above (or something), and fieldset-border-below (or something) however a change like that would require waiting until WET `4.1` as it is breaking.

This is the original developers comment:

>  Bootstrap puts the border below the legend which creates a visual
    separation between the legend and the fields to which it relates. Putting
    the border above eliminates that visual separation. Putting it on the
    fieldset element instead ensures that all fieldsets will have a separation
    even when no legend is used.


This is "not a bug" and the intended (non-ideal) behavior of how fieldsets function in WET currently

**Comment by seguinrs** [comment]
With Wet 3.1 you can tell that there is a fieldset withing a fieldset.
![fieldsetwithinfieldsetold](https://cloud.githubusercontent.com/assets/14113912/10393265/5b00d5ae-6e5c-11e5-98b0-cfdc7017ad3b.png)

With Wet 4.0 you can't tell:
![fieldsetwithinfieldset](https://cloud.githubusercontent.com/assets/14113912/10393275/7a9e883e-6e5c-11e5-9cb0-abaf09c9da74.png)

I know that this is an intended feature, but it's not user friendly, the user can't tell visually that the second fieldset is a child of the the parent.

**Comment by LaurentGoderre** [comment]
Technically, nested fieldset are not great for accessibility. IN this case, it might be better to have a heading for the section and individual fieldsets for the checkboxes.

**Comment by hsrudnicki** [comment]
@andre-gh , @seguinrs and others: Based on the above with the last comment from @LaurentGoderre , this issue can be resolved by more than one solution, therefore please update again this issue's status whether this issue, also labeled as "Going Stale", can be closed or if otherwise?  Thank you
