### ISSUE TITLE
Tabbed Interface: Force Vertical Mobile Layout

### ISSUE THREAD

**Issue by Evanjv** [wet-boew/wet-boew#7080]
When using the <a href="https://wet-boew.github.io/v4.0-ci/demos/tabs/tabs-en.html">Tabbed Interface</a>, is there a way to force the mobile layout on screen sizes larger than small? Or alternatively have the layout respond to the width of the object rather than the width of the screen. Mobile layout below.
![image](https://cloud.githubusercontent.com/assets/5808168/9670152/5e6cd290-5248-11e5-81e2-4c743b67b47f.png)

**Comment by LaurentGoderre** [comment]
You can specify grids on small views to limit the width

http://getbootstrap.com/css/#grid-example-mixed-complete

**Comment by pjackson28** [comment]
The tabbed interface switches to the [toggle accordion](http://wet-boew.github.io/wet-boew/demos/toggle/toggle-en.html#accordion) in mobile view so you can just use the toggle accordion directly if you want that interface across all views.

**Comment by Evanjv** [comment]
Even with a grid specified, the layout of the tabbed interface doesn't react to the width of the column. For example, this markup:
```html
<div class="col-xs-9">
    <h1>
        Title
    </h1>
</div>
<div class="col-xs-3">
    <h2>Page Title</h2>
    <p>Page Content</p>

    <div class="wb-tabs">
        <div class="tabpanels">
            <details id="details-panel1">
                <summary>Example 1</summary>
                <p>
                    Filler Text Content
                </p>
            </details>
            <details id="details-panel2">
                <summary>Example 2</summary>
                <p>                                
                    Filler Text Content
                </p>
            </details>
            <details id="details-panel3">
                <summary>Example 3</summary>
                <p>                                
                    Filler Text Content
                </p>
            </details>
        </div>
    </div>
</div>                
```
Will produce this:
![image](https://cloud.githubusercontent.com/assets/5808168/9685222/2426ef02-52da-11e5-9733-806d94610ac0.png)

**Comment by Evanjv** [comment]
I know about the accordion/toggle plugin but since I'm using this as part of a CMS, the ability to create an accordion or tabbed interface using the same HTML markup (+/- a class) would be very useful. Thank you for the suggestions though.
