### ISSUE TITLE
Enable protected branches

### ISSUE THREAD

**Issue by nschonni** [wet-boew/wet-boew#7081]
Since this has happened before, it would be good to turn this on https://github.com/blog/2051-protected-branches-and-required-status-checks

**Comment by hsrudnicki** [comment]
Please update this issue's status as well, thx

**Comment by hsrudnicki** [comment]
@masterbee and others: Make "Going Stale" or otherwise?
Either way, please update this issue's status whether this issue can be closed as resolved/fixed or if otherwise?  Thank you

**Comment by hsrudnicki** [comment]
Can be this closed or otherwise? Please update the status of this again, thx

**Comment by lucas-hay** [comment]
Completed today in PR Review meeting.
