### ISSUE TITLE
Control Sizing Issue

### ISSUE THREAD

**Issue by seguinrs** [wet-boew/wet-boew#7083]
Putting a class on the control like col-lg-* puts the cursor at the wrong location.
![cursor](https://cloud.githubusercontent.com/assets/14113912/9687217/34f368da-52f6-11e5-8fcc-964516df35c4.png)

**Comment by pjackson28** [comment]
I don't think Bootstrap intended for the col-* classes to be put directly on the form control but instead on a parent container. The col-* classes are for grid cells which I don't think a form control would qualify as such.

**Comment by seguinrs** [comment]
Yes it does, please look at the following in section “Control Sizing”
Control sizing
Set heights using classes like .input-lg, and set widths using grid column classes like .col

http://wet-boew.github.io/wet-boew-styleguide/v4/design/forms-en.html#inputs

If we can’t use this what can be used?

Thanks
Roger

**Comment by LaurentGoderre** [comment]
As you may notice at the top of that page that it's a draft I believe the information there is inaccurate.

**Comment by pjackson28** [comment]
The .input-lg class is not a grid cell class, it is intended to be used on a form control. I looked at the page in question and no col-* classes are used directly on a form control, only on the parent container or on the accompanying label.

**Comment by pjackson28** [comment]
@LaurentGoderre What information is inaccurate there? I didn't see any col-* classes applied to any form controls when looking through the markup.

**Comment by seguinrs** [comment]
Ok, how can we set the width of a textbox/input control?

**Comment by pjackson28** [comment]
You could set the width of the parent container using a <code>col-*</code> class and then apply <code>full-width</code> to the form control itself. The form control will then size itself to the sized parent container.

**Comment by pjackson28** [comment]
As a caveat, if you are limiting the number of characters that can be entered, it can be confusing to users for a form field to be wider than the number of characters that can be entered.

**Comment by seguinrs** [comment]
This fixes the width and the curson location within the text but it adds a padding to the left so the above label don't align.  mrgn-lft-0 doesn't fix the issue.

Thanks
Roger

**Comment by pjackson28** [comment]
Is the <code>col-*</code> class nested within a <code>row</code> class? Grid cells are not meant to be used outside of grid rows.

**Comment by seguinrs** [comment]
Yes

**Comment by pjackson28** [comment]
Note the following from the Bootstrap site: "•Columns create gutters (gaps between column content) via padding. That padding is offset in rows for the first and last column via negative margin on .rows."

**Comment by seguinrs** [comment]
Yes before we could use indent-none, is there an equivalent?

**Comment by pjackson28** [comment]
Is the label within a grid cell as well? They won't be in alignment if the label is outside of the grid system but the form field is inside. As for indent-none, no there isn't, the issue likely is with how you are using the grid system (so likely can be fixed through the grid system).
