### ISSUE TITLE
Anchors not working properly in tabs

### ISSUE THREAD

**Issue by EricLavoie88** [wet-boew/wet-boew#7084]
We are having issues when trying to link to an anchor in content that uses the wb-tabs functionality.

When clicking on the link, the page focus is in content way above the anchor itself. This is happening in both Firefox and IE 11. Note that when we hit enter on the URL in the address bar, the page focus is correct.

Thanks.

**Comment by pjackson28** [comment]
Is the link to the tab panel or an anchor within the tab panel? If it is to the tab panel then you should apply <code>class="wb-tabs-ext"</code> to the link so that it sets focus properly. For example:

```html
<a href="#details-panel3" class="wb-tabs-ext">Show the third panel</a>
```

**Comment by EricLavoie88** [comment]
An anchor within the tab panel.

**Comment by EricLavoie88** [comment]
Also, the link to the anchor inside the tab is from a different page.

**Comment by pjackson28** [comment]
That would explain a lot. Most likely the browser is pointing to the pre-enhancement position of the anchor and not the post-enhancement position. This would be a non-issue if you just pointed to the tab panel as the plugin takes care of resolving the focus.

**Comment by EricLavoie88** [comment]
There is no way to point to the anchor itself?

**Comment by pjackson28** [comment]
You are pointing to it, it is just the anchor position has changed after the browser has already scrolled to the position. Now a possible future enhancement could be to have it detect linking from another page to an anchor within a tabpanel and then to correct the focus position post enhancement, but that functionality does not exist at the moment.

**Comment by EricLavoie88** [comment]
Okay thanks for the response Paul.

**Comment by pjackson28** [comment]
PR #7012 introduces a fix for this (and automatically opens the panel when linking from another page to an anchor within a panel).

**Comment by hsrudnicki** [comment]
as a further, when the fix is working, please update this issue's status as well, and corresponding PR when applicable

**Comment by pjackson28** [comment]
The fix hasn't been merged in yet.
@andre-gh Any news on that?

**Comment by andre-gh** [comment]
Will test and merge tomorrow alongside my other tab related fix and make sure there is nothing weird on either of them.  Tabs does a lot so I want to make sure nothing breaks.

**Comment by ktombs** [comment]
I'm trying to link to an anchor on the same page that uses the expand (accordion) class; but it won't work. Is this also a known issue?
