### ISSUE TITLE
Organizational Charts

### ISSUE THREAD

**Issue by nimans2** [wet-boew/wet-boew#7086]
I am looking for existing code for creating an organizational chart in WET4.  Is this available?

**Comment by hsrudnicki** [comment]
@nimans2 : do you still need more info? Please update this issue's status, thx

**Comment by nimans2** [comment]
No it's ok I will send out a message on GCconnex to see if other departments have created something.

Thank you 
Sylvie Niman

>>> hsrudnicki <notifications@github.com> September 29, 2015 3:58 PM >>>

@nimans2 : do you still need more info? Please update this issue's status, thx

**Comment by hsrudnicki** [comment]
Due to no further discussion, status update(s), this issue labeled as "Going Stale" and closed as resolved.
If you think otherwise, please update this issue's status again, thank you
