### ISSUE TITLE
Rss feeds - internal links

### ISSUE THREAD

**Issue by marieeved** [wet-boew/wet-boew#7089]
Hi,

I'm able to display RSS feeds with external links (pages on internet), but not with internal links (ex: link to a blog in a intranet).

I already read the other issues about it... if I understand I have to make a manipulation to the code, right?
I have to use data-ajax or add this code :https://github.com/ryanhyma/wet-boew/commit/d6390d2f2d78a4ed290429875b9107d514eb68f3 ??
but how and where?

Or 
do I have absolutely to download 4.0.17 to have rss feeds functionals with internal links? for now, I use 4.0.12, so it will means to recreate all my pages... :(

Thanks for help.

**Comment by LaurentGoderre** [comment]
You need v4.0.17. Version prior to that have no option to bypass the external Google Feed service

**Comment by LaurentGoderre** [comment]
However, 4.0.17 is a drop in replacement and do not require any change to the HTML

**Comment by marieeved** [comment]
really? because I download it and the page are really differents. the files are in format hbs. I don't know this one.
I replace the "placeholdercontent" by my previous content?

**Comment by marieeved** [comment]
I check quickly on internet...
I need an other software than Dreamweaver to use these files, right? like adobe edge cc?

**Comment by marieeved** [comment]
sorry...didn't download the right thing. it seemed to me that the download had been too fast...
if you say that's the only way. 
Again, thanks a lot Laurent.

**Comment by marieeved** [comment]
I copy/paste a page with the new files, change path for css files, I create a folder on my server and everything...

same problem. external links works fine (the feeds are displayed auto), but not with a internal links.
with this code:
`<section class="wb-feeds">`
`<h3>Fil RSS</h3>`
`<ul class="feeds-cont">`
`<li>`
`<a href="http://www.tc.gc.ca/medias/rss/routier.xml">external link</a>`
`</li>`
`<li>`
`<a href="http://blogs-blogues.prv/qc-sma-adm/?feed=rss2&lang=fr">internal link</a>`
`</li>`
`</ul>`
`</section>`

I noticed that at the end of the code : this have changed and the lines after. 
`<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.js"></script>`

there is  other changes that would affect the page?

**Comment by andre-gh** [comment]
The important file to update in this case is to replace `wet-boew.min.js` and all other files in the `js` folder

**Comment by andre-gh** [comment]
When upgrading WET you should also replace the CSS, etc, but in this case (of a small upgrade) no HTML should need updating.

**Comment by marieeved** [comment]
I use all the new files. I make a whole new folder with the wet 4.17.
I copy/paste code from a page of wet 4.12 and replace it in the content-subsite-fr page, than I change links to new css/js files.

**Comment by marieeved** [comment]
and the code that I used (see above) for feeds is supposed to work with internal links? because now, it doesn't work.

**Comment by LaurentGoderre** [comment]
No, you need to use another way for internal feeds.

**Comment by marieeved** [comment]
what way?

**Comment by LaurentGoderre** [comment]
You would need to implement something to turn you feed to JSONP. Perhaps @ryanhyma has a solution.

**Comment by LaurentGoderre** [comment]
This is this solution for Windows Server and .NET https://github.com/patridge/rss-to-jsonp

**Comment by marieeved** [comment]
you mean to use this: https://github.com/ryanhyma/wet-boew/commit/d6390d2f2d78a4ed290429875b9107d514eb68f3 
so I create a new file " feeds.js" that I place in the folder js, right?

**Comment by marieeved** [comment]
so i forget Ryan and I download all the files in the adress you give me: https://github.com/patridge/rss-to-jsonp 
or than it's best that I talk directly to Ryan?

**Comment by LaurentGoderre** [comment]
They are both options, and I would investigate both and pick the one that is the most suited to your situation

**Comment by marieeved** [comment]
ok thank you very much!!! :)

**Comment by marieeved** [comment]
come back at office only next tuesday.

**Comment by marieeved** [comment]
Hi,
so is it possible?
Do you see an option better than the other?
Again, thanks a lot for your time.

**Comment by LaurentGoderre** [comment]
Well the feeds.js is harder to maintain because you have to maintain two different formats, while the other one converts it on the fly for you

**Comment by marieeved** [comment]
so, which one do you think that is best for me? because you said that you will look at them and choose...

personnaly, I suggest the option that will take the less time to implement because my boss push me a lot on this issue. He wants that the problem will be solved quickly.

so just tell me one, directs me toward documentation to read and I will try to handle it.
thank you.

**Comment by ryanhyma** [comment]
I used a library called GSON to translate the ATOM feed into JSON: https://github.com/google/gson. (It is a server side Java library though)

If there is a need, I can remove the dependency on the Google API, it would require using another library such as: xml2json or maybe http://hovinne.com/articles/jfeed-jquery-rss-atom-feed-parser-plugin unless WET already has a library included that does this.

I'm not sure how practical it would be to do this though, It appears there might be some CORS security problems. The XML would have to be included on the same server that the WET libraries are loaded from.

**Comment by marieeved** [comment]
@ryanhyma 
ok, so I have to download your library and then what?
explain me like if I didn't know programmation (for me, to manage RSS feeds from intranet site is Advanced programmation).

**Comment by LaurentGoderre** [comment]
I am afraid this is not an easy thing to setup

**Comment by marieeved** [comment]
I know that. 
but nobody tell me what kind of work that it will represent... this could make a good explanation to give to my boss (that I can't do that)...

I will have to create html pages? php? JS? change CSS file? how many pages?

**Comment by LaurentGoderre** [comment]
It requires some advanced configuration on the server to put in place a handler to dynamically convert your RSS(s) into the proper format. The work involved depends on the server technology you are running

**Comment by marieeved** [comment]
in that case, if I'm not the administrator of the server. I can't do anything, right?

**Comment by LaurentGoderre** [comment]
You can do the conversion manually but it kind of defeats the purpose of a feed.

**Comment by marieeved** [comment]
ok. last question, just to confirm:

so I will have to do this advanced configuration to display RSS coming from:
-GCconnex blog?
-blog inside an other intranet site (that work with WordPress)?

**Comment by LaurentGoderre** [comment]
WordPress has a plugin for this already that would need to be installed: https://wordpress.org/plugins/feed-json/

**Comment by LaurentGoderre** [comment]
It's also possible that the software that GCConnex is built on has a way to do it but it's not necessarily enabled in GCConnex

**Comment by marieeved** [comment]
Well, I received instructions about an api with gc connex, but the feed doesn't appears on my page...
but thanks, I will check the plugin for WordPress if the page can be opened...

**Comment by ryanhyma** [comment]
Here is what I had to do:
1. Setup the feeds widget on an HTML page with the data-ajax attribute set to a URL on the same server.
2. One of the parameters in the URL is the URL of the RSS/ATOM feed
3. On the server side I used GSON to download the RSS feed, and convert it to JSON
4. The server side then wraps the JSON in a javascript function that is specified in the callback parameter of the data-ajax feed URL.

**Comment by ryanhyma** [comment]
What is the info you received from GCConnex?

**Comment by marieeved** [comment]
GCconnex API – Information sheet
An API (application-programming interface) was created for GCconnex to provide external access by Government of Canada sites to specific functionalities, in this instance Blog posts. As an API is a software-to-software interface, not a user interface, this sheet provides information for developers/programmers/employees who need to integrate the API within their departmental sites.
Are there specific settings for the GCconnex Blog post in order to make it accessible via the API?
Yes, the Blog post access must be set to Public in GCconnex (meaning anyone browsing GCconnex without being logged in may see the blog post). If the blog’s access rights are not set to public it will send back a message stating as much.
What items are available through the API?
For Blog posts, the following items are available:
 Title
 Excerpt
 Body
 Publication date
 Last edit date
 Link to the Blog post in GCconnex
 Author: username, display name, link to user profile, avatar, date user joined GCconnex
 Comments to the post:
o Counter for the number of comments
o Author: username, display name, link to user profile, avatar, date user joined GCconnex
o Comment
How do I choose which Blog post I want to access?
You have to input the number associated with the id to the blog post you want to access. Here’s a sample URL: http://gcconnex.gc.ca/services/api/rest/xml/?method=get.blog&id=6890627
If the id is not a blog it will send back an appropriate message.
What formats is the output available in?
The output is available in xml, json, and php. To change the output format, change the “xml” part of the URL to your format of choice.
Here’s a sample URL: http://gcconnex.gc.ca/services/api/rest/xml/?method=get.blog&id=6890627
API URL
http://gcconnex.gc.ca/services/api/rest/xml/?method=get.blog&id=(insert blog id)

**Comment by ryanhyma** [comment]
Hmm, if you swap the xml in the URL to: http://gcconnex.gc.ca/services/api/rest/jsonp/?method=get.blog&id=6890627&cb=test
You get JSON, which is almost what you need, there is probably a parameter called cp or callback but without the API spec I can only guess. It looks like it might be there. I would ask the GCConnex team if they have a JSONP api, then you should be able to supply the URL into the data-ajax attribute.

**Comment by LaurentGoderre** [comment]
Apparently the ELGG (the software GCConnex runs) does not support JSONP natively. Someone created a plugin but it's not likely they will install it

https://www.marcus-povey.co.uk/2014/05/12/jsonp-support-for-elgg/

**Comment by ryanhyma** [comment]
Huh, kinda cripples the API.

@marieeved your job is a bit easier, all your server side script has to do now is just wrap the returned JSON with the callback parameter from the feed URL.

I'm not 100% sure if the JSON matches up completely with what is required by the widget but it looks close enough to try.

**Comment by marieeved** [comment]
thanks to both of you.
I will try again then if I'm not able to do it, I will give up or my team will ask to someone else...

**Comment by hsrudnicki** [comment]
So, can be this issue closed or otherwise? Please update this issue's status, thx
