### ISSUE TITLE
jQuery validate checkbox required validation doesn't work with name property containing dot

### ISSUE THREAD

**Issue by NPhilouze** [wet-boew/wet-boew#7090]
I'm having an issue where the jQuery Validate plugin is unable to validate checkboxes containing dots in the name property.

When the box is unchecked, the error is identified correctly.
When the box is checked, the input's ```class``` changes to ```valid``` instead of ```error``` and ```aria-invalid``` is set to ```false``` as expected but the error label remains ```display:inline-block``` instead of changing to ```display: none```.

Every time the field fails validation, a new error label will be added causing a duplicate:
![duplicate_errors](https://cloud.githubusercontent.com/assets/11313678/9790280/2cf022fc-57a3-11e5-9b80-f8e00aea100a.JPG)

As far as I know, having complex names only causes problems when calling them when using the rules option in which case you need brackets: [jQuery Validation Plugin Reference documentation] (http://jqueryvalidation.org/reference/#link-fields-with-complex-names-(brackets-dots))
Here however, the validation is set via HTML with required="required" which shouldn't be causing issues.

Here is the source code I wrote to test this which is taken from the [Working examples] (http://wet-boew.github.io/v4.0-ci/demos/formvalid/formvalid-en.html#animal1) page
```html
<div class="wb-frmvld">
	<form action="#" method="get" id="validation-example">
		...
		<p>THIS WORKS</p>
		<fieldset>
			<legend class="required"><span class="field-name">Favourite pets</span> <strong class="required">(required)</strong></legend>
			<div class="checkbox">
				<label for="animal1"><input type="checkbox" name="animal" value="1" id="animal1" required="required" />&#160;&#160;Dog</label>
			</div>
			<div class="checkbox">
				<label for="animal2"><input type="checkbox" name="animal" value="2" id="animal2" />&#160;&#160;Cat</label>
			</div>
			<div class="checkbox">
				<label for="animal3"><input type="checkbox" name="animal" value="3" id="animal3" />&#160;&#160;Fish</label>
			</div>
			<div class="checkbox">
				<label for="animal4"><input type="checkbox" name="animal" value="4" id="animal4" />&#160;&#160;Other</label>
			</div>
		</fieldset>
		
		<p>THIS DOESN'T WORK</p>
		<fieldset>
			<legend class="required"><span class="field-name">Favourite pets</span> <strong class="required">(required)</strong></legend>
			<div class="checkbox">
				<label for="animal1"><input type="checkbox" name="object.animal" value="1" id="animal1" required="required" />&#160;&#160;Dog</label>
			</div>
			<div class="checkbox">
				<label for="animal2"><input type="checkbox" name="object.animal" value="2" id="animal2" />&#160;&#160;Cat</label>
			</div>
			<div class="checkbox">
				<label for="animal3"><input type="checkbox" name="object.animal" value="3" id="animal3" />&#160;&#160;Fish</label>
			</div>
			<div class="checkbox">
				<label for="animal4"><input type="checkbox" name="object.animal" value="4" id="animal4" />&#160;&#160;Other</label>
			</div>
		</fieldset>
		<input type="submit" value="Submit" class="btn btn-primary">
	</form>
</div>
```

**Comment by andre-gh** [comment]
Sounds like something a call to `jqEscape`, I will take a look

**Comment by andre-gh** [comment]
I am having a hard time reproducing using your example "this does not work" fields.  I am only getting an "Error 1" are there specific steps I have to follow?  I try submitting the form multiple times and only see one error which differs from your screenshot.

I should verify that you did not use your example code exactly as you have it there as it has duplicate IDs, I assume you meant for me to test either one separately (which I did) but am unable to duplicate the issue. 

I can picture code which would cause this issue, I just need to reproduce it first so I can verify the fix.

Please let me know of exact steps to reproduce and if it occurs I only one browser.

**Comment by pjackson28** [comment]
@NPhilouze Please also identify the version of WET that you are using as the issue may already be fixed in newer versions of WET.

**Comment by NPhilouze** [comment]
I'm using 4.0.17.

Here are the steps I'm using to reproduce the issue:
1. Press the submit button (error label and summary appear since the validation doesn't pass)
2. Check the "Dog" checkbox (error label and summary stays even though validation passes)
3.Uncheck the "Dog" checkbox (a duplicate of the error label and summary li are added)

Every time steps 2 and 3 are repeated there is an additional label as if the error is being triggered for the first time.

Clicking the submit button does remove the duplicates but the issue is still there until the user submits again.

**Comment by andre-gh** [comment]
I am still having trouble duplicating this issue, which browser version are you in?  Trying to narrow down the differences.

**Comment by NPhilouze** [comment]
I'm able to produce the issue in IE11 and FF35 with not visible difference between the two.

**Comment by andre-gh** [comment]
In `4.0.17` in IE11 I am using this code:

	<div class="wb-frmvld">
	    <form action="#" method="get" id="validation-example">
	        <fieldset>
	            <legend class="required"><span class="field-name">Favourite pets</span> <strong class="required">(required)</strong></legend>
	            <div class="checkbox">
	                <label for="animal1"><input type="checkbox" name="object.animal" value="1" id="animal1" required="required" />&#160;&#160;Dog</label>
	            </div>
	            <div class="checkbox">
	                <label for="animal2"><input type="checkbox" name="object.animal" value="2" id="animal2" />&#160;&#160;Cat</label>
	            </div>
	            <div class="checkbox">
	                <label for="animal3"><input type="checkbox" name="object.animal" value="3" id="animal3" />&#160;&#160;Fish</label>
	            </div>
	            <div class="checkbox">
	                <label for="animal4"><input type="checkbox" name="object.animal" value="4" id="animal4" />&#160;&#160;Other</label>
	            </div>
	        </fieldset>
	        <input type="submit" value="Submit" class="btn btn-primary">
	    </form>
	</div>

Open the page:

![untitled](https://cloud.githubusercontent.com/assets/13316676/9797397/e6632d40-57c8-11e5-928b-7a910bc6eeda.png)

Click submit:

![untitled](https://cloud.githubusercontent.com/assets/13316676/9797428/11cdb8ba-57c9-11e5-886c-5c47d2b37172.png)

Check Dog (Clicking the label, tried by clicking the box directly as well):

![untitled](https://cloud.githubusercontent.com/assets/13316676/9797443/268ac162-57c9-11e5-911b-0b9c676cf6d5.png)

Recheck Dog (Clicking the label, tried by clicking the box directly as well):

![untitled](https://cloud.githubusercontent.com/assets/13316676/9797458/3e648bba-57c9-11e5-92c5-a4842f8767be.png)

Am I doing something incorrectly or different?

**Comment by NPhilouze** [comment]
The steps you're doing are the same as mine but you're getting different results.
I was told we're using 4.0.17 but maybe it's not the case.
I'll check on my side to confirm which version is in use since that could be the only difference I can think of right now.

**Comment by andre-gh** [comment]
I suggest checking the comment at the top of the WET JS file your browser is downloading to verify the version.

**Comment by NPhilouze** [comment]
I checked the JS file and it says 4.0.13 which is a much older version than I was lead to believe.
I'm closing this issue since I downloaded 4.0.17 and can't reproduce the error there (getting the same result as you are).
