### ISSUE TITLE
Twitter embedded timeline: 

### ISSUE THREAD

**Issue by Savardp** [wet-boew/wet-boew#7093]
hi Guys,

I'm working now on an embeded Twitter timeline. English version is ok but on french version, I have a hard time to modify the header in french that should be "Gazouillis".

Challenge: “Tweets” word on top of widget appear to be same for both languages. « Gazouillis” in French does not exist from WET 4: http://wet-boew.github.io/v4.0-ci/demos/twitter/twitter-en.html ?

FYI, I used this code : 

<div class="wb-twitter align-right panel-info span-2">
<a class="twitter-timeline" data-widget-id="451389171337146368" href="https://twitter.com/search?q=%23enviroweek2014+AND+%23+from%3Aenvironmentca">Tweets about &quot;#enviroweek2014 AND # from:environmentca&quot;</a>
</div>

Thanks,
Pierre 
Environment Canada

**Comment by Savardp** [comment]
I mean this code: 

<div class="wb-twitter align-right panel-info span-2">
<a class="twitter-timeline" data-widget-id="451389171337146368" href="https://twitter.com/search?q=%23enviroweek2014+AND+%23+from%3Aenvironmentca">Tweets about &quot;#enviroweek2014 AND # from:environmentca&quot;</a>
</div>

**Comment by andre-gh** [comment]
The "tweets about" portion which shows while the widget is loading needs to be modified separately by the implementer and is not part of the plugin itself (the words inside the middle of the code you used).  The text is basically a fallback text which may be any text of your choosing.

If you are not referring to that text, could you screenshot the incorrect text for me?

To paste code into github the code must have spaces in front of each line.

**Comment by Savardp** [comment]
Bonjour André,

Voici en pièce jointe ce à quoi je fais référence. Voir le cercle rouge. C’est ce texte que je désire changer pour la version française.

Merci,

Pierre

**Comment by andre-gh** [comment]
Unfortunately attachments do not work correctly with github replies.  If you login to the github user interface you can manually drag and drop an image into the reply box or click the button to select an attachment in your reply.

Thank you,

**Comment by Savardp** [comment]
hope firefox will work IE does not work...

![capture](https://cloud.githubusercontent.com/assets/14223305/9819243/dcc34bd2-587a-11e5-99c5-bfe20b6aded0.JPG)

**Comment by andre-gh** [comment]
Thank you, let me just verify how twitter behaves and I will get right back to you shortly.

**Comment by Savardp** [comment]
thanks!

**Comment by andre-gh** [comment]
It is not possible to change the word that twitter displays in the title.

It is possible to use `data-chrome="noheader"` on the `a` element to hide the twitter widget header all together if you prefer.

It appears Twitter believes that the word "Tweet" to be their own special noun and they do not translate it in other languages.

Some other kinds of timelines (for example, lists, or hashtag searches) have different headers, you can read about them here: https://dev.twitter.com/web/embedded-timelines

**Comment by Savardp** [comment]
ok, I already read about this but wasn't sure with the data-chrome="noheader" , but now that you confirm, I'll do some test. Thanks for your quick response!
:)
Pierre

**Comment by hsrudnicki** [comment]
as a further, can be this issue closed or otherwise?

**Comment by Savardp** [comment]
You can close.
 Thanks ! :)

**Comment by hsrudnicki** [comment]
@andre-gh and others: Please close this issue as agreed @Savardp , thank you
