### ISSUE TITLE
module-attention

### ISSUE THREAD

**Issue by regagnon** [wet-boew/wet-boew#7094]
I was ask if it was possible to remove the horn in this alert type box.

**Comment by pjackson28** [comment]
The module-attention feature is only available in WET3 which is no longer supported (support for WET3 was dropped a year ago). You may be able to remove the horn with CSS but we encourage you to migrate to WET4 instead.

Closing the issue since WET3 is no longer supported and the question was answered.

**Comment by regagnon** [comment]
thanks, much appreciated
 
Cheers
 
René

>>> Paul Jackson <notifications@github.com> 2015/09/11 11:44 AM >>>

The module-attention feature is only available in WET3 which is no
longer supported (support for WET3 was dropped a year ago). You may be
able to remove the horn with CSS but we encourage you to migrate to WET4
instead.
Closing the issue since WET3 is no longer supported and the question
was answered.
—
Reply to this email directly or view it on GitHub (
https://github.com/wet-boew/wet-boew/issues/7094#issuecomment-139580847
).



Ce courriel est destiné exclusivement au destinataire mentionné en titre
et peut contenir de l'information privilégiée, confidentielle ou
soustraite à la communication aux termes des lois applicables. Toute
divulgation non autorisée, toute reproduction ou réacheminement est
interdit. Si vous n'êtes pas le destinataire de ce courriel, ou n'êtes
pas autorisé par le destinataire visé, ou encore, si vous l'avez reçu
par erreur, veuillez le mentionner immédiatement à l'expéditeur et
supprimer le courriel et les copies.  

This e-mail message is intended for the named recipient(s) and may
contain information that is privileged, confidential and/or exempt from
disclosure under applicable law. Unauthorized disclosure, copying or
re-transmission is prohibited. If you are not a named recipient or not
authorized by the named recipient(s), or if you have received this
e-mail in error, then please notify the sender immediately and delete
the message and any copies.
