### ISSUE TITLE
Share widget setting parameter in wet 4.0.x

### ISSUE THREAD

**Issue by loyd33** [wet-boew/wet-boew#7097]
Hi , 

In version of WET 3.1 we have the parameter 'sourceTag' according to the reference API (http://keith-wood.name/bookmarkRef.html#sourceTag) that we implement in our project.
ref: http://wet-boew.github.io/wet-boew-legacy/v3.1/docs/ref/share/share-en.html

Look like in WET 4.0 is no longer supported or something change.
Is there a way to set this parameter in WET 4.0 ?

**Comment by hsrudnicki** [comment]
Please update this issue's status, thx

**Comment by pjackson28** [comment]
WET 4.0 no longer uses jQuery Bookmark as a dependency which is why that option is no longer available. Since the share widget is a WET plugin with no 3rd party dependencies, if there is a need for the missing functionality then there is the potential for someone to add it through a pull request.

**Comment by hsrudnicki** [comment]
Does someone or one of you started adding it through a pull request, please continue updating this issue's status in order to close this issue, thank you

**Comment by hsrudnicki** [comment]
Make "Going Stale" or otherwise?
Please update this issue's status whether this issue can be closed as resolved/fixed or otherwise? Thank you
