### ISSUE TITLE
v4.0.18 production zip files not available

### ISSUE THREAD

**Issue by naptash** [wet-boew/wet-boew#7109]
http://wet-boew.github.io/wet-boew/docs/versions/dwnld-en.html#v40stable

Can't download the WET Production zip file. Returns 404.

**Comment by LaurentGoderre** [comment]
That's because it wasn't released yet. /cc @MaximMartel

**Comment by tinazl** [comment]
When will the v4.0.18 be released?

**Comment by LaurentGoderre** [comment]
Soon

**Comment by tinazl** [comment]
http://wet-boew.github.io/wet-boew/docs/versions/v4.0/v4.0.18-en.html

Release date: 2015-09-22
so is it supposed to be released yesterday?

**Comment by MaximMartel** [comment]
Its available now, closing issue
