### ISSUE TITLE
Navigation menu (header and footer) not working on IE9

### ISSUE THREAD

**Issue by hebroin** [wet-boew/wet-boew#7112]
Hi,

I'm working on the new ForcesImages web site (www.forcesimages.ca) and the WET implementation was made by a person that has now quit and I can't find why the menu is not showing in IE9.

In the `<header>` section:
```html
<nav role="navigation" id="wb-sm" data-trgt="mb-pnl" class="wb-menu visible-md visible-lg" typeof="SiteNavigationElement"></nav>
<nav role="navigation" id="wb-bc" property="breadcrumb"></nav>
```

And the `<footer>` section:
```html
<nav role="navigation">
   <h2><%=Resources.GalleryServerPro.about_site %></h2>
   <ul id="gc-tctr" class="list-inline">
      <li><a rel="license" href="<%=Resources.GalleryServerPro.terms_conditions_link %>"><%=Resources.GalleryServerPro.terms_conditions %></a></li>
      <li><a href="<%=Resources.GalleryServerPro.transparency_link %>"><%=Resources.GalleryServerPro.transparency %></a></li>
   </ul>
   <div class="row" id="footer_menu_sections"><!-- Footer menu fed here through forces.js --></div>
</nav>
```

The menus work fine in Chrome or Firefox and since I didn't implement the WET on that website, I kind of clueless here.

You can see a live demo at forcesimages.multimediaservices.ca.
Thank your for your help

**Comment by LaurentGoderre** [comment]
Is jQuery loading fine? Look at the console in IE and make sure there are no errors.

**Comment by hebroin** [comment]
Yes, it's loading fine. The whole site uses javascript so if it didn't load, everything would break.

**Comment by shawnthompson** [comment]
Did you replace @crichard in Montreal?

**Comment by hebroin** [comment]
No, I worked with her as a consultant before she leaves and I need to fix that issue :-)

**Comment by shawnthompson** [comment]
Can you email me at Shawn.Thompson@servicecanada.gc.ca?

**Comment by shawnthompson** [comment]
Could it be one of your other JS files conflicting with the WET core JS files?
Your page is requesting 19 JS files but WET core is only 3.

**Comment by hebroin** [comment]
I'll try to strip the site back to the empty WET template to see if it's a JS conflict and I'll get back to you

**Comment by hebroin** [comment]
I think the problem is in the loadXMLDoc function.
I never used XSLT like that so if anybody could point me towards a fix, that would be greatly appreciated.

Is it the "normal WET way" to implement the menu?

```javascript
/* MEGA MENU LOADING FUNCTIONS */
    function loadXMLDoc(filename) {
        if (window.ActiveXObject) {
            xhttp = new ActiveXObject("Msxml2.XMLHTTP");
        }
        else {
            xhttp = new XMLHttpRequest();
        }

        xhttp.open("GET", filename, false);
        try { xhttp.responseType = "msxml-document" } catch (err) { console.log(err); } // Helping IE11
        xhttp.send("");
        return xhttp.responseXML;
    }

    function displayMenu(xmlfile, xslfile, target) {
        xml = loadXMLDoc(xmlfile);
        xsl = loadXMLDoc(xslfile);
        // code for IE
        if (window.ActiveXObject || xhttp.responseType == "msxml-document") {
            ex = xml.transformNode(xsl);
            document.getElementById(target).innerHTML = ex;
        }
            // code for Chrome, Firefox, Opera, etc.
        else if (document.implementation && document.implementation.createDocument) {
            xsltProcessor = new XSLTProcessor();
            xsltProcessor.importStylesheet(xsl);
            resultDocument = xsltProcessor.transformToFragment(xml, document);
            document.getElementById(target).appendChild(resultDocument);
        }
    }
```

**Comment by hsrudnicki** [comment]
So as last commented, can be this issue closed? Please update this issue's status, thank you
