### ISSUE TITLE
New quarterly release cycle / Nouveau cycle de publication trimestrielle

### ISSUE THREAD

**Issue by MaximMartel** [wet-boew/wet-boew#7116]
WET will now be released 4 times a year as opposed to monthly to facilitate application and website maintenance.

La BOEW va maintenant être publiée 4 fois par ans au lieu de mensuellement pour faciliter la maintenance des applications et des sites Web.

**Comment by hsrudnicki** [comment]
Can be this issue closed or otherwise? Please update this issue's status, thank you

**Comment by andre-gh** [comment]
This is a Meta News issue and should remain open until some time in the early new year.

**Comment by hsrudnicki** [comment]
@MaximMartel @andre-gh : Based on the above, please update this issue's status, whether this issue can be closed as fixed "in the early new year" or if otherwise?
Ether way, please keep this issue's status updated, thank you

**Comment by andre-gh** [comment]
This should remain open until at-least the next release.

**Comment by hsrudnicki** [comment]
Based on the above, and next releases up to now, can be this closed or otherwise? Thank you
