### ISSUE TITLE
Lightbox with ajax

### ISSUE THREAD

**Issue by marieeved** [wet-boew/wet-boew#7130]
Hi,

I'm able to create a simple image galery. it means that I have a web page only for the galery who displays all the pictures and when you click on one, it displays the pop-up.
but I would want to click on a sentence that make the pop-up for the galery  displayed over the same page (I will not have to create a page for each galery that I want - pages economy).

I try to make an image galery in using the lightbox ajax that seams to do that but the images are not shown. Error: this content failed to load.

When I use the dev Tools, under network, the query js magnific pop-up have the result "abandoned".

my question is what I have to write in the ajax file?
I try in copy/paste the same code for a simple image galery or just with the code for an image (<img>). 

Thank you.

**Comment by pjackson28** [comment]
I suggest you look at [opening popups through JavaScript](http://wet-boew.github.io/wet-boew/demos/lightbox/lightbox-en.html#examples5) for some ideas. It has an example of opening an image gallery through an alternate method (in this case a dropdown menu with a button). Also note that if AJAX is involved then you need to use a web server. If you try to do it through the file protocol (so opening the page locally in a folder) then the AJAX call will be fail because of security restrictions.

**Comment by marieeved** [comment]
thank you. will look at it when I come back at office tuesday.

**Comment by hsrudnicki** [comment]
@marieeved and others: So, have been this issue fixed and can be this issue closed or otherwise? Please update this issue's status, thank you

**Comment by marieeved** [comment]
never had the occasion to try it...

I tried it today and the photo doesn't appears.

I copy/paste you JS code in a new document place in the folder js.
I copy/paste the html code in the html page that I want to test.
The button appears and everyting. The pop-up works, but not the photo.
(I publish the 2 pages, the photos and  I look the page on the server)
Why?

**Comment by marieeved** [comment]
and I make a reference to the JS file at the end of my html page.
'<script src="../../../js/galerie-photos.js"></script>'

**Comment by marieeved** [comment]
<script src="../../../js/galerie-photos.js"></script>

**Comment by pjackson28** [comment]
What JS are you using to create the gallery? Could you please post it? Also have you checked to see if you are getting any 404s for the images that you are trying to display? If you are getting any 404s then that would indicate that the path is incorrect.

**Comment by marieeved** [comment]
yes, I have 404 errors... I will check again the path.
otherwise, here's the code:
```
// JavaScript Document
(function( $, wb ) {
"use strict";

var $document = wb.doc;

$document.on( "click vclick", "#lbx-open-btn", function( event ) {
	var value = $( "#lbx-select" ).val();

	if ( value === "1" ) {
		$document.trigger( "open.wb-lbx", [
			[
				{
					src: "../images/ccmtgc/photos-course/photo1.jpg",
					type: "image"
				}, {
					src: "../images/ccmtgc/photos-course/photo2.jpg",
					type: "image"
				}, {
					src: "../images/ccmtgc/photos-course/photo3.jpg",
					type: "image"
				}
			],
			false,
			[
				"Image 1",
				"Image 2",
				"Image 3"
			]
		]);
	}
 
	 else if ( value === "2" ) {
		$document.trigger( "open.wb-lbx", [
			[
				{
					src: "demo/1_b.jpg",
					type: "image"
				}, {
					src: "demo/2_b.jpg",
					type: "image"
				}, {
					src: "demo/3_b.jpg",
					type: "image"
				}
			],
			false,
			[
				"Image 1",
				"Image 2",
				"Image 3"
			]
		]);
	}
	
});

})( jQuery, wb );
```

**Comment by marieeved** [comment]
I know that the photo in value 2 are not ok. but even the photos in value 1 doesn't appears.
but there is probably an error of path somewhere...

**Comment by pjackson28** [comment]
Is the issue that the image doesn't show up in the Lightbox or is it that the Lightbox is not showing up? If it is just the image, then you check to see what path the Lightbox is requesting for the image (so the resolved URL) and correct accordingly. If the issue is that the Lightbox isn't showing up, then are there any errors in the console?

**Comment by marieeved** [comment]
sorry, I'm doing something else at the same time for my boss.

the pop-up works (the lightbox). only 4040 errors for image. so it's probably the path like you said.
and I have this one:
/intranet/js/deps/jquery.magnific-popup.min.js		avec cette erreur: GET(Abandonné)

**Comment by pjackson28** [comment]
That error message is because Magnific Popup is attempting to get the image but since the path is incorrect it has to abandon the request.

**Comment by marieeved** [comment]
I found the error...
the path for image should be calculated from the html to the images and not from js to images.
everything works. :)
my bad! 
thank you.
