### ISSUE TITLE
Tabbed Interface: How do I detect WET Tab event?

### ISSUE THREAD

**Issue by johnpalaganas** [wet-boew/wet-boew#7133]
Hello,

So how do I detect WET Tab event or any other WET plugin for that matter?

I need to run a function only if a WET Tab has been detected otherwise run it on document ready.

Thanks,
John

**Comment by pjackson28** [comment]
The available Tabbed interface events can be found in the [Tabs documentation](http://wet-boew.github.io/wet-boew/docs/ref/tabs/tabs-en.html). Perhaps the <code>wb-ready.wb-tabs</code> event is the one you are looking for.

**Comment by johnpalaganas** [comment]
Thank Paul!

**Comment by MaximMartel** [comment]
Can this issue be closed @johnpalaganas @pjackson28
