### ISSUE TITLE
unmin files (css, js, assets, fonts) missing from unmin folder (v4.0.18 and v4.0.17) 

### ISSUE THREAD

**Issue by biljanap** [wet-boew/wet-boew#7135]
I am not sure if this is now intentional, but all css, js, assets, fonts files are missing from unmin folder. I am finding all these files now in the same folders as minimized files. For example, both theme.css and theme.min.css are now in the same folder.

Is this how it is supposed to be?

**Comment by pjackson28** [comment]
Yes it is intentional, only the unminified HTML was left in the unmin folder.

**Comment by biljanap** [comment]
Thanks. I suppose I don't need both min and unmin versions of the same file? Right?

**Comment by pjackson28** [comment]
The min files are meant to be used in production while the unmin versions are only meant for debugging purposes.

**Comment by biljanap** [comment]
I know. I just wanted to make sure that I don't miss something. Thanks. I'll close the issue.

**Comment by LaurentGoderre** [comment]
@biljanap having them in the same folder has allowed us to use sourceMap that allows browser to show the unminified source on debugging even if minified files are used.

**Comment by biljanap** [comment]
@LaurentGoderre Thanks for clarification.
