### ISSUE TITLE
Question: wet-boew java variant

### ISSUE THREAD

**Issue by ryanhyma** [wet-boew/wet-boew#7136]
Hey,

Where is the wet-boew java variant that is referenced in the: WRI_Onboarding_Manual_EN_v2-1_Sept_21_2015.pdf? Specifically the externally facing non-authenticated web applications section...

Is it this repository? wet-boew-java-maven

**Comment by andre-gh** [comment]
@e-wu

**Comment by e-wu** [comment]
This was created before the WRI_Onboarding_Manual_EN_v2-1_Sept_21_2015.pdf was done. For information on the approach referenced in the PDF, see http://www.gcpedia.gc.ca/wiki/Content_Delivery_Network  (GCNet Link)

**Comment by pjackson28** [comment]
Note that the GCpedia link is to the solution for the "Reskin with centrally deployed templates" onboarding option. The Java variant referenced by the onboarding manual is under development. As for the wet-boew-java-maven variant, that predates Web Renewal and is essentially a packaging of the existing WET resources for Maven.

**Comment by ryanhyma** [comment]
When will the Java/.Net variants be released?

**Comment by ryanhyma** [comment]
Who is developing it? Is the current source available on GitHub?

**Comment by RobJohnston** [comment]
The .Net variant (https://github.com/wet-boew/wet-boew-dotnet) just got an update to WET 4.  It was taken from my work here:  https://github.com/RobJohnston/MasterPages.  Just happened 10 days ago to get things started, so surely nobody is using it yet.

I don't know anything about the Java variant.

**Comment by ryanhyma** [comment]
@RobJohnston Thanks!

**Comment by ryanhyma** [comment]
Just to be clear, the .NET variant you linked to is the code that is to be used for the "Reskin with centrally deployed templates" option?

**Comment by pjackson28** [comment]
@ryanhyma It is unrelated to "reskin with centrally deployed templates". That onboarding option is independent of any variants (although could be leveraged by a variant once the centrally deployed templates are in production).

**Comment by pjackson28** [comment]
@ryanhyma As a word of caution about using WET variants at this point for Canada.ca onboarding, those WET variants may need changes to be able to support the "Migrate frontend to frontend framework variant" onboarding option. Many of those variants predate Web Renewal and may be missing certain features, such as leveraging centrally deployed templates (which aren't in production yet).

**Comment by danpoleary** [comment]
At the Canadian Ice Service, we created our own Java Variant, based on J2EE and JSF 2.2.x. It is completely wrapped useing JSF components and templates. It is fully supporting Intranet, Internet, and Canada.ca. The framework developed here allows developers to concentrate on content, with everything else as either web/faces-config configuration properties, or via page properties.

If interested, or wish to discuss further,  please let me know.

Dan

**Comment by hsrudnicki** [comment]
Can be this issue closed or otherwise? Please update this issue's status? Thx

**Comment by hsrudnicki** [comment]
@ryanhyma and others: Is this still an issue, in regards to the java variant to wet-boew, or if otherwise?
Either way, please update this issue's status whether this issue can be closed as resolved/fixed or otherwise?

**Comment by hsrudnicki** [comment]
Can be this closed as resolved?

**Comment by e-wu** [comment]
yes

Eric

**Comment by hsrudnicki** [comment]
Thank you, based on the above, this is closed.
