### ISSUE TITLE
Version updating question

### ISSUE THREAD

**Issue by tsb2012** [wet-boew/wet-boew#7140]
When updating production files, should ALL versions be installed in order of versions or only the latest version?

**Comment by LaurentGoderre** [comment]
You don't need to hold on to older versions no but you should probably adopt a URL scheme that would maximize your caching

**Comment by tsb2012** [comment]
Therefore, each version (4.0.1, 4.0.2, 4.0.3,…) is self-contained? i.e. does not require any other version to work properly?

James Dawkins

Webmestre / Production de rapports
Bureau de la sécurité des transports du Canada / Gouvernement du Canada
James.Dawkins@bst-tsb.gc.ca<mailto:James.Dawkins@bst-tsb.gc.ca>  / Tél.: 819-953-1577   / ATS: 819-953-7287

Webmaster / Report Production
Transportation Safety Board of Canada / Government of Canada
James.Dawkins@tsb-bst.gc.ca<mailto:James.Dawkins@tsb-bst.gc.ca>  / Tel: 819-953-1577   / TTY: 819-953-7287

**Comment by LaurentGoderre** [comment]
Exactly!

**Comment by hsrudnicki** [comment]
@tsb2012 and others: Can be this issue closed or otherwise? Thank you

**Comment by tsb2012** [comment]
Issue #7140 can be closed.
