### ISSUE TITLE
Help with overlay trigger

### ISSUE THREAD

**Issue by rlambert27** [wet-boew/wet-boew#7141]
Hello,

I'm following the setup instructions but having difficulty triggering the overlay. As per the instructions on (http://wet-boew.github.io/v4.0-ci/demos/overlay/overlay-en.html#centred-popup-modal) this is my section:

```
	<section id="sExitModal" class="wb-overlay modal-content overlay-def wb-popup-full">
		<header class="modal-header">
			<h2 class="modal-title">Secure exit notice</h2>
		</header>
		<div class="modal-body">
			<p>{$exitMsg}</p>
		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-primary popup-modal" id="eOK">OK</button>
			<button type="button" class="btn" data-dismiss="modal">Close</button>
		</div>
	</section>
```

Then i'm using in my javascript

```
$( "#sExitModal" ).trigger( "open.wb-overlay" );
```

The problem is that i'd like the popup to use the modal dialog example here (http://wet-boew.github.io/v4.0-ci/demos/overlay/overlay-en.html under "Centred popup - Modal (Lightbox + Modal)"). When I try using the class for that example:

```
mfp-hide modal-dialog modal-content overlay-def
```

Nothing happens when I try to trigger the popup. Here is a sample page:

https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_18/samples/exitscript-dev-en.shtml

Help, thanks!

Roch

**Comment by rlambert27** [comment]
FYI in my sample I'm using the class that does work :-)

**Comment by pjackson28** [comment]
The modal is implemented using the Lightbox so you'll need to follow the Lightbox documentation.
