### ISSUE TITLE
MathML polyfill question

### ISSUE THREAD

**Issue by gdanova** [wet-boew/wet-boew#7142]
I'm using this feature successfully, but recently I selected the following setting in IE11: Right clicked on a formula and selected **Math Settings** > **Math Renderer** > **MathML**. DON"T DO IT!

The formulas now render differently (incorrectly), and now the context menu is gone so that I can’s set it back to **HTML-CSS anymore**. Any ideas on how I can get the context menu back to change the renderer back to what it was?

Thanks.

**Comment by pjackson28** [comment]
You can fix it by deleting your cookies (or the specific cookie that MathJax set to hold the preference).

**Comment by gdanova** [comment]
Deleted all cookies modified in the last 3 months. That worked. :-)
Thanks!
