### ISSUE TITLE
Help with form submit intercept

### ISSUE THREAD

**Issue by rlambert27** [wet-boew/wet-boew#7147]
Hello,

Need a bit of help with this page: https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_18/samples/exitscript-dev-en.shtml

I'm using 

```
$('#wb-srch-sub, #wb-srch-sub-imprt').click(function(event){
```

To intercept the form submit button and run some code. This works great when the site is in desktop mode but when it switches to mobile it no longer works. I tried:

```
$('#wb-srch-sub, #wb-srch-sub-imprt').on('vclick', function(event) {
```

That doesn't intercept the form submit button either.

Ideas?

Roch

**Comment by LaurentGoderre** [comment]
You are much better off listening for the submit event and return false if you want to abort it.

**Comment by rlambert27** [comment]
Tried that:

```
$( ".cse-search-box" ).submit(function( event ) {
```

Not working for some reason. In all cases Firebug does not give any JS errors.

**Comment by pjackson28** [comment]
@rlambert27 It is because your selector is invalid. There is no element in your page with the "cse-search-box" class (you only have it in a name attribute). You need to provide a valid selector for your form element to catch the submit event.

**Comment by rlambert27** [comment]
@pjackson27 - Yes I noticed it after and Laurent pointed that out as well.

@LaurentGoderre Merci beaucoup pour toute ton aide, works great now!

FYI, if anybody else happens to see this:

```
$(document).on("submit", "#wb-srch, #mb-pnl", function() {
```

Solved my issue, thanks!
