### ISSUE TITLE
Duplication of validation Div in Firefox

### ISSUE THREAD

**Issue by fahmyr** [wet-boew/wet-boew#7155]
Using the Firefox browser and the WET validation, if the user hits the Enter key on the keyboard the validation will fire, if the user subsequently clicks the "Submit" button on the form the validation will fire again in a second Div and render twice on the page. Only the top div is then updated once fixes are registered the second one remains static. See attachment. Reproduced on Form Validation Working Examples page.

![image](https://cloud.githubusercontent.com/assets/5008215/10639557/f7cafdde-77de-11e5-9481-5f7b27ab1e62.png)

**Comment by fahmyr** [comment]
Sorry, appears to be only if you hit Enter after providing a date input.
Start with blank form, go to the Date entry box and place an invalid date, click ENTER. Validation errors trigger, then click Submit. Upon fixing any error only the first (top) div is updated.

**Comment by fahmyr** [comment]
Postal Code, Email Address same behavior. Any field that performs some type of validation on the input.

**Comment by andre-gh** [comment]
Which version of WET are you running?  I believe this was a resolved issue in a later version.

**Comment by fahmyr** [comment]
The last version released reflecting the sample pages. Wouldn't we expect the sample pages to reflect the latest release? We only upgrade out version if we run into a bug that is fixed.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: André DSent: Thursday, October 22, 2015 11:37 AMTo: wet-boew/wet-boewReply To: wet-boew/wet-boewCc: fahmyrSubject: Re: [wet-boew] Duplication of validation Div in Firefox (#7155)Which version of WET are you running?  I believe this was a resolved issue in a later version.

—Reply to this email directly or view it on GitHub.

**Comment by pjackson28** [comment]
I can reproduce the issue on Firefox and Chrome. Will be fixed by PR #7161.
