### ISSUE TITLE
Multimedia demo and feature not working

### ISSUE THREAD

**Issue by TinoTran-Work** [wet-boew/wet-boew#7160]
Good morning,

My colleague downloaded the video player plugin.  He is unable to get the demo and the plugin to work.  Please advise.

In version 0.018, neither the demo or plugin load.

Thanks!

**Comment by TinoTran-Work** [comment]
Hello,  

I was wondering if there is an update or more information needed for this issue.  To clarify, it is the Youtube plugin we are trying to utilize.  Also, the "View Code" part of that page is not working either.  

Thanks!

**Comment by masterbee** [comment]
@TinoTran-Work , when you say does not work how did you view the files? Did you access them directly through a browser and the file system or are you using a local server to serve up the pages to your browser? Maybe if possible do you have a demo link for us to help debug?

**Comment by hsrudnicki** [comment]
@TinoTran-Work : Please update again this issue's status whether this issue can be closed as resolved/fixed or if otherwise? Thank you

**Comment by TinoTran-Work** [comment]
Good morning,

I just spoke with my colleague and I have been informed that it is working.

Thank you for your time.  Have a magnificent day!
