### ISSUE TITLE
WET canada.ca theme popup menu 

### ISSUE THREAD

**Issue by annemac** [wet-boew/wet-boew#7163]
I have tested our app with the WET 4.0.17 and 4.0.18 with several mobile devices including Ipad, nexus and MS Surface. The popup menu (top right) seem to work only on Ipad but not Surface and Google Nexus. Not sure if this is a bug or not. You can view the menu in this location ( http://wet-boew.github.io/themes-dist/GCWeb/index-en.html ) using your mobile device to verify the issue.
Thank you
Anne

**Comment by masterbee** [comment]
@annemac : thank you for this. Can you verify that this is isolated to the implementation of the GCWeb? In other words if you could test the following page with those devices : http://wet-boew.github.io/wet-boew/index-en.html and report back on this thread if those devices could not open the popup menu (top right), this would help us know if this is wet core issue or a theme issue.

**Comment by hsrudnicki** [comment]
@annemac : Please respond to the last comment's question, as well update again this issue's status whether this issue can be closed as resolved/fixed or if otherwise? Thank you

**Comment by annemac** [comment]
As far as I can remember, it was the browser issue. After I had the device's the auto-update mode ON, it seemed to resolve the problem.
