### ISSUE TITLE
Date picker - French months

### ISSUE THREAD

**Issue by rlambert27** [wet-boew/wet-boew#7168]
Hello,

A client recently noticed that in french the months have the first letter in capitals. According to Office québécois de la langue française this is incorrect and the month should all be in lowercase.

See : http://www.oqlf.gouv.qc.ca/francilettre/pdf_franc8/ExtraitCCLQTI_DatesHeures.pdf

Is it possible to have the months set to lowercase.

@LaurentGoderre Should also be done in the new date picker unless it's already like that?

Thanks!

Roch

**Comment by LaurentGoderre** [comment]
I believe this should be done in the i18n file

**Comment by andre-gh** [comment]
@MaximMartel

**Comment by MaximMartel** [comment]
google spreadsheet updated with lower case month name in french @andre-gh @rlambert27

**Comment by rlambert27** [comment]
Merci Maxim!
