### ISSUE TITLE
Table headers not bolded in IE

### ISSUE THREAD

**Issue by Wenifred** [wet-boew/wet-boew#7170]
Hi there, the table headers <th> in IE 11 doesn't seem to be bold like it is in Firefox and Chrome. I haven't checked other versions of IE but thought I would flag it. Here is an example page: http://wet-boew.github.io/themes-dist/GCWeb/content-en.html

**Comment by andre-gh** [comment]
This looks like a CSS reset failure (Firefox appears to just be implicitly bolding them?), let me check with some things and get back to you.

**Comment by andre-gh** [comment]
It appears to be an issue of IE using our body font-weight rather than the implicit font weight on the TH.  I will look into if we should be setting font-weight on the body at all or if we should be resetting it on the TH to 700.

**Comment by andre-gh** [comment]
This issue is specific to the GCWeb theme

**Comment by hsrudnicki** [comment]
Please update this issue's status whether this issue, referenced with the issue 1043, can be closed as resolved/fixed or if otherwise?
[Just in case of more detailed styling guide within tables, there is other issue 7143 but to remove bold from TH ]

**Comment by bsouster** [comment]
Checking in -- WET v4.0.20 is also having this issue.

In IE11, <th> elements are not bolded.
