### ISSUE TITLE
details/summary bugs in all browsers

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/wet-boew#7176]
In browsers using the polyfill, the arrows indicating the state of the the details/summary is not showing up. In Browsers with native support for details/summary, WET breaks the existing support

**Comment by pjackson28** [comment]
The icons aren't showing up because no-details is not being added to the html element any more. Modernizr was doing that but none of the no-* classes are being added any more. Did someone mess with Modernizr?

**Comment by LaurentGoderre** [comment]
I believe the version of Modernizr was updated

**Comment by pjackson28** [comment]
Oddly enough the polyfills seem to be loading, it is just that Modernizr is no longer adding classes to the html element which some polyfills (including details/summary polyfill) was dependent upon. When I manually add no-details to the HTML element then the polyfill works fine. Was that a documented change for the new version of Modernizr? If Modernizr is no longer updating the HTML element then we'll need to review and update all plugins and polyfills as this is a breaking change.

Suggest reverting back the Modernizr version until we can update safely.

**Comment by pjackson28** [comment]
Also suggest we improve our testing to ensure version bumps of our dependencies don't break functionality like what happened here.

**Comment by andre-gh** [comment]
The Modernizr bump was done due to a build failure on new installs (404 downloading community something something) and thus happened without much testing.

**Comment by andre-gh** [comment]
If we want to revert, we will have to be careful not to revert to a version which no longer builds.

**Comment by pjackson28** [comment]
So I see a few possible approaches then.

1. Roll back to a previous versions that still adds the classes to the HTML element but also builds.

2. Test and fix all plugins and polyfills (and core) to remove the dependency upon the Modernizr add classes (or to at least add what is no longer being added).

Either way, something needs to be done quickly as there could be multiple things broken now. Note also that because details/summary doesn't work, the mobile panel will be broken and there is content that will seem unavailable to users (since they won't know that the details elements can be opened).

@masterbee What should be the way forward to address this issue?

**Comment by andre-gh** [comment]
@pjackson28 O.o does grunt-modernizr just build the master version of Modernizr?

**Comment by andre-gh** [comment]
@LaurentGoderre Am I reading their code right?  Do we/does it just follow the Modernizr master regardless of the grunt-modernizr version.

**Comment by pjackson28** [comment]
@andre-gh Yes it looks like it is doing a custom build based upon pass parameters. Here is the build URL in modernizr-custom.js:
```
http://modernizr.com/download/#-elem_details-elm_progress_meter-mathml-cors-load-mg-css3-input-inputtypes-svg-cssclasses-csstransitions-fontface-backgroundsize-borderimage-teststyles-testprops-testallprops-hasevents-prefixes-domprefixes
```

**Comment by andre-gh** [comment]
@pjackson28 Ok, we might have to add a new parameter they added or something.  Reverting would do us no good as we would continue to download the same version.  I will make this my priority today.

**Comment by LaurentGoderre** [comment]
I thi8nk in this case, since they rely on a web service, they don't really have a choice but to always point to the latest

**Comment by pjackson28** [comment]
@andre-gh I noticed something else that is interesting. It looks like Modernizr is still adding the classes that indicate native support (e.g., backgroundsize, borderimage, csstransitions, fontface, svg), they just stop adding the classes that indicate a lack of support (e.g., no-*). So maybe a relative quick fix could be to change all the cases that are dependent upon <code>.no-*</code> to instead be dependent upon the presence of absence of the positive classes. I noticed that the CSS transitions work that way where the presence of ".csstransitions" applies certain CSS (versus for details where it is the presence of .no-details).

**Comment by andre-gh** [comment]
I believe there is a setting for the inverse, I will take a look in a few (putting out a different fire atm)

**Comment by andre-gh** [comment]
The docs claim it will put both the no- and the supports class in, the "add css classes" flag appears to be set.  Still looking into this.

**Comment by andre-gh** [comment]
It seems like the issue is that modernizr is not including a bunch of the tests, trying to figure out why

**Comment by pjackson28** [comment]
The polyfills still seem to be loading correctly (the JS and CSS files are loaded and the polyfills are initialized) so the relevant tests should be running. We have a custom Modernizr build as we don't want to include all the tests as that could become a performance burden. The intention was to only include the tests for which we were providing polyfills/workarounds.

**Comment by andre-gh** [comment]
The JS is executing because `Modernizr.details` is undefined, not because the test is failing.  The test is not there at all.

**Comment by andre-gh** [comment]
We can upgrade to the cutomizr based 1.0.1 grunt-modernizr, but I am having issues getting it to pick up the progress test (I believe they made an incorrect assumption, I filed a bug with them)

**Comment by andre-gh** [comment]
@pjackson28 Should we just switch to using an in-repo copy of modernizr in the mean time?

**Comment by pjackson28** [comment]
@andre-gh Interesting, so the passed tests are the ones that are present. As for what to do next, we could implement that workaround for the short term just to get things working properly again (until we can fix the generation). I'm assuming the in-repo copy would just include the tests we need.

**Comment by andre-gh** [comment]
Yes, I will build a copy with the web interface.
