### ISSUE TITLE
Multimedia palyer: no play icon

### ISSUE THREAD

**Issue by marieeved** [wet-boew/wet-boew#7178]
Hi,

I tried to use the mediaplayer, but the video don't want to start. I don't even have the play icon.

on the server, I received this message: 
Line: 2
Erreur : Bad JSON array in data-wb-mltmd attribute

What I have to do to fix that?
Thanks.

**Comment by andre-gh** [comment]
Could you paste your HTML (place four spaces in front of each line to paste properly)

**Comment by marieeved** [comment]
same code as on the wet page
```
<figure class="wb-mltmd" data-wb-mltmd='{"shareUrl": "\\hrdc-drhc.net\Org\Collaboration\ServiceCanada\5456512\MissionCCMTGC2015_ServiceCanada_fr_v3.mp4"}'>
    <video width="6000" height="4000" title="Looking for a Job" poster="caloren-service-canada.jpg" >
      <source type="video/mp4" src="\\hrdc-drhc.net\Org\Collaboration\ServiceCanada\5456512\MissionCCMTGC2015_ServiceCanada_fr_v3.mp4" />
     <track src="cpts-lg-en.html" kind="captions" data-type="text/html" srclang="en" label="English" />
    </video>
<figcaption>
		<p>Looking for a Job (<a href="http://www.servicecanada.gc.ca/eng/video/lj.shtml">Transcript</a>)</p>
	</figcaption>
</figure>
```
me, I don't need the link for transcript so the figcaption could be eliminated.

**Comment by andre-gh** [comment]
There are two issues.  I believe the back slashes are causing issues with the JSON encoding, but aside from that such a URL will not play as that file is a URI to a network share and is not on the web.  You should have an HTTP or HTTPS url.

**Comment by marieeved** [comment]
thank you. ok it means that we can't do that because my team is not responsible of this video. just by curiosity, how we can put a video like this, that is recorded on shared folder.  on the web with a http adress??

**Comment by andre-gh** [comment]
It should be uploaded to a web (http) server accessible to the network viewing the HTML content

**Comment by marieeved** [comment]
you mean like any page that we want to publish on the server...
the video must have a format like mp4 (and not wpl), then we take this url and we include it in the code for the video, right?

**Comment by andre-gh** [comment]
Yes, the video has to be published to a server and in a format which browsers can play (I do not believe playlist files will play).  It is possible that a local video url like that will work if the html you are viewing is also local, although I am not sure about that.

**Comment by marieeved** [comment]
thanks a lot for the précisions.

**Comment by marieeved** [comment]
Hi, 
I wanted to write an other comment because I had problems again. but the problem was an interaction with adobe flash player. I just click on "autorised" and the play button appears!!!

great. :)
