### ISSUE TITLE
wb-tabs and latest firefox causes tabs to align to right of form

### ISSUE THREAD

**Issue by danpoleary** [wet-boew/wet-boew#7179]
I have compared WET 4.0.12 and 4.0.18, and in 12, the tabs appear inline to the page in all browsers, but in 18, tabs move off to the right of the form in firefox, but the actual tab content is in the correct location. Other browsers work fine. 

Not sure what is causing this. I have tested the demos from the site, and they work, but they are using version 19.

**Comment by andre-gh** [comment]
Likely something broken with the details again, I will take a look.

**Comment by andre-gh** [comment]
Could you provide a screenshot?  I am having a hard time reproducing this issue, the tabs appear aligned correctly for me in Firefox.

**Comment by danpoleary** [comment]
Sorry for the delay. Was off on holiday..
![tab issue](https://cloud.githubusercontent.com/assets/209166/11473689/cfac820a-9741-11e5-84ad-ea43def752a0.JPG)

Update, this issue only happens when deployed WildFly and using Firefox. Everything works fine on Tomcat 7 and 8, and all other browsers work except firefox when using Wildfly 9.

**Comment by danpoleary** [comment]
I was able to resolve. It appears to be an issue with a base CSS conflict between WET and our custom CSS, that causes the issue in Firefox. I was able to put extra conditions to resolve correctly. Took a while, but I found it.
