### ISSUE TITLE
Menu plugin overwriting link url

### ISSUE THREAD

**Issue by GarthMartin** [wet-boew/wet-boew#7180]
I have 2 links in my menu that point to the same url, however one has an encrypted query string and the other does not.  On initial page load, all is well and my links look like this:

```html
<ul class="sm list-unstyled" id="activity" role="menu" aria-expanded="false" aria-hidden="true">
        <li><a tabindex="-1" class=" wb-navcurr" id="Menu_hypWorkspace" role="menuitem" aria-posinset="1" aria-setsize="6" href="/Workspace-Monespace">Workspace</a></li>


        <li><a tabindex="-1" id="Menu_hypAddJDRecord" role="menuitem" aria-posinset="2" aria-setsize="6" href="/CreateJobDescription-Creerdescriptiondetravail">Add a Job Description</a></li>
 
        <li><a tabindex="-1" id="Menu_hypAddGenericJDRecord" role="menuitem" aria-posinset="3" aria-setsize="6" href="/CreateJobDescription-Creerdescriptiondetravail/mnhqmD6s16ChSgxnAXD_ywaZsPcBEjgG5_EIiAH2Sa5VLK2B8wn9YqASjUK8_Rj9">Add a Generic Job Description</a></li>

        <li><a id="Menu_hypFindJDRecord" role="menuitem" aria-posinset="4" aria-setsize="6"></a></li>
        <li><a id="Menu_hypFindGenericJDRecord" role="menuitem" aria-posinset="5" aria-setsize="6"></a></li>

         <li><a tabindex="-1" id="Menu_hypAdvSearch" role="menuitem" aria-posinset="6" aria-setsize="6" href="/Advanced-Search-Recherche-Avancee">Advanced Search</a></li>
    </ul>
```
If for example I select the link with the query string, when the page reloads for some reason the url for the first link (without a query string) has inherited the url from the second link!

```html

<ul class="sm list-unstyled" id="activity" role="menu" aria-expanded="false" aria-hidden="true">
        <li><a tabindex="-1" id="Menu_hypWorkspace" role="menuitem" aria-posinset="1" aria-setsize="6" href="/Workspace-Monespace">Workspace</a></li>


        <li><a tabindex="-1" id="Menu_hypAddJDRecord" role="menuitem" aria-posinset="2" aria-setsize="6" href="/CreateJobDescription-Creerdescriptiondetravail/mnhqmD6s16ChSgxnAXD_ywaZsPcBEjgG5_EIiAH2Sa5VLK2B8wn9YqASjUK8_Rj9">Add a Job Description</a></li>
 
        <li><a tabindex="-1" class=" wb-navcurr" id="Menu_hypAddGenericJDRecord" role="menuitem" aria-posinset="3" aria-setsize="6" href="/CreateJobDescription-Creerdescriptiondetravail/mnhqmD6s16ChSgxnAXD_ywaZsPcBEjgG5_EIiAH2Sa5VLK2B8wn9YqASjUK8_Rj9">Add a Generic Job Description</a></li>

        <li><a id="Menu_hypFindJDRecord" role="menuitem" aria-posinset="4" aria-setsize="6"></a></li>
        <li><a id="Menu_hypFindGenericJDRecord" role="menuitem" aria-posinset="5" aria-setsize="6"></a></li>

         <li><a tabindex="-1" id="Menu_hypAdvSearch" role="menuitem" aria-posinset="6" aria-setsize="6" href="/Advanced-Search-Recherche-Avancee">Advanced Search</a></li>
    </ul>
```

I know that the plugin does some stuff based on the current page matching the selected menu item, but why is it overwriting the url?

Needless to say, I am relying on the query string in the second instance to handle different scenarios.

Thanks in advance,

Garth

**Comment by pjackson28** [comment]
What the plugin does is replace the original markup with what is included in the file referenced by <code>data-ajax-replace</code> (on the <code>nav</code>) element. If you are seeing changes in links after page load then that likely means that the original markup and the markup in the include file are out of sync.

**Comment by GarthMartin** [comment]
I am not using data-ajax-replace.  Due to the security requirements of the application, the menu is driven by the user's role and permissions, so a hardcoded menu file does not work for us.

On another completely unrelated topic, do you have a recommended solution for data driven menus that work with the plugin?

**Comment by pjackson28** [comment]
If you are not using data-ajax-replace then it is unlikely that WET is changing your links. It likely has to do with whatever code is morphing the menu based upon the user's role and permissions.

As for data-driven menus, you could resolve it using data-ajax-replace. You could have a server-side script that returns HTML based upon what is passed in the data-ajax-replace URL (so dynamically update that URL based upon the data before WET sends the request). So for instance you could pass which items to include/exclude in the resulting HTML.

Alternatively you could just update the HTML directly with client-side scripting (or even server-side scripting) in lieu of using the data-ajax-replace attribute (whose sole purpose is bring in the menu to enhance).

**Comment by hsrudnicki** [comment]
@GarthMartin : Is this still an issue?  Please update this issue's status whether this issue can be closed as resolved/fixed, based on the above comments, or if otherwise? Thank you

**Comment by hsrudnicki** [comment]
Based on the above, this can be closed as resolved, if you think otherwise please update the status of this for the current year, thank you
