### ISSUE TITLE
Datepicker doesn't work for IE9

### ISSUE THREAD

**Issue by tinazl** [wet-boew/wet-boew#7181]
https://wet-boew.github.io/wet-boew/demos/datepicker/datepicker-en.html

Datepicker only work for firefox, but not IE9.

**Comment by andre-gh** [comment]
Hmm, appears to work correctly in IE9 for me, is it possible you have some security rules in your IE setup preventing javascript from loading at all?  Is there specific functionality not working?

**Comment by hsrudnicki** [comment]
@tinazl : Is this still an issue? Please update this issue's status whether this issue can be closed as resolved/fixed or otherwise? Thank you

**Comment by masterbee** [comment]
closed since IE9 is not longer supported
