### ISSUE TITLE
Form validation: checkboxes

### ISSUE THREAD

**Issue by splashE** [wet-boew/wet-boew#7182]
Hi, Pls help. How to make the form valid just by selecting one or two checkboxes, but not all four. Pls see the code. Thank you. 
<fieldset>
<legend><span class="h2">Heading 1</span></legend>
<div class="form-group">
<label class="required"><span class="field-name">Heading 2 (check all that apply)</span> <strong class="required">(required)</strong></label>

<div class="checkbox">
<label for="requestor-0" ><input type="checkbox" name="requestor" value="checkbox-1" id="requestor-0" required   />checkbox-1</label>
</div>

<div class="checkbox"> 
<label for="requestor-1" ><input type="checkbox" name="requestor" value="checkbox-2" id="requestor-1" required   />checkbox-2</label>
</div>

<div class="checkbox"> 
<label for="requestor-2" ><input type="checkbox" name="requestor" value="checkbox-3" id="requestor-1" required   />checkbox-3</label>
</div>

<div class="checkbox"> 
<label for="requestor-3" ><input type="checkbox" name="requestor" value="checkbox-4" id="requestor-1" required   />checkbox-4</label>
</div>
</div>
</fieldset>

**Comment by LaurentGoderre** [comment]
I believe you need to create a custom validator for such purpose

**Comment by splashE** [comment]
Thank you for the quick response. If you had any code example handy, could you pls send it over to me. Oh course, if it's not a trouble. I also have the same problem with a drop-down menu. Thank you.

**Comment by biljanap** [comment]
Wouldn’t this be the case where using <code>fieldset</code> could solve the problem?
Example:
```html
<fieldset>
  <legend aria-required="true" class="required"><span class="field-name">Legend text</span> <strong aria-required="true" class="required">(required)</strong></legend>
  <div class="checkbox">
    <label for="checkbox1">
      <input aria-required="true" name="checkboxgroup" value="1" id="checkbox1" required="required" type="checkbox">
      &nbsp;&nbsp;checkbox-1 </label>
  </div>
  <div class="checkbox">
    <label for="checkbox2">
      <input name="checkboxgroup" value="2" id="checkbox2" type="checkbox">
      &nbsp;&nbsp;checkbox-2 </label>
  </div>
  <div class="checkbox">
    <label for="checkbox3">
      <input name="checkboxgroup" value="3" id="checkbox3" type="checkbox">
      &nbsp;&nbsp;checkbox-3 </label>
  </div>
  <div class="checkbox">
    <label for="checkbox4">
      <input name="checkboxgroup" value="4" id="checkbox4" type="checkbox">
      &nbsp;&nbsp;checkbox-4 </label>
  </div>
</fieldset>

**Comment by splashE** [comment]
This works. Thank you for your help.

**Comment by hsrudnicki** [comment]
Based on the last comments, can be this issue closed as resolved or if otherwise?

**Comment by hsrudnicki** [comment]
This can be closed as resolved based on the above. If you think otherwise, please update again the status of this, thx
