### ISSUE TITLE
WET4 latest release v4.0.18 - Play buttons and arrowsmissing

### ISSUE THREAD

**Issue by karyen** [wet-boew/wet-boew#7189]
The play buttons for the videos and arrows for the breadcrumbs disappeared with this latest release. It would be great to have this fixed as soon as possible.

**Comment by pjackson28** [comment]
@karyen They seem to be working fine on the live working examples. Are they working fine on the live working examples for you as well?

**Comment by karyen** [comment]
Hi Paul, no the play buttons don't show up like on this page: http://wet-boew.github.io/v4.0-ci/demos/multimedia/multimedia-en.html I don't see the play buttons on the video overlays, do you?

**Comment by karyen** [comment]
Maybe it's an IE11 issue?

**Comment by pjackson28** [comment]
They are showing up for me in IE11 so most likely it is an issue with how your browser is configured. Likely font download is disabled in the security tab, which the glyphicons are dependent upon being enabled to display correctly.

**Comment by pjackson28** [comment]
Here is blog post about how to change it (although it is about IE8): http://missmarcialee.com/2011/08/how-to-enable-font-download-in-internet-explorer-8/. Note that you may not have access to the security tab (may be managed only by the system administrator).

**Comment by karyen** [comment]
You're right. I don't have access to the security tab so I will see what I can do. Everything worked fine before updating the files with the latest release though. Hopefully I can get this resolved.Thanks you ;-)

**Comment by hsrudnicki** [comment]
Is this above still an issue? Either way, please update this issue's status, whether this issue can be closed as resolved/fixed or if otherwise?  Thank you

**Comment by karyen** [comment]
This can be closed. Thank you ;-)

>>> On 2016/01/21 at 2:18 PM, in message
<wet-boew/wet-boew/issues/7189/173679489@github.com>, Hanna S Rudnicki
<notifications@github.com> wrote:


Is this above still an issue? Either way, please update this issue's
status, whether this issue can be closed as resolved/fixed or if
otherwise? Thank you
—
Reply to this email directly or view it on GitHub (
https://github.com/wet-boew/wet-boew/issues/7189#issuecomment-173679489
).



Ce courriel est destiné exclusivement au destinataire mentionné en titre
et peut contenir de l'information privilégiée, confidentielle ou
soustraite à la communication aux termes des lois applicables. Toute
divulgation non autorisée, toute reproduction ou réacheminement est
interdit. Si vous n'êtes pas le destinataire de ce courriel, ou n'êtes
pas autorisé par le destinataire visé, ou encore, si vous l'avez reçu
par erreur, veuillez le mentionner immédiatement à l'expéditeur et
supprimer le courriel et les copies.  

This e-mail message is intended for the named recipient(s) and may
contain information that is privileged, confidential and/or exempt from
disclosure under applicable law. Unauthorized disclosure, copying or
re-transmission is prohibited. If you are not a named recipient or not
authorized by the named recipient(s), or if you have received this
e-mail in error, then please notify the sender immediately and delete
the message and any copies.

**Comment by hsrudnicki** [comment]
Based on the last comment, it's closed.
