### ISSUE TITLE
Share Widget

### ISSUE THREAD

**Issue by tjshin** [wet-boew/wet-boew#7190]
Is there anyway to trigger a click event for the Share Widget modal with my link instead of using div wb-share? I would like to use the share icon from font-awesome instead of the default glyphicon on share widget link.

**Comment by pjackson28** [comment]
@tjshin I don't think it supports opening on a click event on a custom link but you could easily make the change using the "Add custom CSS to the share link" option. You could add a class that hides the Glyphicon (with display: none) and then adds the Font Awesome version (e.g., using :before + content to inject the HTML).

**Comment by pjackson28** [comment]
@tjshin Correction, you can't insert the HTML with CSS but you could either override what is displayed by the glyphicon span with CSS or you could use JS to inject your own HTML before the glyphicon span (fire off the JS after the wb-ready.wb-share event is fired for that element). So there are a few ways you could manipulate how the share link is displayed.

**Comment by tjshin** [comment]
@pjackson28 Thanks for the info. Perhaps near future release could accommodate custom icon? ;)

**Comment by hsrudnicki** [comment]
@tjshin : Based on the last comments, can be this issue closed as resolved/fixed?  Either way, please update this issue's status, whether this issue can be closed as resolved/fixed or if otherwise? Thank you
