### ISSUE TITLE
Archived webpage:  Alert message

### ISSUE THREAD

**Issue by nimans2** [wet-boew/wet-boew#7198]
To whom it may concern:

FYI (or action if you approve).

We had our french editor read and correct the french text of the Archived message provided on your website as an example.  There is a mistake in the french content of the example for archived content [ARCHIVED - Archived Information](http://wet-boew.github.io/wet-boew/demos/archived/archived-fr.html) and thought we could share it with you.

I have put in bold the text where it needs or suggest the changes.  

Title should read : **Renseignements** archivés 
 
Cette page a été archivée dans le Web. **Les renseignements archivés sont fournis** aux fins de référence, de recherche ou de tenue de documents. **Ils** ne sont pas **assujettis** aux normes Web du gouvernement du Canada et n'ont pas été **modifiés ou mis** à jour depuis leur archivage. Pour obtenir ces **renseignements sous une** autre forme, veuillez **communiquer** avec nous.

If you have any questions, please don't hesitate to contact me.

Sylvie Niman
Web Communications Advisor
Indigenous and Northern Affairs Canada
819-994-3071

**Comment by MaximMartel** [comment]
I'll take care of this issue, and notify when it will be approved etc...

**Comment by nimans2** [comment]
Thank you!
Sylvie

>>> Maxim Martel <notifications@github.com> November 19, 2015 9:33 AM >>>

I'll take care of this issue, and notify when it will be approved etc...

**Comment by nimans2** [comment]
Hi Maxim:

Any news on the approvals of the modified french message?

Thank you,
Sylvie Niman




Sylvie Niman -
Conseillère en communications Web | Web Communications Advisor
Communications interne et Innovation  |  Internal Communications and Innovation
Direction générale des Communications   |   Communications Branch
Affaires autochtones et du Nord Canada  |  Indigenous and Northern Affairs Canada
Gatineau, Québec   K1A 0H4  |  Gatineau, Quebec   K1A 0H4
Sylvie.Niman@aadnc-aandc.gc.ca 
Téléphone  |  Telephone   819-994-3071
Téléimprimeur  |  Teletypewriter  1-866-553-0554
Gouvernement du Canada  |  Government of Canada
>>> Maxim Martel <notifications@github.com> November 19, 2015 9:33 AM >>>

I'll take care of this issue, and notify when it will be approved etc...

**Comment by hsrudnicki** [comment]
Is this above still an issue waiting for the approval(s) or otherwise?  Either way, please update the status of this issue, whether this issue can be closed as fixed or otherwise, thank you

**Comment by nimans2** [comment]
Hi Hanna:

Yes, it is still outstanding I believe.  I never got a response if the archive message was changed in the WET examples.

Thank you for checking.

Sylvie

>>> Hanna S Rudnicki <notifications@github.com> February 23, 2016 12:27 PM >>>

Is this above still an issue waiting for the approval(s) or otherwise? Either way, please update the status of this issue, whether this issue can be closed as fixed or otherwise, thank you

**Comment by nimans2** [comment]
Will anyone provide me an answer regarding the e-mail above?  This has been on-going since November 17, 2015 and had gotten a response from Maxim Martel that this issue was being taken care of.

Thank you,
Sylvie Niman

**Comment by MaximMartel** [comment]
Hi,

This is tricky, since the archive message is not a centralized solution, that means that if we do change the message on the WET examples, only new pages with the updated example will be with the new text. We need to keep this consistent across all sites and we must not have lots of version of the message. 

Therefore, we will not change the french archive message. Whenever we will get a centralize solution for archived pages, at that point we will review the messages.

Thank you,

Maxim Martel

**Comment by nimans2** [comment]
Salut Maxim,

There is a mistake anyways in the last sentence in french from the example that is provided by the WET Toolbox:

http://wet-boew.github.io/v4.0-ci/demos/archived/archived-fr.html
".... Pour obtenir ces informations dans un autre format, veuillez communiquer avec nous."

Therefore, it would need to be changed or else, every department/agencies are putting an error on their pages.  This is risky to have an official language complaint.

Thank you,
Sylvie Niman

>>> Maxim Martel <notifications@github.com> March 14, 2016 12:02 PM >>>

Hi,
This is tricky, since the archive message is not a centralized solution, that means that if we do change the message on the WET examples, only new pages with the updated example will be with the new text. We need to keep this consistent across all sites and we must not have lots of version of the message. 
Therefore, we will not change the french archive message. Whenever we will get a centralize solution for archived pages, at that point we will review the messages.
Thank you,
Maxim Martel

**Comment by nimans2** [comment]
Salut Maxim,
 
There is a mistake anyways in the last sentence in french from the example that is provided by the WET Toolbox:
 
http://wet-boew.github.io/v4.0-ci/demos/archived/archived-fr.html
".... Pour obtenir ces informations dans un autre format, veuillez communiquer avec nous."
 
Therefore, it would need to be changed or else, every department/agencies are putting an error on their pages.  This is risky to have an official language complaint.

This ticket is not to be closed.
Thank you,
Sylvie Niman

**Comment by nimans2** [comment]
Also, this can be rectified in the next version 21 released for the templates.

Thank you,
Sylvie

**Comment by MaximMartel** [comment]
I will fix the error in the last sentence no problem for release 4.0.21

**Comment by nimans2** [comment]
Merci Maxim!
Sylvie

>>> Maxim Martel <notifications@github.com> March 16, 2016 8:43 AM >>>

I will fix the error in the last sentence no problem for release 4.0.21
