### ISSUE TITLE
jQuery 1.11.1 and 2.1.4 in Wrong Directories

### ISSUE THREAD

**Issue by JammG** [wet-boew/wet-boew#7199]
I'm in a position where I need to load jQuery locally instead of from google. I was under the impression that the copies of jquery in js/jquery/1.11.1 and js/jquery/2.1.4 could be used for this purpose. Is this correct? 

Looking at the headers of the source files, it looks like they've been reversed accidentally. ie.: 2.1.4 is in the 1.11.1 directory and vice versa. I will download my own copies and use those, but logging this in case others are having similar problems. (Wet 4.0.18)

**Comment by LaurentGoderre** [comment]
You're right! Thanks for pointing that out
