### ISSUE TITLE
Tabbed Interface: Cannot enter in text into input field when form is inside a tab on Android devices.

### ISSUE THREAD

**Issue by muling** [wet-boew/wet-boew#7205]
When you select a text input field, the keyboard to type in the text expands, then contracts again as soon as you try to type something in.

**Comment by muling** [comment]
This was tested using Browserstack.

**Comment by andre-gh** [comment]
Sounds like a focus issue, I will look into this before the next release.

**Comment by MaximMartel** [comment]
i used BroweserStack, with a Samsung S5, and i do have that issue Muling. Working on a fix @andre-gh

**Comment by andre-gh** [comment]
This is caused by equal heights, equal heights is no longer used on the mobile tabs view of the plugin (and was accidentally used and fixed in #7216) and thus was fixed.
