### ISSUE TITLE
as headingsDetails/summary polyfill (expandable/collapsible content): 

### ISSUE THREAD

**Issue by SBleeks** [wet-boew/wet-boew#7207]
Is it possible to code the expand/collapsible text as a heading?  In essence, once the content is expanded, a new section is introduced and new sections should be preceeded by a heading.

**Comment by LaurentGoderre** [comment]
According to the draft spec for HTML 5.1, you can add a heading inside a details tag

http://www.w3.org/html/wg/drafts/html/master/semantics.html#the-summary-element

**Comment by SBleeks** [comment]
The W3C validator returns this message:

  1.  “Warning: The details element is not supported properly by browsers yet. It would probably be better to wait for implementations.
“.

**Comment by LaurentGoderre** [comment]
Yeah that's finer, it's just a warning and we polyfill it so you can ignore that message

**Comment by MaximMartel** [comment]
Thanks @LaurentGoderre  can we close the issue now?

**Comment by SBleeks** [comment]
Yes. Thank you.
