### ISSUE TITLE
Input type="date" polyfill (date picker): 

### ISSUE THREAD

**Issue by silentcanadian** [wet-boew/wet-boew#7215]
I'm experiencing an issue when using the date picker within the WET tabbed interface.  If the control using the date picker (I'm using a ASP.NET textbox control) is at the bottom of the tab content area the date picker calendar is cut off and 1) doesn't automatically adjust it's position so that it's all visible, and 2) the tab container is not resized to fit the date picker appearing.  I'm using the latest version of WET.

**Comment by RobJohnston** [comment]
Is that the same as #6441 ?

**Comment by MaximMartel** [comment]
@andre-gh

**Comment by silentcanadian** [comment]
I've just viewed issue #6441.  Looks like it is the same issue.

**Comment by MaximMartel** [comment]
Can we close this one then @silentcanadian ?

**Comment by silentcanadian** [comment]
Yes, this can be closed. In the end I had moved the textbox components using the date picker so they are no longer at the bottom of the tabbed content. There's enough room now so the calendar is not cut off.
