### ISSUE TITLE
Update time-grunt in next release

### ISSUE THREAD

**Issue by andre-gh** [wet-boew/wet-boew#7217]
Currently causes a time array related error on `npm install` but only some of the time.  Should be fixed in latest `time-grunt`

**Comment by hsrudnicki** [comment]
Is the above still an issue?  Either way, please update this issue's status whether this issue can be closed as fixed/closed or if otherwise?  Thank you

**Comment by hsrudnicki** [comment]
Can be this closed or otherwise?

**Comment by hsrudnicki** [comment]
FYI: There is also another build issue: 6518 to consider/include in a build upgrade. Thx

**Comment by hsrudnicki** [comment]
Since time-grunt has been merged into CGWeb build ( https://github.com/wet-boew/GCWeb/pull/1174 ), please update the status of this again, whether this remains still an issue or can be closed as resolved? Thank you

**Comment by EricDunsworth** [comment]
@hsrudnicki PR #7391 updated package.json's minimum time-grunt version to 1.3.0 in early May (latest version at the time) to fix the same error covered within this issue. So this issue is now resolved.
