### ISSUE TITLE
Best practices: Function that work inside and outside WET components?

### ISSUE THREAD

**Issue by johnpalaganas** [wet-boew/wet-boew#7218]
Hello,

What would be the best practices for creating a Javascript function that will work on both within a WET component such as Tabs, etc... and the normal way? No point of writing a function twice and I don't want to call the same function twice either. Any recommendations?

```javascript
myAwesomeFunction = function() {
	...
}
//Inside WET
$(document).on("wb-ready.wb", myAwesomeFunction);

//Normal 
$(document).ready(myAwesomeFunction);
```

Thanks,
John

**Comment by LaurentGoderre** [comment]
You can binf to multiple events ion the same call

```
$(document).on("ready wb-ready.wb", myAwesomeFunction);
```

However it will twice. You can use `one` instead to run the function on the first event in the list that occurs

```
$(document).one("ready wb-ready.wb", myAwesomeFunction);
```

**Comment by johnpalaganas** [comment]
@LaurentGoderre Thank you, will give your last suggestion a try!

**Comment by johnpalaganas** [comment]
@LaurentGoderre Your suggestion works inside WET but not outside for some reason. How can you successfully run the function that's inside and outside a WET component on the same page?

**Comment by andre-gh** [comment]
@johnpalaganas I think perhaps we are confused as to what you mean by "outside WET".  Could you clarify the setup?

**Comment by johnpalaganas** [comment]
@andre-gh I meant outside a WET component that should be triggered on document ready under normal circumstances.

An example would be a button A to trigger a function A. This button A is inside a WET tab and I also have another button B to trigger function A that is placed outside the WET tab.

I would like button A and button B to work regardless of whether it's inside a WET tab/component or not.

Please do let me know if it's not clear enough and I will elaborate some more.

**Comment by andre-gh** [comment]
The event `ready` and `wb-ready.wb` are global assuming you have included WET in your javascript.   What I assume is occurring is that you are running 

> $(document).one("ready wb-ready.wb", myAwesomeFunction);

After ready and wb-ready have already fired and nothing is executing as they do not come around twice, `ready` indicates that the document is ready and `wb-ready.wb` indicates that the web experience toolkit is ready and are global events not affected by which element triggers function to register an event listener for them.

**Comment by LaurentGoderre** [comment]
The ready event is a very special scenario. Do you just want click or key events on multiple element to execute the same function? If so, WET plays no part in this and it becomes plain JS and DOM

**Comment by johnpalaganas** [comment]
If I use
```javascript
$(document).on("ready wb-ready.wb", myAwesomeFunction);
```
Element(Button A to trigger Function A) inside a WET component gets triggered once which is great. However, element(Button B to trigger Function A) outside the WET component gets triggered twice. I only need the element(Button B to trigger Function A) to trigger once.

The work around seems to be to duplicate a function for the sake of accommodating elements inside a WET component.

**Comment by pjackson28** [comment]
@johnpalaganas Will both cases (inside a component and outside of a component) still be on a WET-enabled page? If so, then you only need to listen for <code>wb-ready.wb</code> as that event will be fired on any WET-enabled page, after all WET processing is completed, regardless of the number of components in use (and whether or not you are nesting stuff in a WET component).

**Comment by johnpalaganas** [comment]
@pjackson28 Yes, it will be on a WET-enabled page. Thanks, will give that a try.

**Comment by johnpalaganas** [comment]
Wow thanks Paul! So simple, it works! Wasn't sure why I was making things complicated.
```javascript
$(document).on("ready wb-ready.wb", myAwesomeFunction);
```
Only triggers once for any element inside or outside a WET element :)
