### ISSUE TITLE
Addition to writing guide - temperature

### ISSUE THREAD

**Issue by LanaStewart1** [wet-boew/wet-boew#7221]
Could the formatting for temperature be included in the writing guide?

**Comment by hsrudnicki** [comment]
Is the above still an issue? Either way, please update this issue's status whether this issue can be closed as fixed/closed or if otherwise? Thank you

**Comment by hsrudnicki** [comment]
Can be this issue closed after referencing to the 5574 issue that shall implement the temperature formatting or if otherwise?  Please update again the status of this, thx

**Comment by masterbee** [comment]
Closed since caller (creator of issue) has abandoned the issue. 

Notified https://github.com/wet-boew/wet-boew-styleguide repo of this issue to take into consideration.
