### ISSUE TITLE
Geomap 

### ISSUE THREAD

**Issue by Bgolden67** [wet-boew/wet-boew#7224]
Is there anything in the works to replace the WET3 Geomap plugin in WET4?

**Comment by LaurentGoderre** [comment]
There is a geomap ppluigin in WET4

**Comment by MaximMartel** [comment]
http://wet-boew.github.io/wet-boew/demos/geomap/geomap-en.html

**Comment by Bgolden67** [comment]
Great! thanks.. i wasn't finding it
Appreciate the link
