### ISSUE TITLE
HTML5 "pattern" attribute being stripped out

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/wet-boew#7226]
Let's say that I have a textbox in a webforms project that looks like this:

```html
<asp:textbox id="TextBox1" runat="server" pattern="[A-Za-z0-9\s]{4,}"/>
```

Upon rendering, the pattern attribute is removed and there's no work-around that I can think of to get it back.  

I tracked it down to https://github.com/wet-boew/wet-boew/blob/0f614e0efd50df7970a6fc6bb72104e43b48e8f5/src/plugins/formvalid/formvalid.js#L105

```js
// Remove the pattern attribute until it is safe to use with jQuery Validation
  len = $pattern.length;
  for ( i = 0; i !== len; i += 1 ) {
    $pattern.eq( i ).removeAttr( "pattern" );
  }
```

Is this attribute never put back?

**Comment by RobJohnston** [comment]
Update to last... nothing to do with dot net.  Even the following will have the pattern attribute removed:
```html
<input class="form-control" id="an1" name="an1" type="text" pattern="[A-Za-z0-9\s]{4,}" data-rule-alphanumeric="true" data-rule-minlength="4" />
```
This gets rendered as:
```html
<input name="an1" class="form-control" id="an1" type="text" data-rule-minlength="4" data-rule-alphanumeric="true">
```
Where did the pattern go?

**Comment by pjackson28** [comment]
@RobJohnston That is intentional behaviour as the pattern attribute was tripping up jQuery validation by causing it to ignore the configured error message (specific to the field in question and the language of the page) and to instead revert to a generic English error message. Now it may be possible that the issue in jQuery validation has been fixed, negating the need for this workaround, but until that issue is confirmed to be fixed then the workaround should remain in place.

Keep in mind that the pattern attribute doesn't serve much of a purpose unless HTML5 validation is being used which only happens when jQuery validation isn't running. So if JS or WET enhancements are disabled then jQuery validation won't load and the pattern attribute wouldn't be removed, meaning HTML validation using the pattern attribute could proceed as normal.

**Comment by RobJohnston** [comment]
I could find no issue issue related to this and assumed it was a problem from awhile ago, but the use of the pattern attribute in the form validation examples implies that it is useful.  

So if a field had to be validated to match a pattern, then the jQuery Validation addMethod should be used in addition to the pattern?  Is this the way to go?

**Comment by pjackson28** [comment]
@RobJohnston The pattern attribute is only included as a fallback for when jQuery validation doesn't load as jQuery validation doesn't take the pattern attribute into account when initializing a form field. So yes, you can't rely upon the pattern attribute alone as you would also need to use one of the pre-defined validation options or create your own custom validation (using something like addMethod).

**Comment by RobJohnston** [comment]
Then maybe an example on the form validation page is in order... something like:

```html
<div class="wb-frmvld">
	<form action="#" method="get" id="validation-example">
	...
	<div class="form-group">
		<label for="text1"><span class="field-name">Client ID</span> (0000-0000)</label>
		<input class="form-control client-valid" id="text1" name="text1" type="text" pattern="[\d{4}-\d{4}]{9,9}" />
	</div>
	...
	<script type="text/javascript">
		wb.doc.on("wb-ready.wb", function (event) {
			jQuery.validator.addMethod("client-valid", function (value, element) {
			return this.optional(element) || /^\d{4}-\d{4}$/.test(value);
			}, 'Please specify a valid client id.');
		});
	</script>

**Comment by pjackson28** [comment]
@RobJohnston It would likely be helpful to others to have an example of custom validation on the page. Could you please submit a PR for this (for both English and French)? Note that in HTML5 the default type for script elements is "text/javascript" so you don't need to use the type attribute in your example (since you are using JavaScript).

**Comment by RobJohnston** [comment]
Correct me if I'm wrong, but I don't think such as example would actually function on that page because the custom script with addMethod has to be rendered after some other scripts are included, which isn't done until after the footer:
```html
</footer>
<!--[if gte IE 9 | !IE ]><!-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="../../wet-boew/js/wet-boew.min.js"></script>
```
See what I mean?  Changing the hbs file puts everything too high.

**Comment by LaurentGoderre** [comment]
This parts `wb.doc.on("wb-ready.wb", function (event) {` would allow it to maybe work, because it defers the execution of the function after some of WET has loaded. This is the biggest weakness of WET, the fact that it does a pseudo-async.

**Comment by RobJohnston** [comment]
I've only ever seen "JavaScript runtime error: 'wb' is undefined" when I have it before.

**Comment by LaurentGoderre** [comment]
OOOh yes of course, in this case if it's not at the bottom you need to do `$(document).on("wb-ready.wb", function (event) {`

**Comment by RobJohnston** [comment]
But the "$(document)" part must still come after the line that loads jquery.min.js or else "$" will be undefined, no? I don't think this solves the problem.

**Comment by LaurentGoderre** [comment]
Yeah...that's true.....I don't think you can place scripts in the middle of the content. Of course you can but it would be a big hack and very inefficient.

**Comment by RobJohnston** [comment]
On a related note... the jQuery script is loaded at the top in the <head> section for IE below 9 but at the bottom for everything else.  Now that IE8 is out of the support window, will this be changing to put jQuery higher up, or should we just close this issue now and never speak of it again?

**Comment by LaurentGoderre** [comment]
I don't know why it was put on the head for older IE8 but it don't think it likely we would put jQuery in the head for the time being

**Comment by RobJohnston** [comment]
Well, I did notice Paul's concern about the error message ignoring the language of the page, so it's either a fix with jQuery Validation or something else.  Since nothing can be done here, I'm closing.
