### ISSUE TITLE
Can you add the CDN release package on the GitHub release

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/wet-boew#7229]
Like the following release:

https://github.com/wet-boew/wet-boew/releases/tag/v4.0.16

**Comment by andre-gh** [comment]
I saw that.  Doing so, just very slow upload/download over here.

**Comment by LaurentGoderre** [comment]
When/if Github ever adds a token for creating release, you will be able to complete what I started and automate the 5% lleft so you would not need to intervene at all past the release command

**Comment by andre-gh** [comment]
Got the CDN in there while I am waiting for the GCWeb dist to download.

**Comment by LaurentGoderre** [comment]
You guys almost can automate the creation of releases:

https://developer.github.com/v3/repos/releases/

The only thing you should way for is a release create token so you won't have to give the WET Bot push access to all reps (which you should not do)
