### ISSUE TITLE
Toggle in a panel : colors problem

### ISSUE THREAD

**Issue by marieeved** [wet-boew/wet-boew#7231]
Hi,

I put an accordion inside a panel (dark blue- panel primary). now, the text of the accordion is blue (like if a put a color-background).
Is it normal? How to fix that?
thank you.

**Comment by andre-gh** [comment]
What method are you using to make the panel-primary dark blue?

**Comment by andre-gh** [comment]
Sorry, I see, you mean the color of the panel primary is dark blue.  Could you verify that you have a panel-body div nested inside the "panel panel-primary"?

**Comment by marieeved** [comment]
here's my code:
this code is inside a tab divided in two columns.

```

<div class="col-md-6">
<h2>Mesures  d&rsquo;urgence</h2>

<section class="panel panel-primary">
	<header class="panel-heading">
		<h3 class="panel-title">Nous joindre</h3>
	</header>

	<div class="panel-body">
<ul>
...
</ul>

 <div class="accordion">
	<!-- Accordion section 1 -->
	<details class="acc-group">
		<summary class="wb-toggle tgl-tab" data-toggle='{"parent": ".accordion", "group": ".acc-group"}'>Notre équipe</summary>
		<div class="tgl-panel">
			<!-- Section 1's content -->

<ul>
<li>Gestionnaire principale</li>
...
</ul>

<ul>
<li>Agents principaux</li>
...
</ul>
		</div><!--ferme le tgl-panel-->
	</details><!--ferme le groupe-->
 
    </div><!--ferme l'accordéon-->
</div><!--ferme le panel-body-->
</section><!--ferme le panel-->
```

**Comment by marieeved** [comment]
come back at office only tomorrow.

**Comment by andre-gh** [comment]
Which theme are you using?

**Comment by andre-gh** [comment]
(And which browser), I am having a hard time reproducing any blue text in the bodies

**Comment by marieeved** [comment]
I'm using Internet explorer 11 and wet 4.0.12 (theme gc intranet).

**Comment by andre-gh** [comment]
I have still been unable to reproduce, have you tested this using the latest release?

**Comment by hsrudnicki** [comment]
@marieeved and others:  Is this still an issue, waiting for an answer/more details?  Either way, please update this issue's status, whether this issue can be closed as resolved/fixed or if otherwise.  Thank you

**Comment by marieeved** [comment]
no, not testing in the new version...it will take me too time to try it. :)

still happening a second time... now, I use simple accordion (I mean when you click on a second one, the first accordion stay opened). it's not the same thing, but for now, it's good.

thanks, I will maybe consider to update the theme next time.
