### ISSUE TITLE
Huge space at top of page, RE issue 7077

### ISSUE THREAD

**Issue by seguinrs** [wet-boew/wet-boew#7235]
![space](https://cloud.githubusercontent.com/assets/14113912/11540522/36006fde-98fb-11e5-92e7-d963a31101cf.png)
This issue has been fixed in the external template but it still occurring the in the internal template.

**Comment by hsrudnicki** [comment]
Has been this issue resolved/fixed already or if otherwise?  Either way, please update this issue's status, whether this issue can be closed as fixed or otherwise?  Thank you

**Comment by hsrudnicki** [comment]
Is this still an issue? Please update the status of this, whether this can be closed or otherwise, thx

**Comment by masterbee** [comment]
Closed since caller (creator of issue) has abandoned the issue.
