### ISSUE TITLE
Feeds: Widget is currently not working

### ISSUE THREAD

**Issue by fomag** [wet-boew/wet-boew#7236]
We use the feed widget on several spots on our website and it is currently not functioning. I noticed it is also not working on the WET sample page. Does it connect to a service or something or is there a reason as to why it would not be working tight now? We haven't changed anything on our end except for updating the WET framework about a month ago.

http://www.cra-arc.gc.ca/menu-eng.html
http://wet-boew.github.io/v4.0-ci/demos/feeds/feeds-en.html

**Comment by andre-gh** [comment]
We are working to resolve the ongoing issue with the feeds widget.  The service the feeds plugin has been using is no longer functioning.

**Comment by hsrudnicki** [comment]
Fine, but please update this issue's status, whether this issue can be closed as resolved/fixed since two months already passing, or if otherwise?  Thank you

**Comment by LaurentGoderre** [comment]
I believe this was fixed in v.4.20 hasn't it @masterbee ?

**Comment by fomag** [comment]
I will close this task but can you let me know if there are still issues with the feed service? We seem to be having issues again with it not loading but the widget seems to work in some cases but not in others so we're not sure if it is a news.gc.ca issue.

**Comment by hsrudnicki** [comment]
Is this still an issue? Can be this closed or otherwise?
[here is a link to the open and closed issues for the plugin: feeds https://github.com/wet-boew/wet-boew/labels/Plugin%3A%20Feeds that may be useful ]
