### ISSUE TITLE
wet-boew-dist-4.0.19-2 - RSS Feeds still not working

### ISSUE THREAD

**Issue by afull** [wet-boew/wet-boew#7244]
Good afternoon,

We have downloaded the latest version of the latest version of the WET4 template (wet-boew-dist-4.0.19-2).

I am still unable to get our Department's RSS feeds to display on our development server.
Is there some additional code fix that I am missing?

http://news.gc.ca/web/fd-en.do?mthd=dpt&ft=atom&crtr.dpt1D=6672

When I view the Feeds demo page on GitHub, I do not see any results either.
http://wet-boew.github.io/wet-boew/demos/feeds/feeds-en.html

[feeds-EC.txt](https://github.com/wet-boew/wet-boew/files/51174/feeds-EC.txt)

**Comment by LaurentGoderre** [comment]
@andre-gh

**Comment by andre-gh** [comment]
If the demo is not working, it is possible your dept is blocking access to the yahoo api.  Just to verify, could you visit http://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20feed%20where%20url%20%3D%20%27http%3A%2F%2Fweather.gc.ca%2Frss%2Fcity%2Fon-118_e.xml%27%20limit%201&format=json&callback=jQuery214009418939403258264_1449387280755&_=1449387280756 and verify something loads?

**Comment by afull** [comment]
That appears to be the issue.
I will try to get this entry (query.yahooapis.com) un-blocked by our servers to see if this resolves the problem.

**Comment by andre-gh** [comment]
@afull Thanks, which dept are you with?  (For future reference in case I see this issue again)

**Comment by afull** [comment]
Sorry, I am with Environment Canada.

**Comment by afull** [comment]
Hey Andre,
I just noticed that our original RSS feeds (using WET-BOEW version 4.018) on the EC Homepage are suddenly working.

http://www.ec.gc.ca/default.asp?lang=En&n=FD9B0E51-1

Is the Google API functioning again?

**Comment by andre-gh** [comment]
I noticed that when I got in this morning.  Google may have turned the API back on for a period of time, I am not sure if/when it will go down again.

In my research I found that google started deprecating the API in May 2013 stating that the API would continue to function and that after April 2015 the deprecation policy would no longer apply and functionality could be removed.  Therefore, I can not recommend depending on the API for much longer as google could/might remove the API again like they did last week.

**Comment by afull** [comment]
HI Andre,

I got 'query.yahooapis.com' unblocked from our McAfee Web Gateway.

When I tested the link you added to this post, I was able to download and open a 'f.txt' file, that contains the following code;

/**/jQuery214009418939403258264_1449387280755({"query":{"count":1,"created":"2015-12-07T18:13:32Z","lang":"en-us","results":{"entry":{"title":"No watches or warnings in effect, Ottawa (Kanata - Orléans)","link":{"href":"http://www.weather.gc.ca/warnings/index_e.html","type":"text/html"},"updated":"2015-12-06T12:15:00Z","published":"2015-12-06T12:15:00Z","category":{"term":"Warnings and Watches"},"summary":{"type":"html","content":"No watches or warnings in effect."},"id":"tag:weather.gc.ca,2013-04-16:on-118_w1:20151206121500"}}}});

Unfortunately, the RSS is still not working for me.
This is the code we are using:

<section class="wb-feeds limit-3" id="headlines">
	<h2 class="">Headlines</h2>
	<ul class="feeds-cont list-unstyled">
		<li><a href="http://news.gc.ca/web/fd-en.do?mthd=dpt&ft=atom&crtr.dpt1D=6672">Environment Canada Headlines</a></li>
	</ul>
</section>

**Comment by andre-gh** [comment]
When I copy the code locally this appears:

![untitled](https://cloud.githubusercontent.com/assets/13316676/11636560/b8999428-9cea-11e5-9c41-a48155c81bcf.png)

Are you able to open the network inspector and find the request for me?  If you can tell me which browser you are in I can assist you.

**Comment by afull** [comment]
Strange, it suddenly started working but but now I am not getting the dates.

This is what I see.
<section class="wb-feeds limit-3 wb-init wb-feeds-inited" id="headlines"><h2 class="">Headlines</h2><ul class="feeds-cont list-unstyled feed-active"><li><a href="http://news.gc.ca/web/article-en.do?nid=1023779&amp;tp=1">Canada pledges $150 million to support renewable energy investments in Africa</a><br></li><li><a href="http://news.gc.ca/web/article-en.do?nid=1023649&amp;tp=980">Canada advocates for the inclusion of human rights language in the Paris Agreement</a><br></li><li><a href="http://news.gc.ca/web/article-en.do?nid=1023639&amp;tp=980">Minister McKenna taking action to protect the Western Chorus Frog in Quebec</a><br></li></ul></section>

I am using the following browsers, but the issue affects all of them so far.
- Internet Explorer v9.08112.16421 (we will be upgrading to v11 next month)
- Firefox 42.0
- Chrome 47.0.2526.73

**Comment by andre-gh** [comment]
My mistake, the above screenshot ran against the old google API codebase rather than the yahoo one.  After investigating it appears that the dates do not appear as the feed has no published date.  The feed only has an "updated" date which the yahoo api does not automatically normalize to the published date like the google api did.  The previous code only used published date as google's api apparently automatically converted "updated" to a published date if there was no published date.

Tomorrow I will update the code to include "updated" as the date if there appears to be no published date included, this should be included in a planned maintenance release next week.

**Comment by andre-gh** [comment]
Unfortunately the bug fix release is being moved to Wednesday, we have run into an issue we are trying to resolve before the release.

**Comment by afull** [comment]
Hey Andre,

Any news on if the bug fix for the new FEEDS went into the latest release?

**Comment by afull** [comment]
We have updated to version 4.0.2 and the web feeds look good again.
