### ISSUE TITLE
Tables: current implementations of wb-tables

### ISSUE THREAD

**Issue by eswright** [wet-boew/wet-boew#7245]
so is a sortable table already on canada.ca or one of our dept sites that I can look at?   I'm just trying to  figure out how we can post some regularly revised tables

**Comment by MaximMartel** [comment]
You can always us this : http://wet-boew.github.io/v4.0-ci/demos/tables/tables-en.html
I looking in canada.ca to find you a sorting table right now.

**Comment by hsrudnicki** [comment]
@eehret : Is it still an issue, waiting for more data tables details to resolve it?   Either way, please update this issue's status, whether this issue can be closed as resolved or otherwise?  Thank you

**Comment by eswright** [comment]
I still have not found a wet 4.0 sortable table implementation on canada.ca  , but I am assuming it can be done as I believe it is in wet 3.0...just appears not to have been implemented anywhere on nrcan.gc.ca
