### ISSUE TITLE
Details/summary styling issues

### ISSUE THREAD

**Issue by bsouster** [wet-boew/wet-boew#7275]
I understand some of these might be "this wasn't designed for this use-case" use-cases.

* No spacing between stacked details elements
* No spacing on inside-top and inside-right edges of details, causing content to flow right up to the details border (including paragraph text and alert background colours)
* Details/summary arrow is aligned-bottom and does not resize when summary text font-size changes (via headers (h2, h3, etc) and classes)
* Headers (h2, h3, etc) within details/summary have extra left-spacing, throwing alignment off with other elements like paragraphs
* Nesting details/summary within other details/summary causes issues with borders
* Borders of tables nested within details/summary flow outside of the container

Tested in: 
* Firefox 38
* IE11
* Chrome 44

Observed on:
* Internal web server
* WET online examples

**Comment by andre-gh** [comment]
Are these new issues with the latest WET4, or longstanding issues with the implementation.  Could you highlight which if these were not present in an earlier version of WET, and if so, which earlier WET version was correctly implemented?  We had some recent details/summary changes and I would like to target fixes for anything which may have broken with that restoring the functionality before altering the functionality of details/summary with new behavior.

**Comment by bsouster** [comment]
Some of these issues were not issues until a border was added:
* No spacing between stacked details elements
* No spacing on inside-top of details

Old and unresolved:
* Details/summary arrow is aligned-bottom and does not resize when summary text font-size changes (via headers (h2, h3, etc) and classes)
* Headers (h2, h3, etc) within details/summary have extra left-spacing, throwing alignment off with other elements like paragraphs

New:
* No spacing on inside-top and inside-right edges of details, causing content to flow right up to the details border (including paragraph text and alert background colours)
* Nesting details/summary within other details/summary causes issues with borders
* Borders of tables nested within details/summary flow outside of the container

**Comment by andre-gh** [comment]
I can not confirm the expected functionality for headers inside summaries at this time but I can fix the other issues in master.  

I will be making the following changes (although I need to verify things like the tabs small view and the side menu do not break with these changes, so I need a bit of time along with verifying how they functioned before and verifying chrome non-poly-filled works as expected):

1) Add a margin-bottom (.25em?) to details

2) Add a margin-bottom (.25em?) to the summary element inside an open details

3) Investigate issue with nested details borders and resolve, I believe changing "details[open] summary" to "details[open] > summary" will resolve the issue.

4) Use padding-left on details not margin-left on content and then use an inverted margin on the summary (Fixes `Headers (h2, h3, etc) within details/summary have extra left-spacing, throwing alignment off with other elements like paragraphs` as well as the table overflow and likely other content issues not yet found)

5)

**Comment by bsouster** [comment]
@andre-gh sorry for the delay. I'll test ASAP

**Comment by andre-gh** [comment]
@bsouster Thanks, if you have any issues or changes please be sure to get them to me by the morning of the 9th or 10th so that I can get them in the update on Monday.

**Comment by bsouster** [comment]
@andre-gh was it just CSS updates? I loaded up the CSS folder:
http://www.cic.gc.ca/test/dist/cic-content-en.html

**Comment by andre-gh** [comment]
@bsouster This is what the latest `master` GCWeb looks like http://wet-boew.github.io/themes-dist/GCWeb/demos/details/details-en.html  (notice the space between details)

The incorrect css is loading, the css you are loading there is v4.0.19+2 (at the top of the css in the comment), the css in the latest development build of gcweb (https://github.com/wet-boew/themes-dist/archive/GCWeb.zip) is labeled "v4.0.20-development - 2015-12-07"

**Comment by bsouster** [comment]
@andre-gh It looks great.

![same-example](https://cloud.githubusercontent.com/assets/1944744/11690893/b0287ac0-9e66-11e5-8a1e-825914e720bf.jpg)

**Comment by andre-gh** [comment]
@bsouster Excellent, I will do more testing and get it in the release on monday along with a small fix to how feeds plugin handles feeds without published dates but with an updated date, and a small unrelated fix to how various plugins handle a slash in the # of the url.

**Comment by andre-gh** [comment]
Unfortunately the bug fix release is being moved to Wednesday, we have run into an issue we are trying to resolve before the release.

**Comment by hsrudnicki** [comment]
@andre-gh @bsouster and others: Please update this issue's status whether this issue can be closed as already resolved/fixed based on the last comment or if otherwise?  Thank you

**Comment by bsouster** [comment]
I saw the fix is in v4.0.19. Looks great, @andre-gh Thanks for your help on this.
