### ISSUE TITLE
Validating fieldset when only textbox elements present

### ISSUE THREAD

**Issue by biljanap** [wet-boew/wet-boew#7283]
I have a situation where I am grouping 3 form elements in <code>fieldset</code>. They are all <code>input type=”text”</code> elements. I am grouping them in <code>fieldset</code> because either one of them is required to validate the form.
I am adding class=“required” to <code>legend</code> element. Form validation is not producing any errors for this fieldset. I don’t get errors in the list of errors and I don’t get error added to the legend tag. Validating on <code>fieldset</code> level seems to be working only if checkbox or radio are present.
...or I am doing something wrong?

**Comment by hsrudnicki** [comment]
Is this above still an issue, waiting for an answer? Either way, please update this issue's status, whether this issue can be closed as resolved or if otherwise?  Thank you

**Comment by hsrudnicki** [comment]
Is this still an issue? Please update the status of this for the current year, whether this can be closed or otherwise, thx

**Comment by biljanap** [comment]
This is still an issue. I think it would make sense to be able to validate any fieldset not just the ones containing radio buttons and check boxes. If I am isolated case that needs this functionality and there are no plans to fix this, please feel free to close the issue.

**Comment by hsrudnicki** [comment]
Based on the above, this can be closed, thank you

**Comment by biljanap** [comment]
I would like to reopen this issue because I have the exact same situation again. Any reason why we can validate `<fieldset>` only if check boxes/radio buttons and selects are present? Does anybody have a solution for this? Are there any plans to fix this?

**Comment by RobJohnston** [comment]
@biljanap :  You seem to be continuing this in https://github.com/wet-boew/wet-boew/issues/7936, and I believe that the [require_from_group-method](https://jqueryvalidation.org/require_from_group-method/) is what you want to leverage in this case.
