### ISSUE TITLE
Remove disable sorting arrow on multiple Table headers. 

### ISSUE THREAD

**Issue by JackDarth** [wet-boew/wet-boew#7285]
I have problem to remove the disable sorting arrows appear on irrelevance headers in table.  Does anyone know how can I remove those arrows circle red in the image below?
![capture](https://cloud.githubusercontent.com/assets/13342601/11689810/96d2fed8-9e61-11e5-8765-a5d1309a5413.PNG)

**Comment by hsrudnicki** [comment]
Is the above still an issue, waiting for an answer?  Either way, please update this issue's status whether this issue can be closed as resolved/closed or otherwise?  Thank you

**Comment by silentcanadian** [comment]
@JackDarth I was able to do something similar with one of my simpler datatables using the following to affect individual columns:
`data-wb-tables='{"columnDefs": [{"orderable": false, "targets": [2,3]}]}'`

**Comment by hsrudnicki** [comment]
Please update again the status of this, whether this can be closed or otherwise? Thx

**Comment by JackDarth** [comment]
Close
