### ISSUE TITLE
Geomap: jQuery 2.1.4 breaks the table on my site

### ISSUE THREAD

**Issue by upsonp** [wet-boew/wet-boew#7286]
I really don't know how to explain this concisely so you might have to tease some missing or complicated details out of me. It might not even be a GeoMap issue.

I was updating the WET-BOEW-PHP variant and updated the line including jQuery at the bottom of the footer to be consistent with the core WET demos. I was previously using version 2.1.0, which seems to work fine, but after updating the table under the map doesn't render correctly. I've swapped the jQuery version back to 2.1.0 and it works fine, then when back to 2.1.4 and it's broken.

Here's what it looks like in 2.1.4
![geomap](https://cloud.githubusercontent.com/assets/3355126/11692499/1c8247f0-9e76-11e5-8653-5d4515a828df.png)

And here's what it looks like with 2.1.0
![geomap2](https://cloud.githubusercontent.com/assets/3355126/11692508/29a876c0-9e76-11e5-96e8-f41a7ee38d99.png)

**Comment by andre-gh** [comment]
This demo is on 2.1.4 and appears correctly http://wet-boew.github.io/v4.0-ci/demos/geomap/geomap-en.html

Are there any errors in your development console?

**Comment by upsonp** [comment]
This is the error reported using 2.1.4, the error doesn't occur when using 2.1.0

![geo](https://cloud.githubusercontent.com/assets/3355126/11715286/0dade8a0-9f17-11e5-9ae5-f8be6adba75c.png)

**Comment by LaurentGoderre** [comment]
From a lot of article, this often occurs with AJAX when it expects a JSON object but instead receives a string

http://stackoverflow.com/questions/18460368/getting-typeerror-invalid-in-operand-obj-while-fetching-data-using-ajax

**Comment by hsrudnicki** [comment]
Can be this issue closed as resolved/fixed, based on the last comment, or is this above still an issue?
Either way, please update this issue's status, whether this issue can be closed or otherwise, thank you

**Comment by upsonp** [comment]
Yeah doesn't seem to be an issue any more.
