### ISSUE TITLE
Glyphicons and CDN

### ISSUE THREAD

**Issue by danpoleary** [wet-boew/wet-boew#7287]
We use a Java variant of WET that we developed, that uses CDN to get WET resources. The issue we have, is that if I am testing the application all locally in dev mode (No CDN used), then glyphicons display correctly, such as the arrows in the Breadcrumbs. But if I test locally in prod mode (Uses CDN), then the glyphicons show as boxes. If I deploy the app to a server, the same issue occurs between dev mode and production mode. Glyphicons only display if I do not use a remote server to supply WET resources (CDN).

Why is this occurring?

**Comment by LaurentGoderre** [comment]
Are the glyphicon fonts being served from the servers? Did you check on the network log of your browser to make sure the font was loading properly?

**Comment by danpoleary** [comment]
Fonts are loading properly, I can use the developer tools to view network, and the CSS, and see that the fonts are loaded. If I load the demo/example pages from the downloaded WET, boxes appear, but if I view the demo/examples right on github, the boxes appear.

**Comment by LaurentGoderre** [comment]
Did you mean to close?

**Comment by danpoleary** [comment]
Nope, sorry, to quick on the click :-)

**Comment by LaurentGoderre** [comment]
Maybe they're being blocked because of CORS.....

**Comment by hsrudnicki** [comment]
Can be this issue closed as resolved/fixed or if otherwise?  Please again update this issue's status, thank you

**Comment by hsrudnicki** [comment]
Is this still an issue? Please update the status of this for this current year, thx

**Comment by masterbee** [comment]
closing since the caller's (creator of issue) appears to have abandoned the issue.
