### ISSUE TITLE
Persist Toggle State demo is broken

### ISSUE THREAD

**Issue by hub-c** [wet-boew/wet-boew#7292]
If I add `class="wb-toggle" data-toggle='{"persist": "session"}` to a details element, it will no longer work when clicked.

This happens also on the Persist Toggle State demo at http://wet-boew.github.io/wet-boew/demos/toggle/toggle-en.html#persist . All other examples on page work properly.

(Tried in Firefox, Chrome and Safari on Mac)

**Comment by andre-gh** [comment]
yeah, I think I see what caused this (d896b8bcabbfe9cb3461dadbcf58a185bd001360), I will fix this and get it in before the bug fix release today.

**Comment by andre-gh** [comment]
It may not be that though, I also see something odd going on with the on/off state being on the details vs being on the summary.  I will look into this.
