### ISSUE TITLE
Form validation: Is the formatting optional?

### ISSUE THREAD

**Issue by juliemercier** [wet-boew/wet-boew#7295]
I am responsible for ensuring that our team's applications meet WET4 requirements. For the form validation, I was pushing our team to adopt the WET4 form validation including its formatting. However, I was looking at the Welcome to GCKey Form validation screen on Canada.ca (https://clegc-gckey.gc.ca/j/eng/l?ReqID=s265fd44b15d1422a6d932beb46d514c227bffeab3) and see that it does provide the message list at the top, it does have the field level messages and it does have the word required for labels where the input is required. But the formatting is not the same. The word required is not red and there is no asterisk. The message list at the top and the field level error messages are not in an alert with a red bar on the left and a pale red background. Does that mean that we do not need to apply this WET4 formatted version of the form validation? I also reviewed the Application for EI and it is completely different than the other 2.  I thought the idea was to keep the look and feel consistent across all government website pages and apps? If there is some leeway in how we apply the WET4 standards? Or is the WET4 form validation example still the one we should be aiming to achieve? Thank you.
![gckey](https://cloud.githubusercontent.com/assets/7468426/11790243/b06b6262-a268-11e5-847e-6d478ee09fff.PNG)
![wet4validation](https://cloud.githubusercontent.com/assets/7468426/11790264/db575b5c-a268-11e5-95e3-b0c8a5b4820b.PNG)

**Comment by LaurentGoderre** [comment]
I believe the first one is incorrectly implemented.

**Comment by neoinsight** [comment]
@juliemercier The form validation examples are the ones you should be aiming to achieve. We have been updating (or submitting issues to update)  those examples to reflect usability testing findings during the last year.

**Comment by juliemercier** [comment]
Thank you.
