### ISSUE TITLE
"No file selected" label needs translation 

### ISSUE THREAD

**Issue by biljanap** [wet-boew/wet-boew#7296]
"No file selected" label found on Form validation page is not translated on French version of this page.
<a>http://wet-boew.github.io/v4.0-ci/demos/formvalid/formvalid-fr.html</a>

**Comment by andre-gh** [comment]
That text comes directly from your browser and changes with the language setting of your OS/Browser and can not be implemented by WET.

**Comment by biljanap** [comment]
ok, thanks :o(
