### ISSUE TITLE
Multiple http request while the page is interacted with

### ISSUE THREAD

**Issue by GabrielVautour** [wet-boew/wet-boew#7298]
On a project I am currently working on, I use modal popups (jquery.validate.min.js) and forms validation (jquery.magnific-popup.min.js) and noticed that in one single session, each associated plugin (.js) file was loaded (via http request) multiple times, once for each use of the plugin.

![15-12-2015 1-42-54 pm](https://cloud.githubusercontent.com/assets/16308494/11820518/0391d3e8-a333-11e5-8890-49b6190d8c6f.png)

I do trigger "wb-init.wb-frmvld" every time I open a new modal window since it contains a form that is built dynamically and needs to be reinitialized, but I didn't expect it to do another http request for the source files.

The same happens when I open a modal popup which is never removed from my page, but the content inside is changed depending on user interaction, then opens and closes accordingly. There is also another file (additional-methods.min.js) that is loaded multiple times.

Is this simply the way the wet-boew framework was designed?

**Comment by LaurentGoderre** [comment]
This is a mix of how WET works and how yepnope work. Both require propper caching of resources to avoid sending the data multiple times for the same file.

**Comment by hsrudnicki** [comment]
Is this above an issue?  Either way, please update this issue's status, whether this issue can be closed as resolved/fixed or if otherwise?  Thank you
