### ISSUE TITLE
Charts and graphs: represent 'No data' values

### ISSUE THREAD

**Issue by upsonp** [wet-boew/wet-boew#7300]
I was wondering if there's currently a way to represent "no data" values in a graph. I have a bunch of locations with significant wave heights, current summer/winter and projected summer/winter, but some times there is no current summer, or current winter, or projected summer, or projected winter, maybe two of the four or three of the four values.

My client would just like "No data" to show in the table when that happens, but there's no way I can see to exclude that row from the graph. Putting in "No data" messes up the graph. Is there a tag attribute I could put in so the plugin knows to exclude a row?

**Comment by soatley** [comment]
I'm working on something right now to exclude certain columns out of a graph by adding a class to the column.  I should have something in about a week and will update this when it's ready.  It's working right now but it needs to be tested first.

**Comment by upsonp** [comment]
That's awesome, thanks @soatley

**Comment by soatley** [comment]
In the `series: {}` object inside `createCharts`, I added the following option:
```
                       none: {
                           base: "none",
                           none: { show: false }
                       }
```

This allowed me to put `wb-charts-none` in the `<th>` element for each column I did not want to display.

Then, back in the wet-boew JS file, look for the for loop in `createCharts` that counts the number of bars:
```
   // Count the number of bar charts,
           for (i = 0, iLength = dataGroupVector.length; i !== iLength; i += 1) {
               currentDataGroupVector = dataGroupVector[i];
               currDataVector = currentDataGroupVector.header[currentDataGroupVector.header.length - 1];

               // Apply any preset
               currVectorOptions = applyPreset(defaultsOptions.series, $(currDataVector.elem), "flot");
                   if (currVectorOptions.bars || (optionFlot.bars && !currVectorOptions.lines)) {
                     ....
                   }
```

In between the `currVectorOptions` and the `if (currVectorOptions.bars..` and add in 
```
               if (!currVectorOptions.none) {
```
and then don't forget to close off the loop after the currVectorOptions.bars if statement.  So far, I'm only using this for bar graphs so you may need to do some other work for different graph styles.

**Comment by upsonp** [comment]
It'll be nice to expand this to other graphs later, but I think it's a good solution for the Bar charts.

**Comment by hsrudnicki** [comment]
@upsonp and others: Can be this issue closed as resolved/fixed, based on last comment from @soatley or if otherwise?  Either way, please update this issue's status, thank you

**Comment by upsonp** [comment]
I'm happy it's something that's coming at the very least. I haven't looked in to using @soatley suggestion, but I'll prod again if it persists as an issue.

**Comment by oevad** [comment]
It's good that this "wb-charts-none" option exists.  Is this meant to be official? It is not documented in [Charts and graphs documentation](https://wet-boew.github.io/v4.0-ci/docs/ref/charts/charts-en.html).  
There is a bug when using this.  The suppressed column appear in the auto-generated legend.  This is the code:

```
<table class="wb-charts table"  data-wb-charts='{ "reversettblparsing": true }'>
	<thead>
		<tr role="row">
			<th>Period start date</th>
			<th class="wb-charts-none">Period start time</th>
			<th class="wb-charts-none">Period end date</th>
			<th class="wb-charts-none">Period end time</th>
			<th class="wb-charts-bar">Sulfur dioxide</th>
			<th class="wb-charts-none">Flag</th>
			<th class="wb-charts-bar">Calcium, ion (Ca2+)</th>
```
