### ISSUE TITLE
Form validation plugin and Single Page Applications

### ISSUE THREAD

**Issue by UncleZen** [wet-boew/wet-boew#7306]
I have been using the Form Validation plugin successfully in many applications. 

However,  the validation summary links (e.g. http://wet-boew.github.io/wet-boew/demos/formvalid/formvalid-en.html#tel1) in a SPA (Single Page Application) are interfering with routing implementation, which as you may know is controlled by the URL hash, e.g http://myserver/myapp/**#/view1/action1**.

Is it possible to change the way the validation summary links behave? 

Thanks!

Zen

**Comment by andre-gh** [comment]
I have two reccomendations based on my previous experience with single page webapps in wet:

I handled this kind of thing internally in my single page webapps my having a single click handler for all links, and in the event of a click to something which was not my router I avoided updating the url and just scrolled to the element manually and focused it.

After a while of getting fed up with that though, I realized that IE10 and up support the HTML5 history api so I used that with real URLs and ditched the fragment (hash) based URLs all together.  If your single page webapp does not need to support IE9 I highly recommend this.

**Comment by UncleZen** [comment]
Thanks André!

**Comment by hsrudnicki** [comment]
@UncleZen : Can be this issue closed as resolved/fixed, based on last comment from @andre-gh or otherwise?  Either way, please update this issue's status, whether this issue can be closed or otherwise, thank you

**Comment by UncleZen** [comment]
@hsrudnicki : Although I have not tested the @andre-gh approach yet, HTML 5 history API is definitely a way around this issue. The only problem is that IE 9 does not support HTML 5 History API.

**Comment by LaurentGoderre** [comment]
Is IE9 important to your app? WET drop it's support of it a while ago.

**Comment by hsrudnicki** [comment]
@UncleZen : Is this still an outstanding issue? Either way, please update this issue's status again, thank you

**Comment by hsrudnicki** [comment]
Can be this issue closed or otherwise?  Please update the status of this again, thx

**Comment by hsrudnicki** [comment]
Based on the above, this can be closed, If you think otherwise, please update the status of this again, thank you
