### ISSUE TITLE
Geomap: changing the base map

### ISSUE THREAD

**Issue by Bgolden67** [wet-boew/wet-boew#7311]
Can the basemap being called be changed to point to a custom one?
Is it changed in the js  or config file or part of the in page code?

**Comment by hsrudnicki** [comment]
Is the above still an issue, waiting for an answer?  Either way, please update this issue's status, whether this issue can be closed or otherwise? Thank you

**Comment by jvanulde** [comment]
@Bgolden67  it can be changed to anything you like via the config file. You will see in the demo config that a basemap object sample has been provided. Please let me know if you need further assistance.

**Comment by hsrudnicki** [comment]
@Bgolden67 and others: Can be this issue closed as resolved, based on last comment from @jvanulde or if otherwise? Thank you

**Comment by jvanulde** [comment]
@hsrudnicki please close this issue.
