### ISSUE TITLE
ARCHIVED - Archiving content: 

### ISSUE THREAD

**Issue by Mass45** [wet-boew/wet-boew#7315]
Hi, it's Mass45. I wrote a question yesterday and I think my explanation was not clear enough, since I think it's the way Drupal automatically inserts the Archived box.
Anyway, I have a clear question this time: I want to link to a document that has been archived. Before we inserted in the link the word "Archived - " . Now I see that some use only <span class="label label-warning">Archived</span> after the link, as shown on page http://www.tbs-sct.gc.ca/ip-pi/reports-rapports/index-eng.asp.
Is this the way we do it now?

**Comment by pjackson28** [comment]
Yes, the requirement to archived at the end of the link text is describe here: http://www.tbs-sct.gc.ca/ws-nw/mo-om/ts-st/p9-eng.asp.

**Comment by Mass45** [comment]
Thank you very much Paul. I was trying to find the information in the Github Web Experience Toolkit pages.

Christian Massicotte
StatCan

Date: Wed, 6 Jan 2016 09:07:00 -0800

**Comment by hsrudnicki** [comment]
Based on the above, this issue can be closed as resolved.
[If you strongly think otherwise, please update this issue's status again. Thank you]
