### ISSUE TITLE
Broken download link

### ISSUE THREAD

**Issue by grapeape69ca** [wet-boew/wet-boew#7316]
I was trying to download the production v4.020 base from http://wet-boew.github.io/wet-boew/docs/versions/dwnld-en.html, but the link 404s:

https://github.com/wet-boew/theme-base/releases/download/v4.0.20/themes-dist-4.0.20-theme-base.zip

Tried in the latest Firefox and Chrome browsers.

**Comment by LaurentGoderre** [comment]
@andre-gh

**Comment by andre-gh** [comment]
Thanks, fixed
