### ISSUE TITLE
Un-Ordered list layout issue, cannot use "colcount" and "checkbox-inline" css together.

### ISSUE THREAD

**Issue by seguinrs** [wet-boew/wet-boew#7317]
Un-Ordered list layout issue, cannot use "colcount" and "checkbox-inline" css together.

The css "colcount-xl-2" has no impact on the layout "checkbox-inline" seems to override.

Here is a code example:
![untitled](https://cloud.githubusercontent.com/assets/14113912/12123780/d69c73c8-b3b0-11e5-8bf5-21698dc5b9c4.png)

```html
<ul id="ctl00_ContentPlaceHolder1_c1_cblTypeService" class="colcount-xl-2 list-unstyled  checkbox-inline mrgn-lft-lg">
    <li><input id="ctl00_ContentPlaceHolder1_c1_cblTypeService_0" type="checkbox" name="ctl00$ContentPlaceHolder1$c1$cblTypeService$0" /><label for="ctl00_ContentPlaceHolder1_c1_cblTypeService_0">Aerial advertising</label></li>
    <li><input id="ctl00_ContentPlaceHolder1_c1_cblTypeService_1" type="checkbox" name="ctl00$ContentPlaceHolder1$c1$cblTypeService$1" /><label for="ctl00_ContentPlaceHolder1_c1_cblTypeService_1">Aerial construction</label></li>
</ul>
```

**Comment by hsrudnicki** [comment]
Is the above still an issue, waiting for a response to help resolve the css?
Either way, please update this issue's status, whether this issue can be closed or otherwise, thank you

**Comment by hsrudnicki** [comment]
Can be this issue closed or otherwise?

**Comment by cybersubtype** [comment]
Where are you getting `colcount`? Are you referring to [column-count](http://www.w3schools.com/cssref/css3_pr_column-count.asp)? If so WET wouldn't support it has not backwards compatible.

**Comment by LaurentGoderre** [comment]
It's included in the styleguide. Not sure why it's not working for you https://wet-boew.github.io/wet-boew-styleguide/v4/design/lists-en.html#columns

**Comment by LaurentGoderre** [comment]
Oooh but it's only meant for plain lists, not lists with form controls.

**Comment by kodecount** [comment]
@LaurentGoderre The issue is [Line 291](https://github.com/wet-boew/wet-boew/blob/f5f33e0240649fe22fd12f28978113841762bffa/src/base/proximity/_base.scss#L291) which I think can be safely remove.

**Comment by kodecount** [comment]
@seguinrs Until the issue is fix (if it is fixed) you can manually override this class:

```css
[class*=colcount-].list-unstyled li {
    margin-left: inherit;
}
```

**Comment by kodecount** [comment]
@LaurentGoderre @seguinrs I started the pull request to fix this.
