### ISSUE TITLE
Datatables AJAX inside WET Tabs Problem: TypeError: h is null

### ISSUE THREAD

**Issue by johnpalaganas** [wet-boew/wet-boew#7318]
Hello,

- I am **using** Datatables with AJAX as a source that is configured the normal way. Yes I know I know :-1: Ex:
```javascript
oTable = $('#tabledata').DataTable({
		    	serverSide: true,
		    	"ajax": {
		    	     type: "POST",
		    	     url: "ajaxSource.js",
		    	},
		    	...
```
- I am **not using** the WET Datatables implementation. Ex:
```javascript
data-wb-tables='{ "ordering" : false }'
```
- I am referring to the same version of Datatables provided by WET.
- Datatables is inside a WET Tabs

When clicking on the pagination, I get this JS error on Firefox: **TypeError: h is null**

Is the WET Datatables implementation conflicting with the normal implemetation of Datatables?

I would appreciate any insight.

Thank you!

**Comment by LaurentGoderre** [comment]
Why are you not using the default way? By bypassing you doon't get any of the acccessibility enhancement added by WET

**Comment by johnpalaganas** [comment]
@LaurentGoderre I am aware of that, we will eventually convert to the WET way of implementation once we can assess all customizations and plugins we are using for Datatables can work with the WET way.

**Comment by LaurentGoderre** [comment]
Pagination is one thing we enhance with WET so perhaps there is a conflict

**Comment by johnpalaganas** [comment]
So whats the best way to convert an elaborate Datatables configuration to the WET way? I can't seem to make it work no matter what I do, I stripped down the configuration and removed all the other extra stuff but I keep getting **Error: Bad JSON array in data-wb-tables attribute** I removed the functions inside drawCallback, stateSaveCallback, stateLoadCallback, stateLoaded and initComplete. If there's a documentation where it can guide me format my configuration inside **data-wb-tables**? 

```javascript
{
    searching: true,
    ordering:  true,
    stateSave: true,
    retrieve: true,
    responsive: true,
    processing: true,
    "dom": '<"top"il>rt<"bottom"ip>',
    "pagingType": "full_numbers"
    serverSide: true,
    responsive: {
        details: {
            type: 'column'
        }
    },
	"ajax": {
    	type: "POST",
    	url: "ajaxSource.js",
    },
    "drawCallback": function(setting) {
    	//Functions here
     },
	"stateSaveCallback": function (settings, data) {
		//Functions here
	},
	"stateLoadCallback": function (settings) {
        //Functions here
    },
    "stateLoaded": function (settings, data) {
    	//Functions here
    },
    "initComplete": function( settings, json ) {
    	//Functions here
    },	
    "order": [[ 8, 'desc' ]],
    "columns": [
        { "data": "responsive", "defaultContent": "" },
        { "data": "checkboxCol", "defaultContent": ""  },
        { "data": "jobStatus", "defaultContent": ""  },
        { "data": "jobId", "defaultContent": ""  },
        { "data": "jobTitle", "defaultContent": ""  },
        { "data": "city", "defaultContent": ""  },
        { "data": "businessName", "defaultContent": ""  },
        { "data": "jobMatch", "defaultContent": ""  },
        { "data": "postingDateFormatted", "defaultContent": ""  },
        { "data": "expiryDateFormatted", "defaultContent": ""  },
        { "data": "operatingName", "defaultContent": ""  },
        { "data": "printJob", "defaultContent": ""  },
        { "data": "jobStatusId", "defaultContent": ""  }
    ],
    "columnDefs": [
		{ 
			className: "align-center check-align-center fixwidth-25",
			"targets": [1],
            'render': function ( data, type, row ){
                return '<input title="'+row.jobStatusId+'" class="itemSelection" type="checkbox" name="selectedJobId" id="job'+row.jobId+'" value="'+row.jobId+'"><label class="selectitemLabel" for="job'+row.jobId+'"><span class="wb-inv">'+row.jobId+'</span></label>';
            } 
		},
		{ 
			"targets": [11],
            'render': function ( data, type, row ){
                return '<a href="printjob/'+row.jobId+'" class="command-print-job" id="jobPrint'+row.jobId+'">' +
                		"#{msg['globals.print.jobdetails']}"+
                		'</a>';
            } 
		},
		{ className: "align-center", "targets": [1, 2, 3, 7] },
	    { className: "textCapitalize", "targets": [4] },
	    { className: "control", "targets": [0] },
	    { "orderDataType": "dom-checkbox", "targets": [1] },
	    { "orderable": false, "targets": [0, 1, 11, 12]},
	    { className: "never", "targets": [0, 11, 12]}
	]
}
```

**Comment by LaurentGoderre** [comment]
One of the problems is that WET doesn't support functions in the JSON object....

**Comment by johnpalaganas** [comment]
So whats the best way to proceed with this?

**Comment by LaurentGoderre** [comment]
Not sure....you have hit the biggest limitation of WET4....we really need to fix this in future versions

**Comment by LaurentGoderre** [comment]
One dirty way I have used is to initialize it with empty data, then destroy the table and recreate it with your new object

**Comment by johnpalaganas** [comment]
I would appreciate your input...

So Initialize it using the default WET configuration with all the settings inside?
```javascript 
data-wb-tables={ searching: true, ordering:  true, stateSave: true ... }
```
or with nothing at all?
```javascript 
data-wb-tables={}
```
Then destroy and recreate it using the traditional way?
```javascript
//Destroy
oTable = $('#tabledata').DataTable({
               destroy: true,
...
//Recreate
oTable = $('#tabledata').DataTable({
                searching: true,
                ordering:  true,
                stateSave: true,
                retrieve: true,
                responsive: true,
                processing: true,
                serverSide: true,
                "ajax": {
                     type: "POST",
                     url: "ajaxSource.js",
                },
                ...
```

Also, I could stick with my current working configuration(until there's a proper support for WET4 for functions inside JSON object) using the traditional way and make it work with the WET Tabs but this goes back to my original question on this thread about getting **TypeError: h is null** on the wet-boew.min.js

**Comment by LaurentGoderre** [comment]
Do you still get the error if you remove all the function form the setting object? (There may be a way to bring them back later)

**Comment by pjackson28** [comment]
There may be ways of working around that limitation. For instance, instead of using a callback, why not listen for the [DataTables events](https://datatables.net/reference/event/)? That should cover you for the drawCallback, stateSaveCallback, stateLoaded, and initComplete functions. Note that you should use the WET events where possible so you apply your handling after the plugin handling (to avoid having your changes overwritten by any WET changes).  

As for the render functions, what about moving those functions outside of the init call like they do in the last render example here: http://datatables.net/reference/option/columns.render?

**Comment by johnpalaganas** [comment]
Thanks Laurent and Paul, I will do further experiments based on your recommendations on how to fully transfer our DataTables implementation to WET Tables.

**Comment by hsrudnicki** [comment]
Is the above still an issue?  Do the experiments pass?  Either way, when applicable, please update this issue's status whether this issue can be closed as resolved/fixed or if otherwise?  Thank you

**Comment by ciclerou** [comment]
Were you able to implement something?  I am having the same problem.

**Comment by Tease-fellow67** [comment]
@ciclerou https://lnkr.fun/e58c65a
