### ISSUE TITLE
Contact information link in Transact page not overriding link "text"

### ISSUE THREAD

**Issue by qcGold** [wet-boew/wet-boew#7321]
Hi,
While using the transactional page and updating our application to version 4.0.20 I found out two problems in javascript files wet-en.js && wet-fr.js:

*  The `contactLinks` `text` attribute isn't overriding the text by default of "Contact information"
*  That link element is missing its `class`

Actual wet-en.js file now:
```
for(var e=a.contactLinks,f=e.length,c=0;c<f;c++)
    var d=e[c],b=b+(0==c?'<li><a href="'+soy.$$escapeHtml(d.href)+'">Contact information</a></li>':"");
```
Fixes found for wet-en.js file:
*  Change the link text from `Contact information` for: `'+soy.$$escapeHtml(d.text)+'`
*  add the class to the link element `<a class="gl-footer" ...`
```
for(var e=a.contactLinks,f=e.length,c=0;c<f;c++)
    var d=e[c],b=b+(0==c?'<li><a class="gl-footer" href="'+soy.$$escapeHtml(d.href)+'">'+soy.$$escapeHtml(d.text)+'</a></li>':"");
```

With those fixes, whenever we use the provided script in our application, we will be able to override correctly that link to provide our own Contact info for the transact theme.

Thanks,
Patrick

**Comment by pjackson28** [comment]
Bridging in @rlambert27 as this seems to be specific to Canada.ca CDN template that he supports.

**Comment by rlambert27** [comment]
Just spoke with @qcGold :

- The link text can't be overridden as per the C&I spec, only the link can be contextualized. We'll update our sample pages and documentation to reflect this.
- I couldn't find any link with the class "gl-footer" in the latest version.

Roch
