### ISSUE TITLE
opening links files from a doc on a local disk via intranet

### ISSUE THREAD

**Issue by marieeved** [wet-boew/wet-boew#7323]
Hi,

Do you know how to open links that are inside a document (this doc is on a shared local disk, a "CDS"). 

I make a link to this document on my html page (and it works, I can open the document on the browser), but the links inside this doc doesn't work. but these links work if I open the document directly from the shared local disk.

I also notice that the system had "file://" before my links. 

Is it a way to do that? I have to use an other protocol?
thank you.

**Comment by LaurentGoderre** [comment]
Probably because the links inside the doc are relative and not absolute

**Comment by marieeved** [comment]
Link example : 
\\hrdc-drhc.net\QC\CROU-REOC\_Public\Intranet\Français\20150630 - Références - FR.doc

**Comment by LaurentGoderre** [comment]
Looks like a relative link, the share drive part doesn't seem to be there

**Comment by marieeved** [comment]
I assumed that "hrdc-drhc.net" was the server. So, in this case, the link is absolute, no?

and if I add myself the "file:\\" before the link "hrdc..." in the adress bar when I add a hyperlink in the doc Word, it does the same thing. it works on the CDS, but not when I passed through the intranet.

**Comment by marieeved** [comment]
and how can I find it? 
in the Windows explorer, before hrdc-drhc, it written "network". there is nothing else.

**Comment by LaurentGoderre** [comment]
you could try: file:///hrdc-drhc.net/QC/CROU-REOC_Public/Intranet/Français/20150630 - Références - FR.doc

**Comment by LaurentGoderre** [comment]
oops:
file://hrdc-drhc.net/QC/CROU-REOC_Public/Intranet/Français/20150630 - Références - FR.doc

**Comment by marieeved** [comment]
with this one, it works only if I open the doc on the CDS, but not if I open the doc via my html page.

**Comment by LaurentGoderre** [comment]
try the second one

**Comment by marieeved** [comment]
I spoke of the second.

**Comment by marieeved** [comment]
me too

**Comment by LaurentGoderre** [comment]
what happens if you paste it in a browser windows?

**Comment by marieeved** [comment]
it works.

**Comment by LaurentGoderre** [comment]
Then it probably a security settings in Word or something, if the URL is valid but wont work from within Word

**Comment by marieeved** [comment]
is it because the people who created the doc secure it (it is impossible to write/modify the doc for users)?

(and the doc Word is save as a pdf (only the pdf is accessible for users))

**Comment by LaurentGoderre** [comment]
I don't know....

**Comment by marieeved** [comment]
ok, well, thanks for the information/support. then, I will have to propose an other solution...
