### ISSUE TITLE
Usability: Contacts/Footer not found in Hamburger Menu

### ISSUE THREAD

**Issue by neoinsight** [wet-boew/wet-boew#7325]
Over several rounds of usability testing, we have seen mobile phone participants scroll to the bottom of the page to look for Contacts. They try to find it everywhere except in the Hamburger menu. The fact that they are on a mobile device doesn’t change their expectation about footers at the bottom. 

Examples & video clip:  https://youtu.be/QkI5RdRD2oU
R5 P2: “I would look to the bottom for a contact”
R5 P8: “For mobile, it’s just the natural thing to do, to just flick (to the bottom), because it’s fastest”
R6 P18: “I’ll just look down there… (back up to top – looks at hamburger menu) ...No, that’s just the main menu, I don’t think that would be useful.”

The current design breaks with convention - most responsive sites maintain the footer in mobile widths. Thus this behaviour will not change/improve on WET sites. 

Recommend: Need to create a lightweight footer (for example, just the headings) or simply display the entire footer  at the bottom of the mobile view. 
Discussed with @pcwsmith and @dk-knight.

**Comment by LaurentGoderre** [comment]
Unfortunate because on some of our page, that means a LOT of scrolling

**Comment by neoinsight** [comment]
@LaurentGoderre True, but they 'flick' as seen in the video.

**Comment by LaurentGoderre** [comment]
Yeah, that's an extremely small page

**Comment by neoinsight** [comment]
@LaurentGoderre Good point, not saying we couldn't ALSO keep it in the hamburger menu for the 'accidental' finds that I've seen with mobile participants. But this research finding was too powerful to ignore, happened again and again.

**Comment by LaurentGoderre** [comment]
I'm not arguing not to do it but this is an argument for not having long pages

**Comment by andre-gh** [comment]
Is there any argument for just putting it in both places?  As a user I am trained to go to the footer to find contact info and only if I discover I am on an infinite scrolling page do I then check stuff like a sidebar, sidebars are mostly accessed by me for navigation.  As a user, I would think it would be good to just put them in both locations.

**Comment by neoinsight** [comment]
@andre-gh No argument, see above where I said it could also stay in the main hamburger menu at least temporarily. Would want to watch analytics over time though - if it gets no use there in mobile, then it should be removed to reduce complexity and improve ease of use for the main menu items. Clutter is an enemy of usability.

**Comment by hsrudnicki** [comment]
Is the above still an issue, waiting for your consensus/a decision?  Either way, please update this issue's status, whether this issue can be closed as resolved/fixed or if otherwise, thank you

**Comment by pcwsmith** [comment]
Hey everyone, we're doing some design thinking on our side, reacting to and integrating @neoinsight's ... insights. In addition to the idea of putting it at the bottom of the page, we're looking at the analytics and toying with the idea of slimming down the number of links in the footer as well. More news soon!

**Comment by DK-TBS** [comment]
I wholeheartedly support the idea of keeping the footer links in *both* the bottom footer and the mobile menu.  Duplication and clutter aren't great, but... we know that people look for footer links at the bottom, and we can be sure that some people have already learned to look for those in the mobile menu.  The duplication shouldn't really cause any damage in the short term, and usage stats will give us a more solid answer in the long term...

**Comment by neoinsight** [comment]
Usability testing of the new footer approach outlined in the Content and IA spec was successful - all of the 10 mobile participants found the footer on the page (items are also in the menu). Closing this issue.
