### ISSUE TITLE
HTML5 input type=date and associated label question

### ISSUE THREAD

**Issue by robwloch** [wet-boew/wet-boew#7329]
On the WET4 examples form validation page there is this classic datepicker example:

![4github](https://cloud.githubusercontent.com/assets/5721679/12247578/982292d6-b882-11e5-903a-02519c93354c.PNG)

If the browser has a native datepicker like Chrome does then apparently the format asked for is based on the end user's locale. So, our label dictates YYYY-MM-DD but the user may be shown something that conflicts with the label such as mm/dd/yyyy.

Just wondering if you happen to have a solution to this problem?

I've only just started looking into it this afternoon so thought I'd raise it. Unfortunately, at work we only have IE and FF which don't have native datepickers so can't test much here.

Thank you!

**Comment by andre-gh** [comment]
https://github.com/wet-boew/wet-boew/issues/1170#issuecomment-17320174 is the best solution at this time

**Comment by LaurentGoderre** [comment]
I am wondering if we can add CSS to hide the format if the polyfill is not shown?
 
What do you think @pjackson28?

**Comment by pjackson28** [comment]
@LaurentGoderre It already exists with the class <code>.datepicker-format</code>. It is defined here: https://github.com/wet-boew/wet-boew/blob/master/src/polyfills/datepicker/_base.scss#L5-L7

**Comment by pjackson28** [comment]
Note that the class is already in use in the form validation demo and the date picker polyfill demo.

**Comment by LaurentGoderre** [comment]
So @robwloch did you wrap the format in a span with the `datepicker-format` class?

**Comment by robwloch** [comment]
Thanks guys!

@LaurentGoderre , I managed to test it on my Mac and iPhone this morning and it appears to be working great. The only thing we need to worry about now is our error messages because we do server-side error handling so need to make sure we don't specify the format in the error msg text.

**Comment by LaurentGoderre** [comment]
If you did, you can wrap it in the same class

**Comment by robwloch** [comment]
That's true, good call!

**Comment by LaurentGoderre** [comment]
Can we close then?
