### ISSUE TITLE
wb-menu Colour

### ISSUE THREAD

**Issue by DHaslip** [wet-boew/wet-boew#7330]
Between v.4.0.18 and v4.0.19, it appears that the colour of the summary item in the mobile menu has been changed to white, which makes it more difficult to read.  Here is the CSS from theme.css:

.wb-menu details summary, .wb-menu details[open] summary {
    border: 0 none;
    color: #fff;
}

And here is how the mobile menu appears:

![wbmenu](https://cloud.githubusercontent.com/assets/4837220/12266825/324dd10a-b913-11e5-998c-21cec2be1236.png)

Is this what the menu is expected to look like?

**Comment by LaurentGoderre** [comment]
@andre-gh was this fix? I think it was

**Comment by andre-gh** [comment]
This was resolved, @DHaslip can you confirm you are no longer experiencing this issue?

**Comment by DHaslip** [comment]
I just tried on this page, and it still has the problem:

http://wet-boew.github.io/themes-dist/theme-gcwu-fegc/content-secmenu-en.html

**Comment by andre-gh** [comment]
It looks like the fix resolved the issue for gcweb only and should have defaulted to black with an override with white for gcweb.

**Comment by LaurentGoderre** [comment]
Why did you reopen?

**Comment by DHaslip** [comment]
The issue is not resolved for the usability theme.

**Comment by LaurentGoderre** [comment]
Won't the theme inherit this?

**Comment by DHaslip** [comment]
It doesn't on this page:

http://wet-boew.github.io/themes-dist/theme-gcwu-fegc/content-secmenu-en.html

**Comment by LaurentGoderre** [comment]
Yes, it doesn't automatically sync up. I restarted the theme build and it should pick up the change

**Comment by DHaslip** [comment]
So it will be fixed in v4.0.21?

**Comment by LaurentGoderre** [comment]
Yes

**Comment by DHaslip** [comment]
Great, so this can be closed.

**Comment by andre-gh** [comment]
Alright, looks fixed
