### ISSUE TITLE
Tabbed Interface: Form Elements Redrawn

### ISSUE THREAD

**Issue by denis-tessier** [wet-boew/wet-boew#7334]
I attempted to replace a Bootstraps tab interface with the WET version of the tabbed interface, but when I did that, I noticed that it was causing a lot of problems in the supporting JavaScript file for the concerned application, mostly with all jQuery triggers failing. When the WET JavaScript converts the Details \ Summary tags into a tabbing system, it appears that the elements contained within the details tag are being redrawn which makes them lose all of their bindings, which causes all triggers to fail because they don’t even exist anymore at that point. All the events seem to be removed. I looked into using the elements’ parents to bind the triggers to the elements to be able to complete the update, and it is working to a certain extent, but it is causing a lot of issues and would be hard to resolve all the issues arising from the WET tabbed interface update this way. 

For example - The following line from the supporting JavaScript file works perfectly when using the Bootstraps tab interface, but does not trigger at all when I replace it with the WET tabbed interface:  

$('#text-input-id').on('change', function(e) { 

However, it works with both Bootstraps and WET tabbed interface if I change it to this:

$('#parent-div-id').on('change', '#text-input-id', function(e) {

I have gone back to the Bootstraps tab for now, but was wondering if there is something I may not be setting up right which could be causing this issue? 

Please let me know, or let me know if you need any more details or if you have any questions, comments or concerns... 

Thank you,

Denis Tessier

**Comment by LaurentGoderre** [comment]
We generally recommend to bind on the document and filter on the selector which means that any change to the DOM will not affect the event listener.

```javascript
wb.doc.on("change", "#text-input-id", function() {});
```

**Comment by denis-tessier** [comment]
It doesn't appear to just be the triggers and events though, when I try to assign a value to the same input, it also doesn't work, so am not sure how that could be changed to go through the document and filter on the selector... 

$('#text-input-id').val('Put this string in the input'); 

I used the console log so I know there is a value it is trying to input and that it is effectively executing the code, but the value just isn't being set. 

Please advise... Thank you!

**Comment by LaurentGoderre** [comment]
Do you have code I can look at? It should work.

**Comment by denis-tessier** [comment]
I agree and could actually be unrelated and caused by something else, but the only difference I see between the two applications is that one is using the WET Tabbed Interface and the other is using Bootstraps. I'm not sure how to send the code though? 

Please advise... Thanks!

**Comment by LaurentGoderre** [comment]
just put it here and wrap it with 3 ` characters on each side

**Comment by denis-tessier** [comment]
here is the JavaScript function (please let me know if that is not what you wanted): 
```	age : {
		parent : '',		
		init : function(_this) { this.parent = _this; },
		answers: {
			under_45: { id: 1, points:  0, answer: 0 },
			under_55: { id: 2, points:  7, answer: 0 },
			under_65: { id: 3, points: 13, answer: 0 },
			over_74:  { id: 4, points: 15, answer: 0 }
		},
		age : 0,
		
		display : function() {
			this.parent.page_display('age-content');
			this.age = 50;

			/*
			This is how it used to be with Bootstraps, but it doesn't work, so changed it to the below.
			However, I haven't been able to set the min, max and val values for the slider after the change, but at least it gets executed.
			$('#age-slider').slider({
				min: 25,
				max: 75,
				value: 50,
				slide: function( event, ui ) {
					alert("Gets in here...");
					_this.age = ui.value;
					_this._set_storage();	
					_this._load_choice('#age-input');
				}
			});
			*/
			$('#wb-tabs').on('slide', '#age-slider', function( event, ui ) {
				_this.age = ui.value;
				_this._set_storage();	
				_this._load_choice('#age-input');		
			});
			
			this.parent.set_prev_next_btns('Question 1 - eng', 'Question 3 - eng', 'gender', 'bmi');
			this.parent.set_step_counter(2);

			var _this = this;
			
			//The commented trigger failed, so changed it to the one below
			//$('#age-input').on('change', function(e) { 
			$('#wb-tabs').on('change', '#age-input', function(e) {				
				_this.age = $(this).val();
				console.log("Age: " + _this.age);
				if (!isNaN(_this.age)) {
					$('#wb-tabs #age-slider').slider({value:_this.age});
					_this._set_storage();				
					_this._load_choice('#age-slider');
				}
			});
			
			_this._load_choice();
		},
		
		_set_storage: function() {	
			if (this.age <= 44) 					{ this.answers.under_45.answer = this.age; this.parent.set_storage('q_age', this.answers.under_45); }
			if (this.age >= 45 && this.age <= 54) 	{ this.answers.under_55.answer = this.age; this.parent.set_storage('q_age', this.answers.under_55); }
			if (this.age >= 55 && this.age <= 64) 	{ this.answers.under_65.answer = this.age; this.parent.set_storage('q_age', this.answers.under_65); }
			if (this.age >= 65) 					{ this.answers.over_74.answer  = this.age;  this.parent.set_storage('q_age', this.answers.over_74); }
		},
		
		_load_choice : function (obj) {
			
			var first_time_round = true; 
			
			if (obj === '#age-slider') {
				$('#age-input').val(this.age); 				
				first_time_round = false;
			} else if (obj === '#age-input') {
				$('#age-slider').slider({value:this.age});
				first_time_round = false;
			} else {
				var question = this.parent.get_storage('q_age');
				if (question !== null) { this.age = question.answer; first_time_round = false; }
			}
			
			console.log("First time around: " + first_time_round + ' - Age: ' + this.age);

			if (!first_time_round) {
				$('#age-slider').slider({value:this.age});
				// Trying to understand why the age textbox doesn't show the value
				console.log("setting the value for the age in the textbox (" + this.age + ")...");
				$('#age-input').val(this.age); 
				if (parseInt(this.age) > 0) {
					$('a.btn-next').show().attr('disabled', false).fadeTo(0, 1).unbind('click').attr('title', this.parent.text.next_title[this.parent.language_id]); // Activate our next button
				}
				console.log("sliding down the comment box");
				$("div.canrisk-comment").slideDown();
			}else{
				$('#age-slider').slider({value:this.age});
				$('#age-input').val(this.age);	
			}
		}
	}, ```

**Comment by denis-tessier** [comment]
Just wondering if your tests showed the same problems as I am experiencing? 

Please advise... Thank you!

**Comment by LaurentGoderre** [comment]
What part specifically isn't working?

**Comment by denis-tessier** [comment]
The assignment of the age-input textbox value, and you can see there are console log calls around it which log the appropriate values (showing that the code is getting run through), but the textbox isn't being populated. It is the last portion in the code block sent above. When the exact same code gets executed with the Bootstraps tabs, there are no issues, but when I use the WET tabbed interface (using the <details> and <summary> tags), it fails. It all looks to be related to the elements being redrawn.

**Comment by denis-tessier** [comment]
FYI - my last message was affected by the details and sunmary tags written as actual html tags

**Comment by LaurentGoderre** [comment]
Change `$('#wb-tabs').on('change', '#age-input', function(e) {` to `$(document).on('change', '#age-input', function(e) {` and `_this.age = $(this).val();` to `_this.age = $(e.target).val();`

**Comment by hsrudnicki** [comment]
@denis-tessier : Can be this issue closed as resolved/fixed, based on the above comments/inputs from @LaurentGoderre, or if otherwise?  Either way, please update this issue's status, thank you

**Comment by denis-tessier** [comment]
resolved
