### ISSUE TITLE
Secondary menu and footer mobile expand/collpase polyfill no longer initiated

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/wet-boew#7335]
The expand collapse for the secondary menu and the footer no longer work because they don't appear to be initialized anymore.

**Comment by LaurentGoderre** [comment]
This is so weird....I don't even understand how the main menu works because the details/summary are not even initialized

**Comment by andre-gh** [comment]
How do you know they are not inited?  Is this an IE11 issue? I can switch to my windows comp.

**Comment by LaurentGoderre** [comment]
No, it affects all browser except chrome. I figured out part of the problem. They are never explicitly initiated ans were kind of initiated by accident by the `navcurrent` plugin. Not sure why some are skipped (perhaps they are created after the event is). In anycase, it seems fagile to rely on a another plugin to indirectly trigger the initialization

**Comment by LaurentGoderre** [comment]
ANd I know because it doesn't have the initialized class

**Comment by andre-gh** [comment]
Polyfills for something like details should not have to require initing and that is fundamentally incompatible with the polyfill concept.  Previously the init only provided passive enhancement (placing button role in, etc).  Should I update your change so that if it sees a details not united on click it runs init against it?

**Comment by LaurentGoderre** [comment]
All polyfill that are created dynamically always need to be inited.

**Comment by andre-gh** [comment]
I am concerned about breaking anything which was depending on this assumption, like I said, previously it actually worked passively, for example content which is ajaxed with data ajax replace.

**Comment by LaurentGoderre** [comment]
No it never worked passively....we put code to make it look like it does but it doesn't. This is not my change that broke this since my change did not affect the initialization process.

**Comment by andre-gh** [comment]
@LaurentGoderre Thanks, I was recalling incorrectly

**Comment by LaurentGoderre** [comment]
This initialization process is a bit of a mess and is very fragile
