### ISSUE TITLE
Usability: WET table filter field not noticed on right

### ISSUE THREAD

**Issue by neoinsight** [wet-boew/wet-boew#7337]
@dk-knight, @shawnthompson - @pcwsmith suggested you could help with this. 

In usability testing of WET tables, many participants fail to notice the Filter field in its position on the right side of the table. This was particularly an issue on these Find a Passport Location Nearest You pages at http://www.cic.gc.ca/english/passport/map/map.asp- people ended up scrolling endlessly and sometimes failing to find a location. You can see that the bigger the table, the farther the filter moves from the main visual field on the left.

I have been advised by a developer that the filter cannot be repositioned without changes to the basic WET plugin. There are two solutions - the best is to simply swap the 'Showing' and Filter text. Alternatively, make it relocatable, with the default on the right. 

This is fairly urgent - we want to test a new design for Departments and Agencies but cannot with the filter on the right since we already know many people won't spot the filter field. 
![passport office wet table heading](https://cloud.githubusercontent.com/assets/1855584/12304307/ce76efb4-b9fc-11e5-9c7a-6c3a368ea4d2.png)

**Comment by andre-gh** [comment]
At a quick glance the big problem is that there is so much vertical space between the table and the "filter items" field that it seems disconnected.  Moving the second "passport offices" heading (I believe it is a caption) might help a bit?

Regardless, it is possible to move the filter:  The "dom" option sets up how things are setup.

https://datatables.net/examples/basic_init/dom.html

The default is as follow:


            "<'top'ilf>rt<'bottom'p><'clear'>"

If you use:

             "<'top'fil>rt<'bottom'p><'clear'>"

The filter (f) will be before the info (i)

        data-wb-tables='{ "dom" : ""<'top'fil>rt<'bottom'p><'clear'>" }'

**Comment by LaurentGoderre** [comment]
Just an idea, but what about making the field longer and adding a search icon?

**Comment by neoinsight** [comment]
@andre-gh Thanks for that, but we're not trying to do this on a temporary basis, what I'm recommending is that the WET CSS change based on this data, so that it doesn't have to be over-ridden to make it on the left, but is on the left by default. 
@LaurentGoderre That's an idea, but our most recent set of studies on filters/facets is quite clear that we want to avoid confusing dataset/table keyword searches with site search. Gov.UK has a successful model that we tested that uses the label 'Contains' and then has 'Keywords' as a placeholder in the field. Also, the longer the field, the more words people put in, which in these constrained cases causes the searches to fail - 0 results.

**Comment by pjackson28** [comment]
Note that you can change the default for dom in tables.js (right in the definition for defaults.dom) if it is incorrect from a usability standpoint. It was already being configured in WET to address usability issues with the DataTables default layout so can be tweaked again in the same place.

**Comment by neoinsight** [comment]
@shawnthompson @pcwsmith We have mocked up a proposed Departments and Agencies WET table with the filter on the left. The custom CSS has moved it but we are having a little trouble with mobile - the view zooms in on the field in a weird way, and the phone keyboard pops up to cover the results. Small things though - take a look. 
Proposed: http://neoinsight.com/test/wet-sandbox/en/government/dept/index.html
Would replace this page: https://www.canada.ca/en/government/dept.html

At some point, as per this issue, we'd like to make the default WET table design display the filter on the left like this.

**Comment by shawnthompson** [comment]
I've been talking to @masterbee about creating a filter plugin for lists and sections for WET.

Something like [List.js](http://www.listjs.com/). This would help in the search pages as well as the departments and agencies list. Hoping to make it flexible enough to use for sections.

**Comment by neoinsight** [comment]
@shawnthompson That sounds interesting, particularly for the Finder/search pages. In fact, that would possibly help the Passport page problem above, where there are several tables. 

In the meantime, for departments and agencies, I think the WET table will work fairly well, and of course, the WET table is in use on many GC pages and perhaps many non-GC pages. 

So what we're requesting here is just a change to the CSS for the defaults for the WET table, to move the filter box over to the left so that it's more easily noticed. People who didn't spot it were paging through the tables - some tables are just too long for that strategy.

**Comment by shawnthompson** [comment]
oops I think I commented on the wrong issue... that was mean for the other one that talks about [keywords in GCWeb](https://github.com/wet-boew/GCWeb/issues/953)

**Comment by neoinsight** [comment]
@shawnthompson Ok, I see that, but it gave me a chance to mention again that we need this change to the default WET table CSS, please.

**Comment by pjackson28** [comment]
@shawnthompson Did you change it in tables.js or did you make the change in CSS? If you did it with CSS then please undo that change and instead change the layout defined in tables.js like described above (essentially the change suggested by @LaurentGoderre except making that change to the defaults.dom property).

**Comment by shawnthompson** [comment]
@pjackson28, I made this change 

` data-wb-tables='{ "dom" : ""<'top'fil>rt<'bottom'p><'clear'>" }'`

**Comment by pjackson28** [comment]
@shawnthompson I meant you should be making the change here: https://github.com/wet-boew/wet-boew/blob/master/src/plugins/tables/tables.js#L77 so the default is changed rather than manually overriding the default on every page through the data-wb-tables attribute.

**Comment by shawnthompson** [comment]
Is that not what I did?
https://github.com/wet-boew/wet-boew/pull/7354/files#diff-40ae7a3d6d36b3601aab159a047f8321R77

**Comment by neoinsight** [comment]
@shawnthompson Great to see this happening! My developer also says to watch out - that there is some additional CSS in the GC theme.css that will float the filter back the right, he had to override and add some padding. 

See his demo page here: http://neoinsight.com/test/wet-sandbox/en/government/dept/index.html

**Comment by shawnthompson** [comment]
@neoinsight, can you have your developer test my working example?

http://shawnthompson.github.io/wet-boew/unmin/demos/tables/tables-en.html

I believe I fixed the floating problem.

**Comment by pjackson28** [comment]
@shawnthompson Yes it looks like you did it right. I was just responding to what you wrote on this thread which indicated you had done it with a data attribute.

**Comment by steve-h** [comment]
@shawnthompson WET code is good.

I have noticed a theme that overrides positioning with CSS e.g. line 8200 or so.
[https://github.com/wet-boew/themes-cdn/blob/theme-gcwu-fegc/css/theme.css](url)

`.dataTables_wrapper {
  clear: both;
  position: relative;
  zoom: 1; }
  .dataTables_wrapper .dataTables_length {
    float: left; }
  .dataTables_wrapper .dataTables_filter {
    float: right;
    text-align: right; }
    .dataTables_wrapper .dataTables_filter input {
      margin-left: 0.5em; }
  .dataTables_wrapper .dataTables_info {
    clear: both;
    float: left; }
  .dataTables_wrapper .dataTables_paginate {
    padding-top: 1.25em;
    text-align: center; }`

The CSS floats fight with the dataTable ordering.  There may be other themes that over-specify?

**Comment by shawnthompson** [comment]
@steve-h, now the `theme.css` files have the WET base CSS rules integrated into it so those rule are the ones I have changed.

**Comment by steve-h** [comment]
@shawnthompson my warning is with CSS
.dataTables_wrapper .dataTables_filter {
    float: right;
    text-align: right
}

that shows in demo theme at
http://wet-boew.github.io/themes-dist/GCWeb/docs/ref/GCWeb/GCWeb-en.html

if you inspect theme.css.min

I cannot find the source .scss that this comes from. It will keep filters from being shown at the left.
Perhaps the demo just needs a rebuild?

**Comment by shawnthompson** [comment]
Here is my change to the SCSS file with those rules. I removed those rules, floated to the left and added a little margin to space them out.

https://github.com/wet-boew/wet-boew/pull/7354/files#diff-99515a59c6cd92a37eb79e83fb98cb28L917

**Comment by shawnthompson** [comment]
@steve-h, I merged the change. In 15 minutes, can check the themes and see if those rules are still present in the theme.min.css files? 

Thanks

**Comment by neoinsight** [comment]
@RitchieD Can I ask why you would want that option when we have research evidence that people don't see the filter when it is on the right? 
Also the goal is to standardize these types of UX controls, so that people can use them the same way on every GC page. If some tables are different, then GC visitors will have to LOOK for the filter instead of just using it.

**Comment by RitchieD** [comment]
@neoinsight  Well I agree the goal is to standardize.  Thought there is already lots flexibility in WET implementation.   I think our users are used to the right side.  Personally I like it over there when I need it and not in my face the rest of time.  (Like language toggle)
However, its okay if the answer is no.  I'm just asking.  As if it was an option, I would go right for now.

**Comment by neoinsight** [comment]
@RitchieD  Ok. Based on the research evidence, and the standardizing goal, I would not support an option to place it on the right. We're going for evidence-based decisions, so if/when you have evidence, do let us know and we can revisit. Cheers, Lisa

**Comment by RitchieD** [comment]
@neoinsight okay, thanks.

**Comment by duboisp** [comment]
@neoinsight do you know if there is a public repository where all those evidence-based decisions can be found?

**Comment by neoinsight** [comment]
@duboisp Well, here on Github is one place - I post any issues relating to components. Also all of the reports from the research are online on GCPedia in Web Renewal. Unfortunately, because the issues get addressed over time, it's sometimes hard to put it all together. We're working on better solutions!

**Comment by duboisp** [comment]
Thanks @neoinsight
