### ISSUE TITLE
Path to images for map controls broken in latest build

### ISSUE THREAD

**Issue by jvanulde** [wet-boew/wet-boew#7339]
Not sure what changes were made that would affect the relative paths to assets for plugins but Geomap can no longer access the directory. 

Path is now http://wet-boew.github.io/wet-boew/demos/geomap/undefined/zoom-minus-mini.png

![screen shot 2016-01-15 at 12 33 19 pm](https://cloud.githubusercontent.com/assets/2255248/12364561/32a710da-bb84-11e5-80ef-8eca03677737.png)

**Comment by LaurentGoderre** [comment]
@andre-gh could this be related to your pr?

**Comment by MaximMartel** [comment]
Laurent, Andre will use this account from now on : @andre-d

**Comment by andre-d** [comment]
It could be related, I will take a look tomorrow or Thursday briefly since
I merged that in right at the end.

**Comment by MaximMartel** [comment]
Thanks @andre-d :+1:
