### ISSUE TITLE
horizontal description list: left side fixed width

### ISSUE THREAD

**Issue by robwloch** [wet-boew/wet-boew#7340]
Just wondering if there are any plans to improve the horizontal description list by perhaps letting the left side be wider as needed. It seems that sometimes we have long labels and short values so the labels wrap across many lines with tonnes of wasted space on the right.

I presume that the fixed width is for mobile phones so that stacking is easier but just wanted to ask if anyone knew.

**Comment by hsrudnicki** [comment]
Is this still an issue, waiting for an answer?  Either way, please update this issue's status, whether this issue can be closed as resolved/fixed or if otherwise?  Thank you

**Comment by robwloch** [comment]
Hi @hsrudnicki , still waiting for advice on this.

**Comment by hsrudnicki** [comment]
Does this remain an issue?  Please update again the status of this, thx

**Comment by masterbee** [comment]
@robwloch - great suggestion and I like the direction. We welcome any P.R as suggestions and it helps the community better understand the recommendation. I think there good value in looking horizontal definition lists but going to point you more to the style-guide repo where there is a good bunch of design minded folks doing some amazing thing about how WET and other themes came to be.

https://github.com/wet-boew/wet-boew-styleguide
