### ISSUE TITLE
Add remaining table gridify  (tbl-gridify) CSS 

### ISSUE THREAD

**Issue by cfarquharson** [wet-boew/wet-boew#7341]
From what I can tell, only part of the table gridify CSS was added into WET4.  The suggestion originated on https://github.com/wet-boew/wet-boew/issues/4145  

Currently there is some table gridify CSS (`.tbl-gridify`) in WET in the  wet-boew/src/base/proximity/_base.scss file https://github.com/wet-boew/wet-boew/blob/1935692ec0d54f63ebaeaeaa8fcb50b0236a0b2b/src/base/proximity/_base.scss 

However, there is still missing CSS to make it work properly.  Can you add in this extra CSS? 

```
.tbl-gridify {
padding-top: 15px;
}

.tbl-gridify tr {
background-clip: content-box;
background-image: url("data:image/gif;base64,R0lGODlhAQABAIAAAMLCwgAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="), url("data:image/gif;base64,R0lGODlhAQABAIAAAMLCwgAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="), url("data:image/gif;base64,R0lGODlhAQABAIAAAMLCwgAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="), url("data:image/gif;base64,R0lGODlhAQABAIAAAMLCwgAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==");
background-origin: content-box;
background-position: left top, left top, left bottom, right top;
background-repeat: repeat-x, repeat-y, repeat-x, repeat-y;
padding-bottom:30px;
}

.tbl-gridify td:first-child {
 padding-top:15px;
 background:#777;
}
   
.tbl-gridify td:first-child.dataTables_empty {
background: none !important;
}  

.tbl-gridify td:first-child + td{
padding-top:15px;
}

.tbl-gridify td:first-child, .tbl-gridify td:first-child a,.tbl-gridify td:first-child a:hover,.tbl-gridify td:first-child a:active,.tbl-gridify td:first-child a:focus,.tbl-gridify td:first-child a:visited{
color:#fff !important;
}

.tbl-gridify td {
padding:0 15px 15px 15px;
}
```

It takes a table coded like this: 
```
<div class="well">
    <table class="wb-tables tbl-gridify" data-wb-tables='{"order" : [ 0, "asc" ], "bPaginate" : false }'>
      <thead>
        <tr>
          <th scope="col">Design option</th>
          <th scope="col">Description</th>
          <th scope="col">Keywords</th>
          <th scope="col">Example</th>
        </tr>
      </thead>
      <tbody class="row wb-eqht">
        <tr class="col-xs-12 col-sm-6 col-md-4">
          <td><a href="position-en.html" class="h4 mrgn-tp-0 mrgn-bttm-0">Absolute positioning</a> </td>
          <td>Position content on top of other content</td>
          <td class="text-muted small">Tags: Links</td>
          <td><hr class="mrgn-tp-0">
            <div class="row">
              <div class="col-xs-12"> <a href="#"><img alt="" class="img-responsive full-width" src="https://www.canada.ca/content/canadasite/assets/finance/carousel/20141203-1.jpg">
                <p class="well brdr-rds-0 well-sm mrgn-bttm-sm mrgn-rght-md mrgn-lft-md opct-90 pstn-bttm-xs pstn-rght-xs">Link on top of image</p>
                </a> </div>
            </div></td>
        </tr>
        <tr class="col-xs-12 col-sm-6 col-md-4">
          <td><a href="http://wet-boew.github.io/v4.0-ci/docs/ref/data-ajax/data-ajax-en.html" class="h4 mrgn-tp-0 mrgn-bttm-0">Ajax </a></td>
          <td>A basic AjaxLoader wrapper that inserts AJAXed-in content.</td>
          <td class="text-muted small">&nbsp;</td>
          <td><hr class="mrgn-tp-0">
              <p><span class="glyphicon glyphicon-eye-close"></span>  No quick preview available.<br>  To see this feature in action, go to its topic page. </p></td>
        </tr>
        <tr class="col-xs-12 col-sm-6 col-md-4">
          <td><a href="alerts-en.html" class="h4 mrgn-tp-0 mrgn-bttm-0">Alerts </a></td>
          <td>(description)</td>
          <td class="text-muted small">Tags: Colour</td>
          <td><hr class="mrgn-tp-0">
            <div class="row">
              <div class="col-sm-6">
                <section class="alert alert-success">
                  <p>Well done!</p>
                </section>
              </div>
              <div class="col-sm-6">
                <section class="alert alert-info">
                  <p>Heads up!</p>
                </section>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-6">
                <section class="alert alert-warning">
                  <p>Warning!</p>
                </section>
              </div>
              <div class="col-sm-6">
                <section class="alert alert-danger">
                  <p>Oh snap!</p>
                </section>
              </div>
            </div></td>
        </tr>
        <tr class="col-xs-12 col-sm-6 col-md-4">
          <td><a href="alignment-en.html" class="h4 mrgn-tp-0 mrgn-bttm-0">Alignment </a></td>
          <td>(description)</td>
          <td class="text-muted small">&nbsp;</td>
          <td><hr class="mrgn-tp-0">
            <p class="text-left"><span class="glyphicon glyphicon-align-left"></span> Left aligned text</p>
            <p class="text-center"><span class="glyphicon glyphicon-align-center"></span> Center aligned text/image <img alt="A generic square placeholder image with rounded corners" class="img-rounded center-block" src="http://placehold.it/200x40"></p>
            <p class="text-right"><span class="glyphicon glyphicon-align-right"></span> Right aligned text</p></td>
        </tr>
.....
(you get the idea)
</tbody>
</table>
```

And displays it like this (note, it works with dataTables too): 
![gridify](https://cloud.githubusercontent.com/assets/2319199/12413118/5b2d298a-be41-11e5-9b75-3d2b5a42e5b0.jpg)

**Comment by cfarquharson** [comment]
@MaximMartel do you have timeline on this?

**Comment by neoinsight** [comment]
Whoa guys - this is potentially very useful but two things: 
1. I'm trying to get the filter box moved over to the left on the WET table. Floating right is a problem.  We saw many participants not notice the filter over on the right and try to page through a long WET table (that was on the Passport find a location page,which like this one has the filter floated way to the right with nothing to lead the eye to it). So first off, please don't place the filter box floated right. 
2. There's nothing from all our testing of the departments and agencies page that suggests the departments should be broken up into separate lists. Our current prototype, in a WET table (with the filter on the LEFT) seems likely to be quite successful. http://neoinsight.com/test/wet-sandbox/en/government/dept/index.html

**Comment by LaurentGoderre** [comment]
Is this abusing of a table just to get the filter?

**Comment by cfarquharson** [comment]
@LaurentGoderre I don't think it's abuse of a table....it's just taking the current table: http://wet-boew.github.io/v4.0-ci/demos/index-en.html and restyling it.  From an accessibility stance, it's tabular data and correctly coded. This was @thomasgohard 's suggestion from a long time ago, but the CSS was never full implemented (tbl-gridify is already in the WET4 CSS, but not the full CSS).

**Comment by LaurentGoderre** [comment]
This content would be coded just as effecitvly, if not more, as sections with headings.

**Comment by shawnthompson** [comment]
Wouldn't it be verbose for screen readers to use tables to make regular content?

**Comment by cfarquharson** [comment]
@LaurentGoderre and @shawnthompson  The Canada,ca site has been a table-that-looks-like-a-grid  since the site was originally launched here: https://www.canada.ca/en/mobile.html

If you are suggesting an alternate search/filter JS, then what would that solution be and who is going to put it into WET4?  The current suggestion is already in use on canada.ca and is just a few lines of CSS needed to allow everyone to benefit from this design (as the canada.ca solution is 100% custom CSS that is named specific to that page)

**Comment by shawnthompson** [comment]
I agree that the mobile page should be using a section / content filter but it's actually setup as a table with table headers. Personally I think it's pushing the limits but is properly marked up. They based this page from the social media page, which is a proper data table.

**Comment by LaurentGoderre** [comment]
The only reason that Canada.ca did it this way was for the the filtering capabilities it was always a dirty solution.

**Comment by cfarquharson** [comment]
So does anyone have a different js solution that will filter and equalize the items per row (and re-equalize them as you start to filter and they swtich rows)?  This one I'm proposing is a new lines of extra CSS and leverages the equalheights and datatables js.

**Comment by hsrudnicki** [comment]
Is this still an issue waiting for an answer, as well your consensus, based on the above comment(s)?  Either way, please update this issue's status, whether this issue can be closed as resolved/fixed or if otherwise? Thank you

**Comment by cfarquharson** [comment]
@LaurentGoderre @shawnthompson Do you have a different js solution that will filter and equalize the items per row (and re-equalize them as you start to filter and they swtich rows)? This one I'm proposing is a new lines of extra CSS and leverages the equalheights and datatables js.  

If this solution is a no-go, then you also have to fix it's use on the Canada.ca mobile centre.  You can't have it both ways that it's been in use for almost 2 years on the external site, but yet say that it's not a good solution for implementing into WET.

@hsrudnicki fyi

**Comment by shawnthompson** [comment]
@cfarquharson, The mobile and social media pages are getting a new layout very soon which will be using only data tables to display the information and no longer be using custom CSS.

**Comment by hsrudnicki** [comment]
Based on the above, can be this issue closed or otherwise? Please update the status of this, thank you

**Comment by hsrudnicki** [comment]
Based on the last comment from @shawnthompson, as well no further discussion, this can be closed. If you think otherwise, please update the status of this again, thank you
