### ISSUE TITLE
Polyfill: Date picker

### ISSUE THREAD

**Issue by E1D1** [wet-boew/wet-boew#7342]
Good day,

I have an issue with the Date Picker 

I use 2 date field on the page (start date and end date). When the page loads the first one(start) is showing and I'm hiding the "End Date" until the user select a "start date"

once the "start date" is selected (for example 2016-01-15), I then use JQuery Or javascript  to change the min attribute to min="2016-01-25" of the "end date"  to prevent the user to select an "end date" earlier than the "start date" 

Then I display the second calendar.

When I inspect the code with firebug I can see the attribute was added but when the "end date" calendar opens the days before the set min date are not greyed out (still available to select)

Any suggestions will be appreciated.

Thank You

**Comment by E1D1** [comment]
The process describe above was working with the previous version of the calendar.

Thank You

**Comment by LaurentGoderre** [comment]
For performances reasons, the min and max settings are cached. So changing the values afterhand is definitely and issue.

**Comment by E1D1** [comment]
any other options / work around ?

**Comment by LaurentGoderre** [comment]
This was not a documented use case so I can add it to the unit test and change the approach to support it.

**Comment by E1D1** [comment]
Thank You

**Comment by neoinsight** [comment]
@E1D1 We will be usability testing the revised WET datepicker again soon, and I am interested in having participants try your Start and End date solution. Can you provide a link to the page or is it within a protected application?  Thanks

**Comment by E1D1** [comment]
It's within a protected application

**Comment by neoinsight** [comment]
Ah ok, thanks.

**Comment by LaurentGoderre** [comment]
I just added the test for this issue

**Comment by hsrudnicki** [comment]
Does the test pass? Either way, please update the status of this issue, whether this issue can be closed as resolved/fixed or if otherwise? Thank you

**Comment by E1D1** [comment]
I Will close this Since I approached my issue on a different angle 

Thank you

**Comment by LaurentGoderre** [comment]
I still think this should be fixed

**Comment by E1D1** [comment]
How can I test it

**Comment by LaurentGoderre** [comment]
It has been fixed yet. I created a unit test for it though so we just need to write the code to make the unit test pass

**Comment by hsrudnicki** [comment]
Does this remain still an open issue? Either way, please update the status of this again, whether this can be closed as resolved/fixed or otherwise? Thx

**Comment by shjryan** [comment]
Has this issue been addressed yet?
```javascript
$('{input selector}').get(0).state.minDate = new Date();
```
Calling this code will make the issue go away, but doesn't seem ideal.

**Comment by E1D1** [comment]
yes it has .....

On Feb 21, 2017, at 6:21 PM, Ryan Seo <notifications@github.com<mailto:notifications@github.com>> wrote:


Has this issue been addressed yet?

$('{input selector}').get(0).state.minDate = new Date();

Calling this code will make the issue go away, but doesn't seem ideal.

**Comment by shjryan** [comment]
After the polyfill initialization on IE 11.0.9600.18537, setting `min` or `max` attributes does not change the `field.state.minDate` nor `field.state.maxDate` for me.

Is there a function that I could call in order to update the calendar element without explicitly modifying the input element's state?

Thank you.

**Comment by kodecount** [comment]
I have Windows 10 with IE 11.576.14393.0 and the it is using WET Poly-fill and I'm not experiencing any issue.

**Comment by kodecount** [comment]
I think the approach is wrong. If your showing one date field and having another the other date field shouldn't initialize (if it is just remove the date type). After you set the min (and possible change the type) make the input visible and run `$( "dateInputId" ).trigger( "wb-init.wb-date" );`

**Comment by shjryan** [comment]
Hi @kodecount thanks for your reply.

I have a `startdate` and an `enddate` date input elements, which are initialized on page load. The parent container hide these fields based on a radio control.
* If `startdate` has been changed, then datepicker's `minDate` on target `enddate` needs to be set to `startdate`.
* If `enddate` has been changed, then datepicker's `maxDate` on target `startdate` needs to be set to `enddate`.

Triggering `wb-init.wb-date` does not update `minDate` and `maxDate` values.
I am using WET 4.0.23 currently.

Is there an alternative approach I can take on this issue?

**Comment by kodecount** [comment]
Please see http://kodecount.ca/demos/formvalid/date

```javascript
<script>
$( document ).on( "wb-ready.wb", function( event ) {

  var $date1 = $( "#date1" );
  if ( $date1.length ) {

    $date1.on( "change", function() {
      var $date1 = $( this ),
        $date2 = $( "#date2" );

      $date2.on( "change", function() {
        $date1 = setDateInput( $date1, getDate( new Date() ), this.value );
        $date1.trigger( "wb-init.wb-date" );
      });

      $date2 = setDateInput( $date2, this.value );
      $date2.removeAttr( "disabled" );
      $date2.trigger( "wb-init.wb-date" );
    })

    $date1 = setDateInput( $date1, getDate( new Date() ) );
    $date1.trigger( "wb-init.wb-date" );
  }
});

function setDateInput( $date, minDate, maxDate ) {
  var $date = removeInitialize( $date );
  $date.attr( "class", "form-control" );
  $date.attr( "type", "date" );
  $date.attr( "min", ( (minDate) ? minDate : "" ) );
  $date.attr( "max", ( (maxDate) ? maxDate : "" ) );
  return $date;
};

function removeInitialize( $date ) {
  if ( $date.hasClass( "wb-date-inited" ) ) {
    var $div = $date.parent().parent(),
      $clone = $date.clone();
    $date.parent().remove();
    $div.append( $clone );
    return $clone;
  }
  return $date;
};

function getDate( date ) {
  var year = date.getFullYear().toString();
  var month = ( date.getMonth() + 1 ).toString();
  var day = date.getDate().toString();
  return year + "-" + ( ( month.length == 1 ) ? "0" + month : month ) + "-" + ( ( day.length == 1 ) ? "0" + day : day );
};
</script>
```

**Comment by LaurentGoderre** [comment]
This is a lot of code for something that would be a small fix in the actual polyfill. I"m going to try to fix this today

**Comment by shjryan** [comment]
Thank you so much @kodecount  & @LaurentGoderre :)

**Comment by kodecount** [comment]
The update @LaurentGoderre did up might make the next release which has an expected date of 2017-05-16, but that is only if peer reviewing is passed.
