### ISSUE TITLE
Upscaling GeoMaps

### ISSUE THREAD

**Issue by GA-HC** [wet-boew/wet-boew#7343]
Is it possible to use GeoMaps for a map of the entire world? I am looking at potentially implementing this to replace a current mapping solution, but it needs to be a full map, and the only examples I have found are showing Canada. I am continuing to look into this solution, but if someone knows, you might save me some time.

Thanks,

Gord

**Comment by LaurentGoderre** [comment]
@jvanulde

**Comment by jvanulde** [comment]
Yes you can have a map with the extent of the world. Geomap allows you to specify any base map you require. Having said that the default base map has been specifically designed for maximum performance on all devices and is compliant with Policy on Official Languages (i.e. it is bilingual). It is naturally, restricted to Canada. There is a global map as well, that can be added easily via the configuration but it only shows country borders with country names and city names. Would this be sufficient for your needs?

**Comment by GA-HC** [comment]
Yes, that would be perfect. Even just the country names was what I was looking for. Is there somewhere that it might be documented in greater detail that you could point me to?

Thank you for your fast response.

**Comment by jvanulde** [comment]
Would some thing like the image below work? It's available in both official languages. However, it will mean adding some script to your configuration as well as a reference to a js file. If this is workable, let me know and I can provide you with the code.

![screen shot 2016-01-21 at 1 21 27 pm](https://cloud.githubusercontent.com/assets/2255248/12494987/02e06d66-c042-11e5-92eb-bb3ca89f6652.png)

**Comment by GA-HC** [comment]
That would be perfect. Thank you and I look forward to hearing from you :)

**Comment by jvanulde** [comment]
Two steps required:

STEP 1: In your configuration add the base map:

```javascript
var wet_boew_geomap = {
	 basemap : {
			title : "Basic Map",
			type : "esri",
			url : "http://geoappext.nrcan.gc.ca/arcgis/rest/services/BaseMaps/CBMT_CBCT_GEOM_3857/MapServer/export",
			options : {
				singleTile : false,
				ratio : 1,
				projection : "EPSG:3857",
				fractionalZoom : true,
				resolutions: [/*
					156543.03392800014,
					78271.51696399994,*/
					39135.75848200009,
					19567.87924099992,
					9783.93962049996,
					4891.96981024998,
					2445.98490512499,
					1222.992452562495/*,
					611.4962262813797,
					305.74811314055756,
					152.87405657041106,
					76.43702828507324,
					38.21851414253662,
					19.10925707126831,
					9.554628535634155,
					4.77731426794937,
					2.388657133974685,
					1.1943285668550503,
					0.5971642835598172,
					0.29858214164761665*/
				]
			},
			mapOptions : {
				restrictedExtent: "-2.0037507067161843E7, -1.99729719584E7, 2.0037507067161843E7, 1.99750280416E7",				
				projection : "EPSG:3857",
				units : "m",
				displayProjection : "EPSG:4326",

			}
		}
 };

```

STEP 2: In your client_functions.js you need to add the text layer depending on the language:

```javascript
$document.on( "wb-ready.wb-geomap", "#sample_map", function( event, map ) {

	//  get the sample_map
	mapSample = map;

        // set the center of the map 
	mapSample.panTo( new OpenLayers.LonLat( -3500000, 5000000 ) );
                
        // add the txt layer
        var url = $('html')[0].lang === "fr" ? "http://geoappext.nrcan.gc.ca/arcgis/rest/services/BaseMaps/CBCT_TXT_3857/MapServer/export" :
        	"http://geoappext.nrcan.gc.ca/arcgis/rest/services/BaseMaps/CBMT_TXT_3857/MapServer/export";
        
        var layer = new OpenLayers.Layer.ArcGIS93Rest( 
			"Basic Map",
			url,
			{ TRANSPARENT: true },
			{
				maxResolution : "auto",
				projection : "EPSG:3857",
				isBaseLayer: false
			}
	    );
       
        // add the layer to the map
        mapSample.addLayer( layer );

        // makes sure the layer is below the overlays
        mapSample.raiseLayer( layer, -1 );

        // make the layer visible
        layer.setVisibility( true );
} );
```

I did some rudimentary testing but suggest that you test with your own data/layers. Can you point me to the maps that you are going to use this on?
