### ISSUE TITLE
Breadcrumbs and Related Links in style guide broken

### ISSUE THREAD

**Issue by kellerd** [wet-boew/wet-boew#7347]
Found a lot of Related Links that switch sections in the style guide, or the breadcrumbs in the style guide come up with 404 errors.

Example page: http://wet-boew.github.io/wet-boew-styleguide/v4/design/icons-en.html
Related link to Accessibility guide is broken, breadcrumbs broken

Other examples of correct and broken links

Link found: http://wet-boew.github.io/wet-boew-styleguide/v4/wet-boew/design/index-en.html
Should be: http://wet-boew.github.io/wet-boew-styleguide/v4/design/index-en.html

Link found:http://wet-boew.github.io/wet-boew-styleguide/v4/accessibility/design/icons-en.html
Should be: http://wet-boew.github.io/wet-boew-styleguide/v4/design/icons-en.html

Link found:http://wet-boew.github.io/wet-boew-styleguide/v4/accessibility/images-en.html
Should be: http://wet-boew.github.io/wet-boew-styleguide/v4/accessibility/requirements/images-en.html

Link found: http://wet-boew.github.io/wet-boew-styleguide/v4/wet-boew/index-en.html
Should be: http://wet-boew.github.io/wet-boew-styleguide/v4/index-en.html

**Comment by LaurentGoderre** [comment]
The style guide has it's own repo here https://github.com/wet-boew/wet-boew-styleguide, can you please recreate the issue there?

**Comment by kellerd** [comment]
Recreated https://github.com/wet-boew/wet-boew-styleguide/issues/266
