### ISSUE TITLE
Session Timeout: 

### ISSUE THREAD

**Issue by dghouse** [wet-boew/wet-boew#7348]
I've gone over the documentation of this feature several times but I am still having trouble implementing the "refreshCallback" and "refreshCallbackURL" parameters. I understand that the refreshCallback is supposed to accept as a parameter the body of the of the response of the refreshCallbackURL. Where and how do I define this function? 

For testing purposes I had defined the refreshCallback like this:
```javascript
<script type="text/javascript">
	function refreshCallback ( first_parameter ) {
		console.log("HERE");
		return "true";
	}
</script>
```
In the same page as the plugin configuration:
```javascript
<span class="wb-sessto" data-wb-sessto='{
	"inactivity": 60000, 
	"reactionTime": 30000,
	"sessionalive": 60000,
	"refreshLimit": 200000,
	"logouturl": "/app_name/",
	"refreshCallbackUrl": "/app_name/sessionKeepAlive.do",
	"refreshOnClick": false,
	"method": "POST"}'></span>
```
If the this worked the way I think it's supposed to work, since this function always returns "true", my session would always be valid. Obviously, the point is to make sure that this method worked. However, I never see "HERE" printed in my Chrome console and my session is always expired. That implies that the JavaScript never runs and is the crux of my problem.

I understand that the refreshCallbackURL is simply a URL to a page in my application that has some body text. If the refreshCallback method is accepting the literal `<body></body>` of the response, then I could write the sessionKeepAlive page to only contain `<body>true</body>`. Then I could write :

```javascript
function refreshCallback (first_parameter) { 
	if (first_parameter == "true") {
		return "true";
	else {
		return "false";
	}
}
```

and so, since first_parameter = "true" that would be it. Right? 

I know that my URL is correct because I have used a breakpoint on my display class and I get the expected results from that page. In practice, I probably wouldn't even use an actual file, I'd probably just output something directly to HttpServletResponse through my display action class, but that's not the issue.

Many thanks for any advice.

**Comment by dghouse** [comment]
Looks like I forgot to mention that I'm using version 4.0.13.

**Comment by LaurentGoderre** [comment]
What happens if you try with the latest version?

**Comment by dghouse** [comment]
The WET libraries that I'm using are a part of shared resources in our environment so I've asked to have that updated. 

In the meantime, I have tired it in 4.0.13, 4.0.14, and 4.0.18 with the same effect. 

By your reaction, can I assume that I'm on the right track?

**Comment by LaurentGoderre** [comment]
I haven't use that plugin personally but we always recommend trying in the latest version so we don't try to locate a bug that was already resolved

**Comment by RobJohnston** [comment]
Could that be a documentation problem, as I don't see "refreshCallback" in the code anywhere?

And it says that it's to check the value... checking for what?  For debugging purposes only?

I've always used this plugin (in an ASP.NET site) by defining "refreshCallbackUrl" as an HTML page that simple returns the text "true", or in later thinking, as a server page that runs this:

```C#
    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Response.Write(LCase(Not Session.IsNewSession))
    End Sub
```

**Comment by dghouse** [comment]
It appears that my problem was that the body of the returned document can only contain "true" as in no markup language tags or anything else. Robs comment about the server page returning just "true" got me thinking about what the plugin actually expects. 

I should have known but I guess I got caught up thinking about why I couldn't get the refreshCallback method to work.

Thanks to you both for your help. It's much appreciated.

**Comment by JeanPitre** [comment]
I just ran into the same issue and found the documentation to be very lacking about the callback method.  There really is none.   So I figured I share what I came up with. So looking thru the session timeout source script files I tracked down how they initialize the whole thing and worked my way from that.  It might not be the best way to do it, but it seems to be working.

In my html page I added the following : 
`<span class="wb-sessto"></span>`

And bit further down in a script tag I've got the following :

        $(document).on("wb-ready.wb", function (event) {
            var settings = {
                inactivity: 600000,                                     //10 minutes
                reactionTime: 30000,                                    //3 minutes
                sessionalive: 1200000,                                  //20 minutes
                refreshCallbackUrl: "/Home/KeepSessionAlive",
                logouturl: "./",
                refreshOnClick: true,
                refreshLimit: 200000,                                   //2 minutes
                method: "POST",
                additionalData: null,
                refreshCallback: function (response) {
                    var str = response.replace(/['"]+/g, "");
                    str = str.toUpperCase();

                    if (str == "SUCCESS") {
                        return "true";
                    }
                    else {
                        return "false";
                    }
                }
            }

            $(".wb-sessto").trigger("reset.wb-sessto", settings);
        });

In my case "/Home/KeepSessionAlive" is an MVC JsonResult that returns the string "Success".

**Comment by RobJohnston** [comment]
Hi @JeanPitre ! See also https://github.com/wet-boew/wet-boew/issues/7654.

For full points, read the [session timeout from the web.config](https://msdn.microsoft.com/en-us/library/system.web.sessionstate.httpsessionstate.timeout(v=vs.110).aspx).
