### ISSUE TITLE
Roadmap page has a misleading date

### ISSUE THREAD

**Issue by martindholmes** [wet-boew/wet-boew#7351]
On this page:

http://wet-boew.github.io/wet-boew/docs/versions/rdmp-en.html

Your next release is tentatively scheduled for March 2015, instead of (I presume) 2016.

**Comment by LaurentGoderre** [comment]
@MaximMartel

**Comment by MaximMartel** [comment]
im on it @masterbee @LaurentGoderre

**Comment by MaximMartel** [comment]
#7384

**Comment by MaximMartel** [comment]
i also added release 4.0.19 and 4.0.20 with correct date. 
@masterbee @LaurentGoderre

**Comment by MaximMartel** [comment]
Closing this issue, since its fixed in french and english.
