### ISSUE TITLE
Geomap: AOI draw seem broken

### ISSUE THREAD

**Issue by josegar74** [wet-boew/wet-boew#7353]
I was using WET 4.0.14 and AOI draw worked fine, but after upgrading to WET 4.0.16 the feature seem broken, no rectangle drawn. Tested also in latest 4.0.20 and same result.

Tested in Firefox/Chrome (OSX) and IE9 in all cases with same results.

**Comment by LaurentGoderre** [comment]
@jvanulde

**Comment by jvanulde** [comment]
Confirmed. No changes were made that I am aware of. I will look into it.

**Comment by jvanulde** [comment]
@josegar74 please confirm that this issue has been resolved so we can close it.

**Comment by hsrudnicki** [comment]
Based on the above, can be this issue closed or otherwise?

**Comment by hsrudnicki** [comment]
This can be closed as resolved. If you think otherwise please again update the status of this, thank you
