### ISSUE TITLE
Feeds: (URGENT) LONG delay in displaying new items in the RSS feed

### ISSUE THREAD

**Issue by Bgolden67** [wet-boew/wet-boew#7355]
Would any one have any ideas as to why we are experiencing very long delays in seeing an newly published news release appear in the RSS widget display?

We are using the feed widget to display the RSS feed from news.gc.ca. Until recently, it's been a quick display update  but this week we are experiencing over an hour or more before the most recent feed is displayed.

The release is on news.gc.ca instantly, the RSS is updated right away but the feed widget display is not. Is this a widget issue or more a network/firewall issue at this end?

the page the widget is on:
http://www.aadnc-aandc.gc.ca/eng/1393261289317/1393261493049

The RSS feed direct link:
http://news.gc.ca/web/dsptch-dstrbr-en.do?mthd=xml&ft=atom&crtr.dpt1D=6680&crtr.thm1D=&crtr.tp1D=980&crtr.sj1D=&crtr.lc1D=&crtr.aud1D=&crtr.kw=

**Comment by Bgolden67** [comment]
UPDATE: it took 90 minutes for the release from this morning to appear in the widget

**Comment by nschonni** [comment]
Should probably consider updating from 4.18 to 19/20 since #7237 changed from the google feeds API to YQL. It sucks to hear "update it", but the Feeds API was depreciated last year (https://developers.google.com/feed/) and has no guarantees from Google that it will continue to function.

**Comment by Bgolden67** [comment]
Thanks, I think we are due for that update anyway, I will follow up with our IT shop and see if that resolves the delays after the update

**Comment by hsrudnicki** [comment]
Based on the above, can be this issue closed? Is this still an issue?

**Comment by Bgolden67** [comment]
There is still a long delay before the rss feed from news.gc.ca updates in the widget on our site. Our framework is up to date (4.0.21) so I don't know what the cause is, but the complaints seems to have diminished somewhat. They are just told it takes a while (10 minute to over 30 sometimes) and they accept it.
Not a solution, but seems to have reduced any urgency on this.

**Comment by masterbee** [comment]
closing since there has been improvements in the Yahoo API that replaced Google Feeds API. Also working on a native CORS solution for 4.1.
