### ISSUE TITLE
ARCHIVED - Archiving content: 

### ISSUE THREAD

**Issue by lampson** [wet-boew/wet-boew#7359]
Can I get a clearer definition on "will not be altered or updated after the date of archiving;"?  The reason is our content is stored in Drupal and we are now using the Canada.ca theme.  Prior to this, we were using the GoC Web Usability Theme.  Are we supposed to maintain archived content with it's previous theme (e.g. mega menu, footer, left hand menus)?

Here's what is currently mentioned:
A Web page can be archived online if it is:
* maintained for reference, research or record keeping purposes;
* will not be altered or updated after the date of archiving; and
* stored in a digital repository.

**Comment by hsrudnicki** [comment]
Does this remain an issue? Please update the status of this again, thx
