### ISSUE TITLE
How do I disable polyfills?

### ISSUE THREAD

**Issue by YouGotTheWongDev** [wet-boew/wet-boew#7361]
Hi,

I am using wet-boew v4.0.18 - 2015-09-24
I would like to disable the loading of polyfills. 
All users are using browsers that support HTML5 / I am not using of the polyfill controls.

I could only find information for disabling polyfills for v3.1

Thanks

**Comment by LaurentGoderre** [comment]
Polyfill don't load if not need so you don't need to disable them

**Comment by YouGotTheWongDev** [comment]
I see the request for the polyfill css & js in the development tools (f12) > network while running in IE Edge.
I don't think are Polyfills needed for IE Edge?
Its requesting/referencing about 16 extra files that aren't being used every page request.
Thanks

**Comment by LaurentGoderre** [comment]
Yes, IE 11 is still far from fully supporting HTML5 and does need polyfills. The server should be configured to properly cache WET. This would prevent the need to send the file on each request. Caching is properly implemented on the GitHUb hosted examples and you can see the performance benefits.

**Comment by YouGotTheWongDev** [comment]
I was just hoping there was a simple way to disable it because we are never going to be using any of the polyfill functionality.
There is probably no performance drop at all, more of just a personal irk that the resources are flooded with 16 extra files.

Thanks for looking into this.

**Comment by hsrudnicki** [comment]
Based on the above, this can be closed. If you think otherwise, please update the status of this again, thx
