### ISSUE TITLE
Geomap: Use alternate map

### ISSUE THREAD

**Issue by annied2k** [wet-boew/wet-boew#7364]
Hello,

We are contacting you today because we have a project that involves your Geomap interactive function. For this project we have to use a personalized map from our client. Is it possible for us to replace the actual google map style to include our personlized Québec map instead? I would need indications concerning how exactly to achieve this. 

Here are a additional edits that would need to be applied:
- Change the pointers on the map (different look as well as a different color and shape).
-Modify the legend so that all Nations are listed. First hand, the map has no pointers, but when selecting a specific Nation in the legend, that designated pointer appears.
- When a pointer is selected on the map, there should be a bigger "pop up" with a description of that specific Nation… Reproduced at every Nation.

I would need your collaboration on this project to offer the best service possible for the client.

Thank you!

**Comment by LaurentGoderre** [comment]
I'm pretty sure it's possible but @jvanulde is the expert on this

**Comment by jvanulde** [comment]
Sounds possible @annied2k . Can you share the link to the map you want to replicate?

**Comment by annied2k** [comment]
Yes of course, 

This is the link of the current map we have to redo. http://www.aadnc-aandc.gc.ca/Mobile/Nations/carte1200/carte-eng.html

This current map is no longer accessible, therefore we would need to reproduce the map inside the Geomap Wet4 template. 


Looking forward to your help. 

Thank you and have a great day!

Annie
_________________
Annie Guindon
d2k
Graphic Design & Web
819 771-5710

From:  Joost van Ulden
Reply-To:  wet-boew/wet-boew
Date:  Friday, January 29, 2016 at 9:50 AM
To:  wet-boew/wet-boew
Cc:  Annie
Subject:  Re: [wet-boew] Geomap:  (#7364)


Sounds possible @annied2k . Can you share the link to the map you want to replicate?

**Comment by jvanulde** [comment]
Based on what I can see from the link that you provided it is possible to replicate what you require. However, note that you may need to redesign the experience slightly to accommodate what practically can be done in WET. 

By pointers do you mean the icons representing the Nations? If so, that is easily accomplished in Geomap. 

I would suggest that opening up a “bigger” popup with information about a Nation is impractical – hence some thinking needs to be done around the best way to do this. Can you show a popup with baseline information with a link to more information that will take them to another page? 

Just and idea.

**Comment by annied2k** [comment]
That’s great!

How would I need to redesign? I have already installed the geomap, but I am not quite sure how to proceed to redesign and accommodate the changes that I need. For the pop up option, the client was hoping to that a pop up information but if you think its better to leave as is with a link, thats fine for now.


Thank you and have a great day!

Annie
_________________
Annie Guindon
d2k
Graphic Design & Web
819 771-5710

From:  Joost van Ulden
Reply-To:  wet-boew/wet-boew
Date:  Monday, February 1, 2016 at 9:09 AM
To:  wet-boew/wet-boew
Cc:  Annie
Subject:  Re: [wet-boew] Geomap:  (#7364)


Based on what I can see from the link that you provided it is possible to replicate what you require. However, note that you may need to redesign the experience slightly to accommodate what practically can be done in WET. 

By pointers do you mean the icons representing the Nations? If so, that is easily accomplished in Geomap. 

I would suggest that opening up a “bigger” popup with information about a Nation is impractical – hence some thinking needs to be done around the best way to do this. Can you show a popup with baseline information with a link to more information that will take them to another page? 

Just and idea.

**Comment by jvanulde** [comment]
The problem with the popup is that it won't work in a mobile viewport. I would show a popup with some information with a link to more detail. That detail could be on another page or on the same page - it would depend on the UX desired. Do you have the Nations on Geomap yet? That will be your first step.

**Comment by annied2k** [comment]
Ok that’s not a problem I will explain this to the client and stay with te actual pop up with a link to a other information page. 

For the Map the client would like to keep the same image/map if it’s possible. Which format of the map do we need ? 


Thank you and have a great day!

Annie
_________________
Annie Guindon
d2k
Graphic Design & Web
819 771-5710

From:  Joost van Ulden
Reply-To:  wet-boew/wet-boew
Date:  Monday, February 1, 2016 at 9:49 AM
To:  wet-boew/wet-boew
Cc:  Annie
Subject:  Re: [wet-boew] Geomap:  (#7364)


The problem with the popup is that it won't work in a mobile viewport. I would show a popup with some information with a link to more detail. That detail could be on another page or on the same page - it would depend on the UX desired. Do you have the Nations on Geomap yet? That will be your first step.

**Comment by jvanulde** [comment]
It looks like the current map is just an image. Do you know if it is available as a web service or data layer?

**Comment by annied2k** [comment]
Good morning, 

I have discussed with the team and here is what they said, i’m not sure if this is what we need?

Here is what they say:


Here are some links letting you have access to the localisation folders of First Nations and Inuits.
We recommend that the map services be linked directly to the geospatial corporative data base to ensure that the information stays up to date. If you need the geomatic services to adapt to your design needs (Québec only map without pointers) please advise us.


 

First Nations

Data

WMS

http://services.aadnc-aandc.gc.ca/geomatics/services/Donnees_Ouvertes-Open_Data/Premiere_Nation_First_Nation/MapServer/WMSServer?request=GetCapabilities&service=WMS

 

ArcGIS REST

http://services.aadnc-aandc.gc.ca/geomatics/rest/services/Donnees_Ouvertes-Open_Data/Premiere_Nation_First_Nation/MapServer/0

 

WFS

http://services.aadnc-aandc.gc.ca/geomatics/services/Donnees_Ouvertes-Open_Data/Premiere_Nation_First_Nation/MapServer/WFSServer?request=GetCapabilities&service=WFS

 

SHP

http://data.aadnc-aandc.gc.ca/geomatics/output/DonneesOuvertes_OpenData/Premiere_Nation_First_Nation/Premiere_Nation_First_Nation_SHP.zip

 

FGDB

http://data.aadnc-aandc.gc.ca/geomatics/output/DonneesOuvertes_OpenData/Premiere_Nation_First_Nation/Premiere_Nation_First_Nation_FGDB.zip

 

CSV

http://data.aadnc-aandc.gc.ca/geomatics/output/DonneesOuvertes_OpenData/Premiere_Nation_First_Nation/Premiere_Nation_First_Nation_CSV.zip

 

Data Dictionaries

Data Dictionary - SERVICES

http://data.aadnc-aandc.gc.ca/geomatics/output/DonneesOuvertes_OpenData/Premiere_Nation_First_Nation/Reference/First_Nation_Data_Dictionary_SERVICES.csv

 

Data Dictionary - CSV

http://data.aadnc-aandc.gc.ca/geomatics/output/DonneesOuvertes_OpenData/Premiere_Nation_First_Nation/Reference/First_Nation_Data_Dictionary_CSV.csv

 

Data Dictionary - FGDB

http://data.aadnc-aandc.gc.ca/geomatics/output/DonneesOuvertes_OpenData/Premiere_Nation_First_Nation/Reference/First_Nation_Data_Dictionary_FGDB.csv

 

Data Dictionary - SHP

http://data.aadnc-aandc.gc.ca/geomatics/output/DonneesOuvertes_OpenData/Premiere_Nation_First_Nation/Reference/First_Nation_Data_Dictionary_SHP.csv

 

Metadata

XML

http://data.aadnc-aandc.gc.ca/geomatics/output/DonneesOuvertes_OpenData/Premiere_Nation_First_Nation/Metadonnees_Premiere_Nation_First_Nation_Metadata.xml

 

Tribal Councils

Data

WMS

http://services.aadnc-aandc.gc.ca/geomatics/services/Donnees_Ouvertes-Open_Data/Conseil_Tribal_Tribal_Council/MapServer/WMSServer?request=GetCapabilities&service=WMS

 

ArcGIS REST

http://services.aadnc-aandc.gc.ca/geomatics/rest/services/Donnees_Ouvertes-Open_Data/Conseil_Tribal_Tribal_Council/MapServer/0

 

WFS

http://services.aadnc-aandc.gc.ca/geomatics/services/Donnees_Ouvertes-Open_Data/Conseil_Tribal_Tribal_Council/MapServer/WFSServer?request=GetCapabilities&service=WFS

 

SHP

http://data.aadnc-aandc.gc.ca/geomatics/output/DonneesOuvertes_OpenData/Conseil_tribal_Tribal_Council/Conseil_tribal_Tribal_Council_SHP.zip

 

FGDB

http://data.aadnc-aandc.gc.ca/geomatics/output/DonneesOuvertes_OpenData/Conseil_tribal_Tribal_Council/Conseil_tribal_Tribal_Council_FGDB.zip

 

CSV

http://data.aadnc-aandc.gc.ca/geomatics/output/DonneesOuvertes_OpenData/Conseil_tribal_Tribal_Council/Conseil_tribal_Tribal_Council_CSV.zip

 

Data Dictionaries

Data Dictionary - SERVICES

http://data.aadnc-aandc.gc.ca/geomatics/output/DonneesOuvertes_OpenData/Conseil_tribal_Tribal_Council/Reference/Tribal_Council_Data_Dictionary_SERVICES.csv

 

Data Dictionary - CSV

http://data.aadnc-aandc.gc.ca/geomatics/output/DonneesOuvertes_OpenData/Conseil_tribal_Tribal_Council/Reference/Tribal_Council_Data_Dictionary_CSV.csv

Data Dictionary - FGDB

http://data.aadnc-aandc.gc.ca/geomatics/output/DonneesOuvertes_OpenData/Conseil_tribal_Tribal_Council/Reference/Tribal_Council_Data_Dictionary_FGDB.csv

 

Data Dictionary - SHP

http://data.aadnc-aandc.gc.ca/geomatics/output/DonneesOuvertes_OpenData/Conseil_tribal_Tribal_Council/Reference/Tribal_Council_Data_Dictionary_SHP.csv

 

Metadata

XML

http://data.aadnc-aandc.gc.ca/geomatics/output/DonneesOuvertes_OpenData/Conseil_tribal_Tribal_Council/Metadonnees_Conseil_tribal_Tribal_Council_Metadata.xml

 

 

Inuit Communities

Data

WMS

http://services.aadnc-aandc.gc.ca/geomatics/services/Donnees_Ouvertes-Open_Data/Collectivite_Inuite_Inuit_Community/MapServer/WMSServer?request=GetCapabilities&service=WMS

 

ArcGIS REST

http://services.aadnc-aandc.gc.ca/geomatics/rest/services/Donnees_Ouvertes-Open_Data/Collectivite_Inuite_Inuit_Community/MapServer/0

 

WFS

http://services.aadnc-aandc.gc.ca/geomatics/services/Donnees_Ouvertes-Open_Data/Collectivite_Inuite_Inuit_Community/MapServer/WFSServer?request=GetCapabilities&service=WFS

 

Shape

http://data.aadnc-aandc.gc.ca/geomatics/output/DonneesOuvertes_OpenData/Collectivite_inuite_Inuit_Community/Collectivite_inuite_Inuit_Community_SHP.zip

 

FGDB

http://data.aadnc-aandc.gc.ca/geomatics/output/DonneesOuvertes_OpenData/Collectivite_inuite_Inuit_Community/Collectivite_inuite_Inuit_Community_FGDB.zip   

 

CSV

http://data.aadnc-aandc.gc.ca/geomatics/output/DonneesOuvertes_OpenData/Collectivite_inuite_Inuit_Community/Collectivite_inuite_Inuit_Community_CSV.zip

 

Data Dictionaries

Data Dictionary - SERVICES

http://data.aadnc-aandc.gc.ca/geomatics/output/DonneesOuvertes_OpenData/Collectivite_inuite_Inuit_Community/Reference/Inuit_Community_Data_Dictionary_SERVICES.csv

 

Data Dictionary - CSV

http://data.aadnc-aandc.gc.ca/geomatics/output/DonneesOuvertes_OpenData/Collectivite_inuite_Inuit_Community/Reference/Inuit_Community_Data_Dictionary_CSV.csv

 

Data Dictionary - FGDB

http://data.aadnc-aandc.gc.ca/geomatics/output/DonneesOuvertes_OpenData/Collectivite_inuite_Inuit_Community/Reference/Inuit_Community_Data_Dictionary_FGDB.csv

 

Data Dictionary - SHP

http://data.aadnc-aandc.gc.ca/geomatics/output/DonneesOuvertes_OpenData/Collectivite_inuite_Inuit_Community/Reference/Inuit_Community_Data_Dictionary_SHP.csv

 

Metadata

XML

http://data.aadnc-aandc.gc.ca/geomatics/output/DonneesOuvertes_OpenData/Collectivite_inuite_Inuit_Community/Metadonnees_Collectivite_inuite_Inuit_Community_Metadata.xml





Thank you and have a great day!

Annie
_________________
Annie Guindon
d2k
Graphic Design & Web
819 771-5710

From:  Joost van Ulden
Reply-To:  wet-boew/wet-boew
Date:  Monday, February 1, 2016 at 11:49 AM
To:  wet-boew/wet-boew
Cc:  Annie
Subject:  Re: [wet-boew] Geomap:  (#7364)


It looks like the current map is just an image. Do you know if it is available as a web service or data layer?

**Comment by annied2k** [comment]
Hi, 

Did you had a chance to look at the email I sent you last week ?


Thank you and have a great day!

Annie
_________________
Annie Guindon
d2k
Graphic Design & Web
819 771-5710

From:  Joost van Ulden
Reply-To:  wet-boew/wet-boew
Date:  Monday, February 1, 2016 at 11:49 AM
To:  wet-boew/wet-boew
Cc:  Annie
Subject:  Re: [wet-boew] Geomap:  (#7364)


It looks like the current map is just an image. Do you know if it is available as a web service or data layer?

**Comment by jvanulde** [comment]
@annied2k can we close this issue?

**Comment by annied2k** [comment]
Yes you can, thank’s

**Comment by jvanulde** [comment]
@LaurentGoderre, @hsrudnicki please close.

**Comment by hsrudnicki** [comment]
Based on the above, it's closed, thank you

**Comment by annied2k** [comment]
Merci de votre message. Je serai en vacances du 27 juillet au 12 août. Pour toute urgence concernant un projet en cours, SVP appeler au 819-771-5710. Pour une soumission urgente ou sujet administratif, svp envoyer un courriel à : vacances@d2k.ca
Sinon, je serai de retour le 15 août, et il me fera plaisir de vous appeler à ce moment.
Merci beaucoup et bon été!
_______

Thank you for your e-mail. I will be on vacation from July 27 to August 12. For an urgent manner concerning an active project, please call 819-771-5710. For an urgent quote or administrative subject, please send an e-mail to: vacances@d2k.ca
I will be back on August 15, at what time I will be glad to call you back. 
Thank you very much and enjoy summer!
