### ISSUE TITLE
WET4.0.20 fails to initalize properly in IE8 when CSS/JS files are loaded from different host

### ISSUE THREAD

**Issue by adam2** [wet-boew/wet-boew#7366]
Hi,

There appears to be a problem in WET4 with Internet Explorer 8 where the CSS styles are not initialized properly when the CSS and JS files are loaded from a different domain than the page itself.

For example, if I have a web page on "mydomain.com" and the CSS/JS files are loaded via absolute URL from "myddomain2.com" the page will not display properly in IE8.  We typically do this in order to have the WET4 files centrally deployed and included into several applications across multiple domains.

It's not clear to me yet what is causing this problem.  The issue appears to be centered around the ie8-theme.min.css file.  If this file in particular is not on the same host as the page the page will not display properly 100% of the time.

Comparing the DOMs on a successful vs failed page load (using the IE8 developer tools), the following inline CSS tags are noticeably missing in the failed page.  If you are injecting inline CSS into IE8 that might be the part that fails when the CSS is loaded from a different domain.
<style type="text/css" media="screen">CSS Stylesheet</style>
<style type="text/css" media="all">CSS Stylesheet</style>
<style type="text/css" media="print">CSS Stylesheet</style>

I'll attach some screenshots and code examples following this post for illustration purposes.

Adam

**Comment by adam2** [comment]
Here are two screenshots of a typical failed page load.  I am using the default content-en.html file bundled with the production files of the GC Intranet theme of WET 4.0.20.  The first one shows the page header.  It is missing the blue ribbon, mega menu, etc. The second one shows the footer.  It shows the bootstrap columns not working and the site footer is missing.
![broken_header](https://cloud.githubusercontent.com/assets/2386629/12732359/34d0015a-c903-11e5-8565-b9d7e140fb80.png)
![broken_footer](https://cloud.githubusercontent.com/assets/2386629/12732363/36e152a0-c903-11e5-8211-92e3ac2666aa.png)

**Comment by adam2** [comment]
Here are two more screenshots.  The first shows the inline CSS elements in the DOM that are only present on a successful page load.  Behind the developer tools window you can see the page looks normal.
![successful_inline_css](https://cloud.githubusercontent.com/assets/2386629/12732654/9fd40e3c-c904-11e5-84c4-c7f9e627b92d.png)

The second image shows the same inline CSS styles missing on a failed page load.  This occurs when I try to load the CSS and JS files from the wet-boew.github site (as an example) and view the page locally (either using the file:// protocol or as http:// a locally hosted server).
![missing_inline_css](https://cloud.githubusercontent.com/assets/2386629/12732760/01352b84-c905-11e5-8647-687570d4cb59.png)

**Comment by adam2** [comment]
Here is an HTML file (renamed as a .txt so I could attach it) which demonstrates this bug.  It is the standard content-en.html file from the GC Intranet theme 4.0.20, modified to load the CSS and JS files from the wet-boew.github.io server.  Open this file in IE8, either as a local file or on a locally accessible server and you should see the broken page.  Page displays normally on IE11, Firefox, etc.


[content-en.txt](https://github.com/wet-boew/wet-boew/files/113092/content-en.txt)

**Comment by LaurentGoderre** [comment]
Sounds like CORS related problem, but IE8 is outside of the support window

**Comment by LaurentGoderre** [comment]
Actually...maybe not....the stylesheet are loading, otherwise the readcrumb would not display like that. The stylesheet probably hit the maximum selectors limit that IE8 uses.

**Comment by MaximMartel** [comment]
Since this issue is not supported, can we close this issue ?

**Comment by adam2** [comment]
Hi,

Which part of this issue is not supported?  Does WET4 not support IE8?  Please confirm.

Thanks,
Adam

**Comment by adam2** [comment]
I don't believe this is a max selectors issue.  The page displays properly in IE8 when the CSS and JS files are loaded form the same domain as the page.  If it was a max selectors, wouldn't the page always display broken?

**Comment by adam2** [comment]
Please also note that in other discussions with TBS we are also being asked to use centrally deployed and managed template files (which I believe include the CSS and JS) as we transition to Canada.ca
http://www.gcpedia.gc.ca/wiki/Content_Delivery_Network

**Comment by LaurentGoderre** [comment]
If you wish to support IE8, you will need to proxy `[theme]/css/ie8-theme.min.css`. Bootstrap (and therefore WET) relies on Respond.js for media queries to work, and Respond.js doesn't work in with cross-origin.

**Comment by adam2** [comment]
To be sure, nobody wants to support IE8.  I'd rather you say WET4 didn't support it anymore so we wouldn't have to either.

However, if it was simply Bootstrap and Respond.js not working in cross-origin, why does it work in IE9?

**Comment by LaurentGoderre** [comment]
Correct!

**Comment by adam2** [comment]
Well, i see the problem more clearly now.  It's a pickle!

If you want to close this issue, that is fine by me.  I have solved it on my end by copying the WET4 files to multiple places.  It just means more maintenance effort long term.

This will pose a problem in adopting the recommended CDN approach for Canada.ca though.  From application to application our ability to proxy/reverse proxy files like that varies greatly.  You may wish to notify that group about this limitation so that they can provide instructions to other departments.

**Comment by LaurentGoderre** [comment]
Btw, you only need the IE8 css file locally I think

**Comment by masterbee** [comment]
@adam2 - Thanks for the input and I have added @rlambert27 to this thread so that they are away for the CDN you referenced.

/cc @rlambert27
