### ISSUE TITLE
Breadcrumb links are broken in the documentation

### ISSUE THREAD

**Issue by jaycuse** [wet-boew/wet-boew#7369]
Breadcrumb links for "Style Guide" and  "Design Guide" are broken in your documentation.
For example see [Buttons Example Page](http://wet-boew.github.io/wet-boew-styleguide/v4/design/buttons-en.html)
And check the breadcrumb link

**Comment by masterbee** [comment]
@jaycuse - Thanks for this. I have moved this issue to the appropriate repo to ensure it gets the visibility it needs (Issue 268)[https://github.com/wet-boew/wet-boew-styleguide/issues/268].
