### ISSUE TITLE
wb.js : getUrlParts encode/decode issues

### ISSUE THREAD

**Issue by pierrelalonde** [wet-boew/wet-boew#7370]
The wb.js getUrlParts function does not encode/decode forward slashes correctly. We end up with double encoded values when a query param is already encoded.

See https://github.com/wet-boew/wet-boew/blob/v4.0.18/src/core/wb.js#L35

Fiddle: https://jsfiddle.net/2mp7z66n/

**Comment by masterbee** [comment]
@pierrelalonde - The fear I have with encoding decoding like getUrlParts is that there will always be an edge case that create a bug of some sort. Are you up for trying to find a robust solution to this? PR's are welcome :+1:

**Comment by masterbee** [comment]
Closed since caller (creator of issue) has abandoned the issue.
