### ISSUE TITLE
Session Timeout

### ISSUE THREAD

**Issue by patricksmurphy** [wet-boew/wet-boew#7371]
Hey everyone.   I just added the session timeout  (The one at: https://wet-boew.github.io/v4.0-ci/demos/session-timeout/session-timeout-en.html) to an application, and it is not working quite right.   I was initially quite impressed with it, but on further testing, I can’t get it to do what I need.  

So the problem:

The basic setting of:  

<span class="wb-sessto" data-wb-sessto='{"inactivity": 1800000, "logouturl": "/sgiemt-weims/servlet/weimsmaint?curjsp=W.2.3msM.1.3ntM.1.3nM.2n.5@-eng.jsp&amp;curactn=lo&amp;jsenabled=false"}'></span>

works ok.   The popup appears after 30 minutes and the user gets asked to extend the session or not.   Problem is, it they say yes, nothing is sent to the server to extend the server session.   I have the server session set to 70 minutes now to minimize that problem, but the fundamental problem remains.  If the user renews the widget session 3 times then submits, it won’t save and they will be routed to the log-in page.  So we are basically lying when we say we extended the session.

Next, I tried using the refreshCallbackUrl Ajax hook.  Details probably don’t matter, but I used:

<span class="wb-sessto" data-wb-sessto='{"inactivity": 1800000, "sessionalive": 1200000, "refreshCallbackUrl": "/sgiemt-weims/alive.jsp", "logouturl": "/sgiemt-weims/servlet/weimsmaint?curjsp=W.2.3msM.1.3ntM.1.3nM.2n.5@-eng.jsp&amp;curactn=lo&amp;jsenabled=false"}'></span>

Now the refreshCallbackUrl callback does a few nice things.  It will have the widget shut down the user session if the server session ends due to a reboot or something.   It will also extend the servers session indefinitely.  Which would be great if the user was still asked every 30 minutes if they wanted to renew the session.  But they aren’t.  It seems if the refreshCallbackUrl in use it disables that behaviour.    So the session just lasts forever.  I left it running overnight and the session was still alive.  Lots of problems with that of course…

The only work around I can think of for now is to add an external AJAX call to keep the session going and use the first version above to handle logging out.  Seems that should somehow be built in to the wb-sessto widget though.  And that approach won’t warn the user that the server session has died, unless I implement that logic myself.

Let me know if I’m missing something.  It seems to me I just need the behaviour of the first setup to include with the behaviour of the second setup.  But the “inactivity” popup never appears to the user while the refreshCallbackUrl is in use.

**Comment by patricksmurphy** [comment]
Hey everyone.   I just added the session timeout  (The one at: https://wet-boew.github.io/v4.0-ci/demos/session-timeout/session-timeout-en.html) to an application, and it is not working quite right.   I was initially quite impressed with it, but on further testing, I can’t get it to do what I need.  

So the problem:

The basic setting of:  


`<span class="wb-sessto" data-wb-sessto='{"inactivity": 1800000, "logouturl": "/sgiemt-weims/servlet/weimsmaint?curjsp=W.2.3msM.1.3ntM.1.3nM.2n.5@-eng.jsp&amp;curactn=lo&amp;jsenabled=false"}'></span>`

works ok.   The popup appears after 30 minutes and the user gets asked to extend the session or not.   Problem is, it they say yes, nothing is sent to the server to extend the server session.   I have the server session set to 70 minutes now to minimize that problem, but the fundamental problem remains.  If the user renews the widget session 3 times then submits, it won’t save and they will be routed to the log-in page.  So we are basically lying when we say we extended the session.

Next, I tried using the refreshCallbackUrl Ajax hook.  Details probably don’t matter, but I used:


`<span class="wb-sessto" data-wb-sessto='{"inactivity": 1800000, "sessionalive": 1200000, "refreshCallbackUrl": "/sgiemt-weims/alive.jsp", "logouturl": "/sgiemt-weims/servlet/weimsmaint?curjsp=W.2.3msM.1.3ntM.1.3nM.2n.5@-eng.jsp&amp;curactn=lo&amp;jsenabled=false"}'></span>`


Now the refreshCallbackUrl callback does a few nice things.  It will have the widget shut down the user session if the server session ends due to a reboot or something.   It will also extend the servers session indefinitely.  Which would be great if the user was still asked every 30 minutes if they wanted to renew the session.  But they aren’t.  It seems if the refreshCallbackUrl in use it disables that behaviour.    So the session just lasts forever.  I left it running overnight and the session was still alive.  Lots of problems with that of course…


The only work around I can think of for now is to add an external AJAX call to keep the session going and use the first version above to handle logging out.  Seems that should somehow be built in to the wb-sessto widget though.  And that approach won’t warn the user that the server session has died, unless I implement that logic myself.

Let me know if I’m missing something.  It seems to me I just need the behaviour of the first setup to include with the behaviour of the second setup.  But the “inactivity” popup never appears to the user while the refreshCallbackUrl is in use

**Comment by patricksmurphy** [comment]
I have it working now, but there is some non-ideal behaviour.

I fiddled around until I found out what difference broke it.   The problem was that I was using a  sessionalive time that was shorter that the inactivity time.

Not sure why that would be the case.  It would seem to make sense to check with the server more often than the user.  There is also no point is asking the user to extend the session if it’s already expired for some reason.  So I thought checking the server session first would make sense.



I experimented a bit more to see what effects differing values for sessionalive had.

It’s a bit odd.

If  sessionalive < inactivity, the user is never consulted and refreshCallbackUrl is called every sessionalive milliseconds.

If  sessionalive >= inactivity, the user is consulted every inactivity milliseconds and refreshCallbackUrl is called immediately after the user presses the Continue Session button.   So the value of sessionalive doesn’t really make any difference in this case.


This can be made to work, but is not ideal.   I suggest allowing more frequent server pings.

**Comment by masterbee** [comment]
@patricksmurphy - thanks for this @rlambert27 any thoughts on this?

/cc @rlambert27

**Comment by rlambert27** [comment]
Yep will look into this soon!

**Comment by rlambert27** [comment]
I think this can be closed, I did a review and nothing seems wrong our out of place in the logic. Unless @patricksmurphy has a suggestion?

**Comment by hsrudnicki** [comment]
@patricksmurphy and others: if no suggestion(s), can be this issue closed or otherwise?

**Comment by hsrudnicki** [comment]
No further suggestions, so based on the above, this issue can be closed.
[If you think otherwise, please update the status of this again, thank you]
