### ISSUE TITLE
Double loading js files

### ISSUE THREAD

**Issue by yahmon** [wet-boew/wet-boew#7372]
The wet-boew.js is causeing all the js file that get loaded to load twice.  This is really slowing down my pages, especially when the datatables js file loads twice.  Is there a work around for this?  I think it may be caused by the Modernzr.

**Comment by LaurentGoderre** [comment]
This is caused by yepnope. Yepnope relies on the server hosting the files to have proper caching setup. You need to enable caching for the WET resources. Ideally, you would have a different folder for each version of WET you used and cached the content of those folders for long period of time (1 year for example)

**Comment by yahmon** [comment]
Thanks for the reply. That would explain it. I am in active development cycle so all caching is disabled to see screen changes immediately. I will keep that in mind for test and prod.  

Are there any plans to replace yepnope since it has been deprecated by its creator? Which means no further support or develop of yepnope.  The guy who created it says it doesn't fall under best practices anymore. Check yepnope website all the details are there.

**Comment by LaurentGoderre** [comment]
We are aware of it's deprecation and are looking at options

**Comment by masterbee** [comment]
@yahmon - thanks for the input, we have opened a new experimental repo for WET where will be prototyping and exploring options ( like the yep nope alternatives ) very soon. 

Over the next few weeks we will be populating that repo with some new builders ( packaging of WET with less volatile dependencies ) and approaches to plugins architecture. We welcome you to take a peak at its progress and even contribute if you would like [WET-BOEW Experimental Repo](https://github.com/wet-boew/wet-boew-experimental).

/cc @LaurentGoderre
