### ISSUE TITLE
Print active tabbed interface not working well in v4.0.19+2

### ISSUE THREAD

**Issue by samisd** [wet-boew/wet-boew#7373]
We are having issues with the Tabbed interface we use for the Travel advice and advisories at Travel. It seems to be responding erratically to printing in different browsers. We are currently using v4.0.19+2 and implemented the Print-active class to print only one tab, but it is not indicative to the user what the other tab titles would be or even if there is content there. The Print-active class is supposed to be good for v4.0.15+. but some browsers have printed some content but not all as well. ANy help would be appreciated, thanks.

The default doesn't work well for print.

Here is a link to the page: http://travel.gc.ca/destinations/azores 

See figure:
![acores](https://cloud.githubusercontent.com/assets/3083986/12828236/95b37c86-cb51-11e5-9c50-14a25649cb56.PNG)

**Comment by samisd** [comment]
@gandyp

**Comment by masterbee** [comment]
@samisd - have you tried the latest package of WET? Details/Summary had some tweaks in the last package to whitespace so let us know if there is still an issue.

**Comment by samisd** [comment]
@masterbee - Yes, thanks for replying. We tried it with the latest WET package on a dev site and still had the same printing problems with various browsers, so it would appear that the issue remains.
@gandyp, @lampk

**Comment by MaximMartel** [comment]
@andre-d

**Comment by cybersubtype** [comment]
@samisd @masterbee Not sure about the issue on v4.0.19+2 if still exist, but from my testing on v4.0.21 toggle elements work fine on Firefox (v49), and IE11, but failed on first print attempt with chrome if you tried right after the first print attempt it worked. There seemed to be a delay between opening the toggle elements and how chrome prints a page.

**Comment by kodecount** [comment]
@samisd @masterbee Started the pull request to fix this.
