### ISSUE TITLE
Is it possible to have a modal bottom-bar overlay?

### ISSUE THREAD

**Issue by chyne** [wet-boew/wet-boew#7374]
I'd like to have a modal bottom-bar overlay like the one here: [http://wet-boew.github.io/v4.0-ci/demos/overlay/overlay-en.html](http://wet-boew.github.io/v4.0-ci/demos/overlay/overlay-en.html) that would only close via activating the X close link.
Is such a thing currently possible?

**Comment by masterbee** [comment]
@chyne - I tried your link and it came up a 404. Here is the WET demo page for our overlays http://wet-boew.github.io/wet-boew/demos/overlay/overlay-en.html , you will notice that there is one that is a "bottom-bar" overlay example with a code snippet to help you.

Let us know if this helps.

**Comment by chyne** [comment]
Sorry, coded the link in my question wrong (now fixed) but it is the same content you linked to. The bottom bar on that page disappears when you click on the main content of the page. I'd like for it to remain open while the user clicks around in the main content. Is this possible?

**Comment by hsrudnicki** [comment]
@masterbee @chyne others: Is this still an issue waiting for your answer? Either way, please update this issue's status whether this issue can be closed as resolved/fixed or if otherwise, thank you

**Comment by chyne** [comment]
Figured it out. Add the class "outside-off" to the overlay.
