### ISSUE TITLE
validator.addMethod with 

### ISSUE THREAD

**Issue by spacejang** [wet-boew/wet-boew#7377]
I had an issue today when I use validator.addmethod.
I have  a form and when I click submit , it happens.
I am using Wet-boew 4.0.20
The error is   "this.optional(element)" area with wet-boew.min.js
The error message is 
- unalbe to get property 'detach' of undefined or null reference.

My solution is that I replaced wet-boew.min.js from 4.0.20 to 4.0.18. Now it works.
Here is my scripts.

>         wb.doc.on("wb-ready.wb-frmvld", ".wb-frmvld", function (event) {
>             $.validator.addMethod("beforeDate", function (value, element, param) {
>                   return this.optional(element) || (($(param).val() === '') ? false : (value >= $(param).val()));
>             }, "Please enter  End Date greater than or equal to Start Date");
> 
> .....
>         });

**Comment by hsrudnicki** [comment]
Is this still an issue waiting for a further answer? Either way, please update this issue's status, whether this issue can be closed as resolved/fixed or if otherwise, thank you
