### ISSUE TITLE
Security Issue with WET 3.x - Please patch your versions

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/wet-boew#7379]
It has come to my attention that unsupported versions of WET have a cross-site scripting vulnerability bug. It affects all v3.x versions. Because this issue affects security, I have created patches for these versions of WET to resolve this issues. While these are not supported by the WET team, I strongly urge you to apply them to your sites and application.

To get the fix, go the this URL (https://github.com/LaurentGoderre/wet-boew-legacy/releases) and download the patch for the version you are using. At the root of your WET version, run the following command `patch -p1 < 001-Security-Patch.patch`

**Comment by LaurentGoderre** [comment]
Fixes #7350

**Comment by Pacoup** [comment]
When will the full details of this security issue be posted, including a non-minified changeset? Will the patch ever be supported outside of your own fork? Does SSC have any responsible disclosure timeline?

**Comment by LaurentGoderre** [comment]
I don't think the patches will be supported outside my fork no. Since I did this as a volunteer, I am not aware of anything involving SSC.

**Comment by RobJohnston** [comment]
I was forwarded a advisory about this on Monday from SSC titled 
"GC-CIRT Advisory GCAV16-022 XSS Vulnerability in WET Toolkit v3.0/v3.1"

**Comment by LaurentGoderre** [comment]
PLEASE NOTE! The fix is contained in the patch file, not the source zip file.

**Comment by hsrudnicki** [comment]
Based on the above, this can be closed as resolved/fixed. If you think otherwise, please update the status of this again, thank you
