### ISSUE TITLE
Usability Themes

### ISSUE THREAD

**Issue by declares** [wet-boew/wet-boew#7388]
We have a partnership site that is not part of our Internet and I was told by our technician that it is not allowed to use the GOC WET3 or WET4 usability themes. Is that in respect to certain tags that can or can not be used? Please advise.

Thanks

Sandy

**Comment by rlambert27** [comment]
Hi Sandy,

ESDC has multiple partnership sites that use WET3 and WET4:

- Red Seal (http://www.red-seal.ca/)
- FAEYC (http://early-childhood.esdc.gc.ca/adgfje-faeyc/)
- Ellis Chart (http://www.ellischart.ca/)

Some more (Youth, PISA, National Seniors Council, National Child Benefit, Canlearn, etc...)

We use modified WET3/WET4 on many of these web assets.

Roch Lambert

**Comment by hsrudnicki** [comment]
Based on the above, this can be closed. If you think otherwise, please update the status of this again, thank you
