### ISSUE TITLE
Multimedia Player - YouTube: 

### ISSUE THREAD

**Issue by louis-galipeau** [wet-boew/wet-boew#7389]
We have noticed that when we have a carousel with videos that also have the "share" aria code, the heading for “Share this video” is duplicate and at a h2 level. It is improper use of heading level as it will be hard for the screen reader to know what "share this video" link they want to click. 

![output heading](https://cloud.githubusercontent.com/assets/1824337/13009962/500296be-d16d-11e5-8309-49ae7c6b53d2.gif)

This also occur when there is only one video where the "share this video" is also an H2.

e.g. [http://www.cic.gc.ca/english/refugees/welcome/latest.asp ](http://www.cic.gc.ca/english/refugees/welcome/latest.asp)

Heading level 2Hear from refugees and Canadians on the journey
Heading level 2Share this video

**Comment by LaurentGoderre** [comment]
The tool is misleading here because all of these are outside the DOM because they use `display: none` so they are no present in the outline until the modal is displayed

**Comment by hsrudnicki** [comment]
Can be this closed as resolved or otherwise? Please update the status of this, thank you

**Comment by masterbee** [comment]
closed since the issue appears to be addressed
