### ISSUE TITLE
Date picker issue with focus jump

### ISSUE THREAD

**Issue by rlambert27** [wet-boew/wet-boew#7395]
Hello,

We're having a small issue with the date picker:

Sample page : https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_20/samples/content-date-en.shtml

You'll notice the page is very long but with the WET date picker code at the top. When first selecting the calendar icon, the focus jumps to the bottom of the page. This happens in FF43.0.4 and I was able to reproduce using the WET demo as well as using our CDTS (Centrally Deployed Templates Solution (AKA CDN)).

Thanks!

Roch Lambert

**Comment by LaurentGoderre** [comment]
weird that it only happens the first time.....Perhaps the focus happens before the control is positioned
