### ISSUE TITLE
Menu: 

### ISSUE THREAD

**Issue by ChristineLamontagne** [wet-boew/wet-boew#7397]
Any way to do the same thing but without the pre-made menu?  I have to add a lot of parameters to my links on the fly so I can't do a simple html file

**Comment by rlambert27** [comment]
Hi Christine,

I believe I answered this question by email. Let me know if you have anymore questions and I can hop over to your desk and check it out.

**Comment by LaurentGoderre** [comment]
In the future, can you please use a more descriptive title. It's hard manage a list of issues with no meaningful titles

**Comment by hsrudnicki** [comment]
Based on the above, this issue has been resolved, if you think otherwise please update the status of this again, thank you
