### ISSUE TITLE
how to auto generate a calendar?

### ISSUE THREAD

**Issue by marieeved** [wet-boew/wet-boew#7398]
Hi, 
I would like to know if we have a widget calendar that generate auto a month calendar of our choice?
or if we have to do it manually (with a table or with css/JS)?

in the calendar of events, the calendar is not display, only the list of events (I used wet 4.0.12)

it will be great to have a widget like in the  - Input type="date" polyfill (date picker) - but without to click on the image, something that will display immediately the calendar to screen.

thanks for help.

**Comment by LaurentGoderre** [comment]
Did you check the documentation http://wet-boew.github.io/wet-boew/docs/ref/cal-events/cal-events-en.html

**Comment by marieeved** [comment]
well, if I understand. I must create a CSS class to generate the calendar?

that's was the reason of my question... there is no plugin/widget who do that really automatically?

**Comment by LaurentGoderre** [comment]
I don't understand what you mean by automatically. The author has to choose where to use the calendar. The calendar of events work the same way as all other plugins in WET.

**Comment by marieeved** [comment]
well, the calendar doesn't appear on the html page.
So, I have to create the calendar (to tell it which day and month) by CSS or JS?
or is it a bug because I use an old version (4.0.12)?

**Comment by LaurentGoderre** [comment]
Do you have an example?

**Comment by marieeved** [comment]
First thing : 
The code for the WET's calendar events isn't working. So my question was : with your "unique class", do I have to write js code to create the calendar or there is already a code (a class) written for this in the wet? or isn't working because I have an old version (wet 4.12)?

2nd thing : in the case where I have to write the code myself, I was wondering if you knew a widget that will do it for me. Example: you tell it the month and the year and the calendar appears. (something to not manipulate code).

I searched a simple solution because other people (without knowing html/js) in my team will have to manipulate the calendar.
Thanks a lot

**Comment by LaurentGoderre** [comment]
Can you post your code, the plugin does work. It's probably just an html issue.

**Comment by marieeved** [comment]
<h1 id="wb-cont" property="name" style="border-bottom: 1px solid #AF3C43;">Archives</h1>
<p class="pagetag">Vous avez manqué une nouvelle importante? Pas de panique! <br/> Vous retrouverez ici toutes les nouvelles de l'actualité publiées dans les revues de presse quotidiennes du mois courant ainsi que des trois derniers mois.</p>

<div class="wet-boew-calendar-events calendar1">
	<ol>
		<li>
			<section>
				<h4><a href="http://www.canada.gc.ca">Single-Day Event</a></h4>
				<p><time datetime="2011-03-11">March 11th 2011</time></p>
				<p>Event Description</p>
			</section>
		</li>
		<li>
			<section>
				<h4><a href="http://www.canada.gc.ca">Multi-Day Event</a></h4>
				<p><time datetime="2011-03-22">March 22nd, 2011</time> to <time datetime="2011-04-26">April 26th, 2011</time></p>
				<p>Event Description</p>
			</section>
		</li>
	</ol>
</div>
<div id="calendar1"></div>

**Comment by marieeved** [comment]
how I can display just the code ?

**Comment by LaurentGoderre** [comment]
You need to wrap your code with three ` characters

**Comment by LaurentGoderre** [comment]
Aaaah the documentation is wrong, as was mentioned in another issue. The class is not `wet-boew-calendar-events` it is `wb-calevt-cal`

**Comment by LaurentGoderre** [comment]
Related to #6577

**Comment by marieeved** [comment]
However, I always look if there is an issue about my topic. I guess the search is not perfect...

stil doesn't work with your new class (the 2 corrections). 
Do I have to recup the latest demos files in wet 4.20?

**Comment by LaurentGoderre** [comment]
Yeah, it's not as simple as that unfortunately. That page will need to be rewriitten. In the meantime, can you please follow the code example from here:

http://wet-boew.github.io/wet-boew/demos/cal-events/cal-events-en.html#wb-auto-3

**Comment by hsrudnicki** [comment]
Based on the above, can be this issue closed or of otherwise, please update this issue's status again, thank you

**Comment by hsrudnicki** [comment]
Due to the label 'Close: Duplicate', this is closed.
