### ISSUE TITLE
Equal height: 

### ISSUE THREAD

**Issue by Belange87** [wet-boew/wet-boew#7399]
Hi, is it possible to use this plugin without using the "wet"?

I have the css and js installed and i'm wondering if i'm missing anything or it's just impossible without the wet?

**Comment by rlambert27** [comment]
You can use the equal heights jquery plugin:

https://plugins.jquery.com/equalHeight/ OR this one:
https://github.com/mattbanks/jQuery.equalHeights

All you need is the jQuery file and the file associated to the plugin you choose.

**Comment by LaurentGoderre** [comment]
I wonder what you mean by you have the js and css but you don't have "wet"

**Comment by Belange87** [comment]
THanks lambert27 it fix my issues!! You can close the issue.
