### ISSUE TITLE
UXWG - Useful feature for applications and long forms

### ISSUE THREAD

**Issue by MaryBethBaker** [wet-boew/wet-boew#740]
Would this .js code (http://oskarkrawczyk.github.com/heyoffline.js/) be a useful addition to WET? I'm thinking about use cases where a user is entering information into a complex form or logged into an application where they might loose data? Not to invite feature creep, but to keep an eye out for future ways of improving User's experiences in these spaces.

Mary Beth

cc Laura Wesley and Thomas Gohard

**Comment by hsrudnicki** [comment]
@thomasgohard and others: are you ready to close this issue ?

**Comment by hsrudnicki** [comment]
Please update this issue's status whether this issue can be closed or otherwise?

**Comment by hsrudnicki** [comment]
It's almost 3 years since this issue had been opened, so can be this issue closed? In case of otherwise, please update this issue's status, thx

**Comment by hsrudnicki** [comment]
Due to a lack of further discussion or status update(s), this issue has been labeled "Going Stale" and closed.
