### ISSUE TITLE
Tables: DataTables JavaScript

### ISSUE THREAD

**Issue by patricksmurphy** [wet-boew/wet-boew#7403]
Hey everyone.  I need to get table grouping working like at http://www.datatables.net/examples/advanced_init/row_grouping.html.  But I can't seem to get any of the JavaScript running from any of the http://www.datatables.net/examples/ pages in the WET environment.  Is there a way to do so?   

I haven't run across a combination of JavaScript links that won't break either WET or the datatables advance JavaScript.

**Comment by LaurentGoderre** [comment]
You can use any functionality from DataTables in the `data-wb-tables` except for callbacks. Callbacks are more difficult to implement.

**Comment by RobJohnston** [comment]
@patricksmurphy 
I was able to get it to work using the table and the CSS from the example you linked to by add the following script after the wet-boew.js loads:


````js
<script>
    wb.doc.on("wb-ready.wb", function () {
        var table = $('#example').dataTable({
            "retrieve": true,
            "columnDefs": [
                { "visible": false, "targets": 2 }
            ],
            "order": [[2, 'asc']],
            "displayLength": 25,
            "drawCallback": function (settings) {
                var api = this.api();
                var rows = api.rows({ page: 'current' }).nodes();
                var last = null;

                api.column(2, { page: 'current' }).data().each(function (group, i) {
                    if (last !== group) {
                        $(rows).eq(i).before(
                            '<tr class="group"><td colspan="5">' + group + '</td></tr>'
                        );

                        last = group;
                    }
                });
            }
        });

        // Order by the grouping
        $('#example tbody').on('click', 'tr.group', function () {
            var currentOrder = table.order()[0];
            if (currentOrder[0] === 2 && currentOrder[1] === 'asc') {
                table.order([2, 'desc']).draw();
            }
            else {
                table.order([2, 'asc']).draw();
            }
        });
    });
</script>
````

Note that if you add the "[wb-tables](http://wet-boew.github.io/wet-boew/demos/tables/tables-en.html)" class to the table then it won't work.

**Comment by hsrudnicki** [comment]
Based on the above, this can be closed as resolved. If you think otherwise, please update the status of this again, thank you
