### ISSUE TITLE
Form validation: display server-side validation error

### ISSUE THREAD

**Issue by regio760** [wet-boew/wet-boew#7408]
Upon submitting a form, if server-side validation takes place and error messages are to be returned, how do you return error messages to the page and have them display consistently as they do with the client-side validation that this example seems to do?

I am having trouble seeing the code for how the error messages display - I want to be able to display errors in English or French, depending the user's language selection - this can obviously be done but I am not seeing how.

**Comment by LaurentGoderre** [comment]
This is a good question and should be handled by our documentation if it isn't already.

**Comment by regio760** [comment]
Where in the documentation?  Can you provide a link please?  I couldn't find it but it seems like such an obvious feature

**Comment by LaurentGoderre** [comment]
It doesn't look like it http://wet-boew.github.io/wet-boew/docs/ref/formvalid/formvalid-en.html

**Comment by regio760** [comment]
That is the page I was looking at - that and its example pages.  Is there someone I could contact to get such an answer?

**Comment by LaurentGoderre** [comment]
I will post a solution shortly

**Comment by regio760** [comment]
Thank you in advance!

**Comment by RobJohnston** [comment]
I do a lot of form validation, so I remember this coming up before in issue #2852 (and maybe another that I can't find right now).  A few points from that discussion:

1. "If you need to do server validations then you should be using the jQuery Validation remote method".
 
2.  "you should still have basic server-side validation for security reasons, but it should not be trying to tie into the client-side error messaging"
  
3.  "you can choose to make the error messages look any way you want"
  
4.  "WCAG 2.0 does not require a compliant fallback when JavaScript is disabled if the JavaScript-enabled version is compliant"

Maybe the recommendation has changed since then?

**Comment by LaurentGoderre** [comment]
Well for 3, I think he wants to know what markup to use so that the look is consistent with the client-side errors.

**Comment by regio760** [comment]
1. jQuery is still through javascript which the client can always interfere with and circumvent the validation.
2.  Anytime you do server-side validation, you must have a way of displaying errors on the client-side.
3.  It would be nice to display the error messages in a consistent manner, whether it came from the client-side or server-side.
4.  The intent is to make this work with or without javascript - the javascript can alleviate the load on the serverside, but it can always be manipulated so the serverside must catch everything.

Looking forward to your solution Laurent!

**Comment by RobJohnston** [comment]
A somewhat dated example of the HTML needed is given in https://github.com/wet-boew/wet-boew/issues/6281#issuecomment-69065780.

**Comment by LaurentGoderre** [comment]
That markup is exactly what you need. You will need to handle the i18n yourself though

**Comment by hsrudnicki** [comment]
Can be this closed as resolved or otherwise?  Please update again the status of this, thank you

**Comment by regio760** [comment]
It has not been resolved but I am no longer with that project so unless someone else needs this resolved, it may be closed.

**Comment by hsrudnicki** [comment]
Based on the above, this issue can be closed.  If you think otherwise, please update the status of this again, thank you
