### ISSUE TITLE
Should date modified use a dedicated section and heading?

### ISSUE THREAD

**Issue by EricDunsworth** [wet-boew/wet-boew#7412]
In all WET 4.0 page templates, date modified is currently coded as a description list at the end of the content area. But wouldn't it be better off as its own section with dedicated heading? Might be easier for screen reader users to navigate to and be more WCAG 2.0-friendly.

IMO the description list is ok if the content area only contains an H1 heading, some content and no subsections (since date modified's parent heading is the H1 - which represents the whole content area).

However, if sub-sections are used, it results in the last subsection's heading preceding date modified. That might fail [WCAG 2.0 success criterion 2.4.6](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-descriptive.html). According to [technique G130](http://www.w3.org/TR/2015/NOTE-WCAG20-TECHS-20150226/G130)'s test procedure, each heading should describe its section of the content. Since the modified date isn't part of the last sub-section's content, that test procedure arguably wouldn't pass. If date modified used a heading, it would unquestionably pass. AFAIK none of WCAG 2.0's techniques currently take the concept of HTML5 sectioning elements into account.

Thoughts?

**Comment by LaurentGoderre** [comment]
The date modified is not really content though.

**Comment by pjackson28** [comment]
I'd be careful about putting the date modified in a sub-section as it may impact the meaning from an HTML5 semantics and RDFa 1.1 Lite standpoint. Currently it is at the top level of the content area to identify the currency of that area but putting it into the sub-section may change it into meaning only the currency of that sub-section (which is not the intended purpose). May not end up being an issue but certainly something to watch out for if your are looking to change the template structure/semantics.

**Comment by hsrudnicki** [comment]
Based on the above, this can be closed. If you think otherwise, please update the status of this again, thank you
