### ISSUE TITLE
Inquiry on using WET

### ISSUE THREAD

**Issue by krystofurr** [wet-boew/wet-boew#7417]
Hi there,

I'm very new to using WET although I do have some experience with using Bootstrap.  When downloading the theme packages for WET, I have tested using some of the core design features and they seem to work for me.  When testing with any of the demos from the download that require ajax ( i.e data-ajax-before, data-ajax-after, etc ), it fails to load in the .html page that I have referenced.   I believe I am really missing something here and I'm not sure what.  Any help or direction is appreciated. I have done some testing in Chrome and Firefox.  This testing was done locally.     Thanks

**Comment by krystofurr** [comment]
I fixed my issue.  Sorry for bothering.  Didn't realize that you cannot test Web Experience Toolkit and outside of a web server ( meaning locally ).  Functionality will work with css related items but anything that requires ajax will not run until it is located on a server.

**Comment by LaurentGoderre** [comment]
Yeah! If you are using Node.JS, there are several option for running extremely lightweight web servers for testing.
