### ISSUE TITLE
Should generic breadcrumb SCSS be moved into /src/base/?

### ISSUE THREAD

**Issue by EricDunsworth** [wet-boew/wet-boew#7422]
Recently I noticed some RTL issues in WET's breadcrumbs and came up with a fix... but because breadcrumb SCSS is contained within the individual themes, I had to open several PRs to all of them (#7383, wet-boew/theme-gc-intranet#152, wet-boew/theme-ogpl#119, wet-boew/theme-base#125, wet-boew/theme-gcwu-fegc#234, wet-boew/GCWeb#1066).

From what I saw, every theme's breadcrumb SCSS files are virtually identical. The only differences seem to be related to some themes not keeping up-to-date with wet-boew and a couple of colour overrides.

@pjackson28 @LaurentGoderre @shawnthompson @masterbee Would you be on board if I moved all generic breadcrumb SCSS into WET's base folder and only leave minor overrides in the individual themes?

**Comment by LaurentGoderre** [comment]
I am wondering if you could make it a mixin that theme can include, but are not forced to include.

**Comment by EricDunsworth** [comment]
@LaurentGoderre So like a mixin situated somewhere in wet-boew's /src/base/ folder that would get inherited by themes? Are the themes currently setup in a way that allows them to inherit mixins/placeholder selectors from wet-boew?

**Comment by shawnthompson** [comment]
:+1: I like this idea, don't know how it would work but let's do it!

**Comment by LaurentGoderre** [comment]
@EricDunsworth It absolutely is!

**Comment by EricDunsworth** [comment]
@LaurentGoderre Ok, awesome :).

I tried a quick test a few hours ago and it worked. I'll come up with something more definitive and try sending over some PRs later today..
