### ISSUE TITLE
datepicker - does not work French. it still display English.

### ISSUE THREAD

**Issue by spacejang** [wet-boew/wet-boew#7425]
The datepicker does not translate to French. It still display English even though I seleced French.
Any idea would be greatly appreciated. Thanks.

**Comment by shawnthompson** [comment]
What browser are you using? Some browsers have a date picker already in their UI and those are controlled by the language of the system and not the language of the page or code for their calendar. The WET plugin is a polyfill that adds the date picker to the browsers that don't have one in their core. WET then uses the language of the HTML to pick which calendar language to display.

To see which browsers already have the date picker in them, I use http://caniuse.com/#search=date.

This is very similar to when you use other HTML5 input types and you get validation messages based on the system language and not the page.

**Comment by MaximMartel** [comment]
Can we close this issue ?

**Comment by LaurentGoderre** [comment]
Here's a video explaining how to fix this https://www.youtube.com/watch?v=9oFJEU7QzGs

**Comment by MaximMartel** [comment]
Thanks @LaurentGoderre,

I think we can close this issue.

**Comment by spacejang** [comment]
Yes. please closed it. Thank you.
