### ISSUE TITLE
Bad links in the breadcrumbs

### ISSUE THREAD

**Issue by RMFriedman** [wet-boew/wet-boew#7427]
Hi,
Just wanted to let you know that the links on the breadcrumbs haven't been working for awhile. For example from this page:

http://wet-boew.github.io/wet-boew-styleguide/v4/design/grids-en.html

When I click the breadcrumb link on the top to take me back to the Design Guide, it takes me to:

http://wet-boew.github.io/wet-boew-styleguide/v4/wet-boew/design/index-en.html

That gives a 404. Instead it should take me to: 

http://wet-boew.github.io/wet-boew-styleguide/v4/design/index-en.html

**Comment by LaurentGoderre** [comment]
Can you create this issue in the style guide repo?

**Comment by RobJohnston** [comment]
This issue is already in the styleguide repo:

https://github.com/wet-boew/wet-boew-styleguide/issues/268

**Comment by LaurentGoderre** [comment]
Perfect Thanks!
