### ISSUE TITLE
In IE11, the sort icon in the wb-tables shows blank box, not arrow.

### ISSUE THREAD

**Issue by billxu2007** [wet-boew/wet-boew#7429]
I download the wet-boew-4.0.20, and create a wb-tables,  
<table class="wb-tables table table-striped table-hover">
In IE11, The up/down arrow icon is missing for sort, only 2 blank box there. In Chrome, it is correct.
![image](https://cloud.githubusercontent.com/assets/17579314/13474363/abcaa81a-e08b-11e5-81b1-87ef5a1c9bd4.png)

**Comment by billxu2007** [comment]
![image](https://cloud.githubusercontent.com/assets/17579314/13475762/998a0720-e092-11e5-8b76-3aaec1c2ca35.png)

**Comment by LaurentGoderre** [comment]
If it's a corporate IE, I have seen very often that font download is blocked by some weird "security" policy. It doesn't seem to be happening in a regular IE11

**Comment by billxu2007** [comment]
Yes, you are right. So how can I download these icons and save into local? Any manual? Thanks.

**Comment by LaurentGoderre** [comment]
Local fonts are not practical since it would need to be done on all the machine. The best way is to allow font download

**Comment by billxu2007** [comment]
Not for all the machine, just my web server. User should able to download icon from the web server.

**Comment by LaurentGoderre** [comment]
I don't think the problem is with the server but with the browser themselves since it works fine on Chrome. It's the individual browsers that don't download the fonts

**Comment by billxu2007** [comment]
Thanks.

**Comment by hsrudnicki** [comment]
Based on the above, this can be closed as resolved. If you think otherwise, please update the status of this again, thank you
