### ISSUE TITLE
Multimedia player problems when viewing in Firefox

### ISSUE THREAD

**Issue by roryohara** [wet-boew/wet-boew#7430]
Hello, we have been converting our site over to WET4 and we have noticed a problem with the WET4 multimedia player that we are using. We are using the MPEG4 (H264 + AAC) source with inline HTML captions player.
When viewing the video with the Firefox browser, you will see rotating arrows running over top of the video. There is no way to stop the rotating arrows from appearing. We also noticed the same problem happening on the WET4 design guide page for the multimedia player. 
Will there be fixes applied to this multimedia player to correct this problem in Firefox?
Thanks.

**Comment by LaurentGoderre** [comment]
Which version of WET 4?

**Comment by roryohara** [comment]
We have upgraded to V4.0.20 and the problem appears to be fixed now. Thanks.

**Comment by LaurentGoderre** [comment]
Awesome!
