### ISSUE TITLE
Customization of validation messages

### ISSUE THREAD

**Issue by krystofurr** [wet-boew/wet-boew#7433]
Hello,

 How would I go about customizing the validation messages within the toolkit?  Would I need to link my own version of jquery validator to do this?

**Comment by MaximMartel** [comment]
Hi,

Please see form validation documentation : [(http://wet-boew.github.io/v4.0-ci/docs/ref/formvalid/formvalid-en.html)]. 

And Jquery information : [(http://wet-boew.github.io/v4.0-ci/docs/ref/formvalid/formvalid-en.html)]

Did that help answering your question?

**Comment by krystofurr** [comment]
Hi MaximMartel,

No it does not answer my question.  The documentation does not state where to change the validation messages.

**Comment by RobJohnston** [comment]
Is it a wholesale change that you want to make, or just a change here and there?  If the latter, you could add a custom validation method like in https://github.com/wet-boew/wet-boew/issues/7226#issuecomment-160997645.  But I don't know what the effect would be if you re-used an existing method name.

**Comment by RobJohnston** [comment]
Hey @krystofurr, I just stumbled across this:
http://stackoverflow.com/questions/2457032/jquery-validation-change-default-error-message#2457053

> Add this code in a separate file/script included after the validation plugin to override the messages, edit at will :)

```js
jQuery.extend(jQuery.validator.messages, {
    required: "This field is required.",
    remote: "Please fix this field.",
    email: "Please enter a valid email address.",
    url: "Please enter a valid URL.",
    date: "Please enter a valid date.",
    dateISO: "Please enter a valid date (ISO).",
    number: "Please enter a valid number.",
    digits: "Please enter only digits.",
    creditcard: "Please enter a valid credit card number.",
    equalTo: "Please enter the same value again.",
    accept: "Please enter a value with a valid extension.",
    maxlength: jQuery.validator.format("Please enter no more than {0} characters."),
    minlength: jQuery.validator.format("Please enter at least {0} characters."),
    rangelength: jQuery.validator.format("Please enter a value between {0} and {1} characters long."),
    range: jQuery.validator.format("Please enter a value between {0} and {1}."),
    max: jQuery.validator.format("Please enter a value less than or equal to {0}."),
    min: jQuery.validator.format("Please enter a value greater than or equal to {0}.")
});
```

**Comment by krystofurr** [comment]
Hi @RobJohnston , thanks for the reply.  This implies that you are attaching the jquery validation plugin from outside of the toolkit right?  Meaning that I download the plugin and link it in my markup, then initialize it in the seperate script file.  If possible, I would like to see if they can be altered while still using the class variable through the toolkit " wb-frmvld ".  When using the class variable, there is not initialization in a seperate script file to my knowledge ( and according to the documentation ).   I'm wondering if I have to rebuild the theme in order to do this.  I have successfully used the validation plugin external to the toolkit, but I feel that I shouldn't have to do this in order to just customize the way it functions.

**Comment by LaurentGoderre** [comment]
You don't need to I think, you can porbably call his code once the plugin has been loaded by WET to override the strings

**Comment by krystofurr** [comment]
That worked!  Using the following JavaScript from the documentation page:

`$( ".wb-frmvld" ).on( "wb-ready.wb-frmvld", function( event ) {
jQuery.extend(jQuery.validator.messages, {
    required: "This field is required.",
    remote: "Please fix this field.",
    email: "Please enter a valid email address.",
    url: "Please enter a valid URL.",
    date: "Please enter a valid date.",
    dateISO: "Please enter a valid date (ISO).",
    number: "Please enter a valid number.",
    digits: "Please enter only digits.",
    creditcard: "Please enter a valid credit card number.",
    equalTo: "Please enter the same value again.",
    accept: "Please enter a value with a valid extension.",
    maxlength: jQuery.validator.format("Please enter no more than {0} characters."),
    minlength: jQuery.validator.format("Please enter at least {0} characters."),
    rangelength: jQuery.validator.format("Please enter a value between {0} and {1} characters long."),
    range: jQuery.validator.format("Please enter a value between {0} and {1}."),
    max: jQuery.validator.format("Please enter a value less than or equal to {0}."),
    min: jQuery.validator.format("Please enter a value greater than or equal to {0}.")
});
});`

I placed it inside to change the values.  

Only issue I see now is if I want to designate different messages for other languages.  What would be the best practice for this using the toolkit?  I tried using two blocks of the same code, one for english messages and one for french.  Then try checking the lang attribute from the markup I would switch the loading of the custom messages.  Would this be correct or is there another method?

**Comment by LaurentGoderre** [comment]
It's not ideal but it works. I still haven't figured out the best way to deal with big i18n overrides

**Comment by krystofurr** [comment]
I see.  Appreciate the help muchly @LaurentGoderre and @RobJohnston
