### ISSUE TITLE
Feedback form - submit data

### ISSUE THREAD

**Issue by marieeved** [wet-boew/wet-boew#7438]
Hi,

Do you have information on how to send form's data by email/to the server?

Thanks

**Comment by crochefort** [comment]
Good day @marieeved ... this is by using server-side code like PHP or ASP or .NET ... probably other but not with Javascript only!

**Comment by hsrudnicki** [comment]
Can be this closed as resolved or otherwise?

**Comment by masterbee** [comment]
closing since the caller's (creator of issue) appears have been addressed.

**Comment by marieeved** [comment]
Hi,
Can someone help me to begin?
If I use a server-side  code like ASP, do I need something in particular (on my computer, etc) or I just have to learn how to write in ASP like as I would learn to write in JavaScript?
Thank you,

**Comment by RobJohnston** [comment]
JavaScript runs in the web browser, but for ASP you'll need to do some installation.  The .NET Core SDK, at a minimum.  See https://www.asp.net/get-started

**Comment by marieeved** [comment]
in waiting I also receive info from my organization. want I want to do could be created by our IT team, so I will not have to do the complex coding...
but thanks for the info, very appreciated. :)
