### ISSUE TITLE
Geomap: 

### ISSUE THREAD

**Issue by samer73** [wet-boew/wet-boew#7439]
I would like to ask about how I can open the Geomap in Lightbox or in Overlay? I tried it but it does not work with me. Anyone can help?

Thanks in Advance!

**Comment by jvanulde** [comment]
@samer73 you just just need to specify the width in the style attribute of the `wb-geomap-map` element:

    <p><a href="#centred-popup" aria-controls="centred-popup" class="wb-lbx" role="button">Centred popup (Lightbox)</a></p>
	<section id="centred-popup" class="mfp-hide modal-dialog modal-content overlay-def">
		<header class="modal-header">
			<h2 class="modal-title">Centred popup (Lightbox)</h2>
		</header>
		<div class="modal-body">
			<div class="wb-geomap static">
				<div class="wb-geomap-map" style="width:240px;"></div>
			</div>
		</div>
	</section>
</section>

I get the following:

<img width="810" alt="screen shot 2016-07-19 at 12 37 28 pm" src="https://cloud.githubusercontent.com/assets/2255248/16963991/f829a622-4dad-11e6-9873-b5f1db8225b5.png">

**Comment by jvanulde** [comment]
@samer73 did this work for you? If so can you please close this issue.

**Comment by samer73** [comment]
@jvanulde Yes, it does work. Thank you!
