### ISSUE TITLE
Prettify in IE 10 Windows 7 now accounting for half of the build failures

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/wet-boew#7443]
The build has been failing a lot more lately and it seems to be happening because the prettify plugin takes longer than 5 seconds test timeout from Mocha. We have two choices, raise the timeout even more, or figure out what is chocking IE 10 and not the other versions of IE and all other browsers

**Comment by EricDunsworth** [comment]
Just wondering - Does this only apply to wet-boew?

Currently, Travis-CI builds are supposedly failing for all themes apart from wet-boew itself and GCWeb. Not sure if that's related to this issue. I could create a dedicated issue for that if needed.

**Comment by nschonni** [comment]
IE10 isn't supported by Microsoft, so it might be better to just keep it to 9, 11, and Edge

**Comment by LaurentGoderre** [comment]
@EricDunsworth the build says it fails for theme but it doesn't. It complete and stalls at thre very end of the last task until it timeout. It actually works.

**Comment by LaurentGoderre** [comment]
@masterbee what do you think about removing IE10 from the test matrix?

**Comment by masterbee** [comment]
@nschonni - thanks for that. Did some digging and it IE11 and Edge are really all that is Microsoft want to focus on https://www.microsoft.com/en-ca/WindowsForBusiness/End-of-IE-support. I agree and think it is safe to miss IE10 and below for the matrix
