### ISSUE TITLE
glyphicon not displaying in IE 11 

### ISSUE THREAD

**Issue by sophiek4905** [wet-boew/wet-boew#7444]
![image](https://cloud.githubusercontent.com/assets/3309149/13638775/d74b5a84-e5db-11e5-8231-ab114ce92891.png)

From my IE 11 only, none of glyphicon displays at http://wet-boew.github.io/themes-dist/GCWeb/content-fr.html

![image](https://cloud.githubusercontent.com/assets/3309149/13638896/49464d74-e5dc-11e5-8c6f-35c4c68f41fc.png)

is it same issue as : https://github.com/wet-boew/wet-boew/issues/7429    ?

**Comment by LaurentGoderre** [comment]
Is this a work browser?

**Comment by sophiek4905** [comment]
Yes, it is the IE 11 from work computer.

**Comment by sophiek4905** [comment]
Yes, it is the IE 11 from work computer.

**Comment by LaurentGoderre** [comment]
This is a duplicate of #5693
