### ISSUE TITLE
Latest feeds widget does not handle atom title correctly.

### ISSUE THREAD

**Issue by ptsimard** [wet-boew/wet-boew#7450]
In v4.0.18 feeds were being outputted correctly.

But on v4.0.20+ (maybe .19+2 too, I didn't test it.) it does not parse _data.title_ correctly.

You can see on this screenshot, the title are being rendered as object:

![image](https://cloud.githubusercontent.com/assets/2463817/13716586/11f87cb4-e7aa-11e5-9381-27cd37b22037.png)

When I inspect it at 

```
generic: function( data ) {

            return "<li><a href='" + data.link + "'>" + data.title + "</a><br />" +
                ( data.publishedDate !== "" ? " <small class='feeds-date'><time>" +
                wb.date.toDateISO( data.publishedDate, true ) + "</time></small>" : "" ) + "</li>";
        }
```

you can see the title is an object:

![image](https://cloud.githubusercontent.com/assets/2463817/13716548/dd261e74-e7a9-11e5-9ec8-f041a31b3cf6.png)

@LaurentGoderre Any idea?

**Comment by LaurentGoderre** [comment]
The title being a JavaScript object seems new to me so I am not sure this is an issue with WET or a change in the underlying service

**Comment by ptsimard** [comment]
Our feeds have been like that for a while and they worked before. We use
the HTML attribute because the titles might have some in it. All statcan
feeds are like that not just the one I pointed out. Could WET check for an
object and parse accordingly?

**Comment by LaurentGoderre** [comment]
Maybe the service we were using (and got deprecated) was able to gues it and the new one isn't. Not sure what is the best way to tackle this, an object could be anythin.

**Comment by ptsimard** [comment]
Well, in that case I think it should follow the RFC specs of the Atom
format:

https://tools.ietf.org/html/rfc4287#section-3.1.1

3.1.1 <https://tools.ietf.org/html/rfc4287#section-3.1.1>.  The "type" Attribute
   Text constructs MAY have a "type" attribute.  When present, the value
   MUST be one of "text", "html", or "xhtml".  If the "type" attribute
   is not provided, Atom Processors MUST behave as though it were
   present with a value of "text".  Unlike the atom:content element
   defined in Section 4.1.3
<https://tools.ietf.org/html/rfc4287#section-4.1.3>, MIME media types
[MIMEREG <https://tools.ietf.org/html/rfc4287#ref-MIMEREG>] MUST NOT
be used
   as values for the "type" attribute on Text constructs.



*Philippe T. Simard*
Software and Web developer, Drupal expert
*Alien Cargo Entertainment*
*(819) 209-6000 | ptsimard@gmail.com <ptsimard@gmail.com>*

**Comment by ptsimard** [comment]
Here is another link explaining the format:

http://atomenabled.org/developers/syndication/#text

If I understand correctly, the parser should expect to always have an attributes on these elements and if not, behave as if "text" was there.

**Comment by LaurentGoderre** [comment]
Do you have the source atom feed?

**Comment by ptsimard** [comment]
If you go to http://www.statcan.gc.ca/eng/sc/rss you will find a few atom feeds with that type=html attribute.

**Comment by LaurentGoderre** [comment]
SO it's the service that adds this content thing. Then yes the plugin should be changed to accomodate for this since there isn't too many different combination

**Comment by hsrudnicki** [comment]
Is this still a bug/an issue? Please update this issue's status whether this can be closed or otherwise, thx

**Comment by ptsimard** [comment]
Yes it is still an issue and need to be fixed in WET-BOEW
