### ISSUE TITLE
Pattern not working properly?

### ISSUE THREAD

**Issue by supertia** [wet-boew/wet-boew#7451]
My team and I cannot seem to make use of the "pattern" attribute to validate forms. Here is a simple sample.
## Expected behaviour
The “pattern” should enforce the 9999-999-99 pattern (whereas the data-rule only enforces a minimum length). 
## Actual behavioiur
The pattern doesn’t seem to do anything. And if I inspect the element and use the DOM Explorer in my web browser, the pattern attribute doesn’t even show up - so it is being removed by one of the JS scripts?
## Code sample
> &lt;main role="main" property="mainContentOfPage" class="container"&gt;
> &nbsp; &nbsp; &lt;h1 id="wb-cont" property="name" class="page-header"&gt;Form test&lt;/h1&gt;
> &nbsp; &nbsp; &lt;div class="wb-frmvld"&gt;
> &nbsp; &nbsp; &nbsp; &nbsp; &lt;form class="form" action="#" method="get" id="webrequest"&gt;
> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &lt;div class="form-group"&gt;
> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &lt;label for="costcenter1"&gt;&lt;span class="field-name"&gt;Cost center #1&lt;/span&gt; (9999-999-99)&lt;/label&gt;
> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &lt;input class="form-control" id="costcenter1" name="costcenter1" type="text" data-rule-minlength="11" maxlength="11" pattern="[0-9]{4,4}-[0-9]{3,3}-[0-9]{2,2}" /&gt;
> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &lt;/div&gt;
> &nbsp; &nbsp; &nbsp; &nbsp; &lt;/form&gt;
> &nbsp; &nbsp; &lt;/div&gt;
> &lt;/main&gt;

## Full file (originally .asp)
[form-test.txt](https://github.com/wet-boew/wet-boew/files/171940/form-test.txt)

**Comment by RobJohnston** [comment]
@supertia, I think this is the same as https://github.com/wet-boew/wet-boew/issues/7226.  See that issue for the answer and work-around.

**Comment by LaurentGoderre** [comment]
On a small tangent, if you do implement this as a custom jQuery validation type, it is recommend to not be so strict on formatting and accepts the lack for formatting as a valid option. Your pattern would become: `([0-9]{4})-?([0-9]{3})-?([0-9]{2})`. You can then use the capture groups to reformat the way you want it.

**Comment by hsrudnicki** [comment]
Based on the above, can be this issue closed as resolved? Either way, please update the status of this, thank you

**Comment by supertia** [comment]
I agree with @RobJohnston. This is the same as #7226.

**Comment by RobJohnston** [comment]
@supertia:  Also look at https://github.com/wet-boew/wet-boew/issues/7592#issuecomment-240710793 for an alternative implementation.
