### ISSUE TITLE
Lightbox: When BASIC HTML is clicked

### ISSUE THREAD

**Issue by juliemercier** [wet-boew/wet-boew#7452]
![modals](https://cloud.githubusercontent.com/assets/7468426/13758198/92b678aa-e9fe-11e5-932a-e1ebd693c186.PNG)
In the Skip to links section at the top of the WET templates, there is one called BASIC HTML. If we have modal popups as part of our app page and this link is clicked, the modals display. Some of the buttons on the modals stop functioning when this happens. In the case of your demo example, the button that stops functioning is **Close modal popup**.  In our apps, we use modals of the type "Are you sure you want to delete?" to confirm deletions and we offer a **Delete** and **Cancel** button. So in the case of our app popups, the **Cancel** button no longer work. Is that an issue (usability, WCAG or other) or is that just expected behaviour when a user clicks this link? Do we have to design without modals to accommodate the BASIC HTML link?

**Comment by hsrudnicki** [comment]
Is this still an issue?  Please update the status of this, whether this can be closed or otherwise, thank you

**Comment by kpduncan** [comment]
Please look at #7614 which I mentioned how to avoid this issue or #7639 for an alternative approach.

**Comment by hsrudnicki** [comment]
Are you ready to close this or otherwise? Please update the status of this again, thx
