### ISSUE TITLE
Google indexing wrong links

### ISSUE THREAD

**Issue by louis-galipeau** [wet-boew/wet-boew#7457]
I noticed that google is indexing links with wbdisable=true.  

Do a google search with site:canada.ca inurl:wbdisable=true and you will find About 4,100 results. That means the user see "Skip to main content", "Skip to About this site", "Standard version" when they click those link. Is there a way to prevent Google to crawl the pages with wbdisable=true.

![refugeees 2](https://cloud.githubusercontent.com/assets/1824337/13812823/9d140f36-eb54-11e5-8cbd-4f15c376c40d.png)

**Comment by LaurentGoderre** [comment]
I think the best way to fix this is to add canonical urls to the page via HTTP headers.

https://en.wikipedia.org/wiki/Canonical_link_element

**Comment by TouficS** [comment]
Thanks @LaurentGoderre 
can this be fixed at the template level? 
cc: @neoinsight @masterbee

**Comment by LaurentGoderre** [comment]
I doubt it, it would be extremely inefficient

**Comment by RobJohnston** [comment]
Could you use the Google Webmaster Tools to tell Google to ignore certain URL parameters?  See [Learn the impact of duplicate URLs](https://support.google.com/webmasters/answer/6080548?hl=en&rd=1) and [Categorize parameters with the URL Parameters tool] (https://support.google.com/webmasters/answer/6080550?hl=en&ref_topic=6080547).

**Comment by crochefort** [comment]
Like @RobJohnston said ... yes you can go on google and change the setting... 
![wbdisable](https://cloud.githubusercontent.com/assets/4562025/13963973/fcd85eb6-f03d-11e5-9ccf-b9292e3c9471.jpg)
The question is ... you might need to ask the Tiger Team for the search engine ... is it possible to enable this at the .gc.ca level?

**Comment by TouficS** [comment]
I will follow with the Search optimization working group and share my findings here

**Comment by TouficS** [comment]
a ticket is open with the Canada.ca team to see if it is possible to ignore wbdisable in search at the .gc.ca level

**Comment by bsouster** [comment]
Departments can resolve this on their own websites in their robot.txt files with this line:
Disallow: /*wbdisable*

**Comment by katburke** [comment]
In an effort to help users who have visited our site with wbdisable=true (via Google, since they indexed ~4100 pages with that included in the URL) and are now missing out on important functionality, we're thinking of following Gmail's lead and adding a note to the top of our site indicating that they aren't seeing everything available to them, providing the link to the standard view with more context than it currently is. 

@pjackson28 wondering what you think about this?

![wbdisable-gmail](https://cloud.githubusercontent.com/assets/20952339/17564105/5333c72e-5f00-11e6-8e8a-6713f10f8f24.png)

**Comment by hsrudnicki** [comment]
Does this remain still an issue? Please update the status of this, thank you

**Comment by katburke** [comment]
Yes, it does still remain an issue.

**Comment by shawnthompson** [comment]
The link is already there but maybe adding a notification.

Something like this @katburke 

<img width="1324" alt="screen shot 2016-10-06 at 2 30 05 pm" src="https://cloud.githubusercontent.com/assets/2575266/19165370/84986d9e-8bd1-11e6-97bd-c1592855774d.png">

**Comment by TouficS** [comment]
@shawnthompson the notification is a good idea. But users will wont know the difference between basic and standard. Maybe a link or additional info?

**Comment by shawnthompson** [comment]
@TouficS Do they know the difference on Gmail? We might want to add extra information to the _Standard version_ below. Maybe add _switch to_ like Gmail does in the example by @katburke

**Comment by TouficS** [comment]
@katburke got a mockup that have a note and a description

**Comment by katburke** [comment]
Was thinking something like this:
![basicview](https://cloud.githubusercontent.com/assets/20952339/19275096/90143d92-8fa0-11e6-8b04-4c322679a6b2.png)

**Comment by shawnthompson** [comment]
@katburke, if the **basic mode** is causing so many problems, we might not want to bury the notice inside a list. We might want to put it right on top before the skip navigation so it's the first thing a screen reader reads after the `title`.

I actually had this problem today, I was in Basic mode and was wondering why the data tables plugin wasn't working, so I was checking to make sure I didn't disable my JavaScript in my browser and then I noticed the UL at the top of the page. The URL didn't even have `wbdisable=true` in it.

What about a notice like the [Archive notice](http://servicecanada.github.io/GCWeb/archived-en.html) we are about to put into GCWeb?

**Comment by cybersubtype** [comment]
@shawnthompson In the demo link you provided the archive banner doubles in wbdisable mode.

**Comment by cybersubtype** [comment]
Something like this:

![untitled](https://cloud.githubusercontent.com/assets/22446865/19279254/0f9ef546-8fb7-11e6-9c21-6bfe0f71465f.png)

**Comment by shawnthompson** [comment]
I wasn't suggesting using the overlay, just the style and placement  of the notice

**Comment by katburke** [comment]
I agree that having it prominent is a good idea. But also keeping the link to putting it back to standard mode in the same area as the "you're not seeing everything" text.

**Comment by cybersubtype** [comment]
@shawnthompson Update the html to and remove all classes from the section. Still works fine.

**Comment by cybersubtype** [comment]
@katburke Yes in order to have the link with the header the WET JavaScript well be required to change.

**Comment by shawnthompson** [comment]
@katburke the content isn't up to me, I'm fine with whatever you think just as long as it's accessible link text. 

@cybersubtype we would probably want to create new CSS rules for this notice. 

To all: should we use the same data-inview for this notice, might be worth discussing. 

@DK-TBS thoughts?

**Comment by katburke** [comment]
We have a number of situations where people end up in that mode unintentionally, so I want to dummy-proof it, having something to the effect of "you're not seeing everything you should be seeing, click here". I can finesse the wording. Can we have that yellow bar?

**Comment by cybersubtype** [comment]
@katburke For now till this is updated you could use what I have? Updated the post.

**Comment by cybersubtype** [comment]
If want the link I made these changes to the JavaScript ([disable.js](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/wb-disable/disable.js#L28)):

Non-min Javascript:
```javascript
/*
 * Variable and function definitions.
 * These are global to the event - meaning that they will be initialized once per page,
 * not once per instance of event on the page.
 */
var componentName = "wb-disable",
	selector = "#wb-tphp",
	$document = wb.doc,

	/**
	 * @method init
	 * @param {jQuery Event} event Event that triggered the function call
	 */
	init = function( event ) {

		// Start initialization
		// returns DOM object = proceed with init
		// returns undefined = do not proceed with init (e.g., already initialized)
		var elm = wb.init( event, componentName, selector, true ),
			nQuery = "?",
			$html = wb.html,
			i18n = wb.i18n,
			pageUrl = wb.pageUrlParts,
			div, li, param;

		if ( elm ) {
			
			// element for standard link
			div = document.createElement( "div" );
			div.className = "wb-slc";
			
			// element for basic link
			li = document.createElement( "li" );
			li.className = "wb-slc";

			// Rebuild the query string
			for ( param in pageUrl.params ) {
				if ( pageUrl.params.hasOwnProperty( param ) && param !== "wbdisable" ) {
					nQuery += param + "=" + pageUrl.params[ param ] + "&#38;";
				}
			}

			try {
				if ( wb.isDisabled || ( wb.ie && wb.ielt7 ) ) {
					$html.addClass( "wb-disable" );

					try {

						// Store preference for WET plugins and polyfills to be disabled in localStorage
						localStorage.setItem( "wbdisable", "true" );
					} catch ( e ) {}

					// Append the Standard version link
					div.innerHTML = "<section id='wbdisable-bnr' class='wb-sl'><header><h2 class='wb-inv'>" + i18n( "wb-bnr-hdr" ) + "</h2></header><p><strong>" + i18n( "wb-bnr-bdy" ) + "</strong><a href='" + nQuery + "wbdisable=false'>" + i18n( "wb-enable" ) + "</a></p>";

					// Add link to re-enable WET plugins and polyfills
					elm.parentNode.insertBefore( div, elm );
					
					return true;
				} else {
					$html.addClass( "wb-enable" );

					if ( localStorage ) {

						// Store preference for WET plugins and polyfills to be enabled in localStorage
						localStorage.setItem( "wbdisable", "false" );
					}
				}
			} catch ( error ) {
			}

			// Append the Basic HTML version link version
			li.innerHTML = "<a class='wb-sl' href='" + nQuery + "wbdisable=true'>" + i18n( "wb-disable" ) + "</a>";

			// Add link to disable WET plugins and polyfills
			elm.appendChild( li );

			// Identify that initialization has completed
			wb.ready( $document, componentName );
		}
	};

// Bind the events
$document.on( "timerpoke.wb", selector, init );

// Add the timer poke to initialize the plugin
wb.add( selector );

} )( jQuery, window, wb );
```
Min JavaScript:
```javascript
g=function(a){var k,l,m,b=c.init(a,d,e,!0),g="?",h=c.html,i=c.i18n,j=c.pageUrlParts;if(b){k=document.createElement("div"),k.className="wb-slc",l=document.createElement("li"),l.className="wb-slc";for(m in j.params)j.params.hasOwnProperty(m)&&"wbdisable"!==m&&(g+=m+"="+j.params[m]+"&#38;");try{if(c.isDisabled||c.ie&&c.ielt7){h.addClass("wb-disable");try{localStorage.setItem("wbdisable","true")}catch(a){}return k.innerHTML="<section id='wbdisable-bnr' class='wb-sl'><header><h2 class='wb-inv'>"+i("wb-bnr-hdr")+"</h2></header><p><strong>"+i("wb-bnr-bdy")+"</strong><a href='"+g+"wbdisable=false'>"+i("wb-enable")+"</a></p>",b.parentNode.insertBefore(k,b),!0}h.addClass("wb-enable"),localStorage&&localStorage.setItem("wbdisable","false")}catch(a){}l.innerHTML="<a class='wb-sl' href='"+g+"wbdisable=true'>"+i("wb-disable")+"</a>",b.appendChild(l),c.ready(f,d)}};
```

**Comment by cybersubtype** [comment]
@katburke If this is urgent I can make these changes to a local copy of the JavaScript files for your version of WET until a decision is made? Just send me a email (on my GitHub profile).

**Comment by cybersubtype** [comment]
For the link too be included these changes well need to be made in the WET JavaScript:

Non-min Javascript:
```javascript
/*
 * Variable and function definitions.
 * These are global to the event - meaning that they will be initialized once per page,
 * not once per instance of event on the page.
 */
var componentName = "wb-disable",
	selector = "#wb-tphp",
	$document = wb.doc,

	/**
	 * @method init
	 * @param {jQuery Event} event Event that triggered the function call
	 */
	init = function( event ) {

		// Start initialization
		// returns DOM object = proceed with init
		// returns undefined = do not proceed with init (e.g., already initialized)
		var elm = wb.init( event, componentName, selector, true ),
			nQuery = "?",
			$html = wb.html,
			i18n = wb.i18n,
			pageUrl = wb.pageUrlParts,
			div, li, param;

		if ( elm ) {
			
			// element for standard link
			div = document.createElement( "div" );
			div.className = "wb-slc";
			
			// element for basic link
			li = document.createElement( "li" );
			li.className = "wb-slc";

			// Rebuild the query string
			for ( param in pageUrl.params ) {
				if ( pageUrl.params.hasOwnProperty( param ) && param !== "wbdisable" ) {
					nQuery += param + "=" + pageUrl.params[ param ] + "&#38;";
				}
			}

			try {
				if ( wb.isDisabled || ( wb.ie && wb.ielt7 ) ) {
					$html.addClass( "wb-disable" );

					try {

						// Store preference for WET plugins and polyfills to be disabled in localStorage
						localStorage.setItem( "wbdisable", "true" );
					} catch ( e ) {}

					// Append the Standard version link
					div.innerHTML = "<section id='wbdisable-bnr' class='wb-sl'><header><h2 class='wb-inv'>" + i18n( "wb-bnr-hdr" ) + "</h2></header><p><strong>" + i18n( "wb-bnr-bdy" ) + "</strong><a href='" + nQuery + "wbdisable=false'>" + i18n( "wb-enable" ) + "</a></p>";

					// Add link to re-enable WET plugins and polyfills
					elm.parentNode.insertBefore( div, elm );
					
					return true;
				} else {
					$html.addClass( "wb-enable" );

					if ( localStorage ) {

						// Store preference for WET plugins and polyfills to be enabled in localStorage
						localStorage.setItem( "wbdisable", "false" );
					}
				}
			} catch ( error ) {
			}

			// Append the Basic HTML version link version
			li.innerHTML = "<a class='wb-sl' href='" + nQuery + "wbdisable=true'>" + i18n( "wb-disable" ) + "</a>";

			// Add link to disable WET plugins and polyfills
			elm.appendChild( li );

			// Identify that initialization has completed
			wb.ready( $document, componentName );
		}
	};

// Bind the events
$document.on( "timerpoke.wb", selector, init );

// Add the timer poke to initialize the plugin
wb.add( selector );

} )( jQuery, window, wb );
```
Min JavaScript:
```javascript
g=function(a){var k,l,m,b=c.init(a,d,e,!0),g="?",h=c.html,i=c.i18n,j=c.pageUrlParts;if(b){k=document.createElement("div"),k.className="wb-slc",l=document.createElement("li"),l.className="wb-slc";for(m in j.params)j.params.hasOwnProperty(m)&&"wbdisable"!==m&&(g+=m+"="+j.params[m]+"&#38;");try{if(c.isDisabled||c.ie&&c.ielt7){h.addClass("wb-disable");try{localStorage.setItem("wbdisable","true")}catch(a){}return k.innerHTML="<section id='wbdisable-bnr' class='wb-sl'><header><h2 class='wb-inv'>"+i("wb-bnr-hdr")+"</h2></header><p><strong>"+i("wb-bnr-bdy")+"</strong><a href='"+g+"wbdisable=false'>"+i("wb-enable")+"</a></p>",b.parentNode.insertBefore(k,b),!0}h.addClass("wb-enable"),localStorage&&localStorage.setItem("wbdisable","false")}catch(a){}l.innerHTML="<a class='wb-sl' href='"+g+"wbdisable=true'>"+i("wb-disable")+"</a>",b.appendChild(l),c.ready(f,d)}};
```
Preview:
![untitled2](https://cloud.githubusercontent.com/assets/22446865/19284366/02774872-8fcc-11e6-882b-8941d0792c55.png)

By the way I'm using the CSS from my previous post.

**Comment by shawnthompson** [comment]
I'm going to continue this talk on #7686 because it's more relevant to the subject.

**Comment by TouficS** [comment]
We can close this one as the discussion is about keep or remove the basic mode function in #7686,

**Comment by masterbee** [comment]
closing since the caller's (creator of issue) since contining on #7686.
