### ISSUE TITLE
Question about DataTable Initialization

### ISSUE THREAD

**Issue by rn2016** [wet-boew/wet-boew#7459]
I need to initialize a WET dataTable with these options
"searching" : false, 
        
            "deferRender" : true, 
          
            "order" : [],
            "columns" : [ null, null, null, {
              "orderable" : false
            }, {
              "orderable" : false
            } ],
            "drawCallback" : function(settings) {
             
              $('.wb-lbx').trigger('wb-init.wb-lbx');
            },

            "sDom" : "il rt <'row' il><'row' p>",

            "language" : {
              "decimal" : "",
              "emptyTable" : resultsNoData,
               ...
              }
              "aria" : {
                "sortAscending" : resultsSortAscending,
                "sortDescending" : resultsSortDescending
              }
            }

And be able to clear/reload data dynamically.
What is the proper way to achieve that ?
Thank you

**Comment by LaurentGoderre** [comment]
Why did you close the issue?

**Comment by rn2016** [comment]
Sorry for the late reply.
I use the data initialization from one of the provided link and it worked.

Rosine
