### ISSUE TITLE
table tag attribute on how to sort the second column ascending by default?

### ISSUE THREAD

**Issue by d02wang** [wet-boew/wet-boew#7461]
For WET 3, I know how to setup the <table> tag to sort the second column in default. But I do not know how to do it in WET 4. Need a help to do the setting.

Thanks

**Comment by RobJohnston** [comment]
To sort the second column in ascending order:
```html
<table class="wb-tables table" data-wb-tables='{ "order" : [[1, "asc"]] }'>
```
See the documentation about sorting for the DataTable plug-in here:  http://www.datatables.net/examples/basic_init/table_sorting.html

**Comment by d02wang** [comment]
Thank you.

I change the quotations marks (exchange " with '); otherwise, there is an exception.

<table class="wb-tables table"  data-wb-tables="{ 'order' : [[1, 'asc']]}" >

does not change the default sorting order and the the sorting arrows (images) do not display.

**Comment by d02wang** [comment]
<table class="wb-tables table"  data-wb-tables="{ 'order' : [[1, 'asc']]}" >
does not change the default sorting order and the the sorting arrows (images) do not display.

**Comment by d02wang** [comment]
Thank you.

I change the quotations marks (exchange " with '); otherwise, there is an exception.

But it does not change the default sorting order and the the sorting arrows (images) do not display.

**Comment by RobJohnston** [comment]
I took that code from an application that I wrote that used WET v4.0.16.  It had worked fine, I believe.

The problem with the sorting arrows not displaying is likely due to the fonts not being downloaded on your network.  See https://github.com/wet-boew/wet-boew/issues/7429 for an explanation.

**Comment by d02wang** [comment]
It works for Tomcat, but not WebSphere.
Even it works for Tomcat, the table features above the table data such as "Show entries", "Search", and Sorting arrows disappear. I tested for Chrome, IE11, and firefox
the attributes for table tag is set to
class="wb-tables table  table-striped table-hover" data-wb-tables="{ 'order' : [[1, 'asc']]}"

whenever I use the attribute data-wb-tables, those properties above the table disappear.

**Comment by d02wang** [comment]
Sorry, I try it today again. It is working now. Maybe someone remove something in package before.

Thanks
