### ISSUE TITLE
WET4 developers

### ISSUE THREAD

**Issue by glevert** [wet-boew/wet-boew#7464]
Where can I see a list of WET 4 contributors?

Thanks,
Guy

**Comment by LaurentGoderre** [comment]
There are several repo so it's not all in one place but you can look at the Graph for each repo to see a list of contributions

**Comment by masterbee** [comment]
@glevert - did that answer your question or are you requesting a bit more information

**Comment by glevert** [comment]
Not really Mario. What is a repo?

**Comment by glevert** [comment]
Got it. Found the repo.

**Comment by hsrudnicki** [comment]
Based on the above, this issue can be closed, and just in case if otherwise, please update the status of this again, thank you
