### ISSUE TITLE
"Basic HTML version" being picked up by search engines

### ISSUE THREAD

**Issue by bsouster** [wet-boew/wet-boew#7468]
Recently we noticed Google indexed our Welcome Refugees section with this URL:
http://www.cic.gc.ca/english/refugees/welcome/index.asp?wbdisable=true (plugins auto-disabled)

Google is a huge source of traffic and this page had a lot of significance through Dec to Jan, so this probably disrupted the experience for a lot of users.

Is there a way to keep search engines from crawling the basic HTML version?

**Comment by RobJohnston** [comment]
Hi @bsouster , I think that they're talking about this over at https://github.com/wet-boew/wet-boew/issues/7457.

**Comment by LaurentGoderre** [comment]
duplicate of #7457
