### ISSUE TITLE
Calendar issues on daylight saving time days between (midnight - your local timezone offset) to midnight, only in some browsers

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/wet-boew#7470]
The unit tests have revealed a bug with the calendar plugin and dependencies (calendar of event and date picker polyfill) where selecting a date sometimes gives you the wrong date. It also means that build fail between 7PM EDT and 11:59 EDT.

**Comment by LaurentGoderre** [comment]
PR #7467 temporarily disabled the failing test but this still needs to be fixed

**Comment by shawnthompson** [comment]
Thanks @LaurentGoderre :+1:
