### ISSUE TITLE
Creation of a WET-BOEW-Moodle Repo

### ISSUE THREAD

**Issue by michael-milette** [wet-boew/wet-boew#7471]
Not sure where to ask this question. Who would I need to contact in order to create a new WET-BOEW-Moodle repository on this site?

If this isn't the right place to ask, a kind nudge in the right direction would be most appreciated.

Best regards,

Michael Milette

**Comment by hsrudnicki** [comment]
Is this still an issue?  Please update the status of this again, whether this can be closed or otherwise, thank you

**Comment by michael-milette** [comment]
This is still an issue. Nobody has answered the question for me and there is still no wet-boew-moodle repository on GitHub.

**Comment by shawnthompson** [comment]
@michael-milette Would you be interested in starting a Moodle variant of WET? We can create a repo and you can be lead on it.

**Comment by hsrudnicki** [comment]
Shouldn't this issue help be enclosed as well in #5574 ?  FYI, you can decide it, thank you

**Comment by michael-milette** [comment]
I would be interest in starting a Moodle variant of WET and taking the lead @shawnthompson. :-)

**Comment by shawnthompson** [comment]
Created the repo and added you as admin.
https://github.com/wet-boew/wet-boew-moodle
Let me know if you need help. 
Shawn.Thompson@servicecanada.gc.ca

**Comment by michael-milette** [comment]
Thank you @shawnthompson ! :-)
