### ISSUE TITLE
Multi-lingual functionality

### ISSUE THREAD

**Issue by krystofurr** [wet-boew/wet-boew#7477]
Hello,

 I was wondering what is meant by having " multi-lingual functionality " in the toolkit.  Does it mean that there are provided templates for each featured language ( such as the ones used with the jquery validation plugin ) ?.   Is the scope of the functionality based on the validation messages alone or is there something else available?  

Regards,
Chris

**Comment by LaurentGoderre** [comment]
Every plugin will display on the language of the page it's displayed in, not just the form validation.

**Comment by krystofurr** [comment]
Understood.  Thanks @LaurentGoderre
