### ISSUE TITLE
Small size screen: footer content is in the menu bar and at the bottom

### ISSUE THREAD

**Issue by sam-he** [wet-boew/wet-boew#7478]
For small size screen, the footer is still at the bottom, while the top menu bar has the footer content as well. Is this intentional or  is it a bug?

Extra small size screen has no footer menu.

Sam

**Comment by pjackson28** [comment]
It is intentional. It was requested from a usability perspective that in the small size screen the footer be replicated at the bottom and not just be in the mobile panel. I don't recall which issue that was discussed on but it is somewhere in the issue tracker.

**Comment by sam-he** [comment]
Thank you Paul. Then this issue can be closed. This does not introduce any accessibility issue anyway.
