### ISSUE TITLE
v4.0.21 release date?

### ISSUE THREAD

**Issue by d0d00n** [wet-boew/wet-boew#7480]
Hi, apologies if this is not the right avenue to inquire about this but this is the only link under Contact Us.

I know that the roadmap said that 2016-03-01 was the estimated date for v4.0.21 but is there anything more concrete now?

Thanks very much,

Don

**Comment by MaximMartel** [comment]
HI @d0d00n ,

We are looking forward to release v4.0.21 early next week. We still need to do some testing still but will be ready soon. 

Thank you,

Maxim

**Comment by d0d00n** [comment]
Sounds good, thanks for the response. Have a great weekend.
