### ISSUE TITLE
Pagination on data table - "previous" button loses focus after pressing enter

### ISSUE THREAD

**Issue by sliberatori79** [wet-boew/wet-boew#7481]
Currently, if you tab through the pagination buttons using your keyboard and press enter on the "previous" button, the button loses focus, which makes it difficult to navigate to previous views of the table using your keyboard. If you do this with the "next" button, the button keeps focus and you are able to navigate through the pagination buttons easily. I believe this should also be the case with the "previous" button.

Can this functionality be added?

https://wet-boew.github.io/v4.0-ci/demos/tables/tables-en.html

**Comment by hsrudnicki** [comment]
Does this stay an open issue or otherwise?  Please update the status of this again, thank you

**Comment by kodecount** [comment]
This could be tricky to add, but could be done in the [`init.dt draw.dt`](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/tables/tables.js#L151) events of the table, but would require a `setTimeout`.

Anyone have any more input/thoughts?
