### ISSUE TITLE
Date picker issue - focus not on today's date

### ISSUE THREAD

**Issue by sliberatori79** [wet-boew/wet-boew#7482]
Currently, with the date picker, using your keyboard, tab to the calendar icon and press the enter key on the keyboard to open it, today's date is highlighted, but is not in focus, seems to be misleading.

Documentation on how it should work:

If you look at http://www.w3.org/TR/wai-aria-practices/#datepicker it outlines how the date picker should behave using a keyboard and it indicates:

"Like other widgets, the date picker widget receives focus by tabbing into it. Once focus is received, focus is repositioned on today's date in a grid of days and weeks. A second tab will take the user out of the date picker widget. Focus initially is placed on today's date."

Due to the focus being on today's date by default, once the calendar is open, pressing enter should select today's date. If the user wants a different date, then they have to use the arrow keys to make that selection before they press enter.

This is an example of how it should work: http://www.oaa-accessibility.org/examplep/datepicker1/

To eliminate confusion, I believe we need today's date to have the focus.

Thoughts?

**Comment by LaurentGoderre** [comment]
This has been fixed in the calendar redesign that is in the latest development version and will be in the next release (v4.0.21)

**Comment by sliberatori79** [comment]
Great, thank you!
