### ISSUE TITLE
The input type="file" object value bilinguality

### ISSUE THREAD

**Issue by K-Stephens** [wet-boew/wet-boew#7484]
Good afternoon,

I was curious if there's a standard method to create an input of type="file" where the button face can show bilingual text. Trying to change the text within the input object directly is not working. I have seen many work-around options but I'd prefer to take your recommendation.

Thanks for any suggestions you can offer.

Kevin Stephens

**Comment by LaurentGoderre** [comment]
The language of the browser defines the language of the text displayed. The same is true for the date picker in Chrome for example. I don't think it's realistic to create workarounds for such functionality

**Comment by K-Stephens** [comment]
So when we give the user the functionality to view the language of the page in the language of the user's choice, we should be changing the browser's language so that the trickle effect changes the language of the file upload button?

**Comment by LaurentGoderre** [comment]
No. Unfortunately that is not something that we control. It is the user's browser settings, or even installed version, that dictates the language of these elements.

**Comment by K-Stephens** [comment]
I'm flabbergasted. I've developed public facing web sites for provincial and federal governments and the opportunity to change the official language of the page was always at the user's discretion. This is the only button type that doesn't allow us, naturally, to continue providing that 'luxury'. 

thank you for your feedback. I'm going to keep the ticket open a little longer as I confer with my team if you don't mind.

**Comment by RobJohnston** [comment]
There may be a nugget from [jQuery File Upload] (https://blueimp.github.io/jQuery-File-Upload/) that you could take inspiration from.

**Comment by nschonni** [comment]
See #2842

**Comment by K-Stephens** [comment]
Thank you very much all. I have a very clear idea of the issue and the current standard for the input file button. Although I'm a little wary about some of the work-arounds, at least now our default English text is explained.

Have a great day, your help is much appreciated.
