### ISSUE TITLE
Latest Version?

### ISSUE THREAD

**Issue by regio760** [wet-boew/wet-boew#7492]
Hello
I noticed that WET 4.0.20 was out in December and the releases are supposed to be quarterly.  I have been waiting patiently for the last 3 weeks for the next version - anybody know when it is expected?
Gotta ask.

**Comment by MaximMartel** [comment]
Hi,

I am currently doing release 4.0.21, it is very close of being completed.

Thanks,

**Comment by regio760** [comment]
That's most helpful - thank you.  I will wait for .21 to start implementing our upgrades.

**Comment by MaximMartel** [comment]
Please do :)
