### ISSUE TITLE
WET version 4.0.21 production files unavailable

### ISSUE THREAD

**Issue by nicolasraymond** [wet-boew/wet-boew#7495]
Hi,
On this page: http://wet-boew.github.io/wet-boew/docs/versions/dwnld-en.html#v4021, the production files for all themes are broken links.

**Comment by MaximMartel** [comment]
I am in the middle of finishing up the build, and need to upload all the production files. Please be patient, as its very close of being completed.

**Comment by nicolasraymond** [comment]
No problem

**Comment by LaurentGoderre** [comment]
The release is all done!

**Comment by MaximMartel** [comment]
All good :) :+1:

**Comment by nicolasraymond** [comment]
Thanks guys!
