### ISSUE TITLE
WET3 - Redirect Vulnerability

### ISSUE THREAD

**Issue by afull** [wet-boew/wet-boew#7496]
Good day,

We received the following message regarding a potential security vulnerability in the WET3 Framework.  I realize that WET3 is no longer supported but I would like to know if this issue had been previously addressed or if any other information is available regarding this topic.  

We are currently using WET4 for the main EC Internet site.  Unfortunately some older applications still on the internet have not been updated to WET4 yet and are still using the WET3 theme.  

The security risk identified is an ‘Open redirection’ vulnerability within the following file via the statements below.  Do you know if this vulnerability is legitimate, and if so what would be the best way to resolve the issue?

../../dist/js/css/**pe-ap-min.css**

_“The application may be vulnerable to DOM-based open redirection. Data is read from window.location and passed to window.location via the following statements:”_

•	var d=window.location.toString(),f=g.button;
•	d=d.replace(/_f\./,"_e.").replace(/-fra\./,"-eng.")
•	d=d.replace(/lang=eng/,"lang=fra")
•	window.location=d;

_“An attacker may be able to use the vulnerability to construct a URL that, if visited by another application user, will cause a redirection to an arbitrary external domain. This behavior can be leveraged to facilitate phishing attacks against users of the application.”_

**Comment by pjackson28** [comment]
I don't know about the legitimacy of the alleged vulnerability or what could be a possible resolution but based upon the code snippet it seems to be from the [WET3 language selector plugin](http://wet-boew.github.io/wet-boew-legacy/v3.1/demos/langselect/lang-js-en.html). If that is the case then the code shouldn't be executed if you aren't using that plugin (which the plugin is activated using the <code>wet-boew-langselect</code> class).

**Comment by RobJohnston** [comment]
@afull Since you're using WET3, I'll mention another problem with the pe-ap.js file in case you missed it... see https://github.com/wet-boew/wet-boew/issues/7379

**Comment by nschonni** [comment]
> An attacker may be able to use the vulnerability to construct a URL that, if visited by another application user, will cause a redirection to an arbitrary external domain

The [JS you pointed out](https://github.com/wet-boew/wet-boew-legacy/blob/v3.1/src/js/workers/langselect.js#L19) doesn't take any user input or redirect based off of query values so I'm not seeing the injection issue here. https://www.owasp.org/index.php/Open_redirect

**Comment by LaurentGoderre** [comment]
Agreed! The modification to the URL are pretty trivial.

**Comment by afull** [comment]
Thanks for the feedback.
I will share this with our IT Security group.
Please consider this ticket closed.

**Comment by afull** [comment]
Thanks RobJohnston, regarding issue  #7379.
We were aware of it, and the issue was addressed.
