### ISSUE TITLE
Issue with datatables filter and tabbed interface

### ISSUE THREAD

**Issue by dsamojlenko** [wet-boew/wet-boew#7497]
We have a tabbed interface that contains a datatable.  When typing in the Filter items search, after each keypress the text field loses focus and you can't continue typing until you click back into the text field.

The Filter items feature works on other pages (without tabs) fine.

This all worked fine in 4.0.18 and seems to be broken since.

**Comment by causerdan** [comment]
We have this same issue in #7385 .  There is a workaround currently but no word on an approach for a permanent fix.
