### ISSUE TITLE
Subsite bar color

### ISSUE THREAD

**Issue by regio760** [wet-boew/wet-boew#7498]
Is there any way to change the color of the subsite bar using classes in WET?  
I created a custom.css file and gave it the following:

#wb-bnr-ss-red {
	background: #B30000;
	border-top:1px solid #fff;
	-webkit-box-shadow:inset 0 1px 5px;
	box-shadow:inset 0 1px 5px
}

then changed &lt;div id="wb-bnr-ss"&gt; to &lt;div id="wb-bnr-ss-red"&gt;.

Any way to do this without a custom css but rather just with WET components?

**Comment by LaurentGoderre** [comment]
I assume you are asking about the intranet theme? Can you please open an issue with that theme?

**Comment by regio760** [comment]
My apologies - didn't realize it was a separate group.

**Comment by MaximMartel** [comment]
Can we close this issue @regio760 @LaurentGoderre

**Comment by RobJohnston** [comment]
This issue got moved to https://github.com/wet-boew/theme-gc-intranet/issues/157.

**Comment by MaximMartel** [comment]
Ok, ill close this issue since its a duplicate.
