### ISSUE TITLE
sort datatable  column of French date

### ISSUE THREAD

**Issue by sam-he** [wet-boew/wet-boew#7500]
Hi,

We can sort datatable using English date, But French page has issue to sort the same column in French date format "DD MMM YYYY". Is there a easy way to solve it using WET plugin, or we need to use other plug-in? 
Example table: the second table on this page: http://meteo.gc.ca/eer/vaac/index_f.html

Sam

**Comment by LaurentGoderre** [comment]
For the purpose of sorting, dates should always be in ISO format (YYYY-MM-DD)

**Comment by sam-he** [comment]
Thank you Laurent.
