### ISSUE TITLE
Session Timeout Plugin

### ISSUE THREAD

**Issue by krystofurr** [wet-boew/wet-boew#7508]
Hello,

Started using the session timeout plugin and I like the options available.  Only thing is that when I attempt to load it into a page via " include " ( through say JSP ) or some kind of template system, it seems to only provide the default values and not the ones that are set in the template itself.  There is likely something I'm doing incorrectly with it.  Do I need to initialize anything prior to it being injected?  It works fine if I copy the paste the session element statically into the page but I would like to have a single page with it defined and inject in multiple pages.  Thanks

**Comment by rlambert27** [comment]
Hello,

No you don't need to initialize prior to having it injected in your page. I suggest you have a look at the sample Java project that we have for the Centrally Deployed Templates Solution (CDTS) - http://www.gcpedia.gc.ca/wiki/Centrally_Deployed_Templates_Solution_%28CDTS%29/GoC_.NET_template_guide#Session_Timeout

The sample Java project has an example page where the variables are set in a config file and then applied across the board to all pages.

Hope that helps, let me know!

**Comment by krystofurr** [comment]
Thanks rlambert.  I'll definitely check that out.  Seems to be down at the moment.

**Comment by crochefort** [comment]
@krystofurr it's not down ... it's just a page available to gouv of Canada employee at Work!

**Comment by hsrudnicki** [comment]
Based on the above, as well already closed and related issue(s), see #7654,  this can be closed as resolved.
If you think otherwise, please update the status of this again, thank you
