### ISSUE TITLE
IE 9 and above sometimes causes blank pages to print (WET3)

### ISSUE THREAD

**Issue by aaornrylow** [wet-boew/wet-boew#7513]
Hi,

As you'll see on [this page](http://crtc.gc.ca/eng/archive/2016/2016-102.htm), if you try to print, it creates a large amount of blank pages at the end (only in Internet Explorer 9 and above). The document should be 27 pages in print, but IE wants to print 52 pages.

I think I've narrowed it down to **dist/js/jquerymobile/jquery.mobile.min.js** as the culprit. It also seems to happen more on pages with footnotes, but it's unpredictable.

**Comment by LaurentGoderre** [comment]
Unfortunately WET3 is no longer supported

**Comment by hsrudnicki** [comment]
Based on the above, this can be closed. If you think otherwise, please update the status of this again, thank you
