### ISSUE TITLE
datepicker (input type="date") icon not showing next to the textbox

### ISSUE THREAD

**Issue by jonjones** [wet-boew/wet-boew#7517]
When configuring the datepicker, if the id of the control contains a period "." the icon for the datepicker does not show up (IE or Firefox). I had previously submitted this issue in WET 3 and it was promptly fixed but the issues seems to have returned in WET 4.

**Comment by LaurentGoderre** [comment]
Having period in IDs s likely to create way more than this problem since it's a reserved character for CSS selector (which is use to find elements in the DOM). We can fix this instance but it's likely to come up in other places.
