### ISSUE TITLE
Set `no-misspelled-properties` to error when sass-lint fixes nested property

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/wet-boew#7525]
sasstools/sass-lint#352

**Comment by hsrudnicki** [comment]
Based on the above, this can be closed as resolved/fixed.  If you think otherwise, please update the status of this again, thank you

**Comment by nschonni** [comment]
The upstream issue has been fixed, but the depenency would need to be bumped here get the fix and the configuration updated https://github.com/wet-boew/wet-boew/blob/master/.sass-lint.yml#L31

**Comment by LaurentGoderre** [comment]
Sass-lint doesn't even run anymore....
