### ISSUE TITLE
Data Table not resetting input fields that are not currently displayed

### ISSUE THREAD

**Issue by esdcpll** [wet-boew/wet-boew#7532]
I'm encountering a possible issue with the data table. Let me know if this is something you’ve encountered before/known problem… and/or if you have any suggestions as to how to fix/work around this.

(I’ve tried what I describe below in both Firefox and IE11)

Situation:

I have an application which has a data table within a form.  A column of the table contains a checkbox input on each row.  The table displays 10 rows of many (35 in my test) and is sorted by default on the col1+col2 columns.  After the table, there is a button type=”reset”.  (see HTML sample at the end)

To reproduce the problem:

0-     The web page appears
1-	Click on any other column header to change the sort order
2-	Click the checkbox on a few rows that do not show up on page 1 in the default sort order 
3-	Click the “Reset” button
    The sort order gets reset, back to page 1 (which is fine)
4-	Click on the same column header as in step 1
    **The checkbox clicked during step 2 are still checked even though reset was clicked**

However, the following works:

0-     The web page appears
1-	Without changing the sort order, click on the checkbox for a few rows that won’t show up after changing the sort order
2-	Click on a column header to change the sort order to have at least a few of the checked rows disappear
3-	Click the “Reset” button
    The sort order gets reset, back to page 1
    The checkbox clicked during step 1 are correctly no longer clicked 

If it helps, here is a partial HTML showing the definition of the form+table+button:

> 
&lt;form name="resultsForm" method="post" action="/cs/results.do">
... (some inputs type=”hidden”)
&lt;table border="1" id="results_table" 
  class="wb-tables table table-bordered table-striped table-hover table_floating"
  style="white-space:normal;text-align:left;"
  data-wb-tables='{ "lengthMenu": [ [10, -1], [10, "All"] ], "aaSorting": [[ 1, "asc" ], [ 2, "asc" ], [ 4, "asc" ], [ 3, "asc" ]], "columnDefs": [ {"bSortable": false, "aTargets": [0] }, {"type": "html", "targets": [2, 3] } ] }'
  summary="Find Client Search Results"
  data-number-of-optional-columns="1">
&lt;thead>
  &lt;tr>
    &lt;th class="table_cell_floating">&lt;/th>
    &lt;th class="wrap_table_cell_contents table_top_cell_floating_sibling">Surname&lt;/th>
    &lt;th class="wrap_table_cell_contents table_top_cell_floating_sibling">First Name&lt;/th>
    &lt;th class="wrap_table_cell_contents table_top_cell_floating_sibling">Identifier&lt;/th>
... (other columns)
  &lt;/tr>
&lt;/thead>
&lt;tfoot class="StandardVersionWetOnly">
  &lt;tr>
    &lt;td class="table_cell_floating">&lt;/td>
    &lt;td>&lt;/td>
    &lt;td>&lt;/td>
    &lt;td>&lt;/td>
... (other columns)
  &lt;/tr>
&lt;/tfoot>
&lt;tbody>
  &lt;tr>
    &lt;td class="table_cell_input table_cell_floating floating_checkbox">
      &lt;input type="checkbox" name="chkSelected" value="123456" class="searchResultsClientCheckBox searchResultsClientWithSinCheckBox" id="clientCheckbox123456" >
      &lt;input type="hidden" name="hdn616936179378" value="123456789">
    &lt;/td>
    &lt;td class="table_cell_text_nowrap">SMITH&lt;/td>
    &lt;td class="table_cell_text_nowrap">&lt;A REF="javascript:submitFormWithIdentifier('resultsForm',123456,'clientprofile');">John&lt;/A>
    &lt;/td>
    &lt;td class="table_cell_text">&lt;A HREF="javascript:submitFormWithIdentifier('resultsForm',123456,'identifiers');">123456&lt;/A>
    &lt;/td>
... (other columns)
  &lt;/tr>
... (other rows)
&lt;/tbody>
&lt;/table>
&lt;div class="clear">&lt;/div>
&lt;div class="formbuttons">
  &lt;button type="reset" id="findClientResultsFormResetButton" class="btn btn-disabled" formnovalidate disabled>Reset&lt;/button>
  &lt;button type="submit" id="consolidateButton" class="btn btn-disabled" disabled>Consolidate&lt;/button>
&lt;/div>
&lt;/form>

**Comment by hsrudnicki** [comment]
Is this still an issue? Please update the status of this again, whether this can be closed or otherwise, thank you

**Comment by esdcpll** [comment]
No longer a problem
