### ISSUE TITLE
The font awesome icons do not display within Treasury Board. 

### ISSUE THREAD

**Issue by mhutchis** [wet-boew/wet-boew#7533]
How can we see them?

**Comment by RobJohnston** [comment]
Hi @mhutchis ... it's Mike, right?

I'm going to bet that font downloads are blocked by a security policy.  I've seen this issue come up with WET a few time.  For example,  https://github.com/wet-boew/wet-boew/issues/5693

**Comment by hsrudnicki** [comment]
Based on the above, this issue can be closed as resolved. If you think otherwise, please update the status of this again, thank you
