### ISSUE TITLE
Disable Mobile theme ?

### ISSUE THREAD

**Issue by KingBain** [wet-boew/wet-boew#7534]
Is there a way to disable the mobile browser support of the theme. I'm looking for a cut down version of the GOC intranet theme. I'm trying to apply WET to a webapp that doesn't want to be themed :/

John

**Comment by RobJohnston** [comment]
Similar to https://github.com/wet-boew/wet-boew/issues/6482?

**Comment by KingBain** [comment]
similar enough ... would you know what java script file is responsible for flipping the browser into mobile mode ? I'll fork the file and cut'er up

**Comment by hsrudnicki** [comment]
Based on the above, this issue can be closed as resolved.  If you think otherwise, please update the status of this again, thx
