### ISSUE TITLE
Multimedia Player - Video

### ISSUE THREAD

**Issue by phuppe** [wet-boew/wet-boew#7535]
WET Version 4.0.21

HTML5 <video> tag supports "autoplay", but the video multimedia player does not seem to support that.  If I add the attribute "autoplay" on the "<video> tag, it does not automatically play the video as expected.

**Comment by rlambert27** [comment]
I'm not sure if it's related but you'll have to be careful about using the "autoplay" attribute. It could easily contravene success criteria 1.4.2 of WCAG (https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-dis-audio.html).

**Comment by DK-TBS** [comment]
I wouldn't be surprised if the WET media player has been intentionally configured to ignore the ol' autoplay attribute.  Rigging a video to start up on its own without user input is a famously unfriendly thing to do   :)

**Comment by phuppe** [comment]
ok, thanks for the comments.  I will not use it.
