### ISSUE TITLE
Form validation: 

### ISSUE THREAD

**Issue by pixim** [wet-boew/wet-boew#7543]
Hi, Compatible Browsers IE7, IE8, IE9, IE10, IE11, Firefox, Safari, Opera, Chrome or not?

**Comment by MaximMartel** [comment]
IE10, IE11, Firefox, Safari, and Chrome are all compatible. IE7 to IE9, are no longer supported. Opera is not present here : https://github.com/wet-boew/wet-boew/issues/6341

**Comment by hsrudnicki** [comment]
So based on the above, this can be closed. If you think otherwise, please update the status of this again, thank you
