### ISSUE TITLE
MathML rendering

### ISSUE THREAD

**Issue by gdanova** [wet-boew/wet-boew#7546]
We've noticed some differences in rendering MathML in various browsers, but this one is most bothersome. The parentheses in IE11 and Chrome look unbalanced in size.
![mathie](https://cloud.githubusercontent.com/assets/1898789/15227607/05d088be-1856-11e6-82ec-c46efad54b88.png)

Firefox use a consistent, smaller size for the exact same formula.
![mathff](https://cloud.githubusercontent.com/assets/1898789/15227609/0b8ae272-1856-11e6-809b-18dc6f7e30b3.png)

Has anyone encountered this? Is it simply a rendering issue?

**Comment by pjackson28** [comment]
Just a MathJax rendering issue. Firefox has native MathML support while Chrome and IE11 do not so have to rely upon the MathML polyfill which loads MathJax for the rendering.

**Comment by hsrudnicki** [comment]
Can be this closed based on the above or otherwise?

**Comment by gdanova** [comment]
Just closed it.

Thanks.

</gd>
