### ISSUE TITLE
Need for a WYSIWYG rich text editor.

### ISSUE THREAD

**Issue by idurotPauley** [wet-boew/wet-boew#7547]
I am looking for a WYSIWYG rich text editor to use for an application I am developing in ASP.net. I was wondering if there is a plugin that has been implemented for WET 4.0 that I can use.

Thanks,
Pauley

**Comment by rlambert27** [comment]
I don't believe WET has any WYSIWYG editors. You can probably look at something like TinyMCE or CKEditor which has an accessibility tips page:

https://www.tinymce.com/docs/advanced/accessibility/
http://docs.cksource.com/CKEditor_3.x/Accessibility

However i'm not certain if they are 100% accessible to WCAG 2.0 (AA).

**Comment by hsrudnicki** [comment]
Does this remain an issue or otherwise? Please update the status of this, thank you
