### ISSUE TITLE
Updating from WET 4.0.06 to 4.0.20 

### ISSUE THREAD

**Issue by Sburbidge** [wet-boew/wet-boew#7548]
I am new with our organization and also new with working beyond content management. It is my understanding that from time to time the WET template will need to be updated on our website. Would you guide me as to where to get these updated templates? Would anything else require to be updated simultaneously in the process?

**Comment by rlambert27** [comment]
You can download WET and previous versions here:

http://wet-boew.github.io/wet-boew/docs/versions/dwnld-en.html

Or you can use a central solution like the CDTS to keep up to date:

http://www.gcpedia.gc.ca/wiki/Centrally_Deployed_Templates_Solution_%28CDTS%29

**Comment by Sburbidge** [comment]
Thank you for the prompt response.

Yes I got that far. I did get on this page. Do I need to download all of the “source code” & “production files” for all “6 themes”? If so I did a test by downloading the WET Source code. I noticed that are 700 files within the ZIP file and a comment file with a one-line containing alpha-numeral info I do not understand. How would I know where to put these files as there are no explanation?

That being said, if I may make a suggestion. It would be nice for this information (where to replace existing files pertinent to each specific download) to be included in the Comment window that opens up with the Zip file….

Bonne journée / Have a nice day

Web Support Officer
Military Police Complaints Commission of Canada / Government of Canada
suzanne.burbidge@mpcc-cppm.gc.ca<mailto:suzanne.burbidge@mpcc-cppm.gc.ca>
Monday, Wednesday & Friday: 613-769-9006 or 613-943-5577
Tuesday & Thursday: 613-834-9957 / Facsimile: 613-947-5713

Agente de soutien du Web
Commission d'examen des plaintes concernant la police militaire du Canada / Gouvernement du Canada
suzanne.burbidge@cppm-mpcc.gc.ca<mailto:suzanne.burbidge@cppm-mpcc.gc.ca>
Lundi, mercredi & vendredi : 613-769-9006 ou 613-943-5577
Mardi & jeudi : 613-834-9957 / Télécopieur: 613-947-5713

**Comment by rlambert27** [comment]
You don't need to download source code unless you want to look at the uncompressed/unminified files. Otherwise download the production files for the theme you are using. 

From your website URL (http://mpcc-cppm.gc.ca/index-eng.aspx) I'm assuming you are using the Usability theme, so you would download under v4.0.21 the production files for "Government of Canada Web Usability".

You can then follow the instructions here (http://wet-boew.github.io/themes-dist/theme-gcwu-fegc/docs/ref/theme-gcwu-fegc/theme-gcwu-fegc-en.html) for using that theme. 

Depending on how your website is setup you'll need to overwrite your existing files with the new ones. I'm not sure if any HTML structural changes have been done since v4.0.6 but I'm assuming yes so you'll need to verify if you need to update any HTML structure elements.

It should be pretty simple to find out where to put the files as the existing website should use a folder structure similar to what you have downloaded. Looking at your source code it seems like all your files are in the /dist/ folder.

**Comment by Sburbidge** [comment]
Sorry I forgot to add that are pages are .aspx

I believe our site uses Canada.ca theme templates. Maybe if you can have a quick look at our site, and confirm this for me? IF that is the case, do I simply download the Canada.ca theme v4.0.21 under Static pages (version / run)?

[cid:image001.png@01D1AD0C.5531B9B0]

Bonne journée / Have a nice day

Web Support Officer
Military Police Complaints Commission of Canada / Government of Canada
suzanne.burbidge@mpcc-cppm.gc.ca<mailto:suzanne.burbidge@mpcc-cppm.gc.ca>
Monday, Wednesday & Friday: 613-769-9006 or 613-943-5577
Tuesday & Thursday: 613-834-9957 / Facsimile: 613-947-5713

Agente de soutien du Web
Commission d'examen des plaintes concernant la police militaire du Canada / Gouvernement du Canada
suzanne.burbidge@cppm-mpcc.gc.ca<mailto:suzanne.burbidge@cppm-mpcc.gc.ca>
Lundi, mercredi & vendredi : 613-769-9006 ou 613-943-5577
Mardi & jeudi : 613-834-9957 / Télécopieur: 613-947-5713

From: Burbidge, Suzanne
Sent: May-13-16 11:30 AM
To: 'wet-boew/wet-boew'
Subject: RE: [wet-boew/wet-boew] Updating from WET 4.0.06 to 4.0.20 (#7548)

Thank you for the prompt response.

Yes I got that far. I did get on this page. Do I need to download all of the “source code” & “production files” for all “6 themes”? If so I did a test by downloading the WET Source code. I noticed that are 700 files within the ZIP file and a comment file with a one-line containing alpha-numeral info I do not understand. How would I know where to put these files as there are no explanation?

That being said, if I may make a suggestion. It would be nice for this information (where to replace existing files pertinent to each specific download) to be included in the Comment window that opens up with the Zip file….

Bonne journée / Have a nice day

Web Support Officer
Military Police Complaints Commission of Canada / Government of Canada
suzanne.burbidge@mpcc-cppm.gc.ca<mailto:suzanne.burbidge@mpcc-cppm.gc.ca>
Monday, Wednesday & Friday: 613-769-9006 or 613-943-5577
Tuesday & Thursday: 613-834-9957 / Facsimile: 613-947-5713

Agente de soutien du Web
Commission d'examen des plaintes concernant la police militaire du Canada / Gouvernement du Canada
suzanne.burbidge@cppm-mpcc.gc.ca<mailto:suzanne.burbidge@cppm-mpcc.gc.ca>
Lundi, mercredi & vendredi : 613-769-9006 ou 613-943-5577
Mardi & jeudi : 613-834-9957 / Télécopieur: 613-947-5713

**Comment by rlambert27** [comment]
I did have a look at your website (this one http://mpcc-cppm.gc.ca/index-eng.aspx) and it's not using the Canada.ca theme, you can see the difference by going to canada.ca.

If you want to implement the CDTS and the Canada.ca theme it will be a little more complicated than simply downloading the static files. You'll need to follow the instructions in the implementation guide which is here : http://www.gcpedia.gc.ca/gcwiki/images/6/62/CDTS_implementation_EN_v4_7.docx

Otherwise if you are familiar with .NET you can download and use our pre-made .NET templates which have the CDTS built-in. These can be found here : http://www.gcpedia.gc.ca/wiki/Centrally_Deployed_Templates_Solution_%28CDTS%29/GoC_.NET_template_guide

Hope that helps!

**Comment by Sburbidge** [comment]
Good morning,

Thanks for the info. That is a bit more than what I can chew at this point. Is there a training I could take to help me understand the process?

Out of curiosity, based on our web-site, copying the updated files from Download - v4.0.21 source code - Government of Canada Web Usability theme (theme only)<https://github.com/wet-boew/theme-gcwu-fegc/archive/v4.0.21.zip> and replacing the existing files would not be sufficient enough?

Thank you.


Bonne journée / Have a nice day

Web Support Officer
Military Police Complaints Commission of Canada / Government of Canada
suzanne.burbidge@mpcc-cppm.gc.ca<mailto:suzanne.burbidge@mpcc-cppm.gc.ca>
Monday, Wednesday & Friday: 613-769-9006 or 613-943-5577
Tuesday & Thursday: 613-834-9957 / Facsimile: 613-947-5713

Agente de soutien du Web
Commission d'examen des plaintes concernant la police militaire du Canada / Gouvernement du Canada
suzanne.burbidge@cppm-mpcc.gc.ca<mailto:suzanne.burbidge@cppm-mpcc.gc.ca>
Lundi, mercredi & vendredi : 613-769-9006 ou 613-943-5577
Mardi & jeudi : 613-834-9957 / Télécopieur: 613-947-5713

**Comment by rlambert27** [comment]
Hi, it's possible that it would be enough but I can't be 100% certain. WET v4.0.6 was released back in September 2014, so we're almost 2 years later for the next version. That's quite a few minor upgrades and to be honest I wouldn't be comfortable just replacing the files and pushing to production. 

I'm sure if any issues crop up they should be simple to fix but a thorough check would be required.

**Comment by Sburbidge** [comment]
Thanks. Is there a training provided by the GoC that can be taken?

Bonne journée / Have a nice day

Web Support Officer
Military Police Complaints Commission of Canada / Government of Canada
suzanne.burbidge@mpcc-cppm.gc.ca<mailto:suzanne.burbidge@mpcc-cppm.gc.ca>
Monday, Wednesday & Friday: 613-769-9006 or 613-943-5577
Tuesday & Thursday: 613-834-9957 / Facsimile: 613-947-5713

Agente de soutien du Web
Commission d'examen des plaintes concernant la police militaire du Canada / Gouvernement du Canada
suzanne.burbidge@cppm-mpcc.gc.ca<mailto:suzanne.burbidge@cppm-mpcc.gc.ca>
Lundi, mercredi & vendredi : 613-769-9006 ou 613-943-5577
Mardi & jeudi : 613-834-9957 / Télécopieur: 613-947-5713

**Comment by rlambert27** [comment]
Hi,

I don't know of any courses offered by the GoC but Eliquo does offer courses related to WET:

- http://eliquo.ca/en/training/course.php?crs=EWCL401

They have other courses on WET as well:

http://eliquo.ca/en/search.php?q=WET

**Comment by Bgolden67** [comment]
I was about to suggest the same thing @rlambert27 just suggested.. my team has taken it and the free refresher they offer and it helps understand the structure of the templates.

**Comment by Sburbidge** [comment]
Yes, I’ve taken that one about a year ago. However, the course was developed to cover how to use the various css, etc. and how to better customize the content of pages, not so much about how to download/upgrade the background files.

Thank you nonetheless.

Bonne journée / Have a nice day

Web Support Officer
Military Police Complaints Commission of Canada / Government of Canada
suzanne.burbidge@mpcc-cppm.gc.ca<mailto:suzanne.burbidge@mpcc-cppm.gc.ca>
Monday, Wednesday & Friday: 613-769-9006 or 613-943-5577
Tuesday & Thursday: 613-834-9957 / Facsimile: 613-947-5713

Agente de soutien du Web
Commission d'examen des plaintes concernant la police militaire du Canada / Gouvernement du Canada
suzanne.burbidge@cppm-mpcc.gc.ca<mailto:suzanne.burbidge@cppm-mpcc.gc.ca>
Lundi, mercredi & vendredi : 613-769-9006 ou 613-943-5577
Mardi & jeudi : 613-834-9957 / Télécopieur: 613-947-5713

**Comment by Sburbidge** [comment]
Burbidge, Suzanne would like to recall the message, "[wet-boew/wet-boew] Updating from WET 4.0.06 to 4.0.20  (#7548)".

**Comment by Sburbidge** [comment]
Yes, I’ve taken one about a year ago. However, I will look at what else they have. They may just have what I need. Thank you.

Bonne journée / Have a nice day

Web Support Officer
Military Police Complaints Commission of Canada / Government of Canada
suzanne.burbidge@mpcc-cppm.gc.ca<mailto:suzanne.burbidge@mpcc-cppm.gc.ca>
Monday, Wednesday & Friday: 613-769-9006 or 613-943-5577
Tuesday & Thursday: 613-834-9957 / Facsimile: 613-947-5713

Agente de soutien du Web
Commission d'examen des plaintes concernant la police militaire du Canada / Gouvernement du Canada
suzanne.burbidge@cppm-mpcc.gc.ca<mailto:suzanne.burbidge@cppm-mpcc.gc.ca>
Lundi, mercredi & vendredi : 613-769-9006 ou 613-943-5577
Mardi & jeudi : 613-834-9957 / Télécopieur: 613-947-5713

**Comment by Sburbidge** [comment]
Thank you for the insightful help. I will definitely look into it.

Bonne journée / Have a nice day

Web Support Officer
Military Police Complaints Commission of Canada / Government of Canada
suzanne.burbidge@mpcc-cppm.gc.ca<mailto:suzanne.burbidge@mpcc-cppm.gc.ca>
Monday, Wednesday & Friday: 613-769-9006 or 613-943-5577
Tuesday & Thursday: 613-834-9957 / Facsimile: 613-947-5713

Agente de soutien du Web
Commission d'examen des plaintes concernant la police militaire du Canada / Gouvernement du Canada
suzanne.burbidge@cppm-mpcc.gc.ca<mailto:suzanne.burbidge@cppm-mpcc.gc.ca>
Lundi, mercredi & vendredi : 613-769-9006 ou 613-943-5577
Mardi & jeudi : 613-834-9957 / Télécopieur: 613-947-5713

**Comment by Sburbidge** [comment]
Thank you for the information.
I also found this another training, which is given tomorrow, which could be appropriate for what I need. In a nutshell, what I would like to get out on receiving training is how to do the quarterly updates, based on our website<http://mpcc-qc/index-eng.aspx>, which you have determined to be Government of Canada Web Usability …and, if it has an impact, we will start posting on Open Government with the next proactive disclosure.
I’ve contacted Eliquo to found out which one would be most appropriate but I haven’t heard from them yet. Could you give me your 2 cents worth to which would be most appropriate between http://eliquo.ca/en/training/course.php?crs=EWCL401 & http://eliquo.ca/en/training/course.php?crs=EWCL403, if not both and why?
Thank you.



Bonne journée / Have a nice day

Web Support Officer
Military Police Complaints Commission of Canada / Government of Canada
suzanne.burbidge@mpcc-cppm.gc.ca<mailto:suzanne.burbidge@mpcc-cppm.gc.ca>
Monday, Wednesday & Friday: 613-769-9006 or 613-943-5577
Tuesday & Thursday: 613-834-9957 / Facsimile: 613-947-5713

Agente de soutien du Web
Commission d'examen des plaintes concernant la police militaire du Canada / Gouvernement du Canada
suzanne.burbidge@cppm-mpcc.gc.ca<mailto:suzanne.burbidge@cppm-mpcc.gc.ca>
Lundi, mercredi & vendredi : 613-769-9006 ou 613-943-5577
Mardi & jeudi : 613-834-9957 / Télécopieur: 613-947-5713

**Comment by Bgolden67** [comment]
the one I think both @rlambert27 and myself were probably thinking of was EWCL401
It's definitely the one to take to understand how WET packages are built and how to use them,

**Comment by Sburbidge** [comment]
Awesome. Thank you.

Bonne journée / Have a nice day

Web Support Officer
Military Police Complaints Commission of Canada / Government of Canada
suzanne.burbidge@mpcc-cppm.gc.ca<mailto:suzanne.burbidge@mpcc-cppm.gc.ca>
Monday, Wednesday & Friday: 613-769-9006 or 613-943-5577
Tuesday & Thursday: 613-834-9957 / Facsimile: 613-947-5713

Agente de soutien du Web
Commission d'examen des plaintes concernant la police militaire du Canada / Gouvernement du Canada
suzanne.burbidge@cppm-mpcc.gc.ca<mailto:suzanne.burbidge@cppm-mpcc.gc.ca>
Lundi, mercredi & vendredi : 613-769-9006 ou 613-943-5577
Mardi & jeudi : 613-834-9957 / Télécopieur: 613-947-5713

**Comment by Sburbidge** [comment]
I was just asked a question. Since content from all GoC orgnizations will be migrated to Canada.ca by the end of the next calendar year, how important is it to update the templates and other related files?

Bonne journée / Have a nice day

Web Support Officer
Military Police Complaints Commission of Canada / Government of Canada
suzanne.burbidge@mpcc-cppm.gc.ca<mailto:suzanne.burbidge@mpcc-cppm.gc.ca>
Monday, Wednesday & Friday: 613-769-9006 or 613-943-5577
Tuesday & Thursday: 613-834-9957 / Facsimile: 613-947-5713

Agente de soutien du Web
Commission d'examen des plaintes concernant la police militaire du Canada / Gouvernement du Canada
suzanne.burbidge@cppm-mpcc.gc.ca<mailto:suzanne.burbidge@cppm-mpcc.gc.ca>
Lundi, mercredi & vendredi : 613-769-9006 ou 613-943-5577
Mardi & jeudi : 613-834-9957 / Télécopieur: 613-947-5713

**Comment by rlambert27** [comment]
I suggest you contact your departmental WS CoE rep (http://publiservice.tbs-sct.gc.ca/ws-nw/wc-cw/wsce-cenw-eng.asp) for more information on this. You can also review the Web Renewal (WRi) Toolkit page (http://www.gcpedia.gc.ca/wiki/Web_Renewal_Toolkit) to find out who your onboarding lead for your department is. Worst case if you can't find it you can email the WRi team for help: ws-nw@tbs-sct.gc.ca.

Depending on where you are in the on boarding schedule it might be preferable to simply wait to be on boarded into Canada.ca. However I would leave that up to your department's on boarding lead to make that decision.

**Comment by Sburbidge** [comment]
Thank you for the very informative info.

Bonne journée / Have a nice day

Web Support Officer
Military Police Complaints Commission of Canada / Government of Canada
suzanne.burbidge@mpcc-cppm.gc.ca<mailto:suzanne.burbidge@mpcc-cppm.gc.ca>
Monday, Wednesday & Friday: 613-769-9006 or 613-943-5577
Tuesday & Thursday: 613-834-9957 / Facsimile: 613-947-5713

Agente de soutien du Web
Commission d'examen des plaintes concernant la police militaire du Canada / Gouvernement du Canada
suzanne.burbidge@cppm-mpcc.gc.ca<mailto:suzanne.burbidge@cppm-mpcc.gc.ca>
Lundi, mercredi & vendredi : 613-769-9006 ou 613-943-5577
Mardi & jeudi : 613-834-9957 / Télécopieur: 613-947-5713

**Comment by hsrudnicki** [comment]
Based on the above, this can be closed as resolved. Just in case, if you think otherwise, please update the status of this again. Thank you.
