### ISSUE TITLE
Tabbed interface Carousel

### ISSUE THREAD

**Issue by DHaslip** [wet-boew/wet-boew#7549]
Has anyone customized the WET4 carousel in a similar way to what is done here:

http://www.budget.gc.ca/2016/tool-outil/ccb-ace-en.html

**Comment by nschonni** [comment]
That page doesn't have a carousel, unless are you talking about the custom Icon submenu that links to other pages at the top? If it's the icon menu at the top, i'd avoid copying the markup as it looks like the tried to mark the links as `<figures>` for the icons and also doesn't work in mobile mode.

**Comment by DHaslip** [comment]
Yes, I'm talking about the custom icon submenu with links to other pages at the top.  Our client wants to use something like this for a type of quick links/nagivation in their application, and I was wondering if anyone had tried to something similar using any of the existing WET plugins?

**Comment by nschonni** [comment]
If it is for a Canada.ca site, you'll probably need to follow the specs from https://wet-boew.github.io/themes-dist/GCWeb/index-en.html
If it's not, I'd still suggest using the secondary menu layout like https://wet-boew.github.io/themes-dist/theme-base/content-secmenu-en.html since it will correctly integrate on mobile menu and be read correctly by assistive technologies.

**Comment by hsrudnicki** [comment]
Can be this issue closed based on the above or otherwise? Please update the status of this again, thank you

**Comment by DHaslip** [comment]
No, this issue should not be closed.  We still have a requirement for a carousel, similar to the one found here:  http://owlgraphic.com/owlcarousel/

Could we get something like this added to WET?

**Comment by duboisp** [comment]
@DHaslip The carousel link in your last comments do not work and I got redirected to an undesirable marketing site.

I am going to close this issue as it seem that your original question was answered. However, if you find an alternative link, please open up a new issue and add a screen capture in your description showing the feature request you needs.

Cheers
