### ISSUE TITLE
Geomap: 

### ISSUE THREAD

**Issue by Bourdage** [wet-boew/wet-boew#7551]
Does anyone have an actual working example of the Geomap that I could copy the code from, the one on "Web Experience Tool Kit" doesn't explaine very well, lots of missing part.
Thank you

**Comment by jvanulde** [comment]
@Bourdage can you be more specific about what you require? Have you looked at the documentation on how to get started?

**Comment by Bourdage** [comment]
I figure out how to make it work,
The instruction on GitHub are too little to actually site down and incorporated into anyone’s page.
Thank you
Marc

**Comment by hsrudnicki** [comment]
Is this still an issue? Please update the status of this again, whether this can be closed or otherwise, thank you

**Comment by masterbee** [comment]
closing since the caller's (creator of issue) seems to have abandoned the issue. Documentation is on the roadmap for  4.0.24 so this will be addressed.
