### ISSUE TITLE
Footnotes get pushed off the page when using Data Inview Top Bar in IE and Firefox

### ISSUE THREAD

**Issue by Deepgee** [wet-boew/wet-boew#7552]
Hi,

We are using the Data Inview Top Bar as a back to table of contents feature for long reports. But when we use the Data Inview Top Bar, when you click a footnote the footnote reference appears just off the bottom of the page in IE and Firefox, in Chrome the Footnote reference shows in the middle of the browser window.

If I remove the Data Inview Top Bar, the Footnote reference appears, but is at the bottom of the page in IE and Firefox, in Chrome the Footnote reference shows in the middle of the browser window.

First Question: Is it possible to get the footnote functionality in IE and Firefox to work the same as it does in Chrome?

Second Question: Does anyone have any other solutions for what we are trying to accomplish?

**Example 1 - With Data Inview Top Bar Only**
http://international.gc.ca/world-monde_draft/deep.aspx?lang=eng

**Example 2 - With Both Data Inview Top Bar and Footnotes**
http://international.gc.ca/world-monde_draft/deep2.aspx?lang=eng

**Example 3 - With Footnotes Only**
http://international.gc.ca/world-monde_draft/deep3.aspx?lang=eng

Thanks,

Deep

**Comment by hsrudnicki** [comment]
Does this remain still an issue? Please update the status of this again, thank you
