### ISSUE TITLE
Expand/Collapse all content

### ISSUE THREAD

**Issue by Sburbidge** [wet-boew/wet-boew#7556]
Are these good to be used with WET4?

wet-boew-expandcollapseall Create a toggle element. With no other options this will create a single toggle button. 
accent-first Accents the first button. 
print-open Automatically open details when printing. 
toggle Add a button that expands and collapses details elements. 
toggle-close Add a button that will only collapse details elements. 
toggle-open Add a button that will only expand details elements.

**Comment by pjackson28** [comment]
@Sburbidge Those are classes for a WET3 plugin which won't work in WET4. You'll need to switch to the WET4 equivalent which is the Toggle plugin: http://wet-boew.github.io/wet-boew/demos/toggle/toggle-en.html

**Comment by Sburbidge** [comment]
Thank you for the prompt reply. This is awesome

However, I do not see on this page, where the option to collapse the entire of a page and vice-versa, expand it all.

I’m trying to replicate what is on the TBS website: http://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=12153.

Based on this example, I’ve managed to expand/collapse one item at a time, but the expand/collapse does not work at all. Futhermore it looks good on Mozilla but does not work in Explorer 11. It doesn’t even show the simple expand/collapse.


Bonne journée / Have a nice day

Web Support Officer
Military Police Complaints Commission of Canada / Government of Canada
suzanne.burbidge@mpcc-cppm.gc.ca<mailto:suzanne.burbidge@mpcc-cppm.gc.ca>
Monday, Wednesday & Friday: 613-769-9006 or 613-943-5577
Tuesday & Thursday: 613-834-9957 / Facsimile: 613-947-5713

Agente de soutien du Web
Commission d'examen des plaintes concernant la police militaire du Canada / Gouvernement du Canada
suzanne.burbidge@cppm-mpcc.gc.ca<mailto:suzanne.burbidge@cppm-mpcc.gc.ca>
Lundi, mercredi & vendredi : 613-769-9006 ou 613-943-5577
Mardi & jeudi : 613-834-9957 / Télécopieur: 613-947-5713

**Comment by pjackson28** [comment]
@Sburbidge See the [Details Element example for the Toggle plugin](http://wet-boew.github.io/wet-boew/demos/toggle/toggle-en.html#details). You would use the <code>selector</code> and <code>parent</code> parameters to control the scope of the expand/collapse buttons. Further implementation details can be found in the [Toggle plugin documentation](http://wet-boew.github.io/wet-boew/docs/ref/toggle/toggle-en.html).

**Comment by Sburbidge** [comment]
Thanks. I’ll give it a shot.

Bonne journée / Have a nice day

Web Support Officer
Military Police Complaints Commission of Canada / Government of Canada
suzanne.burbidge@mpcc-cppm.gc.ca<mailto:suzanne.burbidge@mpcc-cppm.gc.ca>
Monday, Wednesday & Friday: 613-769-9006 or 613-943-5577
Tuesday & Thursday: 613-834-9957 / Facsimile: 613-947-5713

Agente de soutien du Web
Commission d'examen des plaintes concernant la police militaire du Canada / Gouvernement du Canada
suzanne.burbidge@cppm-mpcc.gc.ca<mailto:suzanne.burbidge@cppm-mpcc.gc.ca>
Lundi, mercredi & vendredi : 613-769-9006 ou 613-943-5577
Mardi & jeudi : 613-834-9957 / Télécopieur: 613-947-5713

**Comment by hsrudnicki** [comment]
Can be this closed or otherwise? Please update the status of this again, thx

**Comment by Sburbidge** [comment]
I haven’t got any feedback on this.

Bonne journée / Have a nice day

Web Publisher
Military Police Complaints Commission of Canada / Government of Canada
suzanne.burbidge@mpcc-cppm.gc.ca<mailto:suzanne.burbidge@mpcc-cppm.gc.ca>
Monday, Wednesday & Friday: 613-769-9006 or 613-943-5577
Tuesday & Thursday: 613-834-9957 / Facsimile: 613-947-5713

Éditrice sur le Web
Commission d'examen des plaintes concernant la police militaire du Canada / Gouvernement du Canada
suzanne.burbidge@mpcc-cppm.gc.ca<mailto:suzanne.burbidge@mpcc-cppm.gc.ca>
Lundi, mercredi & vendredi : 613-769-9006 ou 613-943-5577
Mardi & jeudi : 613-834-9957 / Télécopieur: 613-947-5713

**Comment by Sburbidge** [comment]
Leave a comment

**Comment by Sburbidge** [comment]
Leave a comment
