### ISSUE TITLE
Dropdown list inside of tabs - Chrome on iPhone

### ISSUE THREAD

**Issue by Evanjv** [wet-boew/wet-boew#7560]
Unable to open a drop-down list is inside of a tabbed view when using Chrome on iPhone (iOS 7-9). We haven't received any related issues from any other browsers or devices.

iOS Chrome version: 47.0.2526.107

[Example Page](http://www.albertahealthservices.ca/about/page205a.aspx)
[Video of the problem](https://youtu.be/1cjU7mbESAs)

HTML being used in the test video:
```html
<div class='wb-tabs site_tabs'>
	<div class='tabpanels'>
		<details id='ia_details-panel1' >
			<summary>Dropdown test with well</summary>
			<div class="well site_blue_well">
				<select class="form-control" id="ia_optLocationService">
					<option value="">Please select a Service</option>
					<option value="1070607">Aboriginal Community Health Representative</option>
					...
				</select>
			</div>
		</details>
		<details id='ia_details-panel2' >
			<summary>Dropdown test without well</summary>
			<select class='form-control' id='ia_optGlobalService'>
				<option value=''>Please select a Service</option>
				<option value="1070607">Aboriginal Community Health Representative</option>
				...
			</select>
		</details>
	</div>
</div>
<p>
	<h2>Working Dropdown</h2>
	<select class='form-control' id='ia_optGlobalService'>
		<option value=''>Please select a Service</option>
		<option value="1070607">Aboriginal Community Health Representative</option>
		...
	</select>
</p>
```
`site_tabs` is only used to style the tabs, no custom Javascript functions are being called
`ia_optLocationService` & `ia_optGlobalService` are used on the page we first found the issue and don't change the behaviour of the drop-down list.

Is there any testing I can do to find out if this is an issue with this version of Chrome?

**Comment by hsrudnicki** [comment]
Does this remain still an issue/a help question or otherwise? Please update the status of this, whether this can be closed or otherwise? Thx
