### ISSUE TITLE
 Failed to parse SourceMap - Chrome Issue

### ISSUE THREAD

**Issue by jgrammenos** [wet-boew/wet-boew#7565]
Hello,

While working on a site that uses CDTS and WET-Boew, i noticed a error show up recently in the Google Chome console:

Failed to parse SourceMap:
https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_21/js/wet-boew.min.js.map

To verify if the issue was exclusive to the site i was working on i checked Canada.ca (https://www.canada.ca/en.html), the issue is also present there.

It appears the chrome is having trouble parsing the .map file.

**Comment by byshine** [comment]
Happening to me as well. Chrome Version 51.0.2704.103 m

No issues on Firefox

**Comment by hsrudnicki** [comment]
Does this remain still an issue? Please update the status of this, whether this can be closed or otherwise, thank you

**Comment by jgrammenos** [comment]
This issue appears to be resolved, i no longer see any error in the Google Chrome console
