### ISSUE TITLE
Printing issue

### ISSUE THREAD

**Issue by Belange87** [wet-boew/wet-boew#7566]
Hi. 

Is there a quick solution to fix a printing issue with safari?

I'm using wet 4.0.20 and when i print i get blank pages...

Thanks

**Comment by Belange87** [comment]
Hi, so i fix my issue.
The <object> in the header won't let you print the content if your using SAFARI. So i added a class that hide the object on print and it work.

**Comment by hsrudnicki** [comment]
Based on the above, this issue can be closed. If you think otherwise, please update the status of this again, thx
