### ISSUE TITLE
Multiple forms using form validation

### ISSUE THREAD

**Issue by krystofurr** [wet-boew/wet-boew#7568]
Hello,

When you have multiple forms on a single page can you apply the form validation plugin to each one safely ( using the "wb-frmvld" class ) meaning that they will not interact will each other?  I have one form within a modal-lightbox and the other placed in the parent page.  They seem to work fine when I attempted this.  Any help appreciated, thanks.

**Comment by hsrudnicki** [comment]
Is this still an issue/a help question or otherwise? Please update the status of this again, whether this can be closed or otherwise? Thx

**Comment by kpduncan** [comment]
From my testing as long as each form are put in their own `<div></div>` with class `wb-frmvld' the WET jQuery library will assign each one a different id attribute and treat each as different forms.

**Comment by duboisp** [comment]
@krystofurr me also I didn't experienced any issue when I have multiple forms on a single page and I apply the form validation plugin to each one by using ```wb-frmvld``` class.
