### ISSUE TITLE
Overlay: Example JS method for manually opening "Centred popup - Modal (Lightbox + Modal)" does not work

### ISSUE THREAD

**Issue by kngai** [wet-boew/wet-boew#7573]
I tried the following in the [overlay demo page](https://wet-boew.github.io/v4.0-ci/demos/overlay/overlay-en.html):
`$( "#centred-popup-modal" ).trigger( "open.wb-overlaylbx" );`
and:
`$( "#centred-popup-modal" ).trigger( "open.wb-overlay" );`
and:
`$( "#centred-popup-modal" ).trigger( "open.wb-lbx" );`

None of it works. What is the actual method?

**Comment by pjackson28** [comment]
The approach you should be using is:
```js
$document.trigger( "open.wb-lbx", [
	[
		{
			src: "#inline_content_modal",
			type: "inline"
		}
	],
	true
]);
```

See [Opening popups through JavaScript](http://wet-boew.github.io/wet-boew/demos/lightbox/lightbox-en.html#examples5) for further details.

**Comment by kngai** [comment]
Thank you @pjackson28 . 

Didn't know `src` and `type` could accept those values. I couldn't find those specifics in the documentation.

**Comment by shawnthompson** [comment]
@kngai can we close this issue?
