### ISSUE TITLE
Data table search hidden columns

### ISSUE THREAD

**Issue by sam-he** [wet-boew/wet-boew#7576]
The search filter of data table searches hidden columns.  We have one table with all information with unit (metric or imperial) toggles to control what columns to be displayed, so there are hidden columns. The search function searches all columns and returns rows without search string, which is just not visible. This could confuse users.

Sam

**Comment by RobJohnston** [comment]
I think that the direction to go here would be with the [columns().search()] (https://datatables.net/reference/api/columns().search()) method.  See #6748 for an example close to this that might help you.

**Comment by sam-he** [comment]
Thank you Rob. Just think this could be a common issue that should be fixed as part of WET4 template. We can just use it as is.

**Comment by byshine** [comment]
Don't think this is an issue.. as hidden implies that it's "hidden" not deleted or removed. So internally it's there, but externally it's hidden. You should be adding/removing data from datatables anyway, not hide them under certain conditions.

**Comment by sam-he** [comment]
For performance reason, we sometimes have all data loaded in one http request. Users use toggle to choose what to see. Search is for users not developers. Users don't know there are hidden columns. Search hidden content will confuse users. I don't think  there are use cases to support that search function should search hidden columns.

**Comment by shawnthompson** [comment]
@sam-he, This might help you
https://datatables.net/examples/basic_init/hidden_columns.html

**Comment by hsrudnicki** [comment]
Can be this closed as resolved or otherwise? Please update the status of this again, thx

**Comment by masterbee** [comment]
closing since the caller's (creator of issue) issue appears to be addressed.
