### ISSUE TITLE
Div Vertical allignment not working

### ISSUE THREAD

**Issue by Beastmais27** [wet-boew/wet-boew#7579]
Hello,

I am new to Web Experience Toolkit,

I have been trying to get some of the object inside of div to vertically align in the middle.
Is it possible to do so? if so how?

I have tried:
-Using the class: align-middle (which existed in the version 4.0.4) 
-adding style to the div (style="vertical-align: middle;")
-forcing it with display:absolute; (Would not like to do)

I have attach a zip with the html page I am using.

it is a copy of the Form Validation demo in themes-dist-4.0.21-Theme-gc-intranet, and put the part of my code in the main.
I have put the div that need to be vertical align in red.

[Code Zip.zip](https://github.com/wet-boew/wet-boew/files/312213/Code.Zip.zip)

Let me know and thank you very much,

**Comment by voyera** [comment]
Not sure if there's an official way, but the CSS way would be as follow:

`<p style="height:90px; display: table-cell; vertical-align: middle;">Description of the issues</p>`

note the extra styling on the paragraph to achieve vertical-align. Hopefully that achieves what you're looking for.

**Comment by byshine** [comment]
Set the parent div to

`display: table;`
`table-layout: fixed;`

And the child to

`display: table-cell;`
`vertical-align: middle;`
`text-align: center;`

**Comment by Beastmais27** [comment]
Hello,

Thank you for the answers, they did work for basic/simple object such as "p" element, 'div' element, and text in div.

Sadly they did not work for items like the datepicker, "select" element, "input" element.

I tried the solution you guys sent be in the code I sent as well as non-changed version of the Form validate demo.

Could it be a class that is effecting it or could it be the datepicker rebuild won't accept the style or even something else.

Let me know and Thank you for your time,

**Comment by byshine** [comment]
Wrap the date picker around a 'div'

**Comment by Beastmais27** [comment]
Hello,

Thank for the answer but it did not achieve what i was looking for.

I have found design related way to avoid this issue.

Thank you so much for your time

I will know be closing this issue
