### ISSUE TITLE
WET Template validation issue

### ISSUE THREAD

**Issue by Bgolden67** [wet-boew/wet-boew#7582]
I didn't see this issue raised yet, so I apologize if it is a duplicate .

This line is now giving an error when you validate a page
<code><!DOCTYPE html> </code>

Specifically it is this part <code>IE 8]><!--> </code>

This issue just started happening on my local dev templates (using v4.0.20), so I downloaded the newest release (v4.2.21) and  checked the example pages in the WET download and its the same so I know it's not an error on my local code.

Any reason for this to start? Seemed to happen just this week or late last week.

**Comment by MRicher** [comment]
They change change the comment checking in the latest validator release (to match a recent change to the HTML spec) so that the checker no longer emits errors for "--" (consecutive hyphens) in a comment but does now emit specific error messages for "").

https://github.com/validator/validator/releases/tag/16.6.20

**Comment by nschonni** [comment]
Upstream issue is https://github.com/validator/validator/issues/310

**Comment by sideshowbarker** [comment]
Yeah, see also https://github.com/whatwg/html/issues/1453 for the proposed HTML spec change to address this. Will try to help that get landed soon, and then get the change to the checker code made as soon as possible after that.

**Comment by nschonni** [comment]
Thanks @sideshowbarker

**Comment by MRicher** [comment]
This can be closed, @sideshowbarker has push the fix https://github.com/validator/validator/issues/310

**Comment by shawnthompson** [comment]
Thanks @MRicher 👍
