### ISSUE TITLE
Feed reader - Pinterest issue

### ISSUE THREAD

**Issue by ehcee** [wet-boew/wet-boew#7583]
Hi,

The WET feed reader doesn't seem to work anymore with Pinterest feeds or has the coding changed and not found in the documentation? We were able to get the pinterest feed working last year but in trying it again with the same code it no longer works.

Note: Pinterest is still generating RSS feeds fine if you add .rss after the pinterest wall, ex
https://www.pinterest.com/healthycdns/drug-prevention.rss

Has the code to implement changed or is this something that can be fixed in a future build?

thanks, cheers

**Comment by hsrudnicki** [comment]
Does this remain still an issue/a help question or otherwise?  Please update the status of this again, thx

**Comment by cybersubtype** [comment]
There is a bug with [Line 158](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/feeds/feeds.js#L158) of the feed.js it needs to be changed to use `https:` instead of `http:` when I tried to change it manually it crashed on me. @shawnthompson do you have any ideas?

**Comment by shawnthompson** [comment]
@cybersubtype we need to connect and I can walk you through the build.

Send me an [email](https://github.com/shawnthompson/) and we can set something up next week.

**Comment by cybersubtype** [comment]
Found the problem [Line 95](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/feeds/feeds.js#L95).

To get the feed working these changes are required:
```javascript
OLD: var requestURL = wb.pageUrlParts.protocol + "//query.yahooapis.com/v1/public/yql?q=select%20*%20from%20feed%20where%20url%20%3D%20'" + encodeURIComponent( decodeURIComponent( url ) ) + "'%20limit%20" + ( limit ? limit : 4 ) + "&format=json";
NEW: var requestURL = "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20feed%20where%20url%20%3D%20'" + encodeURIComponent( decodeURIComponent( url ) ) + "'%20limit%20" + ( limit ? limit : 4 ) + "&format=json";
```
```javascript
OLD: var content = fromCharCode( data.content ).replace( /<a href="\/pin[^"]*"><img ([^>]*)><\/a>([^<]*)(<a .*)?/, "<a href='" + data.link + "'><img alt='' class='center-block' $1><br/>$2</a>$3" );
NEW: var content = fromCharCode( data.description ).replace( /<a href="\/pin[^"]*"><img ([^>]*)><\/a>([^<]*)(<a .*)?/, "<a href='" + data.link + "'><img alt='' class='center-block' $1><br/>$2</a>$3" );
```
Can this be reported as major bug? Also for Pinterest to work use http://www.pinterest.com/healthycdns/drug-prevention.rss (http not https).

**Comment by kodecount** [comment]
Found the problem [Line 96](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/feeds/feeds.js#L96).

To get the feed working this change is required:
```javascript
OLD (BUG): var content = fromCharCode( data.content ).replace( /<a href="\/pin[^"]*"><img ([^>]*)><\/a>([^<]*)(<a .*)?/, "<a href='" + data.link + "'><img alt='' class='center-block' $1><br/>$2</a>$3" );
NEW (FIX): var content = fromCharCode( data.description ).replace( /<a href="\/pin[^"]*"><img ([^>]*)><\/a>([^<]*)(<a .*)?/, "<a href='" + data.link + "'><img alt='' class='center-block' $1><br/>$2</a>$3" );
```

**Comment by masterbee** [comment]
closed since corrected with P.R. https://github.com/wet-boew/wet-boew/issues/7719
