### ISSUE TITLE
Multiple overlays on same page

### ISSUE THREAD

**Issue by GarthMartin** [wet-boew/wet-boew#7584]
I have 2 overlays on a page:

1 - a `wb-panel-l` table of contents (TOC) control that has inline href links that is opened by an anchor tag in the second overlay below, using the `overlay-lnk` method
2 - a `wb-bar-t` inview panel that appears when scrolled down

When I open the TOC when the inview is NOT active, and select a link that requires the page to scroll, everything is fine:  the TOC closes and the inview opens.

If I enable the TOC from the anchor in the inview, the inview closes, the TOC opens and even if the link I select causes the page to again scroll, the inview does not reappear.

There does not seem to be a close event on the overlay that I can use to re-trigger the inview.  

Any thoughts?

**Comment by byshine** [comment]
Do you have a link/image of the problem?

**Comment by GarthMartin** [comment]
@byshine:  I will try to describe with images.  Here is the default view with just the inview panel in its normal place:

![defaultview](https://cloud.githubusercontent.com/assets/11050106/16313333/c727ec62-3946-11e6-8570-9cfa33a003fc.png)

Here is the view with the Table of Contents activated:

![defaultviewwithtoc](https://cloud.githubusercontent.com/assets/11050106/16313598/d35fd25a-3947-11e6-8b68-d9e6e2b760ba.PNG)

If I click on a link in the TOC that requires scrolling it scrolls and the inview appears as expected:

![clickarticle8intoc](https://cloud.githubusercontent.com/assets/11050106/16313596/d31829b4-3947-11e6-8b9f-5df4a194c1cf.PNG)

But if I re-enable the TOC, the inview disappears:

![reloadtocfrominview](https://cloud.githubusercontent.com/assets/11050106/16313615/ecfab982-3947-11e6-99a2-c2f16b02c21f.PNG)

And then if I select another link that requires a page scroll, the inview remains hidden until I go back to the top of the page and then scroll back down again.

![clickontocforcingscroll](https://cloud.githubusercontent.com/assets/11050106/16313597/d3252222-3947-11e6-92f9-d0e3974568b5.PNG)

**Comment by byshine** [comment]
@GarthMartin It's hard to say what the problem is. Do you possibly have a link? or at least a reproduction of the problem?

**Comment by GarthMartin** [comment]
@byshine No link, internal dev site.  I could probably mock something up...

**Comment by hsrudnicki** [comment]
Does this remain an issue? Please update the status of this, whether this can be closed or otherwise? Thx

**Comment by kpduncan** [comment]
Are you wanting two overlays active at the same time?

**Comment by GarthMartin** [comment]
No, I do not want them open at the same time.  The issues is exactly that, when using the TOC, if the link selected requires scrolling to a place on the page where the floating menu should be visible, the floating menu does not appear -- UNLESS the TOC was opened from the fixed menu (that is replicated in the floating menu).

**Comment by kpduncan** [comment]
Okay. I think I get it what happening now. This is what I came up with for the html:
```html
<section class="panel panel-default wb-inview show-none bar-demo" data-inview="top-bar">
	<header class="panel-heading">
		<h2 class="modal-title">Page Options</h2>
	</header>
	<div class="panel-body">
		<ul class="list-inline">
			<li><p><a href="#left-panel" aria-controls="left-panel" class="btn btn-default btn-panel overlay-lnk" role="button">Left-panel</a></p></li>
			<li><button class="btn btn-default" type="button">Button 2</button></li>
			<li><button class="btn btn-default" type="button">Button 3</button></li>
		</ul>
	</div>
</section>

<section id="top-bar" class="wb-overlay modal-content overlay-def wb-bar-t">
	<header>
		<h2 class="modal-title">Page Options</h2>
	</header>
	<ul class="list-inline">
		<li><p><a href="#left-panel" aria-controls="left-panel" class="btn btn-default btn-panel overlay-lnk" role="button">Left-panel</a></p></li>
		<li><button class="btn btn-default" type="button">Button 2</button></li>
		<li><button class="btn btn-default" type="button">Button 3</button></li>
	</ul>
</section>

<section id="left-panel" class="wb-overlay modal-content overlay-def wb-panel-l">
	<header class="modal-header">
		<h2 class="modal-title">Left panel</h2>
	</header>
	<div class="modal-body">
		...
	</div>
</section>
```
and for my JavaScript:
```javascript
$( document ).ready(function() {
	$('.btn-panel').click(function() {
		closeBar();
		var isClosed = window.setInterval(function() {
			var tocPanel = findClass('left-panel','open');
		    if (tocPanel === false) { 
		    	openBar();
		        window.clearInterval(isClosed);
		    }
		}, 5);
	});
});

$(window).scroll(function() {
   if($(window).scrollTop() + $(window).height() > $(document).height() - 100) {
	   closePanel();
   }
});

function setLimitedInterval(interval, delay, limitations) {
	var x = 0;
	var limitedInterval = window.setInterval(function() {
		interval();
		if (++x === limitations) {
			window.clearInterval(limitedInterval);
		}
	}, delay);
};

function closePanel() {
	var menuBar = findClass('top-bar','open');
	var tocPanel = findClass('left-panel','open');
	if(menuBar === true && tocPanel === true) {
		$('#left-panel').removeClass('open');
		$('#left-panel').attr('aria-hidden', 'true');
	}
};

function openBar() {
	var menuBar = findClass('top-bar','open');
	if(menuBar === false) {
		$('#top-bar').addClass('open');
		$('#top-bar').attr('aria-hidden', 'false');
	}
};

function closeBar() {
	var menuBar = findClass('top-bar','open');
	var tocPanel = findClass('left-panel','open');
	if(menuBar && !tocPanel) {
		$('#top-bar').removeClass('open');
		$('#top-bar').attr('aria-hidden', 'true');
	}
};

function findClass(element, value) {
	var classList = document.getElementById(element).className.split(/\s+/);
	for (var i = 0; i < classList.length; i++) {
	    if (classList[i] === value) {
	    	return true;
	    }
	}
	return false;
};
```
I can put up a live demo on my blog later today if you wish.

**Comment by GarthMartin** [comment]
Interesting, I will have to give it a try later this week.  Were you able to reproduce the behaviour I was experiencing?

**Comment by kpduncan** [comment]
Yes when I use the default code the left panel appears over the top bar. When open the left panel from the top bar the bar is gone must return to top of page and scroll again to get the bar back. I was also experiencing flickering when the two were open at same time, but that could just be my environment.

**Comment by GarthMartin** [comment]
No worries.  I implemented this and it works like a charm.  Thanks very much!
