### ISSUE TITLE
No accents in FormValidation

### ISSUE THREAD

**Issue by locutux** [wet-boew/wet-boew#7592]
Hi,

In the Form Validation, when we use the `data-rule-lettersonly` attribute, it does not recognise accentuated characters, like "é" or "À". Is this by design? Could it be fixed please?

Thank you and have a great day!

**Comment by nschonni** [comment]
The [lettersonly](https://github.com/jzaefferer/jquery-validation/blob/7b0d035397bcce5372e0dfaee8ef0cc28c5006e6/src/additional/lettersonly.js) rule uses the regular expression `/^[a-z]+$/i.test( value );`. [Regex isn't character sensitive](https://stackoverflow.com/questions/20690499/concrete-javascript-regex-for-accented-characters-diacritics), so if you want to catch accented characters, you'll probably need to use the `pattern` rule and write your own regex.

**Comment by RobJohnston** [comment]
But the problem with using the `pattern` rule is that is that it gets stripped out.  See https://github.com/wet-boew/wet-boew/issues/7226#issuecomment-160984921

**Comment by nschonni** [comment]
`data-rule-pattern` would be a hack, but shouldn't get stripped by that other code

**Comment by hsrudnicki** [comment]
Can be this issue closed as resolved or otherwise?  Please update again the status of this, thank you

**Comment by locutux** [comment]
Hi, the problem is not resolved. so I would like to know: is this something that is going to be fixed by the WET team? Thanks!

**Comment by RobJohnston** [comment]
I've been looking at how to implement @nschonni 's solution.  The [example in the docs] (http://wet-boew.github.io/wet-boew/demos/formvalid/formvalid-en.html) offers this:

````
<input class="form-control" id="letters1" name="letters1" type="text" size="5" maxlength="5" 
pattern="[A-Za-z\s]" data-rule-lettersonly="true" />
````

And using the `data-rule-pattern` attribute, you could do something like this:

````
<input class="form-control" id="letters1" name="letters1" type="text" size="5" maxlength="5" 
data-rule-pattern="[A-zÀ-ÿ]+" data-msg-pattern="Letters only please (can include accents)." />
````

I also looked at the jQuery Validation site and nobody has yet opened an issue about `lettersonly` not validating accented characters.  We may want to get this into the 2.0.0 milestone.

Should check that the pattern, [A-zÀ-ÿ], is actually the best one to use... I grabbed it from StackOverflow -  [Concrete Javascript Regex for Accented Characters (Diacritics)] (http://stackoverflow.com/a/26900132).

And should we slap a "Content: Documentation" label on this issue and update that part of the docs?

**Comment by hsrudnicki** [comment]
Just in case for further consideration, as well as requested, the label has been added and the issue 5574 updated in regards to Rob's comment, thank you

**Comment by locutux** [comment]
Thank you for the solution. Will try it next week and update this issue accordingly.

**Comment by RobJohnston** [comment]
@locutux :  It's been a week... did you try it?

**Comment by locutux** [comment]
Sorry for the delay. I have tested it and it properly stop form submission if the user enters numbers, and submits appropriately on any character, accentuated or not. However, when there were both letters and numbers present, it went through without an error. I added "^" at the beginning and "$" at the end of the regex to fix this. 

There is one little problem: the validation summary does not display the error message of this textbox. I read again the documentation on Form Validation in the WET (http://wet-boew.github.io/v4.0-ci/docs/ref/formvalid/formvalid-en.html) and did not find anything about the error message. Can you please advise?

Thank you again for your help in this matter.

**Comment by locutux** [comment]
OK, forget the non-appearing message, it now appears. Must have been an implementation issue on my end.

Thanks again for all your help, it has been greatly appreciated!
