### ISSUE TITLE
Form validation: Date field doesn't work properly in Microsoft Edge

### ISSUE THREAD

**Issue by sarasuri** [wet-boew/wet-boew#7594]
Hi,
I noticed these form form fields input type="date" and input type="time" don't behave the same way in Microsoft Edge browser as in the other browsers such Chrome, Firefox, IE 11.

Issues:
1. The date picker icon is not displayed.
2. When navigating using the tab key input field doesn't have the focus indicator (black flashing cursor) and doesn't allow users to type in anything.
3.  If you enter or click on it a calendar appears allowing users to pick the date. However, after picking a data, users can't delete the date from the input field they can only modify the date.

**Comment by nschonni** [comment]
Edge has native support for those types http://caniuse.com/#feat=input-datetime so the WET plugin isn't executed. This is the same behaviour as Chrome (not that that function the same), since the library tests for native support, then defers to the browser if it says it knows how to handle those types.

**Comment by LaurentGoderre** [comment]
Closing since we don't have control over native implementations

**Comment by charlietoleary** [comment]
Edge may need to be polyfilled for now? The time input is not working correctly:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8810417/

**Comment by CalvinRodo** [comment]
Is there a policy that we have to use a type=date for inputting dates are we allowed to use type=text and use our own date-picker? @rlambert27

**Comment by duboisp** [comment]
@CalvinRodo, considering this issue are closed and your are asking a new question. I invite you to ask your question in a new issue.
