### ISSUE TITLE
input type="date" polyfill reloading thought Ajax

### ISSUE THREAD

**Issue by Beastmais27** [wet-boew/wet-boew#7596]
Hello,

I am using MVC3 and I have a partial view inside of a view. 

This partial view has a Html.BeginForm that on submit, Ajax Send the Data to the database and refreshes/reloads the partial view. 

In the form, there is a input type=date that changes to a normal textbox after the reload. 

Is there some way to either keep it in polyfill form or rebuild/re-initialize the textbox into a input type=date polyfill

Let me know and thank you very much for your time

**Comment by Beastmais27** [comment]
Hello,

I did some more research and I think I have found the answer:

This is my JavaScript function call on submit with the Ajax Post:
<pre>
function Submit(frm) {
    var form = $(frm);
    $.ajax({
        cache: false,
        async: true,
        type: "POST",
        url: $(form).attr('action'),
        data: $(form).serialize(),
        // datatype: "html",
        success: function (data) {
            //replace form's html with partial view html result
            $(form).replaceWith(data);

            //refresh tabs
            $(".wb-tabs").trigger("wb-init");

            //refresh datepickers and datepicker buttons
            $("input[type=date]").trigger("wb-init.wb-date");

        },
        error: function (data) { alert(data.type); }
    });
    $(form).html("loading...");
}
</pre>


If its possible to let me know if this is the "best" or if there a better way to do it .

Thank you very much for your time
**Beastmais27**

**Comment by hsrudnicki** [comment]
Can be this closed as resolved or otherwise. Please update the status of this, whether this is still an issue? Thank you

**Comment by Beastmais27** [comment]
Hello,
Sorry for the delay.

I have now closed this issues
thank you for your time
Beastmais27

**Comment by cybersubtype** [comment]
This might not be much use but this might be helpful: https://github.com/wet-boew/wet-boew/issues/7682

**Comment by Beastmais27** [comment]
Hello,

I checked through the issues you referenced @cybersubtype and notice that you also call the a trigger on 
"wb-init.wb-date"

This assured that I am using the right code to re-initializing the datepickers

Thank you for your help and your time @cybersubtype 
Beastmais27

**Comment by LaurentGoderre** [comment]
`wb-init.wb-date` is indeed the way to initialize a plugin added dynamically
