### ISSUE TITLE
Event calendar + Modal Popup

### ISSUE THREAD

**Issue by mohamedbecha** [wet-boew/wet-boew#7598]
Hi there,

I wanted to create an Event Calendar and when you click on the event link it shows a modal popup. 
It actually works on the event list below the calendar. But the calendar links don't work and it creates a javascript error:

TypeError: c.getElementById(...) is null
...j,k=b.which;return k&&1!==k?void 0:(e=c.getElementById(l).getAttribute("aria-con...

This will be very useful for my ongoing projects...
Any ideas how to fix this? Did any one tried this in the past? 

Thx

**Comment by shawnthompson** [comment]
Can you test this with the latest development build?
http://wet-boew.github.io/wet-boew/docs/versions/dwnld-en.html#v40dev

We made a fix recently to the plugin.
http://wet-boew.github.io/v4.0-ci/unmin/demos/cal-events/cal-events-en.html

**Comment by mohamedbecha** [comment]
Works fine, thanks a lot. Sorry for the late response

**Comment by shawnthompson** [comment]
Good to hear! Thanks.
