### ISSUE TITLE
Interface à onglets: 

### ISSUE THREAD

**Issue by erickdhaene** [wet-boew/wet-boew#7600]
Bonjour je vous contact par rapport à l'article "Interface à onglets" (https://wet-boew.github.io/v4.0-ci/demos/tabs/tabs-fr.html)

J'aimerais savoir si vous pouviez détaillé les mécanismes pour créer vos onglets horizontal, on peut visualiser le code mais pas le css, et avec l'inspecteur de chrome je n'arrive pas à comprendre: mais <summary> se déplace lorsque les trois sont fermés ?!

Merci d'avance pour vos explications.

-------------------------------------------------------------------------------
Google traduc : 

Hello I you contact relative to the article " Tabbed interface " ( https://wet-boew.github.io/v4.0-ci/demos/tabs/tabs-fr.html )

I wonder if you could detail the mechanisms to create your horizontal tabs, you can view the code but not the css, and chromium inspector I do not understand , but <summary > moves when the three are closed ?!

Thank you in advance for your explanations.

**Comment by voyera** [comment]
Le fonctionalite principale pour montrer/cacher le texte se sert de l'element HTML "details" qui comporte une fonctionalite "open" de base lorsque quelqu'un clique sur l'element on peut voir que "open" se rajoute dessus et fait apparaitre les elements a l'interieur de celui-ci.

Le reste de la fonctionalite est faite en javascript, vous pouvez-voir facilement si vous desactive javascript que le look n'est pas du tout le meme.

J'espere que ca vous aide!

**Comment by erickdhaene** [comment]
oui merci à vous !

**Comment by hsrudnicki** [comment]
Est-ce encore un problem/une question? Please update the status of this again, whether this can be closed or otherwise, thank you/merci

**Comment by masterbee** [comment]
Cette question a déjà été réglée.
