### ISSUE TITLE
Multiple rowspan table headers, and printing

### ISSUE THREAD

**Issue by JVan91** [wet-boew/wet-boew#7602]
Hello, my application has a few tables that have multi row spanning headers in them. They look great in the browser but when going to print them the thick bottom border on the table header will only appear on the bottom most row that is created.

Here is an example table of what I mean. Here you have a table header that has 3 rows. When you go to print a table like this only the 6C elements will receive the thick bottom border

![wet multirow table](https://cloud.githubusercontent.com/assets/20339057/16654350/5b2e4640-4423-11e6-9f1b-61ee22595d15.jpg)

Here is what it looks like in print preview where you can see only the 6C elements where given the thick bottom border.

![wet multirow table print preview](https://cloud.githubusercontent.com/assets/20339057/16654360/66668234-4423-11e6-89c4-772713f6f58d.jpg)

If I remove all of the WET 4 classes from the table the table looks fine in print preview.

**Comment by RobJohnston** [comment]
@JVan91 Post the HTML that you're using.  Or see how the DataTables plugin expects [complex headers] (https://www.datatables.net/examples/basic_init/complex_header.html) to be written.

**Comment by JVan91** [comment]
@RobJohnston here's the code I used to make the example table I posted above.

```
<table class="wb-tables table table-bordered table-striped table-hover" style="white-space:normal;text-align:left;"
				data-wb-tables='{ "sDom": "rt", "pageLength": -1, "aaSorting": [[ 0, "desc" ]] }'
				summary="Example" style="vertical-align:top;"
				data-year-column="0">
				
			<thead style="vertical-align:baseline;">
		
				<tr style="vertical-align:bottom; text-align:center;">
					<th rowspan="3" scope="col"  id="yearCol">1</th>
					<th rowspan="3" scope="col" >2</th>
					<th rowspan="3" scope="col" >3</th>
					<th rowspan="3" scope="col" >4</th>
					<th colspan="2" scope="col" style="white-space:normal;">5A</th>
					<th colspan="4" scope="col" style="white-space:normal;">6A</th>
					<th rowspan="3" scope="col" >7</th>
				</tr>
				<tr>
					<th rowspan="2" scope="col" >5B</th>
					<th rowspan="2" scope="col" >5B</th>
					<th rowspan="2" scope="col" >6B</th>
					<th colspan="2" scope="col" >6B</th>
					<th rowspan="2" scope="col" >6B</th>
				</tr>
				<tr>
					<th scope="col" >6C</th>
					<th scope="col" >6C</th>
				</tr>
			
			</thead>
</table>
```

**Comment by RobJohnston** [comment]
So, stripping this down to the basics of the problem:
```html
<table class="wb-tables table table-bordered table-striped table-hover" data-wb-tables='{"ordering": false }'>
    <thead>
        <tr style="vertical-align:bottom; text-align:center;">
            <th rowspan="3" scope="col">1</th>
            <th rowspan="3" scope="col">2</th>
            <th rowspan="3" scope="col">3</th>
            <th rowspan="3" scope="col">4</th>
            <th colspan="2" scope="col">5A</th>
            <th colspan="4" scope="col">6A</th>
            <th rowspan="3" scope="col">7</th>
        </tr>
        <tr>
            <th rowspan="2" scope="col">5B</th>
            <th rowspan="2" scope="col">5B</th>
            <th rowspan="2" scope="col">6B</th>
            <th colspan="2" scope="col">6B</th>
            <th rowspan="2" scope="col">6B</th>
        </tr>
        <tr>
            <th scope="col" >6C</th>
            <th scope="col" >6C</th>
        </tr>
    </thead>
</table>
```
I see this on the web page:
![table-complex-header](https://cloud.githubusercontent.com/assets/1347487/16659383/c1a4c5fc-4437-11e6-99bd-c0e7b619e2ab.png)
And this is the print preview:
![table-complex-header-print](https://cloud.githubusercontent.com/assets/1347487/16659390/cd2c200a-4437-11e6-96ff-da4a66a6e4bc.png)
That seems quite a bit different from your view... I wonder if you're getting everything WET loaded correctly?  You're using a recent version of WET?  Which browser(s)?

**Comment by JVan91** [comment]
I found out what it was. Someone had added a custom CSS class that I missed that is applying a double thick border to the last th in a thead set of tags. When I strip out all of the custom css I get the same results as you posted above.

Love missing those 2 lovely lines of code sometimes! :)

Thank you for your help! Greatly Appriciated

**Comment by RobJohnston** [comment]
Great!  Don't forget to close the issue.
