### ISSUE TITLE
IE11 Crash Tabbed Interface Carousel

### ISSUE THREAD

**Issue by accurate** [wet-boew/wet-boew#7603]
So I'm testing my site in IE11 along with WET v4.0.16.

On my homepage, I have a Tabbed Interface Carousel and it crashes IE (see screenshots). When I disable the carousel, the page does not crash. No other browsers are affected.

<img width="504" alt="screen shot 2016-07-07 at 09 35 30" src="https://cloud.githubusercontent.com/assets/4964631/16654974/4467878e-4426-11e6-88ba-3392a85ec4df.png">

<img width="504" alt="screen shot 2016-07-07 at 09 35 47" src="https://cloud.githubusercontent.com/assets/4964631/16654989/4ef7c8f8-4426-11e6-897e-58f5caf7e032.png">

When I emulate IE10, it works fine.

I have the same/similar code on two different sites yet it's only crashing on one of them.

The site that works is http://solarbiologicals.com and I can send the other site that crashes (currently in development) privately when someone can take a look into this.

Thanks!

-Richard

**Comment by byshine** [comment]
URL? Code? GIF Images?
You can set breakpoints to determine exact point where the browser crashes

**Comment by hsrudnicki** [comment]
Does this remain still an issue? Please update the status of this again, whether this can be closed or otherwise? Thank you

**Comment by accurate** [comment]
I updated to 4.0.22 and it worked.

Also may have been tied to IE security settings/levels. 

Not exactly sure how/what exactly caused it.
