### ISSUE TITLE
Feedback form: Issue with keyboard focus skipping to the next field

### ISSUE THREAD

**Issue by sarasuri** [wet-boew/wet-boew#7605]
Hi,
I have noticed keyboard focus skipping between form fields in Firefox 47.0.

I took the feedback form example (http://wet-boew.github.io/wet-boew/demos/feedback/feedback-en.html) and made some modifications to cater our needs.

When the keyboard focus is in the "Reason for contacting us" and using the up/down arrows to select "Critical problem with the website" then the tab key to move to the next field. Instead of moving to the newly displayed field "What page address (URL) or page description?" field, it skips over to the "Please contact me if you require further details (checkbox) field.
This issue appears to happen when the new fields are displayed right below the select menu.

You can see the similar issue under "Report a problem or suggest an improvement" on Canada.ca Feedback page (https://www1.canada.ca/en/contact/feedback.html).
Can anyone provide any suggestion/help to fix this issue, please?

![feedback](https://cloud.githubusercontent.com/assets/12256067/16662817/60ed8676-4447-11e6-91a0-dff7171fb4f8.gif)

**Comment by hsrudnicki** [comment]
Does this remain still an issue? Please update the status of this again, whether this can be closed or otherwise? Thx

**Comment by sarasuri** [comment]
Hi,
Yes, this is still an issue. Please leave it open.
Thanks.

**Comment by LaurentGoderre** [comment]
I am unable to reproduce with Firefox

**Comment by sarasuri** [comment]
Hi,
It appears the keyboard focus issue has been fixed in the current version of Firefox (v. 49.0.1).  So the issue can be closed now. 
Thanks.
