### ISSUE TITLE
Lightbox: Has anyone successfully implemented an onbeforeunload using the WET4 modal?

### ISSUE THREAD

**Issue by juliemercier** [wet-boew/wet-boew#7606]
We would like to warn users that they are about to leave a form on which they have unsaved changes. Has anyone successfully implemented this using the WET4 modal? To meet the WET4 and WCAG standards, do we need to use the WET4 modal for this or is it OK to use Windows Internet Explorer dialog "Are you sure you want to leave this page"? It seems to be WCAG compliant (JAWS reads it and interacts with it fine).
![wie_leave](https://cloud.githubusercontent.com/assets/7468426/16742386/80e34d40-4775-11e6-9c77-ed2519876c18.PNG)

**Comment by hsrudnicki** [comment]
Does this remain still an issue? Please update the status of this again, whether this can be closed or otherwise? Thx

**Comment by kpduncan** [comment]
The short is you can't style this popup. This is due to security reason many browsers have remove that or block that functionality. The only thing you can change is the message that displays.
