### ISSUE TITLE
Reset Travis-CI Secure variables

### ISSUE THREAD

**Issue by nschonni** [wet-boew/wet-boew#7607]
https://blog.travis-ci.com/2016-07-07-security-advisory-encrypted-variables
Probably not an issue, but good idea to reset the keys on the bot anyway.

**Comment by LaurentGoderre** [comment]
I'm off until mid-October but I'll try to do this in between diapers ;) or maybe @shawnthompson can do it

**Comment by shawnthompson** [comment]
I can change diapers!

**Comment by LaurentGoderre** [comment]
I mean the tokens everywhere. It's sort of a big change

**Comment by LaurentGoderre** [comment]
@shawnthompson are you up for this?

**Comment by LaurentGoderre** [comment]
Thanks for that! We have script for this now btw
