### ISSUE TITLE
Calendar of Events: Multiday event as first or only event in the calendar

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/wet-boew#7609]
There is an issue with the calendar of events if your first event (or only event) is a multiple day event.

The calendar renders like this:

<img width="368" alt="screen shot 2016-07-15 at 9 03 50 am" src="https://cloud.githubusercontent.com/assets/2575266/16875045/162619ee-4a6b-11e6-9630-e2e53f841f41.png">

I created a working example of the problem.

https://shawnthompson.github.io/wet-boew-calendar/demos/cal-events/cal-events-en.html

@masterbee

**Comment by shawnthompson** [comment]
@duboisp Do you think you can take a look at this?

**Comment by shawnthompson** [comment]
Sorry @LaurentGoderre didn't mean to remove your name from the assignee list.

**Comment by duboisp** [comment]
@shawnthompson I will look in to it

**Comment by duboisp** [comment]
@shawnthompson I found the issue, I am working on a fix.

**Comment by shawnthompson** [comment]
:+1:

**Comment by duboisp** [comment]
@shawnthompson PR #7624 with the fix is ready to merge

Cheers
