### ISSUE TITLE
Having trouble getting Tabs working in IE8

### ISSUE THREAD

**Issue by simkessy** [wet-boew/wet-boew#7610]
Running on IE8 and can't really get the tabs to work. Is this expected?

**Comment by RobJohnston** [comment]
Support for IE 8 was ended on 2015-01-01 and for IE 9 on 2015-10-01.  This was part of the [release notes of 4.0.21] (http://wet-boew.github.io/wet-boew/docs/versions/v4.0/v4.0.21-en.html). 

They promise better documentation of supported browsers in https://github.com/wet-boew/wet-boew/issues/6646, and you can see the justification of why supported ended for IE8 there too.  I believe that they will accept pull requests, but they won't actively work on any issues for older browsers.

**Comment by simkessy** [comment]
Sounds good thanks @RobJohnston
