### ISSUE TITLE
Dialogue box and buttons

### ISSUE THREAD

**Issue by Jawsuser1** [wet-boew/wet-boew#7614]
I use IE 10, JAWS 15 assistive technology.
I test in HTML Basic and not Standard HTML.
Recently, I came across a problem where dialogue box keeps running "Your request is in progress"  and buttons to execute an action do not work. ("View in HTML", "Download PDF" and "Download CSV").  I selected View in HTML as an assistive technology user.
I'm told to test in Standard as a work around cause these reported bugs are a known issue with WET4 and they have no choice but to live with it.
This needs fixing.
![wet4issuein basic](https://cloud.githubusercontent.com/assets/20538447/16951057/5494a208-4d91-11e6-8fec-eeb8202c3e28.png)

**Comment by nschonni** [comment]
Running in Basic mode means WET is not interacting with the page anymore, #6712 has a good explaination of this.

**Comment by kpduncan** [comment]
The way I worked around this was creating a css called called overlay-hidden which set the display to none and using jquery to remove the css when the event for the overlay is called. It not ideal but it a issue got to deal with due to accessibility.

**Comment by hsrudnicki** [comment]
Does this remain still an open issue or otherwise?

**Comment by hsrudnicki** [comment]
Can be this closed or otherwise? Please update it again, thx

**Comment by Jawsuser1** [comment]
Yeah you can close this.
