### ISSUE TITLE
Section Menu - Sub Task links disappear when href is the current page

### ISSUE THREAD

**Issue by ryanhyma** [wet-boew/wet-boew#7616]
Maybe this is outlined somewhere, but I can't find it. Maybe someone could point me in the right direction.

Here is the use case of the possible problem:

If I take this example:
http://wet-boew.github.io/themes-dist/GCWeb/localnav/task1/index-en.html
and replace the URL of Sub Task 1 with the URL of the current page. The text of subtask 1 disappears because the class wb-navcurr is added to the anchor tag. (As far as I can tell)

Is this a bug, or should an item in "Sub task" area of the section menu, never be the URL of the current page?

Thanks.

**Comment by DK-TBS** [comment]
I don't believe that's a bug;  those menus are intended to be used in such a way the current page is never among the nested, "sub task" menu items.  Rather, the "sub task" items should always be children of the current page, if the current page has children.  

So, the menu is always structured relative to the current page:  the parent of the current page at the top, the siblings of the current page (including the current page itself) just below that, and any children of the current page in the level below that (the "sub task" items).

Hope that helps  :)

**Comment by RobJohnston** [comment]
You just beat me to it. 

I'll add, for the GCWeb theme, the specs for the section menu can be found in section 6.5 "Local navigation menus" of the [Canada.ca Content and Information Architecture Specification] (http://www.gcpedia.gc.ca/wiki/Canada.ca_Content_and_Information_Architecture_Specification).

**Comment by ryanhyma** [comment]
Okay this can be closed. Thanks.
