### ISSUE TITLE
Angular Directives / Components

### ISSUE THREAD

**Issue by EricPMulligan** [wet-boew/wet-boew#7617]
Is there an active project for Angular directives and/or components that implement WET?

If not, what is the process to start one and would there be anyone interested in contributing? Also, would there be guidelines that I should abide by other than mimicing the current functionality of the main WET project?

**Comment by hsrudnicki** [comment]
Does this remain still an issue? Please update the status of this again, thx

**Comment by EricPMulligan** [comment]
This isn't an issue, I was waiting for feedback.

**Comment by hsrudnicki** [comment]
Based on the above, @LaurentGoderre shall give the feedback, either way please keep the status of this updated

**Comment by LaurentGoderre** [comment]
I have implemented angular alongside WET with no problem. However I did not create directive or components for WET components but rather for large section of the UI where I would use WET plugins inside them.
