### ISSUE TITLE
Multimedia Plug-in - Playback issues at ECCC

### ISSUE THREAD

**Issue by plpilon** [wet-boew/wet-boew#7621]
Hi,

We have My GCHR videos posted on PSPC's GCintranet site. Many users at ECCC can't initiate playback. They see the controls options and the loader but even after waiting many minutes, the video doesn't start.

Here's one the said videos:
http://gcintranet.tpsgc-pwgsc.gc.ca/rhgc-gchr/intro-eng.html

I've checked with ECCC and they are using IE 11,0.9600.18349  and Flash : 21.0.0.242 (I know the player is HTML5 but who knows...).

I'm thinking this might be a firewall issue were the files would be streamed on a closed/blocked port - can't think of anything else.

Anyone else had this issue before?

Thanks

Pierre-Luc Pilon, TBS, OCHRO, My GCHR Transition and Support

**Comment by rlambert27** [comment]
Did you get it fuxed? Works for me at ESDC, video loads fine and starts 2-3 seconds after I hit play.

I checked console and no Javascript errors.

I think you are right, it might be a firewall issue, maybe check your NET tab in firebug to ensure everything is loading.

**Comment by plpilon** [comment]
Thanks, not being at ECCC complicates the troubleshooting... I will give this a try.
