### ISSUE TITLE
Mobile menu with footer loaded through an ajax call

### ISSUE THREAD

**Issue by jdeezie** [wet-boew/wet-boew#7622]
i know the title isn't the best so I apologize :)

We've been using version 4.0.12 of the templates for a while and we are in the process of updating to 4.0.21. 

In our 4.0.12 pages we are loading a portion of our footer content through a `data-ajax-replace` call and this was displaying in the mobile menu with no problem.

With the updated 4.0.21 js files this no longer works. the ajax-ed footer content still loads and displays but this replacement doesn't get picked up by the mobile menu before it is generated.

Ive tried a few things like adjusting where the ajax call is being made (loading the whole footer content, wrapping a div around the footer to make the load, etc.) to no avail.

Is there something you can suggest or do to defer the menu generation until the ajax-ed content has been pulled in?

**Comment by jdeezie** [comment]
HI @LaurentGoderre just checking in on this any advice or progress with this?

We can place the footer content in every page if we really have to but would like to keep the single point of updating with the ajax call

**Comment by LaurentGoderre** [comment]
This is not currently possible and it was a coincidence that it even worked in previous versions. I think it might be possible to create a fix for this but I'm in parental leave until October. I will look at fixing it then.

**Comment by jdeezie** [comment]
Understood. Enjoy the rest of your time off. Thanks.

**Comment by nschonni** [comment]
There might be some examples with the GCWeb stuff were they were using frames or document.write to pull the header and footer from a central server.

**Comment by rlambert27** [comment]
You could pull in the footer the same way the CDTS does it:

http://www.gcpedia.gc.ca/wiki/Centrally_Deployed_Templates_Solution_(CDTS)

Using Google Closure Templates we generate what's called a SOY file that has the header and the footer plus any other common template sections. Then the pages using the SOY files simply call the different components. Here is an example page:

http://www.esdc.gc.ca/includes/op-so/cdn-demo/content-en.shtml

The domain is esdc.gc.ca but the header and footer are being pulled from ssl-templates.gc.ca.

**Comment by jdeezie** [comment]
Thanks guys. 

No access to gcpedia but I ran a search on Google closure templates and that looks like an interesting option. I guess other templating solutions like handlebars would also work.

**Comment by rlambert27** [comment]
Yes handlebars would work also!

**Comment by hsrudnicki** [comment]
Can be this closed as resolved or otherwise?

**Comment by hsrudnicki** [comment]
Does this remain an open issue until @LaurentGoderre will be back in work to fix this? Please update the status or milestone of this, thank you

**Comment by jdeezie** [comment]
I would like to see it fixed if possible. Other templating possibilities are not as friendly for some of the teams here. Thanks.

**Comment by LaurentGoderre** [comment]
@jdeezie this is a top priority for us as well. I should have a fix in shortly

**Comment by jdeezie** [comment]
Thanks @LaurentGoderre.

**Comment by LaurentGoderre** [comment]
There you go. It will be available for next release
