### ISSUE TITLE
Other Languages

### ISSUE THREAD

**Issue by TalyahAtUXAccess** [wet-boew/wet-boew#7623]
Hi, Just reviewed this project. It is amazing, loved it !!
I am a UX architect and an accessibility specialist. I particularly loved your approach to UX and accessibility issues.
I was wondering whether you may be interested in supporting the Hebrew language.
I know it is far fetched but it doesn't hurt to ask :)

Talyah

**Comment by shawnthompson** [comment]
I'm glad you like our project @TalyahAtUXAccess! 
We can easily support Hebrew. We would just need the translation.

**Comment by TalyahAtUXAccess** [comment]
Hi,
Thank you for the swift response. I am not sure what the scope of work is,
but I will be happy to take a stab at it since Hebrew is my main language
(I wanted to say my Mother Tongue but it is not entirely true since my Mom
was born in the US and lived there 22 years before immigrating to Israel).

Thanks. Talyah



*Talyah Aviran*

Accessibility Specialist / User Experience Architect at UXAccess LLC

Senior Interactive Designer @ Delta Airlines

*eMail:    **talyaav@gmail.com* <talyaav@gmail.com>
*US:*      +1 470.809.9455

Israel:  +972 55 8852121

*Profile:  *
*My LinkedIn Profile * <http://www.linkedin.com/in/talyahaviran>


2016-07-27 8:17 GMT-04:00 Shawn Thompson <notifications@github.com>:

**Comment by RobJohnston** [comment]
You can get a sense of the scope of work from issue #7033.  It will link you to the translation file too.

**Comment by hsrudnicki** [comment]
Does this remain still an open issue or otherwise? Please update the status of this again, thank you

**Comment by masterbee** [comment]
@TalyahAtUXAccess , welcome and as @RobJohnston mentioned issue #7033 gives a good baseline for how WET works. Closing this issue since it has addressed the ask and pointing you in the right direction. Please feel free to open another issue if you discover anything and/or want to help contribute to the translations
