### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by samagit** [wet-boew/wet-boew#7626]
Hello,
I'm building an Angular JS using npm, gulp and browserify. would you have an example on how to integrate this component as npm package. Ideally I would like to wrap it and export it as a global module and then use it in a gulp task. 
Also could this be installed as a npm package?

Thanks

**Comment by LaurentGoderre** [comment]
I use bower for this https://github.com/open-data/report-generator/blob/master/bower.json

This is an angular project with WET

**Comment by samagit** [comment]
Thank you for the quick response.
Any plan to add wet-boew and theme-gcwu-fegc to the NPM registry?

**Comment by masterbee** [comment]
@samagit - great question. I am sure that the community is not opposed to the idea, but there is some work ongoing in the near future to re-work some of the internals that @LaurentGoderre and others ( including I ) are toying with that will potentially help this particular ask. So probably safer to say, "yes" it is on the radar.

**Comment by samagit** [comment]
Awesome! I will be happy to have the ability to use gulp or webpack to build/bundle a project themed with wet-boew (out of the box).

**Comment by LaurentGoderre** [comment]
My hesitation is that bower picks it up automatically. If we were to host it on npm, we would need yet another layer of build to push it to the npm registry.

**Comment by samagit** [comment]
Isn't worth it ? Actually I was stuck with the fact that for my angular(wet-boew) project I could not use any of those angular yoeman  generators that use ES6 and integrate gulp or webpack with npm modules and lazyloading (import) feature. The static way to use wet-boew in index.html is not compatible with lazyloading method (pls correct me if I'm wrong). I'm still open to any other alternative you may have though.

**Comment by LaurentGoderre** [comment]
It's not necessarily worth it if Bower does it at no cost. And beside npm is for node packages, not general JavaScript dependencies. 

WET does not conflict with Angular or lazy loading, it just need a bit of understanding of how both work to make them play nice with each other (which I have done in the past)

**Comment by samagit** [comment]
Would you have an example of how to lazy-load Wet? if yes that would be very helpful to me.
Thanks

**Comment by LaurentGoderre** [comment]
You shouldn't lazy load WET, use lazy loading of resources for angular and use WET the way it was design and build the bridges between the two.

**Comment by hsrudnicki** [comment]
Is this still an issue? Please update the status of this again, whether this can be closed as resolved or otherwise? Thank you

**Comment by masterbee** [comment]
closed since the issue appears to be addressed

**Comment by samagit** [comment]
Addressed??? really ?

**Comment by LaurentGoderre** [comment]
Well i don't think we're going to push to npm since it's in bower. You should open another issie about your angular issue
