### ISSUE TITLE
Data Table Plugin - Form Filter

### ISSUE THREAD

**Issue by gocGrabinski** [wet-boew/wet-boew#7627]
Hello,
We would like to request a new component that works with (or extends) the existing Data Tables plug-in. (http://wet-boew.github.io/wet-boew/docs/ref/tables/tables-en.html)
The component/extension would be comprised of a form with one or more select boxes of key terms that could be applied as filters to a neighboring Data Table.
The filters are applied to the Data Table as select box options are selected.
We have created our own JavaScript for this however the page that will use this will be hosted the Managed Web Service(MWS) and we are unable to include our custom script there. 
The MWS does allow the use of WET components and therefore we are making this request. 

![wet-component-req](https://cloud.githubusercontent.com/assets/5992730/17366964/ed7163c8-595b-11e6-81cc-c5c98de8b7a4.png)

HTML for form and table, CSS, and our custom JS for our data table with form for filtering:
[datatable-home-with-filters-1.zip](https://github.com/wet-boew/wet-boew/files/399565/datatable-home-with-filters-1.zip)

**Comment by masterbee** [comment]
@gocGrabinski - thanks for this, and we are wondering if you have attempted to integrate this javascript into WET. It appears that  you have done the logic for the plugin but just need to integrate the approach but extending the existing WET feature data-tables with potentially some new parameters. 

Did you want to take an attempt at doing that and then creating an PR for us to look at? Since most of the work is already done on your .zip file.

Thoughts?

**Comment by gocGrabinski** [comment]
@masterbee - Some of our developers have tried but have not been able to get the WET builds running. Network restrictions. We are getting some help today in getting the builds running on our machines. Stay tuned :-)

**Comment by gocGrabinski** [comment]
Oops closed issue by accident.

**Comment by Deepgee** [comment]
**@gocGrabinski** - Hi Do you have a working example of this you would be able to share?

**Comment by TouficS** [comment]
@gocGrabinski see ex3 http://wet-boew.github.io/wet-boew/demos/tables/tables-en.html 

we are looking on improving subsequent filtering based on columns headers and cell content. @duboisp will share details.

**Comment by duboisp** [comment]
@Deepgee here a working example on how you will be able to do with field flow http://universallabs.org/wet/labs/wb-fieldflow/v0.2/wb-fieldflow-advanced.php#tblfilter

**Note:** Field flow (wb-fieldflow) should be submitted (PR) to wet-boew project in the coming days, so it should be available with the WET 4.0.24 release.
