### ISSUE TITLE
Tables: Multiple options

### ISSUE THREAD

**Issue by gdanova** [wet-boew/wet-boew#7628]
Does anyone know the syntax for adding **multiple** `data-wb-tables` options? For example, if I wanted both the `data-wb-tables='{ "stateSave" : true }'` **and** `data-wb-tables='{ "searching" : false }'` options in the `<table>` element.

**Comment by gdanova** [comment]
Trial and error prevails. This, for example, works:
`data-wb-tables='{"lengthMenu": [[20, 40, 60, -1], [20, 40, 60, "All"]], "stateSave": true}'`

**Comment by silentcanadian** [comment]
I did the same thing through trial and error.  Was able to do the following as well to order, limit the paging and remove the "filter" textbox: 
`data-wb-tables='{"pageLength": -1, "searching" : false, "order": [2,"asc"]}'`

**Comment by gdanova** [comment]
Nice.

Any idea what will happen to that once content is migrated to Canada.ca, i.e. will it be editable?

**Comment by silentcanadian** [comment]
I'm not sure.  I hope we'll be able to customize some of the options.  Right now I've been using this on my dept's internal apps.

**Comment by hsrudnicki** [comment]
Does this remain still an issue? Please update the status of this again, whether this can be closed or otherwise? Thank you
