### ISSUE TITLE
Tabbed Interface: 

### ISSUE THREAD

**Issue by samer73** [wet-boew/wet-boew#7637]
I would like to ask how I can remove the blue border around the image that I use for the Tabbed interface?
Also, is it a way to switch the image when it is in active tab?
![tabbed](https://cloud.githubusercontent.com/assets/16181993/17713225/dc15c544-63c7-11e6-81c6-abd448399ecb.jpg)

Thanks!
Samer

**Comment by kpduncan** [comment]
I'm not part of the WET team but my recommendation is:

`.wb-tabs [role=tablist]>li {
 background: #fff !important;
}`

Just add this to your custom css file.

**Comment by hsrudnicki** [comment]
Can be this closed as resolved or otherwise? Please update the status of this again, thank you

**Comment by samer73** [comment]
Yes, that works well. Thank you!
