### ISSUE TITLE
Style guide link

### ISSUE THREAD

**Issue by MaryBethBaker** [wet-boew/wet-boew#7647]
Hey WET-BOEW maintainers,

Would it be possible to make it easier to find the design guide link? http://wet-boew.github.io/wet-boew-styleguide/v4/design/index-en.html

It's buried pretty far within the working site example: http://wet-boew.github.io/wet-boew/index-en.html

Thanks,

Mary Beth

**Comment by MaximMartel** [comment]
Can this issue be closed since the Design Guide is now linked and easily accessible in the Key ressources section of the homepage of WET-BOEW.?
