### ISSUE TITLE
Responsive video example

### ISSUE THREAD

**Issue by MaryBethBaker** [wet-boew/wet-boew#7648]
Hi,

Is it possible to add the code and an example for responsive video to the design guide for videos?

Thanks,

Mary Beth

**Comment by MaximMartel** [comment]
Hi @MaryBethBaker,

If you are looking at the Plug-in design features section of the design guide : http://wet-boew.github.io/wet-boew-styleguide/v4/design/index-en.html#plugin, page 3, Multimedia Player - Video, you do have all the information you need (ex: Code and examples).

Does that suffice? 

Please let me know,

Maxim

**Comment by hsrudnicki** [comment]
Does this remain still an issue or otherwise? Please update the status of this again, whether this can be closed or otherwise, thx

**Comment by MaryBethBaker** [comment]
Ok. Will review.

Mary Beth

**Comment by LaurentGoderre** [comment]
@MaryBethBaker the video player is responsive already. If you put a video in a grid cell it will resize accordingly.

**Comment by MaryBethBaker** [comment]
@LaurentGoderre Awesome. Closing ticket now.
