### ISSUE TITLE
WET documentation

### ISSUE THREAD

**Issue by MaryBethBaker** [wet-boew/wet-boew#7649]
Hi all,

The documentation for creating custom error messages didn't get moved from WET3 to WET4 documents? Is this feature still available in WET4? And if it is, can you add it to the documentation?

Mary Beth

**Comment by MaximMartel** [comment]
Hi @MaryBethBaker,

You can create custom error messages in WET4. In order for you to create a custom error message, you would have to go by the theme you are using (Ex: Canada.ca theme : http://wet-boew.github.io/themes-dist/GCWeb/index-en.html and edit/create your custom error message from : [Server message page](http://wet-boew.github.io/themes-dist/GCWeb/servermessage-en.html)  or [Server message page (English/French) ](http://wet-boew.github.io/themes-dist/GCWeb/servermessage-en-fr.html). 

Is that ok for you? 

Thanks,

Maxim

**Comment by MaryBethBaker** [comment]
Hi @MaximMartel 

Works for me. Did this get added the docs?

**Comment by hsrudnicki** [comment]
Shouldn't this be included into #5574 as well?

**Comment by hsrudnicki** [comment]
This issue contains a reference to be included/considered in the docs, therefore this can be closed as resolved.  
If you think otherwise or plan further enhancement(s), please update the status of this again, thank you
