### ISSUE TITLE
Canada.ca: Style Guide: No italics

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/wet-boew#7652]
In the _Canada.ca Web Content Style Guide – version 2.0_ on page 18 it states

> Don’t use any italics because it’s difficult for users with dyslexia and other reading disorders to read

Although in the previous version 1.4 of the guide on page 20 it spoke a lot about using _italics_ for proper titles.

> Use italics for the proper titles of publications, acts and regulations, and in other instances as outlined in The Canadian Style and Le guide du rédacteur. Avoid using italics for page titles or headings unless the text or heading includes (or is) a title.

Authors that are migrating their content will be using `em` for titles on a lot of their pages and I think we should be keeping that semantic meaning to that markup. Right now there's talk about removing the `em` markup from all the pages, which I think would be a huge mistake.

I propose that we style the `em` in another look than _italics_ instead of just removing the `em` element altogether. This could be with another font face, more letter spacing, something to make it different but still accessible for people who have trouble reading text in _italics_.

I'm calling on this community to have an option discussion on how we should move forward on this issue.

Now for the name dropping:

@masterbee, @dboudreau, @bsouster, @Bgolden67, @DK-TBS, @SBleeks, @CoolColin, @neoinsight, @TouficS, @trtustian, @therealolivergross, @rlambert27, @nschonni, @davidpepin

Please share this with anyone you might think who would be interested in participating in this discussion.

**Comment by RobJohnston** [comment]
There's already been some discussion about italics in https://github.com/wet-boew/wet-boew/issues/7631 too.

**Comment by shawnthompson** [comment]
Thanks. I think I should continue on Chad's issue and close this one...

**Comment by shawnthompson** [comment]
Moved to #7631
