### ISSUE TITLE
Form Validation: Custom Validation Method not adding

### ISSUE THREAD

**Issue by ZaphodBebbleBrox** [wet-boew/wet-boew#7653]
Hi,

I'm trying to add a custom validation method for a date picker on a form. The date can only be a date in the future. 

In the aspx file I have:

$(document).on("wb-ready.wb-frmvld", ".wb-frmvld", function ( event ) {
$.validator.addMethod("futureDate", function (value, element) {
var currentDate = new Date();
var selectedDate = new Date();
return this.option(element) || selectedDate > currentDate;
}, "Date must be after today's date");
});

Then an onclick function for calling the validate method:
function validateFunction(){
$('#form').validate({
rules: {
           datepicker: {futureDate: true}
});}

It seems something is going wrong with the validator.addMethod portion. It doesn't seem to run. I found a previous post about waiting for the form, but adding that didn't seem to help. The regular WET form validation still works as expected. Any ideas?

Thanks

**Comment by RobJohnston** [comment]
I've done this by setting the "min" attribute to today, like this:
```html
<input class="form-control" id="date1" name="date1" type="date" data-rule-dateISO="true" min="2016-08-31" />
```
And used something server-side to insert the "min" attribute.  Does that work for you, or are you going for a fully client-side solution?

**Comment by ZaphodBebbleBrox** [comment]
It doesn't have to be fully client-side, but I need it to use the same error messages that WET uses by default for other required fields and validation. Like the little "Error 1: error message" and the "Form cannot be submitted because xx errors" etc. 

Unfortunately setting the min attribute does not trigger those error messages. Thanks though.

**Comment by RobJohnston** [comment]
Sure it does!

If I edit the date example on the [form validation] (http://wet-boew.github.io/wet-boew/demos/formvalid/formvalid-en.html) page to what I wrote above, I get the WET error.

![demomindate](https://cloud.githubusercontent.com/assets/1347487/18140704/b75f8884-6f84-11e6-8a97-5e393f8663c4.png)


For a client-side version, you could do something like this:

Put futureDate in the class attribute of the control to validate, like so:

```html
<input class="form-control futureDate" id="date1" name="date1" type="date" data-rule-dateISO="true" />
```
And put the following script at the bottom of the page, after the jQuery and wet-boew scripts have loaded:
```js
    <script>
        wb.doc.on("wb-ready.wb", function (event) {
            jQuery.validator.addMethod("futureDate", function (value, element) {
            var currentDate = new Date();
            var selectedDate = new Date(value);
            return this.optional(element) || selectedDate > currentDate;;
            }, "Date must be after today's date.");
        });
    </script>
```

But this isn't perfect... it doesn't handle the [problems with parsing dates in JavaScript] (http://dygraphs.com/date-formats.html).

**Comment by ZaphodBebbleBrox** [comment]
So it does! I had a typo in a label so it wasn't updating properly. Passing a value for min from the server works well just as you said.

I still wasn't able to get the client-side version working, which would be the ideal solution. I think there might be something wrong with the javascript inside of the futureDate method. 

`<input class="form-control futureDate valid" ... >`

It looks like the jqueryvalidator is running, and it determines it to be valid. Which is where the new "valid" is from. I'm not the most familiar with javascript, likely there's something wrong with the syntax. But I'm not sure what.

**Comment by RobJohnston** [comment]
I'd say the client-side version is not ideal because it relies on JavaScript (which can be turned off) and it assumes that the clock on the user's computer is correct.  Not to mention that the example above isn't complete... the selectedDate includes the timezone info, so for me it subtracts 4 hours, which makes the date yesterday (I'm not the most familiar with JavaScript either).  

I say server-side is better because the [min attribute of the date input control is defined at part of HTML5](https://www.w3.org/TR/html-markup/input.date.html#input.date.attrs.min), but [support varies] (http://caniuse.com/#feat=input-datetime).

**Comment by hsrudnicki** [comment]
Does this remain still an issue or otherwise? Please update the status of this again, whether this can be closed or otherwise, thx

**Comment by kpduncan** [comment]
Check out #7557 for my example of adding a custom validation. I've added mine directly to the javascript file.

**Comment by cybersubtype** [comment]
Not sure if still looking for help but what about this:

jQuery:
```javascript
$( document ).on( "wb-ready.wb", function( event ) {
	if(jQuery.validator && jQuery.validator !== 'undefined') {
		( function() {
			
			function getDate() {
				var month = (new Date().getMonth()+1).toString();
				var formatedMonth = (month.length === 1) ? ("0" + month) : month;
				var day = new Date().getDate().toString();
				var formatedDay = (day.length === 1) ? ("0" + day) : day;
				return new Date().getFullYear() + "/" + formatedMonth + "/" + formatedDay;
			}
			
			jQuery.validator.addMethod( "futuredate", function( value, element, params ) {
				if(value) {
					var date1 = new Date().setHours(0,0,0,0),
					date2 = new Date(value);
					return (date1 > date2) ? false : true;
				}
				return true;
			}, jQuery.validator.format( "Date must be after " + getDate()));
		}() );
	}
});
```
HTML:
```html
<div class="wb-frmvld">
	<form action="#" method="post" novalidate="novalidate" >
		<div class="form-group">
			<label for="date" class="required"><span class="field-name">Future Date</span></label>
			<input id="date" class="form-control" type="date" name="date" required="required" data-rule-dateISO="true" data-rule-futuredate="true" />
		</div>
		<div class="form-group">
			<button class="btn btn-md btn-primary" type="submit" role="button" >Submit</button>
			<button class="btn btn-md btn-default" type="reset" role="button">Clear</button>
		</div>
	</form>
</div>
```
Preview:
![date-valid](https://cloud.githubusercontent.com/assets/22446865/19313214/1bb2e8fa-906c-11e6-85b1-23731e478bbc.png)

**Comment by masterbee** [comment]
closed since issue appears to be addressed.
