### ISSUE TITLE
Session Timeout: 

### ISSUE THREAD

**Issue by claudielarouche** [wet-boew/wet-boew#7654]
Hello,

I'm trying to implement session timeout on a C# application and I'm not sure what to do about the refreshCallbackUrl (see documentation here: https://wet-boew.github.io/wet-boew/docs/ref/session-timeout/session-timeout-en.html)

Would someone have a working example that they wouldn't mind sharing? 

Thanks!

**Comment by RobJohnston** [comment]
I've used something like this:

```html
<span class="wb-sessto" data-wb-sessto='{"inactivity": 1200000, "reactionTime": 180000, "sessionalive": 1200000, 
"logouturl": "./logout.aspx", "refreshCallbackUrl": "./refreshCallback.aspx"}'></span>
```

And in refreshCallback.aspx, return 'true' if the user's session has already begun:

```c#
protected void Page_Load(object sender, EventArgs e)
{
    Response.Write((!Session.IsNewSession).ToString().ToLower());
}
```

And in logout.aspx

```c#
protected void Page_Load(object sender, EventArgs e)
{
    this.Session.Abandon();
}
```

But I'd be interested to see what other have done too.

**Comment by hsrudnicki** [comment]
FYI only: There is also just recently closed issue #7371, which may be taken into consideration again when/if applicable in your C# application including Session Timeout.

**Comment by claudielarouche** [comment]
Thank you @RobJohnston, it seems to work for me too yay! 

@hsrudnicki, I'm satisfied and we can close the issue but if @RobJohnston prefers to wait a few more days to see if others have anything to add, I'm happy to wait too. I'll let you guys decide what's best!

**Comment by RobJohnston** [comment]
@claudielarouche I think that you can close it... if anybody is interested, they will stumble upon this issue and add their input.
