### ISSUE TITLE
Text highlighting: 

### ISSUE THREAD

**Issue by nijonker** [wet-boew/wet-boew#7655]
biggest limitation I have discovered with this is that it provides false positives when the term is a part of another word. Ex. ear  will be highlighted in fear, nearest, year, wearing ... all undesired highlight matches. Also, don't try and use your form text box with the txthl parameter b/c basic boolean operators (and,or,but etc.) cannot be excluded by this function. As well, quoted phrases cannot be handled.  Excellent concept but not suitable for my situation, unable to leverage without some undesired highlighting or missing highlighting.

**Comment by kpduncan** [comment]
I'm not part of the WET team, but here is my advice. In your JavaScript file change this line: 

"(?=([^>]*<))([\\s'])(" + searchCriteria + ")(?!>)"

too this:

"(?=([^>]*<))([\\s'])(\\b" + searchCriteria + "\\b)(?!>)"

and that should do the trick.

**Comment by hsrudnicki** [comment]
Can be this closed based on the above or otherwise?

**Comment by nijonker** [comment]
Yes, thank you for your response!


Norm Jonker
  Small-Medium Web Solutions | Petites et moyennes solutions Web
  Client Service Operations & Solution Development | Direction des opérations du service à la clientèle et du développement des solutions
  Innovation, Information and Technology | Direction générale d'innovation, information et technologie
  Employment and Social Development Canada | Emploi et Développement Social Canada
  Government of Canada | Gouvernement du Canada
  norman.jonker@hrsdc-rhdcc.gc.ca<mailto:norman.jonker@hrsdc-rhdcc.gc.ca>
  Telephone | Téléphone 226-204-2031

**Comment by hsrudnicki** [comment]
Based on the above, this can be closed as resolved, thank you
