### ISSUE TITLE
Calendar of Events: 

### ISSUE THREAD

**Issue by zomby22** [wet-boew/wet-boew#7656]
I am converted a WET2 ASP calendar using the new WET4 calendar plugin.
1. If no events exist for the month, I like to browse the calendar month by month anyway with or without events, can this be done?
3. Can weekends be excluded? what is the code?
2. My forms will have multiple dates (different location or time but the event title is the same). This doesn't work unless the event is different for every date entered. Is there a solution around this problem?

thanks.

**Comment by kpduncan** [comment]
If you look at the [JavaScript](https://github.com/wet-boew/wet-boew/blob/478d2c628cf006cd90187bc4737f15456582837c/src/plugins/cal-events/cal-events.js) it was designed to use this html:
```html
<div class="wb-calevt" data-calevt-src="calendar1">
	<ol>
		<li>
			<section>
				<h4><a href="http://www.canada.ca" rel="external">Single-Day Event</a></h4>
				<p><time datetime="2013-03-11">March 11th, 2013</time></p>
				<p>Event Description</p>
			</section>
		</li>
	</ol>
</div>
```
as AJAX and creates the calendar solely based off this AJAX. You have to change the JavaScript or you can try something like [Full Calendar](https://fullcalendar.io/).

**Comment by LaurentGoderre** [comment]
for you first question, it should already work.

Not sure how easy it would be to disable the weekends.

You want for one event to have multiple dates associated with it?

**Comment by zomby22** [comment]
1. By default, the calendar only display with available data, if there is no data, there is no calendar displaying for the month selected. (I wish I can include screenshot to show you)
2. if there is a way to disable weekends, that would be great has well.
3. what I mean by the multiple dates associated: for instance, we have a calendar of events. If there is 2 events for October 11 (where the title is written the same), it wont show up properly in the calendar boxes unless the title is different. My page is built to merge multiple sessions into the same box where the title/description matches. in WET2 the calendar was control and maintain with ASP code.

Is there a webpage that explains with sample code all the modification that can be made with this WET4 calendar? let me know thanks.

**Comment by kodecount** [comment]
@zomby22 You can drop saved pictures into the github textbox area.

**Comment by zomby22** [comment]
All is good with this request, you can forget what I wrote.
new issue:
I have some data for month of February and month of march. The calendar doesn't let me browse between the two month using the top drop down and arrow links, any idea why.

`<div class="wb-calevt evt-anchor" data-calevt-src="calendar4">`

![Uploading 01.jpg…]()

**Comment by kodecount** [comment]
Can we see more code? Maybe the whole `div` as the [examples/demos](https://wet-boew.github.io/v4.0-ci/demos/cal-events/cal-events-en.html) seem to be working.

**Comment by zomby22** [comment]
my pages uses ASP coding with this calendar plugin.

The querystring ends with: 
.asp?navMonth=3&navYear=2017
.asp?navMonth=2&navYear=2017

if I write it like the demo, it works, but once I insert ASP code connected to postgres database, then it does not, I see the calendar perfectly fine, except I can't browse using the top calendar links.

**Comment by zomby22** [comment]
I see why....its working now. Except it doesn't load by today date by default. If there is a active date in the past, say October 2016, it loads October 2016 in the calendar by default, where it should be March 2017. Its possible, its the ASP code that is causing it.

**Comment by kodecount** [comment]
I think this is related: https://github.com/wet-boew/wet-boew/pull/7671 (as their is issue with changing the defaults).

**Comment by zomby22** [comment]
why cant you force a default date inside this line (even if there is no data, you can replace the calendar with a message like "there is currently no events for this month".) 

<div class="wb-calevt evt-anchor" data-calevt-src="calendar4">
there is no such line like data-today-date="<%=now()%>">

what is the source for this calendar plugin?

this is what I found but its not enough if there is no source that page that explains all the extra codes you can throw in to make this calendar even more dynamic.
quote: "their is no fix in WET at the moment) and it also dependent on the events listed (you can't see months that have no event"

**Comment by kodecount** [comment]
I agree that by default it should load to the latest events, but currently it doesn't. I'm not sure of a work around. The PR been sitting still for awhile.

**Comment by zomby22** [comment]
temporary solution to browse current to future events (excluding past events). I include this in my query.
date_part('month', distinctdate)>='"&month(now())&"' and date_part('year', distinctdate)>='" & year(now()) & "' "
If ever there is a solution to load today date and still be able to browse past events, I'd like to know. ;)
