### ISSUE TITLE
CC placement on youtube multimedia implementation

### ISSUE THREAD

**Issue by kavinay** [wet-boew/wet-boew#7660]
Hi there, we just noticed a small difference between the MM player when using videos with a local source (MPEG) and Youtube: the locally sourced video opens a nice black bar below the video for captioning whereas the Youtube version displays captions on top of the video itself.

Is it possible to get the Youtube version of the MM player to display captions in a dynamic black bar as well?

Thank you

**Comment by LaurentGoderre** [comment]
Unfortunately, no. We have no control over YouTube captions, we don't even have access to the captions themselves to use our own system. The only thing we have control over is wheter they're on or off

**Comment by kavinay** [comment]
Thanks Laurent.
