### ISSUE TITLE
Input type="date" polyfill (date picker): 

### ISSUE THREAD

**Issue by SBleeks** [wet-boew/wet-boew#7664]
Can this solution for the date picker be used to choose a single date or does the user has to pick a date range?

**Comment by RobJohnston** [comment]
So you're talking about the example page http://wet-boew.github.io/wet-boew/demos/datepicker/datepicker-en.html?

The "Start date" and "End date" are two independent examples.  You could have a single date picker (e.g., date of birth).

Or did I misunderstand the question?

**Comment by SBleeks** [comment]
Yes, we’re talking about the Date picker example page. The example seems to indicate that the Date Picker is set up to choose a date range (from/to). We simply want to use it to literally pick a date. Like you said, birthdate, for example.

Socan you confirm, the WET Date Picker can be used to simply pick a date?

Thanks,

**Comment by RobJohnston** [comment]
Yes.  For example:  https://secure.cic.gc.ca/enquiries-renseignements/canada-case-cas-eng.aspx

**Comment by kpduncan** [comment]
Can this issue be closed?

**Comment by LaurentGoderre** [comment]
@SBleeks the date picker is for specific dates only, though you can create form with two date pickers to create a range

**Comment by masterbee** [comment]
closing since the caller (creator of issue) question appeared to be addressed
