### ISSUE TITLE
jquery validation: Update step validation to handle floating points correctly

### ISSUE THREAD

**Issue by pxl074** [wet-boew/wet-boew#7666]
Environment: WET4.0.21 (jquery validate 1.15.0)

When validating a number input with step = 0.01 (or any floating point number). The current step method always says the input is invalid: "Please enter a multiple of 0.01"

For example, validating a number field with a step attribute of 0.01 produces unexpected results for me - e.g. 0.01, 0.02, 0.04 all validate, whereas other multiples of 0.01 such as 0.03, 0.05 don't.

![wet4_step_validation_issue](https://cloud.githubusercontent.com/assets/22298918/18638156/1848c8a4-7e5d-11e6-9fab-bc01a251a918.PNG)

This issue has been fixed in new jquery validation (version 1.15.1):
https://github.com/jzaefferer/jquery-validation/releases/tag/1.15.1
https://github.com/jzaefferer/jquery-validation/pull/1809 

Could you also fix this in the WET4 please?

Thank you in advance!

Peng Lu

**Comment by masterbee** [comment]
closed since WET was updated to leverage jQuery Validation 1.15.1 (https://github.com/wet-boew/wet-boew/commit/0e6995c8b285c0a33c4499a3b33e20ffd807e49f)

**Comment by ztdan4ik** [comment]
Hi all
Now same think happen if step 0.00000001

**Comment by thekodester** [comment]
If there an issue it need to be brought up over here: https://github.com/jquery-validation/jquery-validation
