### ISSUE TITLE
Overlay: background color of bars

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/wet-boew#7667]
Why are the overlay bars background-color set to #000?

https://github.com/wet-boew/wet-boew/blob/478d2c628cf006cd90187bc4737f15456582837c/src/plugins/overlay/_base.scss#L111

I'm trying to make an alert style for the bar but I don't want to add a lot of CSS overrides in my GCWeb theme to make it happen.

I will be putting in a PR to remove them but I'd like to see if anyone knows why they were there in the first place.

CC/ @andrewc778

**Comment by kpduncan** [comment]
You also have to change [Line 98](https://github.com/wet-boew/wet-boew/blob/478d2c628cf006cd90187bc4737f15456582837c/src/plugins/overlay/_base.scss#L98) cause it is also giving the header a background color.

**Comment by nschonni** [comment]
If you look at `blame` it's been around since the start of 4 https://github.com/wet-boew/wet-boew/blame/478d2c628cf006cd90187bc4737f15456582837c/src/plugins/overlay/_base.scss#L111, but even that change looks like it was just a reformat and not the original change

**Comment by shawnthompson** [comment]
yeah I don't think it will brake anything and be an improvement. Thanks!

**Comment by hsrudnicki** [comment]
also see and clarify #7512

**Comment by duboisp** [comment]
@shawnthompson I am trying to find the "alert style for the bar" that you are referring in GC web, do you know if it was implemented?

I just want to do an impact analysis before to undo PR #7668

(related to #7731 and #7725)

**Comment by shawnthompson** [comment]
@duboisp The colour was moved to the theme's css because when it was put it base css. Can we add the colour to the demo css so theme's can add their own colours?

**Comment by duboisp** [comment]
A valid default should be at set in wet. What do you think of setting the color #fff where the background color dark blue is set?

**Comment by shawnthompson** [comment]
But it's hard to override that in a theme file without using _!important_.

**Comment by shawnthompson** [comment]
Can we use `inherit` or something?

If we add this back we would have to reopen all these:
 - #7667
 - #7512
 - #6550

**Comment by duboisp** [comment]
ok, I will investigate to find a solution that doesn't require using '''!important'''
