### ISSUE TITLE
Form Validation: Numeric (digits only)

### ISSUE THREAD

**Issue by ryanhyma** [wet-boew/wet-boew#7670]
I think there is a bug with the validation for the numeric (digits only) validation on the example page:
http://wet-boew.github.io/wet-boew/demos/formvalid/formvalid-en.html

For some reason it will accept combinations like: "333," or "1,"
It will however not accept 1.

Is this a bug?

**Comment by kpduncan** [comment]
What browser and version? It seems to work fine on IE 11 and Chrome 53.

**Comment by ryanhyma** [comment]
Version 53.0.2785.116 m (64-bit) - Localisation as French 
![2016-09-22 07_38_25digits only-](https://cloud.githubusercontent.com/assets/1958180/18746902/0cd1c966-8098-11e6-9e45-abdf05bcfc16.png)

**Comment by ryanhyma** [comment]
I've tabbed away, and click away, same thing no validation.

**Comment by kpduncan** [comment]
I think this might be a chrome issue cause I'm using 53.0.2785.116 m (64-bit) and it won't let me type nothing, but numbers.

**Comment by kpduncan** [comment]
I also have latest version on my iPhone (53.0.2785.109) and it is working and I get a green https connection.

**Comment by RobJohnston** [comment]
It's all about that French localization.  The ability to use commas was [added 6 years ago] (https://bugs.chromium.org/p/chromium/issues/detail?id=62063).  

I have the exact same version, but localized for English.  No problem entering "1", but is the problem that you can't enter "1." or "1" with the French version? I assume "1," would work.

**Comment by kpduncan** [comment]
I missed the information about french. I assumed it was English cause the page is. If I switch page to french it does work normally for me.

**Comment by ryanhyma** [comment]
The browser is set to French and the page is in English.. The validator will then accept "111," etc as valid.

**Comment by masterbee** [comment]
@ryanhyma - sorry just chiming in as this appears to be expected result since the localization is following the browser setting from what you are saying. Is the idea to have the localization follow the page setting and not the browser? it makes some sense but this could be a deeper dive in to the mechanics jQuery Validation

**Comment by masterbee** [comment]
closed issue since it appears to be abandoned by carrier (creator of issue)
