### ISSUE TITLE
When a fieldset is a list item there is a space above the fieldset

### ISSUE THREAD

**Issue by juliemercier** [wet-boew/wet-boew#7672]
A client would like all form questions numbered. The easiest way I have found of providing that is using an ordered list (and for WCAG  add wb-inv numbering ). However, when a list item contains a fieldset, the fieldset legend sits on a line below the list numbering. (See image and code attached). Is there a workaround for this? Or perhaps another option? 

What I also tried is to create the numbering without a list using a div with a pull-left and a lot of underlying aria code but I am wondering if that is the most efficient way. (Code sample attached) 
Thank you.

![code_with_list](https://cloud.githubusercontent.com/assets/7468426/18788041/59618dbc-8173-11e6-9dc5-42e1337222d5.PNG)
![fieldset in a list](https://cloud.githubusercontent.com/assets/7468426/18787786/53676fe0-8172-11e6-9653-f7df1fb24a06.PNG)
![code_without_list](https://cloud.githubusercontent.com/assets/7468426/18787787/53746a38-8172-11e6-9eb4-06fb4da60c2e.PNG)

**Comment by kpduncan** [comment]
Your not properly labeling the radio buttons and you are not using legend tags as intended. Try this:
```html
<fieldset class="mrgn-lft-md">
<div class="form-group">
<label for="radio" class="required"><span class="wb-inv">Question 2 B</span><span class="field-name">Project Category</span><span class="required">(required)</span></label>
<div class="radio">
<label><input id="radio" name="radio" type="radio" value="1"> Radio 1</label>
</div>
<div class="radio">
<label><input id="radio" name="radio" type="radio" value="2"> Radio 2</label>
</div>
</div>
</fieldset>
```
Also read the [form design](https://wet-boew.github.io/wet-boew-styleguide/v4/design/forms-en.html) page.

**Comment by juliemercier** [comment]
Are you saying that the fieldset examples on the form validation page are incorrect? http://wet-boew.github.io/v4.0-ci/demos/formvalid/formvalid-en.html

**Comment by kpduncan** [comment]
It not the best approach.

**Comment by juliemercier** [comment]
So the alpha Bootstrap4, Mozilla and w3org examples are not using the best approach either?
https://www.w3.org/wiki/HTML/Elements/fieldset
http://v4-alpha.getbootstrap.com/components/forms/
https://developer.mozilla.org/en/docs/Web/HTML/Element/fieldset

**Comment by juliemercier** [comment]
The code you provided does not solve the issue of the gap.  I am using GCintranet template version 4.0.21.
![list](https://cloud.githubusercontent.com/assets/7468426/18792237/a64e8bce-8183-11e6-8c20-f0c16f967802.PNG)

**Comment by kpduncan** [comment]
They are completely different from what you are doing. Their is no need to be rude.

**Comment by nschonni** [comment]
@juliemercier it's easier when code rather than pictures of code are provided. See https://guides.github.com/features/mastering-markdown/ for using code fences when pasting in code block

**Comment by juliemercier** [comment]
@nschonni  OK. I will look at that and post the code. Thanks.

**Comment by kpduncan** [comment]
![icon](https://cloud.githubusercontent.com/assets/22152300/18792460/083a29f2-818d-11e6-89d1-5e2006202e08.png)

**Comment by masterbee** [comment]
closed issue since it appears to be abandoned by carrier (creator of issue)
