### ISSUE TITLE
making an envelope glyphicon an email link

### ISSUE THREAD

**Issue by KCKessler** [wet-boew/wet-boew#7673]
We would like to make the envelope glyphicon link to an email. When we try to do it the email address is visible. This is the code we used:

```
<span class="glyphicon glyphicon-envelope fa-fw">"mailto:taaza@taazaroanoke.com"</span>
</a>
```

What are we missing?

**Comment by biljanap** [comment]
@KCKessler You are missing opening <a> tag and href attribute.  Is this what you need? 
```html
<a href="mailto:taaza@taazaroanoke.com"><span class="glyphicon glyphicon-envelope fa-fw">&nbsp;Firstname Lastname</span></a>
```

**Comment by masterbee** [comment]
closed issue since it appears to be abandoned by carrier (creator of issue)
