### ISSUE TITLE
Feeds: documentation needs to be updated (please?) !

### ISSUE THREAD

**Issue by ghost** [wet-boew/wet-boew#7679]
From my research Facebook longer supports these types of feed and should be removed from the list of supported applications and from the examples. Link: https://wet-boew.github.io/v4.0-ci/docs/ref/feeds/feeds-en.html

Also Facebook would need to be removed from the [feed.js](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/feeds/feeds.js). It was kinda rude of Facebook cause they didn't make it public they just did it. There is no longer any support documents for feeds at https://developers.facebook.com/ and only discussion I found is APIs. There also this [stockoverflow](http://stackoverflow.com/questions/9709016/facebook-killed-public-rss-feeds-how-to-obtain-a-facebook-page-rss-with-the-new) that discussed it.

**Comment by MaximMartel** [comment]
Ill get that change in today. Thanks for this @cybersubtype

**Comment by cybersubtype** [comment]
This is related issue [6888](https://github.com/wet-boew/wet-boew/issues/6888) and PR [7010](https://github.com/wet-boew/wet-boew/pull/7010)

**Comment by kodecount** [comment]
Also #7583

**Comment by Bgolden67** [comment]
Is there an acceptable new widget for including a facebook feed that is part of or at least compatible with WET?

**Comment by kodecount** [comment]
You can try and copy https://github.com/wet-boew/wet-boew/pull/7010

It been sitting around for a while, and hasn't seen as much love as it needs.

**Comment by lucas-hay** [comment]
Addressed in #7917
