### ISSUE TITLE
Fatal error: write EPIPE: Mac OS

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/wet-boew#7687]
I've opened an [issue](https://github.com/asciidisco/grunt-imagine/issues/67) with the [grunt-imagine](https://github.com/asciidisco/grunt-imagine) node module about an issue we are having building WET on a Mac.

I've done loads of test and it seems to only be a problem on the Mac OS.

I'm looking for anyone building WET on a Mac that is running OSX 10.11 or below to try to build WET from a clean clone and see if they are having the same problem.

https://github.com/asciidisco/grunt-imagine/issues/67

**Comment by shawnthompson** [comment]
Update: Tested the build on Mac OSX 10.11.4 with no errors.

**Comment by nschonni** [comment]
Imagmin uses PhantomJS for the sprites. Since PhantomJS is a native binary, it likely won't play nice when you upgrade internals. Clearing the caching and trying to re-install will likely pulldown/check for the lastest binary.

**Comment by shawnthompson** [comment]
@nschonni clearing what cache? I've tried fresh install on a Macbook (my wife's) that's never ran WET. Had to install everything, git, Xcode, node, java and still had the error.

**Comment by nschonni** [comment]
I'd have to look at the install again, but from what I recall, the phantomjs binary gets pulled down during the install if it doesn't find a local compatible version. It looks like it is currently pointing to the older 1.9 https://github.com/asciidisco/grunt-imagine/blob/master/package.json#L38 which isn't supported anymore https://www.npmjs.com/package/phantomjs.
I could be wrong that Phantom is causing this, but I can't think of anything else that would cause platform difference problems.

**Comment by LaurentGoderre** [comment]
I don't think this is critical though since it doesn't affect the build on Travis and you could use docker to build until this is fixed

**Comment by shawnthompson** [comment]
@LaurentGoderre tried using docker and I'm getting the same error with this docker image.

https://hub.docker.com/r/jolicode/nvm/

I'm going to need your help setting docker up because I'm not able to build wet on anything. I've got to to be doing something wrong.

**Comment by shawnthompson** [comment]
@nschonni!!!! OMG OMG!!! you were right (I should NEVER doubt you!) I installed the latest phantomJS globally and it now builds on my Mac OS system! So now we need to see if [grunt-imagine](https://github.com/asciidisco/grunt-imagine) will update to the new phantomJS.
