### ISSUE TITLE
wb-popup-mid class not horizontal align centre in IE11

### ISSUE THREAD

**Issue by Christopher-O** [wet-boew/wet-boew#7688]
The newly implemented wb-popup-mid class does not properly align in Internet Explorer 11.  It works fine in Firefox but in IE11, it aligns to the top and the left of the browser.    I have created a IE11 only hack for our custom CSS, but it might be something to add to a future update of WET 4.   Thanks.

@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {  
.wb-popup-mid {
    border-radius: 6px;
    bottom: 0px;
   left: 0px;
    margin: auto;
    right: 0px;
    top: 0px;
   width:90%;
   max-height:90%;
  max-width:90%;

}
}

**Comment by masterbee** [comment]
@Christopher-O - thanks for this. I have tested your issue out on my machine but was not able to replicate. I have a few custom themes and tweaked my windows native theme a bit so that could be the culprit. 

Do you mind putting a screenshot in this thread or the before and after? Also, since you did all the work for the fix, any interest in P.R'ing that is as well? No sense some else get the credit for your hard work 🐹

**Comment by Christopher-O** [comment]
![modalalign](https://cloud.githubusercontent.com/assets/9367162/19892152/1d602b02-a009-11e6-80a7-cafe82d2563d.png)
Here is a screenshot of an example. My apologies, its more just left aligning rather than at the top.  
And also I have never done a Pull Request before so I have no problem someone taking the lead on that.  I would just be happy to contribute.

**Comment by Christopher-O** [comment]
![modalaligncntr](https://cloud.githubusercontent.com/assets/9367162/19892410/5e292b1a-a00a-11e6-97c2-dd5975a81618.png)
And for reference, here is the overlay when the CSS is applied.

**Comment by cfarquharson** [comment]
@masterbee can this be merged into V4.0.23 instead?

**Comment by kodecount** [comment]
@cfarquharson Posted a PR. New to SASS so hope it good enough.

**Comment by cfarquharson** [comment]
@kodecount Did it get merged into WET4.0.23?

**Comment by kodecount** [comment]
@cfarquharson No. PR #7446.

**Comment by kodecount** [comment]
@cfarquharson No. It won't be added till v4.0.24

**Comment by duboisp** [comment]
As discussed in #7775, the solution proposed by @Christopher-O require further investigation to know if an alternative solution, without any CSS hack, can be used. 

Thanks @Christopher-O for the proposal solution, Thanks @kodecount for the PR.

## Tasks
* [ ] Investigate for an alternative solution that do not use any CSS hack ***(Not assigned)***

**Comment by Christopher-O** [comment]
Thank you for looking into this further....the included code was used as I tried to update the current code to fix the issue, but anything I did that fixed it for IE, would break it for Firefox so that was the only solution I could think of.  If any other fix could be done that would be great.  We will continue to use the injected CSS for IE on our template until a permanent solution can be discovered.

**Comment by Christopher-O** [comment]
After all the confusion, it looks like simply adding the style width: 90%; to the class wb-popup-mid solves the issue.  I tested it in IE11 and Firefox 35 and it centres the overlay.  Can that be added instead of the "hack"?

**Comment by kodecount** [comment]
@Christopher-O I've updated the pull request.

**Comment by Christopher-O** [comment]
Thank you so much @kodecount
