### ISSUE TITLE
"Monthpicker" + datepicker first date

### ISSUE THREAD

**Issue by Beastmais27** [wet-boew/wet-boew#7691]
Hello,

Does the group have any plans to make or maybe is there a "monthpicker" polyfill (input type="month")?

Also there a way to make it so that when you click on the calendar button, it shows the date that in the textbox, not the current date?

Let me know and thank you for your time.

Cheers,
Beastmais27

**Comment by LaurentGoderre** [comment]
@Beastmais27 the latest version should display the selected date on the calendar and revert to the current date if no date is selected

**Comment by kodecount** [comment]
@Beastmais27 @LaurentGoderre Their is a [month polyfill](https://github.com/jonstipe/month-polyfill) except I can't see input `type="month"` being accepted yet as it not fully supported by all browsers.

**Comment by Beastmais27** [comment]
Hello, 
Sorry for the delay,

@LaurentGoderre do you know what version that was fixed? I currently am using 4.0.21 and it does not to work no matter what way i send it the information.
I have tried date with the format "dd/mm/yyyy" and "yyyy/mm/dd" in string and in datetime
Maybe I am sending it the information the wrong way?
Let me know.

@kodecount Thank for the month polyfill you suggested, it technically got the correct functionality that I need. I will still looking for something similar that does not have the day at all (it be sorta like having 2 dropdown: one is the month and one is the years; or like a datepicker with a 3 by 4 table with the name of the month in them and at the top a year selector). Users requested something "Nicer looking" which I can understand why.

@kodecount @LaurentGoderre I know that the `type="month"` is not accepted fully by all browsers but I still kinda want to know if WET had any future plans to add one (or some sort of ability to only select month and year from datepciker). 

Thank you very much for your time 
Beastmais27

**Comment by LaurentGoderre** [comment]
@Beastmais27 aaah! The picker follows the specs, which uses ISO dates format. This is the only format it understands (note that even if Chrome's native date picker shows your system date display preferences, what is actually returned from the picker is an ISO date). So dates should be the format yyyy-mm-dd

**Comment by LaurentGoderre** [comment]
About the month plugin, I also doubt we can pick a third party one without testing it for accessibility first.

**Comment by kodecount** [comment]
@LaurentGoderre Totally understand that thought I throw it out their in case your interested.

@Beastmais27 What you could do is have two text input boxes one which only accepts year values and the other only accepts a month value. You could create your own JavaScript method to validate the method or more ideal if using jQuery Validation (which is built into WET) you can create your own validation method and pass it a range for the years or months you wish to accept.

**Comment by kodecount** [comment]
@Beastmais27 If interested in the jQuery Validation idea I don't mind helping.

**Comment by Beastmais27** [comment]
Hello,

@LaurentGoderre Thank you very much, it appears i did have the incorrect date format.

@kodecount Thank you for the example sent. It good to know what our thoughts are sorta in sync for a work around monthpicker. And thank you very much for the offer but for now the month picker was a "Nice to have" due to new time constraint.

Thank you very much for everything guys,
I will now close this issues.

Cheers,
Beastmais27
