### ISSUE TITLE
Menu: Sub-Menu doesn't expand with IE 8

### ISSUE THREAD

**Issue by jmpotvin** [wet-boew/wet-boew#7692]
Users cannot expand sub-menus with IE8.

    1) Using IE8 -- Go to http://wet-boew.github.io/v4.0-ci/demos/menu/menu-en.html# 
 
    2) In the top menu, expand the Section 3.

    3) Try to expand one of the Sub-Section.

**Comment by RobJohnston** [comment]
Support for IE 8 was ended on 2015-01-01 and for IE 9 on 2015-10-01. This was part of the [release notes of 4.0.21] (https://wet-boew.github.io/wet-boew/docs/versions/v4.0/v4.0.21-en.html).

You can see the justification of why support ended for IE8 in #6646... usage fell below 5% quite some time ago. And also from that issue:

> We should make it clear that we are not stripping out existing support, just that we will not be actively maintaining that support. So things will still likely work well on IE8 and IE9, but that we will treat any new issues raised for IE8 and IE9 as low priority (community can submit PRs to address issues quicker if they like).

**Comment by masterbee** [comment]
closed since will not address due to browser support
