### ISSUE TITLE
wet-boew-texthighlight as search in page

### ISSUE THREAD

**Issue by eswright** [wet-boew/wet-boew#7699]
can I use this to search in a page?   Does someone have an example or a page up that builds the url from a form input?

**Comment by masterbee** [comment]
@eswright -  this should be pretty simple with a form that posts the parameter 'txthl' and is a **get** action. Here is some quick sample code to illustrate.

```
<form action="%pageyouwanttosearch%" method="get">
            <label for="search-highlight">Enter the search term to filter the page</label><br />
            <input type="text" id="search-highlight" name="txthl" placeholder="i.e influenza cook"><br />
            <button type="submit" class="btn btn-default">Search</button>
</form>

**Comment by eswright** [comment]
thanks I'll try that.   Also....do you know why I can;t find an example of at datatable loaded from a json file? I assume this would be ajaxed

**Comment by kodecount** [comment]
Take a look at #6445

**Comment by masterbee** [comment]
closing issue to since issue appears to be resolved - @eswright  you are welcome to open an new ticket if there are issue with what was recommended.
