### ISSUE TITLE
Input type="date" polyfill (date picker): 

### ISSUE THREAD

**Issue by jisheedpdm** [wet-boew/wet-boew#7701]
I have used this control in angular 2 but the localization is not working.

**Comment by jisheedpdm** [comment]
Localization for the control is not working.

**Comment by jisheedpdm** [comment]
@wet-boew-bot localization for this control???

**Comment by cybersubtype** [comment]
@jisheedpdm On certain browsers where the poly-fill isn't managed by wet-boew you can't change the language or format of the date picker. As for IE and Firefox the datepicker will change to french but you have to update your html tags from `<html lang="en">` to `<html lang="fr">`. Also look at issue #1992.

**Comment by cybersubtype** [comment]
@jisheedpdm Also check out the date picker here: https://wet-boew.github.io/v4.0-ci/demos/formvalid/formvalid-fr.html on Chrome its in English (since it is using the browsers poly-fill), but in IE it is french. Not all localization are supported anymore if the language you seek is not available for the wet date picker you can provide localization can help the project.

**Comment by jisheedpdm** [comment]
Is there any way to add lang attribute dynamically in angular 2?? I think this will solve the localization issue.

**Comment by cybersubtype** [comment]
http://stackoverflow.com/questions/34904683/how-to-set-locale-in-datepipe-in-angular2
http://stackoverflow.com/questions/26461711/angularjs-dynamic-lang-attribute-of-html
http://stackoverflow.com/questions/34152526/how-to-set-html-lang-attribute-dynamically

**Comment by jisheedpdm** [comment]
@wet-boew-bot I already tried these links but they are not working as expected.

**Comment by jisheedpdm** [comment]
@wet-boew-bot I also tried by using a directive like 

import { Directive, ElementRef, Input, Renderer } from '@angular/core';
@Directive({ selector: '[dynamicLanguage]' })
export class DynamicLanguageDirective {
    constructor(el: ElementRef, renderer: Renderer) {
        renderer.setElementAttribute(el.nativeElement, 'lang', 'fr');
    }
}

But this too not working

**Comment by cybersubtype** [comment]
It seem angular translate don't support html lang dynamically: https://github.com/angular-translate/angular-translate/issues/1309

**Comment by LaurentGoderre** [comment]
Don't you have an html tag on your angular app?

**Comment by LaurentGoderre** [comment]
Though, I see it can be an issue with switching the language of the app.....

**Comment by jisheedpdm** [comment]
yes I have an HTML tag

**Comment by LaurentGoderre** [comment]
That's what determines the language of the page.

**Comment by cybersubtype** [comment]
@jisheedpdm If your switching language using a button you could use pure jQuery to change to the attribute.

```html
<a class="lang" lang="fr" hreflang="fr" href="?request_locale=fr">Français</a>
```

```javascript
$('.lang').click(function(e) {
  var lang = $(this).attr('lang');
  $('html').attr('lang', lang);
});
```

**Comment by LaurentGoderre** [comment]
but this wont change any of the wet plugin language though

**Comment by jisheedpdm** [comment]
@LaurentGoderre  Yes. That's right. These won't changes the WET plugin language. I am able to change the language of the page by using setElementAttribute() method but it won't change the WET plugin language.

**Comment by LaurentGoderre** [comment]
At the moment, it's probably best to reload the page when changing the language

**Comment by kodecount** [comment]
If still having a issue setting the html lang tag you can try using JavaScript cookies. Here a quick jsFiddle with that: https://jsfiddle.net/kpduncan/64dranL1/

**Comment by masterbee** [comment]
closing issue since appears to be addressed with good sample code for immediate workaround.
