### ISSUE TITLE
Menu: navcurrent (bug report)

### ISSUE THREAD

**Issue by kodecount** [wet-boew/wet-boew#7702]
The issue occurs on a page where I'm loading a datatable. The datatable requires a spinner while it loads a lot of data the spinner freezers on IE 11 seem to be conflicting with the navcurrent. For the spinner I'm using font-awesome spinner.

**Comment by cybersubtype** [comment]
I can confirm the issue is related to a large datatable. When I commented out the datatable table and populate the page with the spinner it works fine.
