### ISSUE TITLE
Tables: thick or double cell borders

### ISSUE THREAD

**Issue by Sburbidge** [wet-boew/wet-boew#7703]
Good morning,

We are constantly asked when converting to HTML asked to replicate as close as possible to the original source document. I was wondering if in WET4 there is a class which would replicate a thicker and/or a double border on TD/TH cells in tables as found on w3schools.com below. If these classes do not exist, can they be created and added to the WET4 stylesheet?

http://www.w3schools.com/cssref/tryit.asp?filename=trycss_border-bottom-style

.double {
	border-bottom:3px double; (or more px to fit the template format)

.thick {
	border-bottom:2px solid; (or more px to fit the template format)

On http://www.irb-cisr.gc.ca/Eng/BoaCom/pubs/Pages/EtaFinSta1112.aspx. there's an example of the expected results (even though they use their own in-house styles).

I've also attached an example.
[borders.docx](https://github.com/wet-boew/wet-boew/files/541704/borders.docx)

Thank you.

**Comment by cybersubtype** [comment]
In future you can drop images right into GitHub and it well attach them to the issue/comment.

As for horizontals line I don't believe their is a WET class for that. The demo link is using custom style sheet. You can check out this: https://github.com/wet-boew/wet-boew/issues/7678

**Comment by Sburbidge** [comment]
Yes, as stated in the original request, the demo is using custom styles. The link was only provided for visual purpose to complement the code from W3C. I read issue #7678 but I was under the impression that we had to refrain from using "style". The question remains, can 2 new classes be added to the WET4 stylesheet to represent the above? How do we proceed to make this request? P.S. thanks for the tip for dropping images. 
![borders](https://cloud.githubusercontent.com/assets/18724824/19561303/1f1c7fd4-96a6-11e6-8205-9b97e76a86cd.png)

**Comment by cybersubtype** [comment]
http://wet-boew.github.io/wet-boew/docs/start-en.html#develop

**Comment by Sburbidge** [comment]
Thank you. I will look into it.

**Comment by duboisp** [comment]
@Sburbidge Try to re-write your table by following the [12 techniques for complex table](http://wet-boew.github.io/wet-boew-legacy/v3.1/demos/tableparser/index-en.html). Then you can use the [wb-zebra plugin](http://wet-boew.github.io/wet-boew/demos/zebra/zebra-en.html) to style the table

Cheers

**Comment by Sburbidge** [comment]
I have taken a look at your suggestion above, however, the borders are ticker for the entire column or row. We are only looking to apply a class to some of the cell, specifically ones containing amounts, as in the image previously uploaded.

**Comment by kodecount** [comment]
@Sburbidge Checkout the solution I had in the pull request, but don't look like it be pushed into WET.

**Comment by Sburbidge** [comment]
Leave a comment
We did, however, we are not looking to add a line in a row of TDs. Thanks for the suggestion however.
