### ISSUE TITLE
Recent changes to the Style Guide index page make it much less useful

### ISSUE THREAD

**Issue by terribly** [wet-boew/wet-boew#7706]
The recent changes to the Style Guide index page have made this page MUCH less useful.

It is a key reference page. It is now much harder to scan. It puts items of less common use and of lesser import into the list with things that are more important. The three column layout is very hard to scan. 

I recommend reverting this to the prior index page.  It was not something that needed fixing. The BREADCRUMBS however, do need to be fixed as they are a mess and this has a direct impact on usability as well.

**Comment by kodecount** [comment]
@terribly I'm not seeing the index page issue, but I agree there is issues with the breadcrumbs (some theme pack demo pages take you to some weird places) and menu link issues.

**Comment by LaurentGoderre** [comment]
Please open this on the right repo http://github.com/wet-boew/wet-boew-styleguide

**Comment by HAKMCQ51** [comment]
You changed the layout WOW! - how about fixing the breadcrumbs

**Comment by masterbee** [comment]
closed since issue is to be raised in correct repository
