### ISSUE TITLE
 Size restrictions?Tables: 

### ISSUE THREAD

**Issue by SBleeks** [wet-boew/wet-boew#7708]
The documentation here says that this plugin can be used for large data table sets. 
1. is there a practical limit to the number of rows that can be used? is 1000 rows too much Is 5000 rows too much?  
1. Is there a ppoint where data sets might be too large and a CSV file would be recommended?

**Comment by kodecount** [comment]
According to the [DataTable Group](https://datatables.net/forums/discussion/24037/what-is-the-limit-of-records-we-can-deal-with) the tables can handle around 50,000-100,000 records. The best way to load them is server-side.

This said be aware of accessibility mode where all rows are displayed (pagination is disable). You'll want to look into making the table scroll able.

**Comment by kodecount** [comment]
If need help with the spinner I have a quick JavaScript method for that.

**Comment by masterbee** [comment]
closing issue since appears to be address with good references and samples. @SBleeks we welcome you to open a new ticket if you need more clarification on datatables

**Comment by SBleeks** [comment]
OK. Will be opening a new ticket.

**Comment by SBleeks** [comment]
I asked 2 questions. I'll open a new ticket and ask again.
