### ISSUE TITLE
Possible Secure / Unsecure issue in feed.js

### ISSUE THREAD

**Issue by crochefort** [wet-boew/wet-boew#7713]
Just doing some test and saw that some call to youtube are http instead of the usual //

Like this line : https://github.com/wet-boew/wet-boew/blob/master/src/plugins/feeds/feeds.js#L87

https://github.com/wet-boew/wet-boew/blob/master/src/plugins/feeds/feeds.js#L151

and this line : https://github.com/wet-boew/wet-boew/blob/master/src/plugins/feeds/feeds.js#L444

Got my finding from this page... 
https://www.whynopadlock.com/

So might be good to take a look on the source code to see if it's possible to remove all http:// and juste put // instead...

Since not good with GitHub ... a PR from me is not an option! 

@masterbee @LaurentGoderre what do you think??

Might cause future secured content to not show the padlock if canada.ca is https

**Comment by kodecount** [comment]
Issue #7583 probably relates. Also see #7679.

**Comment by masterbee** [comment]
@crochefort - thanks for this. I agree it would probably be best that we address this issue the same way we have address the original feed with ```wb.pageUrlParts.protocol ```

**Comment by kodecount** [comment]
@masterbee The problem with `wb.pageUrlParts.protocol` is it is also returning `http` which can break the feed plugin. Just look at  #7583.

**Comment by kodecount** [comment]
@masterbee I did some testing on a Government Network and on my personal network. It seems if `wb.pageUrlParts.protocol` produces `http` and it is being block by SmartFilter application.

Here is an example with Pinterest (generated URL):
`http://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20feed%20where%20url%20%3D%20%27https%3A%2F%2Fwww.pinterest.com%2Fhealthycdns%2Fdrug-prevention.rss%27%20limit%205&format=json`

**Comment by masterbee** [comment]
@kodecount - thanks I was under the impression that yahoo query had an http counterpaart but it looks like probably not. Appreciate the test and will tweak this.

**Comment by kodecount** [comment]
@masterbee It does it just not reliable. It seem some networks accept it and some block it. Not sure why.

**Comment by masterbee** [comment]
@kodecount - ahh ok. I have been meaning to look at a more native solution since CORS is now more main stream. What are your thoughts on the native alternative? 

It would reduce the dependency on 3rd party free stable solutions which are becoming more of a rarity, and allow for easier plugin extensions further down the road. The only concern I really have is more about the major players like Pinterest, Instagram, Linkedin, etc. have implemented a CORS solution or are they pushing API keys as they were hinting at last year.

**Comment by kodecount** [comment]
@masterbee The CORS sounds nice but it relies on the site you want data from to support it. I haven't dealt with many JavaScript feeds, I've done some research on the topic and it becoming a common thing to see depreciated (Google and Facebook are two examples). Also on the note of Yahoos YQL it seems `https` is becoming the norm ([example](https://github.com/enginkizil/FeedEk/blob/master/js/FeedEk.js#L27)).

**Comment by masterbee** [comment]
closed since addressed with P.R - https://github.com/wet-boew/wet-boew/pull/7719. Will be creating feature issue for CORS variant at a later date.
