### ISSUE TITLE
Form validation: 

### ISSUE THREAD

**Issue by akselsoft** [wet-boew/wet-boew#7724]
Question: This section does not explicitly state the (required) is "required" at the end of the field label. In fact, that entire section is marked as "optional". It IS stated that the input object be marked as Required.

Since a screen reader would readily identify these fields as required, if a suitable equivalent was used (asterisk with label, etc), is this mandatory?

Can this be clarified?

Thanks

**Comment by LaurentGoderre** [comment]
For usability and accessibility, it is recommended to use both. Screen reader is only one of the assistive technology used and the required attribute don't necessarily help those.

**Comment by kodecount** [comment]
This was furthered discussed here: https://github.com/wet-boew/wet-boew/issues/7896

I would say this issue can be closed (instead of having multiple of the same one).
