### ISSUE TITLE
Equal height class not working

### ISSUE THREAD

**Issue by jsguy1** [wet-boew/wet-boew#7726]
The equal height class (.wb-eqht) isn't working when I apply it in the following code:

```html
<div class="row wb-eqht">
    <div class="col-sm-8">
        <div class="well">
            text
        </div>
    </div>
    <div class="col-sm-4">
        <div class="well text-center">
			text<br>text<br>text
        </div>
    </div>
</div>
```

When I change col-sm-8 and col-sm-4 to col-sm-6 and col-sm-6 respectively, it works. But not with my existing column layout.  Any help is appreciated.

**Comment by EricDunsworth** [comment]
@jsguy1 It should work if you add the ``hght-inhrt`` class to ``<div class="well">`` and ``<div class="well text-center">``.

The equal heights plugin works by setting ``style="vertical-align: top; min-height: #px;"`` on the direct children of the ``wb-eqht`` container. But in this case, you're trying to get it working 2 levels down. So they need the ``hght-inhrt`` class to inherit the height of their parents.

More info can be found in the [equal heights plugin's documentation](http://wet-boew.github.io/v4.0-ci/docs/ref/equalheight/equalheight-en.html).

**Comment by jsguy1** [comment]
Thanks Eric! This worked.

**Comment by kodecount** [comment]
@jsguy1 Don't forget the close the issue when solved. Thanks.

**Comment by masterbee** [comment]
closing issue since appears to be resolved.

P.S. Thanks @kodecount  for mentioning as well.
