### ISSUE TITLE
Twitter no longer requires the Widget-ID

### ISSUE THREAD

**Issue by fgjohnson** [wet-boew/wet-boew#7727]
Hi,
Twitter no longer requires or allows the creation of a  "widget ID".
The Drupal Wetkit Variant depends on the javascript code.

Can this be updated to not require the Widget ID?

Thanks
Grant

More info can be found at twittercommunity here:
https://twittercommunity.com/t/how-can-i-get-a-twitter-widget-id/68917

and at

Wetkit downstream @ the Drupal Variant here:
https://www.drupal.org/node/2778507

**Comment by masterbee** [comment]
@fgjohnson - thanks for this. It makes sense to evolve the plugin the issue we have is that we have to ensure some non-breaking changes for the plugins evolution. I am sure it is simple since on the surface it looks like just a URL fix, but have not done a deep dive to see if this is the case.  We will take a look to see.

**Comment by LaurentGoderre** [comment]
Maybe that's a good reason to create unit test for this then?

**Comment by fgjohnson** [comment]
Laurent,
I don't know how to do that! :-)

**Comment by LaurentGoderre** [comment]
It should be done by the WET theme

**Comment by fgjohnson** [comment]
So... is that here https://github.com/wet-boew/themes-dist?
Does this need to be assigned there?

**Comment by LaurentGoderre** [comment]
Oops, i meant WET team

**Comment by fgjohnson** [comment]
Good. :-)
Thanks.

**Comment by fgjohnson** [comment]
Has there been any movement on fixing this?

**Comment by kodecount** [comment]
As for the _"...depends on the javascript code."_ I don't think WET can provide a proper feed without JavaScript as you need some sorta language to read the URL where the data is coming from. The best WET could do is provide a message saying JavaScript required for this plugin or hide the plugin. Other then that the fallback would rely on the app create to come up with a solution within their code environment.

**Comment by kodecount** [comment]
This is what I can tell you need widget id for search embedded timelines, but not a users profile:
```
<div class="wb-twitter">
   <a class="twitter-timeline"
      href="https://twitter.com/WebExpToolkit"
      data-width="300"
      data-height="300">
      Tweets by @WebExpToolkit
   </a>
</div>
```

**Comment by kodecount** [comment]
This is what I can tell you need widget id for [embedded search timelines](https://dev.twitter.com/web/embedded-timelines/search), but not a users profile:
```javascript
<div class="wb-twitter">
   <a class="twitter-timeline"
      href="https://twitter.com/WebExpToolkit"
      data-width="300"
      data-height="300">
      Tweets by @WebExpToolkit
   </a>
</div>
```
Maybe the documentation should be updated to example users well need to create a search query (which requires a twitter account) for the widget id, but when using a user id like `@WebExpToolkit` no widget id is required.

**Comment by kodecount** [comment]
@masterbee @LaurentGoderre Thoughts? I don't mind updating the documentation (I can start English and someone could cherry pick my branch with their French version).

**Comment by kodecount** [comment]
I've also updated with examples on my thoughts on what the demo and documentation should look like.

**Comment by fgjohnson** [comment]
Agree,
Just opened my eyes and realized that it's easier to forget the Twitter Widget all together...
Just create a Bean and use the Twitter ember code that you pointed to.

This is a satisfactory solution for me.

Issue can be closed unless others are interested in pursuing.

**Comment by LaurentGoderre** [comment]
I think we still want to fix this.

**Comment by kodecount** [comment]
@LaurentGoderre Their is no code to fix just demo and documentation to update. I can start this if you want someone would need to do french.

**Comment by LaurentGoderre** [comment]
That would be great!

**Comment by kodecount** [comment]
PR https://github.com/wet-boew/wet-boew/pull/7885
