### ISSUE TITLE
Overlay: 

### ISSUE THREAD

**Issue by zomby22** [wet-boew/wet-boew#7733]
Hello

The FULL SCREEN Overlay Side Scrollbar doesn't work using the mouseover to scroll down when the page contains long list of data or information content. It works when the page is short.
![scroll](https://cloud.githubusercontent.com/assets/20478259/19944332/d2f39504-a111-11e6-8c72-c76cc8938bfc.jpg)

Example code:
```
<section id="viewreport" class="wb-overlay modal-content overlay-def wb-popup-full">
	<header class="modal-header">
		<h2 class="modal-title">View Report</h2>
	</header>
	<div class="modal-body">
	<!--#include file="registrants.asp"-->
	</div>
</section>
```

**Comment by kodecount** [comment]
What browser are you using? For me Chrome 54, Firefox 49, IE 11 all work fine. Are you just code dumping with this `browser` or are you formatting the code?

**Comment by kodecount** [comment]
What browser and version of WET are you using? For me Chrome 54, Firefox 49, IE 11 all work fine. Are you just code dumping with this  or are you formatting the code?

**Comment by zomby22** [comment]
WET4 and IE11. Try a data table with over 1000 table rows and see if you get the same effect. I can only browse the overlay properly with the keyboard. Not working with the mouse when trying to drag the bar or use the arrows.

**Comment by kodecount** [comment]
No issue here. Also maybe effect by this https://github.com/wet-boew/wet-boew/issues/7362 for IE.

**Comment by kodecount** [comment]
What version of 4?

**Comment by zomby22** [comment]
same, im pretty sure its 4.0.21 or 22 (government platform)
IE11: I just try without the include file, and got the same result.
Firefox 35.0.1: works but I see two scrollbar.
Firefox with large table:
![1](https://cloud.githubusercontent.com/assets/20478259/19979523/2833eedc-a1d1-11e6-8404-1f5895a91d02.jpg)
Firefox with small table:
![2](https://cloud.githubusercontent.com/assets/20478259/19979528/2e0262bc-a1d1-11e6-9c30-879b4031da0d.jpg)

**Comment by kodecount** [comment]
@zomby22 Do you have any scrolling enabled on your data-table or in a table-responsive div?

**Comment by zomby22** [comment]
not using datatable. Just plain table.

```
<table class="table small table-responsive">
      <thead>
```

**Comment by zomby22** [comment]
if I limit the table to 6 rows, I see 1 scrollbar in firefox. 7 or more rows, the two bars is showing like the screenshot above.

**Comment by kodecount** [comment]
@zomby22 I can't reproduce the issue.

@masterbee @LaurentGoderre @nschonni

**Comment by zomby22** [comment]
I don't know what to say. The overlay scrollbar is overlapping the browser scrollbar when the overlay fullscreen page is long.

**Comment by zomby22** [comment]
Does your button link look similar to this:

`<a href="#viewreport" aria-controls="viewreport" class="overlay-lnk">Registrants</a>`

**Comment by kodecount** [comment]
@zomby22 On any of the version of WETs I've used the overlay don't produced a scroll bar.

**Comment by masterbee** [comment]
@zomby22  same things as well was not able to reproduce,, IE edge, IE11, Chrome v54, and Firefox 49.  May it is the network your on. Sounds weird but we have had numerous bugs we could not replicate  and discovered later it was related to network either being too restrictive (not allowing certain files to the browser ) and or heavy caching created some mixed version of dependencies files.

**Comment by zomby22** [comment]
I do see a invisible scrollbar on the right with the example source link I included above. I get the same result at home using my personal computer, so its not just at work.

**Comment by kodecount** [comment]
@zomby22 Where is this code? Is it a public or work project? What exact version of WET are you using?

**Comment by zomby22** [comment]
WET 4.0.22 (click on this link, then click on "full screen overlay", tell me if you see it) http://wet-boew.github.io/v4.0-ci/demos/overlay/overlay-en.html
![3](https://cloud.githubusercontent.com/assets/20478259/20061576/5ec3396c-a4ce-11e6-8891-5432054941ec.jpg)

**Comment by kodecount** [comment]
@zomby22 What is the OS (windows, mac, etc.) your using?

**Comment by kodecount** [comment]
Yes by design in IE it is transparent?

**Comment by zomby22** [comment]
yup, but when you add more content to make the page long enough to scroll down, this transparent scrollbar appears on the top of the browser scrollbar causing two scrollbar, therefore I can only scroll the page up and down using the keyboard. If you can't reproduced the error, than I guess will just let it be.

Windows 7 32bit, IE11.

**Comment by kodecount** [comment]
@zomby22 Weird your getting two scroll bars that is the part we cannot reproduce. Have your tried removing any all the classes but `tables` to see what well happen?

**Comment by kodecount** [comment]
@zomby22 What theme pack are you using?

**Comment by zomby22** [comment]
I decided to do like you, I create an empty page with long content and its working. Maybe the ASP content is creating this effect somehow!?

**Comment by kodecount** [comment]
@zomby22 No I found the issue.

**Comment by kodecount** [comment]
@zomby22 In the mean time you could try this `<table class="table small table-responsive" style="overflow-y: hidden;">` ?

**Comment by zomby22** [comment]
thanks, the overflow didn't work. Ill run some more test later (table with plain text and a table with some database data to see if there is a difference)

**Comment by kodecount** [comment]
@masterbee It is weird I can reproduce issue on here: https://wet-boew.github.io/v4.0-ci/demos/overlay/overlay-en.html but not in the intranet theme.

**Comment by zomby22** [comment]
I am using the Intranet theme.

**Comment by kodecount** [comment]
@zomby22 Crazy though do you have any detail->summary->p toggle elements?

**Comment by kodecount** [comment]
@zomby22 Crazy though is the page where the overlay button located very long?

**Comment by kodecount** [comment]
@zomby22 I may be crazy but it seem if the page has it self is long then the overlay creates the double bar.

**Comment by kodecount** [comment]
@masterbee @LaurentGoderre @duboisp Would their be anyway to set the body of the page to `overflow: hidden;` only when the overlay is active? This seems to be the issue. If the body/webpage which hosts the overlay current has overflow. Any overlay with overflow will create a second bar. If the body is set to overflow hidden while the overlay is active the issue is fixed.

**Comment by zomby22** [comment]
I found the problem:

if this link is outside it works, else if inside this panel, it creates this double bar.

```
<div class="panel panel-default mrgn-tp-md">
    <div class="panel-heading">
     <h2 class="panel-title">Table of contents</h2>
    </div>
    <div class="panel-body">
    	<div class="col-md-4">
        <strong>View report</strong>
      <ul>
        <li><a href="#viewreport2" aria-controls="viewreport2" class="overlay-lnk">testing</a></li>
      </ul>
    </div>
```

**Comment by zomby22** [comment]
having a datatable table and the overlay page on the same page will also cause the double bar.

**Comment by kodecount** [comment]
@zomby22 I believe it has nothing to do with the table. It not a data-table you are using. As you mentioned in a previous comment. You said your using: `<table class="table small table-responsive">` which is a plain table with WET styling.

**Comment by kodecount** [comment]
@zomby22 As I mentioned above it has something to do with the page under the overlay having scroll length and the overlay also having a scroll length.

**Comment by kodecount** [comment]
@zomby22 I may be crazy but it seems if the page it self is long then the overlay creates the double bar.

@masterbee @LaurentGoderre @duboisp Would their be anyway to set the body of the page to `overflow: hidden;` only when the overlay is active? This seems to be the issue. If the body/webpage which hosts the overlay current has overflow. Any overlay with overflow will create a second bar. If the body is set to overflow hidden while the overlay is active the issue is fixed.

**Comment by zomby22** [comment]
your right, the overflow to the body does make the overlay working properly. However, doing this prevents me from scrolling the main webpage.

**Comment by zomby22** [comment]
maybe this will help, haven't try it yet:
http://luxiyalu.com/playground/overlay/

**Comment by kodecount** [comment]
@zomby22 Nice find. Hopefully the WET team well be interested.

**Comment by zomby22** [comment]
should this work, cause its not for me:

```
body.modal-open {
    overflow: hidden;
}
```

```
$("#viewreport").on("show", function () {
  $("body").addClass("modal-open");
}).on("hidden", function () {
  $("body").removeClass("modal-open")
});
```

**Comment by masterbee** [comment]
@zomby22 - ditto on the nice find. I am going to tag this for the next version since there is some review of overlays as a whole that was on the radar.
