### ISSUE TITLE
Login buttons

### ISSUE THREAD

**Issue by pompousmoose** [wet-boew/wet-boew#7738]
I've been poking around trying to find my answer but I can't, so I'm hoping that someone can point me in the right direction. 

I can't find any documentation on how to handle the login events.  I don't really understand how to implement the 'signed-on' and 'signed-off' template pages.  Do I have to handle the events that redirect the users to the different pages?  There seems to be some session settings that does some automatic redirections but that doesn't really help to set me on the right path.  I assume that I'm just to hide and show the login buttons when appropriate.

I'm a relative newbie to all this so thanks for your understanding.

**Comment by kodecount** [comment]
@pompousmoose WET is just a front-end framework at the end of the day. Logins should be handle by your back end (server). I can give some tips depending on the server language, but this isn't a WET issue. I'm use to Java frameworks like Spring, or Struts 2.

Also you can read #1753 or #6232.

**Comment by masterbee** [comment]
closing the issue since the question appears out of scope for WET. @pompousmoose feel free to re-open another ticket if you have another question about WET.
