### ISSUE TITLE
Overlay/data-inview broken if their demo css is removed

### ISSUE THREAD

**Issue by duboisp** [wet-boew/wet-boew#7741]
Discovered when working on PR #7740 

Overlay and data-inview plugin require the demo CSS in order to work properly.

When that demo CSS is removed, Full-screen modal background color became transparent and top and bottom bar background color became transparent also.

This issue was introduced by the changes from PR #7668

Cheers

**Comment by LaurentGoderre** [comment]
That is by design I think, isn't it @shawnthompson. The menu needs to specify it's own color, and I believe themes need to define them as well.

However, the correct way of implementing #7668 would have been to add variables so that at least there is a default.

**Comment by duboisp** [comment]
I updated PR #7740 and it may fix this issue. I am just waiting for confirmation.
