### ISSUE TITLE
generator-wet-boew-theme

### ISSUE THREAD

**Issue by kodecount** [wet-boew/wet-boew#7749]
I been trying to get this to work with:

Windows 7
Git for windows
NodeJS

and

Ubuntu
Git
NodeJs

I get same results each time it fails. The log is super large so including a file: [npm-debug.txt](https://github.com/wet-boew/wet-boew/files/581295/npm-debug.txt)

**Comment by nschonni** [comment]
Probably better to open this on https://github.com/wet-boew/generator-wet-boew-theme
The issue is that it's still using a really old version of grunt-sass/node-sass, that doesn't support the newer Node runtimes.
