### ISSUE TITLE
ie8 video player

### ISSUE THREAD

**Issue by robmausser** [wet-boew/wet-boew#7765]
In the latest version of the WET toolkit, it does not appear the video player works in ie8.

Is there  an alternative or solution for this?

Thanks

**Comment by kodecount** [comment]
@robmausser IE8 and IE9 support was ended.

**Comment by kodecount** [comment]
@robmausser You could offer the ability to download the video in old browsers. Be easiest solution.

**Comment by robmausser** [comment]
@kodecount can you please tell me what version of WET still has ie8 support? I will have to grab the video player from that version and shoehorn it into the latest version of the toolkit: client absolutely demands ie8 support.

**Comment by MaximMartel** [comment]
@robmausser IE support ended at : 2015-01-01. So based on the roadmap page : http://wet-boew.github.io/wet-boew/docs/versions/rdmp-en.html, the last version that had IE8 support was :  v4.0.9 release.

**Comment by kodecount** [comment]
@robmausser I'm not sure what version work with IE8, but it be any version under v4.0.9.

**Comment by LaurentGoderre** [comment]
WE didn't rep the support out of it though so it should still in theory work with IE8

**Comment by kodecount** [comment]
@LaurentGoderre I find their is a lot that still works in IE8, but I find that a lot of JavaScript no longer works. Sites are still usable.

**Comment by robmausser** [comment]
@LaurentGoderre it absolultely 100% does not work in IE8, including your own examples online: https://wet-boew.github.io/v4.0-ci/demos/multimedia/multimedia-en.html

**Comment by kodecount** [comment]
@LaurentGoderre The video player was update to HTML5 `<video>` tags which don't work in old browsers. You can use a object tag inside of the video tag which that blog I posted suggested.

**Comment by robmausser** [comment]
@kodecount is there any way to grab the video player from older version of WET that works in ie8?

**Comment by robmausser** [comment]
@kodecount the Video for Everybody generator does NOT work for Flash. Tested on 4 computers with 4 browsers.

Flash just shows blank flash plugin

see screenshot here: http://i.imgur.com/0uooDuY.png

Doesnt work on any computer in our office, Firefox, IE, Chrome. 

I think Flash 23 broke this. Cannot use something that doesnt work with latest Flash.

**Comment by LaurentGoderre** [comment]
@kodecount the multimedia has a polyfill that uses Flash when video is supported so it should work

**Comment by LaurentGoderre** [comment]
@robmausser it's possible that the flash part doesn't work in the latest Flash

**Comment by robmausser** [comment]
@LaurentGoderre it doesn't. Not just on my project but on the OFFICIAL WET toolkit page.

See for yourself: https://wet-boew.github.io/v4.0-ci/demos/multimedia/multimedia-en.html

It does not work in ie8. full stop. Stop saying it does. It doesn't.

**Comment by LaurentGoderre** [comment]
I found this commit https://github.com/wet-boew/wet-boew/commit/1d6ba9c7267037ed668ba544497eab8aebab9699 I was not aware that some developers ripped support for ie8. @masterbee why was this done if it breaks semver?

**Comment by LaurentGoderre** [comment]
@robmausser so v4.0.21 is the last version that will work

**Comment by robmausser** [comment]
@LaurentGoderre thank you for the help!!

**Comment by LaurentGoderre** [comment]
Closing since IE8 is not supported
