### ISSUE TITLE
Demande de dotation accélérée - aucune nouvelle

### ISSUE THREAD

**Issue by Dumonts** [wet-boew/wet-boew#7780]
Bonjour

J'ai soumis une demande de dotation accélérée au début de la semaine et je suis sans nouvelle.  Aucun accuse de reception non plus.

Stéphane Dumont
418-803-8436

**Comment by LaurentGoderre** [comment]
@Dumonts ceci est un endroit pour entreposer et discuter de code. Nous n'effectuons aucune tache en lien avec les resources humaines.

**Comment by Dumonts** [comment]
C’est pourtant le lien qui est fourni pour « Questions et commentaires » sur le site de la Dotation accélérée - j’ai suivi la procédure.   A qui dois-je m’adresser alors ?

Stéphane Dumont, ing.
Ingénieur régional | Regional Engineer
Ports pour petits bateaux, Région du Québec | Small Craft Harbours, Quebec Region
Pêches et Océans Canada | Fisheries and Oceans Canada
Gouvernement du Canada | Government of Canada
104 rue Dalhousie, Québec, Qc., G1K 7Y7
Téléphone / Telephone:  (418) 803-8436   Télécopieur / Fax: (418) 648-4470  Cellulaire / Cell Phone (418) 803-8436
Stephane.Dumont@dfo-mpo.gc.ca<mailto:Stephane.Dumont@dfo-mpo.gc.ca>

[cid:image001.png@01D0CDFB.C2CACB60]

De : Laurent Goderre [mailto:notifications@github.com]
Envoyé : 25 novembre 2016 09:30
À : wet-boew/wet-boew
Cc : Dumont, Stéphane; Mention
Objet : Re: [wet-boew/wet-boew] Demande de dotation accélérée - aucune nouvelle (#7780)


@Dumonts<https://github.com/Dumonts> ceci est un endroit pour entreposer et discuter de code. Nous n'effectuons aucune tache en lien avec les resources humaines.

**Comment by LaurentGoderre** [comment]
Quel est ce site??

**Comment by Dumonts** [comment]
Un site intranet de notre Ministère :

https://intra-l01.ent.dfo-mpo.ca/applications/fts-da/

Ça marche comme un mal de ventre ….

Merci de me donner des nouvelles.

Stéphane Dumont, ing.
Ingénieur régional | Regional Engineer
Ports pour petits bateaux, Région du Québec | Small Craft Harbours, Quebec Region
Pêches et Océans Canada | Fisheries and Oceans Canada
Gouvernement du Canada | Government of Canada
104 rue Dalhousie, Québec, Qc., G1K 7Y7
Téléphone / Telephone:  (418) 803-8436   Télécopieur / Fax: (418) 648-4470  Cellulaire / Cell Phone (418) 803-8436
Stephane.Dumont@dfo-mpo.gc.ca<mailto:Stephane.Dumont@dfo-mpo.gc.ca>

[cid:image001.png@01D0CDFB.C2CACB60]

De : Laurent Goderre [mailto:notifications@github.com]
Envoyé : 25 novembre 2016 09:45
À : wet-boew/wet-boew
Cc : Dumont, Stéphane; Mention
Objet : Re: [wet-boew/wet-boew] Demande de dotation accélérée - aucune nouvelle (#7780)


Quel est ce site??

**Comment by LaurentGoderre** [comment]
Ce lien doit y etre par erreur, nous nous occupons seulement de la presentation des sites web.

**Comment by Dumonts** [comment]
Je comprends mais c’est le lien que notre site a donné.

J’ai déjà informé les responsables.  Désolé du dérangement.

Stéphane Dumont, ing.
Ingénieur régional | Regional Engineer
Ports pour petits bateaux, Région du Québec | Small Craft Harbours, Quebec Region
Pêches et Océans Canada | Fisheries and Oceans Canada
Gouvernement du Canada | Government of Canada
104 rue Dalhousie, Québec, Qc., G1K 7Y7
Téléphone / Telephone:  (418) 803-8436   Télécopieur / Fax: (418) 648-4470  Cellulaire / Cell Phone (418) 803-8436
Stephane.Dumont@dfo-mpo.gc.ca<mailto:Stephane.Dumont@dfo-mpo.gc.ca>

[cid:image001.png@01D0CDFB.C2CACB60]

De : Laurent Goderre [mailto:notifications@github.com]
Envoyé : 25 novembre 2016 09:50
À : wet-boew/wet-boew
Cc : Dumont, Stéphane; Mention
Objet : Re: [wet-boew/wet-boew] Demande de dotation accélérée - aucune nouvelle (#7780)


Ce lien doit y etre par erreur, nous nous occupons seulement de la presentation des sites web.
