### ISSUE TITLE
Change URL of data-ajax-replace before it gets loaded?

### ISSUE THREAD

**Issue by rlambert27** [wet-boew/wet-boew#7782]
Hello,

Wondering if someone has an idea on how to change the URL of the "Government of Canada activities and initiatives" BEFORE the ajax call is done. We want to add cache busting to the URL so that for example:

```
data-ajax-replace="https://cdn.canada.ca/gcweb-cdn-live/features/features-en.html"
```

Would give this:

```
data-ajax-replace="https://cdn.canada.ca/gcweb-cdn-live/features/features-en.html?cacheBust=(add date.hour here so that it refreshes every hour)"
```

Unfortunatly in our case we can't change it directly in the source code because we're using compiled code that doesn't allow Javascript code to be compiled (it gets escaped) but we can add it in an external JS file.

Ideas?

**Comment by LaurentGoderre** [comment]
For such task, you only need to include a Javascript file or script tag in the footer. Anywhere should work or before wet if you want to be safe and just manipulate the dom

**Comment by duboisp** [comment]
@rlambert27 How about to configure the server to ensure the file are not cached? 

Various strategies can be set and communicated through http header, as defined in [section 5 of RFC7234](https://tools.ietf.org/html/rfc7234#section-5)

From my point of view, configuring the server to send the right http header are the most reliable solution. Using a "cache busting" strategy as you propose could be ok for the "cdn.canada.ca" server but for other server it could produce unexpected 4xx error message like "400 Bad Request" or "404 Not Found" (like a page served by a domino server [Lotus Notes])

Cheers

**Comment by LaurentGoderre** [comment]
@duboisp we don;t have control over these servers. we had set them correctly and it worked perfectly for a while but something changed.

**Comment by duboisp** [comment]
ok, I will work on that new feature. 

I will add a way to customize how to do the cache bust (to support domino server) and by default the cache bust will be deactivated, and upon activation one cache bust id will be used per session.

I may change the syntax of how to configure data-ajax like

```
data-wb-data-ajax='{
	"type": "replace",
	"url": "https://cdn.canada.ca/gcweb-cdn-live/features/features-en.html",
	"nocache": true
}'
```

I am thinking to append the following url parameter ```wb-cache-buster=[AnUniqueIdGeneratedPerSession]```

**Comment by LaurentGoderre** [comment]
uugh...I really don't like putting extra logic because of bad server configs....

**Comment by rlambert27** [comment]
@duboisp Sounds like a great idea! When you are ready to test it out let me know we can try it out!

**Comment by duboisp** [comment]
@LaurentGoderre what do you propose instead? as you said "we don't have control over these servers"

**Comment by LaurentGoderre** [comment]
I'm not opposing the change.....I just don't like it ;)

**Comment by duboisp** [comment]
Thanks @LaurentGoderre, I will add emphasis in the documentation to use proper server configuration instead of using this cache buster strategy.

**Comment by MaximMartel** [comment]
Thanks @duboisp :)

**Comment by nschonni** [comment]
I'm curious where the requirement for Domino is coming from since most of that suite of products will be phased out with ETI. 
I think the working example shows how you could do this in code already http://wet-boew.github.io/wet-boew/docs/ref/data-ajax/data-ajax-en.html, you just can't use the `data-wb-replace` attribute if you want to change the URL.

**Comment by duboisp** [comment]
@nschonni when I was referring to Domino, it was about to use it as a web server and not as an email client.

So the use case is to successfully pass a custom query parameter to a web page served by a Domino server. So to do it, depending of the server configuration, the query string needs to start with one of the following:
* ?open
* ?openDocument
* ?readForm
Then additional query parameter in the URL could be added.

So the following URL may **fail** with a domino server
http://www.example.com/domino.nsf/page1.html?cacheBust=anUniqueCacheBustSessionId

But this might work
http://www.example.com/domino.nsf/page1.html?open&cacheBust=anUniqueCacheBustSessionId

**Comment by duboisp** [comment]
_FYI Status update:_
I developed a solution, for now, in the next version of the data-json and json-fetch plugin. You can see it in action in your console with this working example: http://universallabs.org/wet/labs/urlmapping/v0.1/patches.php

Now, I just need to apply it to data-ajax, ajax-fetch then submit the PR.

**Comment by duboisp** [comment]
That feature request is now added, see [data-ajax documentation](http://wet-boew.github.io/wet-boew/docs/ref/data-ajax/data-ajax-en.html)

**Comment by rlambert27** [comment]
Awesome, thanks @duboisp ! We'll test it out and let you know if we run into any issues!
