### ISSUE TITLE
Better Docs for Installing Plugins

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew#7788]
On this page here:
https://wet-boew.github.io/wet-boew/docs/ref/plugins-en.html

There should be good docs on how to install plugins.  I'm really not certain where this is at the moment (and I'm certainly not new to WxT).

**Comment by LaurentGoderre** [comment]
Wat do you mean by "installing" plugins?

**Comment by kodecount** [comment]
@mgifford All these plugin functionalities are built into WET and each give examples on how to use them.

**Comment by mgifford** [comment]
We're trying to debug a video issue.  It worked in the old version of WET, but not the new one.  

Plugins are generally extras & not includes, but looks like we'll have to look elsewhere to understand why this isn't loading:
https://wet-boew.github.io/wet-boew/docs/ref/multimedia/multimedia-en.html

Better docs is always useful though.  Even stating, these plugins come with the default WxT.

**Comment by kodecount** [comment]
The video page is working fine: https://wet-boew.github.io/wet-boew/demos/multimedia/multimedia-en.html

If your looking for old browsers support that was pulled out some time ago. See [Issue 7765](https://github.com/wet-boew/wet-boew/issues/7765)

**Comment by LaurentGoderre** [comment]
@mgifford in WET4, all the plugins are loaded all the time so I am not sure what your are refering to. ANd when you say old version of WET, do you mean WET3?

**Comment by mgifford** [comment]
Yes..  I'm asking on behalf of one of my team who has been investigating this. It's a WET3 to WET4 upgrade.

**Comment by LaurentGoderre** [comment]
Do they have markup I can look at? It's probably a markup issue causing it.

**Comment by LaurentGoderre** [comment]
Did they follow this? https://wet-boew.github.io/wet-boew/docs/ref/multimedia/multimedia-en.html

**Comment by mgifford** [comment]
It isn't where they started. They are happy with things now, thanks!  He ended up needing to just change some HTML class names.

**Comment by duboisp** [comment]
@mgifford it is possible to create your own WET4 plugin by inserting them after the ```wet-boew.min.js``` script at the end of your html.

**Comment by mgifford** [comment]
Ok, so if we go back to https://wet-boew.github.io/wet-boew/docs/ref/plugins-en.html

Can we not extend the paragraph at the top to say:

> A WET plugin provides various types of functionality useful to a website and provided by calling the function in the class attribute of an HTML tag. All of the plugins below are included with the default package.  You can create your own WET4 plugins by inserting them after the wet-boew.min.js script.

This way it addresses what is included & also how to extend it.

**Comment by LaurentGoderre** [comment]
WET4 isn't great for extending though. It is something I hope we address in the next version though

**Comment by mgifford** [comment]
That's rather annoying..  But even stating this in that header would be useful knowledge.  Letting folks know it is possible, but it won't be easy.

**Comment by duboisp** [comment]
Thansk for the suggestion @mgifford, I will work on a text to be added in the [Getting Started / Contribution guidelines](wet-boew.github.io/wet-boew/docs/start-en.html).

**Comment by mgifford** [comment]
Excellent..  Thanks @duboisp

**Comment by duboisp** [comment]
Instruction on how to use your own plugin with WET - http://wet-boew.github.io/wet-boew/docs/ref/plugins-en.html

Quick tutorial on how to create a WET plugin - http://wet-boew.github.io/wet-boew/demos/helloworld/helloworld-en.html

**Comment by RobJohnston** [comment]
Thanks @duboisp!  I dug into plugins a couple months ago and noticed that there were at least 3 distinct styles within the existing ones.  It will be good to have a reference implementation.
