### ISSUE TITLE
Form validation: is it possible to bypass or conditionally validate 

### ISSUE THREAD

**Issue by jimBox666** [wet-boew/wet-boew#7796]

**Comment by kodecount** [comment]
Server side validation should never be your only validation anyone can bypass it.

**Comment by LaurentGoderre** [comment]
Can you please add more detail to your request?

**Comment by kodecount** [comment]
Client side validation should never be your only validation anyone can bypass it. Just use web browser developer tools too remove validation attributes from the form fields.

Also WET don't provide server side validation. This is up to the back end developers of the application and that cannot be bypassed (not legally) nor would we tell you how.

**Comment by jimBox666** [comment]
I have a page where a user can click on one of 2 buttons to either cancel their registration or change their password. If they click on the Cancel Registration button the edit check kicks in to make sure that the old a new passwords have been entered.

**Comment by kodecount** [comment]
@jimBox666 Can you provide any HTML markup? Sounds like a issue with the HTML.

**Comment by LaurentGoderre** [comment]
@jimBox666 could you use two different forms instead? That way the buttons won't interfere with the other form.

**Comment by jimBox666** [comment]
I would put it on 2 different forms but you know what clients are like. They want what they want.

**Comment by kodecount** [comment]
@jimBox666 You can make it look like one form have the fields pre-populated and hidden for the `Cancel Registration` button.

**Comment by jimBox666** [comment]
problem solved. I put each in a detail group inside an accordion.  As long as the section is closed the client side edit check is bypassed.

**Comment by kodecount** [comment]
@jimBox666 Since no HTML markup I'm guess you had two submit buttons for same form?

If so jQuery Validation has the ability for this functionally builtin. Can be seen here: https://jqueryvalidation.org/reference/#link-skipping-validation-on-submit

`<input type="submit" formnovalidate="formnovalidate" name="cancel" value="Cancel">`
