### ISSUE TITLE
Tabbed Interface: Tab Height not alwasy adjusting

### ISSUE THREAD

**Issue by RitchieD** [wet-boew/wet-boew#7797]
WET Version v4.0.23

With version 4.0.23 Tab Height remains the largest if opened on largest tab  You can see this issue with demos on Example 2.  http://wet-boew.github.io/v4.0-ci/demos/tabs/tabs-en.html

Note: The Tab heights auto adjusted in v4.0.17.

![capture](https://cloud.githubusercontent.com/assets/2989756/20898014/a89bd7d0-baf2-11e6-9781-1a85365ea4e2.JPG)

**Comment by kodecount** [comment]
Related to this issue: https://github.com/wet-boew/wet-boew/issues/7752

It has to do with the `min-height` which is added by the Equalized Plugin.

**Comment by RitchieD** [comment]
Tested with WET v.4.0.26.  Fixed!  :)
