### ISSUE TITLE
"Feeds" plugin doesn't display feeds...

### ISSUE THREAD

**Issue by stehall** [wet-boew/wet-boew#7802]
Leave a comment

**Comment by stehall** [comment]
Hi there,
Even on the demo page, the feeds aren't displaying - just the links to the XML files.
I'm having the same issue on my site (cbsa-asfc.gc.ca).

**Comment by kodecount** [comment]
This is a issue with the Yahoo plugin we use. Hopefully they get their end working soon.

**Comment by stehall** [comment]
Okay, thanks!

**Comment by kodecount** [comment]
@duboisp @LaurentGoderre @masterbee Is their any possible backup plan if Yahoo was to end support? Considering the limitablity of CORS and how some API feeds require keys would it just be deprecated if that was to happen? Just a random thought,

**Comment by kodecount** [comment]
That would suck, but that stuff happen. For now it seem Yahoo is maintaining it as it has been fix. Let just hope it stays that way.
