### ISSUE TITLE
Styling a checkbox like a button

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/wet-boew#7806]
Has anybody had to style a checkbox like a button?

Similar to https://github.com/wet-boew/wet-boew/issues/6638, I got a request for one of these "I accept" type scenarios, but what they want is to have the user click a button called "Sign" right after (this is weird) they type their name in a signature text box.  I though that the best way to do this would be to use a checkbox, but make it look like a button.

Using jquery-ui, one can style a checkbox like a button.  Found an example here:  http://jsfiddle.net/rbHXX/2/.  

Wonder if anybody has done this with WET yet?

**Comment by kodecount** [comment]
I haven't done this but their is a plugin library you can play with: http://icheck.fronteed.com/

**Comment by kodecount** [comment]
I haven't done this but their is a plugin library you can play with: http://icheck.fronteed.com/

Also you try something like this:

HTML:
```
<input type="button" value="&#x2610; I Agree" class="btn btn-md btn-primary btn-argee">
<input type="hidden" name="acceptButton" value="false" id="btn-argeed">
```
JavaScript:
```
$(".btn-argee").click(function() {
  var $agreed = $("#btn-argeed"),
    hasAgreed = ($agreed.attr("value") !== 'false') ? true : false;
  if (hasAgreed) {
    $(this).attr("value", "\u2610 I Agree");
    $agreed.attr("value", "false");
  } else {
    $(this).attr("value", "\u2611 I Agree");
    $agreed.attr("value", "ture");
  }
});
```

**Comment by RobJohnston** [comment]
The line skins in that link seem the closest to what they want.

That above example does look good, but it doesn't have a non-javascript fall-back like a checkbox would.

I'm currently looking at this as a starting point and working on writing the CSS so that everything aligns well:
```html
<div id="ck-button" class="btn btn-primary">
  <label for="accept">
    <input id="accept" type="checkbox" value="1" required="required" class="btn btn-primary" />
    <span>SIGN</span>
  </label>
</div>
```
It's not too far off... just have to set the min-height of the input and a couple more things.

**Comment by kodecount** [comment]
Yeah it something that isn't as simple as it sounds or looks. I like iCheck cause it does have the no JavaScript fall back.

**Comment by kodecount** [comment]
Expanding on your idea what about:

```
.btn-checkbox {
    min-height: 18px;
    min-width: 18px;
}
```
`btn-checkbox` be added to the checkbox input and the `<span>` add `<span style="vertical-align: text-top;">`

**Comment by RobJohnston** [comment]
Yeah, I worry about screen readers too.  They also didn't even want the check box to show, so I set `opacity:0; position:absolute; `to hide it and a bit of jQuery to have it stayed checked once clicked.  

This whole thing rubs me the wrong way a little bit, but I see this might come up again in the future when used with a signature pad (e.g., https://github.com/szimek/signature_pad). There's work for a new plug-in if anybody wants it.

BTW, @kodecount, you deleted your previous example, and now I'll never have that to refer to... it's been lost to time forever!  I thought it was a bit clever.

**Comment by kodecount** [comment]
It not lost I just thought their was no interest. Sorry. I keep backups of all my comments. You can see it here: https://jsfiddle.net/kpduncan/8vdsxeuo/

**Comment by biljanap** [comment]
@RobJohnston If you don't mind me asking why you wouldn't just use `class="wb-inv"` on checkbox element instead of `opacity:0; position:absolute;`?

Also if you must go with a checkbox that looks like a button, you might try placing `class="btn btn-primary` an a `<label>` element instead of on a wrapping `<div>`. And also  remove  `class="btn btn-primary` from `input`. You will notice that these changes make the whole button appear clickable on mouse over as opposed just the area around label/button text.

```html
<div>
  <label for="accept" id="ck-button" class="btn btn-primary">
    <input id="accept" type="checkbox" name="accept" value="1" required="required" class="wb-invisible" />
    <span>SIGN</span>
  </label>
</div>
```
Notice that I added `name` attribute to checkbox because my form would completely ignore WET form validation (wb-frmvld) on all form elements if the attribute is missing. 
With the `name` attribute added, validation is working but since the whole thing now looks like a button instead of checkbox, having error inside button looks a little strange.

![chk-as-button](https://cloud.githubusercontent.com/assets/2146304/21270119/3b193146-c383-11e6-841a-9715621e0304.jpg)

**Comment by RobJohnston** [comment]
@biljanap :  Putting the checkbox in a fieldset like the "Fovourite Pets" in the [form validation example](http://wet-boew.github.io/wet-boew/demos/formvalid/formvalid-en.html)  would solve the problem of the error inside the button.  

Thanks for the idea... I'm still investigating the best solution.

**Comment by RobJohnston** [comment]
Thanks all.  Looks like this will be the final version (requires no additional CSS):

```html
<div id="ck-button">
  <label for="accept" class="btn btn-primary">
    <input id="accept" type="checkbox" value="1" required="required" class="wb-inv" />
    <span>SIGN</span>
  </label>
</div>
```
And a little bit of jQuery to ensure that once it's clicked (signed), it cannot be unclicked:
```js
wb.doc.on("wb-ready.wb", function (event) {
    //Disable the submit button until a signature exists and the SIGN "button" has been clicked.
    $("input[type=submit]").prop("disabled", true);
    validate();
    $('#accept').change(validate);

    function validate() {
        if ($('#TextBoxSignature').length && $('#TextBoxSignature').val().length > 0) {
            $("input[type=submit]").prop("disabled", false);
            //Don't allow the SIGN "button" to be unchecked.
            $('#accept').prop("checked", true);
        }
    }
});
```
Note:  Instead of all this jQuery code, one could remove the "wb-inv" class and show a checkbox within the "button".  That would have been my preference.

**Comment by duboisp** [comment]
@RobJohnston just my 5 cents about your javascript code in regards of accessibility.

Why to block the user of unsigning? What about if I checked by mistake when I was just trying to scroll the page? What is the strategy for the error prevention? 
See to WCAG 3.3.4 and 3.3.6.

But I can see if the user get to that page after it was submitted then to have the property "disabled" and the "checked" set by the server instead of doing it on the client side.

Cheers
:-)

**Comment by RobJohnston** [comment]
@duboisp Yes, I see the point.  I said it before that this idea rubs me the wrong way.  I don't see what was wrong with the original single "I agree" checkbox.  But they want a textbox where the user types their "signature" and then clicks a SIGN button to acknowledge that they have read (and agree with) the consent text and that their declaration is true.  

It's blocked from unsigning because you cannot unclick a button.

**Comment by kodecount** [comment]
@RobJohnston See my fiddle again. I've update it with some no JavaScript backups.

**Comment by duboisp** [comment]
Is a real button (with form submission) will be better, as the checkbox is styled and acting like a button? 
Think that I can bypass your JS validation by refreshing the page or by closing the current windows.

**Comment by kodecount** [comment]
Based off my original idea:

CSS (add before the `<noscript>`):
```css
<style>
.wb-disable .btn-agreed {
	display: none;
}

.wb-disable .btn-cbox-agreed {
	visibility: visible !important;
}

.btn-cbox-agreed {
	visibility: hidden !important;
}
</style>
```

CSS (add to the `<noscript>`):
```css
<style>
.btn-agreed {
	display: none;
}

.btn-cbox-agreed {
	visibility: visible !important;
}
</style>
```

HTML:
```html
<label for="agreed"><input type="checkbox" name="agreed" value="false" id="agreed" class="required btn-cbox-agreed" required="required"> <span class="field-name btn-cbox-agreed">Signature Agreement</span></label>
<div class="form-group">
<input type="button" name="agree" value="&#x2610; I Agree" class="btn btn-md btn-primary btn-agreed">
</div>
```

JavaScript:
```javascript
<script>
$( document ).ready(function() {
	$(".btn-agreed").click(function() {
	  var $agreed = $("input[name='agreed']"),
	    hasAgreed = ($agreed.attr("value") !== 'false') ? true : false;
	  if (hasAgreed) {
	    $(this).attr("value", "\u2610 I Agree");
	    $agreed.attr("value", "false");
	    $agreed.prop('checked', false);
	  } else {
	    $(this).attr("value", "\u2611 I Agree");
	    $agreed.attr("value", "ture");
	    $agreed.prop('checked', true);
	  }
	});
});
</script>
```

**Comment by RobJohnston** [comment]
I'm still hoping that they rethink this 2-button-to-submit method in testing, but it's getting close to a workable solution with and without JavaScript and with or without an HTML5 browser.  Here's what they want, with the Submit button disabled until it has been signed:

![checkbox-button1](https://cloud.githubusercontent.com/assets/1347487/21323731/d7e891a4-c5ec-11e6-838e-337b573a09e7.png)

And with a slight modification to set the "wb-inv" class via jQuery, this is the HTML5 version with JavaScript disabled:
```js
(`$('#accept').addClass("wb-inv");
```
![checkbox-button2](https://cloud.githubusercontent.com/assets/1347487/21323885/6bea55e0-c5ed-11e6-9e1a-d7e22875b7e1.png)


And of course, server-side validation for a non-HTML5 browser with JavaScript disabled (I'm looking at you IE9!).

**Comment by biljanap** [comment]
@RobJohnston if you are still looking for options, how about this?

![signature](https://cloud.githubusercontent.com/assets/2146304/21364763/28cc2cce-c6c0-11e6-8569-b2ddf4474dcd.jpg)


You might have already discussed this as an option with your client but just in the case you didn't.

**Comment by RobJohnston** [comment]
@biljanap Yes, I agree, and that is what I originally wrote for them.  Then got this change request:

>  The client wants to take away the checkbox and add a “sign” button to the consent and disclaimer section. The user would have to fill in the signature field and then click the sign button to make the submit button clickable. I think the change is due to legal reasons.

**Comment by duboisp** [comment]
@RobJohnston can you provide more information about "due to legal reasons" like a supreme/federal court case number or a legislative reference? As you are designing the form like that for legal reason, it may impact many others organization.

**Comment by RobJohnston** [comment]
@duboisp Good question.  I'm not in direct contact with the client, but I'll see what I can get.  So far, I just have a re-iteration that it was mandatory and speculation that it is to make it very obvious that the user is signing a declaration.
