### ISSUE TITLE
Tables: Issue with Filter Option i18n Text

### ISSUE THREAD

**Issue by kodecount** [wet-boew/wet-boew#7807]
So I have a table with:

`data-wb-tables='{"bProcessing": true, "order": [[0, "asc"]], "columnDefs": [{"orderable": false, "targets": 5}], "bInfo" : false, "oLanguage": { "sEmptyTable": "No Forms Found"}}'` 

With it set to this the filter options don't show `Show All entries` or `Filter items` and I cannot get the french translation.

It has something to do with this part `"oLanguage": { "sEmptyTable": "No Forms Found"}}`

Is their another way to change the text when a table is empty? Other then changing:

`emptyTbl: "No data is available in the table"`

Since I want a more specific text. Since I want it to inform the user when they search that none were found (not using the default table search on some tables for user friendly and client reason).

**Comment by kodecount** [comment]
This might not be best solution but is what I'll use

```
wb.doc.on("wb-ready.wb-tables", function() {
	
    /**
     * Change the dataTables_empty text
     */
	if( $('.dataTables_empty').length ) {
    	var lang = document.documentElement.lang,
    		empty = (lang == 'fr') ? "Aucun r\xE9sultat n'a \xE9t\xE9 trouv\xE9" : "No Results Were Found";
    	$('.dataTables_empty').html(empty);
    }
});
```

**Comment by duboisp** [comment]
@kodecount are you looking for a long term solution or are your looking for a quick fix?

This might work as a quick fix (I didn't tested):
```html
<script>
window[ "wb-tables" ] = {
	language: {
		zeroRecords: "No Results Were Found"
	}
}
if ( document.documentElement.lang === "fr" ) {
	window[ "wb-tables" ].language.zeroRecords = "Aucun résultat n'a été trouvé"
}
</script>
```

For long term, it will be to change the value ```infoEmpty``` of the CVS at https://github.com/wet-boew/wet-boew/blob/master/src/i18n/i18n.csv#L161

**Comment by kodecount** [comment]
@duboisp That is the wrong string I want to change [Line 159: `No data is available in the table`](https://github.com/wet-boew/wet-boew/blob/master/src/i18n/i18n.csv#L159)

This could be confusing because we are not using the datatable search/filter. We have a custom search gets new data from the database if the query sent returns results having `No data is available in the table` is slightly confusing when really their was `No results` in our situation.

**Comment by kodecount** [comment]
@duboisp I ended up going with this method:

```javascript
/**
 * Change the data tables text when empty
 */
var lang = document.documentElement.lang, empty = (lang == 'fr') ? "Aucun r\xE9sultat n'a \xE9t\xE9 trouv\xE9" : "No Results Were Found";
window[ "wb-tables" ] = {
	language: {
		sEmptyTable: empty
	}
};
```
On a side note `window[ "wb-tables" ].language.sEmptyTable = "Aucun résultat n'a été trouvé";` don't work.
