### ISSUE TITLE
Form validation: Adding custom errors

### ISSUE THREAD

**Issue by joeltheukranian** [wet-boew/wet-boew#7808]
Hi,

I am using Adobe AEM 6.2. I have written a servlet which does a POST and gets JSON back. I want to add my own errors to the form validation errors already presented. Essentially two stage validation:

1. Validation at the field level provided OOTB via WET toolkit.
2. Validation on server side, with errors presented as part of WET-style errors. Just adding mine.

Any suggestions on how to do this?

Thanks
Joel

**Comment by kodecount** [comment]
You want to change the default error message? If so in the `i18n` folder add this the the `en.js` at the very bottom (use cant get the list form the `fr.js` file):

```
wb.doc.one( "formLanguages.wb", function() {
/*
 * Translated default messages for the jQuery validation plugin.
 * Locale: EN (English; english)
 */
$.extend( $.validator.messages, {
	required: "My new message..."
});
});
```

**Comment by LaurentGoderre** [comment]
Do you want to display errors fromt he server the same way client-side errors are displayed if so this can probably help you

https://github.com/wet-boew/wet-boew/issues/6281#issuecomment-69065780

**Comment by joeltheukranian** [comment]
Thanks, that worked well.
