### ISSUE TITLE
Tables: Unclear how to create control and populate

### ISSUE THREAD

**Issue by TimCadieux** [wet-boew/wet-boew#7811]
The documentation says to refer to the DataTables api for usage but when I attempt the below, it tells me  'DataTable is not a function'?

First time using WET so I'm not fully clear on the usage as the triggers on the WET Tables page differ from those on the datatables page.  I feel like i'm missing something.

    data.GetTopStoriesData(categories, p_size, dateRange,
                     function (data) {
                         $('#ExecSummTable').DataTable({
                             data: data,
                             columns: [
                                 { title: "Name" },
                                 { title: "Position" }
                             ]
                         });
    });

**Comment by kodecount** [comment]
You could use [`xhr`](https://datatables.net/reference/event/xhr):

```javascript
$( ".wb-tables" )
    .on( "xhr.dt", function ( e, settings, json, xhr ) {
        $('#status').html( json.status );
    } )
    .dataTable( {
        ajax: "data.json"
    } );
```
or you can generate the HTML table with the data. Like if using Java Web Interfaces you use an arraylist loop to generate the HTML.

**Comment by TimCadieux** [comment]
with this example it just says dataTable is not a function....do I need to include anything special other than wet-boew.min.js ?

**Comment by duboisp** [comment]
@TimCadieux may be the last [working example of tables plugin](http://wet-boew.github.io/wet-boew/demos/tables/tables-en.html) might help you. It load the table row from an JSON file.

```html
<table class="wb-tables table table-striped table-hover" id="dataset-filter" aria-live="polite" data-wb-tables='{
            "bDeferRender": true,
            "ajaxSource": "ajax/datasource.json",
            "order": [5, "desc"],
             "columns": [
                { "data": "TITLE", "className": "nws-tbl-ttl h4" },
                { "data": "PUBDATE", "className": "nws-tbl-date" },
                { "data": "DEPT", "className": "nws-tbl-dept" },
                { "data": "TYPE", "className": "nws-tbl-type" },
                { "data": "TEASER",  "className": "nws-tbl-desc" },
                { "data": "LOCATION",  "visible": false },
                { "data": "AUDIENCE",  "visible": false },
                { "data": "SUBJECT", "visible": false },
                { "data": "MINISTER", "visible": false }
              ]}'>
	<thead>
		<tr>
			<th>Title</th>
			<th>Publication date</th>
			<th>Department</th>
			<th>News Type</th>
			<th>Summary</th>
			<th>Location</th>
			<th>For</th>
			<th>Subject</th>
			<th>Minister</th>
		</tr>
	</thead>
</table>
```

**Comment by kodecount** [comment]
Might need to use `.DataTable({});` sorry. Also make sure any script runs after the `wet-boew.min.js`.

**Comment by TimCadieux** [comment]
Argh, so I did some additional research and it turns out my datatable has been working all along..i thought it wasn't properly initialized because I couldn't filter but then I found this [bug](https://github.com/wet-boew/wet-boew/issues/7385)
