### ISSUE TITLE
Datatable - Upgrade to v1.10.13

### ISSUE THREAD

**Issue by duboisp** [wet-boew/wet-boew#7812]
In my [current work to implement the HTML5 ```<template>``` element](http://universallabs.org/wet/labs/data-json/v1.1/templating.php) I am currently facing an random issue when my plugin need to interact with datatable plugin.

I may need to leverage the [```preInit``` event](https://datatables.net/reference/event/preInit) to solve my random issue. In order to use that event I need to upgrade datatable to at least the version 1.10.8.

**Comment by kodecount** [comment]
Is this really need for DataTables? Their already two method for adding JSON data.
