### ISSUE TITLE
Determine Tab ID on click

### ISSUE THREAD

**Issue by TimCadieux** [wet-boew/wet-boew#7813]
Using the below code to catch click but DoSomething only returns [Object]..I'm uncertain how to proceed to find which Tab was actually clicked.

>  $(document).on("wb-updated.wb-tabs", ".wb-tabs", function (event, $newPanel) {
             DoSomething($newPanel);
         });

**Comment by kodecount** [comment]
To get the object that was click use `$newPanel[0]`

**Comment by TimCadieux** [comment]
OMG, I can't believe, of all the things I tried, that wasn't one..<sigh>

For anyone else, this works

> alert(Panel[0].id);
