### ISSUE TITLE
Tables: Empty Table appended on request, data appears but Filter always says 0 

### ISSUE THREAD

**Issue by TimCadieux** [wet-boew/wet-boew#7818]
I use a Tabbed interface and when the User clicks on the tab, I append the below table (same with any calls from dd_Transcripts).  The data appears but the filtering does not work and always says 0 of 0.

    `<details id="details-panel-transcripts">
    <summary>Transcripts</summary>

    <section>
        <form class="wb-tables-filter" data-bind-to="TranscriptsTable">
            <div class="form-group pull-right">
                <select class="form-control" id="dd_Transcripts" name="dd_Transcripts" data-column="3" onchange="GetTranscripts(this)">
                    <option value="T">Today</option>
                    <option value="P24H">Past 24 Hours</option>
                    <option value="PW">Past Week</option>
                    <option value="PM">Past Month</option>
                </select>
            </div>
        </form>
    </section>

    <section>
        <table id="TranscriptsTable" aria-live="polite" data-wb-tables='{ "ordering" : false }'
            class="wb-tables table table-striped table-hover">
            <thead>
                <tr>
                    <th>Headline</th>
                    <th>Rating</th>
                    <th>Source</th>
                </tr>
            </thead>
            <tbody id="Transcripts">
            </tbody>
        </table>

    </section>
`

The .**js**

    `function GetTranscripts(dd_Transcripts){
    Transcripts(dd_Transcripts.value);
    }
    ...foo
     $.ajax({
                url: data.TranscriptsQuery(categories, p_size, dateRange),
                crossDomain: true,
                cache: true,
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data) {
                    if (callbackFunction !== undefined) {
                        return callbackFunction(data);
                    }
                }
            });
    js.utils.AppendTranscripts = function AppendTR(tag, data) {

    var items = [];

    $.each(data.articles, function (i, item) {

        items.push(
        '<tr><td>' +
        '<a href=' +
        item.articleUrl + ' target=_blank>' +
        js.utils.Truncate(item.title, 150) + '</a>' +
        '<td>' + item.rating + '</td>' +
        '</td><td><p style=\"font-size: smaller;\"> <em>' +
        item.publication.name + ' ' +
        item.publicationDateInUsersTimeZone +
        '</em></p></td></tr>');

    });

    $("#" + tag).html(items.join(''));
    }
    `

**Comment by duboisp** [comment]
@TimCadieux Once the wb-tables is initialised you may need to go through the data table plugin to add your row. Issue #7809 might help you.

FYI - It could be interesting to know that I am aiming to release in WET 4.0.24 an updated version of data-json that support HTML5 template element. [See the early demo](http://universallabs.org/wet/labs/data-json/v1.1/templating.php)

**Comment by TimCadieux** [comment]
How close to Release is that?  All my data comes from external sources so I have to populate my tables on the fly in most instances.  In the meantime I'll look at the Issue $ you tagged.  Thx

**Comment by duboisp** [comment]
@TimCadieux it's [planned for 14 Februrary 2017](https://github.com/wet-boew/wet-boew/milestone/60). And there is always a risk it get delayed of 2-4 weeks after.

If my solution fit your needs it is possible to add that plugin in your version of WET until it get officially released. And when you will be ready to upgrade your local WET version to the latest, you would only need to remove the plugin and review/re-test your pages that used that early plugin.

**Comment by TimCadieux** [comment]
I see...how would I go about testing the plugin?

**Comment by TimCadieux** [comment]
In the meantime, I just wanted to share the solution I came up with..
     ` //foo

       var table = $('#' + tag).dataTable({ "retrieve": true }).api();

       $.each(data.articles, function (i, item) {

          var jRow = $("<tr>").append("<td>" +item.title + "</td>", "<td>" + item.rating + "</td>", "<td>" + item.publication.name + "</td>");
          table.row.add(jRow).draw();

        });

    table.draw();
`

**Comment by duboisp** [comment]
Which version of WET are you running? I just remember now that it might conflict with data-json and json-fetch released in WET 4.0.23 because I am updating them with more feature.

**Comment by TimCadieux** [comment]
v4.0.23

**Comment by duboisp** [comment]
Disclaimer: The following are for testing and it might not exactly represent what the plugin will be once officially merged in WET.

You can test the plugin by setting up an WET 4.0.22 env and to include your local copy of those js file:
http://universallabs.org/wet/labs/data-json/v1.1/json-fetch.js
http://universallabs.org/wet/labs/data-json/v1.1/data-json.js
http://universallabs.org/wet/labs/data-json/v1.1/wb-jsonmanager.js
http://universallabs.org/wet/labs/data-json/v1.1/template-polyfill.js
and add in your "wet-boew\js\deps" the following js
http://universallabs.org/wet-boew/js/deps/jsonpointer.js
http://universallabs.org/wet-boew/js/deps/jsonpointer.min.js

then your html code will look like:
```html
<table class="table">
  <thead>
  <tr>
    <th>Name <th>Color <th>Sex <th>Legs
  <tbody data-wb-json='{
		"url": "table-en.json",
		"source": "#tbl2",
		"tplSelector": "tr",
		"queryall": "td",
		"mapping": [
			{ "value": "/name", "placeholder": "{{name}}" },
			{ "value": "/css", "attr": "class" },
			{ "value": "/sex" },
			{ "value": "/legs" }
		]
	}'>


	</tbody>
</table>

<template id="tbl2">
	<table>
		<tr><td>Name is: {{name}}<td class><td><td>
	</table>
</template>
```

where the configuration: 
* url: URL followed by a JSON point that will refer to an array in your JSON file
* source: JQuery selector used to retreive the template
* tplSelector: CSS selector of the inner template element you want to use to run the template (note, this is a work-around to make it work with IE11)
* queryall: CSS selector that return multiple items, it should be the same number of the mapped item..
* mappring: Array of the same lenght of what the queryall will return.
  * value: the textContent value to set
  * placeholder: Do a find and replace in the selected element and replace the place holder by the value

**Comment by duboisp** [comment]
@TimCadieux if you already know what data will be in your table and your JSON is already an array, so you  following already work in WET

```html
<table class="wb-tables table table-striped table-hover" id="dataset-filter" aria-live="polite" data-wb-tables='{
            "bDeferRender": true,
            "ajaxSource": "ajax/datasource.json",
            "order": [5, "desc"],
             "columns": [
                { "data": "TITLE", "className": "nws-tbl-ttl h4" },
                { "data": "PUBDATE", "className": "nws-tbl-date" },
                { "data": "DEPT", "className": "nws-tbl-dept" },
                { "data": "TYPE", "className": "nws-tbl-type" },
                { "data": "TEASER",  "className": "nws-tbl-desc" },
                { "data": "LOCATION",  "visible": false },
                { "data": "AUDIENCE",  "visible": false },
                { "data": "SUBJECT", "visible": false },
                { "data": "MINISTER", "visible": false }
              ]}'>
<thead>
<tr>
<th>Title</th>
<th>Publication date</th>
<th>Department</th>
<th>News Type</th>
<th>Summary</th>
<th>Location</th>
<th>For</th>
<th>Subject</th>
<th>Minister</th>
</tr>
</thead>
<tfoot>
<tr>
<th>Title</th>
<th>Publication date</th>
<th>Department</th>
<th>News Type</th>
<th>Summary</th>
<th>Location</th>
<th>For</th>
<th>Subject</th>
<th>Minister</th>
</tr>
</tfoot>
</table>
```
Where:
* ajaxSource: URL to your JSON file.

**Comment by TimCadieux** [comment]
I have to do a lot of work to the data in the json file before sending it to the table, hence the path I took.

**Comment by duboisp** [comment]
What kind of manipulation you need to do with your JSON? 

FYI - I am working also on a [JSON-manager](http://universallabs.org/wet/labs/json-manager/v0.1.0/jsonmanager.php) where it will be possible to apply pre-defined set of patches to a JSON object. And it will be also possible to [modify the JSON base on user interaction with my new plugin Field flow](http://universallabs.org/wet/labs/json-manager/v0.1.0/fieldflow-and-scripting.php)

**Comment by TimCadieux** [comment]
its data related...i am removing duplicates, adding a href, grouping and sorting based on keywords..

**Comment by duboisp** [comment]
ok, that may are out of scope of the JSON-manager plugin that I plan to release. For heavier JSON operation sometime it could be advantageous to develop/use it's own RESTful JSON API and doign those task on the server rather on the client side.

**Comment by TimCadieux** [comment]
I agree but the data comes from another dept and is provided 'as is'

**Comment by kodecount** [comment]
You could still change the data on your server side and update it accordingly then send your client side the updated date.

**Comment by TimCadieux** [comment]
Well, i am using the solution i posted above and it is working now..

**Comment by kodecount** [comment]
If it is working don't forget to close issue.

**Comment by TimCadieux** [comment]
Sure, i didn't close it because @PDubois was going to respond re: his new
plugins..

**Comment by kodecount** [comment]
When issues are closed they can still be referenced, but the original issue was specif to your case.

**Comment by TimCadieux** [comment]
ok

**Comment by duboisp** [comment]
@TimCadieux I am planning to submit a PR within 5 to 6 weeks with all the new plugin that was referring. But before I need to finalize the working example, write the doc, do the French translation, do more testing and implement a cache buster mechanism.
