### ISSUE TITLE
Ajaxing in content AFTER Overlay appears

### ISSUE THREAD

**Issue by rmwbweb** [wet-boew/wet-boew#7819]
As the subject above suggests, I would like to fetch content for an Overlay via Ajax, but only if the Overlay is actually triggered.

Is this already a capability using the exiting JS and markup, or will I need to write my own jQuery to detect the status of the Overlay and then manually fire the Ajax request?

**Comment by LaurentGoderre** [comment]
You can listen to the `open.wb-overlaylbx` event and AJAX the content after that.

**Comment by duboisp** [comment]
I think that is already possible with lightbox

http://wet-boew.github.io/wet-boew/demos/lightbox/lightbox-en.html

```html
<a class="wb-lbx" title="AJAX - Example 1 of AJAX content" href="ajax/ajax-en.html">AJAX - Example 1</a>
```

**Comment by LaurentGoderre** [comment]
Aren't overlay and lightbox different though, I can't remember? Our two answer cover the two use cases.

**Comment by kodecount** [comment]
The weird thing is the example provided above opens a overlay using the light box script.

**Comment by LaurentGoderre** [comment]
They use similar markup and styles but they are not the same.

**Comment by rmwbweb** [comment]
Thanks. Looks like I have two options. (Have to weigh the custom JS vs Ajaxing in extra markup, I guess.)
