### ISSUE TITLE
Tables: Table Filter loses focus after each letter

### ISSUE THREAD

**Issue by TimCadieux** [wet-boew/wet-boew#7820]
Filtering on the table, the textbox loses focus after each key-up, this is only happening in IE 11 and Edge, but not Chrome or FF.

Inside a tabbed view. I am not using the Equal Height plugins which is known to cause an issue.

`    

    <form class="wb-tables-filter" data-bind-to="TranscriptsTable">
        <div class="form-group pull-right">
            <select class="form-control" id="dd_Transcripts" 
              name="dd_Transcripts" data-column="3" onchange="GetTranscripts(this)">
                <option value="T">Today</option>
                <option value="P24H">Past 24 Hours</option>
                <option value="PW">Past Week</option>
                <option value="PM">Past Month</option>
            </select>
        </div>
    </form>

    <table id="TranscriptsTable"  data-wb-tables='{ "ordering" : false }' 
        class="wb-tables table table-striped table-hover">
        <thead>
            <tr>
                <th class="col-sm-9">Headline</th>
                <th class="col-sm-3">Source</th>
            </tr>
        </thead>
        <tbody id="Transcripts">
        </tbody>
    </table>

`

**Comment by duboisp** [comment]
@TimCadieux is your issue fixed or we still need to look at it? If it not fixed please re-open otherwise it would appreciated if you can quickly describe how your resolved.

Thanks 😃
