### ISSUE TITLE
Tables: WET tables script uses string method on integers (causes table population too fail)

### ISSUE THREAD

**Issue by thekodester** [wet-boew/wet-boew#7825]
So if you have JSON data like:
```
"data": [
{
"id": 12,
...
"publication": {
  "id": 1234,
  "name": "Publication 1234"
},
...
}
]
```
This well break it due to `"id": 12,` and `"id": 1234,` being integers. These are the areas in the `table.js` that break it:

- [Line 121 in table.js](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/tables/tables.js#L121) need to `sData = sData.toString();` before doing `sData.replace(...)`.

- [Line 133 in table.js](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/tables/tables.js#L133)  need to `data = data.toString();` before doing `data.replace(...)`.

Also maybe should add checks to make sure data is not empty or null? This is also discussed on [Issue 7824](https://github.com/wet-boew/wet-boew/issues/7824#issuecomment-268828051).

**Comment by nschonni** [comment]
Looks like the code in 121 should be stripped out since it looks like 1.10 included this functionality https://datatables.net/plug-ins/type-detection/formatted-num

**Comment by LaurentGoderre** [comment]
@nschonni could you PR it?

**Comment by kodecount** [comment]
@nschonni Are you gonna PR this? Its a kinda a pain testing data-tables using JSON at the moment?

**Comment by kodecount** [comment]
https://github.com/wet-boew/wet-boew/pull/7924
