### ISSUE TITLE
Nested Tabbed Carousel inside Tabbed Interface

### ISSUE THREAD

**Issue by TimCadieux** [wet-boew/wet-boew#7826]
Try to use a Tabbed Carousel inside a Tabbed Interface...when using the show-thumbs class the text from figcaption is squished over the thumbnail.  I also dont seem to be able to make the original images any small.  Ideally I'd rather have the text from the figcaption actually display in a seperate div or at least be able to better control the carousel size.

PS: how to i add a proper Label to my questions?

`
    
     <section>
        <div class="wb-tabs ignore-session">
            <div class="tabpanels">
                <details id="details-panel-news">
                    <summary>In the News</summary>

                </details>

                <details id="details-panel-cc">
                    <summary>Combat Camera</summary>
                    <div class="col-sm-8">
                        <div class="panel panel-default">
                            <header class="panel-heading">
                                <h5 class="panel-title">Recent Images</h5>
                            </header>
                            <div class="panel-body">
                                <section>

                                    <div class="wb-tabs carousel-s2 show-thumbs exclude-play">
                                        <ul role="tablist">
                                            <li class="active"><a href="#panel30">
                                                <img src="http://www.forcesimages.ca/gs/handler/getmediaobject.ashx?moid=81462&dt=2&g=2" alt=""></a></li>
                                            <li><a href="#panel31">
                                                <img src="http://www.forcesimages.ca/gs/handler/getmediaobject.ashx?moid=62981&dt=2&g=2" alt=""></a></li>
                                            <li><a href="#panel32">
                                                <img src="http://www.forcesimages.ca/gs/handler/getmediaobject.ashx?moid=60271&dt=2&g=2" alt=""></a></li>
                                        </ul>
                                        <div class="tabpanels">
                                            <div role="tabpanel" id="panel30" class="in fade">

                                                <figure>
                                                    <img src="http://www.forcesimages.ca/gs/handler/getmediaobject.ashx?moid=81462&dt=2&g=2" alt="">
                                                    <figcaption>
                                                        <p>Chief of the Defence Staff, General Jonathan Vance shakes hands with Commander Andrew Hingston, Commanding Officer of Her Majesty’s Canadian Ship (HMCS) CHARLOTTETOWN while alongside in Souda Bay Crete, Greece during Operation REASSURANCE, December 19, 2016.</p>
                                                    </figcaption>
                                                </figure>

                                            </div>
                                            <div role="tabpanel" id="panel31" class="out fade">

                                                <figure>
                                                    <img src="http://www.forcesimages.ca/gs/handler/getmediaobject.ashx?moid=62981&dt=2&g=2" alt="">
                                                    <figcaption>
                                                        <p>General Jonathan Vance, Chief of the Defence Staff, escorted by Officer Cadet Makyla St. Onge and accompanied by Chief Warrant Officer Kevin West, Canadian Forces Chief Warrant Officer inspect the cadet wing during the Royal Military College Commissioning Parade. May 20 2016, RMCC, Kingston, On.</p>
                                                    </figcaption>
                                                </figure>

                                            </div>
                                            <div role="tabpanel" id="panel32" class="out fade">

                                                <figure>
                                                    <img src="http://www.forcesimages.ca/gs/handler/getmediaobject.ashx?moid=60271&dt=2&g=2" alt="">
                                                    <figcaption>
                                                        <p>Mr. Jaime Pitfield, Assistant Deputy Minister; General Jonathan Vance, Chief of the Defence Staff; Major-General Karl McQuillian; Mr. John Forster, Deputy Minister of National Defence and Colonel Kevin Horgan pose for a cake cutting photograph during the Assistant Deputy Minister (Infrastructure and Environment) Full Operational Capability (FOC) Event held at National Defence Headquarters in Ottawa, Ontario on April 1, 2016.</p>
                                                    </figcaption>
                                                </figure>

                                            </div>
                                        </div>
                                    </div>

                                </section>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        For more photos, please visit the Minister of National Defence Gallery at <a href="http://www.forcesimages.ca/default.aspx?aid=5088">Combat Camera.</a>
                    </div>
                </details>

            </div>
        </div>
    </section>`

**Comment by duboisp** [comment]
@TimCadieux you can't add labels to your issue, only admin can do. But you can ease the labeling by starting your issue name with the related plugin or/and to include a list of related plugin in your issue description.

Cheers

**Comment by TimCadieux** [comment]
Ok, thx

**Comment by TimCadieux** [comment]
Anyone have a fix for this?

**Comment by kodecount** [comment]
Just need to change this CSS:

```css
.wb-tabs.carousel-s2.wb-init {
    padding-bottom: 7.2em !important;
}
```

**Comment by kodecount** [comment]
Just need add this CSS to the top of page or custom script file:

```css
.wb-tabs.carousel-s2.wb-init {
    padding-bottom: 7.2em !important;
}
```
Best option would be to add it inline here `<div class="wb-tabs carousel-s2 show-thumbs exclude-play" style="padding-bottom: 7.2em !important;">`, so it only effects that one carousel.

**Comment by TimCadieux** [comment]
OMG I'm stupid, I assumed all along this was a bug, never occurred to me to look at the css.

Thx

**Comment by kodecount** [comment]
We all forget to look at the little thing. Tip next time to see if it broken is to remove `exclude-play` and if the play button still working then just a CSS issue.

**Comment by TimCadieux** [comment]
Thx
