### ISSUE TITLE
Collapsible alerts: icon supposed to disappear when closed?

### ISSUE THREAD

**Issue by naptash** [wet-boew/wet-boew#7827]
http://wet-boew.github.io/v4.0-ci/demos/collapsible-alerts/collapsible-alerts-en.html

I seem to remember that the icons used to stay visible when the details element was closed but now it disappears. Mistake or correct behaviour?

**Comment by kodecount** [comment]
What operating system and browsers? I appear to be able to reproduce on Firefox 50 on Windows 7.

@EricDunsworth Do you think this is related to the detail/summary issues?

**Comment by duboisp** [comment]
duplicate #7778
