### ISSUE TITLE
Multimedia Player: youtube video in a modal issue

### ISSUE THREAD

**Issue by acrazyanimal** [wet-boew/wet-boew#7828]
## Issue description
Displaying a youtube video using the WET multimedia player in a lightbox (uses Magnific Popup plugin) causes an issue with the functionality of the player controls.

- The play image overlay does not fade away and remains over the video when the video starts to play.
- The play button does not switch to a pause image once the video starts to play.
- The timeline counter does not increase as the video plays. It stays at 00:00:00

See http://wb-example.ox.ca as a working example of this issue.

```
<a class="wb-lbx" title="Example of WET player with youtube in a modal" href="#popup1">WET Youtube video in modal</a>
<section class="mfp-hide modal-dialog modal-content overlay-def" id="popup1">
  <header class="modal-header"><h2 class="modal-title">Its broke!</h2></header>
  <div class="modal-body">
    <figure class="wb-mltmd">
      <video title="test youtube vid">
        <source type="video/youtube" src="https://www.youtube.com/watch?v=iT7vWd-nEoU">
      </video>
      <figcaption><p>Notice the controls don't function quite as they should and the play icon doesn't fade out from overtop the video. Counter doesn't count.</p>
      </figcaption>
    </figure>
  </div>
</section>
```

**Comment by kodecount** [comment]
It seems that YouTube has changed their API which is why you can see the YouTube's controls. As for the play button not disappearing that is another issue as well.

**Comment by kodecount** [comment]
It seems that YouTube has changed their API which is why you can see the YouTube's controls. This is a issue on WET site now. This can also bring up issue with accessibility. @masterbee @nschonni @duboisp @EricDunsworth 

As for the play button not disappearing that is another issue as well.

**Comment by kodecount** [comment]
@masterbee @nschonni @duboisp @EricDunsworth It seems that YouTube has changed their API which is why you can see the YouTube's controls. This is a issue on WET site now. This can also bring up issue with accessibility. Also the [YouTube Documentation](https://developers.google.com/youtube/player_parameters) hasn't been updated since October of last year. It seems that the play button animation is still visible even when the controls are disabled on YouTube videos now. I'm not sure if their is a work around for that. Also YouTube added a preview mode which plays the video like a short GIF when hovering over it.

As for the play button not disappearing that is another issue as well.

**Comment by kodecount** [comment]
Here is a workaround until someone creates an actual fix:

```javascript
<script>
$( document ).ready( function() {
	var $modal = $( "#popup1" ).find(".modal-body"),
	figure = "<figure id='youtube'><video title='Youtube Video'><source type='video/youtube' src='https://www.youtube.com/watch?v=iT7vWd-nEoU'></video><figcaption><p>Notice the controls don't function quite as they should and the play icon doesn't fade out from overtop the video. Counter doesn't count.</p></figcaption></figure>";

	setTimeout(function() {
		$modal.append(figure);
		$("#youtube").addClass("wb-mltmd");
		$("#youtube").trigger( "wb-init.wb-mltmd" );
	}, 1000);
});
</script>
```

**Comment by kodecount** [comment]
Workaround till this is fixed:

HTML:
```html
<a class="wb-lbx" title="Example of WET Player with YouTube in a Modal" href="#youtube-modal">WET YouTube Modal</a>
<section class="mfp-hide modal-dialog modal-content overlay-def" id="youtube-modal">
  <header class="modal-header"><h2 class="modal-title">YouTube Modal</h2></header>
  <div class="modal-body"></div>
</section>
```

JavaScript:
```javascript
$( document ).ready( function() {
	var $modal = $( "#youtube-modal" ).find(".modal-body"),
	figure = "<figure id='youtube-video'><video title='Youtube Video'><source type='video/youtube' src='https://www.youtube.com/watch?v=iT7vWd-nEoU'></video><figcaption><p>Example</p></figcaption></figure>";

	setTimeout(function() {
		$modal.append( figure );
		$( "#youtube-video" ).addClass( "wb-mltmd" );
		$( "#youtube-video" ).trigger( "wb-init.wb-mltmd" );
	}, 1500);
});
```

**Comment by kodecount** [comment]
@acrazyanimal I think the issue also has something to do with the initialization time of both plugins. It seems the video players are very slow initialing. Almost 2 seconds after the page has loaded. Why the workaround needs 1.5 seconds before it can even trigger the video element.

Where as the overlays finish complying as soon as the page is finished loading. It almost as if once the overlay is code has ran any coded within stops complying.

**Comment by acrazyanimal** [comment]
@kodecount Thanks for the replies. I had implemented a workaround for the time being that is similar to your own except I didn't use the timeout, I instead copy the outer html of the figure on mfpOpen, add the wb-mltmd class and initialize the player. Then on mfpClose I replace the figure with its original content.

The code below happens to be from Drupal so its wrapped in a drupal behavior, but other then that the code would be similar for non-Drupal.

JavaScript:

```javascript
/**
  * Initialize WET multimedia player in a lightbox.
  */
(function($) {

// Attach a function to initialize WET-BOEW youtube player in lightbox.
Drupal.behaviors.ggInitYoutubeLightbox = {
  attach: function (context, settings) {
    $( ".wb-lbx" ).once('gg-yt-init').on( "mfpOpen", function( event ) {
      if ($.magnificPopup.instance.items[0].src && $.magnificPopup.instance.items[0].type == 'inline') {
        var modal = $($.magnificPopup.instance.items[0].src);
        modal.find(".gg-mltmd").each(function( index ) {
          var video = $(this);
          video.data('ggMltmd', this.outerHTML);
          video.addClass('wb-mltmd');
          video.trigger( "wb-init.wb-mltmd" );
        });

      }
    });

    $( ".wb-lbx" ).once('gg-yt-close').on( "mfpClose", function( event ) {
      if ($.magnificPopup.instance.items[0].src && $.magnificPopup.instance.items[0].type == 'inline') {
        var modal = $($.magnificPopup.instance.items[0].src);
        modal.find(".gg-mltmd").each(function() {$(this).replaceWith($(this).data('ggMltmd'));});
      }
    });
  }
};

})(jQuery);
```
