### ISSUE TITLE
Calender of events fix #7624 for issue #7609 possibly removed the ability for multi day events

### ISSUE THREAD

**Issue by cwhyman** [wet-boew/wet-boew#7833]
Hello, 
I am having the same issue as #7609 i've seen on the original thread that the issue was closed and a push was done for a fix #7624  , I have tested out the code and it seems as though this commit has removed the functionality of multi day events, if this is not the case is there a different way to define a multi day event that I am unaware of.

Thanks.

**Comment by cwhyman** [comment]
This issue can be closed, I just noticed that my version of wet-boew must have been older than the version that was causing the issue, although I had the same issue there was one line of code that must have been removed in later versions that was breaking the code that was done in this fix, the firstDay = false; was breaking the code and I had just noticed this extra line in my version.
`//Add the event to the list
$dayEvents.append( "<li><a tabindex='-1' class='cal-evt-lnk' href='" + event.href + "'>" + event.title + "</a></li>" );

firstDay = false;` 

after the deletion of the firstDay = false; line the code worked.

**Comment by duboisp** [comment]
@cwhyman I am happy that you find out how to resolve your issue.

In the current working example, the multi day event seems working as expected: http://wet-boew.github.io/wet-boew/demos/cal-events/cal-events-en.html

>  is there a different way to define a multi day event 
The plugin will assume that for each individual event (```<li>```) the first ```<time>``` child element represent the start date then the second ```<time>``` child element is the end date.
