### ISSUE TITLE
Input type="date" polyfill (date picker): 

### ISSUE THREAD

**Issue by TimCadieux** [wet-boew/wet-boew#7841]
Is it possible to use this DatePicker as a Date-Time picker?

 ie from 2017-01-10 06:00 to 2017-01-11 11:00?

**Comment by nschonni** [comment]
Nope, only handles `input=date` https://github.com/wet-boew/wet-boew/blob/7e13116b9952a8aedb0894b0ae4996b2123843ae/src/polyfills/datepicker/datepicker.js#L3
Doesn't cover input types:
- datetime
- datetime-local
- month
- time
- week

`datetime` looks like it was dropped from the spec https://github.com/whatwg/html/issues/336

**Comment by TimCadieux** [comment]
Ok, thank you.
