### ISSUE TITLE
Création d'un sous répertoire wet-boew-apex

### ISSUE THREAD

**Issue by SebastienMetivier** [wet-boew/wet-boew#7853]
Bonjour,

Nous avons travaillé à intégrer le thème de la BOEW pour Apex de Oracle et aimerions le partager avec ASC et DND (et toute autre personne qui voudrais l'utiliser).

Serais-ce possible de nous créer un sous-répertoire wet-boew-apex.

Merci

Sébastien Métivier

**Comment by LaurentGoderre** [comment]
@MaximMartel

**Comment by SebastienMetivier** [comment]
Any update on this ?

@LaurentGoderre ? @MaximMartel ?

Thanks

**Comment by LaurentGoderre** [comment]
@lucas-hay

**Comment by MaximMartel** [comment]
im on it

**Comment by MaximMartel** [comment]
https://github.com/wet-boew/wet-boew-apex

**Comment by MaximMartel** [comment]
Can we close this issue ? Repo has been created.

**Comment by SebastienMetivier** [comment]
Yes, thanks.

Just a quick question on who will manage the master branch ? Do I need to fork and request a pull request to manage the content ?

**Comment by lucas-hay** [comment]
Hi, We have renamed the variant to match our naming schemes. (oracle-variant)
We will create a new team for you to manage. And we will also add the release management team.
You must keep in mind and follow the contributions guidelines [](https://wet-boew.github.io/v4.0-ci/docs/start-en.html#develop)
Yes you will need to fork and pull request.
