### ISSUE TITLE
Toggle: Accordion - Determine which is Expanded.

### ISSUE THREAD

**Issue by TimCadieux** [wet-boew/wet-boew#7856]
I have a Search form that allows a Single Date search or a range, using the accordion to differentiate.

Using the below code I merely want to establish which accordion is Open so I know which input to field to query for a date.

Problem is if ($("singledate").attr("aria-expanded", "true")) { ALWAYS is True

`
    <div class="accordion">

        
        <details class="acc-group" open="open">
            <summary id="singledate" class="wb-toggle tgl-tab" data-toggle='{"parent": ".accordion", "group": ".acc-group", "type": "on"}'>Date</summary>
            <div class="tgl-panel">
                <div class="form-group">
                    <input class="form-control" type="date" id="searchdate" name="searchdate" min="2013-03-27" />
                </div>
            </div>
        </details>

        
        <details class="acc-group">
            <summary id="daterange" class="wb-toggle tgl-tab" data-toggle='{"parent": ".accordion", "group": ".acc-group",  "type": "on"}'>Date Range</summary>
            <div class="tgl-panel">
                <div class="form-group">
                    <label for="searchdatefrom">From Date</label>
                    <input class="form-control" type="date" id="searchdatefrom" name="searchdatefrom" min="2013-03-27" />
                </div>
                <div class="form-group">
                    <label for="searchdateto">To Date</label>
                    <input class="form-control" type="date" id="searchdateto" name="searchdateto" min="2013-03-27" />
                </div>
            </div>
        </details>

    </div>

    //Date to search on
    var dateRange = "";
    if ($("singledate").attr("aria-expanded", "true")) {
	    var value = document.getElementById('searchdate').value;
	    dateRange = js.utils.SingleCustomDateRange(dateRange);
    } else
    {
	    var t = js.utils.CustomDateRange(document.getElementById("searchdateto").value);
	    var f = js.utils.CustomDateRange(document.getElementById("searchdatefrom").value);
    }

`

**Comment by kodecount** [comment]
Should be `$("singledate").attr("aria-expanded")` when you use `$("singledate").attr("aria-expanded", "true")` you are setting the attribute.

**Comment by kodecount** [comment]
Please see my updated comment above.

**Comment by TimCadieux** [comment]
Argh....hopefully that will be my only 'duh' moment of the day today..

thank you, that worked.

**Comment by kodecount** [comment]
Mondays we all get them.

**Comment by LaurentGoderre** [comment]
You should test this because I"m not sure it would work in Chrome since Chrome doesn't use the polyfill and only the polyfill uses `aria-hidden`. You should check for the `open` property instead which should work for polyfill and non polyfill. (note that the ID should be on the `details` element, not the summary.

```html
<!-- Accordion section 1 -->
    <details id="singledate" class="acc-group" open="open">
        <summary class="wb-toggle tgl-tab" data-toggle='{"parent": ".accordion", "group": ".acc-group", "type": "on"}'>Date</summary>
        <div class="tgl-panel">
            <div class="form-group">
                <input class="form-control" type="date" id="searchdate" name="searchdate" min="2013-03-27" />
            </div>
        </div>
    </details>

    <!-- Accordion section 2 -->
    <details id="daterange" class="acc-group">
        <summary class="wb-toggle tgl-tab" data-toggle='{"parent": ".accordion", "group": ".acc-group",  "type": "on"}'>Date Range</summary>
        <div class="tgl-panel">
            <div class="form-group">
                <label for="searchdatefrom">From Date</label>
                <input class="form-control" type="date" id="searchdatefrom" name="searchdatefrom" min="2013-03-27" />
            </div>
            <div class="form-group">
                <label for="searchdateto">To Date</label>
                <input class="form-control" type="date" id="searchdateto" name="searchdateto" min="2013-03-27" />
            </div>
        </div>
    </details>
```

```js
var dateRange = "";
if (document.getElementById("singledate").open === true) {
    var value = document.getElementById('searchdate').value;
    dateRange = js.utils.SingleCustomDateRange(dateRange);
} else
{
    var t = js.utils.CustomDateRange(document.getElementById("searchdateto").value);
    var f = js.utils.CustomDateRange(document.getElementById("searchdatefrom").value);
}
```

**Comment by TimCadieux** [comment]
Using IE but will update for future proofing.

**Comment by TimCadieux** [comment]
Just to confirm, var expanded = ( $("#singledate").attr("aria-expanded") == "true" ) ? true : false; DOES fail in chrome but so does document.getElementById("singledate").open === true)

**Comment by kodecount** [comment]
Try:
```javascript
var isOpen = (  document.getElementById("singledate").getAttribute("open") ) ? true : false;
if ( isOpen ) {...}
```

**Comment by LaurentGoderre** [comment]
I didn't think you needed to use the getAttribute so maybe something is up. I need to test.
