### ISSUE TITLE
multimedia player: broken link for placeholder and transcript

### ISSUE THREAD

**Issue by duboisp** [wet-boew/wet-boew#7861]
The placeholder image and the transcript are currently broken.

* English:
  * http://www.servicecanada.gc.ca/eng/video/images/te-lj-eng.jpg
  * http://www.servicecanada.gc.ca/eng/video/images/dc-td-eng.jpg
  * http://www.servicecanada.gc.ca/eng/video/lj.shtml
  * http://www.servicecanada.gc.ca/eng/video/td.shtml
* French
  * http://www.servicecanada.gc.ca/fra/video/images/te-lj-fra.jpg
  * http://www.servicecanada.gc.ca/fra/video/images/dc-td-fra.jpg
  * http://www.servicecanada.gc.ca/fra/video/te.shtml
  * http://www.servicecanada.gc.ca/fra/video/dc.shtml

All video still work, but we are unsure for how long it will work.

According to https://github.com/wet-boew/wet-boew/pull/7817#issuecomment-275124109 that is because servicecanada has migrated their content to canada.ca.

As a temporary fix @EricDunsworth propose that
>   If needed, I could send over a PR to bring all of the the placeholder images and transcript pages into the wet-boew repo. But I'd want to keep the videos alone since it probably wouldn't be wise to bring such large files into this repo.

I agree as a temporary solution to bring into wet-boew the placeholder image and transcript in order to not have broken working example.

**As a long term solution,** what about creating a new repo that will contains our large assets for our demos?

---

@LaurentGoderre @MaximMartel and other any thoughts?

**Comment by kodecount** [comment]
Just my opinion but having a separate repo seems like a better idea that way I don't need to download large media content every time I need to clone my fork for a quick test when working on a WET project.

**Comment by EricDunsworth** [comment]
I'm totally for it for videos.

But for any other assets that already exist in the wet-boew repo, IMO there wouldn't be any value in moving them into a separate large assets repo.

The commits from the time those assets were still a part of the wet-boew repo will always exist. So even if the assets were removed in future commits, the repo's size wouldn't decrease accordingly. It wouldn't benefit download speeds when cloning the repo.

**Comment by nschonni** [comment]
https://github.com/wet-boew/wet-boew-attachments was setup awhile ago, but I don't think it is appropriate for the videos since I don't think GH will serve them properly without `rawgithub`

**Comment by LaurentGoderre** [comment]
I agree with @nschonni. It's a difficult situation all around and it's not the first time we have this problem

**Comment by kodecount** [comment]
Another option is using Google Driver (if WET has a common GDrive).

**Comment by EricDunsworth** [comment]
#7866 fixes part of this issue. But since this issue covers two distinct topics (current linking issues and a longterm way of dealing with video hosting), I decided against formatting my commit message in a way that would directly close this issue once its PR gets merged in.

**Comment by EricDunsworth** [comment]
Gonna close this since it's no longer relevant:
* wet-boew/wet-boew-attachments#14 brought the Service Canada video assets into that repo.
  * That repo has a GitHub pages site that's derived from its ``master`` branch. That provided an easy way to reference that repo's MP4/WebM/XML/etc files with correct MIME types. IIRC that wasn't possible back when this issue was first opened since in the past GitHub pages required a dedicated ``gh-pages`` branch or a ``username.github.io`` repo.
* #9080 updated the multimedia player's links to point to the ``wet-boew-attachments`` repo's GitHub pages site.
