### ISSUE TITLE
Question: JawsAriaFixes

### ISSUE THREAD

**Issue by kodecount** [wet-boew/wet-boew#7862]
What is `jawsariafixes.js` and how can I use it to improve Jaws performance?

**Comment by duboisp** [comment]
@kodecount can you include a reference/link to that specific file?

**Comment by kodecount** [comment]
It was in `js/polyfills/` when I downloaded WET.

**Comment by duboisp** [comment]
Thanks @kodecount 

So it is this file: https://github.com/wet-boew/wet-boew/blob/master/src/polyfills/jawsariafixes/jawsariafixes.js

Based on the file history, here what it does:

* Jaws ARIA polyfill support for nested heading elements
* Polyfill to fix the Jaws sectioning elements/heading level incrementation bug and the sectioning element/heading association bug.

That javascript are only implementing two work around for existing Jaws specific bugs.

So that file do not related to Jaws performance.

If you wonder about Jaws performance, that seems to be more related directly to your Jaws local setup and his configurations. That is out of scope of wet-boew project.

**Comment by kodecount** [comment]
Thanks. I'd guess for the time being I won't include it into our web project.

**Comment by duboisp** [comment]
@kodecount I have no issue to include in our documentation any information that is related to AT configuration and AT setup when it is for testing purpose. That could help developer to identify specific issues by using Jaws software and submit PR that could modify ```jawsariafixes.js```.

If it is about "how an user should configure his AT to better navigate web pages that run with wet-boew frontend framework" then that kind of information could be perceived out of scope of this project. But sometime changing a few wording could make the difference and perceived in scope.

**Comment by kodecount** [comment]
@duboisp It was a more so curiosity question cause a web project I'm working on needs to be Jaws accessible. So if it help our approval with this I would include it. Currently most stuff has passed we were required to create auto focus methods that would focus the page automatically at the main content of the page they were accessing.

**Comment by duboisp** [comment]
@kodecount you can submit PR that would improve how Jaws deals with pages managed with the wet-boew framework. If you find specific issue that is only related when a specific plugin is used, then the fix should be completed in that specific plugin.

But, prior to merge a global solution for Jaws specific, me I will look for at least the following:
* What is issue?
* Is some user testing result exist? If so do we have those test results.
* What is the importance of the issue?
* How frequent that issue will be encountered by user?
* What is the context, how to get the issue?
* Can the issue be reproduced?
* Can an alternate design be used instead? 
* Is the fix are interfering with other AT or other plugin?
* Is the fix would have a major impact on the overall performance?
* Is the fix actually fix the issue?
etc...

**Comment by kodecount** [comment]
This is how they reported how WET read to them when they launched the application (intranet theme):

1. Skip links were
2. Language selection
3. Page header/link (link was request to be removed (seemed confusing))
4. Menu
5. Breadcrumb
6. Main content header
7. Page tools
8. Page table
9. Footer

Thanks for the input. At my work the final decisions are up-to my manager and accessibility group. The final decision was to skip parts 1-5/6 (depends on page) so the user could get to the content of page faster.

**Comment by LaurentGoderre** [comment]
I strongly discourage the autofocus in the page as it can be very disruptive even for the users you are trying to help in this case. The key in web design is predictability, and automatically is not predictable and certainly not consistent with other sites they are used to. The skip links and hidden headers solve the issue of navigating the page much better than forcing the focus to a page.

**Comment by kodecount** [comment]
I agree with you. I tried to explain that the user could simple tab (or use arrow keys) use the skip links to get to the main content, but it was argued that users wouldn't know what these links are. As I mentioned the decision wasn't mine.

**Comment by LaurentGoderre** [comment]
One argument would be that your site with be inconsistent with all of the other Government of Canada website which could create confusion

**Comment by kodecount** [comment]
As I said it a intranet application so our group focus on internal affect and not external (scope is limited to the application).
