### ISSUE TITLE
Share widget (Email): Unreliable 

### ISSUE THREAD

**Issue by kodecount** [wet-boew/wet-boew#7869]
So a issue I ran into during user testing with Email share button using `mailto`.

Issue Experienced:

- Chrome (latest version) would just put the link in a new tab (confusing for users (looks like gibberish))
- Internet Explorer (latest version) always runs, but sometimes fails to open the Email message (give error saying failed to generate message)

We really need a email share button (if required I could possibly write Java code to do it if no other options).

**Comment by LaurentGoderre** [comment]
If you used java to generate a `mailto` wouldn't you encounter the same issues? This sound like mahcine configuration issue rather than the code.

**Comment by kodecount** [comment]
No I meant create a mail function using Java (server side). The issue with IE is problem a issue with the computers, but the issue with Chrome isn't.
