### ISSUE TITLE
Archived - Archived information (BUG): 

### ISSUE THREAD

**Issue by thekodester** [wet-boew/wet-boew#7871]
Using Chrome 55 on Windows 10 (haven't tested with anything else) if you change the length of the page (like opening a detail/summary) the archive overlay well disappear from page or become cut off.

![chrome](https://cloud.githubusercontent.com/assets/23484460/22397383/bb408fc4-e546-11e6-9f11-b5e670cb9def.png)

Also sometimes you have to repeatedly need too scroll up before it well scroll (become trapped). I have found a different approach here: http://servicecanada.github.io/GCWeb/archived-en.html and seems more aggressive.

**Comment by kodecount** [comment]
Also their is a different approach here: http://servicecanada.github.io/GCWeb/archived-en.html I prefer this, but it seems more aggressive.

**Comment by kodecount** [comment]
I was looking more into the issue and it seems to be a focus issue. In Chrome 55 my focus is locked on the detail/summary unless I click another part of the page. Was looking through the code and I'm sure of an appropriate place to fix this, but with the scroll bar overlays we need to clear focus on the page before showing the overlay bar.
