### ISSUE TITLE
Editor

### ISSUE THREAD

**Issue by TimCadieux** [wet-boew/wet-boew#7876]
Is there a preferred Editor we should be using - example [Editor](https://editor.datatables.net/examples/simple/simple.html)

**Comment by kodecount** [comment]
Don't believe WET is setup with that version of DataTables

**Comment by TimCadieux** [comment]
It's a different plugin all together. I was just wondering what is recommended.

**Comment by LaurentGoderre** [comment]
You can probably integrate it but it's not part of WET.

**Comment by kodecount** [comment]
Also french integration probably won't work. So you'll need to integrate that your self. Cause it be confusing if you have DataTables and Editor tables with same features but different labeling.

**Comment by TimCadieux** [comment]
Yeah, this was just me trying to kill 2 birds with one stone...otherwise i'll just create a modal form probably
