### ISSUE TITLE
Collapsible alert - IE11/Edge - align with default dehavior

### ISSUE THREAD

**Issue by duboisp** [wet-boew/wet-boew#7886]
The collapsible alert do not exactly behave as the default details/summary in IE11/Edge

As discussed in https://github.com/wet-boew/wet-boew/pull/7822#issuecomment-278213861

In Standard mode: There is an arrow resize effect when refreshing the page.
In wbdisable mode: The arrow is still visible.

Some suggestion:
* Align collapsible alert with default behavior of details/summary,
  * Remove [Line 101](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/collapsible-alerts/base.scss#L101) and [Line 110](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/collapsible-alerts/base.scss#L110)
* Change the default behavior of details/summary for inserting the arrow in wbdisable  mode
  * Add css line like ```.wb-disable.no-details>summary:before{ content: "\25BC\a0"; } ```

**Comment by duboisp** [comment]
Because of the issue reported in #7887, I think the best solution will be to remove the CSS content at line 101 and line 110

**Comment by EricDunsworth** [comment]
@duboisp Unfortunately, the ``content`` properties on lines 101 and 110 are absolutely needed. Without them, Bootstrap's alert CSS will override the ``details`` polyfill's CSS, resulting in duplicate alert icons appearing in place of the arrows.

I'm looking into resolving the resize effect and wbdisable/noscript issues.

**Comment by duboisp** [comment]
Thanks for investigating @EricDunsworth
