### ISSUE TITLE
Collapsible alert icon appearing twice in Firefox

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/wet-boew#7887]
I have an older version of FireFox (38.0) at work and noticed on the [collapsible alerts example page](http://wet-boew.github.io/wet-boew/demos/collapsible-alerts/collapsible-alerts-en.html), the triangle icon appears twice in either the collapsed or expanded state (see image attached).  

Is this still a problem in newer versions of FF?

![collapsiblealertinff38](https://cloud.githubusercontent.com/assets/1347487/22785754/9ce42214-eea3-11e6-97fd-9410f3c0cd3f.png)

Possibly related to  #7778 and #7886.

**Comment by duboisp** [comment]
So that means we may should remove the [Line 101](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/collapsible-alerts/base.scss#L101) and [Line 110](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/collapsible-alerts/base.scss#L110)

**Comment by RobJohnston** [comment]
Update for FF 53.0.3 (latest).  The double triangles has disappeared, but when collapsed, there is no alert icon (see image below).

![wet-boew-issues-7887](https://cloud.githubusercontent.com/assets/1347487/26606605/881214ea-4560-11e7-9e6c-b70c8449ca83.png)

Is FireFox worth worrying about?  I hear that it's usage has fallen sharply in the last few months and may be too low to be supported :-(

**Comment by EricDunsworth** [comment]
@RobJohnston The issue you identified in your latest comment is a duplicate of #7778 (check it out for more context). Basically, it's a Gecko rendering bug that can't be worked around within WET's CSS without HTML markup changes.

This doesn't seem to be officially documented anywhere at the moment, but I believe WET is technically meant to support IE10+/Edge, current versions of Firefox and current versions of Chrome. Not sure where Firefox ESR stands.

As for this particular issue, #7894 might've helped it, but I don't have Firefox 38.0 to test with so I'm not sure. [Firefox 38.0 was first released on May 12, 2015](https://www.mozilla.org/en-US/firefox/38.0/releasenotes/) and [its final ESR release seems to have been on April 26, 2016](https://www.mozilla.org/en-US/firefox/38.8.0/releasenotes/). So Mozilla hasn't supported it for over a year.

Firefox didn't officially receive native support for ``<details>`` until [Firefox 49.0](https://developer.mozilla.org/en-US/Firefox/Releases/49), so presumably everything up to and including version 48.x was affected by this issue. The only pre-49.0 versions of Firefox that might still be supported by Mozilla to this day would be 45.0 ESR. [Firefox 45 was first released on March 8, 2016](https://www.mozilla.org/en-US/firefox/45.0/releasenotes/) and [its most recent ESR release was 45.9 on April 19, 2017](https://www.mozilla.org/en-US/firefox/45.9.0/releasenotes/). ESR releases are normally supported for around a year, plus 12 weeks. So if 45.x ESR is still currently supported, it's likely to be EOL'd pretty soon.

Given all that, there might be value in closing this issue.

@duboisp @lucas-hay @LaurentGoderre Thoughts?

**Comment by duboisp** [comment]
Technically, I think we should support any browser that is used 5% and more. I know the supported browser could vary per institution depending of their visits stats. In regard of WET, in it's whole, I don't know which statistical data-source we should use.

**Comment by muling** [comment]
This still seems to be an issue for new versions of Firefox (e.g. 58+).

**Comment by RobJohnston** [comment]
The original issue (Feb 9) was resolved, so I'll close this one and leave the other issue (May 30) to be resolved is the linked issues.
