### ISSUE TITLE
Menu: If more than 1 link on menu is the same, last one alwyas highlighted

### ISSUE THREAD

**Issue by TimCadieux** [wet-boew/wet-boew#7888]
I have a tabbed interface on my homepage.  I want navigation in my menu to point to both products and eventually, open the correct tab when navigated to.

I noticed, if I do this

     <li><a href="en/home#a">Executive Summary</a></li>
     <li><a href="en/home#b">Breaking News</a></li>

The Breaking news link is always highlighted, no matter which tab is opened. 

 You can see in the attached image, the Executive Summary is the tab that's open.
![menuerror](https://cloud.githubusercontent.com/assets/22413348/22787177/6270a8ea-eea9-11e6-8be6-558249b17b0a.png)

**Comment by LaurentGoderre** [comment]
@TimCadieux the menu plugin isn't meant to be used to navigate on the same page. From a usability perspective, it's unlikely a user would think of using that menu for navigating the page.

**Comment by kodecount** [comment]
@LaurentGoderre Thoughts? Maybe he should do something like the sign in/sing out menu bar for navigation?

**Comment by TimCadieux** [comment]
This is the main menu.  If a user is on a different page, goes to products and chooses Breaking News, it should take them to that page (which it does).  It just happens that Breaking News is just a tab on the same page as the Executive Summary.  They're distinct products but high profile so are both on the home page.  The plugin just highlights the wrong thing in the menu as *current page*.

**Comment by kodecount** [comment]
As @LaurentGoderre said the menu isn't setup for this.

**Comment by TimCadieux** [comment]
Using  update-hash allows me to link directly to the correct tab...so there wouldn't be any confusion.
