### ISSUE TITLE
Accordions not working on ie8 

### ISSUE THREAD

**Issue by Pubudu-Basnayaka-COS** [wet-boew/wet-boew#7893]
I've been testing using the IE emulation tool as well as on actual browsers, please see to recreate:

visit 
http://wet-boew.github.io/v4.0-ci/demos/toggle/toggle-en.html#accordion on ie8 browser or 

set emulation to IE8, and clicking on accordions no longer work. 

This is regarding v4.0.23 of wet-boew-dist

**Comment by kodecount** [comment]
IE8 and IE9 support was ended. Can be seen here.

**Comment by duboisp** [comment]
@Pubudu-Basnayaka-COS I do not know if the toggle worked well before the end of support of ie8.

However a quick solution will be to extract the toogle plugin when ie8 was supported https://github.com/wet-boew/wet-boew/tree/8abd9faab888e770f1f8514e96f7f94326880055 and modify the plugin name like "wb-toogle-ie8". Then you will need to see if the plugin at that point of time is still compatible with the latest wet core and insert work-around in your "wb-toogle-ie8" plugin any issue that you may found.

The [hello world plugin example](http://wet-boew.github.io/wet-boew/demos/helloworld/helloworld-en.html) may help you to understand how you can achieve it.
