### ISSUE TITLE
Character Encoding Issue (JavaScript (Suggestion))

### ISSUE THREAD

**Issue by kodecount** [wet-boew/wet-boew#7897]
So I'm using Struts2 and I have to do an action redirect. When the page redirects I lose the character encoding when the french JS files are processed and the user well see `entrÃ©es`. Their a really easy fix replace characters like `à` with `\xE0` or `é` with `\xE9` (or for cap `É` with `\xC9`).

Also I get the character codes from: http://www.character-code.com/ .

I would love to see this fixed (right now I'll have to hard code it and have an warning either not to remove the file or apply this change to feature version).

**Comment by LaurentGoderre** [comment]
I think this should be fixed on the server, not in WET. You should set your server to be utf8 by default for all js and css files

**Comment by kodecount** [comment]
It is set to use UTF8

**Comment by kodecount** [comment]
It is set to use UTF8. See http://stackoverflow.com/a/9853620 why I choose to use character codes.

It works perfectly fine it when you leave the page and return using an action call in Struts JavaScript breaks.

**Comment by LaurentGoderre** [comment]
To me that still a server configuration. We can't do the switch to explicit UTF8 escape because it would make translations a nightmare.

**Comment by kodecount** [comment]
I understand that it just a suggestion. Like I said worst case scenario I'll do up a readme in the project I working on and hope the next developer reads it.
