### ISSUE TITLE
Radio/Checkbox Buttons (on focus submits the form)

### ISSUE THREAD

**Issue by kodecount** [wet-boew/wet-boew#7903]
This is a weird issues seems to be bigger then WET. But Radio/Checkbox buttons submit the form when you are focused on them and hit the ENTER key.

Related discussions:
- https://www.jotform.com/answers/261641-When-Radio-Buttons-have-the-focus-ENTER-submits-form

**Comment by LaurentGoderre** [comment]
That is by design....pressing enter anywhere in a form (except for a textarea) submits the form. Checkboxes use the space bar for selection

**Comment by kodecount** [comment]
Okay seems odd. Just my opinion.
