### ISSUE TITLE
Tabbed Interface: printing all tabs

### ISSUE THREAD

**Issue by dghouse** [wet-boew/wet-boew#7904]
I have a page that uses the tabbed interface and my problem is that when a user attempts to print, they will get the active tab only. I know that there is "print-active" option and my interface does not use that option. In fact, if you visit the documentation page [https://wet-boew.github.io/v4.0-ci/unmin/docs/ref/tabs/tabs-en.html](URL) and look at print preview, you will only see the active tab. 

Does anyone have any advice on how I might force the print preview to see all of the tabs?

**Comment by kodecount** [comment]
Their is a fix in the works.

**Comment by dghouse** [comment]
That's great to hear. In the meantime, is there a work around?

**Comment by kodecount** [comment]
No you could pull the code in PR.

**Comment by kodecount** [comment]
If you new to SCSS I could get you a CSS work around using code in PR

**Comment by kodecount** [comment]
I've updated comment with the code. This would have to go in a custom css file (or in style tags at top of page).

**Comment by dghouse** [comment]
That is exactly what I'm looking for. Many thanks kodecount!

So will this be fixed in the next version? If so, what't the expected release date?

Again, many thanks!

**Comment by kodecount** [comment]
It well be in the next release (not the current one (sadly)).

**Comment by EricDunsworth** [comment]
FYI #7759 was merged prior to 4.0.24's release. Printing the tabbed interface plugin's demo page looks fine on my end nowadays.

**Comment by lucas-hay** [comment]
@EricDunsworth thanks!!
Closing this issue.
