### ISSUE TITLE
Feeds: Require file update?

### ISSUE THREAD

**Issue by TinoTran-Work** [wet-boew/wet-boew#7916]
Hello,

We are currently utilizing v4.0.18 of the wet-boew.min.js.  The feeds section is no longer working.  I have tried to copy the example provided on the site and that does not work as well.  When I do a view source, I notice that the demo is utilizing v.4.0.25-development.

Is there an update required for this feature to work again?

Thank you for your time.  Have a wonderful day!

**Comment by kodecount** [comment]
The issue with v4.0.18 is this line of code
```javascript
var requestURL = wb.pageUrlParts.protocol + "//ajax.googleapis.com/ajax/services/feed/load?v=1.0&callback=?&q=" + encodeURIComponent( decodeURIComponent( url ) );
```
As the Google API is deprecated. Either use v4.0.25 or change this the Yahoo API.

Their is some issue with the current (just a warning):

- Facebook no longer supports this type of feed (Facebook is in the works)
- Some government networks could be blocking the Yahoo API that is used to convert the RSS/XML feed to JSON (this has been looked (complicate issue))

See https://github.com/wet-boew/wet-boew/pull/7010 for more information.

**Comment by kodecount** [comment]
I'd say the issue can be closed. As either the creator of the issue well have to attempt to change the feed code on the outdated version or update.
