### ISSUE TITLE
Secondary menus display appears to have been broken by v4.0.24 in gcwu theme

### ISSUE THREAD

**Issue by erarcham** [wet-boew/wet-boew#7918]
This is what it looked like in v4.0.23:
![image](https://cloud.githubusercontent.com/assets/1868098/23364403/f51d4cd0-fccc-11e6-9cf3-3c4a746a70ad.png)

And this is v4.0.24:
![image](https://cloud.githubusercontent.com/assets/1868098/23364383/de453df6-fccc-11e6-9273-4c5ac690f920.png)

Live example:
https://wet-boew.github.io/themes-dist/theme-gcwu-fegc/content-secmenu-en.html

**Comment by LaurentGoderre** [comment]
@EricDunsworth could that be related to the background colors fixes?

**Comment by kodecount** [comment]
You mean this https://github.com/wet-boew/wet-boew/pull/7857/files ?

**Comment by EricDunsworth** [comment]
Sorry :(. Guess I didn't pay enough attention to left navs when I tested #7857 and related PRs in all the themes.

I'll send over a fix for it sometime today.

**Comment by EricDunsworth** [comment]
Specifically, what broke the usability theme's left nav background was wet-boew/theme-gcwu-fegc#243. FWIW, none of my other related PRs broke left nav backgrounds in any other WET themes.

As a part of wet-boew/theme-gcwu-fegc#243, in _screen-md-min.scss I removed ``background-color: #fff;`` from ``%page-background``. The content area's ``container`` class was previously extending ``%page-background`` to set a white background colour on both the left nav and main content areas. I must've overlooked it while testing.

I'll send a PR to wet-boew to rename #7857's ``$main-bg`` variable into something along the lines of ``$content-bg`` and apply it by default to the content area's ``container`` class. Then I'll send out related PRs to other themes. Might also move ``$content-bg``'s declaration before ``$breadcrumb-bg`` and make the latter default to the former's value.

**Comment by EricDunsworth** [comment]
#7920 and wet-boew/theme-gcwu-fegc#244 should fix this issue.
