### ISSUE TITLE
Standardized Canada.ca colours for charts and graphs up to 10 data elements

### ISSUE THREAD

**Issue by MaryBethBaker** [wet-boew/wet-boew#7926]
Hi @duboisp @masterbee,

For the Charts and graph widget is there a standard set of #ally colours that Canada.ca recommends using? Also if you could pull someone from the IA spec team in on this thread - I couldn't find a handle for any of the people I know working there. I'd like to recommend to my clients a standard set of colours that meets Web Standards and the Canada.ca IA Specification.

Thanks!
Mary Beth

// @eketype

**Comment by duboisp** [comment]
@MaryBethBaker here the sequence of color, as defined here https://github.com/wet-boew/wet-boew/blob/master/src/core/wb.js#L242

1. #8d201c
2. #EE8310
3. #2a7da6
4. #5a306b
5. #285228
6. #154055
7. #555555
8. #f6d200
9. #d73d38
10. #418541
11. #87aec9
12. #23447e
13. #999999

For anything Canada.ca specific, like the IA spec, ask your question on [GC web repository](https://github.com/wet-boew/GCWeb/issues/new)

**Comment by MaryBethBaker** [comment]
Thanks @duboisp! 

I will use the GC web repository account in the future too. I didn't think about posting there.

//cc @eketype
