### ISSUE TITLE
Checkbox Error Validation

### ISSUE THREAD

**Issue by Hodgmik** [wet-boew/wet-boew#7929]
I have a form where I want the user to check all of the checkboxes in a fieldset and if they do not check all of the boxes in the fieldset it should return a validation error that the field is required.  When I use the required="required" code in each checkbox input tag it does not work.  It only returns a validation error if the user does not select any checkboxes.  Is there a way to do this while keeping all the checkboxes in the same fieldset?  So in essence, I want the user to select all of the checkboxes or it produces a validation error.

![chkbxerror](https://cloud.githubusercontent.com/assets/3450326/23558424/88eb74aa-0001-11e7-9042-0824cd8152ad.jpg)
![chkbxerror1](https://cloud.githubusercontent.com/assets/3450326/23558423/88e94e64-0001-11e7-95a3-e98c7f1270f7.jpg)
![chkbxerror2](https://cloud.githubusercontent.com/assets/3450326/23560126/5cb53456-0007-11e7-8bca-f5dba3fda6ca.jpg)

**Comment by sgdowney** [comment]
What if you gave each checkbox a unique id?

**Comment by LaurentGoderre** [comment]
Yeah, they need unique id and unique names

**Comment by kodecount** [comment]
Some server languages let you use arrays also like
```javascript
<fieldset>
<legend class="required"><span class="field-name">Idenfication Cards</span> <strong class="required">(required)</strong></legend>
<div class="checkbox">
<label for="idCard1"><input type="checkbox" name="idCard[0]" value="1" id="idCard1" required="required" />&#160;&#160;Card 1</label>
</div>
<div class="checkbox">
<label for="idCard2"><input type="checkbox" name="idCard[1]" value="2" id="idCard2" required="required" />&#160;&#160;Card 2</label>
</div>
<div class="checkbox">
<label for="idCard3"><input type="checkbox" name="idCard[2]" value="3" id="idCard3" required="required" />&#160;&#160;Card 3</label>
</div>
<div class="checkbox">
<label for="idCard4"><input type="checkbox" name="idCard[3]" value="4" id="idCard4" required="required" />&#160;&#160;Card 4</label>
</div>
</fieldset>
```

**Comment by biljanap** [comment]
@Hodgmik Do you need to group your checkboxes in `<fieldset>`?
If not, this might work for you:

```html
<div> 
  <h2>Identification cards <strong class="text-danger">(required)</strong></h2>
  <div class="form-group form-inline">
    <input type="checkbox" name="check1" value="1" id="check1" required="required" class="form-control">
    &nbsp;&nbsp;&nbsp;
    <label for="check1" class="required"><span class="field-name">Check1</span>&nbsp;<strong class="required">(required)</strong></label>
  </div>
  <div class="form-group form-inline">
    <input type="checkbox" name="check2" value="2" id="check2" required="required" class="form-control">
    &nbsp;&nbsp;&nbsp;
    <label for="check2" class="required"><span class="field-name">Check2</span>&nbsp;<strong class="required">(required)</strong></label>
  </div>
  <div class="form-group form-inline">
    <input type="checkbox" name="check3" value="2" id="check3" required="required" class="form-control">
    &nbsp;&nbsp;&nbsp;
    <label for="check3" class="required"><span class="field-name">Check3</span>&nbsp;<strong class="required">(required)</strong></label>
  </div>
</div>
```
Screenshots before and after errors.
Notice that I did not use `<fieldset>` and that I am using `<h2>` instead of `<legend>`.

![checkbox-required](https://cloud.githubusercontent.com/assets/2146304/23628471/56e4280c-0282-11e7-9c23-c43a4d172911.jpg)

![checkbox-required-errors](https://cloud.githubusercontent.com/assets/2146304/23628476/5c8f5902-0282-11e7-88f0-240c44ec19f9.jpg)

**Comment by Hodgmik** [comment]
Thanks Everyone.  Laurent helped me in person.  Good to have him one floor up from me which I did not realize before. lol!  As far as the unique ID's go I tried to give an example without giving to much information out and I forgot to change the unique ID's in the example.  Apologies.  Thanks again.

**Comment by biljanap** [comment]
@Hodgmik would it be too much work to post the solution. I would be very much interested in it. Thanks.
