### ISSUE TITLE
Tables: Are we allowed to embed Overlay in table?

### ISSUE THREAD

**Issue by TimCadieux** [wet-boew/wet-boew#7930]
I ask becuase anything rendered on the first page works but not on any following page

        $.each(data, function (index) {
            var b = '<p><a href=\"#centred-popup-modal-body-' + index + '\" aria-controls=\"centred-popup-modal\" class=\"wb-lbx lbx-modal\" role=\"button\"><i class=\"fa fa-external-link\"></i></a></p>';

            b = b + '<section id=\"centred-popup-modal-body-' + index + '\" class=\"mfp-hide modal-dialog modal-content overlay-def\">';
            b = b + '<header class=\"modal-header\">';
            b = b + '<h2 class=\"modal-title\">' + this.title + ' - ' + this.publication.name + '(' + this.publicationDateInUsersTimeZone + ')</h2>';
            b = b + '</header>';
            b = b + '<div class="modal-body">';
            b = b + '<section>';
            b = b + '<p><strong>Publication :</strong>' + this.publication.name + '</p>';
            b = b + '</section>';
            b = b + '<section>';
            b = b + '<p><strong>Word Count :</strong>' + this.wordCount + '</p>';
            b = b + '</section>';

            b = b + '<button class=\"btn btn-primary popup-modal-dismiss\" type=\"button\">Close</button>';
            b = b + '</div>';
            b = b + '</section>';
            this.publication.name = b;
        });

**Comment by TimCadieux** [comment]
Actually, i just tested and the same happens with a Details panel

**Comment by TimCadieux** [comment]
Actually, what i really want to do is [this](https://datatables.net/extensions/responsive/examples/display-types/bootstrap-modal.html)

**Comment by kodecount** [comment]
Yeah I don't believe WET has this ability. What I would do is use JavaScript localStorage.

Kinda hard to explain (I could attempt an example if you wish). You use an unique id from the table data as the localStorage key and add an object with all the data required as a value. Then on each row use a button like: `<button class="btn btn-md btn-default btn-extinfo" data-btn-extinfo="key" type="button" role="button"><i class="glyphicons glyphicons-plus-sign" aria-hidden="true"></i></button>`

Each button would have `data-btn-extinfo="key"` _key_ being the localStorage key. You also add a signal overlay to the page when the button is press you populate the overlay with the data from the localStorage and you just have to make sure to clear the data when overlay closed or when you reopen it using a trigger after adding data.

**Comment by TimCadieux** [comment]
It's built right into the dataTable though?

**Comment by kodecount** [comment]
No, it requires extra scripts. You have to do it similar too the `excel` button.

**Comment by kodecount** [comment]
What I explain above I have done this my self. I just don't have a copy of the code, but I should be able to recreate it.

**Comment by TimCadieux** [comment]
Thank you.

**Comment by kodecount** [comment]
All done. Example can be seen here: https://kodecount.ca/demos/tables/orders

**Comment by TimCadieux** [comment]
Thx, i got it working but it seems to do the same as the way I had mine setup...if you add more than 10 records, do any of the popups on the next page work?

**Comment by kodecount** [comment]
Forgot about that. Script was updated to handle more then one page of records.

**Comment by TimCadieux** [comment]
That did it, thx!!
