### ISSUE TITLE
Calendar of Events (multiple years)

### ISSUE THREAD

**Issue by kodecount** [wet-boew/wet-boew#7932]
Question? When you have events in let say 2015 and 2017 (you can't remove 2015 for business reasons) the user would have to scroll through all of 2015, 2016, and 2017 (when using the arrows) to get to the next event.

I personally don't need this. Just something I seen and thought was odd (maybe from a code prescriptive it makes sense, but a user prescriptive it could seem tedious).

**Comment by duboisp** [comment]
@kodecount Can you consider an alternate design? It could be something like moving past events, like each quarter, to an archived events pages.

**Comment by kodecount** [comment]
Yes if that is simpler.
