### ISSUE TITLE
Menu: removing aria-posinset and aria-setsize

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/wet-boew#7939]
If you validate a page in WET after JS execution, you will get a bunch of errors with the `aria-posinset` and `aria-setsize` being set to the wrong element. After talking to some accessibility experts at an A11Ymtl meetup, as well as a speaker from the Confoo conference in MTL and looking into the use of these attributes I've come to the conclusion that these attributes are not really needed in our menu and it might be a little overkill to have them there.

I vote for removing them.

Stay tuned for a PR.

cc: @andrewnordlund @masterbee @TouficS @rlambert27

**Comment by kodecount** [comment]
I've had issue on this ages ago because the accessibility software I use for testing flagged them as incorrect.  See issue https://github.com/wet-boew/wet-boew/issues/7795.

**Comment by shawnthompson** [comment]
I'm bad at searching for per-existing issues, my bad. We are going to remove them. Thanks for linking the issues together.

**Comment by kodecount** [comment]
That fine. I closed the issue as their was no interest at the time. Currently WET breaks WCAG by having these on the `<a>` element versus `<li>` anyways.

**Comment by shawnthompson** [comment]
That's why I'm removing them and they aren't really needed because the menu is pretty basic with a standard order and nothing moving inside the drop downs.

**Comment by duboisp** [comment]
I am fine with this as if the menu will remain navigable with common assistive technology.
