### ISSUE TITLE
Collapsible alerts: icon disappears when collapsed

### ISSUE THREAD

**Issue by muling** [wet-boew/wet-boew#7943]
Why does the icon go away when the menu is collapsed?  Was that intentional?  This is with the latest version of WET 4.0.23.

**Comment by kodecount** [comment]
What browser? If it is Firefox their is a bug in their a few of their version.

Also latest version is WET 4.0.24.

**Comment by kodecount** [comment]
It still occurs in the latest version. I can remember if their able to fix this.

**Comment by kodecount** [comment]
Duplicate of https://github.com/wet-boew/wet-boew/issues/7778

**Comment by muling** [comment]
Yes I am using Firefox.

**Comment by kodecount** [comment]
You'll have to wait till Firefox fixes the bug.
