### ISSUE TITLE
Session Timeout: Empty link with no text

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/wet-boew#7945]
If you run wave on this page it shows an empty link 

`<a class="wb-lbx lbx-modal mfp-hide wb-lbx-inited wb-init" href="#wb-sessto-modal" id="wb-auto-2"></a>`

Wave says this...

>**What It Means**
A link contains no text.
>**Why It Matters**
If a link contains no text, the function or purpose of the link will not be presented to the user. This can introduce confusion for keyboard and screen reader users.
>**How to Fix It**
Remove the empty link or provide text within the link that describes the functionality and/or target of that link.
>**The Algorithm... in English**
An anchor element has an href attribute, but contains no text (or only spaces) and no images with alternative text.
>**Standards and Guidelines**
2.4.4 Link Purpose (In Context) (Level A)

cc/ @rlambert27

**Comment by duboisp** [comment]
@shawnthompson do you have that issue with the Session timeout working example or with the lightbox working example?

**Comment by shawnthompson** [comment]
@duboisp issue doesn't show up on the [overlay page](http://wet-boew.github.io/v4.0-ci/unmin/demos/overlay/overlay-en.html), only the [session timeout](http://wet-boew.github.io/v4.0-ci/unmin/demos/session-timeout/session-timeout-en.html).

**Comment by shawnthompson** [comment]
This is the problem

https://github.com/wet-boew/wet-boew/blob/master/src/plugins/session-timeout/session-timeout.js#L136

`temp.innerHTML = "<a class='wb-lbx lbx-modal mfp-hide' href='#" + componentName + "-modal'></a>" +`

What about putting this:

`temp.innerHTML = "<a class='wb-lbx lbx-modal mfp-hide' href='#" + componentName + "-modal'>"+ componentName + "</a>" +`

As placeholder text? Or maybe putting a new variable for relevant link text for this function.

**Comment by shawnthompson** [comment]
Adding this link text would mean doing all the translation for the text. Could I just update the English and French i18n JSON files?

**Comment by shawnthompson** [comment]
Actually I'm going to use `i18nText.st-msgbx-ttl` it's already there and it works. Answered my own question!

**Comment by duboisp** [comment]
Updating only the JSON file is very risky to lost all updates. Don't you have access to the google docs spreadsheet?

**Comment by shawnthompson** [comment]
shoot yeah I forgot about that... doesn't matter I'm not updating / adding to the i18n, I'm going to be using an existing one. :smiley:

**Comment by shawnthompson** [comment]
@stdgit can you take a look at this when you get back from vacation?

CC: @andrewnordlund

**Comment by EricDunsworth** [comment]
Going to close this off since #8443 fixed it (just double-checked on the [session timeout plugin's demo page](http://wet-boew.github.io/v4.0-ci/unmin/demos/session-timeout/session-timeout-en.html)).

Btw #8443's subject references this issue, but didn't do it in a way that would allow GitHub to link the PR and issue together. That's why this issue wasn't auto-closed when #8443 was merged in.
