### ISSUE TITLE
 Tabbed Interface showing/flashing contents from all the tabs on load

### ISSUE THREAD

**Issue by johnpalaganas** [wet-boew/wet-boew#7950]
Hello,

**Scenario:** Tabbed Interface with a lot of content such as Tables
**WET:** 4.0.23

When you have a Tabbed Interface with tabs with a lot of contents, it will show all contents inside the tabs as it loads. It cycles to all tabs showing all contents in a "flashing" manner.

It should only display the contents when its done loading.

Screenshot during the flashing of all the contents as it loads.
![image](https://cloud.githubusercontent.com/assets/4248755/24043925/53ee83c0-0aef-11e7-94e9-5a3298386a6b.png)

Thanks,
John

**Comment by kodecount** [comment]
You already have this same issue open here: https://github.com/wet-boew/wet-boew/issues/7381

Opening two issues won't get it fixed faster.

**Comment by johnpalaganas** [comment]
@kodecount Are you like a bot? Pretty neat! Thanks for reminding me its the same issue.

**Comment by kodecount** [comment]
No just too much free time.

**Comment by kodecount** [comment]
Also lot of these issues are related to this topic: https://github.com/wet-boew/wet-boew/issues/7752

**Comment by johnpalaganas** [comment]
Thats good detective work. I hope this issue can get resolve soon, imagine if you have different background colours in different tabs? Some might fall to the ground.

**Comment by kodecount** [comment]
I just contribute to the project. I would tackle this but it bit complicated for me. Since the equalized plugin is in bed with so many other plugins that fixing issue with one plugin could break others. Hopefully the WET team is looking into a way to fix it or redesign it.

**Comment by mercury64** [comment]
I have a solution that works for this. I have removed the equal height

**Comment by pepers** [comment]
@mercury64  This may be a silly question, but is there anything I can do with css or javascript to stop the flickering in the meantime, without directly editing the wet code?
