### ISSUE TITLE
Angular 2 on WET Intranet theme

### ISSUE THREAD

**Issue by UncleZen** [wet-boew/wet-boew#7959]
I have been working on an Angular v2.0 application that uses WET GoC Intranet theme. 

The only issue that I am experiencing with this theme is setting up the main menu items as Angular router links using the routerLink directive like: `<a [routerLink]="['/fetch-data']">Fetch data</a>`. These menu items don't behave like Angular router links at all. This is not the case links in the other sections of the page. Namely, if I were to put the same link on the footer menu, it would work just fine. 

I have two questions in regards to this issue:

1. Have you ever dealt with an issue like this and do you have a solution for it?
2. Is there a more Angular friendly WET theme available?

Thanks!

Zen

**Comment by LaurentGoderre** [comment]
I would recommend to only use Angular for the content area and leave WET unaltered for menu etc if it can be helped.

**Comment by UncleZen** [comment]
Thanks Laurent!
