### ISSUE TITLE
Prettify has incorrect link

### ISSUE THREAD

**Issue by CalvinRodo** [wet-boew/wet-boew#7977]
The link to the Google-Code-Prettify links to the http://code.google.com/p/google-code-prettify/ which is currently archived and it should link to it's new home on GitHub https://github.com/google/code-prettify

**Comment by nschonni** [comment]
Looks like the JS, docs, and ref need to be updated https://github.com/wet-boew/wet-boew/search?utf8=%E2%9C%93&q=http%3A%2F%2Fcode.google.com%2Fp%2Fgoogle-code-prettify%2F&type=
Do you want to PR something?
