### ISSUE TITLE
Server side datatable

### ISSUE THREAD

**Issue by QuesnelJ** [wet-boew/wet-boew#7985]
Greetings,

I have requirements to run datatable server side. So, I started by just implementing datatable to my page using JavaScrript. However things are not working.

 Part of my code is:

JavaScript:

```fs
$(document).ready(function() {
	var t = $('#allDataTableData').dataTable(
		{
			"processing": true,
			"serverSide": true,
			"ajax": "/fEdit/ajax/getTableData.php"
		} );
	} );

```
HTML:

```html
<table id="allDataTableData">
<thead>...</thead><tfoot>...</tfoot><body>...</body>
</table>

```
I'm getting the error: Object doesn't support property or method 'dataTable'

This error occurs at the `var t = $('#allDataTableData').dataTable(` line above.

However, if I use the `<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js"></script>` library as oppose to WET4's, then things work well.

Any idea? I'll send chocolates if you make this work...

**Comment by RobJohnston** [comment]
What version of WET are you running? My guess is the version of the DataTables script may need to be recent... looks like it was [upgrade in WET from 1.10.7 to 1.10.13](https://github.com/wet-boew/wet-boew/commit/183ff177de43dd28d5acfe29b1af701d8164c88b) a couple months ago.

Find out which version of DataTables is running on your version of WET and see if loading that version via the CDN has the same problem.

**Comment by duboisp** [comment]
Try something like the last working example here: http://wet-boew.github.io/wet-boew/demos/tables/tables-en.html

Then you would need to adjust the mapping of your table columns. 

```html
<table class="wb-tables table table-striped table-hover" id="allDataTableData" aria-live="polite" data-wb-tables='{
            "bDeferRender": true,
            "ajaxSource": "/fEdit/ajax/getTableData.php",
            "order": [5, "desc"],
             "columns": [
                { "data": "TITLE", "className": "nws-tbl-ttl h4" },
                { "data": "PUBDATE", "className": "nws-tbl-date" },
                { "data": "DEPT", "className": "nws-tbl-dept" },
                { "data": "TYPE", "className": "nws-tbl-type" },
                { "data": "TEASER",  "className": "nws-tbl-desc" },
                { "data": "LOCATION",  "visible": false },
                { "data": "AUDIENCE",  "visible": false },
                { "data": "SUBJECT", "visible": false },
                { "data": "MINISTER", "visible": false }
              ]}'>
<thead>
<tr>
<th>Title</th>
<th>Publication date</th>
<th>Department</th>
<th>News Type</th>
<th>Summary</th>
<th>Location</th>
<th>For</th>
<th>Subject</th>
<th>Minister</th>
</tr>
</thead>
</table>
```

If you are using GCWeb, then there are an alternative way by using the [data-json plugin with and HTML5 template element](http://wet-boew.github.io/themes-dist/GCWeb/demos/data-json/template-en.html) which will only work with the next upcoming release of WET.

**Comment by nschonni** [comment]
@QuesnelJ You need to use the `wb-ready.wb-tables` described in the documentation https://wet-boew.github.io/wet-boew/docs/ref/tables/tables-en.html. When you use `document.ready`, WET hasn't had a chance to loaded the dependencies yet. @duboisp example also shows the correct classes you'd need for WET to do the automatic initialization if you don't want to manually trigger anything

**Comment by QuesnelJ** [comment]
I believe that RobJohnston response above is the correct one.

When running the version of dataTables (1.10.7) that comes with WET4.0.24 I experience the issue.

But running with a version of dataTables (1.10.15) that I downloaded from their web site, all works well. I have not tried version 1.10.13, therefore I assume that RobJohnston is correct.

Where do I send the chocolates?

Now someone needs to update the dataTable that is packaged with the WET4 template.

**Comment by RobJohnston** [comment]
I'm actually surprised that a minor version increase would make such a difference.

Luckily for you, I'm having a bit of a "fat day", so you don't have to send the chocolates ;-)

**Comment by QuesnelJ** [comment]
:) I'm having a bit of a fat life. But there's always room for chocolate.

Jacques Quesnel - Dif-tor heh smusma
<https://en.wikipedia.org/wiki/Vulcan_salute#.22Live_long_and_prosper.22>
Quesnel.Jacques@gMail.com

**Comment by BetaGeminorum** [comment]
@nschonni I have tried using `wb-ready.wb` but no luck ... `document.ready` works but my data is undefined at that point. Please find my code bellow.

HTML:

```
<table class="wb-tables table table-striped table-hover" id="datatable" aria-live="polite" data-wb-tables='{
             "destroy": true,
             "retrieve": true,
             "deferRender": false,
             "language": {
               "search": "Search:",
               "info": "Showing _START_ to _END_ of _TOTAL_ projects",
               "infoEmpty": "Your search did not match any projects",
               "infoFiltered": "(searched from _MAX_ total projects)",
               "lengthMenu": "Show _MENU_ ",
               "zeroRecords": "No matching projects found"},
             "order": [1, "asc"],
             "ajax": {
                   "url": "/Project/GetProjects",
                   "dataSrc": "data"},
             "columns": [
                {"data": "ID", "type": "number", "className": "prj-id"},
                {"data": "Title", "className": "prj-ttl"},
                {"data": "Status", "className": "prj-stt"},
                {"data": "Type", "className": "prj-typ"},
                {"data": "Province", "className": "prj-prv"}],
              "columnDefs": [
                {"targets": "_all", "searchable": true},
                {"targets": [2, 3], "visible": false}
               ]}'>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Status</th>
                    <th>Type</th>
                    <th>Province</th>
                </tr>
            </thead>
        </table>

```

The datatable renders fine and my data is loaded as expected. My objective now is to insert a render function inside data-wb-tables = {} to manipulate the json data just in time but I believe that's not a functionality WET currently supports ... **Is there an update on data-wb-tables supporting functions?**

I have seen others achieve this by using events like `$(document).on("xhr.dt", ".wb-tables", function(...){});` or `$(document).on("wb-ready.wb", function(...){});` but it feels like WET isn't loading properly for me and therefore events are not being fired? I'm using CDTS on MVC5 to receive WET.

JS:

```
        <script>
            $(document).on("wb-ready.wb", function () {
                alert("Ready!");
            });
        </script>
```

The above js code does nothing... Any idea?

**Comment by duboisp** [comment]
@BetaGeminorum can you provide a sample that show the data structure of the document that you retrieve here "/Project/GetProjects". Is it a valid JSON file?

**Comment by BetaGeminorum** [comment]
```
{
  "data": [
    {
      "ID": 19920,
      "Title": "Wildlife Project",
      "Status": "Completed",
      "Type": "Review Panel",
      "Province": "Alberta"
    },
    {
      "ID": 18819,
      "Title": "Midwest Project",
      "Status": "Completed",
      "Type": "Comprehensive Study",
      "Province": "Saskatchewan"
    }
  ]
}
```

Yes it is a valid JSON data, Project/GetProjects generates it:

```
            var jsonData = new
            {
                data = db.Database.SqlQuery<Project>(query).ToList()
            };

            return Json(jsonData, JsonRequestBehavior.AllowGet);
```

**Comment by BetaGeminorum** [comment]
@duboisp please dismiss my issue as I figured it out offline (had to recompile CDTS and play with it to get events fired). But do kindly provide an update on when ` data-wb-tables` will support functions?
