### ISSUE TITLE
DataTables - Extensions

### ISSUE THREAD

**Issue by afull** [wet-boew/wet-boew#7999]
Good day,

Are we permitted to use the extensions available for the DataTable plugin.
I have a client that would like to use the FixedHeader extenion so that the table header is frozen while vertically scrolling through the table.  (https://www.datatables.net/extensions/index)

Is there any policy or reason against using this feature?

**Comment by LaurentGoderre** [comment]
These extensions are not tested and may not meet the Accessibility standard.

**Comment by afull** [comment]
Thanks for the update.
