### ISSUE TITLE
CSS: Add class for removing just bullets (setting list style type to none)

### ISSUE THREAD

**Issue by pjackson28** [wet-boew/wet-boew#8001]
We need a better way to remove just the bullets for lists. The only option currently available is .list-unstyled which has the unfortunate side effect of zeroing out padding-left, forcing users to then reapply the indenting to nested lists with the margin classes.

Ideally there would be a class like the following:
.lst-none {
     list-style-type: none;
}

There are classes for applying other list types (and nothing else) such as lst-lwr-rmn and lst-lwr-alph so there should be same for applying the none list type.

**Comment by Bgolden67** [comment]
Can't you just over-ride the existing one to not zero out the left margin?
Is there a reason to have it zeroed out like it is?

**Comment by pjackson28** [comment]
This is a base class from Bootstrap so shouldn't be overridden. It works fine for the first level list but is problematic for the second, third and lower level lists.

What I am recommending is the following:
```html
<ul class="list-unstyled">
     <li>
          <ul class="lst-none">
               <li>...</li>
          </ul>
      </li>
</ul>
```

That way you can have the bullets removed for any nested lists without every list item having x position regardless of nesting.

**Comment by Bgolden67** [comment]
Would there be any impact if you used lst-none on the first level instead of list-unstyled?
Many people won't know the difference. The only difference in the classes would be the margin right? or will lst-none be set to only work on a sublist?

**Comment by pjackson28** [comment]
The only difference would be that with lst-none the left padding wouldn't be removed so the first list level wouldn't be left aligned with the rest of the content (would be indented a bit).

**Comment by Bgolden67** [comment]
sounds good.
