### ISSUE TITLE
Follow - add RSS and Instagram classes to generate icons

### ISSUE THREAD

**Issue by tyhsimms** [wet-boew/wet-boew#8007]
@duboisp We would like to add links to RSS and Instagram in our "Follow:" box. Can we add a class for RSS and Instagram that function the way the facebook, twitter and youtube classes do (populates an icon using a background image)?

http://www.cic.gc.ca/english/department/index.asp

Thanks,
Tyh
![follow](https://cloud.githubusercontent.com/assets/3485710/26158362/9f6e455e-3ae9-11e7-9cd0-2fc125fd75ef.jpg)

**Comment by duboisp** [comment]
@tyhsimms can you put back the issue title and description? Then can you comment how you resolved your issue. It might help for other that have similar issue.

Cheers
