### ISSUE TITLE
Basic HTML - Why are we still using that?

### ISSUE THREAD

**Issue by massep** [wet-boew/wet-boew#8025]
Hi all,

I have googled about Basic HTML for an hour and found no reason to still have this on our pages. Can someone shed some light on why we should not stop allowing it? 

Thanks

**Comment by jsguy1** [comment]
Hello,

What do you mean by Basic HTML? Are you referring to older versions of HTML such as HTML 4?

**Comment by duboisp** [comment]
@massep the "Basic HTML" is a mode in the wet-boew that do not run any plugin. It look similar to a  simulated "no javascript" mode.

The Basic HTML mode help some screen reader user to read content that was not progressively enhanced.

**Comment by massep** [comment]
Thank you duboisp. Is this mode supported in the top 3 browser of 2017? Like latest IE, Chrome and Firefox?

Cheers

**Comment by LaurentGoderre** [comment]
Yes it is.
