### ISSUE TITLE
Feeds: YQL Fate

### ISSUE THREAD

**Issue by kodecount** [wet-boew/wet-boew#8035]
Hey, their currently no issue, but I noticed in the news that it look like it finally official that Verizon well buy Yahoo which been like over year long sale. Currently their isn't much information, but currently looks like Verizon wants to convert it into a new search engine (some sort of re-branding). So far [developer.yahoo.com](https://developer.yahoo.com/yql/console/) which is used by feeds hasn't been affected but it something to keep an eye on.

**Comment by lucas-hay** [comment]
@kodecount thanks for putting this on the radar. We have had issues in the past when YQL was down intermittently. Do you (or anyone), have any suggestions for an alternative to YQL?

**Comment by kodecount** [comment]
Personally I don't know of any FREE ones that are as advance as YQL and support Atom, JSON, RSS, and Media RSS. Hopefully going forward if were so lucky Verizon well keep people in the loop.
