### ISSUE TITLE
CSS not applied to dynamic page content

### ISSUE THREAD

**Issue by dannysheppard** [wet-boew/wet-boew#8041]
Our application is based on CDTS (using wet 4.0.24).

I need to dynamically build two components using JavaScript and add them to the page:

1) A menu built as per CDTS guidelines
2) A number of expand/collapse sections (using details/summary polyfill widget)

Each of these items has an issue, but I believe they are both the result of the CSS not being applied:

1) The "current page" is not highlighted in the menu as it should be.
2) The expand/collapse widgets do not work (i.e. clicking them does not expand them).

The interesting thing here is that the code DOES work when I run it locally on my machine. It works MOST of the time on our development server. However it almost NEVER works on our production server.

Both issues happen at the same time, or neither happens.

I have been playing with this for a while and it appears to be some sort of timing issue with the page load/CSS application. For example, if I open IE developer console, it makes the problem much more reproducible.

I have tried changing where in the HTML file the JavaScript that renders the content is invoked, when it is rendered (onload, onready, on-wb-ready), and I've even tried changing how the content is generated. Anything I can try to make sure that the content has the CSS styles applied. Nothing has worked so far.

At the end of the day, things render correctly sometimes (and is dependent on the server it is deployed to), but I can't identify what is the real root cause.

Here is the code that is used to generate the content. It is a callback method invoked by an Ajax call which loads a JSON file containing the content required to build the menus etc. This file is parsed and the menu and expand/collapse sections are built by calling the appropriate method which returns HTML in the correct format. That content is then set as the innerHTML of the div above.

The content of the div with id "wb-sec" is replaced with the generated content.

```html
<nav class="wb-sec col-md-3 col-md-pull-9" id="navContent">
            <div role="navigation" id="wb-sec" typeof="SiteNavigationElement">
               <noscript>*noscript content*</noscript></div></nav>
```

The following script is used to generate the menu and expand/collapse by using calls to CDTS and creating WET components directly.

```js
headLib.getOrtContentList(function(ortContent) {

       var secondarymenu = document.getElementById("wb-sec");
               var sideMenus = headLib.buildParentSiblingMenu('en', 'task', ortContent);
               var menus = wet.builder.secmenu({
                  sections: sideMenus
               });
               var relatedLinks = headLib.buildRelatedLinks('en', .... params used to configure the expand collapse....  , ortContent);

               if (relatedLinks != '') {
                  menus += relatedLinks;
               }
               secondarymenu.innerHTML = menus;
            });
         </script>
```

Because this works on some servers, and intermittently on others, I know the format of the content is correct.

This is how the menu looks when thing work:

![menuhighlighted](https://cloud.githubusercontent.com/assets/28925380/26796157/66a42196-49f6-11e7-9f7a-32f193d7bfb2.jpg)

And here is how it looks when things do not work:

![menunothighlighted](https://cloud.githubusercontent.com/assets/28925380/26796203/956d7b4e-49f6-11e7-812c-dc252ec102c0.jpg)

Thanks!

**Comment by nschonni** [comment]
> wet.builder.secmenu

Is this a CTDS thing or custom code?

Is the `headLib.getOrtContentList(` being called safely in a block that is waiting for wet (or a particular plugin) to load?
```js
$( document ).on( "wb-ready.wb", function( event ) {
   // some JS relying on WET to be loaded
});
```

**Comment by dannysheppard** [comment]
Yes, wet.builder.secmenu is a CDTS specific call which builds the menu HTML.

I have tried surrounding the call with

`$( document ).on( "wb-ready.wb", function( event ) {})`

But that actually has the opposite effect of making it fail every single time.

It seems that waiting for wet to be finished loading is the problem, and that I need to make sure that the JavaScript is invoked before WET finishes. Based on my testing, it seems that it's a race condition. Once I get that WET event, any further DOM manipulation fails. I have been having similar issues with DataTables (which I opened another issue for).

**Comment by duboisp** [comment]
There is an element in the ```wb-sec``` navigation block that are calling the [wb-navcurr](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/navcurrent/navcurrent.js) plugin in order to select the active menu? Or that active class is set when the left nav is build?

Are you able to provide a sample of the inner html of ```wb-sec``` corresponding of the above both screen capture?

**Comment by dannysheppard** [comment]
I have no idea about the wb-navcurr plugin or how it's used. I am only adding the HTML as directed by CDTS (in the case of the menu) or WET (in the case of the expand/collapse).

In this case I made the wrong (sort of) assumption that it was a CSS issue, but now that I inspect the elements after rendering, I think I'm back to a JavaScript issue as the styles are different on the components based on whether they loaded correctly or not.

Here is what it looks like when things load OK:

```html
<nav class="wb-sec col-md-3 col-md-pull-9">
   <div class=" wb-navcurr-inited" id="wb-sec" role="navigation" typeof="SiteNavigationElement">
      <h2 class="wb-inv" id="wb-sec-h">Section menu</h2>
      <section class="list-group menu list-unstyled">
         <h3>What do you want to do?</h3>
         <ul class="list-group menu list-unstyled">
            <li><a class="list-group-item wb-navcurr" href="/en/procedure/activity/benefit_se.html">Recalculating a claim for self-employment benefits</a>
               <ul class="list-group menu list-unstyled">
                  <li><a class="list-group-item" href="/en/procedure/task/reviewing_claim_calculated_ei_bse.html ">Reviewing a claim calculated with Estimated Income—Benefits for the Self-employed</a></li>
                  <li><a class="list-group-item" href="/en/procedure/task/recalc_benefit_se.html">Recalculation—Benefits for the Self-employed</a></li>
               </ul>
            </li>
         </ul>
      </section>
   </div>
</nav>

<ul class="list-unstyled">
   <li>
      <details>
         <summary tabindex="0" class="relatedLinks wb-init wb-details-inited" id="wb-auto-7" role="button" aria-expanded="false">Related Activities</summary>
         <ul class="list-unstyled">
            <li class="mrgn-bttm-md"><a href="/en/procedure/activity/activity_test_cal_output.html">File Not Found: activity_test_cal_output.xml</a></li>
            <li class="mrgn-bttm-md"><a href="/en/procedure/activity/antedate.html">File Not Found: antedate.xml</a></li>
         </ul>
      </details>
   </li>
   <li>
      <details>
         <summary tabindex="0" class="relatedLinks wb-init wb-details-inited" id="wb-auto-8" role="button" aria-expanded="false">Additional Resources</summary>
         <ul class="list-unstyled">
            <li class="mrgn-bttm-md"><a href="/en/site/generic/jobaids_index.html">File Not Found: jobaids_index.xml</a></li>
            <li class="mrgn-bttm-md"><a href="/en/site/generic/sitegeneric.html">Site generic Edit</a></li>
         </ul>
      </details>
   </li>
</ul>
```

And here's what it looks like when things go wrong:

```html
<nav class="wb-sec col-md-3 col-md-pull-9" id="navContent">
   <div class=" wb-navcurr-inited" id="wb-sec" role="navigation" typeof="SiteNavigationElement">
      <h2 class="wb-inv" id="wb-sec-h">Section menu</h2>
      <section class="list-group menu list-unstyled">
         <h3>What do you want to do?</h3>
         <ul class="list-group menu list-unstyled">
            <li><a class="list-group-item" href="/en/procedure/activity/benefit_se.html">Recalculating a claim for self-employment benefits</a>
               <ul class="list-group menu list-unstyled">
                  <li><a class="list-group-item" href="/en/procedure/task/reviewing_claim_calculated_ei_bse.html ">Reviewing a claim calculated with Estimated Income—Benefits for the Self-employed</a></li>
                  <li><a class="list-group-item" href="/en/procedure/task/recalc_benefit_se.html">Recalculation—Benefits for the Self-employed</a></li>
               </ul>
            </li>
         </ul>
      </section>
   </div>
</nav>

<ul class="list-unstyled">
   <li>
      <details>
         <summary class="relatedLinks">Related Activities</summary>
         <ul class="list-unstyled">
            <li class="mrgn-bttm-md"><a href="/en/procedure/activity/activity_test_cal_output.html">File Not Found: activity_test_cal_output.xml</a></li>
            <li class="mrgn-bttm-md"><a href="/en/procedure/activity/antedate.html">File Not Found: antedate.xml</a></li>
         </ul>
      </details>
   </li>
   <li>
      <details>
         <summary class="relatedLinks">Additional Resources</summary>
         <ul class="list-unstyled">
            <li class="mrgn-bttm-md"><a href="/en/site/generic/jobaids_index.html">File Not Found: jobaids_index.xml</a></li>
            <li class="mrgn-bttm-md"><a href="/en/site/generic/sitegeneric.html">Site generic Edit</a></li>
         </ul>
      </details>
   </li>
</ul>
```

So the wb-navcurr, and wb-init, and wb-details-inited styles are not applied, and the aria-expanded attribute is not updated. This all points back to JavaScript.

So the question is back to: How do I generate this content in my JavaScript and insert it into the DOM BEFORE any of the WET (CDTS?) JavaScript is run which is supposed to modify it?

**Comment by dannysheppard** [comment]
I mentioned that the code uses AJAX to get the data used to update the DOM. This must be the real root of the problem. The code that adds the menu and expand/collapse components to the page does so in a callback method which is invoked after using AJAX to get the datafile used to generate the menus.

So the WET/CDTS finishes loading, then the AJAX call invokes the callback method which updates the DOM.

So in this case, how do I ensure things get initialized again after the callback method is invoked?

`
headLib.getOrtContentList(function(ortContent){
	var secondarymenu = document.getElementById("wb-sec");
    var sideMenus = [];

    // build menu content

    // insert menu into DOM
	secondarymenu.innerHTML = menus;
}
`

**Comment by LaurentGoderre** [comment]
This community doesn't support the CDTS. @rlambert27 do you have a place to track these?

**Comment by dannysheppard** [comment]
@LaurentGoderre I realize that the menu is CDTS, but the issue also exists with the WET expand/collapse component (and I'm also seeing issues with datatables using AJAX), so I'm thinking that under the hood, regardless of using CDTS this is somehow WET related.

**Comment by rlambert27** [comment]
@LaurentGoderre Almost sounds as if you don't like the CDTS :-p

For any CDTS related issues we ask developers to email us at nc-sgdc-cdts-gd@hrsdc-rhdcc.gc.ca. We're working on getting everything up and running in Gitlabs so we'll track issues over there once it's ready.

Although like @dannysheppard says I think this may also be an issue in WET regardless if CDTS is used or not. We discussed it by email and suggested opening an issue on Github to see if anyone could help out.

**Comment by sgdowney** [comment]
After the menu has loaded via ajax, you probably need to manually trigger the menu initialization so that WET can enhance the menu properly.  See the events section of http://wet-boew.github.io/wet-boew/docs/ref/menu/menu-en.html.
I suspect it may be the same with the details/summary as well.   http://wet-boew.github.io/wet-boew/docs/ref/details/details-en.html

**Comment by dannysheppard** [comment]
I've tried adding the following at the end of my callback method, but it doesn't seem to do anything.

`$( ".wb-menu" ).trigger( "wb-init.wb-menu" );`

**Comment by sgdowney** [comment]
On your nav element you don't have the "wb-menu" class.  The selector for triggering the menu init has to return the nav element.  Your code won't reference the nav element because it's looking for an element with the class "wb-menu".

**Comment by dannysheppard** [comment]
Yes, I was just looking at that. The thing is CDTS writes the menu, and it doesn't output that class. I tried picking up the "wb-sec" class or the ID, but it doesn't seem to work.

I was able to get the expand/collapse menus working though by calling

$( "summary" ).trigger( "wb-init.wb-details" );

**Comment by sgdowney** [comment]
I can't say for sure, my comment was based on the documentation for the menu plug-in that uses that class.  

I guess what you need is some way to force the menu to reinitialize after the content has been loaded.  If WET has already initialized the menu content then when you try to manually trigger the initialization it will skip your menu because it appears to have been initialized already.  Does the content you load replace the entire nav element or just content within the nav?

**Comment by dannysheppard** [comment]
I just realized what the difference is here. This is "secondary menu" that is generated by CDTS, and not a WET component per se. It is used to render a side menu, not the top menu as in the documentation for the WET menu (see screenshots above).

So while the expand/collapse was a pure WET issue and solution (thank you!), the side menu may be a CDTS issue. @rlambert27 any thoughts on this? Is there a way to trigger the CDTS secondary menu?

**Comment by rlambert27** [comment]
The only way to trigger the menu is running the JS code for wet.builder.secmenu. Once you run that the JS outputs the HTML to correct DIV. You can certainly delay it by adding a condition.

**Comment by nschonni** [comment]
Closing since the WET part has been answered and the CTDS isn't related to this tracker
