### ISSUE TITLE
Session timeout warning has a nonsensical "Close" button.

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/wet-boew#8043]
Possibly brought in from https://github.com/wet-boew/wet-boew/pull/7908, the[ session timeout warning](http://wet-boew.github.io/wet-boew/demos/session-timeout/session-timeout-en.html) now has a "Close" button.  

![image](https://user-images.githubusercontent.com/1347487/26840203-4fec3e44-4ab3-11e7-9b17-da2a0c497e31.png)

**Comment by sgdowney** [comment]
As mentioned in #7908, the default close button can be suppressed by adding the `popup-modal-dismiss` class to a button in a `modal-footer` div.
I tried that but the footer div seems to loose the styling that ties it to the rest of the dialogue.
Default setup:
![nomodalfooter](https://user-images.githubusercontent.com/5131107/28089528-ea13c5b2-664e-11e7-92cd-b1a804235d82.jpg)
Adding a footer with a button:
![withmodalfooter](https://user-images.githubusercontent.com/5131107/28089533-f375e8e2-664e-11e7-97da-e473de722558.jpg)
```
<section class="modal-dialog modal-content overlay-def">
    <header class="modal-header">
        <h2>Order Details</h2>
    </header>
    <div class="modal-body">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ProductName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UnitPrice)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Quantity)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Discount)
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UnitPrice)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Discount)
                    </td>
                </tr>
            }

        </table>
    </div>
    <div class="modal-footer">
        <button class="btn btn-primary popup-modal-dismiss" type="button">Return to Orders</button>
    </div>
</section>

```

**Comment by sgdowney** [comment]
In the Lightbox.js source it styles the automatically added `modal-footer` div:
`footer.style.background = "#fff";`
Shouldn't that be part of the `modal-footer` class?
