### ISSUE TITLE
Overlay: Why completely darkened behind window?

### ISSUE THREAD

**Issue by RitchieD** [wet-boew/wet-boew#8044]
As of the latest version of WET (4.0.25), the behind window of a modal popup is now completely darkened instead of just “inactive” darkened.  This means the user loses context.  The best practice for usability is to have its lightly darkened  (http://www.uxforthemasses.com/overlays/).

I recommend reverting back to the lightly darkened of previous version, or at least providing an option for that.

**Comment by LaurentGoderre** [comment]
This change was done because modal popup were not really modal. A screen reader could escape the context of the dialog and get stuck. For this reason, in modal mode, the rest of the page uses `display: none`. Reverting this change affects accessibility.

**Comment by DK-TBS** [comment]
Question:  do we face a similar problem on non-modal, lightbox popups as well?  Any chance we can do the 50% black overlay for the non-modal ones?

**Comment by LaurentGoderre** [comment]
I think even non modal lightbox were causing issues for users of screen readers

**Comment by DK-TBS** [comment]
Poop.  Okay, thanks brother.  Good to know  :)

**Comment by UXaaron** [comment]
What makes the modal popup were not really modal? Does this happen across all modals or just our implementation?

**Comment by RitchieD** [comment]
Note:   AJAXed content is not hidden when modal popup is active.  Making a half hidden background.

For anyone who really can't stand the full-blackout here is an unsupported un-recommend band-aid.

Comment out the code that adds the class "wb-modal" to the body.

wet-boew.min.js :
`for(/*o.find("body").addClass("wb-modal"),*/o.find(n).attr("aria-hidden","true")`

 wet-boew.js
`/*$document.find( "body" ).addClass( "wb-modal" );*/`
