### ISSUE TITLE
Random JavaScript 'null' issues

### ISSUE THREAD

**Issue by saqib-dareshani** [wet-boew/wet-boew#8056]
IE 11.0.9600

WET Manifest info:
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.8.3
Created-By: 1.6.0_20-b02 (Sun Microsystems Inc.)
Built-By: dxh136

Name: Versioning
Implementation-Title: wetdev application
Implementation-Version: 4.0.24
Implementation-Vendor: xxxx
Implementation-Date: 2017-06-07 10:54:20
Cvs-Tag: ${cvstag.prefix}

With this WET version are getting random JavaScript Issues such as on **line 8678**:

**HTML1300: Navigation occurred.
File: publicIndex.action
SCRIPT5007: Unable to get property 'replace' of undefined or null reference
File: wet-boew.min.js, Line: 8, Column: 94871**

And if we try to use the pop-up (lightbox) on **line 6546**:

**HTML1300: Navigation occurred.
File: publicIndex.action
SCRIPT5007: Unable to get property 'defaults' of undefined or null reference
File: wet-boew.min.js, Line: 8, Column: 70581**

Looks like some race condition... when I reload the page sometimes no errors occur at all.

**Comment by duboisp** [comment]
Are you able to reproduce those error within one of our [working example](http://wet-boew.github.io/wet-boew/demos/index-en.html)?

Is the page that you are testing run a lot of different wet-boew feature? Is the page contain a lot of HTML code or just a few line?

**Comment by saqib-dareshani** [comment]
Yes, I just got this error on http://wet-boew.github.io/themes-dist/GCWeb/index-en.html

HTML1300: Navigation occurred.
File: index-en.html
SCRIPT5007: Unable to get property 'replace' of undefined or null reference
File: wet-boew.min.js, Line: 8, Column: 95465

Null error on line 8715 in wet-boew.js on replace:  spanTextFtr = spanTextFtr.replace( "'", "&#39;" );

And in jquery.js
ret = ( (jQuery.event.special[ handleObj.origType ] || {}).handle || handleObj.handler )
							.apply( matched.elem, args );
Unable to get property 'replace' of undefined or null reference

And also get exceptions in the footer

**Comment by saqib-dareshani** [comment]
Just so you know the error is random, sometimes it takes a few tries going from Widgets page back to the main page above - or sometimes it just happens right away.

Another one:

HTML1300: Navigation occurred.
File: feedback-en.html
SCRIPT5007: Unable to get property 'replace' of undefined or null reference
File: wet-boew.min.js, Line: 8, Column: 95465

(Line 4434 on jquery.js):

ret = ( (jQuery.event.special[ handleObj.origType ] || {}).handle || handleObj.handler )
							.apply( matched.elem, args );

Unable to get property 'replace' of undefined or null reference

**Comment by duboisp** [comment]
What browser and version are you using?

**Comment by saqib-dareshani** [comment]
As mentioned above IE 8 11.0.9600 :)

**Comment by saqib-dareshani** [comment]
Were you able to reproduce the issue?

**Comment by duboisp** [comment]
I was not able to reproduce the error in Firefox dev and Chrome.

With IE 11.1358.14393 I was able to reproduce the issue intermittently by refreshing the page (1 times for ~10 try) with the GCweb theme. I was not able to reproduce with the wet-boew theme.

Tested page
GCWeb: http://wet-boew.github.io/themes-dist/GCWeb/demos/index-en.html
WET: http://wet-boew.github.io/wet-boew/demos/index-en.html

The error that I got on the test page in IE was

> [SCRIPT5007](https://msdn.microsoft.com/query/dev12.query?appId=Dev12IDEF1&l=FR-CA&k=k(VS.WebClient.Help.SCRIPT5007)): Unable to get property 'type' of undefined or null reference

That error is throw from this line https://github.com/wet-boew/wet-boew/blob/master/src/plugins/tables/tables.js#L89

**Comment by saqib-dareshani** [comment]
FYI I also reproduced the null issue on their GCWeb theme as well.  

SCRIPT5007: Unable to get property 'type' of undefined or null reference
Line 10104 of wet-boew.js

When going to Charts and graphs page on 

http://wet-boew.github.io/themes-dist/GCWeb/demos/index-en.html

I’ll let them know we are also experiencing this issue on their http://wet-boew.github.io/wet-boew/demos/index-en.html too

**Comment by duboisp** [comment]
@saqib-dareshani ???
