### ISSUE TITLE
What is the minimum Firefox version supported by the wet.

### ISSUE THREAD

**Issue by gilles-leblanc** [wet-boew/wet-boew#8057]
Reading other issues, I have read that the WET supports any browser that accounts for at least 5% usage on the Canada.ca site.

These isssues go on to list various browsers and versions of IE that are supported, but not the specific versions of Firefox.

Is it defined what is the minimum version of Firefox that is required? 
I am currently tasked with correcting a  wet-beow site that has been tested with a web accessibility-compatibility tool.

I want to set the tool to ignore errors based on versions of Firefox that aren't support by the wet.

Thanks.

**Comment by nschonni** [comment]
I believe that would be the last ESR release https://www.mozilla.org/en-US/firefox/organizations/faq/
Currently that is 45, but I think it's about to flip over to 52

**Comment by gilles-leblanc** [comment]
Ok thanks.
