### ISSUE TITLE
Filterable Content speed optimization & "position: absolute" problems

### ISSUE THREAD

**Issue by lega0208** [wet-boew/wet-boew#8059]
I'm building a page using the Filterable Content plugin, but the performance seems to be a bit of an issue. Even with just 252 entries, if I click on one of the filters or start typing, it takes several seconds for it to start responding again. I was wondering if there was anything I could do to improve performance, or if it could be worked on for a future release. 
I haven't looked at the code base too much and I'm sort of new to GitHub, so forgive me if what I say is stupid, but I think making certain parts of the plugin asynchronous would help tremendously in terms of performance and/or perceived performance. If it's non-blocking, then the page won't freeze up while it's doing all the filtering work, and the filtering itself should be much faster as well.

Additionally, I found it problematic that the plugin automatically adds an inline styling of "position: absolute" to each box. This meant I had to add `
	.box {
		position:static!important;
	}` to my page for it to behave properly, or else the boxes would just sit on top of and hide any other HTML I put outside of the boxes. (For example, headers that would separate certain sections). There don't seem to be any issues now that I've added that, so it doesn't seem like adding "position: absolute" was necessary in the first place. Anyone feel free to chime in if there is an issue with this.

Thanks

**Comment by duboisp** [comment]
Are you using the data table plugin to filter?

Can you post a sample of your code?

**Comment by lega0208** [comment]
Well now I'm a little embarrassed, because I just noticed that this seems to be a custom CRA plugin. If anyone is from the CRA, [this](http://infozone/english/r1713497/org/sa/sa06/sb/sb01/tlr/tlr06/fltr-e.html) is what I'm referring to. But now this isn't an issue for this repo, so I guess it doesn't belong here. Sorry for the confusion.
