### ISSUE TITLE
Collapsible alerts: Collapse icon disappears

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/wet-boew#8072]
When you collapse the details / summary of the collapsible alerts, the font icon disappears.

http://wet-boew.github.io/v4.0-ci/unmin/demos/collapsible-alerts/collapsible-alerts-en.html

Open
![image](https://user-images.githubusercontent.com/2575266/27687559-485bb4d0-5ca5-11e7-85e1-5c4eb84e2aa9.png)

Closed
![image](https://user-images.githubusercontent.com/2575266/27687526-2d8e5c7a-5ca5-11e7-96ec-809bdce5b1cd.png)

**Comment by RobJohnston** [comment]
Is this just a FireFox thing?  See https://github.com/wet-boew/wet-boew/issues/7887.

**Comment by duboisp** [comment]
What browser? I do not have that issue with Chrome and IE 11

**Comment by shawnthompson** [comment]
Firefox on both Mac and PC

**Comment by shawnthompson** [comment]
That's exactly the same issue, I'm closing this one. Thanks @RobJohnston and @duboisp
