### ISSUE TITLE
How to Disable polyfills

### ISSUE THREAD

**Issue by Slyke** [wet-boew/wet-boew#8074]
I'm using an AngularJS 2 and WET together. So far it's been good.

But right now, I'm getting double carrots ( > ) in a menu that I'm using, and upon closer inspection, it's because the Summary tag is adding one carrot, and WET is loading some polyfill CSS and JS and adding another as a pseudo element. It's loading these psuedo elements from `details.min.css` and `details.min.js`

I'm using the latest version of Chrome as my browser.

**Comment by nschonni** [comment]
Chrome has native support for the Details/Summary so the polyfill wouldn't be loading

**Comment by Slyke** [comment]
@nschonni Well it is loading the polyfills. How can I find out why it's loading, if it shouldn't be?

**Comment by nschonni** [comment]
The polyfills are loaded when the Modernizr test fails. Is there something interfering somewhere, or other console/network errors?

**Comment by Slyke** [comment]
No, no errors anywhere. But you have given me a place to start looking for the issue. I was looking in totally wrong area. When I find out what was happening, I'll report back here.

**Comment by Slyke** [comment]
Okay, so it appears that the Modernizr.details test is returning false on my app.

This Modernizr snippet:
`Modernizr.addTest("details",function(){var e=document,t=e.createElement("details"),n,r,i;return"open"in t?(r=e.body||function(){var t=e.documentElement;return n=!0,t.insertBefore(e.createElement("body"),t.firstElementChild||t.firstChild)}(),t.innerHTML="<summary>a</summary>b",t.style.display="block",r.appendChild(t),i=t.offsetHeight,t.open=!0,i=i!=t.offsetHeight,r.removeChild(t),n&&r.parentNode.removeChild(r),i):!1})`

Seems to be the part that's failing. Trying to figure out why.

**Comment by Slyke** [comment]
So after some more in-depth searching, I've found that the test fails because the offsetHeight of the details tag is not changing after its state is set to open:

`i=t.offsetHeight,t.open=!0,i=i!=t.offsetHeight`

The funny thing is that when I force this test to return true, the detail and summary tags work fine. If this test is allowed to run, it fails, and loads in the polyfills, which prevents the summary tags from working.

Any idea why?
