### ISSUE TITLE
Tables: PHP server side version

### ISSUE THREAD

**Issue by TimCadieux** [wet-boew/wet-boew#8082]
Not a php programmer, got stuck on a php project.  Does anyone have a version of the serverside.php code they could share.  None of the examples i've tried online have worked at all.

**Comment by duboisp** [comment]
Is the "serverside.php" need to return a JSON file that you will use with the data tables feature?

**Comment by TimCadieux** [comment]
Yes, I'm looking to see if someone can share their code for returning the appropriate Json

**Comment by duboisp** [comment]
Is this can help you? https://stackoverflow.com/questions/4064444/returning-json-from-a-php-script

**Comment by TimCadieux** [comment]
Actually the datatables website wrote this...i wasn't aware it existed until now

https://github.com/DataTables/DataTables/blob/master/examples/server_side/scripts/server_processing.php
