### ISSUE TITLE
Images not loading from FTP source

### ISSUE THREAD

**Issue by upsonp** [wet-boew/wet-boew#8092]
Hi All,

I'm pretty sure this isn't a WET issue, but given it's an issue and no one else is responding to me I'm hoping someone here can tell me what's going on and/or point me in the right direction.

I have a website where images are created daily, because of the infrastructure setup for my web servers the images can't be uploaded directly to the web server. We have an FTP location the content provider uploads images to that the web site pulls from.

So when I display images these images are loaded from ftp://ftp1.dfo-mpo.gc.ca

In Firefox and Internet Explorer this works fine, and it use to work fine in Chrome. Within the last couple months it's stopped working in Chrome. I thought it was an internal DFO policy that they were blocking images loaded from FTP, but no one's gotten back to me on that. Up until a couple weeks ago it was only an issue internal to DFO, the images loaded fine from my home PC and/or from Chrome on my phone. But now it seems the images won't load at all.

If you visit [this page](http://www.bio.gc.ca/science/research-recherche/ocean/forecasts-previsions/forecasts-previsions-en.php) and click on any of the links (e.g 000 - 048) you'll see the broken images. The funny thing is if you have the images actual address (e.g Surface Tracks : Scotian Shelf : 00z : hour 000 - 048, ftp://ftp1.dfo-mpo.gc.ca/BIOWebMaster/data_upload/iceocean_model/00Z_SS_track.png) you can see the image fine. 

I'm trying to figure out if this is a Chrome thing, or a Network Policy thing or a WET thing or some combination of issues thing. It's driving me nuts.

**Comment by jvanulde** [comment]
Avoid FTP like a wounded Rhino - it's not supported on many devices. What happens if you use HTTP?

**Comment by upsonp** [comment]
> Avoid FTP like a wounded Rhino

That would be ideal :)

Unfortunately the web server I was provided has no FTP option to upload content, no shared drive, nothing. It's deployed to through an automated script from an SVN setup. So for clients that provide real-time data there's no way to push their content to the web server.

Because the images reside on an FTP server with no web server component you can't load the images using HTTP.

**Comment by CalvinRodo** [comment]
Could you not write an API that lets the clients push data to the web server? Or a page where they can upload the file, there are a lot of libraries out there that handle the nitty gritty of this for you. File uploading has been a solved problem for ever.

**Comment by duboisp** [comment]
Can you create a PHP script that will load the image (server side) from that FTP and return it through HTTP protocol?

**Comment by upsonp** [comment]
Do you mean like have a script that will download the images from FTP to the server then you could use the '<img src="http://..." />' to display them from the server?

Unfortunately I can't do it that way, that I've discovered. It doesn't allow PHP scripts to write to the server.

I should close this issue though, I'm working with a guy in IM&TS to have a web server specifically for serving images setup that'll use a slightly different work flow than my main site.

I'm still interested in your idea if you can expand on it.

**Comment by RobJohnston** [comment]
@upsonp: Having a separate server for images isn't a bad idea.  See "[Static files on a Separate Web Server to Improve Performance](http://performance-expert.blogspot.ca/2012/06/static-files-on-separate-web-server-to.html)" if you have to justify this method to IM&TS.  And they say that [Nginx ](https://en.wikipedia.org/wiki/Nginx) is among the best for serving static content.

**Comment by upsonp** [comment]
You guys are awesome. Thanks @RobJohnston and @duboisp
