### ISSUE TITLE
Font Awesome: 

### ISSUE THREAD

**Issue by TimCadieux** [wet-boew/wet-boew#8105]
Encountering a strange issue
My Font Awesome glyphs don't show on my French pages.
Its the same code to display, only difference bewtween the Eng or French master page is the lang="en" or lang="fr"

Please see the Emg and French screen captures
```
<div class="form-group">
      <button class="btn btn-default btn-sm" id="CreatePDF" data-toggle="tooltip" data-placement="left">
                <i class="fa fa-file-pdf-o" aria-hidden="true"></i>
      </button>
</div>
```

![english](https://user-images.githubusercontent.com/22413348/28843830-89f0ddea-76d0-11e7-86e8-394d23deade7.PNG)
![french](https://user-images.githubusercontent.com/22413348/28843829-89ee63c6-76d0-11e7-9746-99dacd3daa75.PNG)

**Comment by nschonni** [comment]
Font Awesome isn't bundled/supported with the toolkit. There is some demos the styleguide, but only the glyph-icons from Bootstrap are actually included by default.

**Comment by TimCadieux** [comment]
Just a follow up, i fixed this by updating the the most recent version 4.2.0
