### ISSUE TITLE
Form Validation Issue

### ISSUE THREAD

**Issue by NoisyMonk** [wet-boew/wet-boew#8111]
Hello,

I'm having some issues with form validation.

Essentially, the "required field" form validation doesn't kick in the first time that I switch focus away to another field. The only way it kicks in is with the following pattern;

1.  Set focus on the input field "First Name" (currently empty)
2.  Enter in some text
3.  **Leave the "First Name" field (put focus on some other field ("Last Name" for example))**
4.  Go back to the "First Name" field, and delete the text
5.  Switch away to another field again
6.  "Required" validation error activates

Under any other scenario, the validation doesn't work. The important step is 3 - i.e. I must leave the field after entering something, then come back to the field, then remove the text, and then leave the field again to get the "required" error.

My assumption from the examples I've seen is that even if I set focus on an empty field and leave without entering anything, the "required" error should be displayed. But for whatever reason I can't get that to work. Any ideas?

**WET version**: 2.0.24
**Browser**: IE 11.0.96 (unfortunately I don't have access to any other browsers to test on)

**Comment by kodecount** [comment]
I would recommend updating your WET. Their been many improvements to form validation and security vulnerabilities fixed.

**Comment by NoisyMonk** [comment]
Fixed when upgraded to 2.0.25.

This can be closed.

Thanks!

**Comment by EricDunsworth** [comment]
@NoisyMonk FYI you should have the ability to close this issue directly by clicking the "Close issue" button at the bottom of this page.
