### ISSUE TITLE
INPUT tag placeholder styling isn't working as I'd expect

### ISSUE THREAD

**Issue by myGitHubUName** [wet-boew/wet-boew#8118]
I am currently working with v4.0.23 and the theme it uses is at https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_23/css/theme.min.css. I can't tell if the problem is still there because I can't find that file in this repository. Regardless...

The styling I am having a problem with is on line 12 in v4.0.23 regarding:
```
    [placeholder], input[placeholder] {
        color: #5c5c5c!important;
    }
```

It seems the definition for the placeholder font color is overriding the color of the font even when the placeholder text isn't being displayed. 

I created a simple HTML to test how an INPUT tag with placeholder should work and how it works when the styling is defined as in WET. When I use this outside WET (no styling applied whatsoever), the font changes to the default (straight black in the absence of any other styling) from the placeholder's grey font. This is as I expect. 

However, within the WET template, the placeholder's grey font styling remains even when a value is set in the INPUT tag. I think something needs to be adjusted in the WET styling. No idea what...

```
<html>
<body>
  <div id="myDiv">
    <script type="text/javascript">
    function fn(){
        var someValue = "Some value";
        var inputElement = document.getElementById('inputElem');

        if (inputElement.value == someValue){
            document.getElementById('buttonElem').textContent = "Update Value";
            inputElement.value = "";
            inputElement.labels[0].textContent = "Note the font for the 'placeholder' text.";
        }
        else {
            document.getElementById('buttonElem').textContent = "Remove Value";
            inputElement.value = someValue;
            inputElement.labels[0].textContent = "Note whether the font changes when the 'placeholder' text is no longer displayed.";
        }
    }
    </script>
    <label for="inputElem">Note the font for the 'placeholder' text.</label>
    <p />
    <input id="inputElem" type="text" placeholder="Click button ..." readonly="readonly">
    <p />
    <button id="buttonElem" onclick="fn()">Update Value</button>
  </div>
</body>
</html>
```

Hoping this is clear enough, 
jtm

**Comment by nschonni** [comment]
If you're dealing with canada.ca, then the repo theme you're looking for is https://github.com/wet-boew/GCWeb

**Comment by duboisp** [comment]
> I can't tell if the problem is still there because I can't find that file in this repository. Regardless...

That file is created during the build, when the SCSS file are all compiled together to create the theme.css

As @nschonni mention, your issue seems are specific to GCWeb theme. I found the line of code that you mention in the GCWeb repo here: https://github.com/wet-boew/GCWeb/blob/master/src/_defaults.scss#L26

If you are experiencing the same issue with the latest version of wet-boew ([version 4.0.26](http://wet-boew.github.io/wet-boew/docs/versions/dwnld-en.html)) then I recommend also, you to create a new in issue in the [GCWeb repository](https://github.com/wet-boew/GCWeb/issues/new).

Cheers
