### ISSUE TITLE
Calendar of Events: Set the displayed date on load

### ISSUE THREAD

**Issue by upsonp** [wet-boew/wet-boew#8121]
I'd like to set the date the calendar of events displays on load. 

Currently it always shows the earliest date in the calendar, but I'd like to either set it to show the current year and month or the most recent date in the calendar.

Any ideas?

I have a workaround, since I'm building the page from a database, where I only retrieve the most recent and future events, and have a separate place to display "archived" events, but it'd be a lot nicer to keep everything in one place and just show the current month and allow the user to navigate back and forth using the calendar.

I'm sure there some data={...} variable I can set, I just can't find it in the documentation.

**Comment by upsonp** [comment]
Never mind. I found on right where it should be on the demo page.

Add data-wb-calevt='{"year": 2003, "month": 4}' to the tag where the calendar is defined with the year and month set to the date you want.

**Comment by zomby22** [comment]
in my case, I want the calendar to load the current year/month. So examples, the calendar pulls information from the database, if there is an event available in april 2018 but there is none for may 2018, I want to see the calendar showing may 2018 by default even if there is no event. The calendar works for past events but not for future events when empty? help please. Setting the year and month didn't work for me.

**Comment by upsonp** [comment]
That shouldn't be an issue I think. I'll have to go back and check my implementation, but I think it went something like

`data-wb-calevt="year": <?php echo $curYear; ?>, "month": <?PHP echo $curMonth; ?>`

And the calendar always defaults to whatever curYear and curMonth is with or without events for that month.

I'm sure you could also write a select statement that'll return the current date from the database with or without an event entry if you wanted to go that route because your website isn't using something that integrates with HTML well.

**Comment by zomby22** [comment]
there was two solutions for me.
A. either write a future date in the database so that the calendar can browse future dates or 
B. write this for ASP code: `data-wb-calevt='{"year": <%=year(date())%>, "month": <%=DateAdd("m",-1, date())%>}'`
