### ISSUE TITLE
Date Picker Max

### ISSUE THREAD

**Issue by james-roach** [wet-boew/wet-boew#8122]
Hello,

I am having an issue trying to set the max date. 

The date picker works as intended when the max is set in the tag, but when it's set in the vb code only the months and years are greyed out. The days are still selectable.  

VB.NET (Months/Years are greyed but not days) : 
`enddate.Attributes("max") = "2017-08-01"`

ASPX code: (works as intended): 
`<asp:TextBox runat="server" class="form-control" type="date" ID="enddate" name="enddate" Max="2017-08-15"/> `

![datepicker](https://user-images.githubusercontent.com/31314984/29671012-650e65f4-88b6-11e7-83d1-e73e150c07d0.png)

**Comment by james-roach** [comment]
Not sure why but if the string setting the attribute is a date object first there is no issue  : 
```
Dim dateToday As Date = Date.Now
Dim strToday As String = datetoday.ToString("yyyy-MM-dd")
enddate.Attributes("max") = strToday
```

or simpler:

 `enddate.Attributes("max") = Date.Now.ToString("yyyy-MM-dd")`

the date picker works as intended.

**Comment by RobJohnston** [comment]
@james-roach :  I think you stumbled across a problem with the date picker that hasn't been reported before.  

The difference between your two examples is the day that was picked (the 1st or the 15th).  If I set a max date of the 15th, then it works as expected, but if I set a max date of the 1st of the month, then all days within that month are not greyed out.  I would expect every date from the 2nd onward to be disabled.

@LaurentGoderre , is this still your bailiwick?

**Comment by james-roach** [comment]
@RobJohnston: you are correct I was mistaken about the error. I must have been only testing the day being 01. 

I tried ` enddate.Attributes("max") = "2017-08-03"` and it worked fine.

So now I'm thinking that every month on the first, all days in the current month will be selectable.

**Comment by LaurentGoderre** [comment]
@RobJohnston sort of.... I'm really busy on other projects atm.
