### ISSUE TITLE
Input type="date" polyfill (date picker): Setting Max date doesn't work

### ISSUE THREAD

**Issue by TimCadieux** [wet-boew/wet-boew#8125]
Using the below code, I am attempting to set the Min date to 2010 and the Max date to Today.

Instead, it displays the last 100 years, see attachment plz.

```js
    $(document).on("wb-ready.wb-date", function (event) {
        var today = js.utils.Today();

        $("#searchdate").val(today);
        $("#searchdate").attr("Max", today);
        $("#searchdate").attr("Min", "2010-01-01");
    });
```
![untitled](https://user-images.githubusercontent.com/22413348/29839954-3b9861a4-8cce-11e7-88fc-6bcb19f23f4f.png)

```

**Comment by kodecount** [comment]
This was suppose to be resolved with v4.0.25 (#7342). Do you know I your on that version?

**Comment by TimCadieux** [comment]
I just checked and I'm on 4.0.24 so I'll give that a look, thx.

**Comment by TimCadieux** [comment]
Updating to the latest version DID fix this, thx.
