### ISSUE TITLE
Style guide - Forms - Control width - Error in documentation

### ISSUE THREAD

**Issue by agagnon** [wet-boew/wet-boew#8130]
http://wet-boew.github.io/wet-boew-styleguide/v4/design/forms-en.html

The Forms documentation says:
All textual <input>, <textarea>, and <select> elements with .form-control are set to width: 100%; by default.

It's not the case as the CSS is:
.form-control {
    max-width: 100%;
    width: auto;
}

Is there a way, a class to make a form control width 100% inside its parent div?

**Comment by RobJohnston** [comment]
Class="full-width"?

**Comment by agagnon** [comment]
Why didn't I think of that? I only thought of using it with images.

Still, the documentation about forms is confusing on that one.

Thanks.
