### ISSUE TITLE
Tabbed Interface: Determine which tab is open

### ISSUE THREAD

**Issue by TimCadieux** [wet-boew/wet-boew#8145]
After to page has loaded, how can I determine which Tab is open.

I have tried the below but strangely they all return true

var panel1 = ($("details-panel-panel1").attr("open")) ? true : false;
var panel2 = ($("details-panel-panel2").attr("open")) ? true : false;

**Comment by sgdowney** [comment]
I think you have to look at your tab list 
`<ul role="tablist">`
to find the `<li class="active">` item.

**Comment by TimCadieux** [comment]
forgot to update but got it working with

($('#details-panel-panel1').attr('aria-expanded') === "true") ? true : false;

**Comment by sgdowney** [comment]
It looks like you need to use `.prop("open")` instead of `.attr("open")`.
