### ISSUE TITLE
Subresource Integrity

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/wet-boew#8149]
Has anybody deployed using [Subresource Integrity](https://www.w3.org/TR/SRI/)?  

Is there any reason not to use it?  If not, should/could it be included by default in future releases?

It's [already part of Chrome and FireFox](http://caniuse.com/#search=subresource), and is in [preview status for Edge](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/subresourceintegrity/).

More info on [SRI on the MDN web docs](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity).

**Comment by LaurentGoderre** [comment]
It's already included! Packages now include a payload with the SRI checksums

**Comment by RobJohnston** [comment]
Ah, yes... I see it what you're talking about now in PR https://github.com/wet-boew/wet-boew/pull/7798. I expected to see it, for example, in the `<script>` tag that gets jQuery from googleapis in content-en.html.

**Comment by RobJohnston** [comment]
Exactly what is on the [CDTS page](http://www.gcpedia.gc.ca/wiki/Centrally_Deployed_Templates_Solution_(CDTS)/SRI) is what I expected to see:

**SRI values for jQuery files**
* jQuery 1.11.1 - `<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js" integrity="sha256-VAvG3sHdS5LqTT+5A/aeq/bZGa/Uj04xKxY8KM/w9EE= sha384-UM1JrZIpBwVf5jj9dTKVvGiiZPZTLVoq4sfdvIe9SBumsvCuv6AHDNtEiIb5h1kU sha512-nhY06wKras39lb9lRO76J4397CH1XpRSLfLJSftTeo3+q2vP7PaebILH9TqH+GRpnOhfAGjuYMVmVTOZJ+682w==" crossorigin="anonymous"></script>`
* jQuery 2.1.4 - `<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js" integrity="sha256-ImQvICV38LovIsvla2zykaCTdEh1Z801Y+DSop91wMU= sha384-8gBf6Y4YYq7Jx97PIqmTwLPin4hxIzQw5aDmUg/DDhul9fFpbbLcLh3nTIIDJKhx sha512-AFwxAkWdvxRd9qhYYp1qbeRZj6/iTNmJ2GFwcxsMOzwwTaRwz2a/2TX225Ebcj3whXte1WGQb38cXE5j7ZQw3g==" crossorigin="anonymous"></script>`

So I guess it is being used.
