### ISSUE TITLE
Equal height: How to dynamically append multiole <sections> to a <div and then Trigger the wb-eqht pugin

### ISSUE THREAD

**Issue by TimCadieux** [wet-boew/wet-boew#8155]
I need to loop through  a list and append Sections to a a Div that will eventually look like this [https://wet-boew.github.io/v4.0-ci/demos/equalheight/equalheight-en.html](url) however I have tried something like the below which of course did not work.

```
                    var $test = $("#simple");
                    $test.attr("wb-eqht");
                    $test.trigger("wb-init.wb-eqht");
```

Any pointers?

**Comment by sgdowney** [comment]
`wb-eqht` is a CSS class you need to add to the `div` elements within `<section id="simple">`.
You would have to select the `div` elements under `$test` and `.addClass("wb-eqht")`.

**Comment by TimCadieux** [comment]
I've tired doing this bu to no effect

> 
>     <div id="EqualHtDiv">
>         <section>
>             <h3>Short container</h3>
>             ...
>         </section>
>         <section>
>             <h3>Medium container</h3>
>             ...
>         </section>
>         <section>
>             <h3>Long container</h3>
>             ...
>         </section>
>     </div>
> 
>     $("#EqualHtDiv").addClass("wb-eqht");
> 
>     // Initialize the plugin.
>     $(".wb-eqht").trigger("wb-init.wb-eqht");

**Comment by sgdowney** [comment]
perhaps it should be 
`$("#EqualHtDiv").trigger("wb-init.wb-eqht");`
You may need to trigger once wet has finished loading:
```
$( document ).on( "wb-ready.wb", function( event ) {
     $("#EqualHtDiv").addClass("wb-eqht");
     $("#EqualHtDiv").trigger("wb-init.wb-eqht");
});

**Comment by TimCadieux** [comment]
That seems to have been it, thx
