### ISSUE TITLE
Is WET4 specifically married to UTF-8? 

### ISSUE THREAD

**Issue by johanley** [wet-boew/wet-boew#8168]
The context of my  question is that I'm using MS SqlServer 2014. That database doesn't support UTF-8 encoding. 

I'm aware of this :
"Departmental Web Managers, Functional Specialists, and equivalents are responsible for:
Ensuring that Web pages and Web feeds are encoded in UTF-8."
http://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=25875

But my question is specifically for WET4.

**Comment by LaurentGoderre** [comment]
WET is committed to UTF8 as the encoding is required for us to support all the languages we support.

**Comment by LaurentGoderre** [comment]
I just looked into it and you can use UTF8 with SQL Server but it's not as straightforward as other db.

**Comment by johanley** [comment]
Do you have a link demonstrating how to implement UTF-8 in SQL Server?

**Comment by LaurentGoderre** [comment]
There are several articles explaining that SQL Server supports Unicode and the client can be used to return UTF8 from the DB unicode data.

**Comment by johanley** [comment]
Do you have a link please? All I'm seeing is UCS-2...

**Comment by RobJohnston** [comment]
Description of storing UTF-8 data in SQL Server
https://support.microsoft.com/en-us/help/232580/description-of-storing-utf-8-data-in-sql-server

**Comment by RobJohnston** [comment]
I just did a quick test to see if I could put Chinese characters into a SQL Server database from a WET4 page.  No problems on a full Windows stack (ASP.Net 4 with C#) both reading and writing.  

If you're using PHP, you have to [specifiy the UTF-8 encoding with the PDO_SQLSRV drive](https://docs.microsoft.com/en-us/sql/connect/php/how-to-send-and-retrieve-utf-8-data-using-built-in-utf-8-support)r.

Just make sure that the datatypes in SQL are defined as nchar, nvarchar, or ntext and you should be fine..

**Comment by nschonni** [comment]
Just an aside, but it looks like the spec is also going to enforce UTF-8 in the future https://github.com/w3c/html/issues/1039

**Comment by johanley** [comment]
The answer is 'yes, wet is committed to utf-8.'
