### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by sarahblaze** [wet-boew/wet-boew#8170]
Hello,
I work at TBS, am not that technical, but am interested in cool things in the GC and curious about this. Anywhere I can read more / talk to someone?
Thanks!
Sarah

Sarah Bleiwas

Priorities Integration, Priorities and Planning / Intégration des priorités, Priorités et planification 
Treasury Board of Canada Secretariat / Secrétariat du Conseil du Trésor du Canada
sarah.bleiwas@tbs-sct.gc.ca  / (613) 790-3233

**Comment by duboisp** [comment]
@sarahblaze I invited you to our GCCollab group

:-)
