### ISSUE TITLE
Internal pages on the WxT Drupal wiki redirect infinitely

### ISSUE THREAD

**Issue by jameswilson** [wet-boew/wet-boew#8174]
Hi,  Was just checking out the Drupal integration of WET, and while the [homepage](http://wiki.drupalwxt.org/) loads fine, I found that if I click on any link to an internal page, it tries to redirect to itself.

Example link: http://wiki.drupalwxt.org/pages/roadmap

HTML returned:
```
<!DOCTYPE html>
<html>
	<head>
		<title>Road Map</title>
		<meta http-equiv="REFRESH" content="0;url=/pages/roadmap">
		<link rel="canonical" href="/pages/roadmap" />
	</head>
	<body>
		This page has moved. You will be automatically redirected to its new location. If you aren't forwarded to the new page, <a href="/pages/roadmap">click here</a>.
	</body>
</html>
```

**Comment by nschonni** [comment]
Hi, that's a different project. Maybe try reporting it to https://github.com/drupalwxt/wxt

/cc @sylus

**Comment by jameswilson** [comment]
Whoops, sorry.  I´ve re-reported it here: https://github.com/drupalwxt/wxt/issues/79 Thanks!
