### ISSUE TITLE
Carousel with Thumbnails issue: Thumbnails not appearing online

### ISSUE THREAD

**Issue by CCSA-CCDUS** [wet-boew/wet-boew#8183]
When I am editing my website locally (using XAMPP), my carousel and thumbnails look and function exactly as needed.

However, since I have added all my content to my website, everything looks the exact same except the thumbnails, panels that hold the thumbnails, play button, etc, do not appear.

Please see below.

![image](https://user-images.githubusercontent.com/32742654/32111399-6668fd2c-bb08-11e7-8583-fe273fc0d498.png)

![image](https://user-images.githubusercontent.com/32742654/32111410-71509ed4-bb08-11e7-9d50-846ba93c5fae.png)

Thanks!

**Comment by kodecount** [comment]
Are you seeing any console areas? Can you post any code?

**Comment by CCSA-CCDUS** [comment]
I've pasted the code from their demo code below, it's what I am using. I actually tried replacing the thumbnail viewer with a different carousel option, and no matter which one I use, the player controls (play, next, previous, etc.), never show up when added to the website. But locally, they work. 

<div class="wb-tabs carousel-s2  show-thumbs">
	<ul role="tablist">
		<li class="active"><a href="#panel30"><img src="img/protect-environment.jpg" alt="Tab 1: ..." /></a></li>
		<li><a href="#panel31"><img src="img/banff.jpg" alt="Tab 2: ..." /></a></li>
		...
	</ul>
	<div class="tabpanels">
		<div role="tabpanel" id="panel30" class="in fade">
			<figure>
				<img src="img/protect-environment.jpg" alt="" />
				<figcaption>
					<p>
						...
					</p>
				</figcaption>
			</figure>
		</div>
		<div role="tabpanel" id="panel31" class="out fade">
			<figure>
				<img src="img/banff.jpg" alt="" />
				<figcaption>
					<p>
						...
					</p>
				</figcaption>
			</figure>
		</div>
		...
	</div>
</div>

**Comment by kodecount** [comment]
Okay. I get that. How are you adding it to your site and is your site producing console errors?

**Comment by CCSA-CCDUS** [comment]
I am adding it through the file manager with canspace. And yes, some console errors but nothing associated with the carousel from what I see

**Comment by duboisp** [comment]
@CCSA-CCDUS the console error that you see may have a domino effect on the carrousel plugin. Are you able to solve them?

**Comment by CCSA-CCDUS** [comment]
I'm trying but have yet to solve them. I've also found out that when I scale to mobile view, the menu button to expand the mobile menu doesn't function either. But it does function when testing on a local server.

**Comment by duboisp** [comment]
@CCSA-CCDUS try to reset your browser zoom by pressing ```ctrl+0``` to see it that fix your issue

**Comment by CCSA-CCDUS** [comment]
@duboisp Thanks - but I'm referring to the inability to click the menu (see below). When I'm testing, the menu opens and closes - but when I'm online, it doesn't function. 

![image](https://user-images.githubusercontent.com/32742654/32236756-793a111e-be39-11e7-86ff-3d86b499bb32.png)

**Comment by duboisp** [comment]
Can you comments all the errors that you are seeing in the browser console?

**Comment by CCSA-CCDUS** [comment]
@duboisp 

![image](https://user-images.githubusercontent.com/32742654/32237448-5d068c00-be3b-11e7-9570-c94c36e167cc.png)

**Comment by duboisp** [comment]
Are you able to fix the following 404 error?
* wet-boew/js/i18n/en.min.js

**Comment by CCSA-CCDUS** [comment]
@duboisp any suggestions as per how? I have it referenced in my <scripts>.. I've been having issues fixing any of the "failed to load resource" errors

**Comment by CCSA-CCDUS** [comment]
I can acknowledge I made a mistake in my folder structure in my control panel - which has been fixed, which fixed my console errors, which fixed everything. Thanks @duboisp
