### ISSUE TITLE
How to center the menu

### ISSUE THREAD

**Issue by CCSA-CCDUS** [wet-boew/wet-boew#8184]
I am using the default WET Theme, and wondering how to center, or adjust the menu / navigation bar? I am having issues moving it away from the left alignment. 

Ideally, I would have the four menu options reach from one side of the container to the other. Please see the image/red lines. 

Thanks!

![image](https://user-images.githubusercontent.com/32742654/32121256-e3db0342-bb29-11e7-9c1f-fefe1fac5fcb.png)

**Comment by kodecount** [comment]
You can do something like:
<img width="1440" alt="screen shot 2017-10-30 at 11 34 02 am" src="https://user-images.githubusercontent.com/23484460/32179758-8df41f9c-bd66-11e7-8b4c-e3defb2e9916.png">
<img width="446" alt="screen shot 2017-10-30 at 11 34 15 am" src="https://user-images.githubusercontent.com/23484460/32179760-8f6cae48-bd66-11e7-8b68-65885c9e6c21.png">

**Comment by CCSA-CCDUS** [comment]
Awesome. I will try this, thank you

**Comment by CCSA-CCDUS** [comment]
Hi, would you be able to be more specific on your code for this? Could you post more please?

**Comment by EricDunsworth** [comment]
@CCSA-CCDUS The [CGWeb theme](http://wet-boew.github.io/themes-dist/GCWeb/index-en.html) already does what you described in the OP. It's designed to make all of the mega menu's items scale to use the mega menu bar's full width.

Here's an excerpt of relevant SCSS selectors from [wet-boew/GCWeb/blob/master/src/menu/_base.scss](https://github.com/wet-boew/GCWeb/blob/master/src/menu/_base.scss):
```
#wb-sm {
	.menu {
		display: table;
		width: 100%;

		> {
			li {
				display: table-cell;
				float: none;
			}
		}
	}
```

**Comment by CCSA-CCDUS** [comment]
This worked @EricDunsworth thanks
