### ISSUE TITLE
Line break, or new line in a table cell in WET 4

### ISSUE THREAD

**Issue by d02wang** [wet-boew/wet-boew#8186]
In a content of column in db table, there are some newlines (char, say, \n), content with multiple lines. It can be displayed appropriately in textarea. 
If it is displayed in a table cell, it does not show the multiple lines. It only shows a single line in the table cell (that is, the new line disappears or it is ignored).

If I convert the new line \n with line break \<br\> or \<br\/\> in controller, the cell display the string \<br\> or \<br\/\> for \n in WET 4 table cell. 
 

This conversion works for tables in a pure html file and it also works for WET 3 table, but not for WET 4 table in our jsp file (see attached screen). The table attributes are set as follows:
<table id="siteSearchResultTable" class="wb-tables table table-striped table-bordered table-hover">
        <caption class="wb-inv"> <spring:message code="thcd.list.search.results" /></caption>

What should I do to make it work?

![wet4tablecelllinebreakissue](https://user-images.githubusercontent.com/17907221/32177063-a864d9e0-bd5f-11e7-907d-d81dcb6ed38e.jpg)

Thank you very much

David

**Comment by kodecount** [comment]
We might have to see some code, but my guess would be is the way your adding the information to the page (and updating '\n' to '<br>') is being taken as a literal string and not HTML.

**Comment by kodecount** [comment]
What I'm saying is `<br>` should work, but how ever your adding it to the page is not being seen as HTML, but as a string.

**Comment by duboisp** [comment]
@d02wang as @kodecount said, If you see textual ```<br />``` it look like that your are replacing the node text and not the node innerHTML. Is it server side or client side replacement?

> Question is: what should I replace new line char \n in the content to show the content in the cell appropriately (as original multiple lines)?

It depends of the meaning of the ```\n``` character in your content. Is it to delimit the end of a list item? Is it to delimit the end of a paragraph? 
Can you end up with double consecutive ```<br />```? If so that might means you are using ```<br />``` for styling which could fail WCAG 2.0 https://www.w3.org/TR/WCAG20-TECHS/F2.html

**Comment by d02wang** [comment]
Thanks for your comments. Now I find a solution. Put html tag <pre> for the content. It will keep all white spaces and new lines.
