### ISSUE TITLE
Table column sizing inside details element does not work

### ISSUE THREAD

**Issue by ciclerou** [wet-boew/wet-boew#8189]
I have a table inside a details element and I am trying to adjust the widths of the columns, but the classes do not have an effect.
If I put the table outside of the details element, the column width works.
Am I doing something wrong or is there a fix?

I am using the following html with v4.0.27:
```
 <details>
 	    <summary>View current positions flagged for conversion with job number</summary>
        <div class="table-responsive">
 		    <table id="conversionPositions" class="wb-tables table table-striped table-hover">	
	    	        <thead>
 		            <tr>
 		                <th scope="col" class="col-md-1">Position number<br/></th>
 		                <th scope="col" class="col-md-1">Occupational group<br/></th>
 		                <th scope="col" class="col-md-1">Classification<br/></th>
 		                <th scope="col" class="col-md-5">Position title<br/></th>
 		                <th scope="col" class="col-md-4">Conversion status<br/></th>
 		            </tr>
 		        </thead>
 		        <tbody>
                               ...
 		        </tbody>
 		    </table>  
 		</div>
</details>
```

**Comment by duboisp** [comment]
The CSS class ```col-*``` must be in a parent element that have the class ```row```. See: https://github.com/twbs/bootlint/wiki/E014

Side note: adding the scope attribute with the value ```col``` to the ```<th>``` elements is not needed for a simple table. However, the ending ```<br />``` seems to be used only for style by adding more spacing which fail https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/F43

**Comment by ciclerou** [comment]
I am using the col class in a table (not a div) and I am following the WET example:
http://wet-boew.github.io/wet-boew-styleguide/v4/design/tables-en.html#width

Although scope is not required, we use it in our tables and it is applied in the WET example.

The <br /> is to move the arrows down and it doesn't fail.

So I am still looking for an answer to my question.

**Comment by duboisp** [comment]
@ciclerou after tested, I remark that is the data table feature that are causing you the issue. May be the data table feature (```wb-tables```) require some special configuration for the column sizing. You can take a look here: https://datatables.net/reference/api/

**Comment by ciclerou** [comment]
@duboisp - As I mentioned in my original comment, if I put the div and the table outside of the the details element, there is no issue.  The issue only occurs when I put the table inside a details element.

So I am still looking for an answer to my question.

**Comment by duboisp** [comment]
It's look like that the datatable plugin overwrite the column width, but because it is inside a details/summary it can't calculate the appropriate width.

But there is a datatable configuration that you can use: see: https://datatables.net/reference/option/columns.width

**Comment by ciclerou** [comment]
I found a temporary fix by adding the col class on td cells of the first table row, but it should work on the th row.  When a fix is implemented in WET for the th element in the datables when inside a details element, let me know.
