### ISSUE TITLE
Overlay Plugin - How can I listen for the the overlayClose event?

### ISSUE THREAD

**Issue by aaornrylow** [wet-boew/wet-boew#8191]
I need to trigger some functionality for when an overlay is closed by any means (whether by clicking the header X, footer close button, or by blurring).

**Comment by aaornrylow** [comment]
Feels like a bit of a hack, but this seems to work:
`	$(document).on("click vclick", function() {
		if (!$("#right-panel").hasClass("open"))
		{
			//Do Stuff
		}
	});`

**Comment by duboisp** [comment]
Overlay or lightbox?

For overlay there is a close event that you can hook on ```close.wb-overlay``` See the docs: http://wet-boew.github.io/wet-boew/docs/ref/overlay/overlay-en.html

For lightbox there is also a close event that you can hook on
```
$( ".wb-lbx" ).on( "mfpClose", function( event ) {
	var src = $.magnificPopup.instance.items[ 0 ].src;
	
	if ( src === "#inline_content" ) {
	} else if ( src === "demo/1_b.jpg" ) {
	}
});
```
see the docs here: http://wet-boew.github.io/wet-boew/docs/ref/lightbox/lightbox-en.html

**Comment by aaornrylow** [comment]
I'm using a right-panel overlay. But I want the functionality to be triggered by the close event, not to trigger the event itself.


$("#right-panel").on("close.wb-overlay", function(){
alert("hit");
});

The above code doesn't work... Did I do something incorrectly here?



Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by duboisp** [comment]
Try this

```
wb.doc.on( "close.wb-overlay", ".wb-overlay", function( event ) {
   alert("hit");
});
```

**Comment by aaornrylow** [comment]
No luck. The alert doesn't fire on close.


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by aaornrylow** [comment]
Reopened the issue because my hacky solution from above doesn't work in mobile if you tap to blur (no document on click event fires).

**Comment by duboisp** [comment]
After looking closer to the overlay code, there is no event that is trigger when a user close the overlay.

So to support it, it will require PR that will add a one line of code to trigger an event when the ```closeOverlay``` function is called ( https://github.com/wet-boew/wet-boew/blob/master/src/plugins/overlay/overlay.js#L142 )

**Comment by aaornrylow** [comment]
Should I submit a PR myself then? Sorry, I don't have a lot of Github experience... I don't know where to start.

Can you please advise?


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by duboisp** [comment]
@aaornrylow it will be faster if you submit a PR and if it is sent this week then it could be included in the next release.

Here some documentations: http://wet-boew.github.io/wet-boew/docs/start-en.html#develop

**Comment by danieledevito** [comment]
Was this fixed?

**Comment by danieledevito** [comment]
Also how is this a feature request? It lacks a trigger call when all others have it (I assume)?

**Comment by duboisp** [comment]
@danieledevito it will be fixed after PR #8594 would be merged probably at the next technical review weekly meeting. It should be packaged in the next minor version of WET-BOEW v4.0.31.

And this is a feature request because that is a new functionality and not about an existing functionality.

**Comment by danieledevito** [comment]
@duboisp sorry in the documentation it is listed that it calls it on close. 

https://wet-boew.github.io/v4.0-ci/docs/ref/overlay/overlay-en.html

**Comment by duboisp** [comment]
You can call (trigger) that event to close the windows via javascript, but that event aren't fired when the user close the overlay. That is also how it is documented "Used to manually close an overlay".

**Comment by danieledevito** [comment]
@duboisp my apologizes, you are right. I guess it being listed under events and the others triggered automatically I assumed it was a 2 ways street for each event. Cheers.
