### ISSUE TITLE
wb-tables table - initial view

### ISSUE THREAD

**Issue by MarcButeau** [wet-boew/wet-boew#8194]
I'm using "wb-tables table" from this page...
[http://wet-boew.github.io/v4.0-ci/demos/tables/tables-en.html](url)

I would like to know if it possible to configure the initial view when the webpage is loading up?
I would like the webpage to initially show 50 entries instead of 10 and also have the first column sort in descending order.

Please help.

Thanks.

**Comment by duboisp** [comment]
Here the configuration sample that will show 50 rows per page and sort the first column in descending order.

```
<table class="wb-tables table" data-wb-tables='{ "pageLength": 50, "order": [ 0, "desc"] }'>
```

You can see all the available configuration here: https://www.datatables.net/reference/option/

Cheers

:-)

**Comment by MarcButeau** [comment]
This is 100% exactly what I needed.
Worked like a charm.

Thank you very much.
