### ISSUE TITLE
Expand/Collapse IE issue in V 4.0.26

### ISSUE THREAD

**Issue by Deepgee** [wet-boew/wet-boew#8211]
Hi,

We recently upgraded our Framework to version 4.0.26 from version 4.0.23, we've noticed that the Expand/Collapse feature stopped working in IE (we are using IE 11), it is working Chrome and Firefox. Prior to our upgrade, it was working correctly.

http://international.gc.ca/world-monde/stories-histoires/test.aspx?lang=eng

We have looked at the WET4 working examples for the coding for this but can't tell what framework version it is using.

http://wet-boew.github.io/wet-boew/demos/details/details-en.html

Any thoughts on what could be wrong? Is there something wrong with our coding? Or is there something broken in the framework for this version?

**Comment by sgdowney** [comment]
When I load the page in IE there are 3 console errors.  When I view the details.min.js content it contains html content instead of javascript.

**Comment by sgdowney** [comment]
You may need to check that the js files are in the polyfills folder under theme-gcweb/js/polyfills.

**Comment by RobJohnston** [comment]
@Deepgee FYI, you can tell the version that the examples are using by viewing the source and loading either a WET css or WET js file.  The version number will be at the top.  

It currently says, "v4.0.27-development - 2017-11-23".

**Comment by Deepgee** [comment]
@RobJohnston Thanks, I'll be sure to check that next time.

@sgdowney Thanks, I've past this on to our CMS team to look into.

**Comment by duboisp** [comment]
@Deepgee your server return an HTML "Page not found" for those 3 files with an HTTP status 200. Ensure those file is copied on your production environment and fix your server to return 404 HTTP status when a file is not found.

Cheers
