### ISSUE TITLE
Feature: Please provide modular and standalone polyfills and modules on NPM

### ISSUE THREAD

**Issue by hdpinto** [wet-boew/wet-boew#8220]
We can't (and shouldn't have to) download a monolith of a project for a single polyfill or module that we want to use, and having dependencies on .hbs and jquery means we can't just pull and use what we want from the source.

These utilities are extremely useful, but inaccessible.

**Comment by LaurentGoderre** [comment]
BTW, there is not dependency on `.hbs`. Those are only use for the static site generator.

**Comment by LaurentGoderre** [comment]
I would also point out that in the context of this project, Accessibility refers to Inclusive Design so The utilities are accessible but in your opinion are hard to integrate.

**Comment by nschonni** [comment]
@hdpinto I know it's old, but we're (still) tracking this under #6008
