### ISSUE TITLE
How to Disable 'Standard Version'/'Basic HTML version' links at top of page

### ISSUE THREAD

**Issue by segnosaur** [wet-boew/wet-boew#8227]
Forgive me for what may be a simple question....

I am currently working on applying WET 4 templates (CDTS) to an existing application. (The previous application had used WET 3.)

Currently, when I run the application (either through Microsoft Visual Studio or a web application, there is a link at the top of the screen with either 'Basic HTML version' or 'Standard Version'. This will toggle back and fourth when you click on it (with the format of the page changing.)

What I would like to know is: How can I suppress this link so that it shouldn't show up (preferrably having it default to 'Basic'.)

Application details: 
- Language: c#, with .net 4.0 framework

Note: I have found some references in this repository to the 'wbdisable' parameter, but I don't like the affect that it has on the web page.

![basic_html_version](https://user-images.githubusercontent.com/34283466/33626738-7bebda68-d9c9-11e7-98fb-37f7fa5c3a57.png)

**Comment by kodecount** [comment]
The links should be hidden when in the normal view. Personally don't recommend removing as it a mode meant for older screen reader (or when current ones are having issue with some javascript functions).

**Comment by EricDunsworth** [comment]
@segnosaur I'd recommend against hardcoding the "Basic HTML version" link in your page template's HTML code.

From my understanding, the purpose of that link is to is to allow a user to disable all of WET's JavaScript enhancements (such as plugins, polyfills, etc...) to work around potential scripting issues and/or incompatibilities with assistive technology (such as screen readers). It's not meant to be hardcoded into pages.

When JavaScript is enabled in a browser, WET will automatically append the "Basic HTML version" link to the list of bypass blocks at the start of the page. The bypass block links are visually-hidden by default, but can be individually unveiled via keyboard tabbing. Screen readers will also announce them. In practice, basic HTML mode is likely to be functionally identical to viewing a WET page in a browser that has JavaScript disabled.

Related comments:

* https://github.com/wet-boew/wet-boew/issues/7686#issuecomment-257663227
* https://github.com/wet-boew/wet-boew/issues/7686#issuecomment-257676001

CC @rlambert27

**Comment by segnosaur** [comment]
I understand why they have the Basic/Standard HTML links.

The problem is, this is an older application. It doesn't benefit from any of the WET4 enhancements, and when those enhancements are active it severely affects the layout of the page.  And rewriting the page will be a significant time investment which provides no benefit. (Not to mention the fact that many of the users will be confused by the 'Basic/Standard HTML' links.)

**Comment by nschonni** [comment]
This isn't something that would be supported by the core toolkit. You can check with on the CDTS GCcode tracker to see if they have an option for that.
