### ISSUE TITLE
Datatables saveState not properly applied after async refresh of data

### ISSUE THREAD

**Issue by GarthMartin** [wet-boew/wet-boew#8234]
We are initializing a datatable using the following:
`<table class="wb-tables table table-striped" data-wb-tables='{"columns" : [null, null, null, null, null, {"orderable": false,"searchable": false}], "stateSave": "true", "stateDuration": "0"}'>`

Each row has a button that does an ajax post to the server to action the selected row in some way.  The target of the ajax method is an MVC partial view that refreshes the table in question, and re-inits the datatable using `wb-init.wb-tables`

If I change the number of rows in the table from 10 to 25 and then action a row, when the table reloads it is back at the original number of displayed rows.  If I refresh the entire page (or navigate away and return to the page), then the table is displayed as expected with 25 rows shown.

I have tried destroying the table before re-initializing it but that does not resolve the problem.

Any ideas on what may be causing this to not reload properly on the async load?

Thanks,

Garth

**Comment by duboisp** [comment]
@GarthMartin to summarize

1. You have an initial data set
1. That data set is mapped into a data table
2. An user initialize an action - Selecting a row in the data table
3. The information about the row selected is sent to the server through an API call (AJAX)
4. The server return a set of new rows to add to the data set or a new data set.
5. The data table need to be re-draw with the modified data set.

Is that correct?
Can you confirm at step 4 if is it new row that will be added or is it a completely new data set?

----
**Aside:** I am curious on how you handle the risk of having the "Change of context" accessibility issue [SC 3.2.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/consistent-behavior-unpredictable-change.html)? Can you provide more information about how your UI is designed?

**Comment by GarthMartin** [comment]
@duboisp Here is how we are using this:
1. MVC controller loads data from database
2. Partial view renders data into HTML table with wb-tables class as in original post
3. User initiates action on row (button click)
4. Information sent to server via AJAX
5. Controller does it's job and reload the updated data from database 
6. Controller returns the partial view rendered as HTML and we trigger("wb-init.wb-tables") which should re-initialize the table

We are not returning JSON as the source of the table in this scenario.

As for the change of context issue, this is in a form and has been vetted by our accessibility team.

Thanks.

**Comment by duboisp** [comment]
What are you using to render the partial views? React? Vanilla JS?

**Comment by GarthMartin** [comment]
It's MVC.Net - razor engine.

**Comment by duboisp** [comment]
Ok, .net razor engine should not interfere here as it is seems to be fully server side. 

So
What is the javascript code that handle the Ajax response? How do you replace the Dom? Are you using the data table API to change the displayed data?

**Comment by GarthMartin** [comment]
Our framework takes the HTML returned by the view and replaces the html in the target div with the table html source `$(trgt).html(response);` where trgt is the div name.  We then trigger("wb-init.wb-tables")  on the trgt div to re-initialize the datatable.

The partial view looks like this:
`

@{ Html.RenderPartial("Validation/_ValidationSummary", Model); }

@using (Html.BeginForm("Index", "Organization", FormMethod.Post, new { @id = "organization" }))
{
    @Html.AntiForgeryToken()

    <div class="table-responsive">
        <table class="wb-tables table table-striped" data-wb-tables='{"columns" : [null, null, null, null, null, {"orderable": false,"searchable": false}], "conditionalPaging": true}'>
                <thead>
                    <tr>
                        <th scope="col">@Localization.Admin_Organization_Name_col_Header</th>
                        <th scope="col">@Localization.Admin_Organization_Acronym_col_Header</th>
                        <th scope="col">@Localization.Admin_Organization_PAScode_col_Header</th>
                        <th scope="col">@Localization.Admin_Organization_Size_col_Header</th>
                        <th scope="col">@Localization.Admin_Organization_StatusForRound_col_Header</th>
                        <th scope="col">@Localization.Admin_Organization_Actions_col_Header</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.Organizations.Count; i++)
                    {
                        <tr class="maf-form-container">
                            <td>@Html.DisplayFor(m => Model.Organizations[i].Organization_Name)</td>
                            <td>@Html.DisplayFor(m => Model.Organizations[i].Organization_Acronym)</td>
                            <td>@Html.DisplayFor(m => Model.Organizations[i].Organization_Code)</td>
                            <td>@LookupTablesService.GetName(LookupTableEnum.OrganizationSizeType, Model.Organizations[i].Organization_Size_Type_Id)</td>
                            <td>@if (Model.Organizations[i].Organization_Round_Management_Id == (int?)null)
                            { @Localization.Inactive}
                            else
                            { @Localization.Active}</td>
                            <td class="nowrap">
                                @* View Button *@
                                @Html.WetViewLinkButton("ViewOrganization", "Organization", new { organizationId = Model.Organizations[i].Organization_Id }, new { @class = "btn btn-default btn-xs" })
                                @* Activate/Deactivate Button *@
                                @Html.WetActivateDeactivateButtonAsync("ActivateDeactivateOrganization", "Organization", MAF_CRG.Common.Enums.AsyncActionResponseTypes.html, "#organizationList-content", Model.Organizations[i].Organization_Round_Management_Id != null, new { roundId = Model.RoundId, organizationId = Model.Organizations[i].Organization_Id }, new { @class = "btn btn-default btn-xs" }, (Model.Organizations[i].Organization_Round_Management_Id != null ? Model.InactivateOrganizationModal : Model.ActivateOrganizationModal))
                            </td>
                            
                        </tr>
                    }
                </tbody>
            </table>
    </div>
}`

**Comment by duboisp** [comment]
You need to ```trigger("wb-init.wb-tables")``` on the ```table``` element not on the ```div```

**Comment by GarthMartin** [comment]
Sorry, it's a generic re-init that triggers the action on all $(".wb-tables") in the target div...

**Comment by duboisp** [comment]
Can you try with a jQuery selector that is more specific? May be the "generic" are conflicting with other pieces of your web page. Like re-init a data table that was already initiated.

Did your get any browser console errors?

For a generic re-init, you can give a try with jQuery selector like: ```$(".wb-tables:not(.wb-tables-inited)").trigger( "wb-init.wb-tables" );```

**Comment by GarthMartin** [comment]
It's already pretty specific.  We have a certain implementation that we don't want re-inited so our jQuery is the following:
` $(".wb-tables:not(table.maf-search-results-table.wb-tables)", trgt).trigger("wb-init.wb-tables");`

There is only one instance where we have more than one datatable on a page, but this is not the page I am dealing with, so not sure that would have anything to do with it.
Would there be anything with the order we do the re-init in? Currently we have the following:

` // WET buttons.
$(".wb-toggle", trgt).trigger("wb-init.wb-toggle");
// WET datatables.
$(".wb-tables:not(table.maf-search-results-table.wb-tables)", trgt).trigger("wb-init.wb-tables");
// WET form validation.
$(".wb-frmvld", trgt).trigger("wb-init.wb-frmvld");
// WET lightbox/modal popups.
$(".wb-lbx", trgt).trigger("wb-init.wb-lbx");
// WET summary/details.
$("summary", trgt).trigger("wb-init.wb-details");
// WET tabs
$(".wb-tabs", trgt).trigger("wb-init.wb-tabs");`

**Comment by GarthMartin** [comment]
@duboisp  Thanks for you help Pierre.  We have resolved the issue.  I had not realized that we were not assigning an ID to the table which was causing a new ID to be generated each time the AJAX call completed and the table was re-inited.

**Comment by duboisp** [comment]
@GarthMartin here a line of code that you can use to trigger WET on newly inserted content. It should catch all wet-boew features.

```
( function( $, document, wb ) {
"use strict";
var updtElm = document.getElementById("id");
$( updtElm )
	.find( wb.allSelectors )
		.addClass( "wb-init" )
		.filter( ":not(#" + updtElm.id + " .wb-init .wb-init)" )
			.trigger( "timerpoke.wb" );
} )( jQuery, document, wb );
```

**Comment by GarthMartin** [comment]
@duboisp  thanks.  In `var updtElm = document.getElementById("id");` is "id" the container I want to look for new content in?

**Comment by duboisp** [comment]
For example:

HTML
```xml
<section>
   <h2>Title</h2>
   <div id="abc123">
      <p>This is the inner container where its content would be replaced</p>
   </div>
</section>
```

Then you will have configured that line like:
```js
var updtElm = document.getElementById("abc123");
```

Here more info about ```.getElementById(id)``` function.
* Specification: https://www.w3.org/TR/dom/#interface-nonelementparentnode
* Examples: https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById

**Comment by GarthMartin** [comment]
Thanks I am familiar with getElementById....I just wanted to confirm that this was not going to interate over the entire DOM looking for non-inited content, but be restricted to the element I know contains new content.

**Comment by duboisp** [comment]
Yes, it will be restricted to the specified element.

That is the code I used for [URL Mapping](http://wet-boew.github.io/themes-dist/GCWeb/demos/urlmapping/urlmapping-doc-en.html), [fieldflow](http://wet-boew.github.io/themes-dist/GCWeb/demos/fieldflow/fieldflow-doc-en.html) and [doAction](http://wet-boew.github.io/themes-dist/GCWeb/demos/doaction/doaction-doc-en.html) plugin that can insert content through an ajax call and then trigger WET if specified.

See an example here: http://wet-boew.github.io/themes-dist/GCWeb/demos/urlmapping/ajax-en.html?ajxload=5special
