### ISSUE TITLE
Drupal Grids

### ISSUE THREAD

**Issue by AlexCreamer** [wet-boew/wet-boew#8246]
Hi, I read I could come here with questions. 
I'm using Drupal 7 with the Drupal distribution, https://www.drupal.org/project/wetkit, and I was wondering how to make grids. I have the following grid, http://alexcreamer.org/?q=en/content/grid-example, but it looks I'm doing something wrong since I'm not getting any grids.

**Comment by nschonni** [comment]
Hi, the issue tracker for the Drupal variant is here https://github.com/wet-boew/wet-boew-drupal
I'm not sure if the development has all moved to Drupal 8 development in https://github.com/drupalwxt/wxt

**Comment by AlexCreamer** [comment]
Thanks. :)
