### ISSUE TITLE
Reapply - Bower to npm #8147

### ISSUE THREAD

**Issue by duboisp** [wet-boew/wet-boew#8247]
The PR #8147 was reverted because it broke the build in various wet-boew theme such as GCWeb.

The goal is to reapply all the commits bundled with PR #8147 but without breaking the theme build. 

---

@EricDunsworth [wrote](https://github.com/wet-boew/wet-boew/pull/8147#issuecomment-356110153):
> @duboisp @lucas-hay Are there any plans to re-implement this PR's changes (since #8228 reverted it)?
>
>I personally would've preferred quick-fixing the other themes rather than reverting this PR. The changes it brought in were valid and didn't break this repo's build system.
>
>IMO it would've been more ideal to fix the other themes' build systems - even if it resulted in 4.0.27 getting further delayed. Plus in the end, due to other issues, 4.0.27 didn't end up getting released until over a week after #8228 was merged in.

@duboisp [wrote](https://github.com/wet-boew/wet-boew/pull/8147#issuecomment-356140011):
> @EricDunsworth The first thing will be to have all those PR's ready to be merge. Then, after testing, we would be able to merge it and re-apply the change from this PR.
> 
> Feel free to submit all those related PR's then it can be merged all at once during a "PR review" meeting.

**Comment by nschonni** [comment]
Fixed in #8253
