### ISSUE TITLE
Bootlint fails to lint MathJax Docs

### ISSUE THREAD

**Issue by Empereol** [wet-boew/wet-boew#8250]
Regarding PR #8101:

When `bootlint` gets run from the `Gruntfile.coffee`, it fails on the HTML files copied over from MathJax docs. I suspect these files aren't even required and could be removed to easily resolve this issue.

[My initial comment](https://github.com/wet-boew/wet-boew/pull/8101/files?diff=unified#r160799540)

**Comment by EricDunsworth** [comment]
Looks like #8280 addressed this.
