### ISSUE TITLE
"Zebra Stripping" (typo)

### ISSUE THREAD

**Issue by jkshapiro** [wet-boew/wet-boew#8259]
Hi there,

On the page http://wet-boew.github.io/v4.0-ci/docs/ref/zebra/zebra-en.html, the word "stripping" should be "striping" throughout, including the <title>.

As exotic as "zebra stripping" sounds, that is not what this plugin does. :-)

**Comment by thekodester** [comment]
This reminds me of https://github.com/wet-boew/wet-boew/pull/7463 when an example linked to nude images. Thanks for the laugh. 😂

**Comment by nschonni** [comment]
Thanks @jkshapiro do you want to make the pull request yourself?

**Comment by jkshapiro** [comment]
Sure thing. https://github.com/wet-boew/wet-boew/pull/8262
