### ISSUE TITLE
Other possible libs that are WET compliant?

### ISSUE THREAD

**Issue by sgaawc** [wet-boew/wet-boew#8264]
Is [Vaadin Elements](https://vaadin.com/elements/browse) (using [Polymer 2](https://www.polymer-project.org/2.0/docs/about_20)) or [Angular Material](https://material.angular.io/components/categories) elements are WET compliant? 

Just to double-check with the repo authors.

**Comment by LaurentGoderre** [comment]
We rely on Bootstrap so using those other two is likely to result in conflicts
