### ISSUE TITLE
Datalist polyfill (auto-complete): working example not working 

### ISSUE THREAD

**Issue by SBleeks** [wet-boew/wet-boew#8265]
The working example does not populate a list of matches. is it broken?

**Comment by RobJohnston** [comment]
Are you talking about this page:  http://wet-boew.github.io/wet-boew/demos/datalist/datalist-en.html?

No problem seen here.  I type "chi" and see "Chibougamau" and "Chilliwack" in IE, and the addition of "Miramichi" in Chrome.

**Comment by SBleeks** [comment]
Yes, I am using IE11 and the auto complete functionality is not happening.

**Comment by RobJohnston** [comment]
Datalists in IE11 may be buggy:  https://caniuse.com/#feat=datalist

**Comment by SBleeks** [comment]
For the moment, IE11 is still the GoC standard browser.

**Comment by nschonni** [comment]
Polyfills only load when a browser doesn't support a feature. In this case IE11 does support it (although with bugs). I believe this might have been raised before with some other discussion if you're interested.

**Comment by RobJohnston** [comment]
Probably referring to here:  https://github.com/wet-boew/wet-boew/issues/7157

**Comment by duboisp** [comment]
@nschonni Can something be done to fix the poor implementation of datalist in IE11

**Comment by zomby22** [comment]
RobJohnson: quote"the addition of "Miramichi" in Chrome". Can this work in IE? cause currently its only working in Chrome.
Keywords shouldn't just be the first letter of a word or sentence, it should match any words in a sentence base on the search results. Ex. if I type "member" and the word found is "this is member1; this is member 2; the last member of the..."
There is also a dynamic autocomplete for any input results, but I dont understand it, maybe someone can write an example with some ASP code.

**Comment by RobJohnston** [comment]
@zomby22 I believe that different browsers implement it in different ways and that's why "Miramichi" may or may not show.
