### ISSUE TITLE
Datalist - IE11 - No scroll bar

### ISSUE THREAD

**Issue by kawish7** [wet-boew/wet-boew#8273]
On IE11, when we have some items in the [Datalist polyfill (auto-complete)](wet-boew.github.io/v4.0-ci/demos/datalist/datalist-en.html) there is no scroll bar like Firefox.

**Comment by thekodester** [comment]
IE11 doesn't use WET polypill since it supports datalist internally.

**Comment by nschonni** [comment]
As @thekodester mentioned Datalist is a native element in IE11, so there is no WET involvement
