### ISSUE TITLE
All of WET 4.0's logo SVGs are implemented in a manner that fails HTML validation

### ISSUE THREAD

**Issue by EricDunsworth** [wet-boew/wet-boew#8276]
A few days ago, validator/validator#422 was resolved. One of the commits that fixed it (validator/validator@1c02bc18e7a71d531fcd62e60b4dc2064c753cef) intentionally caused any elements containing ``tabindex`` attributes to trigger a validation error when situated within ``<a>``/``<button>`` elements.

Based on my research, validator/validator@1c02bc18e7a71d531fcd62e60b4dc2064c753cef's behaviour is in line with the [W3C's HTML spec](https://w3c.github.io/html/):

* Excerpt from the [spec's tabindex section](https://w3c.github.io/html/editing.html#element-attrdef-global-tabindex):
  * "An element with the [tabindex](https://w3c.github.io/html/editing.html#element-attrdef-global-tabindex) attribute specified is [interactive content](https://w3c.github.io/html/dom.html#interactive-content-2)."
* Excerpt from the [spec's interactive content section](https://w3c.github.io/html/dom.html#interactive-content-2):
  * "The [tabindex](https://w3c.github.io/html/editing.html#element-attrdef-global-tabindex) attribute can also make any element into [interactive content](https://w3c.github.io/html/dom.html#interactive-content-2)."
* Excerpt from the [spec's content model section for the ``a`` element](https://w3c.github.io/html/textlevel-semantics.html#elementdef-a):
  * "[**Content model**](https://w3c.github.io/html/dom.html#content-model): [Transparent](https://w3c.github.io/html/dom.html#transparent), but there must be no [interactive content](https://w3c.github.io/html/dom.html#interactive-content-2) or [<a>](https://w3c.github.io/html/textlevel-semantics.html#elementdef-a) element descendants."

So, what does this have to do with WET? It turns out that most of WET 4.0's themes use SVG site logos that are structured as links containing an ``<object>`` element with a ``tabindex="-1"`` attribute. In other words, WET is nesting interactive content (``<object tabindex="-1">``) within other interactive content (``<a>``), which goes against the HTML spec.

As a result, the following error is now appearing when [validating virtually any pages that use WET](https://validator.w3.org/nu/?doc=http%3A%2F%2Fwet-boew.github.io%2Fv4.0-ci%2Findex-en.html):
> **Error:** An element with the attribute tabindex must not appear as a descendant of the ``<a>`` element.
> 
> From line 61, column 1; to line 61, column 83
> 
> ``<object type="image/svg+xml" tabindex="-1" data="./theme-wet-boew/assets/logo.svg">``

IMO the best way of fixing this would be to replace the ``<object>`` element with ``<img>`` in WET's SVG images and remove the ``tabindex="-1"`` attributes. I believe it should work fine in all modern browsers and retain compatibility with the [SVG image replacer polyfill](https://github.com/wet-boew/wet-boew/blob/master/src/polyfills/svg/svg.js).

@duboisp @LaurentGoderre @nschonni @pjackson28 @shawnthompson Any thoughts/concerns?

**PS:**
The reason a ``tabindex="-1"`` attribute was used on SVG ``<object>`` elements in the first place was because of #1432 (which was fixed by wet-boew/wet-boew-legacy@cc8b81c27b92dc1b2caded92d5503f151393497f). Without that attribute, all browsers attempt to set keyboard tabbing focus inside the ``<object>`` element - which isn't desirable.

**Comment by duboisp** [comment]
@EricDunsworth great, thank for the background.

Do you know what browser required to load SVG via an ```object``` element?

**Comment by EricDunsworth** [comment]
@duboisp Based on https://stackoverflow.com/questions/4476526/do-i-use-img-object-or-embed-for-svg-files, it seems like several years ago, browser support for SVGs referenced within``<img>`` elements was somewhat inconsistent and the ``<object>`` element was considered to be more compatible across browsers. Nowadays it sounds like the ``<img>`` element is much better off than before and is the ideal way of referencing non-interactive SVGs.

I also stumbled upon https://developer.mozilla.org/en-US/docs/Web/SVG/SVG_as_an_Image, which states that Gecko implements several security restrictions on SVGs that are used as images (like when they're referenced via ``<img>`` elements). Those restrictions don't apply to SVGs referenced via ``<object>`` elements. But in WET's case, none of the logo images this issue covers are meant to be interactive. So I don't think the restrictions would be a show-stopper.

**Comment by duboisp** [comment]
@EricDunsworth can you submit a PR and then I would create a working example for testing.

**Comment by EricDunsworth** [comment]
@duboisp Yeah - that's my intent. Should have a PR open for this repo by COB or tomorrow depending on whether I run into any issues in my own testing.

**Comment by Bgolden67** [comment]
I was about to submit this issue this morning.. thanks for this. I will await your test before i implement your suggested fix.

**Comment by EricDunsworth** [comment]
@LaurentGoderre Thanks for the heads up about the nested media queries. Looks like support for ``<img>`` elements referencing SVGs with embedded media queries is inconsistent in modern browsers.

IE11 honours ``@screen`` correctly, but Firefox and Opera (Blink) don't. That's going to make things a lot trickier. I was thinking of maybe trying something with a ``filter`` CSS property as a workaround, but that wouldn't work in IE11. Plus it might have unexpected side effects in browsers that support ``filter`` and honour ``@screen`` correctly (possibly Edge?).

SVGs referenced via ``<img>`` elements also seem to scale slightly differently than ``<object>`` in Firefox and Opera. So I might end up modifying the CSS properties that control the logo SVG's dimensions to try exactly matching the rendered size we were getting with the ``<object>`` element.

**Comment by EricDunsworth** [comment]
Just sent out #8282.

In the end, I wasn't able to figure out how to perfectly replicate the ``<object>`` logo's rendered dimensions with ``<img>``. But the difference is so minor that it's highly unlikely to be noticeable in practice without performing head-to-head comparisons.
