### ISSUE TITLE
question about Language switching with Struts 2

### ISSUE THREAD

**Issue by phattrinh** [wet-boew/wet-boew#8277]
I am currently working with a Struts 2 web app and using WET 4, for me to do languages switching in Strut2 we have properties files that contain Eng Label and FR label file
however the built in error summary didn't work with the toggle... just wonder is there anything other way that I can do the languages switching? using request_locale in struts2?

**Comment by thekodester** [comment]
Make sure that when you're page is changed the that `<html lang="en">` has also updated to `lang="fr"`.

**Comment by phattrinh** [comment]
thank you so much this work beautifully :)
