### ISSUE TITLE
Multimedia player - JSON Parsing error

### ISSUE THREAD

**Issue by snowman30** [wet-boew/wet-boew#8278]
We noticed an issue with the [Multimedia player](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/multimedia/multimedia.js#L706)'s share feature where having multiple single quotes in the video element's title attribute would cause a JSON parsing error.

I suggest making the replace at line 706 global to change all single quotes and not only the first one encountered.

**Comment by EricDunsworth** [comment]
Just for reference, here's an HTML code sample that can be used to replicate this issue:
```html
<figure class="wb-mltmd" data-wb-mltmd='{"shareUrl": "https://wet-boew.github.io/v4.0-ci/demos/multimedia/multimedia-en.html"}'>
	<video poster="demo/video1-en.jpg" title="Test''''">
		<source type="video/mp4" src="http://video2.servicecanada.gc.ca/video/boew-wet/te-lj-eng.mp4" />
	</video>
	<figcaption>
		<p>Looking for a Job (<a href="cpts-lg-en.html">Transcript</a>)</p>
	</figcaption>
</figure>
```

**Console error:**
> Error: Bad JSON array in data-wb-share attribute

I'll send over a PR to fix it soon.
