### ISSUE TITLE
Flash parameter AllowScriptAccess was set to always

### ISSUE THREAD

**Issue by magex9** [wet-boew/wet-boew#8281]
We are using the WET4 template and things are working well.  We do not use flash or have any multimedia on our website however when we run our AppScan utility to find vunrabilities, we get an issue which is a low but valid concern.

Flash parameter AllowScriptAccess was set to "always" in "wet-boew.min.js” and should be set to “same domain”.

Can this value be changed to "same domain" or have a build of the WET4 framework without any flash components?

**Comment by duboisp** [comment]
@magex9 what version of WET are you using? Did you get the same vulnerabilities when checking the [wet-boew website](http://wet-boew.github.io/wet-boew/index-en.html)?
 
The flash fallback was removed from WET since Apr 17, 2016 by 1d6ba9c7267037ed668ba544497eab8aebab9699

**Comment by magex9** [comment]
We are using 4.0.21 as that was the latest when we built the application being tested. I’ll try upgrading locally next week to see if it solves the issue but looks like it should.

**Comment by magex9** [comment]
The bug was fixed and now longer shows up as an issue on appscan
