### ISSUE TITLE
Left menu responsiveness

### ISSUE THREAD

**Issue by spartingto** [wet-boew/wet-boew#8298]
Hello,

We are using WebTemplateCore.LeftMenuItems to add menu items. Everything works as expected. However when we test in mobile view the left menu is rendered under the content of our page. Our recollection is that it would be put in the menu button (span class=glyphicon glyphicon-th-list).

We are using version 4.0.24 loaded from the CDTS.

Is there any way to get the left menu in the responsive menu up top?

Thanks!

**Comment by shawnthompson** [comment]
Moved this issue to the GC Code environment for the CDTS project.

`/sgdc-cdts/sgdc-cdts/issues/6`

I don't want to link directly to GC Code. Contact me for a direct link if you can't find it.

**Comment by spartingto** [comment]
I don't believe this issue should be assigned to CDTS. If you have a look at this example:

**Comment by spartingto** [comment]
https://wet-boew.github.io/themes-dist/GCWeb/localnav/task1/index-en.html

and emulate a phone browser profile, you'll notice the left menu goes into the 'Search and Menus' responsive menu icon at the top right.

This issue was closed with no reason. Will try to reopen.

**Comment by shawnthompson** [comment]
@spartingto I closed this and moved it to the CDTS project on GCCode (SSC Gitlab) because I thought it was something to do with CDTS. Now I see it has nothing to do with CDTS and more to do with the way the IA specs have placed the secondary menu.  Sorry for the confusion.
