### ISSUE TITLE
WET 3 code examples 404

### ISSUE THREAD

**Issue by hblynd** [wet-boew/wet-boew#8303]
Hello,

We're still using WET 3, and are trying to access the code examples under the "View All [Component] Options" on the [design components page](http://wet-boew.github.io/wet-boew-styleguide/v3/components-en.html), but are encountering a 404 error. Can you help us access this?

Thanks!

**Comment by LaurentGoderre** [comment]
It's in the legacy repo: http://wet-boew.github.io/wet-boew-legacy/v3.1/index-en.html#about
