### ISSUE TITLE
Form Validation - wb-ready.wb event never triggering

### ISSUE THREAD

**Issue by GlennFMacdonald** [wet-boew/wet-boew#8304]
Using Wet 4.0.27. This Event is never triggered when I add the code like this ` $(document).on("wb-ready.wb", function (event) {
        //code here
    });` it never get triggered. Is there anything that I am missing? Is there some sort of alternative I should be using when I need to run a script that requires wet to be ready to work correctly?

**Comment by duboisp** [comment]
@GlennFMacdonald I tried locally and it work as expected.

Do you have any error in your browser console? 

Note that jQuery and wet-boew js is loaded just before reaching the ```</body>``` closing tag and not in the page head.

**Comment by GlennFMacdonald** [comment]
Ok that note is what I needed to know I got it firing now.

The end on the body is in the GOCWebTemplate which I don't want change as it will get overwritten with any subsequent Updates. To avoid that I wrote this
```
<script type="text/javascript">
    $(document).ready(function () {
        $(document).on("wb-ready.wb", function (event) { //code here
            alert("HUI");
        });
    });
</script>
```

**Comment by duboisp** [comment]
If your javascript code is on an external file, you can call the script in the page ```<head>``` by adding the ```defer``` atttribute.

```
<script defer="defer" src="path/to/javascript.js"></script>
```
Note that it might not work on IE10 - https://caniuse.com/#search=defer

**Comment by RobJohnston** [comment]
It could be a bit simpler:

```js
    <script>
        wb.doc.on("wb-ready.wb", function (event) {
            alert("HUI");
        });
    </script>
```

**Comment by GlennFMacdonald** [comment]
Hey Rob, 
This was the initial issue. If I just put that code in my cshtml file it does not work. I can either wait for the document to be ready or the window to load, or that code works if you put it in an external file call the script with the defer.

**Comment by RobJohnston** [comment]
Indeed, it has appear after the jQuery script is loaded.  The `defer `attribute will do that, but as noted by @duboisp , it doesn't work with every browser.

I just wanted to point out that the `type `attribute of the script tag is no longer required and the `$.ready(function)` line isn't required.

**Comment by GlennFMacdonald** [comment]
Ah, I see. Thank you.
