### ISSUE TITLE
Tabbed Interface - Carousel: 

### ISSUE THREAD

**Issue by eswright** [wet-boew/wet-boew#8307]
i think this example page is broken.  Or is this the servers

**Comment by carlamcil** [comment]
I am having problems with another example page as well: http://wet-boew.github.io/v4.0-ci/demos/multimedia/multimedia-en.html

There is no longer a play arrow in the middle of the images and clicking anywhere on the image(s) doesn't play the video clip now when I know it used to work perfectly. Also, the expand/collapse feature isn't working although it does in Firefox.

**Comment by eswright** [comment]
It is due to a library not getting loaded , probably due to Canada government servers?

**Comment by opencmii** [comment]
It is working now.

**Comment by LaurentGoderre** [comment]
Fixed by #8308
