### ISSUE TITLE
Left menu responsiveness

### ISSUE THREAD

**Issue by spartingto** [wet-boew/wet-boew#8310]
Please refer to this issue:

https://github.com/wet-boew/wet-boew/issues/8298

It was reassigned to the CDTS queue and subsequently closed without any reasoning.

I don't understand how this would be a CDTS issue. If you have a look at this link:

https://wet-boew.github.io/themes-dist/GCWeb/localnav/task1/index-en.html

and emulate a phone browser profile, you'll notice the left menu goes into the 'Search and Menus' responsive menu icon at the top right. We would like this behaviour.

**Comment by nschonni** [comment]
Thanks, and sorry to keep bouncing you, but this would be GCWeb issue, since that pattern isn't part of WET core.
https://github.com/wet-boew/GCWeb

**Comment by spartingto** [comment]
Okay Nick thanks for letting me know.

Stew
