### ISSUE TITLE
Form Validation (wb-frmvld) and Date Picker not working inside a overlay modal full screen

### ISSUE THREAD

**Issue by zomby22** [wet-boew/wet-boew#8313]
Form validation: validation works except it does nothing, no red field input box and no red error text appearing.
Date Picker: date picker appears outside the modal box instead of keeping the modal box opened.

Code:

```
<a href="#name<%=rs("id")%>" class="overlay-lnk btn btn-sm btn-default" aria-controls="name<%=rs("id")%>" id="button<%=rs("id")%>" data-toggle="modal">edit</a>

<section id="name<%=rs("id")%>" class="wb-overlay modal-content overlay-def wb-popup-full" aria-hidden="true">
        <header class="modal-header">
        <h2 class="modal-title"><span class="fa fa-2x fa-edit"></span> Edit - Tracking Number <%=rs("id")%></h2>
        </header>
        <div class="modal-body">
            <!--#include file="form.asp"-->
        </div>
    </section>
```

**Comment by nschonni** [comment]
What version of WET and browser are you seeing this in?

**Comment by zomby22** [comment]
WET4.0.21
IE11 on windows 7 (will soon have windows 10 with IE edge but not yet).
since the js and css is not control by me, Ill have to find an alternate solution that can make the code accept the validation and date picker inside the modal window screen.

**Comment by zomby22** [comment]
Hello,
The validation appears to be working now. Only the date picker has issues where it doesn't open inside the modal box. If someone has a solution just simply adding a few jquery lines of codes, let me know. thanks in advance.

![1](https://user-images.githubusercontent.com/20478259/39067552-967bab6e-44c8-11e8-9779-8d65d69d5e53.jpg)

**Comment by zomby22** [comment]
Okay, below, solution #1 works, but need to find a way for #2 to work. So that when I close the box, or press the ESC key to close the box, it actually closes. Right now I can't close the box, but the datepicker works when the wb-overlay class is removed.

#1 
```
$('.btinsert').click(function(){
			$('#insert').removeClass('wb-overlay');
	});

```
#2 
```
$('#hdrClose #ftrClose').on("click", function() {
	  //if ( $('#insert').length ){
		  $('#insert').addClass('wb-overlay');
	   //}
	});
```

**Comment by zomby22** [comment]
How to control this X button? once the wb-overllay class is remove, the X button doesn't work, so to make the date picker work within the box, I had to create my own close button, however if there is a way to make it work with the default close button, let me know me how?

![close](https://user-images.githubusercontent.com/20478259/39632780-8ac08c4e-4fa5-11e8-9e1a-1ea47aefe434.jpg)

**Comment by albertkao** [comment]
@zomby22
Had this issue been fixed?
Is there any sample code to fix this issue?

**Comment by zomby22** [comment]
Nobody responded with a better code. What I did is somewhat working (temporary code). But its not the best way to solve it, it also makes the close (X) button not working.

**Comment by duboisp** [comment]
Can you make it to one of the weekly Tuesday WET-BOEW code sprint at place du portage in Gatineau? I can help you to develop the fix and have it implemented in wet-boew.

**Comment by zomby22** [comment]
I am working on other projects, this isn't really important right now. Do you have a piece of sample you can share? thanks.

**Comment by duboisp** [comment]
I don't have any piece of sample that could solve this issue. I was more offering to provide you guidance/teaching you on how you can develop a permanent fix for it and get your fix merged into wet-boew.
