### ISSUE TITLE
Multimedia Player - YouTube: 

### ISSUE THREAD

**Issue by BenTrem** [wet-boew/wet-boew#8314]
Hi - Working through your examples.

I hate peppering people with the sort of fixes / bug reports / errors I pay attention to in my own work. Most everybody sees it as aggressive. I've pret'near given up, after 45yrs in tech.

Anyhow ... this example works fine in Chrome. But not at all in Firefox.
Doesn't that contradict the project's mandage?

heyho
/bdt

**Comment by nschonni** [comment]
On http://wet-boew.github.io/wet-boew/demos/multimedia/multimedia-youtube-en.html it is loading fine with FireFox 59.
Is it possible you're running stuff like NoScript that is blocking the external scripts?

**Comment by duboisp** [comment]
I tested It work fine on Firefox dev edition 60.0b2

What version of firefox do you have issue with? 

Is it about the close caption? The multimedia youtube player wont display the youtube auto-generated close caption.

**Comment by BenTrem** [comment]
FF v55.0.3 (After years of being on bleeding edge I've dragged my feet recently. For no good reason updating on this plain vanilla office-grade PC has caused multiple problems.)
I have no problems with any other media. Nor can I recall problems in years past. So ... really no clue what's up!

Here's what happens:
http://bentrem.net/video/WET-YT-Player.mp4

--ben

**Comment by duboisp** [comment]
Thanks for the information.

I tested the Youtube multimedia player with FF 55.0.3 (64-bit) portable edition on Windows 7 and it work as expected. I wasn't able to reproduce the issue you demonstrated in your video. Thanks for the video, it help a lot for testing.


Do you see any error in the console of your FF? Do you have a different proxy setting in your FF compared to your other installed browser? Did your corporation firewall block some of network communication when navigating the web with FF? Can you access and view the video directly on the [youtube website](https://www.youtube.com/watch?v=9znKJqnFuuY)?

**Comment by BenTrem** [comment]
Greets - I can't throw troubleshooting data just now ... in mid-stream here.

No problem with the YT version.
And again: works fine in Chrome, so not a network thing.

I'll snoop w/Console when I can.

/bdt

**Comment by BenTrem** [comment]
/*_closed - **not reproducible**_ */
