### ISSUE TITLE
Data JSON plugin with IE11

### ISSUE THREAD

**Issue by alexgagnon** [wet-boew/wet-boew#8319]
Hi, the Data JSON plugin uses `<template>` tags to dynamically generate DOM content, however although the tag is in the spec, it is not supported in IE 11 and below or Opera Mini. Does the toolkit polyfill this behaviour, or is there a workaround?

**Comment by duboisp** [comment]
Yes there is a template polyfill but it is currently only available for the Canada.ca theme.

It should work fine in IE11, but I didn't tested with Opera Mini.

Here the source code of the template polyfill: https://github.com/wet-boew/GCWeb/blob/master/src/plugins/deps/template.js
