### ISSUE TITLE
Merge server-side validation errors with client-side validation errors (WET)

### ISSUE THREAD

**Issue by ogati** [wet-boew/wet-boew#8321]
Hi,
When a client-side validation error occurs after a server-side validation error, they are rendered in separate two sections as follows (The 1st one is from server side and the 2nd client side). 

![capture](https://user-images.githubusercontent.com/37627000/37719363-3e6fe0b4-2cfb-11e8-8774-ed00b6e53099.PNG)

Is there a way to merge the two types of validation errors into one section?
Someone recommends server-side validations be performed via jQuery validation remote method. But I don't think it's a good approach because it won't work if JavaScript is disabled. Correct me if I'm wrong.
Thanks.

**Comment by RobJohnston** [comment]
Have you seen https://github.com/wet-boew/wet-boew/issues/7408?

It could be a good approach.  If JavaScript is disabled, then the user will only see the server-side validation.  But if JavaScript is enabled, then all the client-side validation should hide any server-side validators.

**Comment by ogati** [comment]
If JavaScript is disabled, jQuery validation remote method won't work. How could the user see the server-side validation messages if the validation is invoked via the remote method?
Thanks.

**Comment by thekodester** [comment]
Look at https://github.com/wet-boew/wet-boew/issues/8275

**Comment by ogati** [comment]
Thanks thekodester. It works.

Since each server-side validation error is also rendered beside the related field, the error remains beside the field after client-side error box replaces server-side error box. Any suggestion to remove/hide it?

Thanks.

**Comment by ogati** [comment]
The errors beside fields can be hidden via CSS. Thanks a lot for all the input.

Please close this ticket.
