### ISSUE TITLE
MAJOR ISSUE: Wiki Pages

### ISSUE THREAD

**Issue by thekodester** [wet-boew/wet-boew#8326]
So it looks like the Wiki page are wide open to changes. ~~Recently https://github.com/wet-boew/wet-boew/wiki/Implementing-WET was edited to gibberish. (appears the page was removed)~~

This can be changed see https://help.github.com/articles/changing-access-permissions-for-wikis/ .

**Comment by thekodester** [comment]
This can be changed see https://help.github.com/articles/changing-access-permissions-for-wikis/

**Comment by LaurentGoderre** [comment]
I unfortunately am not an admin anymore so I can't prevent this. I can however restore the page.

**Comment by thekodester** [comment]
Yeah I just checked I can myself freely click edit and save on a lot of the Wikis. Hopefully an admin becomes aware before more bot accounts do damage.

**Comment by LaurentGoderre** [comment]
Hmmmm, I trying reverting it but it's super old...perhaps the page should not exist at all....

**Comment by thekodester** [comment]
Yeah it looks like someone already deleted it.

**Comment by thekodester** [comment]
Looks like the bot account is deleting and recreating it multiple times:
<img width="677" alt="screen shot 2018-03-22 at 10 31 56 am" src="https://user-images.githubusercontent.com/23484460/37776864-96e14032-2dbc-11e8-855c-9c8f8593a10b.png">
I blurred image as I think it using a real persons image.

**Comment by LaurentGoderre** [comment]
So did I

**Comment by thekodester** [comment]
Maybe I'm crazy, but it seems lately on GitHub there having major bot account issues.

**Comment by duboisp** [comment]
I did the restriction to collaborator

**Comment by thekodester** [comment]
Thanks! I'll close the issue.
