### ISSUE TITLE
Toggle: disables radio buttons it's applied to

### ISSUE THREAD

**Issue by jkshapiro** [wet-boew/wet-boew#8330]
Hi there,

I'm trying to implement a form with a conditional field. The field should be displayed or hidden depending on which of a set of radio buttons is selected.

Am trying to use the Toggle functionality per http://wet-boew.github.io/v4.0-ci/docs/ref/toggle/toggle-en.html, but am finding a glitch: once I apply the class "wb-toggle", the radio buttons can no longer be selected. They take focus but they don't get clicked.

Tested on Windows, in IE, FF, and Chrome.

Demo code follows:

```
<fieldset>
  <legend class="formLegend">
    <span class="field-name form-group">
      Does the conditional field apply to you?
    </span>
  </legend>
  <div class="radio">
    <label for="yes">
      <input type="radio" id="yes" name="showCondField" value="yes" class="wb-toggle" data-toggle='{"selector": ".conditional-field", "type": "on"}' />
      <span class="field-name">
        Yes it does
      </span> 
    </label> 	
  </div>
  <div class="radio">  
    <label for=no">
      <input type="radio" id="no" name="showCondField" value="no" class="wb-toggle" data-toggle='{"selector": ".conditional-field", "type": "off"}' />
      <span class="field-name">
        No it doesn't
      </span> 
    </label> 	
  </div>

  <div class="conditional-field">
     Conditional field here&hellip;
  </div>
</fieldset>
```

**Comment by crochefort** [comment]
Hi @jkshapiro have you try : http://wet-boew.github.io/themes-dist/GCWeb/demos/fieldflow/fieldflow-en.html ??
You have a lot of option , ( main page, basic option and also advance option )...
pretty sure @duboisp would be your man if you don't have what you need there!

**Comment by jkshapiro** [comment]
Yes, thank you, that meets my need.
