### ISSUE TITLE
Help with writing WET Interview Questions?

### ISSUE THREAD

**Issue by TimCadieux** [wet-boew/wet-boew#8354]
Hello folkz, my old office has asked me to help them hire my replacement, I thought I would ask 2-3 WET specific question but because I haven't used it now for 6months, I was hoping someone could help me with 2-3 ideas. 

Our site was mostly about pulling data from a db and displaying and filtering based on keywords.  I used the datagrid a tonne which i now cannot even name.

Thx in advance.

**Comment by duboisp** [comment]
All depend of your work description. If you don't exactly know what to ask and it is to hire your replacement, then.... 

My 5 cents on that is by asking WET specific question you might put you at risk to miss a great candidate that have the intellectual capacity to learn it. The basic requirement of using WET should be to know HTML and ideally be introduced to WCAG. Keep in mind as far that I know WET are not teaches at CEGEP or University. I am not even sure that WCAG is teaches by those type of institution, lol.

**Comment by thekodester** [comment]
I would agree with @duboisp when I did a contract with Veterans Affairs I had no knowledge of WET or WCAG, but was able to jump right in.

**Comment by TimCadieux** [comment]
You're both right, I had no knowledge of WET either, thx.
