### ISSUE TITLE
WET4 Calendar of Events - set the heading title date base on calendar selection

### ISSUE THREAD

**Issue by zomby22** [wet-boew/wet-boew#8360]
Hello
The plugin works great with ASP and Postgres, however, if I want the heading title to change without LOOPING and simply change the Month and Year base on the calendar selection, how can I code it? I try adding a javascript where the innerHTML would simply display the month and year outside the loop, but this is not working and I know why, but I don't have any other solution on how to do it. 
I also want to display a message when there is no events found for a specific month. This is most likely to be done using jquery with this plugin.

![calendar](https://user-images.githubusercontent.com/20478259/39014066-ca1a2b78-4408-11e8-9874-fb25299eb1aa.jpg)

**Comment by duboisp** [comment]
You have a JS function that bind to the JS event ```wb-updated.wb-calevt```. As per the [calendar documentation](http://wet-boew.github.io/wet-boew/docs/ref/cal-events/cal-events-en.html), it should be triggered every time the events calendar is updated (e.g., month changed).

**Comment by zomby22** [comment]
the documentation is not helping a whole lot. I am not good with jquery unless im working with a working example.

```
$( document ).on( "wb-ready.wb-calevt", ".wb-calevt", function( event ) {$( document ).on( "wb-ready.wb-calevt", ".wb-calevt", function( event ) {
something here!!!
});
```

**Comment by zomby22** [comment]
this is what I get when I try. I have 4 different courses active (this is just an example) September 2015 to April 2018. 

![calendar2](https://user-images.githubusercontent.com/20478259/39053460-94b1cb12-449e-11e8-986a-6673ccb965cf.jpg)

**Comment by thekodester** [comment]
Using this yield the year and month:

```
		$( document ).on( "wb-updated.wb-calevt", ".wb-calevt", function( event ) {
			var calYr = $( "#calendar1" ).find( "select.cal-year option:selected" ).text();
			var calMn = $( "#calendar1" ).find( "select.cal-month option:selected" ).text();
		});
```
