### ISSUE TITLE
freegeoip.net is being shut down July 1st, 2018

### ISSUE THREAD

**Issue by nschonni** [wet-boew/wet-boew#8365]
When looking at the failure in #8364 I saw this message hitting the endpoint
> This API endpoint is deprecated and will stop working on July 1st, 2018. For more information please visit: https://github.com/apilayer/freegeoip#readme"

Seems like the free tier is going to be limited to 10K a month, then it's commercial https://github.com/apilayer/freegeoip#required-changes-to-legacy-integrations-freegeoipnetjsonxml

Probably need to either remove the plug-in or find an alternative.

**Comment by duboisp** [comment]
@TouficS are you able to help us with this issue?
