### ISSUE TITLE
WET-BOEW 4.0.28 - Abandoned theme / Thème abandonné

### ISSUE THREAD

**Issue by duboisp** [wet-boew/wet-boew#8366]
We are going to release WET 4.0.28 and to optimize our operation effort we aren't releasing the following theme:
* Base
* Government of Canada Web Usability
* Government of Canada Intranet
* Open Government Platform (OGPL)

If you are interested to have one of those themes above to be released with WET 4.0.28, we would need an official theme lead with at least one active resource able to do the maintenance, improvements and the quarterly release. I would be available to coach the theme lead and the resource during the weekly WET code sprint (every Tuesday).

Please comment if you have any questions or interest. You can also find my contact information on GCCollab and on GCConnex.

*Pierre Dubois
Web Experience Toolkit Project Lead*

---

Nous allons bientôt publié la version 4.0.28 de la BOEW et afin d'optimiser nos effort d'opération nous allons pas publié les thèmes suivant:
* Base
* Facilité d’emploi Web du gouvernement du Canada
* Gouvernement du Canada pour les sites intranet
* Plate-forme de gouvernement ouvert (PGO)

Si vous estes intéressé d'avoir un de ces thèmes ci-dessus publié avec la version 4.0.28 de la BOEW, nous aurions besoin d'un chef de thème avec au moins une ressource active afin de faire la maintenance, l'amélioration et les publications trimestrielle. Je serai disponible pour de l'encadrement au chef de thème et à ses ressources durant les code sprint hebdomadaire de la BOEW (à chaque mardi).

Veuillez commenter si vous avez des questions ou si vous estes intéressé. Vous pouvez aussi trouver l'information afin de me rejoindre sur GCCollab et sur GCConnex.

*Pierre Dubois
Gestionnaire de projet de la boîte à outils de l'expérience web*

**Comment by RobJohnston** [comment]
So if there is no more Base theme, and the [generator-wet-boew-theme](https://github.com/wet-boew/generator-wet-boew-theme) project has been broken for years, how does somebody create a new theme now?

**Comment by duboisp** [comment]
Short term for WET4, if somebody want to create a new theme he would need to do it based on WET-BOEW theme or on GCWeb theme. Unless if someone are interested to maintain the Base theme and the generator-wet-boew-theme project.

For WET5 the goal is to have each theme independent of the JS framework with no need of using a theme generator. For example, the choice of using a CSS grid framework (like bootstrap) will be made by the theme and not being imposed by the core product. That independency would ease the work of integrating the WET framework on content that are already published.

**Comment by LaurentGoderre** [comment]
So none of the plugin will be able to use grids from Bootstrap? Sounds like going back towards maintaining something very difficult to maintain.

**Comment by duboisp** [comment]
@LaurentGoderre we are still in a very early stage for WET5, but I can say that if they are plugin like that, they will only need to be clearly identified as they require the grids from Bootstrap.

**Comment by LaurentGoderre** [comment]
Maintaining a custom CSS framework for the plugins is way more work than this community can handle so deferring to a third party like Twitter Bootstrap is still the way to go IMO. The best choice would be to have a core and plugins set that are independent so that someone can develop a set of plugins using a different CSS framework.

**Comment by LaurentGoderre** [comment]
With that being said, it might be worth investigating creating plugin logic that is independent of the HTML/CSS implementation.

**Comment by duboisp** [comment]
Yes Laurent, we are looking to have the plugin logic to be independent of the HTML/CSS implementation. It will also help to prevent a lost of functionality and content when the user are switching between the standard mode into the basic HTML mode and vice versa.

For the plugin, the UI would be a JSON object. And the plugin would have a few basic overwritable HTML template.

That is the basic concept for now.

**Comment by SebastienMetivier** [comment]
Is this permanent or only for version 4.0.28 ?

Because if the Government of Canada Web Usability Theme is dropped what are we supposed to use on our Agency website if we are not moving to Canada.ca ?

**Comment by duboisp** [comment]
> Is this permanent or only for version 4.0.28 ?

As I mentioned in the description: "we would need an official theme lead with at least one active resource able to do the maintenance, improvements and the quarterly release."
If nobody can/want to take the lead on the Government of Canada Web Usability theme and to provide an active ressource then yes it is fair to assume it will be permanent.

> what are we supposed to use on our Agency website if we are not moving to Canada.ca

Is the Treasury Board of Canada Secretariat [Directive on the Management of Communications](https://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=30682) are applicable to your Agency? 

**If yes**, then the [Canada.ca Content and IA specification](https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/canada-content-information-architecture-specification.html) mention that you are required to follow that manual and the [Canada.ca style guide](https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/canada-content-style-guide.html) for online content.

**If no**, then an option would be to find a volunteer that are willing to take over the lead of Government of Canada Web Usability theme and to ensure that lead is able to get an active ressource able to contribute.

**Comment by joejoseph00** [comment]
Now that this platform is finally more or less stabilized, why re-invent the wheel?  If you need to change colours or look to reflect the partisan colours of the next or current governing party, that is relatively easy to do with the current platform with very minimal changes (that was the whole idea from the start, and also for mobile support which is currently well done).

**Comment by duboisp** [comment]
@joejoseph00 Are you referring to GCWeb theme or to WET. 

GCWeb theme, including the colours scheme, are driven by the Canada.ca Content and IA specification, by the Canada.ca style guide and by the organisation (TBS/PCO) that manage those documents. 

Regarding WET, there is a need to improve the current WET 4 product and have it more modular, more reusable, more flexible for developper, performing faster,... We are just starting to work on it. Feel free to open an new github issue to share your concern.

**Comment by joejoseph00** [comment]
sounds like a money burning exercise.  Count me in, I've got automated testing software ready to go, fill up my mattresses full of cash.

**Comment by RitchieD** [comment]
Very disappointing to lose GoC Intranet Theme.

**Comment by LaurentGoderre** [comment]
@duboisp is Service Canada willing to revisit this decision if I fix the release script to bring back automated releases? It seems a lot of people are still relying on the Intranet theme and breaking semver like this is a bad precedent.

**Comment by duboisp** [comment]
I/We (Service Canada) are not against to release the intranet theme based on the latest version of WET. What we need is an official theme lead which would be tasked and responsable to do the release and maintain the repository. 

If there a such high interest to have the intranet theme back, then I can coordinate the creation of a small community/team dedicated. This for the intranet theme or any other theme. I can provide technical support during the weekly Tuesday WET code sprint. What I will need to start is a list of participants/members and at least one lead.  Who are interested? Let me know which theme and what role you are interested in.

_(If there is an considerable interest, I will open a new dedicated issue for this purpose.)_

 cc/ @joejoseph00, @RobJohnston, @OCHeather, @RitchieD, @Bgolden67

@LaurentGoderre Fixing the release script would definitely help the future intranet theme lead, but it would not provide me more time to do the periodic release and to maintain that repository.

**Comment by LaurentGoderre** [comment]
Releasing the theme took less than 10 minutes with the automated script why isn't it possible to just do that part?

**Comment by duboisp** [comment]
@LaurentGoderre may be yes to produce and publish the binary/compilation, but that don't include maintenance effort and producing relevant documentation for now on and moving forward. I prefer to have a lead that would be able to maintain it in a more stable manner.

BTW - a PR with the appropriate release note and links to the theme binary/compiled version are welcome.

**Comment by LaurentGoderre** [comment]
I believe what the community is asking is to continue producing the binaries until a proper theme lead is found. Would that be an acceptable compromise?

**Comment by joejoseph00** [comment]
Je suis d'accord avec Laurent, à 100%, sauf je suis un consultant motivé par l'argent, éliminer le support pour le thème intranet risque de m'enrichir grossièrement!  Mais comme contribuable je déplore ce changement car ça va juste créer le chaos et ça ne sert qu'à enrichir les entreprises au détriment de projets de mérite et de plus grand valeur.  J'ai déjà assez de boulot comme c'est là.  Voilà pourquoi comme consultant je suis optimiste que les profits continue à accroître!  Mais comme contribuable je suis pessimiste que les dépenses inutiles et les gourdes dans le gouvernement ne cessera jamais.  Voilà , fait ce que tu veut, peut importe je gagne car j'augmente mon per diem à chaque fois que le taux d'imposition monte.  Alors je m'en fou finalement, la maison qui rend fou, c'est votre maison!  Je ne cherche la laisser passer A38, je l'ai déjà, ça s'appelle incorporation, je passe directement à la caisse!

**Comment by duboisp** [comment]
@LaurentGoderre Feel free to submit the PR. 

If the community want all those sub-products released, we need a more active participation from members of the community.

@joejoseph00 I am sorry to heard that your contract with whatever Government of Canada institution that has hired you, don't include a clause to force you to share all your work in the open by following current best practice.

**Comment by joejoseph00** [comment]
Totally off topic, @duboisp , but ya, maybe if the govt would get it's act together they'd GPLv3 stuff like Phoenix instead of writing blank cheques to IBM.

My point is, I don't think you realize what impact your changes have.  Maybe you should just listen to Laurent, he's the one that built this whole architecture, he's the expert that actually knows how this thing works and the whole ecosystem related to it.

**Comment by thomas-kay** [comment]
I could help.  I've assisted in deploying WET templates to the CDN locations. Example,  ssl-templates.services.gc.ca  ( both into legacy www zones, and intranet zones that get copies of such critical WET assets).  

We can deployed to the shared hub/intranet enclave between GC departments.   I need to move these original template support sites anyways to the next OS platform SSC will enable for them.  SSC has an OS  replacement project underway.   There is a growing opportunity in evolving some of the older parts of the current ecosystems, if the newest parts of the newer ecosystem in the cloud$ ( other peoples servers ) are becoming human resources intensive and less flexible and adaptive as we once hoped.   If i am moving and updating infrastructure with SSC anyways, why not plan a pathway around leveraging the service nodes again.   Less contract issues, if I go open source first in the digital transformation, and we go with a continued replication of the hybrid design for added safety on the data sovereignty, so the newer WET templates can easily flow to all CDN service nodes.

**Comment by Spirch** [comment]
What are the alternative for the internal theme? Does it mean any vulnerability or bug fix is on every and all individual using 4.0.27 to handle/fix? 

Also, depending on how the theme was implemented in a code base, changing it could he expensive/risky.

I find it weird that it was supported and then not supported, it should have been dropped with 5.0 

I hope, this is impossible, there will be no major vulnerability related to 4.0.27 because if that happen, ho boy many peoples will struggle.

Saddly, something tell me that we will see 4.0.27 in production release for a very long time.

**Comment by Bgolden67** [comment]
@michael-milette I think you need to check the Canada.ca Information Architecture and style guide. I could be wrong but i believe that is not allowed, but if it is, this would be good to know.

**Comment by duboisp** [comment]
@michael-milette

Currently in the Content and IA spec it is mentioned the global navigation

> may be optional for:
> * transactional scenarios
> * campaign and promotional events pages

It is also mentioned 

> The global header and footer cannot be altered and must remain consistent, wherever it is used.

Reference: https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/canada-content-information-architecture-specification/headers-footers-navigation.html#toc1

**Comment by PMinhThai** [comment]
Trying not to hijack this post too much but in regards to the themes, I was wondering which one are [https://talent.canada.ca/](url) and [https://digital.canada.ca/](url) using?

**Comment by shawnthompson** [comment]
These sites are not using any WET theme. They took GCWeb and created custom styles. Personally I don't even think they should be using WET. They can pull all that off with just basic CSS. Their site performance would be so much better!

**Comment by PMinhThai** [comment]
So correct me if I'm wrong but just like they did, If we have to reskin or create a new public web app in our government institution and we're not pushing it to Canada.ca or to our institution website, we can basically take the GCWeb theme and enhance it as long as we comply with the Web Standards?

**Comment by duboisp** [comment]
@PMinhThai 

> https://talent.canada.ca/ and https://digital.canada.ca/ using?

The content and IA spec define what is out of scope. It is explained here: https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/canada-content-information-architecture-specification/usage-canadaca-design.html

If you have questions or need more clarification and you can't discuss with your theme lead about this, please open a new issue in [GCWeb repository](https://github.com/wet-boew/GCWeb/issues/new) and I would forward your question to the appropriate group.

**Comment by PMinhThai** [comment]
Thank you for the info Pierre!
