### ISSUE TITLE
Twitter embedded timeline widget

### ISSUE THREAD

**Issue by katmeikle** [wet-boew/wet-boew#8369]
I have some developers that use the twitter widget for their sites. One of them has brought to my attention on May 25, 2018, the widget settings page will no longer allow embedded timeline widgets to be created or edited (https://twittercommunity.com/t/deprecating-widget-settings/102295). We are wondering if there is an alternative or update to the Twitter embedded timeline widget http://wet-boew.github.io/v4.0-ci/demos/twitter/twitter-en.html?

Thanks

**Comment by thekodester** [comment]
When you read this "...From that date, the only (and best) way to create timeline widgets will be to head to publish.twitter.com..", it sounds like timeline widgets are still a thing, but the code is changing.

**Comment by thekodester** [comment]
Just an FYI the https://wet-boew.github.io/v4.0-ci/demos/twitter/twitter-en.html demo page is broken due to twitters changes.
