### ISSUE TITLE
Issues with Form validation example page

### ISSUE THREAD

**Issue by biljanap** [wet-boew/wet-boew#8376]
Is something wrong with Form validation example page?
[http://wet-boew.github.io/v4.0-ci/demos/formvalid/formvalid-en.html](url)
Not sure if new version of WET 4 handles error messages differently but something is not quite right. Only required fields are being validated. Specialized validation (formats and data rules) are ignored and not validated.

**Comment by duboisp** [comment]
http://wet-boew.github.io/wet-boew/demos/formvalid/formvalid-en.html

The forms validation only got a minor update that add a ```testReady``` check to ensure all third party JS dependencies are loaded and ready. (#8363)

I am investigating the issue right now.

**Comment by duboisp** [comment]
I am going to do a new release: WET 4.0.28.1

Thanks @biljanap for finding that issue

**Comment by duboisp** [comment]
WET and GCWeb v4.0.28.1 has been successfully released.

http://wet-boew.github.io/wet-boew/docs/versions/v4.0/v4.0.28-en.html
