### ISSUE TITLE
jQuery 

### ISSUE THREAD

**Issue by dclement24** [wet-boew/wet-boew#8387]
What is the jQuery version being used in the latest available WET template ?

**Comment by RobJohnston** [comment]
It was just bumped up two weeks ago from 2.1.4 to 2.2.4 in https://github.com/wet-boew/wet-boew/pull/8371, but I don't see that in the [latest release](http://wet-boew.github.io/wet-boew/docs/versions/rdmp-en.html) notes.

**Comment by dclement24** [comment]
jQuery version 2.2.4 is vulnerable to XSS.  Do you know if it will be updated to the latest version?

**Comment by duboisp** [comment]
The latest release of WET (v 4.0.28.1) are using jQuery 2.1.4. https://github.com/wet-boew/wet-boew/blob/v4.0.28.1/package.json#L41

The version bump from #8371 would be applied for the next released v4.0.29.

**Comment by nschonni** [comment]
The versions used are the latest for the major versions used by WET 4. I don't think WET 4 will upgrade to jQuery 3, but I might be wrong.
https://blog.jquery.com/2016/05/20/jquery-1-12-4-and-2-2-4-released/ where used, but the CVE is related to calling to a malicious third party and not specifying the dataType parameter. https://snyk.io/test/npm/jquery/1.12.4?severity=high&severity=medium&severity=low

**Comment by dclement24** [comment]
Do you know who to contact at Treasury Board about WET?  The template would definitely be updated to use jQuery 3. Thanks

**Comment by duboisp** [comment]
@dclement24 I am the one to be contacted. You can find my contact info on [GCCollab](https://gccollab.ca/profile/Pierre.Dubois) or on [GCConnex](https://gcconnex.gc.ca/profile/duboisp)

I will be more than happy to upgrade WET 4 to use jQuery 3.

Are you able to provide some ressources?
