### ISSUE TITLE
Tabbed Interface: Tabs on Google Chrome using keyboard only

### ISSUE THREAD

**Issue by sarasuri** [wet-boew/wet-boew#8400]
Hi,
There is an issue accessing elements such links, form fields within the content of a tab in Chrome (tested in version 67.0.3396.62). The keyboard-only users are not able to access those elements. 

Used the Tab and arrow key to select the Example 1 (first tab in Example 1). Then, try to navigate the content of the "Example 1" tab using the Tab key. But the keyboard focus jumped to the "Show the third panel" link right below the "Example 1" section skipping the "Example 3" link within the content the "Example 1" tab.

**Comment by juleskuehn** [comment]
I was able to replicate this issue.
