### ISSUE TITLE
Tables: why do you use a down arrow for sort ascending?

### ISSUE THREAD

**Issue by muling** [wet-boew/wet-boew#8407]
I find this to be counter intuitive to use an up arrow for descending and a down arrow for ascending.

**Comment by nschonni** [comment]
Do you have an example? On the demo table http://wet-boew.github.io/wet-boew/demos/index-en.html the up arrow is highlighted when sorting accending

**Comment by muling** [comment]
Ok you are right.  I just realized that the arrows themselves are not clickable and it is the column header that triggers the sort change.  I was not expecting that.  I assume that we do it this way because the arrows are too small and it is easier for users to click on the entire header?

We can close this item.

**Comment by nschonni** [comment]
I came across https://github.com/wet-boew/wet-boew/issues/5209 when trying to see what previous information/reason we had for changing this
