### ISSUE TITLE
Documentation: Creating a pull request: Single vs Double quotes

### ISSUE THREAD

**Issue by juleskuehn** [wet-boew/wet-boew#8437]
The ["Creating a pull request" document](https://wet-boew.github.io/v4.0-ci/docs/pull-en.html) states the following recommendation:

>   Use single quotes for strings in JavaScript (so unescaped double quotes can be used for attributes in HTML output)

The opposite style is used throughout the repo - double quotes in JavaScript, with nested single quotes for HTML. For instance, in menu.js:

`panelDOM.innerHTML = "<header class='modal-header'><div class='modal-title'>`

**Comment by EricDunsworth** [comment]
That guidance was introduced in #5082 in March 2014. The repo's JavaScript files were being linted with JSHint at the time but [its rules file](https://github.com/wet-boew/wet-boew/blob/478f5a38cd381f8565f3fa796820907f168c455d/.jshintrc) was specifying double-quotes.

JSHint was later replaced with ESLint. WET's .eslintrc.json file doesn't currently specify anything for the [quotes rule](https://eslint.org/docs/rules/quotes), so ESLint is falling back on its default (double quotes).

@nschonni @duboisp @LaurentGoderre Thoughts?

**Comment by LaurentGoderre** [comment]
We were following the jQuery style guide so it should be double quotes, that document is just outdated.
