### ISSUE TITLE
Form buttons and dropdown list element are cut off at 200%

### ISSUE THREAD

**Issue by fredymoko** [wet-boew/wet-boew#8492]
On this page: http://wet-boew.github.io/themes-dist/GCWeb/feedback-en.html,
all form buttons and dropdown list are cut off at 200% due to the absolute length units: 
input[type="button"], input[type="reset"], input[type="submit"] {
    _height: 37px;_
}

.form-control {
     _height: 37px;_
    }

![zoom_200_percent](https://user-images.githubusercontent.com/13095980/46872664-d0044f80-ce02-11e8-9929-746f36f72dc6.PNG)
![form_control](https://user-images.githubusercontent.com/13095980/46872901-633d8500-ce03-11e8-8fa4-b5f36792b283.PNG)
![form_submit](https://user-images.githubusercontent.com/13095980/46872910-68023900-ce03-11e8-96e1-b5772014ea15.PNG)

**Comment by thekodester** [comment]
Yes with Zoom Test Only the enforced height causes the issue. I wonder if using `min-height` would fix it without causing any issues on other browsers.

**Comment by thekodester** [comment]
Looking a the scss files it appears this is not a wet override, but coming directly from bootstrap.

See https://github.com/wet-boew/wet-boew/blob/1882dd3df9cefb0d8d64edb22783903ace778edd/src/base/bootstrap-overrides/_base.scss for bootstrap overrides.

**Comment by thekodester** [comment]
There are other open issues too https://github.com/wet-boew/wet-boew/issues/7744 and https://github.com/wet-boew/wet-boew/issues/6910

**Comment by thekodester** [comment]
The better solution seems to be https://github.com/wet-boew/wet-boew/issues/7744#issuecomment-387200043.

**Comment by nricherbrule** [comment]
@bsouster Other tickets exist focusing on this issue. I think this can be closed.

**Comment by grifare** [comment]
I have applied the fixes pointed out on this discussion to overwrite the existing rules and they worked. Tested IE11, Microsoft Edge 42, Firefox 57 (using zoom text only), and Chrome 75.
