### ISSUE TITLE
v4.0.29 French release notes not updated

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/wet-boew#8503]
The [v4.0.29 - Notes de version](http://wet-boew.github.io/v4.0-ci/docs/versions/v4.0/v4.0.29-fr.html) were not updated

**Comment by EricDunsworth** [comment]
It looks like the French version of that page was fully updated apart from a leftover "4.0.28" H3 heading.

I just sent out an unrelated PR to fix broken commit links in both versions of that page. Will send out another to remove the aforementioned heading.
