### ISSUE TITLE
Help with implementing datatables

### ISSUE THREAD

**Issue by jhaydtw** [wet-boew/wet-boew#8506]
I wish I knew more about this, but here is the issue from my developers:
We need the directory structure to map to the .css and .js files.
--------------------------
What do we include to get all these files? Including the datatables css and js files?

For example this is base directory we have:
https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_27/

Then we add  /cdts/compiled/soyutils.js  to get this file:
https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_27/cdts/compiled/soyutils.js
And this cdts/compiled/wet-en.js to get this one:
https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_27/cdts/compiled/wet-en.js

I accidentally figured out this jquery file I needed:  js/jquery/2.1.4/jquery.min.js
https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_27/js/jquery/2.1.4/jquery.min.js

But we need lots of other files, like for example : https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js
-----------------------------------------------------------------------

Is there a list somewhere?  Is there a place to view the cdn tree?

Thanks,
Jeff

**Comment by jhaydtw** [comment]
hmmm, screwed something up.  this one can be closed.

**Comment by thekodester** [comment]
See https://datatables.net for more features of the plugin.

FYI: WET excludes some features for accessibility reason.

**Comment by duboisp** [comment]
JS dependency, such datatable, are only loaded when your page contains an HTML table enhanced with the WET table plugin. Like: ```<table class="wb-tables">```

It's the same thing for loading polyfill and loading other JS dependencies. They are publisher in this folder: https://github.com/wet-boew/wet-boew-cdn/tree/v4.0-dist/js
