### ISSUE TITLE
CDN - French mega-menu character encoding

### ISSUE THREAD

**Issue by markbelanger** [wet-boew/wet-boew#8508]
The CDN mega menu in French (http://cdn.canada.ca/gcweb-cdn-live/sitemenu/sitemenu-fr.html) is not encoded properly. The accented characters are displaying wrong. This affects any sites using this CDN. Please fix. Thank you.

**Comment by duboisp** [comment]
We are currently investigating the issue. Thanks for reporting it

**Comment by markbelanger** [comment]
Thank you very much for the quick turnaround on this. Much appreciated.

**Comment by markbelanger** [comment]
French accented characters fixed. CDN mega-menu now works as expected.
