### ISSUE TITLE
API to extend mobile menu panel?

### ISSUE THREAD

**Issue by Pacoup** [wet-boew/wet-boew#8510]
In our Intranet redesign, we are adding login links to the menu bar. For example, we add this markup in our Drupal template:

``` HTML
//[...]
<section id="wb-extra" class="visible-md visible-lg">
  <h2><?php print t('Extra links'); ?></h2>
  <?php print $extra_links ?>
</section>
<section id="wb-lng" class="visible-md visible-lg">
  <h2><?php print t('Language selection'); ?></h2>
//  [...]
```

The details aren't relevant, but basically, what I'm trying to achieve is to add links here:

![add_links_here](https://user-images.githubusercontent.com/112764/48158798-74ae6b80-e2a1-11e8-8dba-c50a16b16dc2.PNG)

Since these extra links are not inside the actual menu, the Menu plugin doesn't load them anywhere in the mobile panel.

I suppose I could write a script that inserts the content I want on page load, but before I do that, is there an API or something more official to use to extend the Menu plugin?

**Comment by thekodester** [comment]
I wouldn't use that many level two headers (`<h2>`). You could include it with the language tab.

Update this code:
`<section class="lng-ofr">
<h3>Language selection</h3>
<ul class="list-inline">
<li class="visible-xs-inline visible-sm-inline"><a href="#">Sign out</a></li>
<li><a lang="fr" hreflang="fr" href="index-fr.html">Français</a></li>
</ul>
</section>`

Image:
<img width="826" alt="screen shot 2018-11-07 at 3 44 58 pm" src="https://user-images.githubusercontent.com/23484460/48159777-264e9c00-e2a4-11e8-802c-909b2070e40d.png">

**Comment by thekodester** [comment]
The key is having the `<section>` with 'class="lng-ofr"' and the list item ('<li>') with 'class="visible-xs-inline visible-sm-inline"'.

**Comment by duboisp** [comment]
@Pacoup There is no official and specific API that allow you to insert content in the mobile menu. The mobile menu is generated by the [menu.js plugin](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/menu/menu.js)

What you can do is to listen on the menu "ready" event and then use JavaScript to insert your content inside the mobile panel. You can see the HTML structure of the mobile panel via the DOM inspector, the mobile menu are generated at every page load and hidden if you are in a large view port.

@thekodester I don't recommend to mix the alternate language list with the list of user action about session management. Both should be separated. If we follow your suggestion, when the mobile menu are going to be generated, the heading that identify that section would not represent its content.

FYI - The heading level for the section inside the mobile menu panel are mapped to level 3 (```<h3>```)

**Comment by thekodester** [comment]
Like I said in my second comment you can also do this:

```<section class="lng-ofr">
<div style="display: inline-flex;">
<section class="visible-xs-inline visible-sm-inline">
<h3>Language selection</h3>
<ul class="list-inline">
<li><a href="#">Sign out</a></li>
</ul>
</section>
<section>
<h3>Language selection</h3>
<ul class="list-inline">
<li><a lang="fr" hreflang="fr" href="index-fr.html">Français</a></li>
</ul>
</section>
</div>
</section>

**Comment by Pacoup** [comment]
@duboisp How would I go about listening to the menu ready event outside of a WET plugin? Something with wb.ready?

**Comment by duboisp** [comment]
You will need to write some JavaScript. It should look like:

```js
$( document ).on( "wb-ready.wb-menu", ".wb-menu", function( event, instance, settings ) {
  // Your code to insert user session action in the mobile menu here.
});
```

See the events section in the WET menu documentation: http://wet-boew.github.io/wet-boew/docs/ref/menu/menu-en.html

**Comment by thekodester** [comment]
Using this code works:

```
<section id="wb-lng" class="visible-md visible-lg">
  <div style="display: inline-flex;">
    <section class="visible-xs-inline visible-sm-inline">
      <h2>Profile Management</h2>
      <ul class="list-inline">
        <li><a href="#">Sign out</a></li>
      </ul>
    </section>
    <section>
      <h2>Language selection</h2>
      <ul class="text-right">
        <li><a lang="fr" hreflang="fr" href="index-fr.html">Français</a></li>
        <li class="curr">English&#32;<span>(current)</span></li>
      </ul>
    </section>
  </div>
</section>
```

See https://www.thekodester.ca/wet/menu/demo

**Comment by duboisp** [comment]
@thekodester Your code render like this for the mobile menu generated by the menu plugin:

```xml
<section class="lng-ofr">
<h3>undefined</h3>
<ul class="list-inline">
<li><a href="#">Sign out</a></li>
<li><a hreflang="fr" href="#" lang="fr">Français</a>
</li>
</ul>
</section>
```
See the "undefined" header and you can see it mix up the content of both section.

BTY - It would be nice if a simple solution like yours would work.

FYI - In the long term, the mobile menu may stop to be auto-generated at every page load. Instead, the same markup would be reuse in desktop and in mobile. You can see that concept by looking at the new main menu that are going to be launched with the new gcweb look - http://wet-boew.github.io/themes-dist/GCWeb/index-en.html

**Comment by thekodester** [comment]
I didn't notice that. That kinda sucks. Yes the new menu on GCWeb is nicer then the old style.

**Comment by Pacoup** [comment]
Wow... why is the font so big. So many options... I'm not sure this is an improvement. Pretty sure the Amazon menu is not an example to follow. Does anyone even use it? I would think everyone just uses the search.

**Comment by thekodester** [comment]
Thats a fair point of view. I can get why they want to redesign as the current menu is becoming overloaded. There is also this approach https://www.princeedwardisland.ca/ I know there using drupal for content management. Neat thing about the PEI site is the have a search/departments tab, so you can select a different department.

**Comment by duboisp** [comment]
> Wow... why is the font so big.

The whole design concept was done by TBS and mostly based on usability research. [GC-proto/design-refresh](https://github.com/gc-proto/design-refresh/) repository was the project incubator. Me and a few other contributors has worked on implementing that design concept in GCWeb. For the bigger font, I think that was to improve the readability. TBS knows more about the rationale for these changes.

**Comment by Pacoup** [comment]
@duboisp Anyway, I will implement `wb-ready.wb-menu` soon. Given that this answers the question of my issue, I will close this. Thanks for your help.
