### ISSUE TITLE
how to implement dropdown button

### ISSUE THREAD

**Issue by frankding2014** [wet-boew/wet-boew#8512]
Hey folks,
Is there an example to implement a dropdown button like the one report problem button in url  http://wet-boew.github.io/themes-dist/GCWeb/demos/data-json/data-json-en.html  ?

When "Report problem in this page" button is clicked, a group of checkbox  is showed as well as a submit button.

Thanks

**Comment by Pacoup** [comment]
This just looks like a creative use of details / summary. If you're satisfied with the functionality, code like this should work out of the box in WET 4.

``` HTML
<details class="brdr-0">
  <summary class="btn btn-default text-center">Report a problem on this page</summary>
  <div class="well row">
    <div class="gc-rprt-prblm">
      <div class="gc-rprt-prblm-frm gc-rprt-prblm-tggl">
        <form action="#">
          <fieldset>
            <!-- Form fields here -->
          </fieldset>
          <button type="submit" class="btn btn-primary wb-toggle" data-toggle='{"stateOff": "hide", "stateOn": "show", "selector": ".gc-rprt-prblm-tggl"}'>Submit</button>
        </form>
      </div>
      <div class="gc-rprt-prblm-thnk gc-rprt-prblm-tggl hide">
        <h3>Thank you for your help!</h3>
        <p>You will not receive a reply. For enquiries, please <a href="https://www.canada.ca/en/contact.html">contact us</a>.</p>
      </div>
    </div>
  </div>
</details>
```

This is pulled directly from the page you linked. You can then style it as you wish. I think you can even put pretty much anything you want inside the details.

**Comment by frankding2014** [comment]
Thanks. It works.
