### ISSUE TITLE
Field flow "Output Container ID" not working

### ISSUE THREAD

**Issue by agagnon** [wet-boew/wet-boew#8515]
I'm using the field flow plugin and i'm trying to use the "outputctnrid" attribute, but it doesn't seem to be working.

The page is loaded correctly with AJAX, but not in the div#frame, it loads in a new div (default behavior)

`<div id="frame"></div>`
`<li data-wb-fieldflow='{"action": "ajax", "url": "page1.html", "live": true, "outputctnrid": "frame"}'>Page 1</li>`

Am I missing something?

**Comment by duboisp** [comment]
@agagnon the configuration name is ```container``` not ```outputctnrid``` as illustrated by the first working example in the [field flow advanced](http://wet-boew.github.io/themes-dist/GCWeb/demos/fieldflow/advanced-en.html) example page

The ```outputctnrid``` is to defined an container where you want the field flow controls to be rendered inside the page. I sent a PR to update the field flow documentation.
