### ISSUE TITLE
Data tables pagination not needed when only one page

### ISSUE THREAD

**Issue by jkshapiro** [wet-boew/wet-boew#8516]
With the DataTables plugin, when only one page of results is returned, the pagination should be hidden. It's confusing to see a big "1" button that doesn't even do anything.

Screenshot below is from http://wet-boew.github.io/v4.0-ci/demos/tables/tables-en.html with Firefox on Windows:

![screenshot_2018-11-19 tables - working examples - web experience toolkit](https://user-images.githubusercontent.com/3178838/48728122-161eb100-ec02-11e8-8409-cb2fb72a69e6.png)

**Comment by thekodester** [comment]
This is default design on the plugin. Only way to currently remove would be hiding it using JavaScript as the DataTable loads.

See https://stackoverflow.com/a/11050988 for a way to do that.

Another suggestion is bring your concern to the DataTable group.

**Comment by jkshapiro** [comment]
There's a simple solution at https://datatables.net/forums/discussion/46103/hiding-pagination-when-the-table-only-has-a-single-page-when-filtering . Could this be added to WET?

**Comment by jkshapiro** [comment]
Alternatively https://github.com/DataTables/Plugins/blob/master/features/conditionalPaging/dataTables.conditionalPaging.js

**Comment by thekodester** [comment]
There is another easy way to do this by wrapping the code from [Line 138](https://github.com/wet-boew/wet-boew/blob/6dda28ad4d64de6a051cdd7811024a615066f414/src/plugins/tables/tables.js#L138) in that tables.js which recreates the pagination with accessibility, but instead hide it if only one page.

```
	if (paginate_buttons.length < 4) {
		$( ".dataTables_paginate" ).hide(); // make sure is hidden with one page
	} else {
		$( ".dataTables_paginate" ).show(); // make sure is visible

		....other code...
	}
```

**Comment by thekodester** [comment]
What do you think @duboisp ?

**Comment by thekodester** [comment]
@neoinsight

**Comment by duboisp** [comment]
Yes that feature for the datatable can be added, please send a PR.

Regarding which solution to use, some testing would need to be completed like accessibility and performance.

**Comment by neoinsight** [comment]
Nice!

**Comment by thekodester** [comment]
Pull request was created.
