### ISSUE TITLE
Enforce HTTPS on wet-boew.github.io

### ISSUE THREAD

**Issue by obrien-j** [wet-boew/wet-boew#8531]
Apologies if this isn't the best place to raise this issue, but the github host page for the repo seems to not be enforcing HTTPS properly. (80 doesnt' redirect to 443)

https://help.github.com/articles/securing-your-github-pages-site-with-https/

Seems like it's a simple checkbox fix.

Cheers.

**Comment by duboisp** [comment]
Thanks for the suggestion. Not we hare enforcing the https.
