### ISSUE TITLE
How does WET handle multiple languages?

### ISSUE THREAD

**Issue by mikeym88** [wet-boew/wet-boew#8532]
I'm am implementing the WET in a .NET Core application and need to implement multiple languages (English and French). How does WET handle different languages?

I am looking at the [WET website](http://wet-boew.github.io/wet-boew/index-en.html) and I see the following HTML code for switching between English and French; does this imply that there is a web page for each language?

```
<section id="wb-lng" class="visible-md visible-lg">
    <h2>Language selection</h2>
    <ul class="text-right">
        <li><a lang="fr" hreflang="fr" href="index-fr.html">Français</a></li>
        <li class="curr">English&#32;<span>(current)</span></li>
    </ul>
</section>
```

**Comment by RobJohnston** [comment]
There is, but if you're wondering how the WET components know which language to use, it's controlled by the `"lang"` attribute on the `<html>` tag.  View the source to see either `"en"` or `"fr"`.

**Comment by duboisp** [comment]
In addition to @RobJohnston, once WET have detected the current page language, it will download one single JS file (i18n.js) that contains all the translated string for all its plugins.

**Comment by mikeym88** [comment]
Okay thanks!
