### ISSUE TITLE
Question about vue.js and WET

### ISSUE THREAD

**Issue by locutux** [wet-boew/wet-boew#8545]
Hi,

(slightly related to issue #8018, but with Vue.js)

We are in the process of using Vue.js and the WET to create a new website. Unfortunately, when we call certain aspects, like wb-tables or the datepicker, it does not work in IE. the datepicker works in Chrome. I'm not sure if it is the WET's, or Chrome's native handling of date <input>, but the wb-tables with all the filtering and sorting we need do not work in either Chrome or IE.

We read that Vue.js has trouble giving away control of the DOM to jQuery, could that be related?

Thank you for any help you can provide. Have a great day!

**Comment by duboisp** [comment]
> We read that Vue.js has trouble giving away control of the DOM to jQuery, could that be related?

Yes it could be related. WET-BOEW has a hard dependence with jQuery.

Also, the WET-BOEW enhancement happen after the page load and if there any new WET plugin added into the DOM after the WET-BOEW core has notify its readiness ```wb.isReady === true```, those newly added plugin need to be manually initialized.

**Comment by locutux** [comment]
Thank you Pierre. We decided to get rid of Vue.js for the time being. We'll go static pages for now, especially since the application has so few of them. Cheers! :)
