### ISSUE TITLE
Search Defaulting to Basic HTML mode

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew#8550]
Am I the only one who finds that Googling something (that is in Canada.ca) gives them the "Notice: Basic HTML" warning?  It's just ugly, but also it shouldn't be the default for search. 

I'm not sure what the best way to recreate this or how much is a problem with AEM.  

I can't repeat it on a non-canada.ca site so maybe it is just something messy in how they did redirects or something.

**Comment by duboisp** [comment]
I tried some search terms in Google for content that are published on Canada.ca and the description don't include the "Notice: Basic HTML".

Are you able to provide keywords that you have tried or search result links that provided you those kind of result. Thanks

**Comment by mgifford** [comment]
Ahh..  It's just a cookie thing..  Interesting..  Sorry for the noise, I didn't check that.
