### ISSUE TITLE
Canada.ca theme refresh download

### ISSUE THREAD

**Issue by michael-milette** [wet-boew/wet-boew#8551]
Anyone know where I can Git Clone the production files of the refreshed Canada.ca theme?

I would much prefer to Git Clone it so that it can easily be updated however a ZIP file would also do.

Best regards,

Michael

**Comment by duboisp** [comment]
Will be more suitable to ask that kind of question in the [GCWeb repo](https://github.com/wet-boew/GCWeb/issues).

The production files are published in the [themes-dist](https://github.com/wet-boew/themes-dist) repository

**Comment by michael-milette** [comment]
Hi @duboisp 

Thank you very much for the link. That is exactly what I needed.

Best regards,

Michael
