### ISSUE TITLE
New Canada Theme Availability

### ISSUE THREAD

**Issue by idekaresearch** [wet-boew/wet-boew#8562]
The download links for the new Canada theme are broken; could someone update these.
Thanks!

**Comment by duboisp** [comment]
It will be available soon.

**Comment by duboisp** [comment]
The version 5.0.0 of Canada.ca theme (GCWeb) are now published and available for download.

* [Release notes](https://wet-boew.github.io/themes-dist/GCWeb/gcweb-theme/release/v5.0-en.html)
* [Production files](https://github.com/wet-boew/GCWeb/releases/download/v5.0.0/themes-dist-5.0.0-gcweb.zip)
