### ISSUE TITLE
Canada theme: Menu CSS differences between Canada.ca and the downloadable version

### ISSUE THREAD

**Issue by idekaresearch** [wet-boew/wet-boew#8566]
I noticed that the downloaded Canada theme has a blue background for the main Menu drop-down button; whereas on the Canada.ca site the same menu button background is white.

It looks like on the Canada.ca site, the parent <nav> has v2 classes different than the downloaded Canada theme.

Should we use the theme.min.css from the Canada.ca site or the downloaded Canada theme?

**Comment by thekodester** [comment]
Only the landing page has the white background, if you go to for example https://www.canada.ca/en/services/jobs.html. It is the same as the https://wet-boew.github.io/themes-dist/GCWeb/index-en.html.

**Comment by idekaresearch** [comment]
Ok. Got it

**Comment by duboisp** [comment]
Treasury Board Secretariat has provided a few specific styling requirement that only applies to the home page. Having a white background for the main menu button is one of them.
