### ISSUE TITLE
Info Alert About Changes to WET are only in French

### ISSUE THREAD

**Issue by thekodester** [wet-boew/wet-boew#8574]
The info alert about changes to WET are only in French. See https://wet-boew.github.io/wet-boew/docs/versions/dwnld-en.html.

<img width="1161" alt="screen shot 2019-02-17 at 11 20 32 pm" src="https://user-images.githubusercontent.com/23484460/52927895-c9cf3400-330a-11e9-91f5-10c6f6055176.png">

**Comment by thekodester** [comment]
The last link is also only in French.

**Comment by duboisp** [comment]
@thekodester we have just received the English translation and I have a web publisher that is currently working on it. It would be translated soon in English.

**Comment by thekodester** [comment]
Okay thanks!

**Comment by duboisp** [comment]
It is now translated

:-)
