### ISSUE TITLE
Filter: Add max-width on filter input box

### ISSUE THREAD

**Issue by cfarquharson** [wet-boew/wet-boew#8586]
Re the filter script https://wet-boew.github.io/v4.0-ci/demos/filter/filter-en.html , the filter input box stretches the full width of the element it's inside.  In most cases, that would be the full size of the page 1170px.  This creates poor usability on the box, as inputs should be constrained the roughly the size of what the user would be able to put in the box (it would be like an input that is 1000px wide when all it wants in your phone number).  Can you restrict the size to something like max-width: 400px?

**Comment by duboisp** [comment]
Yes, with some development work it is feasible. Like to add a new configuration to specify the width of the input filter and change the filter input template as defined at [Line 86](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/filter/filter.js#L86).
