### ISSUE TITLE
Tables: Adding table rows dynamically via Jquery/Js

### ISSUE THREAD

**Issue by AlexFauteux** [wet-boew/wet-boew#8587]
So I'm using a data table within a form and my client would like to add one/multiple rows before submitting the changes/additions back to the server. With a bit of research I found that data tables can have rows added to them. The issue is how would I do this with the WET plugin of the table since I can't really do what they show [here](https://datatables.net/reference/api/row.add()). 

I've tried a few different things:
`$('#table').row.add([somehtmlElement, "sometext","moretext"]);` 
and
`window["wb-tables"].row.add([somehtmlElement, "sometext","moretext"]);`

I could be completely wrong on my approach though. I've also tried to see if anyone else had a similar issue though i haven't seen anything similar.

Thanks

**Comment by thekodester** [comment]
Maybe try something like:
```
$( document ).on( "wb-ready.wb-tables", ".wb-tables", function( event ) {
			$datatable = $( this ).dataTable( { "retrieve": true } ).api();
			$datatable.row.add(["25","Test"]).draw( false );
		});
```

**Comment by duboisp** [comment]
The following code sample is like how data-json [add new rows](https://github.com/wet-boew/GCWeb/blob/master/src/plugins/data-json/data-json.js#L254-L266) to an already initiated datatables: 

```js
// Retreive the datatables instance
dataTable = $( elm ).dataTable( { "retrieve": true } ).api();

// Add your row - https://datatables.net/reference/api/row.add()
dataTable.row.add( dataArray );

// Refresh the visible table
dataTable.draw();
```

**Comment by AlexFauteux** [comment]
> The following code sample is like how data-json [add new rows](https://github.com/wet-boew/GCWeb/blob/master/src/plugins/data-json/data-json.js#L254-L266) to an already initiated datatables:
> 
> ```js
> // Retreive the datatables instance
> dataTable = $( elm ).dataTable( { "retrieve": true } ).api();
> 
> // Add your row - https://datatables.net/reference/api/row.add()
> dataTable.row.add( dataArray );
> 
> // Refresh the visible table
> dataTable.draw();
> ```

This works great thanks!
