### ISSUE TITLE
wet-boew 3.1 - Filter items box not firing

### ISSUE THREAD

**Issue by oriishi** [wet-boew/wet-boew#8595]
I have a problem with a the feature related to the Basic Enhanced Table (http://wet-boew.github.io/wet-boew-legacy/v3.1/demos/tables/tables-en.html)
The textbox which allows the Search in the table isn't firing when I am entering data. 
I tried to : 
1) upgrade to the version wet-boew 4.0.30, but given the solution I was given, it would create a script conflict between these 2 files : wet-boew.min.js (4.0.30 - Datatable search box works well with it) and pe-ap-min.js (3.1 - needed for the current menu that uses it)

I also tested the code that was from the link, and it still gives me the same type of result.. which I can't identify the cause of it

Edit : My aspx file is using a MasterPageFile

**Comment by duboisp** [comment]
We don't support WET v3.1. My recommendation is to upgrade your website to WET 4.x.

However, that filter box is added in the page by the [datatables.net](http://datatables.net) third party version 1.9.4.

Your browser console and the network monitor can reveal some useful information to help you in finding the cause of it. The validation of your HTML markup could help too. Likely it could be your implementation of wet-boew in your aspx files+MasterPageFile that cause your issue. Take a look if you are experiencing similar issue with other wet-boew plugin.
