### ISSUE TITLE
How do I solve this "Uncaught TypeError: Cannot read property 'appendChild' of null" error?

### ISSUE THREAD

**Issue by samghar1** [wet-boew/wet-boew#8600]
I'm using WET BOEW  * v4.0.26. Everything is working fine the only thing is this error keeps popping up everytime. 

Is there a way to get rid of it or is there a work around it? 

`wet-boew.min.js:formatted:422 Uncaught TypeError: Cannot read property 'appendChild' of null
               at wet-boew.min.js:formatted:422
               at Object.n.addTest (wet-boew.min.js:formatted:158)
               at wet-boew.min.js:formatted:413`

![image](https://user-images.githubusercontent.com/47831796/53991056-f646c680-40e6-11e9-8bef-fb848ea8b210.png)

Appreciate it.

Thanks!

**Comment by duboisp** [comment]
I don't know, we will need more information on how we can reproduce your error like:
* Step by step 
* Browser
* What kind of content you have on your page, any mathml? If so it the page validate.

Regarding that JS it hasn't changed and it is the same code that is used by the latest version of wet-boew (v4.0.30). Can you reproduce your issue with the latest version?
