### ISSUE TITLE
Geomap: Inline table (only) example

### ISSUE THREAD

**Issue by matty-tee** [wet-boew/wet-boew#8607]
Does anyone happen to have a working example of layer data loaded solely from an inline table? (ie: without the use of a config.LANG.js file?) If so, could you please provide a link? I'd like to see how it's set up, as when I remove "layersFile" (leaving just "tables") from my configuration, there are JS errors and everything breaks.

**Comment by jvanulde** [comment]
What version @matty-tee?

**Comment by matty-tee** [comment]
@jvanulde 4.0.30 (CDTS) to be specific, but any 4.0 version might add some insight just by seeing the code.

**Comment by jvanulde** [comment]
@matty-tee the "Static Map Example" in the demo pages are using only inline tables.

**Comment by matty-tee** [comment]
I should have thought to look there. Thanks very much for your help, @jvanulde!!
