### ISSUE TITLE
Click event in navigation - mega menu

### ISSUE THREAD

**Issue by magex9** [wet-boew/wet-boew#8615]
I am having a similar issue to https://github.com/wet-boew/wet-boew/issues/6702 but the comments do not seem to help.

Our application is very form heavy and we require a confirmation from the user where they choose from multiple options and are using the wet4 modal box which is working great and the clients like it.

The only problem is that it doesnt work on the top menu for some reason, but does work on the breadcrumbs, secondary navigation, footer, and very top system links as well.

I have dumbed down our logic to see what is happening and if i put the following code:

```
$('a').each(function(index, el) {
	$(this).hover(function(e) {
		console.log("Hovering: " + $(this).text());
	});
	$(this).click(function(e) {
		e.preventDefault();
		console.log("Clicking: " + this.getAttribute('href'));
	});
});
```

Neither the hovering or the clicking are working for the top menus and the clients would like to have the modal for every link and im not sure how to register with the top menu.

If i remove the data-trgt="mb-pnl" then the events are able to register but the menu doesnt show up.  What is the best way to register the links with my event?

**Comment by thekodester** [comment]
The answer is in https://github.com/wet-boew/wet-boew/issues/6702#issuecomment-94036610

Just need to modify it to your needs:
```
wb.doc.on("click, mouseover", "a[href]", function( event ) {
event.preventDefault();
console.log("Click and Mouseover: " + $(this).text());
});
```

**Comment by thekodester** [comment]
I've updated it some more.

**Comment by magex9** [comment]
Thanks @thekodester that worked, i just needed to change the $('a') to user wb.doc.on(..) instead and everything else worked unchanged.

I read in another issue what wb.doc was the same as the jquery document, but if it was then both methods would work, why is it that i need to use the wb.doc instead of the $ function?  I will need to go through the code to take a closer look at where else we are using it.  We have other applications that use jquery and bootstrap so we will need to figure a way to keep both method working when its wet4 or not.. 

You can close the ticket.

**Comment by thekodester** [comment]
`wb.doc.on` is not really well documented, but https://github.com/wet-boew/wet-boew/wiki/JavaScript-Development talks about it.
