### ISSUE TITLE
Add ability to turn off WET Controls for YouTube videos

### ISSUE THREAD

**Issue by carlod** [wet-boew/wet-boew#8618]
Is there a way to turn off the WET controls and just use the built in YouTube controls when using the Multimedia Player plugin to play YouTube video's?

**Comment by duboisp** [comment]
You can bypass the WET multimedia player by using (with some custom JS) the YouTube API. I suggest you to do a WCAG assessment if your content need to be conform to web accessibility standard such WCAG Level AA, because we have only tested the YouTube player with the WET multimedia wrapper.

**Comment by carlod** [comment]
Okay thanks.
