### ISSUE TITLE
New Style Guide?

### ISSUE THREAD

**Issue by thekodester** [wet-boew/wet-boew#8626]
Please see https://github.com/wet-boew/wet-boew-styleguide/issues/363 for more information.

I'm posting here in hopes that the repo gets more attention. Also if this repo is abandoned maybe the website should be shut down.

@duboisp

**Comment by duboisp** [comment]
@thekodester it is not abandoned but that repository is going stale.

**Comment by thekodester** [comment]
Fixed. Thanks for help @duboisp!
