### ISSUE TITLE
Broken URLs

### ISSUE THREAD

**Issue by jkshapiro** [wet-boew/wet-boew#8632]
Hi there,

I had a link to https://wet-boew.github.io/wet-boew-styleguide/v4/design/buttons-en.html that used to work. It looks as though it's been changed to https://wet-boew.github.io/wet-boew-styleguide/design/buttons-en.html

Would it be possible please to set up a permanent redirect (HTTP 301) for the pages that used to be in the /v4 subfolder?

**Comment by thekodester** [comment]
Permanent redirect is not that simple since the repo was changed to Jekyll (a static page rendering GitHub pages).

Instead I created a PR for a customer 404 error file (https://github.com/wet-boew/wet-boew-styleguide/pull/373)

**Comment by thekodester** [comment]
The error page be same as https://wet-boew.github.io/wet-boew/404, but instead the home page button directs the user to the style guide home page.

**Comment by thekodester** [comment]
You can also learn more about the update at https://github.com/wet-boew/wet-boew-styleguide/pull/364.

**Comment by jkshapiro** [comment]
Thank you very much for the quick response.

**Comment by thekodester** [comment]
Not a problem the page 404 error is now active.

**Comment by RobJohnston** [comment]
Wait... maybe one can do redirects on GitHub with Jekyll:  
https://help.github.com/en/articles/redirects-on-github-pages

**Comment by thekodester** [comment]
You have to create a page for every redirect. Not feasible.

**Comment by thekodester** [comment]
It basically relies on `<meta http-equiv="refresh" content="0;url=URL" />` due to GitHub restrictions (but automated).
