### ISSUE TITLE
Controls in .net adapted for WET

### ISSUE THREAD

**Issue by jpesant** [wet-boew/wet-boew#8636]
For those who work in .net, I realized controls adapted to the WET. The documentation will follow soon. The controls implement client-side validation.
https://github.com/jpesant/wetcontrols

**Comment by duboisp** [comment]
@jpesant that is great, would you like to move your code inside the wet-boew organisation?

**Comment by jpesant** [comment]
@duboisp,  I think it would be a good idea to integrate it in wet-beow organisation.

**Comment by duboisp** [comment]
Here the new repository: https://github.com/wet-boew/wet-boew-dotnet-controls
