### ISSUE TITLE
Question about WET licencing

### ISSUE THREAD

**Issue by jsguy1** [wet-boew/wet-boew#8637]
Hello,

I've been developing my site in WET for the last 3 years on a part time basis.   At last, I'm only a week or two away from going live with it.

Does WET offer any kind of licensing deal where developers can remove the WET references in the source code if they pay a fee?

I'm basically wondering if there is anything I can do to prevent others from copying my web site design.  Given that WET is open source, can someone just copy my design exactly the way it is without legal consequences?

I know that code is ubiquitous but I would like to know what (if anything) I can do to protect my creation.

Thanks

**Comment by thekodester** [comment]
WET uses a MIT license and is free to us AS IS, except the Government of Canada and WET logo. See https://github.com/wet-boew/wet-boew/blob/master/License-en.txt.

**Comment by duboisp** [comment]
as @thekodester said, WET product is licensed under [MIT license](https://github.com/wet-boew/wet-boew/blob/master/License-en.txt).

The [Canadian Intellectual Property Office](http://www.ic.gc.ca/eic/site/cipointernet-internetopic.nsf/eng/home) is the organization with which you can register your intellectual property (IP) assets, including copyright. If you are looking for more legal advise, including [infringement](https://www.ipic.ca/english/what-is-ip/copyright/protection-copyright-infringement.html), you can [contact them](http://www.ic.gc.ca/eic/site/cipointernet-internetopic.nsf/eng/wr04314.html) or you can contact a Canadian law firms specialized in intellectual property.
