### ISSUE TITLE
Share widget: Twitter doesn't work

### ISSUE THREAD

**Issue by Wenifred** [wet-boew/wet-boew#8638]
The Share widget Twitter button doesn't seem to be working anymore, I am running an older version but it is also the case here: https://wet-boew.github.io/v4.0-ci/demos/share/share-en.html

**Comment by thekodester** [comment]
Works fine. It requires the user to login and auto fills a tweets. 

<img width="664" alt="Screen Shot 2019-04-30 at 9 08 51 PM" src="https://user-images.githubusercontent.com/23484460/57002284-43e22b80-6b8c-11e9-9f5b-15644150176c.png">

**Comment by thekodester** [comment]
If you want the tweet to display without logging in see:

https://wet-boew.github.io/v4.0-ci/demos/twitter/twitter-en.html
https://publish.twitter.com/?buttonType=TweetButton&widget=Button

**Comment by Wenifred** [comment]
Thanks, I am still having the issue though, but I understand why now. There is a new version of Twitter, I was using the new one! As soon as I switched back to the legacy version it worked. So the widget doesn't look like it works in the new one it seems :( 
![new-twitter-switch-back](https://user-images.githubusercontent.com/5551287/57036756-33c95b00-6c23-11e9-8b89-4803c560a05e.jpg)
![Twitter](https://user-images.githubusercontent.com/5551287/57036757-3461f180-6c23-11e9-93ab-30349f11777c.jpg)

**Comment by thekodester** [comment]
Yeah same here, but this link works: https://twitter.com/intent/tweet?original_referer=https%3A%2F%2Fpublish.twitter.com%2F%3FbuttonType%3DTweetButton%26widget%3DButton&ref_src=twsrc%5Etfw&text=Twitter%20Publish&tw_p=tweetbutton&url=https%3A%2F%2Fpublish.twitter.com%2F%3FbuttonType%3DTweetButton%26widget%3DButton

So might need to look at changing the link.

**Comment by thekodester** [comment]
Only need https://twitter.com/intent/tweet?text={text}&url={link}.

**Comment by thekodester** [comment]
Opened a PR to fix. :-)
