### ISSUE TITLE
jQuery.validator.setDefaults() submitHandler not getting picked up?

### ISSUE THREAD

**Issue by stego39** [wet-boew/wet-boew#8640]
Trying to override the submitHandler for all forms to disable the submit button and prevent user from clicking submit multiple times. Seems though using the setDefaults on the validator is being ignored, or i'm doing something wrong.

`$(document).on("wb-ready.wb", function (event) {
	$.validator.setDefaults({
		invalidHandler: function(event, validator) {
			console.log("invalid form!");
		},
		 submitHandler: function (form) {
			 console.log("Success");
			 $("button[type=submit]").addClass('disabled');
			 $("button[type=submit]").prop('disabled', true);
	    }
	});`

Not seeing the console log output...

**Comment by RobJohnston** [comment]
Does the example in https://github.com/wet-boew/wet-boew/issues/7716#issuecomment-456461356 help?

**Comment by stego39** [comment]
> 
> 
> Does the example in [#7716 (comment)](https://github.com/wet-boew/wet-boew/issues/7716#issuecomment-456461356) help?

It does a little.. i was looking for a more "global" solution... we have pages with mulitple forms on them, so the above doesnt quite work, and wanted to avoid having to define a bunch of selectors for each form.. unless i'm missing something.

**Comment by stego39** [comment]
Actually seems the technique in this case is to loop through each form object on the page to target its respective submitHandler...

`$('form').each(function() {`

I'll test that out this morning.

**Comment by stego39** [comment]
This seems to do the trick..

`$(document).on("wb-ready.wb", function (event) {
	$("form").each(function() {
		if ($(this).data("validator")) {
		$(this).data("validator").settings.submitHandler = function (form) {
		 $(form).find("button[type=submit]").addClass('disabled');
		 $(form).find("button[type=submit]").prop('disabled', true);
		 form.submit();
	}
		}
	});
});`

Thanks for the help!
