### ISSUE TITLE
Overlay: Title has duplated "Close"

### ISSUE THREAD

**Issue by sam-he** [wet-boew/wet-boew#8669]
Overlay in template from this page
https://wet-boew.github.io/v4.0-ci/demos/overlay/overlay-en.html
For Centred popup (Lightbox) and  Centred popup - Modal (Lightbox + Modal), when mouse over the close button, there are duplicated "Close" from the button title.

<button type="button" class="btn btn-sm btn-primary pull-left popup-modal-dismiss" title="Close Close overlay (escape key)">Close<span class="wb-inv">Close overlay (escape key)</span></button>

It applies to both English and French version.

**Comment by thekodester** [comment]
I can look at this when I have time @duboisp (unless @sam-he wants to fix).

<img width="251" alt="Screen Shot 2019-06-26 at 7 45 55 PM" src="https://user-images.githubusercontent.com/23484460/60222403-3c1ccb80-984b-11e9-9966-42cb968aff43.png">

**Comment by thekodester** [comment]
PR submitted

**Comment by duboisp** [comment]
PR merged.
