### ISSUE TITLE
Overlay: Centred popup - Modal (Lightbox + Modal) - escape key not working

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/wet-boew#8697]
The escape key isn't working to close the Centred popup - Modal (Lightbox + Modal) dialog box.

**Comment by thekodester** [comment]
Yeah that excepted behaviour for the Lightbox + Modal. Was part of the reason why we need an auto generated close button as sometimes it was not being add in a way that was easy to be found.

**Comment by thekodester** [comment]
I we'll change the text of the close button.

**Comment by thekodester** [comment]
PR submitted.
