### ISSUE TITLE
DataTables filter options: Can't return to default view after filtering anything specific

### ISSUE THREAD

**Issue by EricDunsworth** [wet-boew/wet-boew#8708]
We've noticed that in WET DataTables implementations that contain advanced filtering options (e.g. dropdowns, checkboxes, etc...), WET only triggers DataTables filtering if at least one field contains a non-empty value. If all fields contain empty values, nothing happens.

That's problematic in practice. If a user picks specific categories, triggers the filter, then switches back to the default categories and filters again, they'd expect DataTables to go back to showing all entries. But that isn't currently happening. As things stand, their only option would be to click the "Clear" button (whose functionality isn't very obvious - most people probably wouldn't expect that pressing it would instantly modify the results).

To address this, WET should be modified to always trigger DataTables filtering upon clicking the "Filter" button, regardless of whether or not all fields contain empty values.

**How to reproduce:**
1. Visit the [Tables page](https://wet-boew.github.io/v4.0-ci/unmin/demos/tables/tables-en.html)'s "Filtering Example" section.
2. The table will contain a total of 125 entries.
3. In the "Filter Options" panel, set the "Data Type" dropdown to "Speeches" and press the "Filter" button.
4. The table will show 4 out of 4 entries.
5. In the "Filter Options" panel, set the "Data Type" dropdown to "All news types" and press the "Filter" button.

**Expected outcome:**
The table should show 125 entries.

**Actual outcome:**
Nothing happened. The table continued to show 4 out of 4 entries.

**PS:**
Thanks to @fsnoddy and @donmcdill for having initially noticed this :).

**Comment by thekodester** [comment]
Posted a PR to fix.

**Comment by EricDunsworth** [comment]
@thekodester Looks like you beat me to it lol.

I was prepping another PR prior to opening this issue (only opened the issue to separately explain the problem), but IMO what you did is better than what I was gonna do.

My PR was going to move ``$datatable.column( $column ).search( $regex, true ).draw();`` from [line 270](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/tables/tables.js#L270) outside of ``if ( $value ) {...}``. But what you did is simpler and makes more sense :).
