### ISSUE TITLE
Country Content not working - links to freegeoip.net but that site is different now

### ISSUE THREAD

**Issue by cfarquharson** [wet-boew/wet-boew#8710]
The script no longer locates the IP address.  The free site: https://freegeoip.net that it references now has a redirect to another site, so it's not pulling in the IP info and gives the generic message on the demo page.

**Comment by thekodester** [comment]
Looks like they switched to requiring an API Key with an account. There is also now a limit to how many calls are allowed monthly.

See https://github.com/apilayer/freegeoip#readme

**Comment by thekodester** [comment]
You can see the pricing model also at https://ipstack.com/product.

**Comment by thekodester** [comment]
Looks like someone suggested a free alternative at https://github.com/wet-boew/wet-boew/issues/8365

But it was never updated before the shutdown

**Comment by duboisp** [comment]
@louis-galipeau did you team has found an alternate web service to fetch the country content information?
