### ISSUE TITLE
Broken v4.0.31 dist download links

### ISSUE THREAD

**Issue by grapeape69ca** [wet-boew/wet-boew#8726]
Links on https://wet-boew.github.io/wet-boew/docs/versions/dwnld-en.html to the v4.0.31 Production/dist downloads go to a 404 - Not Found page.

**Comment by duboisp** [comment]
@GormFrank est ce que tu peux l'arrangé?

**Comment by GormFrank** [comment]
Actually, it has been fixed a while ago. Can you replicate it?
I tested all the 4.0.31 on that page and did not fall on a 404.

**Comment by grapeape69ca** [comment]
It was fixed.  I downloaded 4.0.31.  Thanks.
