### ISSUE TITLE
Geomap - Help pop-up has no close button

### ISSUE THREAD

**Issue by j769chen** [wet-boew/wet-boew#8735]
When I click on the question mark icon in the top right of the geomap, the "Instructions: Map Navigation" pop up has no X button to close it.

**Comment by juleskuehn** [comment]
That isn't my experience on the [working example](https://wet-boew.github.io/v4.0-ci/demos/geomap/geomap-en.html). What browser are you using?
![image](https://user-images.githubusercontent.com/1150048/66494669-0a401580-ea86-11e9-9956-f9ec64fcd092.png)

**Comment by j769chen** [comment]
I am using Firefox, however the working example works properly for me as well.

**Comment by juleskuehn** [comment]
Hmm.. we would need some more information about how you have implemented it then.
Do you have a link to the site that isn't behaving properly?

**Comment by j769chen** [comment]
Unfortunately no, it is currently on a test server that is only accessible to my team, I can provide the source code snippet, which should be very similar to the working example:

class="wb-geomap position scaleline geocoder"
	data-wb-geomap='{
		"tables": [{
			"id": "bbox",
			"tab": false,
			"zoom": true,
			"popups": true
		},{
			"id": "cities",
			"zoom": true,
			"tab": false,
			"popups": true,
			"popupsInfo": {
				"id": "citiesPopup",
				"height": 150,
				"width": 300,
				"close": true,
				"content": "<div style=\"white-space:nowrap;\"><p><strong>Station: </strong>_Station</div><div style=\"white-space:nowrap;\"><p><strong>Station ID: </strong>_ID</div><div style=\"white-space:nowrap;\"><p><strong>Downloads: </strong>_Downloads</div>"
			},
			"style": {
				"type": "rule",
				"rule": [
				{
					"field": "Data",
					"value": ["Precip"],
					"filter": "EQUAL_TO",
					"init": {
						"strokeColor": "#0083f5",
						"fillColor": "#57a8f0",
						"pointRadius": 5,
						"graphicName": "triangle",
						"fillOpacity": 0.80,
						"strokeWidth": 1.0
					}
				},
				{
					"field": "Data",
					"value": ["Precip/Temp"],
					"filter": "EQUAL_TO",
					"init": {
						"strokeColor": "#F90",
						"fillColor": "#F90",
						"pointRadius": 5,
						"fillOpacity": 0.80,
						"strokeWidth": 1.0
					}
				},
				{
					"field": "Data",
					"value": ["Temp"],
					"filter": "EQUAL_TO",
					"init": {
						"strokeColor": "#F00",
						"fillColor": "#F00",
						"pointRadius": 5,
						"graphicName": "square",
						"fillOpacity": 0.80,
						"strokeWidth": 1.0
					}
				}]
			}
		}]
	}'>

**Comment by duboisp** [comment]
@j769chen do you have a sample data for that working example? It will be hard to reproduce by only adding the config.
Are you saying any error in your browser console for that page? Is that page pass w3c validation? like no duplicate ids or unclosed element.

**Comment by j769chen** [comment]
There are no errors in the console, and it does pass w3c validation. Here is the config with some data points.

 
<div id="map"
	class="wb-geomap position scaleline geocoder"
	data-wb-geomap='{
		"tables": [{
			"id": "bbox",
			"tab": false,
			"zoom": true,
			"popups": true
		},{
			"id": "cities",
			"zoom": true,
			"tab": false,
			"popups": true,
			"popupsInfo": {
				"id": "citiesPopup",
				"height": 150,
				"width": 300,
				"close": true,
				"content": "<div style=\"white-space:nowrap;\"><p><strong>Station: </strong>_Station</div><div style=\"white-space:nowrap;\"><p><strong>Station ID: </strong>_ID</div><div style=\"white-space:nowrap;\"><p><strong>Downloads: </strong>_Downloads</div>"
			},
			"style": {
				"type": "rule",
				"rule": [
				{
					"field": "Data",
					"value": ["Precip"],
					"filter": "EQUAL_TO",
					"init": {
						"strokeColor": "#0083f5",
						"fillColor": "#57a8f0",
						"pointRadius": 5,
						"graphicName": "triangle",
						"fillOpacity": 0.80,
						"strokeWidth": 1.0
					}
				},
				{
					"field": "Data",
					"value": ["Precip/Temp"],
					"filter": "EQUAL_TO",
					"init": {
						"strokeColor": "#F90",
						"fillColor": "#F90",
						"pointRadius": 5,
						"fillOpacity": 0.80,
						"strokeWidth": 1.0
					}
				},
				{
					"field": "Data",
					"value": ["Temp"],
					"filter": "EQUAL_TO",
					"init": {
						"strokeColor": "#F00",
						"fillColor": "#F00",
						"pointRadius": 5,
						"graphicName": "square",
						"fillOpacity": 0.80,
						"strokeWidth": 1.0
					}
				}]
			}
		}]
	}'>
	<div class="row">
		<div class="col-md-9">
			<div class="wb-geomap-map"></div> 
		</div>
		<section class="wb-geomap-legend col-md-3">
		</section>
	</div>

	
	<div class="row">
	<section><div class="wb-geomap-layers col-md-12"><section>
	<br>
	<table id="cities" aria-label="Stations" class="table wb-tables">
	<caption>Table of Stations</caption>
	<thead>
		<tr>
		<th>Station</th><th>Province/Territory</th><th>Data</th><th>ID</th><th>Downloads</th>
		</tr>
	</thead> 
<tbody>
<tr data-geometry="POINT(-121.8 49.2)"data-type="wkt">
<td>AGASSIZ</td><td>BC</td><td>Precip/Temp</td><td>1100120</td>
<td><a href="/files/map/pi_1100120.txt"download>Precip</a> <a href="/files/map/tia_1100120.txt"download>Temp A</a> <a href="/files/map/tib_1100120.txt"download>Temp B</a></td></tr>

<tr data-geometry="POINT(-126.9 50.6)"data-type="wkt">
<td>ALERT BAY</td><td>BC</td><td>Precip</td><td>1020270</td>
<td><a href="/files/map/pi_1020270.txt"download>Precip</a></td></tr>

<tr data-geometry="POINT(-119.2 50.5)"data-type="wkt">
<td>ARMSTRONG HULLCAR</td><td>BC</td><td>Precip</td><td>1160483</td>
<td><a href="/files/map/pi_1160483.txt"download>Precip</a></td></tr>

<tr data-geometry="POINT(-133.7 59.6)"data-type="wkt">
<td>ATLIN</td><td>BC</td><td>Precip/Temp</td><td>1200560</td>
<td><a href="/files/map/pi_1200560.txt"download>Precip</a> <a href="/files/map/tia_1200560.txt"download>Temp A</a> <a href="/files/map/tib_1200560.txt"download>Temp B</a></td></tr>

<tr data-geometry="POINT(-121.5 53.1)"data-type="wkt">
<td>BARKERVILLE</td><td>BC</td><td>Precip/Temp</td><td>1090660</td>
<td><a href="/files/map/pi_1090660.txt"download>Precip</a> <a href="/files/map/tia_1090660.txt"download>Temp A</a> <a href="/files/map/tib_1090660.txt"download>Temp B</a></td></tr>

<tr data-geometry="POINT(-119 49.5)"data-type="wkt">
<td>BEAVERDELL NORTH</td><td>BC</td><td>Precip/Temp</td><td>1130771</td>
<td><a href="/files/map/pi_1130771.txt"download>Precip</a> <a href="/files/map/tia_1130771.txt"download>Temp A</a> <a href="/files/map/tib_1130771.txt"download>Temp B</a></td></tr>

<tr data-geometry="POINT(-126.6 52.4)"data-type="wkt">
<td>BELLA COOLA</td><td>BC</td><td>Precip/Temp</td><td>1060841</td>
<td><a href="/files/map/pi_1060841.txt"download>Precip</a> <a href="/files/map/tia_1060841.txt"download>Temp A</a> <a href="/files/map/tib_1060841.txt"download>Temp B</a></td></tr>

<tr data-geometry="POINT(-123.1 51.7)"data-type="wkt">
<td>BIG CREEK</td><td>BC</td><td>Precip</td><td>1080870</td>
<td><a href="/files/map/pi_1080870.txt"download>Precip</a></td></tr>

<tr data-geometry="POINT(-119.3 52.1)"data-type="wkt">
<td>BLUE RIVER</td><td>BC</td><td>Precip/Temp</td><td>1160899</td>
<td><a href="/files/map/pi_1160899.txt"download>Precip</a> <a href="/files/map/tia_1160899.txt"download>Temp A</a> <a href="/files/map/tib_1160899.txt"download>Temp B</a></td></tr>

<tr data-geometry="POINT(-116.3 50.8)"data-type="wkt">
<td>BRISCO</td><td>BC</td><td>Precip</td><td>1171020</td>
<td><a href="/files/map/pi_1171020.txt"download>Precip</a></td></tr>

<tr data-geometry="POINT(-123.2 49.6)"data-type="wkt">
<td>BRITANNIA BEACH FURRY CREEK</td><td>BC</td><td>Precip</td><td>1041050</td>
<td><a href="/files/map/pi_1041050.txt"download>Precip</a></td></tr>

<tr data-geometry="POINT(-122.9 49.3)"data-type="wkt">
<td>BURQUITLAM VANCOUVER GOLF COURSE</td><td>BC</td><td>Precip</td><td>1101200</td>
<td><a href="/files/map/pi_1101200.txt"download>Precip</a></td></tr>

<tr data-geometry="POINT(-128.4 50.8)"data-type="wkt">
<td>CAPE SCOTT</td><td>BC</td><td>Precip/Temp</td><td>1031353</td>
<td><a href="/files/map/pi_1031353.txt"download>Precip</a> <a href="/files/map/tia_1031353.txt"download>Temp A</a> <a href="/files/map/tib_1031353.txt"download>Temp B</a></td></tr>

<tr data-geometry="POINT(-131 51.9)"data-type="wkt">
<td>CAPE ST JAMES</td><td>BC</td><td>Precip/Temp</td><td>1051350</td>
<td><a href="/files/map/pi_1051350.txt"download>Precip</a> <a href="/files/map/tia_1051351.txt"download>Temp A</a> <a href="/files/map/tib_1051351.txt"download>Temp B</a></td></tr>

<tr data-geometry="POINT(-129.8 59.3)"data-type="wkt">
<td>CASSIAR</td><td>BC</td><td>Precip</td><td>1191440</td>
<td><a href="/files/map/pi_1191440.txt"download>Precip</a></td></tr>

<tr data-geometry="POINT(-119.4 51)"data-type="wkt">
<td>CELISTA</td><td>BC</td><td>Precip</td><td>116146F</td>
<td><a href="/files/map/pi_116146F.txt"download>Precip</a></td></tr>

<tr data-geometry="POINT(-125.4 50.3)"data-type="wkt">
<td>CHATHAM POINT</td><td>BC</td><td>Precip/Temp</td><td>1021480</td>
<td><a href="/files/map/pi_1021480.txt"download>Precip</a> <a href="/files/map/tia_1021480.txt"download>Temp A</a> <a href="/files/map/tib_1021480.txt"download>Temp B</a></td></tr>

<tr data-geometry="POINT(-124.9 49.7)"data-type="wkt">
<td>COMOX</td><td>BC</td><td>Precip/Temp</td><td>1021830</td>
<td><a href="/files/map/pi_1021830.txt"download>Precip</a> <a href="/files/map/tia_1021830.txt"download>Temp A</a> <a href="/files/map/tib_1021830.txt"download>Temp B</a></td></tr>

<tr data-geometry="POINT(-124.9 50.1)"data-type="wkt">
<td>CORTES ISLAND TIBER BAY</td><td>BC</td><td>Precip</td><td>1021960</td>
<td><a href="/files/map/pi_1021960.txt"download>Precip</a></td></tr>

<tr data-geometry="POINT(-115.8 49.6)"data-type="wkt">
<td>CRANBROOK</td><td>BC</td><td>Precip/Temp</td><td>1152102</td>
<td><a href="/files/map/pi_1152102.txt"download>Precip</a> <a href="/files/map/tia_1152105.txt"download>Temp A</a> <a href="/files/map/tib_1152105.txt"download>Temp B</a></td></tr>

<tr data-geometry="POINT(-116.5 49.1)"data-type="wkt">
<td>CRESTON</td><td>BC</td><td>Precip/Temp</td><td>1142160</td>
<td><a href="/files/map/pi_1142160.txt"download>Precip</a> <a href="/files/map/tia_1142160.txt"download>Temp A</a> <a href="/files/map/tib_1142160.txt"download>Temp B</a></td></tr>

<tr data-geometry="POINT(-120.2 51.3)"data-type="wkt">
<td>DARFIELD</td><td>BC</td><td>Precip/Temp</td><td>1162265</td>
<td><a href="/files/map/pi_1162265.txt"download>Precip</a> <a href="/files/map/tia_1162265.txt"download>Temp A</a> <a href="/files/map/tib_1162265.txt"download>Temp B</a></td></tr>

**Comment by j769chen** [comment]
There are no errors in the console, and it does pass w3c validation. Here is the html file with the error.
[geomap.txt](https://github.com/wet-boew/wet-boew/files/3717895/geomap.txt)

**Comment by j769chen** [comment]
I should note that it is missing head, body and doctype tags because that is all automatically done once it is uploaded to the server.

**Comment by jamespardey** [comment]
I'm working on the same site, and I've been running into similar issues. For background, we're using CDTS, currently at version 4.0.31. It appears as if the panel header is overprinting the X:
![Geomap](https://user-images.githubusercontent.com/58827231/70743316-81479380-1ced-11ea-83d5-a8d7f63f05b9.png)

The close link can sometimes be clicked at a location a pixel or two below the panel header.

I've tested this with a number of display widths, and variations on the code. It seems like in all circumstances, this is occurring. Nothing jumped out at me when comparing the CSS attributes via the Firefox inspector to a functional example (on the documentation page), and the element ordering was identical.

Sorry about the length of the following snippet, but it includes the CDTS static content:

```
<!DOCTYPE html><!--[if lt IE 9]><html class="no-js lt-ie9" lang="en" dir="ltr"><![endif]--><!--[if gt IE 8]><!-->
<html class="no-js" lang="en" dir="ltr">
<!--<![endif]-->
<head>
        <meta charset="utf-8">
        <!-- Web Experience Toolkit (WET) / Boîte à outils de l'expérience Web (BOEW) wet-boew.github.io/wet-boew/License-en.html / wet-boew.github.io/wet-boew/Licence-fr.html -->
        <title>GeoMap Bug test</title>
        <meta content="width=device-width,initial-scale=1" name="viewport">
        <meta name="description" content="Climate Modelling and Analysis">
        <script type="text/javascript" src="https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_31/cdts/compiled/soyutils.js"></script>
        <script type="text/javascript" src="https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_31/cdts/compiled/wet-en.js"></script>
        <noscript>
        		<!--[if gte IE 9 | !IE ]><!-->
		<link href="https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_31/assets/favicon.ico" rel="icon" type="image/x-icon">
		<link rel="stylesheet" href="https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_31/css/theme.min.css">
		<link rel="stylesheet" href="https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_31/cdts/cdtsfixes.css">
		<!-- Are you using the application templates? If so add the following CSS file -->
		<!-- <link rel="stylesheet" href="https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_31/cdts/cdtsapps.css">-->
		<!--<![endif]-->
		<!--[if lt IE 9]>
		<link href="https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_31/assets/favicon.ico" rel="shortcut icon" />
		<link rel="stylesheet" href="https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_31/css/ie8-theme.min.css" />
		<![endif]-->
		<!--[if lte IE 9]><![endif]-->
		<link rel="stylesheet" href="https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_31/css/noscript.min.css" />
		<link rel="stylesheet" href="https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_31/cdts/cdtsnoscript.css" /> 
        </noscript>
                <script type="text/javascript">
            document.write(wet.builder.refTop({   
                cdnEnv: "prod"
            }));   
        </script>
        <!-- Custom CSS -->

    </head>
    <body vocab="http://schema.org/" typeof="WebPage">
        <div id="def-top">
        		<ul id="wb-tphp">
			<li class="wb-slc"><a class="wb-sl" href="#wb-cont">Skip to main content</a></li>
			<li class="wb-slc visible-sm visible-md visible-lg"><a class="wb-sl" href="#wb-info">Skip to "About this site"</a></li>
			<li class="wb-slc visible-md visible-lg"><a class="wb-sl" href="#wb-sec">Skip to section menu</a></li>
		</ul>
		<header>
			<div id="wb-bnr" class="container">
				<div class="row">
					<div class="brand col-xs-5 col-md-4" property="publisher" typeof="GovernmentOrganization">
						<a href="https://www.canada.ca/en.html" property="url"></a>
						<img src="https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_31/assets/sig-blk-en.svg" alt="" property="logo" />
						<span class="wb-inv" property="name"> Government of Canada / <span lang="fr">Gouvernement du Canada</span></span></a>
						<meta property="areaServed" typeOf="Country" content="Canada" />
						<link property="logo" href="https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_31/assets/wmms-blk.svg" />
					</div>
					<section class="wb-mb-links col-xs-4 col-sm-3 visible-sm visible-xs" id="wb-glb-mn">
						<h2>Search and menus</h2>
						<ul class="list-inline text-right chvrn">
							<li><a href="#mb-pnl" title="Search and menus" aria-controls="mb-pnl" class="overlay-lnk" role="button"><span class="glyphicon glyphicon-search"><span class="glyphicon glyphicon-th-list"><span class="wb-inv">Search and menus</span></span></span></a></li>
						</ul>
						<div id="mb-pnl"></div>
					</section>
					<section id="wb-srch" class="col-lg-8 text-right visible-md visible-lg">
						<h2>Search</h2>
						<form action="https://www.canada.ca/en/sr.html" method="get" name="cse-search-box" role="search" class="form-inline">
							<div class="form-group">
								<label for="wb-srch-q" class="wb-inv">Search Canada.ca</label>
								<input name="cdn" value="canada" type="hidden">
								<input name="st" value="s" type="hidden">
								<input name="num" value="10" type="hidden">
								<input name="langs" value="en" type="hidden">
								<input name="st1rt" value="1" type="hidden">
								<input name="s5bm3ts21rch" value="x" type="hidden">
								<input id="wb-srch-q" list="wb-srch-q-ac" class="wb-srch-q form-control" name="q" type="search" value="" size="27" maxlength="150" placeholder="Search Canada.ca">
								<input type="hidden" name="_charset_" value="UTF-8">
								<datalist id="wb-srch-q-ac">
									<!--[if lte IE 9]><select><![endif]-->
									<!--[if lte IE 9]></select><![endif]-->
								</datalist>
							</div>
							<div class="form-group submit">
								<button type="submit" id="wb-srch-sub" class="btn btn-primary btn-small" name="wb-srch-sub"><span class="glyphicon-search glyphicon"></span><span class="wb-inv">Search</span></button>
							</div>
						</form>
					</section>
				</div>
			</div>
			<nav id="wb-sm" class="wb-menu visible-md visible-lg" typeof="SiteNavigationElement">
				<div class="container nvbar">
					<h2>Topics menu</h2>
					<div class="row">
						<ul class="list-inline menu">
							<li><a href="https://www.canada.ca/en/services/jobs.html">Jobs</a></li>
							<li><a href="https://www.canada.ca/en/services/immigration-citizenship.html">Immigration</a></li>
							<li><a href="https://travel.gc.ca/">Travel</a></li>
							<li><a href="https://www.canada.ca/en/services/business.html">Business</a></li>
							<li><a href="https://www.canada.ca/en/services/benefits.html">Benefits</a></li>
							<li><a href="https://www.canada.ca/en/services/health.html">Health</a></li>
							<li><a href="https://www.canada.ca/en/services/taxes.html">Taxes</a></li>
							<li><a href="https://www.canada.ca/en/services.html">More services</a></li>
						</ul>
					</div>
				</div>
			</nav>
			<nav id="wb-bc" property="breadcrumb">
				<h2>You are here:</h2>
				<div class="container">
					<div class="row">
						<ol class="breadcrumb">
							<li><a href="https://www.canada.ca/en.html">Home</a></li>
						</ol>
					</div>
				</div>
			</nav>
		</header>        </div> 
        <script type="text/javascript">
            var defTop = document.getElementById("def-top");
   defTop.outerHTML = wet.builder.top({   
                cdnEnv: "prod",
       lngLinks: [{                       
                    lang: "fr",
                    href: "",
                    text: "Français"
       }],                                
                breadcrumbs:[  					{  title: "Home", href: "http://www.canada.ca/en/index.html" }, 
					{  title: "&hellip;" }, 
                ]
   });                                    
        </script> 
<main property="mainContentOfPage" class="container">
 <h1 id="wb-cont" property="name">GeoMap Test</h1>
 
<section>

<div class="row">
    <div id="areaselectmap" 
	  class="wb-geomap position aoi aoi-open"
	  data-wb-geomap='{
	  	"basemap" : {
			"title": "WMS-Toporama",
			"type": "wms",
			"url": "http://wms.ess-ws.nrcan.gc.ca/wms/toporama_en",
			"version": "1.1.1",
			"format": "image/jpeg",
			"layers": "WMS-Toporama",
			"mapOptions": {
			"maxExtent": "-141, 41, -52, 84",
			"restrictedExtent": "-141, 41, -52, 84",
			"maxResolution": "auto",
			"projection": "EPSG:4269",
			"units": "m",
			"displayProjection": "EPSG:4269",
			"aspectRatio": 0.8
		},
			"overlays": []
		}
	  }' >
     <div class="row">
      <div class="col-md-9">
       <div class="wb-geomap-map"></div>
      </div>
	  <div class="wb-geomap-layers col-md-3">
     </div>

    </div>
</div>


 </section>
<div id="def-preFooter">
<div class="pagedetails">
	<div class="row">
		<div class="col-sm-6 col-md-5 col-lg-4">
			<a href="https://www.canada.ca/en/report-problem.html" class="btn btn-default text-center">Report a problem on this page</a>
		</div>
	</div>
	<!-- Share button -->
	<!-- <div class="wb-share col-sm-4 col-md-3 col-sm-offset-2 col-md-offset-4 col-lg-offset-5" data-wb-share=' { "lnkClass": "btn btn-default btn-block" } '></div> -->
	<!-- END Share button -->
	<dl id="wb-dtmd">
		<dt>Date modified: </dt>
		<dd><time property="dateModified">2019-12-12</time></dd>
	</dl>
</div>
</div>
  <!-- Write closure template -->
  <script type="text/javascript">
  var defPreFooter = document.getElementById("def-preFooter");
  defPreFooter.outerHTML = wet.builder.preFooter({ 
    cdnEnv: "prod",
    dateModified: "2019-12-12"
  }); 
  </script>
</main>
     <div id="def-footer">
        		<footer id="wb-info">
			<div class="landscape">
				<nav class="container wb-navcurr">
					<h2 class="wb-inv">About government</h2>
					<ul class="list-unstyled colcount-sm-2 colcount-md-3">
						<li><a href="https://www.canada.ca/en/contact.html">Contact us</a></li>
						<li><a href="https://www.canada.ca/en/government/dept.html">Departments and agencies</a></li>
						<li><a href="https://www.canada.ca/en/government/publicservice.html">Public service and military</a></li>
						<li><a href="https://www.canada.ca/en/news.html">News</a></li>
						<li><a href="https://www.canada.ca/en/government/system/laws.html">Treaties, laws and regulations</a></li>
						<li><a href="https://www.canada.ca/en/transparency/reporting.html">Government-wide reporting</a></li>
						<li><a href="http://pm.gc.ca/eng">Prime Minister</a></li>
						<li><a href="https://www.canada.ca/en/government/system.html">How government works</a></li>
						<li><a href="http://open.canada.ca/en/">Open government</a></li>
					</ul>
				</nav>
			</div>
			<div class="brand">
				<div class="container">
					<div class="row">
						<nav class="col-md-10 ftr-urlt-lnk">
							<h2 class="wb-inv">About this site</h2>
							<ul>
								<li><a href="https://www.canada.ca/en/social.html">Social media</a></li>
								<li><a href="https://www.canada.ca/en/mobile.html">Mobile applications</a></li>
								<li><a href="https://www1.canada.ca/en/newsite.html">About Canada.ca</a></li>
								<li><a href="https://www.canada.ca/en/transparency/terms.html">Terms and conditions</a></li>
								<li><a href="https://www.canada.ca/en/transparency/privacy.html">Privacy</a></li>
							</ul>
						</nav>
						<div class="col-xs-6 visible-sm visible-xs tofpg">
							<a href="#wb-cont">Top of Page <span class="glyphicon glyphicon-chevron-up"></span></a>
						</div>
						<div class="col-xs-6 col-md-2 text-right">
							<img src="https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_31/assets/wmms-blk.svg" alt="Symbol of the Government of Canada" />
							<meta property="areaServed" typeOf="Country" content="Canada" />
							<link property="logo" href="https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_31/assets/wmms-blk.svg" />
						</div>
					</div>
				</div>
			</div>
		</footer>
    </div>
        <script type="text/javascript">
            var defFooter = document.getElementById("def-footer");
   defFooter.outerHTML = wet.builder.footer({     
                cdnEnv: "prod",
                contactLinks: [ { href:"https://www.canada.ca/en/environment-climate-change/corporate/contact.html" } ]
   });                                            
        </script>
        <script type="text/javascript">
   document.write(wet.builder.refFooter({         
                cdnEnv: "prod",
   }));                                           
        </script>

    </body>
</html>
```

**Comment by juleskuehn** [comment]
The GCWeb CSS is causing this. The offending line is:
```css
header {
    position: relative;
}
```

**Comment by jamespardey** [comment]
Thanks so much!

I'm not too familiar with Sass, but that line appears to be from src/banner/_base.scss. Should I report an issue on the GCWeb tracker?

**Comment by juleskuehn** [comment]
@jamespardey That would be perfect. Can you send a link to that issue when you've reported it? Then I will close this one. Thanks!

**Comment by jamespardey** [comment]
Thanks @juleskuehn . The GCWeb issue is https://github.com/wet-boew/GCWeb/issues/1625 .
