### ISSUE TITLE
Grammatical errors in Spanish Session Timeout message

### ISSUE THREAD

**Issue by kombatnt** [wet-boew/wet-boew#8745]
Currently, the Spanish message on the session timeout warning is as follows:

> **Su** sesión expirará automáticamente en X min Y **sec**.
> Seleccione "Continuar sesión" para prolongar **tu** sesión.

A native Spanish speaker in our organization has pointed out that the "sec" abbreviation is inappropriate for Spanish, as the Spanish word for seconds is **segundos**, which would be abbreviated as **seg** rather than **sec**.

In addition, the two phrases are deferentially inconsistent, mixing formal and informal terminology (i.e., **su** vs **tu**). A more formal and grammatically correct phrasing would be as follows:

> **Su** sesión expirará automáticamente en X min Y **seg**.
> Seleccione "Continuar sesión" para prolongar **su** sesión.

**Comment by duboisp** [comment]
Thanks @kombatnt, we will do that text change in the next release of WET
