### ISSUE TITLE
 datalist polyfill (auto-complete) issue in Edge

### ISSUE THREAD

**Issue by nader4** [wet-boew/wet-boew#8748]
![image](https://user-images.githubusercontent.com/16495398/67879810-32f68080-fb03-11e9-9a3b-643b508418be.png)

![wet_ddl_issue](https://user-images.githubusercontent.com/16495398/67879708-093d5980-fb03-11e9-8b08-1e96c7592db6.png)

**Comment by nader4** [comment]
![image](https://user-images.githubusercontent.com/16495398/67902215-4ec34c00-fb2e-11e9-9cb4-00407307d822.png)

**Comment by thekodester** [comment]
Sorry if I wasn't clear, but the Datalist is a polyfill. Polyfill don't run if the browser has a configuration for it.

Since Edge includes datalist configuration WET never loads. WET has no control over an html object when it generated by the browser.

**Comment by thekodester** [comment]
It the same idea when it come to date pickers in forms.

**Comment by thekodester** [comment]
So since the datalist in Edge is being generated by the browser its a Microsoft issue.

**Comment by thekodester** [comment]
Sorry if I wasn't clear, but the Datalist is a polyfill. Polyfill don't run if the browser has a implementation for it.

So since the datalist in Edge is being implemented by the browser and NOT WET its a Microsoft issue.

**Comment by juleskuehn** [comment]
@nader4 Please enter actual text instead of images of text.

**Comment by crazybat** [comment]
FYI, for accessibility reasons, please type the text out in the input field. Those who rely on screen readers to access this content will only hear the word "image" instead of what is in the screenshot.

**Comment by nader4** [comment]
Hi Kody,

I understand now. Thanks again for highlighting the real underlying issue.  I will send a ticket to microsoft and close this ticket.

Thanks,

Nader
