### ISSUE TITLE
"Share This Page" Digg link is broken

### ISSUE THREAD

**Issue by muling** [wet-boew/wet-boew#8751]
When you click on Digg, you get this error message:

![image](https://user-images.githubusercontent.com/2365028/67985402-2c4d3380-fbff-11e9-9399-445b7da8b595.png)

**Comment by juleskuehn** [comment]
Confirmed

**Comment by thekodester** [comment]
Looks like the solution is to just remove Digg. There are going through a change.

They haven't been greatly vocal about it, but here there about page states "...Re-re-founded in 2019, Digg provides..." and "How You Can Contact Us Please don't. We're busy."

https://digg.com/about
