### ISSUE TITLE
Text highlighting

### ISSUE THREAD

**Issue by jkshapiro** [wet-boew/wet-boew#8755]
Am comparing https://wet-boew.github.io/wet-boew-styleguide/design/textediting-en.html#marked and https://wet-boew.github.io/v4.0-ci/docs/ref/texthighlight/texthighlight-en.html. The latter uses a brighter yellow. Shouldn't they be the same?

**Comment by thekodester** [comment]
There not the same thing, but I can see the confusion.

This page https://wet-boew.github.io/wet-boew-styleguide/design/textediting-en.html#marked is using `<mark></mark>`.

This page https://wet-boew.github.io/v4.0-ci/docs/ref/texthighlight/texthighlight-en.html is using `<code></code>`

###### I am just a volunteer on this GitHub project.

**Comment by duboisp** [comment]
@thekodester the other example is this one with the highlight: https://wet-boew.github.io/v4.0-ci/demos/texthighlight/texthighlight-en.html?txthl=avian%20influenza+world+cook+flu-like%20symptoms+Don%27t%20Forget...+causes%20sickness%20in%20birds,%20it%20can%20also%20infect%20people.#example

**Comment by duboisp** [comment]
Todo:

* [ ] Evaluate the contrast ratio of both example: ```<mark>highlighting</mark>``` vs ```<mark class="txthl">highlighting</mark>```

* [ ] Is the color respect the [SC 1.4.11 : Non- text contras](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html)? What would be the best hightlight color?

* [ ] Submit a PR that would normalized the style for the ```mark``` element which will be the same in both example

* [ ] Submit a PR that would removed the need to use a special CSS class ```txthl```
