### ISSUE TITLE
CDN Server for Mega-menu down

### ISSUE THREAD

**Issue by YanicSirois** [wet-boew/wet-boew#8756]
It seems that servers for those CDNs are down.

https://cdn.canada.ca/gcweb-cdn-live/sitemenu/sitemenu-fr.html
and
https://cdn.canada.ca/gcweb-cdn-live/sitemenu/sitemenu-en.html

Is it temporary or is there a replacement link?

Thanks.

**Comment by EricDunsworth** [comment]
@duboisp @GormFrank FYI.

wet-boew/GCWeb#1616 is also reporting a similar issue on the same subdomain.

**Comment by duboisp** [comment]
@YanicSirois thanks for reporting, we are looking at this.

**Comment by duboisp** [comment]
@YanicSirois the CDN link is now working,

FYI - We, Principal Publisher, are looking for an alternative solution. The URL might change in a near future.
