### ISSUE TITLE
datepicker allows for 6 digit years with keyboard entry

### ISSUE THREAD

**Issue by AtomicNumber28** [wet-boew/wet-boew#8764]
https://wet-boew.github.io/wet-boew/demos/datepicker/datepicker-en.html

users are allowed to enter unrealistic dates ie 200000 - min="2013-03-27" max="2013-05-07" values don't block users from entering these unrealistic looking dates

internet explorer doesn't seem to offer any of this functionality compared to chrome/firefox

**Comment by juleskuehn** [comment]
The date picker polyfill only runs in Internet Explorer. The behaviour you are seeing is native to Chrome or Firefox native `<input type='date'>` implementation, and doesn't have to do with WET.
