### ISSUE TITLE
Lightbox: 

### ISSUE THREAD

**Issue by RoyKressin** [wet-boew/wet-boew#8778]
question:  using WET IV Modal Dialog the background colour is all black.  How to set opacity of the background colour from javascript ?   thx

**Comment by thekodester** [comment]
You can just apply a css override with:
```
.mfp-bg {
background: #000;
opacity: .50;
}
```
But be aware the Lightbox hides the page content, so changing the opacity isn't going to show the page. If you want the page to show you have to use a css override:
```
body.wb-modal summary, body.wb-modal > #wb-tphp, body.wb-modal > footer, body.wb-modal > header, body.wb-modal > main {
    visibility: visible;
}
```

**Comment by thekodester** [comment]
You can just apply a css override with:
.mfp-bg {
background: #000;
opacity: .50;
}
But be aware the Lightbox hides the page content, so changing the opacity isn't going to show the page.

**Comment by thekodester** [comment]
If your not using the Lightbox for a image, there are overlays already that allow you to see the page: https://wet-boew.github.io/v4.0-ci/demos/overlay/overlay-en.html

**Comment by RoyKressin** [comment]
terrific. I'll try these next week.

**Comment by RoyKressin** [comment]
override works fine. thx very much
