### ISSUE TITLE
Tabbed interface - Summary link

### ISSUE THREAD

**Issue by jwilliams8** [wet-boew/wet-boew#8779]
Does anyone know if it's possible to turn one of the tabs in the tabbed interface into a link? The end goal would be to have regular content in the first 4 tabs, but the 5th tab wouldn't actually have content in the details tag, just a link within the summary tag that would bring the user to another page.

Simple example:

```
<div class="wb-tabs">
	<div class="tabpanels">
		<details id="details-panel1">
			<summary><p><a href="http://www.google.com">Google</a></p></summary>
		</details>
	</div>
</div>
```
When I add a link in the summary tab it doesn't function as a normal link but rather cycles through any other tabs that are present when clicked.

I know what I'm looking for isn't intended functionality, but if anyone has any ideas it would be greatly appreciated.

**Comment by juleskuehn** [comment]
I think this would confuse users.

**Comment by jwilliams8** [comment]
Great points juleskuehn, I agree. Case closed.
