### ISSUE TITLE
New to WET - Need Further Guidence

### ISSUE THREAD

**Issue by qfung** [wet-boew/wet-boew#8784]
Hello WET Team
I am looking to utilize WET in a web project I working on for the GoC.
Very new to the framework and need further guidance on implementation.
I look through the website and I cannot find a specific code snippet on how to hook up the CSS and JS files, and there is a lot of CSS and JS within WET, so I am confused.

I have prior experience with Aurora and Bootstrap.

**Comment by joel-osc** [comment]
As someone that has built a lot of GC wxT sites I would recommend starting with https://www.drupal.org/project/wxt unless you have a very, very unique set of requirements. This distribution is becoming the standard in GC for CMS as it incorporates WxT and hits multilingual and accessibility standards. As well it is very flexible and open source. Note that I do not work for the WxT team at TBS so I am not speaking on behalf of them.

**Comment by qfung** [comment]
@joel-osc Thank you for getting to me so quick! I am looking to use WET to develop user interfaces developed using native HTML/CSS/JS. Not sure if Drupal would be the way to go for this project.

**Comment by joel-osc** [comment]
DrupalWxT allows that... you need to consider your current and future requirements. For example:

-  will the site have content that non-developers should be able to maintain by logging in and changing it with a nice WYSIWYG editor? 
- should the end client be able to fix a translation without calling a dev? 
- will the site ever have other features that require login from people with different roles?
- will the site have forms? Will they connect to another system via API?
- etc... the list is long.

These are all things that DrupalWxT can do without a line of code!

From our work with TBS I know they are looking for some sort of standardization on web properties and are looking to Drupal for that. Again, it won't fit all requirements but it is super-powerful and a great foundation for being able to turn around features quickly and future-proof yourself for the ones you don't even know yet.

**Comment by qfung** [comment]
@joel-osc For the current project I am working on does not have non developers needing a login page and there is no role assignment, it is nothing too complex, but it does require the WET framework, and it does require a solution that is coded.

**Comment by juleskuehn** [comment]
Hi @qfung 
I keep meaning to post this on the WET documentation page...
**WET / GCWeb quick start guide**
1.	Download themes-dist-5.0.1-gcweb.zip and unzip
2.	Copy the wet-boew and GCWeb folders into your project (public) root
3.	Begin your HTML page with the following code, adding your own content such as <title>
```html
<!DOCTYPE html><!--[if lt IE 9]><html class="no-js lt-ie9" lang="en" dir="ltr"><![endif]--><!--[if gt IE 8]><!-->
<html class="no-js" lang="en" dir="ltr">
<!--<![endif]-->
<head>
<meta charset="utf-8">
<meta content="width=device-width,initial-scale=1" name="viewport">
<!--[if gte IE 9 | !IE ]><!-->
<link href="./GCWeb/assets/favicon.ico" rel="icon" type="image/x-icon">
<link rel="stylesheet" href="./GCWeb/css/theme.min.css">
<!--<![endif]-->
<!--[if lt IE 9]>
    <link href="./GCWeb/assets/favicon.ico" rel="shortcut icon" />
    <link rel="stylesheet" href="./GCWeb/css/ie8-theme.min.css" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="./wet-boew/js/ie8-wet-boew.min.js"></script>
    <![endif]-->
    <!--[if lte IE 9]>
    <![endif]-->
<noscript><link rel="stylesheet" href="./wet-boew/css/noscript.min.css" /></noscript>
</head>
```
4.	Before the closing </body> tag, add the following scripts:
```html
  <!--[if gte IE 9 | !IE ]><!-->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.js"></script>
  <script src="./wet-boew/js/wet-boew.min.js"></script>
  <!--<![endif]-->
  <!--[if lt IE 9]>
  <script src="./wet-boew/js/ie8-wet-boew2.min.js"></script>
  <![endif]-->
  <script src="./GCWeb/js/theme.min.js"></script>
```

**Comment by qfung** [comment]
@juleskuehn Thank you so much for the code snippet!!

**Comment by duboisp** [comment]
@qfung There is also a quick implementation guide for the Canada.ca Theme here: https://wet-boew.github.io/themes-dist/GCWeb/gcweb-theme/implementing.html
