### ISSUE TITLE
Customize Overlay Close Button Location

### ISSUE THREAD

**Issue by qfung** [wet-boew/wet-boew#8786]
Hi again, WET Team,
I am wondering if there is anyway to change the location of the close button of the overlay? I reviewed the style guide several times and cannot find a way to do this.

Thank you for looking into this!

**Comment by thekodester** [comment]
Which close button? The ‘X’ or footer button?

**Comment by qfung** [comment]
Sorry, I should specify it is the footer button.
![overlay](https://user-images.githubusercontent.com/37078772/70668328-7e3a9d80-1c30-11ea-82de-44b5f92c4cc6.PNG)

**Comment by thekodester** [comment]
> Adding custom close buttons to overlays/modals
> 
> Overlays/Modals through JavaScript are automatically updated with a close overlay/modal button. This button can be changed with the following code:
> 
> <div class="modal-footer">
> ...
> <button class="btn btn-primary popup-modal-dismiss" type="button">Close overlay/modal</button>
> </div>
> Side Note: Close buttons must be inside the modal footer (a div with the class modal-footer).
> 
> https://wet-boew.github.io/v4.0-ci/demos/overlay/overlay-en.html

**Comment by qfung** [comment]
What happens if the close button is not inside the modal footer?
I am looking to put a close button near the top of the overlay... so not sure if that would be a problem.

**Comment by thekodester** [comment]
They already have a button at the top right the 'X'.

The button is in the footer for accessibly reasons as the top is harder for non-visual users when in mobile device.

**Comment by qfung** [comment]
I'll leave the close button the way it is then.
Thank you for looking into this!
