### ISSUE TITLE
Infinite loading/refreshing using Webpack and Vue

### ISSUE THREAD

**Issue by TeamDman** [wet-boew/wet-boew#8792]
I'm new to WET, and am now trying to convert my existing Vue application to use some WET features.

Issue: once the `wet-boew.js` is added to the page source, the page will never finish loading and will instead keep refreshing.

Diagnosis: The `wet-boew.js` adds a request for `wet-boew/js/i18n/en.js`, and once it completes, the `wb.start()` method is called. Through some mechanism this caused the page to keep reloading its contents.

Solution:
Apparently I only copied the `wet-boew` and `theme-wet-boew` folders to the `public/` directory.
Because everything else was missing, a request to `ajax/sitemenu-en.html` was failing and using the `index.html` as a fallback. This caused the page to keep reloading the `wet-boew.js` script, ad nauseam.

Fixed by ensuring that everything from the WET distribution folder was copied into `public/` properly. Creating this issue hoping it helps someone in the future.

**Comment by TeamDman** [comment]
Note: make sure that the history API isn't redirecting fallbacks to the index page.
When WET attempts to load ajax stuff that doesn't exist, it will fail by trying to use the index page as a response and will clear the entire DOM.
Making sure the ajax requests fail with a 404 makes things work smoothly.

```javascript
module.exports = {
	devServer: {
		historyApiFallback: false,
	},
};
```

**Comment by fish4ali** [comment]
Hello, 

I am trying to integrate WET (specifically the GCWeb Canada.ca theme) into my Vue/Nuxt application as well, do you have any documentation on how you achieved this? 

Thanks!

**Comment by TeamDman** [comment]
I no longer have access to the codebase, but would recommend checking out CDTS instead of trying to bundle WET in your static assets.

https://cenw-wscoe.github.io/sgdc-cdts/docs/internet-docwrite-en.html

Can't remember any additional info about how I fixed this issue unfortunately

**Comment by fish4ali** [comment]
Thank you for your response, seems like a great resource. I'll see what I can do
