### ISSUE TITLE
v4.0.32 wet-boew.js issue cannot read property url of undefined

### ISSUE THREAD

**Issue by kieran-github** [wet-boew/wet-boew#8795]
When using release 4.0.42 I am receiving an error cannot read property URL of undefined in wet-boew.js . See attached screenshot. 

![imagewetboewerror](https://user-images.githubusercontent.com/32347545/71294221-d6b31e80-2345-11ea-9e24-14401318346b.PNG)

**Comment by juleskuehn** [comment]
Can you provide more info, ideally a link to the page in question? Thanks.

**Comment by duboisp** [comment]
@kieran-github Can you confirm the version, because 4.0.42 is not released yet. Also, what browser you are using? Do you see that error in every pages or only for one specific page? Do you have an URL or a code sample?

**Comment by wonggra** [comment]
This is happening for me as well. It is occuring on every page when using wet-boew 4.0.32

**Comment by GormFrank** [comment]
As this been fixed since then? We're at v4.0.35 (STR) now.
