### ISSUE TITLE
Unable to get property 'innerHTML' of undefined or null reference

### ISSUE THREAD

**Issue by saketh2341** [wet-boew/wet-boew#8796]
<!DOCTYPE html>
<html>
    <head>

    </head>
    <body >
         chat app
         <div id="messages"> 
         </div>
         <form action="" id="message">
             <input type="text">
             <button >submit</button>
         </form>
         <button id="location">send location</button>
        
         <script id="message-template" type="text/html">
            <div>
                <p>hello</p>
            </div>
            </script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/mustache.js/3.1.0/mustache.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/qs/6.6.0/qs.min.js"></script>

        <script src="/socket.io/socket.io.js" ></script>
        <script src="/js/chat.js"></script>
    </body>
</html>

(js file)
const messages=document.querySelector("#messages")

let messagetemplate=document.querySelector('message-template').innerHTML

socket.on('message',(message)=>{
console.log(message)
const html=Mustache.render(messagetemplate)
messages.insertAdjacentHTML('beforeend',html)

})

**Comment by thekodester** [comment]
This code is missing the hashtag/pound key:

`let messagetemplate=document.querySelector('message-template').innerHTML`
