### ISSUE TITLE
Session Timeout with older WET version on .net 4.7

### ISSUE THREAD

**Issue by vankaikura** [wet-boew/wet-boew#8804]
Hello

Upgrading a site to .NET 4.7 from 4.5 that was originally developed by someone else, WET seems to be v4.0.12 ( I know its old). I haven't changed any WET or GCWeb code even with the session timeout plugin I am having trouble with.

The timeout dialog appears in few seconds with this code in 4.7
` <span class="wb-sessto" data-wb-sessto='{"inactivity": 900000, "reactionTime": 180000, "sessionalive": 900000, "logouturl": "<%=["LogOutUrl"]%>", "refreshCallbackUrl": "<%=Request.ApplicationPath%>/api/session/isalive", "method": "GET"}'></span>`

Runs fine with 4.5 .

The plugin doesn't kick in if I modify the above line to
`<span class="wb-sessto" data-wb-sessto='{"logouturl": "<%=["LogOutUrl"]%>"}'></span>`

   
Inactivity or sessionAlive = IIS session timeout - reactionTime is True.

Any ideas?

**Comment by RobJohnston** [comment]
I would be looking to confirm that the session length in the web.config matches (seems like it should be 15 + 3 minutes).  Also, confirm that the /api/session/isalive controller return the word "true" and nothing more.

**Comment by vankaikura** [comment]
After playing with some other numbers, introducing units. It seemed to be fixed, weirdly. Publishing and coding is being done using VS 2017, have experienced annoying issues with CSS and JS when publishing the project.

Thanks for your help.
