### ISSUE TITLE
Angular

### ISSUE THREAD

**Issue by mrlukrative** [wet-boew/wet-boew#8816]
Hello,

Do you have plans to support the current versions of Angular ?

**Comment by duboisp** [comment]
No there is no plan for WET 4. The next, in development, version of WET (WET 5) would be better structured to provide more guidance on how to create a Angular variant or a ReactJS variant but it will remain out of scope.

**Comment by GormFrank** [comment]
@mrlukrative Hope this answers your question. Can this issue be closed? Thank you!

**Comment by mrlukrative** [comment]
Hi Francis,

Yes it does. You may close it.

Thanks.
Andre

________________________________
