### ISSUE TITLE
TinyMCE Editor Conversion - Exploratory challenge

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/wet-boew#8819]
Related to #836 and #7547 (among others).  There's a new challenge starting at TopCoder:

> A series of challenges to rewrite [TinyMCE ](https://github.com/tinymce/tinymce) will be launched shortly. The first challenge will be an ideation challenge to analyze the source code of TinyMCE and brainstorm how to rewrite it properly. The final code will be open-sourced eventually. If you know Typescript/Javascript but are not familiar with TinyMCE and want to contribute to the open-source, it is the right time to jump in.

More details here:  https://www.topcoder.com/challenges/30113382

> **Basic Requirements**: Explore a way to replace the TinyMCE editor with a new open-source editor. It should cover all the existing functionalities of TinyMCE.

If you think WET needs a WYSIWYG editor, this may be the chance to influence the design.  Don't hesitate to register! You've got 2 1/2 days left for this first part, and a chance to win up to $1500 USD.

**Comment by juleskuehn** [comment]
Cool! Personally, I think it would be more useful to contribute to CKEditor as it has much better accessibility.

**Comment by RobJohnston** [comment]
That's the point... this is the chance to get on-board early to influence what "brainstorm how to rewrite it properly" means.

**Comment by RobJohnston** [comment]
There were 33 registrants, 6 submissions, and [2 winners were announced](https://www.topcoder.com/challenges/30113382?tab=winners) sharing $2,250 in prize money.  

If I see the next stage of the competition come up, which should reveal the design to those of us who didn't submit a solution, I'll post it.
