### ISSUE TITLE
Lightbox: Is it possible to have options of "Yes" "No" button instead of "close" on the lightbox

### ISSUE THREAD

**Issue by kitana-ifbbpro** [wet-boew/wet-boew#8822]
I want to be able to have a button "Yes" and a button "No" on the lightbox pop up. If the user click on "Yes", the pop up closes and continues whatever he was doing on the page. 

If he says no: then he is being redirected to another page. I've tried to look through the style guide and working example, but I can't seem to find anything that come close to what I need. Thank you so much.

**Comment by thekodester** [comment]
I would use the Centred popup - Modal (Lightbox + Modal) and just change the footer buttons (Read the ‘Adding custom close buttons to overlays/modals’).

https://wet-boew.github.io/v4.0-ci/demos/overlay/overlay-en.html

**Comment by duboisp** [comment]
Having your own button might require you to write some custom javascript for it

**Comment by kitana-ifbbpro** [comment]
@thekodester Thank you!
By using the footer buttons, I was able to have my own buttons instead of the default close button!
