### ISSUE TITLE
Language interpolation fails scripts loading

### ISSUE THREAD

**Issue by s-laugh** [wet-boew/wet-boew#8842]
When loading a page with the `lang="en-CA"` set, CDTS trys to load scripts that don't exist.

I had set the default language attribute to `en-Ca` on my page in the `html` element like:
```html
<html lang="{{ site.lang | default: 'en-Ca' }}" xmlns="http://www.w3.org/1999/xhtml" class="no-js" dir="ltr">
```

Which ended up returning this issue:
> SEC7112: Script from https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_32/js/i18n/en-Ca.min.js was blocked due to mime type mismatch
> 2 HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
GET - https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_32/js/i18n/en-Ca.min.js

Which causes features in WET to stop working.

I think it would make sense to have some interpolation on the `lang` element to know that if `en-CA` is entered the `en.min.js` script should be loaded; not the `en-CA.min.js`.

**Comment by ipaksc** [comment]
@s-laugh The has been transferred to WET project

**Comment by RoxannaBatista** [comment]
Is there an ETA for supporting different `lang` values?

When building a portal using Microsoft’s Power Platform the language code has to be either `en-US` or `fr-FR` instead of what wet-boew uses (“en”/”fr”) and unfortunately this is tied to MS's multi-language support so it cannot be changed. 

Right now we are getting an error because `wet-boew.min.js` is trying to get the files `en-US.min.js` and `fr-FR.min.js` which don’t exist.

**Comment by killerrin** [comment]
We're running into the same issue as @RoxannaBatista within our apps. We've hacked together a solution that involves manually referencing the proper files in the footers. However it's not exactly an ideal "long-term" solution given that WET is still throwing 404 errors in the console as it tries, and fails to load the `en-US.min.js` and `fr-FR.min.js` files. And it would require a manual intervention should the versioning change.

I think probably the easiest fix for this would be to just have a copy of the specified files hosted on the canada.ca site under those filenames. Or alternatively, maybe an internal redirect for `en-US.min.js`  -> `en.min.js` and  `fr-FR.min.js` -> `fr.min.js`

Another option could be having a switch statement in the code where it auto-loads the assembly where it looks for common mappings eg: `en-US`, `en-CA`, `fr-FR` ,`fr-CA`; then just substitutes it for `en` or `fr`.

**Comment by EricDunsworth** [comment]
@fsnoddy and I were thinking that maybe the best course of action could be to add a ``data-*`` attribute (like ``data-wb-lang`` or ``data-lang``) on the ``<html>`` element to specify a WET-specific language code.

So for example, using something like this in HTML pages:
```html
<html lang="en-CA" data-wb-lang="en" ...>
```

And modifying [WET core's language declaration](https://github.com/wet-boew/wet-boew/blob/db90ce823ecdef1b6de5eae3992505f2bf6ece3f/src/core/wb.js#L67) to something along these lines:
```js
lang = (document.documentElement.dataset.wb-lang) ? document.documentElement.dataset.wb-lang : document.documentElement.lang;
```

@s-laugh @RoxannaBatista @killerrin Would that kind of solution work for all of you? Or are some of you stuck with web platforms/frameworks that are too limited to add extra attributes to the ``<html>`` element?

**Comment by RoxannaBatista** [comment]
@EricDunsworth yes, this would totally work for us! Power Apps already adds a `data-lang` attribute to the `html` element and we can actually change its value to "en" or "fr" so this is perfect. We can also just add a new `data-wb-lang` attribute.

**Comment by killerrin** [comment]
@EricDunsworth As Roxanna says, for us working with PowerApps this would work for us. We have JavaScript access and can specify content to go within the `<head>` tag on a website. So we should be able to inject a new attribute for `data-wb-lang` into the `<html>` tag.

Another alternative which could also work is specifying something like `<meta name="wb-lang" content="[en/fr]">` in the `<head>` tag. Perhaps something like this would work better for lower-code/limited systems that are required to use WET?

**Comment by s-laugh** [comment]
We'd have no issues with that solution.

**Comment by EricDunsworth** [comment]
Thanks for the super quick follow-ups! Just opened #9272 to pitch our solution :).

> @EricDunsworth yes, this would totally work for us! Power Apps already adds a `data-lang` attribute to the `html` element and we can actually change its value to "en" or "fr" so this is perfect. We can also just add a new `data-wb-lang` attribute.

@RoxannaBatista I ended up going with ``data-wb-lang`` since its name makes it clear that it's WET-specific. I have a feeling that PP would prefer that kind of naming scheme too.

> Another alternative which could also work is specifying something like ``<meta name="wb-lang" content="[en/fr]">`` in the ``<head>`` tag. Perhaps something like this would work better for lower-code/limited systems that are required to use WET?

@killerrin I wouldn't have any concerns with that either. But felt like the ``data-wb-lang`` attribute was probably the most obvious way of dealing with it. I don't mind amending my PR to use a ``meta`` element if PP prefers that way though.

**Comment by killerrin** [comment]
@EricDunsworth No worries, the `data-wb-lang` should be fine for us in PP. I was mostly just thinking aloud alternate ways it could be done.
