### ISSUE TITLE
Customazing an overlay 

### ISSUE THREAD

**Issue by hilaryd198** [wet-boew/wet-boew#8847]
I am learning to use wet toolkit. I am  trying to make an overlay modal popup for message confirmation when a user click on delete button. I want to customize the close button by changing it value  to Cancel and add a second button with value OK. I will appreciate if some can show me how to do that with an exemple.

**Comment by thekodester** [comment]
It is discussed how to replace the footer buttons on https://wet-boew.github.io/v4.0-ci/demos/overlay/overlay-en.html under the section "Adding custom close buttons to overlays/modals"

But here is a demo:
Code
```
<p><a href="#delete-record-modal" aria-controls="delete-record-modal" class="wb-lbx lbx-modal" role="button">Delete Record</a></p>
<section id="delete-record-modal" class="mfp-hide modal-dialog modal-content overlay-def">
<header class="modal-header">
<h2 class="modal-title">Are you sure?</h2>
</header>
<div class="modal-body"><p>You are about to delete this record.</p></div>
<div class="modal-footer">
<button class="btn btn-warning pull-left" type="button">Ok</button>
<button class="btn btn-default pull-left popup-modal-dismiss" type="button">Cancel</button>
</div>
</section>
```
Image:
<img width="613" alt="Screen Shot 2020-04-03 at 1 42 15 AM" src="https://user-images.githubusercontent.com/23484460/78328207-9ec69480-754c-11ea-9e43-95bbea098c55.png">

**Comment by hilaryd198** [comment]
I am trying to customize this modal overlay without a background. but this want i get. I went through the documentation I could not find a way to solve.

This is the code 

`<p><a href="#delete-record-modal" aria-controls="delete-record-modal" class="overlay-lnk  overlay-def " role="button">Delete Record</a></p>
<section id="delete-record-modal" class="wb-overlay modal-content overlay-def">
    <header class="modal-header">
        <h2 class="modal-title">Are you sure?</h2>
    </header>
    <div class="modal-body">
        You are about to delete this record.
    </div>
    <div class="modal-footer">
        <button class="btn btn-warning pull-left" type="button">Ok</button>
        <button class="btn btn-default pull-left popup-modal-dismiss" type="button">Cancel</button>
    </div>
</section>`

<img width="350" alt="Capture22" src="https://user-images.githubusercontent.com/14850023/78708149-a933b600-78df-11ea-887e-7860652ab54f.PNG">

**Comment by thekodester** [comment]
I cannot see your code, but the cancel button must have `popup-modal-dismiss` class.

Please see https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks, this way your code is viewable.

**Comment by thekodester** [comment]
If you want to change background of modal popup that we'll require CSS.

**Comment by GormFrank** [comment]
@hilaryd198 There is the `overlay-bg` class available to you in order to add a black background. If this is something else you want, like @thekodester mentioned it will have to be custom. However, depending on what it is, if you think it could benefit others you should consider contributing to WET to add those styles or feature.

Thank you!
