### ISSUE TITLE
Close overlay modal using JQuery

### ISSUE THREAD

**Issue by hilaryd198** [wet-boew/wet-boew#8848]
I have implement overlay modal as shown in the documentation and it works fine. But what I am trying to do with that is to show a confirmation message when a user want to delete an item. 
He click on delete button and  the modal shows up. the user should confirm by clicking confirm button, a  JQuery function is then called and through Ajax, I call Delete action in the controller to perform the delete action. It work fine so far. The action called and delete is done. But the overlay modal is still there. I would like be able to close that overlay modal inside JQuery function when user hit confirm button. I have tried to use JQuery hide() method, it does not work. It closes closes the modal but the modal will be able to show up if I click again on delete button unless I refresh the page.

Thank you for your help

`<script>
    $("#delete-customer").click(function() {
        var itemId = $("#customerId").val();
        $.ajax({
            type:"POST",
            url: '@Url.Action("Delete", "Customer")',
            data: {id:itemId},
            dataType: "json",
            success: function(response) {                
            }
        });
    });
</script>`

![image](https://user-images.githubusercontent.com/14850023/78802098-66c7b300-798b-11ea-85e0-bde12d0dac8e.png)

**Comment by thekodester** [comment]
All plugins have events, please checkout https://wet-boew.github.io/v4.0-ci/docs/ref/overlay/overlay-en.html the event you want is `$( ".wb-overlay" ).trigger( "close.wb-overlay" );` may need to change the primary class.

**Comment by hilaryd198** [comment]
I really need to understand wet toolkit. I don not understand why the modal does not close. the trigger opens the modal but it does not close. I would like you to take a look at this JQuery

`<script>

    $(".customer-action-link").click(function(){
        $("button").removeAttr("title");
        $(".modal-footer").find("button").html("Cancel");
        $(".modal-footer").find("button").remove();
        var id = $(this).data('id');
        $(".modal-body #noticeId").val(id);
        $( ".wb-overlay" ).trigger( "open.wb-overlay" );
    });

    $("#delete-customer").click(function () {
        var itemId = $("#customerId").val();
        $(".web-overlay").trigger("close.wb-overlay");
        $.ajax({
            type:"POST",
            url: '@Url.Action("Delete", "Customer")',
            data: {id:itemId},
            dataType: "json",
            success: function(response) {
            }
        });
    });

</script>`

**Comment by thekodester** [comment]
You have `.web-overlay` when it should be `.wb-overlay`.

**Comment by GormFrank** [comment]
Thank you @thekodester for answering @hilaryd198 question. @hilaryd198 if what @thekodester replied fixed your problem, feel free to close this issue. And thank you for using WET-BOEW!
