### ISSUE TITLE
Don't know how to get started

### ISSUE THREAD

**Issue by xicoreresearch** [wet-boew/wet-boew#8863]
Hi. I am an experienced Drupal user and developer. I am trying to build a site ba sed on WET. I have succeeded to install a site using the Drupal WxT project but I am afraid I don't even know how to begin to utilize the WET source base. I have tried to follow from the Getting Started page, https://wet-boew.github.io/wet-boew/docs/start-en.html but am still confused.

I need to know just a few things to get me going

1. Where are the git source for the actual site Wxt/WET that I need to perform the basic Drupal site installation?
2. How do I used the 'wet-boew' to implement the Gov of Canada examples?
3. eg: What are the steps I need to recreate the kind of experience I see at https://www.canada.ca/en/services/immigration-citizenship.html

10x in advance.

**Comment by xicoreresearch** [comment]
Hi. I should add that I am working with the Drupal 8.x version and not the Drupal 7.x version.

**Comment by joel-osc** [comment]
This is great, happy you have started using this distribution. There are a couple of things you should do to get started... the first is to migrate in the demo content. You can find the under admin/structure/migrate assuming that the migration modules are enabled. They are called "GCWEB Migrate" - one for En and one for Fr. The second thing to do is enabled the Canada.ca theme under admin/config/wxt/wxt_library. This will bring in the look and feel of the page that you referenced from canada.ca. 

After that you can use the basic page and landing page content types to create pages, you may need to remove the left menu block under structure blocks. You can even create your own content-types of adjust the ones that are there by using layout manager or really any other Drupal methods.

**Comment by xicoreresearch** [comment]
Great. Thanks for the fast response. So I understand that the basic wxt
distribution is the starting point to be enhanced with components that you
described.

**Comment by joel-osc** [comment]
Yes, it is intended as a starting point for building multilingual, accessible and responsive websites as required by the Government of Canada and other governments such as municipal and provincial. In the themes directory there is info on how to create a sub-theme (themes/custom/wxt_bootstrap/starterkits/wxt) so that you can extend your CSS/JS without breaking upgradeability. 

The distro demonstrates best practices so it is really handy to look at the code and constructs it is built with and use them as prototypes for how to extend your own site to meet your client's needs as there is some variance from department to department. The distro is not intended as a one size fits all for everyone.

**Comment by GormFrank** [comment]
Hi, we are always happy to see new people starting to use WET-BOEW and GCWeb! Thank you @joel-osc for your answers. @xicoreresearch whenever you feel like you found all the answers to your question, feel free to close this issue.

**Comment by xicoreresearch** [comment]
Thanks for your help to get it up and running. I HIGHLY recommend that whatever the dev state of the distribution, there must,must,must be a stable version that can be installed with composer that simply cannot ever, ever fail. I had the tenacity to go to the end but believe me there are many that would give up and conclude that the distribution is simply unstable, which would be untrue.
10x

**Comment by joel-osc** [comment]
Agree 100%. Thank-you for pushing through it. With more departments coming on board there should be a lot more refinements and features that get pushed upstream. Cheers.
