### ISSUE TITLE
DataTable re-initializes when trying to retrieve datatable api instance

### ISSUE THREAD

**Issue by GarthMartin** [wet-boew/wet-boew#8885]
I am manually initializing my datatable using 
`trigger("wb-init.wb-tables")` and then after I want to get access to the api instance using 
   `var tableApi = $(elem).DataTable({"retrieve":true});`
but the datatable gets re-initialized and I see both the WET filter section and the standard DataTables one.  Does DataTables not find the WET-initialized table?

my initialization looks like this:

`$table.attr("data-wb-tables", '{"destroy": true, "bDeferRender": true, "ajax": {"url": "' + myUrl + '", "type": "GET", "dataSrc":""}, "columns": [{ "data": "JobDescriptionTitle" },{ "data": "PositionNumber" },{ "data": "Classification" },{ "data": "JobDescriptionType" },{ "data": "DepartmentCode" }], "ordering": false}');`

The result winds up looking like this:
![image](https://user-images.githubusercontent.com/11050106/84075116-99992200-a9a1-11ea-9723-9993fb79a728.png)

Any ideas?  I don't understand why the "retrieve":true is not doing what it is supposed to.

**Comment by thekodester** [comment]
I don't think manually triggering is necessary.

HTML:
```
  <table class="wb-tables table" data-wb-tables='{
    "destroy": true,
    "bDeferRender": true,
    "ajaxSource": "/path/to/data.json",
    "ordering": false,
    "columns": [
    { "data": "TITLE", "className": "title" },
    { "data": "SUBJECT", "className": "subject" }
    ]}' id="retrieveTable">...</table>
```

JS:
```
<script>
$( document ).on( "wb-ready.wb-tables", ".wb-tables", function( event ) {
  let $datatable = $( "#retrieveTable" ).dataTable( { "retrieve": true } ).api();
  console.log( $datatable );
});
</script>
```

**Comment by thekodester** [comment]
Also I have many table example on my site thekodester.ca/wet/demos/tables/

**Comment by GarthMartin** [comment]
It's necessary because of how I need to build my ajax url parameters based on user input.  It is not a static data set.

**Comment by thekodester** [comment]
The only difference with the code above is you have to do...

HTML:
```<table class="table">...</table>```

Make sure to exclude the `wb-tables` from the html.

**Comment by thekodester** [comment]
Second note make sure to set `data-wb-tables` before triggering.

**Comment by GarthMartin** [comment]
@thekodester  Thanks,. Still fighting with this but have reduced it to a simple page using the latest WET version.  The behaviour is not related to getting the api reference, but rather with an instantiated datatable not being seen as a datatable when I try to re-load it.  

Here is the scenario.  If I load a page and instantiate a wb-table, and subsequently manually re-load the table (using javascript via a button click) the table is not recognised as a datatable (fn.dataTables.isDataTable() returns false) and obviously cannot be destroyed.  So the table wrapper created for the paging and filtering gets doubled when the new table loads.  Subsequent reloads properly delete the "second" table wrapper, but not the first, so you always wind up with 2.

Now if I have 2 tables on the page and do not automatically load one on page load, but rather use the button to load them, then whichever one is loaded first will experience this behaviour, but the other tables will not.

I have tried this with vanilla DataTables and do not experience the same behaviour.  

I have attached a couple files:
index-en.html - 2 tables, one table loads on page load, other can be loaded by button click and first can be reloaded by button click.
index-en_kode.html - used more or less your code from the dynamic tables example
index-DT.html - vanilla DataTables version with 2 tables
Data.json - my json file

All the JS is inline.  The index-en.html has a bunch of console logging where you can see the datatable "not" being a datatable.

Screenshots:
Page load:
![image](https://user-images.githubusercontent.com/11050106/84216671-4229ad80-aa98-11ea-9d3c-670f05884193.png)

After Load button click:
![image](https://user-images.githubusercontent.com/11050106/84216740-6a191100-aa98-11ea-9405-6991a5300451.png)


Any help is appreciated!


[index-DT.html.txt](https://github.com/wet-boew/wet-boew/files/4755657/index-DT.html.txt)
[index-en.html.txt](https://github.com/wet-boew/wet-boew/files/4755658/index-en.html.txt)
[index-en_kode.html.txt](https://github.com/wet-boew/wet-boew/files/4755659/index-en_kode.html.txt)
[Data.json.txt](https://github.com/wet-boew/wet-boew/files/4755660/Data.json.txt)

**Comment by thekodester** [comment]
So I reviewed https://datatables.net/reference/api/destroy() and some of their other reference pages, and some of the code has change in newer versions of datatables.

This is what I came up with...

HTML:
```
<button id="reloadTable" class="btn btn-default btn-sm mrgn-tp-md mrgn-bttm-md" >Reload Table</button>
<table id="datatable1"
       class="table wb-tables"
       data-wb-tables='{"destroy": true, "bDeferRender": true, "ajax": "ajax/data.json", "columns": [{ "data": "JobDescriptionTitle" },{ "data": "PositionNumber" },{ "data": "Classification" },{ "data": "JobDescriptionType" },{ "data": "DepartmentCode" }], "ordering": false}'>
    <thead>
        <tr>
            <th>JobDescriptionTitle</th>
            <th>PositonNumber</th>
            <th>Classification</th>
            <th>JobDescriptionType</th>
            <th>DepartmentCode</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>
```

JS:
```
<script>
wb.doc.on("click", "#reloadTable", function () { return updateData(); });

function updateData() {
  let selector = "#datatable1",
  $table = $( selector ),
  link = "ajax/data.json";

  destroyTable( selector );

  $table.attr("class", "table table-hover table-stripped wb-tables");
  $table.attr("data-wb-tables", '{"destroy": true, "bDeferRender": true, "ajax": "' + link + '", "columns": [{ "data": "JobDescriptionTitle" },{ "data": "PositionNumber" },{ "data": "Classification" },{ "data": "JobDescriptionType" },{ "data": "DepartmentCode" }] }');
  $table.trigger("wb-init.wb-tables");

  return false;
}

function destroyTable( selector ) {
  if ( $.fn.DataTable && $.fn.DataTable.isDataTable( selector ) ) {
    let $table = $( selector ),
    $datatable = $table.DataTable();

    $datatable.clear().destroy();
    $table.empty();
    $table.html( "<thead><tr><th>JobDescriptionTitle</th><th>PositonNumber</th><th>Classification</th><th>JobDescriptionType</th><th>DepartmentCode</th></tr></thead>" );
  }
}
</script>
```

Hope it helps.

**Comment by GarthMartin** [comment]
@thekodester  Thanks.  I tried your code above, but the ` if ( $.fn.DataTable && $.fn.DataTable.isDataTable( selector ) )` never gets hit since the table is not considered a datatable.  I was using chrome, so not sure if this is a browser thing or not.

**Comment by thekodester** [comment]
Worked for me in Safari, Chrome, and Firefox.

I am running the code on a localhost server (xampp).

<img width="950" alt="Screen Shot 2020-06-11 at 3 30 12 PM" src="https://user-images.githubusercontent.com/23484460/84430950-7916d500-abf8-11ea-8ca9-dc75b6f99ae7.png">

**Comment by GarthMartin** [comment]
@thekodester  Ok something very strange is going on.  I have copied the html you used and the JS you posted, and put in some console.log statement as you did and here are the results I am getting.  Note that to make sure to know the reload was happening I added a second data file with only one record in it.
This is Chrome.  I am running this in VS, but it should not make a difference.
What version of datatables are you loading?  I have attached the main file again for you to compare.

Can you send me yours and I will try it here?

THanks again.

Garth

[index-en_kode.txt](https://github.com/wet-boew/wet-boew/files/4767280/index-en_kode.txt)

![image](https://user-images.githubusercontent.com/11050106/84438190-1aefef00-ac04-11ea-91cd-aacd0994b13e.png)

**Comment by thekodester** [comment]
The issue is `<script type="text/javascript" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js "></script>` wet loads the datatables script automatically remove this line and it we'll be fixed.

**Comment by GarthMartin** [comment]
Well don't I feel foolish.  Thanks, that fixed it...on the bright side, I learned a lot about datatables!

Thanks again.
