### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by TimCadieux** [wet-boew/wet-boew#8896]
Good day folkz, we are building an external facing GC site and our consultants have raised the issue of the browsers that should be supported.

I referred to [this](https://wet-boew.github.io/wet-boew-documentation/research/2018-2-browser-usage.html) page but its 2 years out of date.  Additionally, the page the that is linked to which provides current statistics now shows a different story based on the 5% threshold.

Is it possible to update the page to provide guidance.

**Comment by Pacoup** [comment]
As far as I know, latest supported browsers are listed in the release notes:
- [v4.0.36 release notes](https://github.com/wet-boew/wet-boew/releases/tag/v4.0.36)

You can find links to the release notes for each version here:
- [Web Experience Toolkit Downloads](https://wet-boew.github.io/wet-boew/docs/versions/dwnld-en.html)

And for GCWeb, you can find the associated wet-boew version in the release notes so you can get to the associated version's browser support:
![image](https://user-images.githubusercontent.com/112764/85752209-36b1c580-b6d9-11ea-9f94-262f36313f16.png)

**Comment by duboisp** [comment]
@TimCadieux each release note de wet-boew and GCWeb include the list of supported browser. Here the procedure we follow: https://wet-boew.github.io/wet-boew-documentation/decision/2.html

There is no significant change in browser support since 2 year. IE 11 is still there.
