### ISSUE TITLE
Inuit Population Dataset

### ISSUE THREAD

**Issue by ds719** [wet-boew/wet-boew#8910]
Hi there, not sure if I'm right here but wanted to ask whether you could provide the population dataset for all the communities that are plotted on this map: https://www.aadnc-aandc.gc.ca/Map/irs/mp/index-en.html. I am writing a thesis and would be super grateful to have all the population numbers per community and region. Many thanks!

**Comment by ned33bm** [comment]
Hello,
You might get some info through Openmaps based on FN data: https://open.canada.ca/data/en/dataset/b6567c5c-8339-4055-99fa-63f92114d9e4
or you will have to contact INAC directly. Good luck!

**Comment by GormFrank** [comment]
Thank you @ned33bm for your answer! Good luck with your thesis @ds719.

**Comment by PatLittle** [comment]
@ds719 - please make a suggestion at - https://open.canada.ca/en/forms/suggest-dataset 
Thx!

**Comment by GormFrank** [comment]
@ds719 Can this issue be closed? Thanks!

**Comment by ds719** [comment]
Yes, thx!
