### ISSUE TITLE
Turn off "show entries" in data table

### ISSUE THREAD

**Issue by michael-613** [wet-boew/wet-boew#8915]
Hello,

Does WET4 offer a way to turn off the "show entries" at the top of the table while keeping pagination? 

![Table](https://user-images.githubusercontent.com/36242734/89063115-98e39300-d335-11ea-91ae-c7df7c410287.PNG)

We are using a custom iframe solution to import a table and I don't want the height to change.

Please let me know if this is possible to do while keeping pagination.

Thanks

**Comment by michael-613** [comment]
I found the solution:

**data-wb-tables='{ "lengthChange" : false }'**

**Comment by RobJohnston** [comment]
For completeness, the link to the related DataTables docs:  https://datatables.net/reference/option/lengthChange

Looks like you can close your own issue, @michael-613 .
