### ISSUE TITLE
Tables: Trying to get DataTable to work with Editor

### ISSUE THREAD

**Issue by jmpotvin** [wet-boew/wet-boew#8931]
Hi,

I'm trying to implement the datatables editor ([https://editor.datatables.net/](url)).

Looks like the "B" in data-wb-tables dom is ignored and the buttons are not showing.

How can I get the editor to work?

Thanks!

**Comment by thekodester** [comment]
That version of datatables is not free and requires that you load additional datatables files.

See https://editor.datatables.net/manual/installing/

**Comment by jmpotvin** [comment]
The problem is that DataTable do not support DataTable buttons, it is not related to the editor.

I will create a new question with more details.

**Comment by thekodester** [comment]
It the same issue you need to include additional files. You cant use data-wb-tables.

See https://github.com/wet-boew/wet-boew/issues/7219#issuecomment-259237349 for a similar question.
