### ISSUE TITLE
Tabbed Interface: 

### ISSUE THREAD

**Issue by chrisblack** [wet-boew/wet-boew#8932]
Hi, 
Can someone please tell me if it's possible to configure the tab control to load a different page when the user clicks a tab.
I tried inserting an anchor tag in the summary section but that didn't work.
Thanks,
Chris

**Comment by thekodester** [comment]
If where talking about https://wet-boew.github.io/v4.0-ci/demos/tabs/tabs-en.html that is not possible as this is using detail/summary elements.

**Comment by thekodester** [comment]
Might be better to look at using https://wet-boew.github.io/wet-boew-styleguide/design/secmenu-en.html# you could put this on the left side of screen.
