### ISSUE TITLE
Question about colour and palettes

### ISSUE THREAD

**Issue by swapnalithakarpspc** [wet-boew/wet-boew#8941]
Hi
I am working on a project for PSPC and have the following questions:
1. WET guidelines talk about using different colours for buttons to communicate state. 
Does that mean that this is the colour palette we "HAVE" to use?
2. I understand the colour contrast requirements for WCAG - could I use my own colour palette that abides by these guidelines?
3. I understand that different button colours can be used to inform the user of the "state" of the button. But do I have to follow the exact same colours as mentioned in the WET guidelines? 

i.e. if my base colour is #503879, (purple) could I use this purple as my "Primary" button. Note that this colour with white text passes AAA.

![image](https://user-images.githubusercontent.com/71705355/93878960-eaaaf880-fca8-11ea-89f8-09ff69dc6d56.png)

**Comment by GormFrank** [comment]
@delisma

**Comment by swapnalithakarpspc** [comment]
Hi Gorm,
I am using simply WET-BOEW.

**Comment by GormFrank** [comment]
Ok so to answer your questions:

**1. WET guidelines talk about using different colours for buttons to communicate state. Does that mean that this is the colour palette we "HAVE" to use?**
- If you are planning on using the basic theme from WET-BOEW then you should be using the same colours (which mostly come from Bootstrap 3). However, nothing prevents you from creating your own "theme", just like GWeb is the theme that gives the look and feel of Canada.ca.

**2. I understand the colour contrast requirements for WCAG - could I use my own colour palette that abides by these guidelines?**
- If you know about the colour contrast criteria from WCAG and apply it, then you could create your own colour palette yes. 

**3. I understand that different button colours can be used to inform the user of the "state" of the button. But do I have to follow the exact same colours as mentioned in the WET guidelines?**
- When there are WET guidelines, it means that it has been tested and reviewed by experts. If you are moving away from what WET-BOEW suggests/offers, then just make sure that you know what you are doing. Also, if your project is from the GoC you should really consider using GCWeb (but you don't necessarily have to).

**Comment by thekodester** [comment]
Also just too add my own two cents creating your theme is quite easy. You can see an example of wet-boew (non-goc) modified on my site here thekodester.ca/wet/

All the CSS: thekodester.ca/wet/static/css/theme.color.css and thekodester.ca/wet/static/css/theme.helpers.css

**Comment by swapnalithakarpspc** [comment]
Thanks a lot for your help. I will keep your advice in mind for sure.
