### ISSUE TITLE
Question about grid

### ISSUE THREAD

**Issue by swapnalithakarpspc** [wet-boew/wet-boew#8943]
![image](https://user-images.githubusercontent.com/71705355/94146114-76f02380-fe41-11ea-9579-8704fcc0d12a.png)
How does this math add up?
12 columns of 95px with 30px gutter comes to 1470 total width of the columns. Which is larger than 1200.

Can you please explain?

**Comment by thekodester** [comment]
Probably just a type, but should say `(>= 1200)`.

The media query used by bootstrap is `@media (min-width: 1200px)`.

**Comment by swapnalithakarpspc** [comment]
Ok thanks for clarifying.

**Comment by swapnalithakarpspc** [comment]
So as long as I am following bootstrap grid, I am ok right?

**Comment by thekodester** [comment]
Yes, WET also uses Bootstrap 3, so make sure you're follow that.

**Comment by swapnalithakarpspc** [comment]
Ok thanks... so the column widths and gutters could be slightly different right? They don't have to be exactly 95px... Did I understand that correctly?

**Comment by swapnalithakarpspc** [comment]
i.e.
Could I use this?
![image](https://user-images.githubusercontent.com/71705355/94149624-216a4580-fe46-11ea-85c9-8ccfd3745f68.png)

**Comment by thekodester** [comment]
This is how the css works:
Medium is `@media (min-width: 992px)/.col-md-1 {width: 8.3333333333%; }`
Small is `@media (min-width: 768px)/.col-sm-1 {width: 8.3333333333%; }`
Extra Small is `width: 768px/.col-xs-1 {width: 8.3333333333%; }`

**Comment by GormFrank** [comment]
Thank you @thekodester for responding. If I may add, depending on what you are trying to achieve @swapnalithakarpspc, you can use the `.row-no-gutters` class jointly with the `.row` class in order to get rid of the gutters.

**Comment by swapnalithakarpspc** [comment]
Thanks guys! Much appreciated.
