### ISSUE TITLE
Overlay: 

### ISSUE THREAD

**Issue by amandadmills** [wet-boew/wet-boew#8961]
Is there a way to remove the x in the top right corner? Or hide it?

**Comment by thekodester** [comment]
There is a modal with this affect (Centred popup - Modal (Lightbox + Modal)).

See all examples at https://wet-boew.github.io/v4.0-ci/demos/overlay/overlay-en.html

**Comment by GormFrank** [comment]
Thank you @thekodester. @amandadmills does that answer your question so that this issue can be closed? If not, can you give more details on your use case? Thanks!

**Comment by amandadmills** [comment]
I should have clarified I want it not to be able to be closed at all

**Comment by GormFrank** [comment]
Can you elaborate a little bit more on your use case or provide us with a graph or screen shots because without any more information I would be strongly against exposing users to such behaviour, for many reasons including accessibility and usability. Thank you!

**Comment by amandadmills** [comment]
You can close the issue. I can work with just the close button. Thanks!
