### ISSUE TITLE
Page refresh in chrome on form submit

### ISSUE THREAD

**Issue by tanahel-udem** [wet-boew/wet-boew#8974]
When using a form clicking submit makes the page refresh in chrome. It is not the case in Firefox. Here is the simplest code to reproduce the issue : 
[Demo](https://codesandbox.io/s/light-box-validation-r142n?fontsize=14&hidenavigation=1&theme=dark)

**Comment by thekodester** [comment]
That is normal behaviour if the `action="#"` is set to the same page. You have to use javascript to prevent the submit button form doing anything. Great example is validation.

See demos:
Regular Forms: https://wet-boew.github.io/wet-boew-styleguide/design/forms-en.html
Validation: https://wet-boew.github.io/v4.0-ci/demos/formvalid/formvalid-en.html
