### ISSUE TITLE
Font of °C in tables differ than font in text

### ISSUE THREAD

**Issue by btam001** [wet-boew/wet-boew#8976]
Hi, 

When I create a table under the wetbeow framework, the font for °C is in a serif format, which is different than how it appears when simply in text (sans-serif).

**Comment by thekodester** [comment]
Are you using a regular table or datatable? Also are you using HTML codes? Like `&#8451;` (https://www.toptal.com/designers/htmlarrows/symbols/degree-celsius/).

**Comment by btam001** [comment]
I believe it's data table (class='wb-table), using the html code. Actually, I'll see if text (no html code) works. I'll let you know.

**Comment by thekodester** [comment]
How is the table populated? Hard coded or json?

**Comment by btam001** [comment]
Hard coded

**Comment by thekodester** [comment]
Might be server/rendering related. Testing locally seems to work fine with `&#8451;`.

Image:
<img width="512" alt="Screen Shot 2020-11-03 at 1 59 12 PM" src="https://user-images.githubusercontent.com/23484460/98028934-c9c3e000-1ddc-11eb-89fb-be8fe4079dcf.png">

**Comment by btam001** [comment]
Perhaps. It seems that when using the html code, it's serif. but with when using this, '°C', then it works. I'll just replace the html code with °C. Thanks for looking into this. I'll close this issue.
