### ISSUE TITLE
Data-ajax no longer functional when used in wb-tabs WET 4.0.39

### ISSUE THREAD

**Issue by alamarch** [wet-boew/wet-boew#8981]
It appears that when using data-ajax-replace inside Tabbed Interface (wb-tabs) is no longer functional in v4.0.39.

**Comment by duboisp** [comment]
@alamarch can you re-test with the version v4.0.39.1, we have fixed a bug that was interfering with the Tabbed Interface

**Comment by alamarch** [comment]
@duboisp re-tested and all is now good. Thank you.
