### ISSUE TITLE
Expand/hide do not work if placed after a tabbed interface

### ISSUE THREAD

**Issue by Christopher-O** [wet-boew/wet-boew#8984]
Hi there, we discovered an issue with a newer version of WET4 (cannot tell exactly which version this happened to but it doesn't happen in WET 4.0.30).

If you place expand/hides (details/summary) under a tabbed interface, the script does not add the classes (except for wb-init) or function in order to make the expand/hide work (the tabbed interface works fine).  This is only an issue for browsers that still depend on script to make details/summary expand/hide (IE11, Edge pre chromium).

**Comment by Christopher-O** [comment]
Upon a bunch of testing to see how I could resolve this issue with a "hack", it seems that the tabs script is not completing (e.g. not at a ready state).  If I try to add an alert to trigger after the tabs have initialized (e.g. $( document ).on( "wb-ready.wb-tabs", ".wb-tabs", function( event ) {…})), nothing happens, which I sense means that the script is not ending, and why scripts below (re: expand/hide) do not initialize as needed.

**Comment by thekodester** [comment]
Sounds like it related to this issue https://github.com/wet-boew/wet-boew/issues/8982

**Comment by Christopher-O** [comment]
@thekodester I saw that, and was not sure if they were related or not, but I agree it might be.

**Comment by ialexca** [comment]
@Christopher-O Any of our javascript that is triggered after event wb-ready and after a tab is due to issue #8982.

Our work around is to go back to version 4.0.38.

**Comment by Christopher-O** [comment]
@ialexca thanks, we are on Canada.ca so unfortunately that is out of our hands.  Instead I used a script to make the expand/hide re-initialize after the first initialization was done (but failed due to the tabbed interface).  That works an interim solution until a patch can be applied in a future version.
