### ISSUE TITLE
Lightbox v8.x error while loading Image

### ISSUE THREAD

**Issue by agagnon** [wet-boew/wet-boew#8985]
I downloaded WET version 8.x and I get an error with the lightbox plugin when I try to open an image. I got the error with all v8.x versions.
`<a class="wb-lbx" href="image.jpg" title="Image title">View image</a>`

![Lightbox-error](https://user-images.githubusercontent.com/1794026/99858089-bfcf0a80-2b5a-11eb-88e5-1ad6b826581e.PNG)

**Comment by thekodester** [comment]
There seems to be no issues with the demos at:
https://wet-boew.github.io/v4.0-ci/demos/lightbox/lightbox-en.html
https://wet-boew.github.io/themes-dist/GCWeb/demos/lightbox/lightbox-en.html

Test on macOS (Safari, Firefox, and Chrome).

Can you provide more code?

Also there is currently a bug with TABs causing other plugins to fail do you have any tabs on your page?

**Comment by agagnon** [comment]
It seems to be working when the link wraps an image, but not when it wraps text. There is no example in the Lightbox page of link to an image with text only content within the link.

**Working**
```
<a class="wb-lbx" href="image.jpg" title="Image title">
    <img src="image.jpg">
</a>
```

**Not working**
```
<a class="wb-lbx" href="image.jpg" title="Image title">
    View image
</a>
```

**Comment by agagnon** [comment]
It does work this way, though, with a combination or image (may be hidden or not) and text. In other words, it needs to have an image within the link to open properly.

```
<a class="wb-lbx" href="image.jpg" title="Image title">
    <img src="image.jpg" class="hidden">View image
</a>
```

or even

```
<a class="wb-lbx" href="image.jpg" title="Image title">
    <img>View image
</a>
```

**Comment by duboisp** [comment]
The lightbox default HTML pattern to display an image require to include a thumbnail image. (ref. https://github.com/wet-boew/wet-boew/blob/master/src/plugins/lightbox/lightbox.js#L87 )

However, you can add the CSS class "lbx-image" to force the modal behavior to be the one specialized for images.

I didn't tested, but it might be something along those lines:
```
<a class="wb-lbx lbx-image" href="image.jpg">
    View image
</a>
```

**Comment by agagnon** [comment]
It works with "lbx-image" class. Thanks

I used to work with WET v4.27 and it worked without "lbx-image". Was this class added after 4.0.27 or was it always there?

**Comment by thekodester** [comment]
Class name rules where introduced in 2014 with v4.0.8.

See https://github.com/wet-boew/wet-boew/pull/6198.
