### ISSUE TITLE
build wet-boew project failed

### ISSUE THREAD

**Issue by jiebinGao** [wet-boew/wet-boew#8989]
Hello,

I am fresh one of Wet project. I am trying to pull wet-boew repo and build the project in Windows 10  on my computer. I followed the instruction on the website https://wet-boew.github.io/wet-boew/docs/start-en.html  and select the last one (I want to fix or improve WET as a developer) on that page.  I got errors as below.  I also enclosed the log file. 
Can somebody help me with this? Thanks very much!
[2020-11-25T16_46_16_325Z-debug.log](https://github.com/wet-boew/wet-boew/files/5600298/2020-11-25T16_46_16_325Z-debug.log)

> node-sass@4.13.1 install C:\Users\Jiebin Gao\Documents\GitHub\wet-boew\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.1/win32-x64-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.1/win32-x64-83_binding.node":

HTTP error 404 Not Found

**Comment by jiebinGao** [comment]
It is the same as #2895

**Comment by RobJohnston** [comment]
I think you meant the same as #7845
