### ISSUE TITLE
Tables: 

### ISSUE THREAD

**Issue by chrisblack** [wet-boew/wet-boew#8999]
Hello,
Can anyone please tell me which version of the DataTables.net Buttons Extension I should use that is compatible with the DataTables/JQuery version used with this Framework?
Many thanks,
Chris

**Comment by thekodester** [comment]
You can use any version, but you'll have to add custom JS as it not built into WET.

It was already discussed here: https://github.com/wet-boew/wet-boew/issues/7219#issuecomment-259237349

**Comment by chrisblack** [comment]
Thanks - works great for the Buttons extension
