### ISSUE TITLE
Toggle: Off toggle not working in details elements

### ISSUE THREAD

**Issue by laurencechavet** [wet-boew/wet-boew#9000]
Hi
In Firefox 78.2.0esr (32-bit), in https://wet-boew.github.io/wet-boew/demos/toggle/toggle-en.html#details, it seems I can't make the "off" button collapse the details if they are open. The same the toggle can't close open details.
The 2 buttons toggle and On works to open the closed details.
The click on each detail works too
Thanks

Canadian Heritage

**Comment by laurencechavet** [comment]
I forgot to mention in Firefox 78.2.0esr (32-bit)
It works in Chrome

**Comment by thekodester** [comment]
The latest version of Firefox seems to have no issues (version 83.0).

###### I am just a volunteer on this GitHub project.

**Comment by laurencechavet** [comment]
Yes working on Firefox 83. My professional machine is locked with FF78, which was why it was not working.
Thanks a lot
