### ISSUE TITLE
PDF forms inaccessible with in-browser PDF reader on Canada.ca in the immigration theme

### ISSUE THREAD

**Issue by cvloo** [wet-boew/wet-boew#9015]
I'm trying to download some PDF forms from canada.ca and Modernizr keeps steering me to a dummy PDF file that says my Adobe version is not accepted. I've never had any issues with PDF files whatsoever aside from Canada.ca.

It doesn't work on Firefox/Linux, it doesn't work on Chrome/ChromeOS, and it doesn't work on friends' Windows computers on Edge/Explorer browser. Same problem all around: Modernizr pushes a PDF file that contains an error instead of the forms.

Can you please advise? All I need to do is download some PDF forms and I've already wasted all morning digging through JS code trying to get something as simple as a PDF download to work.

**Comment by thekodester** [comment]
Are you having a issue with a specific page on Canada.ca or you trying to code something?

If it a specific page what page?
If your try to code something can we see some code?

###### I am just a volunteer on this GitHub project.

**Comment by cvloo** [comment]
Thanks for replying. I'm just trying to download some PDF forms in Canada.ca. I'm not a web developer, I just want to be able to download the forms so I can use them. Here's one URL example:

Within this URL: https://www.canada.ca/en/immigration-refugees-citizenship/services/application/application-forms-guides/application-renew-replace-permanent-resident-card.html

The following PDF files are inaccessible (ie, it downloads a PDF that contains a line that says wrong Adobe version instead of the form)
2) Document Checklist (IMM 5644) (PDF, 2.19MB)
3) Application for a Permanent Resident Card [IMM 5444] (PDF, 1.84MB)

Photograph Specifications for Permanent Resident Cards (PDF, 614.24KB)

**Comment by thekodester** [comment]
If you mean the following error:

```
The document you are trying to load requires Adobe Reader 8 or higher. You may not have the Adobe Reader installed or your viewing environment may not be properly configured to use Adobe Reader. For information on how to install Adobe Reader and configure your viewing environment please see http://www.adobe.com/go/pdf_forms_configure.
```

![76E8AA31-8369-4629-9789-566D62BE49E5](https://user-images.githubusercontent.com/23484460/103578832-43438180-4ea5-11eb-9604-ad32bbd9ea1a.jpeg)

This is not a WET issue, but an web browser issue not being compatible with the type PDF that is being rendered.

That said this type of PDF is not compatible with many browser at this point. An alternative link should be code to directly down the PDF.

@duboisp

**Comment by cvloo** [comment]
Why are you using that format? Canada.ca is literally the only website in the entire internet that causes issues downloading PDFs for my setup (Debian Stable on Firefox). It's also unacceptable that it can't be displayed properly on the latest Chrome version on Chrome OS.

It has been like this for more than a year and there are complaints about this on several Canada immigration forums. How many people do you think are having the same issue and are unable to get a resolution because they aren't Github-literate?

**Comment by thekodester** [comment]
Just wanted to include some addition information.

These forms well work but only on Windows or MacOS using the desktop version of Adobe Reader (well not work on other OS or mobile devices).

The process to download them without a direct download link/button is not necessarily complicated but could be to some people (everyone has a different level of computer skills).

That stated other parts/departments on Canada.ca offer two versions of the forms fillable and non-fillable for this reason.

I already CC @duboisp in my last message as he should have a general idea of the correct department to bring this up to.

**Comment by cvloo** [comment]
I couldn't get it to work on a Macbook last year either. I think OS version was Snow Leopard and it didn't work on either Chrome or Safari

**Comment by thekodester** [comment]
Like I stated you have to download and use the desktop version of Adobe Reader. These types of forums can longer be opened in many web browsers.

Unfortunately these PDF documents are basically Adobe Forms, the first browser to remove all/any Adobe support was Chrome. When big tech giants like Google do something like that others follow.

**Comment by cvloo** [comment]
Look, I have two Linux computers, two Chromebooks, one Macbook, and none of them work with your particular site even though they work for literally every other site. If I can't find a resolution through Github I will file a complaint with Immigration and with Procurement because the solution is not acceptable.

**Comment by thekodester** [comment]
As I stated before I am just a volunteer on this GitHub project. This GitHub project is not directly responsible for all of Canada.ca

You can see it is clearly documented on https://www.cic.gc.ca/english/helpcentre/answer.asp?qnum=138&top=18

1. Use your computer (Mac or PC). The forms won’t open on mobile devices (iPads, tablets, mobile phones, etc.)
2. Install Adobe Reader 10 (or higher)
3. Download the PDF file to your computer. Save the file in a place you can remember.
4. Make sure you use Adobe Reader to open the form. Sometimes if you try to open the form directly, it will use your Internet browser to try to open it.

Unfortunately the documents in their current state current state do not work on anything but MacOS or PC (windows) using the desktop application provided by Adobe.

**Comment by duboisp** [comment]
@cvloo my team (Principal Publisher - Canada.ca) are going to contact IRCC to let them know the issue you are experiencing with their PDF files which seems to require a PDF reader that must support PDF 1.7 (ISO 32000-1).

\cc @louis-galipeau @GormFrank

**Comment by cvloo** [comment]
> @cvloo my team (Principal Publisher - Canada.ca) are going to contact IRCC to let them know the issue you are experiencing with their PDF files which seems to require a PDF reader that must support PDF 1.7 (ISO 32000-1).
> 
> \cc @louis-galipeau @GormFrank

Thanks. It's mind-boggling that there was no UX testing performed. Essentially, Canada.ca is locking out Linux and Chromebook users because the selected format requires proprietary Adobe software.

So basically users of more expensive Macbook users are able to access, but free software and Chromebook users are denied access to immigration forms.

**Comment by RobJohnston** [comment]
@duboisp Specifically, the section within IRCC is called "Forms Management".  Hope that helps.

**Comment by duboisp** [comment]
@cvloo I received an answer from the IRCC (Immigration, Refugees and Citizenship Canada) web publisher team. They are aware of the PDF issue and they are currently working on implementing a solution. 

FYI - Canada.ca is a centralized web site product supported by Principal Publisher where each government departments are responsible for publishing and maintaining their content.

**Comment by cvloo** [comment]
I see, well it's still not working. Besides IRCC, who was the QA team in charge of approving this format choice?

**Comment by cvloo** [comment]
And just to be clear, Maximizr is also a burden. If Maximizr wasn't filtering access to the forms, I could at least access them to print them myself and deliver them physically. It turns out IRCC accepts printed forms and electronically-signed forms, but those who can't access the electronic version ALSO can't access the workaround to print and deliver physically due to Maximizr

**Comment by duboisp** [comment]
> Besides IRCC, who was the QA team in charge of approving this format choice?

IRCC are responsible for the quality assurance of the web content they are publishing, including ensuring their published content meet all web standards such WCAG 2.0 Level AA. Me and my team (Principal Publisher) are providing the platform to enable a centralized web publishing and implement the common look and feel as specified by Treasury Board Secretariat.

I already shared your concern and issue with the IRCC web team that are responsible for that published web content. As I said, they have a solution but it's not implemented yet.

You next step will be contact [IRCC department](https://www.canada.ca/en/immigration-refugees-citizenship/corporate/contact-ircc.html).

**Comment by RobJohnston** [comment]
It was Adobe who abandoned support by not updating their Acrobat Reader software for non-Windows PCs.  I've found 2 posts where people claim that there's another piece of software that can open an XFA form, which is what is causing the problem:
 * https://askubuntu.com/a/1263988
 * https://unix.stackexchange.com/a/342128

The "Master PDF" software seems to be available for Windows, Mac, and Linux.  I've never used it.

**Comment by cvloo** [comment]
Well when is it gonna be implemented? I have to submit these forms in a week and this has been broken for more than a year. The media is gonna love to hear how IRCC is locking immigrants who don't own Apple products out of Canada, especially in an election year

**Comment by RobJohnston** [comment]
I installed Master PDF (https://code-industry.net/downloads/) and it worked.  I was able to open and fill-out the two documents in question, IMM 5644 and IMM 5444.

**Comment by cvloo** [comment]
Thanks for the workaround, but many people are unable to follow these steps. It's such a simple thing to build a PDF form server. The fact that the national government doesn't follow minimum QA standards brings to light into question how these contractors are awarded these projects. The fact that they have messed up something so simple and it has remained unfixed for more than a year is a spit in the face to all immigrants to Canada who regularly need to resubmit these forms per Canada's own rules. I am reaching out to alternate channels because this is a gross misuse of taxpayer money

**Comment by RobJohnston** [comment]
No work-around necessary in the case of Android.  Adobe provides a version of Acrobat Reader:  https://get.adobe.com/reader/otherversions/

**Comment by duboisp** [comment]
We informed IRCC of the issue as this is not something we can fix on our side; it is not a WET-BOEW issue and we are not the content owners of those PDFs.

@cvloo I invite you to reach out [IRCC Client Support Center](https://www.canada.ca/en/immigration-refugees-citizenship/corporate/contact-ircc/client-support-centre.html) to get further assistance.
