### ISSUE TITLE
Faceted finder page

### ISSUE THREAD

**Issue by CaroGagnon** [wet-boew/wet-boew#9024]
Hello, 
I'm wondering if anybody is using the [faceted finder page](https://design.canada.ca/recommended-templates/pages-index.html#faceted). I couldn't find an example of it under WET examples.
Thank you,
Caroline

**Comment by duboisp** [comment]
The faceted finder page is currently not implemented in GCWeb but it is on our radar to do it. I don't have a turn around time for the moment.

**Comment by CaroGagnon** [comment]
Merci.
