### ISSUE TITLE
lightbox plugin issue

### ISSUE THREAD

**Issue by tangqinying** [wet-boew/wet-boew#9027]
## Required information

**Describe the bug**
there is a bug in the code to load the html file in this plugin.

**To Reproduce**

**Expected behavior**
in the http://esdc.prv environment, the the lightbox plugin works in the image gallery, and inline box, but can't load the external html file(s).

**Who shall do the work?**
[I will do it, I want to contribute] or [I am asking for Principal publisher to please do the work]

## Additional information (optional)

**Version of WET-BOEW/GCWeb you are using**
v4_0_39

**Desktop/Smartphone (please complete the following information)**
 - OS or Device: [e.g. iOS]

**Screenshots**
If applicable, add screenshots to help explain the bug.

**Additional context**

**Comment by duboisp** [comment]
> , but can't load the external html file(s).

You probably have a CORS issue. This require is a server side configuration. Are you seeing any browser console error?

**Comment by tangqinying** [comment]
Hi,
I don’t see console error.
Nick, here is my test file http://s2tst-srv401.sade-edap.prv/en/qin.shtml

The AJAX – Exmaple 1 and AJAX gallery section are not working. Those are loading a external file.

Thanks

Tang, Qinying
Direction générale de l'innovation, de l'information et de la technologie
Emploi et Développement social Canada / Gouvernement du Canada
qinying.tang@hrsdc-rhdcc.gc.ca / Tél : 819-654-4039

Information, Innovation and Technology Branch
Employment and Social Development Canada / Government of Canada
qinying.tang@hrsdc-rhdcc.gc.ca / Tel: 819-654-4039

**Comment by duboisp** [comment]
@tangqinying your issue if your Ajax file: http://s2tst-srv401.sade-edap.prv/en/ajax1-en.html

You need to remove the CSS class `mfp-hide` that you have set on the section at line 1

You can compare your file with this example: https://wet-boew.github.io/wet-boew/demos/lightbox/ajax/ajax1-en.html

**Comment by tangqinying** [comment]
Thank you so much Pierre. It works.

Thanks

Tang, Qinying
Direction générale de l'innovation, de l'information et de la technologie
Emploi et Développement social Canada / Gouvernement du Canada
qinying.tang@hrsdc-rhdcc.gc.ca / Tél : 819-654-4039

Information, Innovation and Technology Branch
Employment and Social Development Canada / Government of Canada
qinying.tang@hrsdc-rhdcc.gc.ca / Tel: 819-654-4039
