### ISSUE TITLE
Accessibility scan

### ISSUE THREAD

**Issue by jaimeiniesta** [wet-boew/wet-boew#9034]
Hello!

I just found this toolkit and it's an awesome resource. I wanted to contribute to it by sharing the results of an HTML and accessibility issues site-wide scan on Canada.ca, which I hope throws some light on some issues:

https://rocketvalidator.com/s/cc40d96a-ac74-4ade-8b5e-9f3925eaf7a8

I'm the creator of Rocket Validator and I'll be happy to provide free accounts for open source projects like this. We're already helping other open source projects like [Facebook Docusaurus](https://github.com/facebook/Docusaurus) this way. If you're interested in a free open source account just ping me at jaime@rocketvalidator.com and I'll set it up for you.

**Comment by mgifford** [comment]
Rocket validator isn't open source, right?  So this is probably just sales spam.  Canada.ca isn't an open source project.
