### ISSUE TITLE
[BUG] pagination issue - pagination lost data 

### ISSUE THREAD

**Issue by mingjiongliao** [wet-boew/wet-boew#9043]
## Required information

I use datatable to load my data and set pagination. the table was populated with my data as well as a checkbox each row. when I check some boxes and go to next page, the system can not remember my choices. it only recognizes the current page. I google and find many similar issues. 
https://salesforce.stackexchange.com/questions/219030/jquery-is-not-working-for-second-page-onwards-in-page-pagination
https://stackoverflow.com/questions/30723911/checkboxes-will-only-work-on-current-pagination-page-in-jquery-datatables
 it is the issue for jquery but I am wondering if WET has fixed this issue??

**Comment by thekodester** [comment]
It a known issues of DataTables 3rd party login. They have a solution, looking for link.

**Comment by thekodester** [comment]
https://datatables.net/faqs/index

![F642CD84-1327-4D19-8D94-A062559E3712](https://user-images.githubusercontent.com/23484460/108439223-d7cc2e00-721e-11eb-9fd5-77bdb78c705a.jpeg)

**Comment by mingjiongliao** [comment]
thanks! done.
