### ISSUE TITLE
Remove "generator-wet-boew-theme" under implement section

### ISSUE THREAD

**Issue by timarney** [wet-boew/wet-boew#9061]
This section implement[ section](https://wet-boew.github.io/wet-boew/docs/start-en.html#implement) refers to generator that isn't maintained and is [broken ](https://github.com/wet-boew/wet-boew/issues/8802#issuecomment-572373708)

 

1) Would you accept a PR to remove it from the [docs](https://github.com/wet-boew/wet-boew/blob/master/site/pages/docs/start-en.hbs)? 

> I want to customize WET and design a new WET theme
... Install the WET theme generator by running npm install -g generator-wet-boew-theme.
Run yo wet-boew-theme from the command prompt, and answer the questions at the prompt to setup your theme project.

2) Ideally the NPM package + other artifacts would be archived + deprecated to avoid confusion

**Comment by thekodester** [comment]
I would think a PR you be accepted at this point to clear any documentation that would cause confusion.

@duboisp @GormFrank 

###### I am just a volunteer on this GitHub project.
