### ISSUE TITLE
Example for Multimedia Video player not working

### ISSUE THREAD

**Issue by emilieviau** [wet-boew/wet-boew#9067]
Hi,
My comment is about the Multimedia Video player given on those pages: 
https://wet-boew.github.io/v4.0-ci/demos/multimedia/multimedia-en.html
https://wet-boew.github.io/v4.0-ci/demos/multimedia/multimedia-fr.html

In the example page, the video player is not working: the media is endlessly waiting to play.

**Comment by EricDunsworth** [comment]
Looks like the site that hosted those videos (https://video2.servicecanada.gc.ca/) was recently taken down.

@duboisp @GormFrank Thoughts? FWIW I have backups of the missing videos and their supporting files.
