### ISSUE TITLE
Footnotes: Footnotes using symbols such as asterix * are broken/not linking

### ISSUE THREAD

**Issue by nfrenette** [wet-boew/wet-boew#9085]
Tested here: https://wet-boew.github.io/v4.0-ci/demos/footnotes/footnotes-en.html

![image](https://user-images.githubusercontent.com/15619641/115554303-51fb4c00-a27c-11eb-99e5-210dae589b05.png)

**Comment by thekodester** [comment]
Problem is using `href="#fn*"` and `id="#fn*"` asterix gets treat like a wildcard is not unique enough.

Example should be changed too:
```
<section>
	<h2>Recommended usage</h2>
	<ul>
		<li>Implementing footnotes in Web pages<sup id="fnasterix-rf"><a class="fn-lnk" href="#fnasterix"><span class="wb-inv">Footnote </span>*</a></sup></li>
	</ul>
</section>
```
		<dt>Footnote *</dt>
		<dd id="fnasterix">
			<p>Example of a standard footnote, denoted by a symbol.</p>
			<p class="fn-rtn"><a href="#fnasterix-rf"><span class="wb-inv">Return to footnote </span>*<span class="wb-inv"> referrer</span></a></p>
		</dd>
```
