### ISSUE TITLE
Form validation error message in English only

### ISSUE THREAD

**Issue by llchen8988** [wet-boew/wet-boew#9087]
After I clicked on Français, the validation error still shows English message not in French

**Comment by thekodester** [comment]
The demo page seems to work fine https://wet-boew.github.io/v4.0-ci/demos/formvalid/formvalid-fr.html

![284FAFC3-D1EB-4D2F-A6E1-7C18F89F1F78](https://user-images.githubusercontent.com/23484460/115888898-6cbaf580-a421-11eb-919a-d337e5c74ed5.jpeg)

Is this your own project? Have any code to share?

**Comment by llchen8988** [comment]
Maybe my chrome has auto translation on
