### ISSUE TITLE
[BUG] Feature name - Steps form script conflicting with other scripts

### ISSUE THREAD

**Issue by Christopher-O** [wet-boew/wet-boew#9089]
## Required information

**Describe the bug**
I find when I use the steps form to test in a project (for GCWeb), I cannot run an event listener for it or even just the regular wet4 even (wb-ready.wb).   When the class (wb-steps) is removed, the event works just fine....

This also prevents functions like doaction from working on the same page.

A quick validation of the script function does not show any issues...so unsure where the conflict may be.

**To Reproduce**
1. Add an instance of the step form function to a page
2a. try adding a WET4 event call (e.g. $(document).on("wb-ready.wb", function() {....});
2b. Add an instance of a component like doaction
3. neither functions seem to run.

**Expected behavior**
Other functions should run when the steps form is present on the page.

**Who shall do the work?**
I am asking for Principal publisher to please do the work

## Additional information (optional)

**Version of WET-BOEW/GCWeb you are using**
e.g. v9.01

**Desktop/Smartphone (please complete the following information)**
All browsers seem to have the issue

**Comment by duboisp** [comment]
The issue is the provision step plugin do not notify WET core that is ready.

Basically, the change to do is to add the following at line 130 ->  https://github.com/wet-boew/wet-boew/blob/master/src/plugins/stepsform/stepsform.js#L130
```
wb.ready( $( elm ), componentName );
```
