### ISSUE TITLE
Would like to get validation samples using MVC

### ISSUE THREAD

**Issue by seguinrs** [wet-boew/wet-boew#9090]
Are there any complex validation samples using MVC?

**Comment by thekodester** [comment]
This project primarily focuses on the front end code (HTML, CSS, and JavaScript).

There some old projects using dotnet, php, and struts:
https://github.com/wet-boew/asp.net-formvalid-serverside
https://github.com/wet-boew/wet-boew-dotnet
https://github.com/wet-boew/GCWeb-dotnet
https://github.com/wet-boew/wet-boew-dotnet-controls
https://github.com/wet-boew/wet-boew-php
https://github.com/thekodester/struts2-wet-form-validation

None of these are maintained or updated.
