### ISSUE TITLE
Details/summary polyfill (expandable/collapsible content): No icon

### ISSUE THREAD

**Issue by QuesnelJ** [wet-boew/wet-boew#9129]
I cannot get the bullets to show, even if I copy/paste the example in my code. Same issue if I use the Accordion.

**Comment by thekodester** [comment]
Can you provide any code? What os are you on? What web browser are you using and which version?

**Comment by QuesnelJ** [comment]
Thank you for responding Kodi.

I guess I should have closed the ticket as the issue resolved it-self by updating to the newest version of the template.

Thanks for your support.'
