### ISSUE TITLE
Header link broken on WET5 Docs page 

### ISSUE THREAD

**Issue by ericmoore123** [wet-boew/wet-boew#9135]
The header link on: **https://wet-boew.github.io/wet-boew-documentation/research/2018-4-wet5-project.html** returns a 404 page not found error at the following: **https://wet-boew.github.io/index-en.html**

Links broken on both ENG and FRA pages.

![image](https://user-images.githubusercontent.com/51104403/125543641-a473f6ef-c463-4d28-beb1-25236ee51a75.png)

<br>
<br>

![image](https://user-images.githubusercontent.com/51104403/125543765-095869c6-55c7-4128-8d5a-1f503f9ae3ce.png)

**Comment by thekodester** [comment]
The issues is with the wet-boew-documentation repo.

I have already created a PR to fix some of issues with the repo.

https://github.com/wet-boew/wet-boew-documentation/pull/268

But there been no response to fix it for a good year.

###### I am just a volunteer on this GitHub project.

**Comment by ericmoore123** [comment]
@thekodester Ahh. Makes sense. Thanks for clearing the air. 

See : https://github.com/wet-boew/wet-boew-documentation/pull/268 for present issue.
