### ISSUE TITLE
[BUG] Switch to Basic HTML - URI parameters not transferred properly

### ISSUE THREAD

**Issue by sgdowney** [wet-boew/wet-boew#9139]
## Required information

**Describe the bug**
The link generated to switch to Basic HTML Version has invalid URL parameters when the original page link contains URL parameters.
Original Page Link
https://int16-ssl.services.gc.qat/irs-sdi/interdec/infodebase-basicinfo/preambule-preamble.aspx?wn=0&fwc=0
Generated Link
https://int16-ssl.services.gc.qat/irs-sdi/interdec/infodebase-basicinfo/preambule-preamble.aspx?wn=0&#38;fwc=0&#38;wbdisable=true
Please note the URLs provided above point to a secure app.  They are provided only as an example of the issue.
**To Reproduce**
Steps to reproduce the behaviour:
1. Navigate to a page with URL parameters
2. Tab to the Switch to Basic HTML link
3. View the generated link

**Expected behaviour**
A properly formatted URL with the wbdisable parameter appended to it.

**Who shall do the work?**
I am asking for Principal publisher to please do the work

## Additional information (optional)

**Version of WET-BOEW/GCWeb you are using**
e.g. v4.0.43

**Comment by EricDunsworth** [comment]
FWIW it looks like that bug was introduced in #9036 (it changed how the disable event plugin's ``nQuery`` variable gets used).
