### ISSUE TITLE
[OTHER] WET DataTable Extension Support

### ISSUE THREAD

**Issue by ibrahim-ahmed03** [wet-boew/wet-boew#9156]
## The purpose of this issue is to understand if WET has support for the various extensions of DataTables.
Does WET have support for the [select](https://datatables.net/extensions/select/) DataTable extension? I have tried configuring different versions of the select extension to get it to work without success. I am using Version 4.0.43 of WET-BOEW and version 2.4.0 of GCWeb.

**Comment by thekodester** [comment]
There is additional JavaScript files that must be loaded depending on which one you are trying to do.

See examples here https://datatables.net/extensions/select/examples/

See how to load additional JavaScript files for table extensions here
https://github.com/wet-boew/wet-boew/issues/9019

**Comment by ibrahim-ahmed03** [comment]
@thekodester Thanks, this answered my question, I will close this issue now.
