### ISSUE TITLE
Any way to specify the version of jQuery or DataTables to be loaded?

### ISSUE THREAD

**Issue by GarthMartin** [wet-boew/wet-boew#9205]
Is there any way to specify which version of jQuery and/or datatables to be loaded via configuration?

**Comment by duboisp** [comment]
@GarthMartin it is not possible to specify that via configuration.

**jQuery version** is loaded according to the `<script>` HTML tag located in your page template. Our latest release use jQuery version 2.2.4. 
```html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.js"></script>
```
Ref. https://github.com/wet-boew/wet-boew/blob/master/site/includes/footerresources.hbs


**Datatable version** is loaded depending of which version of wet-boew that have been implemented for your web site. The files hosted on the https://www.canada.ca correspond to the latest release of GCWeb (+/- 1 weeks after the release).
On that note, I just submitted a PR to bump the version of the datatable for the latest released. https://github.com/wet-boew/wet-boew/pull/9207

**Comment by GarthMartin** [comment]
@duboisp Thanks, you've answered both my questions.

**Comment by duboisp** [comment]
@GarthMartin the next release of wet-boew will contains the latest version of the datatable v1.11.3 (PR #9207) and patches for jQuery 2.2.4 (#9210)
