### ISSUE TITLE
Multimedia Player - YouTube: 

### ISSUE THREAD

**Issue by smulvih2** [wet-boew/wet-boew#9224]
Getting JS error on this page in console: Uncaught TypeError: e.fetch.pointer is undefined, in wet-boew.js. Media player is not working on this page.

**Comment by duboisp** [comment]
@smulvih2 thanks for reporting the issue.

We have fixed the issue yesterday overnight. The fix is now included with the latest release of [wet-boew v4.0.44.4](https://github.com/wet-boew/wet-boew/releases/tag/v4.0.44.4).
