### ISSUE TITLE
Table filters - Number filtering issue

### ISSUE THREAD

**Issue by Ricokola** [wet-boew/wet-boew#9235]
## Required information

**Describe the bug**
If only one value is selected when filtering by number, the search results will return the value and any value above the  selected number.

**To Reproduce**
Based on the "Number Range Filters" working example available on the WET Table Filters page: http://localhost:8000/unmin/demos/tables/tables-fltrs-en.html#dataset-filter2 use the following simplified code and try filtering using one number only. 

e.g. Enter the number 67 in the age field and the search result will return any age available from 67 and above.

```
<div class="row">
  <div class="col-md-3">
	  <h4 class="wb-inv">Filtering Options</h4>
	  <details open>
		  <summary><h4 class="h4">Filter Options</h4></summary>
		  <p class="mrgn-tp-md">Use filters to below options to change the focus of your results in following data table</p>
		  <form class="wb-tables-filter" data-bind-to="dataset-filter2">
			  <div class="form-group">
				  <fieldset>
					  <legend><span class="field-name">Age</span></legend>
					  <div class="row form-group">
						  <div class="col-md-12">
							  <label for="dt_age" class="small">Age</label>
							  <input type="number" class="form-control" id="dt_age" name="dt_age" min="0" data-column="3"/>
						  </div>
					  </div>
				  </fieldset>
			  </div>
			  <div class="form-group">
				  <button type="submit" class="btn btn-primary" aria-controls="dataset-filter2">Filter</button>
			  </div>
			  <div class="form-group">
				  <button type="reset" class="btn btn-link btn-sm p-0">Reset to defaults</button>
			  </div>
		  </form>
	  </details>
  </div>
  <div class="col-md-9">
	  <table class="wb-tables table table-striped table-hover" id="dataset-filter2" data-wb-tables='{
	  "bDeferRender": true,
	  "ajaxSource": "ajax/mockdata.json",
	  "order": [3, "desc"],
	  "columns": [
		  { "data": "id", "visible": false },
		  { "data": "first_name" },
		  { "data": "last_name" },
		  { "data": "age" },
		  { "data": "salary" },
		  { "data": "taxes" }
	  ]}'>
		  <thead>
		  <tr>
			  <th>Id</th>
			  <th>First Name</th>
			  <th>Last Name</th>
			  <th>Age</th>
			  <th>Salary</th>
			  <th>Taxes</th>
		  </tr>
		  </thead>
	  </table>
  </div>

```

**Expected behaviour**
When I enter a number in a filtering option where there is only one input field, since it's not a number range, I expect the search results to return data for that number only or zero (0) results if null.

e.g. When entering the number 67 in the date field and click the "Filter" button, the search result must return any data containing 67 only.

## Additional information (optional)

**Version of WET-BOEW/GCWeb you are using**
v4.0.44.5

**Screenshots**
![table filter - number age](https://user-images.githubusercontent.com/1846481/144074571-0a16e2b3-6aee-4199-a0dd-7b7cc528abf0.png)

**Additional context**

**Comment by thekodester** [comment]
This is the functionality I was talking about earlier where with the number range only requires min or max. So that is being treated as min age of 67.

**Comment by thekodester** [comment]
There is no number specific filter option available at this time

**Comment by acev0010** [comment]
I tried to follow the steps to replicate the issue, however, it doesn't match the screenshot provided. It's possible that this issue was already resolved, as there is now one field for min age and one field for max age.

**Comment by radmorecameron** [comment]
> I tried to follow the steps to replicate the issue, however, it doesn't match the screenshot provided. It's possible that this issue was already resolved, as there is now one field for min age and one field for max age.

I believe they modified the code on that page to only have one number input instead of two
