### ISSUE TITLE
[BUG] Geomap - Has stop working

### ISSUE THREAD

**Issue by duboisp** [wet-boew/wet-boew#9247]
Hi @jvanulde,

We recently noticed the [geomap plugin](https://wet-boew.github.io/wet-boew/demos/geomap/geomap-v4.0.30-en.html) has stop working.

We have found that sometime we see an NS_BINDING_ABBORTED error in the browser network tab and it is for the domain: geoappext.nrcan.gc.ca I don't know if it can be fixed that by adding an HTTP Expires headers when the geoappext server is sending the response. 

Let me know if you would like me to plan a meeting.

Thanks

**Comment by jvanulde** [comment]
Yes, lets set up a meeting.

**Comment by duboisp** [comment]
Thanks @jvanulde, it was nice to meet you.

We will wait until the NRCAN maps services go back online.

As discussed, we might explore way to add a fallback mechanism later on.

**Comment by jvanulde** [comment]
Services are back up. My local build works but the samples on wet-boew do not.

**Comment by duboisp** [comment]
I just tested in wet-boew example and it is now working.

Thanks @jvanulde
