### ISSUE TITLE
[FEATURE] wb-postback could trigger events on success or fail for further customization

### ISSUE THREAD

**Issue by at88mph** [wet-boew/wet-boew#9253]
## Required information

**Is your feature request related to a problem? Please describe.**
The `wb-postback` feature works well when there are static error and success messages to be shown on form submission.  However, there are cases where the error message should be tuned to the specific error from the form's submission, such as using the HTTP response's `statusText` or `responseText` to print the server's message, or perhaps the application would like to add something to the success message, such as thanking the user for registering.

**Describe the solution you'd like**
Two new events could be added that are dispatched before the success/failure message is revealed to allow customization before proceeding to unhide the message.

**Describe alternatives you've considered**
I looked into just having a flag to instruct using the response's `responseText`, but the events provide much more flexibility.

**Who shall do the work?**
I am seeking guidance because I want to contribute

## Additional information (optional)

**Timeline**

**Screenshots**

**Additional context**

**Comment by duboisp** [comment]
Thanks for your contribution and we will merge your change upon success by our continuous integration script

**Comment by at88mph** [comment]
Thank you, Pierre.  How do I patch it to fix the CI build?

Thanks,
Dustin
