### ISSUE TITLE
Redacted text

### ISSUE THREAD

**Issue by Sburbidge** [wet-boew/wet-boew#9277]
I'm unable to view the redacted text as being redacted.

https://www.mpcc-cppm.gc.ca/public-interest-investigations-and-hearings-enquetes-et-audiences-dinteret-public/military-police-unit-investigation-enquete-unite-de-police-militaire/2021-012-017-026-conduct-investigation-mener-enquete-eng.aspx#background

In the following paragraph under the Background section, there are 4 redacted words (referenced in bold) starting with the 5th word "X". 

On March 10, 2021, **X**, a newly appointed MP Operations (Ops) Officer at a local Canadian Forces Base (CFB) MP Detachment (Det) was caught trying to drive **herself** and **her** three children home from a restaurant while **she** was impaired.

The redacted text as been coded as per the instructions on https://wet-boew.github.io/GCWeb/components/redacted-en.html.

I have verified the CSS attribute is present in the CSS folder, and it is. I'm not sure where to verify for the role attribute however and/or the aria-label.

What am I doing incorrectly?

**Comment by kodz1** [comment]
The redacted class we'll not automatically add the redacted characters just changes how they are displayed. You must add the redacted characters. See below:
```
We recommend to use the Full block as your obfuscated character.

Name: Full block
Symbol: █
HTML Entity: &#9608;
Unicode: U+2588
```

CSS:
```
.redacted {
display: inline-block;
line-break: anywhere;
overflow-wrap: break-word;
word-break: break-all;
word-wrap: break-word;
}
```

Just want to point out your website (https://www.mpcc-cppm.gc.ca/index-eng.aspx) has some major broken html in regards to the header.

<img width="1222" alt="Screen Shot 2022-02-11 at 10 24 42 AM" src="https://user-images.githubusercontent.com/23484460/153619256-c64f224d-25c1-44ff-b8e0-53d5d2c38ee7.png">

###### I am just a volunteer on this GitHub project.

**Comment by Sburbidge** [comment]
Thank you Kody for the prompt reply.

Thank you for pointing out the broken link in our header. The link to our English website has been fixed. The French was not broken.

From the explanation provided on the redacted text, I don’t understand where to include the following.

We recommend to use the Full block as your obfuscated character.

Name: Full block

Symbol: █

HTML Entity: &#9608;

Unicode: U+2588

Can you provide an example?

**Comment by kodz1** [comment]
Here's a random example.

HTML CODE:
```
<span class="redacted" role="img" aria-label="4 redacted character">&#9608;&#9608;&#9608;&#9608;</span>
```

RESULTS:
<img width="1128" alt="Screen Shot 2022-02-14 at 11 29 54 AM" src="https://user-images.githubusercontent.com/23484460/153905112-88b18393-7ba6-4df3-857b-bb48768939af.png">

**Comment by Sburbidge** [comment]
I'm very happy, it works. Thank you.

When redacting, i.e in the example of **Mr. X**, I would think 3 redacted characters. However would it technically be 4 or 5 characters assuming either the punctuation and/or space are to be included? Or do any of the latter need to be included?

**Comment by kodz1** [comment]
I believe the concept is you use 1 redacted character for every character that is redacted. For `Mr. X` I go with 5 as that be a closer visual representation of the missing characters.
