### ISSUE TITLE
Toggle: Accordion 

### ISSUE THREAD

**Issue by gusmiller** [wet-boew/wet-boew#9290]
I have implemented the Persist Toggle State in my accordion and it work 'ok' but I like to default the accordion to open. The way is working now is fine as it remains open or close based on what the user has selected. But when first open the browser I want the accordion open by default.

Anyone has done this before?

**Comment by crochefort** [comment]
Hi @gusmiller did you try what's in the example page ? : https://wet-boew.github.io/v4.0-ci/demos/details/details-en.html 

`<details open="open">
			<summary>Example 2</summary>
			...
		</details>`

**Comment by gusmiller** [comment]
Good morning @crochefort ! LOL that was awesome, I hate it when is right there and you miss it. Thank you so much and please don't just have a good weekend have an awesome one!
