### ISSUE TITLE
Session Timeout: 

### ISSUE THREAD

**Issue by hilaryd198** [wet-boew/wet-boew#9319]
Hi everyone,
I have implemented session timeout in my project by adding this line `"<span class="wb-sessto" data-wb-sessto='{"logouturl": "#"}'></span>"` in my `_Layout.cshml`, I have realized that, on the server when the session has expired, intermittently the Sign in button of  the session timeout warning modal is missing. So I want to know if someone has already experienced this issue. If yes what can be the cause.

Thanks

**Comment by duboisp** [comment]
@hilaryd198 are you able to reproduce the issue in the [session timeout working example](https://wet-boew.github.io/wet-boew/demos/session-timeout/session-timeout-en.html) or in a standalone environment?
Are you using a CMS (Content Management System) or CDTS?
Do you see any error in your browser console?
What version of wet-boew are you using?
