### ISSUE TITLE
Shaky videos on Firefox

### ISSUE THREAD

**Issue by CaroGagnon** [wet-boew/wet-boew#9384]
There seems to be a problem with the video player on Firefox. It's very shaky. You can see even on the [WET4 example](https://wet-boew.github.io/v4.0-ci/demos/multimedia/multimedia-youtube-en.html). Chrome and Edge don't have that issue. 
Caroline

**Comment by duboisp** [comment]
@CaroGagnon thanks for reporting the issue. I tried on my FF dev edition 101.0b9 and the video work as expected, it is not shaky.

@GormFrank or @Ricokola could one of you test the video to see if you are experiencing the same shaky effect, as described, in FF.

**Comment by CaroGagnon** [comment]
Hi @duboisp, I did check on the FF dev, and it worked fine. The shakiness I'm seeing is with the FF 102.0. Thank you.

**Comment by EricDunsworth** [comment]
FWIW I just checked out the "Suspect" video in [WET's YouTube demo page](https://wet-boew.github.io/v4.0-ci/demos/multimedia/multimedia-youtube-en.html) in both Firefox 102.0 and 102.0.1. The video played back normally without any shaking. I have hardware acceleration disabled.

Maybe the shaking is related to hardware acceleration or GPU driver bugs?

**Comment by CaroGagnon** [comment]
Here's an update. I started FF again in Troubleshoot mode, and there was no shakiness. Interestingly, a colleague and I both tested on our personal laptop, There was never had any shakiness. Only happened on our work laptops (with and without vpn).
