### ISSUE TITLE
Datatable Export to PDF button not working in Chrome

### ISSUE THREAD

**Issue by zomby22** [wet-boew/wet-boew#9408]
using WET4, datatable and export buttons
IE Edge: Exporting buttons to Excel, CSV and PDF is working
**Chrome**: Exporting buttons to Excel, CSV is working however not working with the PDF button.

**_Chrome error: Uncaught File 'Roboto-Regular.ttf' not found in virtual file system_**

These files exists:
pdfmake.min.js
vfs_fonts.js

Code:
`$.extend(true, {}, {exportOptions : {format : {body : exportCsvFunction}, columns: [ ':visible' ]}}, {extend: 'pdfHtml5', orientation: 'landscape', pageSize: 'LEGAL', title: 'testing', bom: 'true', text: '<span class="fa fa-file-pdf-o"></span> PDF', className: 'btn btn-danger' })`

Anyone have an idea why its not working? if you need more info, let me know.

**Comment by duboisp** [comment]
@zomby22 we don't support that extension from datatables.net. But I marked your request as a feature request in the case of someone would like to add it and documents it.
