### ISSUE TITLE
ID attribute value must be unique

### ISSUE THREAD

**Issue by Malcolm-Tsai** [wet-boew/wet-boew#9409]
On the CAAPS Web app, there is a header tag within a header on the Forms page. 

Where:
The header is a child of header (used W3C validator)
https://intradev16-i.intra.dev/AS-SA/CAAPS-PROTO/forms?formTypeId=1

Issue:
A header cannot be a child of another header tag
 (used W3C validator)
https://validator.w3.org/nu/

Solution:
Please fix the child of header 

Please message me for more details if required

**Comment by duboisp** [comment]
@Malcolm-Tsai as @kodz1 said, your issue don't seem to be related to wet-boew project.
