### ISSUE TITLE
Lightbox: Modal accessibility issue with close button and screen readers

### ISSUE THREAD

**Issue by cdjobin** [wet-boew/wet-boew#9412]
NVDA and JAWS are currently reading the X close button as "Times, close's overlay (escapte key)" and will repeat "Close's overlay (escape key). I believe that we could fix this problem either by wrapping letter **X** in a "span aria-hidden="true"" or may be by changing the button title attribute, by an aria-label attribute?

**Comment by lisafast** [comment]
Odd that the screenreaders speak 'x' as 'Times'. Seems better not to use 'hidden' in case their screenreaders do that for ALL overlay close features (I have to click the X for advertisements and popup invites a LOT). So I'd opt to change the button title attribute or aria label and if possible, force it to say 'X' as the name of the letter vs 'times' somehow through markup.
