### ISSUE TITLE
[BUG] Feature name - Error 403 redirect session bug

### ISSUE THREAD

**Issue by K4leS1er** [wet-boew/wet-boew#9437]
## Required information

**Describe the bug**
Hi, I'm a user of the GCKey Login. I've been experiencing issues with the GCKey login on the clegc-gckey.gc.ca website. 

When authenticating to the site, I enter my credentials and very frequently the browser drops the session, with an Error 403 page. Curiously, if the page is refreshed then it occasionally reverts back to the login session, but doesn't properly continue the session (i.e. I cannot submit any documentation etc.). I first explored Reddit/Facebook pages for help and it looks as though this has been a long-term issue, with people suggesting clearing browser caches, incognito windows, the use of Chrome/Edge. None of these have worked for me and I've also tried using two different laptops, Firefox, Edge, Chrome with cleared caches/cookies/browsing data and also with/without the use of a VPN.

Since this has apparently been an issue for a while, I'd like to find out if this is a known problem and if there is anything that I can do to workaround it?

I would like to point out at this point that I'm not a Developer, but am familiar enough with the Chrome console that I was able to find this Git repo. 

**To Reproduce**
As the issue appears to have variable output, I'm not sure how to replicate it. I've looked at the errors that appear on the Chrome console, and this could be the cause:

_Because a cookie’s SameSite attribute was not set or is invalid, it defaults to SameSite=Lax, which prevents the cookie from being sent in a cross-site request. This behavior protects user data from accidentally leaking to third parties and cross-site request forgery.
Resolve this issue by updating the attributes of the cookie:
Specify SameSite=None and Secure if the cookie should be sent in cross-site requests. This enables third-party use.
Specify SameSite=Strict or SameSite=Lax if the cookie should not be sent in cross-site requests._

Name | Domain & Path
-- | --
JSESSIONID | onlineservices-servicesenligne.cic.gc.ca/auth/
_ga | .cic.gc.ca/
_gid | .cic.gc.ca/
lang | onlineservices-servicesenligne.cic.gc.ca/
AMCVS_A90F2A0D55423F537F000101%40AdobeOrg | .cic.gc.ca/
AMCV_A90F2A0D55423F537F000101%40AdobeOrg | .cic.gc.ca/
s_ppvl | .cic.gc.ca/
s_ppv | .cic.gc.ca/
s_sq | .cic.gc.ca/
amlbcookie | .onlineservices-servicesenligne.cic.gc.ca/
iPlanetDirectoryPro | .onlineservices-servicesenligne.cic.gc.ca/

If I understand this informational link about how this attribute works (https://web.dev/samesite-cookies-explained/?utm_source=devtools), I believe that this change should be applied to all of the pages that require re-directs once authenticated.

**Expected behaviour**
I had expected to be able to authenticate and submit the documentation that I need to submit my visa application. Curiously, I have been able to do this historically, it's just in the past week or so that I've been having issues. 

**Who shall do the work?**
Apologies, but as I mentioned, I'm not a developer, and I was hoping that someone could look into this for me. 

## Additional information (optional)

**Version of WET-BOEW/GCWeb you are using**
I'm not sure how to identify this. 

**Desktop/Smartphone (please complete the following information)**
 - OS or Device: MacOS 11.6.1 (note that I've not updated the OS since I was able to access the site), also used a Windows 10 device. 
 - Browser Chrome (v105.0.5195.125), Safari (14.1.2 ), Firefox (most up to date version), Edge

**Screenshots**
I've screenshotted the other errors in my console, unsure if they'll help. 

![Screenshot 2022-09-20 at 01 17 13](https://user-images.githubusercontent.com/113951197/191140944-c7ea1941-bede-4ba5-8dbc-256be3d0159e.png)

**Comment by K4leS1er** [comment]
Thanks for responding, appreciated. 

As an added thing, I was experimenting logging in last night and noticed this error in the HTTP POST Header, when I was requested for an answer to a security question (I note that my session was again dropped after this). Might be useful for added context

![Screenshot 2022-09-22 at 00 20 51](https://user-images.githubusercontent.com/113951197/191628167-d324c04e-d7fb-419b-aee3-f8c3e2bfa661.png)

**Comment by duboisp** [comment]
@K4leS1er Your issue seem to be specific to the web site that you are trying to connect and base on the various URL in your description/screen capture I can assume it is about Immigration, Refugees and Citizenship Canada (IRCC).

I am going to close your request because it is not related to the wet-boew product which is a baseline product used by website author/developer to create website and web application mostly for the Government of Canada website. We don't provide support for a service provided by a Government of Canada department like Immigration, Refugees and Citizenship Canada (IRCC). 

However you can try to [contact Immigration, Refugees and Citizenship Canada (IRCC)](https://www.canada.ca/en/immigration-refugees-citizenship/corporate/contact-ircc.html) to get support. I found out this [IRCC web form](https://secure.cic.gc.ca/enquiries-renseignements/canada-case-cas-eng.aspx) where you should be able to submit your technical issue with GCKey.
