### ISSUE TITLE
Broken link - Canada.ca theme

### ISSUE THREAD

**Issue by jabdali** [wet-boew/wet-boew#9473]
In the page  https://wet-boew.github.io/wet-boew/docs/ref/themesstyle-en.html , the following  "Canada.ca theme" is a broken link that returns "404 file not found" :

[Canada.ca theme](https://wet-boew.github.io/themes-dist/GCWeb/docs/ref/GCWeb/GCWeb-en.html) - This theme implements the layout and design requirements for Canada.ca 

Thanks,

Jamal Abd-Ali

**Comment by duboisp** [comment]
@jabdali Thank for reporting the issue, it should be fixed on our website today.

Thanks @Ricokola for fixing the broken links.
