### ISSUE TITLE
Multimedia player - Mute icon when video is muted by default

### ISSUE THREAD

**Issue by agagnon** [wet-boew/wet-boew#9486]
When "video" element has attribute "muted" at page load, the mute button state is not shown properly. It should be at "muted" state.

`<video muted>`
`    <source src="video.mp4" type="video/mp4">`
`</video>`

(I wanted to share screenshots, but adding image to message is not working)

**Comment by duboisp** [comment]
Thanks for reporting the issue.

I confirm the mute button state don't show properly on initial state and it don't work at all for youtube video until the video are being played once
