### ISSUE TITLE
Bug - JSONManager not issuing URL request

### ISSUE THREAD

**Issue by at88mph** [wet-boew/wet-boew#9524]
## Describe the bug
We use the `data-wb-jsonmanager` to load a JSON document and pull properties from it.  This was working until it was noticed today.

## To Reproduce
Steps to reproduce the behaviour:
1. Go to http://206-12-98-60.cloud.computecanada.ca/en/github-bug.html
2. Content is missing

## Example

The relevant HTML in the page above looks valid:
```html
<div id="view_meeting" class="panel panel-default meeting-panel mrgn-tp-lg" data-wb-jsonmanager='{"url": "/en/meeting.json", "name": "meeting"}'>
    <span>Address:</span><span data-json-replace="#[meeting]/address"></span>
    <div class="panel-body small">
		<span>Should be a title in an &lt;h3&gt; tag below:</span>
        <h3 class="title mrgn-tp-sm" data-json-replace="#[meeting]/title"></h3>
    </div>
</div>
```

## Current behaviour
The `/en/meeting.json` isn't being requested at all according to the browser's Network tab.

## Expected behaviour
The `/en/meeting.json` document should be requested, and made available to the `data-json-replace` tags in the HTML.

## Desktop (please complete the following information):
 - OS: MacOS 13
 - Browser: chrome, safari
 - Version: Safari 16.3, Chrome 109.0.5414.119

## Additional context
This may be related to a recent change somewhere as it seems like a new issue.

**Comment by at88mph** [comment]
I did notice this commit:
https://github.com/wet-boew/wet-boew/commit/4256ba1af2f2e852aa598eab9e2fbc8ad6d3e64e

Which may close this Issue.

**Comment by polmih** [comment]
@at88mph, you are right about that commit, I just tested it and it provides a solution for this issue.
