### ISSUE TITLE
[BUG] wb-tables - upgrad breaks datatables that are non wb-tables

### ISSUE THREAD

**Issue by joel-osc** [wet-boew/wet-boew#9548]
## Required information

**Describe the bug**

After updating to release 4.0.50.1 datatables that were not wb-tables were broken across the site. Selecting a filter triggers the error:
`
wet-boew Uncaught TypeError: i18nText is undefined`

Adding "wet-boew/wet-boew": "4.0.43.1 as 4.0.50.1" to composer.json fixes the issue. It appears that in this commit: https://github.com/wet-boew/wet-boew/commit/b388deeb9465506b23d36a8bdc7da92003225bcb the following code was added:

```
// Identify that initialization has completed
$document.on( "init.dt", function( event ) {
	**var $elm = $( event.target ),
		settings = $.extend( true, {}, defaults, window[ componentName ], wb.getData( $elm, componentName ) );

	// Handle sorting/ordering
	var ordering = ( settings && settings.ordering === false ) ? false : true;
	if ( ordering ) {
		$elm.find( "th" ).each( function() {
			var $th = $( this ),
				label = ( $th.attr( "aria-sort" ) === "ascending" ) ? i18nText.aria.sortDescending : i18nText.aria.sortAscending;

			$th.html( "<button type='button' class='sorting-cnt' aria-controls='" + $th.attr( "aria-controls" ) +  "' title='" + $th.text().replace( /'/g, "&#39;" ) + label + "'>" + $th.html() + " <span class='sorting-icons' aria-hidden='true'></span></button>" );
			$th.removeAttr( "aria-label tabindex aria-controls" );
		} );
		$elm.attr( "aria-label", i18nText.tblFilterInstruction );
	}**
	wb.ready( $( event.target ), componentName );
} );

```
I believe this code assumes that all datatables across a site will be wb-tables that the i18nText object will be in scope, which is why there is an error.

**To Reproduce**
Steps to reproduce the behaviour:
1. We use DrupalWxt, but this should be recreatable elsewhere
2. Add a datatable with filters as shown in the screenshot
3. Select one of the filters and see the error.

**Expected behaviour**
No errror, wet-boew js should not even execute.

**Who shall do the work?**
I am asking for Principal publisher to please do the work

## Additional information (optional)

**Version of WET-BOEW/GCWeb you are using**
e.g. v4.0.50.1

**Desktop/Smartphone (please complete the following information)**
All

**Screenshots**
Selecting this filter produces the error and the datatable does not filter.

![datatable](https://user-images.githubusercontent.com/1280955/223569242-760d7715-f87d-44e6-9449-e0c3e0e9aeb9.png)

**Additional context**

**Comment by joel-osc** [comment]
Thank-you for your comments. This is DrupalWxt so the lang attribute is set 100% of the time. Maybe my description was not clear enough, this is not done with wb-tables, just straight datatables. So I believe the defect is that the wet-boew is acting on the table when it should not be. Cheers.

**Comment by wewhite** [comment]
I found that you cannot include jQuery.dataTables.js on its own from within WET.
If your using WET, you must use wet-tables.

I have run into this issue before, here is my commented code:

```
 // DO NOT ADD DATATABLES, bad things will happen, conflicts with WET DTs */
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
```

My only suggestion is you may have to compile WET without DataTables, or remove you jQuery.dataTables and convert to wt-tables.

**Comment by wewhite** [comment]
I have found a fix.
Not sure if this should be implemented in WET or if it should be implemented in DrupalWxt.

Basically, the `init.dt` function provides access to the initialized object. 
This would be any datatable, including DataTable and wb-tables.

By adding the `.wb-tables` selector to the function, ONLY wb-tables will be included in this function.

Current wet-brew tables.js script wil be called on any datatable :
```
// Identify that initialization has completed
$document.on( "init.dt", function( event ) {
....
```

Possible solution will only include wt-tables:
```
// Identify that initialization has completed
$document.on( "init.dt", ".wb-tables", function( event ) {
....
```

I think the default comment `// Identify that initialization has completed` is incorrect.
Should be `// Apply custom options on wb-tables after initialization`

**Comment by joel-osc** [comment]
Agree with @wewhite - only include wb-tables is a solid solution. Thank-you @wewhite!
