### ISSUE TITLE
Dead link to Drupal theme

### ISSUE THREAD

**Issue by onshisan** [wet-boew/wet-boew#9553]
The Drupal link on the [Variants](https://wet-boew.github.io/wet-boew/docs/ref/variants-en.html) page gives a 404 error: 
https://github.com/wet-boew/wet-boew/blob/a941c439c1be52835112727a201f18073b59627f/site/pages/docs/ref/variants-en.hbs#L11

In issue #9103, https://www.drupal.org/project/wxt is offered. I suspect this may be the correct URL but this is outside my personal expertise.

**Comment by wewhite** [comment]
I thought the Drupal WXT was dead, obviously I was wrong.
There is a home page located here: https://drupalwxt.org/
A github home page here: https://drupalwxt.github.io/en/


The question is, where should the Varients page link to, github code, external domain, or git webpage?

**Comment by onshisan** [comment]
> There is a home page located here: https://drupalwxt.org/

This looks better for this purpose than the link in #9103. I've created a PR.
