### ISSUE TITLE
Row header in datatables getting sorting classes in v4.0.45+

### ISSUE THREAD

**Issue by GarthMartin** [wet-boew/wet-boew#9578]
There seems to be an issue in v4.0.45 and up of WET.  I have a datatable with a scope="row" in one of the cells and WET is adding the column header formatting with the button and sorting classes.
```
<table id="employees" class="wb-tables table" data-wb-tables='{ "ordering" : true, "paging": true, "searching": true, "info": false, "aaSorting": [[1, "asc"]]}'>
    <thead>
        <tr>
            <th class="hide" scope="col">Id</th>
            <th scope="col">@Localization.EmployeeFirstName</th>
            <th scope="col">@Localization.EmployeeLastName</th>
            <th scope="col">@Localization.EmployeeJobDescription</th>
             </tr>
    </thead>
    <tbody>
        @foreach (var employee in Model.Employees)
        {
            <tr>
                <td class="hide">@employee.Id</td>
                <th scope="row">@employee.FirstName</th>
                <td>@employee.LastName</td>
                <td>@employee.JobDescription</td>
               </tr>
    }
    </tbody>
</table>
```
Using CDTS template and v4_0_44 it renders like this:
![image](https://user-images.githubusercontent.com/11050106/236452005-0aa09b36-13e7-4bf5-8b0c-b7ff76fed6e1.png)

If I change to 45 or up, it renders like this:
![image](https://user-images.githubusercontent.com/11050106/236452084-39b8afa5-e9e1-4a3e-b1a5-7a2bcae61ec9.png)

and the html looks like this:
![image](https://user-images.githubusercontent.com/11050106/236452227-cb503ddc-9e26-411d-9d8e-714689d55231.png)

**Comment by wewhite** [comment]
You have a <th> defined in your  table row <tr> that should be a table data <td>
```
<tbody>
        @foreach (var employee in Model.Employees)
        {
            <tr>
                <td class="hide">@employee.Id</td>
                <th scope="row">@employee.FirstName</th>
                <td>@employee.LastName</td>
                <td>@employee.JobDescription</td>
               </tr>
    }
    </tbody>
```

Change the <**th** scope="row">@employee.FirstName</**th**>
to
<**td**  scope="row">@employee.FirstName</**td**>

**Comment by GarthMartin** [comment]
@wewhite Hmmm, that does not match what I have always done on complex tables, plus it used to work properly.  Pretty sure ```<td>``` does not allow scope as an attribute, and scope is not a global attribute.  

Both https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th and https://www.w3.org/WAI/tutorials/tables/multi-level/ reference simply using ```<th>``` in place of the ```<td>``` with a scope="row"

I suppose I could refactor it all to specify id's and use the ```headers``` attribute on the ```<td>``` element, but that's a larger undertaking.

**Comment by wewhite** [comment]
I understand the problem now. Disregard my previous comment.

**Comment by wewhite** [comment]
I think I fixed it:
https://github.com/wet-boew/wet-boew/commit/ad938c4ea5bc8854131ef537bb863eb4fd8d27ad

The column header formatting is applied to all th, including if they are in  tbody tr.
The change I added above, will only apply column header formatting for th elements in the thead only.
