### ISSUE TITLE
[BUG] Tables - removing sorting from a column generates aria-controls="undefined"

### ISSUE THREAD

**Issue by ChristineLamontagne** [wet-boew/wet-boew#9588]
## Required information

**Describe the bug**
We use a table with 1 column that will not be orderable.  Upon rendering, the header contains a button
button type="button" aria-controls="undefined" title="activate for ascending sort"

The aria-controls generate a W3C validation error:
Error: The aria-controls attribute must point to an element in the same document.

Here is the table definition
```
<table  id="ResultsTable" class="cards wb-tables table draftLayout"
                   data-wb-tables='{"paging":"true", "ordering":"true", "info":"true", "columnDefs": [ {"orderable": false, "targets": [5]}], "aaSorting": [[2, "asc"]], "lengthMenu": [[9, 18, 36, 54, -1], [9, 18, 36, 54, "@Common.AllFilter"]]}'>
```

**Expected behaviour**
No button at all as the sorting is not available

**Who shall do the work?**
I am asking for Principal publisher to please do the work

## Additional information (optional)

**Version of WET-BOEW/GCWeb you are using**
v4.0.47

**Comment by wewhite** [comment]
Your html code table definition needs to be wrapped in triple back ticks ```
and closed with triple back ticks
Single line html tags with single back tick `
and closed with single back tick

Cannot see your code snippets until it is edited/formatted.

**Comment by wewhite** [comment]
Related issue https://github.com/wet-boew/wet-boew/issues/9564

**Comment by wewhite** [comment]
Using the following works since v4.0.56.1:

`<th data-orderable="false">`

Patch located here: https://github.com/wet-boew/wet-boew/pull/9476
