### ISSUE TITLE
Widget de nouvelles - probèmes avec  nouveau /GCWeb/wet-boew/js/wet-boew.min.js

### ISSUE THREAD

**Issue by CaroGagnon** [wet-boew/wet-boew#9653]
## Required information

La nouvelle version de https://wet-boew.github.io/themes-dist/GCWeb/wet-boew/js/wet-boew.min.js ne permet pas au widget des Nouvelles de charger les nouvelles. Nous avons dû mettre la version précédente pour que le tout fonctionne.

**To Reproduce**
J'ai fait une [page test](https://femmes-egalite-genres.canada.ca/test-nouvelles.html) pour vous démontrer.

**Expected behaviour**
Faire une correction pour que le widget fonctionne.

**Who shall do the work?**
L'éditeur principal.

## Additional information (optional)

**Version of WET-BOEW/GCWeb you are using**
Nous utilisons la dernière version.

**Screenshots**
![erreur](https://github.com/wet-boew/wet-boew/assets/9091299/652057b5-73c6-43bb-8916-c7752bc031fd)

**Comment by agagnon** [comment]
J'ai remarqué aussi le même problème.

**Comment by duboisp** [comment]
Ceci est maintenant corrigé avec la version [v4.0.67.1](https://github.com/wet-boew/wet-boew/releases/tag/v4.0.67.1) de wet-boew et il sera inclus avec la prochaine version de GCWeb cette semaine.

**Comment by duboisp** [comment]
Corrigé via le PR #9656

**Comment by CaroGagnon** [comment]
J'ai toujours la même erreur qui se produit même avec la dernière version de [https://wet-boew.github.io/themes-dist/GCWeb/wet-boew/js/wet-boew.min.js](https://wet-boew.github.io/themes-dist/GCWeb/wet-boew/js/wet-boew.min.js).

![erreur](https://github.com/wet-boew/wet-boew/assets/9091299/baf49701-2a23-4eda-9831-74e91c94875b)

**Comment by CaroGagnon** [comment]
Ça fonctionne maintenant.
