### ISSUE TITLE
[OTHER] Intermittent errors when listening for 'wb-ready.wb' event

### ISSUE THREAD

**Issue by jpardey** [wet-boew/wet-boew#9683]
I've been running into a few intermittent errors. I believe this may be to do with the "wb-ready.wb" event firing before listeners are registered.

In this case, CDTS is being used, and the custom scripts are at the bottom of the page. Since this error is so rare, I can't be certain this is the cause. However, if I wrap the code that installs the wb-ready.wb listener in a setTimeout, a long delay will cause the errors to occur.

Is there some known workaround, for instance checking to see if wet-boew is already ready, and installing a listener or running the code immediately depending on that? Would the `wb.isReady` property be dependable for this purpose?

**Comment by wewhite** [comment]
That is what wb-ready.wb is for, from the documentation:
`Used to identify when all WET plugins and polyfills have finished loading and executing. `

If you delay when wb-ready.wb will be ready, yes I would assume you would get errors, correct, don't do that.

I could assume that your code is attempting to modify a plugin outside of the wb-ready function, and you get the error. 

Post your errors and a code snippet of your javascript. Need more details of the errors to determine the problem.

**Comment by jpardey** [comment]
There are no actual errors showing up. In this case, code called in a listener for "wb-ready.wb" or similar events is just not being run. I can't even be certain that's the cause. Also, as a very intermittent error, I can't make it occur reliably (at first, we thought it was only an error in Safari on Mac OS, but it's been showing up on most browsers).

The custom scripts are not being loaded "async" or "defer," just plain script tags. The listener registration (`$(document).on("wb-ready.wb", function () {...})`) is top level procedural, not within any callback itself (aside from testing). This script is loaded after the "defFooter" cdts page write, since the custom scripts depend on jQuery.

I can send a link, but I think that should clear up the situation.

**Comment by jpardey** [comment]
@wewhite as an example, [this page](https://climate-scenarios.canada.ca/?page=CanDCS6-indices) has been patched to check for wb.isReady prior to setting up a listener, with the function in this script: [exec_wb_loaded.js](https://climate-scenarios.canada.ca/tools/exec_wb_loaded.js) (currently includes a `console.log` call to show if wet-boew has already been loaded before the custom script could execute). [candcs-indices.js](https://climate-scenarios.canada.ca/tools/downscaled-indices-data/candcs-indices.js) is one of the custom scripts referenced that included listeners for wb-ready which were not always being called.

It's still very rare, but occasionally now I'll see the console message and the page will work, unlike previously when it just wouldn't work at random. Of course, this isn't total proof, but it seems consistent with what I'd been thinking.

**Comment by jpardey** [comment]
Thanks for looking into that! I'm updating the CDTS version in use, and I'll keep an eye open over time. If it comes up again, I'll open an issue on the CDTS repo.

The error occurred very rarely, and seemed to show up more frequently on certain computers and browsers. I had spotted those statements that should never execute being executed. With any luck, it won't occur at all with CDTS 4.1.0.
