### ISSUE TITLE
[FEATURE] Published Component Library for Figma or Mural

### ISSUE THREAD

**Issue by seanpoulter-foci** [wet-boew/wet-boew#9695]
## Required information

**Is your feature request related to a problem? Please describe.**

Yes. I cannot find a published themable component library to use with a collaborative design tool like Figma or Mural. This slows down rapid prototyping and costs taxpayers more money.

**Describe the solution you'd like**

Ideally, the component libraries for tools like Figma are published with each theme. 

**Describe alternatives you've considered**

Any other solution that has theme consumers repeating the work an unnecessary duplication of work.

**Who shall do the work?**

We can discuss this when necessary.
It may also help to collaborate with the [aurora-design-system](https://github.com/gctools-outilsgc/aurora-design-system).

## Additional information (optional)

**Timeline**

My team could use this immediately for WET with the Canada.ca theme.

**Screenshots**

N/A

**Additional context**

* [Guide to Libraries in Figma](https://help.figma.com/hc/en-us/articles/360041051154-Guide-to-libraries-in-Figma)

**Comment by AleksueiR** [comment]
Hey, @seanpoulter-foci, 

I'm part of the UX team at ECCC and we've recently published our [Web Experience Toolkit and Canada.ca Design System Kit](https://www.figma.com/community/file/1342923790850747276/web-experience-toolkit-and-canada-ca-design-system-kit) to the Figma community. This resource is specifically developed to support design of WET and Canada.ca-related projects and we are very excited to share it 🎉. Feel free to check it out and see if it fits your use case:

[![598437bd-1096-437c-ab78-31ad809ff143-cover](https://github.com/wet-boew/wet-boew/assets/2285779/10d050f8-774e-48ff-9b1e-9f5d9a12f932)](https://www.figma.com/community/file/1342923790850747276/web-experience-toolkit-and-canada-ca-design-system-kit)

This is something we developed internally for our own use to speed up the designing process, but thought it might be helpful to other folks out there who design for WET. 

This library is not limited to vanilla WET components, but also includes Canada.ca style guide elements and components from the Centrally Deployed Templates Solution (CDTS) templates.

If you see any missing elements that you need or have other suggestion for improvements, let us know and we'll try to add them.

Thank you!

**Comment by seanpoulter-foci** [comment]
Thanks @AleksueiR and congratulations!

Let me know if you'd like a PR to add a link in the docs. It seems like there's a bit of a backlog so I won't open one now.

**Comment by AleksueiR** [comment]
Thank you, @seanpoulter-foci. Yes, a PR with a link to the docs would be nice. Please, submit on when the backlogs clears up.
