### ISSUE TITLE
Pagination - Datatable Dom option - Pagination still show at the top when hidden at the bottom

### ISSUE THREAD

**Issue by crochefort** [wet-boew/wet-boew#9709]
## Required information

**Describe the bug**
When you add the datatable option DOM to the table.
`<table class="wb-tables table table-bordered table-striped" data-wb-tables='{"ordering" : false, "dom":"<\u0027top\u0027pfil>rt<\u0027bottom\u0027p><\u0027clear\u0027>"}'>`

Let say you have 60 item in your table and select the option to show 100, the pagination at the top stay but the one at the bottom stay hidden.

**Expected behaviour**
The top pagination to be hidden like the bottom one
![image](https://github.com/wet-boew/wet-boew/assets/4562025/c9a6511e-ea85-4c30-a7da-9cb5f7bba7eb)

**Who shall do the work?**
I am asking for Principal publisher to please do the work.
I don't want to add additional JS to my application.

## Additional information (optional)

**Version of WET-BOEW/GCWeb you are using**
* v4.0.70 - 2023-10-25

**Additional context**
From the work should be done around here :  [table.js](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/tables/tables.js#L135-L178 )

You can see on line 137-138 it's looking for .bottom but not .top

**Comment by wewhite** [comment]
Interesting, this is the default behavior for DataTables.net.

For WET, I have a working solution

Add after line 137:
```
137:		pagination = $elm.next( ".bottom" ).find( "div:first-child" ),
	        pagination_top = $elm.prevAll( ".top" ).find( "div.dataTables_paginate" ),
```
$elm is the table, pagination div above table, hence the prevAll.

Then after line 174:
```
174: pagination.addClass( "hidden" );
        pagination_top.addClass( "hidden" );
```
And finally after line 181:
```
181: pagination.removeClass( "hidden" );
       pagination_top.removeClass( "hidden" );
```

**Comment by crochefort** [comment]
Thank you @wewhite it's working!
Just need this to be done in a PR

**Comment by crochefort** [comment]
Implemented! Thank you!
