### ISSUE TITLE
Datatable (serverSide) French characters when searching

### ISSUE THREAD

**Issue by zomby22** [wet-boew/wet-boew#9750]
Anyone have a suggestion, a code, related to searching any words or phrases that includes **French Characters**. I have a datatable using serverside (my ajax file is a json ASP page). I can search for anything including apostrophes but the rows clears when entering any French characters and I wonder why the search does not support it. What else can be included to make it work, is this doable without any additional plugins.

**table:**
`data-wb-tables='{ "ordering" : true,
		"processing": true,
		"serverSide": true,
			"ajax": {
				"url": "activity_ajaxdata.asp",
				"type": "POST",
				"async": false
		},`

**json ASP:**
`strSearch = server.HTMLEncode(lcase(trim(Request("search[value]"))))

if strSearch <> "" then
	strWhere = strWhere & " and (dbactivity.id::text LIKE '%" & JSONEscape(sqlSingleQuote(strSearch)) & "%' OR "
	strWhere = strWhere & " lower(dbactivity.dbtitle::text) SIMILAR TO '%" & JSONEscape(sqlSingleQuote(strSearch)) & "%')"
end if`

**Comment by mercury64** [comment]
Maybe this will help:
https://github.com/wet-boew/wet-boew/issues/9638#issuecomment-1686624317

**Comment by zomby22** [comment]
thanks for the help. couldnt get it working, trying to solved this part (what dependencies that is missing?)

```
accent-neutralise.js:309 Uncaught TypeError: Cannot read properties of undefined (reading 'ext')
    at accent-neutralise.js:309:11
    at accent-neutralise.js:42:3
    at accent-neutralise.js:44:2
```

`DataTable.**ext.type.search.allowDiacritics**`

**Comment by mercury64** [comment]
I'd verify that your browser is actually sending the correct data in the POST request.
Then on the server side, your going to have to debug and verify it is the same data in the "search[value]".

I'm using PHP and works without any extra plugins. I would guess that your json ASP server side code is not correct.

**Comment by zomby22** [comment]
i did a test with my server side page - when I enter the word "français" it appears with unicode character. The page is using UTF-8, but my json results is in unicode format. I try to use a function to decode the characters, but the results remains the same.

{"draw": 0,"recordsTotal":1,"recordsFiltered": 1,"data": [["123","**fran\u00E7aise**
