### ISSUE TITLE
Form Validation - Radio/Checkbox inputs being cleared during page load.

### ISSUE THREAD

**Issue by sgdowney** [wet-boew/wet-boew#9816]
## Required information

**Describe the bug**
Using Form Validation Plugin, the following behaviour has been observed when a page is loading over a slow network.
When the form is visible, but scripts are still loading, if a user clicks on a radio button or checkbox to select it, that control is cleared when the page finishes loading.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the WET examples page.
2. Open the DevTools window and select the Network tab.  Enable throttling (3G) and disable cache.
3. Click on 'Form Validation' example
4. Scroll down to any of the radio button/checkbox examples as soon as the page is visible and select some of them.
5. Once the page completes loading you will see the selected items are cleared.

**Expected behaviour**
Any radio buttons or checkboxes selected while the page is loading should remain selected.

**Who shall do the work?**
I am asking for Principal publisher to please do the work.

## Additional information (optional)

**Version of WET-BOEW/GCWeb you are using**
current version on GitHub

**Desktop/Smartphone (please complete the following information)**
 - OS or Device: Windows 10
 - Browser any supported browser
 - Version any supported version

**Comment by mercury64** [comment]
With the example Form Validation, only checkbox/radio buttons that are nested are cleared on page load.
The code that 'clears' the input is located in file formvalid.js: https://github.com/wet-boew/wet-boew/blob/6145945db8caeb846f229153262fc52b06316477/src/plugins/formvalid/formvalid.js#L115-L119

Labels and inputs that are not nested work fine.
Working example:
```html
<label for="status1"> Canadian citizen</label>
<input type="radio" name="status" value="1" id="status1" data-rule-required="true" />
```
Not working example:
```html
<label for="status1"><input type="radio" name="status" value="1" id="status1" data-rule-required="true" /> Canadian citizen</label>
```

I do not have a fix, but this may help someone else to solve this issue.

**Comment by sgdowney** [comment]
Thank you for identifying the cause.  I don't think I would have recognized the significance of line 118 and the effect it would have.
